### ISSUE TITLE
estimate api 관련 하여 문의 드립니다.

### ISSUE THREAD

**Issue by younseunghyun** [naver/searchad-apidoc#10]
안녕하세요

기존의 estimate 관련 api에서는 특정 키워드가 특정 position을 하기 위한 bid가와 관련된 지표들을(click, impression, cost)를 같이 넘겨 주었는데, 현재는 bid가격만 넘겨 주는 것으로 알고 있습니다.

대량의 키워드에 대한 앞서 말한 정보들을 얻기 위해서는 이전 방식의 api 사용이 필요한 상황인데, 이를 현재 api에서 구현 하기 위해서는 현재 제공 해주시는 api로 구현시에는` /estimate/average-position-bid/`를 통해서 대량의 키워드에 대해서 순위에 따른 비드 가격을 가져 올 수 있으나, 그에 따른 지표들은 키워드와  bid가를 담아서 `/estimate/performance` 에 요청을 키워드 갯수 많큼 해야 되는 것으로 보입니다.

이 방식으로 구현시에 대량의 키워드에 대해서 하게 되면, 상당히 많은 요청을 해야되는 상황이라 우려 됩니다.

대량의 키워드에 대해서 특정 가격에 대해 지표를 얻는 api가 현재 네이버 검색광고 시스템에서는 있는 것으로 보이는데, 공개적 사용으로 오픈 할 예정은 없는 것인지요?

없다면, 저희가 앞서 말한 방법대로 사용 하려 하는데, 현재 빠른 속도로 하면  429 에러인  too many request를 처리하면서 요청을 하면 되는 것으로 보이는데, 429 에러를 status code만을 체크하여 하는 방법이 아닌 식으로 하기 위해서는 초당 허용 하는 요청수가 얼마인지 알면 좋을 것 같습니다.

대량 키워드에 대한 bid가에 대한 지표 정보 estimate api 오픈 여부와 허용 하는 초당 요청 수를 알려 주시면 감사하겠습니다.

**Comment by naver-searchad** [comment]
최대 200개 키워드까지 조회하실 수 있도록 하는 기능이 곧 추가될 예정입니다.
트래픽 제한은 상황에 따라 조절되기 때문에 알려드리기 어렵습니다.
429 코드가 반환될 경우 Sleep 1초 정보 하신 후 재 요청하시기 바랍니다.

**Comment by younseunghyun** [comment]
감사합니다 :)
