### ISSUE TITLE
statReport 확인

### ISSUE THREAD

**Issue by sourcreamy** [naver/searchad-apidoc#100]
안녕하세요.
StatReport를 create하고 생성된 StatReport를 확인 하려고 합니다. StatReport.get에서는  생성된 report가 있는지, 어떤 reportTp 인지 등을 확인하는 메서드인것 같고  실제 생성된 파일은 downloadurl에서 확인 해야 하나요? 맞다면 현재 403 status인데 어떻게 해결 해야 하는지 문의 드립니다.

**Comment by naver-searchad** [comment]
안녕하세요. 검색광고 api입니다.
create는 생성 요청이 맞고, get은 요청한 보고서의 진행상태를 확인하는 것입니다. 
downloadUrl은 실제 생성된 보고서를 로컬에 다운로드 하실 수 있는 경로 정보가 맞습니다.
응답으로 403 코드를 받으신 경우는 보통 Signature 값에 오류가 있는 경우입니다.
Timestamp 와 같은 주요 필드가 올바른지 확인 해보시기 바랍니다.
상세한 Http Response 메시지를 남겨주시면, 자세히 답변드리도록 하겠습니다.

**Comment by naver-searchad** [comment]
매체 정보는 MasterReport에서 `MEDIA` 보고서를 다운로드 받으시면 됩니다.
http://naver.github.io/searchad-apidoc/#/operations/GET/~2Fmaster-reports
