### ISSUE TITLE
시간대별 및 키워드 데이터 문의

### ISSUE THREAD

**Issue by jaehawnlee** [naver/searchad-apidoc#1002]
안녕하세요

각 항목에 대해서 데이터를 가져오고자 합니다.

1.  시간대별로 전환수,전환매출액,노출,클릭,비용 등 데이터 
2. 쇼핑검색, 파워링크 등 캠페인의 검색어 별 전환수, 전환매출액,노출,클릭,비용 등 데이터 

각각 전환 수를 가져오기 위해 AD_CONVERSION_DETAIL 및 SHOPPINGKEYWORD_CONVERSION_DETAIL를 사용중에 있습니다.

검색 광고 시스템에서는 위 항목들을 45일 이전 데이터도 가져올 수 있는 부분을 확인했습니다.
api 에서도 위 항목들에 대해 45일 이전의 데이터도 가져오고 싶은데 다른 참고할만한 지표가 있을까요?

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

말씀대로

- AD_CONVERSION_DETAIL 
- SHOPPINGKEYWORD_CONVERSION_DETAIL

두 보고서 모두 45일을 제공 기준으로 하고 있습니다.

검색 광고 시스템에서 45일 이상을 확인하신 화면은 다차원 보고서를 말씀하시는 것 같습니다. 
다차원 보고서는 최근 2년을 제공하지만 Open API 로 제공하고 있지 않습니다.

감사합니다.
