### ISSUE TITLE
Adgroup타입 /master-reports 호출 시점에 따른 "fields":"{requestJob=fromTime(1727481600000) is too young. 원인 확인

### ISSUE THREAD

**Issue by SEUNGHEESEO** [naver/searchad-apidoc#1003]
안녕하세요. 
마스터 리포트 생성 시점에 따른 에러가 반환 되어 정확한 원인을 알 수 있을지 문의드립니다.

**에러 상황** 
**발생 시점** 01:15 ~ 01:59
**api 호출 및 반환 정보 :** 

> api_domain : api.searchad.naver.com
> request_body: {"item": "Adgroup", "fromTime": "2024-09-28"}
> request_url:  /master-reports
> ■■■■■■■■■■ response.getheaders() :  [('content-encoding', 'gzip'), ('transfer-encoding', 'chunked'), ('server', 'nfront'), ('x-transaction-id', 'eaa3cdc803e160de'), ('cache-control', 'no-store, must-revalidate'), ('date', 'Fri, 27 Sep 2024 16:59:38 GMT'), ('referrer-policy', 'unsafe-url'), ('content-type', 'application/json;charset=UTF-8')]
> ■■■■■■■■■■ response.status :  400
> @@@@@ response start
>  response status  400

마스터 리포트가 실시간 정보가 아닌 것으로 알고 있는데요.
따라서 반환할 마스터 리포트 값이 없어 위와 같은 에러가 발생하는 것이라면, 
당일의 리포트를 생성할 수 있는 가장 빠른 시점이 언제인지 알려주시면 도움이 될 것 같습니다. 

확인 부탁드립니다. 
감사합니다!

**Comment by naver-searchad** [comment]
안녕하세요.
`fromTime`은 시간단위 변경분을 제공하기 위해, 날짜와 시간을 `ISO8601 UTC`형식으로 입력하시기를 안내해드리고 있습니다. 따라서 입력하신 정보는 기준에 따라 플랫폼 내부에서 timestamp 값으로 변경하여 처리되게 됩니다.
따라서 `2024-09-28`은 UTC로 간주하기에, timestamp 값으로 변경하게되면, 의도하지 않게 9시가 더해진 값으로 처리가 됩니다.
아래 패턴 참고하셔서 요청시점보다 이전 시간으로 요청하시기 바랍니다.

- UTC : `2024-09-27T15:00:00Z`
  KST : `2024-09-28T00:00:00+09:00`
