### ISSUE TITLE
과거에 삭제된 광고그룹에 대한 정보가 MasterReport에 넘어오는 기준

### ISSUE THREAD

**Issue by SEUNGHEESEO** [naver/searchad-apidoc#1004]
안녕하세요.

GET /master-reports/{id}

사용중 아래 시간에 이미 삭제된 광고그룹이 9/26일 기준 변경분 데이터에 포함되어 넘어왔습니다.

> 2024-08-05T14:14:20Z
> 2024-08-05T14:14:20Z
> 2024-08-05T14:12:30Z
> 2024-08-05T13:12:35Z
> 2024-08-14T12:54:21Z
> 2024-08-14T12:54:21Z
> 2024-07-31T06:27:56Z
> 2024-08-02T07:20:52Z
> 2024-08-12T12:10:16Z

이미 삭제된 광고그룹의 변경이 가능한 정보가 있을 수 없다고 생각되는데,
왜 해당일에 변경 데이터로 함께 넘어오는것인지 
광고그룹 마스터 데이터의 변경분 기준 문의드립니다. 

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요.
삭제된 광고정보의 경우 별도의 액션을 취할 수 없기 때문에, 변경분으로 더이상 넘어오지 않는 것이 맞습니다.
이번건은 이번 광고플랫폼의 신규 기능 추가 및 개선 작업이 진행되는 동안 삭제된 광고에도 변경 시간에 영향을 미쳐서 다시 전달된건으로 보입니다.
업무에 불편을 드려서 대단히 죄송합니다.
