### ISSUE TITLE
MasterReport 문의건

### ISSUE THREAD

**Issue by jaehawnlee** [naver/searchad-apidoc#1005]
안녕하세요

만약 MasterReport에서  FromTime 을 09/01로 두고

 Keyword를 요청하면 해당날짜부터 현재까지의 모든 키워드 정보가 반환되는게 맞을까요?
 
 현재 검색 광고 시스템에서 출력한 키워드 데이터가 맞지않아 상세 내용을 확인해보니 

파워링크 관련 키워드가 대부분 누락이되어있었고 

MasterReport에는 하나의 파워링크 키워드만 반환되었습니다.

위 내용에대해 답변 부탁드립니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

fromtime 기준으로 변경 이벤트가 있었던 항목으로만 구성됩니다.
따라서 말씀주신 내용을 확인하고 싶으시다면 현재시점 MASTER와 변경분을 함께 확인하셔야 합니다.

감사합니다
