### ISSUE TITLE
급) 공유예산 포함된 그룹 수정 시, 확장검색 비율 수정 API 문의

### ISSUE THREAD

**Issue by SM11187** [naver/searchad-apidoc#1006]
안녕하세요,

이번에 확장검색 기능이 추가되어 API 테스트 중에 있습니다.

Adgroup: update (by fields)를 사용하여 그룹에 등록된 확장검색 비율은 수정하려고하는데요,

![image](https://github.com/user-attachments/assets/eeb2555d-c31c-48ea-8d5e-6910f1897eff)

위와 같이 API를 보내게되면 오류는 나지 않지만

![image](https://github.com/user-attachments/assets/1549b448-33e4-440e-9268-3fcb07dfb2be)

확장 검색 예산 상한 비율은 변경되지 않고 있습니다.

g.setUseExpSearch(true); 부분을 false로 변경하여 API를 보내면 
'확장검색'에서 '일치검색'으로 정상적으로 변경되는 것은 확인했습니다.

비율을 변경하는 방법 문의드립니다!

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요
공유예산을 사용하는 그룹일 경우 sharedBudgetId를 넣어주셔야 적용이 됩니다.
감사합니다.

**Comment by SM11187** [comment]
알려주신 방법으로 해결했습니다.

감사합니다!
