### ISSUE TITLE
/ncc/keywords no permission to access the resource

### ISSUE THREAD

**Issue by stellanoh** [naver/searchad-apidoc#1007]
statReport에서 받아오는 keywordId로 /ncc/keywords 조회 요청을 하면, 존재하지 않는 아이디여서 에러를 리턴하는 것으로 파악됩니다.

만약 statReport에 존재하는 keywordId의 keyword 이름을 받아오려면 어떻게 해야 하나요?
- 키워드가 삭제되어 keyword master 리포트에서도 조회되지 않습니다..

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

광고키워드를 삭제하면 광고 관리쪽의 모든 광고키워드 정보가 삭제가 됩니다.
stat의 경우 삭제된 광고키워드라 하더라도, 이전 기간에 쌓였던 지표를 제공해야 하기 때문에 일정기간 stat 정보를 조회할 수 있습니다.
하지만 stat의 경우 keywordId가 키가 되기 때문에 keywordId 기준의 지표만 제공됩니다. keywordId에 엮여 있던 광고관리쪽 정보는 조회할 수가 없습니다.

감사합니다.

**Comment by stellanoh** [comment]
stat의 유니크 키의 키워드id 가 있어서 성과보고서에서 id확인이 가능한것이군요!

그렇다면 혹시 검색광고 ui에서처럼 (다차원보고서에서는 삭제된 키워드라 하더라도 어떤 키워드인지 확인가능), api에서도 그렇게 확인할 수 있는 방법이 없을까요?

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

삭제 광고 정보 자체의 조회는 가능합니다.
예를들어, 삭제 키워드의 경우 대용량보고서에서 삭제시점 이전 ~ 현재로 조회하는 경우 삭제 이벤트를 확인할 수 있기때문에
정보 확인 자체는 가능합니다.

감사합니다

**Comment by stellanoh** [comment]
그럼 삭제 키워드 내용을 확인하려면 등록키워드마스터에서 확인 가능하다고 보면 되는건가요?

지금으로부터 1년전으로 기간을 설정하고 키워드 id를 검색했는데도 안 나왔어서요..

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

네 맞습니다.
등록키워드마스터에서 지금으로부터 1년전으로 기간을 설정하고 리포트 다운로드를 할 경우
설정한 기간부터 현재까지 변경된 내용이 다운로드 됩니다 (삭제포함)

**Comment by stellanoh** [comment]
흠 그럼 그 키워드마스터에 해당 키워드가 안나온다는 건 그 기간보다 전에 키워드가 삭제됐는데 전날 통계 데이터에는 해당 키워드가 포함된 데이터를 받는 다고 이해하면 될까요?

**Comment by naver-searchad** [comment]
안녕하세요 네이버 검색광고 API입니다.

네 맞습니다, 해당 키워드가 나오지 않는다는건 선택한 기간동안 변경이 발생하지 않았다는 의미입니다.
