### ISSUE TITLE
키워드 실적 vs 키워드플러스 실적 문의

### ISSUE THREAD

**Issue by githubcnsbs** [naver/searchad-apidoc#1008]
안녕하세요.

콘솔 화면과 키워드 플러스의 실적데이터를 비교해보고 있습니다.  

아래는 콘솔화면의 데이터 값이고, 
- nkw-a001-01-000004672931182 키워드의 실적은 아래와 같이 노출수: 858, 클릭: 65, 전환: 3
- 확장검색 결과: 노출수 4, 클릭 0, 전환 0

![전체실적](https://github.com/user-attachments/assets/fc7f12c1-0daa-4189-a762-aec39cce258a)

아래는 키워드플러스 실적을 API로 받아 동일 키워드 이름으로 filtering한 결과입니다. 
- search_keyword_type을 어떻게 조합해야, 위 콘솔과 같이 확장검색결과 / keyword_id에 대한 결과로 분류할 수 있을까요. 
![keyword_plus_실적](https://github.com/user-attachments/assets/19bd9451-0e7a-4c36-9585-d4ba591bf9a8)

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요 검색광고 API 담당자입니다.

문의내용을 정확하게 파악하지 못하였는데요.
일치검색과 확장검색의 결과를 비교하고 싶으시다는 질문으로 해석하여 답변 드리겠습니다.

답변 : 
Powerlink Search Term Report (reportTp: EXPKEYWORD)
8번 항목에서 search keyword type을 제공하고 있습니다.
위 항목에서 일치검색, 확장검색에 대한 분류를 확인할 수 있습니다.

**Comment by githubcnsbs** [comment]
안녕하세요.

제가 EXPKEYWORD로 호출하여 받은 결과가 최초 문의에 엑셀 스샷으로 드린 결과입니다.
말씀해주신 8번 항목이 스샷에 있는 6번째 search_까지만 보이는 컬럼 (search keyword type)이며, 

**문의의 요지는 이 8번 항목의 어떤 값으로 filter를 해야 콘솔 화면의 값을 뽑을 수 있는 지에 대한 질문입니다.** 

 제가 임의로 조합을 하면 비슷한 수치를 뽑을 수는 있으나 정확한 type 값과 콘솔 화면의 표기 기준을 알 수 있는 설명이 없어 문의 드린 것입니다. 
![image](https://github.com/user-attachments/assets/12900b55-87da-4d08-b5e6-6b9c4b3a3bb4)

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요 검색광고 API 입니다.

말씀주신 콘솔화면 (검색광고 관리 화면)에서 상단 보고서 클릭하시어 다차원 보고서로 진입 '검색어 보고서' 항목으로 확인하시면 원하시는 값 확인 가능할것으로 보여집니다.

감사합니다.

**Comment by githubcnsbs** [comment]
안녕하세요. 
콘솔로 다운 받아서 비교하여 보았습니다. 

결과에 대한 두 가지 비교사항이 아래와 같습니다. 

---------- **1번 키워드: nkw-a001-01-000005441002145 의 10/10일자 실적 데이터 입니다.** 

- 콘솔 화면: 
- ![image](https://github.com/user-attachments/assets/516e2536-d359-47d2-9fcc-6c8370cf07c1)
- 콘솔로 다운로드한 결과: 
- ![image](https://github.com/user-attachments/assets/e5286fcf-eda9-457f-82e8-d1bb2c25a509)
- 키워드 플러스(EXPKEYWORD) API response 결과의 동일 키워드명으로 filter:
- ![image](https://github.com/user-attachments/assets/ef12fc9d-04dd-4127-afb2-b79165209559)

**결과: 콘솔 결과(sum(impressions) = 769) != 콘솔다운로드결과(sum(impressions) = 81) = 키워드플러스 response 결과(sum(impressions) = 81)**
-----------------------------------------------------------------------------------------------

---------- **2번 키워드: nkw-a001-01-000004672931182 의 10/10일자 실적 데이터 (최초 질문했던 키워드 입니다.)** 

- 콘솔 화면: 
- ![image](https://github.com/user-attachments/assets/694acc21-078d-4a02-893d-5b99a4e95f41)
- 콘솔로 다운로드한 결과: 
- ![image](https://github.com/user-attachments/assets/726ab837-76ce-4bb1-b396-17ecf7b3fe44)
- 키워드 플러스(EXPKEYWORD) API response 결과의 동일 키워드명으로 filter:
- ![image](https://github.com/user-attachments/assets/14676e9b-77a7-47b7-aaec-b10cec1ef62f)


**결과: 콘솔 결과(sum(impressions) = 858) != 콘솔다운로드결과(sum(impressions) = 1615) = 키워드플러스 response 결과(sum(impressions) = 1615)**
-----------------------------------------------------------------------------------------------

즉, 콘솔 결과 != 키워드플러스 response 결과가 일치하지 않습니다. 
키워드 플러스 결과를 어떻게 조합해야 키워드 플러스 실적과 키워드의 실적을 알아낼 수 있는 지에 대한 문의 입니다. 
(참고로 키워드플러스 response 결과의 2번 키워드에서 "네이버 통합검색 파워링크 스마트블록 - PC" 항목을 빼면 콘솔 수치와 일치합니다. 그러나 1번 키워드 같은 경우는 어떻게 맞춰도 실적을 맞출 수 없습니다.)

**Comment by naver-searchad** [comment]
안녕하세요 검색광고 API 담당자입니다.
용어에 대해 먼저 정리가 필요할 듯 싶습니다.

말씀주신 각각의 용어는 다음을 의미하는것으로 보여지는데요.
1. 콘솔화면 = 네이버 검색광고 키워드 화면
2. 키워드 플러스 = EXPKEYWORD (검색어)

키워드화면(콘솔화면)에서 보여주는 키워드와, 키워드플러스(EXPKEYWORD)에서 보여주는 검색어 
는 애초에 다른 지표이며, 서로 조합하여 사용할 경우 정합성이 맞지 않습니다.

키워드 플러스(EXPKEYWORD / 검색어) 의 성과만 확인하고 싶으신 경우
위에 말씀드린 다차원보고서에서 확인하시면 전환수까지 확인이 가능합니다.

감사합니다.

**Comment by githubcnsbs** [comment]
안녕하세요, 
계속 논의가 돌고 도는데요.

실적을 분석하는 입장에서는 
 - 세팅된 키워드에서 발생한 실적인가
 - Keyword_ID로 세팅하지 않은 키워드 플러스 기능으로 추가된 실적인가
로 구분하는 것이 당연한데, 어떻게 구분해야 하는 지에 대한 답변 없이 계속 다운 받아서 알아서 보라는 답변을 주시는 부분은 이해가 되지 않네요. 

 키워드 플러스 실적(EXPKEYWORD) 을 주는 이유가 무엇인가요.
 이것은 "고객이 세팅하지 않은 키워드에서도 이런 정도의 실적이 발생하도록 네이버가 시스템을 마련했고, 그 실적은 이것이다 " 라는 의미가 아니라 다른 의미 인가요. 

 키워드 플러스 (EXPKEYWORD)의 실적에서 KEYWORD_ID로 세팅하지 않은 키워드 플러스로 인한 실적을 볼 수 있는 방법을 알려주시면 감사하겠습니다. 
 (Search Type 1, 2로 들어오는 것만 보면 Keyword ID로 세팅하지 않은 추가 실적을 볼 수 있다던가 하는 공식적인 가이드 요청드리는 것입니다)

 방법이 없으면 없다는 명확한 답변으로 주시면 감사하겠습니다.

**Comment by naver-searchad** [comment]
안녕하세요 ? 검색광고 API 입니다.
제가 질문을 정확하게 이해하지 못해 애매한 답변만 드린 것 같습니다.
이 점 다시한번 사과드립니다.

최대한 정확하고 명확하게 답변 드릴 수 있도록 하겠습니다.

1. 우선 EXPKEYWORD는 키워드 플러스에 대한 실적이 아닙니다.
2. EXPKEYWORD는 파워링크 캠페인 유형의 검색어별 광고 성과를 제공하는 리포트이며, 말씀주신 키워드 플러스는 서비스 중지 되었습니다. 
3. (이 부분은 NAVER SEARCH AD API > REFERENCE > STATREPORT > OVERVIEW > POWERLINK SEARCH TERM REPORT 
혹은 검색광고 센터 > 보고서 > 대용량 보고서 > 도움말 보기 > 데이터 사양서 다운로드 확인 부탁드리겠습니다)

#### 문의주신 내용 답변 드리겠습니다.
>키워드 플러스 (EXPKEYWORD)의 실적에서 KEYWORD_ID로 세팅하지 않은 키워드 플러스로 인한 실적을 볼 수 있는 방법을 알려주시면 감사하겠습니다.
(Search Type 1, 2로 들어오는 것만 보면 Keyword ID로 세팅하지 않은 추가 실적을 볼 수 있다던가 하는 공식적인 가이드 요청드리는 것입니다)
- 위 내용 정확하게 답변 드리겠습니다.
EXPKEYWORD에서 keyword_id로 세팅되지 않은 '확장검색'으로인한 실적은 
EXPKEYWORD 8번 항목의 Search Keyword Type  = 5이고, 
6번 Media Code = 4124060 혹은 4124069 인 경우입니다.

감사합니다.

**Comment by githubcnsbs** [comment]
안녕하세요. 
자세한 답변 감사드립니다.

그럼,  [확장 검색 기능](https://saedu.naver.com/notice/view.naver?notiSeq=4445&catg=&fixYn=Y&searchOpt=all&keyword=) 에서 안내하고 있는 실적은 어떤 API를 이용하여 가져올 수 있을까요.

감사합니다.

**Comment by githubcnsbs** [comment]
안녕하세요.  질문을 바꿔서 하나 씩 다시 해보겠습니다. 

- 검색광고시스템 > 보고서 > 다차원보고서 > 새보고서 > 기본 > 검색어 로 검색한 아래 콘솔 화면의 결과를 어느 API로 확인이 가능할까요. 
![image](https://github.com/user-attachments/assets/d520e5d5-2072-40cf-947f-3a16209878e7)

 NAVER SEARCH AD API > REFERENCE > STATREPORT > OVERVIEW > Powerlink Search Term Report (reportTp: EXPKEYWORD) 가 해당 API가 맞을까요

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요 ? 검색광고 API 입니다.

> 검색광고시스템 > 보고서 > 다차원보고서 > 새보고서 > 기본 > 검색어 로 검색한 아래 콘솔 화면의 결과를 어느 API로 확인이 가능할까요.
- 콘솔화면의 다차원보고서와 EXPKEYWORD가 100% 일치하다고 볼 순 없습니다.
다만, API로 파워링크 검색어 관련 데이터를 확인할 수 있는 리포트는 Powerlink Search Term Report (reportTp: EXPKEYWORD)가 유일합니다.
- 가장 큰 차이점에 관해 설명드리면, 다차원보고서를 콘솔화면에서 확인하는 경우 전환관련 데이터까지 확인이 가능하지만, Powerlink Search Term Report (reportTp: EXPKEYWORD) 에서는 전환관련 데이터를 제공하지 않고 있습니다.

감사합니다 !

감사합니다.

**Comment by githubcnsbs** [comment]
네, 답변 감사드립니다.

그럼 impression / click만 놓고 볼 때, 
grp-a001-01-000000028108102 애드그룹의 검색광고 실적을 보면 아래와 같습니다. 
![image](https://github.com/user-attachments/assets/f5b6140d-b38f-4504-8ae5-093152b219f2)

그리고,  동일 'grp-a001-01-000000028108102' 애드그룹의 다차원보고서 > 검색어 보고서를 다운 받아보면 
![image](https://github.com/user-attachments/assets/09619c03-3545-4f43-a033-489c9eb03176)
이렇게 나타납니다. 

위 두 보고서만 놓고 보면 검색광고에 나타나는 확장검색이라고 표기되는 실적은 다차원보고서 > 검색어 보고서에서의 
-  '검색유형'은  '확장'
-  '매체이름'은 '네이버 통합검색 - 모바일'
인 경우를 합산한 것이 검색광고 실적에 표기되는 확장검색과 동일합니다.

제가 이해한 것이 맞을까요.

**Comment by naver-searchad** [comment]
안녕하세요 검색광고 API 입니다.

네 맞습니다, 정확하게 이해하신 것 같습니다!

**Comment by githubcnsbs** [comment]
네, 감사합니다.

그렇다면 이제, EXPKEYWORD와의 매핑이 필요합니다. 
아래 엑셀 피봇은 위 comment에 해당하는 동일 날짜(10-20일)의 동일 애드그룹('grp-a001-01-000000028108102')의 API 호출 return을 피봇한 값입니다. 
![image](https://github.com/user-attachments/assets/3aa86793-08d6-4448-9af9-b65d3db737de)


이 보고서를 보면 아래와 같다고 추론하게 됩니다. 
- 검색광고 화면에서의 '확장'이란 EXPKEYWORD의 search_keyword_type의 '1'이면서 media code가 '8753'을 의미하고
- 검색광고 화면에서의 '키워드 실적'이란 search_keyword_type의 '0','5'를 의미
![image](https://github.com/user-attachments/assets/75b2b5b3-a81a-455b-af6e-09cd3460ed0c)

 다만 이것은 저의 추론일 뿐이고 실제로 제가 놓친 media code가 있을 수 있고, 다르게 조합해야 나올 수 있는 값이 있는 것으로 보입니다. 

 당장 위 값만 보아도 앞서 공유해주신 아래 내용과 다릅니다. 
(아마도 search_keyword_type이 5가 아니라 2를 의미하신 것으로 보입니다)

>     _위 내용 정확하게 답변 드리겠습니다.
>     EXPKEYWORD에서 keyword_id로 세팅되지 않은 '확장검색'으로인한 실적은
>     EXPKEYWORD 8번 항목의 Search Keyword Type = 5이고,
>     6번 항목의 Media Code가 27758혹은 8753 인 경우입니다._

 **API를 이용하여 데이터를 가져오는 개발자/데이터 분석 입장에서는 저의 추론이 아닌 API 제공 데이터에 대한 명확한 가이드 라인이 있어야 잘못된 분석을 방지할 수 있습니다.** 

 (제 첫 질문은 '개발자가 code와 type만 보고 어떤 데이터인지 맞추기가 어렵다' 에서 시작합니다. 중간에 주신 media code가 Media Code가 27758혹은 8753는 제외한다던가 하는 것들은 개발자가 데이터만 보고 알 수 없는 정보입니다. 문서에도 없습니다.)

**이에 아래 3가지 화면 **vs** 다차원리포트 **vs** EXPKEYWORD API의 값 매핑 관계에 대한 가이드를 요청드립니다.** 

> 예시) 
> 검색광고 키워드 화면 **vs** 다차원리포트/검색어 **vs** EXPKEYWORD API response값
>  - 확장검색결과 **vs** 검색유형(확장) & 매체이름('네이버 통합검색 - 모바일') 값 **vs** search_keyword_type(1) & media code in (8753, 27758)인 값
>  - 키워드 xx개 결과 **vs** 검색유형 in (일치, 일치(유사검색어)) + 검색유형(확장) & 매체이름('네이버 통합검색 파워링크 스마트블록 -모바일') 값 **vs** search_keyword_type in ('0','5')의 값  **(아마도 이 부분은 추가 가이드가 있을 것으로 보입니다)**


감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요 검색광고 API입니다.

먼저, 확장검색에 대해서 설명을 드리자면
24년 8월 26일 공지된 내용 (https://saedu.naver.com/notice/view.naver?notiSeq=4425) 확인하시면
24년 10월 부 확장 검색 기능은 다차원 보고서 > 검색어 보고서에서 ‘검색 유형 = 확장’이고 ‘매체 이름 = 네이버 통합검색 -PC/모바일’ 경우에 해당된다. 라고 명시 되어있습니다.
그렇다면, EXPKEYWORD API에서는 위 조건과 동일하게 search keyword type = 1(검색 유형 = 확장)이고, media code = 27758, 8753(매체 이름 = 네이버 통합검색 -PC/모바일)인 경우입니다.

이때, 미디어명과 미디어ID는 광고그룹 생성/수정화면의 ‘매체’ 에서 매체리스트 다운로드를 통해 모든 미디어 정보를 제공하고 있습니다.

또한, 검색광고에서 제공하고 있는 모든 기능은 공지를 사전 고지를 드리고 있으며, API 의 변경 또한 사전 고지하고 관련 내용들은 레퍼런스 페이지와 메뉴얼 파일로 모두 제공하고 있으니 공지를 확인해주시기 바랍니다.

말씀주신 검색광고 키워드 화면 vs 다차원리포트/검색어 vs EXPKEYWORD API response값에 대해 설명 드리자면
- 검색광고 키워드 화면 : 특정 광고그룹의 키워드별 성과를 제공합니다. 이때 ‘확장 검색 결과’로 특정 광고그룹의 확장 검색 성과를 확인 하실 수 있습니다. 
이때 제공되는 성과는 노출수, 클릭수, 클릭률, 평균클릭비용, 총비용, 전환수, 전환율, 전환매출액, 전환수익률, 전환당비용, 동영상조회수, 평균노출순위, PC통검평균노출순위, 모바일통검평균노출순위, 최근통검평균노출순위, 최근통검평균클릭비용 입니다.
- 다차원 보고서 > 검색어 보고서 : 전체 광고 중 해당 기간에 성과가 있었던 광고에 대해 검색어별로 성과를 제공합니다. 다차원보고서는 필요하신 항목을 여러 가지 조합하여 확인하실 수 있으며, 검색어 보고서에서 제공되는 성과는 노출수, 클릭수, 클릭률, 평균클릭비용, 총비용, 전환수, 전환율, 전환매출액, 전환수익률, 전환당비용, 동영상조회수, 평균노출순위, 반응수, 직/간접 전환수, 직/간접 전환매출액, 네이버페이 전환수/전환매출액, 방문당 평균 페이지뷰, 방문당 평균체류시간 입니다.
- EXPKEYWORD API : 파워링크 캠페인 유형의 검색어 별 광고 성과를 제공합니다. 제공되는 성과는 노출수, 클릭수, 광고비, 동영상조회수 입니다.

만약 특정 광고그룹에 대해서 키워드별로 성과확인이 필요하시다면 **검색광고 키워드 화면**을 보시면 되며,
전체 광고의 검색어에 대해서 좀 더 다양하고 긴 기간으로 성과를  확인하고 싶으시다면 **다차원 보고서 > 검색어 보고서**를 사용하시고
파워링크 캠페인의 검색어별 성과를 대용량으로 성과를 확인하고 싶으시다면 대용량 보고서의 **EXPKEYWORD를 활용하시면 됩니다**. 
각 리포트들이 제공되는 범위와 제공되는 항목이 모두 다르기 때문에 **광고주님이 니즈**에 따라 결정하셔서 활용해주시기 바랍니다.

**Comment by githubcnsbs** [comment]
네, 감사합니다.
