### ISSUE TITLE
시군구별 지역코드도 다 알려주세요

### ISSUE THREAD

**Issue by devjy1550** [naver/searchad-apidoc#1009]
00 = 해외
-1 = 미분류
99 = 국내
01 = 강원도
02 = 경기도
03 = 경상남도
04 = 경상북도
05 = 광주광역시
06 = 대구광역시
07 = 대전광역시
08 = 부산광역시
09 = 서울특별시
10 = 울산광역시
11 = 인천광역시
12 = 전라남도
13 = 전라북도
14 = 제주특별자치도
15 = 충청남도
16 = 충청북도
17 = 세종특별자치시

이렇게 말고도

각 시의 구나 도의 군같은 수준의 세부코드는 어디서볼수있나요??

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

지역코드를 사용하시는 이유를 알 수 있을까요?
네이버 검색광고 API는 지역 코드를 제공하지 않습니다.

만약 광고그룹의 타겟팅에 사용하시는 거라면, https://naver.github.io/searchad-apidoc/#/operations/GET/~2Fncc~2Fcriterion-dictionary%7B%3Fdictionary%20type%7D API를 이용하여 Dictionary code를 조회할 수 있습니다.

감사합니다.
