### ISSUE TITLE
AdKeyword 관련 문의 입니다.

### ISSUE THREAD

**Issue by sourcreamy** [naver/searchad-apidoc#101]
안녕하세요.
키워드가 어느 위치 또는 매체에서 클릭되었는지 알 수 있을까요?
예를 들면 통합검색 또는 블로그 ,카페 ,쇼핑 등이 있을때
키워드가 클릭 된 횟수가 5번이라고 하면
3번은 통합검색,2번은 블로그 .. 
이런 식으로 확인 할 수 있을까요?

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API 입니다. 

답변이 늦어 죄송합니다. 제가 개인적인 사정으로 몇일간 회사에 출근을 하지못했었습니다. 
클릭이 발생한 매체는 보고서에서 확인가능하십니다. 
보고서 스팩 중에 media code 가 매체를 나타냅니다. 
보고서 스팩 : http://naver.github.io/searchad-apidoc/#/tags/StatReport
                      https://saedu.naver.com/help/faq/ncc/view.nhn?faqSeq=178
                       (데이터 사양서를 참고하시면 되겠습니다. 몇개 마스터 보고서는 사양서에 업데이트가 
                        아직 되지 않았는데요. 이점 양해 부탁드립니다.)

media code 값으로 매체의 이름이나 URL 등을 확인하시고자 하실때는 
MASTER REPORT의 Media Details (Media) 보고서를 이용해 주시면 되겠습니다.
한가지 주의 하실 점이 있는데요. 웹툰이나 네이버블로그의 경우 다른매체들과는 달리 PC용 매체, 모바일 환경용 매체가 나눠져 있지 않습니다. 블로그나 웹툰이 매체일때는 보고서의 PC/모바일 필드를 이용해서 구분해 주시면 되겠습니다.

이외의 광고 클릭시 순위가 필요하신 경우
1) 평균 노출 순위 라면 보고서에 sum of ranks 를 impression으로 나눠서 사용
2) 실제 클릭 발생시 순위는 API가 아닌 추적기능을 통해 광고대상 웹사이트(광고주님 웹사이트)에서 
로그를 수집하시는 방법으로 조회 가능하십니다.

감사합니다.

**Comment by sourcreamy** [comment]
네 감사합니다.
질문이 한가지 더 있습니다.
마스터 데이터와 보고서 데이터는 create하는 경우에만 생성이 되나요?(create하지 않은 날짜의 데이터가 
있어서 질문 드립니다.)
매일 마스터 데이터와 보고서 데이터를 create한다고 했을때 삭제하기 전까지는 데이터가 유지 되나요?

**Comment by naver-searchad** [comment]
마스터 보고서와 지표 보고서는 요청한 경우에만 생성됩니다. 생성 요청은 광고주의 접근권한을 소유한 모든 계정에서 가능합니다. 다른 계정을 통해서 생성된건 아닌지 확인해보시기 바랍니다. 
보고서 생성 이력은 삭제하기 전까지 유지됩니다. 다만, 마스터 보고서의 경우 최대 100개까지 이력이 유지되므로, 그 이상은 이전 이력을 삭제하기 전까지 처리되지 않습니다. 이점 참고하시기 바랍니다.

**Comment by sourcreamy** [comment]
안녕하세요.
위에 답변 주신 부분에
2.실제 클릭 발생시 순위는 API가 아닌 추적기능을 통해 광고대상 웹사이트(광고주님 웹사이트)에서
 로그를 수집하시는 방법으로 조회 가능하십니다.
이런 내용이 있는데 실제 클릭 발생시 순위를 조회 하려고 합니다.
클릭 발생시 순위는 어떤 파라미터로 확인이 가능 할까요?

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

전달되는 파라미터 값 중 n_rank 파라미터의 값입니다. 

전체 스팩은 아래 링크에서 확인 가능하십니다.
https://saedu.naver.com/help/faq/ncc/view.nhn?faqSeq=120

감사합니다.
