### ISSUE TITLE
광고 type에 따른 데이터 출력값 문의

### ISSUE THREAD

**Issue by wb-sychoi** [naver/searchad-apidoc#1010]
api 문서 상에 TEXT_45에 관련된 예제는 나와있지만 나머지 type항목들에 대한 예제는 나오지 않아 일일이 데이터 확인 후 출력중입니다.
하지만 해당 type들을 다 사용하는 것이 아니다보니 확인되지 않는 예제들도 있는데요.

CONTENTS_AD_PRODUCT, CATALOG_AD, SHOPPING_BRAND_AD
이거에 대한 출력값들이 어떻게 될까요?

또한 문서상에 나와있는 type의 종류 외에도 출력되는 것들이 있던데 문서상에 표기만 되지 않은건가요?
이런 것들이 추가적으로 더 있나요?
=> RSA_AD , SHOPPING_BRAND_IMAGE_BANNER_AD

(https://naver.github.io/searchad-apidoc/#/operations/GET/~2Fncc~2Fads%7B%3FnccAdgroupId%7D)
[type] [string]
TEXT_45
SHOPPING_PRODUCT_AD
CONTENTS_AD_INFORMATION
CONTENTS_AD_PRODUCT
BRAND_SEARCH_AD
PLACE_AD
CATALOG_AD
SHOPPING_BRAND_AD

TEXT_45
Ad type for Text ad: a headline, a description (length:45), a pc url, a mobile url
valid charactor and pattern formed as javascript regex.
Example
{  
   "pc":{  
      "final":"http://searchad.naver.com"
   },
   "mobile":{  
      "final":"http://m.searchad.naver.com"
   },
   "headline":"the first line",
   "description":"the second line of your ad text"
}

**Comment by searchad-api-customer-service** [comment]
안녕하세요? 네이버 검색광고 API입니다.

아래 FAQ 내용을 참고하시기 바랍니다.
https://github.com/naver/searchad-apidoc/wiki/FAQ#q-%EA%B4%91%EA%B3%A0-%EC%86%8C%EC%9E%AC-%EC%9C%A0%ED%98%95%EB%B3%84-%EC%9D%91%EB%8B%B5-json%EC%9D%98-ad-adattr-%ED%94%84%EB%A1%9C%ED%8D%BC%ED%8B%B0%EB%8A%94-%EC%96%B4%EB%96%BB%EA%B2%8C-%EB%90%98%EB%82%98%EC%9A%94

감사합니다.
