### ISSUE TITLE
/stat-reports ad 타입 데이터 정합성 문의

### ISSUE THREAD

**Issue by stellanoh** [naver/searchad-apidoc#1012]
안녕하세요 api 로 현재 stat report 생성후 리포트를 받아서 확인 중에 있는데, 
대용량 보고서에서 검색어는 어떻게 구별가능할까요? 키워드와 검색어의 값이 다른데, 제공되는 stat-report는 키워드 별로만 분류되는 것 같아 문의드립니다!

EXPKEYWORD, SHOPPINGKEYWORD_DETAIL, SHOPPINGKEYWORD_CONVERSION_DETAIL 로 검색어 단위로 만약 조회를 해야 한다면, 해당 보고서에서 지원하지 않는 필드의 경우(EXPKEYWORD- Sum of AD rank, 전환수, 전환매출액 ) 는 어떻게 표현해야 하는지 알고 싶습니다. 
-현재 다차원보고서에서는 파워링크, 쇼핑검색 유형이 아닌 캠페인에 대한 성과는 stat-report의 keyword 기준으로 조합해서 보여주고 있는 건가요?

**Comment by stellanoh** [comment]
@naver-searchad 
안녕하세요! 혹시 해당 내용은 답변이 어려우신 걸까요..? 
일별, 캠페인, 광고그룹, 검색어, 캠페인유형, device 별로 노출수, 클릭수, 총비용, 전환수, 전환매출액, 평균노출순위를 확인하려고 합니다! 

다만, 제공되는 api 를 확인해본 결과 쇼핑검색만 모든 정보를 확인 가능한것으로 보이고(SHOPPINGKEYWORD_DETAIL, SHOPPINGKEYWORD_CONVERSION_DETAIL), 파워링크는 검색어별 노출수, 클릭수, 총비용(EXPKEYWORD) 만 제공하는 것으로 파악했습니다.  

그렇다면 다차원보고서에서 확인할 수 있는 그외 지표와 그외 캠페인 유형은 어떻게 조합해서 보여줘야 하는지 궁금해 문의드렸습니다!

**Comment by naver-searchad** [comment]
안녕하세요? 검색광고 API입니다.

답변이 늦었습니다.
키워드와 검색어는 다른 지표이며 powerlink search term report (EXPKEYWORD)에서 제공하는 지표를 다른 보고서에서 제공하는 지표(특히 키워드)와 조합하는 경우 정합성이 맞지 않습니다. 

문의주신 검색어별 각 지표는 API에서 제공하는 것 외에는 확인이 어렵습니다.
다만 다차원보고서 > 검색어보고서에서 확인 시 전환 수 등 추가적으로 확인이 가능합니다.

감사합니다.

**Comment by stellanoh** [comment]
그럼 다차원보고서에서는 검색어별 전환수, 전환매출액, 평균 순위는 어떻게 보여주고 있는 건가요? 
등록되어 있는 키워드와 검색어가 일치할 경우 키워드 기반으로 지표를 측정하는 걸까요??

**Comment by naver-searchad** [comment]
안녕하세요? 검색광고 API입니다.

우선, 문의주신 @stellanoh님꼐서도 알고 계시겠지만
API로 제공되는 항목이 훨씬 많기 때문에 전환과노출/클릭 등 지표 정보를 분기하여 따로 제공하고 있습니다
(전환의 경우 ~~conversion report 등으로 별도 제공중)

현재 검색어를 기준으로 하는 CONVERSION 리포트는 별도로 제공할 수 있도록 검토중에 있으며
빠른 시일내에 제공하고자 노력하고 있습니다.
일정은 별도 공지를 통해 찾아보실 수 있도록 하겠습니다.

감사합니다.
