### ISSUE TITLE
master-reports API 호출 시 "Internal Server Error" 오류 발생

### ISSUE THREAD

**Issue by donghwan-ahn** [naver/searchad-apidoc#1014]
안녕하세요.

저희는 새벽에 master-reports API를 호출하여 광고 데이터를 수집하고 있습니다.

어제, 오늘 4시 ~ 6시 사이에 대부분의 API 호출이 아래와 같은 응답을 주며 실패했습니다.
```json
{"status":500,"type":"about:blank","title":"Internal Server Error","detail":""}
```

혹시 해당 시간대에 어떤 문제가 있었던 걸까요?
답변에 미리 감사 드립니다.

**Comment by naver-searchad** [comment]
안녕하세요? 검색광고 API입니다.

내부 배치작업과 광고주님이 요청주신 보고서 생성 작업 요청이 겹쳐서 발생한 이슈로 보여집니다.
보통 새벽시간대에 내부 시스템에 필요한 배치들이 진행되는데요, 이 때 타임아웃으로 인한 에러가 종종 발생하곤 합니다.

이 경우 보통 잠시 후 재시도를 하게되면 정상적으로 동작합니다.

감사합니다.

**Comment by donghwan-ahn** [comment]
답변 감사 드립니다.
추가로 하나만 더 질문 드리겠습니다.

내부 배치 작업이 실행되는 시간대가 언제일까요?
가능하면 그 시간대를 피해서 API 호출을 하려고 합니다.

**Comment by naver-searchad** [comment]
안녕하세요? 검색광고 API입니다.

보통 사용자가 가장 적은 시간인 새벽시간에 여러 배치들이 동작하게 됩니다.
작업이 너무 많아 정확하게 말씀드리기는 어렵지만.
완전한 새벽시간 보다는 오히려 주 업무시간 ~ 새벽시간 사이인, 오후 7~11시 사이 이 정도가 가장 TIMEOUT 확률이 적을것으로 보여집니다.

답변이 충분하다면 확인 후 이슈 종료 부탁드리며
추가 문의사항 있으실경우 새로 이슈 생성 부탁드리겠습니다.

감사합니다 ~!
