### ISSUE TITLE
현재 api 관련 이슈되는부분이 있나요??

### ISSUE THREAD

**Issue by jyKim1114** [naver/searchad-apidoc#1016]
굉장히 진행되는 속도가 느린거같아서요.

**Comment by naver-searchad** [comment]
안녕하세요 검색광고 API 입니다.

현재 확인하고 있으며, 즉시 조치 가능한 부분은 조치하고 있습니다.
잠시 후 재시도하시어 동일한 이슈 발생시에 코멘트로 말씀해주시면 감사하겠습니다.

조치 완료후에는 별도로 안내드리거나 공지를 통해 내용 전달드릴 수 있도록 하겠습니다.

감사합니다

**Comment by naver-searchad** [comment]
안녕하세요 검색광고 API 입니다.

외부 요청량이 급증하여 TIMEOUT이 다수 발생한 것으로 확인되어 
현재보다 훨씬 많은 양의 요청도 처리가능하도록 수정/배포 완료하였습니다.

리포팅 감사드리며, 재시도 후에도 동일이슈 발생한다면
다시 전달 부탁드리겠습니다.

감사합니다 !
