### ISSUE TITLE
get /master-reports 500 에러가 수시로 나고있습니다.

### ISSUE THREAD

**Issue by mainmai** [naver/searchad-apidoc#1018]

**Comment by naver-searchad** [comment]
안녕하세요 검색광고 API 입니다.

외부 요청량이 급증하여 TIMEOUT이 다수 발생한 것으로 확인되어 
현재보다 훨씬 많은 양의 요청도 처리가능하도록 수정/배포 완료하였습니다.

리포팅 감사드리며, 재시도 후에도 동일이슈 발생한다면
다시 전달 부탁드리겠습니다.

감사합니다 !
