### ISSUE TITLE
report api 오류 발생중입니다.

### ISSUE THREAD

**Issue by chanwj82** [naver/searchad-apidoc#1019]
어제부터(2024-10-23) report api  애러가 발생해서 재처리 하였는데, 금일도(2024-10-24) 지속적으로 애러가 발생하네요,,,

별도 장애공지도 없고,,, 여기 비슷한 장애 문의가 있는거로보아 저희만 문제가 아는듯 한데 빠른 확이 부탁드립니다.

**Comment by naver-searchad** [comment]
안녕하세요 검색광고 API 입니다.

500 에러는 Timeout으로 인한 error 입니다.
보통은 잠시 후 재시도하면 정삭적으로 처리되는데요.

현재 동시다발적으로 비슷한 유형의 이슈가 발생중에 있어 정확한 원인 확인중에 있습니다.
현재 즉시 조치 가능한 부분은 조치하고 있으니
잠시 후 재시도하시어 동일한 이슈 발생시에 코멘트로 말씀해주시면 감사하겠습니다.

조치 완료후에는 별도로 안내드리거나 공지를 통해 내용 전달드릴 수 있도록 하겠습니다.

감사합니다

**Comment by naver-searchad** [comment]
안녕하세요 검색광고 API 입니다.

외부 요청량이 급증하여 TIMEOUT이 다수 발생한 것으로 확인되어 
현재보다 훨씬 많은 양의 요청도 처리가능하도록 수정/배포 완료하였습니다.

리포팅 감사드리며, 재시도 후에도 동일이슈 발생한다면
다시 전달 부탁드리겠습니다.

감사합니다 !
