### ISSUE TITLE
get /stat-reports 에서 상세 breakdown 확인

### ISSUE THREAD

**Issue by stellanoh** [naver/searchad-apidoc#1020]
안녕하세요, 
다차원보고서에서는 지역, 상세지역, 성별, 연령대 별로 성과를 분리해서 확인 할 수 있는데,
stat-reports 에는 지역을 제외하고는 그렇게 세분화해서 볼 수 있는 방법이 따로 없어보이는데 제가 이해한 상황이 맞을까요? 

만약에 있다면 어떤식으로 조합하면 되는 건가요?

**Comment by naver-searchad** [comment]
안녕하세요 @stellanoh 님,

이해하신 부분이 맞습니다.
타겟팅 관련 성과는 타겟팅 성과/전환 보고서에서 확인이 가능하지만, 아쉽게도 다른 광고 엔티티들과 조합하여 확인하기는 어렵습니다.

타겟팅 설정 별 성과를 확인하고 싶으시다면 다차원보고서를 활용 부탁드리겠습니다.

감사합니다
