### ISSUE TITLE
api 인증정보 변경 여부 문의

### ISSUE THREAD

**Issue by breakit100** [naver/searchad-apidoc#1021]
안녕하세요 

통합회원 전환 공지와 관련 문의 드립니다. 
https://saedu.naver.com/notice/view.naver?notiSeq=4415

회원 전환과 관련 하여 api 인증정보도 변경 예정인지 확인 부탁드립니다. 

감사합니다.

**Comment by searchad-api-customer-service** [comment]
안녕하세요? 네이버 검색광고 API입니다.

회원 전환과 관련하여 API인증에 대한 변경은 예정되어 있지 않습니다.

감사합니다.
