### ISSUE TITLE
제외 키워드 갯수 문의 증가

### ISSUE THREAD

**Issue by miinye** [naver/searchad-apidoc#1022]
안녕하세요.

제외 키워드 최대 갯수에 대해서 질문 드립니다.
현재 광고그룹당 제외 키워드를 등록할 수 있게 되어 있는데, 최대 950개까지 등록 가능한 것으로 나옵니다.

그런데 이 갯수를 더 늘릴 수 있는 방법이 있는지 문의드립니다.

만약 그게 안된다면 추후 제외 키워드관련 기능을 추가할 계획이 있는지도 같이 문의드립니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요 검색광고 API 입니다.

> 그런데 이 갯수를 더 늘릴 수 있는 방법이 있는지 문의드립니다.
- 현재 개수를 늘릴 수 있는 방법은 없습니다.
>만약 그게 안된다면 추후 제외 키워드관련 기능을 추가할 계획이 있는지도 같이 문의드립니다.
- 본 채널은 API 문의 채널로써, 해당 문의는 검색광고 고객센터를 통해 문의 부탁드립니다.

감사합니다.
