### ISSUE TITLE
adgroup에서 keyword 이외의 stats만 받을 수 없나요?

### ISSUE THREAD

**Issue by qlee3** [naver/searchad-apidoc#1023]
![스크린샷 2024-10-25 오전 10 28 43](https://github.com/user-attachments/assets/d57497fb-2c2a-4e6b-84ee-c7895a2d8051)

해당 데이터에 대한 stats를 받고 싶습니다.
adgroup id로 stats api를 요청하면 전체 값은 나오지만, 키워드 - 로 표기된 다차원 보고서의 데이터만을 정확하게 받을 수 없습니다

**Comment by naver-searchad** [comment]
안녕하세요 검색광고 API입니다.

원하시는 사양으로만 데이터를 내려받기는 어렵습니다.
데이터를 내려받은 후 원하시는 내용으로 가공하셔야 할 것 같습니다. 

감사합니다.
