### ISSUE TITLE
안녕하세요 네이버 검색광고 소재 순위별 입찰가 문의 드립니다

### ISSUE THREAD

**Issue by Guwon** [naver/searchad-apidoc#1024]
혹시 API로 소재의 네이버측에서 추천해주는 순위별 입찰가(pc1 ~ mobile 4위)를 가져올 수 있는 API가 있을까요?

**Comment by naver-searchad** [comment]
안녕하세요 검색광고 API

API로 순위별 입찰가는 제공하고 있지 않습니다.
감사합니다
