### ISSUE TITLE
stat-reports의 get 문의 드립니다. 

### ISSUE THREAD

**Issue by jaejunglimdata** [naver/searchad-apidoc#1025]
uri = '/stat-reports/'
method = 'GET'

r = requests.get(BASE_URL + uri, params={'reportJobId':job_id}, #jobid는 POST로 발급받은 ID 입니다.
                 headers=get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID))

안녕하세요, 담당자님.
stat-reports에서 위와 같이 params를 입력했음에도 불구하고 reportJobId에 대한 리스트가 나오는 것이 아니라 전체 리스트가 출력됩니다.
(stat-reports의 list와 같은 형식)
혹시 위와 같은 오류가 접수된 적이 있을까요?  아니면 params 부분에 문제가 있을까요? 답변 부탁드리겠습니다.

**Comment by searchad-api-customer-service** [comment]
안녕하세요. 네이버 검색광고 API입니다.

문의주신 것처럼 특정 jobId를 전달하시려는 경우에는 pathVariable 형태를 사용하셔야 합니다.

`BASE_URL + uri + {reportJobId}`

- https://naver.github.io/searchad-apidoc/#/operations/GET/~2Fstat-reports~2F%7BreportJobId%7D

<br/>

감사합니다.
