### ISSUE TITLE
리소스에 접근할 권한이 없습니다.

### ISSUE THREAD

**Issue by uneedDO** [naver/searchad-apidoc#1026]
<img width="1367" alt="스크린샷 2024-11-01 오전 10 39 52" src="https://github.com/user-attachments/assets/4813c3ee-0aeb-43a0-bf13-7647ec791c8e">
안녕하세요 광고관리자 권한을 받고 해당 광고 소재를 검색하면 위 화면과 같이 리소스에 접근할 권한이 없다고 뜨는데 어떤 권한이 빠진걸까요?
<img width="820" alt="스크린샷 2024-11-01 오전 10 40 51" src="https://github.com/user-attachments/assets/8a66cb09-e5a5-4c13-8449-583009f78951">

**Comment by searchad-api-customer-service** [comment]
@uneedDO 안녕하세요. 검색광고 API 담당자 입니다. 

여기에서는 검색광고 API 에서만 답변을 드리고 있어서 광고주센터에 대한 문의는 검색광고 고객센터로 문의 부탁드리겠습니다. ( https://saedu.naver.com/help/faq/ncc/index.naver )

문의 주신 내역에 대한 부분만 간략하게 답변 드리면 삭제된 소재에 대해서 접근을 하려고 하셔서 오류가 발생한것으로 확인됩니다.

감사합니다.
