### ISSUE TITLE
네이버 검색광고 API 키워드 성과 데이터 확장 검색 데이터 추출 문의

### ISSUE THREAD

**Issue by jeffjeong06** [naver/searchad-apidoc#1028]
2024년 10월 10일에 확장검색이 새로 나온걸로 알고 있는데,
현재 사용하고 있는 reportTp 에서 AD 에는 확장검색 데이터가 미집계 되어 추출되고 있는데,

혹시 확장 검색은 아직 API로 구현이 되지 않은 부분인가요?

아니면 이미 구현되어있다면 어디에서 추출가능한지 궁금합니다.

**Comment by naver-searchad** [comment]
안녕하세요 검색광고 API입니다.

파워링크 검색어 보고서(EXPKEYWORD) 에서 search keyword type을 통해 구분하여 확인이 가능합니다.
(일치/확장/유사)

감사합니다.
