### ISSUE TITLE
Invalid Signature 오류 관련 문의

### ISSUE THREAD

**Issue by ljtwo33800** [naver/searchad-apidoc#1029]
안녕하세요, 네이버 검색광고 API를 사용하여 캠페인 데이터를 조회하려고 하는데, Invalid Signature 오류가 발생하고 있습니다.

아래는 제가 사용하고 있는 코드입니다:

import requests
import time
import hmac
import hashlib
import base64

# 네이버 검색광고 API 엔드포인트 URL
url = "https://api.naver.com/ncc/campaigns"

# Access License와 Secret Key
access_license = "YOUR_ACCESS_LICENSE"
secret_key = "YOUR_SECRET_KEY"

# 현재 시각을 밀리초 단위로 생성
timestamp = str(int(time.time() * 1000))

# "timestamp.access_license" 형식으로 message 생성
message = f"{timestamp}.{access_license}"

# Secret Key를 Base64로 디코딩하여 바이트 형태로 변환
decoded_secret_key = base64.b64decode(secret_key)

# HMAC-SHA256으로 X-Signature 생성
signature = hmac.new(decoded_secret_key, message.encode('utf-8'), hashlib.sha256).hexdigest()

# 요청 헤더 설정
headers = {
    "X-API-KEY": access_license,
    "X-Timestamp": timestamp,
    "X-Signature": signature
}

# GET 요청을 통해 캠페인 데이터 조회
response = requests.get(url, headers=headers)

# 응답 확인
if response.status_code == 200:
    print("API Response:", response.json())  # 성공 시 응답 데이터 출력
else:
    print("API Call Failed:", response.status_code, response.text)  # 실패 시 에러 메시지 출력
문제 설명
위와 같은 방식으로 서명을 생성하였으나, 여전히 Invalid Signature 오류가 발생하고 있습니다.

혹시 서명 생성 과정에서 누락된 점이나, 추가적으로 확인해야 할 사항이 있는지 안내 부탁드립니다.

감사합니다.

**Comment by searchad-api-customer-service** [comment]
안녕하세요. 네이버 검색광고 API 입니다.

signature를 아래 형태로 생성하시고 재시도를 부탁드립니다.

`API_SECRET, unix epoch (milliseconds) + "." + http method + "." + request uri`

ex) 1457082455307.GET./ncc/campaigns
- https://naver.github.io/searchad-apidoc/#/samples

<br/>

감사합니다.

**Comment by ljtwo33800** [comment]
현재 API 호출을 시도할 때   "Invalid Signature" 오류가 발생하고 있습니다.
--
 
제가 작성한 Python 코드에서 HMAC 서명을 생성하여 API를   호출하고 있습니다. 서명을 생성하는 과정에서 올바른 타임스탬프와 요청 URI를 포함하고 있습니다. 그럼에도 불구하고   "Invalid Signature" 오류가 지속적으로 발생하고 있습니다.
 
아래는 요청 시 출력되는 정보입니다:
- **Timestamp:** [여기에 출력된 타임스탬프 값 입력]
- **Message:** [여기에 생성된 메시지 입력]
- **Signature:** [여기에 생성된 서명 입력]
- **요청 URL:**   https://api.naver.com/ncc/campaigns/grp-a001-02-000000027324225
- **HTTP 메서드:** GET
 
서명 생성에 사용한 코드:
```python
import requests
import time
import hmac
import hashlib
import base64
 
# 네이버 검색광고 API 엔드포인트 URL
url =   "https://api.naver.com/ncc/campaigns/grp-a001-02-000000027324225"
 
# 발급받은 Access License와 Secret Key
access_license = "네이버 검색광고 api   엑세스라이선스"
secret_key = "시크릿 키"
 
# 현재 시각을 밀리초 단위로 생성
timestamp = str(int(time.time() * 1000))
 
# 요청 URI와 메시지 생성
http_method = "GET"
request_uri =   "/ncc/campaigns/grp-a001-02-000000027324225"
message =   f"{timestamp}.{http_method}.{request_uri}"
 
# HMAC-SHA256 서명 생성
decoded_secret_key =   base64.b64decode(secret_key)
signature = hmac.new(decoded_secret_key,   message.encode('utf-8'), hashlib.sha256).hexdigest()
 
# 요청 헤더 설정
headers = {
"X-API-KEY": access_license,
"X-Timestamp": timestamp,
"X-Signature": signature,
"X-Customer": "2341275"
}
 
# 서명과 메시지 출력
print("Timestamp:", timestamp)
print("Message:", message)
print("Signature:", signature)
 
# API 요청
response = requests.get(url,   headers=headers)
 
if response.status_code == 200:
print("API Response:", response.json())
else:
print("API Call Failed:", response.status_code,   response.text)
```
 
문제가 발생하는 원인과 해결 방법에 대해 안내해 주시면 감사하겠습니다.   혹시 추가로 필요한 정보가 있다면 말씀해 주세요.
 
감사합니다.



> 안녕하세요. 네이버 검색광고 API입니다.
> 
> 서명을 작성해 주셔서 재시도를 부탁드립니다.
> 
> `API_SECRET, unix epoch (milliseconds) + "." + http method + "." + request uri`
> 
> 예) 1457082455307.GET./ncc/campaigns
> 
> * https://naver.github.io/searchad-apidoc/#/samples
> 
> 
> 감사합니다.

**Comment by ljtwo33800** [comment]
현재 API 호출을 시도할 때   "Invalid Signature" 오류가 발생하고 있습니다.
 
제가 작성한 Python 코드에서 HMAC 서명을 생성하여 API를   호출하고 있습니다. 서명을 생성하는 과정에서 올바른 타임스탬프와 요청 URI를 포함하고 있습니다. 그럼에도 불구하고   "Invalid Signature" 오류가 지속적으로 발생하고 있습니다.
 
아래는 요청 시 출력되는 정보입니다:
- **Timestamp:** [여기에 출력된 타임스탬프 값 입력]
- **Message:** [여기에 생성된 메시지 입력]
- **Signature:** [여기에 생성된 서명 입력]
- **요청 URL:**   https://api.naver.com/ncc/campaigns/grp-a001-02-000000027324225
- **HTTP 메서드:** GET
 
서명 생성에 사용한 코드:
```python
import requests
import time
import hmac
import hashlib
import base64
 
# 네이버 검색광고 API 엔드포인트 URL
url =   "https://api.naver.com/ncc/campaigns/grp-a001-02-000000027324225"
 
# 발급받은 Access License와 Secret Key
access_license = "네이버 검색광고 api   엑세스라이선스"
secret_key = "시크릿 키"
 
# 현재 시각을 밀리초 단위로 생성
timestamp = str(int(time.time() * 1000))
 
# 요청 URI와 메시지 생성
http_method = "GET"
request_uri =   "/ncc/campaigns/grp-a001-02-000000027324225"
message =   f"{timestamp}.{http_method}.{request_uri}"
 
# HMAC-SHA256 서명 생성
decoded_secret_key =   base64.b64decode(secret_key)
signature = hmac.new(decoded_secret_key,   message.encode('utf-8'), hashlib.sha256).hexdigest()
 
# 요청 헤더 설정
headers = {
"X-API-KEY": access_license,
"X-Timestamp": timestamp,
"X-Signature": signature,
"X-Customer": "2341275"
}
 
# 서명과 메시지 출력
print("Timestamp:", timestamp)
print("Message:", message)
print("Signature:", signature)
 
# API 요청
response = requests.get(url,   headers=headers)
 
if response.status_code == 200:
print("API Response:", response.json())
else:
print("API Call Failed:", response.status_code,   response.text)
```
 
문제가 발생하는 원인과 해결 방법에 대해 안내해 주시면 감사하겠습니다.   혹시 추가로 필요한 정보가 있다면 말씀해 주세요.
 
감사합니다.

**Comment by ljtwo33800** [comment]
현재 API 호출을 시도할 때 "Invalid Signature" 오류가 발생하고 있습니다.

아래는 요청 시 출력되는 정보입니다:

Timestamp: [여기에 출력된 타임스탬프 값 입력]
Message: [여기에 생성된 메시지 입력]
Signature: [여기에 생성된 서명 입력]
요청 URL: https://api.naver.com/ncc/campaigns/cmp-a001-02-000000005281644
HTTP 메서드: GET
서명 생성에 사용한 코드:

import requests
import time
import hmac
import hashlib
import base64

# API 엔드포인트 URL
url = "https://api.naver.com"
request_uri = "/ncc/campaigns/cmp-a001-02-000000005281644"
access_license = "01000000001bcb449979a451e8d475d8d70dd1572910a04726ac84e42bdd1144b1441059f3"
secret_key = "AQAAAAAby0SZeaRR6NR12NcN0Vcp0lozwE81nXGypaObbJ5Trg=="

# 현재 시각을 밀리초 단위로 생성
timestamp = str(int(time.time() * 1000))
http_method = "GET"

# HMAC 서명 메시지 생성
message = f"{timestamp}.{http_method}.{request_uri}"

# HMAC-SHA256 서명 생성
decoded_secret_key = base64.b64decode(secret_key)
signature = base64.b64encode(hmac.new(decoded_secret_key, message.encode('utf-8'), hashlib.sha256).digest()).decode('utf-8')

# 요청 헤더 설정
headers = {
    "X-API-KEY": access_license,
    "X-Timestamp": timestamp,
    "X-Signature": signature,
    "X-Customer": "2341275"
}

# API 요청
response = requests.get(url + request_uri, headers=headers)

if response.status_code == 200:
    print("API Response:", response.json())
else:
    print("API Call Failed:", response.status_code, response.text)


서명 생성 과정에서 올바른 타임스탬프와 요청 URI를 포함하고 있음에도 불구하고 여전히 "Invalid Signature" 오류가 발생하고 있습니다. 문제의 원인과 해결 방법에 대한 안내를 부탁드립니다. 추가로 필요한 정보가 있다면 말씀해 주세요

**Comment by searchad-api-customer-service** [comment]
안녕하세요.

우선 signatue 생성 오류와 관련하여 가장 마지막 회신 주신 코드에서 signature 생성 부분을 아래처럼 수정하신 후
Invalid Signature 오류가 발생하지 않는지 확인 부탁드립니다.
- 참고: https://github.com/naver/searchad-apidoc/blob/master/python-sample/examples/signaturehelper.py#L9-L14

```
# 현재 사용 중이신 형태
decoded_secret_key = base64.b64decode(secret_key)
signature = base64.b64encode(hmac.new(decoded_secret_key, message.encode('utf-8'), hashlib.sha256).digest()).decode('utf-8')
```

```
# 아래처럼 변경
# 지금 코드에서 사용 중이신 decoded_secret_key 사용 X
signature = base64.b64encode(hmac.new(secret_key.encode('utf-8'), message.encode('utf-8'), hashlib.sha256).digest())
```

이 상태에서도 동작이 안되는 경우에는 우선 `request_uri = "/ncc/campaigns/"` 형태까지만 사용해보신 후 이 상태에서도 Invalid Signature 오류가 발생하는지 확인 부탁드립니다.



감사합니다.
