### ISSUE TITLE
Naver Search Ad API 파라메터적용을 어떻게 하나요?

### ISSUE THREAD

**Issue by feeris** [naver/searchad-apidoc#103]
안녕하세요. 
Naver Search Ad API를 PHP로 구현해보려 하는데요 
API 적용을 어떻게 해야 할 지 파라미터가 잘 이해되지 않아서요.
GET /ncc/ad-extensions{?ids} => {?ids} 이건 PHP로 어떻게 표현을 하는건지?
GET /ncc/adgroups/{adgroupId} =>  {adgroupId} 이건 PHP로 어떻게 표현을 하는건지?

list, get 차이? 용도? 적용 상황 등을 설명해주면 좋겠습니다.

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

단순히 답변을 드릴 수 있는 사항은 아닌듯 싶습니다. 
아래 주소에서 PHP 샘플 코드를 받운받으실 수 있사오니 샘플 코드를 참고하시면 
도움이 되실 것으로 생각 됩니다.
https://github.com/naver/searchad-apidoc/tree/master/php-sample

추가로 
저희 검색광고시스템도 동일한 API를 이용해서 작성되어 있으므로 
브라우져의 개발자 도구을 여시고 네트워크 통신 내역(크롬의 경우 F12-> 네트워크탭)을 보시면 REST 호출 인자의 형태와 용례를 를 확인하시는데 도움이 되실 것으로 생각 됩니다.

두번째로 저희가 가이드 상 LIST로 표현한 경우는 리턴값 항목들이 여러개인 경우이고 GET으로 표현한 경우는 1개 항목만 조회할때를 의미 합니다. 간단히 말씀 드리면 

예를 들어 
Adgroup GET 즉  /ncc/adgroups/{adgroupId}은 한개 광고 그룹의 아이디를 인풋으로 넣어 
그 광고 그룹의 정보만을 조회하는 기능이며, 
Adgroup: list (by campaign id)  즉 GET /ncc/adgroups{?nccCampaignId,baseSearchId,recordSize,selector}는 특정 캠페인 아이디를 입력해서 그 캠페인에 속한 모든 광고 그룹 리스트를 조회 하는 기능입니다.

감사합니다.
