### ISSUE TITLE
AD_DETAIL Stat 리포트의 click 합계가 웹에서 확인한 것과 다릅니다.

### ISSUE THREAD

**Issue by donghwan-ahn** [naver/searchad-apidoc#1030]
- customer_id: 2384006
- campaign_id: cmp-a001-01-000000005433140
- ad_group_id: grp-a001-01-000000045227441
- ad_id: nad-a001-01-000000323457613
- 조회 일자: 2024-11-07

위의 정보에 해당하는 광고에 대한 성과를 확인하면, 웹(manage.searchad.naver.com)에서는 클릭수가 80이 나오는데, AD_DETAIL stat report API로 조회하면 79가 나옵니다.

조금 더 상세하게 확인하면 22시~23시의 클릭수가 웹에서는 5, API는 4로 나옵니다.

왜 이런 차이가 발생하는지 알고 싶습니다.
감사합니다.

<img width="1579" alt="image" src="https://github.com/user-attachments/assets/32c4099f-8c01-4f4c-be17-497e3f1f760c">

<img width="824" alt="image" src="https://github.com/user-attachments/assets/e53456f7-e5f0-45ee-95d4-cbecfb4a391a">

**Comment by naver-searchad** [comment]
안녕하세요 검색광고 API 입니다.

대용량 다운로드 API 에서는 view_count 라는 항목이 존재합니다.

광고 관리화면에서의 클릭수는 모든 클릭수와 동영상 재생수를 합산하여 제공하고 있고
대용량 다운로드 보고서에서는 클릭수와 동영상 재생수를 분리하여 제공하고 있습니다.

따라서 웹에서의 clicks는 
stat report의 click과 view count를 합산한 것과 일치하게 됩니다.

감사합니다

**Comment by donghwan-ahn** [comment]
빠른 답변 감사합니다.
