### ISSUE TITLE
네이버플러스 media_code 문의

### ISSUE THREAD

**Issue by githubcnsbs** [naver/searchad-apidoc#1031]
안녕하세요, 

네이버플러스의 media_code를 알고 싶습니다. 

 - 네이버 검색광고시스템 화면에서 광고그룹 생성/수정화면 > ‘매체’ > 매체리스트 다운로드
로는 네이버플러스가 나오지 않는데, 

POST /stat-reports API의 AD_DETAIL 호출시 return되는 media_code에서 네이버플러스 코드를 확인할 수 있는 경로가 있는지 문의 드립니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요 검색광고 API 입니다.

- 다운로드 받으신 '매체리스트'는 파워링크 그룹에서 다운로드 받으셨을것으로 추측됩니다 ( 쇼핑검색은 제공 X)
- 네이버플러스는 쇼핑검색에서만 노출되는 media로 입니다.
- 원하시는 정보는 대용량 다운로드 보고서 > 광고 정보 일괄 다운로드 > 광고 매체 마스터 를 통해 확인 가능합니다.

감사합니다

**Comment by githubcnsbs** [comment]
네, 감사합니다.
