### ISSUE TITLE
네이버 검색 광고 캠페인별 실시간 당일 소진 비용 관련 문의 

### ISSUE THREAD

**Issue by passionful7** [naver/searchad-apidoc#1032]
안녕하세요. 현재 네이버 검색 광고에서 캠페인별 실시간 당일 소진 비용을 API를 통해 확인하고자 합니다.

비즈머니 API를 통해 계정 전체의 실시간 당일 소진 비용은 확인할 수 있지만, 캠페인별 실시간 당일 소진 비용은 확인이 어렵습니다.
Stats 등 다른 API들은 4시간 전 데이터만 제공되는 것으로 보이는데, 

캠페인별 실시간 당일 소진 비용을 API로 확보할 수 있는 방법이 있을까요?

**Comment by naver-searchad** [comment]
안녕하세요 검색광고 API 입니다.

안녕하세요 캠페인별 실시간 당일 소진비용은 제공하지 않고 있습니다.
다만, 캠페인별 '전일' 소진금액은 stat-report에서 cost라는 항목으로 제공하고 있으며 
필요하신 형식에 맞춰 사용하시면 될 것 같습니다.

감사합니다 !
