### ISSUE TITLE
네이버 쇼핑에 등록된 상품 목록을 가져오는 API는 없을까요?

### ISSUE THREAD

**Issue by nitmus-lab-jack** [naver/searchad-apidoc#1033]
안녕하세요 상품목록 연동 관련해서 문의드릴께 있습니다.

상품 DB URL을 통해 등록된 쇼핑파트너센터의 상품 목록을 가져올 수 있는 API가 있을까요?

아니면 쇼핑몰 상품ID로 네이버 쇼핑 상품ID를 조회 할 수 있는 방법이 있는지 문의드립니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

쇼핑의 상품목록을 조회하는 API는 검색광고에서 제공하고 있지 않습니다.

감사합니다.
