### ISSUE TITLE
COST api 문의

### ISSUE THREAD

**Issue by h-julie** [naver/searchad-apidoc#1035]
네이버 검색광고의 cost을 mixpanel로 가져오려고 합니다. 어떤 api를 사용해야 네이버 검색광고 cost(또는 spending)을 가져올 수 있나요? 
https://naver.github.io/searchad-apidoc/#/tags/AdKeyword

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

비즈머니는 아래 API를 이용하여 조회하실 수 있습니다.
https://naver.github.io/searchad-apidoc/#/operations/GET/~2Fbilling~2Fbizmoney~2Fhistories~2Fperiod%7B%3FsearchStartDt,searchEndDt%7D

응답값중 useNonRefundableAmt 와 useRefundableAmt 를 합한 값이 소진액입니다.

감사합니다.
