### ISSUE TITLE
쇼핑 소재 statusReason 문의

### ISSUE THREAD

**Issue by kwak82721** [naver/searchad-apidoc#1036]
안녕하세요, 

쇼핑소재조회에서 확인하는 statusReason 중 AD_ABNORMAL_INTERLOCK코드값은
네이버 광고 콘솔에서의 노출제한, 연동제한 모두 포함하는 것인지 연동제한만 포함하는 것인지 궁금합니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API 입니다.
AD_ABNORMAL_INTERLOCK은 연동 제한이 맞습니다. 하지만, StatusReason이 연동 제한이 되는 경우 Status 값이 PAUSED가 되기 때문에 광고 노출도 중지가 됩니다. 

광고 노출가능 여부는 status 로 확인하시고, 노출이 중지된 사유를 statusReason으로 확인하실수 있습니다.

감사합니다.
