### ISSUE TITLE
파워링크 iOS/Android 구분할 수 있는 API가 있나요?

### ISSUE THREAD

**Issue by h-julie** [naver/searchad-apidoc#1037]
파워링크 성과를 operating system별로 구분해서 보려고 하는데 api중에 사용 가능한 api가 있을까요?

**Comment by naver-searchad** [comment]
안녕하세요 검색광고 API입니다.

모바일/PC 외 별도 OS를 구분할 수 있는 api는 없습니다.
감사합니다
