### ISSUE TITLE
PHP 샘플 코드 오류

### ISSUE THREAD

**Issue by natz92** [naver/searchad-apidoc#104]
restapi 에 DOWNLOAD 함수
$fp = fopen($localpath, "w"); 에서
fopen(AD_DETAIL-20180326.tsv): failed to open stream: Permission denied 이 발생합니다.

**Comment by natz92** [comment]
확인해보니 샘플 소스엔 date format을 Ymd로 지정하셨는데,
실제론 ISO-8601 형식에 맞춰야 하는것 같습니다.

**Comment by naver-searchad** [comment]
안녕하셔요 검새광고 API 입니다. 

$fp = fopen($localpath, "w"); 에서
fopen("AD_DETAIL-20180326.tsv:"):

위와 같은 식으로 파일명을 따움표로 묶어서 처리해 보시기 바랍니다. 

감사합니다.
