### ISSUE TITLE
마스터 리포트 변경분 (fromTime) 데이터에 대한 문의

### ISSUE THREAD

**Issue by leeyoseph-dev** [naver/searchad-apidoc#1041]
안녕하세요.

문의 사항이 있습니다.

리포트 타입이 SHOPPINGKEYWORD_CONVERSION_DETAIL 인 statReport를 호출했는데요.
아래와 같은 데이터를 얻어 올 수 있었습니다.

Campaign ID : cmp-a001-02-000000004108763
AD Group ID  : grp-a001-02-000000027266745
AD ID : nad-a001-02-000000184943895

그리고 Campaign, Adgroup, ShoppingProduct 마스터  리포트 / 마스터 리포트 변경분을 호출 했습니다. 
이때 fromTime을 22년 11월 29일로 잡았습니다.

조회된 마스터 리포트 변경분 데이터를 확인 해 봤는데

1.  Adgroup 마스터 변경분 데이터 중에 위의 광고그룹 아이디가 22년 6월 28일에 삭제되었다고 나오는데 fromTime 보다 이전 시점에 발생 했던 일이 조회가 가능 한가요?

2.  AD ID 로 ShoppingProduct 의 마스터 리포트 / 마스터 변경분 리포트의 일치하는 값을 찾아봤는제 존재 하지 않습니다.
 광고그룹이 삭제가 되었기 떄문일까요?

**Comment by naver-searchad** [comment]
안녕하세요 검색광고 API 입니다.

> Adgroup 마스터 변경분 데이터 중에 위의 광고그룹 아이디가 22년 6월 28일에 삭제되었다고 나오는데 fromTime 보다 이전 시점에 발생 했던 일이 조회가 가능 한가요?
- 원래는 fromtime 이전 시점에 발생했던 변경분의 조회는 되지 않아야 맞는 스펙입니다, 
다만 광고 플랫폼의 신규 기능 및 추가 개선작업이 진행되는 경우 삭제된 광고에도 변경 시간에 영향을 끼친것으로 보여집니다.
업무에 불편을 끼쳐드려 대단히 죄송합니다.
>AD ID 로 ShoppingProduct 의 마스터 리포트 / 마스터 변경분 리포트의 일치하는 값을 찾아봤는제 존재 하지 않습니다.
광고그룹이 삭제가 되었기 떄문일까요?
- 네 맞습니다, 마스터리포트 기준 fromtime 기준 이전으로 삭제가 되었기 때문으로 보여집니다.

감사합니다

**Comment by leeyoseph-dev** [comment]
안녕하세요. 
답변 감사합니다.

추가적으로 문의 드릴게 있습니다.
삭제된 AD ID 인   nad-a001-02-000000184943895 에 대해서
광고관리 시스템(UI)의 다차원 보고서에는 전환이 잡히는데 사유를 확인 가능 할까요?
2024년 11월 26일 기준 입니다.

**Comment by naver-searchad** [comment]
안녕하세요 검색광고 API 입니다.

이곳은 API 관련 기술 문의를 하는 곳으로 각 기능별 담당 개발자 분들이 답변을 드리고 있습니다.
따라서, 해당 문의는 검색광고 운영자가 담당할 수 있도록 검색광고 고객센터 (고객센터 : https://saedu.naver.com/help/faq/ncc/index.naver#)
혹은 대행사 사용중이시라면 공식채널을 통해 문의 부탁드리겠습니다.

감사합니다.
