### ISSUE TITLE
keywordstool 키워드 띄어쓰기

### ISSUE THREAD

**Issue by kiyoung-choi** [naver/searchad-apidoc#1043]
https://api.searchad.naver.com/keywordstool 해당 API 통신중에 hintKeywords에 값이 띄어쓰기가 있으면
"There are invalid parameters" 해당 오류가 발생합니다. 띄어쓰기는 사용이 불가능한걸까요?

Array ( [title] => Invalid Parameter [status] => BAD_REQUEST [detail] => There are invalid parameters [type] => about:blank [parameters] => Array ( ) [instance] => )

**Comment by searchad-api-customer-service** [comment]
안녕하세요. 네이버 검색광고 API 입니다.

문의주신 API와 parameter 중에서 `hintKeywords` 값에 공백(whitespace)이 하나라도 포함되어 있으면 Invalid Parameter 오류가 발생하며 띄어쓰기는 사용이 불가능한 것이 맞습니다.

감사합니다.
