### ISSUE TITLE
현재 접속이 안되는것 같습니다.

### ISSUE THREAD

**Issue by kaorimikage** [naver/searchad-apidoc#105]
sign = 1522207402823.GET./ncc/campaigns Http Status : 503

캠페인 정보를 취득하려고 하는데 503 에러가 뜹니다.

**Comment by naver-searchad** [comment]
안녕하세요. 검색광고API입니다.
오전에 잠시 접속에 문제가 있었습니다.
업무에 불편을 드려서 대단히 죄송합니다.
현재 정상화 되었이니 확인 부탁드립니다.
