### ISSUE TITLE
ShoppingProduct 정보 조회 시 stat와 master report 차이

### ISSUE THREAD

**Issue by ROSETTA-LEE** [naver/searchad-apidoc#1051]
안녕하세요.
ShoppingProduct 데이터를 stat api로 조회 시에는 productTitle이 확인되나,
master api 로 다운로드 받은 보고서에서는 확인되지 않는 케이스가 있어 확인 요청 드립니다.

JobID : 7c97f02a3ae3eac1a2797e5265099601
ADID : nad-a001-02-000000335254448

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요 검색광고 API입니다.

쇼핑 정보를 업데이트 하거나, 내부 대량 처리 등 쇼핑 정보를 대량으로 처리하는 과정과 마스터 리포트 생성의 시점이 우연히 겹치는 경우 데이터를 읽어 오는데 실패할 수 있습니다.
이 패턴은 특정한 패턴 없이 불규칙 적으로 발생하는데

현재 확인하였을 때는 ,별도 누락된 정보 없이 마스터 파일의 생성이 가능한ㅍ\것으로 보여집니다.
혹시 신규로 생성하여 다시 재확인해 주실 수 있으실까요?

**Comment by ROSETTA-LEE** [comment]
재생성하여 같은 ADID로 조회 시 productIdofMall, productName 등 이 여전히 나오지 않습니다ㅠ

![image](https://github.com/user-attachments/assets/40b3d3be-fca7-4f0c-904b-fe2e363136b3)

**Comment by ROSETTA-LEE** [comment]
정상 확인됩니다. 감사합니다!
