### ISSUE TITLE
키워드의 view url을 가져오고 싶습니다.

### ISSUE THREAD

**Issue by natz92** [naver/searchad-apidoc#106]
api 문서에서 view url, Linked url 을 찾지 못했는데,

모바일/데스크탑 4개의 키워드 URL을 가져올 수 있는 방법이 없을까요?

**Comment by naver-searchad** [comment]
안녕하십니까..검색광고 API입니다. 

우선 viewURL은 광고 그룹 조회(http://naver.github.io/searchad-apidoc/#/operations/GET/~2Fncc~2Fadgroups~2F%7BadgroupId%7D) 시 리턴되는 값중 
mobileChannelId : 모바일 비즈채널 아이디, pcChannelId: PC 비즈채널 아이디
값을 인자로 비지니스 채널을 조회 하셨을때 리턴되는 값중 채널키(channelKey) 혹은 채널 정보( businessInfo) 항목에서 확인 하실 수 있습니다. 
(http://naver.github.io/searchad-apidoc/#/tags/BusinessChannel)

계정 단위 일괄조회를 원하시면 마스터리포트(http://naver.github.io/searchad-apidoc/#/tags/MasterReport) 의 

Business Channel (BusinessChannel), Ad group (Adgroup) 두개 파일을 받으시어 
AD GROUP의 Business Channel Id(Mobile), Business Channel Id(PC) 필드와 비지니스채널의 Business Channel Id 필드를 조인 하시면 되겠습니다. 

링크 URL은 

1) 키워드별 링크 URL의 경우 
ADKeyword 오퍼레이션(http://naver.github.io/searchad-apidoc/#/operations/GET/~2Fncc~2Fkeywords~2F%7BnccKeywordId%7D)조회에서 links 필드를 
조회 하시거나 마스터 리포트>Ad Keyword (Keyword)의 landing URL(PC), landing URL(Mobile)을 조회 하시면 됩니다. 

2) 소재에 설정된 랜딩 URL은 
AD 오퍼레이션(http://naver.github.io/searchad-apidoc/#/operations/GET/~2Fncc~2Fads~2F%7BadId%7D)의 리턴값 중 AD 필드를 조회 하시거나 
마스터 리포트>Creative (Ad) 중 Landing URL(PC) , Landing URL(Mobile)을 조회 하시면 되겠습니다.

감사합니다.

**Comment by natz92** [comment]
감사합니다.
