### ISSUE TITLE
오늘따라 응답속도가 많이 늦는것 같습니다.

### ISSUE THREAD

**Issue by kaorimikage** [naver/searchad-apidoc#107]
오전 09:20분경부터 API 응답속도가 상당히 느려진것 같습니다. API 서버에 이상이 있는것인지요?

**Comment by kaorimikage** [comment]
sign = 1524617283262.GET./billing/bizmoney
현재 응답속도가 너무 늦습니다.

**Comment by kaorimikage** [comment]
sign = 1524618394663.GET./billing/bizmoney
응답완료까지 평균 14초를 넘어가고 있습니다.

**Comment by kaorimikage** [comment]
sign = 1524621461550.GET./billing/bizmoney Http Status : 200 Array ( [customerId] => 618481 [bizmoney] => 275031 [budgetLock] => [refundLock] => ) 
12.958991050720214844초 걸림

**Comment by naver-searchad** [comment]
안녕하셔요 검색광고 API입니다. 

리턴된 메세지 헤더에 있는 x-transaction-id 값을 알려 주시겠습니까?

현재 전체적인 평균응답 속도는 50ms 이하라 특정 기간이나 특정 계정에 관련 된 문제일 가능성이 있어서 호출 이력을 찾고 있는데요. 워낙 많다보니 주신 정보만으로 찾기에는 시간이 한참 걸리듯 싶네요. 

감사합니다.

**Comment by kaorimikage** [comment]
sign = 1524624678082.GET./billing/bizmoney Http Status : 200 Transaction-ID : B2VAR63VPP60A Array ( [customerId] => 618481 [bizmoney] => 270862 [budgetLock] => [refundLock] => ) 
15.968088150024414062초 걸림

**Comment by kaorimikage** [comment]
sign = 1524624775207.GET./billing/bizmoney Http Status : 200 Transaction-ID : B2VARTQQ1P69C Array ( [customerId] => 618481 [bizmoney] => 270862 [budgetLock] => [refundLock] => ) 
20.028519868850708008초 걸림

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

자료 감사드립니다. 

우선 말씀 주신 내용 찾는 과정에서 문제가 있는 장비가 발견 되어 조치를 했습니다만.
이 현상의 원인이라고 100% 확신할수는 없어 추가 조사 진행 중입니다. 짧아도 하루 정도는 소요될 것으로 보입니다. 불편을 드려 죄송합니다. 

감사합니다.

**Comment by kaorimikage** [comment]
sign = 1524627101380.GET./billing/bizmoney Http Status : 200 Transaction-ID : B2VBDLOBHP7BE Array ( [customerId] => 618481 [bizmoney] => 264427 [budgetLock] => [refundLock] => ) 
12.681744098663330078초 걸림

장비에 조치를 하셨다 해서 혹시나해서 그 뒤에 느려지는 것에 대해 최근 자료를 다시 보내드립니다.

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

네 주신 것처럼 저희 조사로도 조치한 
장비와는 지연 현상이 무관하다는 사실이 최종 확인 되었습니다. 다른 각으로 조사를 확대하고 있습니다.
문제 발견 되는 대로 조치하겠습니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

중간 답변 드립니다. 

현재 느려지는 원인을 찾는 조사가 계속 진행 중입니다. 

전수 조사 결과 응답이 느린 케이스가 극히 드물게 발견 되는데 
타 호출과 비교해서 특이한 부분이 없어서 찾는데 조금 더 시간이 걸릴듯 싶습니다. 

불편을 드려 대단히 죄송하며 찾는대로 조치하고 다시 말씀 드리겠습니다. 

감사합니다.

**Comment by kaorimikage** [comment]
이후 진척은 아직 없으신것인지요?

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

저희 장비에서 간혈적 지연 되는 현상은 몇가지 해결책들을 적용하여 
결과적으로는 거의 해결이 된 상태이긴 합니다만..(여전히 원인을 찾지 못하여 이쪽 트랙도 조사가 
계속 되고 있긴 합니다.)

문의 주신 비즈머니 조회시 간혈적인 지연 건은 저희 게이트 웨이까지는 모든  콜에 대해 수십 밀리세컨드 내 응답으로 정상 속도를 보이고 있는 상황이라 게이트 웨이 이후 회선과 통신 경로에 대한 트래킹 및 조사를 진행하고 있습니다. 

그러나 불행히도 아직까지도 원인이나 해결책을 찾지는 못한 상황입니다. 

불편을 드려서 대단히 죄송하오며 저희 인프라 쪽 전문 인원들이 투입되어 조사를 진행하고 있는바 
이번달 말까지 최선을 다해 진행한 후 차월 초 결과나 대응책에 대해 말씀 드릴 수 있도록 하곘습니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

몇가지 추가 조치를 취하였는데요. 
혹 재발이된다면 이 이슈로 신고 부탁드립니다. 

트랜잭션 아이디와 호출 일시 말씀 주시면 되겠습니다.

감사합니다.
