### ISSUE TITLE
쇼핑검색 광고 등록 오류

### ISSUE THREAD

**Issue by ghost** [naver/searchad-apidoc#108]
http://naver.github.io/searchad-apidoc/#/operations/POST/~2Fncc~2Fads
와 공지 사항을 참고하여  제공해준 쇼핑검색 광고 등록을 위해 java 프로그램을 수정하여 테스트 중에 있습니다.

POST /ncc/ads
- isList=true 
- referenceKey=네이버상품코드 
- ad는 {}
- nccAdgroupId는 쇼핑 소재를 만들 해당 그룹ID
- type : SHOPPING_PRODUCT_AD
- userLock은 false로 세팅해서 request날렸습니다.

Ad 출력
-----------------------------------
{"nccAdId":null,"nccAdgroupId":"grp-a001-02-000000006747643","customerId":1374036,"inspectStatus":null,"type":"SHOPPING_PRODUCT_AD","ad":{},"userLock":false,"inspectRequestMsg":null,"referenceKey":"14116819660","adAttr":{"useGroupBidAmt":true,"bidAmt":50}}
// adAttr은 추가도 해보고 뺴보기도 했으나 오류가 납니다.

request&response 메시지
============ Request =============
POST /ncc/ads?isList=true HTTP/1.1
accept-encoding: gzip
Content-Type: application/json;charset=UTF-8
user-agent: unirest-java/1.3.11
X-Signature: 1DdQ7dljazipLKpZ0kaNPrzXFWZpjmxwrzBjbsTLT6M=
X-Timestamp: 1525360594196

============ Response ============
HTTP/1.1 400 Bad Request
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Connection: close
Cache-Control: no-store, must-revalidate
X-Transaction-ID: B34QB0BT1PCQH
Content-Type: application/json;charset=UTF-8
Date: Thu, 03 May 2018 15:19:15 GMT
Strict-Transport-Security: max-age=15768000

{"code":1028,"status":400,"title":"Invalid request message."}

문서상으로는 잘못 보낸게 없는것같은데 오류가 납니다. 
request를 잘못 보낸 부분이 어딘지요?

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

request param의 isList=true 면 1건을 전송하더라도 array list를 보내셔야 합니다.
1건만 전송하실 경우라면 request param을 제거하고 보내시면 됩니다.

시도해 보시고 안되시면 다시 코멘트 부탁들입니다. 

p.s 문의 주실때 Customer:,API-KEY와 Signature는 표기 하시지  않는 것이 좋습니다. 
리턴 메세지 헤더의 X-Transaction-ID 와 현상 만 알려 주시면 되겠습니다. 
이 게시판은 전체 공개 게시판으로 위의 정보가 공개될 경우 보안 위험이 있을 수 있습니다.
(큰 무리가 없으시다면 라이선스와 비밀키를 재발급 받으시는 것을 권장 드립니다.)

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 API입니다. 

제가 다른 질문과 질문 주신 내용을 혼돈하여 잘못 답변을 드렸습니다. 
다시 답변 드리겠습니다. 

혼란 드려 죄송합니다.

**Comment by koglp** [comment]
등록시에 list로 최대 몇개까지 한꺼번에 등록 가능한가요?
