### ISSUE TITLE
권한관련

### ISSUE THREAD

**Issue by buru21** [naver/searchad-apidoc#109]
안녕하세요.
campaign을 일시중지시키기 위해 update (userlock) 하려고 하는데
No permission to access the resource
라는 메시지가 뜨네요.
광고는 제 아이디로 관리하고 있는데 이런 경우 권한 제한이 있을 수 있나요?

[code] => 1018 [status] => 404 [title] => No permission to access the resource.

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

클로징 하신것으로 보아 해결이 되신듯 싶긴 합니다만 
참고하실 수 있도록 코멘트 남깁니다. 

해당 메세지는 권한이 없는 경우에도 리턴되지만 아이디를 잘못 기입하거나 삭제된 항목에 접근하려고 할때도 리턴됩니다.

감사합니다.

**Comment by buru21** [comment]
네 해결했습니다.
감사합니다.
