### ISSUE TITLE
keyword의 delete-items api 관련 문의 입니다.

### ISSUE THREAD

**Issue by younseunghyun** [naver/searchad-apidoc#11]
안녕하세요

`DELETE /ncc/keywords{?ids}`관련 문의 입니다.

위의 api를 사용하는데 있어서 예제를 따라하면, id를 ,를 구분자로 하여 value로 넣으면 되는 것으로 보입니다.

현재 예제의 사용법과 위의 path로 요청을 보내는 경우에 HttpResponseCode가 400이 오고 있습니다.

어떤식으로 사용을 해야 되는 것 인가요?

아래는 현재 요청에 관련된 내용입니다.

```
[main] DEBUG com.yx.stark.pubapi.naver.util.RestClient - ============ Request =============
[main] DEBUG com.yx.stark.pubapi.naver.util.RestClient - DELETE /ncc/keywords?ids=nkw-a001-01-000000046023699%2Cnkw-a001-01-000000046023700 HTTP/1.1

```

**Comment by naver-searchad** [comment]
안녕하세요~
검색광고 API입니다.
보내주실때 인코딩 되지 않은 콤마구분자(',')로 보내주시면 됩니다.
```
DELETE /ncc/keywords?ids=nkw-a001-01-000000046023699%2Cnkw-a001-01-000000046023700 HTTP/1.1
```
감사합니다.

**Comment by younseunghyun** [comment]
말씀하신 방법으로 진행하니 삭제가 되고 있습니다 :) 

감사합니다.
