### ISSUE TITLE
클릭하여 유입된 리퍼러값의 종류 질문

### ISSUE THREAD

**Issue by realholic** [naver/searchad-apidoc#111]
안녕하세요?
리퍼러값을 통해 파워링크인지 추적과 값에 적혀있는 n_rank 값을 기록해두고 순위를 벗어나면 입찰하라고 알람을 보내고 있는데요.

리퍼러 종류를 보니 파워링크 아닌것들도 있어서 그런지 종류가 많던데
NaPm값만 있는것도 있고 어떤건 n_rank 값이 없고 종류가 많던데
이런 종류별로 어디서 클릭이 되는건지 알수있는방법이 있는지 궁금합니다.
예를들면 여러종류가 있는데 종류가 어떻게 다양한지 몰라 눈에 보이는 몇개만 수집해서 적어봅니다만
아래 주소체계만 보셔도 파라미터들이 다 다른데 이런 기준이 뭔지좀 알고 싶습니다. 
설명좀 해주실 수 있을까요?

https://search.naver.com/search.naver?f=&fd=2&filetype=0&nso=so%3Ar%2Ca%3Aall%2Cp%3Aall&qdt=0&query=%EC%8A%A4%EB%A7%88%ED%8A%B8%EC%8A%A4%ED%85%9C%EC%85%80&qvt=0&research_url=&sm=tab_nmr&start=1&where=webkr

https://search.naver.com/search.naver?sm=tab_hty.top&where=nexearch&query=%ED%94%BC%EC%BD%94%EC%9B%A8%EC%9D%B4%EB%A0%88%EC%9D%B4%EC%A0%80&oquery=%EB%88%88%EC%8D%B9%EB%AC%B8%EC%8B%A0%EC%A7%80%EC%9A%B0%EA%B8%B0&tqi=TYcqespySDlssZuYvU4ssssssSN-191336

https://search.naver.com/search.naver?where=nexearch&sm=top_hty&fbm=0&ie=utf8&query=%EC%97%AC%EB%93%9C%EB%A6%84%ED%94%BC%EB%B6%80%EA%B3%BC

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API 입니다. 

네이버 서비스의 파라미터 스팩은 공개하지 않습니다. 
그러나 말씀 주신 것과 같이 광고 클릭 발생시 광고 정보를 확인하고자 하시는 경우를 위해 
추적  기능을 검색광고 서비스에서 정규 제공하고 있으므로 이 기능을 활용해 주시는 방법을 권장드립니다.

주의 하실 점은 추적 URL 기능 사용시 광고 랜딩 URL에 파라미터가 붙으므로 파라미터를 광고 사이트에서 처리할 수 있도록 조치해 주셔야 한다는 점입니다. (조치를 하지 않으시는 경우 광고 랜딩인 사이트가 올바르게 로딩 되지 않을 수 있습니다.)

추적 기능에 대한 정보는 아래 링크에서 확인하실 수 있습니다. 
(추적 기능을 이용하시면 문의 주신 광고 클릭시 순위, 매체, 노출된 광고 정보 등을 모두 확인하실 수 있습니다.)
https://saedu.naver.com/help/faq/ncc/view.nhn?faqSeq=120

감사합니다.
