### ISSUE TITLE
NPC와 NPLA 차이?

### ISSUE THREAD

**Issue by bbangpower** [naver/searchad-apidoc#112]
동일한 메소드명인데 NPC 혹은 NPLA 태그를 달고 있는 것들이 있는데 무슨 차이인가요?

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

네 해당 구분명칭은 상품(혹은 캠페인 타입)을 의미합니다. 

NPLA는 쇼핑 검색광고, NPC는 컨텐츠 검색광고(파워컨텐츠)를 의미합니다. 
이런 구분 스트링이 없다면 

이상과 같은 구분은 대체로 
입찰참고 지표인 Estimate의 경우에 적용 되어 있는데요.
각 상품별로 광고 노출 매체와 시장 상황이 모두 
다르기 때문에 각 상품에서 집행된 내역만을 원천 데이터로 해서 각각 순위별 평균입찰가 등을 계산하게 됩니다. 

이를 구분하시기 쉽도록 오퍼레이션 분리를 해둔것이라고 생각해 주시면 되겠습니다. 

p.s 참고로 Estimate에서 이러한 값이 없는 
get (average position bid)
get (median bid)
get (exposure minimum bid)
get (performance)
get (performance-bulk)

위 기능들은 파워링크 상품에 대한 정보입니다. 

감사합니다.
