### ISSUE TITLE
안녕하세요. 질문할게 있습니다 -

### ISSUE THREAD

**Issue by jinwoo8333** [naver/searchad-apidoc#113]
대용량 다운로드 보고서 데이터 정의서와 

http://naver.github.io/searchad-apidoc/#/operations/POST/~2Fstat-reports

두개를 참조하면서 만들고 있는데, 보고서 명칭과 영문명이 헷갈려서 문의드립니다.

예를 들면 

AD : 광고 성과 보고서
AD_DETAIL : 광고 성과 상세 보고서

이런식으로 나와있는 곳이나, 없다면 위의 예와 같이
대용량 다운로드 보고서 데이터 정의서와
같은 이름으로 답변 부탁드립니다.

AD : 
AD_DETAIL :
ADEXTENSION : 
AD_CONVERSION : 
ADEXTENSION_CONVERSION : 
AD_CONVERSION_DETAIL : 
NAVERPAY_CONVERSION : 
EXPKEYWORD : 
SHOPPINGKEYWORD_DETAIL : 
SHOPPINGKEYWORD_CONVERSION_DETAIL :

그리고 SHOPPINGKEYWORD_DETAIL, SHOPPINGKEYWORD_CONVERSION_DETAIL 이 두개는 데이터 정의서에 없던데 혹시 링크 있으면 부탁드립니다.

좋은 하루 되세요 : )

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

대용량 다운로드 보고서 한글 명칭 기준으로 말씀 일단 말씀 드립니다. 
AD : 광고효과보고서
AD_DETAIL : 괄ㅇ고효과상세보고서
ADEXTENSION : 확장소재광고효과보고서
AD_CONVERSION :전환보고서
ADEXTENSION_CONVERSION :확장 소재전환보고서
AD_CONVERSION_DETAIL : 전환상세보고서
NAVERPAY_CONVERSION :네이버페이보고서
EXPKEYWORD :키워드확장광고효과보고서
SHOPPINGKEYWORD_DETAIL :쇼핑검색광고키워드상세보고서
SHOPPINGKEYWORD_CONVERSION_DETAIL :쇼핑검색광고키워드상세전환보고서

SHOPPINGKEYWORD_DETAIL, SHOPPINGKEYWORD_CONVERSION_DETAIL
위 두개 보고서는 영문 스팩 문서만 현재 존재합니다. 
http://naver.github.io/searchad-apidoc/#/tags/StatReport 에서 제일 아래쪽으로 스크롤 내려 보시면 
찾으시 수 있습니다. 

감사합니다.

**Comment by jinwoo8333** [comment]
@naver-searchad 감사합니다 : ) 좋은하루보내세요 !
