### ISSUE TITLE
API 호출 초당 회수 제한 있나요?

### ISSUE THREAD

**Issue by bbangpower** [naver/searchad-apidoc#114]
안녕하세요.

API 호출 초당 회수가 있다면 얼마나 되나요?

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다 

답변이 늦어 죄송합니다. 
호출 속도 제한은 있습니다.  단 특정숫자가 정해진것은 아니고 초 단위 이하에서 측정합니다. 

속도는 저희 시스템이 현재 시스템 사용량을 판단하여 실시간으로 설정하고 있어 
정확한 수를 특정하기 어려우나 

기준은 호출대상이 되는 커스터머 아이디 (X-customer)단위이며 최근 관측치로는 
초당 25회~30회 정도가 측정 되고 있습니다. 

감사합니다.
