### ISSUE TITLE
컬럼명 문의입니다 : )

### ISSUE THREAD

**Issue by jinwoo8333** [naver/searchad-apidoc#115]
안녕하세요 오랜만에 인사드립니다 : )

$qstr = array('type' => 'MYCLIENTS');
$res = RestApi::GET('/customer-links', $qstr);

위와 같은 호출로 불러올시, 하단과 같은 컬럼명을 주는데 한글명 부탁드립니다.
PDF랑 Github 및 검색에도 찾지를 못해서 남깁니다 : ( 

customerLinkId
managerCustomerId
clientCustomerId
roleId
linkStatus
description
regTm
editTm
managerLoginId
clientLoginId
managerName
managerEnable
managerPenaltySt
managerCustomerDelFlag
clientEnable
clientPenaltySt
clientCustomerDelFlag
delFlag

부탁드립니다 : )

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 
개인적인 사정이 있어 답변이 늦었습니다. 죄송합니다. 

customerLinkId : 권한 설정 시 부여되는 고유 시리얼넘버입니다.  사용시 큰 의미는 없으실 것입니다.
managerCustomerId : 권한 받은 계정의 커스터머 아이디 입니다. 
clientCustomerId : 권한 준 계정의 커스터머 아이디 입니다. 
roleId  : 권한 종류입니다. 
linkStatus : 권한 상태입니다. 
description : 권한 관련 설명입니다. 
regTm : 설정일입니다.
editTm : 변경일입니다. 
managerLoginId : 권한 받은 계정의 로그인아이디 입니다. 
clientLoginId : 권한 준 계정의 로그인 아이디입니다. 
managerName : 권한 받은 계정의 소유자명입니다. 
managerEnable : 권한 받은 계정의 사용 가능 여부 입니다. 
managerPenaltySt : 권한 받은 계정의 이용 정지 여부입니다. 
managerCustomerDelFlag : 권한 받은 계정의 삭제 유무입니다.  
clientEnable : 권한 준 계정의 사용 가능 여부입니다. 
clientPenaltySt : 권한 준 계정의 이용 정지 여부입니다. 
clientCustomerDelFlag : 권한 준 계정의 삭제 여부입니다. 
delFlag : 해당 권한 설정의 삭제 유무입니다.

**Comment by jinwoo8333** [comment]
@naver-searchad 죄송하실것까지야 :; 바쁘시면 그럴수 있다고 생각합니다 : )
항상 친절한 답변 감사합니다 : )
