### ISSUE TITLE
keywordstool 문의 드립니다.

### ISSUE THREAD

**Issue by jxamen** [naver/searchad-apidoc#117]
c# 샘플 다운 받아서 아래 내용만 추가/수정후 실행하는데 
리턴이 안되고 있습니다. {"keywordList":[]} 
무엇이 문제일까요?

//App.config
BASE_URL : https://api.naver.com
API_KEY : 엑세스라이선스
SECRET_KEY : 비밀키
CUSTOMER_ID : 내 계정 : CUSTOMER_ID

//SampleProgram.cs
string keyword = "airbnb";
var request = new RestRequest("/keywordstool", Method.GET);
            request.AddQueryParameter("hintkeywords", keyword);
            request.AddQueryParameter("showDetail", "1");
            
            List<CustomerLink> customerLinks = rest.Execute<List<CustomerLink>>(request, managerCustomerId);

============ Request =============
GET /keywordstool?hintkeywords=airbnb&showDetail=1
X-API-KEY=0100000d95ab1ae811cf4
X-Customer=37
X-Timestamp=1530063898482
X-Signature=Kfy0eV3xpoj+kEs36lwRZU6r4Whhz22bAt+CXV9t3gY=

============ Response ============
200 OK
Connection=close
X-Transaction-ID=B47RL4GP1HJHS
Strict-Transport-Security=max-age=15768000
Cache-Control=no-store, must-revalidate
Content-Type=application/json;charset=UTF-8
Date=Wed, 27 Jun 2018 01:44:58 GMT

{"keywordList":[]}

**Comment by ystopia** [comment]
안녕하세요.

hintkeywords를 hintKeywords로 바꾸셔야합니다.

**Comment by jxamen** [comment]
요즘 시력이 떨어져서... 이런걸 놓치네요. 감사합니다.
