### ISSUE TITLE
Business Channel의 생성 관련 문의

### ISSUE THREAD

**Issue by younseunghyun** [naver/searchad-apidoc#12]
안녕하세요

business channel 문서를 보면

channel type이 site외에는 생성 ,수정이 안되는 것으로 보입니다.

해당 Type의 Channel Type에 대한 api 요청은 제공 예정이 없는 것인지, 아니면 아직 제공이 안되고 있는 것인지 궁금합니다.

**Comment by naver-searchad** [comment]
안녕하세요
비즈채널 담당자 입니다.

현재 사이트 타입 이외의 채널 타입( 전화번호, 예약, 주소, 톡톡)에 대해서는
 API 제공 예정이 계획 되어 있지 않습니다.

감사합니다.

**Comment by younseunghyun** [comment]
감사합니다 :)
