### ISSUE TITLE
Bizmoney 당일 실시간 소진액 조회

### ISSUE THREAD

**Issue by xBoomz** [naver/searchad-apidoc#121]
안녕하세요?

PHP Restapi 이용하고 있습니다. 

Bizmoney 당일 실시간 소진액을 조회하고자 getCost method에 당일날짜로 요청을 하여보았으니, 당일 소진액은 조회가 되지 않았습니다. 전일 이전의 데이터는 조회할 수 있었습니다.

1. Bizmoney 당일 실시간 소진액을 조회하려면 어떻게 해야 할까요?

2. 혹 당일 실시간 소진액 조회가 안 된다면, 우회적으로 전일 자정 시점의 Bizmoney 잔액을 조회함으로써 현재 잔액과 비교하여 실시간 소진액을 계산하고자 하는데, 전일 자정 시점의 Bizmoney 잔액을 조회하는 방법은 있을까요?

3. stat의 stat type는 무엇을 참조해야 할까요? stat을 조회하고자 하는데 정의된 stat type들이 무엇이 있는지 알지 못하여 문의드립니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

getCost 는 전일까지의 데이터를 제공드립니다 따라서 당일 소진액에 대해서는 조회하실 수 없습니다. 

크게 두가지 방법이 있습니다. 

A. stat을 이용해서 캠페인 합산 광고비를 당일 데이터로 조회하는 것입니다. 최대 2시간 지연데이터라는 점이 한게점입니다. 

B. 비즈머니잔액(Bizmoney: get)를 0시0분에 조회하셔서 저장하신 후 일중 조회하신 값과 비교하는 방식입니다. 단점은 충전이 발생하면 값을 계산하기 난처해 집니다. 

결론적으로 당일 비즈머니 소진액을 명시적으로 명확하게 조회할 방법은 제공되지 않습니다.(저희 역시 당일 광고비가 아닌 비즈머니 잔액만을 관리하지 않으므로 제공 드릴 방안도 없습니다.)

STAT의 stat type 옵션에 대해 설명 드립니다. 

현재 사용 중인 타입은 두가지입니다. 
NPLA_SCH_KEYWORD : 쇼핑검색광고의 노출 키워드 및 지표를 보는 옵션입니다. 
STAT REPORT로 더 상세한 보고서가 제공 되고 있으므로 간략히 체크하시는데 활용하실 수 있습니다.
이 기능을 쓰고 있는 검색광고내 화면은 쇼핑캠페인 하위 그룹 혹은 소재의 제외키워드탭에서 제외키워드 추가 버튼을 클릭했을때 노출 되는 팝업의 하단 1개월간 노출 키워드 부분입니다. 

BRND_CONTRACT : 브랜드 검색의 계약 기간중 누적 지표를 제공합니다. 
물론 그룹이나 캠페인 등에서 보실 수 있는 정보이므로 크게 활용처는 없으나 게약단위 누적 지표를 본다는 정도의 의미가 있습니다. 이 기능을 사용하고 있는 검색광고 내 화면은 브랜드 검색 캠페인 하위 그룹에서 계약관리 혹은 도구>계약 관리 화면입니다. 

감사합니다.
