### ISSUE TITLE
/keywordstool 에러관련입니다.

### ISSUE THREAD

**Issue by sk13098** [naver/searchad-apidoc#122]
해당 /keywordstool url 로
검색어를 for문으로 10~20개 정도 돌리면서 하나씩
get 요청을 후 검색수를 받아오고있습니다.
5개 정도는 무난하게 데이터를 받아옵니다
하지만 6번째에서 항상 code 429 와 message Too Many Requests 를
돌려줘서 어떻게 해야 되는지 여쭙고자 질문 요청 합니다..

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

네이버 검색광고 API 서비스는 속도 제한이 존재합니다. 
제한 기준은 시스템 상황에 따라 유동적으로 변화되고 있으며 측정 단위도 초 이하 단위이므로 
명확하게 이 제한에 맞춰 호출 하실 수 있도록 제한값을 정확하게 가이드 드리기는 어려우나 
대략 전반적으로 초당 25회~30회 정도의 수준으로 측정이 됩니다. (오퍼레이션 별로 상태가 조금씩
달라서 서비스 모두에 글로벌하게 적용하기는 좀 무리가 있는 수치기는 합니다.)

가장 간단하게 최대 속도로 호출 하시는 방법은  Too Many Requests 에러가 리턴될때 
몇 밀리섹~1초 사이의 sleep을 주셨다가 다시 시도 하도록 코드를 구성하는 방식입니다. 

그리고 사족입니다만 RelKwdStat 서비스(즉 GET /keywordstool)를 통해 제공되는 정보는 네이버 검색광고 집행 및 운영 목적으로 사용 목적이 한정 되어 있어 이외의 목적으로 이용하셨을 때 민/형사상 책임이 발생할 가능성이 있으므로 사용시 주의 하셔야 합니다. 

감사합니다.
