### ISSUE TITLE
현재 API가 작동하지 않는 것 같습니다.

### ISSUE THREAD

**Issue by kaorimikage** [naver/searchad-apidoc#123]
현재 결과값이 돌아오지 않고 있습니다. 확인 부탁드립니다.

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

금일 오전 11시 30분~12시 사이에 장비 이상으로 긴급 조치를 취했고 그 과정에서 순단이 발생한 일이 있었습니다. 혹 현재도 호출시 응답이 없으신지요?

감사합니다.
