### ISSUE TITLE
Campign Master의 Campaign Type 문의입니다 : 0

### ISSUE THREAD

**Issue by jinwoo8333** [naver/searchad-apidoc#124]
@naver-searchad 님 안녕하세요 : )
날이 많이 덥네요 : (

또 다시 컬럼명 문의드립니다 : ()

Campaign Master 의 Campaign Type 리턴이 1,2,3,4,0 이렇게 되고 있는데
1,2,3,4,0 설명 좀 부탁드립니다

(대용량 리포트랑 릴리즈 노트 다 뒤졌는데 못찾았습니다 ㅠㅠ)

1 : 웹사이트
2 : 쇼핑

이런 식으로 부탁드립니다 
상세하면 더 좋습니다 : )

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

1. 파워링크 (웹사이트)
2. 쇼핑검색광고 (쇼핑)
3. 파워컨텐츠 (컨텐츠)
4. 브랜드검색 (브랜드)

입니다. 소상공인광고는 6번으로 추가될 예정입니다. 

레퍼런스에도 업데이트 해 두도록 하겠습니다.

**Comment by jinwoo8333** [comment]
@naver-searchad 감사합니다 5번은 없는건가요 'ㅡ'?
