### ISSUE TITLE
네이버 API 사용법 문의

### ISSUE THREAD

**Issue by hirhdxo** [naver/searchad-apidoc#125]
안녕하세요. 
1. 네이버에서 제공하는 네이버 광고 API를 통해 월간 검색수(PC, 모바일), 월평균 클릭률, 월평균 클릭수, 경쟁 정도를 가지고 올 수 있다고 들었는데 광고 API를 보니 설명이 나와 있지 않아 사용법을 알고싶어 글을 남깁니다.
네이버광고에서 키워드를 조회했을 때 network탭을 조회해 보니 keywordstool이란 것으로 값을 가져오는 것은 알겠는데 네이버 API에는 설명이 없어서 설명해주시면 감사하겠습니다. 그리고 네이버 광고에서 키워드르 가지고 조회했을 때  requestURL은 https://manage.searchad.naver.com/로 시작하는데 API설명에서는 https://api.naver.com
로 나와있습니다. keywordstool 사용 샘플 또는 사용가이드를 부탁드립니다.

2. 해당 키워드로 발행된 블로그의 개수를 알고 싶은데 알 수 있는 API가 몬지 알려주시면 감사하겠습니다.

**Comment by ktko0714** [comment]
죄송합니다. 1번은 해결했는데, 2번 API는 몬지 알 수 있을까요 ?

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API 입니다. 

답변이 늦어 죄송합니다. 
2번 문의는 대략 특정 키워드 검색시 노출되는 블로그 갯수를 말씀 주신것 같습니다. 
네이버 검색광고 API는 네이버 검색광고 집행에 필요한 정보와 기능을 제공하는 기능으로 
블로그 서비스의 정보를 제공드리지 않습니다. 
참고로 해당 정보는 네이버의 어떠한 서비스에서도 API를 통해 제공되지 않습니다. 

혹 네이버 검색광고 파워링크 상품이 노출 가능한 매체 리스트 중 블로그 매체의 리스트가 필요하시다면
마스터 보고서의 Media Details (Media)을 통해 조회 가능하십니다. 

이외에 네이버 검색광고 API 서비스 특히 키워드도구 데이터 사용에 관련되어 참고하실만한 사항이 있어
추가로 말씀 드립니다. 
키워드 도구 (keywordstool)에서 제공되는 모든 정보는  "네이버 검색광고의 광고 상품"을 구매/집행하시거나 운영하시는 목적으로만 사용 가능하십니다. 이외의 목적으로 사용하실 경우 서비스 이용의 제한이 있을 수 있사오니 참고 부탁드립니다. 

감사합니다.

**Comment by ktko0714** [comment]
답변 감사드립니다.
