### ISSUE TITLE
브랜드검색 키워드 정보

### ISSUE THREAD

**Issue by jsam1319** [naver/searchad-apidoc#126]
안녕하세요

네이버 브랜드 검색 키워드의 클릭수, 전환수 등을 알고 싶은데요 
report를 통해서 키워드 ID와 클릭 수 등은 알 수 있더라고요
그런데 그 키워드 ID가 어떤 String 인지 알 수 있는게 ncc밖에 안보이더군요
혹시 다른 메소드가 존재하나요?

가령 nkw-a001-xxxxxxxxxx 를 넣었을 때에 -> 'XX병원' 같은 형태 말이죠 

혹시 이를 대체할 수 있을 만한 메소드가 있는지도 답변 부탁드립니다.

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

두가지 방법이 존재합니다. 

1. AdKeyword: get (http://naver.github.io/searchad-apidoc/#/operations/GET/~2Fncc~2Fkeywords~2F%7BnccKeywordId%7D)이나 
2. AdKeyword: list (by ids) (http://naver.github.io/searchad-apidoc/#/operations/GET/~2Fncc~2Fkeywords%7B%3Fids%7D)
위 기능으로 조회 하시는 방법이 있습니다. 

2. MASTER REPORT의 Ad Keyword (Keyword) 보고서
http://naver.github.io/searchad-apidoc/#/tags/MasterReport
를 받으셔서 조인해 보시는 방법이 있습니다. 

감사합니다.
