### ISSUE TITLE
네이버 브랜드 전환 수에 대해서

### ISSUE THREAD

**Issue by jsam1319** [naver/searchad-apidoc#128]
안녕하세요..

네이버 브랜드 전환 수에 대해서 궁금합니다.

네이버 브랜드 전환수를 보면
현재 클릭 수 보다 전환 수가 많던데 
제가 아는 전환 수랑 다른 의미 인 것 같더라고요 

제가 알고있는 전환 수는 
클릭 후 -> 구매 등의 작업을 했을 때 -> 전환
으로 알고 있는데

네이버 브랜드의 전환은 다른 의미인가요?
(클릭수보다 전환수가 많이 나오는 경우가 있을 수가 없기 때문에)

데이터 -> 보고서 중 AD_CONVERSION

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 API입니다. 

네이버 검색광고 프리미엄 로그분석의 전환 정의는 말씀 주신 내용에서 크게 벗어나지 않습니다. 
클릭수에 비해 전환수가 많은 경우는 크게 세가지 케이스가 주로 확인 되고 있습니다. 

1. 보고서 기준 일자에 기인한 경우 

전환은 전환 추적 기간에 따라 두가지로 나뉠 수 있습니다. 
클릭으로 부터 전환 발생 시점까지가 30분 이내인 경우 직접전환,30분 이후로부터 7~20일 이내(광고주 직접 설정 가능)발생한 경우 간접 전환으로 구분합니다. 

네이버 검색광고의 보고서의 일시는 해당 지표가 발생한 시점을 기준으로 합니다. 
즉 어제 발생한 클릭과 어제 발생한 노출은 어제의 데이터로 집계 되어 제공됩니다. 그러나 전환의 발생 시점 이전에 클릭의 발생 시점이 존재하는 경우, 어제 보고서의 전환은 전전일 혹은 최대 20일 이전에 발생한 클릭으로부터 기인한 전환과 어제 발생한 클릭으로부터의 전환이 합쳐져 있을 수 있으므로 
클릭수보다 전환수가 커질 수 있습니다 
이 케이스인지 확인해 보실 수 있는 방법은 직접 전환수만으로 체크해 보시거나(물론 23시 30분 이후에 발생한 클릭은 익일에 지표가 잡힐 수 있습니다.) 브랜드 검색의 경우 계약 종료 이후 최대 20일이후 까지의 해당 그룹/캠페인 단위 전환수를 취합하시어 비교해 보시는 방법이 있습니다. 

2.  무효 클릭으로 보고서에서 제외된 경우 
전환이 발생한 클릭일지라도 무효 클릭으로 판정되면 과금(브랜드 검색의 경우는 기간제 노출 계약 상품으로 무효 클릭으로 판정되어도 과금에서 제외되진 않습니다.) 및 리포팅 대상에서 
제외 됩니다. 직접 전환수만으로 체크해보셨음에도 차이가 작은 숫자로 발생하는 경우에는 이 케이스를 의심해 볼 수 있습니다.

3. 전환 스크립트 설치 구성에 관한 건 
스크립트를 자가 설치하신 경우 간혹 있는 경우입니다만 1회 전환을 중복해서 호출하거나 
엉뚱한 곳에 스크립트가 설치된 경우 등이 존재할 수 있습니다.  그러나 이런 경우는 최근에는 거의 
발견 되지 않는 케이스로 확률은 낮을 것 같습니다.

감사합니다.
