### ISSUE TITLE
About Slot information

### ISSUE THREAD

**Issue by licuiwei** [naver/searchad-apidoc#129]
Hello,
My team is using Naver searchad, and started to put ads on mobile recently.
I see you provide a PCPLMaxDepth to tell PC naver power link ads slot, and wonder whether there is any information about slot on mobile or other medias.
Thanks and looking forward to your reply.

**Comment by naver-searchad** [comment]
Hi. 

PCPLMaxDepth is The maximum number of ad impressions(Slot) per keyword at https://search.naver.com/search.naver.

The number of impressions available for each keyword and each available medium can vary. But
It does not provide the maximum number of exposures (SLOT) other than the PCPLMaxDepth value.

For mobile (https://m.search.naver.com/search.naver), three or five SLOTs per keyword are provided on the first page of search results. Three journals Five journals vary by keyword but do not provide this value.

Thanks
