### ISSUE TITLE
php에서 Stat 파라미터 형식에 관한 문의

### ISSUE THREAD

**Issue by kmangyo** [naver/searchad-apidoc#13]
안녕하세요. php를 통해 네이버 검색광고 api를 사용하고 있는데요.
Stat의 파라미터 형식에 관해서 알 수 가 없어서 문의드립니다.
다른 경우(Adgroup, Ad, AdKeyword 등)에는 list를 호출 해보면 파라미터 형식을 유추할 수 있는데, Stat는 따로 확인할 수가 없네요 ㅠ

**Comment by naver-searchad** [comment]
stat api의 파라미터는 http://naver.github.io/searchad-apidoc/#/tags/Stat 매뉴얼을 참고하시면 되는데요,

파라미터를 하나씩 설명드리면 아래와 같습니다.
## id, ids
* 캠페인 ID, 광고그룹 ID, 키워드 ID, 소재 ID를 의미하는 파라미터입니다.
* ids의 경우 ID 리스트를 의미하며, 동일한 엔티티 ID 리스트를 사용 가능합니다.

```
id=cmp-a001-0000
```

## fields
* 조회 대상 지표 리스트를 의미하는 파라미터입니다.
* 노출수, 클릭수, 클릭률 등, 매뉴얼에 표시된 지표를 포함하여 조회할 수 있습니다.
* 입력형식은 JSON 포맷으로 입력합니다.
```
fields=["impCnt","clkCnt","salesAmt"]
```

## timeRange
* 조회 기간
* 시작일, 마지막일을 JSON 포맷으로 입력합니다.
* datePreset과 동시 사용할 수 없으며, 만약 datePreset과 동시 사용할 경우, datePreset 값이 적용됩니다.
```
 timeRange={"since":"2016-07-01","until":"2016-07-10"}
```

## datePreset
* 미리 정의된 조회 기간
* 조회 시점 기준으로 어제, 지난 7일과 같이 미리 정의된 기간을 나타내는 파라미터입니다.
* timeRange와 동시 사용할 수 없으며 만약 timeRange와 동시 사용할 경우, datePreset  값이 적용됩니다.
```
datePreset=last7days
```
## timeIncrement
* 일별, 요약 조회 구분
* 조회 기간에 대해 일별 조회할지, 요약 조회할지 구분하는 파라미터입니다.

## breakdown
* 상세 지표 구분값
* 조회 기간내 PC/모바일, 요일별, 시간별, 지역별 지표를 구분하여 제공할지 정하는 파라미터입니다.

지표 조회 예시는 아래와 같습니다.
``` 
// 지난 30일 일별 지표 조회
/stats?id={id}&fields=["impCnt","clkCnt","salesAmt"]&datePreset=last30days&timeIncrement=1

// 당일 시간대별 요약 지표 조회
/stats?ids={id}&fields=["impCnt","clkCnt","salesAmt"]&datePreset=today&breakdown=hh24&timeIncrement=allDays

```

**Comment by kmangyo** [comment]
답변 감사합니다. 
근데 아래 와 같이 요청할 경우,

`$stats = $api -> GET('/stats?id='.'cmp-a001-01-0000000000xxxxx'.'&fields=["impCnt","clkCnt"]&datePreset=last30days&timeIncrement=1');`

다음과 같은 오류를 반환하는데요.
```
(
    [signature] => NEXix1v2YWNtrZZgayJBJAcmVkslnNnlMjkOHKrRppk=
    [status] => 403
    [title] => Invalid Signature
    [detail] => Signature 'NEXix1v2YWNtrZZgayJBJAcmVkslnNnlMjkOHKrRppk=' is inva
lid.
    [type] => urn:naver:api:problem:invalid-signature
)

```
동일한 restapi.php를 사용하는데도 불구하고, stat요청을 제외한 리스트롤 호출하는 등 다른 작업들은 잘 되는데, 
```
$adcamplist = $api->GET('/ncc/campaigns/'.'cmp-a001-01-0000000000xxxxx');
debug($adcamplist, $DEBUG);
```

왜 이경우에만 signature관련 오류를 반환하는걸까요?

**Comment by naver-searchad** [comment]
아래와 같이 작성하셔야 합니다.
```php
$stats = $api->GET ( '/stats', array (
		'id' => 'cmp-a001-01-0000000000xxxxx',
		'fields' => '["impCnt","clkCnt"]',
		'datePreset' => 'last30days',
		'timeIncrement' => '1' 
) );
```
signature 생성 시에는 path가 사용됩니다. 따라서 path와 query를 분리해서 요청하셔야 서명이 올바르게 생성됩니다.

**Comment by kmangyo** [comment]
답변 감사합니다. 문제는 잘 해결되었습니다.
