### ISSUE TITLE
getBizmoneyCostByStatDt 에 대해서 문의 드립니다. 

### ISSUE THREAD

**Issue by jsam1319** [naver/searchad-apidoc#131]
안녕하세요 .

브랜드 검색 API 사용 중에 값에 이상이 있어 질문 드립니다.

8월 16일, 17일에 API Return 값이 이상해서 질문드려요 

/billing/bizmoney/cost (getBizmoneyCostByStatDt) 사용 하는 중
'productCode'가 'BRAND_SEARCH'인 것만 합산하는 작업 중 
일부 계정에 있어서 광고비가 비 정상적으로 나오는 현상이 발생합니다.

가령 8월 16 일 이외에 다른 날의 광고비가 15000원 이었다면 8월 16일은 180000원 정도로 
10배 정도가 뻥튀기가 되어 값이 발생하는데요 

다른 날 API 통신을 해보면 정상적인 것을 확인 하였습니다.

왜 8월 16, 17일만 이런 현상이 발생하는지 여쭙고 싶습니다.

만약 계정에 대한 정보가 필요하시면
메일로 연락 주시면 알려 드리도록 하겠습니다. 감사합니다. 
(jsam1319@naver.com) 

(만약 브랜드 검색의 광고비라면 계약기간 중 매일의 광고비는 10원 이내의 오차로 일정해야 한다고 알고 있습니다. )

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

말씀 주시는 케이스라면 

1. 16일 부터 함께 진행되는 다른 계약이 존재
2. 중도 환불로 인한 영향 (최소 과금액이 존재하는데요. 이미 집행 시작한 계약 파기로 인한 중도 환불시 기 집행된 금액 보다 최소과금액이 크면 최소 과금액을 계약 종료 일에 일괄 부과하게 됩니다) 

두자기 케이스 중 하나가 아닐까 싶습니다. 

메일로 연락처를 알려 드려도 해당 채널로 지속적인 커뮤니케이션이 어렵고(1회용 이메일 주소나 공용 이메일 주소를 알려 드릴 수 밖에 없습니다.) 여러 경로를 거치게 되어 시간도 오래 걸리니 
아래 정보 두가지만 알려 주시면 저희가 로그를 찾아서 상세를 확인하도록 하겠습니다.

1. 리턴값의 트랜잭션 아이디 
2. 호출 일시(GMT 기준인지 KST 기준인지 표기해 주십시오.)

감사합니다.

**Comment by jsam1319** [comment]
비 정상의 경우
T_id : B5AMJLAU1HG6J
date : Monday August 20, 2018 13:45:54 (pm) (KST)  
timestamp : 1534740354


정상의 경우 
T_id : B5AML0FJ1DH7F
date : Monday August 20, 2018 13:48:50 (pm) (KST)
timestamp : 1534740530


확인해보니 비 정상인 날에 채결한 계약이 있더군요
그럼 이 체결한 계약의 계약금이 2,200,000원 이라면, 그 날의 광고비에 2,200,000이 추가되는 것인가요?
API 리턴 값으로는 그렇게 보입니다.
이것이 처음에 기획된 내용인지, 
만약에 정상적인 리턴이라면, 혹시 계약금은 제외하고 매일 계산되는 계약금(총 계약금 / 계약 Days)만 받을 수 있는지
궁금합니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

getcost 기능에서 브랜드검색 상품의 광고비는 비즈머니 실 차감금액이 아닌 일할 계산하여 집행 기간 중 금액을 드리는 구조이므로 실제 차감된 계약 금액이 제공되지는 않습니다.

주신 트랜잭션 아이디를 기반으로 체크해본결과 말씀 주신 상황처럼 16일부터 금액이 튀는 현상이 보이지 않는데요. 리턴 받으신 메세지 전문을 제가 체크해 보는 것이 좋을듯 싶습니다.
그러나 이 공간은 퍼블릭한 공간이므로 광고비 정보가 노출 될수 있으니 번거롭게 해드려 대단히 죄송합니다만. 
혹 광고주님 본인이시거나 본인 명의의 네이버 검색광고 회원(즉 광고주아이디) 계정을 가지고 계신다면 온라인 문의하기 https://saedu.naver.com/help/inquiry/onlineInquiry.nhn에서 로그인 하시고 
문의 종류를 API 문의로 선택하시어 헤더를 포함하여 리턴 메세지 전문을 보내 주실 수 있으실지요?
대행사이신 경우 서비스 광장을 이용하실 수 있습니다. 

두 방법이 모두 어려우시면 시간이 걸리더라도 다른 방안을 찾아보겠습니다. 

감사합니다.
