### ISSUE TITLE
region code 에 관한 질문입니다.

### ISSUE THREAD

**Issue by jinwoo8333** [naver/searchad-apidoc#135]
안녕하세요 : )

광고상세성과보고서에서 region code가 있는데
메뉴얼상에는 없는 -1, 99 는 어디를 뜻하는건가요 ?

00번은 해외나 미분류라고 알고있습니다 -

혹시 지역 코드 전체적으로 한번 정리해주실 수 있을까요 ?

대용량 리포트 메뉴얼상에서는 

Region code string 광고 성과가 발생한 지역 코드 입니다. 지역 코드는 아래와 같습니다.
00: 해외 or 지역 판별 되지 않음.
01: 강원도
02: 경기도
03: 경상남도
04: 경상북도
05: 광주광역시
06: 대구광역시
07: 대전광역시
08: 부산광역시
09: 서울특별시
10: 울산광역시
11: 인천광역시
12: 전라남도
13: 전라북도
14: 제주특별자치도
15: 충청남도
16: 충청북도
17: 세종특별자치시

이렇게 되어있지만, 넘어오는 값은 좀 추가된게 많은가보네요
위처럼 한번 정리 부탁드립니다 !

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다 

올해 2월경에 시군구 타게팅 기능이 추가되면서 코드가 좀더 세부화 되엇습니다. 
업데이트가 누락된점 사과 드립니다. 

0 혹은 00는 대한민국외 
99는 대한민국 내 이기는 하나 지역 특정이 되지 않은 경우 
-1은 국내/국외 여부 조차 알 수 없음 

입니다. 메뉴얼 및 홈페이지 상에도 수정된 사항을 업데이트 하도록 하겠습니다.

감사합니다.
