### ISSUE TITLE
확장소재(Ad Extension) 생성 방법

### ISSUE THREAD

**Issue by astrotauter** [naver/searchad-apidoc#136]
[2017.03.21 Release Note](http://naver.github.io/searchad-apidoc/#/release-notes)에 보면 광고문구를 JSON 형식으로 요청하도록 되어 있으나, [레퍼런스](http://naver.github.io/searchad-apidoc/#/operations/POST/~2Fncc~2Fad-extensions)에서는 확장소재를 생성(create)할때 JSON을 통해 광고문구를 전달하는 방법이 명시되어 있지 않습니다. 필수 파라미터에는 type만 전달하도록 되어있습니다. 

예를 들어 '추가제목'(HEADLINE)을 광고그룹에 추가한다고 할 경우 텍스트 광고를 생성하는 것과 같은 방식으로 아래와 같이 시도해보았으나 400 에러가 뜨네요.

"ad-extension" => $object_json_adextension 는 제가 임의로 넣어본 것입니다. 주석 처리해도 동일한 결과가 나옵니다.

---------------------------------------------------------------------------------------------
	       // 확장소재를 JSON 타입으로 생성
		$json_adextension = '{
					  "headline": "'.$title2.'"
					}';
		$object_json_adextension = json_decode($json_adextension); 

		$data = array(

			"ad-extension" => $object_json_adextension, //테스트용

			"mobileChannelId" => $businesschannel_id,
			"pcChannelId" => $businesschannel_id,
			"ownerId" => $nccAdgroupId,
			"schedule" => null,	//Every day and time
			"type" => "HEADLINE",
			"userLock" => 0 //Enable or Pause this ad by the user. 0:'ENABLED', 1:'PAUSED'.
		);

              $createadextension = $api->POST('/ncc/ad-extensions', $data);
--------------------------------------------------------------------------------------------

추가제목(HEADLINE), 홍보문구(DESCRIPTION), 서브링크(SUB_LINKS), 파워링크 이미지(POWER_LINK_IMAGE)의 문자열(광고문구, URL 등)을 어떻게 설정하여야 하는지 샘플 코드 부탁드립니다.

하나더 궁금한 것이 있는데요. 광고시스템(UI)에서 홍보문구가 API에서 DESCRIPTION이 맞나요? 맞다면 API에 있는 PROMOTION은 어떤 확장소재인가요?

감사합니다 ^^

**Comment by naver-searchad** [comment]
안녕하세요. 네이버 검색광고 입니다.

우선 누락된 내용에 대해서 불편을 끼쳐드려 죄송합니다.
빠른 시일내에 확장 소재를 생성할 수 있는 파라메터를 문서에 명시하도록 하겠습니다.

### adExtension 필드
- 특정 확장 소재 유형은 `adExtension` 필드를 필수로 요구합니다.
- 위에서 언급한 예제를 보면 `ad-extension` 으로 표기 되는데 `adExtension` 필드로 변경하여 호출해주시면 됩니다.

### 각 유형별 sample json
- 각 유형별로 json sample 을 기록하겠습니다. 일부 필드는 생략하도록 하겠습니다.
- 이미지를 요구하는 유형은 front 에서 등록 및 편집이 먼저 되어야 하기 때문에 API 로 등록하는 것은 어렵습니다.
  - 파워링크 이미지 (POWER_LINK_IMAGE), 이미지 서브링크 (IMAGE_SUB_LINKS)

#### 추가제목 (HEADLINE)
```json
{
  "ownerId": "grp-a001-01-000000000000001",
  "type": "HEADLINE",
  "adExtension": {
     "headline": "추가 홍보문구입니다"
  }
}
```
#### 홍보문구 (DESCRIPTION)
- `adExtension` 필드 안에 `heading` 필드는 정해진 문자열만 들어갈 수 있습니다.
```json
{
  "ownerId": "grp-a001-01-000000000000001",
  "type": "DESCRIPTION",
  "adExtension": {
     "heading": "할인",
     "description": "할인해드립니다"
  }
}
```

#### 서브링크 (SUB_LINKS)
- `adExtension` 필드에 배열로 데이터를 생성해야 합니다.
```json
{
  "ownerId": "grp-a001-01-000000000000001",
  "type": "SUB_LINKS",
  "adExtension": [
    { "name" : "사이트링크 이름1", "final" : "http://www.naver.com" },
    { "name" : "사이트링크 이름2", "final" : "http://manage.searchad.naver.com" }
  ]
}
```

#### 가격링크 (PRICE_LINKS)
- `adExtension` 필드에 배열로 데이터를 생성해야 합니다.
- `adExtension` 필드내 일부 필드는 필수가 아닙니다.
```json
{
  "ownerId": "grp-a001-01-000000000000001",
  "type": "PRICE_LINKS",
  "adExtension": [
    {"name" : "엑세사리", "price" : "10000", "modifier" : "부터", "final" : "http://www.naver.com"}
    {"name" : "마사지", "price" : "100000", "final" : "http://www.naver.com"}
  ]
}
```

### PROMOTION type
- 확장 소재에서 `추가홍보문구`에 대응되는 유형입니다.
- 쇼핑 검색 캠페인 하위 광고그룹 및 소재 에서만 등록 가능합니다.

**Comment by astrotauter** [comment]
빠른 답변 감사합니다 ~~


파워링크 이미지 (POWER_LINK_IMAGE) 관련하여 추가 문의가 있습니다. 

광고시스템 UI에서 도구 > 이미지 라이브러리에 이미지를 등록하면 '이미지 ID'가 생성되는데요. 이 이미지 ID값을 JSON 형식으로 전달하여 세팅할 수는 없나요? API 문서에는 type에 'POWER_LINK_IMAGE'가 명시되어 있어서 지원이 되지 않을까하는 생각이 들어 여쭤봅니다. ^^;

**Comment by naver-searchad** [comment]
`이미지 ID` 로 직접 확장 소재를 생성할 수 있는 방법은 없습니다.
이미지 라이브러리에 이미지를 등록하면 이미지 ID 에 대응되는 이미지 경로 가 생성됩니다.
예) 
```
/MjAxODAyMTNfNTAg/MDAxNTE4NTEzNDg5Mjkw.DEbPekwz8MZ21WJ1AarnLBZ5rhGzBMigR827TLQTqi4g.G7Yg-u_4ulB4-QJC0W9c_fnXjEyrKBVwR0fjGV8-Bxog.JPEG/729070-d17d9fe6-84e9-4a54-b437-876ecb4e9860.jpg
```

해당 값을 활용하여 아래와 같이 `파워링크 이미지`, `이미지형 서브링크` 유형의 확장 소재를 등록할 수 있습니다.

### 파워링크 이미지 (POWER_LINK_IMAGE)
```json
{
  "ownerId": "grp-a001-01-000000000000001",
  "type": "POWER_LINK_IMAGE",
  "adExtension": {
     "imagePath": "/MjAxODAyMTNfNTAg/MDAxNTE4NTEzNDg5Mjkw.DEbPekwz8MZ21WJ1AarnLBZ5rhGzBMigR827TLQTqi4g.G7Yg-u_4ulB4-QJC0W9c_fnXjEyrKBVwR0fjGV8-Bxog.JPEG/729070-d17d9fe6-84e9-4a54-b437-876ecb4e9860.jpg"
  }
}
```

### 이미지형 서브링크 (IMAGE_SUB_LINKS)
- adExtension 필드에 배열로 데이터를 생성해야 합니다.
```json
{
  "ownerId": "grp-a001-01-000000000000001",
  "type": "IMAGE_SUB_LINKS",
  "adExtension": [
    { "name" : "링크 이름1", "final" : "http://www.naver.com", "imagePath": "/MjAxODAyMTNfNTAg/MDAxNTE4NTEzNDg5Mjkw.DEbPekwz8MZ21WJ1AarnLBZ5rhGzBMigR827TLQTqi4g.G7Yg-u_4ulB4-QJC0W9c_fnXjEyrKBVwR0fjGV8-Bxog.JPEG/729070-d17d9fe6-84e9-4a54-b437-876ecb4e9860.jpg" },
    { "name" : "링크 이름2", "final" : "http://manage.searchad.naver.com", "imagePath": "/MjAxNzEyMTJfOTMg/MDAxNTEzMDQ5MDgwMTI2.FIXM2Z8VFdWBWO8aFFE4g5CVCpqvgdLH3twNRukDG-og.Bahf7dPwqsHHEggdvxNZpnpQLS_E4cKmdKMEj0pdcOkg.JPEG/genesis.jpg" }
  ]
}
```

**Comment by astrotauter** [comment]
죄송합니다만, '이미지 ID 에 대응되는 이미지 경로'는 어떻게 얻을 수 있나요? 

광고관리시스템 > 도구 > 이미지 라이브러리에서는 제공되지 않는듯한데요. 혹시 API를 통한 호출 방법이 있는지요?

감사합니다 ~~

**Comment by naver-searchad** [comment]
`광고관리시스템 > 도구 > 이미지 라이브러리` 에서는 이미지 경로를 가지고 이미지를 참조할 수 있는 url 을 만들어서 제공하고 있습니다.
- 이미지 라이브러리 데이터
```json
{
  "imageId": "img-a001-00-000000000755530",
  "imagePath": "/MjAxODAyMTNfNTAg/MDAxNTE4NTEzNDg5Mjkw.DEbPekwz8MZ21WJ1AarnLBZ5rhGzBMigR827TLQTqi4g.G7Yg-u_4ulB4-QJC0W9c_fnXjEyrKBVwR0fjGV8-Bxog.JPEG/729070-d17d9fe6-84e9-4a54-b437-876ecb4e9860.jpg"
}
```
- 예) https://searchad-phinf.pstatic.net/MjAxODAyMTNfNTAg/MDAxNTE4NTEzNDg5Mjkw.DEbPekwz8MZ21WJ1AarnLBZ5rhGzBMigR827TLQTqi4g.G7Yg-u_4ulB4-QJC0W9c_fnXjEyrKBVwR0fjGV8-Bxog.JPEG/729070-d17d9fe6-84e9-4a54-b437-876ecb4e9860.jpg?type=THUMBNAIL

현재 이미지 라이브러리 API 가 공개 되어 있지않습니다.
해당 API (조회 only)를 공개 하는 것을 검토하겠습니다.

**Comment by astrotauter** [comment]
"광고관리시스템 > 도구 > 이미지 라이브러리 에서는 이미지 경로를 가지고 이미지를 참조할 수 있는 url 을 만들어서 제공"한다고 하셨는데요.  광고관리시스템 UI에서 이미지 참조 URL(imagePath 값)을 얻을 수 있는 방법을 자세히 설명해 주실수 있나요? 이미지 라이브러리 페이지에서 아무리 눈씯고 찾아봐도 보이질 않네요 ^^;;

감사합니다 ~~

**Comment by naver-searchad** [comment]
chrome 개발자 도구를 사용하였습니다.
아래 이미지를 보시면 `이미지 미리보기` 에서 `img` 태그의 `src`를 보시면 그 값은 아래와 같습니다.
- img src
``` 
https://searchad-phinf.pstatic.net/MjAxODAyMTNfNTAg/MDAxNTE4NTEzNDg5Mjkw.DEbPekwz8MZ21WJ1AarnLBZ5rhGzBMigR827TLQTqi4g.G7Yg-u_4ulB4-QJC0W9c_fnXjEyrKBVwR0fjGV8-Bxog.JPEG/729070-d17d9fe6-84e9-4a54-b437-876ecb4e9860.jpg?type=THUMBNAIL
```

해당 URL 을 통해서 이미지를 참조할 수 있으며 이미지 경로는 아래와 같습니다.
- imagePath
```
 /MjAxODAyMTNfNTAg/MDAxNTE4NTEzNDg5Mjkw.DEbPekwz8MZ21WJ1AarnLBZ5rhGzBMigR827TLQTqi4g.G7Yg-u_4ulB4-QJC0W9c_fnXjEyrKBVwR0fjGV8-Bxog.JPEG/729070-d17d9fe6-84e9-4a54-b437-876ecb4e9860.jpg
```
![sample](https://user-images.githubusercontent.com/18188635/45072777-6fa13480-b117-11e8-9c96-47d23f8bc2df.png)

이미지 라이브러리 조회 결과 data 는 `Network` 탭을 확인하시면 데이터를 확인하실 수 있습니다.
![sample_data](https://user-images.githubusercontent.com/18188635/45073077-a592e880-b118-11e8-9cbb-f12d816d27ec.png)

**Comment by astrotauter** [comment]
감사합니다 ^^~

**Comment by naver-searchad** [comment]
안녕하세요.

네이버 검색광고 입니다.

`선택안함`을 하시려면 `heading` 필드를 삭제하고 API 를 호출하시면 됩니다.

**Comment by astrotauter** [comment]
안녕하세요!

최근 API를 통한 파워링크이미지 세팅이 안되고 있습니다.

가끔 세팅이 안될 경우 관리시스템에서 이미지를 삭제하고 재동록한 후 이미지ID와 경로(imagePath)를 다시 얻어 세팅하면 되었으나, 최근에는 아예 세팅이 안되고 있네요. ^^;

혹시 세팅 방식에 변경이 있었나요?

**Comment by naver-searchad** [comment]
안녕하세요
네이버 검색광고 입니다.

transactionId: B6G9G9P2PHGJD
API 호출시간: 2018-10-17 23:14:21
이미지 path 가 아래처럼 확인됩니다.
- /MjAxODEwMTdfMTEg/MDAxNTM5Nzg1Mjc5Mjg5.UHbH2Yc9wV_zWw6jh858koov7BnhsWR1V7nABoPNFx8g.Sv5OM5ayXmezEoTKyWbg2o9VeL8Mgobtd-lnOFwm4Fkg.JPEG/814071-20f31fa1-5e95-4e5f-8307-b9480d4165be.jpg

그런데 이 path 를 사용하여 이미지를 조회해보니 존재하지 않는 이미지로 확인됩니다.
광고주가 보유한 이미지 라이브러리의 path 를 보니 기존에 보유한 path 와 다른 것으로 보입니다.

확인 부탁드립니다.

**Comment by astrotauter** [comment]
답변이 늦었네요

지금은 잘되고 있습니다.

감사합니다 ^^
