### ISSUE TITLE
StatReport

### ISSUE THREAD

**Issue by chiakaileng** [naver/searchad-apidoc#137]
Is there a way to get report of a range of dates in one API call without calling StatReport API each time for each individual date?
E.g. Looking at data for L7days and I have to call StatReport 7 times.

https://naver.github.io/searchad-apidoc/#/tags/StatReport

**Comment by naver-searchad** [comment]
Hi. 

This is NAVER Search AD. API service support team.

The "STAT REPORT" form, the File Download report, does not support this date range.
The STAT function, on the other hand, provides period data. However, the data provided by the STAT function is not basic data but processed data.
http://naver.github.io/searchad-apidoc/#/tags/Stat

Thanks
