### ISSUE TITLE
StatReport 응답 결과 report has no data가 나옵니다.

### ISSUE THREAD

**Issue by wooram1125** [naver/searchad-apidoc#138]
과거에 나왔던 리포트 데이터도 조회해보니 안나오는데요
어떤 경우인지 알 수 있을지 문의드립니다.

**Comment by naver-searchad** [comment]
안녕하셔요 검색광고 API입니다. 

일반적으로 실제로 데이터가 없는 경우이긴 합니다만  이전에 조회를 해보셨다고 하니 
상세 사항 파악이 필요할듯 싶습니다. 
호출 시점과 시간기준(ex KST), 트랜잭션 아이디를 알려 주실 수 있으실지요?
* 참고로 시점, 트랜잭션 아이디 이외의 정보는 게시하지 말아 주십시오. 이곳은 공개 게시판이미로 
시그니쳐나 커스터머아이디, API 라이선스 키등이 게시될 경우 보안 리스크가 발생합니다.

감사합니다.

**Comment by wooram1125** [comment]
Transaction ID: B5PE2016PHGDD
호출시점: Wed, 12 Sep 2018 11:02:30

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

제공해 주신 트랜잭션 아이디 및 9월 6일 호출 이력을 체크해 보니 
광고가 집행된 일이 없는 계정을 대상으로 리포트 생성 요청이 이루어 지고 있었습니다.

커스터머 아이디 항목을 다시 확인하여 주십시오.

감사합니다.
