### ISSUE TITLE
Bizmoney: getCost에 들어가는 statDt 변수는 예를 들어 어떤것이 들어가야 하나요? 

### ISSUE THREAD

**Issue by EDMAI** [naver/searchad-apidoc#139]
1. statDt에 무엇을 넣어야 할지 몰라서 여쭤봅니다. 
'2018-09-09'인지 '20180909'인지 'lastday'인지 어떤것이 어떤형식으로 들어가야하는지 몰라서 여쭤봅니다.

2. https://manage.searchad.naver.com/customers/6179/billing/bizmoney 에 들어가면

금일의 소진비용을 알 수 있는데요, 이를 알 수 있는 방법은 무엇이 있을까요?

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

답변이 늦어져 대단히 죄송합니다. 

1. KST 기준으로 "yyyymmdd" 형식의 마스크를 적용하여 조회 하시면 됩니다. 
2. 당일 소진액(시간지연이 있습니다만)은 아직 제공되지 않고 있습니다. 잔액만 현재 제공중인데요. 
해당 기능 전체가 추가 제공될 예정으로 곧 관련 공지가 게시될 예정입니다.

감사합니다.
