### ISSUE TITLE
PHP 버전에 대해 문의드립니다.

### ISSUE THREAD

**Issue by LimMIR** [naver/searchad-apidoc#14]
이번에 처음으로 API 를 이용한 개발을 시작하게 되어 몇가지 문의드립니다.

1. 가이드에 나오는 PHP버전은 5.4 이상으로 나오는것 같은데.. 5.2나 5.3에서 개발하기에는 무리가 있는지 궁금합니다.

2. 제공중인 PHP 샘플을 실행해보니 
(1)  timestamp 값이 문제인지 오류가 생깁니다.
      restapi.php 파일에 gettimestamp() 함수안에  round(microtime(true)*1000); 이부분인거 같은데.. 
      실행하면 
       [timestamp] => 1.46892279674E+12
       [detail] => Non-numeric character in timestamp at(1)
       [status] => 403
       [title] => Invalid Timestamp
       [type] => urn:naver:api:problem:invalid-timestamp

검색광고 API는 처음이라 이것저것 궁금한게 많습니다. 
근데, 여기에 문의글 올려도 되는건지 그것조차 궁금하네요.

**Comment by naver-searchad** [comment]
1. php 샘플코드는 php 5.4 버전 이상에서 테스트 되었습니다. 그 이하의 버전에서는 정상 동작을 보장할 수 없습니다. 버전 차로 인해 발생하는 문제는 직접 해결하셔야 합니다.
2. php.ini 파일의 precision 값을 14 이상으로 조정하시기 바랍니다.

이곳에 문의 주시는 경우 답변 드리고 있습니다만
문의하신 내용은 모든 API 사용자가 볼 수 있사오니 
이점 유의 부탁 드리며 어떠한 경우에도 개인정보나 인증 정보가 노출된 문의(이슈)나 코멘트를 등록하시지 않도록 주의하셔야 합니다.
