### ISSUE TITLE
AdKeyword: update의 최종 request 형태 샘플은 어떻게 될까요? 

### ISSUE THREAD

**Issue by EDMAI** [naver/searchad-apidoc#140]
파이썬 사용하고 있는데,
bidAmt를 수정하려고 하는데 아래와 같이 요청하면 되나요? 
아니면 다른 형식이 되야되는지요? 
감사합니다.

https://api.naver.com/ncc/keywords/nkw------?fields=bidAmt%3D7000

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 API입니다. 

네 URL 자체는 적어주신것처럼 어베이트할 필드를 적어 주시면 되겠습니다. 
추가로  nccKeywordId, nccAdgroupId, bidAmt, useGroupBidAmt 항목을 json 메세지로 구성하시어 
호출시 넣어 주시면 되겠습니다.

감사합니다.
