### ISSUE TITLE
managerCustomerId System.ArgumentNullException 질문입니다.

### ISSUE THREAD

**Issue by OhShinHyeok** [naver/searchad-apidoc#141]
안녕하세요 C# 샘플코드에서 아무것도 바꾸지 않고 키값만 입력하고 실행해보았는데,
var managerCustomerId = long.Parse(ConfigurationManager.AppSettings["제 Customer_ID 입력"]);에서 오류가 나옵니다.
Console.writeln으로 확인해보니 ConfigurationManager.AppSettings["제 Customer_ID 입력"] 부분에 아무런 값도 들어가있지 않습니다. 어떤 것이 문제일까요?

처리되지 않은 예외: System.ArgumentNullException: 값은 null일 수 없습니다.
매개 변수 이름: String
   위치: System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   위치: System.Number.ParseInt64(String value, NumberStyles options, NumberFormatInfo numfmt)
   위치: System.Int64.Parse(String s)
   위치: Naver.SearchAd.SampleProgram.Main(String[] args)

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 api입니다. 

답변이 늦어 죄송합니다. 
이미 답을 찾으신 듯 합니다만 호출 하는 대상 계정의 CUSTOMER_ID 항목도 입력해 주셔야 호출이 이루어집니다.내 계정의 CUSTOMER_ID는 광고관리시스템>도구>API 사용관리에서 확인하실 수 있습니다.

감사합니다
