### ISSUE TITLE
소재 노출용 상품명, 이미지 수정 API

### ISSUE THREAD

**Issue by JMKim74** [naver/searchad-apidoc#143]
수고많으십니다.

광고관리 -> 소재 상세보기 -> 수정 
으로 진입하면 '노출용 상품명' 과 '이미지'를 수정할 수 있도록 되어있습니다.

API로 '노출용 상품명' 과 '이미지'를 수정할 수 있는지 문의드립니다.
현재 API 가이드 문서에는 Ad 의 update fields 에 userLock과 inspect만 보이네요.

혹 현재 수정할 수 없다면 향후 지원해 주실수 있는지도 함께 문의드립니다.
그럼 즐거운 하루되세요.

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

답변이 늦어 대단히 죄송합니다. 

현재 상품명, 이미지 수정 기능은 제공하고 있지 않습니다.(단 API 권한이 막혀 있는 것은 아니므로 광고 시스템 통신 내역을 참고하시어 호출을 하시면 작동은 합니다.) 상품명까지는 추후 제공할 수 있을 것으로 예상되나 이미지의 경우 이미지를 스토리지에 업로드 하고 이미지 아이디를 받아서 다시 설정하는 방식이다 보니 제공에 어려움이 존재할 것으로 예상됩니다.

감사합니다.

**Comment by JMKim74** [comment]
답변 감사합니다.
