### ISSUE TITLE
api중 master report, statreport는 무슨 차이인가요? 

### ISSUE THREAD

**Issue by EDMAI** [naver/searchad-apidoc#144]
다차원 보고서 api가 따로 제공되지 않아서 
데이터를 가공하려고 하는데 
master report statreport의 차이점이 어떤 점이 있을까요?

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

MasterRport는 광고 데이터의 메타정보 예를 들면 캠페인 명이나 키워드명 등을 제공하는 기능입니다. 
내 광고 정보의 대부분을 특정 시점 스냅샷으로 다운로드 받을 수 있다고 생각해 주시면 되겠습니다.

StatReport는 일 단위 광고 집행 성과 정보 즉 보고서 지표를 제공하는 보고서 입니다. 

보통 양자를 각 엔티티의 ID(ex. 캠페인아이디, 광고 그룹아이디, 등록 키워드 아이디등)로 join 하여 사용하게 됩니다. 

데이터를 1차 정규화 하여 나눠서 제공 드리는 정도로 이해해 주시면 되겠습니다.

감사합니다.
