### ISSUE TITLE
Transaction-ID : B6392E051DGVJ 인데 질문드립니다. 

### ISSUE THREAD

**Issue by EDMAI** [naver/searchad-apidoc#145]
stat을 읽어오려고 네이버깃헙의 Stat: get (by id) 참고해봤는데요,
(http://naver.github.io/searchad-apidoc/#/operations/GET/~2Fstats%7B%3Fid,fields,timeRange,datePreset,timeIncrement,breakdown%7D)

콘솔에서 아무런 반응이없는데 제대로 요청된건지 궁금하네요. 
Transaction-ID : B6392E051DGVJ입니다. 
원하는 timerange는 2018-09-18, 2018-09-21입니다. 

query와 request body 예시를 말씀해주시면 더욱 감사하겠습니다.

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

정상 호출이 된 것으로 확인 됩니다. 단, 해당 시점의 데이터가 없어 리턴이 없었던 것으로 보입니다. 
예를 들어 특정 캠페인의 과거 30일간 노출수를 호출 하시는 방식은 아래와 같이 메세지를 구성하시면 되겠습니다.

datePreset: last30days
fields: ["impCnt"]
id: cmp-a001-01-00000000XXXXXXX
timeRange: {"since":"2018-09-05","until":"2018-10-04"}

감사합니다.
