### ISSUE TITLE
 X-Transaction-ID:B6BGQJ60 질문입니다

### ISSUE THREAD

**Issue by phc118** [naver/searchad-apidoc#146]
AdKeyword 의 update-items 테스트중인데 

Request: PUT https://api.naver.com/ncc/keywords?fields=bidAmt HTTP/1.1
Entity: {"nccKeywords":[{"nccAdgroupId":"grp-a001-01-000000000892665","inspectStatus":"APPROVED","userLock":true,"editTm":0,"nccKeywordId":"nkw-a001-01-000000152932043","statusReason":"KEYWORD_PAUSED","useGroupBidAmt":false,"nccCampaignId":"cmp-a001-01-000000000123295","customerId":115804,"regTm":0,"bidAmt":220,"keyword":"SMS발송사이트","status":"PAUSED"},{"nccAdgroupId":"grp-a001-01-000000000892665","inspectStatus":"APPROVED","userLock":true,"editTm":0,"nccKeywordId":"nkw-a001-01-000000152932044","statusReason":"KEYWORD_PAUSED","useGroupBidAmt":false,"nccCampaignId":"cmp-a001-01-000000000123295","customerId":115804,"regTm":0,"bidAmt":220,"keyword":"SMS문자메세지","status":"PAUSED"}]}

와같이 호출했는데 status400 bad request 
JSON parse error: Cannot deserialize instance of `java.util.ArrayList` out of START_OBJECT token;

메세지가 반복됩니다.

request 의 어떤부분이 잘못된건가요?

**Comment by naver-searchad** [comment]
안녕하세요
네이버 검색광고입니다.

해당 API 호출시 기대되는 request body 는 `array` 입니다.
첨부한 request body는 `object` 입니다.

`nccKeywords` key 를 제거하고 array 로 구성하여 API 호출하시면 됩니다.

**Comment by phc118** [comment]
답변 감사합니다
