### ISSUE TITLE
X-Transaction-ID=B6FB63BS9HH9M 호출 질문

### ISSUE THREAD

**Issue by ultralisk** [naver/searchad-apidoc#148]
AdKeyword 의 update-items 테스트중입니다.

C#으로 테스트 하고 있으며, PHP로 테스트해보아도 
Keyword를 가져온다 던지, 레포트를 가져온다던지 하는 GET API는 정상적으로 잘 되고 있는데
처음 테스트 하는 함수이지만, 아래 기능을 테스트할 수 가 없습니다.

PUT으로 테스트하고 update-items은 항상 Invalid Signature 오류가 납니다.

============ Response ============
403 Forbidden
Connection=close
X-Transaction-ID=B6FB63BS9HH9M
Strict-Transport-Security=max-age=15768000
Content-Type=application/json; charset=UTF-8
Date=Tue, 16 Oct 2018 02:54:55 GMT

{"signature":"MRmfkJa0B1WI1HPAn8PNYxJ1SFHKfSx66Jc2FGeGaos=","detail":"Signature 'MRmfkJa0B1WI1HPAn8PNYxJ1SFHKfSx66Jc2FGeGaos=' is invalid.","title":"Invalid Signature","status":403,"type":"urn:naver:api:problem:invalid-signature"}

**Comment by naver-searchad** [comment]
query param 을 제외한 `{timestamp}.PUT./ncc/keywords` 로 signature 를 생성하셨는지 확인 부탁드립니다.

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

404 오류는 크게 세가지 원인이 있습니다. 

1. 존재하지 않는 아이디에 대해 호출 하였을때 
-->문의 주신 키워드 입찰가 변경건은 특정 그룹과 여기에 소속 키워드로 호출하게 되므로 
     해당 키워드나 그룹이 삭제 되지 않았는지, 혹은 그룹내에 속한 키워드인지 체크해 보시면 되겠습니다.

2. 내가 권한이 없는 계정에 속한 아이디를 호출 하였을때 
--> 호출 대상이 되는 계정(x-customer) 소유주로 부터 광고관리 (쓰기) 권한을 받으시면 POST나 PUT 메소드를 사용하실 수 있습니다. 성과조회(읽기) 권한만 받으셨다면 get만 가능합니다(대용량 보고서 즉 STAT-REPORT나 MASTER-REPORT기능의 경우 POST도 가능합니다.)
아래 권한 관련 도움말을 참고해 주시기 바랍니다. 권한은 광고 시스템(UI)쪽의 권한을 API도 공유하게 됩니다. 단, 몇몇 기능의 경우(다차원보고서)는 UI에서만 제공되므로 권한이 있더라도 API로는 호출 하실 수 없습니다.
권한 받기 주기 관련 도움말 : https://saedu.naver.com/help/faq/ncc/view.nhn?faqSeq=33

3. API에서 제공하지 않는 기능에 대해 호출 하였을때 
--> 예를 들면 충전이나 계정 정보 같은 기능들인데요. 아마도 이 케이스는 아니실것 같네요

감사합니다.

**Comment by ultralisk** [comment]
정보 감사합니다.
