### ISSUE TITLE
list API에 대해 403 Invalid Signature 에러 문의

### ISSUE THREAD

**Issue by 0xB4DF4C3D** [naver/searchad-apidoc#149]
```python
class NaverAPI:

    @classmethod
    def request(cls, method, uri, naver_id):
        naver_api_secret = naver_key[naver_id]['secret']
        naver_api_access = naver_key[naver_id]['access']
        naver_customer_id = naver_key[naver_id]['id']

        service_url = 'https://api.naver.com'

        now = int(time.time() * 1000)
        msg = f"{now}.{method}.{uri}".encode()
        signature = base64.b64encode(hmac.new(naver_api_secret, msg=msg, digestmod=hashlib.sha256).digest())

        headers = {
            # 'Host': f"{{service_url}}",
            'X-Timestamp': str(now),
            'X-API-KEY': naver_api_access,
            'X-Customer': naver_customer_id,
            'X-Signature': signature,
        }

        url = service_url + uri

        try:
            return pd.DataFrame(requests.request(method, url, headers=headers).json())
        except ValueError:
            try:
                return requests.request(method, url, headers=headers).json()
            except json.JSONDecodeError:
                return requests.request(method, url, headers=headers)
```

위와 같은 코드를 가지고 `NaverAPI.request('GET', '/ncc/adgroups', 'naver1')` 를 하면 adgroup 목록이 잘 나오는데요. 다른 API들, 예를 들면
 - /ncc/adgroups{?nccCampaignId,baseSearchId,recordSize,selector}
 - /ncc/keywords{?nccAdgroupId,baseSearchId,recordSize,selector}
 - /ncc/targets{?types,ownerIds}
과 같은 {?..., ...} 형태의 API는 어떻게 호출해야 하는지 전혀 모르겠습니다.

Sample코드와 다른 issue를 봐도 {?..., ...} 형태의 API 호출 방법은 찾질 못했구요.

`/ncc/keywords?nccAdgroupId=~~~` 형태로 호출하면 403 Invalid Signature가 나네요. 

{?..., ...} 형태의 API 호출 예제가 궁금합니다.

감사합니다.

**Comment by naver-searchad** [comment]
해당 값을 query parameter로 요청하시는게 맞습니다. (`/ncc/keywords?nccAdgroupId=~~~`)

단, signature는 query parameter를 제외한 path 만으로 생성하셔야합니다. (`{timestamp}.GET./ncc/keywords`)

**Comment by 0xB4DF4C3D** [comment]
깃헙 서버에 오류가 생겨 이슈가 제대로 등록이 안되었다고 나왔는데 제대로 등록이 되었었나 보네요.
답변 감사드립니다. 이슈 해결되었습니다. 감사합니다.
