### ISSUE TITLE
channel의 request inspect 관련 하여 문의 입니다.

### ISSUE THREAD

**Issue by younseunghyun** [naver/searchad-apidoc#15]
안녕하세요

channel에 관련한 api중 request inspect의 경우 문서에서는 

`PUT /ncc/channels/{businessChannelId}/inspect{?message}`로 나와 있습니다.

현재 해당 기능을 사용 하기 위해서

`PUT /ncc/channels/{businessChannelId}/inspect?message=test` 처럼 사용 하고 있습니다.
(businessChannelId에 해당 채널 id를 넣고 있음)
해당 방법처럼 사용시 500 에러가 뜨는데 어떤식으로 사용 해야 될까요?

**Comment by naver-searchad** [comment]
안녕하세요
비즈채널 담당자입니다.

답변이 늦어져서 죄송합니다.
현재 비즈채널 관련된 API 문서 업데이트 중에 있습니다.

정상적인 재검수 API사용을 위해서는 

PUT /ncc/channels/{businessChannelId}/inspect 으로 주시되
다른 업데이트와 동일하게 requestbody에 channel 정보로 주셔야합니다.
RequestBody 에  { "nccBussinessChannelId": (businessChannelId), "inspectRequestMsg": (검수를 위한메세지) } 를 포함하면 정상적인 응답을 받으실 수 있습니다.

**Comment by younseunghyun** [comment]
친절한 답변 감사합니다 :)

**Comment by younseunghyun** [comment]
말씀해주신대로 사용 하였으나 500이 반환되어 재문의 드립니다.

`PUT /ncc/channels/{businessChannelId}/inspect` 의 url로 요청을 보내고 있습니다.

또한 body에 inspectRequestMsg를 담은 channel을 담아서 보내고 있습니다.

하지만 500 return이 오는 상태입니다.

혹시 inspectRequestMsg말고 다른 필드도 채워줘서 보내야 되는 것이 있는건가요 ?

**Comment by naver-searchad** [comment]
안녕하세요
비즈채널 담당자입니다.

내부 사정으로 인해 금일 5시반 이후에 재시도 부탁드리며,  
5시반 이후에도 시도시 정상적인 응답을 받지 못할 경우

transactionId 를 남겨 주시면 로그 확인 후 문제사항 답변드릴수 있도록 하겠습니다.

감사합니다.
