### ISSUE TITLE
No HTTP code was returned

### ISSUE THREAD

**Issue by jxamen** [naver/searchad-apidoc#151]
특정 서버에서만 이른 증상이 나타나고 있습니다.
카페24 500월짜리 웹 호스팅에선 되는데...
회사 서버에서는 이런 에러가 나네요.

서버 환경은 아래와 같습니다.
PHP Version 5.5.5
Apache/2.4.6 (Unix) PHP/5.5.5

cURL support | enabled
-- | --
cURL Information | 7.19.7

아래 샘플 코드 입니다.
sign = 1540460137157.GET./keywordstool No HTTP code was returned

$api = new RestApi($config['BASE_URL'], $config['API_KEY'], $config['SECRET_KEY'], $config['CUSTOMER_ID']);

$keyword =  "서울여행";
$keywords = array(
		'format'	=>'json',
		'siteId'	=>'',
		'mobileSiteId'=>'',
		'hintKeywords'	=>$keyword,
		'includeHintKeywords'	=>'0',
		'showDetail'	=>'1',
		'biztpId'	=>'',
		'mobileBiztpId'=>'',
		'month'	=>'',
		'event'	=>'',
		'keyword'	=>'',
	);
$k_data = $api->GET('/keywordstool',$keywords);

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

문제가 발생하는 호출에서 리턴된 x-transactionID 와 호출일시를 알려 주시겠습니까?
트랜잭션 아이디와 호출일시외의 다른 정보는 말씀 주실 필요가 없다는 점 참고 부탁드립니다.

감사합니다.

**Comment by jxamen** [comment]
nameserver 문제 였습니다.

/etc/resolv.conf 
nameserver 8.8.4.4 
nameserver 8.8.8.8

이걸로 해결했어요.
