### ISSUE TITLE
update AdKeyword API 문의

### ISSUE THREAD

**Issue by 0xB4DF4C3D** [naver/searchad-apidoc#152]
안녕하세요. 늦은 밤까지  혼자 이것저것 시도해보는데 잘 되지 않아 여쭤봅니다.

현재 GET과 DELETE는 어떻게 하다보니 잘 사용중인데요. PUT은 어떻게 사용해야될지 정말 감이 안오네요.

먼저 간단하게 AdKeyword update 의 명세를 살펴보면
`PUT /ncc/keywords/{nccKeywordId}{?fields}`인데 이건

```python
foo_api.put('/ncc/keywords/nkw-a001-01-000001573147359?fields=bidAmt', data={
    'bidAmt': '130'
})
```
이런식으로 요청하면 되는건가요? 

```python
foo_api.put('/ncc/keywords/nkw-a001-01-000001573147359?fields=bidAmt', data={
    'bidAmt': '130',
    'nccAdgroupId': 'grp-a001-~',
    'nccKeywordId': 'nkw-a001-~'
})
```
이렇게 Id값도 지정해줘봤습니다.

Accept헤더도 설정해보고 Cotent-type헤더도 설정해보고 json도 쌩으로 날려보고 dumps도 해보고 인코딩도 해보고 다른것도 껏다 켯다 다 해봤는데 막막하네요..

아무리해도 400 에러만 반환됩니다.. 요청 예시를 알 수 있을까요? 샘플코드에는 너무 단순한 예제만 있어서 알기가 어렵네요. update-items 형태도 알려주시면 넘넘 감사하겠습니다..

**Comment by 0xB4DF4C3D** [comment]
해결하였습니다. 누군가 저처럼 삽질할 분들을 위해 기록해둡니다.

415에러는 Header에 Content-Type을 application/json으로 지정해주어 해결하였고
400에러는 요청폼이 잘못되어서 그랬던것이었습니다.

bidAmt를 수정할때는 json body에 nccGroupBidAmt도 불린값으로 지정해줘야 되더라구요. 명세에 이미 나와있는거였는데 제가 제대로 읽어보질 못했습니다.

bid값 업데이트의 예는 다음과 같고
data = {
    'bidAmt': 100,
    'useGroupBidAmt': 0,
    'nccAdgroupId': 'grp-a001-01-000000008418616',
    'nccKeywordId': 'nkw-a001-01-000001573147359'
}

userLock 업데이트는 다음과 같습니다.
data = {
    'userLock': 1,
    'nccKeywordId': 'nkw-a001-01-000001573147359'
}

근데 bid값 업데이트에는 AdgroupId가 필수고 userLock은 선택인건 왜 그런걸까요? useGroupBidAmt가 0이라면 groupId는 필요없지 않나 싶어서요.

**Comment by 0xB4DF4C3D** [comment]
그리고 단일 키워드 업데이트 말고 여러개를 업데이트 하려면 update-items 쓰는게 맞나요?

```python
request('PUT', '/ncc/keywords?fields=userLock', data={
    'nccKeywords':[
        {
            'nccKeywordId': 'nkw-~'
        }
    ]
})
```
이런식으로 요청하면

```
[Errno 400] Bad Request: 'JSON parse error: Cannot deserialize instance of `java.util.ArrayList` out of START_OBJECT token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.util.ArrayList` out of START_OBJECT token\n at [Source: (PushbackInputStream); line: 1, column: 1]'
```
이런 에러가 뜨더라구요. 제 전송방법이 잘못된건지 궁금합니다.

물론 아래처럼 이것저것 변경도 해보았습니다.
```python
request('PUT', '/ncc/keywords?fields=userLock', data={
    'nccKeywords':[
        {
            'nccKeywordId': 'nkw-~',
            'userLock': 1,
        },
        {
            'nccKeywordId': 'nkw-~~',
            'userLock': 1,
        }
    ]
})
```
그래도 같은 에러만 나오네요. 도움 부탁드립니다. 감사합니다.

**Comment by 0xB4DF4C3D** [comment]
아 이 문제는 https://github.com/naver/searchad-apidoc/issues/146 를 참고하여 해결했습니다.

```python
request('PUT', '/ncc/keywords?fields=userLock', data=[
        {
            'nccKeywordId': 'nkw-~',
            'userLock': 1,
        },
        {
            'nccKeywordId': 'nkw-~~',
            'userLock': 1,
        }
    ]
```

이런식으로 하니까 잘 됩니다 :D

**Comment by naver-searchad** [comment]
안녕하세요

네이버 검색광고 입니다.

키워드의 입찰가를 변경하는 경우 광고그룹 ID 를 필수로 하고 있습니다.
광고그룹 ID 필수 사항를 선택사항으로 변경할 수 있는지 내부적으로 검토해보겠습니다.

감사합니다.
