### ISSUE TITLE
네이버 광고도구 점프 문의

### ISSUE THREAD

**Issue by 0xB4DF4C3D** [naver/searchad-apidoc#153]
안녕하세요.

customerId와 nccKeywordId를 알면  광고도구에서 이에 해당하는 링크로 넘어가게끔 하는법이 있을까요?

https://manage.searchad.naver.com/customers/~~~~/adgroups/@@@@

형태로 해당 그룹까지는 점프가 가능한데
네이버 광고도구에서는 자동으로 필터링을 걸어주더라구요.

이걸 구현하려면 혹시 헤더나 body어디를 설정해줘야 할까요..?
감사합니다.

**Comment by 0xB4DF4C3D** [comment]
아 저기 말고

https://manage.searchad.naver.com/customers/~~~~/searchs?q=@@@@&exact=false

여기다가 하니까 됩니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하셔요 검색광고 API입니다. 

문의 주신 내용만으로는 정확한 구현 사항을 확인키 어려워 일단 일반적인 사항으로 안내 드립니다.

현재 말씀 주신 네이버 검색광고 광고 시스템(네이버 검색광고 내에서 UI를 통해 제공되는 광고관리서비스의 고유 명칭입니다.)에 파라미터를 포함시킨 URL을 생성하여 이동하는 링크를 제공하는 형태는 네이버 검색광고 서비스 이용 약관 제 16조 회원의 의무 3 항에 따라 서비스 이용 제한의 가능성이 있을 수 있습니다. 구현 혹은 설계 시 하기 검색광고 서비스 이용 약관을 다시 한번 참고해 주기시를 부탁드립니다.https://saedu.naver.com/adguide/policy/terms.nhn

또한 상기 안내는 사용자남께서 약관을 위반하고 계신다고 안내를 드리는 것은 아니며 위반 가능성이 존재할 수 있음에 기반하여 사용상 주의 사항을 안내 드리는 것으로 사용자님의 네이버 검색광고 이용 약관 위반 혹은 위반하지 않음 여부에 대한 고지를 드리는 안내가 아님을 말씀드립니다.

감사합니다.

**Comment by 0xB4DF4C3D** [comment]
헉

저는 그저 회사 내부적으로 마케팅팀에서 키워드를 쉽게 관리할수 있게 하고 싶어서
특정 키워드와 이에 대응하는 광고도구 링크를 얻고 싶었던건데 문제가 된다면 취소하겠습니다.
(사실 방법은 찾았어요.) 

근데 이게 막 1초에 엄청 여러번 들어가는것도 아니고 뭘 우회하는것도 아니고 URL을 그냥 GET해서 들어가는건데 이것도 뭔가 조항에 위반되는걸까요?

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

놀라실까봐 마지막 문단을 넣은 것인데요. 
저희가 약관 위반을 했다고 말씀드리는 것이 아니라 가능성이 있을 수 있으니 
약관 내용을 참고해 주십사 부탁을 드리는데 위 코멘트의 목적이 있었습니다. 

기술적으로는 여러가지 경우의 수가 있고, 실상 말씀 주신 방법은 그 사용 목적과 빈도, 그리고 세부적인 
구성에 따라 약관 위반이 될 수도 있고 아닐 수도있습니다. 
이에 대한 몇가지 원칙들이 존재하나 이 부분은 저희로서도 보안상의 문제로 공개하기 어렵다 보니 
세부적인 기술 가이드를 드리기가 쉽지 않은 상황이기도 합니다. 이점은 양해를 구합니다.

약관 위반 사항이 발생하는 경우 이 사실을 이용자 분께 통지 드리고 이용자분 혹은 광고주님의 말씀에 따라 상황별로 실제 이용정지 가 되거나 약간의 기능 수정 정도로 해결이 되는 등 이에 대한 진행 역시 다양합니다. 단, 개발 업무의 특성상 이미 작업해 놓으신 기능이나 로직을 추후에 수정하거나 변경하는 것은 이용자님의 시간과 비용이 소요되는 일이므로 미리 약관상 제약조건을 체크해 보실수 있도록 안내를 드린 것으로 이해해 주시면 감사하겠습니다.

**Comment by 0xB4DF4C3D** [comment]
놀라지 않았습니다.
보안상의 문제로 세부적인 기술 가이드를 알려주시기 어려운 점 이해합니다.
미리 알려주셔서 감사합니다.
