### ISSUE TITLE
일치검색 기능은 어떤것 사용해야하나요?

### ISSUE THREAD

**Issue by UnlimitedCity** [naver/searchad-apidoc#154]
일치검색 기능은 어떻게 해야 사용이 가능할까요?

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

저희가 상품이 다양하고 용어의 차이가 있을 수 있어 정확한 답변을 드리는 것이 아닐 수도 있다는 점 우선 양해를 구합니다. 답변 보시고 부족한 부분은 추가 문의를 주시기 바랍니다. 

파워링크 상품, 파워콘텐츠, 브랜드 검색 상품의 경우 기본값이 일치 검색입니다. 
쇼핑검색광고 상품의 경우는 키워드만 기준으로 말씀드리면 기본 값이 확장 검색 기반 매칭입니다.

파워링크 상품에서 확장 검색(키워드플러스)/일치 검색 사용 여부를 셋팅하시려면 
adgroup 기능에서 useKeywordPlus 항목을 설정하시면 되겠습니다. true가 사용함(즉 확장검색), 
false가 사용하지 않음 (즉 일치 검색)입니다. 

한가지 주의 하실 점은 키워드플러스 기능의 확장 검색은 동일한 의미를 가진 다른 키워드로 확장되는 방식입니다. 

쇼핑검색상품은 일치 검색으로 노출 가능한 키워드를 설정할 수 없는 상품이라 기능이 제공되지 않습니다.

이외의 상품은 일치 검색만 지원하여 설정할 수 있는 옵션이 없습니다.

감사합니다.
