### ISSUE TITLE
[ID:B6NQ5EEBHHIA8] resultStatus는 어떻게 얻을 수 있을까요?

### ISSUE THREAD

**Issue by 0xB4DF4C3D** [naver/searchad-apidoc#155]
안녕하세요. 늘 도와주셔서 감사드립니다.

지금 제가 [AdKeyword](https://naver.github.io/searchad-apidoc/#/tags/AdKeyword) API를 활용하여
키워드 정보를 가져오는데 만약 키워드 상태가 PENDING인 경우 이에 대한 자세한 사유에 대해서도 정보를 얻고 싶었습니다.

그래서 resultStatus 열을 가지고 알 수 있는건가 싶었는데 요청을 해도 resultStatus 열은 반환되지 않더라구요. 광고도구에서 나오는것처럼 statusReason 보다 더 자세한 사유를 받고 싶습니다.

X-Transaction-ID는 B6NQ5EEBHHIA8입니다.

어떻게 하면 좋을까요? 감사합니다.

**Comment by 0xB4DF4C3D** [comment]
그리고 사소한건데 resultStatus 열 설명에서 Infomation 으로 오타가 있는것 같아요

**Comment by naver-searchad** [comment]
안녕하세요

네이버 검색광고 입니다.

키워드에서 `resultStatus` 의 경우 `키워드 등록` 이 실패했을 경우에 각각의 키워드에 대해 등록 불가능한 사유를 제공하고 있습니다.
키워드 API 에서는 `status` 와 `statusReason` 이 제공되는데 이는 각각 키워드의 상태 및 사유에 해당됩니다.

현재 사유 관련해서 더 자세한 사항을 반환하는 API 는 공개가 안되어 있습니다.

또한 언급해주신 오타 관련해서는 빠른시간내에 수정하도록 하겠습니다.

감사합니다.

**Comment by 0xB4DF4C3D** [comment]
답변 감사드립니다.

혹시 키워드 노출 제한시 이에 대한 자세한 사유를 반환해주는 API는 앞으로도 공개가 안되는건가요?

지금껏 손으로 광고도구를 관리하다 API를 알게되서 조금씩 도입중인데 도움이 많이 되고 있습니다.

자세한 사유를 반환해주는 API가 개발이 된다면 정말 더 좋을것 같습니다.

부탁.. 드립니다..!
