### ISSUE TITLE
Stat Report Download 부분 질문드립니다!

### ISSUE THREAD

**Issue by niceday026** [naver/searchad-apidoc#156]
현재 Stat_Report를 통해서 

현재 RestApi의 DOWNLOAD 메소드를 통해서 SHOPPINGKEYWORD_DETAIL을 가져오는 작업을 하고 있습니다

1. POST 요청을 통해 보고서 생성
2. GET 요청을 통해 보고서의 생성여부 체크 
3. 2번의 DownloadUrl을 통해 파일 다운로드를 진행중인데

요청했던 정보를 DB에 입력하여 관리 할수 있도록 할려면 어떻게 처리를 해야할까요?
단순 출력을 통해서 파일 내 정보를 확인하고자 var_dump를 찍어봐도 $output에는 true 만 나오고 파일내 정보를 볼수 있는 방법이 없습니다

    public function DOWNLOAD($url, $localpath)
    {
		echo "start download...";
        $fp = fopen($localpath, "w");
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");
        curl_setopt($ch, CURLOPT_HEADER, false);
        curl_setopt($ch, CURLOPT_HTTPHEADER, $this->getHeader("GET", "/report-download"));
        curl_setopt($ch, CURLOPT_FILE, $fp);
        curl_setopt($ch, CURLOPT_TIMEOUT, 120);

        $output = curl_exec($ch);
        $code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        $error = curl_error($ch);
        curl_close($ch);
        fclose($fp);
        if (empty ($code)) {
            die ("No HTTP code was returned");
        } else {
            echo "Http Status : " . $code . "\n";
        }

        if (!empty ($error)) {
            echo "error : $error\n";
            die("failed to request");
        }
    }

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

"요청했던 정보를 DB에 입력하여 관리 할수 있도록"
--> 이 말씀에서 요청 했던 정보라 함은 어떤 정보를 의미하시는 것인지요?

감사합니다.

**Comment by niceday026** [comment]
넵 안녕하세요! 
 RestApi의 DOWNLOAD를 통해 SHOPPINGKEYWORD_DETAIL에 대한 정보를 가져오는 경우
(즉, 검색광고의 쇼핑검색광고 키워드 상세 보고서)의 내용을 DB에 넣어서 통계분석을 원하는경우를 이야기합니다!

저희는 현재 작동중인 검색광고의 효율을 분석하고자 검색광고 API를 통해 쇼핑검색 키워드 상세보고서, 쇼핑검색키워드전환보고서의 정보를 저희 DB에 입력하여 통계분석을 하고자 이 프로젝트를 진행하고 있습니다!

하지만 RestApi->DOWNLOAD에서 반환되는 정보가 해당 폴더의 .tsv 파일로 다운로드 되는것 까진 확인을 했는데 파일을 생성되기전 파일로 출력되야할 내용을 바로 DB에 넣기위해선 어떤식으로 작업을 해야할까요?

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다 .

일단 보고서 파일을 수령하시어 이를 DB에 업로드 하는 방법을 문의 주신것 같지는 않습니다. 
(아닐 것 같지만 만일 문의 주신 것이 위의 내용이라면 사용하시는 DBMS와 언어의 데이터 import 예제나 도움말을 찾아보시는 것을 권장드립니다.)

"파일이 생성되기전에 파일로 출력되어야 할 내용" 에 대한 이해가 조금 어려운데요. 
번거로우시겠지만 예를 들어 주실 수 있으실지요?

감사합니다.
