### ISSUE TITLE
Stat에서 전환수와 전환매출액 정보를 받을 순 없나요?

### ISSUE THREAD

**Issue by kaorimikage** [naver/searchad-apidoc#157]
Stat에 전환수와 전환매출액 정보를 포함하여 주실수 있는지요?
기간 단위의 정보가 필요한데 Stat Report에서 하루씩 가져오려고 하니 너무 힘듭니다.

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

현재 공식 지원되고 있지는 않지는 조회는 가능합니다.
(공식지원이 되지 않는다는 내용은 데이터나 기능 자체는 정상이나 기술지원을 하지 않는다는 의미입니다.)

그간 요청이 없어서 일단 기본 자료로 한정 했습니다만 최대한 빠르게 공식지원 대상으로 변경하고 메뉴얼 업데이트 하겠습니다. 

STAT 호출시 fields array에 아래 항목을 넣어서 호출해 주시면 되겠습니다.
"ccnt" : 전환수
"crto" : 전환율
"convAmt" : 전환 매출액
"ror" : 광고 수익율
"cpConv" : 전환당비용(원)

혹 안되시면 말씀 부탁드립니다. 

감사합니다.

**Comment by kaorimikage** [comment]
원하던 내용입니다. 답변 감사합니다.
