### ISSUE TITLE
Estimate: get (average position bid) api 통계 기준일이 어떻게 되나요?

### ISSUE THREAD

**Issue by kaorimikage** [naver/searchad-apidoc#158]
한시간 간격으로 정보를 받을 방법이 있나요?

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

문의 주신 순위별 평균 입찰가 데이터는 주 단위로 생성됩니다. 
생성 시점은 매주 일요일 입니다. 대략 새벽에 작업합니다만 오후 중에 처리될때도 있습니다. 
데이터의 기준 기간은 전주 토요일로부터 과거 28일입니다. 

계산 방식은 기간중 키워드별, PC통검/모바일 검색 별로 노출이 발생한 모든 광고의 입찰가를 
품질지수 일반화하여 모은 다음 순위별로 단순평균한 값입니다. 

조회시 제공되는 값은 특정 등록 키워드를 기준으로 조회(type = IDd 인경우) 조회 대상 등록 키워드의 
품질지수를 반영 하여 입찰가를 계산하여 제공하며 키워드명 자체로 조회 하실 때는 품질지수 4단계를 
기준으로 값을 계산하여 제공합니다. 

또한 제공드리는 값은 요일별 변동성을 반영 하여 제공드리고 있습니다. 

결론적으로 1) 원본 데이터는 1주일 내내 변경 되지 않음. 2) 요일 단위로 가중치를 반영함. 
3) 품질지수는 반영 된 값임 입니다. 

estimate 로 제공되는 정보들의 생성 로직과 기반 데이터 기준은 모두 공개하고 있사오니 
추가로 궁금하신 점은 언제든 문의 부탁드립니다. 

마지막으로 해당 정보는 한시간 단위로는 생성하지 않기도 하며, 
앞으로도 한 시간 단위로 정보를 생성하여 제공 드릴 계획은 없습니다. 

감사합니다.
