### ISSUE TITLE
campaign api 관련 문의 입니다.

### ISSUE THREAD

**Issue by younseunghyun** [naver/searchad-apidoc#16]
안녕하세요

campaign 관련하여 문의 드릴게 있습니다.

현재 campaign update api는 userLock만 제공 되는 것으로 보입니다.

다른 항목들을 업데이트 할 수 있는 api는 제공을 안 할 것인지, 안하는 것인지 궁금합니다.

감사합니다 :)

**Comment by premierman** [comment]
현재까지는 캠페인 update api에서 userLock만  제공되는게 정책입니다.
향후  userLock외에 다른 항목도 수정 가능하게  반영, 오픈 예정이오니 참고 부탁드립니다

**Comment by naver-searchad** [comment]
현재까지는 캠페인 update api에서 userLock만 제공되는게 정책입니다.
향후 userLock외에 다른 항목도 수정 가능하게 반영, 오픈 예정이오니 참고 부탁드립니다

**Comment by younseunghyun** [comment]
감사합니다 ::)
