### ISSUE TITLE
키워드 1월~11월 조회수를 알 수 있나요?

### ISSUE THREAD

**Issue by jxamen** [naver/searchad-apidoc#160]
$keywords = array(
					'format'	=>'json',
					'siteId'	=>'',
					'mobileSiteId'=>'',
					'hintKeywords'	=>$keyword,
					'includeHintKeywords'	=>'0',
					'showDetail'	=>'1',
					'biztpId'	=>'',
					'mobileBiztpId'=>'',
					'month'	=>'1',
					'event'	=>'',
					'keyword'	=>'',
				);
			$k_data = $this->GET('/keywordstool',$keywords);
			//print_r($k_data);exit;

이런식으로 month 파라미터를 바꿔서 조회를 해보면 동일한 데이터만 나오네요.

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API 입니다. 

month 파라미터는 특정 월에 연관된 키워드를 조회 하는 옵션입니다.

API 서비스에서는 과거 특정 기간의 검색수 정보를 제공하지 않습니다. 
또한 향후 제공 가능성도 무척 낮다고 예상하고 있습니다.

감사합니다.
