### ISSUE TITLE
AdKeyword: create API  호출 관련 문의입니다.

### ISSUE THREAD

**Issue by phc118** [naver/searchad-apidoc#161]
키워드 create API 테스트중인데 이런 응답이 왔는데 무슨 경우일까요?

API 문서에 create 는 post 로 되어있어서 HttpPost 타입으로 호출을 했습니다.

X-Transaction-ID:B760852THHITQ#_#Method Not Allowed#_#Request method 'POST' not supported

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요.
네이버 검색광고 입니다.

전달해주신 트랜잭션 ID 의 request URI 는 아래와 같습니다.
- `/api/ncc/keywords/grp-a001-01-000000007037244`

위의 URI 에서 광고그룹 ID 를 제거하고 아래와 같은 형태의 URI 로 호출되어야 합니다.
- `/api/ncc/keywords`
