### ISSUE TITLE
/billing/bizmoney/cost 사용시 날짜 값

### ISSUE THREAD

**Issue by k54821** [naver/searchad-apidoc#162]
안녕하세요. 

GET("/billing/bizmoney/cost", array('statDt' => '20181126')

사용하면 리턴되는 값에 날짜가 하루 전에 값이 나옵니다. 

Array
--
  | (
  | [0] => Array
  | (
  | [customerId] =>
  | [date] => 2018-11-25T15:00:00.000Z
  | [productCode] => SHOPPING
  | [device] => PC
  | [networkType] => NAVER
  | [refundableAmt] => 3322
  | [nonRefundableAmt] => 0
  | )
  |  
  | [1] => Array
  | (
  | [customerId] =>
  | [date] => 2018-11-25T15:00:00.000Z
  | [productCode] => SHOPPING
  | [device] => MOBILE
  | [networkType] => NAVER
  | [refundableAmt] => 8052
  | [nonRefundableAmt] => 0
  | )
  |  
  | )

**Comment by naver-searchad** [comment]
안녕하세요. 검색광고 API입니다. 

호출시 인자는 KST 기준 으로 받았으나 
리턴 값의 일자는 UTC(GMT, 줄루타임) 로 변환하여 제공드리고 있습니다. 

저희 타 API들의 규약에도 어긋나고 혼돈을 드릴 수 있는 방식이라 저희도 고민이 많습니다만..
이미 서비스중이고 많은 분들이 KST로호출하고 게신 API라 쉽게 수정하기가 조금 난처한 상황입니다. 

방안을 좀 논의하여 추가로 KST 일자를 드린다던가 하는 안을 고민해 보겠습니다.

감사합니다.
