### ISSUE TITLE
AdKeyword update로 field=inspect일 경우 질문

### ISSUE THREAD

**Issue by 0xB4DF4C3D** [naver/searchad-apidoc#163]
api 문서를 봐도 잘 모르겠어서 직접 요청을 날려보니까
노출 제한이었던 키워드가 다시 Under review 상태로 바뀌는걸로 보아 해당 API의 기능은
BusinessChannel API의 update에서 field=inspect인 경우와 동일한걸로 추측했습니다.

그런데 BusinessChannel.update.inspect API는 inspectRequestMsg 파라미터가 있어서 재검수 요청시 메세지를 보낼 수 있었는데 AdKeyword.update.inspect API 에서는 그런게 없는건가요?

아니면 API문서에 적혀져 있지 않지만 똑같이 body에 inspectRequestMsg를 명시해주면 메세지가 가는건가요?

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요
네이버 검색광고 입니다.

`AdKeyword` 의 경우 검수요청을 위한 update 요청시 `검수요청메세지`를 설정할 수 있는데
API 문서에 누락이 있었습니다.
언급해주신대로 `inspectRequestMsg` 를 명시한다면 `검수요청메세지`가 설정됩니다.

빠른시일내에 문서 업데이트 하도록 하겠습니다.

**Comment by 0xB4DF4C3D** [comment]
그렇군요.

감사합니다.
