### ISSUE TITLE
Region Code에 관한 문의입니다 

### ISSUE THREAD

**Issue by jinwoo8333** [naver/searchad-apidoc#164]
00 = 해외
-1 = 미분류
99 = 국내
01 = 강원도
02 = 경기도
03 = 경상남도
04 = 경상북도
05 = 광주광역시
06 = 대구광역시
07 = 대전광역시
08 = 부산광역시
09 = 서울특별시
10 = 울산광역시
11 = 인천광역시
12 = 전라남도
13 = 전라북도
14 = 제주특별자치도
15 = 충청남도
16 = 충청북도
17 = 세종특별자치시

이렇게 알고 있는데 네이버 광고관리 시스템에서 보는것과 API로 받아온 tsv랑 차이가 너무 심하게 나서
위의 코드가 맞는지 확인 부탁드립니다

틀리다면 전체적으로 코드 = 지역명 알려주시면 감사하겠습니다
(저번에 업데이트 해주신댔는데 안해주셨어요.....)

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

지역코드가 향후 임의 변경 가능성이 있어 데이터 확인 및 방안 마련중입니다.
중간에라도 상황을 말씀드렸어야 했는데 제가 말씀을 드리지 않았네요. 
사과의 말씀 드립니다.
참고 : https://github.com/naver/searchad-apidoc/issues/135

거의 정리가 되어 가니 금주내로 공지를 드리도록 하겠습니다.(물론 이 이슈에도 답변을 다시 드리도록 하겠습니다.)

감사합니다.

**Comment by jinwoo8333** [comment]
@naver-searchad 네 알겠습니다 꼭 알려주세요 ! : )

**Comment by jinwoo8333** [comment]
@naver-searchad 답변 감사합니다 저도 장기간 회사를 못나왔었는데 오늘 나와서 확인하게 되서 기쁩니다 : )

일단 문의 드릴 사항이 있습니다.

1. 커스터머아이디 : 941821
2. 날짜 : 2018년 12월 25일
3. 성과 상세 보고서 (AD_DETAIL)

오늘 오전에 api를 통해서 받아온 데이터 (노출수)를 조회해서 보면 네이버 광고 관리 시스템과 맞지 않습니다.
tsv상 노출수는 1,205,159 이지만, 네이버 광고 관리 시스템에서는 1,140,475 입니다
노출수 64,684 건이 붕 떠버립니다

혹시나 해서 tsv를 다시 받아도 결과는 같습니다.
이건 어떤 차이인지 알고 싶습니다.

(예전에 지역코드를 물어본 이유가 수치가 안맞아서 여쭤봤습니다ㅠㅠ)

**Comment by jinwoo8333** [comment]
@naver-searchad 

네이버 광고 관리 시스템에서 알림메세지를 확인했습니다.

**지역, 상세 지역 항목은 파워링크 캠페인과 파워컨텐츠 캠페인, 플레이스 캠페인에서만 제공합니다.**

위의 내용에서 궁금한게 API로 tsv를 가져왔을때 (광고성과상세보고서)
브랜드검색 및 쇼핑광고도 지역 코드가 들어가있던데
이 해당 코드는 맞지 않는건가요 '' ?

포함되지 않은 이유를 알고 싶습니다 : )

**Comment by naver-searchad** [comment]
안녕하셔요 검색광고 API입니다. 


아마도 다차원보고서에서 말씀주신 메세지를 보셨을 것 같습니다. 
다차원 보고서나 광고관리내 보고서에서 지역 데이터를 제공드리지 않는 이유는 쇼핑 캠페인이나 브랜드 검색 키워드에 지역 타게팅이 존재하지 않기 때문이 가장 큰 이유입니다. 
즉 보고서의 성과를 보고 지역 타게팅을 설정하고자 하더라도 이를 설정할 수 없기 떄문이 
가장 큰 이유입니다. 

쇼핑의 경우 통상 전국을 영업대상으로 하기 때문에 지역 타게팅이 가지는 가치는 상당히 찾고 
브랜드 검색 브랜드 정보 제공이라는 측면에서 
역시 특정 지역별로 특정 소재를 노출하는 니즈 등이 낮기 때문에 제공드리지 않습니다. 

그러나 대용량 다운로드 보고서(API에서는 STATREPORT)에서는 타게팅 목적외의 세부적인 지표 분석의 
Needs가 있으신 경우를 대비하여 제공드리고 있습니다. (즉 데이터를 꼭 필요하신 분들께만 
제공드린다는 컨셉입니다.)
또한 API의 대용량다운로드 보고서(STATREPORT)의 광고 효과 디테일에서 제공드리는 정보는 유효 클릭/노출로그를 단지 한시간 단위로 합산해서 제공드리는 형태이므로 데이터 자체는 광고 노출 시 로깅된 즉 확인된 데이터입니다. 

감사합니다.
