### ISSUE TITLE
너무 죄송해서... 너무 초보라 부끄럽고... php관련 

### ISSUE THREAD

**Issue by madeul** [naver/searchad-apidoc#165]
제가 정말 이슈에 있는 글들을 다 읽어보고
php샘플도 봤는데 저 같은 초보는 여기에 오면 안되는 곳인거라는 것을 느꼈지만
공부하고 싶은 마음에...

질문드려봅니다.
/ncc/keywords/{nccKeywordId}{?fields}

이런식의 폴더?를 자주 보는데
이걸 어떻게 사용하는건지 도무지 예제가 없으니 알수가 업습니다.

제가 도메인에 php샘플 소스들을 다 넣었는데
가령 아래 주소에 넣었습니다.
도메인주소/ad_management_sample.php

/ncc/keywords/{nccKeywordId}{?fields} <- 요런거를 사용하고 싶은데
ncc 폴더가 어디에 있는 건가요?^^;;;;
이게 네이버에 있는거면 그냥
https://api.naver.com/ncc/keywords/{광고아이디}{?fields} 요렇게 해서 사용하는 건가요?

**Comment by naver-searchad** [comment]
안녕하세요 네이버 검색광고 입니다.

문의주신 API는 키워드의 특정 필드들을 업데이트 하는 것입니다.
`{?fields}` 는 업데이트 하고자 하는 필드를 지정할 수 있고 이를 `query 파라메터`로 전달 가능하다는 것입니다.
먼저 아래의 문서를 참조 부탁드립니다.
- http://naver.github.io/searchad-apidoc/#/operations/PUT/~2Fncc~2Fkeywords~2F%7BnccKeywordId%7D%7B%3Ffields%7D
- 조금만 내려보시면 `Query parameters` 항목이 보이고 어떤 필드들을 업데이트 할 수 있는지를 명시하고 있습니다.

예를 들어 keyword id 가 `nkw-a001-01-000000000000001` 이고 입찰가를 업데이트 하려는 경우 아래와 같은 요청을 만들어서 API 를 호출하시면 됩니다.

- request url: `.../keywords/nkw-a001-01-000000000000001?fields=bidAmt`
- request body
```json
{
  "bidAmt": 100,
  "useGroupBidAmt": false
}
```
