### ISSUE TITLE
stats의 avgRnk 항목 관련하여 질문 있습니다.

### ISSUE THREAD

**Issue by kaorimikage** [naver/searchad-apidoc#166]
stats에서 fields의 avgRnk 항목이 실적에 따른 평균 노출 순위인것으로 알고 있습니다.

해당 항목에 대하여 datePreset 을 last30days 을 하면 값을 주긴 하는데 PC하고 모바일에 대한 구분이 되어 있지 않더군요. 해당 값이 어떻게 산출되나 하여 확인해보니 (PC + 모바일) / 2 로 되어 있는것 같습니다. 그냥 PC와 모바일을 분리해서 주실순 없는지요.

아니면 breakdown 을 pcMblTp 으로 주니 PC와 모바일 데이터를 분리해서 주긴하던데 최근 7일간의 데이터만 취득이 가능합니다. 이 부분에 대하여 기간을 좀 더 늘려주셨으면 합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API 입니다. 

보고서는 크게 stat과 statreport가 있습니다. 
statreport는 거의 가공되지 않은 raw데이터 형태로 보고서 지표들을 제공드리는 보고서로 
평균 노출 순위를 틀정 매체/지역/시간대까지 분류해서 계산하실 수 있습니다. 
STAT이 자유도가 거의 없는 대신 일정 형태로 미리 계산된 값을 제공드리는 반면 
STATREPORT는 RAW데이터를 제공드려 자유롭게 원하시는 형태로 데이터를 가공하실 수 있는데 
그 의미가 있는 보고서입니다.

제공 기간은 가장상세한 ad_detail 보고서의 경우 과거 180일까지 제공드리고 있습니다.
레퍼런스 : http://naver.github.io/searchad-apidoc/#/tags/StatReport
참고로 평균 노출순위의 계산식은 노출순위 합 필드를 노출수로 나누시면 것입니다.

감사합니다.
