### ISSUE TITLE
노출가능광고개수는 어떻게 얻을 수 있을까요?

### ISSUE THREAD

**Issue by wert321** [naver/searchad-apidoc#168]
또 PC 노출가능광고개수 뿐만 아니라 모바일 노출가능광고개수도 확인하는 방법이 없을까요?

**Comment by wert321** [comment]
그렇다면 PC노출가능광고개수는 어디에서 확인할 수 있을까요???? 도큐먼트를 아무리 뒤져봐도 보이지가 않습니다

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

ManagedKeyword(http://naver.github.io/searchad-apidoc/#/tags/ManagedKeyword)
에서 개별 키워드별로 PCPLMaxDepth 항목을 조회해 보시면 되겠습니다.

감사합니다.
