### ISSUE TITLE
AdKeyword의 검색횟수를 확인할 수 있을까요?

### ISSUE THREAD

**Issue by wert321** [naver/searchad-apidoc#169]
키워드의 노출수(impCnt)는 제공되는 것으로 알고 있습니다만, 해당 키워드를 유저들이 검색하는 횟수를 알 수 있는 방법은 없을까요?

노출되지 않은 키워드들의 평균노출순위는 무조건 0이 되는데, 그게 검색이 되어도 노출순위에 들지 못해서 0인 것인지 아니면 검색이 전혀 되지 않아서 0으로 표시되는 것인지 확인할 방법이 없네요......

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다.

우선 답변이 늦어 죄송합니다. 

특정 키워드의 검색수는 http://naver.github.io/searchad-apidoc/#/tags/RelKwdStat 기능으로 확인이 가능하십니다. 

주의 하실 점은 위 정보는 월(30일) 합산 검색수로 매일 일단위 업데이트 되며, 스케일링 적용되어 있어정확한 값이 아니라는 점입니다. 

따라서 말씀 처럼 랭킹에 들어가지 못해서 노출이 되지 못한것인지, 혹은 순위에 들어가지 못해서 노출이없는 것인지 특정 일자 단위로 정확하게 확인할 방법은 현재 저희 제공 데이터로는 확인이 어렵습니다.

감사합니다.
