### ISSUE TITLE
keyword update api관련 문의입니다.

### ISSUE THREAD

**Issue by younseunghyun** [naver/searchad-apidoc#17]
안녕하세요 :)

keyword update 관련 문의 입니다.

문서상에서 fields에 파라미터를 넣어서 PUT request를 보내면 update가 가능하도록 명시되어 있는데,

fields에 한개의 update fields가 아닌 여러개의 필드가 올 수 있는지요?

`PUT /ncc/keywords/nkw-a001-01-000000075205659?fields=bidAmt,links,userLock`

위의 방법으로 시도를 하는데,  userLock에 관련된 필드만 업데이트 되는 것으로 보입니다.

사용방법이 잘 못 된 것인지, 위의 방법 처럼 동작을 하지 않는 것인지 궁금 합니다.

감사합니다 :)

**Comment by naver-searchad** [comment]
@younseunghyun 
안녕하세요~
fileds는 한번에 한개만 처리가 되도록 구현이 되어 있습니다.
동시에 업데이트 되지 않으니 각 필드당 한번씩 요청해 주시면 감사하겠습니다.

**Comment by younseunghyun** [comment]
감사합니다 :)
