### ISSUE TITLE
소재 생성시 쇼핑몰ID

### ISSUE THREAD

**Issue by JMKim74** [naver/searchad-apidoc#170]
수고많으십니다.
소재 생성시 네이버쇼핑ID를 넣도록 되어있는데요.
쇼핑몰ID를 넣어서 생성할 수는 없는지요?

혹 불가능하다면  쇼핑몰ID를 네이버쇼핑ID로 변환할 수 있는 방법을 문의드립니다.
광고시스템의 소재등록시 방법을 따라하니 401 에러를 보냅니다.
감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요, 검색광고 API 입니다.

소재는 네이버쇼핑ID 로만 생성할 수 있습니다.
네이버 검색광고에서는 광고주님의 네이버쇼핑몰ID와 쇼핑ID 정보를 직접적으로 가지고 있지 않아서, 쇼핑몰ID를 네이버쇼핑ID로 변환할 수 있는 방법를 제공해드리가 어렵습니다.
번거로우시겠지만 네이버 쇼핑 사이트에서 쇼핑ID를 조회하시어 소재 등록 부탁 드리겠습니다.

감사합니다.
