### ISSUE TITLE
기업강의 관련해서 여쭤볼게 있어서 질문드립니다. 

### ISSUE THREAD

**Issue by EDMAI** [naver/searchad-apidoc#171]
안녕하세요, 이번에 기업강의로 간단한 크롤링 시연을 하려고 하는데요,

네이버 뉴스기사던 검색결과던 블로그 글이던 카페글이던 간에

headless chrome 브라우저로 xpath사용해서 

사람당 열번 정도 내외로 크롤링 해보는 시간을 가지려고 하는데요,

저 포함 대략 10명이서 진행할 것 같습니다. 

하는 인원들은 대부분 초보자들이고요. 

기업강의에서 간단하게 크롤링 가능한지 해서 여쭤봅니다. 

감사합니다.

**Comment by wert321** [comment]
from bs4 import BeautifulSoup
import urllib.request as req
from urllib.parse import quote

search_keyword = '블라블라'
byte_keyword = quote(search_keyword)
url = 'https://search.naver.com/search.naver?sm=top_hty&fbm=1&ie=utf8&query='+byte_keyword
json_data = req.urlopen(url).read()
soup = BeautifulSoup(json_data, 'html.parser')

네이버 검색이야 어차피 오픈 소스인데 굳이 허락맡고 해야되나요? 그리고 여기는 네이버 광고 api 관련해 기술적인 부분을 묻는 곳이지, 허락을 맡는곳이 아니에요

위에 코드는 네이버 광고 크롤링하는 파이썬 코드인데 도움될까 싶아서 남겨봅니다

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

이 깃텁은 네이버 검색광고 API에 관한 기술 지원을 해드리는 용도로 개설 되었다는 점 우선 안내 드리오니 향후 이용시 참고해 주시기 바랍니다.

문의 주신 사항에 대해서는 
네이버 약관 및 개인정보 보호 페이지 중 검색결과 수집에 대한 정책(https://policy.naver.com/policy/search_policy.html ) 페이지 4번 항목을 참고해 주시기를 부탁드립니다.

감사합니다.
