### ISSUE TITLE
소재별 입찰가 순위

### ISSUE THREAD

**Issue by JMKim74** [naver/searchad-apidoc#172]
수고많으십니다.

소재의 평균 입찰가 순위에 대해 문의드립니다.

소재의 평균 입찰가 순위를 /npc-estimate/average-position-bid/id 로 조회시 API 문서에 the position for a targetted keyword. valid range: 1-15 on PC, 1-5 on MOBILE로 PC의 position을 1~15로 설정 할수 있도록 되어있었습니다.

그런데 항상 3위부터 무조건 50원이 나오네요. 
3위 부터는 조회가 안되는 건지 아니면 아니면 값이 잘못된건지 확인 부탁드립니다.

감사합니다.

**Comment by naver-searchad** [comment]
파워컨텐츠 상품의 경우 1위에서 3위까지만 데이타가 존재합니다.
3위보다 큰 데이타를 요청할 경우 기본 입찰가만 반환됩니다.
API 가이드는 아래 문서 참고하시기 바랍니다.

http://naver.github.io/searchad-apidoc/#/definitions/NpcKeyAndPosition
