### ISSUE TITLE
isLowSearchVolume 속성에 대하여 문의드립니다.

### ISSUE THREAD

**Issue by Daniel-Dobal-Oh** [naver/searchad-apidoc#173]
isLowSearchVolume 속성에 "기간"에 대한 개념이 포함되어 있을런지요?
예를 들어 A라는 키워드가 1달 전에는 검색이 많이 되었으나, 
최근 1달에는 검색이 안되어 low searchvolume으로 간주되는 식으로요.

기간 개념이 포함되어 있다면, 한번 조회된 low search volume 키워드에 대해
일정기간 api를 호출하지 않도록 하려고 합니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

적은 검색량은 상당히 긴 기간(대략 말씀 드리면 년단위에 가깝습니다.)을 기준으로 합니다만 세부 기준을 밝히고 있지 않습니다. 단 적은 검색량 플래그는 기간 기준에만 국한되었다기 보다는 저희가 판단하기에 대상 키워드나 주제에 대한 사용자들의 관심이 증가할 만한 특별한 이벤트가 없는 것을 가정할 때 검색될 가능성이 극히 낮은 키워드가 지정된다고 이해해 주시면 되겠습니다. 

사용 목적과 전략에 따라서 다르시겠지만 말씀 주신 호출량을 줄이는 목적에만 국한되면 월단위 조회 정도로도 충분한 트래킹이 가능하시리라 생각 됩니다. 

감사합니다.

**Comment by Daniel-Dobal-Oh** [comment]
빠른 답변 고맙습니다.
