### ISSUE TITLE
매니저 아이디에 소속된 계정들 정보중 상세정보는 못가지고 오나요??

### ISSUE THREAD

**Issue by psychodoma** [naver/searchad-apidoc#175]
매니저 아이디에 소속된 계정들을 모두 가지고 오는건 확인하였습니다.

그런데 그 값들이 로그인 아이디, 계정id, 이런 부분만 가지고 오고 

상세한 값은 가지고 오지 못하더라고요..(예를들어 사이트주소, 계정주성함 등..) 

그래서 한눈에 보기에 이 계정이 누구계정이고 그런걸 바로 판별하기 어려워서 가지고 오고 싶은데..

현재
$api->GET('/customer-links', array('type' => 'MYCLIENTS'));
이런식으로해서 데이터를 가지고 옵니다.

여기서 상세한 정보를 볼려면 위에 customer-links 에서 얻은 값중 하나의 계정id를 선택해서
$api->GET('/ncc/channels');
여기로 보내서 얻어 오는 방법 밖에 없나요??

등록 계정이 몇천개 인데 이걸 하나하나 이렇게 하는게 불가능해서 
한번에 가지고 올 수 있는 방법이 있는지 궁금합니다!

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

우선 성함이나 연락처 등 계정 소유주에 관련 된 정보, 특히 개인정보 관련 사항은
API를 통해 제공되지 않습니다. 

이외의 사이트 주소등 
현재 API서비스에서는 권한 가지고 있는 모든 계정의 특정 정보를 일괄로 제공하는 기능은 아직 마련 되어 있지 않아 개별 조회를 하시는 방법 밖에는 없습니다.
추후 비즈채널 정보까지는 권한 기준으로 제공할 예정에 있기는 하나 아직 일정이 잡혀 있지는 않은 상황입니다. 

감사합니다.

**Comment by psychodoma** [comment]
> 안녕하십니까 검색광고 API입니다.
> 
> 우선 성함이나 연락처 등 계정 소유주에 관련 된 정보, 특히 개인정보 관련 사항은
> API를 통해 제공되지 않습니다.
> 
> 이외의 사이트 주소등
> 현재 API서비스에서는 권한 가지고 있는 모든 계정의 특정 정보를 일괄로 제공하는 기능은 아직 마련 되어 있지 않아 개별 조회를 하시는 방법 밖에는 없습니다.
> 추후 비즈채널 정보까지는 권한 기준으로 제공할 예정에 있기는 하나 아직 일정이 잡혀 있지는 않은 상황입니다.
> 
> 감사합니다.

gjh

**Comment by psychodoma** [comment]
kl;k
