### ISSUE TITLE
stat-reports download 날짜기간 설정 가능한가요??

### ISSUE THREAD

**Issue by psychodoma** [naver/searchad-apidoc#176]
안녕하세요 혹시 네이버 광고 api 궁금한게 있어서 글올렸습니다.

$stat_req = array(

"reportTp" => $reportType, //타입

"statDt" => 원하는 날짜 입력// 1일 단위

);

$api->POST("/stat-reports", $stat_req);

이런식으로 날짜에 해당하는 데이터를 다운 받습니다.

그런데 날짜가 1일 단위밖에 안되는건가요?? 가이드를 찾아봐도 이부분에 언급이 없내용..

저는 월 단위라던가 적어도 주단이라도 받고 싶은데.. 가능한지 궁금합니다!

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다 

STAT_REPORT는 한번 생성 호출시 1일 단위 데이터생성이 가능합니다. 

기간을 길제 제공하지 못하는 이유는 속도와 데이터양 때문으로 
당분간을 기간 기준으로 데이터를 제공드릴 계획이 없습니다. 

감사합니다.
