### ISSUE TITLE
광고그룹의 이름을 변경하는 API는 없나요?

### ISSUE THREAD

**Issue by 0xB4DF4C3D** [naver/searchad-apidoc#178]
현재 1682개의 광고그룹을 운영중인데
용이한 관리를 위해 이 광고그룹 이름들을 일정한 포맷에 맞춰 변경하고 싶습니다.

찾아봤는데 아무래도 이 기능은 API로 제공되지 않는것 같아요.

질문을 바꿔 다시 말하면 광고그룹의 이름을 변경하는 API를 만들어주실 수 있으신가요?

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요?
아래의 API를 이용하여 변경가능합니다.
* http://naver.github.io/searchad-apidoc/#/operations/PUT/~2Fncc~2Fadgroups~2F%7BadgroupId%7D

하지만 주의하셔야할 내용은 `name 외 다른 값들은 기존 값을 넣어 주셔야` 합니다. 이 API는 이름만 변경하지 않고 설정된 여러개의 값을 동시에 변경하는 기능을 합니다.

만약 이름만 변경하고자 한다면 아래의 API를 사용하면 됩니다. 하지만 `이 API는 현재 지원되고 있지 않고, 2019년 2월 14일 부터 지원될 예정`입니다.  
* http://naver.github.io/searchad-apidoc/#/operations/PUT/~2Fncc~2Fadgroups~2F%7BadgroupId%7D%7B%3Ffields%7D
