### ISSUE TITLE
nccCampaignId를 키로 얻어온 adGroup에 Target 정보가 없습니다. 

### ISSUE THREAD

**Issue by dreamersnme** [naver/searchad-apidoc#179]
광고 그룹 ID를 사용해서 GET /ncc/adgroups{?ids} 로 객체를 받았을 때에는 
해당 그룹의 Targets 정보를 잘 받을 수 있는데요, 

캠페인 ID를 키로 사용해서 /ncc/adgroups{?nccCampaignId} 를 사용해서 광고그룹을 받으면, 
대부분의 adGroup 객체에 targets 정보가 없습니다. 

동일한 광고그룹ID (grp-a001-01-000000008532359)를 사용하여 확인하였습니다. 
이유가 무엇인가요?

캠페인 ID로 모든 하위 그룹의 target  포함 정보를 한꺼번에 가져오고 싶은데, 다른 방식이 있을까요?

**Comment by naver-searchad** [comment]
안녕하세요?

여러개의 그룹을 동시에 조회할 때에는 타겟팅 정보가 포함되지 않습니다. 하지만 단건에 대한 조회는 타겟팅이 포함되어 있습니다.
타겟팅 정보는 아래의 API를 이용하여 따로 조회하셔야 합니다.

* http://naver.github.io/searchad-apidoc/#/operations/GET/~2Fncc~2Ftargets%7B%3Ftypes,ownerIds%7D

캠페인 하위의 그룹에 대한 모든 타겟팅 조회는 아래와 같은 순서로 진행하시면 됩니다.

1. 캠페인 하위의 그룹목록 조회
2. 조회된 그룹 ID목록으로 타겟팅 조회

감사합니다.
