### ISSUE TITLE
그룹 내 키워드 갯수를 API를 통해 조회가능한가요?

### ISSUE THREAD

**Issue by ncrash** [naver/searchad-apidoc#18]
![image](https://cloud.githubusercontent.com/assets/153414/17501448/d04287ce-5e19-11e6-8cbd-8a6a8239f95e.png)

위 캡쳐화면에서 **키워드 840개 결과** 부분을 API를 통해 가져오고 싶습니다.
API 문서에서는 해당 데이터를 제공하지 않는것으로 보이는데 확인 부탁 드립니다.

**Comment by bluewings** [comment]
안녕하세요. 키워드광고 웹버전도 동일한 API 를 사용하고 있습니다. API 에서 제공되는 값은 아닙니다.
해당 숫자는 클라이언트(브라우저)에서 ```GET /api/keywords``` 을 통해 받아온 데이터를 조건에 따라 필터링한 후 개수를 카운트 한 값입니다.

**Comment by naver-searchad** [comment]
키워드광고 웹버전도 동일한 API 를 사용하고 있습니다. API 에서 제공되는 값은 아닙니다.
해당 숫자는 클라이언트(브라우저)에서 ```GET /api/keywords``` 을 통해 받아온 데이터를 조건에 따라 필터링한 후 개수를 카운트 한 값입니다.

**Comment by ncrash** [comment]
HTTP HEAD 메소드로 키워드 갯수만 리턴받을 수는 없을까요?
시도 해보니 405 Method Not Allowed 상태코드를 리턴해 주네요
API를 통해 얻고자 하는 정보는 키워드 갯수만 확인하면 되는것이라 추가적으로 질문 드립니다.

**Comment by naver-searchad** [comment]
요청 주신 기능에 대해서 검토가 되었으나, 조회 후 카운트 하면 알 수 있는 기능이기 때문에 지금은 제공 계획이 없습니다.
개수를 카운트해서 사용해 주세요.
감사합니다.
