### ISSUE TITLE
StatReport API에서 AD 리포트 cost 데이터 타입 변경된건가요??

### ISSUE THREAD

**Issue by wooram1125** [naver/searchad-apidoc#180]
float 형으로 변경된거 같은데, 공지 내용이 없어서 확인 문의드립니다
감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

공지 현재 작성 중입니다. 

필드 스팩이 real 이었는데 마치 integer인 것처럼 제공 드리고 있어서 스팩에 맞춰 real 형으로 변경 작업을 하였습니다. 

영향성 범위 판단에 착오가 있어 선공지를 하지 못한점 사과말씀 드립니다.

감사합니다.

**Comment by wooram1125** [comment]
확인 감사합니다.
