### ISSUE TITLE
광고그룹의 [키워드 확장] 여부 가져오기 

### ISSUE THREAD

**Issue by dreamersnme** [naver/searchad-apidoc#181]
네이버 광고 싸이트의 광고관리에서 보면, [키워드 확장 beta] 에서 사용여부를 설정 할 수 있습니다. 
API로 해당 정보는 어떻게 가져와야 하나요?

**Comment by naver-searchad** [comment]
안녕하세요?

키워드 확장 beta에 대한 API는 아래의 API를 이용하실수 있습니다.
* 조회 : http://naver.github.io/searchad-apidoc/#/operations/GET/~2Fncc~2Fadgroups~2F%7BadgroupId%7D~2Frestricted-keywords%3Ftype=KEYWORD_PLUS_RESTRICT
* 키워드 추가 : http://naver.github.io/searchad-apidoc/#/operations/POST/~2Fncc~2Fadgroups~2F%7BadgroupId%7D~2Frestricted-keywords
* 삭제 : http://naver.github.io/searchad-apidoc/#/operations/DELETE/~2Fncc~2Fadgroups~2F%7BadgroupId%7D~2Frestricted-keywords%7B%3Fids%7D
