### ISSUE TITLE
오늘 당일의 keyword별 performance를 가져오고 싶습니다. 

### ISSUE THREAD

**Issue by SukHoon-Jung** [naver/searchad-apidoc#182]
과거의 광고 키워드 별  performance 지표는 StatReport type =AD 를 통하여 전체키워드를 벌크로 가져오고 있습니다. 
그런데 StatReport 로 오늘 당일 자의 performance 를 불러오는 것은 불가능 한 것 같습니다. 다음과 같은  response가 나옵니다.
{"code":11001,"message":"잘못된 파라미터 형식입니다."}

혹시 당일에 대하여, 현재 시각 까지의 모든 키워드 별 PERFORMANCE를 벌크로 받아올 수 있는 방법은 없을까요?

Stat: get (by ids)를 통해 DatePreset = today 설정으로 가져오는 법이 있기는 하지만, 
한번에 가져올 수 있는 ID 개수가 너무 한정적 인 것 같습니다. 
 
추가로..
Stat: get (by ids) 로 키워드별 퍼포먼스를 가져온다면, 
A. 1회에 가져올수 있는 ID 개수는 몇 개인가요?
B. 당일 실적이 발생한 키워드 ID를 알 수 있는 방법이 있을까요?. 실적이 발생하지 않은 키워드도 Stat: get (by ids) 로 호출한다면, 호출량이 매우 많을 것 같습니다.

**Comment by naver-searchad** [comment]
안녕하세요 네이버 검색광고 API입니다.

저희가 Stat, StatReport 2가지의 지표 API를 지원하고 있고, Stat API는 당일지표를 지원합니다만, StatReport는 당일지표를 지원하고 있지 않습니다.
더불어 Stat API는 200개 초과의 ID에 대한 대용량 조회 기능을 지원하고 있지 않습니다.

그리고 Estimate API는 광고주분들이 등록하신 키워드단위로 예측을 수행하는게 아니라,
통상적인 키워드에 대해 개략적인 예측만을 제공하고 있기 때문에
광고주개인별 키워드 ID 기준으로의 조회는 의미가 없습니다.
비슷한 맥락으로 특정날짜를 입력하지 않는 것도 날짜와 상관없이 개략적인 예측만을 제공하기 때문입니다.

감사합니다.
