### ISSUE TITLE
BRAND_SEARCH 광고그룹(Ad group) 생성 시 templateId

### ISSUE THREAD

**Issue by nyob3** [naver/searchad-apidoc#183]
![image](https://user-images.githubusercontent.com/29356782/52904004-a059ce00-3260-11e9-913b-3d0bcd9f8f29.png)
![image](https://user-images.githubusercontent.com/29356782/52904042-0c3c3680-3261-11e9-8600-f53973a4217c.png)
![image](https://user-images.githubusercontent.com/29356782/52904016-b2d40780-3260-11e9-8250-2563e8ba2857.png)

안녕하세요.

인터페이스에서 브랜드서치 광고그룹을 생성할 때 보면 여러 유형의 템플릿이 존재합니다.

같은 과정을 API를 통해 업로드 하고 싶은데요.

브랜드서치 유형의 광고그룹 생성 시에 adgroupAttrJson에 media와 templateId를 함께 POST 하는 것으로 안내 되어 있는 것으로 보아 브랜드서치 광고그룹을 생성하려면 템플릿 중 하나를 선택하고 이를 위해서는 해당 템플릿의 ID (templateId)를 알아야 하는 것 같은데요.

공식 문서에서는 어떤 템플릿이 어떤 id (API에서 받아들이는) 를 가지고 있는지 안내가 되어있지 않는 것 같아서 이렇게 Github 통해 문의드립니다.

templateId에 어떤 값을 넣고 POST 해야 BRAND_SEARCH 광고그룹을 API를 통해 생성할 수 있을까요?

**Comment by naver-searchad** [comment]
안녕하세요 네이버검색광고 api입니다.

문의하신 브랜드검색 템플릿 id를 별도로 api로 지원해 드리고 있지는 않습니다.
광고주센터 화면에서 브랜드검색 광고그룹을 등록하면서 나타나는 템플릿 id를 캐치해서
광고그룹 api에 담아 이용하실 수는 있겠지만 그리 권장하지는 않습니다.
브랜드검색 상품 자체가 api로 광고그룹을 많이 만들면서 진행하기보다는
등록된 광고그룹과 기간을 기준으로 '계약'을 생성해 가며 관리하는 상품이기 때문입니다.
더군다나 광고그룹 등록 후 키워드, 소재, 계약을 생성하는 경우에는
광고주센터 ui 상에서 여러 조건들과 인터페이싱 하면서 진행해야 하기 때문에
더더욱 api를 이용하는 것은 매우 어렵고 불편한 작업이 될 것입니다.
따라서 브랜드검색 상품은 광고주센터 화면을 통해 진행하시는 걸 추천드립니다.
