### ISSUE TITLE
안녕하세요 키워드 광고에서 상세데이터추출필터 설정 질문드립니다.

### ISSUE THREAD

**Issue by EDMAI** [naver/searchad-apidoc#184]
![image](https://user-images.githubusercontent.com/33061592/52985632-1e240200-3438-11e9-89b6-34426421cf1a.png)

상세데이터에서 pc/모바일 필터를 걸어서 노출/클릭/클릭비용을 추출하려는
api에서는 어떤방식으로 호출해야할까요? 
마스터리포트나 스탯리포트에 관련된 어떤 항목이 있을까요?
아니면 다른 방식이 있을까요?

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요 네이버 검색광고 API 입니다.

/stat 에서 PC/모바일을 구분하는 api는
breakdown=pcMblTp
조건으로 api를 호출하시면 됩니다.

api 상에서 필터 기능은 지원하지 않으므로 데이터를 가지고 가신 후에 필요한 것을 보여주거나 사용하시면 됩니다.

감사합니다.
