### ISSUE TITLE
[건의사항] 공지 사이트 장애 복구시까지 README 파일 업데이트 시 릴리즈 요청합니다.

### ISSUE THREAD

**Issue by joonhokim-recobell** [naver/searchad-apidoc#185]
현재 공지 사이트가 장애 중이라 검색 API 관련 알림을 못 받고 있습니다. 그래서 이 리포지토리 리드미 파일에 공지 사항을 업데이트 해주고 계신데, 문제는 공지를 올리셔도 저희가 알 길이 없습니다. 그렇다고 매일 아침 이 페이지를 들어와서 확인하는 건 너무 번거롭고요. 
그래서 Github 의 알림 기능을 이용해서 알림을 받을 수 있으면 좋을 것 같은데, Github에서는 어느 리포를 Watch 하고 있으면 새로운 릴리즈가 배포될때마다 알림을 받을 수 있습니다. 릴리즈하지 않고 그냥 README 파일을 업데이트 하는 것 만으로는 Watch 하고 있어도 알림이 오지 않고요. 
한 번 검토 부탁드립니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

앞으로 API 관련한 변경 및 점검공지는 http://naver.github.io/searchad-apidoc/#/release-notes 를 통해 이루어질 예정입니다.
3월내로 해당 페이지에서 rss로 feed 받으실 수 있는 링크도 같이 제공될 예정이니 참고 부탁드리며, rss feed가 생기는데로, 검색광고홈의 공지에 따로 전체 공지 예정입니다. 

감사합니다.
