### ISSUE TITLE
Adgroup Create에 관한 문의

### ISSUE THREAD

**Issue by phc118** [naver/searchad-apidoc#186]
안녕하세요,
Adgroup Create Api 를 테스트중입니다.
제가 SHOPPING Type Adgroup 을 생성하려고 테스트중인데,
다음과 같은 메세지를 응답 받았습니다. 

{"code":3725,"status":400,"title":"Unavailable channel type for campaign which the ad group belongs to."}
02-20 13:33:34 ERROR ApiCommonNaver.execute:266] 	X-Transaction-ID:B914N2B91HJ8E
java.lang.RuntimeException: X-Transaction-ID:B914N2B91HJ8E#_#Unavailable channel type for campaign which the ad group belongs to.

만들고자 하는 Adgroup이 속해있는 캠페인이 입력한 채널 타입과 맞지 않는다는 내용으로 보여집니다.
SHOPPING Type 그룹을 만들려면 어떤 타입의 채널이 필요한지, 
그러한 타입의 채널을 생성하려면 Business Channel API 를 활용하는 방법뿐인지.. 검색광고센터 UI 에는 채널만 따로 만드는기능을 찾을수가 없어서 질문드립니다.

감사합니다.

아 그리고 API 문서에 오타가 있습니다.
http://naver.github.io/searchad-apidoc/#/operations/POST/~2Fncc~2Fadgroups
adgroupType 필드에 입력값에서 SHOPPING 이 SHOPING 으로 나와있네요

**Comment by naver-searchad** [comment]
안녕하세요? 검색광고 API입니다.

`SHOPPING` 타입 그룹을 생성하기 위해서는 다음의 두가지 조건이 만족되어야 합니다.

1. 생성하고자 하는 그룹이 쇼핑 캠페인에 속해야 합니다.
쇼핑 캠페인은 캠페인의 `campaignTp`값이 `SHOPPING ` 입니다.
쇼핑 캠페인은 API를 이용하여 생성이 가능합니다.

2. 생성하는 그룹의 채널의 타입이 `MALL` 타입이어야 합니다.
`MALL`타입 채널은 검색광고 [광고주센터](https://searchad.naver.com)에서 생성가능합니다.
광고주센터의 `도구 > 비즈채널 관리` 화면에서 `채널 추가` 버튼 클릭후 `쇼핑몰`을 선택하여 생성 가능합니다.
