### ISSUE TITLE
Master Ad Report 다운로드시 일부 Ad 누락문제 관련

### ISSUE THREAD

**Issue by jjh4698** [naver/searchad-apidoc#187]
안녕하세요. 

쇼핑 검색 광고의 Ad 같은 경우, 
광고정보 일괄 다운로드 -> 소재 마스터 다운로드 시, 
데이터가 내려오지 않습니다. 

쇼핑 상품 마스터 조회시, ad 정보가 내려오긴 하나, 
각 쇼핑 검색 광고 ad 별 정보만 얻을 수 있는 레포트가 있는지 궁금합니다.

**Comment by naver-searchad** [comment]
안녕하세요.
소재 정보는 유형에 따라 분리되어 제공하고 있습니다.
아래 정보 참고하셔서 다운로드 하시기 바랍니다.

- 광고주센터에서 "대용량 다운로드 보고서 > 광고정보 일괄 다운로드" 이용 시
  - "소재(광고)마스터" -> 파워링크유형의 텍스트소재만 제공
  - "쇼핑상품마스터" -> 쇼핑검색유형의 상품노출 정보만 제공
  - "파워컨텐츠소재마스터" -> 파워컨텐츠유형의 정보제공형만 제공

- MasterReport API 이용시
  - item : "Ad" -> 파워링크유형의 텍스트소재만 제공
  - item : "ShoppingProduct" -> 쇼핑검색유형의 상품노출 정보만 제공
  - item : "ContentsAd" -> 파워컨텐츠유형의 정보제공형만 제공
  - item : "PlaceAd" -> 플레이스유형의 업체정보만 제공
  - item : "CatalogAd" -> 쇼핑검색유형의 제품카탈로그 정보만 제공
