### ISSUE TITLE
쇼핑 검색광고의 소재 생성 호출 에러 확인 부탁드립니다.

### ISSUE THREAD

**Issue by rasoio** [naver/searchad-apidoc#188]
쇼핑 검색 광고 소재 생성을 위해 남겨주신  [issue](https://github.com/naver/searchad-apidoc/issues/130) 를 참고 해서 호출해봤는데 아래와 같은 에러가 발생합니다.
```
{
  "code": 1018,
  "status": 404,
  "title": "No permission to access the resource."
}
```

response X-Transaction-ID 는 아래 값입니다.
```
X-Transaction-ID: B91U78I5HHHG1
```

확인 부탁드립니다.
감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요, 검색광고API 입니다.

접근 권한이 없어서 발생한 에러입니다.
소재 생성시 요청하신 광고그룹의 광고주와 서명 만드실 때 사용한 광고주ID가 일치하지 않습니다.
X-API-KEY 에 조회/생성할 광고주ID를 넣고 서명을 만들어 호출해주세요.

감사합니다.

**Comment by rasoio** [comment]
답변 감사합니다.

말씀해 주신 광고주ID 확인하고 요청 했는데요
아래와 같은 에러가 발생합니다.

```
{
  "code": 3830,
  "status": 400,
  "title": "Invalid ad type."
}
```
type 값은 "type":"SHOPPING_PRODUCT_AD" 로 호출했습니다.

response X-Transaction-ID 는 아래 값입니다.

```
X-Transaction-ID: B94T67B0HDJC9
```

확인 부탁드립니다.
감사합니다.

**Comment by naver-searchad** [comment]
@rasoio 
안녕하세요, 검색광고API 입니다.
소재의 타입별로 단수개로만 생성 가능한 API와 복수개로 생성 가능한 API가 나뉘어 존재합니다.
쇼핑소재는 복수개로만 생성 가능한 타입입니다.

호출값 확인 결과 소재 생성시 RequestBody 내용을 단수로 생성요청하시어 소재의 타입이 맞지 않다는 응답을 받으셨습니다.
요청 값을 `[]` 로 감싸서 호출하시면 정상 생성 될 것으로 보입니다.
감사합니다.

**Comment by rasoio** [comment]
빠른 답변 감사합니다.

복수개만 등록 가능하다고 하셔서 [issue](https://github.com/naver/searchad-apidoc/issues/108) 참고해서 아래 isList=true 파라메터 추가하고 array 로 감싸서 호출했습니다.

아래와 같은 에러가 발생하는데 등록 건수 제한에 걸려서 등록이 안되는건가요?
**혹시 복수개로 몇개까지 등록 가능한지도 추가로 확인 부탁드립니다. 가이드 문서나 링크가 존재하면 말씀 부탁드립니다.**

```
{
  "code": 1014,
  "status": 400,
  "title": "Cannot handle the request. The limit has been exceeded."
}
```

response X-Transaction-ID 는 아래 값입니다.

```
X-Transaction-ID: B950OJEDHHJDO
```

확인 부탁드립니다.
감사합니다.

**Comment by naver-searchad** [comment]
@rasoio 
쇼핑 소재의 경우 하나의 광고그룹에 최대 100개의 소재를 등록할 수 있습니다.
https://saedu.naver.com/help/faq/ncc/view.nhn?faqSeq=402

그 외 자세한 내용은 아래 도움말을 참고해보세요.
https://saedu.naver.com/help/faq/ncc/list.nhn?categorySeq=519

감사합니다.
