### ISSUE TITLE
API 요청시 URLEncoding 관련 질문입니다.

### ISSUE THREAD

**Issue by younseunghyun** [naver/searchad-apidoc#19]
안녕하세요

URLEncoding 관련하여서 질문이 있습니다.

stat api를 사용 하려고 하는데, timeRange에 json의 형태로 since, until에 기간을 넣어 줘야 되는 것으로 보입니다.

현재 네이버 광고 플랫폼에서 보았을 땐, URLEncoding을 해서 보내주는 것으로 보이는데, URLEncoding의 대상 중에서 아래의 경우는 URLEncoding 대상에 포함 되지 않는 것으로 보입니다.

`, : `

Java Sample code에서도 사용하는 방식이 queryString(key,value)로 넘겨주어서 하는데, 그 방식으로는 위의 문자도 인코딩을 해버려서 문제가 생기는 것으로 보입니다.

URLencode를 하여 파라미터를 보내는 경우에 있어서, 따라야 되는 URLEncoding 규칙이 있는지 궁금합니다.

감사합니다 :)

**Comment by naver-searchad** [comment]
자바 샘플코드 (timeRange 파라미터를 사용하여 지표 조회를 하는 경우 : https://github.com/naver/searchad-apidoc/blob/master/java-sample/src/main/java/com/naver/searchad/api/sample/StatSample.java#L44) 를 실행해 보면 말씀해주신 문자(, :)에 대해서도 URL 인코딩되어 정상적으로 지표 조회가 되는 것을 확인할수 있는데요,

/stats api의 경우 query string에 해당하는 부분을 모두 URL 인코딩 처리해 주시면 되며, 별도로 특정 문자에 대해서 따로 처리해야하는 규칙은 없습니다.

만약 URL 인코딩 처리를 적용하였는데 지표 조회가 실패하는 경우 해당 케이스 사례를 알려주시면 확인해보겠습니다.

감사합니다.

**Comment by younseunghyun** [comment]
말씀하신 방법으로 수행시 api가 동작하는 걸로 확인 되었습니다.


`,`의 경우 되지 않는다고 말한 이유가, #11 의 이슈에서 keyword쪽에서 delete하는 api는  `,`를 encoding 하여 사용시에 문제가 있다고 하여서, api를 사용시에  `,`를 사용 하면 안된다고 생각 하여서 말씀드렸었습니다.


keyword를 delete하는 api와 stats api를의 경우를 각각 다른 경우로 보고 사용 하면 될까요?



감사합니다 :)

**Comment by naver-searchad** [comment]
네 말씀해주신대로 각각 다른 경우로 보고 사용 부탁드리겠습니다.

감사합니다.

**Comment by younseunghyun** [comment]
넵 감사합니다 👍
