### ISSUE TITLE
리포트 (Master, Stat) 최대 제공 기간이 궁금합니다.

### ISSUE THREAD

**Issue by jinwoo8333** [naver/searchad-apidoc#191]
안녕하세요.

광고관리 시스템에서 도움말에 보니 

**모든 광고보고서의 최대 제공기간은 '최근2년전(730일)' 입니다. 보고서의 최대 제공 기간을 참고하여 필요한 경우 미리 보고서를 다운로드 받아주시기 바랍니다.**

라고 되어있었는데 실제적으로는 마스터는 최대 730일, 스탯(대용량) 365일 까지는 성성이 됩니다.
또 스탯에서는 상세전환효과가 45일까지인거같습니다.

궁금한점은 각 리포트당 API로 최대 제공하는 기간이 궁금합니다.

마스터

- [ ] 캠페인
- [ ] 광고그룹
- [ ] 키워드
- [ ] 쇼핑상품

스탯
- [ ] 광고효과보고서
- [ ] 광고효과상세보고서
- [ ] 전환보고서
- [ ] 전환상세보고서
- [ ] 쇼핑검색광고키워드상세보고서
- [ ] 쇼핑검색광고키워드상세전환보고서

각각 API를 통한 최대 제공 기간을 알려주시면 감사하겠습니다.

**Comment by naver-searchad** [comment]
안녕하세요, 검색광고 API 입니다.
문의 주신 api 들의 제공 기간을 안내 드립니다.

### 마스터 리포트

마스터 리포트 서비스에서 변경분을 조회하기 위한 `fromTime` 필드의 유효값은 `-730일`~ 현재시간까지 입니다.
참고로 변경분 서비스를 제공하지 않는 아이템은 ["Account", "Media", "Biz", "SeasonalEvent"] 입니다.

###  대용량보고서(/stat_reports) 

대용량 보고서는 현재 아래 표 대로 제공하고 있습니다.

ReportType | 제공기간 | 보고서 이름
-----------| -------|---------|
AD|365일|광고효과보고서
AD_DETAIL|180일|광고효과상세보고서
AD_CONVERSION|365일|광고전환보고서
AD_CONVERSION_DETAIL|45일|광고전환상세보고서
ADEXTENSION|365일|확장소재효과보고서
ADEXTENSION_CONVERSION|365일|확장소재전환보고서
NAVERPAY_CONVERSION|365일|네이버페이보고서
EXPKEYWORD|365일	|키워드확장광고효과보고서
SHOPPINGKEYWORD_DETAIL|180일|쇼핑검색광고키워드상세보고서
SHOPPINGKEYWORD_CONVERSION_DETAIL|45일|쇼핑검색광고키워드상세전환보고서


감사합니다.

**Comment by naver-searchad** [comment]
아래와 같이 답변 완료 하였습니다.

안녕하세요, 검색광고 API 입니다.
문의 주신 api 들의 제공 기간을 안내 드립니다.

### 마스터 리포트

마스터 리포트 서비스에서 변경분을 조회하기 위한 `fromTime` 필드의 유효값은 `-730일`~ 현재시간까지 입니다.
참고로 변경분 서비스를 제공하지 않는 아이템은 ["Account", "Media", "Biz", "SeasonalEvent"] 입니다.

###  대용량보고서(/stat_reports) 

대용량 보고서는 현재 아래 표 대로 제공하고 있습니다.

ReportType | 제공기간 | 보고서 이름
-----------| -------|---------|
AD|365일|광고효과보고서
AD_DETAIL|180일|광고효과상세보고서
AD_CONVERSION|365일|광고전환보고서
AD_CONVERSION_DETAIL|45일|광고전환상세보고서
ADEXTENSION|365일|확장소재효과보고서
ADEXTENSION_CONVERSION|365일|확장소재전환보고서
NAVERPAY_CONVERSION|365일|네이버페이보고서
EXPKEYWORD|365일	|키워드확장광고효과보고서
SHOPPINGKEYWORD_DETAIL|180일|쇼핑검색광고키워드상세보고서
SHOPPINGKEYWORD_CONVERSION_DETAIL|45일|쇼핑검색광고키워드상세전환보고서


감사합니다.
