### ISSUE TITLE
안녕하세요, transaction-ID : B958EN50HDGSC입니다. 질문 있습니다. 

### ISSUE THREAD

**Issue by EDMAI** [naver/searchad-apidoc#192]
fields로 impcnt와 timerange를 적용한 request는 잘 받아옵니다.
그리고 breakdown='pcMblTp'를 추가했는데 breakdown을 적용하기 전과 아무런 변화가 없습니다. 

어떻게 바꿔야 할까요?

**Comment by naver-searchad** [comment]
안녕하세요, 검색광고 API 입니다.

get (by id) api 의 default timeIncrement=1 입니다.
breakdown 은 timeIncrement=allDays 일 때 제공되고 있습니다.
timeIncrement=allDays 로 요청해 주세요.

감사합니다.
