### ISSUE TITLE
모든캠페인에서 '일별 총비용(vat포함)'는 어떻게 가져올까요?

### ISSUE THREAD

**Issue by EDMAI** [naver/searchad-apidoc#193]
![image](https://user-images.githubusercontent.com/33061592/53466698-6fff0480-3a96-11e9-9335-eb679c1c88f1.png)

찾아보니까 비용가져오는 것은 stat리포트의 get:id의 필드에 없는 것 같은데
이 부분 질문드립니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

문의하신 총비용은 'salesAmt' 필드로 다음 api 문서에서 확인하실 수 있습니다.
http://naver.github.io/searchad-apidoc/#/operations/GET/~2Fstats%7B%3Fid,fields,timeRange,datePreset,timeIncrement,breakdown%7D

문서의 fields 파라미터에 example에는 salmesAmt 가 나와 있으나 valid items 목록에 이 salesAmt 가 안나와 있어서 혼동하실 수 있을 것 같습니다.
문서에서 빠진 부분은 업데이트 해 놓도록 하겠습니다.

감사합니다.
