### ISSUE TITLE
인증서 오류

### ISSUE THREAD

**Issue by jayjay248** [naver/searchad-apidoc#195]
인증서 만료 오류와 함께 api 사용이 되지 않습니다.

아이피로 요청하지 않고 기존에도 api.naver.com 도메인으로 api를 요청했었습니다.

인증서 만료와 관련해서 따로 해야되는 조치가 있나요??

아래 외국분 질문을 보니 저희랑 비슷한 현상인데 뭽에서도 그렇고 올려주신 소스 받아서 해봐도 똑같은 인증서 만료와 관련된 오류입니다.

현재 api 사용을 못하고 있어 빠른 답변부탁드리겠습니다.

감사합니다.

**Comment by naver-searchad** [comment]
2019년 3월 1일 오전 9시를 기준으로 만료된 인증서 일부가 제대로 교체되지 않아 서비스 이용이 불안정했습니다. 오후 3시13분을 기준으로 복구되어 현재 서비스 이용 가능합니다.

서비스 이용에 불편을 드려서 죄송합니다.

http://naver.github.io/searchad-apidoc/#/notice

**Comment by jayjay248** [comment]
답변 감사합니다~

그런데 다른 오류가 나오길래 다른 게시물에 다시 질문드렸습니다.

확인 부탁드려요~

> 2019년 3월 1일 오전 9시를 기준으로 만료된 인증서 일부가 제대로 교체되지 않아 서비스 이용이 불안정했습니다. 오후 3시13분을 기준으로 복구되어 현재 서비스 이용 가능합니다.
> 
> 서비스 이용에 불편을 드려서 죄송합니다.
> 
> http://naver.github.io/searchad-apidoc/#/notice
