### ISSUE TITLE
api 요청 오류

### ISSUE THREAD

**Issue by jayjay248** [naver/searchad-apidoc#196]
앞서 ssl 인증서 관련 오류는 해결됬는데 그 이후로 요청을 하게 되면 아래와 같은 오류가 발생됩니다.

unable to find valid certification path to requested target

기존 githup에 올려주신 소스코드 그대로 사용하고 인증서 관련 오류전까지는 정상작동하던 코드였는데 다른 문제가 있는걸까요?

답변부탁드리겠습니다.

감사합니다.

**Comment by naver-searchad** [comment]
SSL 체인 인증서 오류가 복구되어 현재 서비스 이용 가능합니다.

서비스 이용에 불편을 드려서 죄송합니다.
