### ISSUE TITLE
광고센터 대용량 보고서데이터와 StatReport데이터가 다르게 확인됩니다

### ISSUE THREAD

**Issue by sseylee** [naver/searchad-apidoc#197]
StatReport를 create하고 생성된 StatReport를 get 으로 가져와서 보고서데이터를 수집하고 있습니다.
광고센터에서 대용량 보고서 다운로드를 통해서 2/1~2/28일까지 데이가 존재함을 확인하였습니다.
그런데 API로 확인하면 보고서를 get하면

{'regTm': '2019-03-04T10:58:18Z', 'statDt': '2019-01-31T15:00:00Z',
'reportJobId': 538343916, 'updateTm': '2019-01-31T15:00:00Z', 
'downloadUrl': '', 'reportTp': 'AD_DETAIL', 'status': 'NONE'}

위와 같은 상태로 반환되어, 보고서 데이터를 확인할수가 없습니다.
'X-Transaction-ID': 'B994RNVVPHHH8'
'X-Transaction-ID': 'B994RQFM1HJCL'

무슨 이유일까요???
1월부터 계속 그러네요.
광고주 보고서 보내줘야하는데...흑..
빠른 답변 부탁드립니다..ㅠㅠ

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

문의주신 reportJobId를 비롯해서 생성하신 대용량 보고서가
모두 'ahahah57' 계정에서 요청된 것으로 보이는데요,
이 계정은 광고가 하나도 없는 관리 목적 계정인 듯하며,
실제 광고주 계정(customer_id)으로 보고서를 생성하셔야 하겠습니다.

**Comment by sseylee** [comment]
해결되었어요!!! 감사합니다!!!!ㅎㅎㅎ
