### ISSUE TITLE
API 소재 UPDATE 관련 문의드립니다.

### ISSUE THREAD

**Issue by phc118** [naver/searchad-apidoc#198]
Ad update 를보면 
field 타입으로  userLock, inspect 을 받게 되어있습니다. 
위에 제시된 두가지 항목 이외의 나머지 Ad 항목(headline, description, pc URL, mobile URL 등) 은 
수정할수 있는 API가 없는지 문의 드립니다. 

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요, 검색광고API 입니다.
파워링크 소재의 말씀하신 항목들은 수정할 수 없습니다. 
네이버 검색광고 광고시스템에서도 동일하게 수정 불가한 항목들입니다.

수정하고 싶으신 대상 소재를 삭제 후 신규 등록으로 부탁 드립니다.
감사합니다.

**Comment by phc118** [comment]
답변감사합니다.
