### ISSUE TITLE
python 2에서 python sample 사용하는 방법 

### ISSUE THREAD

**Issue by hieonn** [naver/searchad-apidoc#199]
제가 python2 를 쓰다보니까, 받아서 해보니까, 2군데를 수정해야 사용가능하네요. 

1) signaturehelper.py 에서 
hash = hmac.new(bytes(secret_key, "utf-8"), bytes(message, "utf-8"), hashlib.sha256)
요 부분을 →  hash = hmac.new(bytes(secret_key.encode('utf-8')), bytes(message.encode('utf-8')), hashlib.sha256)

2) ad_management_sample.py에서 
    timestamp = str(round(time.time() * 1000)) 요거를
    → timestamp = str(int(round(time.time() * 1000))) 요렇게

수정하시면 사용가능하네요.

참고하셨으면 해서요! 그럼 Good luck!

**Comment by 0xB4DF4C3D** [comment]
지식이 늘었다
