### ISSUE TITLE
campaign 생성 방법 문의

### ISSUE THREAD

**Issue by rndmania** [naver/searchad-apidoc#2]
Campaign 관련 API에 create API는 지원되지 않는것으로 보이는데, API로는 생성 불가능한가요?
(http://naver.github.io/searchad-apidoc/#/tags/Campaign)

**Comment by naver-searchad** [comment]
현재 API 스펙에서 Campaign 생성 기능은 제공하지 않습니다.
Campaign 생성 및 삭제는 광고주 센터통해서 처리하셔야 합니다.

**Comment by younseunghyun** [comment]
campaign 생성 api 향후 지원 계획은 없나요?

**Comment by naver-searchad** [comment]
향후 추가 계획은 있습니다만 일정이 확정 되어 있지 않습니다.
사용자의 요구사항을 어느 정도 취합한 이 후에 제공 일정이 확정 될 것으로 예상됩니다.
