### ISSUE TITLE
stat api 관련 문의 입니다.

### ISSUE THREAD

**Issue by younseunghyun** [naver/searchad-apidoc#20]
안녕하세요

stat의 get api사용시에 field로  아래의 값들이 사용 가능 한 것으로 나옵니다.

- impCnt
- clkCnt
- ctr
- cpc
- avgRnk
- ccnt
- recentAvgRnk
- recentAvgCpc

java-sample로 제공되는 field에는 salesAmt와 drtCrto field가 더 있어서, salesAmt 필드를 이용해서 해당 정보도 가져다가 사용 중입니다.

drtCrto의 경우에는 지원되지 않는 파라미터로 request를 보냈다는 500에러가 나오고 있습니다.

drtCrto가 지원 되지 않는 entity와 breakdown에 대하여 request를 한 것인지, 아니면 지원되지 않는 field값인지 궁금합니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요.

/stats에서 제공하는 drtCrto(직접전환율) 지표는 광고주센터 광고관리화면에 지표를 표시할 목적으로 해당 요건에 맞는 형태로 지표가 제공이 되고 있습니다.

그래서 만약 사용하시려면, 아래와 같은 제약사항이 있습니다.
* fields 파라미터로 drtCrto만 포함
* timeIncrement=allDays
* ids= 광고그룹ID만 가능
* datePreset, timeRange 파라미터 포함 안함

직접전환율을 구할수 있는 다른 방식으로는 /stat-reports API를 통해서 제공되는 지표를 통해 직접 계산하실 수도 있으니 참고 부탁드립니다.

**Comment by younseunghyun** [comment]
답변 감사합니다 :)
