### ISSUE TITLE
/master-reports 외에 전부 시그니쳐 오류가 납니다

### ISSUE THREAD

**Issue by devdmoji** [naver/searchad-apidoc#200]
안녕하세요?
현재 Postman 이라는 API Development Environment 어플리케이션으로
네이버 검색광고 API 요청을 테스트 중입니다.

이 소프트 웨어로는 API 요청 직전에 자바스크립트 코드를 돌릴 수 있는데요,
그래서 X-Signature 헤더와 X-Timestamp 헤더를 매 요청마다 자바스크립트 코드로 생성 중입니다.

/master-reports 는 요청에 성공해서 리스트 JSON을 보는데 성공 했는데
그 외의 다른 API 요청에선 전부 시그니쳐 오류가 납니다.
문서를 봐도 API 별로 별도의 시그니쳐 생성 로직을 써야 되는 거로는 보이진 않는데, 왜 이런 걸까요?

---

API 요청 직전 실행되는 자바스크립트 코드는 아래와 같습니다.

``` javascript
var stamp = (new Date()).valueOf().toString(); // 타임스탬프 생성. 자바스크립트 빌트인 클래스 Date 이용.

/* CryptoJS 자바스크립트 라이브러리를 통해 시그니처 생성 ; 시작 */
var hash = CryptoJS.HmacSHA256(
    stamp + ".GET." + "/master-reports",
    "시크릿 들어가는 자리"
);
var signature = hash.toString(CryptoJS.enc.Base64);
/* CryptoJS 자바스크립트 라이브러리를 통해 시그니처 생성 ; 끝 */

pm.environment.set("signature", signature); // 환경변수로 등록. 요청 헤더에서 참조 가능.
pm.environment.set("stamp", stamp); // 환경변수로 등록. 요청 헤더에서 참조 가능.
```

성공한 호출
GET https://api.naver.com/master-reports

시그니쳐 오류로 실패한 호출
POST https://api.naver.com/master-reports/{id}
GET https://api.naver.com/stat-reports

**Comment by devdmoji** [comment]
API 요청 직전 실행되는 자바스크립트 코드는 아래와 같습니다.

``` javascript
var stamp = (new Date()).valueOf().toString(); // 타임스탬프 생성. 자바스크립트 빌트인 클래스 Date 이용.

/* CryptoJS 자바스크립트 라이브러리를 통해 시그니처 생성 ; 시작 */
var hash = CryptoJS.HmacSHA256(
    stamp + ".GET." + "/master-reports",
    "AQAAAADkw3CV6oDclJJ9XXFUWPgxBEfD+fKvYVwX0ZWXjqyPQg=="
);
var signature = hash.toString(CryptoJS.enc.Base64);
/* CryptoJS 자바스크립트 라이브러리를 통해 시그니처 생성 ; 끝 */

pm.environment.set("signature", signature); // 환경변수로 등록. 요청 헤더에서 참조 가능.
pm.environment.set("stamp", stamp); // 환경변수로 등록. 요청 헤더에서 참조 가능.
```

성공한 호출
GET https://api.naver.com/master-reports

시그니쳐 오류로 실패한 호출
POST https://api.naver.com/master-reports/{id}
GET https://api.naver.com/stat-reports

**Comment by naver-searchad** [comment]
안녕하세요, 검색광고API 입니다.

시그니쳐 오류일 경우 해당 광고주 혹은 리소스에 접근 권한이 없는 경우가 있을 수 있습니다.
더 자세한 확인을 위해서는 오류난 요청의 대략적인 `호출시간`과 `Transaction-ID` 를 알려주시면 내용 좀 더 파악해서 답변 드릴 수 있습니다.

**Comment by devdmoji** [comment]
성공한 호출
X-Transaction-ID →B9BETPRRHDJNQ
Date →Fri, 08 Mar 2019 05:16:56 GMT

시그니쳐 오류로 실패한 호출1
X-Transaction-ID →B9BETV2B9DHA1
Date →Fri, 08 Mar 2019 05:17:17 GMT

시그니쳐 오류로 실패한 호출2
X-Transaction-ID →B9BETVU39DI21
Date →Fri, 08 Mar 2019 05:17:21 GMT

이렇게 입니다.
답변 부탁드리겠습니다. 감사합니다!

**Comment by naver-searchad** [comment]
실패한 각 요청에 대해 실제로 생성되야 하는 서명값은 아래 `Valid Signature`와 같으나 `Requested Signature`로 요청하셨습니다.
서명 생성 시 사용한 데이터가 아래 표의 `Data for signature`와 같은지 확인 부탁드립니다.

Transaction ID | Requested Signature | Valid Signature | Data for signature
---|---|---|---
`B9BETV2B9DHA1` | `bf/N+CPmbVbB5jFqD1Yn6vF53gEql9eYqCh3WkPUhdg=` | `BWn8RPgRZsCl7KwBakCLuryrDHOpkU1xMOZny+C1ig0=` | `1552022237272.POST./master-reports/88B2BFE6970A74F800DFFF4C57A5C14A`
`B9BETVU39DI21` | `Uazb0SErM6TaaPFGRKlp58ODgTbTvEtwEsUYXHE5h/w=` | `P2R4X+1AGfTggiJkumkF3i2nqobAqx13aVFIIp8MuHs=` | `1552022240864.GET./stat-reports/rtt-a001-000000000174229`

**Comment by naver-searchad** [comment]
댓글 내용 중 시크릿 키가 수정 이력에 노출되어 임의로 삭제하고,
이슈 본문에 댓글 내용을 옮겨놓았습니다. 양해 바랍니다.
