### ISSUE TITLE
쇼핑검색광고 소재 생성 API 문의 드립니다.

### ISSUE THREAD

**Issue by phc118** [naver/searchad-apidoc#202]
안녕하세요
쇼핑검색광고 API 개발중에 문의사항이 있습니다.
API 문서와 관련 issue들을 모두 찾아보면서 쇼핑검색광고 소재 생성 개발중에 있습니다.
다른이슈에 쇼핑검색광고 소재는 복수개로만 생성 가능해서  데이터를 [] 로 감싸서 보내면 된다고 되어 있어서 issue 에 나와있는 예제 참고해서 다음과 같이 호출했습니다.
[
{
"ad":{},
"customerId":609939,"
nccAdgroupId":"grp-a001-02000000010069428",
"type":"SHOPPING_PRODUCT_AD",
"userLock":false,"
"delFlag":false,
"referenceKey":"12672873845",
"adAttr":
{
"bidAmt":50,
"useGroupBidAmt":false
}
}
]

하지만 다음과 같은 응답이 반복되고 있습니다.
"title":"Bad Request","status":400,"detail":"JSON parse error: Cannot deserialize instance of `com.naver.searchad.heroes.domain.ncc.NccAd` out of START_ARRAY token;

X-Transaction-ID:B9F7U9AKPHJ7B

어느부분이 문제일까요?

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요, 검색광고API 입니다.

복수개의 소재를 등록할 때는 isList=true 파라메터를 추가하셔야합니다.
`/ncc/ads?isList=true`

아울러 알려주신 값은 오타가 있어 json 파싱 오류가 발생하였습니다.

`"userLock":false,"` 이 부분에서 false 뒤에 있는 `"` 를 지워주시면 정상적으로 데이터가 들어갈 것으로 예상됩니다.

데이터의 json 형태가 맞는지는 여러 온라인 사이트에서 검증하실 수 있습니다.
ex) https://jsonformatter.curiousconcept.com/

감사합니다.

**Comment by phc118** [comment]
오타가 난부분은 제가 글을쓸때 편의성을 위해서
줄간격을 띄우다가 들어간 오타고 실제 입력된 데이터의 오타가 아닙니다...
입력된 데이터는

[{"ad":{},"customerId":609939,"nccAdgroupId":"grp-a001-02-000000010069428","type":"SHOPPING_PRODUCT_AD","userLock":false,"delFlag":false,"referenceKey":"12672873845","adAttr":{"bidAmt":50,"useGroupBidAmt":false}}]

X-Transaction-ID:B9FQT3S7HDINN

첫 문의와 같은 응답이 나옵니다. 확인부탁드립니다.
감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요, 검색광고 API 입니다.

금일 9시 22분 경 들어온 요청 트렌젝션을 확인해 보니
url 상에 isList=true 파라미터가 없이 요청되었습니다.
ncc/ads?isList=true 로 요청되어야 합니다.

**Comment by phc118** [comment]
아 파라미터로 isList 를 포함시켜야 하는군요.
답변 감사합니다.
