### ISSUE TITLE
광고도구에서 모바일통검평균노출순위를 API로 조회

### ISSUE THREAD

**Issue by 0xB4DF4C3D** [naver/searchad-apidoc#203]
현재 네이버 광고도구에서는 모바일 통합검색 평균 노출 순위 열을 조회할 수 있는데

DailyStatResponse 타입이나
Stat, StatReport API 를 사용하여 얻은 결과에서는 따로 

모바일 통합검색 평균 노출 순위 를 알수 없었고 그냥 통합 평균 노출 순위만 알 수있었습니다.

제가 미처 발견하지 못한 부분이 있거나 앞으로 따로 이 열을 조회할 수 있게끔 지원하실 계획이 있으신가요?

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

stat api의 get(by id)를 이용해 키워드id로 조회시
field 정보에 "pcNxAvgRnk","mblNxAvgRnk"를 추가하면
각각 pc와 모바일 통검 평균 노출 순위 지표가 포함됩니다.
API 문서에는 아직 업데이트가 돼 있지 않은 상태이며 향후 업데이트 예정입니다.

감사합니다.

**Comment by 0xB4DF4C3D** [comment]
넵 감사합니다.
