### ISSUE TITLE
API를 통한 키워드 업로드 관련

### ISSUE THREAD

**Issue by nyob3** [naver/searchad-apidoc#204]
안녕하세요.

API를 통해 초기 캠페인 세팅을 할 때 각 광고그룹에 속하는 키워드들을 업로드 하고자 합니다.

http://naver.github.io/searchad-apidoc/#/operations/POST/~2Fncc~2Fkeywords%7B%3FnccAdgroupId%7D

상기 문서를 확인해보니 원하는 해당 광고그룹에 업로드 할 키워드를 광고그룹 id와 함께 호출하는 것으로 보입니다.

다만 광고그룹에는 대개 한 개 이상의 키워드가 필요합니다

제가 이해한 상기 문서 내용에 따르면 호출 URL을 구성할 때 여러 개의 키워드를 List와 같은 형태로 한꺼번에 받는 것이 아니라 '하나의 키워드'만 '하나의 광고그룹 ID'와 함께 '하나의 URL'을 구성하여 호출하면 그 한 개의 키워드가 해당 광고그룹에 업로드 되는 것으로 보입니다.

이러한 경우라면 만약 400개의 키워드를 하나의 광고그룹 ID에 업로드 해야한다면 그 한 개의 광고그룹 ID에 400개의 API 요청을 해야하는데요. 

**1.** 우선 제가 문서를 맞게 이해한 것이 맞는지 궁금합니다.  현재는 키워드는 한 URL 호출에 여러 개를 호출할 수 없고 한 URL 호출에 하나의 키워드만 업로드가 가능한 것이 맞나요?

**2.** 한번에 하나의 키워드만 업로드 가능하다면 불가피하게 서버에 여러 번 요청이 필요할 것으로 보입니다.

- 만약 API를 통해 전체 400개의 키워드를 업로드 해야한다면 한번에 100개 업로드라는 제한에 걸리게 됩니다. API에서는 100개 제한을 어떤 기준으로 제한하고 있나요? (예를 들어 일정 시간 안에 하나의 광고그룹 ID를 기준으로 100개를 초과하는 요청을 하면 요청이 거부된다.)
- 위의 호출 제한 기준과 관련하여, 한번에 하나씩 호출해야 한다는 것과 100개를 초과하는 키워드를 업로드 해야한다는 것을 고려하면, 호출 방법을 어떻게 구성하면 좋을까요? (예를 들어 n개의 키워드를 업로드 후 일정 시간 Sleep, 혹은 too many requests return을 받았을 때 일정 시간 Sleep)

**3.** 
![image](https://user-images.githubusercontent.com/29356782/54407183-c798a380-4717-11e9-8a3f-438a30db8459.png)

마지막으로 광고키워드 업로드 시에 파라미터를 구성할 때 키워드 자체적으로 Max CPC를 설정하지 않고 우선은 현존하는 광고그룹의 Max CPC를 따르고자 한다면 'bidAmt'는 null값으로 설정하고 'useGroupBidAmt'를 'true'로 설정하여 호출하면 되나요?

아니면 그러한 설정은 불가능 하고 직접 광고그룹의 Max CPC를 받아서 키워드 업로드를 호출할 때 bidAmt 파라미터에 그 값을 넣어서 호출해야 하는 건가요?

감사합니다.
좋은 하루 보내세요!

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

문의하신 AdKeyword: create 는 단건이 아닌 복수 키워드 생성 요청입니다.
위에 올려주신 'AdKeyword Parameters'는
키워드 각각의 객체를 어떻게 입력할지에 대한 스펙이고
API 문서상 'parameters'를 보시면 request body에 nccKeywords[] 형태로 안내되어 있습니다.

즉,
url은 /ncc/keywords{?nccAdgroupId} 형태로,
body에는 각각의 AdKeyword 객체를 리스트 형태로 담아 요청하시면 되겠습니다.

**Comment by nyob3** [comment]
안녕하세요. 답변 감사드립니다.

복수의 키워드 생성인 것을 확인했고 테스트까지 완료했습니다. 감사합니다.

bidAmt 설정에 관한 질문이 있습니다.

테스트 과정에서 AdKeyword Parameters 의 'bidAmt'와 'useGroupBidAmt'을 null값으로 호출하니 자동으로 광고그룹의 dafault bid로 설정 됨을 확인하였습니다.

혹시 어떤 특정 키워드는 광고그룹의 default bid가 아니라 특정 금액을 지정하고 싶다면
bidAmt에는 원하는 금액을 넣고
useGroupBidAmt에는 'false'를 넣고 API를 호출하면 원하는 작업을 수행할 수 있는 것인가요?

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

네 질문하신 내용대로 하시면 개별 키워드 입찰가로 적용됩니다.
