### ISSUE TITLE
네이버 모바일 검색광고에서 게재중인 광고 개수 조회 API 있나요?

### ISSUE THREAD

**Issue by 0xB4DF4C3D** [naver/searchad-apidoc#205]
문서에는 보이지 않는데

RelKwdStat에서 PC 광고에 한해서 제공되는 CompIdx 유사한 지표라도 뭔가 해당 키워드를 광고 집행 중인 사람들이 얼마나 있는지 경쟁이 얼마나 쌘지 조회할 수 있는 API가 있는지 궁금합니다.

항상 답변해주셔서 감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

RelKwdStat API에서 제공하는 지표들은 문서에 나와 있는 항목 그대로입니다.
Stat API처럼 요청 field에 원하는 항목을 넣는 방식이 아니라
요청시 모든 항목들이 한번에 제공됩니다.
그리고 말씀하신 의미의 지표로는 CompIdx가 유일합니다.

**Comment by 0xB4DF4C3D** [comment]
아 그렇군요 감사합니다. CompIdx가 PC말고 모바일쪽에서도 유효한가요? 명세 에서는 `based on PC ad` 란 말이 있어서요.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

CompIdx는 도움말 내용대로 현재 PC 기반으로만 제공되고 있습니다.

**Comment by 0xB4DF4C3D** [comment]
그렇군요. 알겠습니다. 감사합니다.
