### ISSUE TITLE
Stat api 빈값 문의 드립니다.

### ISSUE THREAD

**Issue by 0xB4DF4C3D** [naver/searchad-apidoc#206]
Stat get (by ids) api로 성과를 조회할 경우

ids 여러개를 요청하면 일부가 누락되서 반환됩니다.

hh24로 쪼개서 봤더니 어떤 개체는 하루에도 열번 넘게 성과가 측정되었고
어떤 개체는 한번만 측정되고 다양하던데요. 혹시 이렇게 누락된 키워드들은
date 또는 datePreset 날짜에 한번도 성과가 측정되지 않아서 생긴 것들인가요?

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

stat api 요청 결과로 성과지표가 없는 경우, 경험하신 것처럼 반환 객체가 비어서 리턴됩니다.
개발 시 참고 부탁드립니다.

**Comment by 0xB4DF4C3D** [comment]
성과 지표가 없는건 왜 그런건지 알수 있을까요? 검색 볼륨이 적어서 그런건가요? 아니면 그냥 무작위로 성과가 측정되는건가요? 감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

stat api는 광고주들이 등록한 광고나 키워드 등에 대한 명확한 성과지표입니다.
(무작위로 집계하는 지표는 없습니다)
해당 광고가 요청기간 내에 노출이 전혀 되지 않은 경우 어떠한 지표도 잡히지 않게 됩니다.
노출이 되지 않는 사유는 각각의 광고 조건과 광고주의 조건 등에 따라 다양할 수 있습니다.

**Comment by 0xB4DF4C3D** [comment]
아~ 노출이 안되면 지표가 안잡히는군요. 감사합니다!
