### ISSUE TITLE
RelKwdStat: list 호출 결과 관련

### ISSUE THREAD

**Issue by nanpuhaha** [naver/searchad-apidoc#207]
안녕하세요.

[RelKwdStat: list](http://naver.github.io/searchad-apidoc/#/operations/GET/~2Fkeywordstool) API 관련하여, `호출 결과`가 `빈 배열`이라서 문의드립니다.

```python
uri = '/keywordstool'
method = 'GET'
params = {
    'siteId': '',
    'biztpId': '',
    'hintKeywords': '네이버',
    'event': '',
    'month': '',
    'showDetail': 1,
}

r = requests.get(BASE_URL + uri, headers=get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID))

print("response status_code = {}".format(r.status_code))
print("response body = {}".format(r.json()))
```
```python
response status_code = 200
response body = {'keywordList': []}
```

---

그래서 제가 `NAVER광고 > 도구 > 키워드 도구`에서
https://manage.searchad.naver.com/customers/{CUSOMTER_ID}/tool/keyword-planner
똑같이 검색하였을 때 크롬 개발자 도구에서 확인되는 결과를 보니
Query String Parameter가 더 다양하길래 똑같이 아래와 같이 날려본 결과,

그 결과는 똑같이 `빈 배열`이었습니다.

RelKwdStat: list API 관련하여 왜 빈 배열이 날아오는지,
어떻게 써야하는지 알려주시길 요청드립니다.

```python
uri = '/keywordstool'
method = 'GET'
params = {
    'format': 'json',
    'siteId': '',
    'mobileSiteId': '',
    'hintKeywords': '네이버',
    'includeHintKeywords': 0,
    'showDetail': 1,
    'biztpId': '',
    'mobileBiztpId': '',
    'month': '',
    'event': '',
    'keyword': '',
}
r = requests.get(BASE_URL + uri, headers=get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID))

print("response status_code = {}".format(r.status_code))
print("response body = {}".format(r.json()))
```

```python
response status_code = 200
response body = {'keywordList': []}
```

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

샘플로 올려주신 '네이버' 키워드의 경우 판매금지 키워드입니다.
키워드도구 화면에서 조회가 가능한 키워드를 샘플로 넣어 보시면 결과를 받으실 수 있습니다.

**Comment by doohyun** [comment]
안녕하세요 
똑같은 예제를 사용해서 키워드를 바꿨는데요
빈배열이 출력됩니다.
uri = '/keywordstool'
method = 'GET'
params = {
    'format': 'json',
    'siteId': '',
    'mobileSiteId': '',
    'hintKeywords': '베지밀',
    'includeHintKeywords': 0,
    'showDetail': 1,
    'biztpId': '',
    'mobileBiztpId': '',
    'month': '',
    'event': '',
    'keyword': '',
}

r = requests.get(BASE_URL + uri, headers=get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID))

print("response status_code = {}".format(r.status_code))
print("response body = {}".format(r.json()))

**Comment by naver-searchad** [comment]
http request와 response 내용을 올려주시면 확인에 도움이 되겠습니다.
전체 내용 확인이 어려우시면
요청시간 정보와 response에 포함된 transaction id를 알려 주시면 됩니다.
