### ISSUE TITLE
Adgroup의 statusReason 중에서

### ISSUE THREAD

**Issue by kaorimikage** [naver/searchad-apidoc#208]
BUSINESS_CHANNEL_DISAPPROVED
비즈채널 노출제한 값이 걸리기 30분 전부터 광고가 노출이 되지 않는 현상이 있습니다.

그 기간동안의 스테이터스를 어떻게 확인해야하나요?

**Comment by naver-searchad** [comment]
안녕하세요? 검색광고 API 입니다.

광고의 노출은 여러가지 상태값에 영향을 받습니다.
대표적으로 캠페인 상태, 그룹 상태, 사업채널 검수상태, 키워드 검수상태, 소재 검수상태등의 영향을 받으며,
`BUSINESS_CHANNEL_DISAPPROVED`는 위에 나열한 상태값 중에서 사업채널의 검수상태입니다.

문의하신 통합 상태값을 확인할 수 있는 API는 제공하지 않으며, 각 항목별 상태 값을 조회하여 확인 하셔야 합니다.

**Comment by kaorimikage** [comment]
검색광고센터에서 변경이력을 보면 광고 중단의 마지막 이력이 비즈채널 노출제한 입니다.
API에서 해당 결과를 받은 시간과 검색광고센터의 변경이력에 등록된 시간이 동일합니다.
그런데 해당 이력이 발생하기 이전 캠페인, 그룹, 키워드 등등 여타 다른 이유없이 30분전부터 광고노출은 진행되지 않는 현상이 발생합니다. 특별히 내부적으로 광고노출을 ON/OFF하는 뭔가가 있는것인지요?

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

우선, 내부적으로 광고노출을 ON/OFF 하는 건 별도로 없습니다.
비즈머니나 예산 부족 등의 이유로 잠김상태가 될 수는 있으나 이 경우 이력에는 남습니다.

문의주신 내용과 현상을 좀 더 구체적으로 파악하기 위해서는
광고주 계정과 광고 정보가 추가로 필요한데요,
위에서 언급하신 노출제한 비즈채널과 노출이 되지 않고 있는 광고그룹 등의 정보를
추가로 알려 주시면 좋겠습니다.
