### ISSUE TITLE
stats 에서 어제자 데이터는 언제 생성이 되는건가요?

### ISSUE THREAD

**Issue by kaorimikage** [naver/searchad-apidoc#209]
날짜가 넘어간 뒤에 바로 검색을 하면 값이 안넘어오는것 같습니다.
하루가 지나면 어제자 데이터가 언제 취합이 되는지 확인하고 싶습니다.

**Comment by naver-searchad** [comment]
안녕하세요 검색광고 API 입니다.

일반적으로 전날 데이터는 다음날 4시 30분 정도에 사용 가능하십니다.
현재 사용 가능한 데이터 날짜는 response 의 cycleBaseTm 항목으로 제공 중입니다.
cycleBaseTm 항목은 api 문서에 업데이트 예정입니다.

감사합니다.
