### ISSUE TITLE
target api 관련 질문입니다.

### ISSUE THREAD

**Issue by younseunghyun** [naver/searchad-apidoc#21]
안녕하세요

현재 group을 Adgroup: list (by campaign id) 으로 가져오면 target 정보는 summary만 오고 있어서, 해당 group의 target정보가 필요할 경우에는 각 group에 대하여 요청을 하여 target정보를 가져오고 있습니다.

이번 update를 통해 target만을 ownerId를 통해 가져 올 수 있는 api가 생겼는데, 
그렇다면 각각의 group에 대해서 요청시 target의 정보를 주던 것을 이젠 target API를 통해서 가져가게 하려고 하는 것인지, 아니면 단지 target에 대한 접근을 ownerId로 할 수 있게 API를 열어 준 것인지 궁금합니다.

감사합니다.

**Comment by naver-searchad** [comment]
@younseunghyun 
안녕하세요.

이번 변경을 통해서 새로운 target 유형들이 추가 되었으며 또한 target의 owner가 `광고그룹` 뿐만 아니라 `소재`가 될 수 있습니다.

그러한 이유로 단일 ownerId로 target 리스트 조회 및 단일 target을 업데이트 할 수 있는 API를 제공하게 되었습니다.
target에 대한 범용적인 API가 제공된다고 보시면 되겠습니다.

즉 ownerId로 target API를 쓸 수 있도록 열었다고 보시면 되겠습니다.

**Comment by younseunghyun** [comment]
빠른 답변 감사합니다 👍
