### ISSUE TITLE
invalid-signature 살려주세요

### ISSUE THREAD

**Issue by aliswell86** [naver/searchad-apidoc#210]
const CryptoJS = require('crypto-js');
  const moment = require('moment');
  const request = require('request');
  const milliSeconds = moment.now('x');
  const key = milliSeconds + '.GET.' + '/ncc/keywords';
  const api_url = 'https://api.naver.com/ncc/keywords/' + encodeURI('세키로');
  const generateSign = CryptoJS.HmacSHA256(secretKey, key);
  const hashInBase64 = CryptoJS.enc.Base64.stringify(generateSign);
  console.log(hashInBase64);
  const options = {
    url: api_url,
    headers: {
      'X-API-KEY': acsLicense,
      'X-Signature': hashInBase64,
      'X-Customer': customerID,
      'X-Timestamp': milliSeconds
    }
  };

  request.get(options, function (error, response, body) {
    console.log(response.body);
  });

**Comment by aliswell86** [comment]
제가 봤을땐 맞게 한거같은데 invalid-signature오류가 납니다. 어느부분을 확인해야할지 더이상 생각나지 않습니다. ㅠㅠ

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고API 입니다.

서명 생성 시에는 path param을 포함해야합니다. (query param 제외)
질문하신 코드의 경우 아래와 같이 수정하시면 됩니다.

```javascript
const resource =  '/ncc/keywords/' + encodeURI('세키로');
const key = milliSeconds + '.GET.' + resource;
const api_url = 'https://api.naver.com' + resource;
```

**Comment by aliswell86** [comment]
`const request = require('request');
  const milliSeconds = new Date().getTime();
  const resource =  '/ncc/keywords';
  const key = milliSeconds + '.GET.' + resource;
  const api_url = 'https://api.naver.com' + resource;
  const hash = CryptoJS.HmacSHA256(secretKey, key);
  const hashInBase64 = CryptoJS.enc.Base64.stringify(hash);
  
  const options = {
    url: api_url,
    headers: {
      'X-Timestamp': milliSeconds,
      'X-API-KEY': acsLicense,
      'X-Customer': customerID,
      'X-Signature': hashInBase64,
      
    }
  };

  request.get(options, function (error, response, body) {
    console.log(response.body);
  });`

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고API 입니다.

올려주신 코드에서
const resource = '/ncc/keywords';
에 여전히 마지막 nccKkeywordId path가 없습니다.

/ncc/keywords/{nccKeywordId} 형식이 되어야 합니다.

{nccKeywordId}는 이미 등록해 놓은 광고 키워드의 unique id를 말합니다.
'nkw-a001-01-000000000987940'와 같은 형식입니다.

**Comment by aliswell86** [comment]
const milliSeconds = new Date().getTime();
  const resource =  '/ncc/managedKeyword';
  const key = milliSeconds + '.GET.' + resource;
  const api_url = 'https://api.naver.com' + resource + '?keywords=' + encodeURI('세키로');
  const hash = CryptoJS.HmacSHA256(secretKey, key);
  const hashInBase64 = CryptoJS.enc.Base64.stringify(hash);
  console.log(key);
  const options = {
    url: api_url,
    headers: {
      'X-Timestamp': milliSeconds,
      'X-API-KEY': acsLicense,
      'X-Customer': customerID,
      'X-Signature': hashInBase64,
      
    }
  };

이건왜 오류가 나는걸까요? 힘들게해서 죄송합니다

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고API 입니다.

```javascript
const hash = CryptoJS.HmacSHA256(secretKey, key);
```
`CryptoJS.HmacSHA256` input parameter의 순서가 바뀌었습니다.

아래 문서를 참고하시기 바랍니다.

https://cryptojs.gitbook.io/docs/#hmac
```javascript
var hash = CryptoJS.HmacSHA256("Message", "Secret Passphrase");
```

**Comment by harryhan24** [comment]
issue들 살펴보면 개발자분들 대부분  js/ts에 대해 알고계신것같아 자바스크립트 샘플제공도 가능할텐데 왜 안하는지 너무 아쉽네요. API 요청 자체의 난이도가 높은건 아니지만 Docs가 단순히 명세 나열식으로되어있어서 파악하기가 상당히 어려워서요..

**Comment by naver-searchad** [comment]
@harryhan24 
안녕하세요, 네이버 검색광고 API입니다.

좋은 의견 주셔서 감사합니다.
내부적인 검토 과정에서 주신 의견 적극 반영될 수 있도록 노력하겠습니다.
