### ISSUE TITLE
확장소재에 사용되는 이미지 라이브러리 관련 요청

### ISSUE THREAD

**Issue by nanpuhaha** [naver/searchad-apidoc#211]
'광고 관리 > 도구 > 이미지 라이브러리' 관련하여 불편한게 많습니다.

관리자 페이지에 기능 추가와 해당 API 추가 요청드립니다.

- 이미지 규격 (픽셀 사이즈, 파일 사이즈, 파일 확장자) 명시
- 현재 '다운로드'를 하면 `Image ID`, `Image type`, `Filename`, `Date Uploaded` 컬럼이 있는 xlsx파일이 다운로드 되는데, 여기에 `Image Path` 컬럼 추가
- 올렸던 이미지를 모두 다운로드 (백업기능)
- 대량 업로드 (규격에 맞지 않으면 자동 패스 및 규격에 맞지 않는 이미지 목록과 이유 리턴)

또한, 관리자 페이지에서 업로드할 때 이미지를 Drag & Drop하면 바로 Crop이 어느정도 들어가도록 되는데, 기본값으로는 Crop이 안 되도록 해주시면 수동으로 하나씩 업로드할 때 그나마 덜 힘들 것 같습니다...

**Comment by jackbaul** [comment]
안녕하세요 네이버 검색광고API 입니다.

이미지 라이브러리는 기존에 등록한 이미지를 쉽게 다시 등록 할 수 있고, 대량으로 다양한 그룹에 이미지가 추가될 수 있도록 지원하기 위해 추가된 기능입니다.
이미지 라이브러리 자체가 대량으로 이미지를 등록 관리하기 위한 목적으로 준비된 기능이 아니어서 언급주신 불편들이 있을수 있는점 깊이 공감하나 이미지에 대한 대량 관리기능을 추가 제공할 계획은 현재 없습니다. 이점 양해 부탁 드립니다.
다만,  '다운로드'를 파일 내 Image Path의 경우 대량 관리와 무관하게 일반 사용자들의 사용성에도 도움이 될 것으로 보여 추가될 예정입니다.

감사합니다.
