### ISSUE TITLE
확장 소재 Create 시, userLock 관련 문의 드립니다.

### ISSUE THREAD

**Issue by jjh4698** [naver/searchad-apidoc#212]
확장소재를 등록 할 때,
userlock = true 로  request 요청 시, 
{nccAdExtensionId=null, adExtension={basicText="test"}, customerId=null, ownerId=grp-a001-02-000000010625049, inspectStatus=null, type=PROMOTION, schedule=null, pcChannelId=null, mobileChannelId=null, periodStartDt=null, periodEndDt=null, regTm=null, editTm=null, usePeriod=null, userLock=true, status=null, statusReason=null}

아래와 같은 응답이 오는데 

{"nccAdExtensionId":"ext-a001-02-000000016621570","ownerId":"grp-a001-02-000000010625049","customerId":885846,"inspectStatus":"UNDER_REVIEW","type":"PROMOTION","adExtension":{"basicText":"test"},"schedule":null,"delFlag":false,"regTm":"2019-04-18T06:31:46.000Z","editTm":"2019-04-18T06:31:46.000Z","inspectRequestTm":"2019-04-18T06:31:46.000Z","userLock":false,"usePeriod":false,"status":"PAUSED","statusReason":"AD_EXTENSION_UNDER_REVIEW"}

userLock true 인 상태로 create api는 사용 불가능 한가요?

**Comment by naver-searchad** [comment]
안녕하세요 네이버 검색광고 입니다.

현재 확장 소재 등록 API 는 사용자 잠금 (userLock)을 항상 false 로 설정하고 있습니다.
차후 개선사항으로 해당 필드를 사용자가 원하는 값으로 설정해서 등록할 수 있도록 하겠습니다.
