### ISSUE TITLE
Time discrepancy of stat report

### ISSUE THREAD

**Issue by TomXiaoYZ** [naver/searchad-apidoc#213]
Hi Naver,
Is there any time discrepancy before I can get yesterday stat report, for example, AD or AD Conversion report?
I found that when I tried to generate yesterday data at 7 am each morning, I got nothing at all. I tried again later at 10 am and generated successfully. 
Thanks for your help!

**Comment by naver-searchad** [comment]
This is Naver API answering.

Yes there are.
'yesterday-report' needs some time to complete data aggregation and calculations after 00 hrs.
You can check that completion time in every status-report api response field 'compTm'
as a local timezone here(GMT+9).
