### ISSUE TITLE
Adgroup: list (by ids) id 개수 제한

### ISSUE THREAD

**Issue by nanpuhaha** [naver/searchad-apidoc#215]
안녕하세요.

**Adgroup: list (by ids)** API의 id 개수 제한이 있는지 궁금합니다.

https://api.naver.com/ncc/adgroups?ids=grp-a001-01-000000000000000,grp-a001-01-000000000000001,grp-a001-01-000000000000002

와 같이 호출하는데

529개까지는 정상적으로 리턴값이 오는데,
530개부터는 아래와 같이 400 에러가 발생합니다.

`400 Bad request`
`Your browser sent an invalid request.`

 **Adgroup: list (by ids)** API의 id 개수가 529개로 제한되어 있는건지 확인 요청드립니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

adgroup의 list (by ids) API의 리스트 개수 제한은 걸려 있지 않습니다.
하지만 Get Request의 특성상 parameter의 최대 길이는 client와 서버의 환경 설정에 따라 영향을 받을 수 있습니다.
400 Bad Request는 530번째 파라미터가 Client또는 서버의 HTTP 송수신 단계에서 짤린 것으로 보여집니다.
서버의 파라미터 최대 길이의 설정은 내부 사정에 의해 바뀔수 있습니다.
