### ISSUE TITLE
광고그룹의 키워드 확장 업데이트 API

### ISSUE THREAD

**Issue by brithely** [naver/searchad-apidoc#216]
API로 광고 그룹 키워드 확장 BETA 기능을 사용하려고 하는데 잘 안되는 부분이 있어서 질문 올립니다.
그룹을 생성 할 때 Post 요청에서는 useKeywordPlus True로 보내면 키워드 확장이 자동으로 켜지는데, 이미 생성된 그룹을 업데이트를 하려고 Put요청을 아무리 보내도 변경되지 않네요 
처음 생성될때 False이면 변경이 되지 않는건가요? 웹으로는 변경이 가능한대 API로는 안되어서 질문드려요

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API 입니다.

그룹 키워드 확장 Beta 기능을 변경하기 위해서는 아래 API를 사용하시고 `fields=useKeywordPlus` 파라미터를 사용하시면 됩니다.

http://naver.github.io/searchad-apidoc/#/operations/PUT/~2Fncc~2Fadgroups~2F%7BadgroupId%7D%7B%3Ffields%7D

**Comment by brithely** [comment]
넵 파라미터 적용해서 잘 되었습니다. 감사합니다.
