### ISSUE TITLE
Stats API 데이터 업데이트 주기가 있나요?

### ISSUE THREAD

**Issue by SongYunSeop** [naver/searchad-apidoc#217]
오늘자 데이터를 Stats API breakdown을 hh24로 설정하여 시간별 통계를 보는데 데이터가 언제 업데이트 되는지 궁금합니다.

**Comment by naver-searchad** [comment]
안녕하세요 네이버 검색광고 API입니다.

stat api 에서 breakdown=hh24&datePreset=today 를 call 했을 때 리턴되는 cycleBaseTm 항목을 현재까지 집계 완료된 통계 시간으로 사용하실 수 있습니다.

- 관련 response 정의
http://naver.github.io/searchad-apidoc/#/definitions/SummaryStatResponse
- 관련 도움말
https://alpha.saedu.naver.com/help/faq/ncc/view.nhn?faqSeq=529
