### ISSUE TITLE
Master Keyword Report 관련 문의입니다.

### ISSUE THREAD

**Issue by k3363** [naver/searchad-apidoc#218]
Master Keyword Report를 통해 다운받는 데이터가 
광고주센터에서 받은 데이터와 다른데 광고주센터에서 받은 데이터로 받을 순 없는지 궁금합니다.
현재 customerId, groupId, keywordId, keywordNm, act_st만 넘어오고있어서 문의드립니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고API 입니다.

MasterReport 의 Ad Keyword (Keyword) 리포트 형식은 광고주센터 이외에 전문 데이터 분석도구 및 통계패키지 등을 사용하는 고급 사용자 분들에게 적합한 형태로 서비스 하고 있습니다.
별도의 합산 및 가공이 되지 않는 원본 형태로 서비스하기 때문에, 광고주센터 보고서 형태로 제공해 드리긴 어렵습니다.

일반적인 광고 리포트 형태를 이용 하시려면, 광고주센터 보고서를 이용해 주시기 바랍니다.

**Comment by k3363** [comment]
API문서에는 광고주센터에서 받은 형태로 데이터가 있는데 실제로 받아온 결과물은 API문서와 달라서 문의드린 내용이였습니다.
API문서의 내용과 결과물이 다른 것이 맞는지 확인 부탁드리겠습니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

MasterReport api 내용은 표시된 그대로인 것으로 확인됩니다.
실제 내려받은 결과물이 다르다면 샘플 데이터를 하나 첨부해 주시기 바랍니다.
