### ISSUE TITLE
target api 관련 질문입니다.

### ISSUE THREAD

**Issue by younseunghyun** [naver/searchad-apidoc#22]
안녕하세요

이번에 추가 된 target api를 사용을 하려 합니다.

문서에 명시된 사용 방법이 아래와 같이 두가지로 보입니다.

`/ncc/targets?ownerId={ownerId}`
`/ncc/targets?ownerId={ownerId}&types={types}`

첫번째 사용법으로 사용을 하려고 해보았는데 404 not found 가  Return 되고 있습니다

ownerId에 해당되는 그룹의 id가 잘못된 것인가 확인을 해보았지만, 해당 id로 group의 정보를 가져오는 api는 정상작동하고, group의 정보를 가져오면서 얻어온 target의 정보에도 ownerId가 해당 group의 id로 되어있는것을 확인 했습니다.

테스트를 한 group은 노출 전략들을 설정하지 않은 상태 입니다.

해당 group에 target관련 설정을 하지 않은 상태의 경우는 group의 정보를 가져오는 api로는 targe의 정보를 가져올 수 있으나, target api를 통해서는 가져 올 수 없는 것인지, 아니면 해당 target api가 아직 동작을 안하는 것 인지 궁금합니다.

감사합니다

**Comment by naver-searchad** [comment]
@younseunghyun 
안녕하세요.
트랜잭션 ID를 알려주시면 빠른 확인이 가능합니다.

**Comment by younseunghyun** [comment]
`X-Transaction-ID: null` 로 나오고 있습니다

**Comment by naver-searchad** [comment]
@younseunghyun 
안녕하세요.
타게팅 조회가 될 수 있도록 하였습니다. 다시 한번 테스트 부탁드립니다.

**Comment by younseunghyun** [comment]
동작 하는것을 확인하였습니다.

감사합니다 👍
