### ISSUE TITLE
PUT /ncc/adgroups/{adgroupId}

### ISSUE THREAD

**Issue by jxamen** [naver/searchad-apidoc#221]
입찰가를 변경하려고 합니다.
아래와 같이 전송을 하는데 잘못된게 뭘까요?
아래 에러 메세지 있습니다.

코드
var baseUrl = ConfigurationManager.AppSettings["BASE_URL"];
var apiKey = ConfigurationManager.AppSettings["API_KEY"];
var secretKey = ConfigurationManager.AppSettings["SECRET_KEY"];
var managerCustomerId = long.Parse(ConfigurationManager.AppSettings["CUSTOMER_ID"]);

var rest = new SearchAdApi(baseUrl, apiKey, secretKey, context, conn);

var body = "{'bidAmt':" + changeBidAmt + "," +
                    "'contentsNetworkBidAmt':50," +
                    "'dailyBudget':20000," +
                    "'keywordPlusWeight':100," +
                    "'mobileNetworkBidWeight':100," +
                    "'pcNetworkBidWeight':100," +
                    "'useCntsNetworkBidAmt':false," +
                    "'useDailyBudget':true," +
                    "'useKeywordPlus':false, " +
                    "'userLock':false," +
                    "'nccAdgroupId':'" + group + "'}";

var request = new RestRequest("/ncc/adgroups/"+ group + "?fields=bidAmt", Method.PUT);
 request.AddParameter("application/json; charset=utf-8", JsonConvert.SerializeObject(body), ParameterType.RequestBody);

에러
{"title":"Bad Request","status":400,"detail":"JSON parse error: Cannot construct instance of `com.naver.searchad.heroes.domain.manage.AdgroupRequest` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('['bidAmt':380,'contentsNetworkBidAmt':50,'dailyBudget':20000,'keywordPlusWeight':100,'mobileNetworkBidWeight':100,'pcNetworkBidWeight':100,'useCntsNetworkBidAmt':false,'useDailyBudget':true,'useKeywordPlus':false, 'userLock':false,'nccAdgroupId':'grp-a001-02-000000011030903']'); nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `com.naver.searchad.heroes.domain.manage.AdgroupRequest` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('['bidAmt':380,'contentsNetworkBidAmt':50,'dailyBudget':20000,'keywordPlusWeight':100,'mobileNetworkBidWeight':100,'pcNetworkBidWeight':100,'useCntsNetworkBidAmt':false,'useDailyBudget':true,'useKeywordPlus':false, 'userLock':false,'nccAdgroupId':'grp-a001-02-000000011030903']')\n at [Source: (PushbackInputStream); line: 1, column: 1]"}

**Comment by naver-searchad** [comment]
안녕하십니까? 네이버 검색광고 API입니다.

보내신 Request Log를 확인한 결과 HTTP Body에 JSON이 잘못입력되어 있습니다.
Array 밖에 `{}`를 한번더 감쌓아서 JSON 오류가 발생했습니다.
아래 내용은 보내신 JSON입니다. 
```
"{[{'bidAmt':380,'contentsNetworkBidAmt':50,'dailyBudget':20000,'keywordPlusWeight':100,'mobileNetworkBidWeight':100,'pcNetworkBidWeight':100,'useCntsNetworkBidAmt':false,'useDailyBudget':true,'useKeywordPlus':false, 'userLock':false,'nccAdgroupId':'grp-a001-02-000000011030903'}]}"
```

**Comment by jxamen** [comment]
이렇게 저렇게 수없이 테스트 해보고 질문 남겼습니다.
json 겉에 { 빼고 전송해도 동일한 오류입니다.

죄송하지만 c#으로 된 샘플 코드를 볼 수 없나요?

body에 보낸 nccAdgroupId 값과 
var request = new RestRequest("/ncc/adgroups/"+ group + "?fields=bidAmt", Method.PUT);
group 값이 동일한데 이건 이상이 없나요?


var body = "[{'bidAmt':" + changeBidAmt + "," +
"'contentsNetworkBidAmt':50," +
"'dailyBudget':20000," +
"'keywordPlusWeight':100," +
"'mobileNetworkBidWeight':100," +
"'pcNetworkBidWeight':100," +
"'useCntsNetworkBidAmt':false," +
"'useDailyBudget':true," +
"'useKeywordPlus':false, " +
"'userLock':false," +
"'nccAdgroupId':'" + group + "'}]";

var request = new RestRequest("/ncc/adgroups/"+ group + "?fields=bidAmt", Method.PUT);
request.AddParameter("application/json; charset=utf-8", JsonConvert.SerializeObject(body), ParameterType.RequestBody);

**Comment by jxamen** [comment]
해결완료
