### ISSUE TITLE
Stat API 관련 문의입니다.

### ISSUE THREAD

**Issue by SongYunSeop** [naver/searchad-apidoc#224]
timeRange를 사용해서 조회할 수 있는 기간의 제한이 있나요?

일주일 전의 데이터를 조회하려는데 아래처럼 응답이 오는것 같아서요
`{"code":11001,"message":"잘못된 파라미터 형식입니다."}`

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

'상세데이터'를 포함해서 질의할 경우 대부분 상품이 7일간 제한이 있습니다.
포함하지 않는 경우는 2년(데이터 윈도우는 92일)입니다.

**Comment by SongYunSeop** [comment]
상세데이터라 함은 어떤것인가요?

**Comment by naver-searchad** [comment]
query param에 들어가는 breakdown을 말합니다
