### ISSUE TITLE
java 샘플 코드.. 정상 가동되는건가요?

### ISSUE THREAD

**Issue by dodeji** [naver/searchad-apidoc#226]
안녕하세요.
자바 샘플코드로 테스트해볼려고 이클립스에 올려서 테스트 해봤는데 라이브러리도 다 넣고 했는데도 제대로 실행이 되질 않네요..
빨간줄 쫙쫙 뜨고..
3년전 업데이트 이후에 업뎃이 없던데..
매뉴얼에 있는 api와 클래스가 없는것도 있고 새로생긴 것도 있는것 같은데 현행화가 안되어있는것 아닌가요?
제가 잘 못하는건지..

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

이클립스 상에 빨간 줄이 있으신 것으로 보아, lombok이 설치되지 않은 것 같습니다.
lombok을 설치하면 이클립 상의 문제가 해결될 것 같습니다.
그리고 샘플 코드는 3년이 지났으나 기본적인 기능들은 변경된 것이 없기 때문에 크게 사용하시는데는 문제가 없을 것 같습니다. 다만, 새롭게 추가된 기능이나 상품을 사용하기 위해서는 api 문서를 확인하시고 수정할 필요가 있을 수 있습니다.

감사합니다.
