### ISSUE TITLE
그룹등록시 bidAmt에러 

### ISSUE THREAD

**Issue by k3363** [naver/searchad-apidoc#228]
그룹 등록시에 Invalid value in the bid amount field for the content media of an ad group.
이라는 에러 메시지가 나옵니다.

X-Transaction-ID:BB1JVBLN1DH9C 입니다.

확인 부탁드리겠습니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

Request JSON을 확인해보니 `contentsNetworkBidAmt`값이 `0`으로 입력 되어 발생한 오류입니다. `useCntsNetworkBidAmt` 값이 `false`인 경우에 `70`(기본값)을 입력 하시면 됩니다.
