### ISSUE TITLE
campaign type 관련

### ISSUE THREAD

**Issue by k3363** [naver/searchad-apidoc#229]
campaign_type관련해서 API엔 WEB_SITE, SHOPPING만 나와있는데
총 4개값이 있는 것으로 알고 있습니다.
나머지 2개의 값도 알려주시면 감사하겠습니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

캠페인 종류는 아래와 같습니다.

* WEB_SITE : 파워링크 캠페인 유형
* SHOPPING : 쇼핑 검색 유형
* POWER_CONTENTS : 파워 컨텐츠 유형
* BRAND_SEARCH : 브랜드 검색 유형
* PLACE : 플레이스 유형

감사합니다.

**Comment by k3363** [comment]
그리고 또하나 질문이 있는데 추적 URL에 보면 n_campaign_type 이라는 파라미터가 있는데
이 값과 같이 매칭이 되는 것으로 알고 있습니다.
WEB_SITE : 1, SHOPPING : 2 로 알고 있는데
POWER_CONTENTS : 3, BRAND_SEARCH : 4, PLACE :5 로 
처리를 하면 될지 알려주시면 감사하겠습니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API 입니다.
다음 내용을 참고 하세요.

* WEB_SITE : 1
* SHOPPING : 2
* POWER_CONTENTS : 3
* BRAND_SEARCH : 4
* PLACE : 6

감사합니다.
