### ISSUE TITLE
ip-exclusions api 문의

### ISSUE THREAD

**Issue by blackhck** [naver/searchad-apidoc#23]
안녕하세요

해당 [API](http://naver.github.io/searchad-apidoc/#/operations/DELETE/~2Ftool~2Fip-exclusions%7B%3Fids%7D)를 보면 

```
DELETE /tool/ip-exclusions{?ids}
````
라고 되어 있는데요. 

콤마(,)로 구분해서 DELETE를 하라는건가요?

`DELETE /tool/ip-exclusions?ids=1,2,3,4`

이런 식으로 보내면 `Invaild Signature`라고 응답이 옵니다

**Comment by naver-searchad** [comment]
GET으로 조회한 데이터의 ipFilterId 값을  콤마(,)를 구분자로 사용하여  넣어주면 다수의 IP에 대해 삭제가 가능합니다.
예를 들어 DELETE /tool/ip-exclusions?ids=47958,47956 와 같이 사용 가능합니다.

**Comment by blackhck** [comment]
@naver-searchad 감사합니다 :)
1개로는 삭제가 무난히 되는데 
`DELETE /tool/ip-exclusions?ids=47958` 

여러개를 할 때  
`DELETE /tool/ip-exclusions?ids=47958,47959`
와 같이 할 때 `No Permission`이라고 하는데 
여러개만 삭제가 안되는 경우가 있나요 ?
