### ISSUE TITLE
GET /stat-reports/{reportJobId} 의 응답 중 status 에 대한 질문

### ISSUE THREAD

**Issue by devdmoji** [naver/searchad-apidoc#230]
GET /stat-reports/{reportJobId} 의 응답 중 각 status 값은 아래 중 하나라고 알고 있습니다.

- REGIST
- RUNNING
- BUILT
- NONE
- ERROR
- WAITING
- AGGREGATING

제가 짜고 있는 로직 상에서 GET /stat-reports/{reportJobId} 를 통해
유효한 데이터를 다운로드 받을 수 있는 상태일때만 다음 프로세스로 진행 하도록
플래그 값으로써 이 status를 이용하려 하는데요...

어느 status 값을 허용하면 될까요?
현재 추측으로는 'BUILT' 일 때만 허용, 나머지는 불허 하면 될 것 같은데 맞나요?
각 status 값들이 갖고 있는 정확한 의미를 알려주셨으면 좋겠습니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

데이터를 가져갈수 있는 상태는 `BUILT` 입니다.

아래는 나머지 상태에 대한 의미입니다.
```
REGIST // 등록
BUILT // 생성완료
ERROR // 생성에러
RUNNING // 생성중
WAITING // 대기중
NONE // 지표없음
AGGREGATING // 지표집계 전
```

**Comment by devdmoji** [comment]
감사합니다.
