### ISSUE TITLE
Adgroup: create (keyword plus restricted keywords) 문의

### ISSUE THREAD

**Issue by jxamen** [naver/searchad-apidoc#231]
http://naver.github.io/searchad-apidoc/#/operations/POST/~2Fncc~2Fadgroups~2F%7BadgroupId%7D~2Frestricted-keywords

파라미터를 아래 형태로 보내라고 되어 있는데요
샘플을 찾을 수가 없습니다.

어떻게 보내야 하는지 샘플 코드 좀 부탁 드립니다.

Request body
restrictedKeywords[] | AdgroupRestrictKwd

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

파워링크 캠페인 그룹의 `키워드 확장 Beta(제외 키워드 등록/삭제)` 기능에 대한 자세한 설명은 [FAQ](https://github.com/naver/searchad-apidoc/wiki/FAQ#q-키워드-확장-beta는-어떻게-사용하나요)에 자세히 설명되어 있습니다.

감사합니다.
