### ISSUE TITLE
쇼핑 검색 가격 업데이트는 불가능한가요?

### ISSUE THREAD

**Issue by underhappy** [naver/searchad-apidoc#232]
쇼핑 검색 상품  가격의ㅣ 업데이트는 불가능한가요?
/ncc/ads/ 를 이용해서 변경할려니  가격 변경이 불가능 하더군요..

 $updatekeyword = $api->PUT('/ncc/ads/', $adkeywordlist,array("fields" => "bidAmt"));

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

말씀하신 상품 가격(입찰가) 업데이트는 bidAmt 필드가 아닌 adAttr 필드로 가능합니다.
PUT api/ncc/ads/{adId}?fields=adAttr
API 문서로는 다음을 참고하시면 됩니다.
http://naver.github.io/searchad-apidoc/#/operations/PUT/~2Fncc~2Fads~2F%7BadId%7D%7B%3Ffields%7D

request body 정보에서 adAttr 필드의 example을 열어 보시면
해당 필드 내에 bidAmt key로 입찰가를 넣을 수 있음을 확인하실 수 있습니다.

**Comment by underhappy** [comment]
php에서 예제를 보더라도 adAttr 오브젝트 이용법을 모르겠습니다.

fields=>adAttr{ "bidAmt": 50,   "useGroupBidAmt": true}

이렇게 넣으면 되는가요?

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

쿼리파라미터 fields값이 adAttr이어야 한다는 의미였습니다.
업데이트를 원하는 fields가 adAttr이라는 의미입니다.
`"fields" => "adAttr"`
그리고 요청 body 객체에 adAttr값을 다음과 같이 넣어 주시면 됩니다.
`adAttr: {bidAmt: 50, useGroupBidAmt: false}` (bidAmt는 희망하는 입찰가값으로)
useGroupBidAmt를 false로 해주셔야 개별입찰가가 적용됩니다.

**Comment by underhappy** [comment]
adttr에 객체 값을 넣는게 이해가 안되는군요.

아래 처럼 하면 안되는건가요??

$uri = '/ncc/ads/' . "nad-a001-02-000000062675438";
$adUpdate["adAttr"] = (object) array("bidAmt" => 2000, "useGroupBidAmt" =>0 );
$field = array("fields" => 'adAttr');

$updateAd = $api->PUT($uri, $adUpdate, $field);

**Comment by naver-searchad** [comment]
fields=adAttr은 쿼리 파라미터이므로 다음과 같이 uri를 만드시면 되고
`/api/ncc/ads/nad-a001-02-000000062675438?fields=adAttr`
http body에 들어갈 내용은 올려주신 것처럼 하면 됩니다.
올려주신 PUT의 argument 순서가 어떻게 되는지 모르겠지만
queryParam과 body 순서를 잘 확인해 보시고 사용하시면 될 것 같습니다.
