### ISSUE TITLE
대행사 계정이 보고서 생성 API 사용시 status가 NONE이 되지 않으려면 어느 수준의 권한을 부여 받아야 되나요?

### ISSUE THREAD

**Issue by devdmoji** [naver/searchad-apidoc#235]
대행사 계정의 customer_id로 보고서 생성 API 사용시 status가 NONE이 되지 않으려면
아래 중 어느 수준의 권한을 부여 받아야 되나요?

광고 관리자
성과조회
광고관리/세무
성과조회/세무
광고관리/로그분석
성과조회/로그분석
광고관리/로그분석/세무
성과조회/로그분석/세무

아니면 무조건 실제광고주계정만 API를 통해 보고서를 생성 할 수 있나요??

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

우선 먼저 올려주신 문의의 트렌젝션 ID 확인이 아직 안되어 답변을 드리지 못했습니다.

customer_id는 대행사 에이전트 계정이 아닌 리포트 대상의 해당 광고주 customer_id를 사용하셔야 합니다.
그리고 권한이 없는 라이선스로 api 요청할 경우는
stat-report 상의 응답이 아닌 api 권한 오류가 리턴될 것입니다.
따라서 올려주신 문의의 status NONE과 권한과는 상관이 없어 보입니다.

만약 에이전트 계정의 customer_id로 api 요청을 하신 거라면
먼저 올려주신 문의와 함께 모두 동일한 원인으로 보시면 되지 않을까 싶습니다.

**Comment by devdmoji** [comment]
X-Transaction-ID →BBD3LK8E1HJQ2
Date →Tue, 18 Jun 2019 04:49:37 GMT
에 대한 요청이 실제광고주의 customer_id를 통해 요청되었는지 확인 해 주실 수 있으실까요?
status NONE이 발생한 요청 입니다.

**Comment by naver-searchad** [comment]
에이전트 계정의 customer_id와 광고주의 customer_id 정보를 먼저 알려주시면 확인에 더 도움이 될 수 있을 것 같습니다. login_id 라도 괜찮구요.

**Comment by naver-searchad** [comment]
BBD3LK8E1HJQ2 이 요청의 경우,
대행사 계정의 customer id로 요청한 것으로 나오네요.
그럼 당연히 데이터가 없는 것으로 나옵니다.

**Comment by devdmoji** [comment]
감사합니다.

**Comment by devdmoji** [comment]
아 한가지 질문만 더 드리겠습니다.
대행사 계정의 customer id로는 API를 통해
"데이터가 존재하는 유효한 보고서 생성"이
전혀 불가능 한 것인지요?

**Comment by naver-searchad** [comment]
대행사 계정이든 아니든
요청된 customer id 소유의 광고관리 항목의 성과로 보고서가 만들어집니다.
요청하신 본인 대행사 계정이 직접 관리하는(권한 대행 말고) 광고가 있고 성과가 있다면
그에 해당하는 보고서가 생성될 수 있습니다.
권한 대행만 하는 계정이라면 당연히 본인 계정의 보고서 내용이 있을 수가 없겠지요.
