### ISSUE TITLE
차트에 있는 데이터를 얻고싶습니다.

### ISSUE THREAD

**Issue by momochii** [naver/searchad-apidoc#236]
![이미지 2](https://user-images.githubusercontent.com/26451229/59812044-6c460500-9347-11e9-902f-f1bcad414de5.png)

위 첨부파일처럼, 차트에 있는 데이터를 얻고 싶습니다.
혹시 api 제공하고 있는 데이터인가요?
제공하고 있다면 어떤걸 사용해야 데이터를 얻을 수 있을까요?

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

API 의 다음 문서 상에 보시면
http://naver.github.io/searchad-apidoc/#/operations/GET/~2Fkeywordstool
연관키워드를 조회하는 것으로 되어 있는데요
동일한 API지만 쿼리파라미터에 다음과 같이 keyword 파라미터 하나를 더 추가하시면
원하시는 데이터를 얻으실 수 있습니다.
```
format: json
siteId: 
mobileSiteId: 
hintKeywords: 다낭나만리트리
includeHintKeywords: 0
showDetail: 1
biztpId: 
mobileBiztpId: 
month: 
event: 
keyword: 다낭나만리트리
```

**Comment by momochii** [comment]
너무너무 감사합니다!!
해결되어서 너무 마음이 편안하고 기쁘네요 :D

**Comment by naver-searchad** [comment]
@momochii 

안녕하십니까 네이버 검색광고 API 입니다.

상기 드린 답변에 오류가 있어 다시 정정하여 답변드립니다.
혼란을 드린 점 사과의 말씀 먼저 드립니다.

특정 키워드의 과거 1년간의 검색수 추이는 연관키워드의 선택에 도움을 드리고자 그래프 UI 형태로만 제공드리며, 네이버 검색광고 API 서비스를 통해서는 제공드리지 않습니다.
(혹 이전 답변에 가이드된  파라미터로 조회가 되시더라도 곧 차단이 될 것이라는 점 참고 부탁드립니다.)

검색수 추이에 대한 정보는 검색광고가 아니라 네이버 차원에서 네이버데이터랩을 운영하고 있는데요.
더 자세하고 더 긴기간의 데이터가 제공되고 있으니 활용을 검토해 보시면 좋을 것 같습니다.
단, 이 API의 경우는 절대 값이 아닌 조회 기간중 최대 값을 기준으로 구성된 상대값이라는 점은
주의 부탁드립니다.
네이버 데이터랩 API 안내 : https://developers.naver.com/products/datalab/

감사합니다.
