### ISSUE TITLE
키워드확장광고효과보고서(StatReport EXPKEYWORD) 관련

### ISSUE THREAD

**Issue by nanpuhaha** [naver/searchad-apidoc#238]
안녕하세요.

키워드확장광고효과보고서를 다운받아 보던 도중 의아한 점을 발견했습니다.

(Date, CUSTOMER ID, Campaign ID, Adgroup ID, Search Keyword, Media code, PC Mobile Type) 쌍이 Unique할 것이라는 예상과 달리,
아래와 같은 값을 확인할 수 있었습니다.

설명 부탁드립니다.

```
20190628, 1580100, cmp-a001-01-000000001777137, grp-a001-01-000000010509972, 의류도매시장, 27758, P, 1, 0, 0.0, 0
20190628, 1580100, cmp-a001-01-000000001777137, grp-a001-01-000000010509972, 의류도매시장, 27758, P, 2, 0, 0.0, 0

20190628, 1580100, cmp-a001-01-000000001777137, grp-a001-01-000000010509972, 의류도매, 27758, P, 15, 1, 500.0, 0
20190628, 1580100, cmp-a001-01-000000001777137, grp-a001-01-000000010509972, 의류도매, 27758, P,  1, 0,   0.0, 0
```

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

동일한 search keyword더라도 매칭된 광고주의 등록 키워드가 다를 수 있기 때문입니다.
현재 효과보고서에는 합산되어 나오지 않기 때문에
필요에 따라 합산해서 처리하시면 될 것 같습니다.
