### ISSUE TITLE
media id 166758는 무엇인가요?

### ISSUE THREAD

**Issue by nanpuhaha** [naver/searchad-apidoc#239]
StatReport를 뽑다보니 media id를 보게되는데,
아래 링크에서 확인되지 않는 media id가 있습니다.

https://manage.searchad.naver.com/file/static/naver_ad_media.xlsx
https://manage.searchad.naver.com/file/static/naver_ad_blog_webtoon.xlsx

media id 166758에 대한 정보와
그 외 위의 링크에 나와있지 않은 media 들에 대한 정보도 같이 부탁드립니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

media id 166758은
naver_ad_blog_webtoon.xlsx 파일의 'nblog' 시트 144281 행에서 확인되고 있습니다.

```
네이버 블로그 | 166758 | 평범한 직장인의 돈벌궁리 | http://blog.naver.com/makemoremoney
```

**Comment by nanpuhaha** [comment]
197605는 확인되지 않는데, 무엇인가요?

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

시트의 row수가 많아서 개인 pc 성능 영향을 받을 수 있을 것 같습니다.
엑셀에서 찾기 시 '전체 셀 내용 일치' 옵션과 함께 검색하면 도움이 될 수 있습니다.

![image](https://user-images.githubusercontent.com/18188635/61857944-15ac8780-af00-11e9-98da-fc5644f1e1eb.png)

**Comment by naver-searchad** [comment]
올라가 있는 파일 상에는 아직 업데이트가 안된 것으로 보이구요
문의하신 media 정보는 다음과 같습니다.

![image](https://user-images.githubusercontent.com/18188635/61858845-df700780-af01-11e9-9d60-9f1392f5070b.png)
