### ISSUE TITLE
bizmoney api 기능 확장 관련 질문입니다.

### ISSUE THREAD

**Issue by younseunghyun** [naver/searchad-apidoc#24]
안녕하세요

지금 제공해 주시는 bizmoney api로는 현재의 bizmoney 잔액과, 특정일의 소진액을 받아오는 api가 있는 것으로 보입니다.

특정 기간에 대한 소진액을 받아 오고 싶으면, 특정일의 소진액을 받아오는 api(getCost)를 특정 기간의 일자 만큼 호출 해야 되는 것으로 보입니다.

혹시 특정 기간에 대한 소진액을 조회하는 것이 가능하도록 지원 하실 예정은 없으신지 궁금합니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API 정책 담당자입니다. 

현재는 지원 계획이 없습니다만 긍정적으로 검토하겠습니다. 
단, 가까운 기간내 해당 기능이 지원될 가능성은 낮으며 조회를 하더라도 월단위 등으로 
기간 제한은 존재하게 될 것으로 예상됩니다.

감사합니다.

**Comment by younseunghyun** [comment]
답변 감사합니다 👍
