### ISSUE TITLE
Stat에서 get(by ids) 의 fields 값들에 대한 추가적인 설명

### ISSUE THREAD

**Issue by bluesme519** [naver/searchad-apidoc#240]
Get by ids 의 fields 값들에 대한 추가적인 설명을 부탁드립니다
impCnt 
clkCnt
salesAmt
ctr
cpc
avgRnk
ccnt
recentAvgRnk
recentAvgCpc
pcNxAvgRnk
mblNxAvgRnk
crto
convAmt
ror
cpConv
viewCnt

특히 AvgRnk는 평균순위인것 같은데 recentAvgRnk 과는 어떤차이인지 등 추가설명 부탁드리겠습니다.

**Comment by naver-searchad** [comment]
안녕하세요?
네이버 검색광고 API 입니다.

avgRnk는 지표 요청 기간 동안의 평균이며,
recentAvgRnk 는 통검영역에서 지난 24시간 중 지표가 발생한 가장 최근 한 시간내의 평균노출순위입니다.

예를 들어 당일지표가 아래와 같이 발생한 경우,

시간대 | 노출수 | 시간별 평균노출순위 
-- | -- | --- 
0~1 |1 |1.0
1~2 |1| 2.0

avgRnk는 1.5가 될 것이고, 
recentAvgRnk는 2.0 으로 보여지게 됩니다.

**Comment by sogangCSmaster** [comment]
ccnt가 의미하는게 무엇인가요?
저 위에 있는 것들 각각에 대해 API 문서에 설명이 없더라구요..

**Comment by naver-searchad** [comment]
@sogangCSmaster 
wiki 탭의 FAQ 문서를 참고해 주세요.
https://github.com/naver/searchad-apidoc/wiki/FAQ-stat#q-stat-%EC%A7%80%ED%91%9C-%ED%95%AD%EB%AA%A9-%EC%9D%98%EB%AF%B8
