### ISSUE TITLE
RellKwdStat 관련 문의드립니다.

### ISSUE THREAD

**Issue by doohyun** [naver/searchad-apidoc#242]
해당 api를 호출 했을 때 요청 성공해서 코드값이 200인데
응답 값은 빈 배열로 옵니다.
어떤 문제가 있는지 도움 부탁 드립니다.
`uri = '/keywordstool'
method = 'GET'
params = {
    'format': 'json',
    'siteId': '',
    'mobileSiteId': '',
    'hintKeywords': '베지밀',
    'includeHintKeywords': 0,
    'showDetail': 1,
    'biztpId': '',
    'mobileBiztpId': '',
    'month': '',
    'event': '',
    'keyword': '',
}

r = requests.get(BASE_URL + uri, headers=get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID))

print("response status_code = {}".format(r.status_code))
print("response body = {}".format(r.json()))`

![1562057016754](https://user-images.githubusercontent.com/3966925/60561424-62cc8c00-9d8e-11e9-8724-38186996cbd6.jpg)

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

올려주신 코드로만 보면, params를 정의한 뒤 request에서 사용하지 않는 것으로 보입니다.
