### ISSUE TITLE
키워드 검색광고, 신제품 검색광고를 구분 할 수 있나요?

### ISSUE THREAD

**Issue by devdmoji** [naver/searchad-apidoc#243]
campaignTp 값으로는 다음과 같이 구분이 가능하다는건 검색을 통해 알게 되었는데요.
WEB_SITE : 파워링크 캠페인 유형
SHOPPING : 쇼핑 검색 유형
POWER_CONTENTS : 파워 컨텐츠 유형
BRAND_SEARCH : 브랜드 검색 유형
PLACE : 플레이스 유형

키워드 검색광고, 신제품 검색광고 유형은 어떻게 구분하나요?
혹시 GET /ncc/ads/{adId} 응답의 type 값으로 구분할 수 있을까요?
그렇다면 아래의 GET /ncc/ads/{adId} 응답의 type 값이 각각 어떤 의미를 지니고 있는건가요?
문서상에는 나와있지 않아 여쭈어 봅니다.

TEXT_45
SHOPPING_PRODUCT_AD
CONTENTS_AD_INFORMATION
CONTENTS_AD_PRODUCT
BRAND_SEARCH_AD
PLACE_AD
CATALOG_AD

**Comment by naver-searchad** [comment]
안녕하세요, 검색광고API입니다.
신제품검색 광고의 경우 현재 네이버 검색광고에서 서비스 되고 있는 상품이 아닙니다.
따라서 저희 API 에는 신제품검색 광고 관련 데이터는 제공되지 않습니다.

ad 의 type 별로 의미가 있는 것은 사실입니다.
하지만 예제가 있는 `TEXT_45` 유형 외에는 등록/수정시 별도로 연동하고 있는 시스템의 값이 필요하므로,
API 상에서 공식적으로 지원하고 있지 않음을 양해 부탁 드립니다.

감사합니다.

**Comment by devdmoji** [comment]
답변 감사합니다. 참고하겠습니다.
