### ISSUE TITLE
Target API update 오류 문의 

### ISSUE THREAD

**Issue by breakit100** [naver/searchad-apidoc#244]
target api 를 사용해 "MEDIA_TARGET" (type: 3) 정보 변경시 아래와 같은 오류가 납니다. 
500 Internal Server Error. X-Transaction-ID:BBRD6P7319I6J, Response Body:{"code":1005,"status":500,"title":"Cannot handle the request."}

500 Internal Server Error. X-Transaction-ID:BBRDBU7FPHJTN, Response Body:{"code":1005,"status":500,"title":"Cannot handle the request."}

요청시 잘못된 부분이 어디인지 확인 가능 할까요?

(type: 1) 일때 정상 동작은 확인 했습니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

매체 타겟팅의 특정 매체 지정 (type=3)의 mediaGroup이 입력되지 않을 경우 입력된 메체의 검증을 위해 PC/Mobile 타겟팅 입력이 필요합니다.

**Comment by breakit100** [comment]
안녕하세요 
target api 문서 에서는 두개의 타겟 정보를 입력 할 수 없는것 같은데요 이럴 경우에는 
adgroups api 를 사용 해야 하나요? 아니면 target api 에서 처리 할 수 있는 방법이 있는가요?

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

Target API를 이용하는 경우 단건에 대한 변경만 가능합니다. 타겟팅 전체 변경을 원하시면 [Adgroup API](http://naver.github.io/searchad-apidoc/#/operations/PUT/~2Fncc~2Fadgroups~2F%7BadgroupId%7D)를 사용하셔야 합니다.

**Comment by breakit100** [comment]
넵 확인 감사합니다.
