### ISSUE TITLE
네이버 프리미엄 로그

### ISSUE THREAD

**Issue by sangkooyoon82** [naver/searchad-apidoc#245]
안녕하세요. 

네이버 api를 통하여 프리미엄 로그 분석 UV 보고서를 받을 수 있을까요?
API 문서를 봐도 해당 내용이 없는듯 하여 문의 남겨봅니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

말씀주신 것처럼 현재 API로는 지원하지 않고 있습니다.
장기적으로 지원 계획은 있지만 구체적으로 아직 일정이 세워져 있지는 않습니다.
감사합니다.

**Comment by sangkooyoon82** [comment]
답변 감사합니다. 
혹시 nosp 결과 report 관련 api도 지원이 안되는 것 인가요?

**Comment by sangkooyoon82** [comment]
> 안녕하세요, 네이버 검색광고 API입니다.
> 
> 말씀주신 것처럼 현재 API로는 지원하지 않고 있습니다.
> 장기적으로 지원 계획은 있지만 구체적으로 아직 일정이 세워져 있지는 않습니다.
> 감사합니다.

**Comment by naver-searchad** [comment]
네 마찬가지로 지원하지 않고 있습니다.
