### ISSUE TITLE
네이버 검색 광고 API 성별, 연령병 검색량 데이터를 다시 받고 싶습니다..

### ISSUE THREAD

**Issue by mosball** [naver/searchad-apidoc#246]
@naver-searchad
안녕하세요.
네이버 검색 광고 API를 이용해서 웹 서비스를 구축, 운영중인 취준생 개발자입니다.
해당 웹 서비스는 사용자가 키워드를 입력하면 그에 대한 통계정보(검색량, 검색 추이등)를 분석, 시각화해서 제공하는 서비스입니다. 

hintKeywords가 아닌 keyword파라미터로 요청시 성별, 연령별 검색량을 받을 수 있는 것을 이용해 제 웹 서비스에서는 검색량 뿐아니라 성별 연령별 검색 비율또한 시각화해서 제공하고있었습니다.

그런데, 7월 17일 오후 5시경부터 keyword를 파라미터로 전달했을 때 더이상 데이터가 넘어오지 않습니다. 아마도 데이터를 받을 수 없게 변경이된 것 같습니다. 제 서비스는 오픈한지 2달 정도 되었는데, 어떠한 상업적인 광고 없이 최근 일일 페이지뷰 5000정도가 나오고 있습니다. 사람들의 입소문 만으로 이렇게 퍼진것을 보면, 제 서비스가 그만큼 유용하다는것의 증거라고 생각합니다.

하지만, 이제 그 웹 서비스가 문을 닫아야할 상황에 놓여있습니다. 제 서비스는 키워드 관련 데이터가 꼭 필요한 분들에게 유용한 정보를 드리기위해 정말 순수한 마음으로 만든 서비스입니다. 혹 절대적인 수치 공개가 꺼려지신다면 상대적인 값으로 표시해도 괜찮으니, 다시 연령별, 성별 검색량을 받을 수 있었으면 합니다.

저 뿐만아니라, 제 서비스를 이용하던 많은 유저들이 혼란을 겪고있습니다. 좋은 방향으로 다시한번 검토 해주셨으면합니다. 감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API 입니다.

문의 주신 키워드 도구 기능 중 월별 성별, 나이별 트랜드 정보는 네이버 검색광고 API를 통해 제공되지 않았어야 하는 데이터이나 API 오류로 인해 데이터가 제공되고 있었으며 전일(7월 17일) 오류를 확인하여 이를 수정하였습니다.

저희 오류로 인하여 혼란을 겪으신 점 사과 드립니다.

문의 주신 검색어의 연령, 성별, 모바일/PC 별 트랜드는 네이버가 제공하는 서비스 API 중 데이터렙 API를 통해서 제공되고 있습니다. 아래 링크를 참고해 주시기 바랍니다.
https://developers.naver.com/docs/datalab/search/
상기 API는 조회 기간 중 가장 조회수가 많았던 시점을 100으로 하여 계산된 상대 값이 제공된다는 점
주의 부탁드립니다.

또한 데이터 라이선스별 일 단위 사용량 제한이 존재하고 사용 형태나 목적에 따라 이용이 제한 될 수 있으므로 앞서 안내 드린 데이터렙 API를 사용하시기 앞서 이용 안내 및 약관을 우선 꼼꼼히 살펴 보시기를 권장 드립니다.
https://developers.naver.com/products/intro/plan/

추가로 네이버 검색광고 API는 라이선스를 가진 본인의 광고 계정 혹은 네이버 검색광고 시스템을 통해 부여된 권한을 가진 타 네이버 검색광고 회원의 광고 계정에 대한 네이버 검색광고 운영 및 관리 목적으로만 사용이 가능한 서비스입니다. 따라서 추후 네이버 검색광고 API의 다른 기능을 활용하실 계획이 있으신 경우 상기 사항에 대해 참고를 부탁드립니다.

감사합니다.

**Comment by mosball** [comment]
@naver-searchad
답변 감사합니다.
데이터랩 API에 대해서는 잘 알고 있습니다. 현재 데이터랩 API는 남성과 여성간에 검색량 비율, 연령대간의 검색량 비율이 아닌 남성의 검색 추이, 여성의 검색 추이, 또는 특정 연령대의 검색추이만을 제공하는 것으로 알고 있습니다. 사용자들이 실제로 더 궁금해 하는 것은 남성과 여성 중 어느 성별이 더 많이 해당 키워드를 검색하는가, 어떤 연령층의 검색량이 가장높은가등등 인데 해당 내용에 대해서는 API제공 계획이 없으신가요? 아니면 다른쪽에 문의를 해야하는건가요?

**Comment by naver-searchad** [comment]
요청 주신 데이터는 네이버 검색광고 API를 통해 제공 드릴 계획이 없으며
향후 제공을 고려하고 있지 않습니다.

저희 이외에 문의를 주실 수 있는 곳은 데이터랩 서비스 API 쪽이 적절하리라 생각 되며
개발자 포럼(https://developers.naver.com/forum/list)을 통해 문의를 주실 수 있습니다.
유사 문의 및 데이터렙서비스의 답변은 아래 링크를 참고 부탁드립니다.
https://developers.naver.com/forum/posts/26409 -> 모바일 PC 항목별 비율 및 절대값 제공 관련 문의

감사합니다.
