### ISSUE TITLE
MasterReport Ad Quality Index(AdQi) 누락 확인 요청

### ISSUE THREAD

**Issue by kohunmin** [naver/searchad-apidoc#247]
안녕하세요.

현재 설정된 Ad 에 대한 AdQi 값이 MasterReport 에 존재하지 않아 확인 요청드립니다.
실제 API 를 통해 확인을 했을때는 AdQi 값이 존재합니다.

현재 설정된 ad 가 2000 개 있는데 그중 17건이 값이 존재 하지 않습니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

Ad API 조회 결과와 달리 마스터리포트에 존재하지 않는 Ad Id를 알려 주시면 확인에 도움이 되겠습니다.
감사합니다.

**Comment by kohunmin** [comment]
안녕하세요.
"nad-a001-02-000000068104948" 의 AdId 의 값이 API 에서는 QI 값이 "nccQi":{"qiGrade":4} 로 나오는데요.

report 에는 해당 값이 존재하지 않습니다.

**Comment by naver-searchad** [comment]
소재 품질지수는 특성상 노출이력이 없으면, 품질지수가 제공되지 않습니다. 
문의주신 소재는 노출이력이 없어 품질지수가 반환되지 않았습니다.
소재정보는 조회되나 소재품질지수 마스터에 존재하지 않으면, 
광고주센터에서 보이는 바와 같이 "4"단계로 판단해주시기 바랍니다.
