### ISSUE TITLE
API 제공여부

### ISSUE THREAD

**Issue by newbreed77** [naver/searchad-apidoc#249]
국내 어떤 사이트를 보니 스마트 스토어의 키워드 검색에 따른 노출되는 상품수와

특정 카테고리별 연관 키워드 리스트를

노출해주는 사이트가 있던데요.

이건 어떠한 API를 이용해야 하는걸까요?

레퍼런스를 봐도 해당 결과를 리턴하는 API를 못찾겠습니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

해당 정보들은 네이버 검색광고 API의 관리대상 데이터들이 아닙니다.
네이버 쇼핑검색에서도 공식적인 API는 없는 것으로 보이는데요,
따라서 해당 사이트는 쇼핑검색 웹서비스를 분석 및 크롤링 해서 제공하는 것으로 추측됩니다.

감사합니다.
