### ISSUE TITLE
Keyword API 관련 문의입니다.

### ISSUE THREAD

**Issue by younseunghyun** [naver/searchad-apidoc#25]
안녕하세요

현재 AdKeyword API를 사용시 managedKeyword에 있는 pCPLMaxDepth 정보를 통해서 pc의 경우 최대 노출 가능한 광고 갯수 정보를 얻어 올 수 있는데, 모바일의 경우에는 최대 노출 가능 광고 갯수 정보를 얻어 오는 방법은 없는 것으로 보입니다.

키워드의 모바일 최대 광고 노출 갯수를 받아 올 수 있는 방법은 없는 것인지, 현재 없다면 향후 지원 계획은 없는지 궁금합니다. 

감사합니다 :)

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API 담당자입니다. 

문의 주신 모바일 통합검색 영역내에서 광고 노출 최대 갯수는 현재 제공 되지 않는 기능입니다. 
모바일 매체에서는 아직까지 광고 노출의 갯수와 형상에 있어 다 나은 광고 표현 방식은 없는지 
저희 네이버 뿐만 아니라 모둔 업체들이 모색을 하고 있는 상황이다 보니 해당 정보를 드리기에는 
시기 상조라는 판단을 하고 있습니다. 
아마도 이런 고민이 어느 정도 해답을 찾고 시장에서도 받아 들일 수 있는 시점에 모바일 광고 상품에 대한 광고 노출 갯수를 제공드리게 될 것으로 예상됩니다만....현재로서는 이를 추정키 어려운 상황입니다.

감사합니다. 

감사합니다.

**Comment by younseunghyun** [comment]
답변 감사합니다 👍
