### ISSUE TITLE
Python에서 MasterReport, StatReport API 사용법에 대한 문의드립니다.

### ISSUE THREAD

**Issue by u5071** [naver/searchad-apidoc#250]
안녕하세요. 친절한 항상 친절한 답변에 감사드립니다.

현재 Python으로 광고관련한 API를 사용하고 있는데요,

MasterReport, StatReport  API를 사용하던 중 해결하지 못한 문제가 발생하여 문의드리게 되었습니다. (create와 downloadURL관련문의)

1. StatReport 에서 create기능을 구현하기 위해 다음과 같은 코드로 호출을 하였으나, 오류가 나서 어떤 부분이 문제인지 확인을 받을 수 있을지 문의드립니다.  (report list를 요청할 시에는 정상적으로 받을 수 있는 상태입니다. )

    def stat_report_create(self, reportTp, stat_date):
        uri = '/stat-reports'
        method= "POST"
        params = {'reportTp' : reportTp,
                  'statDt' : stat_date}
        r = requests.get(self.BASE_URL + uri, params=params, headers=self._header(method, uri))
        return r.json()

report_class = Report('user')
rc = report_class.stat_report_create('AD','20190719')

결과 : 

rc  =  {'signature': '--------------------비공개------------------', 'status': 403, 'detail': "Signature '--------------------비공개------------------' is invalid.", 'title': 'Invalid Signature', 'type': 'urn:naver:api:problem:invalid-signature'}

2. MasterReport에서 요청을 통해 만들어진 download URL을 통해서 파일을 다운로드 받고자 합니다. JAVA Sample코드를 참조하여  파이썬 코드로 다음과 같이 요청을 하였으나 403오류가 떠서 어떤 부분이 문제일지 확인을 받을 수 있을까 하여 문의드립니다.

---------------------------------------------------------
참조한 JAVA Sample 코드:

	private static void download(RestClient rest, long customerId, MasterReport built) throws Exception {
		List<NameValuePair> params = URLEncodedUtils.parse(new URI(built.getDownloadUrl()), "UTF-8");
		if (!params.isEmpty()) {
			NameValuePair value = params.get(0);
			if ("authtoken".equals(value.getName())) {
				String authtoken = value.getValue();
				HttpResponse<InputStream> response = rest.get("/report-download", customerId)
						.queryString("authtoken", authtoken)
						.asBinary();
				File downloaded = new File("test-" + built.getItem() + "-" + built.getId() + ".tsv");
				try (FileOutputStream out = new FileOutputStream(downloaded);
				     InputStream in = response.getBody()) {
					System.out.println("Download Available: " + in.available());
					IOUtils.copy(in, out);
					System.out.println("file-size = " + downloaded.length());
					System.out.println("file = " + downloaded.toString());
				}
			}
		}
	}
}
--------------------------------------------------------------

작성한 Python코드 :

    def master_report_detail(self, id):
        uri = '/master-reports/'
        method = 'GET'
        params = {'id': id}
        r = requests.get(self.BASE_URL + uri, params=params, headers=self._header(method, uri))
        return r.json()

    def master_report_get(self, uri):
        method = 'GET'
        r = requests.get(uri, headers=self._header(method, uri[21:]))
        return r.json()

uri = detail[0].get('downloadUrl')
download = report_class.master_report_get(uri)

결과 : 

{'signature': '--------------비공개-----------------', 'status': 403, 'detail': "Signature '--------------비공개-----------------' is invalid.", 'title': 'Invalid Signature', 'type': 'urn:naver:api:problem:invalid-signature'}

3. Python Sample코드에 Report 관련한 코드를 추가할 계획이 있으신지 문의드립니다.

아직 학습하는 단계여서 부족한 점이 많습니다.
항상 도움주셔서 감사드립니다. 
모두들 행복한 하루 되시기바랍니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

'invalid signature' 오류에 대해서는 #253 답변 부분을 참고하시면 될 것 같습니다.
감사합니다.

**Comment by u5071** [comment]
감사드립니다. 답변해주신 내용 활용하여 해결 완료하였습니다.

행복한 하루 되시기바랍니다.
