### ISSUE TITLE
/keywordstool 관련 데이터를 받아오지 못합니다.  

### ISSUE THREAD

**Issue by hdkhh** [naver/searchad-apidoc#251]
안녕하세요 
API문서의 PHP 샘플 파일을 바탕으로 API 호출을 했을 시 값이 넘어오지 않습니다. 

$hintKeywords = "카시오";

$param = array (
    'format' => 'json',
    'hintKeywords' => $hintKeywords,
    'includeHintKeywords' => 0,
    'siteId' => '',
    'biztpId' => '',
    'month' => '',
    'event' => '',
    'showDetail' => 1,
    'keyword' => ''
);

$tmp_list = $api->GET('/keywordstool', $param);

debug($tmp_list, $DEBUG);
print_r($tmp_list);

이렇게 API호출 시 
sign = 1564023399042.GET./keywordstool Http Status : 200 Transaction-ID : BC4S7H409HHSS 
로 출력만 되며,  배열이나, json 값은 들어오지 못하는 것 같습니다. 

제가 잘못 호출을 한것인지, 아니면 호출 방법이 바뀐건가요?? 
도움을 부탁드립니다.

**Comment by hdkhh** [comment]
혹시 저와같은 비슷한 문제있으신 분들은 확인하세요 ㅠㅠ 
CUSTOMER_ID 부분 문제였습니다 
네이버 광고검색의 API확인 페이지에서 CUSTOMER_ID 부분을 복사/붙여넣기 했더니 
에디터나, 화면 상에는 안보이는 특수문자가 존재하네요,,  
아톰이나, 서브라임텍스트에서는 확인 안되는 문자 였습니다.   ;;; 
혹시 API 호출 안되시는 분들 CUSTOMER_ID 부분 확인해보세요!!

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

먼저 파악해 주신 대로
![image](https://user-images.githubusercontent.com/18188635/62176112-39962000-b37b-11e9-988e-a444f4b2e7f0.png)
customerId 가 잘못 요청된 것으로 보입니다.

감사합니다.

**Comment by zaxguy** [comment]
안녕하세요. php로 코딩중인데요. 결과값이 잘 나오는데.. 문제가 너무많이 나와서 그러는데요. 검색한 결과 말고도 연관 검색어 결과치까지 대량으로 리턴되서 페이지가 다운되는데요. 혹시 검색한 결과만 나오도록 제한하거나 리턴받을 결과 갯수를 지정하는 파라메터가 있을까요?

$data = array (
	"hintKeywords" =>"떡볶이",
	"includeHintKeywords" => 1,
	"showDetail" => 1
);

$response = $api->GET('/keywordstool', $data);
