### ISSUE TITLE
Is it possible to get hourly data from /stats?

### ISSUE THREAD

**Issue by tackong** [naver/searchad-apidoc#252]
Hello Naver, I'm trying to get hourly data from /stats, looks like it's doable based on http://naver.github.io/searchad-apidoc/#/operations/GET/~2Fstats%7B%3Fid,fields,timeRange,datePreset,timeIncrement,breakdown%7D by setting dateRange (Hours of stats based on KST (JSON format string)) with hours information. What is the right date time format should I use in the GET request? I didn't make it with time format like "2018-07-23 01:00:00". Also, could you give some details about the usages of breakdown enums:

pcMblTp,
dayw,
hh24,
regnNo

Thanks!

**Comment by naver-searchad** [comment]
Hello, this is Naver Searchad API.

'timeRange' is just a date format like this.
`timeRange: {"since":"2019-07-23","until":"2019-07-28"}`
You can break a day in 24 time ranges by using the option
`breakdown: hh24`

rest of the breakdown options are,

pcMblTp: PC or Mobile
dayw: week days
regnNo: regional code

you can use only 1 option per every request.

**Comment by tackong** [comment]
Hello, thanks for the reply.

I tried to run below lines:

`NaverStat.TimeRange timeRange = new NaverStat.TimeRange("2019-08-02", "2019-08-04");

NaverStat.SummaryStat dailyStat = NaverStatAction.getSummaryStatById(client, account_id, adgroup_ud, List.of(NaverStat.Field.impCnt, NaverStat.Field.ctr, NaverStat.Field.cpc, NaverStat.Field.salesAmt), timeRange, null, null, NaverStat.Breakdown.hh24);
`
The returned dailyStat has 3 SummaryStatData as expected while the breakdowns fields in those objects are still null, any idea why? Thanks!

**Comment by naver-searchad** [comment]
@tackong 
below is the sample of the api parameters (url decoded)
```
GET /api/stats
?breakdown=hh24
&fields=["clkCnt","impCnt","salesAmt","ctr"]
&ids=nkw-a001-01-000000000987940,nkw-a001-01-000000000987936
&timeIncrement=allDays
&timeRange={"since":"2019-07-30","until":"2019-08-01"}
```
and if you have the same problem, let us know those 'ids'

**Comment by sem-naver** [comment]
@naver-searchad Hi, I'm a PM working along with @tackong for getting the hourly data. Since 'IDs' are very private information, we can't share them in github. Is there another method we could share them more privately? Thank you!

**Comment by tackong** [comment]
Looks like I can only pull the hourly breakdowns with "ids" instead of "id".
