### ISSUE TITLE
파이썬 쇼핑 검색 광고 광고비 변경 코드 확인 부탁드립니다.

### ISSUE THREAD

**Issue by dd1233345** [naver/searchad-apidoc#253]
import time
import random
import requests
import signaturehelper

def get_header(method, uri, api_key, secret_key, customer_id):
    timestamp = str(round(time.time() * 1000))
    signature = signaturehelper.Signature.generate(timestamp, method, uri, SECRET_KEY)
    return {'Content-Type': 'application/json; charset=UTF-8', 'X-Timestamp': timestamp, 'X-API-KEY': API_KEY, 'X-Customer': str(CUSTOMER_ID), 'X-Signature': signature}

BASE_URL = xxxxx
API_KEY = xxxxx
SECRET_KEY = xxxxx
CUSTOMER_ID = xxxxx
AD_ID = 'nad-a001-02-0000000XXXXXXXXX'

uri = '/ncc/ads/' + AD_ID + '?fields=adAttr'
method = 'PUT'
created_ad = {'fields': 'adAttr', 'nccAdId' : AD_ID, 'BidAmt': 300, "useGroupBidAmt": True}
r = requests.put(BASE_URL + uri, params={'fields': 'adAttr'}, json=[created_ad], headers=get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID))

print("response status_code = {}".format(r.status_code))
print("response body = {}".format(r.json()))

아직 초보적인 수준이라 감이 안 잡히네요. 이전에 올라왔던 질문들과 가이드를 참고해서 최대한 만들어봤는데 invalid_signature 에러가 나옵니다.

response status_code = 403
response body = {'signature': '2P22K1Jtaqofr9rbuuM4w1ZPR/luCe9t5jQ5Oc35i0U=', 'title': 'Invalid Signature', 'status': 403, 'detail': "Signature '2P22K1Jtaqofr9rbuuM4w1ZPR/luCe9t5jQ5Oc35i0U=' is invalid.", 'type': 'urn:naver:api:problem:invalid-signature'}

이렇게 나오는데 어떤 점이 문제인지 알려주시면 감사하겠습니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

signature를 생성하는 uri는 query paramter를 제외한 path만으로 사용해야 합니다.
`?fields=adAttr` 부분을 제거하고 signature를 생성해 주세요.

**Comment by dd1233345** [comment]
AD_ID = 'nad-a001-02-0000000XXXXXXXXX'

uri = '/ncc/ads/' + AD_ID
method = 'PUT'
created_ad = {'fields': 'adAttr', 'nccAdId' : AD_ID, 'BidAmt': 300, "useGroupBidAmt": True}
r = requests.put(BASE_URL + uri, params={'fields': 'adAttr'}, json=[created_ad], headers=get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID))

와 같이 수정해서 진행 했습니다.

response status_code = 400
response body = {'title': 'Bad Request', 'status': 400, 'detail': 'JSON parse error: Cannot deserialize instance of `com.naver.searchad.heroes.domain.ncc.NccAd` out of START_ARRAY token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `com.naver.searchad.heroes.domain.ncc.NccAd` out of START_ARRAY token\n at [Source: (PushbackInputStream); line: 1, column: 1]'}

이런 에러가 뜨는데 제가 초보라서 어디가 문제인지 잘 모르겠습니다...
어떻게 고치면 해결이 될까요?

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

소재 1건에 대한 PUT 수정요청이므로 request body에는 ad 객체가 그대로 들어가면 됩니다.
`json=[create_ad]` 와 같이 Array로 묶인 부분이 보이네요.

그리고 create_ad 객체 내용 자체도 잘못 기입돼 있는데요
가장 좋은 방법은 해당 ad를 먼저 get해서 객체를 가져온 다음
adAttr 내 bidAmt만 수정한 뒤 이 객체를 그대로 PUT으로 수정 요청하는 데 사용하시면 됩니다.
혹은,
광고주센터에서 쇼핑검색광고 소재 입찰가 변경시 network로 http put request 내용을 참조하셔도 됩니다.

**Comment by dd1233345** [comment]
```
uri = '/ncc/ads/nad-a001-02-000000xxxxxx'
method = 'PUT'
created_ad = {'adAttr': {'bidAmt': 540, 'useGroupBidAmt': False}}
r = requests.put(BASE_URL + uri, params={'fields': 'adAttr', 'nccAdId': 'nad-a001-02-000000058725329'}, json=created_ad, headers=get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID))

```

response status_code = 400
response body = {'code': 3830, 'status': 400, 'title': 'Invalid ad type.'} 에러가 나옵니다 ㅠㅠ
어디가 잘못된 걸까요

**Comment by naver-searchad** [comment]
먼저 말씀드린 대로 먼저 adId로 GET 하신 뒤
해당 객체의 bidAmt만 수정해서 실행해 보시길 권장합니다.
일단 위의 오류 메시지로만 보면
ad 객체 중 'type' 필드가 필요해 보입니다.
ex) `type: "SHOPPING_PRODUCT_AD"`

참고로 올려주신 ad id의 bidAmt는 현재 540원으로 조회되고 있습니다. (위의 예제값과 동일)
