### ISSUE TITLE
파이썬 쇼핑광고 관련

### ISSUE THREAD

**Issue by bluesme519** [naver/searchad-apidoc#254]
안녕하세요

쇼핑광고의 경우 어떤 키워드로 몇순위에 노출되었는지를 키워드별로 볼수있는 방법은 따로 없나요?
예를들면 광고관리자에서 광고그룹안으로 들어가서 해당 소재에 상세보기를 클릭하고, 제외키워드 추가 를 누르면  지난 30일간 어떤 키워드로 몇번의 클릭이 이루어졌고 전환이 얼마나 되었는지 확인이 가능한데요, 이부분은 API로 불러올 방법이 혹시 없는건가요?

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

api doc의 다음 문서를 참고하시면 되겠습니다.
http://naver.github.io/searchad-apidoc/#/operations/GET/~2Fstats%7B%3Fid,statType%7D

즉 다음과 같이 원하시는 소재 id와 statType 파라미터로 요청하시면 됩니다.
`/api/stats?id=nad-a001-02-0000000000XXXXX&statType=NPLA_SCH_KEYWORD`

**Comment by bluesme519** [comment]
```
def get_stats_keywords(ad_id):
    uri = '/stats'
    method = 'GET'
    r = requests.get(BASE_URL + uri, params={'id': ad_id, 'statType': 'NPLA_SCH_KEYWORD'}, headers=get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID))
    parsed = r.json()
    return(parsed)
```

이런식으로 만들어서 사용하게되었습니다. 감사합니다. 다른분들을 위해서도 공유합니다.
해당 내용 python example 에 반영되면 더욱 좋을 것 같습니다

그런데 이건 stats 불러오는건데도 날짜설정하는게 없네요
혹시 불러와지는 데이터는 날짜설정이 뭘로 되어있는건가요? 무슨기준으로 불러오는건지 말씀해주세요

**Comment by naver-searchad** [comment]
광고주센터 화면을 보고 문의를 주셨지요.
해당 화면에서 사용하는 api가 답변 드린 위 api와 동일합니다.
즉, 해당 화면을 보시면 문의하신 내용이 다 나와 있습니다.

첫 질문에서 '지난 30일간'이라고 하신 게 바로 이 api의 기간 기준이고
화면상에 보이는 '노출수', '클릭수', '총비용', '직접전환율'이 곧  impCnt, clkCnt, salesAmt, drtCrto 입니다.
