### ISSUE TITLE
Campaign 필드 값 설명

### ISSUE THREAD

**Issue by SM10855** [naver/searchad-apidoc#255]
목록중 MasterReport 캠페인 설명부분입니다.
- 영문설명
The type for the campaign.
- 1: WEB SITE
- 2: NAVER Shopping Ad
- 3: POWER CONTENTS
- 4: BRAND SEARCH

- 한글설명
- 1: 웹사이트방문
- 2: 파워컨텐츠
- 3: 쇼핑

종종 다른것도 한글과 영문이 상이하게 나오고 맞지 않는데
어떤걸 기준으로 봐야하나요?

추가적으로 캠페인 유형이 플레이스 유형은 값이 어떤건지 알 수 있을까요

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

올려주신 정보에서 '영문설명'이 맞습니다. 한글 부분은 2번과 3번이 바뀌어 있네요.
소스가 어딘지 알려주시면 확인해서 수정하도록 하겠습니다.

그리고 플레이스 유형은 6번입니다.

**Comment by SM10855** [comment]
http://naver.github.io/searchad-apidoc/#/tags/MasterReport

이 부분에서 한글과, 영문 설명이 상이합니다.

추가적으로 목록중 MasterReport 에서 Ad Group 부분
Business Channel Id(Mobile), Business Channel Id(PC) 
이 부분 Field Name하고 Description 부분이 상이합니다.

**Comment by naver-searchad** [comment]
@SM10855 
말씀해 주신 부분 잘 확인했습니다.
담당자 통해서 수정 진행할 예정입니다.
알려 주셔서 감사합니다!
