### ISSUE TITLE
ASP로 작업중 invalid-signature 문의 드립니다.

### ISSUE THREAD

**Issue by airshivan** [naver/searchad-apidoc#256]
API Guide 페이지의 샘플 메뉴(http://naver.github.io/searchad-apidoc/#/samples)를
보며 ASP Classic으로 작업하고 있습니다.

어찌어찌 타임스탬프와 sha256-hmac 을 검색해서 다음과 같이 구현하고
실행을 시켰더니

	Dim X_Signature 
	Dim offsetInMillis : offsetInMillis = 60000 * GetTimeZoneOffset()
	Dim X_Timestamp : X_Timestamp = DateDiff("s", "01/01/1970 00:00:00", Now()) * 1000 - offsetInMillis + Timer * 1000 mod 1000

	X_API_KEY = X_API_KEY
	X_API_Scretkey = X_API_Scretkey
	X_Customer = X_Customer

	X_Signature = mac256(X_API_Scretkey,X_Timestamp&".GET./ncc/campaigns")
	Response.write X_Signature

	url ="https://api.naver.com/ncc/campaigns"
	Set xml = Server.CreateObject("Microsoft.XMLHTTP") 
	xml.Open "post",url,False
	xml.setRequestHeader "X-Timestamp",X_Timestamp
	xml.setRequestHeader "X-API-KEY",X_API_KEY
	xml.setRequestHeader "X-Customer",X_Customer
	xml.setRequestHeader "X-Signature",X_Signature
	xml.send
	ResponseText = xml.responseText
	Set xml = Nothing
	Response.write ResponseText

{"signature":"d569bab637b53bb5d8a976c848659c1dc17409ed9e4872eba4efdb11020b76db","title":"Invalid Signature","status":403,"detail":"Signature 'd569bab637b53bb5d8a976c848659c1dc17409ed9e4872eba4efdb11020b76db' is invalid.","type":"urn:naver:api:problem:invalid-signature"}
란 메세지가 뜹니다.

근데 샘플에서의 시그니처(PY6keeelL+7HV+498Y83BLv4K65XJRxmfbnZYVzutCA=)와 
제가 찾은 시그니처와는 형식이 좀 다른거 같은데...

뭐가 문제인지 알 수 있을까요?

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

base64 가 아닌 hexadecimal 로 인코딩한 것으로 보입니다.

**Comment by airshivan** [comment]
아, 감사합니다.
X_Signature = CryptoJS.HmacSHA256( X_API_Scretkey , 
                        X_Timestamp&".GET./ncc/campaigns").toString(CryptoJS.enc.Base64)

로 해서 값은 샘플과 비슷한 /pNMh5PnGLV6dUjwLxmvyj/Hvqv1wDW8mNAR3LkqDKs= 형식으로 바뀌었습니다.

그런데도 여전히 invalid-signature 가 발생합니다 ㅠㅠ

CryptoJS.HmacSHA256 를 CryptoJS.SHA256 로 해도 마찬가지구요...
타임스탬프도 13자리 숫자로 정상적으로 나옵니다.

**Comment by haedols8097** [comment]
안녕하세요. airshivan님
저도 classic asp로 개발을 하고 있는데
invalid-signature 에러로 고생을 하고 있습니다. ㅜㅜ
혹시 이 이슈 해결하셨는지요?
답변 부탁 드립니다.
