### ISSUE TITLE
키워드별 실시간 순위

### ISSUE THREAD

**Issue by sosklaus** [naver/searchad-apidoc#257]
키워드별 실시간 순위를 알수 있는 API가 있나요?

아니면 파싱으로 검색해서 순위를 조회할 경우 문제가 생기나요?

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

1.
문의 주신 현재 시점의 광고 노출 순위를 제공하는 API 기능은 존재하지 않으며 향후 제공할 계획도 없습니다.

API를 통해 제공되는 가장 최신 노출 순위 정보는
STAT(http://naver.github.io/searchad-apidoc/#/tags/Stat)에서
조회 기간(datePreset)을 오늘(Today)로 설정하시고
상세데이터(breakdown)여부를 시간대 별(hh24)로 설정하신 후
조회 대상필드를 avgRnk로 지정하시면
약 3시간 정도 지연된 1시간 단위 평균 노출 순위를 확인하실 수 있습니다.

주의 하실 점은 여러 매체에 노출 된 경우 모든 매체에서 노출된 순위의 평균이라는 점으로
혹 네이버 통합검색 PC나 모바일 검색의 평균 노출 순위만을 조회하고자 하시는 경우
최근평균 노출 순위(recentAvgRnk) 필드를 통해 조회가 가능합니다.
이때 추가로 breakdown 항목을 pcMblTp로 선택하시면 모바일 검색 및 PC 네이버 통합검색 내 최근 평균 노출 순위가 각각 리턴됩니다.
최근평균 노출 순위는 요청된 기간 파라미터와는 무관하며
현재 시점에서 과거 24시간 중 지표가 존재하는 가장  최근 1시간 동안의 네이버 통합검색(PC/모바일)매체에서 노출된 광고의 평균노출 순위를 의미하며 역시 최소 30분 ~최대 3시간 지연 데이터입니다.

2.
네이버 검색광고 시스템에 대해 제공되는 API 사용외에 크롤링, 기계적 접근 등은 네이버 검색광고 이용약관에 정의된 금지 사항으로서 민, 형사상 책임이 발생할 수 있으므로 주의 하셔야 합니다.
네이버 검색 결과 및 네이버 검색 서비스에 대한 크롤링 혹은 기계적 방식에 따른 정보 수집은
웹문서 및 삭제 정책
(https://help.naver.com/support/contents/contents.help?serviceNo=19634&categoryNo=19668)
을 참고하여 주시기 바랍니다.
