### ISSUE TITLE
네이버 쇼핑 검색 광고 제외키워드 설정이 가능한가요?

### ISSUE THREAD

**Issue by dd1233345** [naver/searchad-apidoc#259]
쇼핑검색 그룹 별로 제외키워드 설정이 가능한가요? 
가능하다면 어떤 부분을 참고해야되는지 알려주시면 감사하겠습니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

먼저 아래 api doc을 참조하셔서
원하시는 쇼핑검색 광고그룹의 제외키워드 target을 조회해야 합니다.
ownerId는 광고그룹ID
types는 'RESTRICT_KEYWORD_TARGET'로 요청합니다.

http://naver.github.io/searchad-apidoc/#/operations/GET/~2Fncc~2Ftargets%7B%3FownerId,types%7D

response 로 제외키워드 target을 불러왔다면
'target' 필드에 다음과 같이 키워드리스트를 추가해서 
update(PUT) api를 요청하면 됩니다.

`target: [{keyword: '키워드1'}, {keyword: '키워드2'}]`

http://naver.github.io/searchad-apidoc/#/operations/PUT/~2Fncc~2Ftargets~2F%7BtargetId%7D

이 api는 update(PUT)이므로
이후 다시 해당 광고그룹의 제외키워드를 추가/삭제하려면
항상 list 조회를 먼저 한 뒤
'target' 필드를 최종 원하는 상태로 업데이트 한 뒤 요청하시면 됩니다.

**Comment by jxamen** [comment]
답변을 토대로 성공했습니다. 감사합니다.
