### ISSUE TITLE
AD.tsv 파일 관련 문의

### ISSUE THREAD

**Issue by FreeEgo** [naver/searchad-apidoc#26]
tsv 파일을 받아서 디비 테이블에 저장하고 keyword_name을 업데이트 하는 작업을 하고 있습니다.
tsv파일을 보면 keyword_id 정보만 있고 keyword_name 정보가 없어서
Keyword[] keywords = Keywords.listByAdgroupId(rest, customerId, group_id)
로 키워드 ID를 받아온 뒤에 다시 디비의 keyword_id 정보를 찾아서 업데이트를 쳐주고 있는데
for문을 이용하여 돌려도 키워드 약 3만개를 id를 찾아서 업데이트를 하다보니
쿼리를 3만번 실행해서 작업시간이 5시간 이상이 걸리고 있습니다.
처음부터 keyword_name 을 같이 받아온다던지...뭔가 빠르게 처리하는 방법이 없나요?

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API 입니다. 

아마도 보고서 파일만 다운 받으시는 것 같습니다.
master report(http://naver.github.io/searchad-apidoc/#/tags/MasterReport) 중 
adkeyword 항목을 다운 받으시면 키워드명과 광고 키워드 아이디를 쉽게 맵핑 하실 수 있습니다. 
삭제된 광고 키워드의 경우는 마스터 리포트를 다운 받으실 때 특정 기간으로 받으시고 삭제 플래그를 
보시면 되겠습니다. 

저희 권장 드리는 방식은 master report를 다운 받으셔서 별도의 테이블에 업로드 하시고 
이를 계속 증분 업데이트 하는 방식 유지하시면서 보고서 데이터와 join 하시어 루프를 돌리지 
않아도 사용이 가능합니다.

감사합니다.
