### ISSUE TITLE
네이버 자동규칙 API 문의

### ISSUE THREAD

**Issue by 0xF4D3C0D3** [naver/searchad-apidoc#260]
안녕하세요?
네이버 광고도구에 자동규칙 이라는 기능이 있는데
이건 네이버 광고도구 API로는 등록이 불가능 한가요?

할 수 있으면 좋겠는데 현재는 지원되지 않는것 같습니다...

혹시 제가 모르고 있는 API가 있거나 앞으로 지원 여부만이라도 알려주시면 정말 감사하겠습니다.

좋은 하루 되세요.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.
답변 확인이 늦었습니다!

현재 검색광고 API에서 자동규칙 관련 API는 지원하지 않고 있습니다.
그리고 아직은 추후지원 계획이 없는 상태입니다.

**Comment by 0xF4D3C0D3** [comment]
그렇군요. 답변 감사 드립니다.
