### ISSUE TITLE
/keywordstool api 문의드립니다.

### ISSUE THREAD

**Issue by sdaehoon87** [naver/searchad-apidoc#261]
안녕하세요

여러가지 키워드를 많이 알고싶어서

키워드스툴기능으로 키워드를 확장시켜서 검색해보고싶습니다.

다른 답변글을 보니 시간은 25~30초정도 지켜주면 된다라고 나와있는데

시간을 지키면 키워드 수는 상관이 없는건가요?

----------------------------------------------------------------------------------------------------------
그리고 사족입니다만 RelKwdStat 서비스(즉 GET /keywordstool)를 통해 제공되는 정보는 네이버 검색광고 집행 및 운영 목적으로 사용 목적이 한정 되어 있어 이외의 목적으로 이용하셨을 때 민/형사상 책임이 발생할 가능성이 있으므로 사용시 주의 하셔야 합니다.
----------------------------------------------------------------------------------------------------------

이 내용이 추가로 있어서 질문드립니다.

목적은 검색광고집행을 원활히 하기위해서입니다.

꼭 그 계정에 맞는용도로만 되는건지 궁금합니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 API입니다. 

네이버 검색광고 API는 호출 속도의 제한이 존재합니다. 
속도는 시스템 상황에 따라 좀 다를 수 있습니다만 통상 초당25~ 30회이내 정도의 속도로 호출이 가능합니다. **문의 주신 연관키워드 (/keywordstool) 기능의 경우 초당 2~5회 정도의 속도로 호출이 가능합니다.** 
시스템 사용자가 몰리거나 해서 더 느려질 수 있지만 대체로 위의 속도 정도가 측정되고 있다는점 
참고 부탁드립니다. 호출수가 제한을 넘길 경우 에러가 리턴되는데요. 에러 리턴시 약 0.5초에서 1초 정도 sleep을 주셨다가 다시 호출해 주시면 되겠습니다. 속도가 일정치 않으므로 호출 속도를 클라이언트에 셋팅해 두시는 방식보다는 에러 처리 방식이 더 효율적입니다. 

문의 주신 내용 상 아마도 초당 호출 가능 횟수를 대기 시간으로 오해하신 것 같습니다. 
이외의 사용량의 제한은 없습니다.  

두번째로 문의 주신 데이터 제공 범위 및 목적 제한에 관하여 답변 드립니다. 
의미가 포괄적이기는 하나 광고를 운영하시는 전략이나 형태는 모든 광고주나 솔루션별로 
상의할 수 있으므로 이를 확정적으로 가이드 드리기는 어려울 것 같습니다.
원칙적인 관점에서 키워드 발굴 및 잡행 대상 키워드의 선택/변경 등의 용도로 활용해 주시는 형태를 "권장" 드립니다. 

또 한가지 중요한 부분은 제공 범위인데요. 
제공 범위는 소유하고 있는 계정, 네이버 검색광고 시스템을 통해 권한(광고관리 권한 등)을 받은 타인 계정 에 제공이 가능합니다. 타인 계정의 제공할 정보를 조회할때는 가지고 계신 본인의 라이선스와 비밀키로 호출 하시더라도 다른 API 기능과 동일하게 권한을 제공한 타인 계정의 명의 즉 달리 말해 해당 계정의 커스터머 아이디를 헤더(x-customer)에 기재 하셔서 호출 하시는 형태가 바람직합니다.

감사합니다.
