### ISSUE TITLE
SHOPPING 그룹생성 시 오류가 발생 문의 드립니다.

### ISSUE THREAD

**Issue by rio7412** [naver/searchad-apidoc#262]
안녕하세요 
WEB_SITE 캠패인의  그룹생성은 잘되었습니다. 하지만 SHOPPING으로 생성하려 할 경우  

다음과 같은 메세지가 출력됩니다.
responseBody : {"code":1018,"status":404,"title":"No permission to access the resource."}

이렇떤 어떻게 해야 할지 알려주세요.

참고로 넘기는 파라메터의 값이 필요할 경우 올리도록 하겠습니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API 입니다.

알려주신 정보가 충분하지 않아 정확한 원인을 확인 할 수 없습니다. 하지만 응답코드 `1018`의 경우 본인 소유가 아니거나, 또는 권한을 위임받지 않은 광고주의 캠페인에 대한 접근이 발생할때 응답하는 코드입니다. 

그룹 생성시 사용한 캠페인의 번호 또는 사업채널의 번호에 대해 다시 확인이 필요해 보입니다.

감사합니다.

**Comment by rio7412** [comment]
안녕하세요 빠른답변 감사합니다.

죄송하지만 한번더 물어볼게 있어요....
광고주 API에 대한 작업을 처음해보다 보니 막히면 대책이 없네요..... 물어볼곳이 여기뿐이라..ㅠㅠ

**WEB-SITE의 그룹을 생성시에는 정상적**으로 되지만 **SHOPPING의 그룹을 생성 시 안되는것**은 권한이 따로 있기 때문인지요?

**채널의 경우에도 권한이 따로 부여가 되어야 하는게 있는지요..** 
(사용한 채널ID의 상태는 적격입니다.)

참고로 SHOPPING 그룹을 만들 때 전송한 Body부분의 내용을 아래에 붙입니다.

request body :
adRollingType=PERFORMANCE,
adgroupAttrJson={
  "campaignTp" : "1"
},
adgroupType=SHOPPING, 
bidAmt=100, 
budgetLock=false,
contentsNetworkBidAmt=70,
dailyBudget=1000,
keywordPlusWeight=100, 
mobileChannelId=a001-00-000000000149470,
mobileNetworkBidWeight=100, 
name=링크쇼핑#1 1그룹,
nccCampaignId=cmp-a001-02-000000002224338,
pcChannelId=a001-00-000000000149470,
pcNetworkBidWeight=100,
targets=[
Target(editTm=null, nccTargetId=null, ownerId=null, regTm=null, 
target={THU=0, TUE=229376, SAT=0, WED=0, FRI=0, SUN=0, MON=491520}, targetTp=TIME_WEEKLY_TARGET), 
Target(editTm=null, nccTargetId=null, ownerId=null, regTm=null, target={white={mediaGroup=[1], media=[27758]}, type=3}, targetTp=MEDIA_TARGET), 
Target(editTm=null, nccTargetId=null, ownerId=null, regTm=null, target={pc=true, mobile=false}, targetTp=PC_MOBILE_TARGET)
], 
useCntsNetworkBidAmt=false,
 useDailyBudget=true, 
useKeywordPlus=false, 
userLock=true, 
customerId=1029864, 
nccAdgroupId=null, 
status=null, 
statusReason=null, 
targetSummary=null, 
regTm=null, 
editTm=null

responseBody : {"code":1018,"status":404,"title":"No permission to access the resource."}
