### ISSUE TITLE
API에러 문의드립니다.

### ISSUE THREAD

**Issue by SteveKim7878** [naver/searchad-apidoc#263]
X-Transaction-ID : BCLJ7RPQ9HIJR

API 권한 에러인 것 같은데 해당 트랜잭션에서 발생한 에러는 어떤 건지 궁금합니다.

**Comment by SteveKim7878** [comment]
X-Transaction-ID : BCLJ7RPQ9HIJR

API 권한 에러인 것 같은데 해당 트랜잭션에서 발생한 에러는 어떤 건지 궁금합니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.
지금은 해당 에러 없이 잘 쓰고 계실 듯하지만 기록을 위해 답변글을 남깁니다.

위 transaction에서 발생한 에러는 '권한없음'인데요
광고주로부터 광고권한을 요청/수락하기 전에 API를 호출해서 발생했다고 보시면 되겠습니다.
