### ISSUE TITLE
API  Shopping 그룹생성 관련 문의

### ISSUE THREAD

**Issue by rio7412** [naver/searchad-apidoc#264]
안녕하세요 

죄송하지만 한번더 물어볼게 있어요....

WEB-SITE의 그룹을 생성시에는 정상적으로 되지만 SHOPPING의 그룹을 생성 시 안되는것은 권한이 따로 있기 때문인지요?

채널의 경우에도 권한이 따로 부여가 되어야 하는게 있는지요..
(사용한 채널ID의 상태는 적격입니다.)

참고로 SHOPPING 그룹을 만들 때 전송한 Body부분의 내용을 아래에 붙입니다.

request body :
adRollingType=PERFORMANCE,
adgroupAttrJson={
"campaignTp" : "1"
},
adgroupType=SHOPPING,
bidAmt=100,
budgetLock=false,
contentsNetworkBidAmt=70,
dailyBudget=1000,
keywordPlusWeight=100,
mobileChannelId=a001-00-000000000149470,
mobileNetworkBidWeight=100,
name=링크쇼핑#1 1그룹,
nccCampaignId=cmp-a001-02-000000002224338,
pcChannelId=a001-00-000000000149470,
pcNetworkBidWeight=100,
targets=[
Target(editTm=null, nccTargetId=null, ownerId=null, regTm=null,
target={THU=0, TUE=229376, SAT=0, WED=0, FRI=0, SUN=0, MON=491520}, targetTp=TIME_WEEKLY_TARGET),
Target(editTm=null, nccTargetId=null, ownerId=null, regTm=null, target={white={mediaGroup=[1], media=[27758]}, type=3}, targetTp=MEDIA_TARGET),
Target(editTm=null, nccTargetId=null, ownerId=null, regTm=null, target={pc=true, mobile=false}, targetTp=PC_MOBILE_TARGET)
],
useCntsNetworkBidAmt=false,
useDailyBudget=true,
useKeywordPlus=false,
userLock=true,
customerId=1029864,
nccAdgroupId=null,
status=null,
statusReason=null,
targetSummary=null,
regTm=null,
editTm=null

responseBody : {"code":1018,"status":404,"title":"No permission to access the resource."}

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

문의 주신 내용중에 그룹의 사업 채널 번호 (pcChannelId, mobileChannelId)는 등록된 채널 번호가 아닙니다. 정상적인 사업채널 번호는 `bsn-a001-XX-XXXXXXXXXXXXXXX`형식의 번호입니다. 아마도 앞에 `bsn-`가 빠진듯 합니다. 다시 확인 부탁드립니다.

감사합니다.

**Comment by rio7412** [comment]
해결했습니다 감사합니다.
