### ISSUE TITLE
쇼핑 그룹 만든 다음 소재 등록시 에러 확인 부탁드립니다.

### ISSUE THREAD

**Issue by rio7412** [naver/searchad-apidoc#265]
안녕하세요 
쇼핑 그룹을 만든 후 소재를 등록하고 있습니다.
다른 글에서 "isList":true 에 대한 부분과  [] 로 묶어주는 부분까지 했는데....
잘 안돼어서 문의드립니다.

파라메터는 
requestBody : 
[{"customerId":1029864,
"nccAdgroupId":"grp-a001-02-000000012111805",
"type":"SHOPPING_PRODUCT_AD",
"ad":{},
"inspectRequestMsg":"요청 메시지...",
"userLock":false,
"isList":true,
"referenceKey":"4581683596"}]

호출 후 

responseBody : {"title":"Bad Request",
"status":400,
"detail":"JSON parse error: Cannot deserialize instance of `com.naver.searchad.heroes.domain.ncc.NccAd` out of START_ARRAY token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `com.naver.searchad.heroes.domain.ncc.NccAd` out of START_ARRAY token\n at [Source: (PushbackInputStream); line: 1, column: 1]"}

응답이 나왔습니다.

바쁘시겠지만 확인 부탁드리겠습니다.

그리고, referenceKey의 값은 광고주 상품검색에서 
네이버 소핑 상품 ID (몰 상품ID) 중 어떤값을 써야하는지요? 혹시 완전 다른값인가요?

**Comment by rio7412** [comment]
안녕하세요 ^^ 바쁘신데 계속 물어볼게 생기네요..ㅜㅜ

혹시 동일광고주의 다른 그룹에 등록된 소재일 경우 등록이 안되는건가요? 
referenceKey의 값은 어떤게 들어가는지는 알아내어서 테스트를 진행했는데도 동일한 Respons 가 오고 있는 상태입니다.

**Comment by rio7412** [comment]
테스트 한 RequestBody부분을 다시 올릴게요 
위의것에는 adAttr 이 없었어요.

requestBody : 
[{"customerId":1029864,
"nccAdgroupId":"grp-a001-02-000000012111805",
"type":"SHOPPING_PRODUCT_AD",
"ad":{"pc":{"final":"https://www2.linkprice.com"},
        "mobile":{"final":"https://www.linkprice.com"},
        "description":"첫번째 입력합니다. 너무짧아서 길게~~~",
        "headline":"첫번째"},
"adAttr":{"useGroupBidAmt":true,
              "bidAmt":800},
"inspectRequestMsg":"요청 메시지...",
"userLock":false,
"isList":true,
"referenceKey":"10355360693"}]

responseBody : {"title":"Bad Request",
"status":400,
"detail":"JSON parse error: Cannot deserialize instance of `com.naver.searchad.heroes.domain.ncc.NccAd` out of START_ARRAY token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `com.naver.searchad.heroes.domain.ncc.NccAd` out of START_ARRAY token\n at [Source: (PushbackInputStream); line: 1, column: 1]"}

**Comment by rio7412** [comment]
안녕하세요.  테스트를 좀 더 해보았습니다,
위의 테스트에서 referenceData가 빠져 있길래 추가적으로 더 넣어서 테스트를 진행했지만 동일한 결과가 출력되었습니다.
requestBody : 
[
{
	"customerId":1029864,
	"nccAdgroupId":"grp-a001-02-000000012111805",
	"type":"SHOPPING_PRODUCT_AD",
	"ad":{},
	"adAttr":{
		"useGroupBidAmt":true,
		"bidAmt":800
		},
	"enable":true,
	"status":"ELIGIBLE",
	"statusReason":"ELIGIBLE",
	"inspectStatus":"APPROVED",
	"inspectRequestMsg":"요청 메시지...",
	"userLock":false,
	"isList":true,
	"referenceKey":"82126203750",
	"referenceData":
		{
		"mallName":"노바리빙",
		"category1Name":"생활/건강",
		"category2Id":"50000076",
		"category1Id":"50000008",
		"mpTp":"1",
		"productName":"노바리빙 행거형 10단 신발정리대",
		"prodTypeCd":"P01001",
		"lowPrice":"69000",
		"category3Name":"정리함",
		"isLgtModelMat":"0",
		"purchaseCnt":44,
		"imageUrl":"https://shopping-phinf.pstatic.net/main_8212620/82126203750.jpg",
		"dvlryFeeCont":"0",
		"category3Id":"50000905",
		"imgStatusCd":"I01003",
		"category4Id":"50002471",
		"mobilePrice":"69000",
		"id":"82126203750",
		"mblProdUrl":"https://m.smartstore.naver.com/main/products/4581683596",
		"brand":"",
		"priceUnit":"KRW",
		"category4Name":"신발정리대",
		"adCustomerId":1029864,
		"saleTp":"0",
		"mallProductId":"4581683596",
		"maker":"노바",
		"DEL_FLAG":0,
		"displayNx":"1",
		"parentId":"82126203750",
		"rcvYn":"Y",
		"reviewCountSum":14,
		"productTitle":"노바리빙 행거형 10단 신발정리대",
		"APPLY_TM":"1566435959879",
		"hasDvlryFeeCont":"1",
		"keepCnt":63,
		"category2Name":"수납/정리용품",
		"mallProductUrl":"https://smartstore.naver.com/main/products/4581683596",
		"openDate":"20190704171302",
		"fullMallCatNm":"생활/건강>수납/정리용품>정리함>신발정리대",
		"mallNo":"366982",
		"prodStatusCd":"P02015"
		},
	"nccQi":{"qiGrade":6},
	"delFlag":0
}
]

responseBody :
 {
	"title":"Bad Request",
	"status":400,
	"detail":"JSON parse error: Cannot deserialize instance of `com.naver.searchad.heroes.domain.ncc.NccAd` out of START_ARRAY token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `com.naver.searchad.heroes.domain.ncc.NccAd` out of START_ARRAY token\n at
 [
	Source: (PushbackInputStream); 
	line: 1,
	column: 1
]"
}

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

isList 파라미터의 경우 body가 아닌 query parameter로 확인됩니다.
`/api/ncc/ads?isList=true`
그리고 referenceData는 필요치 않습니다.

**Comment by rio7412** [comment]
답변 감사합니다 ^^ 
소스를 수정하여 쿼리 파라메터로 해서 보냈는데...아래와 같은 메세지가 나옵니다.
말씀하신데로 
/ncc/ads?isList=true 로 쿼리에 넣어서 호출했는데....
signature  메세지가 나오는데 어떻게 해야되는지요? ㅠㅠ 
어떤 파라메터가 Body 에서 빠졌는지 알려주시면 감사하겠습니다..ㅠㅠ

내용은 아래와 같습니다.
requestBody:
[{
              "customerId":1029864,
              "nccAdgroupId":"grp-a001-02-000000012111805",
              "type":"SHOPPING_PRODUCT_AD ",
              "ad":{},
              "adAttr":{
                            "useGroupBidAmt":true,
                            "bidAmt":800
              },
              "enable":true,
              "inspectStatus":"APPROVED",
              "inspectRequestMsg":"요청 메시지...",
              "userLock":false,
              "referenceKey":"82126203750",
              "delFlag":0
}
]

responseBody : {
              "signature":"SMkWXxpEQyBWBYWrbsgU5es0Cr53zC7NwI2Tu0YfMTg=",
              "title":"Invalid Signature",
              "status":403,"detail":
              "Signature 'SMkWXxpEQyBWBYWrbsgU5es0Cr53zC7NwI2Tu0YfMTg=' 
              is invalid.","type":"urn:naver:api:problem:invalid-signature"
}

**Comment by naver-searchad** [comment]
다른 invalid signature 관련 문의들을 찾아 보시면 아시겠지만
signature 생성에 query parameter 는 포함되면 안됩니다.
참고 #210

**Comment by rio7412** [comment]
안녕하세요 확인하여 테스트를 다시 진행하였습니다.... 

**최종적으로 호출되는 request 부분의 Debuging 부분을 캡쳐하여 첨부로 올립니다.**
URL 쿼리에서 isList 부분 제거하고 requestBody  부분에 다시 추가하였습니다.
PS : 혹시 isList가 boolean인가요? String 인가요?

호출하는부분을 Debuging 하여 파라메터를 확인하였는데 쿼리에 들어가는 부분이 확인되지 않아서요..ㅠㅠ

request 시 생성된 인자들은 첨부파일에 캡쳐하여 올렸습니다.
![request호출 전 세팅 부분](https://user-images.githubusercontent.com/48825716/63669866-2eb59a80-c816-11e9-8c78-8edbe8c6bd4f.png)
![request호출부분](https://user-images.githubusercontent.com/48825716/63669868-2eb59a80-c816-11e9-85d3-a7bd6c4401bb.png)

requestBody:
[
{
          "nccAdgroupId":"grp-a001-02-000000012111805",
          "type":"SHOPPING_PRODUCT_AD ",
          "ad":{},
          "adAttr":{
                    "useGroupBidAmt":true,
                    "bidAmt":800
          },
          "enable":true,
          "status":"ELIGIBLE",
          "statusReason":"ELIGIBLE",
          "inspectStatus":"APPROVED",
          "inspectRequestMsg":"요청 메시지...",
          "userLock":false,
          "isList":true,
          "referenceKey":"82126203750",
          "nccQi":{
                    "qiGrade":6
          },
          "delFlag":0
}]

responseBody : 
{
          "timestamp":"1566800349983",
          "detail":"Request has expired.",
          "title":"Invalid Timestamp",
          "status":403,
          "type":"urn:naver:api:problem:invalid-timestamp"
}

**Comment by naver-searchad** [comment]
http request url 은 `/api/ncc/ads?isList=true`가 맞습니다.
signature 생성 시 들어가는 url에서는 `/api/ncc/ads`까지만 이용해야 한다는 의미였습니다.
#210 내용을 잘 참고해 주시기 바랍니다.

**Comment by rio7412** [comment]
안녕하세요 도움덕분에 성공하였습니다 ^^

다른분들도 도움될수 있도록 소스부분을 캡쳐하여 올립니다.

고맙습니다.

signature 부분이 이해가 잘 안됐었는데 도움주셔서 감사합니다 ^^

![request호출 성공](https://user-images.githubusercontent.com/48825716/63732795-d7b0d380-c8b0-11e9-9bfa-fbc6a4ed9c5f.png)
