### ISSUE TITLE
Stats 에서 avg rnk 들의 의미에 대해서

### ISSUE THREAD

**Issue by bluesme519** [naver/searchad-apidoc#266]
안녕하세요.
stats 에서 불러올 수 있는 rank 관련 fields 값들이

avgRnk
recentAvgRnk
pcNxAvgRnk
mblNxAvgRnk
이렇게 4가지가 있습니다.

각각이 의미하는 바가 정확하게 어떻게 될까요?
예를들어 이 글 작성일 기준으로 그저께날짜인 2019-08-24~2019-08-24를 조회했다고 한다면 각각 어떤걸 의미할까요
avgRnk - 2019-08-24기준 pc,mobile합친 평균
recentAvgRnk - 조회를 실행한 날짜(2019-08-26')기준 지난 일주일 뭐 이런식?
pcNxAvgRnk - 2019-08-24 기준 pc 평균
mblNxAvgRnk - 2019-08-24 기준 pc 평균

이런식일까요?

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

API 문서 상으로는 설명이 다소 부족한 것이 사실입니다.
이는 API를 이용하시는 분들이 API만 사용하는 것이 아니라
광고주센터 UI를 통해 광고관리에 대한 어느 정도 이해를 하고 있으리란 점을 바탕으로 하고 있기 때문입니다.

광고관리 화면 상에서 원하시는 광고그룹이나 키워드, 소재 등의 목록을 보시면
위의 지표들을 포함한 여러 지표들을 추가하거나 제거해서 테이블 목록으로 조회해 보실 수가 있고
해당 지표들의 타이틀에 보면 '물음표 툴팁'이 있어 이를 통해 자세한 설명을 보실 수도 있습니다.
혹은 도움말 검색을 통해 필요한 정보를 더 얻으실 수도 있습니다.

참고로 위 4가지 지표는 광고관리 화면 상에서 각각
`평균노출순위`
`최근통검평균노출순위`
`PC통검평균노출순위`
`모바일통검평균노출순위`
입니다.

**Comment by bluesme519** [comment]
평균노출순위 - 조회한 날짜에 대한 평균노출순위
최근통검평균노출순위 - 조회시각으로부터 지난 24시간의 평균
PC통검평균노출순위 - 조회시각으로부터 지난 24시간의 평균
모바일통검평균노출순위 - 조회시각으로부터 지난 24시간의 평균
이라고 광고관리자 톡톡에서 답변받았습니다. 여기 공유합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

상담 받으신 내용이 정확한 정의가 아니라서 직접 대화 하신 저희 고객센터 담당자 분께 확인해 
보니 안내에 오류가 있었습니다. 
혼란 드린 점 사과의 말씀 드립니다. 

각 항목별 정의 말씀 드립니다. 

평균노출순위
-->통계 기간동안 모든 영역에 노출된 대상 광고의 평균 노출 순위 입니다. 
계산식은 통계기간 중 대상 광고가 노출된 모든 매체(여역)별 노출 순위의 합을 통계기간 중 대상 광고의 총노출수로 나눈 값입니다. 

최근통검평균노출순위 
--> 조회 시점에서 과거 24시간 중 지표가 존재하는 가장 최근 1시간 동안의 네이버 통합검색(PC/모바일)매체에서 대상 광고가 노출된 순위의 합을 동일 조건의 대상 광고의 노출수 합으로 나눈 값입니다.

PC통검평균노출순위 
-->통계 기간동안 네이버 PC통합검색 매체(영역)에 노출된 대상 광고의 평균 노출 순위 입니다. 
계산식은 평균노출 순위와 동일하나 지표 수집의 범위가 PC 통합검색 매체로 제한된다고 생각해 주시면 되겠습니다.
모바일통검평균노출순위 
-->통계 기간동안 네이버 모바일검색 매체(영역)에 노출된 대상 광고의 평균 노출 순위 입니다. 
계산식은 평균노출 순위와 동일하나 지표 수집의 범위가 네이버 모바일검색 매체로 제한된다고 생각해 주시면 되겠습니다.

참고로 광고관리 화면내  파워링크 상품 키워드 항목에서 표 우측 상단에 다운로드 버튼 옆 기본설정 혹은 사용자 설정 버튼을 클릭하시면 아래와 같이 제공 가능한 모든 항목이 표시 됩니다. 이 항모들에서 물음표 아이콘에 마우스 오버를 하시면 세부 설명을 보실 수 있습니다. 
![image](https://user-images.githubusercontent.com/18188635/63744938-d0eb8600-c8db-11e9-9788-0b5a60c77940.png)

감사합니다.

**Comment by bluesme519** [comment]
정말 상세한 답변 감사합니다. 궁금하던 것이 완전 해결됬습니다!
