### ISSUE TITLE
'/ncc/keywords' put 으로 bidAmt update 관련

### ISSUE THREAD

**Issue by bluesme519** [naver/searchad-apidoc#267]
```
def update_keyword_cpc(keyword_id,ad_group_id, bid_amt):
    retrieved_adkeyword = {'nccKeywordId':keyword_id,'nccAdgroupId':ad_group_id}
    uri = '/ncc/keywords'
    method = 'PUT'
    retrieved_adkeyword['bidAmt'] = bid_amt
    retrieved_adkeyword['useGroupBidAmt'] = 0
    r = requests.put(BASE_URL + uri, params={'fields': 'bidAmt'}, json=[retrieved_adkeyword], headers=get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID))
    return('id: ', keyword_id, ' / updated_cpc: ',bid_amt)
```

위와 같은 코드로 입찰가를 업데이트하고싶어 function 을 만들었습니다.

한번에 한 200개 정도 for loop 으로 로직을 만들어 한번에 update하려고하니 중간에 연결이 끊기는 것 같네요.

limit이 걸려있나요? 혹은 한번에 여러개의 키워드의 입찰가를 업데이트 하는 방법은 없나요?

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

API 호출은 초당 수 건 이상 발생시 제한될 수 있습니다.
약간의 interval을 두고 호출하시는 걸 권장합니다.

키워드 입찰가 업데이트의 경우,
여러 키워드를 하나의 호출로 처리할 수 있습니다.
request body 포맷이 'nccKeywords[]' 즉 array이므로
[] 내에 원하시는 키워드 객체를 복수로 담아 하나의 호출로 요청하시면 됩니다.

**Comment by bluesme519** [comment]
아 그렇다면'nccKeywords에 키워드를 리스트로 담고 bidamt도 리스트로 담으면 한번에 처리가 가능한가요? 개수제한은 없나요?

**Comment by bluesme519** [comment]
```
response status_code = 400
response body = {'title': 'Bad Request', 'status': 400, 'detail': 'JSON parse error: Cannot deserialize instance of `java.lang.String` out of START_ARRAY token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_ARRAY token\n at [Source: (PushbackInputStream); line: 1, column: 18] (through reference chain: java.util.ArrayList[0]->com.naver.searchad.heroes.domain.ncc.NccKeyword["nccKeywordId"])'}
```

각각에 python list 로 넣어봤더니 이런 에러가 나네요

**Comment by naver-searchad** [comment]
'nccKeywords[]'라는 건 'nccKeyword 객체 형태의 리스트'라는 의미입니다.
위에 올려주신 코드에서는,
`[retrieved_adkeyword]`
이 부분이 nccKeyword 객체 하나를 리스트에 넣은 형태이므로
'retrieved_adkeyword' 객체를 원하는 갯수만큼 [] 안에 넣어 주시면 될 것 같습니다.
따라서 bidAmt를 따로 리스트에 담는 게 아니라
retrieved_adkeyword 객체 내에 각각 들어가는 것입니다.
