### ISSUE TITLE
statReport 와 프리미엄로그분석/다차원보고서 내용 관련

### ISSUE THREAD

**Issue by bluesme519** [naver/searchad-apidoc#268]
이전 답변들을 보고, 다차원보고서의 내용을 따로 api로 제공하지는 않으신다는 말씀은 확인했습니다.

다만 제가 확인하고 싶은것은 키워드광고 시 키워드 별로
1. 장바구니 등 상세한 전환내용
2. 체류시간
3. 페이지뷰
를 얻어오고 싶습니다. 프리미엄로그분석을 설치완료한 상태이고 다차원보고서에서는 해당 내용이 확인 되고있습니다.
혹시 stat report 가 해당 내용을 주나 싶어서 테스트를 해보고 있는데

```
def get_statReport():
    uri = '/stat-reports'
    method = 'GET'
    r = requests.get(BASE_URL + uri, headers=get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID))
    parsed = r.json()
    return(parsed)
```

위와 같이 하니 내용을 4개의 리포트가 있다고 보여지네요
여기에서 이제 
https://naver.github.io/searchad-apidoc/#/operations/GET/~2Fstat-reports~2F%7BreportJobId%7D
각각의 리포트를 자세히 보고싶어서 아래와 같이 해봤습니다.

```
def get_statReport2(jobId):
    uri = '/stat-reports'
    method = 'GET'
    r = requests.get(BASE_URL + uri, params={'reportJobId': jobId},headers=get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID))
    parsed = r.json()

    return(parsed)
```
jobid 에는 statReport() 에서 reportJobId 값을 하나 넣어봤는데 결과값이 statReport() 와 똑같네요
그리고 jobid 는 각각 무엇을 의미하나요. 제가 이해한대로 각각이 report 인건 맞는건가요?
혹시 사용법이 어떻게 될지 여쭤봐도 될까요?

정리하면
1. statreport 상세보기 를 하는 방법
2. statreport로 불러오면 나오는 4개의 reportJobId마다 각각 하나의 리포트를 의미하는건지
3.  장바구니 등 상세한 전환내용, 체류시간,  페이지뷰를 statReport로 볼수있는지. 혹은 다른 방법이 있는지

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

1. Response 에는 downloadUrl 과 status 가 있습니다. BUILT 상태일때 downloadUrl 을 통해 받으실수 있습니다.

2. reportJobId 는 요청하신 각각의 보고서의 ID 입니다.

3. 보고서의 상세내용은 아래와 같습니다.
대용량 다운로드 보고서 데이터 사양서 다운로드
http://searchad.naver.com/File/downloadfilen/?type=10&filename=masterreport808.pdf
참고로 statReport에서 전환은 Conversion Report (reportTp : AD_CONVERSION) 로 제공하고 있으며,
체류시간 페이지뷰는 제공하지 않고 있습니다.
