### ISSUE TITLE
tsv 파일 관련 문의

### ISSUE THREAD

**Issue by FreeEgo** [naver/searchad-apidoc#27]
매일 tsv파일을 받아서 보고서를 생성하고 있습니다.

그런데 이번 주말부터 tsv 파일을 받아올때 간간히

{"status":400,"title":"Bad Request","detail":"invalid id","fields":"id"}

위와 같은 내용만 들어서 BUILT가 되어버립니다.

원인을 알 수 있을까요?

**Comment by naver-searchad** [comment]
안녕하세요. 
내부 보고서 다운로드 시스템 문제로 일부 서버에서 보고서를 정상적으로 생성/전달하지 못했습니다.
24일 새벽 3시경부터 26일 오후 3시경까지 문제가 있었습니다.
문제가 되었던 보고서의 경우 재 요청하셔서 다운로드 받으시기 바랍니다.
업무에 불편을 드려서 대단히 죄송합니다.
