### ISSUE TITLE
Adgroup api를 통한 Target 정보 조회 오류

### ISSUE THREAD

**Issue by angalle** [naver/searchad-apidoc#270]
대량의 adgroup 조건을 조회하는데 
꽤 시간이 지난 adgroup 데이터도 조회하고있습니다.

어떤 Target은 null이 아닌 정상적인 값으로 오지만
어떤 target은 null로 아무것도 들어오지 않습니다.

혹시 이전의 히스토리나

adgroup api로 이전의 adgroup을 조회하면 target정보가 없거나
target api로 따로 조회하거나 해야하는 조건이나

히스토리가 있을까요 ?

![image](https://user-images.githubusercontent.com/10177319/64149894-1bcc4700-ce62-11e9-89bc-782c1390e9cd.png)

![image](https://user-images.githubusercontent.com/10177319/64149986-3e5e6000-ce62-11e9-938b-f6152ee713ab.png)

**Comment by naver-searchad** [comment]
안녕하세요? 검색광고 API입니다.
Adgroup에 대한 [단건 조회](http://naver.github.io/searchad-apidoc/#/operations/GET/~2Fncc~2Fadgroups~2F%7BadgroupId%7D)의 경우에는 그룹에 속한 타겟 정보를 포함하여 받을 수 있습니다. 하지만 [여러 그룹에 대한 조회](http://naver.github.io/searchad-apidoc/#/operations/GET/~2Fncc~2Fadgroups%7B%3Fids%7D)의 경우에 그룹의 타겟 정보는 포함하지 않습니다.

단건 조회라 하더라도 타겟의 target 프로퍼티가 null인 경우는 해당 타겟을 사용하지 않는 경우입니다.
그룹의 등록된 시간에 상관없이 현재 유효한 그룹인 경우 조회가 가능합니다.

감사합니다.

**Comment by angalle** [comment]
그러면 조회할때 get api로만 조회를 해야하나요 ?
아니면 그 캠페인안에 그룹이 한개일때만 타겟정보가 나오는건가요 ?

**Comment by angalle** [comment]
여러그룹api로 조회햇을때 나오는 Target정보들은
캠페인안에 그룹이 하나밖에 없으면 나오는건가요 ?

여러그룹 api로 조회했을때도 조회되는 부분이 있어가지구요

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API 입니다.

여러 그룹을 조회하는 list API에 포함되는 타겟 정보는 `targetSummary` 프로퍼티이고, 이 정보는 타겟에 대한 요약 정보입니다.

또한 캠페인 하위에 그룹이 하나만 있을 경우에 `targets` 프로퍼티에 타겟 정보가 포함되어 있습니다.
감사합니다.

**Comment by mz-heesun** [comment]
네 알겟습니다..

그럼 혹시 adgroup을 여러건조회하면서 target정보도 함께나오게 할 방법은 단건조회방법밖엔 없는거죠 ?
다른 방법이있을까해서요

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API 입니다.

타겟 정보를 조회하기 위해서는 광고 그룹을 단건 조회하시거나, [Target API](http://naver.github.io/searchad-apidoc/#/operations/GET/~2Fncc~2Ftargets%7B%3FownerId,types%7D)를 이용하여 광고 그룹별 타겟팅을 따로 조회 하셔야 합니다.

감사합니다.

**Comment by mz-heesun** [comment]
감사합니다
