### ISSUE TITLE
Target api관련 호출 오류 

### ISSUE THREAD

**Issue by mz-heesun** [naver/searchad-apidoc#271]
target api로 변경하고 다시 호출을 하니 오류가 나는 부분이 생겼습니다.

400 Bad Request. X-Trasaction-ID : nulll 
Response Body <html><body><h1>400 Bad request</h1></body></html>
Your borwser sent an invalid request.

이렇게 오류메세지가 오고있는데 
어떤 특정한 상황에서 나는것같은데 

단순히 제 요청이 잘못된건가요 ?

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

올려주신 정보만으로는 확인 가능한 내용이 없을 것 같습니다.
어떤 request를 어떤 내용으로 보냈는지와
response 도 좀 더 자세히 공유해 주시면 좋겠습니다.

**Comment by mz-heesun** [comment]
네네 너무 정보없이 보냈습니다.
호출이 정상적인게 있고 없고 구분이 있어서 저도 좀 두서없이 보내드렸습니다.

지금 디버깅 하다가 확인한 부분인데 
target api 다수건 조회할때 
owerids의 최대개수가 있을까요 ?

**Comment by mz-heesun** [comment]
400개 조회시 정상호출되는것으로 확인하였고
500개 조회 시 호출이 응답에러로 BadRequest를 응답하는것으로 확인하였습니다.

정확한 수치는 알수 없으나 테스트 결과 확인되었습니다.
