### ISSUE TITLE
에러확인 부탁드립니다.

### ISSUE THREAD

**Issue by SteveKim7878** [naver/searchad-apidoc#272]
X-Transaction-ID:BD0L1HN2HHIPV
2019-09-06 15:29:07 경에 요청한 것으로 응답은 Cannot handle the request. Too many requests already exist 로 확인이 되나 
보다 정확한 오류 원인을 알고 싶어 문의 드립니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

API 요청 처리시 customerId 단위로 일정 수준의 request 요청수 제한 관리가 되고 있습니다.
현재는 초당 수 건 이상 정도의 제한수준이라고 보시면 되겠습니다.
