### ISSUE TITLE
Adgroup: list (keyword plus restricted keywords) 조회 문의

### ISSUE THREAD

**Issue by rio7412** [naver/searchad-apidoc#273]
안녕하세요
Adgroup: list (keyword plus restricted keywords) API 사용에 대한 문의를 올립니다.

호출 시 Get 방식으로 호출했구요

request 정보
request.getHttpMethod().name() : GET
path : /ncc/adgroups/grp-a001-02-000000012111805/restricted-keywords
request.asString() :com.mashape.unirest.http.HttpResponse@3b0ee03a

response 정보 :
responseBody : []

빈 배열만 나오고 있는데요.. 파라메터에 뭔가 추가되거나 하는것이 필요한지요...ㅠㅠ

답변 부탁드리겠습니다.

**Comment by naver-searchad** [comment]
@rio7412 안녕하세요? 네이버 검색광고 API 입니다.

문의하신 그룹의 노출 제한 키워드에 등록된 내용이 없어서 빈 배열이 리턴되었습니다.

감사합니다.
