### ISSUE TITLE
Breakdown in /stat request not working

### ISSUE THREAD

**Issue by conmolloy** [naver/searchad-apidoc#274]
Hello, 

I want to get a bunch of information about campaigns split by device type pc vs mobile. I added the breakdown parameter to my request but I am still unable to get the outputting data to split by device type. No matter what value I set the breakdown parameter it doesn't seem to change the data at all. I am coding this in Python:

Here is request:
 ` r = requests.get(BASE_URL + uri, params={'id': j, 'fields': '["clkCnt", "impCnt", "ctr", "cpc", "avgRnk", "ccnt"]', 'timeRange': '{"since":"2019-09-10","until":"2019-09-10"}', 'breakdown': 'pcMblTp' }, headers=get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID))`

Here is the output (anonymised):
`{'summary': {'dateStart': '2019-09-10', 'dateEnd': '2019-09-10'}, 'data': [{'ctr': z, 'clkCnt': y, 'dateStart': '2019-09-10', 'cpc': x, 'ccnt': 0, 'avgRnk': j, 'dateEnd': '2019-09-10', 'impCnt': 4117}], 'compTm': '201909120330', 'cycleBaseTm': '201909110000'}`

Any help here would be greatly appreciated.

Thanks!

**Comment by naver-searchad** [comment]
Hello, this is Naver SearchAd API.

In order to get ' summary stats' on your response data,
you should add 'timeIncrement' parameter with value of 'allDays'
You can see those description on API document ('timeIncrement' parameter)
