### ISSUE TITLE
campaign, group, channel type 별 매칭 가능 조합이 궁금합니다.

### ISSUE THREAD

**Issue by lachelngose** [naver/searchad-apidoc#276]
캠페인 타입 별로 가질 수 있는 그룹 타입의 조합과 캠페인/그룹 타입 별로 가질 수 있는 채널 타입의 조합을 알고싶은데, 찾지 못해서 질문합니다.

**Comment by naver-searchad** [comment]
@lachelngose 
안녕하세요? 네이버 검색광고 API입니다.

캠페인 유형별 등록가능 그룹 유형 및 채널 유형에 대한 설명은 [FAQ](https://github.com/naver/searchad-apidoc/wiki/FAQ#q-캠페인-유형별-등록가능한-그룹-유형은-어떻게-되나요)에서 확인 가능합니다.

감사합니다.
