### ISSUE TITLE
특정날짜(7일이내)의 summaryStat response 문의

### ISSUE THREAD

**Issue by githubcnsbs** [naver/searchad-apidoc#277]
java sample 을 이용하여 오늘(today) data 어제(yesterday) data의 summaryStat을 가져오는 것은 Stat.DatePreset을 이용하여 확인하였습니다.
 그런데, 특정 날짜(7일 이내)의 data를 요청할 시에 cycleBaseTm과 compTm의 값이 요청한 날과 다른 날(어제날짜)로 값이 들어오고 있습니다.

1. 해당 내용이 버그인지 문의
 1-1. 버그라면 들어오는 data는 요청한 날짜의 data가 맞는지 문의
 1-2. 버그가 아니라면 summaryStat의 날짜별 요청은 today/yesterday 만 가능한지 문의

드립니다.

* 참고: 특정 날짜 summaryStat 요청 code
`
Stat.TimeRange timeRange_custom = new Stat.TimeRange("2019-09-22", "2019-09-22");
Stats.getSummaryStatById(rest, customerId, keywordId, hh24fields, timeRange_custom, null, Breakdown.hh24);
`

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

cycleBaseTm과 compTm은 timeRange에 따라 바뀌는 값이 아니라,
현재 Stat api의 기준일이 언제고 작업이 언제 완료된 상태인지 알려주는 값입니다.
가령 금일(24일) Stat 작업이 완료되었는지 확인하기 위한 용도 등으로 사용하실 수 있습니다.
즉 24일 Stat api를 사용했는데 cycleBaseTm이 23일이 아닌 여전히 22일로 리턴되고 있다면
24일 Stat 작업이 완료되지 않아 전일 Stat을 아직은 조회할 수 없다는 의미로 이해하시면 됩니다.

cycleBaseTm은  Stat 최종 기준일이므로 보통은 어제 날짜까지만 리턴되며
compTm은 실제 작업이 완료된 시간이므로 당일 특정 시간(주로 새벽 시간대)까지 리턴됩니다.

**Comment by githubcnsbs** [comment]
그럼, return되는 data는 제가 요청한 날짜의 data가 return되었다고 생각하면 되는건가요.

즉, 위의 문의에서,
`
Stat.TimeRange timeRange_custom = new Stat.TimeRange("2019-09-22", "2019-09-22");
`
 code로 요청하였으므로, return되는 hourly data는 22일 00시 ~ 22일 23:59:59까지의 data가 (금일이 24일이므로) hourly로 모두 묶여 collecting되었다고 생각하면 되는 걸까요

**Comment by naver-searchad** [comment]
@githubcnsbs 
네 맞습니다.

**Comment by githubcnsbs** [comment]
감사합니다.
