### ISSUE TITLE
Master Report media details 매체코드 , 그룹 아이디 겹침

### ISSUE THREAD

**Issue by SM10855** [naver/searchad-apidoc#278]
마스터리포트에서 media api 호출시 내려받는 데이터 관련된 문의사항입니다.

media  type 그룹엔 4는 밴드페이지, 5는 포스트

미디어  값(ID)이 밴드와(4) 포스트(5) 겹치는 데이터가 내려오는거 같습니다.

http://blog.naver.com/qaad090
https://blog.naver.com/bartsdeving

정상인건지 확인 부탁드립니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

media id와 media group id는 별개의 데이터입니다.
media group id 4는 밴드페이지
media id 4는 http://blog.naver.com/qaad090
라고 보시면 됩니다.

**Comment by SM10855** [comment]
답변 감사합니다.
