### ISSUE TITLE
부여되는 Id들의 Unique 범위문의

### ISSUE THREAD

**Issue by githubcnsbs** [naver/searchad-apidoc#279]
https://naver.github.io/searchad-apidoc/ 에 보면, customerId, nccCampaignId, nccAdgroupId, nccKeywordId, nccAdId등에 ID들이 부여되고 있습니다.

 Document에는 아래와 같은 형태로 설명되고 있는데, 각 ID들의 Unique 범위에대해 문의 드립니다.
- customerId: The unique ID of the customer
- nccCampaignId: The unique ID of the campaign
- nccAdgroupId: The unique ID of this Ad Group
- nccKeywordId: The unique Id of the keyword
- nccAdId: The id of this ad

 예를 들어, nccKeywordId라는 것은 customerId/nccCampaignId/nccAdgroupId 내에서 Unique한 것인지, 아니면 naver ads내 모든 customer와 모든 Campaign/모든 Adgroup 사이에서도 nccKeywordId는 중복이 되지 않는 것인지 문의 드립니다.

 특정 범위 내에서 Unique한 것이라면, 어떤 범위인지 알려주시면 감사하겠습니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

실제 데이터를 한번 확인해 보시면 쉽게 아실 수 있는 내용입니다.

캠페인/광고그룹/키워드/소재/확장소재 등은 모두 각각의 고유한 prefix와 함께 sequence가 붙기 때문에 검색광고 데이터 전체에서 unique가 보장됩니다.
단 customerId는 단순히 sequence number이기 때문에 검색광고 전체에서 unique하지는 않습니다.
sequence number로 id를 가지는 다른 데이터들도 존재하기 때문입니다.
다만 광고관리 API를 이용하시는 측면에서만 보자면 (즉 문의하신 범위 안에서만 보자면)
number만으로 id를 가지는 데이터가 Customer 뿐이므로
역시 전체 범위에서 unique하게 생각하셔도 될 것 같습니다.

**Comment by githubcnsbs** [comment]
네, 그럼, 말씀하신대로 전체 범위에서 unique라고 이해하면 될 것 같습니다. 감사합니다.

그런데, 답변 내용 중 궁금증이 있는데요. 
저는 실제 데이터를 봐도 Unique성을 쉽게 알기는 어려운데 제가 놓치는 부분이 있는지 궁금합니다.
실제 Data 예시)
 . Campaign: cmp-a001-01-00000000xxxxxxx
 . AdGroup: grp-a001-01-00000000xxxxxxx
 . Keyword: nkw-a001-01-00000xxxxxxxxxx

 Keyword ID라는 것에 초점을 맞춰보면, KeywordID라는 것은 AdGroup이 만들어져야하고 Adgroup이 만들어지기 위해서는 Campaign이 있어야되는데, 위 ID 정보에서 제가 알 수 있는 부분은 
 . prefix로 종류가 구분된다. 
 . 중간에 a001-01이라는 특이한 규칙이 있다.
 . 뒤쪽에 많은 수의 data를 가져갈 수 있도록 공간을 확보했다
정도만 파악이 되는데, 저 규칙으로 특정 AdGroup내에서만 Unique한 Keyword ID 혹은 특정 Customer내에서만 Unique한 ID가 아니라 전체 System내에서 Unique성이 보장되는 ID라는 것을 파악할 수 있나요

**Comment by naver-searchad** [comment]
'파악'하신다는 관점이 어떤 것인지 이해가 가지 않습니다만,
쉽게 말해 데이터베이스 테이블로 설명드리자면
Keyword table의 pk는 nccKeywordId 단독 필드입니다.

**Comment by githubcnsbs** [comment]
> 실제 데이터를 한번 확인해 보시면 쉽게 아실 수 있는 내용입니다.

쉽게 어떻게 알 수 있는지, 제가 혹시 문서에서 못 보고 놓친 규칙이 있는지 여쭤본 것 입니다.
시스템내 모든 keyword를 다루는 table의 pk로 이해하겠습니다.

감사합니다.
