### ISSUE TITLE
campaign api  관련 질문입니다.

### ISSUE THREAD

**Issue by younseunghyun** [naver/searchad-apidoc#28]
안녕하세요

campaign api에 create이 추가 되었는데, update는 가능한 field가 문서상으로 userLock밖에 지원 안하는 것으로 보입니다.

campaign의 다른 field에 대해서는 update기능을 지원할 예정이 없는지 궁금합니다.

감사합니다

**Comment by naver-searchad** [comment]
답변이 늦어 죄송합니다.

userLock 뿐만 아니라, budget, period 값을 변경할수 있습니다.  위 3개를 제외하고  특정항목만을 선택하여 수정하는것은 없습니다.

사용하는 방법은 아래처럼 호출하시돼 request body로 campaign json을 넘겨주시면 됩니다. 

1. userLock 수정
PUT /campaigns/{campaignId}?fields=userLock 
{ 
"nccCampaignId":"xxxxxx", 
"customerId": xxxx, 
"userLock":true 
} 

2. budget 수정
PUT /campaigns/{campaignId}?fields=budget 
{ 
"nccCampaignId":"xxxxxx", 
"customerId": xxxx, 
"useDailyBudget":true, 
"dailyBudget": 100000 
} 

3. period 수정
PUT /campaigns/{campaignId}?fields=period 
{ 
"nccCampaignId":"xxxxxx", 
"customerId": xxxx, 
"usePeriod":true, 
"periodStartDt":"2016-08-29T15:00:00.000Z", 
"periodEndDt":"2016-08-31T15:00:00.000Z" 
}

**Comment by younseunghyun** [comment]
답변 감사합니다 👍

**Comment by younseunghyun** [comment]
추가 질문이 있어서 이슈를 재오픈 하였습니다. 답변에서 말씀 해주신 아래의 설명에 대해서 추가 적으로 궁금한 부분이 있습니다.
 `위 3개를 제외하고 특정항목만을 선택하여 수정하는것은 없습니다.`
이 말은 3개의 필드를 제외 하곤 업데이트가 불가능 하다는 것인지, 아니면 3개의 필드만 개별적으로 업데이트가 가능하고, 나머진 업데이트 할려면 전체를 업데이트하는 방식(field에 업데이트 할 필드를 명시 하지 않고, 전체의 campaign object를 넘김)를 사용해야 한다는 의미인지 궁금합니다.

감사합니다.

**Comment by naver-searchad** [comment]
후자가 맞습니다.  다른 항목도 수정이 가능하지만,  그럴땐  campaign 정보 전체를 업데이트 하는 방식으로 해야된다는 의미입니다.  
예를들어  아래 처럼 호출하면 되겠습니다

PUT /campaigns/{campaignId}
{
  "nccCampaignId":"xxx",
  "customerId": xx,
  "name":"xxx",
  "userLock":true,
  "campaignTp":"WEB_SITE",
  "deliveryMethod":"STANDARD",
   "trackingMode":"TRACKING_DISABLED",
   "usePeriod":false,
    "dailyBudget": xxx,
    "useDailyBudget":true
}

**Comment by younseunghyun** [comment]
빠른 답변 감사합니다 :)
