### ISSUE TITLE
제공되는 항목 및 설명

### ISSUE THREAD

**Issue by casis1004** [naver/searchad-apidoc#280]
http://naver.github.io/searchad-apidoc/#/tags/Stat

해당 URL 좌측의 메뉴에서 해당 항목들이 어떤 내용을 제공하고
어떤 항목을 제공하는지 한글 문서로 된게 있을까요?

어떤 데이터들이 어떤 형태로 제공이 되어서,
필요한 데이터가 어떤건지 확인해서 필요한 데이터만 받아보려고 합니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고  API입니다.

현재 한글문서를 별도로 제공하고 있지는 않습니다.
난해하거나 특수한 단어들을 사용하고 있지 않으므로 광고관리 내용들과 매칭하시기에 어렵지 않으리라 생각됩니다.
다만 StatReport 관련한 내용들은 다소 혼동의 여지가 있어 별도
명세표를 제공하고 있으니 참조하실 수 있습니다.
아래 도움말 내 링크를 통해 다운로드 받아 보실 수 있습니다.
https://saedu.naver.com/help/faq/ncc/view.nhn?faqSeq=178
