### ISSUE TITLE
/keywordstool 을 이용해 얻은 데이터와 searchad 에서 제공하는 검색수가 차이나는 점 문의

### ISSUE THREAD

**Issue by creasor** [naver/searchad-apidoc#281]
안녕하세요
제공하시는 PHP 샘플을 이용하여 아래와 같이 구성하였습니다.

`<?php
$hintKeywords = "모니터,듀얼모니터";
$param = array (
'format' => 'json',
'hintKeywords' => $hintKeywords,
'includeHintKeywords' => 0,
'siteId' => '',
'biztpId' => '',
'month' => '',
'event' => '',
'showDetail' => 1,
'keyword' => ''
);
$tmp_list = $api->GET('/keywordstool', $param);
debug($tmp_list, $DEBUG);
print_r($tmp_list);
?>`

위 소스를 실행하면 아래와 같은 형태로 리턴이 오는것을 확인 했습니다.

[0] => Array
  | (
  | [relKeyword] => 모니터
  | [monthlyPcQcCnt] => 44400
  | [monthlyMobileQcCnt] => 82100
  | [monthlyAvePcClkCnt] => 144.5
  | [monthlyAveMobileClkCnt] => 114
  | [monthlyAvePcCtr] => 0.38
  | [monthlyAveMobileCtr] => 0.15
  | [plAvgDepth] => 15
  | [compIdx] => 높음
  | )
  |  

보시면 모니터에 대한 월간검색수가 44400 | 82100 으로 각각 찍히고있습니다.
네이버 광고의 도구->키워드도구 에서도 검색했을때 동일한 값이 보이는것을 확인 후
키워드인 "모니터" 를 클릭해 봤습니다.

의문점은 이때 발생했는데요
각 키워드를 클릭했을때 뜨는 "월별 검색수 추이 (최근 1년)" 항목의 
2019-08 의 그래프는 33,700 | 76,800 을 보여주고 있습니다.

질문 1)
/keywordstool API 나 네이버 광고의 도구->키워드도구 가 제공하는 값과
검색후 각 키워드를 클릭했을때 나오는 그래프에 찍히는 값이 서로 틀린 이유는 무엇인가요?

질문 2)
저희는 그래프에 찍히는 값이 더 신뢰도가 있다고 생각되어 그 데이터를 보고 싶은데
방법이 있을까요?

위 두가지 사항 확인 부탁드립니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

'월간검색수'의 툴팁을 확인해 보시면 '최근 한달간'의 검색수임을 보실 수 있는데
이는 '전월'이 아니라 과거 30일간을 의미하기 때문에
8월 데이터와는 다른 게 맞습니다.

그리고 월별 검색수 추이는 저희 운영 정책상 API로는 제공되지 않는 점 양해 부탁드립니다.
