### ISSUE TITLE
네이버 api 질문있습니다.

### ISSUE THREAD

**Issue by hangari123** [naver/searchad-apidoc#282]
웹문서 영역에서 최신순으로 정렬하려면 파라미터로 뭘 보내야 하나요? 문서에 나온건 3가지 밖에 없어서요.. 답변좀 부탁드릴게요.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

질문하신 내용이 너무 모호해서 정확히 이해되지 않습니다.
('웹문서 영역', '문서에 나온 3가지' 등)
좀 더 상세하게 알려 주시면 확인해 드리도록 하겠습니다.

**Comment by hangari123** [comment]
> 안녕하세요, 네이버 검색광고 API입니다.
> 
> 질문하신 내용이 너무 모호해서 정확히 이해되지 않습니다.
> ('웹문서 영역', '문서에 나온 3가지' 등)
> 좀 더 상세하게 알려 주시면 확인해 드리도록 하겠습니다.

![image](https://user-images.githubusercontent.com/54837386/66033166-b1322800-e541-11e9-9732-15ab2e6cdb75.png)

네이버 api를 이용해 웹문서를 검색하려고 하는데 검색하는 것까지는 됐는데 정확도가 디폴트값으로 되어 있어서요.. 이걸 최신순으로 정렬해서 보고 싶습니다.. 그래서 그러려면 파라미터 값으로 최신순으로 정렬하라고 값을 보내야 할 것 같은데.. 안나와있어서 질문을 드리게 됐습니다.

**Comment by naver-searchad** [comment]
@hangari123 
본 지면은 '네이버 검색광고' API를 사용하는 광고주들을 위한 repository입니다.
네이버 서비스(검색 포함) 관련 API문의는 https://developers.naver.com/main/ 을 이용해 주시면 되겠습니다.
