### ISSUE TITLE
Prohibited keywords 오류 문의

### ISSUE THREAD

**Issue by angalle** [naver/searchad-apidoc#283]
3909 | 광고노출이 금지된 키워드 입니다. | Prohibited keywords

해당 오류는 네이버에서 금지시킨 키워드인가요 ?

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

네 설명 그대로입니다.

**Comment by angalle** [comment]
해당 키워드는 공개되어있나요 ?

**Comment by naver-searchad** [comment]
검색광고 API 이슈 상에서 말씀드리기는 어려운 주제인 것 같습니다.
다만 추측해 보자면,
판매금지 키워드를 운영하는 일에는 여러가지 이슈들이 있을 수 있어
아마도 공개되어 있지는 않을 것으로 생각됩니다.

**Comment by naver-searchad** [comment]
참고로,
검색광고 운영정책 등의 문의는 고객센터 (온라인 고객센타 https://saedu.naver.com/help/inquiry/index.nhn, 혹은 고객지원 문의 전화 1588.5896 유료 080.500.5896 (유선)무료)로 문의하시는 방법이 있습니다.
