### ISSUE TITLE
에러 확인 부탁드립니다.

### ISSUE THREAD

**Issue by SteveKim7878** [naver/searchad-apidoc#284]
X-Transaction-ID:BDMKPKI1HHGN5
X-Transaction-ID:BDMKPTI39HI67
X-Transaction-ID:BDMKQKGNPDIV7
X-Transaction-ID:BDMKQRJK1DHHC
이며 위의 Transaction 코드 외에도 훨씬 많이 있지만 모두 Too many request에 대한 에러이긴 한데 유독 해당 계정에서만 동일한 에러가 많이 발생을 합니다.
혹시 권한을 위임받은 계정들이 여러개이고 서로 다르게 위임받은 계정을 통해 동시에 많은 양의 request가 발생을 하면 위와 같은 에러가 나오는지 궁금합니다.
Too many request의 기준이 customerId로 알고 있는데 이것이 권한을 위임받은 customerId인지 실 광고주의 customerId인지도 확인 부탁드리겠습니다.
다른 계정에선 그렇지 않은데 해당 계정만 워낙 많이 발생을 해서 정확한 원인을 알고 싶습니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

알고 계신 내용이 모두 맞습니다.
request 처리 기준이 광고주 단위이며
해당 광고주 분의 유효 manager 권한 계정을 세어 보니 스무개가 넘습니다.
동시에 여러 manager로부터 request가 몰린다면 충분히 벌어질 수 있는 상황입니다.
