### ISSUE TITLE
"연관키워드 조회 결과" 정보도 얻어올 수 있는지요? 

### ISSUE THREAD

**Issue by kakpple** [naver/searchad-apidoc#286]
안녕하세요, 네이버 검색 API 관련 질문 드립니다. 

키워드 검색 API를 통하여 키워드 뿐만아니라  "연관키워드 조회 결과" 정보도 얻어올 수 있는지요? "연관키워드 조회 결과"를 얻을 수 없다면 엑셀결과를 다운로드 할 수 있는 API는 있는지요? 

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

연관키워드 검색은 다음의 API 문서를 참조하시면 됩니다.
http://naver.github.io/searchad-apidoc/#/tags/RelKwdStat

엑셀 다운로드는 키워드도구 ui상의 기능이므로 별도 API로는 지원되지 않습니다.

**Comment by kakpple** [comment]
신속한 답변 감사합니다. ^^ 
키워드 도구에서 보여주는 모든 연관키워드의 모비일/PC 조회수, 전환율 등 정보도 같이 받아 볼수 있는지요?

**Comment by naver-searchad** [comment]
네 맞습니다.
키워드도구 조회 결과 테이블 데이터들은 모두 포함됩니다.
단 키워드를 클릭했을 때 보여주는 별도 별 월별지표나 사용자별 지표는 지원되지 않습니다.

**Comment by kakpple** [comment]
넵, 감사합니다. ^^
