### ISSUE TITLE
Estimate(exposure minimum bid)의 Period 관련 문의드립니다.

### ISSUE THREAD

**Issue by Daniel-Dobal-Oh** [naver/searchad-apidoc#287]
안녕하세요.

"exposure minimum bid"의 period 파라메터 의미가 아래와 같을런지요?

1. month : 직전 일요일부터 28일(4주)간 데이터 통계를 기반하여 예측.
2. day : 어제 통계를 기반한 예측.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

API 문서의 설명대로 생각하시면 되겠습니다.
`Choose whether to use the stats of yesterday or last 28 days`
'DAY'는 어제, 'MONTH'는 어제까지의 과거 28일간을 의미합니다.

**Comment by Daniel-Dobal-Oh** [comment]
답변 고맙습니다.
