### ISSUE TITLE
2019:10:17 03시경  API Status 관련 문의드립니다.

### ISSUE THREAD

**Issue by riemannulus** [naver/searchad-apidoc#289]
안녕하세요.

2019:10:17 03시경 네이버 SA API에 요청을 했을 때 503 에러가 발생함을 확인하였습니다.
혹시 03시경부터 06시경까지 API status에 상태 변동이 있었는지 문의드립니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요?
네이버 검색광고 API 입니다.

2019년 10월 17일 03시 부터 07시까지 네이버 검색광고 정기점검이 진해 되었습니다.
https://saedu.naver.com/notice/view.nhn?notiSeq=3555&catg=&fixYn=N&searchOpt=all&keyword=

해당 시간에는 API를 사용할 수 없었습니다.

감사합니다.

**Comment by riemannulus** [comment]
안녕하세요.

빠른 답변 감사합니다.

이슈 닫도록 하겠습니다.
