### ISSUE TITLE
campaign delete api 지원관련 문의입니다.

### ISSUE THREAD

**Issue by younseunghyun** [naver/searchad-apidoc#29]
안녕하세요 현재 문서상으로는 campaign에 대해서 delete를 지원하지 않는 것으로 보입니다.

campaign에 대해서 delete를 지원 하실 계획은 없으신지 궁금합니다.

감사합니다.

**Comment by naver-searchad** [comment]
오픈초기에는 정책상  공개를 하지 않았으나,  현재 기준으로 내부 검토 결과  지원 준비할 예정에 있습니다.
다만 api 사용 권한부여등의 절차 등이 남아 있어  다음 배포때 적용 될 예정입니다
오픈되면 따로 api 공지 드리겠습니다

**Comment by younseunghyun** [comment]
빠른 답변 감사합니다 👍
