### ISSUE TITLE
Keyword별 hourly Report에 Sales by conversion 확인 가능한 API 문의

### ISSUE THREAD

**Issue by githubcnsbs** [naver/searchad-apidoc#290]
Keyword별 hourly data로 Sales by conversion 확인이 가능한 API가 있는지 문의 드립니다.
 Stat API(https://naver.github.io/searchad-apidoc/#/tags/Stat)에서 찾아보았으나 찾기가 어려워 문의드립니다.

 Master Report/Stat Report와 같이 download형 API에는 있는 것으로 보이나, json으로 response해주는 API 중 가능한 API가 있는지 문의 드립니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버검색광고 API입니다.

https://naver.github.io/searchad-apidoc/#/operations/GET/~2Fstats%7B%3Fid,fields,timeRange,datePreset,timeIncrement,breakdown%7D

위 문서의 breakdown 항목을 참고하시면 됩니다.
파라미터에 'breakdown=hh24&timeIncrement=allDays' 로 요청하시면
시간대별 상세데이터를 확인하실 수 있습니다.
단 상세데이터 조회시에는 timeRange 를 오늘 또는 지난1주간의 기간만 요청 가능합니다.
datePreset으로는 today, yesterday, last7days 정도만 유효합니다.

**Comment by githubcnsbs** [comment]
답변 감사드립니다. 저는 Java Sample을 참고하고 있으며, 
 (StatSample.java)[https://github.com/naver/searchad-apidoc/blob/master/java-sample/src/main/java/com/naver/searchad/api/sample/StatSample.java]에 보면 50라인부터 아래와 같은 comment가 있습니다.
`
			/*
			 * Retrieving detail data
			 * 
			 * You can receive detail data with breakdown parameter.
			 * However, with breakdown parameter, you can retrieve data within maximum last 7 days only.
			 * And breakdown is applied to timeIncrement(allDays), not timeIncrement(1).
			 * 
			 * - breakdown(pcMblTp, dayw, hh24, regnNo) Usage
			 * [Possible combinations of breakdown and field parameter]
			 * 
			 * [breakdown=pcMblTp] impCnt, clkCnt, ctr, cpc, salesAmt, avgRnk, ccnt, recentAvgRnk, recentAvgCpc (recentAvgRnk, recentAvgCpc are applied to ad, keyword entity only) 
			 * [breakdown=hh24] impCnt, clkCnt, ctr, cpc, salesAmt, avgRnk, ccnt
			 * [breakdown=regnNo] impCnt, clkCnt, ctr, cpc, salesAmt, avgRnk, ccnt
			 * [breakdown=dayw] impCnt, clkCnt, ctr, cpc, salesAmt, avgRnk, ccnt
			 * 
			 */
`

 여기에 보면 hourly로 부르기위한 valid field는 다음과 같다고 표기되는데,
`			 * [breakdown=hh24] impCnt, clkCnt, ctr, cpc, salesAmt, avgRnk, ccnt`

답변의 내용으로보아 다른 field가 더 있는 것으로 보입니다.
 hourly data의 valid field를 알 수 있는 문서나 code가 있으면 공유 부탁드립니다.

**Comment by naver-searchad** [comment]
위에 드린 링크에 보면 stat api로 조회 가능한 valid fields 목록이 함께 나와 있습니다.
The type of the fields. Valid items are:

impCnt
clkCnt
salesAmt
ctr
cpc
avgRnk
ccnt
recentAvgRnk
recentAvgCpc
pcNxAvgRnk
mblNxAvgRnk
crto
convAmt
ror
cpConv
viewCnt

**Comment by githubcnsbs** [comment]
아.. 네, 그럼 comment처럼 breakdown의 option에 따라 valid field가 변경되지 않고, breakdown=hh24일때도 나열된 field가 모두 valid하다고 이해하면 될까요

**Comment by githubcnsbs** [comment]
`* [breakdown=hh24] impCnt, clkCnt, ctr, cpc, salesAmt, avgRnk, ccnt`
에 'convAmt'만 추가하여 호출 결과
```

{
   "data": [
      {
         "ctr": 0.75,
         "convAmt": 0,
         "clkCnt": 1,
         "cpc": 3487,
         "breakdowns": [
            {
               "ctr": 0,
               "clkCnt": 0,
               "cpc": 0,
               "name": "10시~11시",
               "ccnt": 0,
               "avgRnk": 1.1,
               "impCnt": 23,
               "salesAmt": 0
            },
```
와 같이 hourly data에 convAmt가 나오는 것이 아닌, summary에 convAmt가 나오고 있습니다. 
hourly data에 convAmt가 나오는 방법 혹은 다른 API를 통해서라도 받아올 수 있는지 문의 드립니다.

**Comment by naver-searchad** [comment]
추가확인이 필요해 답변이 늦어졌습니다.

breakdown 항목별로 아래와 같이 지원 field 범위가 다를 수 있습니다.

dayw : 모두제공
pcMblTp : 모두제공
hh24 : 제외항목 ('cpConv', 'ror', 'convAmt', 'recentAvgCpc', 'recentAvgRnk')
regnNo : 제외항목('cpConv', 'ror', 'convAmt', 'recentAvgCpc', 'recentAvgRnk')

**Comment by githubcnsbs** [comment]
네, 답변 감사합니다.
그럼, 현재로서는 hourly convAmt를 json response로 제공하는 API는 없다고 이해하면 될까요

**Comment by naver-searchad** [comment]
네 맞습니다

**Comment by githubcnsbs** [comment]
네, 감사합니다.
