### ISSUE TITLE
/keywordstool 에 관한 자바코드의 예제가 실행되지 않습니다.

### ISSUE THREAD

**Issue by cruisepunch** [naver/searchad-apidoc#292]
git 와 메뉴얼을 통해 파일을 다운 받고 프로젝트를 열어보니
정상적인 컴파일이 이루어지지 않아,

/keywordstool 부분만을 찾아보려고 했지만,
코드에서는 따로 언급이 되지 않은 것인지, 찾기가 어려워 질문 올려봅니다.

자바코드에서 /keywordstool 부분을 보려면 어떤부분을 확인하면 될런지요.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

제공되는 샘플은 API 요청시 필요한 secretKey 사용 등 기본적인 프로세스를 참조하시라는 의미로 만들어진 것입니다.
따라서 API DOC 중 일부 요청에 대한  샘플만 제공되며
샘플에 없는 API 유형의 경우 문서 상의 url, paramter, method 등을 참조하셔서 만들어 주시면 됩니다.

그리고 /keywordstool 이라는 path는 광고관리 웹 상의 경로인데
아마 API로는 아래 링크를 얘기하시는 것 같습니다.
http://naver.github.io/searchad-apidoc/#/tags/RelKwdStat
