### ISSUE TITLE
keywordstool 결과값이 너무 많이 리턴됩니다.

### ISSUE THREAD

**Issue by zaxguy** [naver/searchad-apidoc#293]
안녕하세요. php로 코딩중인데요. 결과값이 잘 나오는데.. 문제가 너무많이 나와서 그러는데요. 검색한 결과 말고도 연관 검색어 결과치까지 대량으로 리턴되서 페이지가 다운되는데요. 혹시 검색한 결과만 나오도록 제한하거나 리턴받을 결과 갯수를 지정하는 파라메터가 있을까요?

$data = array (
"hintKeywords" =>"떡볶이",
"includeHintKeywords" => 1,
"showDetail" => 1
);

$response = $api->GET('/keywordstool', $data);

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

연관키워드 API 결과는 따로 제한 파라미터가 없습니다.
다만 최대 결과라고 해도 1000건이 조금 넘는 수준이라서 네트워크가 다운될 수준은 아닙니다.
아마 페이지가 다운된다고 하신 건 웹 상에서 구현하시면서 나타나는 증상인 거로 보이는데요
리턴 결과를 바로 사용하지 마시고 원하시는 최대건수에 맞춰 잘라내신 후 사용하시면 될 것 같습니다.

**Comment by zaxguy** [comment]
네 답변 감사합니다.
