### ISSUE TITLE
MasterReport Campaign 마지막 컬럼

### ISSUE THREAD

**Issue by nanpuhaha** [naver/searchad-apidoc#294]
안녕하세요.

Campaign MasterReport를 받아보고 뭔가 이상하여 살펴본 결과, 웹에서 **광고 정보 일괄 다운로드**로 받은 MasterReport.tsv보다 API downloadUrl을 통해 다운받은 MasterReport.tsv가 Column이 1개 더 많습니다.

#### 광고 정보 일괄 다운로드
| Customer ID | Campaign ID | Campaign Name | Campaign Type | Delivery Method | Using Period | Period Start Date | Period End Date | regTm | delTm |
|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|
| - | cmp-a001-01-000000000904993 | - | 1 | 1 | 0 |  |  | 0000-00-00T00:00:00Z |  |
| - | cmp-a001-04-000000001019531 | - | 4 | 1 | 0 |  |  | 0000-00-00T00:00:00Z |  |

#### API downloadUrl
| Customer ID | Campaign ID | Campaign Name | Campaign Type | Delivery Method | Using Period | Period Start Date | Period End Date | regTm | delTm | `???` |
|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|
| - | cmp-a001-01-000000000904993 | - | 1 | 1 | 0 |  |  | 0000-00-00T00:00:00Z |  | `0` |
| - | cmp-a001-04-000000001019531 | - | 4 | 1 | 0 |  |  | 0000-00-00T00:00:00Z |  | `1` |

[MasterReport Overview (searchad-apidoc)](http://naver.github.io/searchad-apidoc/#/tags/MasterReport)에서도 delTm 이후의 컬럼 정보가 없고,
[master-reports-spec.md (Gist)](https://gist.github.com/naver-searchad/186ca42e1e8596b0e3dcf74e3a86c04f)에서도 delTm 이후의 컬럼 정보가 없습니다.

apidoc과 gist 모두 MasterReport Spec을 다시 업데이트해주시기 바랍니다.

---

추가로, MasterReport와 StatReport Column 정보도 같이 API로 제공해주시길 요청드립니다.
Content에 값만 넘어오니, 무슨 값인지 알려면 별도로 apidoc과 gist에 올려주신 내용을 바탕으로 매핑을 해야되는데, apidoc과 gist가 업데이트가 되지 않으면 매핑에 오류가 생깁니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

확인 결과 내부적으로 사용하는 API는 동일하기 때문에 결과에 차이가 나지는 않습니다.
다만 해당 필드가 2018년 하반에 추가되었으므로 그 전에 안녕하세요, 네이버 검색광고 API입니다.

확인 결과 내부적으로 사용하는 API는 동일하기 때문에 결과에 차이가 나지는 않습니다.
다만 해당 필드가 2018년 하반에 추가되었으므로 그 전에 생성된 결과와는 현재 차이가 날 수는 있겠습니다.

해당 문서들은 바로 업데이트 요청이 들어가서 수정된 것으로 확인이 되었으며
추가로 의견주신 내용은 현업 부서에서 고려해 볼 수 있도록 전달해 드리도록 하겠습니다.

감사합니다.
