### ISSUE TITLE
[RelKwdStat] Signature 생성 부분을 샘플코드 그대로 썼는데, 403 : Invalid Signature 발생합니다.

### ISSUE THREAD

**Issue by javabt01** [naver/searchad-apidoc#295]
package keyword.main;

import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;

public class KeywordProc {

	
	public void request(){
		
		String customerId = "MyCustomerId ";
		String apiKey = "MyApiKey";//애플리케이션 클라이언트 아이디 값";
        String clientSecret = "MySecretKey";//애플리케이션 클라이언트 시크릿 값";

        try {
        	
        	String baseUrl = "https://api.naver.com";
            String path = "/keywordstool";
            String sTime = String.valueOf(System.currentTimeMillis());
            
            //네이버 샘플 Signatures
            String sginature = Signatures.of(sTime, "GET", path, clientSecret);
            
            URL url = new URL(baseUrl+path);
            HttpURLConnection con = (HttpURLConnection)url.openConnection();
            
            con.setRequestMethod("GET");
            con.setRequestProperty("X-Timestamp", sTime);
            con.setRequestProperty("X-API-KEY", apiKey);
            con.setRequestProperty("X-Customer", customerId);
            con.setRequestProperty("X-Signature", sginature);

            con.setDoOutput(true);
            DataOutputStream wr = new DataOutputStream(con.getOutputStream());
            wr.writeBytes("test");
            wr.flush();
            wr.close();

            int responseCode = con.getResponseCode();
            BufferedReader br;
            System.out.println("responseCode : "+responseCode);
            if(responseCode==200) { // 정상 호출
                br = new BufferedReader(new InputStreamReader(con.getInputStream(), "UTF-8"));
            } else {  // 에러 발생
                br = new BufferedReader(new InputStreamReader(con.getErrorStream(), "UTF-8"));
            }

            String inputLine;
            StringBuffer response = new StringBuffer();
            while ((inputLine = br.readLine()) != null) {
                response.append(inputLine);
            }
            br.close();
            System.out.println(response.toString());

        } catch (Exception e) {
            System.out.println(e);
        }
		
	}
	
}
------------------------------------------------------------------------------------
[결과]
responseCode : 403
{"signature":"/Ir2cRpQ5NyIf9d5F4g5/YfOx0zFW6JXX95/EXD71Jc=","status":403,"detail":"Signature '/Ir2cRpQ5NyIf9d5F4g5/YfOx0zFW6JXX95/EXD71Jc=' is invalid.","title":"Invalid Signature","type":"urn:naver:api:problem:invalid-signature"}

------------------------------------------------------------------------------------

어떤것이 잘못 된 걸까요?
답변 좀 부탁드리겠습니다. ㅠ

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

서명은 `GET`으로 생성하였으나, 요청은 `POST`로 하셨습니다.

감사합니다.
