### ISSUE TITLE
stat에서 id문의

### ISSUE THREAD

**Issue by casis1004** [naver/searchad-apidoc#296]
http://naver.github.io/searchad-apidoc/#/operations/GET/~2Fstats%7B%3Fid,statType%7D

Stat: get (by statType)

위의 내용으로 데이터 조회를 하는데,

$stat_req = array(
    "id" => "cmp-m001-01-000000000255304",
    "statType" => "NPLA_SCH_KEYWORD"
);
$response = $api->GET("/stats", $stat_req);

이 경우 [잘못된 파라미터 형식입니다] 오류가 나오는데, 어떤 문제일까요?

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

'NPLA_SCH_KEYWORD' 타입은 쇼핑검색 유형의 키워드 보고서입니다.
요청하신 id 'cmp-m001-01-000000000255304'는 '파워링크' 캠페인인 것으로 보입니다.
