### ISSUE TITLE
keywordstool parameter 문의

### ISSUE THREAD

**Issue by javabt01** [naver/searchad-apidoc#297]
아래와 같이 요청하였습니다.
------------------------------------------------------------------------------
public void request(){
		
		String customerId = "커스텀아이디";
		String apiKey = "API키";//애플리케이션 클라이언트 아이디 값";
        String clientSecret = "시크릿키";//애플리케이션 클라이언트 시크릿 값";

        try {
        	
        	String baseUrl = "https://api.naver.com";
            String path = "/keywordstool";
            String parameter = "siteId=SITE&biztpId=0&hintkeywords=광고,우유,사과&event=1&month=11&showDetail=1";
            parameter = URLEncoder.encode(parameter,"UTF-8");
            
            String sTime = String.valueOf(System.currentTimeMillis());
            
            
            //네이버 샘플 Signatures
            String sginature = Signatures.of(sTime, "GET", path, clientSecret);
            
            URL url = new URL(baseUrl+path+"?"+parameter);
            HttpURLConnection con = (HttpURLConnection)url.openConnection();
            
            con.setRequestMethod("GET");
            con.setRequestProperty("X-Timestamp", sTime);
            con.setRequestProperty("X-API-KEY", apiKey);
            con.setRequestProperty("X-Customer", customerId);
            con.setRequestProperty("X-Signature", sginature);

            con.setDoOutput(true);
            
            int responseCode = con.getResponseCode();
            BufferedReader br;
            System.out.println("responseCode : "+responseCode);
            if(responseCode==200) { // 정상 호출
                br = new BufferedReader(new InputStreamReader(con.getInputStream(), "UTF-8"));
            } else {  // 에러 발생
                br = new BufferedReader(new InputStreamReader(con.getErrorStream(), "UTF-8"));
            }

            String inputLine;
            StringBuffer response = new StringBuffer();
            while ((inputLine = br.readLine()) != null) {
                response.append(inputLine);
            }
            br.close();
            System.out.println(response.toString());

        } catch (Exception e) {
            System.out.println(e);
        }
		
	}

------------------------------------------------------------------------------
[결과]
responseCode : 200
{"keywordList":[{"relKeyword":"디스커버리롱패딩","monthlyPcQcCnt":21700,".........................................................monthlyAveMobileClkCnt":0.7,"monthlyAvePcCtr":0.15,"monthlyAveMobileCtr":0.04,"plAvgDepth":15,"compIdx":"높음"}]}
------------------------------------------------------------------------------

위와 같이 'hintkeywords' 와 상관없이 'biztpId' 파라미메터값에 대한 키워드를 모두 가져옵니다.
제가 파라미터 값을 잘못넣은걸까요?

![image](https://user-images.githubusercontent.com/47851821/67653742-171d9e00-f98e-11e9-85fd-302899b4ec92.png)
제가 파라메터 값의 의미를 정확히 모르겠어서 간단하게라도 설명이나 요청 예제 좀 부탁드리겠습니다.

수고하십시오^^

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

원하시는 결과는 그냥 shoeDetail=1과 hintkeywords=광고,우유,사과 두개만 입력하시면 됩니다.
다른 파라미터들은 광고관리 '키워드도구' 화면의 조회조건에서 사용되는 내용들입니다.

**Comment by javabt01** [comment]
답변감사드립니다^^

말씀하신대로 파라미터를 요청하였으나 아무런 결과를 받지 못 했습니다. 
제가 무엇을 잘못하고있는걸까요 ㅠㅠ
----------------------------------------------------------------------------------
[파라미터]
String parameter = "hintkeywords=과일&showDetail=0";
[결과]
responseCode : 200
{"keywordList":[]}

**Comment by naver-searchad** [comment]
@javabt01 
includeHintKeywords=0 를 하나 더 추가해 봐 주세요

**Comment by javabt01** [comment]
넵!!

[파라미터]
String parameter = "hintkeywords=과일&showDetail=1&includeHintKeywords=0";
[결과]
responseCode : 200
{"keywordList":[]}
----------------------------------------------------------------------

**Comment by naver-searchad** [comment]
@javabt01 
hinkeywords -> hintKeywords 대문자로 바꿔서 해보세요

**Comment by javabt01** [comment]
> @javabt01
> includeHintKeywords=0 를 하나 더 추가해 봐 주세요



> hintKeywords

아,,, 되네요..

이런 간단한걸로 귀찮게 해드려서 죄송합니다.. 
감사합니다..
