### ISSUE TITLE
비즈채널 api중에 create 에 대해서 궁금한게 있습니다.

### ISSUE THREAD

**Issue by ghost242** [naver/searchad-apidoc#298]
페이지에 보면 입력 파라미터에 있는 항목들 중에 이상한게 있는데 여기 들어가는 값이 뭔지 알 수 있을까요?

페이지 위치는 [BusinessChannel/create(http://naver.github.io/searchad-apidoc/#/operations/POST/~2Fncc~2Fchannels)](http://naver.github.io/searchad-apidoc/#/operations/POST/~2Fncc~2Fchannels)입니다.

아래는 어떤 내용인지 알 수 없는 항목입니다. 

Parameter name | Data type | Description
-- | -- | --
nidAut | {{ vm.getType(item, true) }} | nidAut
nidSes | {{ vm.getType(item, true) }} | nidSes
passNaTokenToSa | {{ vm.getType(item, true) }} | passNaTokenToSa

그리고 business info에 들어가는 값을 알 수 있는 문서가 일부 채널 타입에 대해 json으로 작성되있는 md파일만 보이는데 항목이랑 각 항목에 대한 데이터 타입, 어떤 데이터가 들어가는지 알 수 있는 별도 문서가 있나요?

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

광고관리 화면을 통해 비즈채널을 생성해 보시면 아시겠지만
현재 등록 가능한 비즈채널 유형은 상당히 많은 편입니다.
그리고 유형에 따라 ui상에서 필요한 액션들(특히 인증 관련들)을 거쳐야만 하기에
API로 구현하시기에는 다소 어려운 점이 있을 수밖에 없고
API 문서로도 관리하기가 어려운 내용이라고 보시면 되겠습니다.

올려주신 세 파라미터들도 사용자 네이버 쿠키가 필요한 비즈채널 유형에서 사용하는 값들이므로
실제로 optional인데 문서상에는 정확히 표기돼 있지 않고 있네요.
이 부분은 추후 업데이트 되도록 하겠습니다.

감사합니다.

**Comment by ghost242** [comment]
네 감사합니다. 해당 값들을 비우고 SITE 타입을 생성하는건 간단하게 되는걸 확인했습니다.
