### ISSUE TITLE
keyword 생성에 대해서 질문드립니다.

### ISSUE THREAD

**Issue by ghost242** [naver/searchad-apidoc#299]
지금 keyword create api를 이용해서 키워드를 여러개 생성해보고 있는데 아래와 같은 에러가 발생합니다.

`{"title": "Bad Request", "status": 400, "detail": "JSON parse error: Cannot deserialize instance of `java.util.ArrayList` out of START_OBJECT token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.util.ArrayList` out of START_OBJECT token\n at [Source: (PushbackInputStream); line: 1, column: 1]"}`

파이썬의 json 패키지를 이용해서 json 문자열로 변환해도 마찬가지입니다. 어떤 문제인지 혹시 확인 가능할까요?
아래는 제가 요청보낸 json 문자열입니다.

`
{"nccKeywords": [{"keyword": "\ud14c\uc2a4\ud2b8 \ud0a4\uc6cc\ub4dc#10"}, {"keyword": "\ud14c\uc2a4\ud2b8 \ud0a4\uc6cc\ub4dc#11"}, {"keyword": "\ud14c\uc2a4\ud2b8 \ud0a4\uc6cc\ub4dc#12"}, {"keyword": "\ud14c\uc2a4\ud2b8 \ud0a4\uc6cc\ub4dc#13"}, {"keyword": "\ud14c\uc2a4\ud2b8 \ud0a4\uc6cc\ub4dc#14"}]}
`

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

body에 들어갈 내용은 nccKeywords 형태의 list라는 의미이며
'nccKeywords' attribute 라는 의미는 아닙니다.
즉 위 요청 json에서 [...] 사이만 넣으시면 됩니다.

**Comment by ghost242** [comment]
답변 감사합니다.. 말씀해주신대로 해보니까 결과가 잘 돌아옵니다ㅠㅠ
이슈는 이대로 close 하겠습니다.
