### ISSUE TITLE
AdKeyword모델에는 ResultStatus가 내장되어있는데 Adgroup에는 없습니다.

### ISSUE THREAD

**Issue by openmaya** [naver/searchad-apidoc#3]
Client의 로직의 레벨을 맞추는게 좋을것 같은데요. Adgroups를 사용할때 결국 파싱 에러가 나게되서 부정확 한것 같습니다. 일단은 방어로직으로 재파싱해서 사용하는 걸로 처리 하였습니다.

**Comment by naver-searchad** [comment]
AdKeyword는 복수등록 기능이 적용되어 있어 부분성공, 실패에 대한 정보가 필요하여 ResultStatus가 추가된 경우입니다.
하지만  
Adgroups는 단건 등록만 허용이 되기 때문에 Http Response code를 이용하여 처리하시면 됩니다.

**Comment by openmaya** [comment]
답변 감사합니다. 
작성하신 RestClient.asObject에서 이미 Http Response code가 2xx가 아닐때 Exception을 던지도록 작성하셔서 이를 catch하여 처리하도록 작성하였습니다.
