### ISSUE TITLE
api 문의 드립니다.

### ISSUE THREAD

**Issue by handbbang** [naver/searchad-apidoc#30]
$stats = $api->GET ( '/stats', array (
        'id' => 'rtt-a001-000000000053992',
        'fields' => '["impCnt","clkCnt","salesAmt"]',
        'datePreset' => 'last30days',
        'timeIncrement' => '1' 
));

위와같이 호출시 

Array
(
    [code] => 11001
    [message] => 잘못된 파라미터 형식입니다.
)

이런 오류가 나오는데요. 

설명에 맞게끔 하였는데 어떤 문제가 있는걸까요?

**Comment by naver-searchad** [comment]
안녕하세요.
현재 통계지표를 제공하는 ID는 켐페인(cmp-xxxx), 광고그룹(grp-xxxx), 소재(nad-xxxx), 키워드(nkw-xxxx)입니다. 입력하신 `"id"=>"rtt-a001-000000000053992"` id값은 존재하지 않습니다.
올바른 id를 입력하시기 바랍니다.

**Comment by handbbang** [comment]
답변 감사합니다.

그러면 혹시 다차원 보고서는 api 리포트로 출력 할 수 없는건가요 ?

![default](https://cloud.githubusercontent.com/assets/23492999/21795817/f9cc6fea-d747-11e6-87e8-f0e3a96fbec2.png)

답변 부탁드립니다.

**Comment by naver-searchad** [comment]
다차원 보고서에서 사용되는 API는 /stats와 별도의 내부 API를 사용하고 있기 때문에 /stats를 이용하여 다차원 보고서와 동일한 지표를 확인하실수는 없습니다.

대신에, /master-reports, /stat-reports API를 통하여 상세 지표를 직접 가공하여 원하시는 관점의 데이터를 만드실수 있습니다.

http://naver.github.io/searchad-apidoc 의 MasterReport, StatReport 항목을 참고 부탁드립니다.

감사합니다.

**Comment by bluesme519** [comment]
혹시 체류시간, 페이지뷰 를 확인할수 있는 리포트가 있을까요?
