### ISSUE TITLE
MasterReport status

### ISSUE THREAD

**Issue by SM10855** [naver/searchad-apidoc#300]
Job Status 가 아래와 같이 명세서에 명시되어있는데

REGIST
RUNNING
BUILT
NONE
ERROR

혹시 FAIL이라는것도 있나요?

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

FAIL status는 없습니다.
감사합니다.

**Comment by SM10855** [comment]
감사합니다.
