### ISSUE TITLE
keywordstool invalid signature 문의

### ISSUE THREAD

**Issue by ssam1213** [naver/searchad-apidoc#301]
안녕하세요 

아래 코드처럼 Google Apps Script를 이용해서 네이버 연관검색어 조회수를 확인해 보려고하는데요

api_url과 signature uri에 ncc/keywordstool을 붙이면  
{"timestamp":1572845282815,"status":405,"error":"Method Not Allowed","exception":"org.springframework.web.HttpRequestMethodNotSupportedException","message":"Request method 'POST' not supported","path":"/ncc/keywordstool"}

라는 에러가 나고

ncc를 제외한 /keywordstool만 입력하면 403 invalid Signature 에러가 납니다.

hmac을 base64로 인코딩한 값은 https://www.devglan.com/online-tools/hmac-sha256-online에서 

확인한 값과 일치하는데 어떤 값때문에 403 invalid Signature 나는지 궁금합니다.

`function monthlyKwd() {
  var api_key = ""
  var api_secret = ""
  var customer = ""
  var api_url = 'https://api.naver.com/ncc/keywordstool'
  
  var data = {
    'siteId': '',
    'hintKeywords': '화장품추천',
    'showDetail': 1,
    'biztpId': '',
    'month': '',
    'event': '',
    'keyword': '',
  }

  var timestamp = Number(new Date())
  var date = timestamp.toPrecision()
  Logger.log(date)
  var signature = date + "." + "GET" + "." + "/ncc/keywordstool"

  var hash = CryptoJS.HmacSHA256(api_secret, signature);
  Logger.log(hash)
  var hashInBase64 = CryptoJS.enc.Base64.stringify(hash);
    
  Logger.log(hashInBase64)

  var options = {
    'method' : 'get',
    'headers':{ 
      'X-Timestamp': date,
      'X-API-KEY': api_key,
      'X-Customer': customer,
      "X-Signature": hashInBase64
    },
    'contentType': 'application/json',
    'payload' : data,
    'muteHttpExceptions': true
  };
  var req = UrlFetchApp.fetch(api_url, options);
  
  Logger.log(req);
  
 }`

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

일단 `GET /keywordstool` 만을 제공합니다. `POST` 메소드는 지원하지 않으며, `/ncc` 가 붙지 않습니다.
http://naver.github.io/searchad-apidoc/#/tags/RelKwdStat


또한, `CryptoJS.HmacSHA256` input parameter의 순서가 바뀌었습니다.

```javascript
var hash = CryptoJS.HmacSHA256(api_secret, signature);
```

아래 문서를 참고하시기 바랍니다.

https://cryptojs.gitbook.io/docs/#hmac

```javascript
var hash = CryptoJS.HmacSHA256("Message", "Secret Passphrase");
```

질문 시 응답 메시지 HTTP Header `X-Transaction-ID` 값을 같이 남겨주시면 좀 더 자세한 답변이 가능합니다.

**Comment by ssam1213** [comment]
> 안녕하세요, 네이버 검색광고 API입니다.
> 
> 일단 `GET /keywordstool` 만을 제공합니다. `POST` 메소드는 지원하지 않으며, `/ncc` 가 붙지 않습니다.
> http://naver.github.io/searchad-apidoc/#/tags/RelKwdStat
> 
> 또한, `CryptoJS.HmacSHA256` input parameter의 순서가 바뀌었습니다.
> 
> ```js
> var hash = CryptoJS.HmacSHA256(api_secret, signature);
> ```
> 
> 아래 문서를 참고하시기 바랍니다.
> 
> https://cryptojs.gitbook.io/docs/#hmac
> 
> ```js
> var hash = CryptoJS.HmacSHA256("Message", "Secret Passphrase");
> ```
> 
> 질문 시 응답 메시지 HTTP Header `X-Transaction-ID` 값을 같이 남겨주시면 좀 더 자세한 답변이 가능합니다.
