### ISSUE TITLE
keywordstool API의 plAvgDepth 의미

### ISSUE THREAD

**Issue by 0xF4D3C0D3** [naver/searchad-apidoc#303]
가 무엇인가요? 설명을 봐도 depth가 무엇을 의미하는지 잘 모르겠어요. 그리고 `Average depth of PC` 라는데 모바일은 전혀 상관 없는것인가요?

그리고 클릭이랑 전환율은 지난 4주의 평균, 쿼리는 지난 28일간의 합으로 보이는데
대충 아무거나 뽑아서 봤을때 예를 들어
홈쇼핑의 클릭전환율은 9.47%, 쿼리 카운트는 84500번, 평균 클릭수는 7360.2가 나오는데요.

84500 * 0.0947 = 8002 <> 7360로 미묘하게 다들 차이가 나는데요. 왜 그런걸까요? 어떤 키워드들은 차이가 많이 큽니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

먼저 detph란,
파워링크 PC 기준의 월평균노출광고수를 의미합니다.
여기서 월평균노출광고수란,
최근 한 달 간 사용자가 해당 키워드를 검색했을 때
PC통합검색 영역에 노출된 평균 광고 개수입니다.

키워드도구의 지표는 각 지표의 특성에 따라 최신성과 데이터 제공정도가 다르기 때문에
각 수치를 직접 계산한 값은 맞지않으니 제공된 평균클릭수를 활용해주세요.
문의 주신 CTR과 쿼리 데이터로 좀더 자세히 설명 드려보면 아래와 같습니다.

A. 데이터 집계기간 상이
- 쿼리수는 매일 업데이트되며 최근 30일간의 데이터
- CTR은 매주 월요일 업데이트되며 최근 4주간의 데이터
B. 쿼리수는 절대값이 아니라, 키워드 선택에 필요한 정도로 Scaling 된 데이터 입니다.
- 홈쇼핑을 예로 든다면 백의 자리에서 내림된 수치이므로 십의자리, 일의 자리가 모두 0입니다

**Comment by 0xF4D3C0D3** [comment]
아하! 그렇군요. 감사합니다~
