### ISSUE TITLE
광고관리 - 상세데이터

### ISSUE THREAD

**Issue by casis1004** [naver/searchad-apidoc#304]
광고관리 - 우측에 상세데이터 항목에서 [시간대구분]

에 해당하는 데이터를 얻으려면 어떤 경로와 파라미터로 조회를 해야 할까요?

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

http://naver.github.io/searchad-apidoc/#/tags/Stat
stat api 에서 다음 파라미터를 활용해서 조회하시면 됩니다.
`breakdown=hh24`
단, breakdown을 추가해서 조회하실 경우 조회 기간은 과거 7일 이내로 제한됩니다.

**Comment by casis1004** [comment]
답변 감사합니다.
$stat_req = array(
    "id" => "cmp-m001-01-000000000255304",
    "fields" => "avgRnk",
	"datePreset" => "yesterday",
    "breakdown" => "hh24"
);
$response = $api->GET("/stats/", $stat_req);

이런 식으로 요청할 경우
code:11001 message : 잘못된 파라미터 형식으로 응답이 옵니다.

어떤 부분이 잘묏된 건지 알수 있을까요?

**Comment by naver-searchad** [comment]
@casis1004 
fields 정보는 json format string 입니다.
그리고 올려주신 fields 항목이 하나지만
`["avgRnk"]` 형태처럼 해 주셔야 합니다.

**Comment by casis1004** [comment]
감사합니다.

breakdown 항목은 PC/모바일 구분, 요일 구분, 시간대 구분, 지역 구분 4가지 이고
fields 항목에 대한 것도 정보를 알수 있을까요?
impCnt
clkCnt
salesAmt
ctr
cpc
avgRnk
ccnt
recentAvgRnk
recentAvgCpc
pcNxAvgRnk
mblNxAvgRnk
crto
convAmt
ror
cpConv
viewCnt

**Comment by naver-searchad** [comment]
필요하신 정보는 아래 링크의 wiki FAQ-stat 에 정리해 두었습니다

https://github.com/naver/searchad-apidoc/wiki/FAQ-stat

**Comment by casis1004** [comment]
늦은 시간까지 답변주셔서 감사드립니다.
