### ISSUE TITLE
create StatReport 9월 리포트 다운로드 요청 시 400이 돌아옵니다

### ISSUE THREAD

**Issue by lachelngose** [naver/searchad-apidoc#305]
9월 1일 ~ 30일까지의 StatReport create 요청을 보냈는데,
1일 ~ 22일까지의 요청에 대해 '잘못된 파라미터 형식입니다.' 라는 response가 돌아옵니다.
파라미터는
{'reportTp': 'AD_CONVERSION_DETAIL', 'statDt': '20190922', 'item': 'AD_CONVERSION_DETAIL', 'fromTime': '2019-01-01T00:00:00.000Z'} 
이고, 9월 23일부터 30일까지는 동일 형식으로 다운로드 가능했습니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

먼저 확인이 늦어 죄송합니다.

https://github.com/naver/searchad-apidoc/wiki/FAQ-stat
위 faq에 보시면 해당 리포트의 조회 가능 기간은 45일로 나와 있습니다.
감사합니다.
