### ISSUE TITLE
Stat API호출 문의

### ISSUE THREAD

**Issue by mz-heesun** [naver/searchad-apidoc#306]
안녕하세요 

Stat Api호출 시에 문의점이 있습니다.

해당 API를

 NaverStat.DatePreset.today, NaverStat.Breakdown.hh24

이런 파라미터를 주어서 호출하고있는데요

해당 api 를 테스트해보느라고 매시간 한번씩 호출해보았습니다.

문제가 되는게 새벽시간때인데 

저희가 3시 30분에 호출했을때는 21~22 이시간대가 결과값이 나오는데

언제는 22~23시까지 나오기도합니다.

저희가 하고싶은것은 3~4시간의 딜레이를 감수하더라도 가장 최신의 데이터를 받아오고 싶은데

이 새벽시간대에는 어떻게 Stat api가 처리되는지 문의드립니다.

4시 30분에는 아무데이터도 출력되지 않더라구요 이것도 설명부탁드립니다 ~

**Comment by mz-heesun** [comment]
어제 시간이 모두 나오는 stat 값을 보고싶은데 
저희가 어느시간대에 어제자 stat api를 호출하면 
00~24시까지 다 나오는 stat값을 받아볼수있을까요

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

먼저 breakdown의 경우 today는 지원이 되지 않습니다.
말씀 주신 의미로 봐서는 전일자 지표인 듯한데요
전일 지표 작업이 완료되는 시점은 그날의 작업 상황에 따라 유동적이기 때문에
확정된 시간을 알려 드릴 수는 없습니다.
단, 사용자 분들의 api 작업에서 참고하실 수 있도록 response에
`cycleBaseTm'과 'compTm'을 리턴하고 있습니다.
각각 기준일과 작업완료시간을 의미합니다.
즉 특정 새벽시간에도 아직 cycleBaseTm이 전전일이면 전일 데이터 작업이 완료되지 않은 것이구요
전일이 리턴되었다면 완료된 거로 보시면 됩니다.
혹은 compTm의 날짜가 당일인지 여부로 판단하셔도 되구요.

**Comment by mz-ycg** [comment]
@naver-searchad  api 문서에서는 cycleBaseTm, cycleBaseTm 확인이 안되고 있습니다. 혹시 문서 업데이트가 안된건가요 ?

**Comment by mz-heesun** [comment]
**먼저 breakdown의 경우 today는 지원이 되지 않습니다.**

이렇게 말씀해주셨는데 이건 확인 한번 부탁드립니다. 
저희가 **NaverStat.DatePreset.today, NaverStat.Breakdown.hh24**

이 두가지 파라미터를 추가해서 확인하고있습니다.


그리고 api 문서상에 **`cycleBaseTm'과 'compTm'** 해당내용도 없는데 
문서상에만 없는것일까요 ?

**Comment by mz-heesun** [comment]
그리고 **먼저 breakdown의 경우 today는 지원이 되지 않습니다.**
지원이 되지 않는다면 올바른 파라미터 값은 무엇일까요 ?

매시간마다 오늘자 stat api를 통해서 해당 값들을 받아보고싶습니다.

**Comment by naver-searchad** [comment]
@mz-heesun 
stat api의 두가지 response type을 참조하시면 됩니다.
http://naver.github.io/searchad-apidoc/#/definitions/DailyStatResponse
http://naver.github.io/searchad-apidoc/#/definitions/SummaryStatResponse

compTm은 시스템 필요에 의해 추가된 내용이라서 공식적으로 문서화까지는 아직 안돼 있는 것 같습니다. 향후 업데이트 될 수 있도록 진행하겠습니다.

'오늘'자 stat에 대한 '상세데이터' 미지원은 현재 네이버 검색광고 API 특성 상의 제약사항입니다.
전일까지의 과거 7일 동안의 데이터만 지원하고 있습니다.
https://github.com/naver/searchad-apidoc/wiki/FAQ-stat

**Comment by mz-heesun** [comment]
**NaverStat.DatePreset.today, NaverStat.Breakdown.hh24**
이 파라미터로 받은 리턴필드
**`cycleBaseTm'과 'compTm'**
이 두가지 변수 확인해보면 

오늘 조회한 데이터는 오늘자 완료시간을 리턴하는걸 확인하였는데요.
이 오늘자 리턴한값을 어제자로 이해하면 되는건가요 ?

말씀하시는내용과 데이터의 값이 다른걸로 이해되서 한번 더 질문 드립니다.
