### ISSUE TITLE
일별 허용량 제한이 걸려있는지 궁금합니다.

### ISSUE THREAD

**Issue by audidas** [naver/searchad-apidoc#307]
developers API 같은 경우 일 검색 API 일 허용량이 25000회로 정해져있던거 같던데 혹시 이 API도 같은 제한이 걸려있나요?

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

일 허용량 기준은 없습니다.

**Comment by audidas** [comment]
답변 감사드립니다  
좋은 하루 보내시길 바랍니다
