### ISSUE TITLE
쇼핑소재 평균 노출 순위

### ISSUE THREAD

**Issue by lachelngose** [naver/searchad-apidoc#308]
얼마전에 쇼핑검색 소재 룰 기반 입찰 기능이 오픈된 걸 보았는데,
룰 중 pc/mobile 통합 검색 노출 순위 기준이 있더라구요.
기존 get ad api 에서 해당 값을 받아올 수 있나요?
그리고 가능하다면 통합 검색 화면이 아니라 쇼핑 화면에서 노출 되는 순위도 조회 되나요?

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

필요하신 필드 정보는 아래 링크에서 확인해 보실 수 있습니다.
https://github.com/naver/searchad-apidoc/wiki/FAQ-stat

그리고 쇼핑 지면 상의 노출 순위는 제공되지 않습니다.
감사합니다.
