### ISSUE TITLE
StatReport에는 존재하는 키워드 ID이나 MasterReport 에는 존재하지 않는 ID 건

### ISSUE THREAD

**Issue by riemannulus** [naver/searchad-apidoc#309]
안녕하세요.

## 발생한 문제
같은 날짜의 StatReport와 MasterReport를 받아 와 키워드 id 기준으로 매핑하였을 때, StatReport에는 존재하는 키워드 ID이나 MasterReport에는 존재하지 않는 keyword id가 발견되었습니다.

## 질문
1. StatReport에는 존재하나 MasterReport에는 존재하지 않는 id가 있을 수 있나요?
2. MasterReport를 과거의 날짜를 지정해서 받아 올 경우, 그 날짜 기준의 스냅샷을 받아오나요?

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

우선, 해당 키워드 id가 삭제된 상태인지 확인해 보시기 바랍니다.
StatReport 시간을 기준으로 그 이후 삭제된 키워드일 가능성이 높아 보입니다.

마스터리포트의 경우 fromTime 조건을 주지 않으면 현재 삭제되지 않은 대상만 리턴됩니다.
과거 시간으로 조회할 경우에는 삭제된 대상도 리턴이 되고 있습니다.

**Comment by riemannulus** [comment]
안녕하세요. 확인이 늦었습니다.

마스터 리포트의 fromTime 조건을 주지 않고, 해당 키워드가 삭제되기 전 날짜를 조회하면 마스터 리포트에서 해당 키워드의 id와 값이 리턴이 되는 게 맞는지요?
