### ISSUE TITLE
문의 드립니다.

### ISSUE THREAD

**Issue by handbbang** [naver/searchad-apidoc#31]
안녕하세요.

 api로 다차원보고서를 못가져 온다고 말씀 하셨는데요.

 차후 api로 확장 개발 될 가망성이 있나요 ?

**Comment by naver-searchad** [comment]
안녕하세요.

다차원 보고서에서 사용되는 API와 관련하여 문의주셨는데요, 
현재는 확장 개발 계획이 없습니다.

감사합니다.

**Comment by naver-searchad** [comment]
@handbbang 

첨언 드리자면 

API 서비스에서는 최대한 가공이 되지 않은 RAW데이터를 제공드려 사용자분들께서 커스트마이징을 하시기 용이한 데이터 제공을 목표로 하고 있는 반면 
다차원 보고서는 웹사이트내에서 데이터를 말 그대로 다차원적으로 분석하실 수 있도록 
가공한 데이터를 제공드딘다는 차이점이 있습니다. 

따라서 향후에도 다차원 보고서는 API로는 제공드릴 계획이 없으며 
다차원 보고서가 반드시 필요하신 경우는 API 보고서의 지표를 다차원 보고서와 동일 하게 가공하실 수 
있도록 데이터 계산 방식이나 기준등을 안내 드리고 있습니다. 
다차원 보고서는 API 보고서와 동일 기반 데이터를 어떤 관점에서 가공한 것인가의 차이만 있으므로
본질적으로는 API 보고서를 이용해 다차원 보고서와 동일한 데이터 셋을 만들어 내실 수 있습니다. 

감사합니다.

**Comment by handbbang** [comment]
우선 답변 감사드립니다.

현재 다차원 보고서를 굉장히 편리하게 여러가지 구성이 가능하여 해당 리포트를 만들어
api가 지원 된다면 해당 데이터들을 가져와 사용 하려고 했는데요.
답변 주신 말대로 원천 데이터로 가공을 할 수는 있지만 해당 다차원 보고서 api도 지원 해주시면
보다 사용자들이 편리하고 다양하게 이용 가능 할 것이라고 생각이 드내요 ^^;

사실 구글이나 기타 다른 글로벌 기업들은 소소하지만 전부 화면에 보이는 리포팅은 
원천 데이터 뿐만 아니라 가공되어져 있는 다차원 보고서들에 대해서도 api를 제공 해주고 있기에
네이버 광고 관리자에서도 당연히 api를 제공 해주거나 앞으로 확장 된 api가 나오지 않을까 궁금하여
문의 드렸습니다.

좀 많이 아쉽지만 친절하게 알려주신 정보대로 이용 하도록 하겠습니다.
감사합니다.

ps. ^___^ 혹시 확장을 다시 고려 해보시면 더 좋겠습니당~ 수고하세효~

**Comment by handbbang** [comment]
우선 답변 감사드립니다.

현재 다차원 보고서를 굉장히 편리하게 여러가지 구성이 가능하여 해당 리포트를 만들어
api가 지원 된다면 해당 데이터들을 가져와 사용 하려고 했는데요.
답변 주신 말대로 원천 데이터로 가공을 할 수는 있지만 해당 다차원 보고서 api도 지원 해주시면
보다 사용자들이 편리하고 다양하게 이용 가능 할 것이라고 생각이 드내요 ^^;

사실 구글이나 기타 다른 글로벌 기업들은 소소하지만 전부 화면에 보이는 리포팅은 
원천 데이터 뿐만 아니라 가공되어져 있는 다차원 보고서들에 대해서도 api를 제공 해주고 있기에
네이버 광고 관리자에서도 당연히 api를 제공 해주거나 앞으로 확장 된 api가 나오지 않을까 궁금하여
문의 드렸습니다.

좀 많이 아쉽지만 친절하게 알려주신 정보대로 이용 하도록 하겠습니다.
감사합니다.

ps. ^___^ 혹시 확장을 다시 고려 해보시면 더 좋겠습니당~ 수고하세효~
