### ISSUE TITLE
계정관리

### ISSUE THREAD

**Issue by casis1004** [naver/searchad-apidoc#311]
키워드별로 각 관리 계정을 만들었고,
만든 계정으로 캠페인 및 / 광고그룹 / 키워드 id등을 관리하고 있습니다.

계정A에 대해서는 A에 해당하는 캠페인 /광고그룹/키워드 id만 조회가 가능하네요.

혹시, 마스터계정(?)처럼
A계정의 AA키워드
B 계정의 BB키워드로 접근이 가능한 방법이 있나요?

계정이 여러개일 경우, 각 계정별로 api접근정보를 달리해서 접근해야만 하는건가요?

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

광고홈 내계정의 계정 간 권한 부여/수락 기능을 이용하면 타 계정의 광고관리가 가능합니다.
이렇게 권한을 부여받은 광고관리용 계정을 이용해서 다른 계정(권한을 준)들의 데이터에 접근할 수 있습니다.
이 때는 광고관리용 계정에서만 API Secret Key를 발급 받으면 됩니다.

관리용 계정 본인의 customer id를 가지고 customer-links api를 조회하면
권한을 준 client 계정들의 customer id를 알 수 있으며 이를 이용해 해당 계정의 데이터를 이용하시면 됩니다.

단, 한번의 api 요청으로 여러 계정의 데이터를 접근하는 것은 불가능합니다.

**Comment by casis1004** [comment]
다른 계정의 customer_id는 이미 알고 있습니다.
다만, customer_id가 서로 다른데도 조회를 할수 있는지 궁금합니다.

**Comment by naver-searchad** [comment]
@casis1004 
문의하신 의미가 잘 이해가 안되네요.
권한을 주고 받아 조회할 경우 api 요청하는 계정와 광고주 데이터 계정은 당연히 서로 다른 게 됩니다.

**Comment by casis1004** [comment]
답변 주신 내용중에서
"관리용 계정 본인의 customer id를 가지고 customer-links api를 조회하면
권한을 준 client 계정들의 customer id를 알 수 있으며 이를 이용해 해당 계정의 데이터를 이용하시면 됩니다."

이렇게 답변을 주셨는데요, 
관리용 계정 본인의 customer id 를 가지고, 권한을 준 client 계정들의 customer id를 이용하지 않고
관리용 계정 본인의 customer id로 다른 계정들의 데이터를 바로 이용가능한지 궁금합니다.

**Comment by naver-searchad** [comment]
@casis1004 
당연히 안됩니다.
customer id가 곧 원하는 데이터의 소유주를 의미하기 때문입니다.

**Comment by casis1004** [comment]
네, 답변 주셔서 감사합니다.
