### ISSUE TITLE
js 로 keywordstool 받아오는데 문의드립니다.

### ISSUE THREAD

**Issue by dd1233345** [naver/searchad-apidoc#313]
<script>
    var timestamp = new Date().getTime();
    var date = timestamp.toPrecision()
    var signature = date + "." + "GET" + "." + "/keywordstool"
    var hash = CryptoJS.HmacSHA256(signature, "????");
    var hashInBase64 = CryptoJS.enc.Base64.stringify(hash);

    $.ajax({
        method: "get",
        url: "https://api.naver.com",
        data: {
          hintKeywords: "남자반바지"
        }
        headers: {
          X - Timestamp: date,
          X - API - KEY: "????",
          X - Customer: "????",
          X - Signature: hashInBase64
        }
      })
      .done(function(msg) {
        alert(msg);
      });
  </script>

이렇게 해서 돌렸는데 결과가 아예 안나오네요...
왜 그런지 알 수 있을까요

**Comment by dd1233345** [comment]
<script>
    var timestamp = new Date().getTime();
    var date = timestamp.toPrecision()
    var signature = date + "." + "GET" + "." + "/keywordstool"
    var hash = CryptoJS.HmacSHA256(signature, "????");
    var hashInBase64 = CryptoJS.enc.Base64.stringify(hash);

    $.ajax({
        method: "get",
        url: "https://api.naver.com",
        data: {
          hintKeywords: "남자반바지"
        }
        headers: {
          X - Timestamp: date,
          X - API - KEY: "????",
          X - Customer: "????",
          X - Signature: hashInBase64
        }
      })
      .done(function(msg) {
        alert(msg);
      });
  </script>

**Comment by dd1233345** [comment]
<script><br>
    var timestamp = new Date().getTime();
    var date = timestamp.toPrecision()
    var signature = date + "." + "GET" + "." + "/keywordstool"
    var hash = CryptoJS.HmacSHA256(signature, "????");
    var hashInBase64 = CryptoJS.enc.Base64.stringify(hash);

    $.ajax({
        method: "get",
        url: "https://api.naver.com",
        data: {
          hintKeywords: "남자반바지"
        }
        headers: {
          X - Timestamp: date,
          X - API - KEY: "????",
          X - Customer: "????",
          X - Signature: hashInBase64
        }
      })
      .done(function(msg) {
        alert(msg);
      });
  </script>

**Comment by dd1233345** [comment]
<script>
var timestamp = new Date().getTime();
var date = timestamp.toPrecision()
var signature = date + "." + "GET" + "." + "/keywordstool"
var hash = CryptoJS.HmacSHA256(signature, "????");
var hashInBase64 = CryptoJS.enc.Base64.stringify(hash);

$.ajax({
  method: "get",
  url: "https://api.naver.com",
  data: {
    hintKeywords: "남자반바지"
    }
  headers: {
    X - Timestamp: date,
    X - API - KEY: "????",
    X - Customer: "????",
    X - Signature: hashInBase64
    }
  })
  .done(function(msg) {
    alert(msg);
  });
</script>

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

API 응답이 정상인데 결과가 비어 있다는 말씀이신가요?

**Comment by dd1233345** [comment]
응답이 없습니다. 코드에 문제가 있나요??

**Comment by naver-searchad** [comment]
@dd1233345 
response header 내용을 공유해 주셔야 확인이 가능하겠습니다.

**Comment by dd1233345** [comment]
네트워크를 봐도 아무런 응답이 없습니다.

**Comment by dd1233345** [comment]
고쳐서 응답을 받았는데 403 이 나옵니다

HTTP/1.1 403 Forbidden
Allow: GET, HEAD, POST, PUT, DELETE, TRACE, OPTIONS, PATCH
Content-Length: 20
Date: Tue, 19 Nov 2019 01:31:17 GMT
Strict-Transport-Security: max-age=15768000

**Comment by dd1233345** [comment]
Invalid CORS request 가 문제인 것 같습니다... 어떻게 해결하는지 알 수 있을까요?

**Comment by naver-searchad** [comment]
@dd1233345 
참고로 <script> 태그가 있는 것으로 봐서 클라이언트 브라우저 스크립트로 실행하시려는 듯한데요
이럴 경우 코드가 그대로 노출이 되므로 api 사용이 금지되어 있습니다.
nodeJs와 같은 서버 javascript를 이용해서 테스트해 주시기 바랍니다.
