### ISSUE TITLE
exceeded limit of '100' numbers of 'job'

### ISSUE THREAD

**Issue by aquazen** [naver/searchad-apidoc#314]
https://api.naver.com/master-reports 호출시 아래와 같은 에러가 나고 있습니다.

{"name":"BadRequest","status":400,"title":"Bad Request","detail":"exceeded limit of '100' numbers of 'job'"}

이유를 알 수 있을까요?
참고로 며칠전까지 잘 돌았었습니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

API 명세에 보시면 job list는 최대 100개 제약이 있음을 알 수 있습니다.
list해 보시고 삭제 가능한 job들을 먼저 정리(delete)하신 뒤
새 요청을 해 주시면 됩니다.

**Comment by aquazen** [comment]
감사합니다. 해결되었습니다.
