### ISSUE TITLE
keywordstool 응답을 받았는데 리스트가 비어있습니다.

### ISSUE THREAD

**Issue by dd1233345** [naver/searchad-apidoc#315]
const request = require("request");
var SHA256 = require("crypto-js/sha256");
var CryptoJS = require("crypto-js");
var timestamp = Number(new Date())
var date = timestamp.toPrecision()
var signature = date + "." + "GET" + "." + "/keywordstool"
var hash = CryptoJS.HmacSHA256(signature, secetkey);
var hashInBase64 = CryptoJS.enc.Base64.stringify(hash);

var options = {
  'uri' : 'https://api.naver.com/keywordstool',
  'method' : 'GET',
  'headers':{
    'X-Timestamp': date,
    'X-API-KEY': '',
    'X-Customer': '',
    "X-Signature": hashInBase64,
   },
  'hintKeywords': '남자바지'
 };

request.get(options, function (err,res,body){
console.log(body)
});

위는 제가 짠 코드입니다.
응답은 받았는데 body: '{"keywordList":[]}' 와 같이 나옵니다.

'x-transaction-id': 'BEHI6GINPHIIG' 입니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

먼저, 답변이 좀 늦어져서 죄송합니다.

올려주신 transaction id 'BEHI6GINPHIIG'로는 남아 있는 로그가 확인되지 않고 있습니다.
다시 한번 확인 부탁드립니다.
그리고 올려주신 코드 만으로는 특별히 문제되는 점은 보이지 않습니다만,
hinKeywords 한글이 적절히 인코딩 되고 있는지도 확인해 주시면 좋을 것 같습니다.
