### ISSUE TITLE
master-reports에서 fromTime을 입력하지 않을 경우에 대하여 문의드립니다.

### ISSUE THREAD

**Issue by Daniel-Dobal-Oh** [naver/searchad-apidoc#316]
안녕하세요.
먼저 항상 친절하고 빠르게 회신주셔서 감사합니다.

/master-reports api를 이용하여 keyword master 데이터를 이용하고 있습니다.
마스터 파일 생성 시점은 한국시간 기준 새벽 1~2시 사이입니다.
생성시 전달하는 파라메터는 아래와 같습니다. 

`
MasterReport(id=null, item=Keyword, fromTime=null, updateTime=null, status=null, downloadUrl=null)
`
의도했던 바는 요청시점에 등록되어 있는 모든 키워드를 얻기 위함이었습니다.
그런데 위와 같이했을 때 전날에 삭제된 키워드 중 일부가 파일에 포함되는 것같습니다.
아마도 fomeTime이 null로 지정된 것과 연관이 있을 것으로 추정하고 있습니다.

문의드릴 부분은 두 가지입니다.
1. 위와 같이 삭제된 키워드가 포함되는 이유.
2. fromTime을 지정하지 않을 경우 어느 시점부터의 데이터가 대상인지.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.
fromTime을 입력하지 않으셨다면, 요청 시점 이전까지 등록된 정보 중 삭제되지 않은 광고 목록 전체를 반환하도록 되어 있습니다.
요청시점 즈음에 삭제된 키워드가 있다면, 포함되었을 수도 있습니다.
그렇지 않다면, 삭제된 키워드가 포함되어 있는 보고서의 ID를 알려주시면 확인하는데 도움이 될 거 같습니다.

**Comment by Daniel-Dobal-Oh** [comment]
보고서 ID는 7ADCA523EB74FE8DF3B404DD3F14C5BD 입니다.

이미 며칠 전에 삭제되었지만, 보고서에 들어있는 키워드는 다음과 같습니다.
`nkw-a001-01-000001592503865 (grp-a001-01-000000008527136)
nkw-a001-01-000001592503896 (grp-a001-01-000000008527136)
nkw-a001-01-000001592510535 (grp-a001-01-000000008495682)
nkw-a001-01-000001592514229 (grp-a001-01-000000008348585)
nkw-a001-01-000001592515459 (grp-a001-01-000000008495682)`

고맙습니다.

**Comment by naver-searchad** [comment]
확인 결과 2018년 11월 27일 17시 27분경에 삭제하신 광고들 중 일부가 마스터 리포트 시스템으로 동기화가 되지 않았던 문제가 있었습니다.
업무에 불편을 드려서 대단히 죄송합니다.
문제가 되었던 광고, 정보들을 동기화하였습니다.

**Comment by Daniel-Dobal-Oh** [comment]
답변 고맙습니다.
오늘 리포트에  데이터 보정된 것 확인하였습니다. ^^
