### ISSUE TITLE
/stats에서 결과 갯수가 일부만 돌아옵니다.

### ISSUE THREAD

**Issue by ghost242** [naver/searchad-apidoc#317]
/stats에 파라미터로 id 12개를 한번에 보내는 요청을 수행했을 때 결과가 10개만 돌아오고 있습니다.
개별 id를 한번씩 모두 보내보면 12개가 정상적으로 돌아옵니다.

마지막으로 테스트해본게 X-Transaction-ID 값이 'BEM5MP071DGR2'인 요청입니다. 
도움 부탁드립니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

stats api는 지표가 존재하는 id만 리턴하게 되어 있습니다.
요청하신 transaction의 시간은 2019-11-28 18:52:57
제외된 두 지표는
```
nkw-a001-01-000001665635095 : 21시 ~ 22시 사이 노출
nkw-a001-01-000001665635092 : 28일에 노출된 적 없음
```
으로 확인됩니다.

**Comment by ghost242** [comment]
아... 확인했습니다. 답변 감사합니다
