### ISSUE TITLE
RelKwdStat 의 month 파라미터

### ISSUE THREAD

**Issue by Yearang** [naver/searchad-apidoc#318]
안녕하세요 
RelKwdStat 의 month 파라미터가 정확히 뭘 뜻하는지 궁금합니다.
month를 바꿔가며 호출해도 검색한 키워드 관련 통계 숫자는 변하지 않고 연관 키워드 목록이 바뀝니다. 
1. month 파라미터가 해당월의 검색량이 아닌 해당월의 연관검색어를 뜻하는건가요?
2. 기간을 필터링해 특정 키워드의 검색량을 조회할 수 있는 API는 없나요?

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

1.
말씀해 주신 부분이 맞습니다.
month 파라미터는 해당 월과 관련된 연관도를 이용하기 위한 힌트로 사용됩니다.

2.
기간별 검색량 API는 지원해 드리고 있지 않습니다.
다음의 FAQ 내용을 더 참고해 주시기 바랍니다.
https://github.com/naver/searchad-apidoc/wiki/FAQ-stat#q-%EC%97%B0%EA%B0%84-%ED%82%A4%EC%9B%8C%EB%93%9C-%EA%B2%80%EC%83%89%EC%88%98-%EC%B6%94%EC%9D%B4-api-%EC%A0%9C%EA%B3%B5%EC%97%AC%EB%B6%80

**Comment by Yearang** [comment]
감사합니다. 적게일하고 많이버세요
