### ISSUE TITLE
쇼핑 소재 생성 문의

### ISSUE THREAD

**Issue by Sene68** [naver/searchad-apidoc#319]
안녕하세요. 

쇼핑소재 생성하는 중 궁금한 점이 있어 문의드립니다.

1. Ad: create 의 Request Parameter중 ad parameter가 필수값으로 되어있어 있는데
1.1 pc / mobile은 PC랜딩 Mobile랜딩 url을 입력하는건가요?
1.2 headline / description은 샘플 텍스트로 등록하였는데 등록시 어디에 표시가 되나요?

2. 노출용 상품명은 API상 create / update 중 어떤 파라미터를 활용해야 하는지 등록되나요?

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

API DOC 문서의 소재 create는 '파워링크' 상품 기준입니다.
쇼핑 상품 소재의 경우는 상품 연동 등 여러가지 이유로 API로는 이용이 어려우니
되도록 광고관리 화면을 통해 등록해 주시기 바랍니다.
API로 반드시 이용하고 싶으신 경우에는
광고관리 화면에서 소재를 등록하고 노출용 상품명을 수정할 때 발생하는 http request 양식을 참고하시면 됩니다.
