### ISSUE TITLE
문의드립니다.

### ISSUE THREAD

**Issue by handbbang** [naver/searchad-apidoc#32]
c#에서 캠페인 정보를 가져오려고 하는데요.

 var request = new RestRequest("/stats?id=cmp-a001-01-000000000233277&fields=['impCnt','clkCnt','salesAmt']&datePreset=today&breakdown=hh24&timeIncrement=allDays", Method.GET);

Campaign cp = rest.Execute<Campaign>(request, managerCustomerId);

이런 형태로 실행을 하니 값을 못가져 오는 것 같습니다.

stats의 파마메터를 어떤 식으로 전달 해야 하나요?

**Comment by naver-searchad** [comment]
답변이 늦어 죄송합니다. 내용상 캠페인의 광고 효과 정보(보고서)를 조회 하시는 것으로 생각 되는데요. 

STAT 파라미터 자체는 올바르게 설정 하신 것으로 보입니디만 
값을 못 가져 오신다는 말씀이 어떤 내용인지 예를 들면 에러가 발생했는지 혹은 빈 값이 반환 되는지 
등에 대한 정보가 있어야 상세한 답변을 드릴 수 있을것 같습니다. 

지금 내용만으로 의심이 가는 부분은 managerCustomerId 인데요. 저희 샘플 코드를 사용하셨다면 
managerCustomerId => 라이선스를 가지고 있는 본인 계정을 의미 합니다. 캠페인 ID가 본인 계정에 
있는 캠페인의 ID가 맞는지요?
