### ISSUE TITLE
키워드 별로 클릭 카운트를 조회할 수 있나요 ?

### ISSUE THREAD

**Issue by mz-heesun** [naver/searchad-apidoc#320]
종합적인 클릭카운트말고

키워드 개별로 카운트가 가능한지 문의드립니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

의도하시는 질문 내용이 정확하지 않아 답변 드리기는 어렵겠습니다.
다만 광고관리에 등록하신 키워드의 개별 클릭 카운트를 의미하는 것이라면
stat api를 이용해서 조회할 수 있습니다.
http://naver.github.io/searchad-apidoc/#/operations/GET/~2Fstats%7B%3Fids,fields,timeRange,datePreset,timeIncrement,breakdown%7D

**Comment by mz-heesun** [comment]
감사합니다
