### ISSUE TITLE
확장소재 질문

### ISSUE THREAD

**Issue by Sene68** [naver/searchad-apidoc#321]
안녕하세요. 

확장소재 PROMOTION 타입을 여러개 한번에 등록가능 할 수 있을까요?

가능하면 예시부탁드립니다.

아니면 한개씩 메소드를 여러번 호출해야하나요?

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

확장소재는 한 개 씩만 등록 가능합니다.

**Comment by Sene68** [comment]
감사합니다~
