### ISSUE TITLE
쇼핑소재 관련 문의드립니다.

### ISSUE THREAD

**Issue by SteveKim7878** [naver/searchad-apidoc#322]
안녕하세요 쇼핑소재 관련 궁금한 부분이 있어서 문의드립니다.

API에서 소재에 대한 정보를 가져왔을때 쇼핑소재일 경우에 해당 소재의 노출상품명, 상품 이미지 등 등록시에는 입력하는 내용이 확인이 되지 않는 것 같습니다.

어떻게 조회를 하면 상세 내용을 확인 할 수 있는지 문의드립니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

쇼핑검색 유형 소재는 등록시 노출용 상품명과 이미지를 별도로 함께 등록할 수 없고
등록 후 수정으로만 가능합니다.
등록된 소재를 조회해서 리턴되는 데이터 중
referenceData 필드 객체를 열어보면 해당 상품에 대한 쇼핑쪽 정보들이 포함되어 있으니 참고하시면 됩니다.

**Comment by SteveKim7878** [comment]
네 확인 했습니다. 
답변 감사합니다.
