### ISSUE TITLE
쇼핑검색광고 관련 문의

### ISSUE THREAD

**Issue by yuchigirl** [naver/searchad-apidoc#323]
쇼핑검색광고에 등록된 상품목록을 가지고 올려하는데요, 
이 부분이 api로 제공이 되는지 궁금합니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

쇼핑검색광고 유형에 등록한 광고 즉 '소재'를 API로 조회하시면 됩니다.
http://naver.github.io/searchad-apidoc/#/operations/GET/~2Fncc~2Fads%7B%3FnccAdgroupId%7D
