### ISSUE TITLE
Error Code 가 다르게 날아옵니다.

### ISSUE THREAD

**Issue by kaorimikage** [naver/searchad-apidoc#324]
계정에서 그룹을 생성시킨후에 삭제하고 해당 그룹에 대한 정보를 취득하려고 하는데 Error Code가 상황에 따라 다르게 날아옵니다.
https://github.com/naver/searchad-apidoc/blob/master/NaverSA_API_Error_Code_MAP.md
기준으로...

$api_link->GET( '/ncc/adgroups/group_id' );
형식의 경우 1018(퍼미션 오류) 이 반환되고

$api_link->GET( '/ncc/adgroups', array( 'ids' => group_id ) );
형식의 경우 3017(삭제된 그룹) 이 반환됩니다.

왜 결과가 다른것인가요?

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

특별한 이유가 있지는 않습니다.
의도한 결과라기보다는 path 단건 api와 ids 목록 api 구현 상의 차이라고 보시면 되겠습니다.

단건 조회에서는 삭제된 객체를 배제하고 '접근 가능'한 id인지를 먼저 확인하기 때문에
해당 id가 삭제된 객체인지 존재하지 않는 객체인지 다른 광고주의 객체인지를 구분하지 않고
'퍼미션 오류'가 되는 것이고
목록 조회에서는 일단 삭제여부를 확인하지 않고 모든 목록을 가져온 후 대조하기 때문에
이 상황에서는 일단 '퍼미션' 확인은 통과한 상태이기 때문에
'삭제된 오류'라는 세부 메시징이 가능합니다.

어쨌든 삭제된 객체에 대한 정보는 조회할 수 없기 때문에 이와 같은 차이에 대해 따로 고려하실 부분은 없으리라 생각됩니다.

**Comment by kaorimikage** [comment]
해당 부분에 대하여 단일 조회도 퍼미션 확인을 넘긴 후 명확한 코드를 주시는건 안되는건가요?
실제 권한이 없는것인지 삭제가 된 상태인건지 알 방법이 없습니다.

**Comment by naver-searchad** [comment]
@kaorimikage 
권한이 없는 경우라면 어떠한 api라도 http status 403이 리턴될 겁니다.
위에서 퍼미션 오류는 404 즉 '리소스 없음'을 의미합니다.
즉 이 때 퍼미션 오류는 삭제된 것인지 존재하지 않는 것인지까지는 구분이 되지 않는다는 것입니다.

결국 관리하던 id가 위의 에러를 리턴한다면 '삭제'되었다고 보셔도 되지 않을까 싶습니다.
임의의 id를 조회하시지는 않을 테니까요.

**Comment by kaorimikage** [comment]
$api_link->GET( '/ncc/adgroups', array( 'ids' => group_id ) );
의 경우, 3017이 반환되었었는데 오늘 확인해보니 1018이 넘어옵니다.

거기에 기존에는 그룹 id를 여러개 넣었을 경우 삭제된 그룹 id가 포함되어 있으면 해당 그룹은 제외하고 나머지 그룹에 대한
데이터를 반환했었는데 현재는 전부 반환하지 않고 있습니다.

언제 수정이 된 것인지요? 변경되었다면 변경에 대한 공지를 어디에서 확인할 수 있을까요?

**Comment by naver-searchad** [comment]
@kaorimikage 안녕하세요? 네이버 검색광고 API입니다.

광고 그룹 관련 API가 수정된건 없습니다.
수정이된 경우 Release note에 공지를 하고 있습니다.

1018은 부정한 접근일 경우에 리턴 하고 있습니다. (예를 들어 본인 소유의 광고 그룹이 아닌경우)

정확한 원인을 확인하기 위해서는, 요청한 Request를 알려주셔야 확인이 가능합니다.

감사합니다.

**Comment by kaorimikage** [comment]
그룹 ID는 실제 사용하는 ID라 임의로 표현했습니다.

$group  = $link->GET( '/ncc/adgroups', array( "ids" => "grp-a001-01-000000000000001" ) );
으로 값을 취득하면 제대로 정보를 끌어옵니다.

$group  = $link->GET( '/ncc/adgroups', array( "ids" => "grp-a001-01-000000000000002,grp-a001-01-000000000000001" ) );
로 값을 취득하면 404오류가 납니다. grp-a001-01-000000000000002는 삭제된 그룹입니다.

기존에는 grp-a001-01-000000000000002에 대한 정보를 빼고 grp-a001-01-000000000000001에 대한 정보를 반환했었습니다. 그리고 ID 두개가 전부 삭제된 경우에는 빈 array를 반환했었습니다.

그룹을 예로 들었는데 복수로 값을 취득하는 모든 API에 일괄적으로 적용되는 내용입니다.
