### ISSUE TITLE
Shopping Campaign Search Keyword Performance Detail Report 문의

### ISSUE THREAD

**Issue by Sene68** [naver/searchad-apidoc#325]
안녕하세요

Shopping Campaign Search Keyword Performance Detail Report를 다운로드 받아 내용을 확인하는데
궁금한점이 있어 문의남깁니다.

1. Region code는 참고할만한 사이트나 표가 있을까요?

2. 데이터의 Hours 필드 없이 Date기준으로 sum된 데이터를 받을 순 없나요?

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

지역코드는 다음 wiki에 등록되어 있습니다.
https://github.com/naver/searchad-apidoc/wiki/FAQ#q-%EC%A7%80%EC%97%AD-%EC%BD%94%EB%93%9C

2번은 지원이 되지 않고 있습니다.

**Comment by Sene68** [comment]
감사합니다~
