### ISSUE TITLE
Estimate (Average position bid) 문의

### ISSUE THREAD

**Issue by SunJang** [naver/searchad-apidoc#326]
안녕하세요. 

POST /estimate/average-position-bid/id 을 호출 할 때,
광고주의 액세스라이센스와 시크릿키로 호출하면 bid, keyword, position, nccKeywordId를 정상적으로 리턴하지만,
AE의 액세스라이센스와 시크릿키로 호출하면 position, nccKeywordId만 리턴되고 bid 값을 리턴하지 않습니다.

예전에는 AE의 권한으로 호출해도 정상적으로 bid 값을 리턴했었는데요. 언제부터 변경 된 것인지
향후에도 광고주의 계정으로 호출했을 때만 해당 API를 사용 가능한건가요?

**Comment by SunJang** [comment]
참고로 searchad.naver.com 웹에서는 AE 계정으로도 estimate 가 가능합니다. api 에서만 막아놓은 것 같습니다.

**Comment by naver-searchad** [comment]
안녕하세요. 검색광고 API입니다.
TransactionID 알려주시면 확인 후 답변 드리도록 하겠습니다.

**Comment by SunJang** [comment]
'x-transaction-id': 'BF3HLOK0PHH79' 입니다.

**Comment by naver-searchad** [comment]
AccessToken을 발급하실 때 CustomerID를 대상 광고주의 ID를 입력하셔야 합니다.
입력하신 CustomerID와 등록키워드를 조회할 수 없어 견적 데이타를 생성하지 못한 케이스 입니다.

**Comment by SunJang** [comment]
X-Customer의 값이 잘못되었다는게 무슨 말인지 잘 모르겠네요.

X-Customer 는 API를 호출하는 자의 ID 아닌가요?
AE의 customerId (1171307) 을 X-Customer 1171307 값을 가지고, 해당 id에 맞게 사이닝해서 X-Signature설정 후 API를 호출하고 있습니다. 광고주의 customerId(957874) 에 맞게 X-Customer를 설정하고 사이닝해서 호출하면 정상리턴하는 것은 확인했구요.

최초 질문이 그거였습니다. AE가 searchad.naver.com 에 접속하면 아래 스크린샷 처럼 광고주의 estimate 값을 가져 올 수 있는데 (bid 값이 존재)

<img width="1269" alt="스크린샷 2019-12-19 오후 4 44 47" src="https://user-images.githubusercontent.com/1294162/71154493-f6cbda80-227e-11ea-88f0-786cdf219f17.png">

<img width="1265" alt="스크린샷 2019-12-19 오후 4 44 59" src="https://user-images.githubusercontent.com/1294162/71154507-00edd900-227f-11ea-9736-88d4f434bce3.png">

API 를 통해서는 AE 가 호출하면 bid값이 없음(광고주가 호출하면 있음)
<img width="488" alt="스크린샷 2019-12-19 오후 4 56 46" src="https://user-images.githubusercontent.com/1294162/71155216-9d64ab00-2280-11ea-9829-3049f27d968d.png">

1. 이 상황 (내부 API와 외부 API가 동작을 다르게하는게) 정상적인 상황인 것인지?
2. 정책에 의해 AE가 외부 API를 통해 estimate값을 가져올 수 없는게 확정적이라면 앞으로도 그렇다는 것인지 궁금합니다.

* 내부 API : https://manage.searchad.naver.com/api/estimate/average-position-bid/id
* 외부 API : https://api.naver.com/estimate/average-position-bid/id

**Comment by naver-searchad** [comment]
헤더의 `X-Customer`에 엑세스하고자 하는 대상 광고주의 ID가 입력되어야 합니다.
정책이 변경되지  않았습니다. 
Signature 생성 시에는  CustomerID가 사용되지 않습니다.
`X-Customer`에 대상 광고주ID를 사용해서 다시 호출해보시기 바랍니다.

**Comment by naver-searchad** [comment]
좀 더 부연 드리자면,

웹에서 AE(AE가 뭔지는 잘 모르겠지만 대행계정을 의미하시는 것으로 이해하고) 계정으로 로그인해서
광고관리 대상 계정으로 바꾼 후 사용하시는 걸 API로 해석하자면,
AE 계정의 api key를 사용한다는 게 곧 '로그인'한 계정과 같은 개념이고
X-Customer에 입력하는 customer id가 곧 관리대상 계정을 설정한 것과 같은 개념입니다.

즉 api key는 로그인한 계정이니 바뀌지 않는 정보이고
관리대상 계정은 바꿔 가면서 사용하는 것이므로 X-Customer를 변수처럼 이용하시는 의미입니다.

**Comment by SunJang** [comment]
네 이해했습니다.
친절한 답변 감사합니다.
