### ISSUE TITLE
invalid-signature 관련 문의 드립니다.

### ISSUE THREAD

**Issue by SteveKim7878** [naver/searchad-apidoc#327]
현재 API를 사용하고 있는 중인데 간혹 Invalid Signature 라는 에러 메시지가 나타납니다.
다른 호출에선 문제가 없는 것 같은데 간혹 Invalid Signature 가 발생하는 이유가 어떤 것인지 궁금합니다.
X-Transaction-ID:BF3F5O8L1DIDC
입니다.

확인 부탁드리겠습니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

이미 생성된 서명 값은 역산이 불가능하므로, 정확히 어느 부분이 잘못되었는지를 확인해드릴 수는 없습니다.
다만, 해당 요청에 첨부한 서명은 T2kZ ~중략~ wrqI= 이지만,
실제로는 uAy ~중략~ FxtY=가 되어야 합니다.

서명을 생성을 위해 사용한 데이터가 1576719320133.GET./billing/bizmoney 가 맞는지도 확인해보시기 바랍니다.

**Comment by SteveKim7878** [comment]
API#_# Request: GET https://api.naver.com/billing/bizmoney HTTP/1.1
        X-Timestamp 1576719320133
        X-API-KEY XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X-Customer XXXXXXX
        X-Signature T2kZ2axjJo/SBSs41bYnbNP8903yHYIhtnW9a1TwrqI=
 API#_# Response: {"signature":"T2kZ2axjJo/SBSs41bYnbNP8903yHYIhtnW9a1TwrqI=","title":"Invalid Signature","detail":"Signature 'T2kZ2axjJo/SBSs41bYnbNP8903yHYIhtnW9a1TwrqI=' is invalid.","status":403,"type":"urn:naver:api:p
roblem:invalid-signature"}
X-Transaction-ID:BF3F5O8L1DIDC

생성한 signature에 대한 결과 입니다.
말씀하신 1576719320133.GET./billing/bizmoney 로 생성한 것이 맞는 것 같은데 서명값이 왜 틀리게 나오는지 궁금합니다.
기존엔 발생안했는데 갑자기 간혹 해당 에러가 발생을 하고 있습니다.

확인 부탁드리겠습니다.
감사합니다.

**Comment by naver-searchad** [comment]
이미 말씀드린 것처럼, **원인을 파악해드릴 수 있는 방법이 없습니다.**

문의주신 요청 메시지에 포함된 `X-API-KEY` 헤더에 해당하는 `SECRET-KEY`와 `1576719320133.GET./billing/bizmoney` 로 서명 값을
직접 생성해서 `uAymub+ ... +zGikiFxtY=` 와 같은 값이 나와야합니다.

`T2kZ2axjJo/SBSs41bYnbNP8903yHYIhtnW9a1TwrqI=`는 정상적인 서명 값이 아닙니다.

간혹 발생하는 문제일 경우 작성하신 로직이 thread-safe 하지 않은 경우가 많습니다.
**서명 생성 로직을 직접 수행해서 안내드린 값이 나오는지부터 확인**하시기 바랍니다.
