### ISSUE TITLE
계정관련 질문입니다.

### ISSUE THREAD

**Issue by SteveKim7878** [naver/searchad-apidoc#328]
Account API를 통해서 하위 계정들을 가져오려고 하는데 {"status":403,"title":"You don't have permission to access on this server (resource)."} 이러한 메시지가 나옵니다. 계정내에 별다른 작업을 하진 않았다고 하는데 어떤 이유에서 해당 메시지가 발생하는지 궁금합니다.

X-Transaction-ID:BF3G52KEPHHTL

그럼 확인 부탁드리겠습니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

customer-links는 '본인' 계정의 권한 목록을 가져올 때만 사용됩니다.
즉 api-key와 X-Customer가 동일해야 합니다.
특정 관리대상 광고주의 권한목록을 대행계정 권한으로 조회할 수는 없기 때문입니다.

**Comment by naver-searchad** [comment]
참고로 api-key와 X-Customer가 같다는 의미는 api-key 소유 계정의 customer id와 동일해야 한다는 의미입니다.

**Comment by SteveKim7878** [comment]
넵 감사합니다.

**Comment by SteveKim7878** [comment]
그런데 궁금한 부분은 동일한 api-key와 customer-id로 잔액을 조회했을떄는 잔액이 조회가 되는데
그럼 api-key와 customer-id가 잘못된 것이 아닌것 아닌가요?

**Comment by naver-searchad** [comment]
@SteveKim7878 
광고관리 대상 광고주의 잔액을 조회하는 것은 광고관리 권한 범주에 속하기 때문에 가능합니다.
만약 customer-links에 광고관리 대상 광고주의 customer id 입력이 가능하다면
해당 광고주가 권한을 맡긴 다른 대행 계정들(api를 사용하는 대행 계정과는 무관한)
목록을 볼 수 있다는 의미가 되어 이는 보안정책상 위배가 됩니다.
