### ISSUE TITLE
MasterReport 문의 입니다.

### ISSUE THREAD

**Issue by Sene68** [naver/searchad-apidoc#329]
delta master-report ShoppingProduct 을 fromDate = 2019-12-31 설정하여 호출 하였습니다.
결과 tsv에서 31일에 등록한 소재가 없는데 이전에 삭제되지않은 소재들이 전부 나타났습니다.
하지만, Adgroup에 대해선 동일한 조건으로 status = NONE을 리턴해주는것을 확인했습니다.
저는 delta master-report에 fromDate 값을 입력 하였을때 입력한 일자부터
모든 상태의 소재가 나타나는것으로 이해하고 Adgroup과 ShoppingProduct에 대해 
하루 한 번 fromDate를 전 일로 호출하고 추가된 데이터를 처리하도록 개발하였습니다.
어떤 부분을 잘못 이해한걸까요?

**Comment by naver-searchad** [comment]
안녕하세요. 검색광고API입니다.
Job ID를 남겨주시면 확인 후 답변 드리도록 하겠습니다.

**Comment by Sene68** [comment]
안녕하세요. 두개의 계정에서 진행했습니다.
ID : E088C38AB309B6361DA80FC9ECBDA6CE
ID : EF7118CF83597F987468669548D81080

**Comment by naver-searchad** [comment]
마스터리포트 요청시  fromTime에 시간을 설정하시면, fromTime 이 후에 변경된 항목이 있을 경우 해당 정보를 반환하게 됩니다.
삭제를 포함해 등록/수정이 있을 경우 모두 제공이 됩니다.
요청하신 보고서의 경우 다수의 소재가 연동상태가 변경되어서 해당 정보가 반환되었습니다.
참고로 fromTIme을 입력하지 않으시면, 요청 시간 기준으로 삭제된 정보를 제외한 모든 데이타를 받으실 수 있습니다.
