### ISSUE TITLE
Java 샘플 문의

### ISSUE THREAD

**Issue by FreeEgo** [naver/searchad-apidoc#33]
![image](https://cloud.githubusercontent.com/assets/24306471/22004129/9665c4c4-dc9c-11e6-940d-5251d4f872d7.png)

샘플을 받아 maven 프로젝트로 추가하였더니
메소드를 찾을수 없다던지, 초기화에 실패했다는 등의 오류가 많습니다.

샘플을 설치하는 다른 방법이 있나요?

**Comment by naver-searchad** [comment]
lombok 설치가 필요합니다.

https://projectlombok.org/download.html
