### ISSUE TITLE
키워드 입찰가 업데이트 시 useGroupBidAmt : true 일 경우

### ISSUE THREAD

**Issue by lachelngose** [naver/searchad-apidoc#330]
키워드 입찰가를 그룹 기본 입찰가로 사용하도록 업데이트 하는 Api에서,
useGroupBidAmt 와 bidAmt 값을 둘 다 보내는데
response 로 돌아오는 객체에는 useGroupBidAmt 만 true 로 업데이트되어있고 bidAmt 는 그룹 입찰가 적용 직전 키워드에 설정되어있던 입찰가가 그대로 돌아옵니다.

그룹 입찰가 적용 시 키워드에 원래 설정했던 입찰가를 사용하는 곳이 있나요?
키워드 입찰가를 그룹 입찰가로 같이 업데이트할 수 없는지 궁금합니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

해당 내용은 키워드 입찰가 관련해서 의도된 정상 스펙입니다.

우선, 기본입찰가를 사용하도록 설정하는 Action에서 동시에 키워드의 개별입찰가를 업데이트 하는 것은 자연스럽지 못합니다.
개별 키워드 입찰가 필드가 그룹의 기본입찰가와 연동되어야 한다면,
기본입찰가를 변경하는 시점에도 모든 키워드의 입찰가 필드도 갱신되어야 하기 때문입니다.
물론 연동은 별개의 문제고 명시적인 키워드 업데이트만 돼도 된다고 생각하실 수 있겠지만
그렇게 되면 전체적인 광고주 또는 API 유저 간 커뮤니케이션에서 혼동의 여지를 품게 됩니다.

따라서 기본입찰가를 사용하는 키워드들의 입찰가를 조회하기 위해서는 반드시 해당 광고그룹을 함께 조회하셔야 합니다.
