### ISSUE TITLE
파워링크 키워드 1~5위 입찰가 확인 방법

### ISSUE THREAD

**Issue by teamusit** [naver/searchad-apidoc#331]
안녕하세요.

파워링크 키워드별 1~5위 입찰가를 확인하려면 어떤 api를 사용해야 할까요?

average position bid, median bid, exposure minimum bid 등은 확인했는데요.

광고에서 키워드의 입찰가를 1위 평균 입찰가, 2위 평균 입찰가 등으로 선택할 수 있고, 이때 각 랭크의 입찰가를 한번에 확인할 수 있는 방법이 없을까요?

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

다음의 공식문서 내용 상의 api만 지원되고 있습니다.
http://naver.github.io/searchad-apidoc/#/tags/Estimate
이미 살펴 보셨겠지만 랭크 구간을 한번에 조회할 수 있는 api는 현재 없습니다.
