### ISSUE TITLE
네이버쇼핑 검색어 별 남/여비율 및 연령대 비율 관련 문의

### ISSUE THREAD

**Issue by hadxit75** [naver/searchad-apidoc#332]
안녕하세요 keywordstool을 이용해서 검색어 별 PC , Mobile 기간별 검색량은 알수 있었는데요
해당 키워드에 남/여 비율 및 연령대비율도 같이 보고 싶어서 이곳저곳 찾아봐도 찾지를 못해서요
관련해서 볼수 있는 API가 있을까요~

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

해당 데이터는 아쉽게도 검색광고 API로 제공해 드리고 있지 않습니다.
상세한 추가 도움말은 아래 FAQ를 참조해 주시기 바랍니다.
https://github.com/naver/searchad-apidoc/wiki/FAQ-stat#q-%EC%97%B0%EA%B0%84-%ED%82%A4%EC%9B%8C%EB%93%9C-%EA%B2%80%EC%83%89%EC%88%98-%EC%B6%94%EC%9D%B4-api-%EC%A0%9C%EA%B3%B5%EC%97%AC%EB%B6%80
