### ISSUE TITLE
[Python] 캠페인 생성 권한 오류

### ISSUE THREAD

**Issue by sion8310** [naver/searchad-apidoc#333]
안녕하세요, 네이버 검색광고 캠페인을 API를 통해 생성을 하고자 하는데, 계속 권한 오류가 떠서 이렇게 문의드립니다.

method = 'POST'
uri = '/ncc/campaigns'

r = requests.post(BASE_URL + uri, json = {'campaignTp' : 'WEB_SITE', 'name' : 'TEST#' + str(1)},
                  headers=get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID))

print("response status_code = {}".format(r.status_code))
print("response body = {}".format(r.json()))

다음과 같은 코드를 사용하였고, 이에 대한 Response 값은 이렇습니다.
response status_code = 404
response body = {'code': 1018, 'status': 404, 'title': 'No permission to access the resource.'}

Adgroup은 생성이 잘 되는데, 이상하게 캠페인만 생성이 계속 안되네요. 네이버 검색광고 광고주 권한 계정으로 진행하고 있기 때문에, 일반적인 권한 부여 문제는 아닌 것 같습니다.

혹시 현재 Naver 검색광고 API를 통해 캠페인 생성은 제한 되어 있는 것 인가요?
실제로 API Version Specific Features Comparison 페이지를 확인해보니, 캠페인 생성에 대한 내용을 찾을 수 없더군요.

위에 대한 답변을 해주시면 정말 감사하겠습니다.

**Comment by sion8310** [comment]
추가로, Keyword 생성도 동일한 에러를 받고 있습니다.

제가 놓치고 있는 게 뭔지 궁금하네요...ㅠㅠ 답변해주시면 감사하겠습니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

캠페인 생성 api 문서 링크는 다음과 같습니다.
http://naver.github.io/searchad-apidoc/#/operations/POST/~2Fncc~2Fcampaigns

올려주신 코드 내용만 보면 문제가 없어 보이긴 합니다.
하지만 에러 내용을 보면 POST가 아닌 GET mothod가 호출된 것처럼 보입니다.
상세한 건 transacion id 정보를 남겨 주셔야 확인이 가능할 것 같습니다.
response header 포함 전체 내용도 첨부해 주실 수 있으실까요?

**Comment by sion8310** [comment]
response content = {'Expires': 'Thu, 01 Jan 1970 00:00:00 GMT', 'Connection': 'close', 'Cache-Control': 'no-store, must-revalidate', 'X-Transaction-ID': 'BFJK97JTPDG9F', 'Content-Type': 'application/json;charset=UTF-8', 'Date': 'Mon, 13 Jan 2020 04:03:51 GMT', 'Strict-Transport-Security': 'max-age=15768000'}

라고 나옵니다.

**Comment by sion8310** [comment]
조금 헷갈리는건, 비슷한 포맷으로 Adgroup / Keyword를 새롭게 생성하는 작업은 문제 없이 돌아갑니다.

**Comment by sion8310** [comment]
response header = {'Expires': 'Thu, 01 Jan 1970 00:00:00 GMT', 'Connection': 'close', 'Cache-Control': 'no-store, must-revalidate', 'X-Transaction-ID': 'BFJKE9PN99J07', 'Content-Type': 'application/json;charset=UTF-8', 'Date': 'Mon, 13 Jan 2020 04:14:55 GMT', 'Strict-Transport-Security': 'max-age=15768000'}

**X-Transaction ID - BFJKE9PN99J07**

**Comment by sion8310** [comment]
참고로 같은 계정 정보로 adgroup과 keyword들은 잘 생성이 됩니다.

**Comment by naver-searchad** [comment]
@sion8310 
안녕하세요? 네이버 검색광고 API  입니다.

캠페인 생성시 발생하는 1018오류는 `customerId`값이 없을 경우 발생하는 오류입니다.

감사합니다.

**Comment by sion8310** [comment]
> @sion8310
> 안녕하세요? 네이버 검색광고 API 입니다.
> 
> 캠페인 생성시 발생하는 1018오류는 `customerId`값이 없을 경우 발생하는 오류입니다.
> 
> 감사합니다.

제가 프로그래밍 지식이 부족해서 그런 것 같은데, 분명히 코드상에는 customerId값을 잘 넘겨주는데, customerId값이 없을 수도 있을까요?

그리고, 비슷한 코드 & 같은 계정정보로는 광고그룹 및 키워드 생성에는 전혀 문제가 없습니다. 보다 구체적인 답변 주시면 정말 감사하겠습니다.

**Comment by naver-searchad** [comment]
@sion8310 
campaignTp, name을 넣은 json에 customerId 를 추가해서 전송해 보시면 되실 겁니다.
(참고로 campaign create api 문서에는 해당 설명이 누락돼 있어 추후 보완하도록 하겠습니다)
