### ISSUE TITLE
RelKwdStat: list 관련 질문 드립니다.

### ISSUE THREAD

**Issue by jklee0219** [naver/searchad-apidoc#334]
monthlyPcQcCnt <-- 최근30일이라고 나와있는데 조회한날짜의 어제까지의 데이터인가요? 정확하게 30일이 언제부터 언제인지 궁금합니다

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

최근30일이면 말 그대로 전일자까지의 지표를 말함입니다.
단, 통상적으로 전일 데이터지표 작업에 소요되는 시간이 있으므로
조회 시점에 따라, 가령 자정을 갓 넘긴 시간일 경우 전일자 기준은 전전일이 될 수도 있습니다.
따라서 '정확히'라는 표현은 통상적인 기준이라고 생각하시면 좋을 것 같습니다.

**Comment by jklee0219** [comment]
그럼 23시정도에 데이터를 조회하는경우 무조건 전일까지의 데이터라고 봐도 무방하겠네요?

**Comment by naver-searchad** [comment]
@jklee0219 
네. 특별한 장애가 지속되지 않는 한 그렇겠네요.
