### ISSUE TITLE
stat api read timeout 문의

### ISSUE THREAD

**Issue by mz-myc** [naver/searchad-apidoc#337]
안녕하세요 

stat api 호출 시 간헐적으로 read time out error 가 발생하고있어 문의드립니다. 
<img width="1021" alt="스크린샷 2020-01-22 18 04 26" src="https://user-images.githubusercontent.com/16996715/72880171-b1993d80-3d41-11ea-8e59-656acb093196.png">

NaverStat.DatePreset.yesterday, NaverStat.Breakdown.hh24
파라미터는 이렇게 주고 매일 오전 6시 호출하고있습니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

해당 시간대에 stat 시스템 쪽에서 오류가 발생했던 것으로 확인되었습니다.
일시적인 오류로 이후 다른 문제는 리포트 되고 있지 않습니다.
