### ISSUE TITLE
Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by ezuev44** [naver/searchad-apidoc#338]
Why an error may appear  "Could not create SSL/TLS secure channel."?
```
ERROR Transport or Format error in Naver searchad status Error query Method: GET, Resource: /ncc/ads, Body: , UrlParameters: , Parameters: nccAdgroupId=grp-a001-01-000000012056609 response 
  WebException*The request was aborted: Could not create SSL/TLS secure channel.*   at System.Net.HttpWebRequest.GetResponse()
   at RestSharp.Http.GetRawResponse(HttpWebRequest request)
   at RestSharp.Http.GetResponse(HttpWebRequest request)
```

**Comment by ezuev44** [comment]
I tried to use `System.Net.ServicePointManager.SecurityProtocol = System.Net.SecurityProtocolType.Tls | System.Net.SecurityProtocolType.Ssl3 | System.Net.SecurityProtocolType.Tls12;` 
but it did not help

**Comment by naver-searchad** [comment]
Hello, this is Naver SearchAd.

`Could not create SSL/TLS secure channel`
is not an our API level response.
Try use security protocol TLS 1.2,
or you can search the solutions on the online site like stackoverflow.
