### ISSUE TITLE
Ad 에서 statusReason 응답에 문제가 있습니다.

### ISSUE THREAD

**Issue by youngbw8** [naver/searchad-apidoc#339]
캠페인을 on 하고 
해당 캠페인의 광고그룹을 on 하고
소재를 off 하고 해당 ad의 statusReason 을 보면 정상적으로 AD_PAUSED 가 출력됩니다

그런데

캠페인을 off 하고 
해당 캠페인의 광고그룹을 on 하고
소재를 on 하고 해당 ad의 statusReason 을 보면 
CAMPAIGN_PAUSED이 출력될걸로 예상했는데 ELIGIBLE이 출력됩니다

즉, 상위 그룹, 캠페인들의 userLock의 상태와 상관없이 
소재의 statusReason 만 출력되는것 같은데요

statusReason 의 item들중에는

CAMPAIGN_PAUSED
GROUP_PAUSED

이런 타입들이 있는데 
왜 statusReason에 
상위 그룹,캠페인의 userLock의 상태를 반영 하지 않는걸까요?

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API 입니다.
소재, 키워드, 확장 소재의 경우 자신의 상태값만 계산 되고 있습니다.
상태 계산에 대한 자세한 내용은  [FAQ](https://github.com/naver/searchad-apidoc/wiki/FAQ#q-각-항목의-상태와-상태이유-계산-방식은-어떻게-되나요) 내용을 참고해주세요.

감사합니다.
