### ISSUE TITLE
Ad - update 기능 문의 드립니다.

### ISSUE THREAD

**Issue by chosonik** [naver/searchad-apidoc#34]
쇼핑검색광고 입찰가 업데이트를 하려고 하는데요,

$data = array(
	"adAttr" => array(
		"bidAmt" => 200
		,"useGroupBidAmt" => true
	)
	,"nccAdId" => $nccAdId
	,"userLock" => 0
	);
		
$api->PUT('/ncc/ads/' . $nccAdId, $data, array("fields" => "userLock"));

이렇게 작성했는데, userLock의 상태 값은 반영되나, bidAmt의 값이 반영되지 않습니다.
작성된 전달 형태가 잘 못 된건지 알 수가 없습니다. 답변 부탁드립니다.

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

$api->PUT('/ncc/ads/' . $nccAdId, $data, array("fields" => "adAttr"));

위와 같이 요청 하시면 입찰가를 변경 하실 수 있습니다. 

감사합니다.

**Comment by chosonik** [comment]
답변 감사드립니다.

이전에 알려주신대로 해봤으나,

Http Status : 500 Transaction-ID : APN6S6G21P9FO
Array
(
    [code] => 1005
    [status] => 500
    [title] => Cannot handle the request.
)

이렇게 오류가 발생하였습니다. ㅠㅠ

**Comment by naver-searchad** [comment]
요청파라미터에 type이 없어서 발생하는 오류입니다.
"type" => "SHOPPING_PRODUCT_AD"
추가후에 재확인 부탁드립니다.
감사합니다.

**Comment by chosonik** [comment]
감사합니다.
해결하였습니다. ^^
