### ISSUE TITLE
AdExtension Create에서 POWER_LINK_IMAGE 관련 문의

### ISSUE THREAD

**Issue by InhoChoi** [naver/searchad-apidoc#340]
안녕하세요
API를 사용해서 AdExtension을 사용해서 Power Link Image에 대한 속성값을 추가하여 AdExtension을 추가를 할려고 합니다.
https://naver.github.io/searchad-apidoc/#/operations/POST/~2Fncc~2Fad-extensions

1. AdExtension Create의 Reuqest에는 adExtension 라는 Property가 존재를 하지 않는데, Power Link Image Type의 AdExtension을 추가하기 위해 관련된 정보를 입력하기 위해 Property인 adExtension를 추가해서 사용을 할수 있나요?

2. 만약 위에 create api를 통해 Power Link Image Type의 adExtension을 생성이 가능하다면, POWER_LINK_IMAGE에 대한 샘플 값으로 아래와 같이 나와있는데
```
{
  "imagePath" : "/MjAxNzExMjJfMTEw/MDAxNTExMzM5NzYwODk1.QnHcPp6mAr3I-Kkx18IjxoWIAJNrvTgx7NTqXQTfd9kg.Y6csE9Q37Wph49njzVczrmjJWxSkpRPXehxDxpBvlw4g.PNG/mong1.PNG"
}
```
외부 주소 (ex : CDN Image 등)을 사용할수 있을까요?

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

이미지 링크는 광고주시스템 웹상에서 등록되는 내부 관리대상이므로 임의의 링크를 통해서는 등록할 수 없습니다.

**Comment by InhoChoi** [comment]
넵 답변 감사합니다
