### ISSUE TITLE
Adgroup: update 혹은 Adgroup: update (by fields) 활용한 기존 광고그룹 이름 변경

### ISSUE THREAD

**Issue by nyob3** [naver/searchad-apidoc#342]
안녕하세요.

기존 업로드 되어 있는 광고그룹의 이름을 API를 통해 bulk로 새 이름으로 업데이트 하고자 하는데요.

안내되어 있는 공식문서에서는 기존의 이름 자체가 일종의 key 역할을 하는 것 같아서 이 이름을 변경하는 것이 가능한 건지 확실치 않아 issue 글 남겨봅니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

광고그룹의 이름(name) 변경은 별도 by fields로는 지원하지 않고 전체 update(put)시 함께 수정해 주시면 됩니다.
그리고 name은 조회용 데이터 외의 어떤 key 역할도 하지 않습니다.

**Comment by nyob3** [comment]
안녕하세요.

빠른 답변 감사드립니다!

key 관련해서는 제가 문서를 잘못 이해한 것 같습니다.

광고그룹 이름만을 변경 목적으로 update method 사용 시 paramerter를 {'name': '새로운 광고그룹 이름'} 과 같이 구성하여 전달하면 되는 건가요?

아니면 [해당 문서](http://naver.github.io/searchad-apidoc/#/operations/PUT/~2Fncc~2Fadgroups~2F%7BadgroupId%7D)에 따르면 bidAmt와 같은 몇몇 parameter들이 Required로 안내가 되어 있습니다. 

이때 이 parameter들도 함께 포함하여 구성하여야 하는지 아니면 이 parameter들에 대해서 update 해야 할 내용이 없다면 굳이 포함시키지 않고 'name' 으로만 parameter를 구성하여 전달해도 괜찮을까요?

**Comment by naver-searchad** [comment]
@nyob3 
전체를 update하는 api이므로 변경되지 않는 필드들도 모두 현재 value로 포함이 되어 있어야 합니다.
먼저 해당 adgroup 을 get한 뒤 그대로 name 필드만 수정하셔서 다시 put 하시면 됩니다.

**Comment by nyob3** [comment]
감사합니다!

코드 작성 후 또 문의사항이 생기면 문의 드리겠습니다. :)

좋은 하루 보내세요!
