### ISSUE TITLE
[Estimate]_get (average position bid) 관련 문의

### ISSUE THREAD

**Issue by JDCha** [naver/searchad-apidoc#343]
키워드별 1순위 비드가를 확인하기 위해 다수의 키워드(약 90만개)를 조회하였습니다. 조회중 아래와 같은 메시지가와 함께 에러가 발생했습니다.

혹시 조회가능한 키워드 수가 정해져 있는지 아님 네트워크 용량의 문제인지 확인부탁드립니다.

MaxRetryError: HTTPSConnectionPool(host='api.naver.com', port=443): Max retries exceeded with url: /estimate/average-position-bid/keyword (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x11c4827d0>: Failed to establish a new connection: [Errno 50] Network is down'))

During handling of the above exception, another exception occurred:

감사합니다

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

올려주신 메시지는 요청하시는 서버에서 발생한 내용으로 보입니다.
네이버 검색광고 API 서버에서 트래픽 콘트롤에 제한되었을 경우에는
http status 429로 응답됩니다.
