### ISSUE TITLE
MasterReport Label, LabelRef Specification 

### ISSUE THREAD

**Issue by nanpuhaha** [naver/searchad-apidoc#344]
MasterReport Label, LabelRef Specification 

**Label과 LabelRef MasterReport의 API 스펙 문서를 업데이트해주시기 바랍니다.**
[Master Report Specification](https://gist.github.com/naver-searchad/186ca42e1e8596b0e3dcf74e3a86c04f)와
[Naver Search Ad API - MasterReport - overview](http://naver.github.io/searchad-apidoc/#/tags/MasterReport) 문서를 보면 Label과 LabelRef이 5개의 필드가 있다고 적혀있습니다.
하지만, 실제로 다운로드한 tsv 파일의 경우 6개로 1개가 더 많습니다.
아마 deleteTm으로 추정되지만, 정확히 확인해주시길 요청드립니다.

**API를 업데이트하시면, API 스펙도 좀 같이 업데이트해주시기 바랍니다.**
지난번 #294 에서도 그렇고, API만 업데이트하고 스펙을 업데이트하지 않으면 이용하기 정말 불편합니다.

**MasterReport 첫번째 행에 필드명을 추가해주시기 바랍니다.**
사용자 입장에서 API 스펙에 변경이 생겼는지 또는 API 스펙 문서대로 개발했는지 API 스펙 문서가 업데이트가 안되었는지를 체크할 수 있는 수단이 없습니다...

---

[Favorite(Label)](https://gist.github.com/naver-searchad/186ca42e1e8596b0e3dcf74e3a86c04f#favoritelabel)
No | Field Name | Value | Max.Length | Description
-- | -- | -- | -- | --
1 | Customer ID | int |   | Customer ID
2 | Label ID | string | 31 | Label ID(key Value)
3 | Label name | string | 256 | Label name
4 | regTm | date |   | The time at which information was created(ISO8601)
5 | updateTm | date |   | The time at which information was updated(ISO8601)

[Favorite Item (LabelRef)](https://gist.github.com/naver-searchad/186ca42e1e8596b0e3dcf74e3a86c04f#favorite-item-labelref)
No | Field Name | Value | Max.Length | Description
-- | -- | -- | -- | --
1 | Customer ID | int |   | Customer ID
2 | Label ID | string | 31 | Label ID(key Value)
3 | Reference ID | string | 31 | Reference Key Value(Ad group ID, Ad ID, Ad Keyword ID)
4 | regTm | date |   | The time at which information was created(ISO8601)
5 | updateTm | date |   | The time at which information was updated(ISO8601)

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

상세한 내용 리포토해 주셔서 감사합니다.
빠른 시일 내에 확인 후 조치하도록 진행하겠습니다.

**Comment by naver-searchad** [comment]
@nanpuhaha 
리포트 행의 마지막에 불필요한 탭이 하나 더 추가돼 있는 것으로 확인되었습니다.
따라서 API 문서 내용에 대한 업데이트는 필요치 않고
탭을 제거하는 작업이 의뢰되어 진행될 예정입니다.
감사합니다.

**Comment by nanpuhaha** [comment]
@naver-searchad 네, 알겠습니다.
그럼 불필요한 탭(TAB) 하나를 제거하는 작업이 완료되면 코멘트로 알려주시고 이슈를 닫아주시기 바랍니다.
감사합니다.

**Comment by naver-searchad** [comment]
@nanpuhaha 
어제 저녁 기준으로 배포 되었습니다.
