### ISSUE TITLE
GET Summary Report per multiple entities의 sample.py

### ISSUE THREAD

**Issue by JDCha** [naver/searchad-apidoc#345]
안녕하세요 
공유해주신 샘플을 활용하여 작업진행 중 아래와 같은 메시지가 나옵니다.
어떤 문제인지 확인좀 부탁드립니다.

NameError                                 Traceback (most recent call last)
<ipython-input-4-88295f017c5a> in <module>
----> 1 stat_ids = [target_adgroup['cmp-a001-01-000000002655650'], target_adgroup['grp-a001-01-000000014032522']]
      2 r = requests.get(BASE_URL + uri, params={'ids': stat_ids, 'fields': '["clkCnt","impCnt","salesAmt", "ctr", "cpc", "avgRnk", "ccnt"]', 'timeRange': '{"since":"2020-02-04","until":"2020-02-04"}'}, headers=get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID))
      3 
      4 print("response status_code = {}".format(r.status_code))
      5 print("response body = {}".format(r.json()))

NameError: name 'target_adgroup' is not defined

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

먼저 참고로, 개발 코드 상의 오류에 대해서는 답변을 드리지 않습니다.

`target_adgroup' is not defined`
ids 파라미터에는 그냥 `['cmp-a001-01-000000002655650', 'grp-a001-01-000000014032522']`
이런식으로 id만 넣으면 되겠습니다.
그리고 캠페인 혹은 광고그룹 id를 섞어서 사용하지 마시고 한가지 종류로 요청하시기 바랍니다.
