### ISSUE TITLE
Performance 예측값과 실제값의 차이에 대하여 문의드립니다.

### ISSUE THREAD

**Issue by dobal-production** [naver/searchad-apidoc#347]
안녕하세요.

Estimate의 performance api를 테스트하고 있습니다.
저희가 사용중인 키워드를 가지고 테스트를 해보니, estimate 결과와 실제 결과에 많은 차이가 있었습니다.
문의 드릴 것은 세 가지 입니다.

1. 차이의 원인이 무언인지 알 수 있을런지요?
   예는 아래의 "테스트 결과" 참조부탁드립니다.

2. device의 입력에 따라 estimate 결과가 달라지는데, PC, MOBILE, BOTH가 어떤 영향을 미치는지 잘이해되지 않습니다.
   MOBILE로 지정하면, 해당 키워드의 과거 실적 데이터 중 MOBILE 실적 데이터만 사용되는 것인지요?

3. exposure-minimum-bid에 사용되는 데이터가 갱신되는 시각을 알 수 있을까요? 
   실적 데이터의 SLA는 오전 7시로 알고 있습니다. 
   exposure-minimum-bid에 사용되는 데이터의 갱신 시각도 마찬가지 일런지요?

감사합니다.

### 테스트 결과
1. 실제 결과는 전주 금요일부터(포함) 과거 28일간 데이터입니다.
2. 테이블 헤더 값은 아래와 같습니다.
n-impression : estimated impression
n-click : estimated click
n-cost : estimated cost
impression : real impression
click : real click

keyword | bid | device | keywordplus | n-impression | n-click | n-cost | impression | click
---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ----
아이폰아이섀도우 | 180 | MOBILE | false | 244 | 0 | 0 | 1757 | 303 
해피콜바삭튀김기 | 100 | MOBILE | false | 0 | 0 | 0 | 422 | 127
삼성비스포크냉장고 | 390 | MOBILE | false | 4904 | 0 | 0 | 16255 | 120

**Comment by naver-searchad** [comment]
안녕하세요. 검색광고API입니다.
1.
 키워드별로 충분한 표본이 모이지 않았거나, 해당 표본이 패턴을 형성하지 않을 경우 데이타가 제공되지 않습니다. 

2.
Device는 견적 데이타를 사용할 노출 영역을 나타내며, `PC`는 데스크탑 환경, `MOBILE`은 모바일 환경 데이타를 의미합니다. `BOTH`는 PC와 MOBILE 데이타의 합을 의미합니다.

3. 
정확한 시간을 알려드리기는 어렵습니다. 최대한 오전에 완료될 수 있도록 작업하고 있습니다.
참고로 최근 한달간의 평균 완료시간은 06시경이었습니다.
