### ISSUE TITLE
특정 시점 MasterReport형태의 data를 받아오는 것이 가능한지 문의

### ISSUE THREAD

**Issue by githubcnsbs** [naver/searchad-apidoc#348]
안녕하세요.

 특정 시점의 masterReport형태의 data를 받아온 뒤 이후의 변경사항을 받아오는 방법이 있는지 문의드립니다.

예) 
 1. 2019-12-31일자의 Keyword 목록을 모두 받아오고
 2. 2019-12-31일 이후의 변경사항을 받아오는 방법

 2번은 MasterReport의 fromTime을 이용하면 될 것으로 보이나, 
 1번과 같이 현재 시점(2020-02-05일)에서 2019-12-31일자의 Keyword 목록을 모두 받을 수 있는 방법이 있는지 문의드립니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요. 검색광고API입니다.
요청에 `fromTime` 이 없으면, 현재 시점으로 삭제되지 않은 모든 정보를 제공합니다.
`fromTIme`이 있으면, 이 시간부터 최근 시점까지 변경 및 삭제된 정보들을 제공합니다. 
응답의 `updateTime`  시간이 변경분을 수집한 종료시점 입니다. 
이 시간을 다음 요청의 `fromTime`으로 사용하신다면, 주기적으로 변경분을 누락없이 수집하실 수 있게 됩니다.

**Comment by githubcnsbs** [comment]
네, 현재 시점으로 fromtime없이 한번 받아 전체를 가지고, 미래의 어느시점에 fromtime으로 delta를 받아오는 것은 이해하였습니다.

과거 특정시점 (2019.12.31)의 Keyword set을 fromtime이 없이 받는 것처럼 받아올 수 있는지 문의 드립니다.

**Comment by githubcnsbs** [comment]
> 네, 현재 시점으로 fromtime없이 한번 받아 전체를 가지고, 미래의 어느시점에 fromtime으로 delta를 받아오는 것은 이해하였습니다.
> 
> 과거 특정시점 (2019.12.31)의 Keyword set을 fromtime이 없이 받는 것처럼 받아올 수 있는지 문의 드립니다.
> 

위 Comment 추가 문의 답변 부탁드립니다.

**Comment by naver-searchad** [comment]
@githubcnsbs 
특정 시점 기준의 snapshot 데이터를 지원하지는 않습니다.
감사합니다.

**Comment by githubcnsbs** [comment]
네, 감사합니다.
