### ISSUE TITLE
MasterReport/ StatReport API 사용시 광고시스템 메뉴 문의

### ISSUE THREAD

**Issue by githubcnsbs** [naver/searchad-apidoc#349]
안녕하세요.

 MasterReport / StatReport API 사용시, 제가 create로 등록한 report가 광고시스템상 메뉴에서 볼 수 있는지 문의 드립니다.
 광고시스템 메뉴상에서 표시가 된다면 어느 메뉴에 표시가 되는것인지 알려주시면 감사하겠습니다.

예 ) 
 MasterReport:  Naver광고 > 보고서 > 대용량다운로드 보고서 > 대용량다운로드보고서 탭
 StatReport: ???

와 같은 형태로 알려주시면 감사하겠습니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

MasterReport: `보고서 > 대용량 다운로드 보고서 > [탭] 광고 정보 일괄 다운로드`
StatReport: `보고서 > 대용량 다운로드 보고서 > [탭] 대용량 보고서 다운로드` 
입니다.

**Comment by githubcnsbs** [comment]
감사합니다.
