### ISSUE TITLE
adkeyword update 어떻게 금액 변경하는질 모르겠습니다.

### ISSUE THREAD

**Issue by kangkyoungsup** [naver/searchad-apidoc#35]
$fields=array(
 'bidAmt' => '600' ,
 'userLock' => '0'
 'link' => 'aaa',
);
$adkeywordlist = $api->PUT('/ncc/keywords/'."nkw-m01-01-000002110265563",$fields);

위와 같이 여려 배열 변수를 바꿔가면서 하는데 영 안되네요..

아랜 결과값입니다.

sign = 1485917035769.PUT./ncc/keywords/nkw-m001-01-000002110265563
Http Status : 400
Transaction-ID : APUU7BH1HPG9Q
----------
Array
(
    [title] => Bad Request
    [status] => 400
    [detail] => Parameter conditions "fields" not met for actual request parameters: 
)

fields 항목을 어떻게 작성해야는지 알려주시면 대단히 감사해 할께요^^

**Comment by naver-searchad** [comment]
PUT /ncc/keywords/nkw-m01-01-000002110265563?fields=bidAmt

body에 들어가는 json은 get으로 조회한 데이터에서 원하는 값만 변경합니다.
**request body**
```javascript
{
//... adkeyword 다른 property들 ... 
bitAmt:600
}
```
이런식으로 처리하시면 됩니다.

**Comment by kangkyoungsup** [comment]
헉 전혀 모르겠다는...ㅠㅠ

경력 단절이 몇년 되다보니 json 공부를 못했네요...

예제 소스하나만 주세요.. ... 공개가 힘들면 mudori@gmail.com 으로 보녀주셔도 되구요...

네이버에 광고비 어마어마 지불하는 업체입니다.

**Comment by naver-searchad** [comment]
안녕하세요~

예제 소스는 아래 링크들을 참고해 주시면 됩니다.

PHP 코드에는 bidAmt항목을 수정 할 수 있게 되어 있지는 않은데요~ 위의 JSON이나 혹은 JAVA코드를 참고 하셔서 작성해 주시면 됩니다.

JAVA
https://github.com/naver/searchad-apidoc/blob/c09d783ad913115de9ae0457fa8965f68f2a345b/java-sample/src/main/java/com/naver/searchad/api/sample/AdManagementSample.java#L238

PHP
https://github.com/naver/searchad-apidoc/blob/master/php-sample/ad_management_sample.php#L70

**Comment by kangkyoungsup** [comment]
예제소스 어마 보긴했는뎅.. ㅠㅠ 알아서 해볼께요.

**Comment by naver-searchad** [comment]
제일 상단에 적어주신 내용을 바탕으로 동작 가능하게 작성해 보면 아래와 같습니다.
또 nccAdgroupId와 nccKeywordId는 항상 요구되는 값입니다. (ref. [API문서](http://naver.github.io/searchad-apidoc/#/operations/PUT/~2Fncc~2Fkeywords~2F%7BnccKeywordId%7D%7B%3Ffields%7D))

이 코멘트가 도움이 되셨으면 좋겠습니다.

```php
$nccKeyword=array(
    'bidAmt' => '600',
    'useGroupBidAmt' => false,
    'nccAdgroupId' => '{{해당 키워드가 속한 그룹의 ID}}',
    'nccKeywordId' => 'nkw-m01-01-000002110265563'
);
$adkeywordlist = $api->PUT('/ncc/keywords/'."nkw-m01-01-000002110265563", $nccKeyword, array("fields" => "userLock"));
```

**Comment by kangkyoungsup** [comment]
앗.. 긴급 json 습득해서 해결했습니다..... 넘 넘 감사.... 덕분에 넘 넘 감사.... json이 이런거군요....

**Comment by madeul** [comment]
부럽습니다.. 무슨 말인지 모르는 1인
