### ISSUE TITLE
estimate 에서 NPC 와 NPLA 는 어떤의미인가요

### ISSUE THREAD

**Issue by bluesme519** [naver/searchad-apidoc#350]
안녕하세요

estimate 기능을 활용하고싶은데요. 
질문1. NPLA는 쇼핑광고 인것 같습니다. 맞나요?
질문2. 아무것도 안적힌건 검색광고로 생각되는데 NPC는 어떤걸까요?
질문3. 쇼핑광고 perfomance는 estimate에 없나요?

여담으로 말씀드리면 쇼핑광고에 대해서 예상 광고비용을 산출하고싶습니다. 뭐 정확한 값일수는 없겠지만, 상대적인 비교를 위한 지표로, average position bid 에 검색량 을 곱해볼까 라고 생각을 하고 있었는데, 아무래도 예를들어 "부대찌개" 같은 키워드는 레시피를 찾기위해서, 맛집을 찾기위해서 도 많이 찾는 키워드여서 검색량이 상품광고클릭율보다 현저히 높기도 하고 해서 지표가 될 수 없을 것 같아서요.
평균광고클릭율 이런거라도 알면 좋을텐데 뭔가좋은 방법이 있을까요? 검색광고의 경우 키워드마다 광고클릭율을 제공하는 걸로 알고 있습니다. relkeyword 에서요..
제가 원할만한 수치를 제공하는 api가 있을까요?

**Comment by naver-searchad** [comment]
안녕하세요. 검색광고API입니다.
1. NPLA는 Naver Product List Ads의 약자로 쇼핑광고가 맞습니다.
2. NPC는 Naver PowerContents 약자로 파워컨텐츠이고, 이해하신 바와 같이 prefix가 없으면, 파워링크입니다.
3. 현재 쇼핑광고에는 견적데이타를 제공하지 않고 있습니다. 예측모델 만들기에 어려움이 있어 아직까지는 제공하기 어려운상황입니다.
