### ISSUE TITLE
stat api read timeout 문의

### ISSUE THREAD

**Issue by mz-ycg** [naver/searchad-apidoc#351]
2020/02/07 오전 06시경에 생긴 오류 오류입니다. 
https://github.com/naver/searchad-apidoc/issues/337 이슈와 같은 이슈이며
커스터머 아이디 254542에서만 간헐적으로 발생합니다. 

이번에도 일시적 문제인지 확인 부탁드립니다.

`
500 Internal Server Error. X-Transaction-ID: null, Response Body: {"timestamp":1581022858739,"status":500,"error":"Internal Server Error","exception":"java.net.SocketTimeoutException","message":"Read timed out"}
`

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

2.7일 06시에 254542 customer에 대한 로그는 확인되지 않는다고 합니다.
대신 약 6:13~6:30분 내 로그는 확인이 되고 있구요.
6시 전후로 전반적인 timeout 현상도 없었다고 합니다.
