### ISSUE TITLE
쇼핑검색광고 제외키워드 update 질문드립니다

### ISSUE THREAD

**Issue by dd1233345** [naver/searchad-apidoc#352]
안녕하세요. 제외키워드 update 하려고 하는데 

**response status_code = 405
response body = {'title': 'Method Not Allowed', 'status': 405, 'detail': "Request method 'PUT' not supported"}**

와 같은 에러가 떠서 문의 드립니다. 제 코드는 아래와 같습니다. 

**uri = '/ncc/targets'
method = 'GET'**

**r = requests.get(BASE_URL + '/ncc/targets',params={'ownerId': 'grp-a001-02-000000011945531','types':'RESTRICT_KEYWORD_TARGET'},headers=get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID))**

**print("response status_code = {}".format(r.status_code))
print("response body = {}".format(r.json()))
retrieved_target = r.json()**

위 코드로 get 해서 제외키워드 목록을 받아왔습니다. 그 후에

**retrieved_target[0]['target'] = [ {'keyword': '광마우스'}, {'keyword': '무선광마우스'}]**

로 수정했습니다.
retrieved_target 뒤에 [0]을 붙인건 list형으로 답이 와서 이렇게 했습니다.

그 후에

**uri = '/ncc/targets'
method = 'PUT'**

**r = requests.put(BASE_URL + uri + '?tgt-a001-02-000000110358325',
    params=retrieved_target[0],
    headers=get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID))**

**print("response status_code = {}".format(r.status_code))
print("response body = {}".format(r.json()))
r.json()**

로 다시 수정요청을 보냈습니다.

결과는 맨 앞에 설명드렸던 것과 같이

**response status_code = 405
response body = {'title': 'Method Not Allowed', 'status': 405, 'detail': "Request method 'PUT' not supported"}**

이렇게 나왔습니다. 문제가 뭘까요...?

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

Target 변경시 Target ID값을 파라미터가 아닌 URL Path에 추가 하셔야 합니다.
`/ncc/targets?tgt-a001-02-000000110358325` => `/ncc/targets/tgt-a001-02-000000110358325` 로 변경 하셔야 합니다.

아래 API 문서를 참고하세요.
http://naver.github.io/searchad-apidoc/#/operations/PUT/~2Fncc~2Ftargets~2F%7BtargetId%7D

**Comment by dd1233345** [comment]
**uri = '/ncc/targets/tgt-a001-02-000000110358325'
method = 'PUT'
r = requests.put(BASE_URL + uri + '/tgt-a001-02-000000110358325',
    params=retrieved_target[0],
    headers=get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID))**

**print("response status_code = {}".format(r.status_code))
print("response body = {}".format(r.json()))
r.json()**

로 새로 요청했는데 

**response status_code = 403
response body = {'signature': 'hfMe2cQ82z+bKOE2Bcx7mASaTEYVC2C7Zye3jT406Uw=', 'status': 403, 'detail': "Signature 'hfMe2cQ82z+bKOE2Bcx7mASaTEYVC2C7Zye3jT406Uw=' is invalid.", 'title': 'Invalid Signature', 'type': 'urn:naver:api:problem:invalid-signature'}**

이런 에러가 나는데 이유를 모르겠습니다..

**Comment by dd1233345** [comment]
**uri = '/ncc/targets'
method = 'PUT'
r = requests.put(BASE_URL + uri + '/tgt-a001-02-000000110358325',
params=retrieved_target[0],
headers=get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID))**

**print("response status_code = {}".format(r.status_code))
print("response body = {}".format(r.json()))
r.json()**

로 요청해도 같은 에러가 납니다

**Comment by dd1233345** [comment]
**uri = '/ncc/targets/tgt-a001-02-000000110358325'
method = 'PUT'
r = requests.put(BASE_URL + uri,
    params=retrieved_target[0],
    headers=get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID))
print("response status_code = {}".format(r.status_code))
print("response body = {}".format(r.json()))
r.json()**

와 같이 맨 위 uri 를 변경했는데 

**response status_code = 400
response body = {'title': 'Bad Request', 'status': 400, 'detail': 'Required request body is missing: public com.naver.searchad.heroes.domain.manage.TargetResponse com.naver.searchad.heroes.web.controller.manage.TargetController.modify(java.lang.String,com.naver.searchad.heroes.domain.manage.TargetRequest)'}**

라는 오류가 나옵니다. 이유가 뭘까요...

**Comment by naver-searchad** [comment]
@dd1233345 HTTP Request Body에 Target Json이 없어서 발생한 오류입니다.
변경하고자 하는 Target의 JSON 값을 HTTP Body에 넣어 주셔야 합니다.

**Comment by dd1233345** [comment]
죄송하지만 이해가 잘 안 가서 어느 부분을 어떻게 수정해야하는지 자세히 설명해주실 수 있으신가요??
params=retrieved_target[0] 이 request body 에 들어가는 것 아닌가요?

**Comment by dd1233345** [comment]
해결했습니다 감사합니다 ~
