### ISSUE TITLE
쇼핑검색 확장소재 등록 문의드립니다.

### ISSUE THREAD

**Issue by dd1233345** [naver/searchad-apidoc#353]
**uri = '/ncc/ad-extensions'
method = 'POST'
payload = {
           'ownerId': 'grp-a001-02-000000014107742', 'pcChannelId' : 'bsn-a001-00-000000001602084', 'mobileChannelId': 'bsn-a001-00-000000001602084', 'schedule':'','type':'PROMOTION'
          , "adExtension":{
    "basicText" : "문구1 입니다.",
    "additionalText" : "문구2 입니다."
}}
r = requests.post(BASE_URL + uri, json=payload, headers=get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID))**

**print("response status_code = {}".format(r.status_code))
print("response body = {}".format(r.json()))**

와 같이 쇼핑검색광고의 확장소재 create 요청을 보냈습니다.

**response body = {'code': 4003, 'status': 400, 'title': 'Invalid ad extension type', 'detail': '비즈채널이 연결될 수 없는 확장 소재 유형 입니다.'}**

response body가 이렇게 나오는데 비즈채널은 'MALL'이 맞는데 왜 문제가 나오는지 잘 모르겠습니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

해당 확장소재는 'channel' 이 필요 없으므로
pcChannelId와 mobileChannelId 두 필드를 제거하고 요청해 보시기 바랍니다.
