### ISSUE TITLE
그룹명 15~16자 이상으로 생성시 오류 리턴 되서 광고소재 생성 안됨

### ISSUE THREAD

**Issue by jxamen** [naver/searchad-apidoc#354]
해결 완료

**Comment by naver-searchad** [comment]
@jxamen 
안녕하세요? 네이버 검색광고 API입니다.

사용하신 JSON sample을 알려주시면 확인해 보도록 하겠습니다.

**Comment by jxamen** [comment]
그룹명 길이만 줄이면 그룹 생성후에 그룹id로 소재 생성 잘됩니다.
16자만되면 그룹은 만들어지지만 리턴값이 오류가 나는게 문제입니다.

네이버 광고 사이트에서는 그룹명 30자까지 생성 가능하게 되어 있습니다.


{"nccCampaignId":"cmp-a001-02-000000002622757","targets":[{"targetTp":"TIME_WEEKLY_TARGET","target":{"MON":16777215,"TUE":16777215,"WED":16777215,"THU":16777215,"FRI":16777215,"SAT":16777215,"SUN":16777215}},{"targetTp":"REGIONAL_TARGET"},{"targetTp":"MEDIA_TARGET","target":{"type":2,"search":["naver","partner"],"contents":["naver","partner"],"black":{"media":[],"mediaGroup":[]}}},{"targetTp":"PC_MOBILE_TARGET","target":{"pc":true,"mobile":true}},{"targetTp":"GENDER_TARGET","target":{"male":true,"female":true,"unknown":true}},{"targetTp":"AGE_TARGET","target":null},{"targetTp":"PERIOD_TARGET","target":null}],"userLock":false,"useDailyBudget":false,"dailyBudget":"","bidAmt":"50","pcNetworkBidWeight":"100","mobileNetworkBidWeight":"100","adgroupType":"SHOPPING","pcChannelId":"bsn-a001-00-000000000501515","mobileChannelId":"bsn-a001-00-000000000501515","useCntsNetworkBidAmt":false,"contentsNetworkBidAmt":"","adRollingType":"ROUND_ROBIN","name":"\ubc00\ub300\ubaa8\uc74c_01. \uc2a4\ud504\ub808\uc774\ubc00\ub300\ucd94\ucc9c"}Array
(
    [nccCampaignId] => cmp-a001-02-000000002622757
    [targets] => Array
        (
            [0] => Array
                (
                    [targetTp] => TIME_WEEKLY_TARGET
                    [target] => Array
                        (
                            [MON] => 16777215
                            [TUE] => 16777215
                            [WED] => 16777215
                            [THU] => 16777215
                            [FRI] => 16777215
                            [SAT] => 16777215
                            [SUN] => 16777215
                        )

                )

            [1] => Array
                (
                    [targetTp] => REGIONAL_TARGET
                )

            [2] => Array
                (
                    [targetTp] => MEDIA_TARGET
                    [target] => Array
                        (
                            [type] => 2
                            [search] => Array
                                (
                                    [0] => naver
                                    [1] => partner
                                )

                            [contents] => Array
                                (
                                    [0] => naver
                                    [1] => partner
                                )

                            [black] => Array
                                (
                                    [media] => Array
                                        (
                                        )

                                    [mediaGroup] => Array
                                        (
                                        )

                                )

                        )

                )

            [3] => Array
                (
                    [targetTp] => PC_MOBILE_TARGET
                    [target] => Array
                        (
                            [pc] => 1
                            [mobile] => 1
                        )

                )

            [4] => Array
                (
                    [targetTp] => GENDER_TARGET
                    [target] => Array
                        (
                            [male] => 1
                            [female] => 1
                            [unknown] => 1
                        )

                )

            [5] => Array
                (
                    [targetTp] => AGE_TARGET
                    [target] => 
                )

            [6] => Array
                (
                    [targetTp] => PERIOD_TARGET
                    [target] => 
                )

        )

    [userLock] => 
    [useDailyBudget] => 
    [dailyBudget] => 
    [bidAmt] => 50
    [pcNetworkBidWeight] => 100
    [mobileNetworkBidWeight] => 100
    [adgroupType] => SHOPPING
    [pcChannelId] => bsn-a001-00-000000000501515
    [mobileChannelId] => bsn-a001-00-000000000501515
    [useCntsNetworkBidAmt] => 
    [contentsNetworkBidAmt] => 
    [adRollingType] => ROUND_ROBIN
    [name] => 밀대모음_01. 스프레이밀대추천
)

**Comment by naver-searchad** [comment]
@jxamen 
`"name":"\ubc00\ub300\ubaa8\uc74c_01. \uc2a4\ud504\ub808\uc774\ubc00\ub300\ucd94\ucc9c"` 부분이 Encoding 되어 있어서 30자를 초과한 것으로 보여집니다. Encoding 없이 요청하면 될듯 합니다.

**Comment by jxamen** [comment]
제가 특별히 인코딩을해서 보내지 않고 있습니다.
utf-8 기본 인코딩으로 전송하고 있습니다.
php 에서 array 에 데이터를 넣고 json 형태로 확인하기 위해 json_encode 하다보니 화면에 저렇게 나오는거구요, 실제로 한글로 그룹이 생성 잘됩니다.  그룹명을 30자로 해서 api로 전송을해도 생성은 잘 됩니다. 다만 16자가 넘는 그룹은 오류를 리턴하는게 문제입니다.
