### ISSUE TITLE
네이버 API , X-Signature 에러 문의입니다.

### ISSUE THREAD

**Issue by kjs6178** [naver/searchad-apidoc#355]
네이버 API 데이터랩에서 엑셀VBA 사용이 가능하여...
네이버검색광고 API 도 VBA로 구현하려 하였습니다.
invalid Signature 에러가 발생하는데
저는 Signature 에 발급받은 비밀키를 그대로 입력하였습니다.
혹시 다른방법으로 입력해야 하는건가요?
다른 방법으로 변경하여 입력해야 한다면 Tip 부탁드립니다.

Sub keyWordStool2()
    .... 중략...'
    objHTTP.setRequestHeader "X-Timestamp", strX
    objHTTP.setRequestHeader "X-API-KEY", "01000xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    objHTTP.setRequestHeader "X-Customer", "1xxxxxxxxxxxxxxxxxxxx"
    objHTTP.setRequestHeader "X-Signature", "AQAAAABJ5YLSj5rt6+fEo53kz0qihObUB9C61vTuVCc/K/SKdQ=="

    objHTTP.send ''JSONString
    Debug.Print objHTTP.responseText
End Sub

에러내용>
{"signature":"AQAAAABJ5YLSj5rt6+fEo53kz0qihObUB9C61vTuVCc/K/SKdQ==","status":403,"detail":"Signature 'AQAAAABJ5YLSj5rt6+fEo53kz0qihObUB9C61vTuVCc/K/SKdQ==' is invalid.","title":"Invalid Signature","type":"urn:naver:api:problem:invalid-signature"}

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

invalid signature 오류에 대해서는 여러가지 원인이 있으며
올려주신 정보 만으로는 파악하기가 어렵습니다.
issues 내에 많은 유사 문의들이 있으니 참고해 보시기 바랍니다.
https://github.com/naver/searchad-apidoc/issues?utf8=%E2%9C%93&q=invalid+signature
