### ISSUE TITLE
keywordstool 관련 질문입니다.

### ISSUE THREAD

**Issue by kjs6178** [naver/searchad-apidoc#356]
기존에 발생하던 timestamp, Signature 에러 등은 
기존 이슈들을 참조하여 발생하지 않습니다.
다만 쿼리 요청을 했을때
받는 리스트에 값이 없는데
strQuery 에 요청하는 방법이 잘못된걸까요?

제가 작성한 프로시져는 아래와 같습니다.

Sub keyWordStool2()
    Dim URL As String, strQuery As String, objHTTP As Object, strX As String
    Dim o As New ScriptControl
    Dim v
    o.Language = "JScript"
    o.AddCode "function x() {return new Date().getTime();}"
    
    Set objHTTP = CreateObject("WinHttp.WinHttpRequest.5.1")
    URL = "https://api.naver.com/keywordstool"
    objHTTP.Open "GET", URL, False
    
    strX = o.Run("x")
    Debug.Print strX
    
    objHTTP.setRequestHeader "Content-type", "application/JSON"
    objHTTP.setRequestHeader "X-Timestamp", 1581380590392#
    objHTTP.setRequestHeader "X-API-KEY", ""
    objHTTP.setRequestHeader "X-Customer", ""
    objHTTP.setRequestHeader "X-Signature", "IWdZ8t18SdZNseKrpnNg8Tklafoaax/6c5QUXiu0h2k="
    
    strQuery = "{""hintKeywords"":""nike,""""showDetail"":1,""includeHintKeywords"":1}"
    objHTTP.send strQuery
    v = objHTTP.responseText
    Debug.Print v
    
End Sub

결과는
{"keywordList":[]}

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

개발 코드를 직접 봐드리는 건 어려운 일입니다.
작성한 코드로 전송되는 http request 내용을 확인해 보시고
의도대로 전송되었는지 확인해 보시면 좋겠습니다.
가령 url이 다음과 같은 형태로 나가는지가 중요할 듯합니다.
`/keywordstool?hintKeywords=NIKE&includeHintKeywords=1&showDetail=1`
참고로 영문 키워드는 대문자로 변환해 주시면 됩니다.

문의해 주셨듯이 오류가 아닌 빈 결과가 리턴되었다면
요청 파라미터가 정확하지 않게 넘어갔을 가능성이 가장 큽니다.

**Comment by kjs6178** [comment]
감사합니다.
모든 문제가 정상으로 해결되었습니다.
다시한번 감사드립니다.
