### ISSUE TITLE
MasterReport Account 문의

### ISSUE THREAD

**Issue by githubcnsbs** [naver/searchad-apidoc#357]
MasterReport의 Account의 값이 제대로 들어오고 있는지 문의 드립니다.
다른 Report들은 들어오는 것을 확인하였는데(즉, rest/customerID등 세팅 정상) Account data를 요청하면, 

{"id":"67414D2C47A3C0755DF3E629E1A2809A","fromTime":"","item":"Account","downloadUrl":"","updateTime":"2020-02-11T02:24:00Z","status":"NONE",.. 이하 생략

과 같이 downloadUrl: ""으로 없으며, status가 NONE으로 나옵니다.

id가 1개라도 나와야될것 같은데, 이런 경우는 어떤 경우인지 문의드립니다. 
(현재 account는 광고시스템상 (회원유형: 사업자 광고주) 입니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

마스터리포트의 Account는 권한을 위임해 준 계정들의 목록입니다.
즉 이 때 Account는 본인 계정을 뜻하는 게 아닙니다.
따라서 직접 광고주 본인 또는 위임을 받은 계정으로 조회하시면 조회되는 내용이 없습니다.

**Comment by githubcnsbs** [comment]
네, Account가 위임해준 계정 목록임을 이해하였습니다.
 그런데, UI메뉴상 광고시스템 > 내정보 >기본정보 > 권한설정에 내가 권한을 준 계정에 2개의 계정이 등록되어 있습니다.
 이 계정들과 MasterReport의 Account 계정은 다른 것인지 문의 드립니다.

**Comment by naver-searchad** [comment]
@githubcnsbs 
위 답변을 약간 오해의 소지가 있게 말씀드렸네요. 죄송합니다.
내정보 기준으로는,
'내가 권한을 받은 계정'으로 이해하시면 되겠습니다.
`내게 권한을 준 계정`으로 이해하셔도 되겠습니다.

**Comment by githubcnsbs** [comment]
답변 감사드립니다.
