### ISSUE TITLE
advanced-report 처럼 데이터 조합해서 받을 수 있나요?

### ISSUE THREAD

**Issue by jxamen** [naver/searchad-apidoc#358]
안녕하세요. 
항상 좋은 답변 감사드립니다. ^^

리포트 api에서 각각 따로 제공은 하는거 같은데 
광고 정보
광고 성과
전환 성과

네이버 광고 관리자에서처럼 위 3가지 지표를 묶어서 볼 수 있는 방법이 있을까요?

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

광고 및 전환 성과 데이터는
다음의 stat api를 이용하면 원하는 fields 정보를 요청해서 한번에 조회할 수 있습니다.
http://naver.github.io/searchad-apidoc/#/operations/GET/~2Fstats%7B%3Fid,fields,timeRange,datePreset,timeIncrement,breakdown%7D
field별 의미는 다음 FAQ를 참고해 주세요.
https://github.com/naver/searchad-apidoc/wiki/FAQ-stat#q-stat-%EC%A7%80%ED%91%9C-%ED%95%AD%EB%AA%A9-%EC%9D%98%EB%AF%B8

광고정보는 성과와는 기본적으로 별개의 api를 이용하셔야 합니다.
