### ISSUE TITLE
API의 엑셀 활용 문의입니다.

### ISSUE THREAD

**Issue by kjs6178** [naver/searchad-apidoc#359]
1. API 사용 등록시
    어플리케이션이 엑셀일 경우는
    어떻게 등록해야 하나요?
    현재 소유중인 WEB 사이트의 URL을 사용해서 정상 등록했는데
    등록한 어플리케이션과 실사용이 다르면 제한이 있다는 글을 봐서 질문 남깁니다.
2. API 연동 완성 엑셀 파일을 광고파악에 필요한 분들에게 유료로 판매하고
    구매자 분들이 등록한 API 계정으로 그 파일을 사용하면
    상업적 사용 제한에 위배되나요?
3. 마지막으로
    API 사용 유료강의를 통해서 수강생이 배워서 직접 만들어서 사용한다면
    이 또한 강의를 유료로 판매했기 때문에 문제가 되나요?

네이버 API 운영자 분의 답변 부탁드립니다.
감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

1번 문의는 내용이 잘 이해가 되지 않지만 이해한 대로 답변을 드리자면,
API Key를 발급하고 어플리케이션에 적용하는 데에 특별히 제한 같은 건 없습니다.
어플리케이션 단위의 등록은 필요가 없습니다.

2, 3번은 정책적인 문의라 내부적으로 문의절차 중에 있습니다. 추후 추가로 코멘트 올리겠습니다.
