### ISSUE TITLE
AdKeyword에서 pCPLMaxDepth가 사라졌습니다.

### ISSUE THREAD

**Issue by kaorimikage** [naver/searchad-apidoc#36]
managedKeyword로 광고슬롯수 정보를 따로 빼신것 같은데
계속해서 3으로 고정되어 값이 전달되고 있더군요. 언제쯤 적용이 되는것인가요?

**Comment by naver-searchad** [comment]
안녕하세요 네이버 검색광고 입니다.

2월 1일 주요 변경사항중에 `AdKeyword` Resource 에서 `managedKeyword` 속성을 제거하였습니다.
기존에 계속 제공되었던 `ManagedKeyword` API를 통해서 해당 속성을 조회하실 수 있습니다.

- 2월 1일 릴리즈노트에 관련 프로퍼티 이름이 변경 되어 있었는데 누락 되었습니다. 수정해서 올리도록 하겠습니다.
  - `pCPLMaxXDepth` -> `PCPLMaxDepth` 로 변경 되었습니다.

- 일부 키워드에 대해서 해당 값으로 나갈 수 있으나 다른 키워드들을 보시면 `3`이 아닌 다른 값을 전달하는 키워드를 확인하실 수 있습니다.
  - 예) `꽃배달`
