### ISSUE TITLE
이력 관리 - 변경이력, 검토이력 API

### ISSUE THREAD

**Issue by nanpuhaha** [naver/searchad-apidoc#361]
안녕하세요.

웹에서 "네이버 검색광고 > 도구 > 이력 관리" 메뉴로 들어가면 **변경이력**과 **검토이력**을 확인할 수 있는데요, 이러한 변경이력과 검토이력을 확인할 수 있는 API가 있으면 좋겠습니다.

네이버 검색광고 서비스 내부적으로는 histories API를 사용중인 것 같은데, 공개하실 계획은 없으신지요? 
공개하지 않는 이유가 있다면 어떤 이유가 있는지 궁금합니다.

**Comment by naver-searchad** [comment]
안녕하세요.네이버 검색광고API입니다.
내부 검토 사정으로 답변이 늦어져 죄송합니다.

변경 이력관련된 API는 아시는 바대로 별도로 제공하고 있지 않습니다.
해당 API 공개에 대하여 요청하신 사용자 분이 거의 없었기 때문인데요,
어떠한 용도로 필요하신 지 구체적인 사용 계획 등을 말씀 주시면,
제공 검토를 진행해 보도록 하겠습니다.

감사합니다.
