### ISSUE TITLE
359번 문의에 대한 추가 문의입니다.

### ISSUE THREAD

**Issue by kjs6178** [naver/searchad-apidoc#362]
1. 1번 질문이 잘 이해가 안된다고 하셔서 ...
    어플리케이션 등록은 네이버에서 제공하는 API를 안드로이드,IOS,WEB 중에서 어디서 사용할것이냐
    라는 등록으로 이해하고 있습니다. 맞나요?
    그런데 저는 저 세가지가 아닌... 엑셀에서 VBA를 사용하여 API를 사용하려고 합니다.
    이럴때는 어플리케이션을 어떤것으로 선택하고 등록해야 하는가? 라는 질문이었습니다.
    현재는 WEB를 선택하고... 개인URL을 등록하고 승인받아 엑셀에서 사용하는데
    그냥 이렇게 사용해도 문제가 없는건가요?
2. 2,3 번 질문의 네이버 API관련 엑셀파일, 엑셀강의의 유료화에 대한 내부검토 답변은 어제쯤 어떻게 받을수 있을까요?
제가 유료화의 질문을 하게 된 근거는... 쇼핑몰 운영자들 사이에서 유명한
일헥타르(https://1ha.kr/main) 라는 사이트가 네이버의 검색량과 상품수 등을 이용해서 유료화 하고 있어서 문제가 없는가 하는 질문을 드린겁니다.

바쁘시겠지만 답변 부탁드립니다.

**Comment by naver-searchad** [comment]
@kjs6178 

1.
네이버 검색광고 API 사용은 광고관리시스템에서 발급받은 API KEY를 이용하시기만 하면 어떤 어플리케이션이든지 이용 가능합니다. 이에 대한 별도 등록이나 설정 과정은 없습니다. 혹시 네이버의 다른 오픈 API와 혼동하신 것은 아닌지 확인해 주세요.

2.
유료화에 관한 특별한 제약 사항은 없습니다.
단, 어플리케이션이 API를 사용함에 있어
네이버 검색광고 API 이용약관 제8조,제9조 등에 위배 되는지 다시 한번 확인 부탁 드리며, 경우에 따라 네이버 검색광고 API 이용약관 제12조 에서 처럼, '클라이언트의 검사' 를 요구 할 수는 있다는 점 , 참고하여 주시기 바랍니다.

3.
네이버 검색광고 API 이용약관의 검토 범위는 아닌 것으로 판단됩니다.

**Comment by kjs6178** [comment]
네 답변 감사합니다.
1.
아... 맞습니다. 네이버 오픈API 관련 문의였습니다.
네이버 데이터랩, 검색, 오픈API 등록시에 어플리케이션 선택이 있었습니다.
그 페이지에는 이슈질문 관련 항목이 보이지 않아서 여기에 올렸습니다.
이곳이 아니라면 혹시 어디에 올리면 될까요?

2.
네 약관을 다시한번 검토해 보겠습니다.

3.
네 알겠습니다.
