### ISSUE TITLE
PC_MOBILE_TARGET 관련 문의. 

### ISSUE THREAD

**Issue by enfshin** [naver/searchad-apidoc#363]
안녕하세요. 질문이 있어 문의 드립니다. 

uri = '/ncc/targets/'+targetID
method = 'PUT'
pmtype = {
 'nccTargetId': targetID,
 'ownerId': groid,
 'targetTp': 'PC_MOBILE_TARGET',
 'target': {'pc': True, 'mobile': False},
 'delFlag': False,
 'regTm': '2020-02-14T01:20:45.000Z',
 'editTm': '2020-02-14T01:20:45.000Z'}
r = requests.put(BASE_URL + uri, json=pmtype, headers=get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID))
print("response status_code = {}".format(r.status_code))
print("response body = {}".format(r.json()))
r.json()

형식으로 요청을 보내면 200코드가 나오고 
![1](https://user-images.githubusercontent.com/58045951/74494648-ecddf500-4f18-11ea-85c7-1eceda079db4.JPG)
위와 같이 일부매체로 잘 나오긴합니다만, 

수정을 눌러 들어가면 
![2](https://user-images.githubusercontent.com/58045951/74494675-f9624d80-4f18-11ea-8d84-d5c9d6511232.JPG)
모든매체라 표시되어 있습니다. 

위 사항이 제대로 매체제한이 반영이 된것인가요? 반영이 된것이라면 왜 수정사항 안에서는 모든매체라고 나오는건가요?

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API 입니다.

광고그룹의 매체 타겟팅은 화면에 매체 타겟팅으로 표시가 되지만 내부적으로는 `MEDIA_TARGET` 타겟팅과, `PC_MOBILE_TARGET`이 결합되어 있습니다. 이 두 타겟팅은 서버에 저장될때 분리되어 저장되고 있습니다.

광고 그룹 정보에 표시되는 매체 정보는 위의 두 타겟팅이 계산된 정보입니다. 하지만 광고 관리에 표시되는 매체부분의 모든 매체 선택은 `MEDIA_TARGET` 의 type 프로퍼티 값을 보고 보여 주고 있습니다. 이 부분은 조만간 패치 하도록 하겠습니다.

광고 그룹의 매체 타겟을 API를 이용하여 수정 할 경우 [Adgroup의 update API](http://naver.github.io/searchad-apidoc/#/operations/PUT/~2Fncc~2Fadgroups~2F%7BadgroupId%7D%7B%3Ffields%7D)를 이용하여 `PC_MOBILE_TARGET` 과 `MEDIA_TARGET`을 같이 수정 하여 주시기 바랍니다.

또한 타겟팅 수정후 반환 되는 JSON을 이용하면 원하는 대로 변경이 되었는지 반영 여부를 확인할 수 있습니다.
