### ISSUE TITLE
Retrieving analytics data from Naver Search Ad API

### ISSUE THREAD

**Issue by ghost** [naver/searchad-apidoc#366]
Hello,

I'm trying to retrieve Analytics data from Naver Search API but unsuccessfully until now.
I'm not sure what endpoint is the best to use, I'm also not sure if I have to create/configure something first on my Naver account. Could you help me?

I managed to authenticate and make some requests, as seen below:

1 - I was able to get a list of adgroups (but not sure what information I can get from here)
2 - I was also able to request a list of all Report Jobs but received an empty response ("")
3 - For last, I managed to make a POST request to create an Report Job (expecting to retrieve it later) but also received the same empty ("") response and nothing seems to be happened.

Could you help me explaining how I can retrieve data such as clicks, conversions, installs and so on from my account?

Thank you!

**Comment by naver-searchad** [comment]
Hello, this is Naver SearchAd API.

Overall, your problem seems to be getting only 'empty data' in many ways.
We can help you with some more specific information like your `login id` and `x-transaction-id` (which you can get from api response header).
Then please let us know.

Thank you!

**Comment by andrecgro** [comment]
I understand your point but, considering the 3rd request I mentioned, it was a POST request to create a Report Job, how can I get empty response from it fi I'm just creating a report ? The report will run on other date and maybe return empty data doesn't it ?

**Comment by naver-searchad** [comment]
@andrecgro 
Empty response means there's some missing or inappropriate point in your request.
But we can not imagine what it is without any information from you.
Or we can not explain all the abnormal request cases.
So please let us know the request information (also response headers information like error code and x-transaction-id if available)

**Comment by andrecgro** [comment]
I do not have X-Transaction-ID, I'm not receiving any error code, my request is as following:

endpoint: "https://api.naver.com/stat-reports?reportTp=AD_CONVERSION_DETAIL&statDt=20200217"

header:
{"Content-Type"=>"application/json; charset=UTF-8",
   "X-Timestamp"=>"1582295333218",
   "X-API-KEY"=>"<API_KEY>",
   "X-Customer"=>"1622546",
   "X-Signature"=>"<SIGNATURE>"},
 :method=>"POST"}

response received: resp_code: 200,  resp_body: ""

**Comment by naver-searchad** [comment]
@andrecgro 
It is 'POST' request,
so you are supposed to put those query parameters into request body with data object like this
`{reportTp: "AD_CONVERSION_DETAIL", statDt: "20200217"}`

**Comment by ljunior-an** [comment]
@naver-searchad 

We tried the request as with a POST and we are receiving the following error:

URI: https://api.naver.com/stat-reports
Headers: 
X-Timestamp: 1583424329179
X-API-KEY: API_KEY
X-Customer: CUSTOMER_ID
X-Signature: SIGNATURE

Body:
{ "reportTp" : "AD_CONVERSION_DETAIL",
  "statDt" : "20200217"
}

Response:
<!doctype html><html lang="en"><head><title>HTTP Status 403 – Forbidden</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 403 – Forbidden</h1><hr class="line" ><p><b>Type</b> Status Report</p><p><b>Description</b> The server understood the request but refuses to authorize it.</p><hr class="line" ><h3>Apache Tomcat/8.5.16</h3></body></html>

Please note that we tried the body as a JSON, a raw object(as you suggested) and a form_url-encoded and all them returns the same error.

Using the same logic to get the campaigns "/ncc/campaigns" URI, works fine.

Do you have any suggestions?

Thank you.

**Comment by naver-searchad** [comment]
@ljunior-an 
Without your response's header (x-transaction-id), we cannot help you further.

**Comment by ljunior-an** [comment]
@naver-searchad 

Here is a new request with all the Request and Response Headers:

Request:

URI: https://api.naver.com/stat-reports
Headers:
X-Timestamp: 1583753576259
X-API-KEY: API_KEY
X-Customer: CUSTOMER_ID
X-Signature: SIGNATURE
Content-Type: application/json

Body: { "reportTp" : "AD_CONVERSION_DETAIL",
  "statDt" : "20200217"
}

Response:
<!doctype html><html lang="en"><head><title>HTTP Status 403 – Forbidden</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 403 – Forbidden</h1><hr class="line" ><p><b>Type</b> Status Report</p><p><b>Description</b> The server understood the request but refuses to authorize it.</p><hr class="line" ><h3>Apache Tomcat/8.5.16</h3></body></html>

Response Headers:


Connection: close
X-Transaction-ID: BGNS8TP2PHG1O
Content-Type: text/html;charset=utf-8
Content-Language: en
Date: Mon, 09 Mar 2020 11:33:03 GMT
Strict-Transport-Security: max-age=15768000

**Comment by naver-searchad** [comment]
@ljunior-an 
It was cross-domain check issue on your request.
`Origin: chrome-extension://aejoelaoggembcahagimdiliamlcdmfm`
Some of our api servers are checking this cross-domain issue,
so try again without origin value or with right 'naver searchad' domain.
