### ISSUE TITLE
estimate npla 관련

### ISSUE THREAD

**Issue by bluesme519** [naver/searchad-apidoc#367]
```
def N_API_PRD_Estimates(PRD_id):
    uri = '/npla-estimate/average-position-bid/product'
    method = 'POST'
    r = requests.post(BASE_URL + uri, json={'device': 'MOBILE', 'items': [{'key': PRD_id, 'position': 1}, {'key': PRD_id, 'position': 2}, {'key': PRD_id, 'position': 3}, {'key': PRD_id, 'position': 4}, {'key': PRD_id, 'position': 5}]}, headers=N_API_get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID))
    PC_result = r.json()
    PC_result = PC_result['estimate']
    r = requests.post(BASE_URL + uri, json={'device': 'MOBILE', 'items': [{'key': PRD_id, 'position': 1}, {'key': PRD_id, 'position': 2}, {'key': PRD_id, 'position': 3}, {'key': PRD_id, 'position': 4}, {'key': PRD_id, 'position': 5}]}, headers=N_API_get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID))
    M_result = r.json()
    M_result = M_result['estimate']
    result = {
        'PC' : PC_result,
        'M' : M_result
    }
    return(result)
```

이렇게 넣어봤는데 결과가
`{'PC': [{'bid': 50, 'productId': '3877250474', 'position': 1}, {'bid': 50, 'productId': '3877250474', 'position': 2}, {'bid': 50, 'productId': '3877250474', 'position': 3}, {'bid': 50, 'productId': '3877250474', 'position': 4}, {'bid': 50, 'productId': '3877250474', 'position': 5}], 'M': [{'bid': 
50, 'productId': '3877250474', 'position': 1}, {'bid': 50, 'productId': '3877250474', 'position': 2}, {'bid': 50, 'productId': '3877250474', 'position': 3}, {'bid': 50, 'productId': '3877250474', 'position': 4}, {'bid': 50, 'productId': '3877250474', 'position': 5}]}`

이런식으로 전부 bid 값이 50으로만 나옵니다. API자체에 문제가 있는 것 같아요. 제가 다른 여러 상품들도 해봤으나 결과는 항상 bid 값이 50만 나오더라구요.

그리고
type 에 product를 넣어서 상품아이디를 넣는게아니라 광고아이디를 넣어서도 해봤는데
결과값이
`{'PC': [{'position': 1, 'nccAdId': 'nad-a001-02-000000026481174'}, {'position': 2, 'nccAdId': 'nad-a001-02-000000026481174'}, {'position': 3, 'nccAdId': 'nad-a001-02-000000026481174'}, {'position': 4, 'nccAdId': 'nad-a001-02-000000026481174'}, {'position': 5, 'nccAdId': 'nad-a001-02-000000026481174'}], 'M': [{'position': 1, 'nccAdId': 'nad-a001-02-000000026481174'}, {'position': 2, 'nccAdId': 'nad-a001-02-000000026481174'}, {'position': 3, 'nccAdId': 'nad-a001-02-000000026481174'}, {'position': 4, 'nccAdId': 'nad-a001-02-000000026481174'}, {'position': 5, 'nccAdId': 'nad-a001-02-000000026481174'}]}`
이런식으로 나옵니다. 이건 bid도 없게 나옵니다.

제가 estimate 함수를 잘못이해하고사용하고 있는건지 뭐가 문제인지 궁금합니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

로그를 확인해 본 결과,
`nad-a001-02-000000026481174`는 권한이 없어서(customerId 다름) 결과가 반환이 되지 않았고,
상품 3877250474의 경우 견적 데이타가 존재하지 않아서 50원이 반환됐습니다.
상품이 노출된 성과 등이 없는 경우로 보여집니다.
