### ISSUE TITLE
대,중,소 쇼핑 카테고리 관련 질문입니다.

### ISSUE THREAD

**Issue by kjs6178** [naver/searchad-apidoc#368]
안녕하세요.
항상 많은 도움 주셔서 감사드립니다.

네이버 쇼핑 카테고리에는 최대 4단계로 총 5000종 이상의 카테고리가 있다고 알고 있습니다.
패션잡화 > 여성신발 > 운동화 > 러닝화
50000000 > 50000173 > 50001463 > 50003835

위와 같은 코드로요 
혹시 API 를 통해서 또는 다른 방법으로라도
네이버에서 관리하는 전체 카테고리명과 코드를 매칭 
확인 할 수 있는 방법이 있을까요?

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

검색광고에서 네이버 쇼핑검색 유형의 광고는 지원하고 있지만
네이버 쇼핑 서비스 정보에 해당하는 내용들은 API로 지원하기 어렵습니다.
광고 정보를 이루는 외부 데이터에 대한 내용은
해당 서비스에서 제공되는 것이 있는지 확인해 보셔야 하겠습니다.
