### ISSUE TITLE
RelKwdStat: list 문의

### ISSUE THREAD

**Issue by jklee0219** [naver/searchad-apidoc#369]
monthlyPcQcCnt,  monthlyMobileQcCnt 30일 데이터가 나오는데 혹시 일별로 받을수 있는 방법은 없을까요? ㅜㅜ

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

현재 API 스펙 외에는 지원되지 않고 있습니다.
