### ISSUE TITLE
keyword update 에서 가중치는 api 에서 제공하지 않는건가요?

### ISSUE THREAD

**Issue by kangkyoungsup** [naver/searchad-apidoc#37]
keyword update 에서 가중치는 api 에서 제공하지 않는건가요? 안보이는데 계획은 있는지?

**Comment by naver-searchad** [comment]
안녕하세요~

AdKeyword에서는 가중치와 관련된 항목이 존재하지 않습니다.
AdGroup(ref. [Adgroup Overview](http://naver.github.io/searchad-apidoc/#/tags/Adgroup))에서는 아래와 같은 가중치를 제공하고 있습니다.
 
keywordPlusWeight , mobileNetworkBidWeight,  pcNetworkBidWeight

다른 답변을 원하시는 경우 좀 더 구체적으로 어떤 항목인지 알려주시면 답변 드리겠습니다.

감사합니다.
