### ISSUE TITLE
RelKwdStat 관련문의.

### ISSUE THREAD

**Issue by enfshin** [naver/searchad-apidoc#370]
관련 레퍼런스의 리스펀스를 확인해보면
monthlyAvePcClkCnt == 피씨광고의 평균 클릭수 
monthlyAveMobileClkCnt == 모바일광고의 평균 클릭수
가 맞나요?

또한 
plAvgDepth에서 Depth는 정확히 무엇을 의미하나요?

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

기본적인 지표 용어는 다음의 wiki 내용을 참고하시면 도움이 되실 겁니다.
https://github.com/naver/searchad-apidoc/wiki/FAQ-stat
올려주신 지표 정보는 이해하신 대로 맞구요
Depth는 노출되는 광고수를 의미합니다.
plAvgDepth가 3이라면 해당 키워드로 파워링크 지면에 평균 3개의 광고가 나간다는 의미입니다.

**Comment by enfshin** [comment]
해당 링크로는 자세한 설명을 찾을 수없어 다시 문의드립니다. 
monthlyAvePcClkCnt와 monthlyAveMobileClkCnt 도 그러면 파워링크의 클릭수를 말하는 건가요?

**Comment by naver-searchad** [comment]
@enfshin 
해당 api가 사용되는 광과시스템의 '키워드 도구' 화면을 보시면 자세한 정보를 얻으실 수 있습니다.
처음 들어가서 보시면 하단에,
`키워드 도구의 연관키워드 조회 및 키워드 추가는 '파워링크 캠페인' 유형에 한해 지원됩니다.`
로 안내돼 있으며
'월평균클릭수' 테이블 컬럼 타이틀의 툴팁을 보시면 자세한 설명도 보실 수 있습니다.

설명들을 확인해 보시면,
질문하신 내용이 맞음을 아실 수 있을 겁니다.
