### ISSUE TITLE
여러개의 계정을 하나의 키로 관리 가능한지 문의 드립니다.

### ISSUE THREAD

**Issue by songxue77** [naver/searchad-apidoc#371]
안녕하세요.
Wiki -> FAQ에 아래와 같은 안내가 있습니다.
-------------------------------------------------------------------------------------------------------------
Q. 하나의 엑세스 라이선스/비밀키로 여러 개의 애플리케이션을 구축할 수 있나요?
여러 광고주에게 권한을 위임받은 계정의 엑세스 라이선스와 비밀키로 검색광고 API를 통해 해당 광고주들의 광고를 관리하실 수 있습니다. 이때 특정 광고주에게 제공한 애플리케이션에서는 다른 광고주의 정보가 노출되어서는 안됩니다.
-------------------------------------------------------------------------------------------------------------
현재 상황이 dev1, dev2, dev3, dev4, dev5 다섯개의 광고계정을 운영하고 있다면 하나의 엑세스 키&비밀키로 다섯개의 광고계정의 광고 데이터에 모두 엑세스할 수 있다는 말씀인가요?

만약 그렇다면 권한을 위임받는다는 액션은 어떻게 할 수 있는지 문의 드립니다.

따로 master1이라는 계정을 생성한 다음 엑세스 라이선스와 비밀키를 생성하고 권한을 dev1, dev2, dev3, dev4, dev5계정에서 위임받는다는 뜻인가요?

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

검색광고 홈(searchad.naver.com)에 접속하셔서 '내정보' - '권한설정' 메뉴로 들어가시면
다른 계정으로 본인 계정의 관리권한을 부여할 수 있습니다.
API를 사용할 계정 하나를 두고 실제 광고 데이터를 운영할 계정들로부터 권한을 위임받아 사용하시면 됩니다.
API 사용시에는 X-Customer id에 본인의 것이 아닌 실제 관리 대상인 계정(Client Customer)의 것을 넣으시면 됩니다.

**Comment by songxue77** [comment]
> 안녕하세요, 네이버 검색광고 API입니다.
> 
> 검색광고 홈(searchad.naver.com)에 접속하셔서 '내정보' - '권한설정' 메뉴로 들어가시면
> 다른 계정으로 본인 계정의 관리권한을 부여할 수 있습니다.
> API를 사용할 계정 하나를 두고 실제 광고 데이터를 운영할 계정들로부터 권한을 위임받아 사용하시면 됩니다.
> API 사용시에는 X-Customer id에 본인의 것이 아닌 실제 관리 대상인 계정(Client Customer)의 것을 넣으시면 됩니다.

답변 감사합니다.

추가질문으로 혹시 실제 관리 대상인 계정(네이버 검색광고 API 서비스를 신청하지 않은 상태)의 X-customer id를 확인하는 방법은 따로 있는지 문의 드립니다.

광고시스템 > 도구 > API사용관리에 진입 시 url이https://manage.searchad.naver.com/customers/XXXXXX/tool/api로 확인되는데 XXXXXX값을 custom id으로 이용해도 될지 문의 드립니다.

감사합니다.

**Comment by naver-searchad** [comment]
@songxue77 

일반적으로 대행사 계정으로 다음 api를 이용해서 나한테 권한을 부여해 준 고객 계정 customer id를 조회할 수 있습니다.
`http://naver.github.io/searchad-apidoc/#/operations/GET/~2Fcustomer-links`
type은 MYCLIENTS, 그리고 api 호출시 customer id는 본인 계정 것을 사용하면 됩니다.

만약 관리 대상 계정이 모두 본인 것들이면(즉 id/pwd를 알고 있다면) 말씀하신 대로 해당 정보를 이용해도 됩니다.

**Comment by songxue77** [comment]
> @songxue77
> 
> 일반적으로 대행사 계정으로 다음 api를 이용해서 나한테 권한을 부여해 준 고객 계정 customer id를 조회할 수 있습니다.
> `http://naver.github.io/searchad-apidoc/#/operations/GET/~2Fcustomer-links`
> type은 MYCLIENTS, 그리고 api 호출시 customer id는 본인 계정 것을 사용하면 됩니다.
> 
> 만약 관리 대상 계정이 모두 본인 것들이면(즉 id/pwd를 알고 있다면) 말씀하신 대로 해당 정보를 이용해도 됩니다.

네, 답변 감사합니다. 많은 도움이 되었습니다.
