### ISSUE TITLE
No permission to access the resourceGET /ncc/keywords{?ids}

### ISSUE THREAD

**Issue by jklee0219** [naver/searchad-apidoc#372]
/ncc/keywords 사용시 아래와 같은 결과가 나오는데

array(3) {
  ["code"]=>
  int(1018)
  ["status"]=>
  int(404)
  ["title"]=>
  string(37) "No permission to access the resource."
}

이유가 뭘까요?

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

말 그대로 permission 에러입니다.
요청하신 자원에 대한 접근 권한이 없다는 의미입니다.
