### ISSUE TITLE
AdExtension Conversion StatReport Spec

### ISSUE THREAD

**Issue by hwangjundong** [naver/searchad-apidoc#373]
안녕하세요.

StatReport 중 AdExtension conversion 에 대한 스펙(필드목록 및 순서) 정보는 어디에 있나요?

다른 StatReport 와 MasterReport 각각의 Report 들에 대한 tsv 형태로 리턴되는 필드 목록들은 어디에서 볼수 있는지 알려주시면 도움이 될것 같습니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API 입니다.

광고시스템의 '대용량 다운로드 보고서' 탭에서 도움말 링크를 가시면
'사양서'를 다운로드 해서 보실 수 있습니다.

**Comment by hwangjundong** [comment]
감사합니다.
