### ISSUE TITLE
Brand Search

### ISSUE THREAD

**Issue by PandoraTV** [naver/searchad-apidoc#375]
Campaign 이 
Shopping Ad 면 --> ShoppingProduct 
Power Contents --> contentsAd
Web Site --> Ad 
Place Ad --> placeAd 에 광고 소재 정보가 들어 있는것 같은데,
Brand Search 인 경우 광고 소재 정보가 어떤 마스터 테이블에 들어가 있는건가요?

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API 입니다.

브랜드검색 소재 정보는 마스터리포트를 통해서 제공되지 않습니다.

**Comment by PandoraTV** [comment]
감사합니다. 
StatReport Ad 에서 브랜드 검색에 포함되어 있는 6번째 필드 광고 성과가 발생한 소재의 고유 아이디에 적혀있는 값은 어떤 의미 인가요? nad-a001-04-000000XXXXX 처럼 적혀 있던데요..

**Comment by naver-searchad** [comment]
@PandoraTV 
필드정보 그대로 '소재(ad) id'입니다.
다른 의미는 없습니다.

**Comment by PandoraTV** [comment]
브랜드 검색 소재 코드는 제공하는데 브랜드 검색 소재 정보는 제공하지 않으시는 건가요? 
아니면 다른 방법으로 구할 수가 있는건가요?

**Comment by naver-searchad** [comment]
@PandoraTV 
마스터 테이블(마스터 리포트)을 질문하셨으므로 제공되지 않는다는 거였구요
일반적인 api로는 물론 제공이 됩니다.
http://naver.github.io/searchad-apidoc/#/tags/Ad

**Comment by PandoraTV** [comment]
감사 합니다. 잘 동작 되네요.
만약 브랜드검색의 내용을 광고주가 수정하면 새로운 ad id 가 발행이 되나요? 
아니면, ad id는 그대로 있고, 내용만 수정되는 건가요?

**Comment by naver-searchad** [comment]
@PandoraTV 
변경 프로세스에 대해서는 광고시스템 소재탭에서 확인해 보시면 상세히 아실 수 있습니다.

기간/시간 변경과 같은 정보는 id 그대로 수정되는 내용이지만
소재 내용을 바꿀 때는 '편집 후 새로등록' 버튼으로 적용되므로
새로운 ad id와 함께 소재 전체가 새로 생성됩니다.

**Comment by PandoraTV** [comment]
네. 감사합니다.
많은 도움이 됐습니다.
