### ISSUE TITLE
MasterReport 스펙 업데이트 요청

### ISSUE THREAD

**Issue by nanpuhaha** [naver/searchad-apidoc#376]
BusinessChannel의 4번째 필드 Business Channel Type이 스펙 문서에는 1~7까지 7가지밖에 없는데, 

실제 데이터의 경우 10(네이버TV)도 있습니다. 

업데이트 요청 드립니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

말씀해 주신 부분에 대해 현재 정보로 업데이트해 두었습니다.
감사합니다.
