### ISSUE TITLE
저희가 어제까지만해도 잘 되었던거 같은데 혹시 차단 당했는지 알고 싶습니다.

### ISSUE THREAD

**Issue by dogpat** [naver/searchad-apidoc#377]
아이피 주소는 : 58.229.176.178입니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

네이버 검색광고 api에서는 별도 ip 차단관리는 하고 있지 않습니다.

혹시 이용하시는 서버의 NTP 동기화 문제로 403 오류가 날 수 있으니
다음 faq를 참고해 보시면 좋을 것 같습니다.
https://github.com/naver/searchad-apidoc/wiki/FAQ#q-invalid-timestamp-%EC%97%90%EB%9F%AC%EA%B0%80-%EB%B0%9C%EC%83%9D%ED%95%A9%EB%8B%88%EB%8B%A4-%EC%96%B4%EB%96%BB%EA%B2%8C-%ED%95%B4%EC%95%BC-%ED%95%A0%EA%B9%8C%EC%9A%94

**Comment by dogpat** [comment]
Failed to connect to 210.89.172.27: Invalid argument 이런 에러 뜨는데 그러면 NTP 문제인가요?

**Comment by naver-searchad** [comment]
@dogpat 
문의하신 내용만으로는 자세히 알 수가 없습니다.
참고로 invalid argument라면 요청하는 데이터가 잘못되지 않았는지 먼저 확인해 보시고 문의 주시기 바랍니다.

**Comment by dogpat** [comment]
제가쓰는 로컬 xampp 에서는 잘 받아지는데
위에 말씀드린 centos7 에서는 안받아지는거면 curl 자체가 문제가 있는걸까요?

**Comment by naver-searchad** [comment]
@dogpat 
api 문의 외의 기술적인 문의는 답변해 드리기가 어렵겠습니다.
