### ISSUE TITLE
AD 소재 수정 관련 문의드립니다.

### ISSUE THREAD

**Issue by whilebreaker** [naver/searchad-apidoc#378]
AD에서 headline 같은 필드를 update써서 수정하고 싶은데 가능한 방법이 없을까요?
소재와 관련해서 update 를 써서 컬럼값을 직접적으로 선택하고 그 항목만 수정할 수 있는 방법이 없을까요?

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

기본적으로 API 구조는 광고시스템의 관리 기능과 동일합니다.
관리화면의 소재 목록 기능을 보시면 아시겠지만
소재 내용(문구 등)을 수정하는 기능은 제공되지 않습니다.
