### ISSUE TITLE
AD 소재 수정 관련해서 다시 문의드립니다.

### ISSUE THREAD

**Issue by whilebreaker** [naver/searchad-apidoc#379]
AD 소재 수정 관련해서 다시 문의드립니다.

API가 네이버 광고 센터와 동일한 기능을 수행할 수 있다고 하셔서 문의 드립니다.

소재 상세보기에서 상단에 수정을 누르면 

노출용 상품명을 수정할 수 있습니다.

이 기능을 API로 어떻게 구성해야 할지 모르겠습니다. 

현재 ADS.UPDATE에서는 노출용 상품명을 수정할 수 있는 요청이 안보이는데 확인 및 어떻게 만들어야 할지 알려주셨으면 합니다. 감사합니다.

**Comment by naver-searchad** [comment]
@whilebreaker 
관리화면에서 해당 기능을 직접 수행해 보시고
http request에서 어떻게 사용되는지를 브라우저에서 확인해서 참조하시면 됩니다.

노출용 상품명을 수정해 보시면 (노출용 이미지도 함께 수정 가능)
`PUT api/ncc/ads/nad-a001-02-000000000xxxxx?fields=ad`
와 같은 형태로 request됨을 알 수 있습니다.
body에는
```
{
...
ad: {productName: "노출용상품명"}
...
}
```
와 같이 ad 필드에 값이 세팅됩니다.
PUT 업데이트이기 때문에 reuqset body의 데이터가 그대로 소재 데이터에 들어가게 되므로 주의하셔야 합니다.

UPDATE의 fields 'ad'는 api 문서에는 나와 있지는 않습니다.
쇼핑 유형 데이터 관리는 가급적 관리화면을 통해 관리하시길 추천 드립니다.
그리고 광고관리 화면상의 모든 기능이 api로 지원되고 있지는 않다는 점도 참고해 주세요.
소개해 드린 내용도 api 공식문서에는 없는 기능이므로
정책에 따라 언제든 변경될 수 있음도 참고해 주시면 되겠습니다.
