### ISSUE TITLE
http status code관련 질문입니다.

### ISSUE THREAD

**Issue by younseunghyun** [naver/searchad-apidoc#38]
안녕하세요

현재 api를 사용함에 있어서, HttpStatusCode가 반환 되고 있는데, 유효하지 않는 api key에 대해서 HttpStatusCode는 500이 body의 status에는 403이 담겨서 반환 되고 있습니다.

HttpStatusCode를 처리하는데 있어서 body의 status의 필드 값이 좀 더 정확한 값이라고 보고 처리해도 되는지, 아니면 body에 있는 status 정보만 가지고 판단하기엔 애매한 부분이 있는지 궁금합니다.

감사합니다 :)

**Comment by naver-searchad** [comment]
body에 있는 status 값을 우선으로 처리해주시기 바랍니다.
Http status code 500 이 반환되는 경우는 곧 수정될 예정입니다.

**Comment by younseunghyun** [comment]
답변 감사합니다 :)
