### ISSUE TITLE
AdGroup 생성시

### ISSUE THREAD

**Issue by uomopeloso** [naver/searchad-apidoc#381]
네이버 광고시스템대로라면
캠페인 생성 후에 광고그룹을 만드는걸로 알고 있는데,
Adgroup API 에서 POST 메소드 실행시 입력해야하는 필수값인
pcChannelId와 mobileChannelId는 어디서 받아올 수 있는건가요?

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

예를 들어 광고시스템 상에서 파워링크 유형 캠페인에 광고그룹 생성하실 때 보시면
광고그룹 이름 아래에 'URL'을 선택하도록 나옵니다.
이 URL 목록이 BusinessChannel 이고 api로는
http://naver.github.io/searchad-apidoc/#/tags/BusinessChannel
를 참고하시면 되겠습니다.
파워링크 유형인 경우 channelTp가 'SITE'인 것만 보여지게 됩니다.
그리고 url 하나를 선택하면 pc/mobile 별도로 가지고 있는지 옵션이 나타나면서
추가로 moblie용 channel을 하나 더 입력받을 수 있게 됩니다.

api 상에서는 각각 pcChannelIdl와 mobileChannelId 에
해당 SITE type의 BusinessChannel들 중 하나를 미리 선택해서
nccBusinessChannelId 값을 입력하시면 됩니다.

즉, 광고그룹을 생성하기 위해서는 미리 해당 캠페인 유형에서 필요한
BusinessChannel 이 1개 이상 먼저 등록돼 있어야 합니다.

**Comment by uomopeloso** [comment]
답변 감사합니다!
하나더 여쭤보고싶은데
파이썬 샘플코드에서 ManagedCustomerLink 실행시 응답코드는 200이 나오는데
response body에는 왜 아무것도 안나오나요?

**Comment by naver-searchad** [comment]
@uomopeloso 
광고시스템 홈에서 내정보-권한설정 에서 조회되는 내용이 있으신지 먼저 확인해 보시기 바랍니다.

**Comment by uomopeloso** [comment]
감사합니다!
ManagedCustomerLink는 권한설정 조회내용이라는 것을 알겠습니다.
이외에도 Label, LabelRef, Target API들은 정확히 어떤것을 의미하는지 파악하기 힘듭니다...

**Comment by naver-searchad** [comment]
@uomopeloso 
Label/LabelRef는 광고관리 화면에서 '즐겨찾기'를 사용해 보시면 api request 샘플을 확인하실 수 있습니다.
Target들은 모두 광고그룹의 고급옵션인 '매체, 지역, 시간' 전략에 사용되는 api입니다.
화면 내용과 api 문서를 참고하셔서 이용하시면 되겠습니다.
