### ISSUE TITLE
Adkeyword 생성시

### ISSUE THREAD

**Issue by uomopeloso** [naver/searchad-apidoc#382]
Adkeyword를 POST할때
파라미터 nccKeywords[]의 data type이 Adkeyword라고 되어있는데
등록하고 싶은 키워드 명만 입력하면 되는건가요?

**Comment by naver-searchad** [comment]
@uomopeloso 
http://naver.github.io/searchad-apidoc/#/operations/POST/~2Fncc~2Fkeywords%7B%3FnccAdgroupId%7D
문서에서 AdKeyword data type을 클릭해 보시면 다음과 같이 type 안내가 나옵니다.
http://naver.github.io/searchad-apidoc/#/definitions/AdKeyword
참고하시기 바랍니다.

모든 api 이용은 api 문서와 광고관리 화면의 api requset 내용을 함께 보시면
웬만한 정보는 모두 얻으실 수 있으니 참고하시기 바랍니다.

**Comment by uomopeloso** [comment]
파이썬 샘플코드를 이용하여 키워드 생성을 시도했습니다.


--------------------------------------------------------------------------------------------------------
uri = '/ncc/keywords?grp-a001-01-000000014658289'
method = 'POST'
payload = {'nccKeywords[]' : {'bidAmt':70,
                             'customerId':-------,
                             'keyword':'애완용샴푸',
                             'links':{"pc": {
                                 "final":"http://lilalovesit.co.kr/category/%EC%83%B4%ED%91%B8%EB%B9%84%EB%88%84%EC%BB%A8%EB%94%94%EC%85%94%EB%84%88/25/"
                             },
                             "mobile":{
                                 "final":"http://lilalovesit.co.kr/category/%EC%83%B4%ED%91%B8%EB%B9%84%EB%88%84%EC%BB%A8%EB%94%94%EC%85%94%EB%84%88/25/"
                             }},
                             'nccAdgroupId':'grp-a001-01-000000014658289',
                             'nccCampaignId':'cmp-a001-01-000000002794239'}
           }
r = requests.post(BASE_URL + uri,
                  json=payload,
                  headers=get_header(method,uri,API_KEY,SECRET_KEY,CUSTOMER_ID))

print("response status_code = {}".format(r.status_code))
print("response body = {}".format(r.json()))

------------------------------------------------------------------------------------------------------------

위 코드 실행시 밑의 결과가 나왔는데요 (customerId에는 저희의 7자리 숫자입력)

------------------------------------------------------------------------------------------------------------

response status_code = 403
response body = {'signature': 'NyIAhZZDQ07IFFIp/Rfvcif8M8ptqShxobLILC9MkkM=', 'title': 'Invalid Signature', 'status': 403, 'detail': "Signature 'NyIAhZZDQ07IFFIp/Rfvcif8M8ptqShxobLILC9MkkM=' is invalid.", 'type': 'urn:naver:api:problem:invalid-signature'}

Process finished with exit code 0

----------------------------------------------------------------------------------------------------------

처음엔, payload에 nccAdgroupId까지 입력했더니 위의 에러 없이
 'nccAdgroupId' : 'grp-a001-01-000000014658289'}
                 ^
SyntaxError: invalid syntax
이 오류가 떠서 해결 못하고, 아예 nccAdgroupId를 지우고 다시 실행한 것입니다.

위 코드의 payload의 'nccKeywords[]': 에는 모든 컬럼을 넣지 않았는데 이게 문제인지,
밑의 결과는 어떤 오류인지, signature와 title은 어디서 나왔고 어떤것인지 모르겠습니다....
