### ISSUE TITLE
BadRequest 400 문의

### ISSUE THREAD

**Issue by dnt-walker** [naver/searchad-apidoc#383]
MasterReport를 조회하는 과정에서 아래와 같은 오류가 발생합니다.
"{"name":"BadRequest","status":400,"title":"Bad Request","detail":"exceeded limit of '100' numbers of 'job'"}"

그래서 웹상이나 API를 통해서 해당 해당 계정에 리포트 갯수를 체크해본 결과 100개가 넘지않는 것으로 확인되었습니다.
조회 횟수가 일정시간동안 많기는 하지만 최대 20개 안밖으로 리포트 개수를 유지하고 있습니다. 

해당 오류가 왜 발생하는지 문의드립니다. 확인 부탁드립니다.

**Comment by naver-searchad** [comment]
안녕하세요. 검색광고API 입니다.
위 오류는 계정당 마스터리포트 생성 이력이 100개를 초과하였을 떄 발생합니다.
오류가 발생한 TransactionID나 customerId 를 남겨주시면, 확인 후 답변 드리도록 하겠습니다.

**Comment by dnt-walker** [comment]
안녕하세요! 답변 감사합니다.
금일도 아래와 같이 오류가 발생하네요.

2020-03-24 08:47:43  400 Bad Request. X-Transaction-ID: BH175NUP1DGCJ MasterReport

현재 리포트 생성 후 다운받고 바로 삭제처리하고 있는데 삭제 반영시간이 실시간이 아닌가요?
문제 발생 시점이 후 다시 전체 계정에 대해서 리포트 수(GET /master-reports)로 조회 시 100개를 넘는 계정이 없습니다.

확인 부탁드리겠습니다.

**Comment by naver-searchad** [comment]
@dnt-walker 
삭제 처리된 목록들이 여전히 큐에 남아 있어 카운트가 오버되는 현상이 있다고 합니다.
비정상적인 데이터를 정리했다고 하니 다시 확인 부탁드립니다.

**Comment by dnt-walker** [comment]
빠른 확인 감사합니다.
처리해주시고 이후로는 동일 문제가 발생하지는 않습니다.

기존에는 문제가 발생 후에 일정 시간이 지난후에 시도하면 정상동작하는 것으로 보입니다. 
혹시 이후로 기간이 지나고 동일 증상이 발생할 수 있는 것인지 문의 드립니다.

**Comment by naver-searchad** [comment]
@dnt-walker 
비정상적인 데이터가 남아 있던 케이스이므로
일반적인 정상 상황에서는 향후 발생하지는 않을 것 같습니다.
다만, 카운팅에 실시간과 실데이터를 이용하는 프로세스가 아닌 만큼
이와 같은 운영 이슈들을 완전히 배제하고 보장하는 데는 한계가 있는 것도 사실이겠습니다.
어쨌든 이런 상황이 발생하면 비정상적인 데이터에 의한 것이므로
문의가 들어오는 대로 곧바로 처리가 가능합니다.

**Comment by dnt-walker** [comment]
@naver-searchad 
확인 감사합니다.

**Comment by dnt-walker** [comment]
위와 같은 문제가 계속 발생해서 진행이 안되고 있습니다. 

확인 부탁드립니다.

```
HTTP/1.1 400 Bad Request
X-Transaction-ID: BJ6UMEDTHDH2K
Content-Type: application/json;charset=UTF-8
Date: Fri, 10 Jul 2020 07:42:25 GMT
{"name":"BadRequest","status":400,"title":"Bad Request","detail":"exceeded limit of '100' numbers of 'job'"}
```
추가로 브랜드검색소재 정보를  MasterReport로 받을 수는 없는건가요?
확인 부탁드립니다.

**Comment by naver-searchad** [comment]
@dnt-walker 
안녕하세요.
확인 결과 job을 처리하는 데에 약간의 문제가 있는 것으로 밝혀져 수정작업 처리되었습니다.
재확인 해 보시면 될 듯합니다.
