### ISSUE TITLE
keywordstool 검색량 관련 문의

### ISSUE THREAD

**Issue by Kimsangbum-bumyfos** [naver/searchad-apidoc#384]
/keywordstool 활용하여 키워드 검색량 조회 시 검색을 하는 키워드가 한개인 경우 한개의 pc, mobile 검색량만 받으려면 어떻게 해야하나요? 예를들어 '콜라'라고 검색 시 아래처럼 콜라에 대한 하나의 결과만 받고 싶은데요 이렇게 가능한가요? 보통은 입력하는 키워드 및 모든 연관키워드에 대한 결과값이 리턴되는데요 '콜라'에 대한 1개의 결과만 받고 싶습니다. 

                (
                    [relKeyword] => 콜라
                    [monthlyPcQcCnt] => 2460
                    [monthlyMobileQcCnt] => 14700
                    [monthlyAvePcClkCnt] => 15.9
                    [monthlyAveMobileClkCnt] => 25.5
                    [monthlyAvePcCtr] => 0.69
                    [monthlyAveMobileCtr] => 0.19
                    [plAvgDepth] => 15
                    [compIdx] => 높음
                )

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

keywordstool은 키워드도구에서 사용되는 '연관키워드' 검색 api입니다.
문의주신 내용은 특정 키워드의 검색량 등의 정보를 원하시는 거로 보이는데요
따라서 해당 용도의 api는 아닙니다.
다만,
연관키워드 결과에는 대부분 힌트키워드 자체도 포함될 것이므로
이를 활용하셔도 되겠습니다.
