### ISSUE TITLE
광고 소재등록 혹은 그룹생성시 추가요청 문의 

### ISSUE THREAD

**Issue by enfshin** [naver/searchad-apidoc#385]
안녕하세요 고생이 많으십니다. 몇가지 질문이 있어 몇일 찾아보다 결국 이슈를 남기게 됩니다. 

1. 혹시 SHOPPING_PRODUCT_AD의 소재등록시에 쇼핑상품부가정보(리뷰노출하는 것) 추가는 API로는 불가능한가요? 
2. 혹은 그룹을 생성할 때에 톡톡문의추가는 API로는 불가능한가요? 
3. keywordstool 요청에서 과거 검색량을 알 수 있나요? 혹은 알 수 있는 다른 API가 있을까요?

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

참고로 API에서 제공하는 기능들은 모두 광고관리스템 화면을 통해 이용하는 것과 동일합니다.
즉 화면에서 제공되지 않는 기능이 추가나 별도로 제공되고 있지는 않습니다.

1.
소재를 등록하게 되면 리뷰수는 자동 연동 되어 나타나는 정보이므로 따로 입력하는 정보가 아닙니다.
2. 그룹 생성시 해당 기능은 없습니다.
'톡톡문의추가'는 혹시 확장소재를 의미하는 것인지요?
어쨌든 광고관리 화면 상에서 구현된 구조를 그대로 따라 하시면 됩니다.
3.
역시 제공되는 기능 밖이므로 지원되지 않습니다.
