### ISSUE TITLE
네이버 쇼핑 내 파워링크 단가 API문의

### ISSUE THREAD

**Issue by hadxit75** [naver/searchad-apidoc#386]
안녕하세요

현재 문서를 검색 해보니 Bidning하는 API 가 있어서 연동을 해보니 
네이버 쇼핑 내의 파워링크 단가가 아닌
네이버 검색에서 파워링크 단가로 확인이 되었는데요. 혹시 네이버 쇼핑몰 내 파워링크 단가를 볼수 있는 API가 어떤건지 알수 있을까요?

[현재 사용중인 API]
/estimate/average-position-bid/keyword

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

'쇼핑 내 파워링크'라고 문의해 주셨는데요
'쇼핑검색광고'로 이해하고 답변 드리겠습니다.

광고시스템 화면을 통해 광고관리를 해 보셨다면 아시겠지만
쇼핑검색광고의 경우 별도로 '키워드'를 등록하지 않습니다.
즉 파워링크 상품처럼 키워드를 등록하고 키워드에 입찰가를 적용하는 것이 아니라
'소재'를 등록하고 소재에 입찰가를 적용하도록 되어 있습니다.
따라서 키워드 입찰가 견적은 적용되어 있지 않습니다.
