### ISSUE TITLE
파이썬 코드 샘플 질문있습니다.

### ISSUE THREAD

**Issue by uomopeloso** [naver/searchad-apidoc#387]
# 1. GET adgroup Usage Sample

uri = '/ncc/adgroups'
method = 'GET'
r = requests.get(BASE_URL + uri, headers=get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID))

print("response status_code = {}".format(r.status_code))
print("response body = {}".format(r.json()))
target_adgroup = r.json()[0]

--------------------------------------------------------------------------------------------------------------

# 2. CREATE adgroup Usage Sample

uri = '/ncc/adgroups'
method = 'POST'
payload = {'name': 'TEST#' + str(random.randrange(1000, 9999)), 'nccCampaignId' : target_adgroup['nccCampaignId'], 'pcChannelId' : target_adgroup['pcChannelId'], 'mobileChannelId': target_adgroup['mobileChannelId']}
r = requests.post(BASE_URL + uri, json=payload, headers=get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID))

print("response status_code = {}".format(r.status_code))
print("response body = {}".format(r.json()))

created_adgroup = r.json()
----------------------------------------------------------------------------------------------------
파이썬 샘플코드 중에 adgroup GET과 POST 코드인데요
각각 마지막에있는
target_adgroup = r.json()[0]

created_adgroup = r.json()

이 두 줄이 무슨 의미이고 어떤 관계인지 모르겠습니다.
target_adgroup = r.json()[0] 여기서 [0]는 어떤것을 나타내는지도 알려주시면 감사하겠습니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

어떤 의미를 문의하신 건지가 명확치 않지만,
문의 주신 내용 그대로에 대한 답변을 드리자면,
get adgroups api는 하나 이상의 adgroup을 list 형태로 반환합니다. (복수)
create의 경우는 요청한 adgroup이 생성된 결과를 그대로 반환합니다. (단수)
따라서 각각의 경우에 대한 response 내용을 이용하는 예시입니다.

**Comment by uomopeloso** [comment]
항상 친절하신 답변 감사합니다!

그럼 target_adgroup = r.json()[0] 에 있는
[0]은 현재 등록되어있는 광고그룹이 리스트를 의미하는 건가요?
예를들어 [0, 1, 2] 이런 식으로 바꾸면 첫번째, 두번째, 세번째 광고그룹을 GET 하는 건가요?

**Comment by naver-searchad** [comment]
@uomopeloso 
구체적인 개발방법이나 python 문법에 대해서는 답변 범위를 넘어서는 부분입니다.
api 종류에 따라 response 형태가 리스트 `[]` 일 수도 개별 객체 `{}` 일 수도 있으므로
각각에 맞게 이용하셔야 합니다.
참고로 위 샘플은,
response 타입이 리스트이므로 `[0]` 형태로 접근하면 된다는 예시일 따름입니다.
리스트 형태의 data를 어떻게 접근하고 처리할지는
사용하는 개발 언어 document를 참고하셔서 진행하시면 되겠습니다.
