### ISSUE TITLE
download URL

### ISSUE THREAD

**Issue by uomopeloso** [naver/searchad-apidoc#388]
안녕하세요.

statReport와 masterReport를 create와 get까지 했습니다.

get 호출시 나오는 downloadURL을 들어가면 웹상에

{"header":"X-API-KEY","title":"Missing Header","detail":"HTTP header required: X-API-KEY","status":403,"type":"urn:naver:api:problem:missing-header"}

이런 오류가 뜨는데 어떻게 해결해야하나요?

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

다운로드도 api에 사용되는 authorization을 동일하게 적용해 주셔야 합니다.
참고로 다운로드는 광고관리시스템 웹을 통해서도 받으실 수 있습니다.

**Comment by uomopeloso** [comment]
API 상으로 다운로드를 받아보고싶은데
보고서 다운로드하는 샘플코드같은건 없을까요?
어떤식으로 해야 다운로드가 될지 아예 감이 오지않습니다..

**Comment by uomopeloso** [comment]
"downloadUrl": "https://api.naver.com/report-download?authtoken=xi%2FKcMSgR8ObHgn93iRPGETVN%2Bdm1zNlclXqIojSoeWoqAiRf51%2BCLWgxEiLa5OFD2oUAPPrZXktn7GCtquWob%2BfzOIC7uN6"

이거 보고

uri = '/report-download'
method = 'GET'
r = requests.get(BASE_URL + uri,
                 params={
                     "authtoken" : "xi%2FKcMSgR8ObHgn93iRPGETVN%2Bdm1zNlclXqIojSoeWoqAiRf51%2BCLWgxEiLa5OFD2oUAPPrZXktn7GCtquWob%2BfzOIC7uN6"
                 },
                headers=get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID))

print("response status_code = {}".format(r.status_code))
print("response body = {}".format(json.dumps(r.json(), ensure_ascii=False, indent='\t')))

이렇게 해봤는데

response status_code = 200
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
<ipython-input-40-9ea7c4e89125> in <module>
      8 
      9 print("response status_code = {}".format(r.status_code))
---> 10 print("response body = {}".format(json.dumps(r.json(), ensure_ascii=False, indent='\t')))

~\anaconda3\lib\site-packages\requests\models.py in json(self, **kwargs)
    895                     # used.
    896                     pass
--> 897         return complexjson.loads(self.text, **kwargs)
    898 
    899     @property

~\anaconda3\lib\json\__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    346             parse_int is None and parse_float is None and
    347             parse_constant is None and object_pairs_hook is None and not kw):
--> 348         return _default_decoder.decode(s)
    349     if cls is None:
    350         cls = JSONDecoder

~\anaconda3\lib\json\decoder.py in decode(self, s, _w)
    338         end = _w(s, end).end()
    339         if end != len(s):
--> 340             raise JSONDecodeError("Extra data", s, end)
    341         return obj
    342 

JSONDecodeError: Extra data: line 1 column 10 (char 9)

이런 결과가 나오네요..

도와주시면 감사하겠습니다..
