### ISSUE TITLE
소재관련 api 확인 요청드립니다.

### ISSUE THREAD

**Issue by songxue77** [naver/searchad-apidoc#390]
안녕하세요.

현재 문서에 있는 GET /ncc/ads{?nccAdgroupId}를  사용중에 있습니다.

그룹아이디로 소재데이터를 조회하는 API인데요 여기서 리턴받은 status와 statusReason값이 상위에 있는 캠페인이 OFF상태여도 ELIGIBLE로 나오는데 문서에는 캠페인이 OFF상태일때 statusReason이 CAMPAIGN_ENDED로 나온다고 해서 문의 드렸습니다.

요청한 TransactionId는 BH7391UFHHIOI입니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

Wiki 내 [FAQ](https://github.com/naver/searchad-apidoc/wiki/FAQ#q-%EA%B0%81-%ED%95%AD%EB%AA%A9%EC%9D%98-%EC%83%81%ED%83%9C%EC%99%80-%EC%83%81%ED%83%9C%EC%9D%B4%EC%9C%A0-%EA%B3%84%EC%82%B0-%EB%B0%A9%EC%8B%9D%EC%9D%80-%EC%96%B4%EB%96%BB%EA%B2%8C-%EB%90%98%EB%82%98%EC%9A%94)를 확인해 주시면 소재(Ad)에 대한 상태 계산 내용을 확인하실 수 있습니다.
소재의 경우 소재의 상태만 확인하고 있습니다.

api 문서의 'statusReason' field 설명은
모든 경우의 값을 열거한 거라고 보시면 되겠습니다.

**Comment by songxue77** [comment]
네, 확인하였습니다. 감사합니다.
