### ISSUE TITLE
StatReport, MasterReport downloadUrl

### ISSUE THREAD

**Issue by uomopeloso** [naver/searchad-apidoc#391]
안녕하세요.
며칠 전에 downloadUrl로 질문드렸었는데 답변이 없으셔서 다시 올립니다.
Issues들 찾아봐도 downloadUrl에 대한 문제들은 다들 잘 해결하시는것 같은데,
초보라 그런지 이틀 넘게 해결법을 찾아봐도 다운로드할 방법을 못찾고 있습니다.
사이트 내에서 다운로드하는것 말고 파이썬 내에서 다운로드를 해보고 싶은데,
downloadUrl이용하는 샘플코드같은거 없을까요?
간단한 팁이라도 주셨으면 좋겠습니다...

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

API 관련 오류나 스펙에 대한 문의가 아닌
개발상의 문제, 샘플코드 요구 등에 대해서는
답변 가능 범위를 넘어서는지라 따로 답변드리지 않고 있으니
양해 부탁드립니다.

**Comment by uomopeloso** [comment]
죄송합니다..
