### ISSUE TITLE
그룹, 키워드의 상태계산시 요일/시간 타겟팅에 관련해 문의 드립니다.

### ISSUE THREAD

**Issue by songxue77** [naver/searchad-apidoc#392]
기존 문의글에 해당 질문이 있엇지만 2017년도 질문이라서 다시 한번 문의하고자 합니다.

그룹상태 요청시 요일/시간 타겟팅은 현재 같이 계산을 하고 있는지 확인 부탁드립니다.

같이 계산을 하고 있지 않다면 (GET /ncc/adgroups/{adgroupId} ) 해당 API에서 리턴받은 Target값으로 유출할 수는 있을지 문의드립니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

상태에서는 당연히 요일/시간을 반영하지 않습니다.
그룹의 target 객체를 이용해서 직접 계산하실 수는 있겠습니다.

**Comment by songxue77** [comment]
네, 답변 감사합니다.

많은 도움 되었습니다.
