### ISSUE TITLE
그룹 생성 시 "No permission to access the resource" 응답

### ISSUE THREAD

**Issue by lachelngose** [naver/searchad-apidoc#394]
POST api.naver.com/ncc/adgroups 으로 다 건 요청했는데,
일부는 성공, 일부는 아래 패턴으로 실패 응답을 받았습니다.
요청 수 제한으로 인해 실패한 건지, 아니면 다른 부분이 있는 건지 궁금합니다.

`404 Not Found, Publisher customerId: 129302.
 X-Transaction-ID: BHC6J1DV9HJ3A
Response Body: {"code":1018,"status":404,"title":"No permission to access the resource."}`

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

요청하신 그룹생성에 대해 확인해 보니, 요청한 캠페인이 삭제된 상태입니다.

감사합니다.
