### ISSUE TITLE
쇼핑검색광고 소재 등록시 

### ISSUE THREAD

**Issue by LimJW** [naver/searchad-apidoc#395]
{"signature":"b++nCVHVIaBBLLWbs7erJYJpiqVzorTE/v7cDo5NCRQ=","title":"Invalid Signature","status":403,"detail":"Signature 'b++nCVHVIaBBLLWbs7erJYJpiqVzorTE/v7cDo5NCRQ=' is invalid.","type":"urn:naver:api:problem:invalid-signature"}

API로 쇼핑검색 소재 등록시 위와같은 에러가 발생하는데 어떠한 권한이 없어서 그런건지 문의드립니다.
현재 테스트하고 있는 계정에 쇼핑몰과의 연동 인증은 완료된 상태여서 해당 비즈니스채널로 캠페인, 광고 등록은 가능한데 소재 생성에 어려움이 있습니다.

소재생성 API 호출시
{
	"nccAdgroupId": "그룹 ID",
	"customerId": "customerId",
	"type": "SHOPPING_PRODUCT_AD",
	"adAttr": {
		"useGroupBidAmt": true,
		"bidAmt": 50
	},
	"referenceKey": "referenceKey Value"
} 
위와 같이 전달하고 있습니다.

response X-Transaction-ID는 BHC8BFM5H9I07 입니다.

확인 부탁드립니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

invalid signature 오류에 대해서는 여러 원인이 있으므로
우선 여기 올라온 issue들 중에서 검색해 보시고 참고하시면 좋을 것 같습니다.
https://github.com/naver/searchad-apidoc/issues?q=%22Invalid+Signature
