### ISSUE TITLE
Naver keyword Download the data Via Report download URL

### ISSUE THREAD

**Issue by pradipraut737** [naver/searchad-apidoc#397]
hi Naver Team,

when i am trying to download the Keyword data from the Download URL it gives me error like header is missing, so could you please help me on this; how can we download the report URL data using Python code

![Report data](https://user-images.githubusercontent.com/64010395/79742865-1f450d80-8321-11ea-89f3-a02a56a16376.png)
![error message](https://user-images.githubusercontent.com/64010395/79743041-819e0e00-8321-11ea-98e3-df96bf5e26f1.png)

**Comment by naver-searchad** [comment]
Hello, this is Naver Search Ad' team.

As you can see those response messages, you need to follow 'search ad api usage' like other api you use.
'api.naver.com' always check authorization/authentication even if it is download url.

**Comment by pradipraut737** [comment]
Thank You Naver Team,

Today we have checked the 'search ad api usage', but in which we did not find the way to download the report form URL which is return from master report via get method. we have tried to add the url with header still we getting same error is header is missing, it would be great help if you explain the way we have download the report from url using the Python script

**Comment by naver-searchad** [comment]
@pradipraut737 
If you get the same error, your header doesn't have enough authorization information.
'Like other API use' as we mentioned before means that
you need to put api header parameters
```
"X-Timestamp"
"X-API-KEY"
"X-Customer"
"X-Signature"
```
and 'download url' goes to base url.
