### ISSUE TITLE
쇼핑검색 소재에 RESTRICT_KEYWORD_TARGET에 대한 java sample은 없나요?

### ISSUE THREAD

**Issue by sang-koo-yoon** [naver/searchad-apidoc#398]
쇼핑 검색 소제에 제외 키워드를 등록하려고 하는데요.

List<Target> targets = new ArrayList<>();

Target keywordTarget = targetMap.get("RESTRICT_KEYWORD_TARGET");
target = new HashMap<>();
target.put("keyword", "test");
keywordTarget.setTarget(target);

targets.add(keywordTarget);
adgroup.setTargets(targets);

Adgroups.update(rest, customerId, adgroup, "targetTime");

위에 Adgroups.update를 실행하려 하는데 targetTime 자리에 어떤 fields 명을 넘겨야 할지를 모르겠습니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

검색해 보시면 다음과 같은 이슈들을 참조하실 수 있습니다.
https://github.com/naver/searchad-apidoc/issues/259
https://github.com/naver/searchad-apidoc/issues/352
