### ISSUE TITLE
광고그룹의 표시URL을 가져오는 방법을 알고싶습니다.

### ISSUE THREAD

**Issue by sonh1230** [naver/searchad-apidoc#399]
광고그룹id를 이용해서 광고그룹을 가져오면
파라미터 중에 pcChannelKey와 mobileChannelKey이 있습니다.
이것들이 표시URL인가요?
아니라면 저 파라미터는 무엇을 의미하고 표시URL은 어떻게 get하는지 알고 싶습니다 ?

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

'표시 URL'이 맞습니다.
해당 광고그룹을 등록하실 때 이용한 'BusinessChannel'의 site url 정보입니다.

**Comment by sonh1230** [comment]
답변 감사드립니다!

헌데 광고그룹을 생성하거나 수정할 때 URL설정에 있어서 pc와 모바일이 따로 있지않은데
파라미터는 pcChannelKey와 mobileChannelKey 따로 있어서 관련하여 설명을 해주실 수 있나요?

**Comment by naver-searchad** [comment]
@sonh1230 
광고시스템에서 새 광고그룹을 생성하실 때 보면,
URL을 선택하고 난 뒤
`PC/Mobile 웹 사이트를 별도로 가지고 있습니다.` 옵션이 나오는 걸 보실 수 있을 겁니다.
즉 pc와 mobile 각각의 표시 URL 설정이 가능합니다.
