### ISSUE TITLE
여러개의 그룹에 같은 키워드를 등록시 광고 대상으로 선정된 키워드를 알 수 있나요?

### ISSUE THREAD

**Issue by younseunghyun** [naver/searchad-apidoc#4]
여러개의 그룹에 같은 키워드가 등록 될 수 있는데, status나 status_reason의 값으로 어떤 그룹의 키워드가 노출 대상으로 선정 되는지 알 수 있나요?

**Comment by naver-searchad** [comment]
@younseunghyun 노출시점마다 광고청취대상의 상황 (지면, 지역, 시간 등등 )과 각 광고그룹의 상황( 타겟팅, 예산 등등) 따라 선택되는 광고가 다르기때문에 API 호출시에는 어떤 그룹의 키워드가 선택되는지를 광고를 알려드리기가 힘듭니다. 참고 부탁드리겠습니다.

**Comment by younseunghyun** [comment]
답변 감사합니다 :)
