### ISSUE TITLE
자바 listByAdgroupId 에서 managedKeyword 문의

### ISSUE THREAD

**Issue by FreeEgo** [naver/searchad-apidoc#40]
Keyword[] keywords = Keywords.listByAdgroupId(rest, i, adgroupId);
을 사용해서 getNccKeywordId, getBidAmt 등은 값을 잘 받아오는데
getManagedKeyword().getpCPLMaxDepth(); 같은 경우에는
getManagedKeyword가 null로 받아와집니다. 
샘플에도 메니지키워드에 대한 정보는 없는데 원인을 알 수 있을까요?
아니면 키워드 노출수를 가져오는 다른 api가 있나요?

**Comment by naver-searchad** [comment]
안녕하세요 네이버 검색광고 입니다.
2017년 2월 1일 릴리즈 노트를 확인하시면 관련 변경사항들이 있습니다.
- http://naver.github.io/searchad-apidoc/#/release-notes
- `AdKeyword` 리소스 중 `managedKeyword` 속성이 더 이상 제공되지 않습니다.
- 기존에 제공되었던 `ManagedKeyword` API 통해서 `managedKeyword` 속성 조회 가능합니다.
  - 빠른시간내에 java 샘플 추가하도록 하겠습니다.
- 또한 기존 `pCPLMaxDepth` 속성이 `PCPLMaxDepth'로 변경 되었습니다.

**Comment by FreeEgo** [comment]
Keyword[] keywords = Keywords.listByAdgroupId(rest, i, adgroupId);

자바에서는 위와 같은 방법으로 ManagedKeyword를 가져올 수 있는 방법이 현재는 없는건가요?

지금 사용 가능한 방법이 있다면 예시를 보여주시면 감사하겠습니다.

**Comment by naver-searchad** [comment]
현재 java 샘플 기준으로 `managedKeyword` 가져오는 방법을 설명하도록 하겠습니다.
 - 클래스 수정 및 추가로 클래스 정의들이 필요합니다. (import는 빼고 기술하겠습니다.)

- `com.naver.searchad.api.model.Keyword.ManagedKeyword`에서 기존 pCPLMaxDepth 수정하기
```java
@JsonProperty("PCPLMaxDepth")
private Integer pCPLMaxDepth;
```

- `com.naver.searchad.api.rest.ManagedKeywords` 클래스 정의하기
```java
public class ManagedKeywords {
	/*
		관리키워드 목록 조회 GET /ncc/managedKeywords{?keywords}
	*/
	private static final String MANAGED_KEYWORD_PATH = "/ncc/managedKeyword";

	public static ManagedKeywordResponse[] listByKeywords(RestClient rest, long customerId, String[] keywords) throws Exception {
		String joinedKeywords = Arrays.stream(keywords)
				.collect(Collectors.joining(","));

		HttpResponse<String> response =
				rest.get(MANAGED_KEYWORD_PATH, customerId)
						.queryString("keywords", joinedKeywords)
						.asString();

		return rest.asObject(response, ManagedKeywordResponse[].class);
	}

	@Data
	public static class ManagedKeywordResponse {
		private String keyword;
		private Keyword.ManagedKeyword managedKeyword;
	}
}
```

- 관리키워드 및 `PCPLMaxDepth` 조회해보기
```java
private static void ManagedKeywordsSamples(RestClient rest, long customerId) throws Exception {
	// 관리키워드 조회
	final String[] keywords = new String[] {"꽃배달", "커피"};

	// 관리키워드 API 특성상 입력키워드, 관리키워드 속성 pair로 전달됩니다.
	final ManagedKeywords.ManagedKeywordResponse[] managedKeywordResponses = ManagedKeywords.listByKeywords(rest, customerId, keywords);

	Arrays.stream(managedKeywordResponses)
			.forEach(mkr -> {
				final String keyword = mkr.getKeyword();
				final Keyword.ManagedKeyword managedKeyword = mkr.getManagedKeyword();

				System.out.println("keyword : " + keyword + " PCPLMaxDepth : " + managedKeyword.getPCPLMaxDepth());
			});
}
```
  - 위 샘플코드를 실행하면 아래와 같은 결과가 나옵니다.
  ```
  keyword : 꽃배달 PCPLMaxDepth : 15
  keyword : 커피 PCPLMaxDepth : 15
  ```

java sample 작성해서 확인하실 수 있도록 할 예정이니 참고 부탁드립니다.

**Comment by FreeEgo** [comment]
감사합니다~

**Comment by FreeEgo** [comment]
위에 알려주신 소스대로 적용해본결과 키워드 10개정도를 하면 무리가 없이 돌아가는데
그룹 전체 키워드를 날릴경우 400에러가 뜨는데 왜 그런걸까요?
테스트 한 키워드 갯수는 164개 입니다.

**Comment by naver-searchad** [comment]
안녕하세요 네이버 검색광고 입니다.

`keywords` 의 입력이 대부분 한글이고 `GET` 요청을 해야 하므로 이를 `urlencode`를 하게 되면
`query string`이 길어지게 됩니다.

각 http client 마다 다르겠지만 url 전체 길이에 제한이 있습니다.
`400 에러`가 리턴되었다는건 client error 라고 보여집니다.

키워드를 100개 수준으로 적당히 잘라서 반복 호출 하시면 원하는 응답을 받으실 수 있을 것으로 생각됩니다.
