### ISSUE TITLE
키워드 일부노출 관련 정보를 얻을 수 있는 방법이 있나요?

### ISSUE THREAD

**Issue by kaorimikage** [naver/searchad-apidoc#400]
광고계정에서 키워드명 옆에 일부노출이라고 뜨고 해당 링크를 클릭하면 미노출 매체 리스트가 표시됩니다. 해당정보는 group 단위 정보가 아니고 keyword 단위 정보이며 AdKeyword 에서는 해당 정보를 주지 않습니다.

혹시 미노출 매체 리스트를 얻을 수 있는 API가 존재하거나 앞으로 계획이 있는지 알고 싶습니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

말씀하신 대로 keyword 단위의 정보입니다.
즉 해당 keyword가 해당 매체에서 광고 검색어로 동작하는지에 대한 정보이므로
AdKeyword 와는 전혀 관계가 없습니다.

그리고 이 정보는 광고시스템 상에서만 제공되며 API로는 제공되지 않습니다.
