### ISSUE TITLE
광고주 정보 리스트 호출시 ( customer-links ) 시 clientLoginId 정보중 뒤에 숫자가 붙는 id는 뭔가요?

### ISSUE THREAD

**Issue by kwon2s** [naver/searchad-apidoc#401]
안녕하세요
api 체크중 이상한 내용이 나와서요

질문 1
Transaction-ID : BHKN66BNHHH0F

customer-links 호출시
권한이 있는 광고주 리스트가 나오는데요 
[clientLoginId] => *******.1316565

이런식으로 뒤에 숫자가 붙습니다.
다른 데이터랑 차이점으로는 클라이언트 접근 권한( clientEnable  : 0 ) 이던데요
접근권한이 없을때 저렇게 해놓으셨나요??

질문2
customer-links 호출로 업체리스트는 나오는데요
회사에 속한 마케터들 리스트를 볼수 있는 api 는 없나요?
문득 생각이 들어서 이것도 문의를 합니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

1. 탈퇴한 계정인 경우입니다.
2. 호출 응답은 업체리스트가 아니라 광고 계정 리스트입니다. 업체와 마케터 단위의 별도 관리 체계는 없습니다.

**Comment by kwon2s** [comment]
답변 감사합니다.
