### ISSUE TITLE
keywordstool 파라메터 문의

### ISSUE THREAD

**Issue by jklee0219** [naver/searchad-apidoc#403]
hintKeywords 파라메터에 '홍길동 떡볶이' 와 같이 중간에 공백이 들어간것은 어떻게 처리하여야 할까요? 애러가 나네요

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

검색광고 키워드에는 공백이 허용되지 않습니다.
웹에서 키워드를 등록할 때나 키워드도구를 이용할 때는
공백이 입력되더라도 이를 제거하고 사용되기 때문에 문제가 없지만
api를 직접 이용해 파라미터값을 입력하는 경우에는
직접 공백을 제거해 주셔야 합니다.
