### ISSUE TITLE
쇼핑검색유형 소재 이미지 수정

### ISSUE THREAD

**Issue by LimJW** [naver/searchad-apidoc#404]
쇼핑검색 유형의 캠페인에 등록된 소재는 쇼핑몰에 등록된 이미지를 바로 가져오기 때문에 이미지에 텍스트가 있는 경우 노출이 불가능한기 때문에 소재 변경을 해야하는데 API로 소재 변경 방법 문의드립니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

쇼핑검색 소재의 경우 광고 노출용 이미지를 별도 등록하려면
일단 등록된 소재에 대해 update(put) 요청으로 ad field를 수정하셔야 합니다.
http://naver.github.io/searchad-apidoc/#/operations/PUT/~2Fncc~2Fads~2F%7BadId%7D%7B%3Ffields%7D
(api 문서상에는 `fields=ad`가 나와 있지 않음)
이 때 ad 객체에 imagePath를 넣어 주셔야 하는데요
이 imagePath는 광고관리 화면에서 이미지를 등록한 후 만들어지기 때문에
api 상으로 모두 control이 불가능합니다.
api 문서상 쇼핑소재 업데이트에 대한 내용이 명기돼 있지 않은 이유이기도 합니다.
쇼핑소재 업데이트는 광고관리 화면을 통해 수행하시길 권장합니다.

**Comment by LimJW** [comment]
쇼핑검색 유형의 경우 캠페인, 그룹, 소재 등 각각 API로 제어 가능한 범위가 어디까지인가요??

**Comment by naver-searchad** [comment]
@LimJW 
api 로 모두 다 가능은 합니다.
다만 소재 관련해서는 등록과 수정 상에서 필요한 연동 데이터들이 있고
이 정보들을 웹을 통해서 직접 구하셔야 하므로
api로 구현하기에는 다소 어려울 수 있다는 의미입니다.

**Comment by LimJW** [comment]
@naver-searchad 
쇼핑광고의 소재를 등록 및 수정시 필요한 연동 데이터들도 API로 제공이 되는건가요??
제공되는거라면 해당 API를 기반으로 웹 화면을 별도로 구현한다면 사용이 가능하다고 봐도 되는건지 문의드립니다.

또한, 파워링크 유형을 제외한 나머지 유형들은 API로 모두 다 제어가 가능은하지만 정식적으로 API 문서에 명기하여 API를 제공하는건 아니기 때문에 네이버의 내부 정책에 따라 언제든 변경될 가능성이 있다는걸 인지하고 사용하면 문제될 건 없는건지도 문의드립니다.

**Comment by naver-searchad** [comment]
@LimJW 
물론 API로 제공되지 않습니다.
제공되지 않으므로 '제어가 가능한지' 등 이에 대한 문의는
저희 답변 범위에 적합하지 않다고 보시는 것이 좋겠습니다.
