### ISSUE TITLE
키워드 품질지수 검색시 한번에 키워드id를 여러개 넘기는 방법은 없나요?

### ISSUE THREAD

**Issue by kwon2s** [naver/searchad-apidoc#405]
안녕하세요
키워드 품질지수 관련 문의를 드릴려고 합니다.

현재 키워드를 호출을 했을때 품질 지수를 
            [nccQi] => Array
                (
                    [qiGrade] => 3
                )
이런식으로 주고 있는데요

그룹 id 로 검색을 제외한
개별적인 키워드로 검색시에 일일이 nccKeywordId 값을 넘겨서 호출을 해야 품질지수 정보를 받을수가 있는데요

한번에 nccKeywordId  100개 정도 를 호출을 할수 있는 기능이 있나해서 문의를 드립니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

http://naver.github.io/searchad-apidoc/#/operations/GET/~2Fncc~2Fkeywords%7B%3Fids%7D
ids 파라미터에 콤마 구분자로 복수의 keyword id를 넣어 주시면 됩니다.
다만 get 요청의 query parameter이므로 http url 상의 길이 제한이 있으므로
id를 너무 많이 입력할 경우 length 오류(api 오류가 아닌 http 오류)가 발생할 수 있습니다.

**Comment by kwon2s** [comment]
답변 감사합니다.
