### ISSUE TITLE
시군구 및 동 코드는 어디서 확인할 수 있나요?

### ISSUE THREAD

**Issue by lachelngose** [naver/searchad-apidoc#406]
행정동 단위까지 타겟팅 가능한 것으로 알고있는데, 위키에는 시도 코드만 나와있는 것 같습니다.
코드표를 어디서 확인할 수 있나요?
그리고 행정동의 경우 가끔 변동이 있는걸로 알고있는데 네이버에서도 반영하는지,
반영한다면 업데이트는 어떻게 확인할 수 있는지 궁금합니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

아쉽지만 현재로선 오픈된 내용이 없습니다.
불편하시더라도 광고시스템 지역설정 화면을 통해 target 동 code를 확인해서 사용해 주시기 바랍니다.

행정동 변동에 대해서는 변경 내용에 따라 다를 수 있겠지만
기본적으로는 마이그레이션이 가능한 범위 내에서는
공지 및 자체 업데이트를 진행합니다.
