### ISSUE TITLE
/ncc/adgroups 의 selector=NEXT 파라미터 문의

### ISSUE THREAD

**Issue by kwon2s** [naver/searchad-apidoc#407]
안녕하세요

질문 1 : 
api  : /ncc/adgroups 
call url :  https://api.naver.com/ncc/adgroups?recordSize=1000&selector=NEXT

그룹 리스트 호출시 별도로 캠페인 id 를 지정을 안하면
해당 커스터머 id 의 모든 그룹 리스트를 반환을 하고 있는데요.

만약 그룹이 1000개가 넘을경우 selector =NEXT 로해서 1001 부터의 데이터를 받을려고 했는데
0 ~ 1000 의 동일한 데이터를 그대로 출력을 하고 있습니다.

아마도 제가 잘못 이해를 해서 그런거 같은데 
사용법이 어떻게 되나요?
selector =NEXT  사용이 제가 이해를 정확히 하고 있는게 맞나요?
기본 으로 지정을 안할시 최대 0 ~ 1000 개를 리턴을 하고
selector =NEXT  를 추가로 전달할경우 1001 ~ 2000 순서의 데이터를 리턴을 하고

질문 2 : 각 캠페인별 생성할수 있는 그룹의 수는 어떻게 되나요?
키워드는 각 그룹별 1000개씩 생성이 되고
그룹은 각 캠페인별 동일하게 1000 개씩 생성인가요??

해당 부분 문의 드립니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

NEXT를 이용하기 위해서는 이전 조회된 결과의 마지막 id를 baseSearchId에 넣어 주셔야 합니다.
즉 해당 id부터 recordSize 만큼 조회됩니다.

각 entity들의 제한 수는 다음 도움말에서 확인하실 수 있습니다.
https://saedu.naver.com/help/faq/ncc/view.nhn?faqSeq=38
