### ISSUE TITLE
네이버 브랜드검색의 소재영역별 데이터를 불러오는 API가 존재하나요?

### ISSUE THREAD

**Issue by kingnad** [naver/searchad-apidoc#408]
네이버 브랜드검색의 소재영역별(썸네일, 제목, 부가제목 등) 데이터를 API로 불러오고 싶은데요.

우선 소재 데이터를 가져오기 위해

GET /ncc/ads/{adId}

해당 API를 호출하여 나온 결과 데이터가

"type":"BRAND_SEARCH_AD","ad":{"dittoId":"crtv-q9jeso6bk7uv","thumbnail":"https://ssl.pstatic.net/adimg2.search/o/tachikoma/q9j/crtv-q9jeso6bk7uv.png"}

위와 같이 알아볼 수 있는 데이터는 썸네일 URL 데이터 밖에 없습니다.

혹시 영역별 수치를 불러올 수 있는 API가 있으신지, 있다면 공유 부탁드리겠습니다.
ㅠㅠㅠㅠㅠ

영역별이라 함은, 이미지영역/제목/부가제목 등등의 클릭이 가능한 영역을 뜻합니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

문의하신 내용은 지원하지 않고 있습니다.
브랜드검색은 파워링크 상품처럼 대량으로 광고를 관리하거나 실시간 관리하는 상품이 아니므로
광고관리시스템 웹을 통해서 충분히 필요하신 정보와 기능을 이용하실 수 있다고 생각됩니다.

더군다나 브랜드검색 소재는
템플릿과 스키마 등 소재를 구성하고 관리하는 요소가 많고 복잡해서
모든 기능을 API로 지원해 드리기는 매우 어려우니 양해해 주시기 바랍니다.
