### ISSUE TITLE
다차원 보고서 문의드립니다.

### ISSUE THREAD

**Issue by LimJW** [naver/searchad-apidoc#409]
광고시스템상에서 제공해주시는 다차원 보고서의 데이터가 필요한데 API로 제공을 하고있지 않은 것 같습니다. 

이전에 올라온 비슷한 유형의 질문들을 보다보니 답변주신 것 중에 다차원 보고서가 필요할 경우 동일하게 가공 할 수 있는 데이터 계산 방식 및 기준 등을 안내해 주신다는 답변을 보았습니다.

다차원 보고서의 데이터와 동일한 데이터가 필요하여 가이드 부탁드립니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다. 

다차원보고서의 데이터는 API로 제공하지 않으며, 향후에도 제공할 계획이 없습니다. 

다차원보고서는 광고주센터 이용자 분들이, 광고 효과 분석을 광고주 본인이 분석하고 싶은
관점으로 여러가지 지표를 조합해서 볼 수 있는 광고주센터의 편의 서비스이며,
API보고서는 원본 raw data에 가까운 데이터를 제공하므로,
이를 가공, 개발하여 다차원보고서에서 제공하는 대부분의 데이터를 만들 수 있습니다. 

또한, 데이터의 유무 관점에서도 다차원보고서에서 제공하는 데이터가, 
검색광고 API에서 제공 안되는 것은 거의 없습니다. 

API보고서 데이터를 통해서 개발 진행해 보시고, 그래도 개발 진행이 어렵다면,
"구체적으로 다차원보고서의 어떠한 데이터가 필요한지, 어떻게 구현하고 싶으신지 등의 샘플' 을 문의 주시면 
확인 후에 해당 되는 개발 가이드를 드릴 수 있을 것 같습니다.
