### ISSUE TITLE
시간전략 상태값 문의

### ISSUE THREAD

**Issue by FreeEgo** [naver/searchad-apidoc#41]
네이버 검색광고 시스템에 들어가보면 시간단위로 광고를 콘트롤 할 수 있는

시간전략이라는게 있는데 이걸 On/Off 하게 되었을떄

API에서 해당 키워드의 시간전략 상태값을 받아올 수 있는 방법이 있나요?

**Comment by naver-searchad** [comment]
시간/요일 타겟팅은 그룹에 있으며 아래의 API를 이용하여 타겟팅을 조회할 수 있습니다.
http://naver.github.io/searchad-apidoc/#/operations/GET/~2Fncc~2Ftargets%7B%3FownerId,types%7D

**Comment by FreeEgo** [comment]
좀더 상세히 질문 드립니다.

네이버 검색광고 시스템으로 시간전략 설정 후 
시간전략으로 off가 확인된 키워드를 
API로 캠페인, 그룹, 키워드에 상태를 확인하니
"status":"ELIGIBLE" 으로 확인됩니다.

시간전략으로 off된 키워드의 실제 status를 확인하는 방법이 있나요?

**Comment by naver-searchad** [comment]
현재 그룹, 키워드의 상태계산시 요일/시간 타겟팅은 같이 계산을 하고 있지 않습니다.
(시간 변경에 따라 상태값의 변화가 심하기 때문에 예를 들어 59분 30초에 계산한 값이 30초 뒤에는 유효하지 않을수 있습니다.)
요일/시간타겟팅 포함 계산에 대한 부분은 내부 협의중에 있습니다.
