### ISSUE TITLE
statReport의 null keyword 문의

### ISSUE THREAD

**Issue by githubcnsbs** [naver/searchad-apidoc#410]
statReport로 AD_DETAIL 및 AD_CONVERSION_DETAIL로 실적을 받아오고 있습니다.

이 중 일부 data의 
 . keyword id = '-' && keyword name이 null인 경우
 . keyword id는 정상적으로 존재하나 keyword name만 null인 경우
의 데이터가 내려오고 있습니다.

이 부분은 어떤 경우인지 문의 드립니다. (가장 최근 데이터인 5-24일자 data에서도 발생하고 있습니다)

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

먼저, 광고가 노출되는 영역에 따라(가령 컨텐츠 영역) 검색 키워드가 없을 수도 있습니다.
이 때 keyword name은 없게 됩니다.
그리고 등록하신 광고의 상품종류에 따라(파워링크, 쇼핑검색, 컨텐츠, 브랜드 등)
등록 키워드(keyword id)가 없게 됩니다.
이 두가지 조합으로 보시면 되겠습니다.

**Comment by githubcnsbs** [comment]
네, 감사합니다.
