### ISSUE TITLE
광고 입찰 API 가 갑자기 작동이 안되어 문의드립니다.

### ISSUE THREAD

**Issue by drlee7-cray** [naver/searchad-apidoc#411]
네이버 광고입찰 API 가 갑자기 작동이 안되서 문의드립니다. 
( NAVER Search Ad API - Ad - create )
관련 원인을 알 수 있을까요?

평소에 잘 되던 API였는데 갑자기 오류코드 3830 을 리턴하는군요.
오류메시지는 'Invalid ad type.' 입니다.

테스트해보실수 있는 URL 입니다.

http://scrap.ngoods.kr/naverApi/ad_add.ajax.php?nccAdgroupId=grp-a001-02-000000002330398&number=1000033863&bidAmt=50&test=1
-----------------------------------------------------------------------------------------------
php 소스 일부

    $data = array(array(
      "customerId"=>$this->api->customerId,
      "nccAdgroupId"=>$nccAdgroupId,
      "type"=>"SHOPPING_PRODUCT_AD",
      "adAttr"=>array(
        "useGroupBidAmt"=>false,
        "bidAmt"=>$bidAmt*1
      ),
      "ad"=>$ad_json,
      "referenceKey"=>$referenceKey // 네이버 쇼핑상품 ID
    ));
    $ads = $this->api->POST('/ncc/ads', $data, array("isList"=>true));

RestFull 소스 내의 생성되는 json 데이터는 아래와 같이 2가지 유형 모두 테스트해보았습니다.

[{"customerId":14196,"nccAdgroupId":"grp-a001-02-000000002330398","type":"SHOPPING_PRODUCT_AD","adAttr":{"useGroupBidAmt":true,"bidAmt":50},"ad":[],"referenceKey":"22923965417"}]

[{"customerId":"14196","nccAdgroupId":"grp-a001-02-000000014965493","type":"SHOPPING_PRODUCT_AD","adAttr":{"useGroupBidAmt":false,"bidAmt":50},"ad":"{\"pc\":{\"final\":\"https:\\\/\\\/www.ngoods.com\\\/goods\\\/goods_view.php?goodsNo=1000052217&ref=naver_open\"},\"mobile\":{\"final\":\"https:\\\/\\\/m.ngoods.com\\\/goods\\\/goods_view.php?goodsNo=1000052217&ref=naver_open\"},\"headline\":\"ngoods\",\"description\":\"ngoods\"}","referenceKey":"22907059590"}]

배열이니 당연히 isList=true 파라미터는 추가했습니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

올려 주신 정보상으로 봤을 때 쇼핑검색광고 유형의 데이터가 아닌 파워링크 정보로 보이는 것들이 보입니다.
우선,
쇼핑검색광고 유형의 소재 등록을 API로 했을 때 안되는 건 아니지만
공식 문서를 보시면 아시다시피 정식으로 지원하는 건 아닙니다.
그리고 잘 되다가 안되는 이유는,
기존에는 validation 체크가 충분치 못해서 잘못된 정보라도 그대로 입력이 됐었던 것 같은데요
아마 최근에 이런 데이터들이 발견되면서 validation을 강화한 것으로 보입니다.

다시 말씀드리지만
API로는 임의의 데이터들을 넣을 수 있기 때문에
가급적 센터 광고관리 화면을 이용해 주시고
API를 사용하시더라도 광고관리 화면 상에서 전달되는 데이터를 잘 확인 후 이용해 주시기 바랍니다.

**Comment by drlee7-cray** [comment]
타개발건으로 이제야 확인해서 잘 해결되었습니다.
답변 감사합니다.
