### ISSUE TITLE
StatReport 다운로드 시 특정 계정만 다운로드가 안됩니다

### ISSUE THREAD

**Issue by lhw8611** [naver/searchad-apidoc#413]
2000개 정도의 계정의 StatReport를 다음날 오전 4시에 배치를 돌려 모두 다운로드받아 DB에 저장합니다.
그런데 특정 일자에 특정 계정은 늘 다운로드가 안되네요..
그래서 다음날 출근해서 다시 다운로드를 해보면 정상적으로 들어갑니다.

statReport의 status가 계정마다 built 상태로 되는 것이 달라서 그런건가요?
왜 새벽 4시가 아닌 다음 날엔 정상적으로 다운로드가 되는지,
왜 어떤 계정은 늘 다운로드가 잘 되는데  어떤 계정은 늘 안되는지 궁금합니다!

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

리포트는 계정과 report type별로 요청시마다 각각 생성되므로
built 상태 시점은 다를 수 있습니다.
따라서 built 상태를 확인 후 다운로드를 진행하셨다면 문제가 없을 것으로 생각됩니다.

**Comment by lhw8611** [comment]
StatReport를 생성하고 none일 경우에만 그냥 넘어가고 none이 아닐땐(regist,running,error 상태) built 상태임을 확인하고 다운로드를 진행하게 코드를 바꿔봤는데
6월 12일자 데이터가 안들어가있어 오늘 다시 돌려보니 들어가더라구요..

제 코드실수인지 다른 무언가 있는지 궁금합니다.

**Comment by naver-searchad** [comment]
@lhw8611 
built 상태라면 다운로드 되는 스펙입니다. 특별히 다른 내용은 없습니다.
