### ISSUE TITLE
디스플레이 광고 관련 문의드립니다.

### ISSUE THREAD

**Issue by lachelngose** [naver/searchad-apidoc#414]
안녕하세요,
검색광고 API 를 활용해서 서비스를 제공하고 있는데요,
혹시 디스플레이광고도 API 가 있을까 해서 문의드립니다.
감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

디스플레이광고의 경우 현재 검색광고와 같은 API 제공은 없는 것으로 알고 있습니다.
다만 문의해 주신 내용이 검색광고에 해당하지 않으므로
정확하거나 최신현황에 대한 답변이 아닐 수도 있음을 양지해 주시기 바랍니다.
