### ISSUE TITLE
권한 설정과 계정생성 관련해서 문의드립니다.

### ISSUE THREAD

**Issue by sonh1230** [naver/searchad-apidoc#415]
안녕하세요~2가지 질문이 있습니다.

api를 통해서
1. 네이버 검색광고 계정을 생성이 가능한가요?
2. put이나 post 요청으로 권한부여나 권한수락이 가능한가요?

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

계정 생성시 필요한 인증 등 관련 액션들이 있기 때문에 API로는 구현이 불가능합니다.
권한에 대한 내용도 해당 계정으로 직접 로그인 해서 수행해야 하는 액션이므로
역시 API로는 지원이 불가합니다.

**Comment by sonh1230** [comment]
답변 감사드립니다.

추가적으로 하나만 더 질문드리겠습니다.

광고시스템-도구-api 사용관리 에서 api사용신청을 하는 방법외에
본인의 customerId를 알 수 있는 방법은 없나요?

**Comment by naver-searchad** [comment]
@sonh1230 
광고시스템을 접속하시면 url path 상에서 customer id 값을 확인 가능합니다.

**Comment by sonh1230** [comment]
하다보니 계속 궁금한게 생기네요...

faq에서 제공해주시는 지역코드외에 읍면동 등의 더 구체적인 지역코드를 받아 쓰고싶어서
지도api도 살펴봤지만 마땅한 방법이 없더군요

광고시스템상에서 network탭을 봤을때는
/addressRcode?queryKeyword={검색어}  라는 uri로
지역코드를 받아오던데 파이썬으로 실행해보니 401오류가 뜨네요

해당 uri를 쓰기위해서는 광고api의 시크릿키나 api키와는 다른 권한key가 필요해보이는데 혹시 알 수 있을까요?
