### ISSUE TITLE
클릭초이스플러스 및 상품광고도 현재 API에서 정보를 제공하고 있는지요?

### ISSUE THREAD

**Issue by kaorimikage** [naver/searchad-apidoc#416]
클릭초이스플러스 및 클릭초이스상품광고에 대한 정보를 현재 API에서 제공하고 있는지 확인하고 싶습니다.

구 검색광고 시스템에 별도의 API 관리 페이지가 존재하는데 신청해도 alert으로 오류가 발생했습니다 메세지만 표시됩니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

현재 제공되고 있지 않습니다.
구 광고시스템 상의 메뉴는 제거될 예정입니다.
