### ISSUE TITLE
/stats에서 데이터 가져올 때 문의사항입니다.

### ISSUE THREAD

**Issue by DJDJ326** [naver/searchad-apidoc#417]
키워드의 노출수(impCnt), 클릭수(clkCnt), 클릭률(ctr) 데이터가 PC와 Moblic이 합쳐진 데이터인데

하나의 지표(노출수, 클릭수, 클릭률 등)에 PC, Moblic 따로 따로 받아올 수는 없나요?

있다면 샘플데이터 부탁드립니다 ㅠㅠ

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

stat api에서는
`breakdown=pcMblTp`
파라미터를 이용해서 상세 지표를 조회할 수 있습니다.

**Comment by DJDJ326** [comment]
r = requests.get(BASE_URL + uri, params={'ids': 'cmp-xxxx-xx-xxxxxxxxxxxxxxxxxx',
                                        'fields' : '["clkCnt","impCnt","salesAmt", "ctr", "cpc"]',
                                        'timeRange':'{"since":"2020-06-02","until":"2020-06-08"}',
                                        'timeIncrement':'allDays',
                                        'breakdown':'pcMblTp'  } , headers=get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID))

이런식으로 진행했는데 11001 오류가 뜨네요 ㅠㅠ 수정되야할 부분이 있나요?

**Comment by naver-searchad** [comment]
@DJDJ326 
403이나 404 등 오류가 아니라면 파라미터 상에는 문제가 없어 보입니다.
캠페인 id가 정확한지 또는 삭제된 상태인지 등 확인이 필요해 보이네요.
적어주신 코드 외에 상세한 response 내용을 모두 알려 주시면 좋겠습니다.

**Comment by DJDJ326** [comment]
넵 캠페인 ids는 여기 질문할때만 x로 변경한 것으로 문제 없습니다.  새로운 코드 추가 전 데이터들은 잘 불러와졌습니다. ㅠㅠ

print("response status_code = {}".format(r.status_code))
print("response body = {}".format(r.json()))  실행 시 


results: response status_code = 400, 
response body = {'code': 11001, 'message': '�߸��� �Ķ���� �����Դϴ�.'} 로 출력됩니다.

**Comment by naver-searchad** [comment]
@DJDJ326 
status code가 400이네요.
파라미터 상 잘못된 점이 있는 듯합니다.
올려주신 코드상으로는 파악이 어려우며
실제 생성된 request 내용이 필요해 보입니다.
response 중 transaction id가 있을 텐데요 함께 올려 주시면 확인이 가능하겠습니다.
그리고 올려주신 메시지가 인코딩 문제로 깨어진 듯한데
혹시 이것도 원문 확인 가능하시면 추가내용 부탁드립니다.

**Comment by DJDJ326** [comment]
'response 중 transaction id가 있을 텐데요 함께 올려 주시면 확인이 가능하겠습니다.'
파이썬을 다뤄본적이 거의 없어서 이부분을 어떻게 찾아서 보여드릴지 모르겠네요..

**Comment by naver-searchad** [comment]
@DJDJ326 
http://naver.github.io/searchad-apidoc/#/samples
여기 보시면 api의 response header에
`x-transaction-id: AJ83GTFPN7FR2`
와 같은 정보가 리턴됨을 보실 수 있습니다.
response의 header를 모두 올려 주셔도 됩니다.

**Comment by DJDJ326** [comment]
계속 끙끙대다 코드를 재실행 하니 정상작동 합니다. 제 실수인듯 하네요 ㅠㅠ 
긴 시간 감사드립니다!!
