### ISSUE TITLE
API 호출 제한에 대해 질문드립니다.

### ISSUE THREAD

**Issue by uomopeloso** [naver/searchad-apidoc#419]
안녕하세요.
FAQ에서 초당 호출 제한이 있는 것은 확인했는데, 일일 호출 제한이 있는지 궁금합니다.
일일 호출 제한이 있다면 각 API 별로 다른지,
초당, 일일 호출 제한 말고도 다른 호출 제한 기준이 있는지
알려주시면 감사하겠습니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

일일호출 제한이 있다면 FAQ에 명기를 해 놓았겠지요.
기본적인 시스템 과부하 제한이라고 보시면 되겠습니다.

**Comment by uomopeloso** [comment]
답변 감사드립니다.
