### ISSUE TITLE
Java API 403에러 문의

### ISSUE THREAD

**Issue by FreeEgo** [naver/searchad-apidoc#42]
Adgroup[] adgroups = Adgroups.listByGroupId(rest, customerId, groupId);
============================================================
위와 같은 소스를 작성하여 테스트 하는 도중 2~3번 성공 후 계속 아래와 같은 에러가 발생합니다.
원인이 뭔지 궁금합니다.
============================================================
java.lang.Exception: 403 Forbidden. X-Transaction-ID: AQD93BEHPPESL, Response Body: {"timestamp":"1487841220234","detail":"Request has expired.","status":403,"title":"Invalid Timestamp","type":"urn:naver:api:problem:invalid-timestamp"}

**Comment by naver-searchad** [comment]
해당 오류는 요청 메시지에 포함된 `X-Timestamp` 값이 기준 시간 이상 차이날 경우에 발생합니다.

timestamp 값을 생성하고 실제 호출하기까지 오래걸리거나,
클라이언트의 시간이 표준 시간 서버와 동기화가 제대로 안되어있을 경우에 주로 발생합니다.

우선 아래 문서에 있는 시간 서버 또는 공개된 다른 시간 서버와 NTP 시간 동기화를 하시기 바랍니다.
http://time.ewha.or.kr/domestic.html

이후에도 동일한 오류가 발생할 경우에는 `X-Timestamp`를 최대한 호출 직전에 생성하도록 하거나 네트워크 지연이 있는지 확인해볼 필요가 있습니다.

**Comment by FreeEgo** [comment]
시간동기화도 하고  Restclient 호출하고 바로 Api 명령어를 실행하는데도 같은 오류가 발생합니다. 네트워크 지연은 tracert api.naver.com으로 확인하면 될까요?
