### ISSUE TITLE
생성하는 보고서 갯수 제한있나요

### ISSUE THREAD

**Issue by qkdnsxl** [naver/searchad-apidoc#420]
[reportJobId] => 907468544
    [statDt] => 2020-06-29T15:00:00Z
    [updateTm] => 2020-06-29T15:00:00Z
    [reportTp] => SHOPPINGKEYWORD_DETAIL
    [status] => NONE
    [downloadUrl] =>
    [regTm] => 2020-07-01T03:18:24Z
    [loginId] => 아이디

안녕하세요.
잘 되었는데 오늘부터 안되내요.
예전에 30개라고 어디서 본것 같은데 맞나요?
감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

대용량보고서의 보고서 갯수제한은 있지만, 
가장 오래된 보고서를 삭제하고 새 보고서를 생성하기 때문에
갯수제한으로 오류가 리턴되지는 않습니다. (동시 생성요청인 경우가 아니라면)

문의하신 jobId의 결과는 '지표없음'으로 확인되는 것 같습니다.
