### ISSUE TITLE
RelKwdStat과 Estimate 결과 문의

### ISSUE THREAD

**Issue by githubcnsbs** [naver/searchad-apidoc#421]
RelKwdStat의 Impressions, Click과Estimate.PerformanceBulk의 Impressions, Click, 실제 과거 1개월간의 Keyword Impressions, Click이 모두 다르며 차이가 많이 나는 부분이 있어 어떤 차이인지 문의 드립니다.

아래는 현재 운영중인 광고의 1개 키워드 실 예로, 6월 1일 ~ 6월31일까지의 실적과 동일키워드를 RelKwdStat과 Estimate.PerformanceBulk(10만원 bid)를 호출해 본 예시입니다.

|         | Impressions           | Clicks  |
| ------------- |:-------------:| -----:|
| 본 키워드의 저희쪽 지난달 PC에서만 실제 실적      | 9만  | 250  |
| RelKwdStat      |   10,710     |   256 |
| Estimate PerformanceBulk (10만원 bid, Device.PC) | 3981      |    286 |

* 해당 키워드는 파워링크로 세팅된 키워드입니다.

 위 예시에서 사용한 키워드는 실제로 지난달 저희쪽 광고에서만 9만건 이상의 Impression이 발생하는 키워드이며 상반기에 평균 4 ~ 5만정도의 Impression이 나오는 매우 일반적인 키워드입니다. (해당 키워드뿐 아니라 Impression이 월평균 수만~수십만이 나오는 다른 키워드 몇개를 테스트해봐도 결과는 비슷합니다)
 해당 키워드를 RelKwdStat으로 검색시에는 1만(monthlyPcQcCnt=4290, monthlyMobileQcCnt=6420) 정도의 Impression을 예측하고 있으며, Estimate performanceBulk를 이용하여 bidding가를 max(10만)으로 했을때에는 오히려 Impression이 RelKwdStat로 조회한 Impression 보다도 낮게 나옵니다.

이 세가지의 차이를 이해할 수 있었으면 합니다. 
API의 결과가 너무 차이가 많이나고 있어 이런 현상이 나타나는 이유에대해 설명부탁드립니다.

**Comment by githubcnsbs** [comment]
RelKwdStat과 Estimate를 어느 정도 신뢰하고 사용해야 할지가 필요하여 문의한 내용입니다.
답변부탁드립니다.

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API 입니다. 

답변이 늦어 죄송합니다. 

설명을 드리기 앞서 잘못 알고 계시거나 안내가 필요한 부분부터 질문 주신 내용에 대한 상세로 이어지는 형태로 
설명드리겠습니다.

우선 impression과 query count를 혼용하여 말씀해 주셨는데요. 
기본적인 사항이라 잘알고 계시리라 생각됩니다만 양 지표의 정의는 다르며 RelKwdStat에서 제공되는 query  
count를 광고 impression과 동일한 성격으로 간주하고 이야기를 이어나가기는 조금 무리가 있다는 점 전제합니다.

RelKwdStat에서 제공되는 데이터는 예측 데이터가 아닌 과거 데이터의 실측치로서 문의 주신 monthlyPcQcCnt나 monthlyMobileQcCnt는 각각 네이버 통합검색(pc), 네이버 모바일검색(모바일)에서 최종 데이터 생성일로부터 
과거 30일간의 합산 값입니다. 또한 10회 미만인 경우 <10, 10회 이상인 경우 일정 수준의스케일링을 적용한 값을 제공드리며
스케일링 방식은 공개하지 않습니다. 

반면 Estimate Performance 혹은 Estimate Performancebulks의 데이터는 28일 기준으로 제공드리는 데이터 입니다. 

데이터의 생성 방식은 과거 장기간의 과거 입찰가별 노출 분포 데이터를 기반으로 표준이 되는 예측 통계 모델을 만들고 
이 모델에 최근 28일간의 데이터 분포를 반영하여 복수의 후보 예측 모델을 생성한 다음 다시 이 후보들을 검증하여 최종적으로 하나의 예측 모델을 채택하여 제공되는 형태입니다. 이때 제공되는 값의 기준 매체는 PC는 네이버 통합검색, 모바일은 네이버 모바일검색 매체이며 기준 기간은 향후 28일입니다. 데이터 생성주기는 주단위로 는 한국시간으로 매주 일요일 업데이트 됩니다. 

질문에서 말씀하신 것과 같이 Estimate performance에 입찰가로 최대 입찰가를 제시한다면 모든 검색 건에 대상 광고가 노출 될 가능성이 높다고 볼 수 있으므로 예측 광고노출수와 QC를 비교할 수도 있고, "일반적인 상황"에서는 이틀치를 값을 RelKwdStat기준으로 단순 비율 증가 시켜면 비슷한값이 도출될 가능성이 높을 것입니다. 그러나 이상 설명드린것과 같이 데이터의 기준 기간이 다르고 실측과 예측 데이터를 비교하는 것이기 때문에  RelKwdStat의 검색수와 Estimate Performance의 예측 광고 노출수를 그대로 비교하는 것은 크게 의미가 없으며 저희 제공 목적에도 부합하지 않을 것으로 생각됩니다.
(위의 말씀 드린 일반적인 상황이라 함은 검색수의 변동이 고정적인 패턴을 가져 아웃라이어의 비율이 적고, 노출 되는 광고나
구매한 광고주의 수역시 큰 변동이 없을때를 의미합니다.)

그럼 왜 양 데이터가 비슷하지 않는가라는 의문이 드실 터인데요. 
질문 주신 내용에서도 확인할 수 있지만 RelKwdStat의 검색수는 PC통합검색 모바일 검색을 합친 값으로 Estimate Performance의 PC의 노출수값을 비교하게 되면 당연히 RelKwdStat의 값이 훨씬 클수 밖에 없습니다.
PC 통합검색 매체를 기준으로 기술해 주신 내용만을 기준으로 본다면 
RelKwdStat는 4290회 , Estimate Performance 는 3981회로 합리적으로 납득할 수 있는 정도가 아닐까 싶습니다.
참고로 단순 비율로 Estimate Performance의 노출수를 30일 기준으로 변환해 보면 4,267회가 나옵니다.

마지막으로 보고서의 실적은 제 예상으로는 광고 시스템의 광고관리 화면내에서의 PC 모바일 분류가된 실적 혹은 
stat 오퍼레이션으로 확인하셨을것으로 생각 되는데요. 만일 이렇게 확인하신 것이라면 광고 노출 매체가 RelKwdStat나 
Estimate performance에서 PC옵션으로 조회했을때 기준이 되는 PC통합검색 매체 뿐만아니라 네이버 내외의 다양한 PC 환경에 서 서비스 되는 "매체들"에서 "광고 노출"된 수의 합산이므로 실적에서의 값이 대단히 커질 수 있습니다. 

PC 통합검색이나 모바일검색과 같이 개별 매체별 지표를 확인하시려면 광고시스템에서는 다차원보고서, API에서는 StatReport 기능을 활용해 주시면 되겠습니다.

대상이 되는 키워드관련 정보가 전혀 없어 데이터 성격과 기능 구성을 기반으로만 설명드렸습니다만
좀더 명확하게 저희가 상황 파악을 하고 답변을 드리기 위해서는 아래 정보가 필요합니다. 

1) 키워드명 
2) 해당 키워드로 RelKwdStat, Estimate performance를 조회한 일시
3) 실적은 확인 하신 대상 키워드의 등록키워드 아이디, 
    등록 키워드 아이디가 전체 공개인 이 공간에 노출 되시는 것이 꺼려지신다면
    해당 키워드 아이디로 API를 호출한 트랜잭션 아이디와 호출 일시를 알려 주셔도 무방합니다.

해당 정보를 제공해 주실 수 있으실지 문의 드립니다. 
(위의 답변으로 해결이 되셨다면 굳이 제공해 주실 필요는 
없을것 같습니다.)

감사합니다

**Comment by githubcnsbs** [comment]
친절한 설명 감사합니다.
제공해주신 답변으로 가지고 있던 의문이 해결되었습니다.

감사합니다.
