### ISSUE TITLE
마스터 리포트에서 소재 문구를 대량 다운로드 받는 방법이 궁금합니다.

### ISSUE THREAD

**Issue by roatch** [naver/searchad-apidoc#422]
캠페인 / 그룹 / 키워드 를 master 리포트에서 받듯이 

소재 문구도 master 리포트에서 대량 제공이 되면 어떤 api 를 사용 해야 하나요?

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

MasterReport의 `Ad` type(Createive)을 받으시면 됩니다.
해당 결과의 컬럼 5,6번을 보시면 Title(문구)과 Description(설명)이 있습니다.
