### ISSUE TITLE
BadRequest 400 문의

### ISSUE THREAD

**Issue by dnt-walker** [naver/searchad-apidoc#424]
MasterReport  API를 사용하는 도중에 아래와 같이 진행이 안되고 있습니다.
해당 계정에 생성된 리포트는 20개정도를 넘지 않고 있습니다.
이와 같은 문제가 일전에도 발생하여 문의 드렸는데 일시적인 캐쉬 문제가 아닌것 같습니다.

확인 부탁드립니다.

HTTP/1.1 400 Bad Request
X-Transaction-ID: BJ6UMEDTHDH2K
Content-Type: application/json;charset=UTF-8
Date: Fri, 10 Jul 2020 07:42:25 GMT
{"name":"BadRequest","status":400,"title":"Bad Request","detail":"exceeded limit of '100' numbers of 'job'"}

추가로 브랜드검색소재 정보를 MasterReport로 받을 수는 없는건가요?
확인 부탁드립니다.

**Comment by naver-searchad** [comment]
안녕하세요. 검색광고API입니다.
불편을 드려서 대단히 죄송합니다.
보고서 생성에 문제가 있는 부분을 수정하셨습니다.
다시 확인 해보시기 바랍니다.

**Comment by dnt-walker** [comment]
처리 감사합니다.
금일 다시 진행 해본 결과 타 계정에도 동일한 증상이 발생하고 있습니다.

HTTP/1.1 400 Bad Request
X-Transaction-ID: BJ8C3RS0HDHP

{"name":"BadRequest","status":400,"title":"Bad Request","detail":"exceeded limit of '100' numbers of 'job'"}

확인 부탁드립니다.
그리고  위에도 문의 드렸듯이 브랜드검색소재 정보를 MasterReport로 받을 수는 없는건가요?
쇼핑검색이나 기타 검색은 존재하는데 브랜드검색만 존재하지가 않네요.
확인 부탁드립니다

**Comment by dnt-walker** [comment]
다시 동일한 이슈가 발생하고 있습니다.

400 Bad Request. 
X-Transaction-ID: BJAMG39Q1HJ4L, 
Response Body: exceeded limit of '100' numbers of 'job'

확인 부탁드립니다.

**Comment by naver-searchad** [comment]
위 오류가 발생한 계정에 대해서 정리 작업 진행되었습니다.
