### ISSUE TITLE
특정 광고주 계정 StatReport를 Get 할 때 403 Forbidden

### ISSUE THREAD

**Issue by lhw8611** [naver/searchad-apidoc#425]
항상 특정 광고주의 StatReport를 Get할 때 
403 Forbidden. X-Transaction-ID: BJ78EMR79DJGI, Response Body: {"code":20005,"message":"요청한 작업을 수행할 수 없습니다."}
라는 에러를 발생시킵니다

리포트 생성 시에는 문제없이 잘 생성되었습니다.

어떻게 해결해야 하나요?

**Comment by lhw8611** [comment]
참고로 새벽 4시쯤 Get하는 상황입니다. (오후에 다시 하면 정상 작동합니다.)

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

아시다시피 403은 권한오류입니다.
signature등 transaction 관련 오류에서도 403이 리턴되지만
위에서처럼 '작업' 관련한 메시지가 리턴되는 경우는
customerId를 잘못 요청했기 때문이라고 보시면 됩니다.
생성시 요청했던 client customer id와 동일하게 요청해 주시면 됩니다.

**Comment by lhw8611** [comment]
customerId 가 잘못 요청됐다면 왜 항상 코드 수정 없이 오후에 또 다시 돌리면 오류가 한번도 안나는걸까요..?

그리고 오늘은 처음으로 같은 지점에서
java.lang.RuntimeException: java.lang.RuntimeException: javax.net.ssl.SSLException: SSL peer shut down incorrectly 
이런 로그가 발생했네요..

**Comment by lhw8611** [comment]
자바 코드 
HttpResponse<InputStream> response = rest.get("/report-download", customerId).queryString("authtoken", authtoken).asBinary();
이 줄에서 발생한 로그입니다.

**Comment by naver-searchad** [comment]
@lhw8611 
자바 코드 문제는 저희가 답변 드릴 수 있는 내용이 아닌 것 같구요
위에서 '권한 오류'라고 답변 드렸던 것은 다시 transaction id로 직접 로그를 찾아 보니
이미 '삭제'되어 없는 리포트를 요청했던 케이스로 확인되었습니다.
이 경우에 403으로 응답되고 있다는 점이 맞지 않아 보여
내부적으로 404로 조치를 계획하고 있습니다.
