### ISSUE TITLE
to many request 의 기준을 알고싶습니다.

### ISSUE THREAD

**Issue by JungHunYu** [naver/searchad-apidoc#426]
경험상 1초에 10개 이상의 실시간성 api를 던지면 이런 에러가 가끔 나옵니다.
내용은 이해 합니다만.
이게 1개의 ip기준인지 1개의 customerid 기준인지
1개의 세션 기준인지 알고싶습니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

customer id 기준입니다.
