### ISSUE TITLE
StatReport.Create API 오늘날짜 호출시

### ISSUE THREAD

**Issue by JungHunYu** [naver/searchad-apidoc#427]
어제날짜에 대해서는 YYYYMMDD 형태로 api가 정상동작하는데(AD, AD_DETAIL)
오늘 당일에대해서는 Bad Request 답변이 날라옵니다. 혹시나싶어 
yyyy-MM-ddTHH:mm:ssZ (ISO8601) 형태 -> 2020-07-14T17:57:44.224Z(오늘)
던져봐도 Bad Request 답변이 날라옵니다. 

해당 리포트는 호출당일날짜에 대해서는 서비스를 안하는건지요?
아지면 제가 잘못호출한건지 알고싶습니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

StatReport는 당일 지표를 지원하지 않습니다.
