### ISSUE TITLE
캠페인 update 적용이 안되는 이슈

### ISSUE THREAD

**Issue by soultrain23** [naver/searchad-apidoc#428]
uri = '/ncc/keywords'
method = 'PUT'
에서 bidAmt를 업데이트 하려하는데요

{'nccKeywordId': 'nkw-a001-01-000003039626404', 'keyword': '새로운마케팅', 'customerId': 000000, 'nccAdgroupId': 'grp-a001-01-000000016001605', 'nccCampaignId': 'cmp-a001-01-000000000953023', 'userLock': False, 'inspectStatus': 'APPROVED', 'bidAmt': 120, 'useGroupBidAmt': True, 'delFlag': False, 'regTm': '2020-07-13T08:10:51.000Z', 'editTm': '2020-07-15T00:21:40.000Z', 'status': 'ELIGIBLE', 'statusReason': 'ELIGIBLE', 'nccQi': {'qiGrade': 4}}

이렇게 bidAmt을 120원으로 요청을 하면 

응답에서 
response body = [{'nccKeywordId': 'nkw-a001-01-000003039626404', 'keyword': '새로운마케팅', 'customerId': 000000, 'nccAdgroupId': 'grp-a001-01-000000016001605', 'nccCampaignId': 'cmp-a001-01-000000000953023', 'userLock': False, 'inspectStatus': 'APPROVED', 'bidAmt': 70, 'useGroupBidAmt': True, 'delFlag': False, 'regTm': '2020-07-13T08:10:51.000Z', 'editTm': '2020-07-15T00:36:32.000Z', 'status': 'ELIGIBLE', 'statusReason': 'ELIGIBLE', 'nccQi': {'qiGrade': 4}}]

잘 받았다고 들어옵니다. 중요한 bidAmt만 안바뀌어 있고요. 각 키워드 마다 인터벌은 20초로 충분할 것 같고,
어쩌다가는 바뀌고 대부분은 업데이트가 안되는데 timestamp 문제인 것 같기도하고..

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

개별 키워드의 입찰가를 변경하려면
`useGroupBidAmt` 필드도 함께 `false`로 바꿔 주셔야 합니다.
