### ISSUE TITLE
MasterReport 타입 문의

### ISSUE THREAD

**Issue by dnt-walker** [naver/searchad-apidoc#429]
MasterReport 로 소재 정보를 가져오고 있습니다.
다른 유형의 소재 정보는 다 되는 것 같은데 브랜드검색 소재는 MasterReport로 가져올 수 없는 건가요?
제한적인 범위 내에서라도 가능했으면 합니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

브랜드검색 소재의 경우,
우선 소재를 구성하는 템플릿과 데이터 유형이 다양하고 계속 유동적으로 바뀌기 때문에
고정된 유형의 데이터를 관리하고 제공해야 하는 API의 직접 대상이 되기 어렵습니다.
