### ISSUE TITLE
키워드 통계정보 호출에러

### ISSUE THREAD

**Issue by ChoiDaeJung** [naver/searchad-apidoc#43]
안녕하세요.
API를 가지고 테스트를 진행하는데 특정 키워드만 에러를 발생을 시키는데 원인을 알 수가 없습니다.

##############################################################################
# 요청로그
##############################################################################
GET /stats?ids=nkw-a001-01-000000141113597&fields=%5B%22impCnt%22%2C+%22clkCnt%22%2C+%22ctr%22%2C+%22cpc%22%2C+%22avgRnk%22%2C+%22ccnt%22%2C+%22salesAmt%22%2C+%22crto%22%2C+%22recentAvgCpc%22%2C+%22recentAvgRnk%22%5D&timeIncrement=allDays&datePreset=today HTTP/1.1
accept-encoding: gzip
user-agent: unirest-java/1.3.11
X-API-KEY: 0100000000f248e472e26cb4194bcc68bc81b3024cc3f0a3d19375ad7217702758f74689a4
X-Customer: 753343
X-Signature: 95w5aY1Hxtnif4MB6PYjj79/oKU5bRGsNIfwikxgTEU=
X-Timestamp: 1487917204015
##############################################################################

##############################################################################
# 결과로그
##############################################################################
HTTP/1.1 429 Too Many Requests
Connection: close
Cache-Control: no-store, must-revalidate
X-Transaction-ID: AQDR3B581P9I5
Content-Type: application/json;charset=UTF-8
Date: Fri, 24 Feb 2017 06:19:59 GMT

{"code":429,"message":"Too Many Requests"}
##############################################################################

**Comment by naver-searchad** [comment]
`429 Too Many Requests` 는 과도한 요청으로 인해 일시적으로 처리를 제한할 경우 발생합니다.
잠시 후 다시 시도하시면 정상 처리됩니다.
