### ISSUE TITLE
AdGroup 에 포함되어 있는 keyword Stat 리스트를 조회할 수 있는 방법이 있나요?

### ISSUE THREAD

**Issue by KangSunghoon** [naver/searchad-apidoc#432]
안녕하세요..

AdGroup 에 keyword 리스트가 존재하는데요..
해당 AdGroup 에 포함되어 있는 keyword 의 stat 리스트를 조회할 수 있는 방법에 대해 가이드 부탁 드립니다..

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

문의하신 내용에 정확히 맞는 방법은 없습니다.
http://naver.github.io/searchad-apidoc/#/operations/GET/~2Fstats%7B%3Fids,fields,timeRange,datePreset,timeIncrement,breakdown%7D
해당 api에서 ids 파라미터에 keyword id 목록을 넣어 요청하셔야 합니다.
따라서 먼저 해당 AdGroup의 keyword list를 조회해서 keyword id들을 구하셔야 합니다.

**Comment by KangSunghoon** [comment]
빠른 답변 감사 드립니다..

keyword 별로 하나씩 조회를 해야 해당 keyword 에 대한  Stat 값들을 확인할 수 있다는 말씀이신지요?
만일, AdGroup 에 200개의 keyword 가 존재한다면 200번을 조회해야 
AdGroup 에 포함된 keyword 의 Stat 값들을 조회 할 수 있다는 건데요..
너무 비효율적 인데.. 개선이 불가능할 까요?

**Comment by naver-searchad** [comment]
@KangSunghoon 
http://naver.github.io/searchad-apidoc/#/operations/GET/~2Fncc~2Fkeywords%7B%3FnccAdgroupId,baseSearchId,recordSize,selector%7D
그룹 id를 조건으로 모든 키워드들을 한번에 조회할 수 있습니다.
