### ISSUE TITLE
400 Bad Request.

### ISSUE THREAD

**Issue by dnt-walker** [naver/searchad-apidoc#434]
일전에도 문의 드렸는데 동일 증상이 또 발생하고 있습니다. 

``` 
400 Bad Request. 
X-Transaction-ID: BJIIRJT7PDH7N,

exceeded limit of '100' numbers of 'job'
```

실제 조회 계정의 문서 숫자는 20개 정도 됩니다.
확인 부탁드립니다.

**Comment by naver-searchad** [comment]
안녕하세요. 검색광고API입니다.
위 계정 정리되었습니다.

**Comment by dnt-walker** [comment]
금일 동일한 오류가 발생하였습니다.

인증 시 대표 아이디로 인증하고 
리포터 다운로드 시 권한을 부여받은 광고 아이디로 리쿼스트 진행합니다.

웹상에서 리포트가 100개 이하이고요.
해당 오류가 발생하면 이후 해당 아이디는 조회시 항상 동일 오류가 발생합니다.

해결할 수 있는 방법은 없는지 확인 부탁드립니다.

400 Bad Request. X-Transaction-ID: BL0LVBE71HJ4H, detail=exceeded limit of '100' numbers of 'job'
400 Bad Request. X-Transaction-ID: BL0M67709DG2U, detail=exceeded limit of '100' numbers of 'job'
400 Bad Request. X-Transaction-ID: BL0MD2V31DHBH, detail=exceeded limit of '100' numbers of 'job'
400 Bad Request. X-Transaction-ID: BL0MJUOI99IJI, detail=exceeded limit of '100' numbers of 'job'
400 Bad Request. X-Transaction-ID: BL0MQQGP1DIA1, detail=exceeded limit of '100' numbers of 'job'
400 Bad Request. X-Transaction-ID: BL0N1M9H9HGOI, detail=exceeded limit of '100' numbers of 'job'
400 Bad Request. X-Transaction-ID: BL0N8I33PDG82, detail=exceeded limit of '100' numbers of 'job'
400 Bad Request. X-Transaction-ID: BL0NFDTCHHGCU, detail=exceeded limit of '100' numbers of 'job'
400 Bad Request. X-Transaction-ID: BL0NM9NN9HI51, detail=exceeded limit of '100' numbers of 'job'
400 Bad Request. X-Transaction-ID: BL0NT5HA9HI7B, detail=exceeded limit of '100' numbers of 'job'
400 Bad Request. X-Transaction-ID: BL0O419G1DI43, detail=exceeded limit of '100' numbers of 'job'
400 Bad Request. X-Transaction-ID: BL0OAT2U99JJF, detail=exceeded limit of '100' numbers of 'job'
400 Bad Request. X-Transaction-ID: BL0Q8G56HDH06, detail=exceeded limit of '100' numbers of 'job'
400 Bad Request. X-Transaction-ID: BL0QD2N1HDI6V, detail=exceeded limit of '100' numbers of 'job'
400 Bad Request. X-Transaction-ID: BL0QHL9L1HIKV, detail=exceeded limit of '100' numbers of 'job'
400 Bad Request. X-Transaction-ID: BL0QM7Q1PHJP5, detail=exceeded limit of '100' numbers of 'job'
400 Bad Request. X-Transaction-ID: BL0QQQACPHGK1, detail=exceeded limit of '100' numbers of 'job'
400 Bad Request. X-Transaction-ID: BL0QVCQJPHGT9, detail=exceeded limit of '100' numbers of 'job'
400 Bad Request. X-Transaction-ID: BL0R3VAPH9J51, detail=exceeded limit of '100' numbers of 'job'
400 Bad Request. X-Transaction-ID: BL0R8HRTPHIHH, detail=exceeded limit of '100' numbers of 'job'
400 Bad Request. X-Transaction-ID: BL0RD4C999JAP, detail=exceeded limit of '100' numbers of 'job'

**Comment by naver-searchad** [comment]
@dnt-walker 문제가 발생한 광고주에 대해서 이력 초기화 작업을 진행하였습니다. 
과거 버그로 인해 이력 삭제에 문제가 있던 계정이 있어, 실제 목록과 차이가나는 현상이 있습니다.
불편하시더라도 동일한 오류가 발생할 경우 알려주시면 처리해드리도록 하겠습니다.

**Comment by dnt-walker** [comment]
@naver-searchad 빠른 처리 감사합니다.

금일 또 한건 발생하였습니다.

400 Bad Request. X-Transaction-ID: BL3DHCDQ1HHBN,  detail=exceeded limit of '100' numbers of 'job'

처리 부탁드립니다.

감사합니다.

**Comment by naver-searchad** [comment]
@dnt-walker 위 광고주에 대해서 이력 초기화 작업을 진행하였습니다.

**Comment by dnt-walker** [comment]
@naver-searchad 빠른 처리 감사합니다.

**Comment by dnt-walker** [comment]
추가 발생건이 있어서 요청드립니다.

400 Bad Request. X-Transaction-ID: BL3GV2ET1DG00,  detail=exceeded limit of '100' numbers of 'job'

**Comment by naver-searchad** [comment]
@dnt-walker 요청주신 광고주에 대해서 이력 초기화 작업 완료됐습니다.

**Comment by dnt-walker** [comment]
@naver-searchad 먼저 빠른 처리 감사합니다.
X-Transaction-ID: BL3GV2ET1DG00 요청 건은 오류가 발생한 계정은 근래에 문제가 문제가 없었던 계정입니다.
혹시 해당 계정이 일전 버그로 발생한 문제인가요?
금일 API로 데이터를 많이 요청하고 있습니다. 실제 트래픽이 많이 발생해서 발생한 문제가 아닐까요?
만약이 트래픽 과도로 막힌 문제이면 트래픽 발생 빈도 가이드 부탁드립니다.

**Comment by naver-searchad** [comment]
@dnt-walker 다수의 계정에서 과거 버그로 인해 이력 삭제가 불완전하게 처리되어 화면에 보이는 것과 DB에 남아있는게 불일치하게 되었습니다. 
트래픽이 위 계정에 이런 현상을 빨리 일으키기는 했겠지만, 트래픽이 많아서 생기는 문제는 아닙니다.

**Comment by dnt-walker** [comment]
@naver-searchad 
금일 동일한 문제가 발생하였습니다.
확인 부탁드립니다.

```
2020-12-11 08:08:29,514 400 Bad Request. X-Transaction-ID: BM9RKRP4P9IB5, exceeded limit of '100' numbers of 'job
```

**Comment by naver-searchad** [comment]
@dnt-walker 해당 계정 이력 초기화 작업 완료됐습니다.

**Comment by dnt-walker** [comment]
@naver-searchad 
안녕하세요! 금일 동일한 문제가 발생하였습니다.

400 Bad Request. 
X-Transaction-ID: BP3D78UFPHH0L, 
exceeded limit of '100' numbers of 'job'

근본적으로 해결할 수 있는 방법은 없는건가요?

**Comment by naver-searchad** [comment]
@dnt-walker 해당계정 문제 해결되었습니다. 
과거 버그로 인해 이력삭제가 정상적으로 되지 않아 발생한 문제인데요.
최대한 빠르게 처리할 수 있도록 하겠습니다.

**Comment by dnt-walker** [comment]
@naver-searchad 
빠른 처리 감사합니다.

**Comment by dnt-walker** [comment]
@naver-searchad 
안녕하세요! 
한동안 발생 안하다가 기존 이슈와 동일하게 문제가 발생하고 있습니다.
현재 해당 계정(backpackr:1607124)에 리포트 수가 50개가 안되는 것으로 파악됩니다.

2022-01-27 11:06:37 400 Bad Request. X-Transaction-ID: BUJ54E47PHJ25, Response Body: MasterReport(id=null, item=null, fromTime=null, updateTime=null, status=null, downloadUrl=null, name=BadRequest, title=Bad Request, detail=exceeded limit of '100' numbers of 'job
2022-01-27 11:16:37 400 Bad Request. X-Transaction-ID: BUJ590K31HIB8, Response Body: MasterReport(id=null, item=null, fromTime=null, updateTime=null, status=null, downloadUrl=null, name=BadRequest, title=Bad Request, detail=exceeded limit of '100' numbers of 'job'

확인 부탁드립니다.
