### ISSUE TITLE
Stat에서 전환 데이터 추출시 직접/간접 관련 파라미터가 있나요 ?

### ISSUE THREAD

**Issue by mingirlSo** [naver/searchad-apidoc#435]
안녕하세요. 

혹시 Stat 에서 전환수와 전환매출액 을 보고서에서와 같이 직접/간접으로 구분지어 
추출할 수 있는 파라미터가 있을까요 ?

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

api doc에 명기된 parameter 외의 옵션은 따로 없습니다.

**Comment by mingirlSo** [comment]
그렇다면 혹시 api 전체에서 에서 직접전환수 , 간접전환수를 추출할 수 있는 방법은 
없을까요 ?

답변 감사합니다 !

**Comment by naver-searchad** [comment]
@mingirlSo 
리포트 외의 api를 문의하시는 거라면 없는 게 맞습니다.
첫번째 답변과 동일한 답변입니다.

**Comment by mingirlSo** [comment]
답변 정말  감사합니다 . 
관련 데이터는 StatReport에서 추출가능한 것을 확인하였습니다.

그런데 StatReport API에서 GET은 추출이 되는데 POST를 통해 보고서를 생성하는 부분에서 
status code 500 error가 떠서 문의드립니다. 
제가 파이썬 외 다른 언어는 다룰줄 몰라, report쪽 sample을 참조하는데 한계가 있어서요..

다시 한번 감사드립니다.
![sample](https://user-images.githubusercontent.com/40485182/89151489-0e509d00-d59c-11ea-8c86-b4eb42b2b7d8.PNG)

**Comment by mingirlSo** [comment]
해당 문제 해결했습니다. 

params 부분을 

json = {'reportTp' : 'AD_CONVERSION_DETAIL', 'name' : 'TEST#' + str(1),
                          'statDt': '20200701'} 

와 같이 수정했더니 생성되었습니다.
감사합니다. 좋은 하루 되세요.
