### ISSUE TITLE
Stat.SummaryStat 처럼 Stat.DailyStat도 여러개 Ids 를 넘기는 기능은 없나요?

### ISSUE THREAD

**Issue by lhw8611** [naver/searchad-apidoc#436]
자바 샘플에서 SummaryStat에서 ids를 넘기는 방법은 확인했습니다 
비슷한 방법으로 DailyStat을 만들어 해보니 기능이 없다고 뜨네용

Stats 코드는 

	public static Stat.DailyStat getDailyStatByIdList(RestClient rest, long customerId, List<String> ids, List<Stat.Field> fields,
			Stat.TimeRange timeRange, Stat.DatePreset datePreset, Breakdown breakdown) throws Exception {

		HttpRequest request = rest.get("/stats", customerId).queryString("ids", ids)
				.queryString("fields", fields.toString())
				.queryString("timeIncrement", TimeIncrement.daily.getValue());

		if (null != datePreset) {
			request.queryString("datePreset", datePreset.getValue());
		}

		if (null != timeRange) {
			request.queryString("timeRange", timeRange.toString());
		}

		if (null != breakdown) {
			request.queryString("breakdown", breakdown.getValue());
		}

		
		return rest.asObject(request.asString(), Stat.DailyStat.class);
	}

이거입니다.

1. 해당 기능 없는것인지?
2. Ids는 200개 이상 넘길경우 400 Bad request가 뜨던데 최대 200개씩 보낼 수 있는것인지?

* 캠페인 단위로 조회하면 빠르겠지만 노출키워드 수와 해당 계정의 상위키워드를 조회하고싶어 키워드 하나하나 조회하려고 합니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

저희가 코드 검증을 해드리지는 않구요 (그럴 수도 없지만),
API로 요청된 데이터 정보로 어떤 문제가 있는지 확인해 드리고 있습니다.

Get 요청 ids 파라미터 갯수 제한은 정해져 있지 않으나
http 프로토콜 상에 url 길이 제한이 있을 것이므로 적절한 수준으로 나누어 요청하셔야 합니다.

**Comment by lhw8611** [comment]
코드는 네이버에서 올린 샘플이라 올려봤구요

제한이 있을 뿐 DailyStat도 단일 id가 아닌 배열로 보내도 가능하단 말이죠?

SummaryStat 과 똑같이 넘겼는데 기능이 없습니다라고 떠서 안되나 싶어서 질문글 올렸습니다.

**Comment by naver-searchad** [comment]
@lhw8611 
`DailyStat`, `SummaryStat`은 api 상의 정식 명칭이 아닙니다.
/stats api를 이용한 코드상의 이름일 뿐입니다.
