### ISSUE TITLE
검색어(search keyword)를 조회할 수 있는 API가 있나요?

### ISSUE THREAD

**Issue by lhw8611** [naver/searchad-apidoc#437]
캠페인 타입이 쇼핑검색인 캠페인으로 키워드로 검색하면 키워드가 하나도 안뜨는데

검색어를 조회할 수 있는 방법이 있을까요?

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

먼저, 키워드와 검색어는 다른 용어입니다.
키워드는 검색광고 상품에 광고주가 등록하는 입찰단위 개체이지만
검색어는 말그대로 네이버/쇼핑 사용자로부터 유입된 검색어입니다.

쇼핑검색광고 상품은 '키워드'를 등록하고 관리하는 상품이 아닙니다.
키워드는 API 지원 대상이지만
검색어는 API로 지원하지 않고 있습니다.

**Comment by lhw8611** [comment]
감사합니다
