### ISSUE TITLE
이력 관리 - 변경이력 API

### ISSUE THREAD

**Issue by zxchsr** [naver/searchad-apidoc#439]
안녕하세요.

웹에서 "네이버 검색광고 > 도구 > 이력 관리" 메뉴로 들어가면 변경이력과 검토이력을 확인할 수 있는데요, 
이러한 변경이력과 검토이력을 확인할 수 있는 API 제공하는지 여쭤보고 싶습니다.

찾아봤을때는 따로 없는 거 같은데 혹시나 해서 문의드립니다.
확인 후 회신 부탁드립니다.
감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

기존 유사 문의를 참고해 주시구요 #361 
현재 API는 제공되고 있지 않습니다.
