### ISSUE TITLE
시간 별 전날 순위 관련 문의

### ISSUE THREAD

**Issue by FreeEgo** [naver/searchad-apidoc#44]
Stat.DailyStat에서 Stat.DatePreset.yesterday 등의 옵션으로 데이터를 가져오면
전날 순위로 보이는 avgRnk, recentAvgRnk를 가져오는데

StatReport를 사용하지 않고 Stat에서 시간 별 전날 순위를 가져오는 방법이 있나요?

**Comment by naver-searchad** [comment]
안녕하세요.

/api/stats API를 이용하여 전날 시간별 순위(평균노출순위)값을 조회하실 수 있습니다.

조회 방식은 쿼리 스트링에 아래와 같은 필드를 포함하여 요청주시면 됩니다.
```
id 혹은 ids
fields= avgRnk를 포함
datePreset=yesterday
timeIncrement=allDays
breakdown=hh24
```

**Comment by FreeEgo** [comment]
위와 같이 yesterday로 breakdown의 name과 avgRnk를 받아오면 아래와 같습니다.
############
08시~09시 : 3.0
10시~11시 : 5.3
11시~12시 : 4.5
12시~13시 : 6.0
13시~14시 : 4.0
14시~15시 : 5.3
15시~16시 : 6.5
16시~17시 : 4.8
17시~18시 : 6.0
############
24시간을 전부 받는 방법이 있나요?

**Comment by naver-searchad** [comment]
말씀드린 파라미터 정보를 통해서 지표를 조회하는 경우, 지표가 있는 시간대에 대해서만 지표를 반환하도록 되어 있습니다.

그래서 비어있는 시간대에 대한 처리는 클라이언트단에서 별도로 수행하셔야합니다.

**Comment by FreeEgo** [comment]
감사합니다!
