### ISSUE TITLE
특정 키워드ID로 CTR 값

### ISSUE THREAD

**Issue by zxchsr** [naver/searchad-apidoc#440]
특정 키워드 ID 를 던졌을 때 금일 또는 전일 CTR 값을 조회할 수 있는 API가 있을까요?

**Comment by naver-searchad** [comment]
@zxchsr 
[공식문서의 stat api](http://naver.github.io/searchad-apidoc/#/operations/GET/~2Fstats%7B%3Fid,fields,timeRange,datePreset,timeIncrement,breakdown%7D) 를 참고하시면 됩니다.
