### ISSUE TITLE
특정 키워드ID로 CTR 값

### ISSUE THREAD

**Issue by zxchsr** [naver/searchad-apidoc#441]
/stats 를 통해 특정 키워드ID을 던져 ctr 데이터를 조회하려하는데
실제 클릭률이 존재하는 키워드 ID를 던져 조회하여도 0으로 조회되는데..
어떤 부분이 잘못된 걸까요? 별도의 에러코드도 안나오고 데이터는 나오는데
ctr값이 전부 0으로 잡혀요

**Comment by naver-searchad** [comment]
@zxchsr 
참고로 먼저,
추가 문의사항 등록시 새 이슈로 등록하지 마시고 댓글로 추가해 주시면 감사하겠습니다.

에러가 나오지 않았다면 조회하신 데이터는 실제 지표값이 맞습니다.
ctr이 0이라면 clicks 값도 0일 테니 확인해 보시구요
api로 확인하는 대신 광고시스템 화면에서 해당 키워드를 조회해 보셔서 지표값을 확인해 보시는 것도 방법입니다.

그리고 참고로 실제 유저로부터 들어온 클릭이 아닌 경우
무효클릭으로 판정되어 클릭수에 포함되지 않을 수도 있습니다.

**Comment by zxchsr** [comment]
데이터가 전부 0으로 나오는데 광고시스템 화면에서의 클릭률은 존재합니다.
광고시스템 - 광고관리 - 키워드별 클릭률 데이터와 stats에서 조회하는 ctr은 상이한 데이터인건가요?

**Comment by naver-searchad** [comment]
@zxchsr 
당연히 모두 동일한 데이터입니다.
보신 두군데 값이 서로 다르다면 조회조건이 동일하지 않다는 의미입니다.

그래도 원인이 잘 파악되지 않으시면
어떤 키워드id를 어떤 조건으로 조회하신 것인지 추가 정보를 알려 주시기 바랍니다.

**Comment by zxchsr** [comment]
키워드값 : nkw-a001-01-000002405923010

API 요청 시 파라미터값으로 id=nkw-a001-01-000002405923010&fields=["ctr"]&timeRange={"since":"2020-08-16","until":"2020-08-18"}
