### ISSUE TITLE
position 의미

### ISSUE THREAD

**Issue by nonamelight** [naver/searchad-apidoc#442]
안녕하세요

1위 입찰가를 조회하고 싶은데
average-bid, median-bid, minimum-bid 등이 있는데
1위 입찰가가 없어서요. position 값을 1로 설정하면 1위 입찰가가 조회되는 것이 맞나요?

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

http://naver.github.io/searchad-apidoc/#/operations/POST/~2Festimate~2Faverage-position-bid~2F%7Btype%7D
위 API의 position이 문의하신 순위를 의미합니다.
items 항목에
`[{key: "nkw-xxxxxxxxx", position: "1"}, {...}]`
이런 식으로 요청값을 넣어 주시면 됩니다.
