### ISSUE TITLE
API 접속이 잘 안되는것 같습니다.

### ISSUE THREAD

**Issue by kaorimikage** [naver/searchad-apidoc#443]
어제부터 저녁시간대에 API 서버에 접속이 잘 되지 않습니다.

뭔가 문제가 있는 것인지요?

**Comment by enfshin** [comment]
저도 같은 문제 겪고 있는데 됐다가 안됐다가 504에러 뜨던데 무슨 문제인가요 ?

**Comment by SM10855** [comment]
저도 동일한 문제가 발생합니다. 504 에러나옵니다.

**Comment by enfshin** [comment]
지금은 또 잘 되는거 같은데 다들 그러신가요?

**Comment by lachelngose** [comment]
저희는 한시간 반쯤 전부터 갑자기 안되기 시작했는데, 지금도 잘 되는 건 아니고 일부는 되고 일부는 504 돌아오네요

**Comment by enfshin** [comment]
저도 다시 됐다 안됐다 하네요.

**Comment by SM10855** [comment]
지금도 안되는거같아요 됐다가 안됐다가 반복합니다.

**Comment by jayjay248** [comment]
혹시 문의 하셔서 답변 받으신분 계신가요??

마냥 기다려야 하는건지요;;

공지라도 나오면 좋을거 같은데요.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고입니다.

전일 저녁 상황파악에 다소 시간이 걸려 공지가 늦게 게재되었습니다.
http://naver.github.io/searchad-apidoc/#/notice
- 특정 서비스 장애 공지 (오후 10시 경)
- 정상화 공지 (오후 11시 30분 경)

**Comment by mschoi2** [comment]
혹시 RelKwdStat 말고도 다른 서비스도 요청 제한을 두었나요? StatReport과 MasterReport를 평소와 같은 양으로 호출하였으나 429 Too Many Requests가 발생합니다. 다른 서비스도 요청 제한이 있는지, 요청 제한은 일시적인지 혹은 영구적인지 확인 부탁드립니다.
