### ISSUE TITLE
2020년 9월 10일자 공지 관련 문의

### ISSUE THREAD

**Issue by mschoi2** [naver/searchad-apidoc#444]
안녕하세요.

공지 올라온대로 API 서비스 응답이 느린 현상이 복구된 것은 확인하였으나 
현재 429 Too Many Requests가 빈번하게 발생하여 문의드립니다.

혹시 RelKwdStat 말고도 다른 서비스도 과도한 요청 제한을 두었나요?
평소에 api 사용시 많이 요청하면 429 Too Many Requests가 발생한다는 것은 인지하고 있어 429가 발생하지 않는 선으로 사용하고 있었습니다.
하지만 금일 StatReport과 MasterReport를 평소와 같은 양으로 호출하였으나 429 Too Many Requests가 발생합니다.
RelKwdStat 서비스 외 다른 서비스도 요청 제한수를 기존보다 적게 잡았는지, 변경된 요청 제한수는 일시적인지 혹은 영구적인지 확인 부탁드립니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

요청수 제한은 플랫폼 상황이나 어제와 같은 비정상적인 사용자 요청이 있는 경우 유동적으로 조정될 수 있습니다.
따라서 일시적인지 영구적인지에 대해 정확히 답변 드리기는 어려울 것 같구요
현재 응답속도는 정상으로 회복된 것으로 확인되므로 계속 사용 상에 어려움이 있는지 확인 부탁드립니다.
