### ISSUE TITLE
429 Too Many Requests 문의

### ISSUE THREAD

**Issue by SM10855** [naver/searchad-apidoc#446]
안녕하세요.
`
[429 TOO_MANY_REQUESTS]APIGateway Server Error, <html><body><h1>429 Too Many Requests</h1>
You have sent too many requests in a given amount of time.
</body></html>
, X-Transaction-ID: , {"status":"429 TOO_MANY_REQUESTS","title":"APIGateway Server Error","detail":"<html><body><h1>429 Too Many Requests</h1>
You have sent too many requests in a given amount of time.
</body></html>
","transactionId":""}
`

어제보다는 응답속도가 많이 회복은 된 거 같은데, 평소와 같은 호출량인데 아직까지는 429 Too Many Requests 가 발생하고 있습니다.

유동적으로 변하게 된다면 혹시 어느정도 기준내로 해야되는지 알려주실 수 있나요,
특정 시간내 요청횟수라던지, 아니면 429가 나오지 않게 하려면 몇 초 후에 다시 호출을 하는지 어떤 방법을 사용하는게 좋을까요.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

해당 오류에 대해서는 wiki 내용을 참고하시기 바랍니다.
감사합니다.
