### ISSUE TITLE
keywordstool 429 에러뜨는데 혹시 이거 할달량이 어찌되나요

### ISSUE THREAD

**Issue by chanjuyou** [naver/searchad-apidoc#447]
저희가 실수로 너무많은걸 요청한건지 3시간 전부터 저 429에러가 안풀리더라고요

1초에 호출한도? 이런거 어떤건지 자세히 나와있는 곳을 제가 못찾은걸까요 안보이네요 

429 뜰떄 대처 방법과 호출? 제약사항에 대해 좀더 자세히 알고 싶네요 ㅠㅠ

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

해당 오류에 대해서는 wiki 내용을 참고하시기 바랍니다.
https://github.com/naver/searchad-apidoc/wiki/FAQ#q-api-%ED%98%B8%EC%B6%9C-%EC%86%8D%EB%8F%84-%EC%A0%9C%ED%95%9C%EC%9D%B4-%EC%9E%88%EB%82%98%EC%9A%94
감사합니다.

**Comment by chanjuyou** [comment]
초 단위 이하 라고 되있는데 혹시 1초마다 호출하면 429호출을 안하게 될까요?
