### ISSUE TITLE
HTTP 429 Too Many Requests 관련 문의

### ISSUE THREAD

**Issue by devfreshi85** [naver/searchad-apidoc#448]
안녕하세요.

HTTP 429 Too Many Requests의 경우, 

client의 IP 당 제한이 걸리는 것인지?
customerId 당 제한이 걸리는 것인지 문의 드립니다.

FAQ는 관련 자료를 찾아보았지만, 데이터가 없어서 문의 드립니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

제한 기준은 customerId 입니다.
