### ISSUE TITLE
쇼핑 검색 상품 소재의 검수 상태 관련 문의 드립니다.

### ISSUE THREAD

**Issue by exit39** [naver/searchad-apidoc#449]
쇼핑 검색 소재에 대해서 api를 통해 데이터 구현은 완료 된 상태 입니다.

소재 검수 상태에 Ad Creative Inspect Status가 30: LIMITED_APPROVED 상태일때

현재는 해당 소재 ID를 찾아서 아래 이미지의 빨간 테두리 부분의 사유를 확인하는데 이를 api로 제공해 주는게 있나요? 
api 문서를 찾아보아도 해당 내용을 찾기가 어려워서 문의 남깁니다.
혹시 api 제공이 안된다면 혹시 추가 가능성이 있는지도 함께 문의 드리겠습니다.

![스크린샷 2020-09-22 오후 3 17 05](https://user-images.githubusercontent.com/64013581/93849797-d20e0300-fce7-11ea-93ea-469c0f438d71.png)

이상입니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

문의하신 내용은 API 제공 대상이 아닙니다.
추가 가능성이 없다고는 말씀드리기 어렵겠지요... 불가능은 없으니까요.
다만 현재로선 예정이나 계획은 없습니다.
