### ISSUE TITLE
API 통신 호출 시 에러

### ISSUE THREAD

**Issue by ChoiDaeJung** [naver/searchad-apidoc#45]
가끔식 API 호출중

com.mashape.unirest.http.exceptions.UnirestException: java.lang.RuntimeException: java.lang.RuntimeException: javax.net.ssl.SSLException: SSL peer shut down incorrectly

이런 에러가 발생하는 경우가 있는데
이런건 어떤 경우에 발생하는 건가요?

**Comment by naver-searchad** [comment]
해당 오류를 방지하기 위해 서버측 SSL 인증서 관련 설정을 변경하였습니다.
차후 동일한 오류가 또 발생할 경우 추가 문의 부탁드립니다.

**Comment by ChoiDaeJung** [comment]
안녕하세요.
오늘 같은 에러가 또 3번 발생을 하였습니다.
한가지 특이상 점은 같은 CustomerID에서 발생을 했습니다.
필요 하실지 몰라 해당 관련 정보 올려드려요.

###########################################################################
# 에러 발생시간(대략) 2017-03-21 04:04:08.443, 2017-03-21 12:04:12.773, 2017-03-21 16:30:40.843
# 에러 CustomerID : 381133
# 에러메시지
com.mashape.unirest.http.exceptions.UnirestException: java.lang.RuntimeException: java.lang.RuntimeException: javax.net.ssl.SSLException: SSL peer shut down incorrectly
###########################################################################
