### ISSUE TITLE
How to get top ad groups by spending, OR get all ad groups id

### ISSUE THREAD

**Issue by imaksp** [naver/searchad-apidoc#451]
Hi currently I can get ad groups for single campaign id, but is it possible to get all ad groups ids & stats of all, 
or top adgroups,
or ids of all adgroups for all campaigns.

**Comment by naver-searchad** [comment]
HI, this is Naver SearchAd.

There is no exact way to get the data you described by requesting just one time.
But you can get by requesting each entity api several times.
(campaign by customer id then ad group by each campaign...)

**Comment by aksdevac** [comment]
Ok it seems I will need to send multiple requests. for getting stats of all active Ad Groups by custom date range, let me know if there is a better way to achieve this.

**Comment by naver-searchad** [comment]
@aksdevac 
Recommend you to use [`StatReport`](http://naver.github.io/searchad-apidoc/#/tags/StatReport) for your purpose.
First, `create` `Ad` type report with wanting date range,
then after waiting for seconds try `get` the created report.
With this report, summarize by grouping Ad group.

**Comment by aksdevac** [comment]
Ok but report is only taking one date param which is `statDt`, I need to pass date range, also not able to understand report response. It is is returning data in some table format, but missing Title, how to find column/field name?

**Comment by naver-searchad** [comment]
@aksdevac 
Sorry, you're right `StatReport` doesn't support date range.
And response data doesn't have any titles.
You have to read each report type's data format on that api link.

**Comment by naver-searchad** [comment]
@aksdevac 
As many as the Get method url length permits.
It depends on your query parameters on time so the exact numbers can not be documented.

**Comment by aksdevac** [comment]
@naver-searchad Hi can I get cost data for pre-paid contract campaign ? 
currently I am getting other data like clicks, impressions in stat report but cost is always zero.
