### ISSUE TITLE
keep-alive header 사용 관련 문의

### ISSUE THREAD

**Issue by ohseunghyeon** [naver/searchad-apidoc#452]
안녕하세요.
아드리엘이라는 광고플랫폼에서 근무하는 개발자입니다.

광고주의 광고 데이터를 가져오기 위해서 campaign, adgroup, ad, stat 등의 API를 사용하고 있습니다. 그런데 네이버 광고 API의 경우 초당 최대 request 제한이 있어서 어느 정도 흐름을 제어하면서 request를 날리고는 있지만 최대한 빨리 결과를 얻고자 시도하다보니 요청 수가 좀 많습니다. 그 중 keywords를 대상으로 하는 stat API 요청이 특히 절대적으로 콜 수가 많고요.

그래서 keep alive 헤더를 사용하고 싶은데, 테스트를 해보니 naver 광고 서버는 항상 헤더가 connection: close로 날아오네요. 아마 지원하지 않는 건가 생각되는데요, 혹시 이 부분에 대해서 확인 부탁드려도 될까요. 그리고 지원하지 않는 게 맞다면, 지원되도록 수정될 여지가 있을지도 궁금합니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다

keep alive와 request 제한과는 관련이 없습니다.

그리고 request 제한은 custoemrId 단위이므로
광고주별로 api를 적절히 스케쥴링 해서 활용하시면
keywords로 무리한 logic을 가져가지 않는 이상
원하시는 플랫폼 작업을 하시는 데에는 지장이 없으리라 생각합니다.

**Comment by ohseunghyeon** [comment]
제가 request 제한을 언급한 이유는 429 status code를 받을 시 계속 재시도를 하는 바람에 200 응답을 받는 요청 + 429를 받는 요청 갯수의 합이 크다는 얘기를 하기 위함이었습니다.

저 또한 이에 대한 해결방안으로 답변에 언급하신대로 적절한 스케쥴링을 활용하고자 하긴 합니다만, 그럼에도 keep alive를 활용할 수 있다면 리소스 소모를 조금 더 줄일 수 있을 것 같아 질문하였습니다.

혹 지원 여부에 대한 답을 다시 부탁드려도 될까요?

**Comment by naver-searchad** [comment]
@ohseunghyeon 
connection을 관리하는 클라이언트 측 리소스에 대한 언급을 하신 것으로 이해했습니다.

반대로 다수의 클라이언트로부터 웹서버와는 비교도 안될 만큼 많은 api 트래픽을 처리해야 하는 api 서버 플랫폼 입장에서는
keep alive를 유지하고 대기하는 비용이 부담될 수 있고 실제로 connection 유지에 문제의 소지가 될 수 있다고 봅니다.
429와 같은 트래픽 제한을 운용하고 있는 걸 보면 이해하실 수 있을 겁니다.
