### ISSUE TITLE
403에러

### ISSUE THREAD

**Issue by hyunjoo123** [naver/searchad-apidoc#453]
현재 저희서버에서 403에러가 일어납니다
다른서버로 테스트해보니 200 정상작동이 되는데
혹시 저희 서버의 아이피가 막혔거나 하는 문제인지 궁금합니다
왜 특정서버에서 403이 발생하는지 궁금합니다
![KakaoTalk_20201006_130940814](https://user-images.githubusercontent.com/72428330/95157910-47440280-07d5-11eb-841d-afe9cccbff27.png)
![KakaoTalk_20201006_130940814_01](https://user-images.githubusercontent.com/72428330/95157921-4b702000-07d5-11eb-8810-98093c4c054f.png)

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

403 메시지가 `Invalid Timestamp`이고 특정 서버만 해당된다고 하니
해당 서버의 server time이 잘 맞고 있는지 확인이 필요해 보입니다.

**Comment by hyunjoo123** [comment]
원래 문제가 되고있는 서버에서도 잘 되었었는데 9월10일 이후로 403이 뜨며 안되거든요ㅠㅠ
뭐가 문제일까요?ㅠ
