### ISSUE TITLE
api 에러문의

### ISSUE THREAD

**Issue by xptmxm1231** [naver/searchad-apidoc#454]
/estimate/average-position-bid/

이 API 문서상에서는 200개라고 되어있는데

100개정도 넣고 넘기면 400에러 뜨구요

특정 키워드 긴거 20개만 넘겨도 status 는 200이 뜨는데 결과값이 빈값으로 넘어오네요

10개 까지가 안정권 같은데 이거 확인좀 부탁 드립니다.

/estimate/performance-bulk

이것도 200개까지라고 되어있는데 마찬가지인것 같습니다.

확인 부탁 드립니다.

**Comment by naver-searchad** [comment]
안녕하세요. 검색광고API입니다.
오류가 발생한 요청의 TransactionId를 알려주시면 확인 후 답변 드리도록 하겠습니다.

**Comment by xptmxm1231** [comment]
TransactionId unknown 으로 뜹니다.
