### ISSUE TITLE
keywordstool 관련 문의드립니다.

### ISSUE THREAD

**Issue by worldskysarang** [naver/searchad-apidoc#458]
keywordstool을 사용하여 월별(e.g. 1,2,3,4) 키워드 검색수를 찾는 기능을 구현하려고 하는데

관련된 쿼리파라미터를 알고 싶습니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

답변이 늦어 죄송합니다.
해당 API는 월별 키워드 검색수를 공식 지원하고 있지 않습니다.
