### ISSUE TITLE
용어문의 

### ISSUE THREAD

**Issue by EDMAI** [naver/searchad-apidoc#459]
안녕하세요, 가이드문서(https://github.com/naver/searchad-apidoc)를 보고 궁금한 점있어서 여쭤봅니다. 
내부팀과 커뮤니케이션을 해야하는데 개발을 잘 모르는 부서여서 이에 따른 어려운 점이 있어서 여쭤봅니다.

1. 여러 API들 중에서, 예를 들어 AdExtension: list (by ids) 에서 
list라고 명명되었는데요,이와 같이 대부분의 API가 list라는 단어와 함께 명명되어 있습니다.

list라고 명명된 것은 
array 형태로 데이터를 반환해서 그런건지요? 

2. Data type에서 object인 데이터타입은 숫자와 문자 혼용인지 궁금합니다. 

3. 가이드 문서를 보니 API에서 반환되는 데이터를 프로퍼티라고 명명되어 있는데요, 
프로퍼티로 명명된 다른 이유가 있을까요? 혹은 그냥 data 정도로 이해할 수 있는지요?

4. Adgroup API에서 
list (keyword plus restricted keywords), list (by ids), list (by campaign id)와 같은 methods가 정의되었는데 
이러한 메서드들은 API 내 정의된 함수 정도로 이해하면 될까요?

5. AdExtension(http://naver.github.io/searchad-apidoc/#/tags/AdExtension)에서 
Resource representations라고 되어 있는데 여기서 말하는 Resource란 어떤 것인지요?
restAPI를 따르기 때문에 Resource가 되는것인지요? 

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

대부분 이해하신 내용을 적어주셔서 따로 답변 드리지 않아도 될 것 같구요
응답 형태가 json이라는 점만 이해하시면 될 것 같습니다.
list(by ~) 형태는 동일한 api를 search 할 조건을 parameter 형태로 분리해서 명시한 것이라고 보시면 되겠습니다.
