### ISSUE TITLE
/ncc/campaigns API와 관련하여 문의드립니다.

### ISSUE THREAD

**Issue by kimdohoyeong** [naver/searchad-apidoc#46]
https://goo.gl/hHySQr에 나와있는 Response항목중
명세 되어 있지 않은 
migType과 expectCost는 어떤 데이터를 나타내는건가요?
감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요
campaign response에서 migType과  expectCost는  일반적으로 사용자에게 의미 없는 프러퍼티입니다.
migType은  새로운 검색광고 오픈 초기에  시스템적으로 구분을 위해 사용했지만 지금은 더이상 사용치 않습니다.  
또한 expectCost은 캠페인 전체과금액이  하루예산에 도달되어 잠겼을때만,  보여지는  예상과금액의 용도로서  사용자들이  일반적으로 사용되어 지는 값은 아닙니다.
migType은 response 항목에서 제외될 예정입니다
참고 부탁드립니다

**Comment by kimdohoyeong** [comment]
감사합니다! 하나만 더 여쭤보겠습니다..
캠페인 생성 API를 사용하였을 때 다음과 같은 에러가 뜨는데  왜 그런건가요?

```
'{"title":"Bad Request","status":400,"detail":"Could not read document: Can '
 'not deserialize instance of com.naver.searchad.heroes.domain.ncc.NccCampaign '
 'out of START_ARRAY token\\n at [Source: '
 'java.io.PushbackInputStream@1f980a19; line: 1, column: 1]; nested exception '
 'is com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize '
 'instance of com.naver.searchad.heroes.domain.ncc.NccCampaign out of '
 'START_ARRAY token\\n at [Source: java.io.PushbackInputStream@1f980a19; line: '
 '1, column: 1]"}')
```

보내는 값은 
`[{"campaignTp": "WEB_SITE", "name": "\ub09c\ub2c8\uac00\uc815\ub9d0\uc88b\uc544"}]`
입니다.

만약 `{"campaignTp": "WEB_SITE", "name": "\ub09c\ub2c8\uac00\uc815\ub9d0\uc88b\uc544"}`와같이
array json이 아닌 객체 하나만 보낼 경우

'{"code":1018,"status":404,"title":"No permission to access the resource."}' 가 뜨네요..

**Comment by naver-searchad** [comment]
캠페인 생성 api는  캠페인 생성 object 요청만 받을수 있습니다.
customerId 값을 추가하여   아래 처럼 요청하시면  될것 같습니다.  
{
  "campaignTp": "WEB_SITE", 
  "name": "xxxx",
  "customerId":  xxxx
}

**Comment by kimdohoyeong** [comment]
감사합니다.
