### ISSUE TITLE
비즈니스 채널과 관련하여 문의 드립니다.

### ISSUE THREAD

**Issue by devfreshi85** [naver/searchad-apidoc#460]
안녕하세요. 비즈니스 채널과 관련하여 문의드립니다.

채널 URL : http://abc.co.kr 를 사용하고,

소재의 모바일 URL를 http://m.abc.co.kr/product를 사용할 경우, 소재 승인이 안나나요?

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

질문하신 내용은 API 사용 문의가 아닌 검색광고 운영 문의에 해당합니다.
광고시스템 내 도움말을 이용해 주시기 바랍니다.
