### ISSUE TITLE
광고 그룹 조회의 타겟팅 정보 관련하여 문의 드립니다.

### ISSUE THREAD

**Issue by devfreshi85** [naver/searchad-apidoc#461]
광고 그룹을 조회할 때, (by campaign id) 나 (by ids)에 ID 여러개를 전송할 경우,

target 은 응답되지 않고, targetsummary(연동규격서에 미존재함) 로 응답하고 있습니다.

(by ids) 에 ID를 1개를 전송할 경우, target이 정상적으로 응답되고 있습니다.

연동규격서와 다른데, campaign id나 ids를 여러개 보낼때, 한번에 target 정보를 수신 받을 수 있는 방법은 없나요?

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API 입니다.

광고그룹의 타겟팅은 단건 조회시에만 포함되도록 설정되어 있습니다.
여러건의 그룹을 조회할 경우 Response의 크기가 커지고, 사용하지 않는 정보가 포함되는 문제가 있어 여러건 조회시 요약 정보만 포함되고 있습니다.

다수 광고그룹의 타겟팅을 조회하고자 하실때는 http://naver.github.io/searchad-apidoc/#/operations/GET/~2Fncc~2Ftargets%7B%3FownerId,types%7D 이 API를 사용하시면 됩니다.

감사합니다.
