### ISSUE TITLE
리포트 컬럼 의미

### ISSUE THREAD

**Issue by lachelngose** [naver/searchad-apidoc#462]
리포트를 다운받으면 데이터가 배열로 들어있는데,
stat report 의 각 컬럼별 의미가 정리된 페이지가 있나요?
guide 페이지에 있었던 것 같은데 못 찾겠네요ㅜ

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

http://naver.github.io/searchad-apidoc/#/tags/StatReport
stat report 의 overview에 보시면 report type별 컬럼 정의들을 보실 수 있습니다
