### ISSUE TITLE
자동입찰 설정(beta) 사용시 질문입니다.

### ISSUE THREAD

**Issue by kaorimikage** [naver/searchad-apidoc#464]
자동입찰 설정(beta) 기능을 사용하면 Adgroup에서 systemBiddingType 의 값을 ML로 주는것으로 알고 있습니다.

그런데 네이버 광고센터 고객센터에 문의해보니 해당 기능이 입찰경쟁이 심화되어 광고비가 많이 나갈 것으로 예상되는 시간에는 자동으로 광고를 ON/OFF 한다고 하더군요. 이때 광고 ON/OFF의 여부를 API로 확인할 수 있는지 알고 싶습니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

확인과 답변이 늦었습니다.

파워링크 광고에서 자동입찰 기능을 사용하면, 광고비 소진을 24시간 이내 골고루 배분하기 위해 임의로 광고 노출을 조정합니다. 
특정 시점에 광고그룹의 소진율이 평균적인 소진율보다 높으면 일시적으로 광고를 노출하지 않습니다.
노출여부는 파워링크 광고 노출서버에서 매 노출시점마다 판단하고 있습니다.
노출여부에 대한 판단이 빠르게 진행되며 그 상태가 매우 일시적이기 때문에,
그 상태를 저장하고 API로 제공하는 등의 프로세스는 어렵다고 보시면 좋을 것 같습니다.
