### ISSUE TITLE
네이버 광고 키워드 도구의 "월별 검색수 추이", "월간 검색수 사용자 통계"에 대한 API는 없나요?

### ISSUE THREAD

**Issue by HeysenChoi** [naver/searchad-apidoc#465]
안녕하세요, 
네이버 광고 API를 활용하고자 문서를 보고있는데,
연관키워드 (RelKwdStat)는 정상적으로 사용하고 있습니다.
그런데, 웹상에서 제공하는"월별 검색수 추이", "월간 검색수 사용자 통계"에 대한 API는 없나요?

확인한 바로 아래 request로 요청이되는 것같은데, api는 따로 정의되지 않아서 이렇게 문의드립니다.

https://manage.searchad.naver.com/keywordstool?format=json&hintKeywords=&includeHintKeywords=0&siteId=&biztpId=&month=&event=&showDetail=1&keyword=0000

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

해당 API는 정식으로 지원하고 있지 않습니다.
