### ISSUE TITLE
/stat get 메소드 timeRange 관련 문의드립니다. 

### ISSUE THREAD

**Issue by dearplan** [naver/searchad-apidoc#466]
안녕하세요. 혹시 당일의 데이터를 가져올때 

`timeRange = '{"since":"2020-10-29","until":"2020-10-29"}'`
로 가져오면 안되나요? 

datePreset = 'today'로 가져올땐 데이터를 잘 가져오는데 timeRange로 당일 데이터를 가져오려고 하니 아무것도 넘어오지 않아서요. 

감사합니다. 

언어는 python입니다. 

@naver-searchad

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.
확인이 늦어져서 죄송합니다.

timeRange 는 일별 데이터 제공 용도이며 일별 지표는 익일 집계 후에 확정되므로
timeRange를 통해서는 당일지표를 받아보실 수 없습니다.
당일 지표는 datePreset = today 를 통해서만 제공됩니다.

**Comment by dearplan** [comment]
답변 감사합니다! 그렇군요. 살짝 아쉽네요 ㅠㅠ 

-----Original Message-----
