### ISSUE TITLE
AD 생성(소재 등록) 시 product ID 전달 관련

### ISSUE THREAD

**Issue by bellamy-k** [naver/searchad-apidoc#467]
광고 생성시 referenceKey 항목을 이용해서 쇼핑상품 ID를 넘겨 광고를 제작할 수 있다는 것을 알았는데요,
혹시 쇼핑상품 ID가 아니라 몰 상품 ID를 이용해서 소재를 등록하고 싶다면 어떻게 해야 할까요?
`
{
        "customerId":'2060998',
        "nccAdgroupId":adgroupID,
        "type":"SHOPPING_PRODUCT_AD",
        "adAttr":
        {
            "useGroupBidAmt":False,
            "bidAmt":100
        },
        "referenceKey" : productID, #오류
        "userLock" : 0
}
`

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

답변이 늦었습니다.
쇼핑상품 광고의 경우 정식으로 지원하는 스펙이 아닙니다.
원하시는 유형의 지원은 제공되고 있지 않습니다.
