### ISSUE TITLE
캠페인생성시 404오류 질문드립니다.

### ISSUE THREAD

**Issue by JungHunYu** [naver/searchad-apidoc#468]

**Comment by JungHunYu** [comment]
같은 계정의 api키와 시크릿키로 캠페인목록은 잘불러와집니다.
헌데 같은 로직으로 캠페인생성은  {"code":1018,"status":404,"title":"No permission to access the resource."}

라고 나옵니다.
애초에 권한이 없다고 나올꺼면 캠페인목록또한 불러와지면 안됩니다.
권한이있으니 캠페인목록은 잘불러와지고
캠페인생성또한 다른누구의 캠페인을 edit,delete 하는게 아니고 새로이 생성하는것이므로 남에꺼 만지는게
아니라 생각됩니다.

답변부탁드립니다.
customerId	customerNm	apiKey
1018467	솔루티온	01000000002938fdd9342175eb9a85c76b3c2ba7da060d42f34b33a702373bfd0dd63ac420

시크릿키는 첨부하지않았습니다.

생성 body 부분입니다.
{"campaignTp":"WEB_SITE","name":"1111","dailyBudget":"10000","deliveryMethod":"ACCELERATED","periodEndDt":"2020-11-01T00:00:00.000Z","periodStartDt":"2020-11-02T00:00:00.000Z","trackingMode":"AUTO_TRACKING_MODE","trackingUrl":"http://tracking.sample.com/?n_final_url={final_url}","useDailyBudget":"true","usePeriod":"false","userLock":"true"}

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API 입니다.

캠페인 생성시 Body에 customerId 값이 포함되어 있어야 합니다.

감사합니다.

**Comment by JungHunYu** [comment]
해결되었습니다.
https://naver.github.io/searchad-apidoc/#/operations/POST/~2Fncc~2Fcampaigns
캠페인 생성 문서에 customerid 가 언급이안되어있는데
문서보완이 필요해보입니다.
