### ISSUE TITLE
MasterReport  Keyword 데이터 시간별로 차이나는 문제.

### ISSUE THREAD

**Issue by dnt-walker** [naver/searchad-apidoc#469]
안녕하세요!

MasterReport로 Keyword 정보를 가져오는데 AM. 01시때와 AM. 10시 데이터에서 전일 등록한 키워드가 차이가 납니다.

요청 정보는 아래와 같습니다.

AM. 01시 요청 
Transaction-ID=05B3C84EF350FD7E2A866CAE23C77EFC
item=Keyword
fromTime=2020-10-27T15:00:00Z
updateTime=2020-11-04T16:01:00Z

AM. 10시 요청 
Transaction-ID=E5889D65177D628D181C2AF07E0BCC77
item=Keyword
fromTime=2020-11-03T15:00:00Z
updateTime=2020-11-05T01:21:00Z

조회 기간은 다르나 전일 등록된 키워드만 비교했을때 1시에 요청한 리포터에는 존재하지 않고 10시에 요청한 리포트에서는 해당 키워드가 나타납니다.

전일 등록 키워드의 등록시간은 아래와 같습니다.
2020-11-04 11시 등록건 14
2020-11-04 17시 등록건 208

@naver-searchad 
확인 부탁드립니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

다른 채널로 동일 내용을 문의주신 듯한데요
구체적으로 차이를 발견하신 키워드 정보(id)를 알려 주셔야 좀 더 명확하게 답변을 드릴 수 있을 것 같습니다.
