### ISSUE TITLE
오늘 새벽시간에 점검이 있었나요?

### ISSUE THREAD

**Issue by FreeEgo** [naver/searchad-apidoc#47]
오늘 새벽에 예상견적가 받아오는 작업이 전부 실패했는데요,

9일 새벽 점검은 확인했는데 오늘도 점검이 있었는지 궁금합니다.

**Comment by naver-searchad** [comment]
안녕하세요.
새벽에 장비 문제로 견적 서비스가 정상 수행되지 않았습니다.
불편을 드려서 대단히 죄송합니다.

**Comment by FreeEgo** [comment]
빠른 답변 감사합니다~
