### ISSUE TITLE
How to GET cost data for pre-paid contract campaign

### ISSUE THREAD

**Issue by imaksp** [naver/searchad-apidoc#470]
Hi, how to cost data for pre-paid contract cpm campaign. I am getting other values like impressions, clicks but cost is always zero.

**Comment by naver-searchad** [comment]
Hello, this is Naver Search Ad. API.

If you mean 'Brand Search' campaign, 'cost' is not provided.
As you mentioned Brand Search is a 'pre-paid', it is periodical product so does not cost for any impression or click.

**Comment by aksdevac** [comment]
@naver-searchad ok but can I get total amount which is paid in advance?

**Comment by naver-searchad** [comment]
@aksdevac 
there is no api reference about what you described
but you can check our web manage system, Tools - Manage contract.
