### ISSUE TITLE
StatReport 데이터가 시간별로 차이나는 문제에 대해 확인 부탁드립니다.

### ISSUE THREAD

**Issue by mirr7656** [naver/searchad-apidoc#471]
안녕하세요~

StatReport로 Keyword 정보를 가져오는데 AM. 04시대와 AM. 09시대의 데이터에 차이가 있습니다.
PC와 mobile 데이터 각각의 차이에 대한 확인 요청을 드리며, 조회와 관련한 정보는 아래와 같습니다.

1-1. PC stat report 요청 시간 : 11-12 07:48:50
     Transaction-ID : BLN5VL1L1DHTG
     Data count : 117,902
     Keyword-ID : nkw-a001-01-000002599863977
     AD-ID : nad-a001-01-000000103002946
     Impression : 0
     Click : 0
     Cost : 0
     Keyword-ID : nkw-a001-01-000002599863977
     AD-ID : nad-a001-01-000000111809838
     Impression : 0

1-2. PC stat report 요청 시간 : 11-12 09:45:49
     Transaction-ID : BLN7L6TEHDIUA
     Data count : 262,027
     Keyword-ID : nkw-a001-01-000002599863977
     AD-ID : nad-a001-01-000000103002946
     Impression : 51,460
     Click : 2
     Cost : 420
     Keyword-ID : nkw-a001-01-000002599863977
     AD-ID : nad-a001-01-000000111809838
     Impression : 50,959

2-1. Mobile stat report 요청 시간 : 11-12 07:48:49
     Transaction-ID : BLN5VL1HHDI3C
     Data count : 132,448
     Keyword-ID : nkw-a001-01-000003248022665
     AD-ID : nad-a001-01-000000111775539
     Impression : 0
     Click : 0
     Cost : 0

2-2. Mobile stat report 요청 시간 : 11-12 09:45:49
     Transaction-ID : BLN7L6T6HDGOQ
     Data count : 308,102
     Keyword-ID : nkw-a001-01-000003248022665
     AD-ID : nad-a001-01-000000111775539
     Impression : 39,873
     Click : 491
     Cost : 213,130

**@naver-searchad** 
확인을 부탁드립니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

2020-11-12 07:48:58.0
2020-11-12 09:45:58.0
양 시간에 걸쳐 응답된 데이터는 동일한 것으로 확인됩니다.
여러 광고자 데이터를 처리하시는 가운데 혼동하신 것이 아닌가 생각됩니다.
