### ISSUE TITLE
AdKeyword: list (by ids)  limit 문의

### ISSUE THREAD

**Issue by githubcnsbs** [naver/searchad-apidoc#472]
GET /ncc/keywords{?ids} 를 이용하여 keyword list를 가져오려고 합니다.
ids로 한번에 요청할 수 있는 Keyword의 개수 limit이 있는지 문의 드립니다.

AdKeyword: update-items (PUT /ncc/keywords{?fields})
AdKeyword: delete-items (DELETE /ncc/keywords{?ids})
의 한번에 요청할 수 있는 list limit도 같이 알려주시면 감사하겠습니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

특별히 제한은 없으나 http 프로토콜 상에서 url과 query parameter를 합쳐 길이 제한이 있을 것입니다.
