### ISSUE TITLE
광고 소재 등록시 ad Object에 대한 문의

### ISSUE THREAD

**Issue by yeongyu-dbase** [naver/searchad-apidoc#473]
@naver-searchad 안녕하세요, API 관리자님.

네이버 검색 광고 api를 보던중 문의 드릴 사항이 생겨 문의 남깁니다.
네이버 api중 /ncc/ads 를 보면 ad object의 예제가 
```
{
  "pc": {
    "final": "http://searchad.naver.com"
  },
  "mobile": {
    "final": "http://m.searchad.naver.com"
  },
  "headline": "the first line",
  "description": "the second line of your ad text"
}
``` 
로 되어있지만, 이것 외에 다른 데이터도 들어가는 것으로 보입니다.
그리하여, 좀 더 상세한 오브젝트 정보를 알려 주실 수 있으실까요?

Ps. 그 외 타 api 명세도 그냥 Map<String, Object> 형태의 명세가 많은데,
이에 관련된 상세 명세를 볼 수 있는 곳이 따로 있을까요? 따로 없다면, 
상세한 정보를 공유해주면, 네이버 검색 광고 api 연동하는데 좀 더 수월하게 개발 가능 할 것 같습니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

검색광고 APi에서 소재는 파워링크 유형에 대해서만 예제로 제공하고 있습니다.
APi로는 파워링크 상품의 소재 관리만 권장되기 때문인데요
다른 상품 유형의 경우 주로 광고시스템에서 인터페이스를 통해서 소재를 등록하고 관리하는 게 정석입니다.

이들 상품 소재에서는 타 서비스와의 연동 데이터 등이 사용되므로 APi 사용만으로는 모든 관리가 어렵습니다.
또한 하나의 상품 소재이더라도 관리성격에 따라 데이터 스키마가 변경될 수 있으므로
하나의 명세로 유지 및 스키마를 제공하기 어려운 환경입니다.

관련해서 이러한 이유들로 Map object 형태로 제공되는 여타 property들의 명세를 유지하고 제공하는 것이 어렵습니다.
이 점 양해해 주시기 바랍니다.

**Comment by yeongyu-dbase** [comment]
@naver-searchad 
그렇다면, ad 등록 시 type 이
```
TEXT_45
SHOPPING_PRODUCT_AD
CONTENTS_AD_INFORMATION
CONTENTS_AD_PRODUCT
BRAND_SEARCH_AD
PLACE_AD
CATALOG_AD
```

이렇게 있는데
이 중에 TEXT_45에 대한 예제만 표시 되고 있는데, `SHOPPING_PRODUCT_AD` 타입에 대한 예제는 어떻게 되나요?!

**Comment by naver-searchad** [comment]
@yeongyu-dbase 
`TEXT_45` 타입이 곧 파워링크 캠페인 유형에 해당하는 소재 타입입니다.
먼저 답변드린 바와 같이
다른 소재 타입들의 경우 예제나 명세가 제공되지 않으므로
실제 데이터를 통해 데이터 구조를 파악하셔야 한다는 의미였습니다.

광고시스템 이용을 계속 권장하는 이유는
가령 쇼핑광고 소재의 경우 등록시 쇼핑서비스로부터 연동받은 데이터가 필요한데
이를 api로는 구현이 되지 않기 때문입니다.
