### ISSUE TITLE
Adgroup update (by fields) 질문드립니다.

### ISSUE THREAD

**Issue by JungHunYu** [naver/searchad-apidoc#474]
수정하고자하는 항목은 contentsNetworkBidAmt 이구요

Body JSON
{"contentsNetworkBidAmt":"100","nccAdgroupId":"grp-a001-01-000000019037544"}

URL
https://api.naver.com/ncc/adgroups/grp-a001-01-000000019037544?fields=contentsNetworkBidAmt

Return
Not support modify field.

Header 같은경우는
기존에 쓰는걸 동일하게썼구요
그냥 bidAmt 같은경우는 수정이 잘됩니다.

**Comment by naver-searchad** [comment]
@JungHunYu
안녕하세요? 네이버 검색광고  API 입니다.

콘텐츠 네트워크 입찰가를 수정하기 위해서는 , fields 파라미터의 값을 `contentsNetwork` 값을 사용하셔야 합니다.

감사합니다.

**Comment by JungHunYu** [comment]
Cannot handle the request.   라는 에러메세지가나오는데 이거는 무슨뜻인가요?

**Comment by naver-searchad** [comment]
@naver-searchad 콘텐츠 네트워크 입찰가 사용여부를 나타내는 값이 빠져있습니다.
```
"useCntsNetworkBidAmt": boolean
```
