### ISSUE TITLE
AdExtension update에서 Query parameters  fields[] string fields  다중으로 주고싶을때

### ISSUE THREAD

**Issue by JungHunYu** [naver/searchad-apidoc#477]
Query Parameter 인데 어떻게 배열로 넘겨야할까요?
명세서에서는

fields[] | string | fields
이런식으로 배열로 넘기게끔되어있는데
Request Body야 Json 을 조합해서 보내면 됬었지만
Query Parameter 에 설마 Json을 조합해서 보내진 않겠지하고
?fields=period,userLock  이런식으로 주면 안되더군요

예를들어 period와 userLock을 동시에 Update하고싶다면
어떻게 해야하나요?

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

period와 userLock은 동시에 업데이트 할 수 없습니다.
fields[] 형식이 존재하는 경우는,
period 업데이트 요청시 fields=usePeriod,periodStartDt,periodEndDt 와 같이 요청해야 하기 때문입니다.
