### ISSUE TITLE
search

### ISSUE THREAD

**Issue by JungHunYu** [naver/searchad-apidoc#478]
Query Parameter 인데 어떻게 배열로 넘겨야할까요?
명세서에서는

fields[] | string | fields
이런식으로 배열로 넘기게끔되어있는데
Request Body야 Json 을 조합해서 보내면 됬었지만
Query Parameter 에 설마 Json을 조합해서 보내진 않겠지하고
?fields=period,userLock  이런식으로 주면 안되더군요

예를들어 period와 userLock을 동시에 Update하고싶다면
어떻게 해야하나요?

**Comment by naver-searchad** [comment]
@JungHunYu 
#477 에 동일한 문의를 하신 내용에 대해 답변해 드렸으니 참고하시기 바랍니다
