### ISSUE TITLE
BusinessChannel Image와 관련하여 문의드립니다.

### ISSUE THREAD

**Issue by kimdohoyeong** [naver/searchad-apidoc#48]
BusinessChannel API요청시 반환되는 
`thumbnailPath`,  `originalPath` 의
`baseURL`을 알 수 있을까요?

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요.
해당 path의 도메인은

http://adimg.search.naver.net 

을 이용하시면 될 것 같습니다.
감사합니다.

**Comment by kimdohoyeong** [comment]
감사합니다.
