### ISSUE TITLE
RelKwdStat: list api 관련 문의 입니다.

### ISSUE THREAD

**Issue by jklee0219** [naver/searchad-apidoc#480]
month 라는 파라메터가 있는데 12를 넣으면 최근 12개월 치가 나오는건가요? 이 파라메터는 값을 아무리 변경해도 키워드 클릭수 결과 값이 같은것 같아서요. 제가 원하는 부분은 현재 부터 한달치를 가져오는게 아니라 예를들어 작년 5월 데이터도 가져오고 싶은데 그건 불가능 할까요?

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

기본적으로 광고시스템의 '키워드 도구'에 사용하기 위한 API입니다.
즉 키워드 도구에 없는 기능은 지원하지 않습니다.
month는 키워드 hint를 이용하지 않았을 때의 연관 키워드 힌트로 사용하기 위한 정보입니다.
키워드 성과와는 무관합니다.
