### ISSUE TITLE
/ncc/keywords?ids 빈 배열이 돌아오는 경우...

### ISSUE THREAD

**Issue by gw-ascent** [naver/searchad-apidoc#481]
stat report에 있는 광고 키워드 아이디들로
/ncc/keywords?ids 를 호출하면 빈 배열이 응답으로 오는 경우가 있던데 
이건 어떤 경우 인가요?

이 아이들 중 일부를
/ncc/keywords 로 하나씩 조회해 보면
{
    "code": 1018,
    "status": 404,
    "title": "No permission to access the resource."
}
이렇게 퍼미션 에러가 나던데
빈배열로 돌아오는 모든 아이디가 전부 퍼미션 에러 케이스밖에 없는건가요?

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

404 permission 에러는 요청한 id가 존재하지 않거나 customer의 소유가 아닌 경우 발생합니다.
그리고 id 중 하나의 오류이더라도 전체 오류와 함께 정상 id들도 리턴이 되지 않습니다.

**Comment by gw-ascent** [comment]
> 안녕하세요, 네이버 검색광고 API입니다.
> 
> 404 permission 에러는 요청한 id가 존재하지 않거나 customer의 소유가 아닌 경우 발생합니다.
> 그리고 id 중 하나의 오류이더라도 전체 오류와 함께 정상 id들도 리턴이 되지 않습니다.

아 예 감사합니다. 한가지만 더 여쭤보겠습니다. id가 존재하지 않는데 stat report에 나타날 수가 있나요?

**Comment by naver-searchad** [comment]
@gw-ascent 
삭제된 id의 경우 과거 성과지표가 존재하면 report에 포함될 수 있습니다
