### ISSUE TITLE
Reports 에러

### ISSUE THREAD

**Issue by tkwon365** [naver/searchad-apidoc#482]
안녕하세요.

API를 통해 stat-reports, master-reports를 수신해 오고 있었습니다.
잘 동작하던 API가 2021년 1월 9일 오전 8시경부터 403 에러를 반환하며 동작하지 않고 있습니다.
리포트 생성하는 API를 호출하면 403 에러가 반환됩니다.

혹시 변경 사항이 있었을까요?

확인 부탁 드리겠습니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

API 변경사항은 따로 보고된 바 없습니다.
그리고 관련된 문의도 추가 확인된 바 없는 걸로 봐서는
사용하시는 customer 계정 상태가 정상인지 혹은 대행권한이 변경된 점은 없는지 먼저 확인해 보시기 바랍니다.

확인 결과 별다른 이유가 없으시면,
요청한 request 상세 정보를 남겨 주셔야 저희 측에서 추가 확인이 가능하겠습니다.

**Comment by tkwon365** [comment]
서버 시간이 1분 느려서 생긴 이슈로 확인 되었습니다.
덕분에 빨리 원인을 찾을 수 있었습니다.

감사합니다.
