### ISSUE TITLE
imageid 에대한 api는 없는건가요?

### ISSUE THREAD

**Issue by JungHunYu** [naver/searchad-apidoc#483]
api로 AD_Extention 을 구현중인데 
이미지에 관련없는 타입들은 대부분 구현했는데
이미지가 들어가는 파워링크 이미지 등록같은경우
ImageID를 입력하는게 아니라

요청
/api/tool/imageLibrary/img-a001-00-000000004649587

응답
{"customerId":1018467,"imageId":"img-a001-00-000000004649587","imageType":"AD_EXTENSION_COMMON","uploadFileName":"파워링크이미지.png","imagePath":"/MjAyMTAxMDRfMzkg/MDAxNjA5NzQxNDgwMjUx.8l_5_LMRiweYwcRjevSNEQ4orpRNfgUj8Zea8uA8Wpgg.5WxAZOPEusTJf3BSP_Su40-DHMRaI6rc4eskp0FMb3cg.PNG/1018467-22dc22d6-2e72-4d66-9de2-5c5320aadbc2.png","regTm":"2021-01-04 15:24:40.0"}

을 통해서 ImageID가 아닌 imagePath를 등록하더군요(네이버광고센터에서...)

API Document 에는 ImageID에 관한 내용이 없습니다.

imagePath를 가져오는 api  or  파워링크 이미지등록시 IMAGEID 로 등록하는법중 가이드 해주시면될것같습니다.

**Comment by naver-searchad** [comment]
@JungHunYu 안녕하세요? 네이버 검색광고 API입니다.

imagePath 조회 또는 imageID를 이용하는 API는 공식 지원 API가 아닙니다.
추후 지원여부에 대한 부분은 내부적으로 검토해 보도록 하겠습니다.

감사합니다.

**Comment by JungHunYu** [comment]
그럼 API로 AD_Extention  파워링크 이미지 등록은 어떻게 하라는건가요?
ImageID를 받아야 등록이가능한데 Create 시 등록 할 수 있도록 만들어 놓으시고 ImageID를 입력하는 칸을 안만들어놓고
ImagePath 로 해놓으시면 API 이용자 못사용하는거 아닌가요?
