### ISSUE TITLE
AD_Extention 파워링크 이미지 등록은 어떻게 하나요?

### ISSUE THREAD

**Issue by JungHunYu** [naver/searchad-apidoc#484]
그럼 API로 AD_Extention 파워링크 이미지 등록은 어떻게 하나요?
ImageID를 받아야 등록이가능한데 Create 시 등록 할 수 있다고 Document 에는 있으나
정확한 JSON레이아웃 내용은 없습니다.
네이버 광고센터에서 하는 방식을 가져와서
흉내를 내봤지만 저희는 ImageID만  알수있는 상황에서
ImagePath를 받게끔 되어있습니다.
1. ImagePath를 알수있는 API가 제공되거나
2. ImagePath를 받는 모든 API에 ImageID or ImagePath 둘중 하나가 들어와도 되도록 로직변경이 필요해보입니다.

현상황에서 어떻게 해야
AD_Extention  Create 
type = POWER_LINK_IMAGE
을 할 수있습니까?

**Comment by naver-searchad** [comment]
@JungHunYu 안녕하세요? 네이버 검색광고 API 입니다.

이미지형 확장소재의 등록은 API에서 공식 지원하지 않습니다.
이미지형 확장소재의 등록은 네이버 검색광고 광고주센터(https://searchad.naver.com)에서 등록하셔야 합니다.

감사합니다.
