### ISSUE TITLE
디스플레이 광고 API 제공 여부 문의드립니다.

### ISSUE THREAD

**Issue by bluesyoo** [naver/searchad-apidoc#485]
안녕하세요,
성과형 디스플레이 광고 API 도 제공중이신가요?
아직 API가 제공중이 아니면 혹시 언제쯤 제공계획이 있으신지 알 수 있을까요?
감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

현재 디스플레이 광고 API는 제공되고 있지 않습니다.
당분간, 특히 연내에 제공되기는 어려울 것 같습니다.
시장의 니즈와 광고주 분들의 요구사항이 충분히 접수되면 검토될 수 있을 것으로 생각됩니다.
