### ISSUE TITLE
How to change the number of data in '/keywordstool' api

### ISSUE THREAD

**Issue by epsilon-deltta** [naver/searchad-apidoc#486]
I wanna get just 100 keywords but ...default setting is 1000 ...
So, is there any option to change the number of data in getting data?

ps. i can customize the number of data after getting data.
but i wanna get certain number of data before fetching data

**Comment by naver-searchad** [comment]
Hello, this is Naver SearchAd API.

'keywordstool' api's 1000 response is fixed number so you can't set to wanted size.
I'm very sorry that I can't help you any more!

**Comment by epsilon-deltta** [comment]
ㅠㅜ 😥
could you add this on next development cycle?

**Comment by naver-searchad** [comment]
@epsilon-deltta 
I'm afraid it can't be done in the near future,
but we can put your request on the `voc` list.
Thank you!

**Comment by epsilon-deltta** [comment]
thanks
