### ISSUE TITLE
POS 페이지에 대한 API가 있나요?

### ISSUE THREAD

**Issue by lhw8611** [naver/searchad-apidoc#488]
POS페이지->  영업 -> 이관, 피이관 요청이력을 실시간으로 받아보고 싶은데 관련 API는 없나요?

doc.api.naver.com 이 문서에는 없는 거 같고

POS 페이지에 'API 라이선스 관리' 페이지가 있어서 찾아보고 있는데 못찾겠네요

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

api 공식 문서 외에 지원되는 api는 없습니다. 감사합니다.
