### ISSUE TITLE
새벽에 예상견적을 받아오지 못했습니다.

### ISSUE THREAD

**Issue by FreeEgo** [naver/searchad-apidoc#49]
혹시 점검인건가요?

그리고 장비교체나 점검시 공지하는 주소가 있는지 궁금합니다.

**Comment by naver-searchad** [comment]
안녕하세요.
오늘 점검은 없었습니다. 
문제가 발생한 시간대와 Transaction-ID를 알려주시거나, 
응답으로 받으신 오류 메시지등을 알려주시면 확인해보도록 하겠습니다.
참고로 점검 공지는 네이버 검색광고 페이지의 공지사항을 통해서 안내해드리고 있습니다.

http://searchad.naver.com/AIHM20/AIHM2001_A01.nbp
