### ISSUE TITLE
Incorrect ids format when using get stat by ids

### ISSUE THREAD

**Issue by anezkap** [naver/searchad-apidoc#490]
Hi there,

I am trying to get statistics for specific campaigns/ad groups/ad/ad keywords, but I am unable to find the correct format in which I should pass the ids parameter. So far I have tried the following but without any success.

`https://api.naver.com/stats?ids=cmp-1234,cmp-5678,cmp-9102&fields=...`
`https://api.naver.com/stats?ids=[cmp-1234,cmp-5678,cmp-9102]&fields=...`
`https://api.naver.com/stats?ids=["cmp-1234","cmp-5678","cmp-9102"]&fields=...`

Could you, please, let me know what the correct format is? When I try only with 1 id, i.e. id=cmp-1234, everything works fine so the rest of the query should be correct.

I am getting 11001 잘못된 파라미터 형식입니다. error.

Thank you for your help!

**Comment by naver-searchad** [comment]
Hello, this is Naver SearchAd API.

1st example you wrote down is the right format for the ids parameter.
So your error occurred not because of `ids` parameter but because of others.
Then we need rest of the parameters besides `ids` to find out what's wrong.

Or you can find out what's wrong with your requests by referencing below regular example for `stats` api.
```
api/stats?datePreset=last7days
&fields=["clkCnt","impCnt","salesAmt","ctr","cpc","ccnt","crto","convAmt","ror","cpConv","viewCnt"]
&timeIncrement=allDays
&ids=grp-a001-01-0000000000xxxx1,grp-a001-01-0000000000xxxx2,grp-a001-01-0000000000xxxx3
```

**Comment by anezkap** [comment]
Hi there,

Thank you for your quick reply!

I tried the example you provided and everything worked fine. But once I changed `timeIncrement=1` to get the daily breakdown, I got error 11002 - 지원하지 않는 기능입니다. Does this mean that the daily stats are only available for individual campaigns/groups and not for multiple? I left the rest of the parameters totally same.

Thank you.

**Comment by naver-searchad** [comment]
@anezkap 
You just can't use `timeIncrement=1` with breakdown options.

**Comment by anezkap** [comment]
Hi,

I am not using any breakdown. I am trying to use 
`api/stats?datePreset=last7days
&fields=["clkCnt","impCnt","salesAmt","ctr","cpc","ccnt","crto","convAmt","ror","cpConv","viewCnt"]
&timeIncrement=1
&ids=grp-a001-01-0000000000xxxx1,grp-a001-01-0000000000xxxx2,grp-a001-01-0000000000xxxx3`

But, could I also ask you to tell me what each of the breakdowns means and does exactly, please?

Thank you so much.

**Comment by naver-searchad** [comment]
@anezkap 
`timeIncrement=1` is avaliable only in `get by (id)`.
Now you can see those avaliable options in that [api documents](http://naver.github.io/searchad-apidoc/#/operations/GET/~2Fstats%7B%3Fids,fields,timeRange,datePreset,timeIncrement,breakdown%7D)
