### ISSUE TITLE
stat과 statReport 결과값 다릅니다

### ISSUE THREAD

**Issue by jys6367** [naver/searchad-apidoc#491]
campaignId = cmp-a001-01-000000002350545
조회날짜  2021-02-08

stat 클릭수  (clkCnt)
= 68    
statReport (AD_DETAIL) 클릭수 합계
= 66

이거 외에도 전체적으로 report의 수치가 더 낮습니다
이유가 있을까요?

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

stat의 클릭수가 statReport AD_DETAIL에서는 `Click`과 `View count (동영상 재생수)` 둘로 나뉘어 들어갑니다.
이 둘을 합한 값으로 검증하시면 될 것 같습니다.

statReport가 한번 생성한 시점의 스냅샷이기 때문에
이후 데이터 변경에 따른 stat api 내용과 다를 수는 있겠지만
기본적으로 stat과 statReport가 다를 이유는 없습니다.

**Comment by jys6367** [comment]
빠른 답변 감사합니다

클릭수와 노출수 확인했습니다

추가로 

stat의 salesAmt가 report의 cost 합계보다 더 큰 값이 나오는데 

이것도 동영상 관련된 금액일까요?

**Comment by naver-searchad** [comment]
@jys6367 
report의 금액은 부가세가 제외돼 있습니다.
1.1을 곱한 값과 stat의 금액을 비교해 보시면 될 것 같습니다.

**Comment by jys6367** [comment]
네 확인했습니다
감사합니다
