### ISSUE TITLE
About shopping search api

### ISSUE THREAD

**Issue by epsilon-deltta** [naver/searchad-apidoc#492]
검색 > 쇼핑 : https://openapi.naver.com/v1/search/shop.xml
1. sim 은 네이버쇼핑에서 네이버 랭킹과 같은 옵션인가
![image](https://user-images.githubusercontent.com/45354219/108193250-96714b00-7158-11eb-80c7-3874709668b3.png)
<get param option 중 sort >
![image](https://user-images.githubusercontent.com/45354219/108193329-abe67500-7158-11eb-9ed7-6b332e0137d4.png)
< 네이버 쇼핑 검색시 정렬에 대한>

1.1
sim 과 네이버 랭킹 옵션이 같다면 , 대부분의 동일 하나 일부 다른 것은 무엇때문인가
example 의자라는 키워드 검색시 (맨 상단 3개 광고제외) 대부분 동일 하나 'best of ~' 항목이 누락됨
![image](https://user-images.githubusercontent.com/45354219/108193742-21524580-7159-11eb-81b1-83e5a768fc19.png)

2. 맨상단 광고에 대한 정보(this is important information to me)는 왜 제공이 되지 아니 한가 ...
![image](https://user-images.githubusercontent.com/45354219/108193891-4cd53000-7159-11eb-801c-bdd312e787e5.png)
위 사진과 같은 경우 광고 3개 다음인 에어블루 커블체어 부터 api로부터 정보를 받을 수있음

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

먼저, 쇼핑의 open api와 검색광고 api는 전혀 다른 서비스입니다.
쇼핑의 서비스 api 문의에 대한 답변은 여기서 가능하지 않으므로 별도 쇼핑 서비스 채널로 문의를 하셔야겠습니다.

**Comment by epsilon-deltta** [comment]
? 그게 어떤 뜻이죠 여거 [naver development](https://github.com/naver/naver-openapi-guide) 에서 제공해주는 api에 대한 문의를 하는곳 아닌가요
 제가 한 질문은 저 개발api 에 있는 검색>쇼핑 api 에 대한 질문인데 여기다 질문하는거 아닌가요?

혹시그럼 어디다가 문의 하는지 링크좀 부탁드립니다.

**Comment by naver-searchad** [comment]
@epsilon-deltta 
이곳은 검색 `광고`의 api 사용에 대한 문의 채널입니다.
http://naver.github.io/searchad-apidoc
일반 서비스 open api와는 무관합니다.

그리고 저희가 가진 타 서비스 관련 정보가 제한적이라 open api에 대한 문의 채널이 존재하는지에 대한
자세한 안내는 어려울 것 같습니다.

**Comment by epsilon-deltta** [comment]
🤬
