### ISSUE TITLE
광고 소재 업데이트 문의

### ISSUE THREAD

**Issue by jih07090709** [naver/searchad-apidoc#494]
안녕하세요. C# 광고 소재 - 입찰가 변경 문의 드립니다.

아래 소스와 같이 진행을 했는데요, 계속해서 오류가 나오네요.

어디가 잘못 되었는지 확인 좀 부탁 드립니다..

public bool updAdBidAmt(string _adId, double _cost)
{
	var request = new RestRequest("/ncc/ads/" + _adId, Method.PUT);
	request.AddQueryParameter("fields", "\"adAttr\"");
	request.AddParameter("application/json", "{\"adAttr\":{\"bidAmt\":" + _cost.ToString() + ",\"useGroupBidAmt\":false},\"nccAdId\":\"" + _adId + "\"}", ParameterType.RequestBody);
	
	...
	
}

오류 메시지 : Content	"{\"code\":1002,\"status\":400,\"title\":\"Invalid request\"}"

**Comment by naver-searchad** [comment]
@jih07090709 
안녕하세요? 네이버 검색광고 API입니다.

 광고소재의 adAttr 수정을 위해서 `fields=adAttr` 파라미터를 이용하여 요청을 보낼때에도 http://naver.github.io/searchad-apidoc/#/tags/Ad 에서 정의한 광고 구조에 맞게 필수 프로퍼티값이 있어야 합니다.
필수 프로퍼티는 http://naver.github.io/searchad-apidoc/#/operations/PUT/~2Fncc~2Fads~2F%7BadId%7D%7B%3Ffields%7D 에 Required로 표시되어 있는 값과, `Type` 프로퍼티 입니다.

**Comment by jih07090709** [comment]
해결 했습니다. 저처럼 헤메는 초보개발자분들을 위해 해결 방법 작성합니다.

var request = new RestRequest("/ncc/ads/" + _adId, Method.PUT);
request.AddQueryParameter("fields", "adAttr");
request.AddParameter("application/json", "{"adAttr":{"bidAmt":" + _cost.ToString() + ","useGroupBidAmt":false},"nccAdId":"" + _adId + ","type":"SHOPPING_PRODUCT_AD"}", ParameterType.RequestBody);
