### ISSUE TITLE
StatReport status NONE for all the reports

### ISSUE THREAD

**Issue by anezkap** [naver/searchad-apidoc#495]
Hi there,

I am trying to use the StatReport API endpoint but I have run into an issue. I tried to create a report by sending a POST request to 

`https://api.naver.com/stat-reports`

with body

`{"reportTp": "AD", "statDt": "20201231"}`

The report job got registered and I got the report ID. Unfortunately, when I do GET https://api.naver.com/stat-reports, the status is **NONE**. I have tried with different report types and statDt as well but without any success. All the reports have status NONE. From your examples, it looks like the status is set to NONE if there are no data. But when I am using the /stat API endpoint, there are data (and we have live campaigns running). 

Did I do something wrong? Does NONE really mean there are no data? Is statDt supposed to be set to the start date from which I would like to get data about our campaigns or not? Did I forget to include something in the request?

Thank you very much for your help, it is greatly appreciated.

Anezka

**Comment by naver-searchad** [comment]
Hello, this is Naver Search Ad team.

Please leave the `Report Job ID` so we can look into what's wrong with your report.
And make sure the job left not deleted.

**Comment by anezkap** [comment]
Hi, 

Thank you very much for getting back to me this fast.

The Report Job ID is 1102594577 .

**Comment by naver-searchad** [comment]
@anezkap 
There is really no stat count in date `20201231` and the same with as many other dates.
All zero reports are not supplied through api.

**Comment by anezkap** [comment]
Hi, thank you for your reply.

Is there some suggestion on what statDt I should use then? Are there any limitations? When using the stats API endpoint, there are data for all the time periods.

Also, in what format is the returned report, please?

Thank you for your help.

**Comment by anezkap** [comment]
Hi, I have an additional question -- I wasn't able to find what the rate limits are and I have been running into 429 too many requests lately. Is the limit 100 requests per second? Thank you

**Comment by naver-searchad** [comment]
@anezkap 
We can't help that what StatDt has impressions and clicks. It's your call.
As for 429 error you should request less than 10 api call per second,
but cannot guarantee because of network or system circumstances.
