### ISSUE TITLE
[공지] 마스터 보고서 변경 공지(2021-3-17 반영)

### ISSUE THREAD

**Issue by naver-searchad** [naver/searchad-apidoc#496]
안녕하세요 검색광고 API입니다. 쇼핑검색광고 브랜드형 상품 출시에 따른 대용량 보고서의 추가/변경이 있어
이에 공지 드립니다.<br/>
참고공지 : https://saedu.naver.com/notice/view.nhn?notiSeq=3752 <br/>

**1. 대상 오퍼레이션** <br/>
MASTERREPORT<br/>

**2. 대상 보고서** <br/>
**A. 변경 보고서** <br/>
- Business Channel (item=BusinessChannel) <br/>
    *쇼핑비지니스 타입 유형 추가<br/>*
- Ad group (item=Adgroup) <br/>
   *광고 상품 세부분류에 따른 광고 그룹타입항목추가 , 중복이 되는 17번 컬럼인 컨텐츠 타입은 하위 호환을 위해 유지*.<br/>
   *그룹 타입에 따른 입찰가 범위 안내 추가,* <br/>
- Ad Keyword (item=Keyword)<br/>
    *키워드 타입 추가, 키워드타입에 따른 입찰가 범위 안내 추가*<br/>
* 변경 사항 상세는 아래 보고서 상세 명세에서 굵은 글자로 표기<br/>

**B. 신규 보고서** <br/>
- Product Group (item=ProductGroup)<br/>
- Product Group Relation (item=ProductGroupRel)<br/>

**3. 반영일정** <br/>
**2021년 3월 17일 오후 5시 (KST)**<br/>

**4.변경/신규 보고서 상세 명세**<br/>
**Business Channel (BusinessChannel)**<br/>
No|Field Name|Value|Max.Length|Description
-- | -- | -- | -- | --
1|Customer ID|int||Customer ID
2|Name|string|256|channel name
3|Business Channel Id|string|31|Business Channel Id
4|Business Channel Type|int|| - 1: Web Site<br/> - 2: Phone<br/> - 3: Address<br/> - 4: "NAVER Booking" Service<br/> - 5: "NAVER TALK" service<br/> - 6: NAVER Shopping<br/> - 7 : NAVER BLOG<br/> - 8 : Place Ad<br/> - 9 : Catalog Ad<br/> - 10 : NAVER TV<br/> - 11 : Brand store<br/> - **12 : NAVER Shopping Brand**
5|Channel Contents|string|1024|short information by channel type.<br/>	1: Site URL<br/>	2: Phone Number<br/>	3: Address<br/>	4: "NAVER Booking" Site URL<br/>	5: "NAVER Talk" URL<br/>	6: Shopping Mall ID, Shopping Mall URL<br/>	7: Contents Url<br/>8: SiteName<br/>9: Catalog ID<br/>10: Channel ID<br/> 11: Shopping Mall ID<br/>**12: Mall URL, Mall Name**
6|PC Inspect Status|int|| - 10: UNDER_REVIEW<br/> - 20: APPROVED<br/> - 30: LIMITED_APPROVED<br/> - 40: PENDING
7|Mobile Inspect Status|int|| - 10: UNDER_REVIEW<br/> - 20: APPROVED<br/> - 30: LIMITED_APPROVED<br/> - 40: PENDING
8|regTm|date||The time at which information was created(ISO8601)
9|delTm|date||The time at which the campaign was deleted(ISO8601)

**Ad group (Adgroup)**<br/>
|No|Field Name|Value|Max.Length|Description|
|------|---|---|---|---| 
|1|Customer ID|int||Customer ID|
|2|Ad Group ID|string|31|Ad Group ID|
|3|Campaign ID|string|31|Campaign(which has this Ad Group) ID |
|4|Ad Group Name|string|256|The maximum number of characters allowed (regardless of character types) is 30 Korean Hangul, alphanumeric characters can be used.|
|5|Ad Group Bid amount|int|| Korean Won(KRW), from 70 to 100,000|
|6|ON/OFF|int|| - 0: ON<br/> - 1: OFF|
|7|Using contents network bid|int|| - 0: not used <br/> - 1: used|
|8|Contents network bid|int||Korean Won(KRW) <br/>**For the minimum and maximum prices according to the [AdGroup Type], please refer to the product-specific advertisement management section of the link below.</br>https://saedu.naver.com/help/faq/ncc/index.nhn**|
|9|PC network bidding weight|int||percent, from 10 to 500|
|10|Mobile network bidding weight|int||percent, from 10 to 500|
|11|Using KeywordPlus|int|| - 0: not used <br/> - 1: used|
|12|KeywordPlus bidding weight|int||percent, from 1 to 9999|
|13|Business Channel Id(Mobile)|string|31|The unique ID of the Mobile business channel containing this ad group |
|14|Business Channel Id(PC)|string|31|The unique ID of the PC business channel containing this ad group|
|15|regTm|date||The time at which information was created(ISO8601)|
|16|delTm|date||The time at which the campaign was deleted(ISO8601)|
|17|Content Type|string|32|Content type information. Only if the campaign type is 3.<br/>- INFORMATION : Contents  Ad Type is Information Type.<br/>- PRODUCT : Contents Ad Type is Product Type.|
**18**|**AdGroup Type**|**int**||**- 1: NAVER PowerLink<br/>- 2: NAVER Shopping Product Ad<br/>- 3: NAVER PowerContents Information<br/>- 4: NAVER PowerContents Product<br/>- 5: NAVER Brand SearchAd<br/>- 6: NAVER Place Ad<br/>- 7: NAVER Catalog Ad<br/>- 8: NAVER Brand SearchAd Brand Zone<br/>- 9: NAVER Brand Shopping SearchAd**|

**Ad Keyword (Keyword)**<br/>
|No|Field Name|Value|Max.Length|Description|
|------|---|---|---|---| 
|1|Customer ID|int||Customer ID|
|2|Ad Group ID|string|31|Ad Group ID|
|3|Ad Keyword ID|string|31|Ad Keyword ID|
|4|Ad Keyword|string|300|Ad Keyword.<br/>The maximum number of characers allowed (regardless of character types) is 25. Korean Hangul, alphanumeric characters, and special characters (# . & - +) can be used.|
|5|Ad Keyword Bid Amount|int||Korean Won(KRW)<br/>**For the minimum and maximum prices according to the [AD keyword type], please refer to the product-specific advertisement management section of the link below.</br>https://saedu.naver.com/help/faq/ncc/index.nhn**|
|6|landing URL(PC)|string|1024|Ad landing URL in PC Media(RFC 1738)|
|7|landing URL(Mobile)|string|1024|Ad landing URL in mobile Media(RFC 1738)|
|8|ON/OFF|int|| - 0: ON<br/> - 1: off |
|9|Ad Keyword Inspect Status|int|| - 10: UNDER_REVIEW<br/> - 20: APPROVED<br/> - 30: LIMITED_APPROVED<br/> - 40: PENDING|
|10|Using Ad Group Bid Amount|int|| - 0: not used <br/> - 1: used|
|11|regTm|date||The time at which information was created(ISO8601)|
|12|delTm|date||The time at which the campaign was deleted(ISO8601)|
|**13**|**Ad Keyword Type**|**int**|| **Ad Keyword Type.<br/>Ad keyword type is a returned value only in the Shopping SearchAd Brand type.<br/>- 0 : normal keyword<br/>- 1 : brand keyword**|

**Product Group (ProductGroup)**<br/>
|No|Field Name|Value|Max.Length|Description|
|------|---|---|---|---| 
|1 | Customer ID | int |   | Customer ID|
|2 | Product group ID | string | 31 | Product Group ID|
|3 | Business channel ID | string | 31 | Business Channel ID|
|4 | Name | string | 256 | Product Group Name|
|5 | Registration method | int |   | method of registering a product group.<br/>- 1 : All Products.<br/>- 2: each product or categories|
|6 | Registered product   type | int |   | Registered product type<br/>- 1 : general product<br/>- 2:catalog type product|
|7 | Attribute | string(json) | 4000 | detailed config.<br/>ex)<br/>{<br/>"productNvmids":   ["nv_mid1", "nv_mid2", "nv_mid3",....],<br/>"excludeNvmids":   ["nv_mid4", "nv_mid5", "nv_mid6",....]<br/>}<br/> - productNvmids : Product exposure priority. The priority is high from the left.<br/> - excludeNvmids : list of excluded products. It can only exist if the product registration method is all products.|
|8 | regTm | date |   | The time at which information was created(ISO8601)|
|9 | delTm | date |   | The time at which the campaign was deleted(ISO8601)|

**Product Group Relation (ProductGroupRel)**<br/>
|No|Field Name|Value|Max.Length|Description|
|------|---|---|---|---| 
|1 | Customer ID | int |   | Customer ID|
|2 | Product Group Relation ID | string | 31 | Product Group Relation ID|
|3 | Product Group ID | string | 31 | Product Group ID|
|4 | AD Group ID | string | 31 | Ad Group ID|
|5 | regTm | date |   | The time at which information was created(ISO8601)|
|6 | delTm | date |   | The time at which the campaign was deleted(ISO8601)|

**Comment by SM10855** [comment]
안녕하세요.
http://naver.github.io/searchad-apidoc/#/release-notes 
릴리즈노트에 상품그룹  타입 설명중 registrationMethod, registeredProductType 타입이 string으로 작성되어있습니다.

**Comment by naver-searchad** [comment]
@SM10855 
답변이 늦어 대단히 죄송합니다.
릴리즈 노트의 상품그룹에 대한 설명은 마스터가 아닌 신규 API 오퍼레이션에 대한 설명입니다. 즉 GET /api/ncc/product-groups 에 리턴값에 대한 설명을 표로 표시했다고 생각해 주시면 되겠습니다. 

그리고 API 오퍼레이션에서 사용하는 enum 값들은 대부분 스트링으로 되어 있으나 마스터보고서의 경우는 속도와 데이터량을 줄이기 위해 대부분의 enum값들을 integer로 변경하고 제공하고 있습니다. 따라서 enum 값들은 대부분 리턴되는 값의 데이터형이 다릅니다. 
또한 API 오퍼레이션들은 여러값들을 받아 DB나 스토리지에 저장후 자체적으로 join을 하시는 등의 가공을 하지 않고 받아서 대체로 그대로 쓰시는 경우(항상 이규칙이 지켜지고 있는 것은 아닙니다만)를 가정하기 때문에 몇몇 정보들은 저희 API 서비스가 자체적으로 다른 곳에서 조회와서 데이터를 합쳐서 보여드리고 있습니다. 그러나 대용량 다운로드 보고서는 이와 같은 작업을 수행할 경우 성능을 유지할수 없어 제공되지 못하는 정보들도 존재합니다. 특히 광고 시스템에서 생성 관리 되는 정보가 아닌 타 서비스에서 생성관리 되는 정보들이 그러한데요. 예를 들어 마스터 보고서만을 메타 정보 확보에 사용하신다면 몰ID의 경우는 비즈채널 아이디를 키로하여 비즈채널 마스터의 Channel Contents를 통해 조회 하는 방법이 있습니다. 그러나 브랜드 정보는 mallID를 이용해 네이버 쇼핑에서 조회하셔야 하는데 네이버 쇼핑은 현재 API를 부분적으로만 지원하고 있어 결국 브랜드 정보는 마스터보고서만으로는 조회가 불가능한 상황입니다. 

감사합니다.
