### ISSUE TITLE
소재 ID 입찰가 변경 성공 시, 이력 관리 문의

### ISSUE THREAD

**Issue by jih07090709** [naver/searchad-apidoc#498]
안녕하세요. API를 통해 소재ID의 입찰가를 변경하였습니다.

다만 해당 내역이 네이버 검색광고의 [도구] > [이력관리] 화면에서는 확인되지 않는데요,
별도로 이력입력을 위한 추가 작업이 필요한가요?

이력을 남길수 있는 방법이 없을까요?

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

이력관리 내 소재 변경 이력으로 확인 가능합니다.
다만 이력관리 반영이 실시간으로 조회되지 않고 약간의 시간지연이 있을 수 있습니다.
