### ISSUE TITLE
Stat daily로 출력

### ISSUE THREAD

**Issue by belrina93** [naver/searchad-apidoc#499]
담당자님 안녕하세요, 아래의 내용에서 2월 1일 ~ 28일까지 합산된 데이터가 아닌 개별 일자의 데이터를 출력하고자 하는데요.  timeIncrement에 1을 입력하면 400에러가 발생하고 진행이 되지 않습니다. 어떻게 처리를 하면 좋을까요? 파이썬에 익숙하지 않아 예시문으로 작성해주시면 매우 감사하겠습니다 :)
-
uri = '/stats'
method = 'GET'
stat_ids = ['cmp-a001-01-000000002******','cmp-a001-01-000000002*****']
r = requests.get(BASE_URL + uri, params={'ids': stat_ids, 'fields': '["impCnt", "clkCnt", "ctr", "cpc", "salesAmt"]', 'timeRange': '{"since":"2021-02-01","until":"2021-02-28"}'}, headers=get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID))

print("response status_code = {}".format(r.status_code))
print("response body = {}".format(r.json()))

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

stat api 문서의 get by id와 get by ids 를 비교해 보시면
timeIncrement 파라미터는 get by id인 경우에만 값 `1`이 유효함을 보실 수 있습니다.
'ids' 대신 'id'를 그리고 id 목록(array)대신 개별 id를 string으로 하나씩 호출하셔야 합니다.

**Comment by belrina93** [comment]
담당자님 안녕하세요, 아래와 같이 stat_ids > stat_id 로 변경하고 개별 id를 string으로 호출하라는 말씀이 맞으실까요? 아래와 같이 입력을 해도 일자별로 호출이 되지 않습니다. 확인 부탁 드립니다!


uri = '/stats'
method = 'GET'
stat_id = ['cmp-a001-01-000000002******']
stat_id = ['cmp-a001-01-000000002******']
stat_id = ['cmp-a001-01-000000002******']
stat_id = ['cmp-a001-04-000000002******']
stat_id = ['cmp-a001-01-000000002******']
stat_id = ['cmp-a001-01-000000002******']
stat_id = ['cmp-a001-03-0000000030******']
stat_id = ['cmp-a001-01-000000002******']

r = requests.get(BASE_URL + uri, params={'ids': stat_ids, 'fields': '["impCnt", "clkCnt", "ctr", "cpc", "salesAmt"]', 'timeRange': '{"since":"2021-03-08","until":"2021-03-11"}'}, headers=get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID))

print("response status_code = {}".format(r.status_code))
print("response body = {}".format(r.json()))

**Comment by belrina93** [comment]
uri = '/stats'
method = 'GET'
stat_id = ['cmp-a001-01-000000002******']
stat_id = ['cmp-a001-01-000000002******']
stat_id = ['cmp-a001-01-000000002******']
stat_id = ['cmp-a001-04-000000002******']
stat_id = ['cmp-a001-01-000000002******']
stat_id = ['cmp-a001-01-000000002******']
stat_id = ['cmp-a001-03-000000003******']
stat_id = ['cmp-a001-01-000000002******']
r = requests.get(BASE_URL + uri, params={'id': stat_id, 'fields': '["impCnt", "clkCnt", "ctr", "cpc", "salesAmt"]', 'timeRange': '{"since":"2021-03-01","until":"2021-03-10"}', 'timeIncrement':""}, headers=get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID))
print("response status_code = {}".format(r.status_code))
print("response body = {}".format(r.json()))

--
위와 같이 변경 후 적용되었습니다. 
하지만 아래 부분 출력 후 KeyError: "None of ['id'] are in the columns" 와 같은 에러로 출력이 되지 않는데요,
id를 어느 부분에서 변경 처리해야 하는지요? 확인 부탁 드립니다!
-
fields=r.json()['data'][0].keys()
df=DataFrame(None,columns=fields)

for idx in range(0,len(r.json()['data'])):
    df=df.append(DataFrame(r.json()['data'][idx],index=[idx]))

df.set_index('id',inplace=True)
df.rename({'ctr':'클릭률','clkCnt':'클릭수','cpc':'평균클릭비용','impCnt':'노출수','salesAmt':'총비용'},axis=1,inplace=True)
df=df[['노출수', '클릭수', '클릭률', '평균클릭비용', '총비용']]

df

**Comment by naver-searchad** [comment]
@belrina93 
get by id이므로 id 파라미터는 array 타입이 아닌 string 입니다.
`stat_id = ['cmp-a001-01-000000002******']`를
`stat_id = 'cmp-a001-01-000000002******'로 변경하셔야 할 듯하네요.
그리고 한번 요청헤 하나의 id만 넣어 실행하시면 되겠습니다.

**Comment by belrina93** [comment]
담당자님, 설명 감사 드립니다. 위의 개별 일자 데이터 불러온 후 1)과 같이 작성 시 2)와 같은 오류가 발생하는데요, 어떤 오류인지 알 수 있을까요?  

1)
fields=r.json()['data'][0].keys()
df=DataFrame(None,columns=fields)

for idx in range(0,len(r.json()['data'])):
    df=df.append(DataFrame(r.json()['data'][idx],index=[idx]))

df.set_index('id',inplace=True)
df.rename({'ctr':'클릭률','clkCnt':'클릭수','cpc':'평균클릭비용','impCnt':'노출수','salesAmt':'총비용','dateStart':'시작일','dateEnd':'종료일'},axis=1,inplace=True)
df=df[['시작일', '종료일', '노출수', '클릭수', '클릭률', '평균클릭비용', '총비용']]

df

2)KeyError                                  Traceback (most recent call last)
<ipython-input-89-09678de611d1> in <module>
      5     df=df.append(DataFrame(r.json()['data'][idx],index=[idx]))
      6 
----> 7 df.set_index('id',inplace=True)
      8 df.rename({'ctr':'클릭률','clkCnt':'클릭수','cpc':'평균클릭비용','impCnt':'노출수','salesAmt':'총비용','dateStart':'시작일','dateEnd':'종료일'},axis=1,inplace=True)
      9 df=df[['시작일', '종료일', '노출수', '클릭수', '클릭률', '평균클릭비용', '총비용']]

~\anaconda3\lib\site-packages\pandas\core\frame.py in set_index(self, keys, drop, append, inplace, verify_integrity)
   4549 
   4550         if missing:
-> 4551             raise KeyError(f"None of {missing} are in the columns")
   4552 
   4553         if inplace:

KeyError: "None of ['id'] are in the columns"

**Comment by naver-searchad** [comment]
@belrina93 
죄송하지만 api 상의 오류나 설명 외의 지원은 어렵습니다.

**Comment by belrina93** [comment]
확인 감사드립니다!

캠페인 id or 광고그룹 id 대신 캠페인 이름 or 광고 그룹 이름으로 불러오는 방법이 있을까요?

-
stat_id = ['cmp-a001-01-000000002******']
r = requests.get(BASE_URL + uri, params={'id': stat_id, 'fields': '["impCnt", "clkCnt", "ctr", "cpc", "salesAmt"]', 'timeRange': '{"since":"2021-03-01","until":"2021-03-10"}', 'timeIncrement':""}, headers=get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID))
print("response status_code = {}".format(r.status_code))
print("response body = {}".format(r.json()))

**Comment by belrina93** [comment]
확인 감사 드립니다!
추가로 문의 드릴 부분이 있는데요, get by id로 출력 시 id 값은 출력하지 않고, fields 와 timeragne 값만 출력이 되는데요. get by id로 출력 시에는 id값이 출력되지 않는지요? 확인 부탁 드립니다.
[입력]
r = requests.get(BASE_URL + uri, params={'id': stat_id, 'fields': '["impCnt", "clkCnt", "ctr", "cpc", "salesAmt"]', 'timeRange': '{"since":"2021-02-01","until":"2021-02-28"}', 'timeIncrement':""}, headers=get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID))
[출력]
{'summary': {'dateStart': '2021-02-01', 'dateEnd': '2021-02-28'}, 'data': [{'ctr': 3.79, 'clkCnt': 7, 'dateStart': '2021-02-01', 'cpc': 1318, 'dateEnd': '2021-02-01', 'impCnt': 185, 'salesAmt': 9229}, {'ctr': 2.17, 'clkCnt': 10, 'dateStart': '2021-02-02', 'cpc': 980, 'dateEnd': '2021-02-02', 'impCnt': 461, 'salesAmt': 9801},

**Comment by naver-searchad** [comment]
@belrina93 
네. 응답 데이터에서 직접 확인해 보셨듯이 포함되지 않습니다.
