### ISSUE TITLE
Adgroup의 targetTime, targetLocation, targetMedia update가 작동하지 않습니다.

### ISSUE THREAD

**Issue by younseunghyun** [naver/searchad-apidoc#5]
Adgroup을 update하는 api를 사용하는 중인데, targetTime, targetLocation, targetMedia의 field를 업데이트하는 api가 정상적으로 작동하지 않는 것 같습니다.

200 response code는 return 받으나, 실제 신규 검색광고에는 반영되어 있지 않고, 신규 검새광고 플랫폼에서 수동으로 설정이시에도 적용되지 않는 것 같습니다.

기존에 위에 관련한 정보들이 없는 것에 대하여, targetId를 넣지 않고, 해당 targetTp와 target만 넣어서 update하고 있습니다.

어떤 방법으로 사용해야 되는지 궁금합니다.

**Comment by naver-searchad** [comment]
targetTime, targetLocation, targetMedia의 field는 어떤것을 말씀하시나요?
Adgroup의 Target을 변경하려면 adgroup json 내부에 targets 프로퍼티(array)에 각 target 별 json object를 넣어 주셔야 합니다. 또한 targetTp에 해당하는 모든 target을 같이 넣어 주셔야 합니다.

adgroup의 Target은 아래 target 정의문서를 참고하세요.

http://naver.github.io/searchad-apidoc/#/definitions/Target

**Comment by younseunghyun** [comment]
현재 아래와 같이 targets에 target에 관한 정보들을 담아서 request를 보내고 있습니다.

targetTime을 업데이트 하려고 하고 있습니다.

400, message :{"code":1002,"status":400,"title":"The request is invalid."}

로 response가 오고 있는데, 어떤 항목을 더 채워 넣어야 할까요?
   "targets": [
      {
         "targetTp": "TIME_WEEKLY_TARGET",
         "target": {
            "THU": 0,
            "TUE": 0,
            "SAT": 0,
            "WED": 0,
            "FRI": 0,
            "SUN": 0,
            "MON": 22
         }
      },
      {
         "targetTp": "REGIONAL_TARGET",
         "target": {
            "location": {
               "OTHERS": [
                  "0"
               ],
               "KR": [
                  "11",
                  "12",
                  "13",
                  "14",
                  "15",
                  "16",
                  "17",
                  "1",
                  "2",
                  "3",
                  "4",
                  "5",
                  "6",
                  "7",
                  "8",
                  "9",
                  "10"
               ]
            }
         }
      },
      {
         "targetTp": "MEDIA_TARGET",
         "target": {
            "type": 1
         }
      },
      {
         "targetTp": "PC_MOBILE_TARGET",
         "target": {
            "pc": true,
            "mobile": true
         }
      }
   ]

**Comment by naver-searchad** [comment]
Target정보를 수정하실때는 nccTargetId, ownerId는 필수로 입력 하셔야 합니다.
아래와 같이 입력 하시면 됩니다.
```json
"targets": [{
		"nccTargetId": "tgt-m001-01-000000000000000",
		"ownerId": "grp-m001-01-000000000000000",
		"targetTp": "TIME_WEEKLY_TARGET",
		"target": {
			"MON": 0,
			"TUE": 16777215,
			"WED": 16777215,
			"THU": 16777215,
			"FRI": 16777215,
			"SAT": 16777215,
			"SUN": 16777215
		}
	}, {
		"nccTargetId": "tgt-m002-01-000000000000000",
		"ownerId": "grp-m001-01-000000000000000",
		"targetTp": "REGIONAL_TARGET",
		"target": null
	}, {
		"nccTargetId": "tgt-m003-01-000000000000000",
		"ownerId": "grp-m001-01-000000000000000",
		"targetTp": "MEDIA_TARGET",
		"target": {
			"type": 1
		}
	}, {
		"nccTargetId": "tgt-m004-01-000000000000000",
		"ownerId": "grp-m001-01-000000000000000",
		"targetTp": "PC_MOBILE_TARGET",
		"target": {
			"pc": true,
			"mobile": true
		}
	}]
```

**Comment by younseunghyun** [comment]
nccTargetId, ownerId을 알기 위해서는 adgroup을 get하는 request를 날려 해당 값들을 가지고, 다시 Request를 날려야 된다고 생각 하고 있는데, 현재 adgroupd에 get request를 날리면 아래와 같이 반환 되고 있습니다.

개인정보가 노출될 수 있는 부분은 testsetes로 대체 하였습니다.

adgroup에 get을 하여 정보를 얻는 것이 아니라면, 어떤식으로  nccTargetId, ownerId의 정보를 가져와서 업데이트를 하여야 하나요?
```
[
  {
    "nccAdgroupId": "testsetes",
    "customerId": testsetes,
    "nccCampaignId": "testsetes",
    "mobileChannelId": "testsetes",
    "pcChannelId": "testsetes",
    "bidAmt": 100,
    "name": "testsetes",
    "userLock": false,
    "useDailyBudget": true,
    "useKeywordPlus": true,
    "keywordPlusWeight": 30,
    "contentsNetworkBidAmt": 70,
    "useCntsNetworkBidAmt": false,
    "mobileNetworkBidWeight": 10,
    "pcNetworkBidWeight": 30,
    "dailyBudget": 4000,
    "budgetLock": false,
    "delFlag": false,
    "regTm": "2016-06-26T04:46:52.000Z",
    "editTm": "2016-06-26T11:57:13.000Z",
    "targetSummary": {
      "week": "all",
      "pcMobile": "all",
      "media": "all",
      "time": "all",
      "region": "all"
    },
    "pcChannelKey": "testsetes",
    "mobileChannelKey": "testsetes",
    "status": "ELIGIBLE",
    "statusReason": "ELIGIBLE",
    "expectCost": 0,
    "migType": 0
  }
]
```

**Comment by naver-searchad** [comment]
http://naver.github.io/searchad-apidoc/#/operations/GET/~2Fncc~2Fadgroups~2F%7BadgroupId%7D

위에 정의된 api를 사용하시면 targets 정보를 얻을수 있습니다.

**Comment by younseunghyun** [comment]
말씀하신대로 위의 정보는 GET /ncc/adgroups/{adgroupId}` 을 사용하니 nccTargetId와 ownerId가 target에 담겨 targets가 반환 되고 있습니다.

위에 첨부해드린 response는 `GET /ncc/adgroups{?nccCampaignId,baseSearchId,recordSize}` 을 사용하여 얻은 결과였습니다.

궁금한점이 문서에는 `GET /ncc/adgroups{?nccCampaignId,baseSearchId,recordSize}` 을 사용하여도, targets가 response에 포함되는 것으로 나오는데, 이 부분은 변경 되어 있는 건가요?

제가 참조 하고 있는 문서 링크는 다음과 같습니다. 
[http://naver.github.io/searchad-apidoc/#/operations/GET/~2Fncc~2Fadgroups%7B%3FnccCampaignId,baseSearchId,recordSize%7D](url)

**Comment by naver-searchad** [comment]
처음 의도는 Adgroup 내부에 모든 Target을 포함하여 반환하는 것이었습니다. 하지만 광고 그룹수가 많아지면 Response Data의 크기가 너무 커지는 문제점이 있어 List 조회시에는 요약정보만 보내는 것으로 수정 되었습니다.

List 조회시 대부분 Adgroup의 정보만 사용하고 상세 타겟 정보는 개별 Adgroup id를 이용하여 조회하는 패턴을 사용하고 있어 List 조회시 Target정보는 제거된 상태로 반환됩니다.

**Comment by younseunghyun** [comment]
아 그렇군요 알겠습니다

감사합니다 :)

**Comment by younseunghyun** [comment]
추가 질문이 있어서 이슈를 오픈 하였습니다.

네이버 검색광고와 동기화를 하려고 하는데, 말씀하신대로라면 target정보까지 담긴 그룹 정보를 가져 오기 위해서는, 그룹 각각에 get을 하여서 가져와야 되는 것으로 보입니다.

이전 api에서는 빠른 속도의 api 요청을 금지 하였는데, 신규 버전에서는 빠른 속도로 요청을 하여도 문제가 없을까요?(한번에 100개의 request를 날린 다던지, 100개를 순차적으로 request를 날린다던지)

**Comment by naver-searchad** [comment]
한 번에 너무 많은 요청을 할 경우 HTTP Status `429 Too Many Requests`를 반환합니다.
이를 방지하기 위해서는 적절히 끊어서 요청하시거나 sleep을 두고 호출하시는 게 좋습니다.

**Comment by younseunghyun** [comment]
감사합니다 👍
