### ISSUE TITLE
Too Many Requests기준 문의

### ISSUE THREAD

**Issue by kimdohoyeong** [naver/searchad-apidoc#50]
1. `HTTP/1.1 429 Too Many Requests`가 판단되는 기준은
` IP`인가요? 아니면` API KEY(User)` 인가요?

2. 보통 어느 정도의 Request요청시 429에러가 반환되나요?

3. 저번주에 남겼던 질문은 언제쯤 답변을 받을 수 있을까요?

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

답변 드립니다. 

1. 속도 측정 기준은 호출 대상이 되는 CUSTOMER ID 기준입니다. (IP나 라이선스 단위는 아닙니다.)  

2. 현재 평균 초당 15회~20회 정도 수준으로 측정이 됩니다만 속도는 광고주시스템 이용 (UI 이용)속도와 합산하여 계산하고 있기 때문으로 순수하게 API로만 이용하신다면 초당 25회~30회 정도입니다. STATReport나 MASTERReport의 경우는 통상 초당 10회 내외입니다.속도 제한은 저희 시스템 상황에 따라 가변적으로 적용 되기 때문에 에러 리턴이 되지 않는 측정값 기준으로 알려 드립니다. 

3. 일전 답변은 담당자 분께 답변 요청을 드리겠습니다. 답변이 늦어져 죄송합니다.

**Comment by kimdohoyeong** [comment]
감사합니다.
