### ISSUE TITLE
API 기능 추가건 부탁드립니다.

### ISSUE THREAD

**Issue by JungHunYu** [naver/searchad-apidoc#500]
https://manage.searchad.naver.com/api/search?q=%EC%86%94%EB%A3%A8%ED%8B%B0%EC%98%A8&exact=false

검색어 api 인듯한데
이런것도 서비스 하나요?

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

검색 API는 광고관리 웹 시스템을 위한 기능이며 검색광고 API로는 서비스되지 않습니다.
