### ISSUE TITLE
광고시스템에 추가된 기능 API 지원 요청드립니다.

### ISSUE THREAD

**Issue by colonist4** [naver/searchad-apidoc#501]
최근 도구 > 노출진단 > 쇼핑검색 (노출현황진단) 기능이 네이버 광고관리 시스템에 추가된 것으로 알고있습니다.
해당 기능은 아직 API로 제공되지 않는 것으로 파악되는데

쇼핑검색 (노출현황보기) 기능은 여러문제로 API로 제공해주시기 어려울 것 같으나
쇼핑검색 (노출현황진단) 은 API로 제공 가능하지 않을까 해서 요청드립니다
해당 기능 제공 해주시면 감사하겠습니다!

**Comment by naver-searchad** [comment]
안녕하세요 네이버 검색광고 API입니다.

해당 기능들은 API 지원 대상으로 설계된 것이 아니라는 점 먼저 말씀 드립니다.
다만 제안주신 내용은 내부 채널로 공유해서 정책에 고려될 수 있도록 하겠습니다.
의견 주셔서 감사합니다.

**Comment by colonist4** [comment]
넵 감사합니다 :)
