### ISSUE TITLE
campaign.list & stats.getSummaryStatByIdList 503 Error

### ISSUE THREAD

**Issue by miinye** [naver/searchad-apidoc#504]
2021년 4월 8일  02:01:56 ~ 05:30:19 경 campaign list & stats.getSummaryStatByIdList  api를 호출시 

{"status":503,"title":"Service Unavailable"} 

503error가 발생하여 혹시 이슈가 있었는지 문의드립니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

금일 오전 2~4시 사이 일부 서버들의 재시작 내용이 확인됩니다.
이로 인해 일부 API 서버들이 일시적으로 영향을 받았을 수 있습니다.
그 외 별도 공지 내용은 확인된 바 없습니다.
