### ISSUE TITLE
그룹마스터 18열 데이터 문의

### ISSUE THREAD

**Issue by insuhp** [naver/searchad-apidoc#505]
안녕하세요

올해 2월-3월 쯤부터 대용량 다운로드 보고서의 [그룹마스터] 파일의 18열에
[1] 혹은 [2] 숫자가 출력되고 있는데 어떤 데이터인지 확인 부탁드리고자 합니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

API Document의 다음 내용을 확인하시면 되겠습니다.
http://naver.github.io/searchad-apidoc/#/tags/MasterReport

![image](https://user-images.githubusercontent.com/18188635/115333779-3721cc80-a1d5-11eb-8db2-f7862ceb91db.png)

**Comment by insuhp** [comment]
감사합니다 자세한 사항 API Document에서 확인하도록 하겠습니다!
