### ISSUE TITLE
소재 수를 가져올수 있는 API 가 있나요?

### ISSUE THREAD

**Issue by EleninJayTech** [naver/searchad-apidoc#506]
현재는 광고 그룹별로 호출한 소재를 적재 해두고 수량을 카운팅 하고 있습니다.
혹시 가지고 있는 소재 수(count) 전체를 가져 올수 있는 API 가 있나요?
또는 다른 좋은 방법이 있을가요?

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

전체를 리스팅 하는 API는 현재 지원되지 않습니다.
