### ISSUE TITLE
RelKwdStat - biztpId 문의

### ISSUE THREAD

**Issue by beomhee** [naver/searchad-apidoc#507]
RelKwdStat에서  biztpId 값을 못찾겠어요..
다른 이슈 이슈를 확인해보니 MasterReport에서 item이 Biz인 것을 확인하면 된다고 되어있지만, 
MasterReport 리스트를 확인해보면 item이 Biz인 항목이 보이지 않습니다.

MasterReport에서 확인되는 데이터는 총 3개로 아래와 같습니다.
![masterreport](https://user-images.githubusercontent.com/14227142/115528625-2d7b9000-a2cd-11eb-9549-576125dd6003.png)

뭐가 잘못된것일까요?

데이터를 호출한 코드는 다음과 같습니다. (python으로 작성되었습니다.)
        uri     = "/master-reports"
        current_timestamp, Signature = get_signature(log_handler, 'GET', uri)
        header['X-Timestamp'] = str(current_timestamp)
        header['X-Signature'] = Signature
        url = f"{base_url}{uri}"
        r = requests.get(url, headers=header)
        business_list = json.loads(r.text)

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

http://naver.github.io/searchad-apidoc/#/operations/POST/~2Fmaster-reports
위 링크에서 request body 파라미터 중 `item`에 `Biz` 로 명시되어 있습니다.

**Comment by beomhee** [comment]
감사합니다.
