### ISSUE TITLE
소재 생성 문의 Received value is not suitable for JSON format with 'type

### ISSUE THREAD

**Issue by EleninJayTech** [naver/searchad-apidoc#508]
안녕하세요
대상 언어는 PHP 이고 샘플에 소재 생성이 없어서 API 문서와 issue를 찾아봐도 해결되지 않아 문의 드립니다.

대상 캠페인의 campaignTp 은 WEB_SITE 이고
해당 광고그룹 adgroupType 은 WEB_SITE 입니다

호출 코드
`$ad_create_test = $this->naverrestapi->POST('/ncc/ads', [
						'ad'=>'{ "pc":{ "final":"http://searchad.naver.com" }, "mobile":{ "final":"http://m.searchad.naver.com" }, "headline":"the first line", "description":"the second line of your ad text" }',
						'nccAdgroupId'=>'grp-a001-01-000000020179214',
						"userLock" => true,
						'type'=>'TEXT_45',
					]);`

오류 (var_dump)
array(4) { ["code"]=> int(1010) ["status"]=> int(400) ["title"]=> string(47) "Received value is not suitable for JSON format." ["detail"]=> string(106) "instance type (string) does not match any allowed primitive type (allowed: ["object"]), at '' with 'type' " }

오류 (기본 출력)
request : {"ad":"{ \"pc\":{ \"final\":\"http:\/\/searchad.naver.com\" }, \"mobile\":{ \"final\":\"http:\/\/m.searchad.naver.com\" }, \"headline\":\"the first line\", \"description\":\"the second line of your ad text\" }","nccAdgroupId":"grp-a001-01-000000020179214","userLock":true,"type":"TEXT_45"} Http Status : 400 Transaction-ID : BOUF2RSSHDH08

type 을 json 형태? 로 보내야 하는건지
ad 의 json 형태가 잘못된건지
이렇게 저렇게 바꿔봐도 안되네요
도움 부탁드립니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

` [ 'ad'=>'{ "pc"` 이 부분에서 ad의 value가 객체여야 하지만 `'`로 시작하기 때문에 string으로 인식되어 그렇습니다.
앞 뒤 `'`를 제거하시면 될 것 같습니다.

**Comment by EleninJayTech** [comment]
해결되었습니다.
PHP 에서 'ad' 값 요청시 json 형식이 아닌 배열로 요청하니 정상으로 진행되었습니다.
