### ISSUE TITLE
쇼핑검색 문의드립니다.

### ISSUE THREAD

**Issue by nwn777** [naver/searchad-apidoc#510]
안녕하세요.
쇼핑검색 광고는 소재등록하고, 키워드는 필요없는 것으로 압니다.
근데 사용자 입장에서 검색어를 사용해서 광고에 접근할텐데, 검색어마다 입찰액이 다 다를것인데,
관리페이지에는 왜 검색어마다 입찰가가 나오지 않고, 통합으로 소재 하나에 대한 입찰가설정만 되는것인가요?
상식적으로 매치가 안돼 많은 의문이 듭니다.

입찰가가 100원이면, a검색어와 b검색어가 인기와 조회량 등에서 차이로 입찰가가 틀린텐데, 이 부분에 대한 설명 부탁드립니다.
수고하세요.

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

쇼핑검색광고는 키워드 1개를 등록하거나 키워드 단위로 입찰하지 않고, 
노출하고자하는 상품과 연관된 키워드에 골고루 입찰되는 방식의 광고 상품입니다.
검색어별로 조회량 등이 모두 다릅니다만, 그 검색어들을 모두 합하여 관리하는 방식의 광고 상품입니다.
일부 원하지 않는 키워드는 제외검색어를 통해 관리하실 수 있습니다.

감사합니다.

**Comment by nwn777** [comment]
네. 그건 이해하고 있습니다.
제가 질문드리는 것은 소재에 해당하는 대표 검색어를 알고 싶다는 거예요~
소재에 연관된 검색어가 몇십개정도 있다고 봤을때, 대표적인 루트 검색어를 알수 있냐는 질문입니다.
즉 제일 광고비가 높게 책정되는 대표 검색어를 말씀드리는 것입니다.
가령 그룹명으로 사용된 이름이 대표검색어라든지, 상품명에 있는 단어들이 대표 검색어라든지, 카테고리의 소분류가 대표 검색어가 된다든지...

이게 중요한 이유가 만약 제가 소재하나를 광고한다면 실제 어디에 노출이 되고있는지 파악을 해야되기 떄문입니다.
지금은 너무 막연해서 노출이 어디어디에 되고 있는지 파악이 안되어서 답답하다는 것입니다.

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다.

우선 알고 계실것으로 생각 되나 혹시 모르실 가능성도 있어 검색어별로 입찰가가 다르지 않으며 동일한 소재 입찰가가 적용된다는 점을 설명에 앞서  말씀드립니다.

쇼핑 검색광고의 검색어는 상품정보를 바탕으로 쇼핑 검색엔진이 실시간으로 판단하게 됩니다.
따라서 사전에 어떤 검색어에 어떤 상품이 노출될지 저희도 미리 알수 없습니다. 

그러나 어떤 키워드에 어떤 소재(광고)가 노출 되었는지에 대한 정보는 집행 후 제공되는 보고서를 통해 확인이 가능합니다. 
보고서는 STAT 오퍼레이션 혹은 STATREPORT로 제공되며 
STAT의 경우 [get (by statType)](https://naver.github.io/searchad-apidoc/#/operations/GET/~2Fstats%7B%3Fid,statType%7D)
으로 호출 시 ID 값은 AD ID, statType= NPLA_SCH_KEYWORD 를 통해 제공됩니다. 
[STAT REPORT(대용량 보고서)](https://naver.github.io/searchad-apidoc/#/tags/StatReport)의 경우는 
 reportTp=SHOPPINGKEYWORD_DETAIL를 통해 노출수, 클릭수 광고비 정보를 ,
전환 추적이 가능하시도록 프리미엄로그분석에 가입하시어 테그 설치가 완료되었거나 스마트스토어인 경우는 reportTp=SHOPPINGKEYWORD_CONVERSION_DETAIL를 통해 키워드-소재별 전환 성과를 확인하실수 있습니다. 

해당 데이터는 전일까지의 데이터라는 점도 추가로 안내 드립니다.  

감사합니다.

**Comment by nwn777** [comment]
네...
감사합니다.
