### ISSUE TITLE
API로 ON 처리된 그룹 내 소재 미노출 문의 건

### ISSUE THREAD

**Issue by miyeonleeemnet** [naver/searchad-apidoc#511]
안녕하세요. 하단의 요청사항 확인 부탁드리겠습니다.

1. ID :  dresther
2. 미노출 일시 : 2021.04.24 06시경
3. 미노출 광고 정보 (광고상품/ 키워드 / 소재 ID) : 
4. 검색 환경 (PC/MOBILE, 지역) : PC/ MO 모두. 모든 지역
5. IP : (파워링크 키워드 노출현황보기의 최초 접속위치가 실제 위치와 다른 경우)
6. 스크린샷 첨부

- 문의사항 :

홈쇼핑 일정에 매출의 등락이 심한 편인 광고주입니다. 

따라서, 홈쇼핑에 대응할 수 있도록 방영 시간대에는 라이브할 수 있는 '타임딜 전용 그룹'을 별도로 운영하고 있습니다. 

 

홈쇼핑 대응 방식을 예시로 간략히 설명 드리자면, 아래와 같습니다.

- 토요일 오전 06~09시 홈쇼핑 예정

- 06~09시 상시용 그룹은 OFF / 타임딜 전용 그룹 ON하여 자사몰 유입 극대화

 

지난 주말 발생한 이슈 내용입니다. 

전주 토요일 오전 위와 같은 방식으로 상시용 그룹 OFF/ 타임딜 전용 그룹은 ON 처리되어야 했기에, 

당사 솔루션 내에서 API로 그룹 ON/OFF 처리 될 수 있도록 스케쥴러를 설정해두었습니다. 

실제로 솔루션은 지난 토요일(4/24) 06시 정상 작동하여 그룹은 모두 정상적으로 ON/OFF 되었으나, 

ON처리된 그룹 내에 소재/키워드 모두 '노출 가능' 상태임에도 06시 30분까지 검색 결과에 광고가 노출되지 않는 이슈가 있었습니다.

그룹 ON 후에 광고 노출까지 반영되는 시간을 고려하더라도 30분이나 시간이 소요된다는 것은 이상이 있다고 판단하였고, 

수기로 노출 시간대를 변경하고 난 후에야 광고가 송출되었습니다. 

해당 그룹에 설정된 노출 디바이스, 매체, 지역은 문제 없었으며, API 스케쥴러를 사용하기 전 '노출 시간대'로 광고 ON/OFF를 조정할 때에는 문제가 없는 그룹이었습니다. 

 

아래의 내용 문의 드립니다. 

- API 관련하여 네이버 측의 정책 변경 및 시스템 업데이트, 강화 등의 변화가 있었는지 궁금합니다.

- 없다면, API로 ON 처리 된 그룹 내의 소재/키워드는 왜 30분 이후에도 검색 결과에 노출되지 않았는지 사유 파악 필요합니다. 

- 아래에 광고 그룹과 소재 정보 전달 드리니, 답변에 도움 부탁드립니다.  

   ㄱ. 06시 라이브 되었어야 할 타임딜 전용 그룹:  00.대표_엘라스틴_타임딜 ( 그룹 ID:  grp-a001-01-000000020511271)

        위 그룹 내 소재 ID:  nad-a001-01-000000129155794 /   nad-a001-01-000000129155793 /   nad-a001-01-000000129155788 

        위 그룹 내 키워드 ID: 먹는엘라스틴 ( 키워드 ID:  nkw-a001-01-000003578682039 ) 

   ㄴ. 06시 OFF 처리한 상시 운영 그룹: 00.대표_엘라스틴  ( 그룹 ID:  grp-a001-01-000000016557988 ) 

 

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API 입니다.


> ㄴ. 06시 OFF 처리한 상시 운영 그룹: 00.대표_엘라스틴 ( 그룹 ID: grp-a001-01-000000016557988 )

이 경우는 6시10분에 반영되었습니다.

> ㄱ. 06시 라이브 되었어야 할 타임딜 전용 그룹: 00.대표_엘라스틴_타임딜 ( 그룹 ID: grp-a001-01-000000020511271)

이 경우는 의도와는 다르게 기존 해당 그룹의 시간타케팅이 토요일 0 으로 미노출 설정되어있었고,
18시 20분이 되서야  반영되었습니다.
20일 off -> 23일 18시 10분( 18시 20분에  반영)
SAT: 0 -> SAT: 448 ( 6, 7, 8 ON )

정상반영된 것으로 확인됩니다.

감사합니다.
