### ISSUE TITLE
SHOPPINGKEYWORD_DETAIL 보고서 데이터중 키워드에 - (하이픈) 문의

### ISSUE THREAD

**Issue by kwon2s** [naver/searchad-apidoc#512]
안녕하세요
쇼핑검색 키워드 보고서를 체크중입니다.
한가지 문의점은
키워드가 
- ( 하이픈 ) 
으로 
데이터가 나와서요 

해당 하이픈 키워드는 뭔지 문의 드립니다.
거의모든 광고주 계정별 있는듯 합니다.

![keyword_](https://user-images.githubusercontent.com/48579154/116329038-54721e80-a805-11eb-81a1-d9ea75533646.png)

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

쇼핑 검색광고는 검색영역에 노출되는 경우에만 키워드가 보고됩니다.
확장된 매체인 경우 키워드가 특정되지 않으므로 보고서에 표기되지 않습니다.
