### ISSUE TITLE
#324 이슈 재확인 부탁드립니다.

### ISSUE THREAD

**Issue by kaorimikage** [naver/searchad-apidoc#513]
https://github.com/naver/searchad-apidoc/issues/324#issue-538895193

갑자기 변경점이 생겨서 확인해보니 예전에 질문드렸던 이슈와 연관이 있어 해당 이슈를 링크했습니다.
확인부탁드립니다.

**Comment by naver-searchad** [comment]
@kaorimikage 안녕하세요? 네이버 검색광고 API입니다.

문의하신 내용에 대해 확인이 늦어져서 답변이 늦은점 대단히 죄송합니다.

확인결과 API의 변경은 없었습니다.
삭제된 광고그룹의 아이디가 포함된 요청을 할 경우에 삭제된 광고 그룹에 대해서도 소유자 확인을 같이 진행하고 있는 것으로 확인이 되었습니다.

다만 네이버 검색광고 정책상 삭제된 광고그룹의 삭제일이 현 시점 기준으로 특정시간이 지난 경우 DB에서 완전히 삭제가 되기 때문에, 특정시간 이전에 삭제된 광고그룹의 ID가 포함된 경우에는 소유자 확인이 불가능하여 문의하신것과 같이 1018응답이 나갈 수 있습니다.

감사합니다.

**Comment by kaorimikage** [comment]
특정시간이 지나면 DB에서 완전 삭제된다고 하셨는지 대략 얼마정도의 시간인지 알 수 있는지요?
