### ISSUE TITLE
쇼핑검색광고 API 관련 건

### ISSUE THREAD

**Issue by anto3324** [naver/searchad-apidoc#515]
안녕하세요 
네이버 쇼핑검색 성별, 연령 타겟팅을 그룹별로 각 확인이 되고 있습니다

그룹 = 성별 X 연령의 복합 성과를 확인하기 위해 
API 리포트를 통해 확인을 하고자 하는데, 관련 기능이나 공지가 릴리즈 된 부분이 있는지 문의 드립니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

breakdown 항목은 1개 이상으로 복합 구성이 불가합니다.
