### ISSUE TITLE
광고 계정의 광고비 지불 정보를 가지고 있는 API가 있을까요??

### ISSUE THREAD

**Issue by jjeonsangwon** [naver/searchad-apidoc#516]
안녕하세요.
다름이 아니라 특정 네이버 계정에서 선불이 아닌 후불로 사용중이라는 연락을 받아서 대응하려고 합니다.
혹시 특정 계정이 선불 혹은 후불인지 알 수 있는 API나 필드가 있을까요???

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

현재 비즈머니 api로는 해당 정보 파악이 불가합니다.
