### ISSUE TITLE
API로 캠페인, 광고그룹, 키워드의 상태값 변경이 가능한가요?

### ISSUE THREAD

**Issue by beomhee** [naver/searchad-apidoc#517]
안녕하세요..
API를 이용해서 캠페인, 광고그룹, 키워드의 상태값 확인은 가능한데요.
상태값을 변경할 수 있는 방법은 없는건지 궁금합니다.
문서에서 update항목을 살펴보았으나 상태(status)에 대한 내용은 보지 못하여 문의드립니다.

**Comment by naver-searchad** [comment]
@beomhee 안녕하세요? 네이버 검색광고 API 입니다.

상태값은 여러 필드의 조합으로 계산이 되는 값입니다. 조합되는 필드의 값이 바뀔경우 재 계산이 됩니다.
[wiki](https://github.com/naver/searchad-apidoc/wiki/FAQ#q-각-항목의-상태와-상태이유-계산-방식은-어떻게-되나요)의 내용을 참고하시어 update로 원하는 필드를 변경하시면 상태값이 다시 계산됩니다.

**Comment by beomhee** [comment]
안녕하세요...
알려주신 wiki에서 확인해보았으나 잘 모르겠습니다.
![image](https://user-images.githubusercontent.com/14227142/118600936-9a127d80-b7ec-11eb-8641-f67363ae4a05.png)

여기서 ON/OFF가 계쇤된 값이 무엇을 의미하는지, API어디서 ON/OFF값을 변경할 수 있는지 궁금합니다.
검수가 끝난 키워드의 상태를 ELIGIBLE <-> PAUSE 변경하고 싶습니다.

**Comment by naver-searchad** [comment]
@beomhee 
ON/OFF 관리는 userLock 필드를 update 하시면 됩니다.
true 값은 OFF, false는 ON을 의미합니다.

**Comment by beomhee** [comment]
확인했습니다.  
자세한 설명 감사합니다. ^^
