### ISSUE TITLE
Targets의 TIME_WEEKLY_TARGET 수정 시 문의드립니다.

### ISSUE THREAD

**Issue by hdkhh** [naver/searchad-apidoc#519]
```
"targets": [
   {
        "nccTargetId": "tgt-m001-01-000000000000000",
        "ownerId": "grp-m001-01-000000000000000",
        "targetTp": "TIME_WEEKLY_TARGET",
        "target": {
            "MON": 0,
            "TUE": 16777215,
            "WED": 16777215,
            "THU": 16777215,
            "FRI": 16777215,
            "SAT": 16777215,
            "SUN": 16777215
     } 
]
```

타겟에서 TIME_WEEKLY_TARGET 타입을 수정하고 싶은데요, 
"WED": 16777215,에서  key=요일, value는 int형 인것 같은데 16777215를 계산하는 방법이 무엇일까요?

예를들어서 해당 Target을 수요일은 오전8시~오후10시 까지만으로 지정하고 싶을때
int형으로 어떻게 표시해야하는지,  방법을 알고싶습니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

Wiki 탭에 보시면 FAQ 항목을 확인하실 수 있습니다.
https://github.com/naver/searchad-apidoc/wiki/FAQ#q-%EC%8B%9C%EA%B0%84-%ED%83%80%EA%B2%8C%ED%8C%85%EC%9D%80-%EC%96%B4%EB%96%BB%EA%B2%8C-%EC%82%AC%EC%9A%A9%ED%95%98%EB%82%98%EC%9A%94
