### ISSUE TITLE
혹시 다차원 보고서를 api로 제공하실 계획이 있을까요?

### ISSUE THREAD

**Issue by ej31** [naver/searchad-apidoc#520]
master report와 stat report 를 재가공해서 쓰고 있는데 혹시 별도 계획이 있으신지 알고싶네요

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

아쉽게도 문의하신 기능은 아직 계획이 잡혀 있지 않습니다.
감사합니다.

**Comment by jjsk109** [comment]
안녕하세요 궁금한 접에 문의 드립니다 

master report와 stat report 를 재가공해서 사용하는 결과와 다차원 보고서의 결과가 같을까요??
다르다면 왜 @naver-searchad 에서는 왜 다차원 보고서 기능을 추가 안해주시는지 궁금합니다.

정말 궁금해서 문의 드립니다.

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 대용량 보고서 담당자입니다. 

2023년 2월 현재 대용량 보고서(master report와 stat report)를 이용하여 다차원 보고서의 지표를 자체적으로 구현한다고 할때 
대부분의 항목은 동일하게 구현이 가능힙니다. 
현재 대용량 보고서에서 제공되지 않는 지표는 방문당 평균페이지뷰와 방문당 평균체류 시간인데요. 
이항목들은 전환 유형별로 데이터를 수집하고 있지 않아 현재 대용량 보고서의 구조상 제공이 어려워 방안을 모색하고 있습니다.

과거(2017~18년 이전)에는 저희가 완전히 가공된 한가지 형태의 보고서만을 제공드리고 있었는데요. 
사용자 분들은 추구하는 목표와 용도 및 사용 패턴 광고 관여도에 따라 다양한 형태의 보고서를 원하거나 에초에 직접 자유롭게 가공할수 있는 원본 데이터 제공 혹은 어느정도 편의성이 있는 분석 도구 형태의 보고서등 다양하고 복합적인 Need를 모두 만족시켜 드리기가 대단히 어렵다고 판단했습니다.

이에 따라 저희는 API 서비스를 포괄한 보고서 제공 방향성을 아래와 같이 3가지 요소로 구상했습니다. 
1. UI를 통해 빠르게 필수적인 지표만을 확인하기를 원하는 (UI only 혹은 가벼운 API)사용자를 위해 : STAT(STAT은 광고관리사이트내 관리 화면에 표시되는 지표들입니다.) 
2. 네이버의 시각과 관점이 반영 되어 있기는 하나 어느정도 조건들을 바꿔가면서 분석을 원하는 사용자에게 : 다차원보고서
3. 전문적이고 대량의 데이터를 최대한의 자유도로 이용하고자 하는 고급 이용자 혹은 API 이용자에게 : 대용량 보고서(STAT REPORT와 MASTER)

이에 따라 각 타겟 이용자군의 Needs를 최대한 만족시킬수 있는 형태로 각 보고서 기능을 구현하게 되었는데요. 
여기가 가장 크게 고민이 된 부분은 다차원 보고서 였습니다. 다차원 보고서는 여러 조건에 항목들을 자유롭게 조합하여 데이터를 합산 혹은 연산해야 하는데 이를 단지 API 서비스 단에서만 구현하기에는 무리가 있었고, 일정 부분은 UI 혹은 클라이언트의 자원을 이용할수 있도록 구성할수 밖에 없었습니다. (오랜 노력을 통해 현재는 클라이언트의 자원을 거의 사용하지 않지만...여전히 이러한 자원 사용 여지를 남겨두는 것이 향후 상품 변화와 더 좋은 데이터 제공에 유리하다고 판단하고 있습니다.)
또한 퍼포먼스에 있어서는 각고에 노력에도 불구하고 UI를 통한 서비스 품질수준만을 만족시킬수 있었습니다. 

따라서 이를 API형태(예를 들어 STAT)로 제공드리기에는 너무 많은 걸림돌이 있었고, 이에 대한 대안으로 API에서는 최대한 raw 데이터를 대량으로 제공하여 다차원 보고서와 같은 형태의 지표를 이용자가 직접 구성할수 있도록 하는 형태로 대용량 보고서를 만들게 되었습니다. 물론 대용량 보고서만으로 대응이 되지 않는 지표들이나 지표 형태도 언젠가는 나타날수 밖에 없고...이 경우에는 다차원 보고서를 API로 제공드리기보다는 대용량 보고서를 업그레이드 하거나 기능 추가 하는 형태로 대응하는 것으로 방향을 잡았습니다. 

과거 API 서비스를 새롭게 론치 하던 시점에는 이러한 보고서 제공 방향에 대해 설명회나 문서등을 통해 홍보와 함께 사용자분들의 이해를 구했습니다만..이미 오랜 시간이 흘러 길게 말씀드리게 되었습니다. 장황하고 두서 없는 내용인 점 양해를 구하며 이해 하시는데 도움이 되었기를 기대해 봅니다. 

감사합니다.
