### ISSUE TITLE
Invalid Signature 문의 드립니다.

### ISSUE THREAD

**Issue by haedols8097** [naver/searchad-apidoc#521]
안녕하세요.
몇일 고생하고 있는데 도움 부탁 드립니다.

classic asp로 개발을 하고 있는데...
서명이 맞음에도 불구하고 403 에러, Invalid Signature 가 리턴되고 있습니다.

https://www.devglan.com/online-tools/hmac-sha256-online
여기에서 확인을 해도 생성된 서명은 동일한데
왜 Invalid Signature 가 리턴되는지 원인을 모르겠습니다.

관련 내용은 아래에서 확인 가능합니다.
http://www.nofriday.co.kr/test/api2.asp

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.
invalid signature 원인은 여러가지가 있을 수 있으며
올려주신 정보만으로는 파악이 불가합니다.
이 이슈와 관련해서는 다른 여러분들의 문의 이력을 참고해 보시면 도움이 되실 수 있겠습니다.
https://github.com/naver/searchad-apidoc/issues?q=Invalid+Signature

**Comment by haedols8097** [comment]
꼭 해결을 해야 할 상황이라서... ㅜㅜ
추가적으로 어떤 정보를 알려 드리면 조금이라도 피드백을 받을 수 있을까요?
답변 부탁 드립니다.

**Comment by naver-searchad** [comment]
@haedols8097 
가능하시면 response 헤더에 포함된 transaction id를 남겨 주시기 바랍니다.

**Comment by haedols8097** [comment]
답변 감사합니다.
첨부한 이미지와 같이 response 헤더쪽에 transaction id 값이 없습니다.
어떤 부분을 확인하면 되는지요?

![화면 캡처 2021-06-24 122600](https://user-images.githubusercontent.com/86386170/123198150-93f87680-d4e7-11eb-83e0-95235a6b242d.png)

**Comment by naver-searchad** [comment]
@haedols8097 
올려주신 이미지는 작성하신 asp의 response입니다.
asp 내에서 api.naver.com으로 요청한 request의 response 내용을 확인해 주셔야 합니다.
이 때 Customer id는 첨부파일 상에서 노출되지 않도록 주의해 주세요.

**Comment by naver-searchad** [comment]
@haedols8097 
추가로 확인 결과,
요청 헤더에 X-Signature: <script>document.write(test());</script>와 같이
생성된 결과값이 아니라 스크립트 코드가 그대로 들어온 것으로 보입니다.
코드 작성 후 테스트 시 실제로 전송되는 request 내용을 모두 잘 확인해 보시길 권장합니다.

그리고 공유해 주신 asp 테스트 코드는 공개되어서는 안되는 정보가 포함돼 있어 곧바로 조치가 필요합니다.
api 이용 약관을 주지해 주시고 이용에 주의해 주시기 바랍니다.

**Comment by haedols8097** [comment]
빠른 답변 감사합니다.
해결했습니다.
테스트 파일은 삭제했습니다.
감사합니다.
