### ISSUE TITLE
API로 AD 소재 입찰가 변경 시 광고 문의

### ISSUE THREAD

**Issue by eeeeeunh** [naver/searchad-apidoc#522]
안녕하세요.

쇼핑 검색에서 광고 소재 입찰가 변경 후 광고가 사라지는 현상을 발견하여 문의남깁니다.
현재 이슈는 아래와 같습니다.

1. 광고 소재 on상태이고 광고 노출 되는거 확인 함
2. 해당 검색광고API 중 ad update 부분에 PUT /ncc/ads/{adId}{?fields} 을 활용하여 입찰가 변경 시도
3. 한시간 내 광고 노출이 안됨

이러한 현상이 왜 나타나는 것이며 유의해야할 점이 있습니까?

**Comment by eeeeeunh** [comment]
윈도우 환경에 C#으로 진행했을 경우에 이상이 없는 것으로 판단되며 리눅스 환경에 java버전으로 진행했을 때 발생하는것으로 추측됩니다. 리눅스환경에 C#도 이상이 없어보이는데 리눅스 + 자바로 진행 했을 때 따로 설정해야하는 부분이 있을까요?

(광고가 사라지는 시점이 입찰가 변경 시도 후 대략 한시간 정도였는데 더 걸리는 경우도 있었습니다..)

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

알려주신 정보만으로는 도움을 드릴 수가 없겠습니다.
해당 증상이 발생한 광고에 대한 정보나
입찰가 변경을 요청한 response의 transaction id 등의 추가 정보가 필요합니다.
