### ISSUE TITLE
오전부터 429 오류가 자주 떨어지고 있습니다.

### ISSUE THREAD

**Issue by kaorimikage** [naver/searchad-apidoc#523]
오전부터 전체적인 API에서 429 오류가 자주 떨어지고 있습니다.

혹시 무슨 이슈가 있는지요?

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

특별한 내부 이슈나 변경사항은 없는 것으로 확인되었습니다.
당시 API 사용 환경 변화(가령 호출 빈도수 증가) 등을 확인해 보시면 될 것 같습니다.
