### ISSUE TITLE
당일 전환을 알려면..

### ISSUE THREAD

**Issue by underhappy** [naver/searchad-apidoc#524]
당일 키워드의 전환을 알고 싶습니다.
물론 실시간은 아니기에 시차는 있는건 알고 있습니다.

1)
우선은 다차원보고서로 알수 있으나... api에서 지원 안되며

2) stat report로 알 수 있으나 이건 당일 전환 조회는 안되는걸로 알고 있습니다.

가장 쉽게 당일 전환을 체크 할 수 있는 간단한 방법이 있을가요??

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

알고 계신 방법, 즉 키워드 id 목록으로 조회하는 방법이 현재로선 유일한 듯합니다.
당일 전환 데이터를 stat report에서 지원하는 것은 현실적으로 어려울 것으로 보입니다.
