### ISSUE TITLE
광고그룹 마스터 리포트 비즈니스 채널 데이터가 이상한 것들이 있습니다.

### ISSUE THREAD

**Issue by jjeonsangwon** [naver/searchad-apidoc#526]
마스터 리포트 ID : FDE94EA6EF0DBEE515BAA67208812DDE
마스터 리포트 종류 : Adgroup

해당 광고그룹을 생성요청하고(fromTime 없음) 다운로드를 받았는데 약 7개의 광고그룹 정보에서 데이터들이 이상하게 나와서 문의 드립니다.
약 7개의 광고그룹이 컬럼명과 맞지 않는 데이터들이 출력됩니다. 자세히 보니 다른 컬럼에 데이터들이 저장되어 있는 것 같습니다. (비즈채널 데이터가 등록시간에 있음)
이상 여부를 확인해주실 수 있을까요?

------

adgroupId=grp-a001-01-000000022202963, campaignId=cmp-a001-01-000000001282411, adgroupName=텐핑_PC_6-7세_여름방학, adgroupBidAmount=0, onOff=0, usingContentsNetworkBid=70, contentsNetworkBid=1, pcNetworkBiddingWeight=0, mobileNetworkBiddingWeight=70, usingKeywordPlus=100, keywordPlusBiddingWeight=100, businessChannelIdMobile=0, businessChannelIdPc=0, regTm=bsn-a001-00-000000000455870, delTm=bsn-a001-00-000000000455870, contentType=2021-07-07T06:04:11Z,

adgroupId=grp-a001-01-000000022202971, campaignId=cmp-a001-01-000000001282411, adgroupName=텐핑_PC_8-10세_여름방학, adgroupBidAmount=0, onOff=0, usingContentsNetworkBid=70, contentsNetworkBid=1, pcNetworkBiddingWeight=0, mobileNetworkBiddingWeight=70, usingKeywordPlus=100, keywordPlusBiddingWeight=100, businessChannelIdMobile=0, businessChannelIdPc=0, regTm=bsn-a001-00-000000000455870, delTm=bsn-a001-00-000000000455870, contentType=2021-07-07T06:04:22Z,

adgroupId=grp-a001-01-000000022202976, campaignId=cmp-a001-01-000000001282411, adgroupName=텐핑_PC_11-13세_여름방학, adgroupBidAmount=0, onOff=0, usingContentsNetworkBid=70, contentsNetworkBid=1, pcNetworkBiddingWeight=0, mobileNetworkBiddingWeight=70, usingKeywordPlus=100, keywordPlusBiddingWeight=100, businessChannelIdMobile=0, businessChannelIdPc=0, regTm=bsn-a001-00-000000000455870, delTm=bsn-a001-00-000000000455870, contentType=2021-07-07T06:04:32Z,

adgroupId=grp-a001-01-000000022203640, campaignId=cmp-a001-01-000000001290241, adgroupName=텐핑_모바일_통합_여름방학, adgroupBidAmount=0, onOff=0, usingContentsNetworkBid=70, contentsNetworkBid=1, pcNetworkBiddingWeight=0, mobileNetworkBiddingWeight=70, usingKeywordPlus=100, keywordPlusBiddingWeight=100, businessChannelIdMobile=0, businessChannelIdPc=0, regTm=bsn-a001-00-000000000455870, delTm=bsn-a001-00-000000000455870, contentType=2021-07-07T06:28:36Z,

adgroupId=grp-a001-01-000000022203651, campaignId=cmp-a001-01-000000001290241, adgroupName=텐핑_모바일_6-7세_여름방학, adgroupBidAmount=0, onOff=0, usingContentsNetworkBid=70, contentsNetworkBid=1, pcNetworkBiddingWeight=0, mobileNetworkBiddingWeight=70, usingKeywordPlus=100, keywordPlusBiddingWeight=100, businessChannelIdMobile=0, businessChannelIdPc=0, regTm=bsn-a001-00-000000000455870, delTm=bsn-a001-00-000000000455870, contentType=2021-07-07T06:28:47Z,

adgroupId=grp-a001-01-000000022203659, campaignId=cmp-a001-01-000000001290241, adgroupName=텐핑_모바일_8-10세_여름방학, adgroupBidAmount=0, onOff=0, usingContentsNetworkBid=70, contentsNetworkBid=1, pcNetworkBiddingWeight=0, mobileNetworkBiddingWeight=70, usingKeywordPlus=100, keywordPlusBiddingWeight=100, businessChannelIdMobile=0, businessChannelIdPc=0, regTm=bsn-a001-00-000000000455870, delTm=bsn-a001-00-000000000455870, contentType=2021-07-07T06:28:56Z,

adgroupId=grp-a001-01-000000022203663, campaignId=cmp-a001-01-000000001290241, adgroupName=텐핑_모바일_11-13세_여름방학, adgroupBidAmount=0, onOff=0, usingContentsNetworkBid=70, contentsNetworkBid=1, pcNetworkBiddingWeight=0, mobileNetworkBiddingWeight=70, usingKeywordPlus=100, keywordPlusBiddingWeight=100, businessChannelIdMobile=0, businessChannelIdPc=0, regTm=bsn-a001-00-000000000455870, delTm=bsn-a001-00-000000000455870, contentType=2021-07-07T06:29:05Z

**Comment by naver-searchad** [comment]
안녕하세요 
보고서 파일을 다운로드하시고 삭제를 요청하셔서 저희쪽에서는 파일의 이상 유무가 확인이 안되는 상황입니다.
`Adgroup` 마스터를 api나 광고주센터를 통해서 재새성하시고 ID를 알려주시면 저희쪽에서 확인 후 답변드리도록 하겠습니다.
