### ISSUE TITLE
ad create 시 type SHOPPING_PRODUCT_AD 

### ISSUE THREAD

**Issue by JungHunYu** [naver/searchad-apidoc#527]
https://naver.github.io/searchad-apidoc/#/operations/POST/~2Fncc~2Fads

type SHOPPING_PRODUCT_AD 인경우
TEXT_45는 다큐먼트화되어있는데 SHOPPING_PRODUCT_AD 는 다큐먼트화도 안되어있고
대충 json 만들어서보내면
{
  "ad":{},
  "adAttr":{},
  "customerId":"1518247",
  "nccAdgroupId":"grp-a001-02000000022289784",
  "referenceKey":"28035378140",
  "type":"SHOPPING_PRODUCT_AD",
  "inspectRequestMsg":"ELIGIBLE"
}

{"code":3830,"status":400,"title":"Invalid ad type."}  라고 에러메세지가 나옵니다.
SHOPPING_PRODUCT_AD으로 create AD하는방법좀 부탁드립니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

#202  이슈 등 기존 문의 답변 내용을 참고하시면 될 것 같습니다.
