### ISSUE TITLE
네이버 키워드의 일간 조회량을 알수는 없을까요?

### ISSUE THREAD

**Issue by underhappy** [naver/searchad-apidoc#528]
안녕하세요
1) 
월 조회량은 알 수가 있는데 일 조회량 파악은 어떻게 해야할까요?

2)RelKwdStat의 키워드의 월조회량은  어떤 기준인가요? 매월초마가 전월 조회량이 갱신이 되는건지 아니면 당일날 기준으로 한달치 조회량인지가 궁금합니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

- 일 조회량은 지원되지 않습니다.
- 키워드도구의 '월간검색수' 툴팁을 확인해 보시면 다음과 같습니다.
```
최근 한 달간 네이버를 이용한 사용자가 PC 및 모바일 에서 해당 키워드를 검색한 횟수입니다.
```
여기서 `최근 한 달`은 전월이 아니라 이전 30일을 의미합니다. 당일은 포함되지 않습니다.
