### ISSUE TITLE
SLA 문의

### ISSUE THREAD

**Issue by jasminecccc** [naver/searchad-apidoc#529]
안녕하세요,

네이버 클라우드의 경우는 아래와 같이 SLA 를 확인할 수 있는데요,
https://www.ncloud.com/policy/sla/svc

네이버 검색이나 광고 SLA 는 어떻게 확인할 수 있는지 궁금합니다.

고맙습니다.

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 api 담당자입니다. 

유사한 정보인 네이버 검색광고 및 네이버 검색광고 API에 관련된 정책/약관을 
아래 주소에서 확인하실수 있습니다.
네이버 검색광고 이용약관 :https://saedu.naver.com/adguide/policy/terms.nhn
네이버 검새광고 운영정책 : https://saedu.naver.com/adguide/policy/policy.nhn
네이버 검색광고 API 이용약관 : https://saedu.naver.com/adguide/policy/api.nhn

SLA에 대해서는 추가 확인후 답변 드리겠습니다. 

감사합니다.

**Comment by jasminecccc** [comment]
안녕하세요, SLA 언제쯤 확인 가능할지 재문의 드립니다.

고맙습니다.

**Comment by naver-searchad** [comment]
@jasminecccc 
네 현재 '검색광고' 서비스에 별도의 SLA는 없습니다.
추가 확인은 향후 계획 부분에 대해서 확인할 사항이 있는지 파악중이라고 보시면 되겠습니다.
감사합니다.

**Comment by naver-searchad** [comment]
@jasminecccc 
안녕하십니까 네이버 검색광고 API 담당자입니다. 

앞서 설명 드린 것처럼 네이버 검색광고 API에서는 SLA를 제공 하지 않으며 향후에도 제공할 계획은 없습니다. 

감사합니다.
