### ISSUE TITLE
RelKwdStat - biztpId

### ISSUE THREAD

**Issue by softkid** [naver/searchad-apidoc#53]
business type id ? 
종류에는 어떤 것이 들어가나요?

**Comment by naver-searchad** [comment]
biztpId는 업종 연관 키워드를 조회하실때 이용하시는 옵션입니다. 
들어가는 값은 업종 코드 이며 업종 코드리스트는 
마스터 리포트 중 BusinessCode (item=Biz)항목을 생성하시어 다운받으시면 되겠습니다. 
http://naver.github.io/searchad-apidoc/#/tags/MasterReport

주의 하실 점은 모든 업종에 데이터가 존재하는 것은 아니므로 데이터가 리턴되지 않는 업종도 있다는 것입니다.
