### ISSUE TITLE
쇼핑키워드 전환 디테일 리포트 생성 중 오류가 발생합니다.

### ISSUE THREAD

**Issue by lachelngose** [naver/searchad-apidoc#532]
-- Request
POST /stat-reports
Body: {'reportTp': 'SHOPPINGKEYWORD_CONVERSION_DETAIL', 'statDt': '20210630'}

-- Response
status_code: 400
Header: {'Connection': 'close', 'Cache-Control': 'no-store, must-revalidate', 'X-Transaction-ID': 'BRB60NH81DGC8', 'Content-Type': 'application/json;charset=UTF-8', 'Date': 'Wed, 18 Aug 2021 13:44:22 GMT', 'Strict-Transport-Security': 'max-age=15768000'}
Body: {'code': 11001, 'message': '잘못된 파라미터 형식입니다.'}

20210531 ~ 20210630 기간 리포트 생성 시도했고
SHOPPINGKEYWORD_DETAIL 타입은 해당 날짜 데이터가 잘 생성되는데
SHOPPINGKEYWORD_CONVERSION_DETAIL 타입이 전부 위와 같은 오류가 나고 생성이 안됩니다.

바디 파라미터 타입도 전부 동일하게 사용하였는데 어떤 파라미터가 잘못되었는지 모르겠습니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.
문의 확인이 늦었습니다.

문의하신 리포트 유형의 경우 최근 45일까지만 가능합니다.
상세한 사항은 아래 faq 항목을 참고해 주시기 바랍니다.
https://github.com/naver/searchad-apidoc/wiki/FAQ-stat#q-stattype-%EC%9D%84-%ED%86%B5%ED%95%B4%EC%84%9C-%EC%A0%9C%EA%B3%B5%EB%90%98%EB%8A%94-%EB%B3%B4%EA%B3%A0%EC%84%9C-%EC%A2%85%EB%A5%98
