### ISSUE TITLE
keywordstool을 사용하였는데 null 값만 돌아옵니다.

### ISSUE THREAD

**Issue by NCuber** [naver/searchad-apidoc#533]
` 
String apiURL = "https://api.naver.com/keywordstool?hintKeywords=" + keyword + "&includeHintKeywords=1&showDetail=1";
        String path = "/keywordstool";
        String signatureID = null;
        
        try {
            signatureID = Signatures.of(time, "GET", path, clientSecret);
        } catch (SignatureException e) {
            e.printStackTrace();
            System.out.println("실패");
        }

        final HttpHeaders headers = new HttpHeaders();
        headers.set("X-Timestamp", time);
        headers.set("X-API-KEY", clientId);
        headers.set("X-Customer", customerId);
        headers.set("X-Signature", signatureID);

        final HttpEntity<String> entity = new HttpEntity<>(headers);
        return restTemplate.exchange(apiURL, HttpMethod.GET, entity, relateKeyword.class, keyword).getBody();
`

몇 개를 프린트 해본 결과

진입주소는
https://api.naver.com/keywordstool?hintKeywords=USB&includeHintKeywords=1&showDetail=1

결과는
<200,relateKeyword{relKeyword='null', monthlyPcQcCnt='null', monthlyMobileQcCnt='null', monthlyAvePcClkCnt='null', monthlyAveMobileClkCnt='null', monthlyAvePcCtr='null', monthlyAveMobileCtr='null', plAvgDepth='null', compIdx='null'},[Connection:"close", Cache-Control:"no-store, must-revalidate", X-Transaction-ID:"BRD8OBQQPDI09", Content-Type:"application/json;charset=UTF-8", Date:"Sat, 21 Aug 2021 19:29:44 GMT", Strict-Transport-Security:"max-age=15768000"]>
나옵니다. 

여러가지 확인해본 것 같은데 이유를 잘 모르겠습니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

문의주신 요청 형태 자체에 문제는 없어 보입니다.
다만 결과에
```
relateKeyword{relKeyword='null',...
```
처럼 적어 주셨는데요,
api의 정상적인 응답 형태는 다음과 같습니다.
```
{"keywordList":[{"relKeyword":"USB",...
```
혹시 응답 데이터 파싱이 잘못되었는지 확인 부탁드립니다.
