### ISSUE TITLE
php /stats ids값 파라미터

### ISSUE THREAD

**Issue by sdaehoon87** [naver/searchad-apidoc#536]
안녕하세요

$a = $api->GET('/stats',array (
    'ids' =>'cmp-a001-01-000000000230690','cmp-a001-03-000000003722161',
    'fields' => '["impCnt","clkCnt","ctr","cpc","salesAmt","convAmt","cpConv","crto","ror","ccnt"]',
    'datePreset' => 'last30days',
    'timeIncrement' => 'allDays')
);

캠페인 하나만 리턴이 됩니다.

ids값에 여러 캠패엔 ID는 어떤 형식으로 넣는지 질문드립니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

ids 요청 파라미터는 다음과 같은 형태가 되게 하면 됩니다.
```
&ids=cmp-a001-000000000015129,cmp-a001-000000000015135,...
```

**Comment by sdaehoon87** [comment]
$a = $api->GET('/stats',array (
'&ids' =>'cmp-a001-01-000000000230690','cmp-a001-03-000000003722161',
'fields' => '["impCnt","clkCnt","ctr","cpc","salesAmt","convAmt","cpConv","crto","ror","ccnt"]',
'datePreset' => 'last30days',
'timeIncrement' => 'allDays')
);

위와 같은 형태면 호출이 안되는데 맞는건지 질문드립니다.

가능하다면 위 해당 예제를 변경하여 답변 요청드려도 될까요?

**Comment by naver-searchad** [comment]
@sdaehoon87 
위의 답변 드린 내용은 http get 요청시 query paramter 형태를 얘기드린 것이니
개발하시는 언어와 무관하게, 생성되는 request url을 잘 살펴보고 참고하시라는 의미입니다.
(&는 url query parameter 구분자입니다)

개발하시는 프로그램의 내용 자체에 대해서는 도움을 드릴 수 없음을 양해해 주시기 바랍니다.
