### ISSUE TITLE
그룹 생성시 error 발생.

### ISSUE THREAD

**Issue by exit39** [naver/searchad-apidoc#537]
안녕하세요. naver api를 통해서 그룹 생성 및 여러가지 기능을 잘 사용하고 있습니다.

질문은 다름이 아니라 제목과 같이 그룹 생성 기능을 잘 사용하고 있다가 다음과 같은 에러가 6월 19일? 이후부터 발생하고 있는데 
그룹 유형이 필수값으로 변경 된 것인가요?

{"code":3734,"status":400,"title":"Invalid type of ad group.","detail":"광고그룹 유형이 없습니다."}

sample 소스를 찾아봐도 그룹 추가에 대한 내용을 확인 할 수가 없어서 질문 드립니다.
sample 소스를 업데이트 해주시거나 간단한 샘플 작성 (model / adgroups 필드명이라도 참고 가능하도록) 부탁드립니다.

**Comment by naver-searchad** [comment]
@exit39 안녕하세요? 네이버 검색광고 API 입니다.

기존에도 광고 그룹 유형은 필수 입력값 이었습니다. 하지만, 사용자의 편의를 위해 기본 값을 서버에서 설정해 주고 있었습니다.
하지만, 쇼핑 캠페인의 광고 그룹 유형이 다양화 되면서, 서버에서 광고 그룹의 유형을 입력하게 되면 사용자의 의도와 상관없이 다른 종류의 광고그룹이 생성될 수 있어서, 더이상 기본값으로 설정해주지 않도록 변경 되었습니다.

캠페인별 등록 가능한 광고그룹 유형은 아래의 링크를 참고하세요.

https://github.com/naver/searchad-apidoc/wiki/FAQ#q-캠페인-유형별-등록가능한-그룹-유형은-어떻게-되나요

**Comment by exit39** [comment]
그럼 메뉴얼에 있는 adgroupType 필드를 model / adgroups 에 추가해서 알맞는 그룹 타입만 넣으면 된다는 것이겠지요?

WEB_SITE
SHOPING
INFORMATION
PRODUCT
BRAND_SEARCH
PLACE
CATALOG

이렇게 등록이 가능하다고 메뉴얼상에 나타나있던데요.
