### ISSUE TITLE
광고그룹에서 요일 시간 타겟팅 확인방법

### ISSUE THREAD

**Issue by beomhee** [naver/searchad-apidoc#538]
안녕하세요..

adgroup에서 타겟팅 정보를 확인하려는데 API 문서와 get으로 읽어온 내용이 다른 것 같아 문의 드립니다.

Adgroup에서 get으로 가져온 항목에는 targets[] 보이지 않습니다.
targetSummary라는 항목이 있는데 targets가 targetSummary로 변경된 것인지요?
targetSummary의 내용을 살펴보면 week와 time으로 구분되어 보여지는데, 어떻게 사용하는지 궁금합니다.
디버깅에서 확인된 내용입니다. 
ad_group['targetSummary'] : {'week':'all', 'time':'all'}

http://naver.github.io/searchad-apidoc/#/definitions/Target 에서 확인한 샘플의 내용은 다음과 같습니다.
{
    "SUN":16777215,
    "MON":16777215,
    "TUE":16777215,
    "WED":16777215,
    "THU":16777215,
    "FRI":16777215,
    "SAT":16777215
} // Ads to be shown always. This is exactly the same with to set 'target' as null.

사용방법에 대해서 확인부탁드립니다.

감사합니다.

**Comment by naver-searchad** [comment]
@beomhee 안녕하세요? 네이버 검색광고 API 입니다.

[광고 그룹 단건 조회](http://naver.github.io/searchad-apidoc/#/operations/GET/~2Fncc~2Fadgroups~2F%7BadgroupId%7D)시에는 광고그룹에 속한 타겟 상세 정보와 요약정보를 포함하고 있습니다.

[하지만 복수의 광고 그룹 목록 조회](http://naver.github.io/searchad-apidoc/#/operations/GET/~2Fncc~2Fadgroups%7B%3FnccCampaignId,baseSearchId,recordSize,selector%7D)의 경우 타겟팅 요약 정보만 포함됩니다. 이는 API가 처음 제공될 때 부터 고려된 내용입니다.

타겟팅 정보가 필요할 경우 광고그룹 ID를 이용하여 개별 광고그룹을 조회하시거나, 타겟팅 API를 이용하여 조회하실수 있습니다.
https://github.com/naver/searchad-apidoc/issues/21 이 이슈를 참고하시면 될듯 합니다.

감사합니다.
