### ISSUE TITLE
Adgroup: update (by fields) 키워드 확장 관련

### ISSUE THREAD

**Issue by yjseo11h11m** [naver/searchad-apidoc#539]
안녕하세요. 
Adgroup: update (by fields) 을 통해 키워드 확장 관련값을 수정하려고 하는데 에러가 발생하여 문의드립니다.

body : {"useKeywordPlus":true,"keywordPlusWeight":150}
url : https://api.naver.com/ncc/adgroups/grp-a001-01-000000023302857?fields=useKeywordPlus

에러 : statusCode 500 : {"code":1005,"status":500,"title":"Cannot handle the request."} 

필드값인 useKeywordPlus 에 대한 값도 넣어줬는데 왜 안되는 걸까요?
또한 그냥 update를 해보아도 useKeywordPlus와 keywordPlusWeight 값은 업데이트가 안되었습니다.

제가 혹시 놓친 것이 있을까요? 
확인 부탁드립니다.

감사합니다.

**Comment by naver-searchad** [comment]
@yjseo11h11m 안녕하세요? 네이버 검색광고 API 입니다.

광고 그룹 수정시 adgroupType 값은 필수 입력값입니다.

감사합니다.
