### ISSUE TITLE
/customer-links 호출시 403 에러

### ISSUE THREAD

**Issue by ghost** [naver/searchad-apidoc#540]
You don't have permission to access on this server 라는메세지와함께

403 forbidden 이뜹니다.

어떻게 해결해야할까요

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

아마도 /customer-links api 사용시 customer id를 광고주의 것으로 사용하셨을 듯합니다.
이 api는 api 사용자 계정 자신의 customer id를 이용하셔야 합니다.
