### ISSUE TITLE
stat 오퍼레이션 get stats by statType (NPLA_SCH_KEYWORD) 관련 

### ISSUE THREAD

**Issue by begatsby** [naver/searchad-apidoc#541]
안녕하세요?

문제현상 : stat / get / statType / NPLA_SCH_KEYWORD / api를 콜할경우 [] 의 리턴값만 받습니다.

콜하는 ad id 는 광고 소재 상세 >제외키워드 (https://manage.searchad.naver.com/customers/쇼핑아이디/ads/소재아이디)
탭에서 이전 30일까지 노출되었던 키워드들이 보이는 소재입니다.

해당 api의 기간이 이전 30일이 아닌, 요청 전날을 기준으로 결과값을 리턴하나요?
아니라면 왜 빈 값을 리턴하는지 모르겠습니다.

하기의 코드로 요청했습니다.

---------------------------------------
uri = '/stats'
method = 'GET'
sample_params = {
'id': '광고소재 아이디',
'statType':'NPLA_SCH_KEYWORD',
}

BASE_URL = 'https://api.naver.com'
API_KEY = ''
SECRET_KEY = ''
CUSTOMER_ID = ''

r = sess.get(BASE_URL + uri, params=sample_params, headers=get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID))

parsed = r.json()
print(parsed)
---------------------------------------

**Comment by naver-searchad** [comment]
안녕하세요 네이버 검색광고 API입니다.

확인해 본 결과,
플레이스 오픈 당시 관련 데이터의 스펙 변경, 저장소 이전 작업 중 오류가 있었음이 확인되었습니다.
지금은 12일 기준 데이터 이후로 정상화 되었습니다.
