### ISSUE TITLE
자동입찰 정책이 궁금합니다

### ISSUE THREAD

**Issue by lhw8611** [naver/searchad-apidoc#543]
파워링크, 쇼핑검색의 키워드/소재를 몇 분마다 API를 이용하여 자동입찰을 하려고 합니다.
예를 들어 1초에 한 번  순위를 불러와서 1초에 한 번씩 100개의 키워드를 입찰을 한다던지 해도 정책상 문제가 없을까요?
있다면 최대 한도가 궁금합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 API 담당자 입니다. 

네이버 검색광고 API는 호출수의 제한은 존재하지 않으며 호출 속도만 제한 됩니다. 
속도 측정 기준은 호출 대상이 되는 계정이며 
속도 제한 값은 시스템 전체 사용 상황에 따라 유동적으로 변경되나 일반적으로 초당 25회 내외, 최대 30회 정도로 
관측되고 있습니다. 
속도를 초과할 경우 429번 에러가 리턴됩니다. 이떄 계속 호출을 하게 되면 429번 에러만 리턴되며 결과가 리턴되지 않습니다. 
너무 많은 호출 에러(429번)가 리턴되면 짧은 시간 즉 0.5초 내외~ 1초 정도 sleep을 하셨다가 다시 호출 하시는 방법을  권장 드립니다. 

말씀 주신 시나리오에서 "순위를 불러와서"라는 부분이 있는데요. 네이버 검색광고 API를 통해서 제공되는 순위는 일 단위 주기로 제공되는 전일의 평균노출 순위 혹은 1시간 이상의 주기로 업데이트 되는 당일의 시간대 단위 평균 노출 순위이므로 말씀 주신 시나리오 처럼 순위를 1초에 한 번씩 조회 하는 것은 무의미 합니다. 

또한 네이버 검색광고 API의 엑세스라이선스와 비밀키를 이용한 호출 만이 네이버 검색광고 API 사용으로 인정 되며 이외의 방식을 통한 API 혹은 광고시스템 기능에 대한 UI를 사용 하지 않은 호출은 모두 기계적 접근 및 어뷰징 혹은 시스템 공격 시도로 간주됩니다. 네어버 검색광고는 기계적 접근 등을 네이버 검색광고 이용약관(https://saedu.naver.com/adguide/policy/terms.naver)에 의거하여 금지하고 있습니다.
기계적 접근 확인 시 계정 및 광고서비스 이용 중지, 해지 등 제재가 있을 수 있으며 경우에 따라서는 민,형사상 책임이 발생할 수 있으므로 주의 하셔야 합니다. 
또한 광고가 게재 되는 네이버 서비스(검색결과 및 쇼핑등 포함)는 이용 약관(https://policy.naver.com/policy/service.html)에서 자동화된 수단을 통한 서비스 이용을 금지하고 있으므로 이 점 역시 참고 부탁드립니다. 

감사합니다.
