### ISSUE TITLE
searchad 에서 NPC 와 NPLA 는 무슨 의미인가요?

### ISSUE THREAD

**Issue by SAT0SHINAKAM0T0** [naver/searchad-apidoc#549]
안녕하세요
searchad 의 estimate 에서 비슷한 api 가 자주 나오는데 
NPC 와 NPLA 는 무슨 의미이며 어떨때 사용하나요?

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

NPC는 '파워컨텐츠', NPLA는 '쇼핑검색광고'를 각각 지칭하고 있습니다.
