### ISSUE TITLE
에러가 납니다.

### ISSUE THREAD

**Issue by gurumzip** [naver/searchad-apidoc#55]
```
Properties properties = PropertiesLoader.fromResource("sample.properties");
		   String baseUrl = properties.getProperty("BASE_URL");
		   String apiKey = properties.getProperty("API_KEY");
		   String secretKey = properties.getProperty("SECRET_KEY");
		   long customerId = Long.parseLong(properties.getProperty("CUSTOMER_ID"));
		   
		   RestClient rest = RestClient.of(baseUrl, apiKey, secretKey);
		   
		   
		   String keywordsPath = "/keywordstool"; 
		  
		   com.mashape.unirest.http.HttpResponse<String> response =
		     rest.get(keywordsPath, customerId)
		       .queryString("hintKeywords", "구름집")
		       .queryString("includeHintKeywords", 1)
		       .queryString("showDetail", 1)
		       .asString();
		   String keyBody =  response.getBody();
		   //rest.asObject(response, RelKeyword[].class);
		   
		   /* Data Parser */
		   JSONParser jsonParser = new JSONParser();
		   JSONObject jsonObject = (JSONObject) jsonParser.parse(keyBody);
		   JSONArray keywordList = (JSONArray) jsonObject.get("keywordList");
		   
		   System.out.println(keywordList.toString());

```

============ Request =============
GET /keywordstool?hintKeywords=%EA%B5%AC%EB%A6%84%EC%A7%91&includeHintKeywords=1&showDetail=1 HTTP/1.1
accept-encoding: gzip
user-agent: unirest-java/1.3.11
X-API-KEY: 
X-Customer: 883708
X-Signature: 7mXcC618XIT3HrhxncmTGPvt/cycu6QJaTp77mlPqWs=
X-Timestamp: 1493237459290

============ Response ============
HTTP/1.1 403 Forbidden
Connection: close
X-Transaction-ID: ARLFHMA5HPEQI
Content-Type: application/json; charset=UTF-8
Date: Wed, 26 Apr 2017 20:10:58 GMT

Exception in thread "main" java.lang.NullPointerException
	at com.naver.searchad.api.util.RelKeyword.main(RelKeyword.java:43)

keybody를 보니까

{"signature":"hNiutdUYU756oQjd7vzjTEr2iZAnCBHurVExhz028Ys=","status":403,"detail":"Signature 'hNiutdUYU756oQjd7vzjTEr2iZAnCBHurVExhz028Ys=' is invalid.","title":"Invalid Signature","type":"urn:naver:api:problem:invalid-signature"}
라고 나오는데요..

뭐가 잘못된걸까요?

제가 넣지 않은 정보가 있었을까요?

api_key라는게 엑서스라이선스 키 맞죠?
api사용 관리 들어가면 비밀키 위에 있는거요.

**Comment by gurumzip** [comment]
그리고 request 규격만 맞추면 꼭 java나 php 등 예제코드가 있는 언어가 아닌 python 같은 언어로도 충분히 구현이 가능하나요?

**Comment by gurumzip** [comment]
엑세스라이선스
비밀키
customer id는 제가 다시 확인해봤으나 정확합니다.

**Comment by ystopia** [comment]
@gurumzip 네 가능합니다. 어짜피 HTTP로 request하기 위한 headers, parameters 등을 세팅하기 위해 다양한 언어로 접근하는거니까요!

**Comment by ystopia** [comment]
@gurumzip customer_id도 string으로 해보시겠어요? rest.get(keywordsPath, customerId) 여기서 두번째 인자에 대해서 설명해주시겠어요?

**Comment by ystopia** [comment]
@gurumzip signature만드는 함수는 http://naver.github.io/searchad-apidoc/#/samples로 하셨는지요?

**Comment by gurumzip** [comment]
@ystopia rest.get(arg1, arg2) arg2가 long 타입이라 string으로는 들어가지가 않네요.. 

그리고 말씀하신 signature는 어디서 만들어야되는건가요??ㅠ 처음해보는거라
java코드 내에서 해야되는건가요??;
그리고 java코드 내에서 해야한다면 query보낼때 담아서 보내면 되는건가요? 키워드 담아서 보내듯이요.

**Comment by ystopia** [comment]
@gurumzip signature를 직접 생성하셔야 합니다. java 코드 내에서 함수 만들어서 signature를 생성하시면 (http://naver.github.io/searchad-apidoc/#/samples 참조) 그 signature를  RestClient로 request 보내실때 헤더값의 X-Signature에 들어가도록 하셔야 합니다. request를 보내실 때 query(입력파라미터), 헤더값을 보내시는데요. 헤더값에 X-API-KEY, X-Customer, X-Signature, X-Timestamp 가 있고 이것들을 모두 헤더값에 넣으셔야 합니다. RestClient가 어디까지 자동으로 해주는지는 모르겠지만 참고하시고 개발해주세요~
