### ISSUE TITLE
소재의 연결 URL 을 어떻게 가져올 수 있나요?

### ISSUE THREAD

**Issue by kangseonghyun94** [naver/searchad-apidoc#551]
api 문서에서 잘 못찾겠어서 문의 드립니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

소재를 get하는 [api](http://naver.github.io/searchad-apidoc/#/operations/GET/~2Fncc~2Fads~2F%7BadId%7D)에 보시면
ad object 가 있습니다. example을 열어 보시면 연결 url들을 보실 수 있습니다.
