### ISSUE TITLE
네이버 검색광고 API 사용 중 간헐적으로 Connection reset 에러가 발생합니다.

### ISSUE THREAD

**Issue by jjeonsangwon** [naver/searchad-apidoc#552]
안녕하세요.
현재 사내에서 검색광고 API를 사용 중인데, 10월 28일부터 간헐적으로 API 호출 과정에서 Connection reset 에러가 발생합니다.
광고그룹 조회 (GET /ncc/adgroups/{adgroupId}) 사용 시에 간헐적으로 Connection reset(broken pipe) 에러가 발생합니다.
서버 문제인가 싶어서 로컬에서 테스트 해보니(1초에 1번 씩 광고그룹 조회) 일정 시간이 지난 이후(약 4시간 이후 정도로 추정됨) Connection reset 빈도가 점점 높아지는 것을 확인하였는데요.

10월 28일 이전에는 아무런 에러가 없었기에 문의 드립니다.
네이버 개발자 포럼에도 28일 이후로 Connection reset 관련 글이 몇개씩 올라오는 것으로 보아 바뀐 것이 있는 건지 궁금합니다. (https://developers.naver.com/forum/list?page=1&q=Connection)
새로운 규칙이 적용된 것이 있을까요??

**Comment by lhw8611** [comment]
저도  10월 29일부터 이 오류가 많이 뜨네요..

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 API 담당자입니다.

우선 업무에 불편을 드려 대단히 죄송합니다.

문의 주신 에러와 관련하여 관련하여 몇가지 대응 조치를 전일 시행했습니다. 
혹시나 계속 관련 현상이 발생한다면 다시 코멘트 부탁드립니다.

이와는 별개로 현재 문제의 근본적인 원인은 사용량의 지속적인 증가로 인한 것으로 보입니다. 
최근에도 지속적으로 증가하는 사용량을 고려하여 기존의 가용량 확보를 위한 정기 작업 외에 추가
대응 방안 역시 고려하고 있습니다.

아마도 이번 달 내로 대응책을 적용하는 작업 공지를 드리게 될 것으로 예상됩니다.

감사합니다.
