### ISSUE TITLE
최근 갑자기 자주 발생하는 429 Too Many Requests 관련 문의

### ISSUE THREAD

**Issue by choics** [naver/searchad-apidoc#553]
안녀하세요.
최근 Too Many Requests 가 자주 발생하여 문의 드립니다.
API 호출을 늘리지 않은 상태에서 몇년간 지속적으로 서비스 사용을 하고 있는데
최근들어 호출양을 변경하지 않았음에도 불구하고 Too Many Requests 가 많이 발생하고 있습니다.
오늘 특히 더 자주 발생하는듯하여 관련하여 확인 요청 드립니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

최근 API 서비스의 성능 관련이나 혹은 영향을 줄 수 있는 변경 내용은 확인되지 않고 있습니다.

**Comment by gimslab** [comment]
안녕하세요. 참고로 저도 어제, 오늘 저런 오류를 많이 접하고 있습니다.

**Comment by lhw8611** [comment]
저희도 예전보다 훨씬 많아졌습니다!

**Comment by lachelngose** [comment]
저희도 어제부터 다수 발생합니다 ㅠ

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 API 담당자입니다.

우선 업무에 불편을 드려 대단히 죄송합니다.

문의 주신 에러와 관련하여 현재 서비스 장비 및 시스템 점검을 진행 중에 있으며
최근에도 지속적으로 증가하는 사용량을 고려하여 기존의 가용량 확보를 위한 정기 작업 외에 추가
대응 방안 역시 고려하고 있습니다.
아마도 이번 달 내로 대응책을 적용하는 작업 공지를 드리게 될 것으로 예상됩니다. 

감사합니다.

**Comment by naver-searchad** [comment]
@choics 님 @lachelngose 님 @gimslab 님 @lhw8611 님 @GamjaPower 님 

안녕하십니까 네이버 검색광고 API 담당자입니다. 

지난 수요일에 속도 관련 추가 대응 작업을 진행하였습니다. 
지난 주말부터 현재까지 429 에러 발생 빈도가 지난 주 수요일 이전과 비교하여 어떠하신지 혹 가능하시다면
말씀을 부탁드립니다.

추가로 과거보다 최근 들어 호출이 필요한 관리 광고수나 키워드 수가 증가하신 상황은 아닌지에 대한 말씀도 부탁드립니다. 
번거롭게 해드려 죄송합니다만 추후 작업 계획에 참고하고자 문의 드려 봅니다. 

감사합니다.

**Comment by lhw8611** [comment]
지난 수요일에 속도 관련 추가 대응 작업을 진행하였습니다.
지난 주말부터 현재까지 429 에러 발생 빈도가 지난 주 수요일 이전과 비교하여 어떠하신지 혹 가능하시다면
말씀을 부탁드립니다.

-> 전저는문제 없었습니다.  안정적으로 잘 됩니다.

추가로 과거보다 최근 들어 호출이 필요한 관리 광고수나 키워드 수가 증가하신 상황은 아닌지에 대한 말씀도 부탁드립니다.
번거롭게 해드려 죄송합니다만 추후 작업 계획에 참고하고자 문의 드려 봅니다.

-> 없었습니다

**Comment by gimslab** [comment]
> @choics 님 @lachelngose 님 @gimslab 님 @lhw8611 님 @GamjaPower 님
> 
> 안녕하십니까 네이버 검색광고 API 담당자입니다.
> 
> 지난 수요일에 속도 관련 추가 대응 작업을 진행하였습니다. 지난 주말부터 현재까지 429 에러 발생 빈도가 지난 주 수요일 이전과 비교하여 어떠하신지 혹 가능하시다면 말씀을 부탁드립니다.
> 
> 추가로 과거보다 최근 들어 호출이 필요한 관리 광고수나 키워드 수가 증가하신 상황은 아닌지에 대한 말씀도 부탁드립니다. 번거롭게 해드려 죄송합니다만 추후 작업 계획에 참고하고자 문의 드려 봅니다.
> 
> 감사합니다.

안녕하세요 일단 자세한 로그는 안봤지만
문제 없이 잘되고 있습니다.
데이터가 더 늘어난건 아니었습니다.
감사합니다.

**Comment by naver-searchad** [comment]
@gimslab님 @lhw8611님  
안녕하십니까 네이버 검색광고 API 담당자입니다. 

답변에 감사드립니다. 피드백 주신 내용 큰 도움이 되었습니다. 

감사합니다.
