### ISSUE TITLE
오늘 저녁 18시 경 503 Service Unavailable 상태 관련 문의 드립니다.

### ISSUE THREAD

**Issue by lachelngose** [naver/searchad-apidoc#555]
오늘 17시 50분 정도부터 20분간 naver api 요청에서 계속해서 503 Service Unavailable 응답을 받았습니다.
공지 사항을 봐도 특별한 사항을 찾지 못했는데, 혹시 원인을 알 수 있을까요?
트랜잭션 ID 일부만 첨부합니다.

BT14A3VE19JCT
BT14A42UP9JMI
BT14A440P9JP5
BT14A44GP9JQI
BT14A45C99JSP
BT14A45C99JSR

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 API 담당자입니다. 

11월 10일 오후 서비스 메인터넌스 과정에서 발생한 에러입니다. 

사용량 체크 및 순차 작업을 통해 에러가 발생하지 않도록 작업을 하고 있어 별도로 공지를 드리고 있지는 않으나 
이번 건의 경우 장비 교체 및 전환 과정에서 약간의 시차가 발생하여 일부 커넥션에서 에러가 발생한 것을 
확인하였습니다. 

업무에 불편을 드려 대단히 죄송합니다. 
향후에는 이러한 일이 없도록 주의하겠습니다. 

감사합니다.
