### ISSUE TITLE
STAT REPORT(대용량 보고서) 관련하여 질문드립니다.

### ISSUE THREAD

**Issue by mm00nn** [naver/searchad-apidoc#556]
안녕하세요.
STAT REPORT(대용량 보고서) 관련하여 질문드립니다.
**네이버 쇼핑 검색 광고**를 집행하여 리포트를 조회했을 때

1. AD(광고 효과 보고서)의 키워드 ID와 SHOPPINGKEYWORD_DETAIL(쇼핑 검색 광고 키워드 상세 보고서)의 키워드 ID의 차이
2. 각 리포트에서 키워드 ID가 하이픈으로 표시되는 경우

를 알 수 있을까요?

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

쇼핑 검색광고의 경우 아시다시피 파워링크 등의 다른 상품과는 달리 관리되는 키워드가 별도로 없습니다.
즉 광고주가 등록하고 관리하는 키워드가 없으므로 키워드 id도 없습니다.
따라서 쇼핑 검색광고 키워드 상세 보고서에서의 '키워드'는 property name이 `Search keyword`(질의어)이며
다른 상품들의 보고서에 나가는 `AD keyword ID`(nkw-로 시작하는 관리 id)와는 다릅니다.
그리고 쇼핑 검색광고의 광고가 매칭되는 질의어가 있을 수도 있지만 조건에 따라 없을 수도 있으므로 이 때는 하이픈으로 표시됩니다.

**Comment by mm00nn** [comment]
> 안녕하세요, 네이버 검색광고 API입니다.
> 
> 쇼핑 검색광고의 경우 아시다시피 파워링크 등의 다른 상품과는 달리 관리되는 키워드가 별도로 없습니다. 즉 광고주가 등록하고 관리하는 키워드가 없으므로 키워드 id도 없습니다. 따라서 쇼핑 검색광고 키워드 상세 보고서에서의 '키워드'는 property name이 `Search keyword`(질의어)이며 다른 상품들의 보고서에 나가는 `AD keyword ID`(nkw-로 시작하는 관리 id)와는 다릅니다. 그리고 쇼핑 검색광고의 광고가 매칭되는 질의어가 있을 수도 있지만 조건에 따라 없을 수도 있으므로 이 때는 하이픈으로 표시됩니다.

**Comment by mm00nn** [comment]
쇼핑 검색 광고의 경우 키워드 ID가 존재하지 않는 것으로 이해하였습니다.
그렇다면 AdKeyword: list (by adgroup id) API를 호출하였을 때, 아래의 쇼핑 검색 광고 캠페인의 하위에 키워드 ID가 존재하는 이유를 알 수 있을까요? (추가적으로 공유드려야 하는 정보가 있다면 알려주세요.)

- Campaign ID: cmp-a001-02-000000004035682

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

쇼핑 검색 캠페인의 경우 3가지 유형의 광고그룹을 등록할 수 있습니다.
* 쇼핑몰 상품형
* 제품 카탈로그형
* 쇼핑 브랜드형

위 광고 그룹중 `쇼핑몰 상품형`, `제품 카탈로그형`의 광고그룹인 경우 앞서 언급한 경우와 같이 키워드를 등록할 수 없습니다.
하지만 `쇼핑 브랜드형` 광고그룹은 3가지 유형의 키워드를 등록할 수 있습니다.

자세한 내용은 검색광고 API release note (2021년 3월 17일)(http://naver.github.io/searchad-apidoc/#/release-notes)를 확인하시거나, 광고주센터 공지사항(https://saedu.naver.com/notice/view.naver?notiSeq=3752&catg=1&fixYn=N&searchOpt=all&keyword=) 확인 부탁드립니다.

**Comment by mm00nn** [comment]
빠른 답변 감사드립니다.
그렇다면 쇼핑 검색 광고를 집행하여 AD(광고 효과 보고서) API를 호출하였을 때 광고 그룹의 유형이 쇼핑 브랜드형일 경우에는 키워드 ID 값이 조회된다는 것이 맞을까요?
