### ISSUE TITLE
전환의 누락 여부

### ISSUE THREAD

**Issue by begatsby** [naver/searchad-apidoc#557]
안녕하세요? 

네이버 쇼핑 상품 광고 / 프리미엄로그 설치 전제 하에
클릭이나 전환(구매)숫자의 누락 가능성 문의드립니다.

자체 서버 내 방문(클릭)이나 구매(전환) 데이터와 차이가 있는 것 같아 여쭤봅니다.
클릭의 경우 무효 클릭으로 카운트 되는것도 몇몇 보이는것같은데 전환 또한 그러한지요?

혹시 수치상으로 표현된 누락 관련 데이터가 있는지 문의드립니다.

만약 누락이 된다면 링크([https://saedu.naver.com/help/faq/ncc/view.naver?faqSeq=120])에서 추천하듯 URL 파라미터 추가 등을 통해 정확도를 향상시킬수 있는지도 문의드립니다.

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 API 담당자입니다.

답변이 늦어 죄송합니다. 전환 관련 문의는 네이버 검색광고 고객센터 문의하기(https://saedu.naver.com/help/inquiry/bridge.naver)를 이용하시며 더 빠르게 답변을 받으실수 있습니다. 

네이버 검색광고에서 제공되는 클릭/전환 값이 자체적으로 인식하신 값과 차이가 발생하는 부분에 대하여 답변 드립니다.
클릭의 경우 네이버 검색광고는 무효 클릭수는 제외하고 있어 이로 인해 광고주님 사이트에서 직접 측정하신 방문 수와 클릭수간 차이가 발생하는 경우가 존재할수 있으며 이 외에도 광고주님들 사이트 상황 및 측정하시는 방식 그리고 측정 기준에 따라 상호간 값의 차이가 발생하는 경우가 간혹 있습니다.

다음으로 전환의 경우를 말씀드리면 네이버 광고 시스템은 네이버 광고 유입으로 인해 발생한 전환 데이터 중 광고주님께서 설정하신 전환 추적 기간 이내에 발생한 전환 데이터만 유효한 전환으로 처리하여 보고서를 통해 제공드리고 있으므로 광고주님 자체 서버에서 집계하시는 지표와는 차이가 발생할수 있습니다. 참고로 전환의 경우 무효클릭에서 발생한 전환도 유효 전환으로 집계하고 있습니다. (예를 들어 광고 성과 보고서상 전환수가 클릭수보다 큰 경우도 발생 가능합니다.)

마지막으로 말씀 주신 추적 기능은 자체적으로 전환이나 클릭을 측정하실때 유용한 기능이며 네이버로 부터 유입된 트래픽 (그리고 어떤 광고로 부터 유입된 트래픽)인지 여부를 명확하게 파악하시는데 도움이 될수는 있으나 앞서 말한 측정 기준으로 인한 값의 차이가 발생할수 있는 가능성은 항상 존재하므로 상호간 차이를 줄이는데 크게 도움이 된다고 말씀드리기는 어렵습니다.

감사합니다.
