### ISSUE TITLE
XMLHttpRequest error 관련 문의

### ISSUE THREAD

**Issue by enfshin** [naver/searchad-apidoc#558]
안녕하세요. flutter를 통해서 네이버광고 API를 이용하는 모바일 앱과 웹을 만들고 있는 중입니다. 
모바일 앱에서는 api request가 전부 정상적으로 작동하는데 웹에서는 아무것도 안되서 문의드립니다.

제가 초보여서 그런지 모르겠지만, 
![image](https://user-images.githubusercontent.com/58045951/142591151-789abc28-4683-41a2-a033-69479aa41884.png)
api request를 하면 XMLHttpRequest error 같은 에러를 받습니다.

구글링에서는 웹 브라우저는 CORS로 인해 이런 답변이 오는게 정상이라고 server side에서 header를 추가하면 가능하다는데
네이버 광고 API는 제가 수정 가능한 서버가 아니니깐요.. 
혹시 해결 방법이 있나요? 
모바일 앱에서는 모든 API기능이 정상 작동합니다.  테스트용 브라우저는 크롬입니다.
웹과 연결된 node.js나 다른 backend를 만들어야만 가능한가요?

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

검색광고 API는 공식 광고관리 웹을 통해 API 사용 라이선스와 키를 발급받아 개발해서 이용해 주시기 바랍니다.
비공식적인 루트나 요청부하로 API 사용시 서비스 이용 제재 대상이 될 수 있으며
상세한 이용 가이드는 해당 'API 사용 관리' 페이지 신청 중 안내되는 내용을 참고하시기 바랍니다.

**Comment by enfshin** [comment]
네이버광고에서 도구 - API 사용관리 에서 받는 customer_ID, 액세스라이선스, 비밀키를 말씀하시는건가요? 그거라면 이미 발급받아서 잘 사용하고 있습니다. 
http://naver.github.io/searchad-apidoc/#/guides 
이 사이트도 잘 참고하여 검색광고API를 잘 사용하고 있습니다. 
flutter 모바일 앱, 데스트탑 앱에서는 모든 API request가 정상 작동합니다.

그런데 flutter로 웹사이트를 만드는 중인데 웹에서만 API 호출이 안되고 XMLHttpRequest 에러가 나서 문의 드린겁니다.
XMLHttpRequest 에 대하 내용도 apidoc에 있는건가요??

**Comment by naver-searchad** [comment]
@enfshin 
네 cors 오류는 api key를 사용하더라도 브라우저에서 직접 사용시 발생할 수 있을 것 같습니다.
클라이언트 웹을 통헤 api를 사용하실 경우 라이선스와 인증키가 노출될 우려가 있으니
서버 앱을 통해 검색광고 api에 접근해 주시길 바랍니다.
