### ISSUE TITLE
TrackingMode 의 Value 값 관련 질문입니다.

### ISSUE THREAD

**Issue by BlossomWhale** [naver/searchad-apidoc#559]
제공된 api docs에 따라,

trackingMode에는 'TRACKING_DISABLED', 'AUTO_TRACKING_MODE', 'PASS_THROUGH_SITE_MODE' 가 있다는것을 인지하고 있습니다.

'PASS_THROUGH_SITE_MODE'의 경우 trackingUrl에 명시한 uri를 통과하여 엔드포인트에 도달하게끔 유도된다는것은 인지가 되나,

'AUTO_TRACKING_MODE'에 관해서는 어떤 일이 수행되는지 알기 어렵습니다.

혹시 관련한 docs를 제가 찾지 못하고 있다면 해당 docs url이나,

부연설명이 가능할까요?

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

AUTO_TRACKING_MODE의 경우 사용자의 클릭이 광고주사이트로 전달이 될때 미리정의된 파라미터를 같이 전달해 주는 기능입니다.

아래 공지사항을 참고 부탁드립니다.
https://saedu.naver.com/notice/view.naver?notiSeq=2793&catg=&fixYn=N&searchOpt=all&keyword=추적기능

감사합니다.

**Comment by BlossomWhale** [comment]
감사합니다 해결되었습니다
