### ISSUE TITLE
Estimate: get (exposure minimum bid)에서 간간히 socket exception, connection reset이 발생합니다.

### ISSUE THREAD

**Issue by younseunghyun** [naver/searchad-apidoc#56]
안녕하세요.

Estimate: get (exposure minimum bid)의 api를 type을 id로 하여 요청하고 있습니다.

해당 api를 사용하는데 있어서, 간간히 socket exception, connection reset이 발생하고 있습니다.

해당 exception이 발생하는 원인이 있는 건지, 일시적인 장애로 인해서 발생하는 것인지 궁금합니다.

감사합니다.

**Comment by younseunghyun** [comment]
추가적으로 발생 한 에러 첨부합니다.
Connect to bidtool.ncc.navercorp.com:8080 [bidtool.ncc.navercorp.com/10.99.163.31] failed: connect timed out

**Comment by naver-searchad** [comment]
안녕하세요.
금일 14시50분 경부터 15시 20분 사이에 내부 서버 문제로 응답이 원할하지 않았습니다.
그 외시간에 발생한 오류는 TransactionId 를 남겨주시면 확인 후 답변드리도록 하겠습니다.

**Comment by younseunghyun** [comment]
socket exception의 경우  Transaction id가 null으로 오고 있습니다.

방금 socket exception, connection reset이 발생 하였습니다. timestamp 값은 1494232911009이었습니다.
