### ISSUE TITLE
11월27일 STAT REPORT 등록 이슈 확인 요청 {"code":20007,"message":"해당 일자 지표 준비중입니다."} 

### ISSUE THREAD

**Issue by choics** [naver/searchad-apidoc#561]
11월 27일 리포트 데이터 요청에서 아직까지도
{"code":20007,"message":"해당 일자 지표 준비중입니다."} 
해당 에러 발생중입니다.

빠른 확인 요청 드립니다.

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 API 담당자입니다. 

우선 업무에 불편을 드린점 사과 말씀드립니다. 

전일인 11월 28일 지표 생성에 지연이 발생하여 
STAT-REPORT의 11월 27일자 보고서는 14시 31분 부터, 
STAT의 보고서 11월 27일자 지표는 14시 40분 부터  제공이 되었으며 
STAT의 보고서  11월 28일자 당일 시간대별 지표는 14시 48분 부터 07시대를 시작으로 순차적으로 제공 되었습니다. 
제가 전일 개인적인 사유로 상황을 금일 오전에야 인지하게 되어 전일 공지나 답변을 드리지 못하였습니다.
이점 역시 사과의 말씀 드립니다. 

감사합니다.
