### ISSUE TITLE
대용량 보고서  Fix 시점에 대해서 질문 드립니다!!!

### ISSUE THREAD

**Issue by ChanghwanK** [naver/searchad-apidoc#562]
안녕하세요 문의할 내용이 예를 들어 설명하는 것이 좋을 것 같아서 예를 들어 설명 드리겠습니다. 

예를 들어 제가 11.30일에 대해서 대용량보고서 생성을 했고 해당 보고서의 내용으로 특정 작업을 한다고 가정하겠습니다. 이 때 제가 염려되는 점은 11.30일날 생성한 보고서의 내용이 추후에 변경될 일이 없는지 궁금합니다. 제 생각에는 부정 집계, 집계 미스 등의 이유로 세부내역이 변경될 여지가 있을 것 같은데 유효성을 언제까지 검토하고 Fix 되는지 궁금합니다.!!

쉽게 말하면 11.30날 집계가 끝난 대용량 보고서를 어떤 이유에서든 앞으로 12월01일에 생성하든 12월02일에 생성하든 12월 30일 생성하든 내용이 달라질이 없는지 궁금합니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

대용량 다운로드 보고서(STAT-REPORT)의 지표들은 시스템 점검이 없는 경우 매일 06시 이전(KST 기준)에 생성되며 한번 생성되면 임의로 변경되지 않습니다.
단, 장애나 지표 오류 등 여러가지 이유로 재 집계를 하는 경우도 드물지만 존재하며 이런 경우에는 공지를 드리고 있습니다.

일반 보고서(STAT)의 경우는 일중 지표와 전일까지의 과거 지표로 나뉘는데요. 일중 지표의 경우 일중 계속 업데이트 되다가 일자가 변경된 후 일정 시간 (정검이 없는 경우 통상 다음날 06시-KST 기준)이 지나면 확정된 값으로 고정되며 이렇게 과거 지표가 되면 변경 되지 않습니다.
그러나 일반 보고서 역시 여러가지 이유로 재집계를 하는 경우가 존재하며 이 경우에도 대용량 다운로드 보고서와 동일하게 공지를 통해 이 사실을 고지 하고 있습니다.

공지 게시판 : https://naver.github.io/searchad-apidoc/#/notice
공지 및 릴리즈 노트 RSS : https://naver.github.io/searchad-apidoc/feed.xml

지표 재생성 혹은 변경에 대한 공지 있는 경우 공지에 고시된 대상 일자에 대용량 보고서를 다시 생성하시어 다운로드(일반보고서의 경우 다시 조회하여) 받으시기를 부탁드립니다.
