### ISSUE TITLE
keywordstool 로 연관검색어 요청 시 Response 에 body 내용이 없습니다.

### ISSUE THREAD

**Issue by ParkChanghoon** [naver/searchad-apidoc#563]
안녕하세요,

연관검색어 추출 App 을 구현하고자, 검색광고 API 사용신청 후,
python sample code 로 테스트를 해보고 있습니다.

def GetHeader(method, uri, api_key, secret_key, customer_id):
  signature_ = signaturehelper.Signature.generate(timestamp_, method, uri, G_SECRET_KEY)

  ret_ = {
    'Content-Type': 'application/json; charset=UTF-8',
    'X-Timestamp': timestamp_,
    'X-API-KEY': G_API_KEY,
    'X-Customer': str(G_CUSTOMER_ID),
    'X-Signature': signature_
  }

  return ret_

uri = '/keywordstool'
method = 'GET'

r = requests.get(
  G_BASE_URL + uri+'?hintKeywords={}&showDetail=1'.format('커피'),
  headers=GetHeader(method, uri, G_API_KEY, G_SECRET_KEY, G_CUSTOMER_ID)
)

print(r)

request.get 으로 Header 와 parameter (hintKeywords, showDetail) 를 채워서 요청 시,
r 의 내용이 없습니다.

print 로 확인 시 <Response [200]> 만 확인되는데,
어떤 경우인지 답변주실 수 있을까요?

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

올려주신 내용만으로는 정확히 파악이 어렵지만,
일단 hintKeywords로 사용하신 한글이 url encoding이 되고 있는지 확인이 필요해 보이고
encoding 문제가 맞는지 확인을 위해 적당한 영문 키워드로 먼저 테스트해 보시는 것도 좋을 것 같습니다.

**Comment by ParkChanghoon** [comment]
영문으로 coffee 로 확인해 보아도 결과는 동일하네요.

**Comment by naver-searchad** [comment]
@ParkChanghoon 
응답 헤더의 x-transation-id값을 첨부해 주시면 실제 어떻게 request가 들어왔는지 확인이 가능할 것 같습니다.
