### ISSUE TITLE
/stat-reports request JSONDecodeError 문의

### ISSUE THREAD

**Issue by enfshin** [naver/searchad-apidoc#564]
안녕하세요. 파이썬으로 /stat-reports 를 테스트 중인데
```
uri = '/stat-reports'
method = 'GET'
r = requests.get(BASE_URL + uri, headers=get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID))
print(r.json())
```

하면 아래와 같은 에러가 나옵니다.
`json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

/stat-reports 는 response가 json이 아닌가요??? 그럴리는 없을텐데.. json 에러가 나와서 문의합니다.

다른 모든 api 기능은 정상적으로 사용하고 있습니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

api에 이상이 있는 상황은 확인되지 않고 있습니다.
요청에 어떤 문제가 있을지에 대해서는 올려주신 내용만으로는 확인하기가 어렵습니다.
실제 http 요청이 어떻게 전송되고 응답이 되는지 확인이 필요합니다.
상세 확인이 어려우시면 응답의 x-transaction-id 값이라도 확인해 주시면 좋을 것 같습니다.

감사합니다.

**Comment by enfshin** [comment]
'X-Transaction-ID': 'BTRC7DJJHHG2I'
이걸 알려드리면 될까요?

**Comment by naver-searchad** [comment]
@enfshin 
네 확인에 다소 시간이 소요되었습니다.

요청하신 tid의 경우 생성된 리포트가 없기 때문에 응답 내용이 empty로 확인되었습니다.
다만 이 api 응답에서 스펙상 empty의 경우 빈 array가 맞겠으나 현재는 "" 이 리턴되는 것으로 확인되었습니다.
아마도 이부분 때문에 json 오류가 발생하신 게 아닌가 추측됩니다.
이 점 감안해서 확인해 보시면 되겠습니다.

감사합니다.

**Comment by naver-searchad** [comment]
@enfshin 
네 확인에 다소 시간이 소요되었습니다.

요청하신 tid의 경우 생성된 리포트가 없기 때문에 응답 내용이 empty로 확인되었습니다.
다만 이 api 응답에서 스펙상 empty의 경우 빈 array가 맞겠으나 현재는 "" 이 리턴되는 것으로 확인되었습니다.
아마도 이부분 때문에 json 오류가 발생하신 게 아닌가 추측됩니다.
이 점 감안해서 확인해 보시면 되겠습니다.

감사합니다.

**Comment by enfshin** [comment]
그럼 POST 에서 Internal Server Error가 나오는 이유는 뭐일까요? 여러 방법으로 시도해도 Internal Server Error가 나오던데
```
uri = '/stat-reports'
method = 'POST'
params = {"reportTp": "AD_DETAIL", "statDt": "20211201", }, 
r = requests.post(BASE_URL + uri, params=params, headers=get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID)) 
print(r.status_code) 
print(r.json()) 
## 'X-Transaction-ID': 'BTSNQLBF9DJQ7'
```

제가 혹시 잘못 요청하거나 잘못 이해한게 있을까요?
