### ISSUE TITLE
Adgroup Master-report 응답값 문의

### ISSUE THREAD

**Issue by flygil** [naver/searchad-apidoc#565]
Adgroup Master-report 응답이 탭으로 구분된 문자열로 들어오는데요.
특정 그룹은 탭 갯수가 한개 더 많아서 파싱시에 오류가 발생하네요.
확인좀 해주실 수 있을까요?

job id : 18BAFFB76C895ED97C41657A6BF59C43 입니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

해당 그룹 이름에 '탭' 문자가 들어가 있는 것으로 의심되므로
광고시스템이나 그룹수정 api를 통해 수정 후 이용하시면 될 것 같습니다.

**Comment by flygil** [comment]
그룹이름에 탭 문자 들어가 있네요~ 수정했습니다. 감사합니다.

근데 제 생각에는 그룹이름에 탭 문자는 입력되지 않도록 수정하면 좋지 않을까 생각합니다.

**Comment by naver-searchad** [comment]
@flygil 
해당 문제가 발견된 지는 꽤 지났는데 아직 개발일정상 진행되지는 못하고 있는 것 같습니다.
어려운 수정사항은 아니므로 향후 패치는 어렵지 않을 것입니다.
의견 주셔서 감사합니다.
