### ISSUE TITLE
/stats 전환 데이타 관련 문의드립니다.

### ISSUE THREAD

**Issue by dhmoon91** [naver/searchad-apidoc#566]
안녕하세요, ad-api를 사용해 보통 보고서 항목에있는 데이터를 가져올라하는데요, 

테스트를 해보앗는데 **/stat** endpoint에서는
`전환수, 전환매출, 전환율, 전환비용`밖에 없는건가요? 

아래 이미지에있는 항목들 - 디테일 한 전환관련 데이터(eg; `직접전환수` `간접전환수` `직접전환매출액` `간접전환매출액`, etc)를 어디서 가져올 수 있는지 궁금합니다.

![image001](https://user-images.githubusercontent.com/6810688/147854542-9ae860a5-7dd3-4601-9dce-a7c64a080d05.jpg)

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

stat-reports api를 확인해 보시면 좀 더 상세한 리포트 유형(전환 포함)들을 확인해 보실 수 있습니다.
http://naver.github.io/searchad-apidoc/#/tags/StatReport

**Comment by dhmoon91** [comment]
@naver-searchad 감사합니다. 
/stat-reports로 리퀘스트를 해보앗는데 code는 200로 success 나오는데 돌아오는 데이터는 아무것도 없습니다.

array로 `downloadUrl` `reportJobId`등등이 돌아와야되는거 아닌가요?

어떤경우에 empy가 돌아오나요? 현재 postman으로 테스트중인데 이미지 첨부합니다. 
![Screen Shot 2022-01-02 at 8 56 54 PM](https://user-images.githubusercontent.com/6810688/147895251-361494c6-fe99-40ce-a1dd-3843e9e791bf.png)

**Comment by naver-searchad** [comment]
@dhmoon91 
stat-report는 명시적인 생성 요청에 의해 만들고 조회하는 api 입니다.
먼저 post 요청으로 원하시는 report type을 create 하신 뒤 list로 조회해서 생성이 완료된 걸 확인하시고
해당 jobid로 get 요청하시면 되겠습니다.
참고로 생성된 리포트가 일정수 이상이 되면 더이상 생성이 되지 않으므로
필요없이진 리포트는 명시적으로 delete 해주시기 바랍니다.

**Comment by dhmoon91** [comment]
@naver-searchad 감사합니다. 생성하고 다운로드 가능 확인했습니다.
마지막으로

1) 다운되는 파일이 .tsv파일인데 혹 .xlsx나 .csv또는 raw json format으로 요청 가능한가요?

2) `AD`리포트를 `statDt: 2021-10-31`에 대하여 보니 2000row가 넘는 데이터가 있는데요, 이 리포트는 해당 날짜(statDt)에 대한 **모든 광고캠페인**에 대한 데이터가 포함되는것이 맞나요?

3) 리포트를 만들때 statDt에 명시되어있는 날짜에대한 리포트만 만들수 있나요? 혹 날짜 `range`로 aggregate된 리포트를 요청 할 수 있나요? (예: 2021-10-01 ~ 2021-10-31).

또한 광고그룹이나 캠페인 아이디를 명시하여 해당 데이터만 요청할 수 있나요? (예: `ad group id`: `grp-xxxx'에만 해당하는 데이터 요청)

4) https://github.com/naver/searchad-apidoc/wiki/FAQ-stat#q-stattype-%EC%9D%84-%ED%86%B5%ED%95%B4%EC%84%9C-%EC%A0%9C%EA%B3%B5%EB%90%98%EB%8A%94-%EB%B3%B4%EA%B3%A0%EC%84%9C-%EC%A2%85%EB%A5%98 이곳에 명시되어잇는 `항목별 기간`의 뜻이 무엇인가요? 제가 이해한바로는 현 날짜기준 - `항목별기간`동안의 데이터만 리포트 추출 가능하다는것인데 - 맞나요? 
예) `AD_CONVERSION_DETAIL`의 리포트는 현 날짜기준 -45일까지 추출 가능.

감사합니다!

**Comment by naver-searchad** [comment]
@dhmoon91 
1. 불가합니다.
2. 네 맞습니다.
3. api document에 명시된 대로만 이용 가능합니다.
4. 네 이해하신 내용이 맞습니다.
