### ISSUE TITLE
Dart 요청 시 invalid-signature 문의

### ISSUE THREAD

**Issue by whdcks4904** [naver/searchad-apidoc#567]
test sample url 인 https://api.naver.com/customer-links?type=MYCLIENTS 에 요청할 때는 코드 200에 [] return 값을 리턴 받는데 다른 url 요청할 때마다 {"signature":"생략","title":"Invalid Signature","detail":"Signature '생략' is invalid.","status":403,"type":"urn:naver:api:problem:invalid-signature"} 의 값을 받습니다. 테스트 코드는 왜 정상 작동 하나요?

아래는 signature 생성 코드 입니다.
`
String  generate(int timestamp,String method,String uri,String secretKey){
  String message = "$timestamp.$method.$uri";
  List<int> secretBytes = utf8.encode(secretKey);
  List<int> messageBytes = utf8.encode(message);
  var hmac = new Hmac(sha256, secretBytes);
  Digest digest = hmac.convert(messageBytes);
  String base64Mac = base64.encode(digest.bytes);
  return base64Mac;
}

Map<String,String> getheader(String method,String uri,String apiKey,String secretKey,String customerId){
  int timestamp = DateTime.now().millisecondsSinceEpoch;
  String  signature = generate(timestamp, method, uri, secretKey);
  return {"Content-Type": "application/json; charset=UTF-8", "X-Timestamp": "$timestamp", "X-API-KEY": "$apiKey", "X-Customer": "$customerId", "X-Signature": "$signature"};
}
`

**Comment by yunseong3736** [comment]
> 안녕하세요, 네이버 검색광고 API입니다. 해당 문의는 다른 채널을 통해 답변이 된 것으로 보입니다.

어디에 답변이 되었는지 알려주실 수 있나요????
