### ISSUE TITLE
키워드 입찰가 변경을 하려고 하는데, 권한 없음 오류가 발생하는 이유가 궁금합니다.

### ISSUE THREAD

**Issue by jjeonsangwon** [naver/searchad-apidoc#568]
안녕하세요.
다름이 아니라 특정 계정의 키워드 입찰금액을 API를 통하여 변경하려고 하는데 1006 코드가 발생합니다
해당 API-Key로 캠페인, 광고그룹, 키워드 정보 조회는 가능하나 키워드 입찰가 변경을 하려고 하니 1006 코드가 발생하네요.
해당 코드가 발생 하는 이유가 뭔지 궁금합니다.

운영 권한, API-Key 설정은 이상 없는 것으로 확인하였습니다.

response 중 일부입니다.

    X-Timestamp 1645757982020
    X-API-KEY 0100000000b32fb669acbba143f252ba1c0d951b63813526fcb8de601038c6c64f09453ea4
    X-Customer 321229
    X-Signature nB1zrW3uxJgRgxdbAFWYw/m71qzJc0rksVNbaeWN4Oc=
    X-Transaction-ID:BV5R8UAK9HIN2
    {"code":1006,"status":403,"title":"No permission. Please check permissions granted to the account."}

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

사용하신 manager id의 사용권한이 `성과조회/로그분석`으로 확인됩니다.
즉 입찰가 변경 등 일반적인 광고관리 권한이 없어 응답된 내용입니다.

**Comment by jjeonsangwon** [comment]
> 안녕하세요, 네이버 검색광고 API입니다.
> 
> 사용하신 manager id의 사용권한이 `성과조회/로그분석`으로 확인됩니다. 즉 입찰가 변경 등 일반적인 광고관리 권한이 없어 응답된 내용입니다.

담당자에게 해당 내용 전달 드리겠습니다.
답변 주셔서 감사합니다.
