### ISSUE TITLE
php /stats get by id에서

### ISSUE THREAD

**Issue by zlzl789** [naver/searchad-apidoc#569]
breakdown 의 hh24를 활용하여 시간대별 광고현황을 만들고싶은데
timeRange 의 {"since":"YYYY-MM-DD","until":"YYYY-MM-DD"} 형식을 쓸수있는 방법이나 코드가 있다면 알고싶습니다.
datePreset의 today등은 잘 되는데 특정날짜를 달력에서 선택해서 그 값만 추출하는방법을 알고싶습니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

wiki 의 stat faq 부분을 참고하시면 될 것 같습니다.
https://github.com/naver/searchad-apidoc/wiki/FAQ-stat#q-timerange-%EA%B8%B0%EC%A4%80-%EB%B2%94%EC%9C%84
