### ISSUE TITLE
네이버 서치 애드로 키워드 광고의 stats를 확인하기 위해 테스트를 하다가 'Internal Server Error'로 접근이 불가능해졌습니다

### ISSUE THREAD

**Issue by Choi-jun9803** [naver/searchad-apidoc#570]
stats 엔드포인트로 키워드 광고의 성과 보고를 데일리로 받아 보려는 기능을 개발하기 위한 테스트 도중, 
{'timestamp': 1646009869159,
 'status': 500,
 'error': 'Internal Server Error',
 'exception': 'java.lang.IllegalArgumentException',
 'message': 'Map has no value for \'"id"\''}
 이와 같은 에러 메세지가 뜨고 있습니다.

아마 너무 많은 수의 api call을 보내서 위와 같은 이슈가 생긴 것 같은데, 발생원인과 해결 방법에는("ids"에 해당하는 리스트 값의 길이를 10으로 제한한다던가) 무엇이 있을지 공유 부탁드립니다.

감사합니다.

**Comment by Choi-jun9803** [comment]
아직 답변을 안 해주셨는데 빠른 답변 부탁드립니다!!

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

해당 오류는 검색광고 api에서 응답한 내용이 아닌 것으로 보이는데요
좀 더 정확한 파악을 위해 응답 헤더의 transaction id를 첨부해 주시면 좋을 것 같습니다.

**Comment by Choi-jun9803** [comment]
{'timestamp': 1646614719709, 'status': 500, 'error': 'Internal Server Error', 'exception': 'java.util.regex.PatternSyntaxException', 'message': 'Illegal character range near index 11\n\\Q?\\E( "[\'nkw-a001-01-000003474399048\']", "fields": "[\'impCnt\', \'clkCnt\', \'ccnt\', \'viewCnt\', \'salesAmt\']", "datePreset": "yesterday")\n           ^'}
{'Content-Type': 'application/json; charset=UTF-8', 'X-Timestamp': '1646614719199', 'X-API-KEY': '0100000000bafc61a7e6d98a2823aadabace22af386c97266b341dd15678c31351fdf41a89', 'X-Customer': '1121314', 'X-Signature': b'YPciodJbJ+mGCAh70gMp0gn4z7o4TZJdB/MmJBq6xOc='}

해당 값을 보내드리면 될까요?? 답변 감사합니다

**Comment by naver-searchad** [comment]
@Choi-jun9803 
본 지면은 public 영역이므로 인증키 관련 부분을 노출하시면 안됩니다. 제가 임의로 올려주신 내용을 수정하였습니다.

올려주신 정보는 request 내용이구요,
해당 request가 네이버 검색광고 서버까지 정상적으로 들어왔다면 네이버 검색광고 서버에서 500 오류가 발생했더라도
응답된 response의 헤더에 x-transaction-id 가 있을 겁니다.

**Comment by Choi-jun9803** [comment]
{'Connection': 'close', 'Content-Type': 'application/json;charset=UTF-8', 'Date': 'Mon, 07 Mar 2022 00:58:39 GMT', 'Strict-Transport-Security': 'max-age=15768000'}
수정 감사합니다!
해당 부분이 맞을까요? 파이썬 리퀘스트를 사용하고 있고, response.headers로 받아왔습니다

**Comment by naver-searchad** [comment]
@Choi-jun9803 
정상적인 검색광고 응답이라면 다음과 같은 형태로 되어야 합니다.
(참고 이슈 #568 )
```
X-Timestamp 1645757982020
X-API-KEY xxxxxxxxxxxxx
X-Customer 321229
X-Signature xxxxxxxxxxxxx
X-Transaction-ID:BV5R8UAK9HIN2
{"code":1006,"status":403,"title":"No permission. Please check permissions granted to the account."}
```

**Comment by Choi-jun9803** [comment]
/ncc/campaigns response : 
{'Expires': 'Thu, 01 Jan 1970 00:00:00 GMT', 'Connection': 'close', 'Cache-Control': 'no-store, must-revalidate', 'Keep-Alive': 'timeout=60', 'X-Transaction-ID': 'BVC86V5N1HJPL', 'Content-Type': 'application/json;charset=UTF-8', 'Date': 'Mon, 07 Mar 2022 01:45:55 GMT', 'Strict-Transport-Security': 'max-age=15768000'}

 /stats response : 
{'Connection': 'close', 'X-Transaction-ID': 'BVC86V6919IUU', 'Content-Type': 'application/json; charset=UTF-8', 'Date': 'Mon, 07 Mar 2022 01:45:55 GMT', 'Strict-Transport-Security': 'max-age=15768000'}


캠페인 목록을 불러오는 엔드포인트에 대한 응답은 말씀하신대로 X-Transaction-ID가 잘 불러와지는데, 
stats 엔드포인트에 대한 응답은 그렇지가 않아서 해당 응답의 X-Transaction-ID를 알 수 없습니다. 혹시 어떤 문제로 해당 값이 표출되지 않는지 알 수 있을까요??

**Comment by naver-searchad** [comment]
@Choi-jun9803 
만들어진 request url 전체를 공유해 주시기 바랍니다.
다음과 같은 형태로 만들어져야 합니다. (url encoding된 문자는 무시해 주세요)
```
api/stats?fields=[%22clkCnt%22,%22impCnt%22,%22salesAmt%22,%22ctr%22,%22cpc%22,%22ccnt%22,%22crto%22,%22convAmt%22,%22ror%22,%22cpConv%22,%22recentAvgCpc%22,%22recentAvgRnk%22,%22avgRnk%22,%22pcNxAvgRnk%22,%22mblNxAvgRnk%22,%22viewCnt%22]&timeIncrement=allDays&datePreset=last7days&ids=nkw-a001-01-000000000974967,nkw-a001-01-000000000974959,nkw-a001-01-000000000993046
```
참고로 복수의 id 조회용 parameter명은 id가 아니라 ids이며, listing 형태도 fields와는 다르게 []가 아닌 그냥 콤마 separating 입니다.

**Comment by Choi-jun9803** [comment]
naverSA_baseURL = "https://api.naver.com"
naverSA_report_uri = '/stats'
naverSA_idsList = ['nkw-a001-01-000003474399048']
naverSA_report_params = {"ids" : f"{naverSA_idsList}", 
                          "fields" : f"{['impCnt','clkCnt','ccnt','viewCnt','salesAmt']}","datePreset" : "yesterday"}


naverSA_report_response = requests.get(naverSA_baseURL + naverSA_report_uri, params=json.dumps(naverSA_report_params), headers=get_header(naverSA_method, naverSA_campaign_uri, naverSA_accessLicense, naverSA_privateKey, naverSA_customerId))

이런식으로 리퀘스트를 이용했는데 문제 없을까요? 깃허브에 올려주신 코드를 참조했습니다

**Comment by naver-searchad** [comment]
@Choi-jun9803 
저희가 코드를 상세히 봐드릴 수는 없구요,
생성된 request의 http 요청이 어떻게 나가는지 확인을 부탁드린 것입니다.
만들어지는 요청을 정상 요청 샘플과 비교해 보시면서 원인을 파악하시면 될 것 같습니다.

**Comment by Choi-jun9803** [comment]
리퀘스트 url 전문은
https://api.naver.com/stats?%7B%22ids%22:%20%22['nkw-a001-01-000003474399048']%22,%20%22fields%22:%20%22['impCnt',%20'clkCnt',%20'ccnt',%20'viewCnt',%20'salesAmt']%22,%20%22datePreset%22:%20%22yesterday%22%7D

입니다. 
제가 요청한 url과 공유해주신 예시 url간에 차이가 존재하는 것 같은데 형식이 잘못되어서 생긴 오류로 봐도 될까요??
감사합니다

**Comment by Choi-jun9803** [comment]
@naver-searchad 
리퀘스트 url 전문은
[https://api.naver.com/stats?%7B%22ids%22:%20%22['nkw-a001-01-000003474399048']%22,%20%22fields%22:%20%22['impCnt',%20'clkCnt',%20'ccnt',%20'viewCnt',%20'salesAmt']%22,%20%22datePreset%22:%20%22yesterday%22%7D](https://api.naver.com/stats?%7B%22ids%22:%20%22%5B%27nkw-a001-01-000003474399048%27%5D%22,%20%22fields%22:%20%22%5B%27impCnt%27,%20%27clkCnt%27,%20%27ccnt%27,%20%27viewCnt%27,%20%27salesAmt%27%5D%22,%20%22datePreset%22:%20%22yesterday%22%7D)

입니다.
제가 요청한 url과 공유해주신 예시 url간에 차이가 존재하는 것 같은데 형식이 잘못되어서 생긴 오류로 봐도 될까요??
감사합니다

**Comment by naver-searchad** [comment]
@Choi-jun9803 
물론입니다. 당연히 parameter 형식이 맞지 않으면 정상 동작하지 않습니다.

**Comment by Choi-jun9803** [comment]
@naver-searchad 
안녕하세요 전달 주신 url 구조를 기반으로 맞춰서 요청을 드렸는데  X-Transaction-ID는 뜨지만 데이터 값이 나오지 않아서 다시 문의 드립니다.

 /stats response : 
{'Connection': 'close', 'Cache-Control': 'no-store, must-revalidate', 'X-Transaction-ID': 'BVD127UIP9JKG', 'Content-Type': 'application/json;charset=UTF-8', 'Date': 'Tue, 08 Mar 2022 06:43:13 GMT', 'Strict-Transport-Security': 'max-age=15768000'}

 /stats url : 
https://api.naver.com/stats?fields=%5B%22clkCnt%22,%22impCnt%22,%22salesAmt%22,%22ctr%22,%22cpc%22,%22ccnt%22,%22crto%22,%22convAmt%22,%22ror%22,%22cpConv%22,%22recentAvgCpc%22,%22recentAvgRnk%22,%22avgRnk%22,%22pcNxAvgRnk%22,%22mblNxAvgRnk%22,%22viewCnt%22%5D&timeIncrement=allDays&datePreset=last7days&ids=nkw-a001-01-000003474399048,nkw-a001-01-000003474399049


{'data': [], 'compTm': '202203080149', 'cycleBaseTm': '202203070000'}

위와 같이 응답이 왔는데 혹시 X-Transaction-ID로 무슨 문제인지 트래킹이 가능할까요?

**Comment by naver-searchad** [comment]
@Choi-jun9803 
요청하신 기간 내 stat이 모두 0인 경우 empty로 결과가 나갑니다.
실적지표가 발생한 키워드 혹은 기간으로 조회하시면 되겠습니다.

**Comment by Choi-jun9803** [comment]
@naver-searchad 
감사합니다! 그런데 ids 필드의 길이 제한이나 api call의 딜레이를 줘야 하는게 있을까요??

**Comment by naver-searchad** [comment]
@Choi-jun9803 
query param들에 대한 서버측 제한은 없지만 일반적인 http call spec에서 허용되는 길이가 있을 테니 참고하시면 될 듯하구요
api call 제한은 다음 faq 항목을 참고하시면 되겠습니다.
https://github.com/naver/searchad-apidoc/wiki/FAQ#q-api-%ED%98%B8%EC%B6%9C-%EC%86%8D%EB%8F%84-%EC%A0%9C%ED%95%9C%EC%9D%B4-%EC%9E%88%EB%82%98%EC%9A%94
