### ISSUE TITLE
Ad Group Type 관련하여 질문드립니다.

### ISSUE THREAD

**Issue by mm00nn** [naver/searchad-apidoc#571]
안녕하세요.
Ad Group Type 관련하여 질문드립니다.
[http://naver.github.io/searchad-apidoc/#/tags/Adgroup](http://naver.github.io/searchad-apidoc/#/tags/Adgroup)에서 확인할 수 있는 Ad Group Type은 아래와 같습니다.

- WEB_SITE
- SHOPING
- INFORMATION
- PRODUCT
- BRAND_SEARCH
- PLACE
- CATALOG

몇 가지 Ad Group Type이 누락 되어 있는 것으로 보이는데요. Ad Group Type 전체 목록을 공유해주셨으면 합니다.
추가로, [http://naver.github.io/searchad-apidoc/#/tags/MasterReport](http://naver.github.io/searchad-apidoc/#/tags/MasterReport)에서 확인할 수 있는 Ad Group Type과의 차이를 알려주실 수 있을까요?

**Comment by naver-searchad** [comment]
@mm00nn 안녕하세요? 네이버 검색광고 API 입니다.
API 화면의 누락된 부분은 FAQ 정리가된 Wiki 페이지에서 확인이 가능합니다.

https://github.com/naver/searchad-apidoc/wiki/FAQ#q-캠페인-유형별-등록가능한-그룹-유형은-어떻게-되나요

감사합니다.

**Comment by mm00nn** [comment]
Wiki 업데이트되었음을 확인하였습니다.
빠른 답변 감사드립니다.

1. 혹시 PRODUCT 유형은 더 이상 사용하지 않는 걸까요?
2. Wiki에서 확인할 수 있는 Ad Group Type과 http://naver.github.io/searchad-apidoc/#/tags/MasterReport에서 확인할 수 있는 Ad Group Type의 차이를 알려주실 수 있을까요? 두 필드가  매칭되지 않아 질문드립니다.

**Comment by naver-searchad** [comment]
@mm00nn 안녕하세요? 네이버 검색광고 API 입니다.
* 콘텐츠 검색광고의 PRODUCT 그룹 유형은 더이상 사용되지 않습니다.
* Adgroup 유형과 Master Report의 그룹 유형의 차이는 표현의 차이입니다. (문자코드 <-> 숫자코드) wiki에 Master Report에 대응되는 숫자코드를 추가하였습니다.

감사합니다.

**Comment by mm00nn** [comment]
감사합니다 :)
