### ISSUE TITLE
보고서 개수 제한 관련하여 질문드립니다.

### ISSUE THREAD

**Issue by mm00nn** [naver/searchad-apidoc#572]
안녕하세요.
보고서 개수 제한 관련하여 질문드립니다.
Master Report와 Stat Report를 생성할 때 개수 제한이 있어 초과하여 생성하면 가장 오래된 보고서를 삭제하고 새 보고서를 생성하는 것으로 알고 있습니다.

1. Master Report와 Stat Report의 개수 제한이 어떻게 되나요?
2. API Key 기준이 맞을까요?

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

마스터리포트는 api 문서([링크](http://naver.github.io/searchad-apidoc/#/tags/MasterReport))에 보시면  
`maximum 100 jobs`라고 명기돼 있습니다.
이 때는 100개가 제한이므로 추가 등록시 자동 삭제되지 않으며 명시적으로 100개 이하로 줄이신 다음 신규 신청을 하셔야 합니다.

stat report의 경우 별도 제한수가 명기돼 있진 않은데요
동일하게 100개까지 유지가 되지만 마스터리포트와는 다르게 자동으로 가장 오래된 리포트부터 삭제가 됩니다.

그리고 api의 모든 제한이나 갯수 등은 관리기준의 단위가 되는 customer id 기준입니다.

**Comment by mm00nn** [comment]
바쁘신 중에도 빠르게 답변해주셔서 감사합니다.
