### ISSUE TITLE
/keywordstool 의 연관검색어 return 값 순서가 네이버에서 보이는 자동완성 연관검색어와 다릅니다

### ISSUE THREAD

**Issue by nonamelight** [naver/searchad-apidoc#574]
안녕하세요
/keywordstool?hintKeywords=~~ 요청시 네이버의 자동완성 부분 연관검색어와 return 값이 다릅니다.
혹시 자동완성 연관검색어와 호출하는 API가 다른것일까요?
아니면 특정 response의 value로 정렬하는것인지요

![image](https://user-images.githubusercontent.com/42472524/158028939-da852279-77e5-4f16-825e-27b0a6b2ec83.png)
![image](https://user-images.githubusercontent.com/42472524/158028994-4c881878-9d2b-468a-8fac-48f4a4ca516e.png)

dart 언어이며, 아래는 코드입니다

```
  Future<String> getRelKeywords({required String keyword}) async {
    String suburl = '/keywordstool'; // sub url
    http.Response response = await http.get(
      Uri.parse(KeyManager().baseUrl + suburl + '?hintKeywords=' + keyword),
      headers: <String, String>{
        'X-Timestamp': DateTime.now().millisecondsSinceEpoch.toString(), 
        'X-API-KEY': KeyManager().openKey,
        'X-API-SECRET': KeyManager().secretKey,
        'X-Customer': KeyManager().customerKey,
        'X-Signature': UseConn(suburl, 'GET'),
      },
    );
    return response.body;
  }
```

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

- 키워드도구에서는 파워링크 캠페인의 광고를 위한 키워드 선택을 지원하고자 연관키워드를 제공하고 있으며 네이버 검색의 자동완성과는 무관합니다.
- 문의 주신 자동완성 기능은 사용자의 관심사 기반의 자동완성으로 사용자가 누구인지, 로그인 여부에 따라서 결과가 달라진다고 합니다.
- 자동완성 기능의 자세한 사항은 아래 링크 참고하세요.
https://help.naver.com/support/contents/contents.help?serviceNo=605&categoryNo=16658&from=alias
