### ISSUE TITLE
비즈머니 API 관련 문의

### ISSUE THREAD

**Issue by 92hundredxxx** [naver/searchad-apidoc#575]
https://naver.github.io/searchad-apidoc/#/tags/Bizmoney 

네이버 API 가이드에서 현재 네이버검색 비즈머니에 대한 API 데이터를 제공하는 것으로 확인하였습니다.
소진액, 잔액 API 데이터에 네이버검색 모든 광고 상품에 대한 데이터가 포함되는건지 문의드립니다.

예를 들어 브랜드검색의 경우, 검색광고 어드민에서는 소진액에 포함되지 않는 것으로 알고 있습니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.
해당 문의는 다른 채널을 통해 답변된 것으로 확인되므로 close하겠습니다.
