### ISSUE TITLE
StatReport: create - 500에러 문의 

### ISSUE THREAD

**Issue by jy-ha** [naver/searchad-apidoc#576]
customer_id: 2414819
X-Transaction-ID: BVJHD5K91DG9I
{"code":500,"message":"Internal Server Error"}

아래 코드에서 발생합니다.
header는 정상적으로 구성했으며, StatReport: get 요청 등에서는 정상 작동 합니다.
에러의 원인이 궁금합니다.

headers = get_header('POST', '/stat-reports')
data = {
    'reportTp': 'AD', 
    'statDt': '20220317'
}
resp = requests.post(
    'https://api.naver.com/stat-reports', 
    headers=headers, 
    data=data
    )

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

api document의 statDt 스펙은 다음과 같습니다.
`statDt | string | Effective date | yyyy-MM-ddTHH:mm:ssZ (ISO8601)`
따라서 아래와 같은 형태로 입력해서 시도해 보시기 바랍니다.
`statDt: "2022-03-17T09:30:19.589Z`

**Comment by jy-ha** [comment]
빠른 답변 감사합니다.
하지만 아래와 같이 수정하였음에도 여전히 동일한 500 에러가 발생합니다.
data = {
    'reportTp': 'AD_DETAIL', 
    'statDt': '2022-03-17T09:30:19.589Z'
}

{"code":500,"message":"Internal Server Error"}
X-Transaction-ID: BVJHHH1MHHJ2U

**Comment by naver-searchad** [comment]
@jy-ha 
아 응답 포맷과 제가 헛갈렸네요.
요청 포맷은 YYYYMMDD도 유효한 게 맞습니다.
올려주신 transaction id로 확인 문의해 보도록 하겠습니다.

**Comment by naver-searchad** [comment]
@jy-ha 
request header의 contentType이
`application/x-www-form-urlencoded;charset=UTF-8`로 확인된다고 합니다.
다른 api 요청과 마찬가지로 `application/json`로 변경해서 테스트 해 보시기 바랍니다.

**Comment by jy-ha** [comment]
헤더 `application/json` 설정 후 `data = json.dumps(data)` 로 직렬화해 요청하니 정상적으로 작동합니다.
답변 감사합니다.
