### ISSUE TITLE
API 호출 속도 제한(429 Too many requests) 가 IP 당 기준인지 문의드립니다.

### ISSUE THREAD

**Issue by holyachon** [naver/searchad-apidoc#578]
안녕하세요. [위키 문서](https://github.com/naver/searchad-apidoc/wiki/FAQ#q-api-%ED%98%B8%EC%B6%9C-%EC%86%8D%EB%8F%84-%EC%A0%9C%ED%95%9C%EC%9D%B4-%EC%9E%88%EB%82%98%EC%9A%94) 에 따르면 API 호출 속도 제한이 있다고 안내되어 있는데요, 이것이 Customer ID 별로 제한하는 것인지 아니면 IP 당으로 제한하는 것인지 문의드립니다.

만약 전자라면 한 IP로 여러 Customer ID 에 대해서 동시에 호출하는 것이 원활할 것으로 보이는데 아닌 것 같아서 확인차 질문드립니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

일부 잦은 호출이 시스템에 부하를 주게 되는 operation의 경우 (대표적으로 연관키워드),
ip 기준으로도 트래픽 제한을 하고 있습니다.
429가 리턴되지 않는 수준으로 초당 호출 횟수를 조절해서 이용해 주시기 바랍니다.

**Comment by holyachon** [comment]
답변 감사드립니다.
