### ISSUE TITLE
네이버 검색광고 시스템 타켓팅 API 문의

### ISSUE THREAD

**Issue by GamjaPower** [naver/searchad-apidoc#580]
안녕하세요.

아래 공지사항으로 문의드립니다.

네이버 검색광고 시스템 타겟팅 관리 방식 변경 2차 안내
https://saedu.naver.com/notice/view.naver?notiSeq=3896&catg=&fixYn=N&searchOpt=all&keyword=

현재 저희가 아래 API를 사용하고 있는데, 위 공지사항으로 아래 API가 변경 또는 삭제되는것인가요? 아니면 그대로 유지되면서 신규 API가 생성되는것인가요?
GET /ncc/targets
PUT /ncc/targets/{targetId}

**Comment by naver-searchad** [comment]
@GamjaPower 
안녕하세요? 네이버 검색광고 API입니다.

기존 targets 관련 API는 계속 사용가능합니다. 
하지만 TIME_WEEKLY_TARGET, REGIONAL_TARGET, GENDER_TARGET, AGE_TARGET 타겟 유형은 기존 API에서 더이상 제공되지 않습니다.

위의 타겟에 대해서는 새로운 API를 이용하여 수정하거나, 입찰가중치 값을 변경하셔야 합니다.
새로추가되는 API에 대해서는 Release Note 4월 26일 부분을 확인하시면 됩니다.

감사합니다.

**Comment by GamjaPower** [comment]
@naver-searchad 
네, 답변 감사합니다. 

그러면 기존에 사용하던 /ncc/targets API에서 TIME_WEEKLY_TARGET를 사용해서 정기 점검 시 광고가 나가지 않도록 했는데, 앞으로는 이 API를 사용하지 못하고 /ncc/criterion/{adGroupId}/{dictType} API를 사용해야 겠네요. 

릴리즈 노트에 있던 sandbox api 를 확인해보니 api 기능만 사용할 수 있고 실제 테스트를 해보려면 API를 사용해서 직접 캠페인, 광고그룹등을 직접 생성해야 하네요. 
혹시 sandbox API외 UI를 사용할 수 없나요? 
있으면 테스트하는데 많은 도움이 될것 같습니다.

**Comment by naver-searchad** [comment]
@GamjaPower Sandbox 환경의 UI를 체험할 수 있는 환경은 따로 제공하고 있지 않습니다.

감사합니다.
