### ISSUE TITLE
네이버 검색광고 시스템 타겟팅 관리 방식 변경 2차 안내 - 요일별 데이터 이관 문의 

### ISSUE THREAD

**Issue by GamjaPower** [naver/searchad-apidoc#582]
안녕하세요. 

4월 26일 부터 새로운 방식의 타켓팅 방식이 운영된다고 합니다. 
저희가 TIME_WEEKLY_TARGET 타입의 타켓팅을 사용하고 있는데, 기존에 셋팅되어 있던 데이터들도 4월 26일에 같이 이관되는 것인가요? 
아니면 4월 26일에 새롭게 만들어야 하는것인가요? 
기존에는 이진값으로 구성되어 있었는데, 신규 API는 코드값으로 되어 있어서 자동으로 이관이 안될것 같아 미리 문의드립니다.

**Comment by naver-searchad** [comment]
@GamjaPower 안녕하세요? 네이버 검색광고 API입니다.
기존 타겟팅 정보는 모두 이관될 예정입니다.
감사합니다.

**Comment by aramchoi1** [comment]
신규 API는 4월 26일 자정부터 적용인것인지요?
아니면 정해진 적용시간이 있는지 알고 싶습니다.

**Comment by naver-searchad** [comment]
@aramchoi1 
안녕하세요? 네이버 검색광고 API입니다.

새로운 api의 적용은 `4월 26일 오후로 예정`되어 있습니다. 다만, 정확한 시간은 안내가 어려운 점 양해 부탁드립니다.

감사합니다.
