### ISSUE TITLE
SandBox에서 Method Not Allowed 에러 문의

### ISSUE THREAD

**Issue by GamjaPower** [naver/searchad-apidoc#584]
안녕하세요. 

SandBox에서 Target 등록을 하려고 하는데, 에러가 납니다. 

Request Method : POST

Request URL :  /api/ncc/criterion/grp-a001-01-000000000000043/SD

Request Body 
post_data = [{
       "dictionaryCode": "SDWED0009",
       "codeName": "수요일 00시부터 09시까지",
       "ownerId": "grp-a001-01-000000000000043",
       "customerId": 2091508,
       "type": "SD",
       "value": None,
       "bidWeight": 50,
       "negative": False,
       "enable": True
   }]

에러 메세지 : b'{"timestamp":1650007812235,"status":405,"error":"Method Not Allowed","exception":"org.springframework.web.HttpRequestMethodNotSupportedException","message":"Request method \'POST\' not supported","path":"/api/ncc/criterion/grp-a001-01-000000000000043/SD"}'

**Comment by naver-searchad** [comment]
@GamjaPower 안녕하세요? 네이버 검색광고 API 입니다.

신규 추가된 API는 POST method는 지원하지 않습니다.
PUT method를 사용해 주시기 바랍니다.

또한 Release note에 오류가 있어 수정되었습니다. URL path에 `/api` 부분을 제거 하시고 호출 하셔야 합니다.

**Comment by GamjaPower** [comment]
네, 답변 감사합니다. 

그러면 신규 타겟 입력과 수정 모두 PUT API를 사용하는 것이 맞는거죠? 

감사합니다.

**Comment by naver-searchad** [comment]
@GamjaPower 네 맞습니다.
