### ISSUE TITLE
신규 타겟팅 API의 BODY 내용관련 문의 

### ISSUE THREAD

**Issue by GamjaPower** [naver/searchad-apidoc#585]
안녕하세요. 

질문 1 
신규 타겟팅 API에서 노출할 시간대만 등록해주면 되는지 아니면 시간대별 노출 및 비노출 정보를 모두 등록해야 하나요? 
예) SDWED0009만 등록할 경우 그 외시간 9시 부터 그 이후 시간은 노출인지 비노출인지 그 기준을 알고 싶습니다. 

질문 2 
아래 2개 필드 값의 의미를 알고 싶습니다. 
"negative": false,
false : 노출 
true : 비노출 
 "enable": true,
true : 활성화 
false : 비활성화( negative 값이 무시되고 시스템에서 정한 기본값이 적용될것 같은데, 이때 기본값이 무엇인가요?) 

감사합니다.

**Comment by naver-searchad** [comment]
@GamjaPower 
안녕하세요? 네이버 검색광고 입니다.

* 1번 질문은 노출할 시간대만 등록해주시면 됩니다. 그외시간은 모두 `타겟팅 설정안함(노출 안함)` 상태를 가집니다.
* 2번 질문은 `negative`의 경우 `노출 안함(타겟팅 설정)`을 나타냅니다. negative의 경우 Schedule 타겟팅에서는 항상 false 값을 가집니다. 또한 지역 타겟팅의 경우 목록의 negative값이 true와 false가 동시에 설정된게 발견이 되면 오류처리가 됩니다.
* `enable`의 값이 false 일 경우에는 `타겟팅 설정안함`을 의미합니다.
