### ISSUE TITLE
criterion로 정보를 취득할때 여러 그룹에 대한 처리 확인

### ISSUE THREAD

**Issue by kaorimikage** [naver/searchad-apidoc#586]
#sandbox

현재 criterion 로 정보를 취득할때 하나의 그룹에 대해서만 정보를 취득할 수 있는것으로 보입니다.
혹시 여러 그룹에 대한 정보를 한번에 받아올 수 있는 방법은 없는지요?
현재 한번에 정보를 취득할 방법이 없다면 앞으로 지원될 계획은 있는지 알고 싶습니다.

**Comment by naver-searchad** [comment]
@kaorimikage 안녕하세요? 네이버 검색광고 API입니다.

기존 타겟팅 API에서와 같이 그룹 목록에 대한 새로운 타겟팅 조회 API는 지원이 되지 않습니다. 개별 그룹을 이용하여 새로운 타겟팅을 조회하셔야 합니다.

감사합니다.
