### ISSUE TITLE
AG쪽 API가 작동하지않는것 같습니다. label:sandbox

### ISSUE THREAD

**Issue by MunDaesik** [naver/searchad-apidoc#587]
또한 13세 이하는 타겟팅이 불가능한가요? 설정자체가되지않으며
다른 설정값과 값 비교가 불가능해서 수정부탁드립니다.

[
  {
    "dictionaryCode": "AG2529",
    "ownerId": "grp-a001-01-000000000000066",
    "customerId": 1015573,
    "type": "AG",
    "value": null,
    "bidWeight": 100,
    "negative": false,
    "enable": true,
    "delFlag": false,
    "regTm": null,
    "delTm": null,
    "editTm": null,
    "codeName": null
  }
]

HTTP/1.1 200 OK
date: Wed, 20 Apr 2022 03:27:41 GMT
content-type: application/json;charset=UTF-8
expires: Thu, 01 Jan 1970 00:00:00 GMT
cache-control: no-store, must-revalidate
referrer-policy: unsafe-url
server: nfront
Content-Length: 2

[]

**Comment by naver-searchad** [comment]
@MunDaesik 안녕하세요? 네이버 검색광고 API입니다.
온라인 맞춤형 광고 개인정보보호 가이드라인에 따라 만 14세 미만 아동에게 맞춤형 광고 제공이 불가하기 때문에 14세미만은 항상 negative값이 true입니다.

감사합니다.

**Comment by MunDaesik** [comment]
네 그부분은 인지되었습니다.

그런데 제목에 언급한 AG의 경우 값설정이 되지않는것으로보입니다.

본문의 2529 타겟에대해서요 이뿐아니라 다안되기도합니다.

**Comment by MunDaesik** [comment]
@[naver-searchad](https://github.com/naver-searchad)

네 그부분은 인지되었습니다.

그런데 제목에 언급한 AG의 경우 값설정이 되지않는것으로보입니다.

본문의 2529 타겟에대해서요 이뿐아니라 다안되기도합니다.

**Comment by naver-searchad** [comment]
@MunDaesik 안녕하세요? 네이버 검색광고 API입니다.

연령대 타겟팅의 경우 기본값이 `타겟팅 설정안함`입니다. 이경우 타겟팅 데이터가 생성되지 않으며 따로 값을 저장하고 있지 않습니다.
위에 요청하신 연령대 타겟팅의 경우 입력하신 데이터가 기본값과 같기 때문에 타겟팅 값의 변화가 없습니다. 만약 입력하신 데이터의 값을 기본값이 아닌 값으로 변경할 경우 타겟팅이 반영이 됩니다.

감사합니다.

**Comment by MunDaesik** [comment]
네 알겠습니다.
AG와 GN은 비슷하면서도 다르네요

**Comment by MunDaesik** [comment]
감사합니다.
