### ISSUE TITLE
/ncc/criterion API body 내용 문의 

### ISSUE THREAD

**Issue by GamjaPower** [naver/searchad-apidoc#588]
안녕하세요. 

샌드박스  API만 있고 UI가 없어 입력된 내용을 확인할 수 없어서 기본적인 내용임에도 불구하고 질문드립니다. 

질문 1 
PUT /ncc/criterion/groupId/SD API로 요청하면 SD(요일별 노출 스케줄)데이터만 업데이트 되는 것이 맞는 것인가요? 
Body에 bidWeight가 있더라도 동작하지 않는 것 같습니다.(동작하지 않는게 맞는 거겠죠) 

질문 2 
PUT /ncc/criterion/groupId/SD API로 요청시 필수 필드 문의 
dictonaryCode, ownerId, customerId, type  4개 필드만 입력해도 동작하는데 그외 필드는 넣지 않아도 되는 것인가요? 

질문 3 
SD type일 경우에는 negative 값은 무조건 false로 사용하는게 맞는 것이죠? 

질문 4
아래처럼 요청하면 수요일 0시부터 9시까지, 일요일 0시부터 24시까지만 노출되고 그외 시간에는 키워드가 노출되지 않는 것이죠? 

PUT /ncc/criterion/groupId/SD API로 요청
[{
  "dictionaryCode": "SDWED0009",
  "ownerId": "grp-a001-01-0000000000XXXXX",
  "customerId": 123456,
  "type": "SD"
}, {
  "dictionaryCode": "SDSUN0024",
  "ownerId": "grp-a001-01-0000000000XXXXX",
  "customerId": 123456,
  "type": "SD"
}]

**Comment by naver-searchad** [comment]
@GamjaPower 안녕하세요? 네이버 검색광고 API입니다.

1. 입력하신 dictionaryCode의 enable=true인 타겟팅만 `사용`으로 처리됩니다. 그외 입력하지 않은 dictionaryCode는 모두 사용안함 처리됩니다. 또한 입찰가중치(bidWeight)은 반영되는게 원래 의도였고, 오류가 발견되어 수정된 상태입니다.
2. 필수 필드는 dictonaryCode, ownerId, customerId, type,  enable, negative, value (RP인 경우) 입니다.
3. SD 타입의 경우 negative는 항상 false입니다.
4. `enable:true`, `negative:false`가 포함 되어야 합니다.

감사합니다.

**Comment by GamjaPower** [comment]
@naver-searchad  

답변 감사합니다. 

한가지 더 질문이 있습니다. 

1번에서 입찰가중치(bidWeight)를 입력하지 않으면 기존 값이 그대로 남아 있는 것인가요? 
아니면 기본값으로 변경되는 것인가요? 
저희는 입찰가중치(bidWeight)가 불필요해서 PUT API 사용시 BODY에 포함시키지 않을 예정입니다.

**Comment by naver-searchad** [comment]
@GamjaPower 안녕하세요? 네이버 검색광고 API입니다.
 프로퍼티에 값을 입력하지 않을경우 아래의 값을 기본값으로 설정합니다.
* bidWeight: 100
* enable: true
* negative: false
* value: null

하지만 가급적이면 API 사용자가 값을 설정하길 권고하고 있습니다.

감사합니다.
