### ISSUE TITLE
criterion api 호출 url 이 잘못되었다고 나옵니다.

### ISSUE THREAD

**Issue by chokyungho** [naver/searchad-apidoc#589]
GET 방식으로 신규 API criterion 아래와 같이  호출하면, 
https://api.naver.com/ncc/criterion/grp-a001-03-000000021272418?type=SD

아래와 같은 결과값이  나오네요.
  ["timestamp"]=>
  int(1650448223235)
  ["status"]=>
  int(404)
  ["error"]=>
  string(9) "Not Found"
  ["message"]=>
  string(20) "No message available"
  ["path"]=>
  string(46) "/api/ncc/criterion/grp-a001-03-000000021272418"

메뉴얼에 보면 아래와 같은 URL인데?
  GET /ncc/criterion/{광고 그룹 ID}?type={CriterionDictionaryType}
호출 url 이 잘못 되어 있나요?

**Comment by naver-searchad** [comment]
@chokyungho 안녕하세요? 네이버 검색광고 API입니다. 4월 1일 공지사항을 참고하시기 바랍니다. (http://naver.github.io/searchad-apidoc/#/notice)

감사합니다.

**Comment by GamjaPower** [comment]
4월 26일 부터 사용 가능한 API 이고 지금은 샌드박스에서만 사용 가능합니다.
