### ISSUE TITLE
/billing/bizmoney/cost/ 사용시 문제...

### ISSUE THREAD

**Issue by kkhkykkk** [naver/searchad-apidoc#59]
해당 api내용을 gas로 만들어서 사용중인데요...

비용 얻어오는 api를 사용하는데요..

  var params = {
    "headers" : {
      "X-API-KEY": api_key,
      "X-Customer": customer_id,
      "X-Signature": signature,
      "X-Timestamp" : timestamp
    },
    "statDt": "20170524"
  };

위와같이 statDt를 넣어줬습니다.

근데 ...

 {"title":"Bad Request","status":400,"detail":"Required String parameter 'statDt' is not present"}

위와같이 매개변수가 없다는 메시지가 돌아옵니다...

제가 매개변수명을 잘못쓴건가요?...
매개변수값이 잘못된거라면 invalid로 메시지가 나올텐데...
다른 몇몇 api는 잘 작동하는걸 확인 했습니다.

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 API입니다.

매개변수명은 statDt가 맞습니다.
위와 같이 작성하시면 queryString에 statDt가 붙는 형태인지 확인 부탁드립니다.
소진내역 API의 예시는 아래와 같습니다.
````
GET /billing/bizmoney/cost?statDt=20170629
````

**Comment by naver-searchad** [comment]
추가 문의 없으셔서 이슈 종료 합니다.  혹 추가 문의 있으실 경우 다시 오픈 부탁드립니다.
