### ISSUE TITLE
criterion api 수정가능한 부분을 알고 싶습니다.

### ISSUE THREAD

**Issue by kaorimikage** [naver/searchad-apidoc#592]
현재 릴리즈 노트에는 bidWeight 에 대한 수정 예제만 나와있습니다.
value, negative, enable 에 대한 수정은 불가능 한 것인가요?

수정 가능한 방법이 있으면 알려주십시오.

#sandbox

**Comment by naver-searchad** [comment]
@kaorimikage 안녕하세요? 네이버 검색광고 API입니다.

Release note에 설명된 `PUT /ncc/criterion/{광고그룹 ID}/{dictionary type}` API를 이용하여 수정 가능합니다.

감사합니다.

**Comment by kaorimikage** [comment]
해당방식을 사용하면 기존에 등록된 다른 설정이 지워지면서 등록됩니다.
bidWeight 처럼 기존에 등록된 설정에서 일부분만 수정하는 방법은 없는 것인지요.

**Comment by naver-searchad** [comment]
@kaorimikage 안녕하세요? 네이버 검색광고 API입니다.

입찰 가중치의 경우 동일한 값을 여러개의 타겟팅에 변경하는 기능의 사용 빈도가 높을 것으로 예상되어 별도 API로 제공이 됩니다.
나머지 프로퍼티의 경우 타겟팅 변경기능 하나로 가능할 것으로 예상되어 따로 제공되지 않습니다.

타겟팅 변경기능은 기존 타겟팅을 조회하고, 조회한 타겟팅에 원하는 프로퍼티 값을 변경하여 다시 서버로 전송하는 방식으로 사용 부탁드립니다.

감사합니다.

**Comment by kaorimikage** [comment]
답변감사합니다.
