### ISSUE TITLE
criterion API 반경관련 질문

### ISSUE THREAD

**Issue by kaorimikage** [naver/searchad-apidoc#594]
criterion-dictionary 에서 RP(반경)는 조회가 안된다고 되어 있는데  현재 생성이 되지 않아 테스트 진행이 어렵습니다.
조회할 방법이 없는 것인지요?

value 에 {"latitude":37.2691594,"longitude":126.9833165,"radius":10} (경기도 수원시 서둔동) 에 해당하는 반경 코드를
Json 형식으로 넣었는데 Incorrectly entered radius targeting. 이라고 오류가 납니다. 

radius 값에 문제가 있는가해서 1 ~ 12까지 넣어봤는데 안됩니다.

생성 예제를 알려 주실순 없으신지요?

#sandbox

**Comment by naver-searchad** [comment]
@kaorimikage 안녕하세요? 네이버 검색광고 API입니다.

반경 타겟팅의 value 프로퍼티에 입력되는 JSON의 key는 대문자로 입력 하셔야 합니다.
아래의 예제를 참고하세요.
```json
{
  "LATITUDE":35.098769,
  "LONGITUDE":128.8207528,
  "RADIUS":2
}
```

감사합니다.

**Comment by kaorimikage** [comment]
대문자로 입력했을때 500 에러가 나서 소문자로 시도했던것인데 제공해주신 위도, 경도, 범위 값을 넣으니 제대로 등록이 되네요. 

아무래도 정해진 위도, 경도값을 넣어야 하는게 아닌가 싶습니다.

**Comment by naver-searchad** [comment]
@kaorimikage 
* 위도는 -90 ~ 90 사이
*  경도는 -180 ~ 180 사이
* 반경은 1 ~ 20 사이
*  {"LATITUDE":37.2691594,"LONGITUDE":126.9833165,"RADIUS":10} 이 값으로 정상적으로 등록이 가능합니다.

**Comment by kaorimikage** [comment]
제공해주신 위도 경도 값으로는 잘 등록이 되는 것을 확인했는데 value값을 {"LATITUDE":37.2691594,"LONGITUDE":126.9833165,"RADIUS":10} 로 바꿔서 시도해본바 Array( [code] => 1005   [status] => 500   [title] => Cannot handle the request. ) 가 반환되며 등록이 안되는 것을 롹인했습니다.

**Comment by naver-searchad** [comment]
@kaorimikage 안녕하세요? 네이버 검색광고 API입니다.
 Sandbox 환경 구축하면서 반경의 순번값에 오류가 있었습니다. 다시 시도 부탁드립니다.

감사합니다.

**Comment by kaorimikage** [comment]
잘 됩니다. 감사합니다.
