### ISSUE TITLE
python / stat reports 의 상세보고서 다운로드 받는 샘플코드는 없나요?

### ISSUE THREAD

**Issue by metahong** [naver/searchad-apidoc#596]
stat reports에서 상세보고서 리스트를 가져왔는데,
reportID와 report-type에 따른 상세보고서를 가져오거나, downloadUrl을 다운로드 받을 수 잇는 샘플코드는 없을까요?

**Comment by guswnd1** [comment]
uri = '/stat-reports/'
method = 'GET'
headers=get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID)
r = requests.get(BASE_URL + uri, headers=headers)
download_url = r.json()[0]['downloadUrl']


uri = '/report-download/'
method = 'GET'
headers=get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID)
params={
    'authtoken':download_url.split('?')[-1].split('=')[-1]
}
response = requests.get(BASE_URL + uri, headers=headers, params=params)

제 경우에는 동작하였습니다.
