### ISSUE TITLE
새로운 방식의 타겟팅에서 광고그룹에 설정한 입찰가 가중치의 적용 범위에 대해서 문의드립니다. 

### ISSUE THREAD

**Issue by GamjaPower** [naver/searchad-apidoc#597]
안녕하세요. 

새로운 방식의 타겟팅에서 광고그룹에 설정한 입찰가 가중치를 200%로 설정하면 
광고그룹에 속한 키워드들에 대한 입찰가도 기존 입찰가에 2배로 설정되는것인가요? 

예를 들면 
광고그룹의 기본입찰가는 100원이고, 개별 키워드의 입찰가는 500원일때 가중치를 200%로 하면 실제 어떻게 적용되는지 알고 싶습니다.

**Comment by naver-searchad** [comment]
@GamjaPower 안녕하세요? 네이버 검색광고 API입니다.

네이버 검색광고 최종입찰가 결정로직은 아래와 같습니다.

광고 그룹은 전략의 단위이므로, 그룹 단위에서 제공 되는 모든 타겟팅 유형의 입찰 가중치를 반영하여 최종적으로 입찰에 참여합니다.
따라서, 최종 입찰가는 기본 입찰가에 각 타겟팅 유형에 부여한 입찰 가중치를 모두 곱한 결과입니다.

이 중 문의주신 소재나 키워드에 설정한 현재 입찰가가 있다면 소재 혹은 키워드 입찰가가 그룹의 기본 입찰가에 우선하므로, 소재 혹은 키워드 입찰가에 타겟팅 입찰 가중치를 반영한 값입니다.

감사합니다.

**Comment by GamjaPower** [comment]
@naver-searchad 

네, 답변 감사합니다. 

가중치로 기본값인 100을 넣으면 되는거죠?
