### ISSUE TITLE
광고그룹의 PC/모바일 타겟팅 가중치 vs 신규 추가되는 SD 타입 타겟팅의 가중치 우선 순위 또는 처리 방식 문의 

### ISSUE THREAD

**Issue by GamjaPower** [naver/searchad-apidoc#599]
안녕하세요. 

저희는 기존에 광고그룹의 PC/모바일 타겟팅 가중치를 사용하고 있습니다. 
그런데 이번에 신규 추가되는 SD 타입 타겟팅에도 가중치가 있어서 2개의 가중치가 어떻게 처리되는지 궁금합니다. 

만약 신규 추가되는 SD 타입 타겟팅에도 가중치를 설명하면 기존 광고그룹의 PC/모바일 타겟팅의 가중치가 무시되는 상황이면 심각한 문제가 생깁니다. 

신규 프로그램 배포전에 긴급하게 문의 드립니다. 

감사합니다.

**Comment by naver-searchad** [comment]
@GamjaPower 안녕하세요? 네이버 검색광고 API입니다.

문의 주신 기존 광고그룹의 PC/모바일 타겟팅의 가중치도 모두 함께 곱해집니다.

네이버 검색광고 최종입찰가 결정로직은 아래와 같습니다.
광고 그룹은 전략의 단위이므로, 그룹 단위에서 제공 되는 모든 타겟팅 유형의 입찰 가중치를 반영하여 최종적으로 입찰에 참여합니다.
따라서, 최종 입찰가는 기본 입찰가에 각 타겟팅 유형에 부여한 입찰 가중치를 모두 곱한 결과입니다.
기본 입찰가 * 타게팅(모바일/PC 가중치)1의 입찰 가중치 * 타게팅 2 입찰 가중치 …  = 최종 입찰가.

감사합니다.
