### ISSUE TITLE
RelKwdStat 샘플은 언제 추가 예정인가요?

### ISSUE THREAD

**Issue by rjpark-epe** [naver/searchad-apidoc#6]
RelKwdStat 샘플은 언제쯤 추가될까요?

**Comment by naver-searchad** [comment]
차후 추가 예정이나, 일정이 정해져있지는 않습니다.
모든 API에 대하여 샘플을 제공하지는 않으므로 API 문서 ( http://naver.github.io/searchad-apidoc/ )를 참고하여 개발을 진행하셔야 합니다.
개발을 진행하다가 궁금한 점은 이곳이나 서비스 광장을 통해 문의하시면 됩니다.
