### ISSUE TITLE
오류코드 정의 문서

### ISSUE THREAD

**Issue by rndmania** [naver/searchad-apidoc#60]
잘못된 요청에 의해 요청을 수행할 수 없는 경우 아래의 예시처럼 오류코드를 리턴 해 주고 있는데요
{"code":1014,"status":400,"title":"Cannot handle the request. The limit has been exceeded."}

오류코드 정의 문서를 
다운로드 받을 수 있는 link 공유 부탁드립니다.

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

오류 정의는 http 오류를 따르고 있어 별도로 제공 드리지 않고 있습니다. 
이해가 어려운 오류들은 별도로 문서 작업을 고려하고 있습니다.

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

Code 부분에 대한 정의 문서입니다. 
혹 Code 부분에 대한 정의가 필요하시면 아래 문서를 참고해 주시기 바랍니다.
https://github.com/naver/searchad-apidoc/blob/master/NaverSA_API_Error_Code_MAP.md

**Comment by rndmania** [comment]
감사합니다~
