### ISSUE TITLE
API /ncc/criterion/ 오픈 언제 하나요?

### ISSUE THREAD

**Issue by chokyungho** [naver/searchad-apidoc#600]
오늘이 오픈일인데, 보통 오후3-4에 한다고 하던데, 혹시 오픈했나요?
그리고 /ncc/targets 에서 더이상 요일 스케쥴 조회 못하나요?

**Comment by naver-searchad** [comment]
@chokyungho 안녕하세요? 네이버 검색광고 API입니다.
아래 공지 사항을 참고부탁드립니다.

https://saedu.naver.com/notice/view.naver?notiSeq=3905

감사합니다.

**Comment by kaorimikage** [comment]
오늘 고객센터 문의하니 예상 오픈 일정이 17시라고 했는데 내일로 연기되었습니다.
다시 문의하니 내일도 17시 예정이라고 하는데 맞는것인지요?

**Comment by naver-searchad** [comment]
@kaorimikage 안녕하세요? 네이버 검색광고 API입니다.

새로운 타겟팅의 광고주센터 및 API 적용 시점은 내일 오후 14시 ~ 19시 사이입니다.

감사합니다.
