### ISSUE TITLE
/ncc/criterion/ invalid-signature 오류

### ISSUE THREAD

**Issue by Parkjongok** [naver/searchad-apidoc#604]
동일한 코드에 
https://api.naver.com/ncc/)ncc/criterion-dictionary/SD
해당 API 를 호출하면, 정상적으로 목록이 보여지는데요.

아래 API 를 호출하면, status code : 403 이 나옵니다.
https://api.naver.com/ncc/criterion/grp-m001-01-000001028131971?type=SD

어떤 부분을 확인해 보아야 하는지요?
확인하시려면, 어떤 정보를 드려야 하나요?

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

signature 생성시 문제가 있는것 같습니다.
signature 생성시 URI를 "/ncc/criterion/grp-m001-01-000001028131971" 로 넣으셔야 할것 같은데요. 
이 부분 한번 확인 부탁드리겠습니다.

감사합니다.

**Comment by Parkjongok** [comment]
감사합니다. 말씀주신대로 하니, 제대로 나오네요.
