### ISSUE TITLE
criterion guides 언제 올라오나요?

### ISSUE THREAD

**Issue by kaorimikage** [naver/searchad-apidoc#605]
http://naver.github.io/searchad-apidoc/#/guides

에 criterion 항목이 존재하지 않습니다.
targets 항목도 live 와 내용이 달라 혼동이 올것으로 예상됩니다.

언제쯤 갱신이 될런지요.

**Comment by naver-searchad** [comment]
@kaorimikage 안녕하세요? 네이버 검색광고 API입니다. 
새로운 타겟팅에 대한 설명은 [Release note](http://naver.github.io/searchad-apidoc/#/release-notes)를 참고하시기 바랍니다.

감사합니다.
