### ISSUE TITLE
타겟팅 변경 API 사용시 500 에러(1005) 문의 드립니다.

### ISSUE THREAD

**Issue by jhahn02** [naver/searchad-apidoc#606]
안녕하세요.

타겟팅 변경 API 사용시 아래처럼 500에러가 발생하고 있는데, 어떤 문제인지 확인이 어려워 문의 드립니다.

{"code":1005,"status":500,"title":"Cannot handle the request."}`

```
...
```

입니다.

감사합니다.

**Comment by naver-searchad** [comment]
@jhahn02 안녕하세요? 네이버 검색광고 API입니다.

호출한 API 정보를 알려주시기 바랍니다.

* 메서스 명
* URL
* Parameter or Request Body 내용
* 호출 시각

감사합니다.

**Comment by jhahn02** [comment]
@naver-searchad 
안녕하세요

메서드명 : put
url : /ncc/criterion/grp-a001-01-000000027023081/SD
request body 
[{"dictionaryCode":"SDWED0009","codeName":"수요일 00시부터 09시까지","ownerId":"grp-a001-01-000000027023081","customerId":1076319,"type":"SD","bidWeight":100,"negative":false,"enable":true}]
호출시각 : 05.09 10:17

**Comment by naver-searchad** [comment]
@jhahn02 안녕하세요? 네이버 검색광고 API입니다.

광고주님이 5월 6일 생성한 스케쥴 타겟팅에 customer_id값이 0으로 입력되어 있어 데이터 보정 작업을 진행하였습니다.
자체적으로 customer_id에 대한 검증로직을 추가 할 예정이나, 서비스 반영전 customer_id가 잘못 입력될 경우 데이터 보정작업을 진행할 수 없고, 광고그룹을 삭제하여야 합니다. 이점 유의 하시기 바랍니다.

감사합니다.

**Comment by jhahn02** [comment]
@naver-searchad 

이제 정상 진행 되는 점 확인했습니다.

감사합니다!
