### ISSUE TITLE
criterion api 호출 에러

### ISSUE THREAD

**Issue by xptmxm1231** [naver/searchad-apidoc#608]
Array ( [status] => 403 [transactionId] => C0M2GVUDHHJAH  [signature] => vR6zO7aUt4d7MKGX+dgnts3Nr+AIFB2XmuXz7tE/TEw= [status] => 403 [detail] => Signature 'vR6zO7aUt4d7MKGX+dgnts3Nr+AIFB2XmuXz7tE/TEw=' is invalid. [title] => Invalid Signature [type] => urn:naver:api:problem:invalid-signature ) 

다른 API는 잘동작하는데 왜 criterion 만 서명에러가 날까요

**Comment by naver-searchad** [comment]
@xptmxm1231 
안녕하세요. 네이버 검색광고 API입니다.

주신 정보로는 정확히 파악하기 어렵지만, signature 생성시 URI 를 잘못넣으셨을것 같습니다.

https://github.com/naver/searchad-apidoc/issues/604

해당 이슈와 유사한 문제이실것 같은데요. 참고부탁드리겠습니다.

감사합니다.

**Comment by xptmxm1231** [comment]
기존 API 문서에서는 이런방식으로 써두었는데

GET /ncc/keywords{?nccAdgroupId,baseSearchId,recordSize,selector}

지금 API 문서에서는 

GET /ncc/criterion/{광고 그룹 ID}?type={CriterionDictionaryType}

이런식으로 써두어서 URI 잘못 넣은거 같네요

저 부분 수정하셨으면 좋겠습니다.

지금은 잘 동작합니다.
