### ISSUE TITLE
master-report에서 Campaign, AdGroup 문의

### ISSUE THREAD

**Issue by HiFaMi** [naver/searchad-apidoc#609]
안녕하세요. 리포트 결과값에 대해 문의 드립니다.

master-report에서 기간 설정을 진행하여 보고서를 다운로드 받았는데 같은 기간인데도 불구하고 AdGroup 리포트 값이랑 Campaign 리포트의 값이 달라 문의 드립니다.
같은 기간을 설정 했는데도 AdGroup에서 나왔던 CampaignId 값이 Campaign리포트에서 조회되지 않습니다.

**Comment by naver-searchad** [comment]
안녕하십니까 @HiFaMi 님

네이버 검색광고 대용량 다운로드 보고서 담당자입니다. 

master-report 에서 기간을 설정하게 되면 해당 기간 동안 "변경" 이 있었던 항목들만 제공 됩니다. 
따라서 말씀 주신 상황은 충분히 발생 가능한 상황입니다. 

예를 들어 캠페인 마스터를 조회 한다고 할때 
from date를 설정하지 않으면 조회 시점 기준(해당 시점은 리턴값으로 제공됩니다.) 캠페인 리스트와 각 캠페인 정보가 제공되며
from date를 설정하면 from date부터 조회 시점 까지 기간 중 변경이 있었던 캠페인 리스트와 해당 캠페인의 조회 시점 기준 현재값이 제공됩니다. 

이와 같이 기능을 분리해서 제공드리는 의도는 마스터 보고서를 전체적으로 한번 조회 하셔서 로컬DB나 서비스 DB등에 올려두고 일정 간격으로 변경 분을 계속 조회해서 계속 기존 DB를 업데이트 하여 최신화 하실수 있도록 하기 위함입니다. 

감사합니다.
