### ISSUE TITLE
소재 복사 api 호출 오류 문의

### ISSUE THREAD

**Issue by rndmania** [naver/searchad-apidoc#61]
소재 복사 api가 동작하지 않는것으로 보입니다.
(지난 주까지 잘 사용했습니다.) 

아래와 같이 호출하면
PUT /ncc/ads?ids=nad-****-**-***************&targetAdgroupId=grp-***-**-****&userLock=false

500 code가 return됩니다.
{"code":1005,"status":500,"title":"Cannot handle the request."}

확인부탁드립니다.

**Comment by naver-searchad** [comment]
복사대상 그룹은 동일캠페인 하위에서 가능합니다.
요청주시것을 보면
targetGroupId가 쇼핑검색 그룹으로 요청을 주신것 같습니다.
```
PUT /api/ncc/ads?ids=nad-a001-01-000000013377204?targetAdgroupId=grp-a001-02-000000001843854?userLock=false
```

**Comment by rndmania** [comment]
동일 캠페인이 아니더라도 동일타입(파워링크)의 캠페인이면 복사가 되는것 같은데요
동일 캠페인 내에서만 복사되는것이 맞나요?
