### ISSUE TITLE
criterion 타겟팅 변경 api 관련 문의드립니다.

### ISSUE THREAD

**Issue by jhahn02** [naver/searchad-apidoc#614]
안녕하세요.

release note에
타겟팅 변경에서 아래와 같이 안내하고 있는데

`타겟팅 변경시 Request Body에 포함되지 않는 코드는 모두 사용안함 처리가 되니 주의를 요합니다.`

실제로 테스트 해보면 지역/반경/요일 시간 변경시에는 해당 사항이 적용되나
성별/연령대 변경시에는 해당 사항이 적용되지 않는 걸로 보입니다.

의도된 내용인지, 추후 수정 예정인지 확인 부탁드립니다.

감사합니다.

**Comment by naver-searchad** [comment]
@jhahn02 안녕하세요? 네이버 검색광고 API입니다.

네이버 검색광고 광고주센터의 기능을 보시면, 성별/연령대의 경우 개별 노출/미노출 설정 기능이 있습니다. 
이 기능을 지원하기 위해 성별/연령의 경우 예외 처리를 하고 있습니다.

감사합니다.

**Comment by jhahn02** [comment]
@naver-searchad 
안녕하세요. 빠른 답변 감사합니다.

그럼 말씀하신 개별 노출/미노출 설정이 현재 API에선 지원하지 않는 걸로 보이는데,
이 기능이 추후 API에 추가 될 예정인가요? 아니면 광고주 센터를 통해서만 설정 가능한 사항인가요?

확인 부탁드립니다.

감사합니다.

**Comment by naver-searchad** [comment]
@jhahn02 안녕하세요? 네이버 검색광고 API입니다.

성별/연령대의 경우 아래와 같이 설정 가능합니다.
* 타겟팅 설정 없을 경우 `전체 노출`(성별/연령대 타겟팅 사용안함)
* 개별 `노출` : negative: false, enable: true
* 개별 `미노출`: negative: true, enable: true

요일/시간 타겟팅의 경우 아래와 같이 설정 가능합니다.
* 타겟팅 설정 없을 경우 `전체 노출`(요일/시간 타겟팅 사용안함)
* 요일의 특정 시간별 `노출`: 해당 시간대 코드의 enable: true, negative: false
* 요일의 특정 시간별 `미노출`(해당 시간 타겟팅 사용안함): 해당 시간대 코드의 enable: false, negative: false

지역/반경 타겟티의 경우 아래와 같이 설정 가능합니다.
* 타겟팅 설정 없을 경우 `전체 노출`(지역/반경 타겟팅 사용안함)
* 지역/반경별 `노출`: 해당 지역 타겟팅 코드의 enable: true, negative: false
* 지역/반경별 `미노출`(해당 지역 타겟팅 사용안함): enable: false, negative: false
* `노출 제외선택`: 해당 지역 타겟팅 코드의 enable: true, negative: true
* `노출 제외선택`과 `개별 노출` 선택을 같이 입력하실 경우 오류처리 됩니다.

감사합니다.

**Comment by jhahn02** [comment]
@naver-searchad 
안녕하세요.
답변 감사합니다.

정리해주신 내용 참고해보겠습니다.

감사합니다!
