### ISSUE TITLE
bizmoney charge 문의

### ISSUE THREAD

**Issue by okziny** [naver/searchad-apidoc#615]
안녕하세요

GET /billing/bizmoney/histories/charge{?searchStartDt,searchEndDt}

charge 와 period 모두 그런데

우선 charge 정보요청시 

    [code] => 1002
    [status] => 400
    [title] => Invalid request
    [detail] => Invalid Date Parameter

라고 뜹니다.

get 파라미터로는

Array
(
    [searchStartDt] => 20220501
    [searchEndDt] => 20220515
)

이렇게 넣어봤습니다.
혹시 파라미터 정보가 잘못된게 있을까요?

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 api입니다.

실제 api request url 내용을 확인해서 query parameter 이름과 값이 올바르게 만들어졌는지 확인해 주시기 바랍니다.
