### ISSUE TITLE
네이버 확장소재 생성시 userLock을 true로 설정하여도 false로 생성됩니다.

### ISSUE THREAD

**Issue by MunDaesik** [naver/searchad-apidoc#617]
네이버 확장소재 생성시 userLock을 true로 설정하여도 false로 생성됩니다.

![image](https://user-images.githubusercontent.com/3860835/169269761-2f08ad92-3d26-4de1-9957-c1b8858d586c.png)

**Comment by naver-searchad** [comment]
@MunDaesik 안녕하세요? 네이버 검색광고 API입니다.
광고 객체 `생성`시 사용자 잠금(userLock) 값은 false 입니다. 광고 객체 수정 API를 이용하여 변경 하시면 됩니다.


감사합니다.

**Comment by MunDaesik** [comment]
[> @MunDaesik 안녕하세요? 네이버 검색광고 API입니다. 광고 객체 `생성`시 사용자 잠금(userLock) 값은 false 입니다. 광고 객체 수정 API를 이용하여 변경 하시면 됩니다.
> 
> 감사합니다.

](http://naver.github.io/searchad-apidoc/#/operations/POST/~2Fncc~2Fad-extensions)

> @MunDaesik 안녕하세요? 네이버 검색광고 API입니다. 광고 객체 `생성`시 사용자 잠금(userLock) 값은 false 입니다. 광고 객체 수정 API를 이용하여 변경 하시면 됩니다.
> 
> 감사합니다.

http://naver.github.io/searchad-apidoc/#/operations/POST/~2Fncc~2Fad-extensions

소재가 아닌 확장소재이며 
This field can be used for ENABLED or PAUSED of the AD extension
Required입니다.
영어를 해석해보면 true와 false 둘다 선택이 가능한데 
어떤값을 입력해도 false로만 생성이 된다는 말씀이신가요?

**Comment by naver-searchad** [comment]
@MunDaesik 안녕하세요? 네이버 검색광고 API 입니다.
확장소재 생성시 `userLock` 필드의 값은 기본(false)값으로 생성이 됩니다. 수정시에는 true 또는 false를 입력 할 수 있습니다.

감사합니다.
