### ISSUE TITLE
현재 순위 관련 질문

### ISSUE THREAD

**Issue by kaorimikage** [naver/searchad-apidoc#62]
현재 키워드의 순위를 가져올 수 있는 방법이 있나요?

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 API입니다. 

현재 키워드의 순위 (에초에 광고가 노출 될때 순위가 결정 되므로 정확히 말씀 드리면 
현재 노출이 발생한다고 가정할때 노출 될 것으로 예상되는 순위) 정보는 네이버 검색광고 
서비스에서 제공드리지 않는 정보입니다.
저희도 해당 정보를 생성하거나 가지고 있지 않습니다.
