### ISSUE TITLE
삭제된 Campaign 정보 관련 문의

### ISSUE THREAD

**Issue by kjhchs2** [naver/searchad-apidoc#620]
안녕하세요. 덕분에 naver sa API를 잘 활용 중에 있습니다.
다름 아니라, '/ncc/campaigns' API를 통해서는 현재 있는 캠페인 정보들만 받을 수 있는 것으로 알고 있습니다.

1. 삭제된 캠페인의 정보를 받을 수 있는 방법이 있을까요?
2. 혹은 삭제된 캠페인을 포함한 광고 관련 정보를 얻을 수 있는 API가 있을까요? 

부족한 실력으로 며칠간 해결하지 못해, 문의를 남깁니다.
답변 주시면 감사하겠습니다!

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 대용량 다운로드 보고서 담당자입니다. 

삭제된 광고 정보들은 대용량 보고서 중 마스터 보고서(masterreport)를 통해 조회가 가능합니다. 
http://naver.github.io/searchad-apidoc/#/tags/MasterReport

마스터 보고서는 광고 정보를 파일 형태로 제공하는 서비스로 이 서비스를 통해 캠페인부터 확장소재까지 대부분의 광고 정보를 모두 조회하실수 있습니다. 
한글 스펙 문서는 아래 링크를 참고하시기 바랍니다. 
https://searchad.naver.com/File/downloadfilen/?type=10&filename=Report_MasterSpecification_02.pdf.pdf

마스터 보고서의 간략한 사용 방식은 아래와 같습니다. 
1. create method를 통해 보고서 생성을 요청하면 (이 한번의 요청 단위를 job으로 저희 서비스에서는 정의하고 있습니다)
2. API 서버는 job ID를 리턴합니다. 
3. 리턴된 job ID를 기준으로 get method를 호출하면 현재 job의 상태 및 파일을 다운로드할수 있는 url이 제공됩니다. 
4. 제공된 URL을 호출하면 파일을 다운받으실수 있습니다. 

마스터 보고서 생성 요청 시 fromtime 항목을 셋팅하지 않는 경우 보고서 생성 시점 기준 스냅샷 데이터가 제공되지만 
fromtime을 특정 시점으로 설정하시면 해당 일자 부터 현재까지 변경이 있었던 항목들만이 제공됩니다. 
이중 각 보고서의 deltm 필드에 값이 존재하는 경우 해당 항목은 삭제된 항목입니다. 

개발 작업 전 데이터를 우선 체크해 보고 싶으시다면 네이버 검색광고 시스템 --> 보고서 --> 대용량 다운로드 보고 --> 광고 정보 일괄 다운로드 탭에서 보고서를 생성하셔서 확인해 보실수 있습니다. 
참고로 해당 기능은 MASTER REPORT API를 사용하여 구성되어 있으므로 기능과 보고서 형태는 동일하며 job 리스트는 공유되고 있습니다. 

감사합니다.

**Comment by kjhchs2** [comment]
담당자님, 빠른 답변 감사합니다.

API를 통해, download 확인할 수 있는 downloadUrl을 통해 파일을 해석하고자 하는데
이번엔 invalid signature 관련 에러가 발생하네요ㅠㅠ

다른 api에 접근할 때는 관련 에러가 안뜨는데, 제공해주는 downloadUrl에 get요청을 보낼 때만 signature관련 에러가 뜨네요..
혹시 힌트가 있을까요!?

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

다운로드 호출 시 에러가 발생한 JOB ID를 와 에러 발생 시점을 알려 주실 수 있으실지요?

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다.

위 내용에서 한가지 누락된 사항이 있어 다시 글 씁니다. 
JOB ID, 에러 발생 시점과 함께 에러와 함께 헤더에 리턴된 트랜잭션 아이디로 함께 알려주시면 확인에 도움이 될수 있을것 같습니다.

그리고 저희가 리턴드린 보고서 다운로드 URI에 authtoken이 파라미터로 함께 리턴되는데요. 시그니처 생성시에는 authtoken을 빼고 생성하셨는지 체크를 한번 해봐 주시기를 부탁드립니다. 
예를 들면 sha256-hmac ( API_SECRET, timestamp + “.GET./report-download”)이런식으로 생성을 하셨는지 확인을 부탁드립니다.

감사합니다.

**Comment by kjhchs2** [comment]
친절하게 답변 주셔서 감사합니다!
과거 issue 글이나, 다른 내용들 참고하여 테스트 중에 있습니다.
최대한 해결해보고 다시 문의드리겠습니다!
정말 감사합니다 👍🏾

**Comment by kjhchs2** [comment]
JOB ID는 BA33F3C123F39C20D21E523DB6A93E40
트랜잭션 아이디는 C133G7TOHHHQK 입니다.
혹시 위의 아이디들로 관련 상태가 조회가 되나요?

이제 200 response를 받는데, 이 파일을 또 처리하는 법을 해결해야겠네요!
