### ISSUE TITLE
키워드 명으로 등록된 키워드를 찾는 기능은 없을까요?

### ISSUE THREAD

**Issue by kaorimikage** [naver/searchad-apidoc#621]
키워드 명으로 캠페인 내 등록된 동일 명칭의 키워드를 찾는 API 기능은 혹시 없는지 확인하고 싶습니다.
현재 없다면 앞으로 추가하실 계획은 있으신지 알고 싶습니다.

**Comment by kaorimikage** [comment]
@naver-searchad 확인부탁드립니다.

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 API 담당자입니다. 

말씀 주신 기능은 제공 되지 않으며 검색과 관련 된 기능은 성능 문제로 향후에도 제공이 어려울 것으로 생각 됩니다. 
단, 이와 같은 기능을 직접 구현하실수 있도록 마스터를 제공드리고 있습니다. 
물론 자체적으로 데이터를 저장하실 공간을 구현하셔야 하는 단점이이 있기는 합니다만 
계정 단위로 모든 등록 키워드를 한개 파일로 제공하므로 경우에 따라서는 이용을 고려해 보실수도 있을것 같습니다. 
(http://naver.github.io/searchad-apidoc/#/tags/MasterReport) 

감사합니다.
