### ISSUE TITLE
이번에 추가된 확장소재 추가설명 관련 에러 확인 요청 건

### ISSUE THREAD

**Issue by choics** [naver/searchad-apidoc#624]
이번에 추가된 DESCRIPTION_EXTRA 추가설명에 대한 API 등록 시 description에 대한 길이가 잘못된 것으로 확인됩니다.
추가설명이 최대 45자까지 입력가능한것으로 알고 있는데

45자를 넘지 않게 입력 후 API를 호출하여도
연장 DESCRIPTION : 입력문구의 길이가 너무 길거나 짧습니다. 입력가능범위 : [1‥14]
에러를 리턴합니다.

확인 부탁드립니다.

**Comment by ChrisPanda** [comment]
@choics 
추가설명 확장소재 requst한 정보를 github에 올려주시기 바랍니다. 해당 정보로서는 파악하기가 어렵습니다.

**Comment by naver-searchad** [comment]
@choics
추가설명 확장소재 requst한 정보를 github에 올려주시기 바랍니다. 해당 정보로서는 파악하기가 어렵습니다.

**Comment by choics** [comment]
내부 개발관련 이슈로 발생한 부분으로 해당 부분 이슈 없는 것 확인하였습니다.

감사합니다.
