### ISSUE TITLE
쇼핑검색 입찰가 변경 관련해서 문의 드립니다.

### ISSUE THREAD

**Issue by gitsimu** [naver/searchad-apidoc#625]
쇼핑검색 입찰가를 api로 업데이트 하려고 /ncc/ads 를 사용하니 업데이트가 잘 되지않아 문의드립니다.
이슈를 검색해보니 이미 비슷한 문의가 있어서 문의에 답해주신 내용대로 수행했는데 **Invalid ad type** 에러가 표시됩니다.
https://github.com/naver/searchad-apidoc/issues/232#issue-454560963

아래는 요청내용입니다. (api 키 부분은 삭제하였습니

[NAVER API ERROR] 400 Bad Request {
  request: {
    baseURL: 'https://api.naver.com',
    method: 'PUT',
    headers: {
      'Content-Type': 'application/json; charset=UTF-8',
      'X-Timestamp': 1655973007266,
      'X-API-KEY': '',
      'X-Customer': '',
      'X-Signature': ''
    },
    params: {
      adAttr: {
              bidAmt: 3000,
              useGroupBidAmt: false
            },
      nccAdId: 'nad-a001-02-000000159077515',
      fields: 'adAttr'
    },
    data: { adAttr: { bidAmt: 3000,  useGroupBidAmt: false }, nccAdId: 'nad-a001-02-000000159077515' },
    url: '/ncc/ads/nad-a001-02-000000159077515'
  },
  response: { code: 3830, status: 400, title: 'Invalid ad type.' },
  auth: {
    api: '',
    id: '',
    secret: ''
  }
}

**Comment by naver-searchad** [comment]
@gitsimu 
안녕하세요? 네이버 검색광고 API 입니다.
아래와 같이 요청해주시면 될 것 같습니다.
```
url : /api/ncc/ads/nad-a001-02-000000159077515/?fields=adAttr
body:
{
    "adAttr": {
        "bidAmt": 2720,
        "useGroupBidAmt": false
    },
    "nccAdId": "nad-a001-02-000000159077515",
    "type":"CATALOG_AD"
}
```
감사합니다.
