### ISSUE TITLE
자동입찰 키워드 실시간 순위 관련해서 문의 드립니다.

### ISSUE THREAD

**Issue by ChoiYoungWoo2197** [naver/searchad-apidoc#626]
파워링크 또는 쇼핑검색의 키워드/소재에 대해서 API를 통해 실시간 순위를 알아내는 자동입찰프로그램을 만들려고 합니다.
현재 현재순위를 알 수 있는 API를 제공하는지와 존재한다면 관련 정책이 있는지 궁금합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 API 담당자입니다. 

광고 노출 순위와 관련된 지표는 전일 및 이전 그리고 당일의 몇시간 이전(즉 과거)의 시간대별 평균 노출 순위 
혹은 이를 계산하실수 있는 데이터(순위합 및 노출수)만을 제공드리고 있습니다. 

한편 네이버 서비스와 관련된 어플리케이션을 구상 중이시라면 
아래 링크를 드린 약관을 비롯한 네이버 정책 및 약관 등을 면밀히 우선 검토해 주시기를 부탁드립니다. 

네이버 검색광고 이용 약관 : https://saedu.naver.com/adguide/policy/terms.naver
네이버 검색광고 API 이용 약관 : https://saedu.naver.com/adguide/policy/api.naver
네이버 서비스 약관 : https://policy.naver.com/policy/service.html
검색결과 수집에 대한 정책: https://policy.naver.com/policy/search_policy.html

감사합니다.
