### ISSUE TITLE
삭제된 캠페인의 campaign 정보

### ISSUE THREAD

**Issue by sonh1230** [naver/searchad-apidoc#627]
안녕하세요

삭제된 캠페인의 경우
GET /ncc/campaigns 을 통해서는 정보가 불러와 지지 않으며,
master-report에서 삭제된 시점을 포함하는 fromTime을 설정하고 파일을 다운로드 받는 방법 외에는 api통해서는 확인 할 수 없는것으로 파악됩니다.

제가 이것 저것 테스트 하다보니 /stats의 경우 삭제된 campaign의 ID로도 stat 수치가 불러와지는데,
삭제된 campaign ID를 api를 통해 얻을 수 없는 것이 불편하여 문의드립니다.
상기한 방법외에 api통해 삭제된 campaign 정보(특히 ID)를 쉽게 알아낼 수 있는 방법을 추가할 계획은 없으신지 문의드립니다.

**Comment by naver-searchad** [comment]
@sonh1230 안녕하세요? 네이버 검색광고 API입니다.

삭제된 광고데이터는 API조회시 제공하고 있지 않습니다. 삭제는 광고시스템에서 해당 데이터가 제거 됩니다.
지표의 경우도 `일정기간`만 제공이됩니다.

감사합니다.
