### ISSUE TITLE
쇼핑검색광고 API 관련 문의

### ISSUE THREAD

**Issue by 92hundredxxx** [naver/searchad-apidoc#628]
검색광고 어드민 내, 쇼핑검색광고 노출 순위별 평균 입찰가 기능을 통해
상품 카테고리(ex. 패션잡화 > 남성가방 > 클러치백) 에 따른 쇼핑검색광고 노출 순위별 평균 입찰가를 사전 조회할 수 있는 페이지를 구축해볼 수 있을지 검토 중입니다.

첨부드린 이미지에서 제공하고 있는 쇼핑검색광고_노출 순위에 따른 평균 입찰가 데이터를 API로 제공하고 계신지 문의드리며,
미제공인 경우에 제공이 가능할지도 확인 부탁드립니다.

![화면 캡처 2022-07-13 100615](https://user-images.githubusercontent.com/101625304/178626638-0ad83f73-bc8d-4027-b7a2-52dbdf594ccb.png)

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 API 담당자입니다. 

문의 주신 기능은 아래의 API를 통해 제공드리고 있습니다. 
순위별 평균입찰가 -->  [Estimate: get (average position bid) - NPLA ](http://naver.github.io/searchad-apidoc/#/operations/POST/~2Fnpla-estimate~2Faverage-position-bid~2F%7Btype%7D)

그런데 현재 구상중이신 서비스에 사용하시기는 어려울듯 싶습니다. 
해당 API의 input 인자는 네이버쇼핑 상품 ID 혹은 광고로 등록된 AD ID를 받고 있으며 이는 상품 혹은 AD 에 연결된 상품 단위로만 평균 입찰가를 계산하여 제공드리고 있다는 것을 의미 합니다. 

이와 같은 구조는 저희 쇼핑 검색광고 광고 노출 방식으로 인한 것인데요. 네이버 쇼핑 검색광고는 광고로 등록된 상품의 정보에 기반하여 네이버쇼핑검색엔진이 노출 여부를 결정하기 때문입니다. 즉 파워링크의 검색어와 같이 노출 조건을 광고주나 광고시스템이 통제할수 없습니다. 

이해를 돕기 위해 우선 쇼핑 검색광고 순위별 평균 입찰가를 계산하는 방식을 설명 드리겠습니다. 
네이버 검색광고 입장에서도 어떤 상품이 어떤 카테고리, 어떤 검색어 및 조건에  매칭 되어 노출 될지 미리 정보를 확보할수가 없습니다.따라서 저희 시스템이 여러가지 데이터를 기반으로 특정 상품이 어떤 조건에 부합하게 될지 "추정"하게 되는데요. 

1. 각 소재가 어떤 키워드(검색어) 들일때 노출될지 추정하고 
2. 추정된 키워드들 중 검색수와 상품과의 연관도가 높은 순으로 키워드 5개만 선택합니다. 
3. 선택된 키워드의 순위별 입찰가(사용자가 입력한 입찰가가 아니라 품질 지수를 반영하여 일반화한 입찰가)를 지표 기간(과거 28일) 으로 단순 평균한 값입니다. 

즉 저희가 제공드리는 값은 특정 상품의 연관도에 따라 "추정"되는 노출 가능성이 높은 검색어에 기반하고 있으므로 저희가 제공드리는 API를 이용하시더라도  카테고리별 순위별 평균 입찰가를 제공하는 서비스를 구성하시기는 대단히 어려울것으로 보입니다.  

감사합니다.

**Comment by 92hundredxxx** [comment]
안내주신 내용 중, 추가 문의가 있어 회신드립니다.

(1) 네이버쇼핑 상품 ID 혹은 (2) 광고로 등록된 AD ID를 통해 입찰가/노출 순위 산정하여 예상 견적을 제공해 주시는 것으로 안내해 주셨는데, 

API 스펙에는 'or' 이 아닌 'and' 조건으로 보여 추가 문의드립니다.
네이버쇼핑 상품id, 희망 순위만 입력하여도 평균 입찰 계산이 가능한게 맞을까요?

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 API 담당자입니다. 

메뉴얼 페이지가 좀 설명이 부실해서 and로 생각하셨을수도 있을것같습니다. 죄송합니다.
type에 id를 입력하면 네이버 검색광고 소재 아이디를 items에 넣어주시면 되고, product를 입력하시면 네이버 쇼핑 상품 아이디를 items에 넣어주시면 됩니다. 
답만 우선 말씀 드리면 네이버 쇼핑 상품 아이디와 조회대상 순위만을 입력하셔도 평균입찰가 조회가 가능합니다. 
단, 값이 서로 다를 수 있는데요. 그 이유는 품질지수의 반영 때문입니다. 
네이버 검색 광고소재 아이디를 입력하신 경우 해당 소재가 가지고 있는 조회 시점 현재의 픔질 지수를 입찰가에 반영하여 값이 리턴되며 네이버 쇼핑 상품 아이디를 입력하신 경우 최초 소재 등록시 받는 품질지수인 4단계의 품질을 반영하여 값을 리턴하게 됩니다. 

즉 이를 달리 말씀 드리면 같은 평균입찰가라도 소재의 품질지수에 따라 값이 달라진다는 것을 의미 합니다. 

감사합니다.

**Comment by 92hundredxxx** [comment]
확인 감사합니다. 이후 추가 문의는 새로운 이슈 발행하겠습니다.
