### ISSUE TITLE
{"timestamp":"1655391600000","detail":"Request has expired.","title":"Invalid Timestamp","status":403,

### ISSUE THREAD

**Issue by LeoSeoulVentures** [naver/searchad-apidoc#629]
{"timestamp":"1655391600000","detail":"Request has expired.","title":"Invalid Timestamp","status":403,

라고 뜨는데 어?떻게 해결하나요?

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 API 담당자입니다. 

API 요청시에 사용하는 timestamp 값이 잘 못되어서 발생하는 오류입니다.
(1655391600000 의 경우 2022년 6월 17일 자정의 timestamp 값으로 보이네요 )

API 요청시 해당 시점의 timestamp 값을 포함하여 요청하시면 됩니다.

감사합니다.

**Comment by LeoSeoulVentures** [comment]
그러면 API 호출 시점의 타임스탬프를 보내야 하는건가요?

**Comment by holyachon** [comment]
@LeoSeoulVentures 

> 그러면 API 호출 시점의 타임스탬프를 보내야 하는건가요?

맞습니다.

> str(datetime.now().timestamp()) 를 타임스탬프로 보내면 되나요?

https://naver.github.io/searchad-apidoc/#/samples -> `Generate Signature` 참고하시면 됩니다.
`int(datetime.datetime.now().timestamp())` 정수 형태를 보내야 할 것입니다.
