### ISSUE TITLE
Campaign creation not working

### ISSUE THREAD

**Issue by minsikzzang** [naver/searchad-apidoc#63]
`http://naver.github.io/searchad-apidoc/#/operations/POST/~2Fncc~2Fcampaigns` 문서에 보면 캠페인 생성 API가 있다고 나오는데 시도해보면 `404 Not found` 에러가 리턴되네요, API스펙 개편 공지에 있는 문서에 보니까 이부분이 생략 되었던데 혹시 지원 안하는건가요? 

혹시 지원하실 계획은 없는건지요?

그리고 `http://naver.github.io/searchad-apidoc/#/operations/PUT/~2Fncc~2Fcampaigns~2F%7BcampaignId%7D%7B%3Ffields%7D` 이 경우에
`fields` 값을 여러개 한꺼번에 넣을수 있는 방법이 있나요??

`/ncc/campaigns/{campaignId}?fields=userLock,budget,period`
`/ncc/campaigns/{campaignId}?fields=userLock&fields=budget&fields=period`
`/ncc/campaigns/{campaignId}?fields[]=userLock&fields[]=budget&fields[]=period`

다 시도해봤는데 안되는것 같아서요.
감사합니다

**Comment by naver-searchad** [comment]
안녕하세요 네이버 검색광고입니다.
캠페인 생성 api는 현재 정상적으로 작동중입니다.
아래와 같이  해당 url로 post방식으로 호출해주시고 campaign 생성 attribute를 request body로 채워서 넣어주시면 됩니다.  404 에러가 난거면  아마 호출url이나 post 방식이  잘못된것으로 보이는데요
혹시 호출하신  api  형식을 보내주시면  확인해보겠습니다 
POST /ncc/campaigns
{
"campaignTp": "WEB_SITE",
"name": "xxxx",
"customerId": xxxx
}

put으로 fields는 복수개로 호출될수 없습니다.  현재는 fields=userLock 또느,ㄴ fields=period 식으로 호출가능합니다.
감사합니다

**Comment by minsikzzang** [comment]
안녕하세요 빠른 답변 감사합니다, 확인해본 결과 api 동작이 되는걸로 확인했습니다 하지만 한가지 더 문제가 있는데요

```
curl -v -XPOST -H 'X-Timestamp: 1499679088' -H 'X-API-KEY: 0100000000f2e75122770874cb904034e7e27f5815c21af53a93f25b0f05f0ce97f263650c' -H 'X-Customer: 1077530' -H 'X-Signature: 0ldF4aBrwHSkvf0bxuJG0FQP/o+G99U6tldOHkhoOF0=' -H 'Content-Type: application/json' -d '{"campaignTp":"WEB_SITE","name":"test-00"}' https://api.naver.com/ncc/campaigns
```
이렇게 호출했더니
```
< HTTP/1.1 404 Not Found
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Connection: close
< Cache-Control: no-store, must-revalidate
< X-Transaction-ID: AT5FBQ4H1PBLC
< Content-Type: application/json;charset=UTF-8
< Date: Mon, 10 Jul 2017 09:32:17 GMT
< Strict-Transport-Security: max-age=15768000
<
* Curl_http_done: called premature == 0
* Closing connection 0
{"code":1018,"status":404,"title":"No permission to access the resource."}
```
아직도 404가 리턴되는데, 퍼미션이 없다고, 다른 api들은 같은 api키로 다 문제 없이 동작하는데 혹시 이문제는 어떻게 해결해야 하나요?

감사합니다.

**Comment by naver-searchad** [comment]
앞서 드린 댓글에서처럼   아래처럼 response body에 customerId값을 셋팅해주셔야 됩니다.

POST /ncc/campaigns
{
"campaignTp": "WEB_SITE",
"name": "xxxx",
"customerId": xxxx
}

감사합니다

**Comment by minsikzzang** [comment]
아 그렇군요 답변 감사합니다.
