### ISSUE TITLE
위임받은 광고관리용계정을 통해 광고관리 대해서 문의드립니다.

### ISSUE THREAD

**Issue by ChoiYoungWoo2197** [naver/searchad-apidoc#630]
안녕하세요. 광고주으로부터 권한을 위임받은 광고관리용계정으로 부터 광고주 광고관리를 하려고 합니다. 테스트시 발생했던 에러에 대해서 문의드립니다.

테스트 순서는 아래와 같습니다.
1. ManagedCustomerLink api를 통해 광고주의 clientCustomerId 값을 알아낸다.
2. api요청시 'X-Customer'에 clientCustomerId로 변경하여 요청한다.
3. 에러가 발생한다. (title => Auth Failed, status => 403, customer-id: xxxxxxxx)

![제목 없음](https://user-images.githubusercontent.com/57242259/179689474-4d779c12-bc0e-4463-b72c-65a3f298d1de.png)

해당 에러가 나타나는 이유를 알고싶습니다.

**Comment by naver-searchad** [comment]
@ChoiYoungWoo2197 

안녕하세요. 네이버 검색광고 API 담당자 입니다.

광고관리용계정 ( 요청하실때 사용하셨던 API-KEY 를 발급하셨던 계정) 에 
광고주 계정의 ( X-Customer에 넣으셨던 client Customer-id 계정 ) 관리 권한이 없어서 발생한 문제입니다.

광고주 계정에서 권한이 제대로 부여가 되있는지 확인 부탁드리겠습니다.

감사합니다.

감사합니다.

**Comment by ChoiYoungWoo2197** [comment]
광고관리용 계정이 받은 관리 권한은  '광고관리자'를 부여받았습니다.
광고주의 광고관리를 하기 위해선 '광고관리/로그분석'을 광고주로부터 받아야 하나요??
![image](https://user-images.githubusercontent.com/57242259/179712598-a3df116c-8823-4fec-a0d7-3288e458d166.png)

**Comment by naver-searchad** [comment]
@ChoiYoungWoo2197 
안녕하세요. 

첨부해주신 transactionID 기준으로 
사용하신 엑세스라이센스(API-KEY) 를 발급받았던 계정에 (Customer ID : 239XXX )  X-Customer 로 넣으셨던 광고 계정 (Customer ID : 646XXX )의 광고 관리 권한이 부여되지 않은것 같습니다.
(어떠한 권한도 없는것으로 확인됩니다.)

권한부여가 잘 되었는지 확인부탁드리겠습니다.
