### ISSUE TITLE
자동입찰 문의

### ISSUE THREAD

**Issue by kiyj** [naver/searchad-apidoc#631]
안녕하세요

자동입찰솔루션을 개발중에 있습니다.
타 자동입찰솔루션을 살펴보니 키워드의 현재 노출순위를 체크하여 입찰가를 자동으로 조정 되게끔 되어있습니다.
하지만 제가 알기로는 현재 순위를 파악할 수 있는 API가 없는 것으로 확인하였습니다.
최소 30분~3시간 지연데이터를 얻는 것이 최선이더라구요
NABUS 자동입찰 솔루션의 경우에는 5분단위로 키워드의 현재순위를 체크하여 입찰가를 조정해 주는 기능이있습니다.
실제 사용시에도 꽤 정확하게 5분단위로 현재 순위를 체킹할 수 있더라구요.
별도 API 값이 존재하는 것인지 문의드립니다.

추가적으로 특정순위에 도달하기위해 입찰이 진행될때 입찰가의 +-증감액을 얼마로 해야하는지 산출할 수 있는 방법이있는지 문의드립니다.

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 API 담당자입니다. 

현재 노출 순위를 확인할수 있는 API는 제공 드리고 있지 않습니다. 
또한 특정 순위에 도달하기 위한 입찰가 결정 방법의 경우 저희도 알고 있는 바가 없습니다. 

감사합니다.
