### ISSUE TITLE
브랜드검색 광고비(cost) 데이터 관련해서 문의드립니다.

### ISSUE THREAD

**Issue by chs1120** [naver/searchad-apidoc#632]
현재 2022-07-25 기준 브랜드검색 광고비 데이터가 0으로 오는데, 
이와 관련해서 api를 통해 받을 수 있는 방법이 있을까요?
방법이 없다면, 추후에 리포트에 이런 기능을 추가할 계획이 있는지 알려주시면 감사하겠습니다.

**Comment by naver-searchad** [comment]
@chs1120 안녕하세요? 네이버 검색광고 API입니다.

브랜드 검색은 기간단위로 계약을 하는 광고 상품입니다. 계약이 완료되는 시점에 계약 금액이 차감이 되는 방식입니다.
https://saedu.naver.com/adbiz/searchad/brandSearch.naver 내용을 참고하세요.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 API입니다. 

지불된 광고비는 Bizmoney: get(cost) 를 통해 조회가 가능합니다. (VAT 포함금액으로 표기됩니다.)
http://naver.github.io/searchad-apidoc/#/operations/GET/~2Fbilling~2Fbizmoney~2Fcost%7B%3FstatDt,searchStartDt,searchEndDt%7D

한가지 주의 하실 점은 브랜드 검색 상품의 경우 계약 시점에 광고비가 차감 되고 계약 중도 해지시 추후 정산을 통해 환급을 받는등 네이버 검색광고의 다른 상품과는 다른 형태의 과금 체계를 가지고 있다는 점입니다. 예를 들어 22년 8월 1일 부터 한달간 집행 예정인 브랜드 검색광고 계약을 22년 7월 10일에 체결 했다면 7월 10일자 비즈머니 조회 시 계약된 금액이 차감된 것을 확인할수 있습니다. 그러나 광고 실제 집행 기간인 22년 8월 1일 부터 8월 말일까지는 비즈머니 지불액이 모두 0으로 표시 됩니다. 

감사합니다.

**Comment by naver-searchad** [comment]
@chs1120 님 죄송합니다. 동시에 두 담당자가 같이 답변을 달았네요. 
혼란의 여지가 있어 추가 설명 남깁니다. 

첫 답변에서 "계약이 완료 되는 시점에 계약 금액이 차감되는 방식"의 의미는 계약의 체결을 의미 하는 것으로 계약 이행 완료를 의미 하지는 않습니다. 정확히 말씀 드리면 계약이 체결 되어 네이버 광고 시스템에 해당 계약이 등록되는 시점을 완료 되는 시점으로 표현한 것입니다. 

감사합니다.
