### ISSUE TITLE
productCode 문의드립니다.

### ISSUE THREAD

**Issue by 92hundredxxx** [naver/searchad-apidoc#633]
네이버 어드민 비즈머니에 표시되는 금액 기준으로, 광고비 소진/잔액 알림을 프로그램을 만들려고 하는데, 
각각의 productCode가 의미하는 상품명을 네이버 광고명 기준으로 확인 부탁드리며,
현재 네이버 검색광고 어드민에서는 아래 광고 상품 전체를 수집/합산 처리하여 노출한 금액일지도 문의드립니다.

1. 광고 상품 : https://saedu.naver.com/adbiz/searchad/placeSearch.naver
2. productCode
CPC
CC_WEB
BRND
CCP
PLA
SHOPPING
POWER_CONTENTS
BRAND_SEARCH
PLACE
BRAND_SEARCH_NOMINAL

**Comment by 92hundredxxx** [comment]
@naver-searchad  확인 부탁드립니다!

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 API 담당자입니다. 

답변이 늦어 죄송합니다. 
해당 기능 담당 개발자 분께 확인 중입니다. 
확인 되는데로 답변 드리겠습니다. 

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 API 담당자입니다. 

개인적인 급한 사정으로 관련 담당 개발자 분께서 금주말까지 출근을 못하시는 상황임을 방금 확인 하여 중간 답변 드립니다. 

해당 코드 중 상당수는 제가 답변을 드릴수 있기는 한데 
아마도 메뉴얼상에 코드표가 최신 코드표로 업데이트가 되지 못한것 같아 
(예를 들어 지역광고들이 추가되고 브랜드 검색도 과거 상품 코드들만 기재되어 있고 개편된 브랜드 검색 코드가 존재하지 않습니다.)
정확한 답변을 드릴수 없기에 담당자 분에 확인 중이었습니다. 

해당 API는 광고관리시스템(searchad.naver.com)의 비즈머니 메뉴의 UI들이 호출 하는 것과 동일한 API인데요. 
모든 상품을 구매하고 계시지 못하기 때문에 모든 코드를 확인하시기는 어려우실 것 같긴합니다만 일정이 촉박하시면 죄송하오나 우선 해당 UI에서 확인을 부탁드립니다. 

담당 개발자분께서 복귀 하시는데로 답변을 드리고 메뉴얼 업데이트도 진행하겠습니다.

감사합니다.

**Comment by 92hundredxxx** [comment]
@naver-searchad 담당자분 복귀 후, 추가 답변주시면 감사하겠습니다.

**Comment by naver-searchad** [comment]
@92hundredxxx 
안녕하세요? 네이버 검색광고 API입니다.

네이버 검색광고에서 사용하는 상품 코드는 아래와 같습니다.

* BRAND_SEARCH: 브랜드검색(신)
* BRND: 브랜드검색
* CCP: 클릭초이스 플러스
* CPC: 클릭초이스
* CPT: 타임초이스
* MBRND: 모바일 브랜드검색
* MODA: 모바일배너
* NCC: 사이트 검색광고(파워링크)
* PLA: 클릭초이스 상품광고
* PLACE: 플레이스검색+지역소상공인(플레이스)
* POWER_CONTENT: 콘텐츠검색광고(파워컨텐츠)
* SHOPPING: 쇼핑검색광고(쇼핑검색)
* WEB_SITE: 사이트 검색광고(파워링크)

하지만 위 상품코드중에 더이상 서비스가 되지 않는 상품도 있으니 참고하시기 바랍니다.

감사합니다.

**Comment by 92hundredxxx** [comment]
@naver-searchad  

1. 네이버 광고관리 시스템과 동일한 비즈머니 데이터를 구현하기 위해서는
아래 상품 외 나머지 상품 코드 데이터를 호출하면 될까요?

목적 : 네이버검색 광고시스템 비즈머니에 표시되는 금액 기준으로, 광고비 소진/잔액 알림을 프로그램을 만들려고 합니다.

BRAND_SEARCH: 브랜드검색(신)
BRND: 브랜드검색
MBRND: 모바일 브랜드검색
MODA: 모바일배너

2. 모바일배너는 검색광고 어떤 상품을 말씀하시는 걸까요? 혹시 GFA 상품 데이터를 의미하는 부분일지 확인 부탁드립니다.

**Comment by 92hundredxxx** [comment]
@naver-searchad 확인 부탁드립니다

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API 담당자입니다. 

문의 주신 API는 [Bizmoney: get(cost)](http://naver.github.io/searchad-apidoc/#/operations/GET/~2Fbilling~2Fbizmoney~2Fcost%7B%3FstatDt,searchStartDt,searchEndDt%7D)로 생각 됩니다. 
문의를 주신 이후 해당 API의 상품 코드와 저희 시스템에서 글로벌 하게 사용하고 있는 상품 코드간에 차이가 있어 API 소스를 
재확인해 보았습니다. 
현재 해당 API에서는 모든 상품의 소진 금액이 표시 되지 않으며 브랜드 검색의 경우 게약 기간 기준의 비즈머니 차감(명목 비용)과 계약 집행중 일할 계산된 비용 인식(기간 인식 비용)을 각각 제공하는 등 구상 중이신 서비스에 이용하시기에 부적절한 것으로 생각 됩니다. 
또한 해당 API는 현재 네이버 검고 광고시스템의 UI(광고관리시스템)에서 사용되지 않는 api 서비스 전용 오퍼레이션으로 저희 광고 시스템에 표시되는 비즈머니 금액을 기준으로 서비스를 구성하시는데 적절하지 않을 것으로 생각 됩니다. 

이외에 제공되는 비즈머니 API들은 아래와 같사오니 이 API들 이용을 고려해 주시는 편이 좋을것 같습니다. 

[get](http://naver.github.io/searchad-apidoc/searchad-apidoc#/operations/GET/~2Fbilling~2Fbizmoney)
GET /billing/bizmoney
--> 광고시스템에 표시되는 비즈머니 잔액을 제공합니다. 추가로 비즈머니 부족으로 인한 광고 노출 중단 (budgetLock =1) 및 환불 처리 중 광고 노출 중단 (refundLock =1) 을 제공합니다. 

[get(charge)](http://naver.github.io/searchad-apidoc/searchad-apidoc#/operations/GET/~2Fbilling~2Fbizmoney~2Fhistories~2Fcharge%7B%3FsearchStartDt%2CsearchEndDt%7D)
GET /billing/bizmoney/histories/charge?searchStartDt,searchEndDt
--> 광고관리 시스템 내 비즈머니 메뉴의 충전내역 탭에 해당 하는 API입니다. 

[get(exhaust)](http://naver.github.io/searchad-apidoc/searchad-apidoc#/operations/GET/~2Fbilling~2Fbizmoney~2Fhistories~2Fexhaust%7B%3FsearchStartDt%2CsearchEndDt%7D)
GET /billing/bizmoney/histories/exhaust?searchStartDt,searchEndDt
--> 광고관리 시스템 내 비즈머니 메뉴의 소진내역 탭에 해당 하는 API입니다. 
--> 상품 구분은 Campaign Type 코드를 이용하시면 됩니다. 캠페인 타입은 캠페인 API에서 사용하는 것과 같습니다. 

[get(period)](http://naver.github.io/searchad-apidoc/searchad-apidoc#/operations/GET/~2Fbilling~2Fbizmoney~2Fhistories~2Fperiod%7B%3FsearchStartDt%2CsearchEndDt%7D)
--> 광고관리 시스템 내 비즈머니 메뉴의 기간별내역 탭에 해당 하는 API입니다. 

한가지 주의 하실 점은 위 API들 중 기간조회 옵션이 있는 GET /billing/bizmoney를 제외한 api들에서 searchEndDt 를 오늘로 할 경우 조회시점 현재까지의 값이 제공되기는 하나 GET /billing/bizmoney와는 값이 다를 수 있다는 점입니다. 

이는 각 지표를 생성하는 시간의 차이로 GET /billing/bizmoney의 기반 지표를 먼저 생성하고 이후에 다른 API들의 지표를 생성하게 됩니다. 시차는 길게는 수 시간~ 24시간 내로 벌어질수 있습니다. 

감사합니다.
