### ISSUE TITLE
이메일 미인증으로 인해 서비스 이용이 정지될 경우 API 확인

### ISSUE THREAD

**Issue by kaorimikage** [naver/searchad-apidoc#634]
https://saedu.naver.com/notice/view.naver?notiSeq=3928&catg=&fixYn=N&searchOpt=all&keyword=

네이버 검색광고 공지로 이메인 미인증의 경우 서비스 이용이 정지된다고 나와있습니다.
혹시 API에서 해당 상태를 알 수 있는 기능을 제공하고 있거나 앞으로 제공할 계획이 있는지 궁금합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API 담당자입니다. 

이용중지 여부 자체는 ManagedCustomerLink(http://naver.github.io/searchad-apidoc/#/tags/ManagedCustomerLink)
의 clientPenaltySt(권한을 가진 타인의 계정), managerPenaltySt(자신의 계정 즉 호출시 사용한 엑세스 라이선스를 가진 계정)을 통해 확인할수 있으나 사유를 확인할수는 없습니다.  단지 1: 이용중지 , 0 :정상 상태  만을 제공합니다. 
참고로 managerEnable나 clientEnable 필드의 경우 이용중지와는 다른 여러가지 사유로 인해 로그인 자체가 차단된 경우를 의미 합니다. 대표적인 예는 변경 약관에 동의 하지 않는 경우나 시스템 업그레이드로 인한 계정 체계 전환을 하지 않은 경우등인데 이미 10년~20년 전에 발생한 일들로 인한 많아 케이스가 실제 사용되는 게정이라면  크게 신경 쓰지 않으셔도 될것 가틉니다. 

그리고 이메일 미인증의 경우 여러가지 이유로 때나 상황에 따라 처리 방식이 다양할수 있어 clientPenaltySt( managerPenaltySt이 0임에도 권한 없음 에러가 리턴되는 형태로 처리될 수도 있습니다. 
따라서 API를 통해 이를 확인하시지 못한다고 생각해 주시면 좋을것 같습니다. 
그리고 이러한 이유로 이를 API를 제공드릴수 있도록 구조화 하기도 어려운 상황이라 향후에도 제공드릴 가능성은 낮아 보입니다.

감사합니다.
