### ISSUE TITLE
네이버 검색광고 API 상품 등록 문의

### ISSUE THREAD

**Issue by jungmyounghwan** [naver/searchad-apidoc#635]
API로 캠페인과 그룹을 만들고 그룹내에 상품들을 넣은 후에 광고 규칙을 넣으려 합니다.

그룹내에 상품들을 추가할 경우 어떤걸 사용해야 하나요? 문서에서 찾지 못하여 문의드립니다.

**Comment by jungmyounghwan** [comment]
api 문의는 여기서만 가능한가요? 전화나 채팅상담 등 담당자분에게 바로바로 피드백을 받고 싶습니다.

**Comment by naver-searchad** [comment]
@jungmyounghwan 안녕하세요? 네이버 검색광고 API 입니다.

> 그룹내에 상품들을 추가할 경우 어떤걸 사용해야 하나요?

이 질문이 모호합니다.
광고 그룹 하위에 등록가능한 요소는 키워드, 소재, 확장 소재 입니다.
말씀 하신 상품이 정확히 어떤걸 말씀 하시는지 확인이 어렵습니다.

또한 캠페인에 따라 키워드 등록이 불가능한 유형이 있습니다.
캠페인 유형별 자세한 특징은 아래 링크 내용을 참고하시기 바랍니다.
https://saedu.naver.com/adguide/common/overall.naver

그리고 캠페인 유형별 등록 가능한 광고 그룹은 아래 링크를 참고하세요.
https://github.com/naver/searchad-apidoc/wiki/FAQ#q-캠페인-유형별-등록가능한-그룹-유형은-어떻게-되나요

감사합니다.

**Comment by jungmyounghwan** [comment]
소재에서 상품명이나 상품코드를 검색하여 그룹에 추가해야 되는데 어떤걸 사용하면 되나요? ad인가요?

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API 입니다.

상품명, 상품 코드 검색에 대한 API는 제공되지 않습니다. (쇼핑쪽에 문의하셔야 합니다).

아래 이슈를 참고하세요.
https://github.com/naver/searchad-apidoc/issues/130

감사합니다.

**Comment by jungmyounghwan** [comment]
그럼 API로는 캠페인 생성 -> 그룹 생성 -> 수동으로 소재 등록에서 상품 입력 -> 광고 이런 형태인건가요? 

검색이 아니라 그럼 제가 소재 상품들 정보를 알고 있으면 이걸 광고 API에 넣어서 적용하는 방법은 없나요?

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

쇼핑 캠페인의 경우, 위 코멘트 주신 내용으로 작업을 하시면 됩니다.
하지만 쇼핑에서 제공하는 네이버 쇼핑 상품 ID(nvmid)를 알고 계신다면, 아래의 api를 이용하여 등록가능합니다.
대신에 https://github.com/naver/searchad-apidoc/issues/130#issuecomment-414217984 에서 설명한 내용과 같이,  referenceKey 값을 잘 입력 해주셔야 합니다

http://naver.github.io/searchad-apidoc/#/operations/POST/~2Fncc~2Fads

**Comment by jungmyounghwan** [comment]
SHOPPING_PRODUCT_AD 타입으로 상품번호 1234를 추가할때 예시 코드 볼 수 있을까요?

**Comment by jungmyounghwan** [comment]
uri = '/ncc/ads'
method = 'POST'
payload = {
    'nccAdgroupId' : "grp-a001-02-000000028618034",
    'type' : "SHOPPING_PRODUCT_AD",
    'ad' : "???",
    "adAttr": 
    {
        "useGroupBidAmt": "true",
        "bidAmt": "50"
    },
    "ad":{},
    "referenceKey":"84232273153"
    }

r = requests.post(BASE_URL + uri, params={'fields': 'ad'}, json=payload, headers=get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID))

print("response status_code = {}".format(r.status_code))
print("response body = {}".format(r.json()))


이런식으로 하는게 맞을까요..? 
??? <- 이거 적은곳은 뭘 넣어야 하는지 모르겠습니다. 언어는 파이썬입니다

**Comment by jungmyounghwan** [comment]
확인 부탁드립니다.

**Comment by jungmyounghwan** [comment]
이전 내역들을 찾아서 여기까지 해봤는데 에러가 아래처럼 뜹니다. 
"response body = {'title': 'Bad Request', 'status': 400, 'detail': 'JSON parse error: Cannot deserialize instance of `com.naver.searchad.heroes.domain.ncc.NccAd` out of START_ARRAY token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `com.naver.searchad.heroes.domain.ncc.NccAd` out of START_ARRAY token\n at [Source: (PushbackInputStream); line: 1, column: 1]'}"



uri = '/ncc/ads'
method = 'POST'
payload = [{
    "customerId": "1134554",
    'nccAdgroupId' : "grp-a001-02-000000028658627",
    'type' : "SHOPPING_PRODUCT_AD",
    "adAttr": 
    {
        "useGroupBidAmt": "true",
        "bidAmt": "50"
    },
    "ad":{},
    "referenceKey":"84232273153,84563768406"
    }]


r = requests.post(BASE_URL + uri, params={'fields': 'isList'}, json=payload, headers=get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID))

print("response status_code = {}".format(r.status_code))
print("response body = {}".format(r.json()))

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.
referenceKey를 하나씩만 등록할 수 있습니다.
아래와 같이 작성하셔서 보내시면 될 것 같습니다.
[
  {
      "ad":{
         
      },
      "adAttr":{
         "useGroupBidAmt":true,
         "bidAmt":50
      },
      "customerId": 1134554,
      "nccAdgroupId":"grp-a001-02-000000028658627",
      "referenceKey":"84232273153",
      "type":"SHOPPING_PRODUCT_AD"
   },
{
      "ad":{
         
      },
      "adAttr":{
         "useGroupBidAmt":true,
         "bidAmt":50
      },
      "customerId": 1134554,
      "nccAdgroupId":"grp-a001-02-000000028658627",
      "referenceKey":"84563768406",
      "type":"SHOPPING_PRODUCT_AD"
   }
]

**Comment by jungmyounghwan** [comment]
response status_code = 400
response body = {'title': 'Bad Request', 'status': 400, 'detail': 'JSON parse error: Cannot deserialize instance of `com.naver.searchad.heroes.domain.ncc.NccAd` out of START_ARRAY token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `com.naver.searchad.heroes.domain.ncc.NccAd` out of START_ARRAY token\n at [Source: (PushbackInputStream); line: 1, column: 1]'}

-----------------------------------------------------

이런 에러가 나옵니다

**Comment by jungmyounghwan** [comment]
현재 상태입니다.

/에러메세지
"response body = {'title': 'Bad Request', 'status': 400, 'detail': 'JSON parse error: Cannot deserialize instance of `com.naver.searchad.heroes.domain.ncc.NccAd` out of START_ARRAY token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `com.naver.searchad.heroes.domain.ncc.NccAd` out of START_ARRAY token\n at [Source: (PushbackInputStream); line: 1, column: 1]'}"


/실행코드
uri = '/ncc/ads'
method = 'POST'
payload = [
{
      'ad':{},
      'adAttr':
      {
         'useGroupBidAmt': 'true',
         'bidAmt': '50'
      },
      'customerId': '1134554',
      'nccAdgroupId':'grp-a001-02-000000028658627',
      'referenceKey':'84563768406',
      'type':'SHOPPING_PRODUCT_AD'
   },
{
      'ad':{},
      'adAttr':
      {
         'useGroupBidAmt':'true',
         'bidAmt':'50'
      },
      'customerId': '1134554',
      'nccAdgroupId':'grp-a001-02-000000028658627',
      'referenceKey':'84563768415',
      'type':'SHOPPING_PRODUCT_AD'
   }
]

r = requests.post(BASE_URL + uri, params={'fields': 'adAttr'}, json=payload, headers=get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID))

print("response status_code = {}".format(r.status_code))
print("response body = {}".format(r.json()))

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

params에 isList=true를 추가해주시기 바랍니다.

**Comment by jungmyounghwan** [comment]
params={'fields': 'adAttr', 'isList' = 'true'} 이런식으로 넣나요? 똑같이 오류나는데 예시 부탁드립니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

로그에는 아래와 같이 요청 되었습니다. 
'fields': 'adAttr', 는 빼고 요청 하셔도 될 것 같습니다.
```
요청 URL
/api/ncc/ads?fields=adAttrisList=true
```

**Comment by jungmyounghwan** [comment]
답변오는동안 이것저것 바꿔서 많이 시도해가지고 어떤게 작동한건지 모르겠습니다.

r = requests.post(BASE_URL + uri, params={'isList':'true'}, json=payload, headers=get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID))

이렇게는 안되는데 예시 없을까요?

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.
표준 json api  방식이여서 현재 공유드린 내용과 크게 다르지 않습니다.

```
에러 로그 >
{"code":1010,"status":400,"title":"Received value is not suitable for JSON format.","detail":"instance type (string) does not match any allowed primitive type (allowed: [\"integer\",\"number\"]), at '/bidAmt' with 'type'\ninstance type (string) does not match any allowed primitive type (allowed: [\"boolean\"]), at '/useGroupBidAmt' with 'type'\n"}
```
요청한 데이터에서 아래와 같이 수정후 요청해주시기 바랍니다.
```
'useGroupBidAmt': true,
'bidAmt':50
'customerId': 1134554
```

**Comment by jungmyounghwan** [comment]
이렇게 ''로 묶은걸 풀으란 말씀이신가요? 묶고해도 안되고 풀어도 안됩니다.
Traceback (most recent call last):
  File "d:/workspace/naver-api/TEST1.py", line 145, in <module>
    'useGroupBidAmt': true,
NameError: name 'true' is not defined

-----------------------------------------------------------

uri = '/ncc/ads'
method = 'POST'
payload = [
{
      'ad':{},
      'adAttr':
      {
         'useGroupBidAmt': true,
         'bidAmt': 50
      },
      'customerId': 1134554,
      'nccAdgroupId':'grp-a001-02-000000028658627',
      'referenceKey':'84563768406',
      'type':'SHOPPING_PRODUCT_AD'
   },
{
      'ad':{},
      'adAttr':
      {
         'useGroupBidAmt': true,
         'bidAmt': 50
      },
      'customerId': 1134554,
      'nccAdgroupId':'grp-a001-02-000000028658627',
      'referenceKey':'84563768415',
      'type':'SHOPPING_PRODUCT_AD'
   }
]

r = requests.post(BASE_URL + uri, params={'isList':'true'}, json=payload, headers=get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID))

print("response status_code = {}".format(r.status_code))
print("response body = {}".format(r.json()))

**Comment by jungmyounghwan** [comment]
"" 으로 싸니까 아래 같이 나오네요

Traceback (most recent call last):
  File "d:/workspace/naver-api/TEST1.py", line 167, in <module>
    r = requests.post(BASE_URL + uri, params={'isList''true'}, json=payload, headers=get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID))
  File "C:\Users\오너클랜\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "C:\Users\오너클랜\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\오너클랜\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "C:\Users\오너클랜\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "C:\Users\오너클랜\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "C:\Users\오너클랜\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\models.py", line 474, in prepare_url
    enc_params = self._encode_params(params)
  File "C:\Users\오너클랜\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\models.py", line 121, in _encode_params
    for k, vs in to_key_val_list(data):
ValueError: too many values to unpack (expected 2)

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.
python 컴파일 에러로 보여집니다.
아래 내용 참고 부탁드립니다.
https://bobbyhadz.com/blog/python-json-nameerror-name-true-is-not-defined#:~:text=The%20Python%20%22NameError%3A%20name%20',with%20True%20in%20your%20code.

**Comment by jungmyounghwan** [comment]
다른 API는 다 정상 작동하는데 ad create만 이런데 컴파일 에러인가요??

uri = '/ncc/ads'
method = 'POST'
payload = [
{
      'ad':{},
      'adAttr':
      {
         'useGroupBidAmt': "True",
         'bidAmt': "50"
      },
      'customerId': '1134554',
      'nccAdgroupId':'grp-a001-02-000000028658627',
      'referenceKey':'84563768406',
      'type':'SHOPPING_PRODUCT_AD'
   },
{
      'ad':{},
      'adAttr':
      {
         'useGroupBidAmt': "True",
         'bidAmt': "50"
      },
      'customerId': '1134554',
      'nccAdgroupId':'grp-a001-02-000000028658627',
      'referenceKey':'84563768415',
      'type':'SHOPPING_PRODUCT_AD'
   }
]

r = requests.post(BASE_URL + uri, params={'isList':'True'}, json=payload, headers=get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID))

print("response status_code = {}".format(r.status_code))
print("response body = {}".format(r.json()))



--------------------------------

**Comment by jungmyounghwan** [comment]
위에 드렸던 문의 해결했습니다. 감사합니다.

**Comment by jungmyounghwan** [comment]
광고 규칙은 어떤 API를 사용하면 되나요?
