### ISSUE TITLE
urn:naver:api:problem:invalid-signature 에러

### ISSUE THREAD

**Issue by hwangk1** [naver/searchad-apidoc#636]
API를 통해서 전환 분석 보고서 다운로드 받으려고 합니다.

uri = '/stat-reports'
method = 'POST'
param = {'reportTp' : 'AD_CONVERSION',
          'statDt': '20220805'}

r = requests.get(BASE_URL + uri,
                 params = param,
                 headers=get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID))

print("response status_code = {}".format(r.status_code))
print("response body = {}".format(r.json()))

---------------------------------------------------------------------------------------------------
result>
response status_code = 403
response body = {'signature': '----------------------------------', 'status': 403, 'title': 'Invalid Signature', 'detail': "Signature '----------------------------------' is invalid.", 'type': 'urn:naver:api:problem:invalid-signature'}

이렇게 invalid-signature 에러가 발생합니다.

검색해보니 uri 또는 method를 잘못 적은 경우 발생하는 문제 같은데,
위에 제가 적은 코드에서는 틀린 부분이 없는것 같아서요..

어떻게 해결할 수 있는지 도와주세요!

**Comment by naver-searchad** [comment]
@hwangk1 
안녕하세요? 네이버 검색광고 API 입니다.

말씀하신대로 서명(signature) 생성이 잘못되어서 발생한 문제인데요. 
작성해주신 코드만으로는 정확히 파악이 어려운것 같습니다. ( get_header method 내의 구현을 봐야 될것 같습니다 )

1. 서명(signature) 생성시에 "{timestamp}.{httpMethod}.{uri}" 를 사용하여 생성하였는지 확인
 -> 1659934078360.POST./stat-reports
2. secret_key 값이 제대로 세팅되었는지 확인
3. hmac sha256 으로 생성하였는지 확인

위의 3개를 확인해보시고, 그래도 문제가 동일하다면 get_header 내부의 코드를 적어주시면 확인해보도록 하겠습니다.

감사합니다.

**Comment by hwangk1** [comment]
def generate(timestamp, method, uri, secret_key):
    message = "{}.{}.{}".format(timestamp, method, uri)
    hash = hmac.new(bytes(secret_key, "utf-8"), bytes(message, "utf-8"), hashlib.sha256)

    hash.hexdigest()
    return base64.b64encode(hash.digest())

def get_header(method, uri, api_key, secret_key, customer_id):
    timestamp = str(round(time.time() * 1000))
    signature = generate(timestamp, method, uri, SECRET_KEY)
    return {'Content-Type': 'application/json; charset=UTF-8', 'X-Timestamp': timestamp, 'X-API-KEY': API_KEY, 'X-Customer': str(CUSTOMER_ID), 'X-Signature': signature}

--- header 생성 코드 입니다! 확인부탁드려요

참고로
uri = '/stat-reports'
method = 'GET'

r = requests.get(BASE_URL + uri,
                 headers=get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID))

이런식에 get 함수는 잘 받아와서 정상적으로 결과가 출력됩니다.
그래서 아마 KEY 세팅에는 문제가 없다는 생각이드네요..!

**Comment by naver-searchad** [comment]
@hwangk1 
안녕하세요.

말씀하신 내용을 듣고, 다시 코드를 보니 
```
r = requests.get(BASE_URL + uri,
headers=get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID))
```

post 요청이 아닌 get 요청을 보내고 계셔서 그런것 같습니다.

post 로 수정하시면 정상동작할것으로 보입니다.
