### ISSUE TITLE
Cannot handle the request. The limit has been exceeded.

### ISSUE THREAD

**Issue by jungmyounghwan** [naver/searchad-apidoc#637]
API를 통해 

1캠페인 > 40개 그룹 > 각 그룹별 상품 100개로 총 4천개 cpc 쇼핑검색 광고 등록을 하던 중 아래 오류가 발생했습니다.

Cannot handle the request. The limit has been exceeded.

과도한 호출로 문제가 된건가요? 맞다면 어느정도로 해야 하는지 회신 부탁드립니다.

**Comment by jungmyounghwan** [comment]
Shop merchant id is invalid

이건 무슨 오류인가요?

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

1.
문의하신 내용은 아래 코멘트 참고하시기 바랍니다.
https://github.com/naver/searchad-apidoc/issues/272#issuecomment-532008259

또한 초당 호출 회수는 저희쪽 시스템 상태에 따라 조절되기 때문에 가이드를 드릴수 없으며 API 사용 프로그램에서 적절히 sleep을 추가하셔야 합니다. 

2. 네이버 쇼핑 상품 번호가 잘못 입력된 경우입니다.

감사합니다.

**Comment by jungmyounghwan** [comment]
넵 해결했습니다. 

상품 번호는 보니까 두가지가 있던데
네이버쇼핑 상품 ID   = 84563768406
(몰상품 ID) = (7019268084)

스마트스토어에서 얻을 수 있는 ID는 몰상품 ID인데 광고 API에서 필요한건 상품 ID인거 같습니다.
상품 ID는 어떻게 불러올 수 있나요? 스마트스토어 상품 조회 등에서 알 수 없나요?

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

상품 정보는 검색광고 API에서 제공하지 않습니다. 
그렇기 때문에 쇼핑 캠페인 유형의 소재는 검색광고 API를 이용하지 않도록 권고하고 있습니다.

감사합니다.

**Comment by jungmyounghwan** [comment]
쇼핑 캠페인 API를 지원하는데 상품 정보를 지원하지 않아서 사용하지 말라고 권고를 하신다구요?

https://github.com/naver/searchad-apidoc/issues/130

여기서 말씀해주신 nvmid는 뭔가요 그럼?

상품ID는 뭔가요? 쇼핑에서 상품 조회에선 몰상품ID만 나오고 네이버쇼핑 상품 ID는 나오지도 않고 
광고쪽 소재등록에만 나오는거 같은데

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

쇼핑 캠페인의 소재 등록은 네이버 검색광고 광고주센터를 이용하셔야 합니다. 문의하신 nvmid등 쇼핑관련 정보조회를 위해서는 광고주센터에서 쇼핑과 연동이 되기 때문입니다.

검색광고 API를 이용하여 등록하실 경우 필요한 nvmid등은 검색광고쪽에서 제공을 하지 않기 때문에 검색광고 API를 이용한 등록은 권고하지 않습니다. 하지만, 검색광고 API 사용자가 nvmid를 이미 알고 있고, 검색광고 API를 이용하여 등록하는 경우는 딱히 막고 있는 상황은 아닙니다.(공식적인 지원 대상이 아닙니다.)

감사합니다.

**Comment by jungmyounghwan** [comment]
광고주 센터라면 아래 url 맞나요?
https://manage.searchad.naver.com/customers/

nvmid는 네이버쇼핑 상품ID인거죠? 
몰상품 ID로는 못하나요?

말씀하신대로 몰상품 ID는 저희가 알고 가지고 있는데 nvmid는 광고센터에서만 볼 수 있고 엑셀 다운도 안되고 한개씩 밖에 못보는거 같은데요? 광고 등록하려면 이걸 하나씩 다 해야 한다는건가요?

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

네이버 검색광고 광고주센터는 https://searchad.naver.com 입니다.

검색광고 쇼핑 캠페인의 광고는 네이버 쇼핑에서 제공하는 데이터를 기반으로 진행이됩니다. 그렇기 때문에 네이버쇼핑 상품 ID가 기준입니다.
네이버 쇼핑의 상품 ID/몰 상품 ID는 검색광고에서 가지고 있지 않습니다. 네이버 쇼핑 상품 ID제공관련해서는 네이버 쇼핑 고객센터에 문의하시기 바랍니다.


감사합니다.
