### ISSUE TITLE
'title': 'Shop merchant id is invalid.'

### ISSUE THREAD

**Issue by jungmyounghwan** [naver/searchad-apidoc#638]
![image](https://user-images.githubusercontent.com/59358301/185050115-4730cc2c-c9ce-452f-8e89-2b4a79faa556.png)

이미지 보시면 광고센터에서 소재 등록할땐 몰상품ID로 등록이 가능한데 API에선 왜 네이버쇼핑 상품 ID만 사용이 가능한걸까요

쇼핑상품 ID로 보내면 등록이되고 몰상품 ID로 보내면 아래처럼 오류가 나옵니다.
response status_code = 400
response body = {'code': 3826, 'status': 400, 'title': 'Shop merchant id is invalid.'}

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

검색광고 광고주센터는 광고주 편의를 위해 네이버 쇼핑 API를 이용하여 몰상품 ID를 이용하여 상품 등록이 가능합니다.
하지만 검색광고 API에서는 해당 기능은 제공하지 않습니다.

감사합니다.
