### ISSUE TITLE
당일 광고비 API

### ISSUE THREAD

**Issue by queendesign112** [naver/searchad-apidoc#639]
안녕하세요! 
**Stat API에서 당일 광고비 데이터**를 확인하고자 하여 **데이터 응답 시점 기준**을 문의드립니다.

Stat API는 당일 데이터 확인이 가능한 것으로 알고 있는데요.
현재 당일 광고비를 테스트한 결과 8월 18일 기준 마지막 응답 일자가 8월 18일 00시로 광고비가 0원으로 표시됩니다.

1) 당일 광고비를 Stat API 요청 시 실시간 또는 1시간에 한번씩 데이터를 확인할 수 있을까요?
2) Stat API 요청 제한이 있나요? (일 몇 회 등)

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 보고서 담당자입니다. 

STAT API로 당일 광고비를 확인하실수 있기는 하나 몇가지 제약이 존재합니다. 

1.조회 시점 기준 최대 4시간 이상(광고비만 보신다면 최대 3시간) 지연된 데이터로 최소 1시간단위로 업데이트 됩니다. 
  지표의 업데이트 주기 및 관련 설명은 아래 링크를 확인하여 주시기 바랍니다.
  https://saedu.naver.com/help/faq/ncc/view.naver?faqSeq=529
 참고로 광고관리시스템([manage.searchad,navercorp.com](https://manage.searchad.naver.com/))내에서 표시되는 지표들은 
 STAT API를 이용해 구현되었습니다.  (대용량 보고서 및 다차원 보고서 제외)

2. 모든 API는 호출 속도의 제한만 존재하며 호출 속도(즉 단위 시간당 호출 횟수, 예를 들어 초당 XX회)는 호출 시점의 저희 시스템 상황에 따라 달라집니다. 즉 사용자들분들께서 많이 사용하고 계신 시점에는 모든 API의 속도가 느려지고 사용자가 적을 때는 빨라집니다. 그리고 각 API들은 그 특성에 따라 다른 api들보다 훨씬 느린 속도만을 지원할수 있는데요.  대략 일반적인 API들의 속도는 초당 15회~20회 사이 정도를 오고가며 빠를 때는 초당 30회까지도 나옵니다.
이런 상황이므로 호출 속도를 고정된 값으로 지정하는 형태로 로직을 구성하시는 것보다는 그냥 호출을 하다가 속도가 빠르다 (too many request )는 에러가 리턴되면 0.5초~1초 정도 sleep을 주시는 형태로 구성하시는 것을 권장 드립니다. 
마지막으로 속도 체크의 기준은 호출 대상이 되는 계정으로 호출메세지 헤더를 기준으로 보면 X-Customer  기준입니다. 

현재 구상하시는 서비스를 감안해 본다면 계정내 캠페인 수가 많더라도 (캠페인 생성 가능수는 제한이 있기 때문에) 아마도 속도가 문제가 되시지는 않을것 같습니다. 

감사합니다.

**Comment by sogangCSmaster** [comment]
안녕하세요.
API의 에러가 왜 플랫폼에도 발생하고 있습니다.

![image](https://github.com/naver/searchad-apidoc/assets/32369381/c18413b9-35cb-4241-88bb-41444700d8e0)

API 429가 네이버 광고플랫폼에도 공유가 된다고 하면 속도 제한이 걸려야 하는게 아닌가 싶습니다.
플랫폼에 뜨는것이 내부 오류인지 아니면 공유되는것이 정책인지 궁금합니다.

감사합니다.
