### ISSUE TITLE
캠페인 신규생성 API 확인

### ISSUE THREAD

**Issue by markkorea** [naver/searchad-apidoc#64]
http://naver.github.io/searchad-apidoc/#/operations/POST/~2Fncc~2Fcampaigns
에서 API로 검색광고의 캠페인 단위를 신규로 생성하려고 할 때 아무런 응답을 보이지 않는데 이유를 할 수 있을까요?
요청한 리퀘스트가 잘못되면 리퀘스트가 잘못되었다는 에러코드가 리턴되어야 할 듯 한데, 이 경우에는 에이피아이가 존재하지 않는다는 에러코드가 리턴됩니다.

POST /ncc/campaigns/{WEB_SITE}{test-00}

확인 부탁 드립니다.

**Comment by naver-searchad** [comment]
POST로 데이터를 보내실때 위에 설명한 http://naver.github.io/searchad-apidoc/#/operations/POST/~2Fncc~2Fcampaigns 의 내용을 JSON으로 생성하여 Request Body에 넣어 주셔야 합니다.

아래의 예제와 같이 HTTP Body 를 생성하시면 됩니다.


```
{"customerId":1234560,"campaignTp":"WEB_SITE","usePeriod":false,"deliveryMethod":"ACCELERATED","useDailyBudget":false,"trackingMode":"TRACKING_DISABLED","name":"sample"}

```

**Comment by naver-searchad** [comment]
추가 문의 없으셔서 문의 종료된 것으로 처리하겠습니다. 추가 문의 있으실 경우 다시 오픈 부탁드립니다.
