### ISSUE TITLE
20일 오전부터 23일 오전까지 광고정보 보고서 생성에 문제가 있었나요?

### ISSUE THREAD

**Issue by jhahn02** [naver/searchad-apidoc#640]
안녕하세요.
20일 오전부터 23일 오전까지 광고정보 보고서 생성에 문제가 있었나요?
API를 이용해 몇시간을 주기로 보고서를 생성하고 다운받고 있었는데
20일 오전부터 23일 오전까지 몇몇 광고주들 광고정보 보고서 생성에 계속 실패한 로그가 남아 있어서요.
보고서 생성 후 보고서 상태 조회를 했을 때 상태값이 ERROR로 응답이 왔었습니다.

몇가지 케이스 첨부 드립니다.
20일 오전 11시 30분즘
1364529 - 426EA2E231780094BDC1491AB5C0F514, 
1387330 - 7548353D5C791587559F93BFB68CED0B 
20일 오후 8시즘
811507  - DE86C95623426E8B8CE28E72345BADBA, 2E53C8653A54A84D71958D0213C0FF93
21일 오후 4시즘
811507 - E85CDE8E4D344F1546FA22D590D70588
...
광고주 ID - 보고서 ID 입니다.

확인 부탁드립니다. 감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 대용량 보고서 담당자입니다. 

8월 19일 밤 부터 보고서 생성시 이를 저장하는 스토리지 장비들에 문제가 있어 간혈적으로 보고서 생성에 실패한 
경우가 있었음을 확인하였고 관련 조치를 실시하였습니다. 실패한 보고서들은 생성 요청 순서대로 재생성하여 금일(8월 24일) 새벽에 모두 생성을 마쳤습니다. 

업무에 불편을 드려 대단히 죄송합니다. 

사용량이 점차 증가하면서 간혹 여러가지 이유로 보고서 생성에 실패하는 경우가 간혹 존재하고 총량 대비 비교적 수가 적을 경우 저희 모니터링에서 발견되지 않는 경우도 드물지만 존재합니다.  이런 경우는 대부분 재시도를 하면 문제 없이 생성이 됩니다. 
번거로우시겠지만 error가 리턴되면 재 생성을 시도하는 형태로 로직을 구성해 주시기를 부탁드립니다. 

감사합니다.

**Comment by jhahn02** [comment]
@naver-searchad 
확인 감사합니다.
