### ISSUE TITLE
report 문의

### ISSUE THREAD

**Issue by jungmyounghwan** [naver/searchad-apidoc#642]
uri = '/stat-reports/1598730843'
method = 'GET'
report = {
    'reportJobId' : '1598730843'
}

a = requests.get(BASE_URL + uri, params={'field' : 'report'}, json=report, headers=get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID))

print("response status_code = {}".format(a.status_code))
print("response body = {}".format(a.json()))

으로 아래 결과를 받았습니다.

response status_code = 200
response body = {'reportJobId': 1598730843, 'statDt': '2022-08-31T15:00:00Z', 'updateTm': '2022-08-31T15:00:00Z', 'reportTp': 'AD', 'status': 'BUILT', 'downloadUrl': 'https://api.naver.com/report-download?authtoken=2l%2FG0aRPWlR4kiwNGsis90r1%2BZllFYpgEzPeARf6a2MYm0o6eh6wEBtV2GYUy%2FnmnajQ%2FfPlVc5DbvDUDZpnT7PUDUYYPFuk', 'regTm': '2022-09-02T05:31:12Z', 'loginId': 'rtpia11'}

다운로드 URL을 확인해보니 

{"header":"X-API-KEY","detail":"HTTP header required: X-API-KEY","status":403,"title":"Missing Header","type":"urn:naver:api:problem:missing-header"}

이렇게 나옵니다

**Comment by naver-searchad** [comment]
@jungmyounghwan  안녕하세요. 네이버 검색광고 API입니다.

report-download API 접근시에도 다른 API와 동일하게 Header ( X-API-KEY, X-Signature 등등 ) 을 넣어서 요청해주셔야합니다.

감사합니다.

**Comment by jungmyounghwan** [comment]
간단한 예시 볼 수 있을까요..?
