### ISSUE TITLE
report-download API 

### ISSUE THREAD

**Issue by jungmyounghwan** [naver/searchad-apidoc#643]
report-download API 접근시에도 다른 API와 동일하게 Header ( X-API-KEY, X-Signature 등등 ) 을 넣어서 요청해주셔야합니다.

라고 답변 주셨는데

download api는 문서에 없는거 같습니다. 예시를 볼 수 있을까요?

**Comment by naver-searchad** [comment]
@jungmyounghwan 

안녕하세요. 검색광고 API 입니다.

문서는 API 호출 샘플을 보시면 됩니다.  (https://naver.github.io/searchad-apidoc/#/samples)

https://github.com/naver/searchad-apidoc/issues/642 이슈에 있는 코드 기반으로 설명드리면 
```
uri = '/report-download'
method = 'GET'

a = requests.get(BASE_URL + uri, params={'authtoken' : '2l%2FG0aRPWlR4kiwNGsis90r1%2BZllFYpgEzPeARf6a2MYm0o6eh6wEBtV2GYUy%2FnmnajQ%2FfPlVc5DbvDUDZpnT7PUDUYYPFuk'}, headers=get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID))

```

위와 같이 호출하시면 될것같습니다.

감사합니다.

**Comment by jungmyounghwan** [comment]
`uri = '/report-download'
method = 'GET'
authtoken = str(b.json()['downloadUrl'])

print( )
print(authtoken)

result = authtoken.split('=')
result = result.pop(1)

print( )
print(result)

c = requests.get(BASE_URL + uri, params={'authtoken' : result}, headers=get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID))

print( )
print("response status_code = {}".format(c.status_code))
# print("response body = {}".format(c.json()))`


`response status_code = 200
response body = {'reportJobId': 1601265812, 'statDt': '2022-08-31T15:00:00Z', 'updateTm': '2022-08-31T15:00:00Z', 'reportTp': 'AD', 'status': 'BUILT', 'downloadUrl': 'https://api.naver.com/report-download?authtoken=%2BlJS6TuhlTaKWk5gQsCrFkHalBXbZAbOXOiH%2Bdfejz0fA%2BpD6qI2YQwHYVShI543PsKKX4GzrFPT6IzwH5K7IHiWbY1sz4WG', 'regTm': '2022-09-05T01:41:36Z', 'loginId': 'rtpia11'}

https://api.naver.com/report-download?authtoken=%2BlJS6TuhlTaKWk5gQsCrFkHalBXbZAbOXOiH%2Bdfejz0fA%2BpD6qI2YQwHYVShI543PsKKX4GzrFPT6IzwH5K7IHiWbY1sz4WG

%2BlJS6TuhlTaKWk5gQsCrFkHalBXbZAbOXOiH%2Bdfejz0fA%2BpD6qI2YQwHYVShI543PsKKX4GzrFPT6IzwH5K7IHiWbY1sz4WG

response status_code = 200`


report를 출력하거나 다운 받으려면 어떻게 해야하나요?

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 대용량 보고서 담당자입니다. 

해당 url (/report-download) 의 return 헤더는 아래와 같습니다.

content-disposition: attachment; filename="{파일명}.tsv"
content-length: {length}
content-type: application/octet-stream; charset=UTF-8

따라서 json으로 읽으실 때 에러가 발생하실 것 같습니다.
리턴받은 content를 tsv 형식으로 읽어 주시기 바랍니다.

감사합니다.
