### ISSUE TITLE
/report-download

### ISSUE THREAD

**Issue by jungmyounghwan** [naver/searchad-apidoc#644]
uri = '/report-download'
method = 'GET'
authtoken = str(b.json()['downloadUrl'])
result = authtoken.split('=')
result = result.pop(1)

c = requests.get(BASE_URL + uri, params={'authtoken' : result}, headers=get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID))

print("response status_code = {}".format(c.status_code))

-----------------------
response status_code = 200

report를 다운하거나 출력하려면 어떻게 해야 할까요?

**Comment by naver-searchad** [comment]
https://github.com/naver/searchad-apidoc/issues/643#issuecomment-1246406172
에서 답변 드렸습니다.
