### ISSUE TITLE
stat-reports invalid signature 오류 관련 문의

### ISSUE THREAD

**Issue by user-cyshin** [naver/searchad-apidoc#646]
안녕하세요,
stat report post api 관련 아래와 같이
실행 결과 403 invalid signature 오류가 발생하여 어떤 부분이 오류인지 확인이 어려워
문의 드립니다. 

`def get_header(method, uri, api_key, secret_key, customer_id):
    timestamp = str(round(time.time() * 1000))
    signature = signaturehelper.Signature.generate(timestamp, method, uri, SECRET_KEY)
    return {'Content-Type': 'application/json; charset=UTF-8', 'X-Timestamp': timestamp, 'X-API-KEY': API_KEY, 'X-Customer': str(CUSTOMER_ID), 'X-Signature': signature}

#API액세스
BASE_URL = 'https://api.naver.com/'
API_KEY = '<API_KEY>'
SECRET_KEY = '<SECRET_KEY>'
CUSTOMER_ID = '<CUSTOMER_ID>'

#API 구현
uri='/stat-reports'
method='POST'
r = requests.post(BASE_URL + uri, params={'reportTp' : "AD_DETAIL", 'statDt' : "20220905"}, headers=get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID))

print("response status_code={}".format(r.status_code))
print("response body={}".format(r.json()))`

[result]
response status_code=403
response body={'signature': '3INVNSiirTp3HwmLz/K1myWRfPqalpqN9XjKKCT7pyM=', 'title': 'Invalid Signature', 'detail': 
"Signature '3INVNSiirTp3HwmLz/K1myWRfPqalpqN9XjKKCT7pyM=' 
is invalid.", 'status': 403, 
'type': 'urn:naver:api:problem:invalid-signature'}

**Comment by naver-searchad** [comment]
@user-cyshin 
안녕하세요. 네이버 검색광고 API 입니다.

코드를 보니 요청이 https://api.naver.com//stat-reports 로 전달되는것으로 보입니다.
BASE_URL의 마지막 슬래쉬를 삭제하시고 테스트 해보시면 될것 같습니다.

```
BASE_URL = 'https://api.naver.com'
```

감사합니다.

**Comment by user-cyshin** [comment]
해결되었습니다! 감사합니다!
