### ISSUE TITLE
node "type":"urn:naver:api:problem:invalid-signature" 질문입니다 

### ISSUE THREAD

**Issue by jjsk109** [naver/searchad-apidoc#647]
const BASE_URL = 'https://api.naver.com';
const api_url = "/customer-links";
const accessKey = "01000000000cac9bfd3acf681edebc6d0419aef24e4b12ad82857abd34dc447eda34d83fa7";
const secretKey = "";
const customerid = "2657655";
const timestamp = moment().unix();

const options = {
  url: `${BASE_URL}${api_url}`,
  headers: {
    'X-Timestamp': timestamp,
    'X-API-KEY': accessKey,
    'X-Customer': customerid,
    'X-Signature': secretKey,
  }
};
request.get(options, function (error, response, body) {
  console.log(body);
  if (!error && response.statusCode == 200) {
    res.writeHead(200, { 'Content-Type': 'text/json;charset=utf-8' });
    res.end(body);
  } else {
    console.log('error = ' + response.statusCode);
    console.log(error)
  }
});

403 "type":"urn:naver:api:problem:invalid-signature" 에러가 발생을 합니다 
셈플을 보고 만들고 있는데 어느 부분이 문제인지 모르겠습니다

**Comment by naver-searchad** [comment]
@jjsk109 
안녕하세요. 네이버 검색광고 API 담당자입니다.

X-Signature 에는 secretkey 를 넣는게 아니라 서명을 생성하셔서 요청주셔야합니다.

https://naver.github.io/searchad-apidoc/#/samples 해당 페이지의 서명생성 부분을 참고부탁드리겠습니다

(secretkey 는 공개가 되면 안되어서 글에서 제거했습니다)

감사합니다.
