### ISSUE TITLE
네이버 검색광고 클라이언트 대상으로 리포트를 출력해서 가공을 할건데 어느 api인가요?

### ISSUE THREAD

**Issue by jjsk109** [naver/searchad-apidoc#648]
네이버 검색광고 클라이언트 대상으로 리포트를 출력해서 가공을 할건데 어느 api인가요?

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 API입니다. 

아래 API 들이 광고 보고서 지표를 조회할수 있는 API입니다. 

http://naver.github.io/searchad-apidoc/#/tags/MasterReport
http://naver.github.io/searchad-apidoc/#/tags/StatReport
http://naver.github.io/searchad-apidoc/#/tags/Stat

감사합니다.
