### ISSUE TITLE
답변 좀 부탁드려요.

### ISSUE THREAD

**Issue by jungmyounghwan** [naver/searchad-apidoc#649]
uri = '/report-download'
method = 'GET'
authtoken = str(b.json()['downloadUrl'])
result = authtoken.split('=')
result = result.pop(1)

c = requests.get(BASE_URL + uri, params={'authtoken' : result}, headers=get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID))

print (c)
print("response status_code = {}".format(c.status_code))
print("response body = {}".format(c.json()))

----

<Response [200]>
response status_code = 200

print("response body = {}".format(c.json()))
>> 오류가 나는데 리포트 내용을 보려면 어떻게 해야하나요?

**Comment by naver-searchad** [comment]
https://github.com/naver/searchad-apidoc/issues/643#issuecomment-1246406172
에서 답변 드렸습니다.
