### ISSUE TITLE
Valid values for "fields" of /stats API are not exhaustive

### ISSUE THREAD

**Issue by sooheon** [naver/searchad-apidoc#65]
The docs mention the following:

impCnt
clkCnt
ctr
cpc
avgRnk
ccnt
recentAvgRnk
recentAvgCpc

However I have found in the DailyStatMap response that "salesAmt" is another valid field. 

Are there other such undocumented valid fields, and if so, do any of them pertain to the various conversion metrics (cost per conversion, 전환매출액, 광고수익률, etc.)

**Comment by naver-searchad** [comment]
Currently, request metrics related to conversion metrics to the /stats API are ccnt(전환수), convAmt(전환매출액), crto(전환율).

roas(광고수익률) is not a request-able indicator but it can be calculated with the salesAmt and convAmt that are provided.

**Comment by sooheon** [comment]
Thank you! I would make a PR to add this information, but it seems the docs are not actually open source.
