### ISSUE TITLE
GET /ncc/targets 요청시 TIME_WEEKLY_TARGET 타입정보가 없습니다.

### ISSUE THREAD

**Issue by moosin76** [naver/searchad-apidoc#650]
광고노출 전략 요일, 시간 설정을 하였습니다만 
GET /ncc/adgroups/grp-a001-01-000000025680687
요청시 targets의 내용에 MEDIA_TARGET 와 PC_MOBILE_TARGET의 정보만 있고
TIME_WEEKLY_TARGET정보가 없습니다.
혹시나 해서 GET /ncc/targets 요청시
{
  ownerId : 'grp-a001-01-000000025680687',
  types : ['TIME_WEEKLY_TARGET']
}
요청을 해도  MEDIA_TARGET 와 PC_MOBILE_TARGET 정보만 있습니다.
TIME_WEEKLY_TARGET 정보를 얻으려면 어떻게 해야 하나요?

**Comment by naver-searchad** [comment]
@moosin76 안녕하세요? 네이버 검색광고 API입니다.
타겟팅 관련 API는 아래 릴리즈 노트의 4월 26일 공지를 참고하시기 바랍니다.
http://naver.github.io/searchad-apidoc/#/release-notes

감사합니다.

**Comment by moosin76** [comment]
빠른답변 감사합니다.
위 내용을 보고 아래와 같이 요청하였습니다.

GET /ncc/criterion/grp-a001-01-000000025680687
{
  type : 'SDWED0618'
}

요청시 500 ERROR가 발생합니다. ㅜㅜ

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고입니다.
아래와 같이 호출 하셔야 합니다.

```
GET /ncc/criterion/{광고 그룹 ID}?type={CriterionDictionaryType}
```

```
GET /ncc/criterion/grp-a001-01-000000025680687?type=SD
```

**Comment by moosin76** [comment]
감사합니다 해결되었네요

**Comment by jjsk109** [comment]
위 내용을 보고 적용 중 문의 드립니다 

```
$bidding_value = $api->GET('/ncc/criterion/grp-a001-02-000000025126072?type=AG');
print_r($bidding_value);
```

GET /ncc/criterion/grp-a001-02-000000025126072?type=AG

Array ( [signature] => j9pCPxbXrs6REOOw8L1mQVFoLTrpD4j+DxrwXLgrRuA= [status] => 403 [type] => urn:naver:api:problem:invalid-signature [title] => Invalid Signature [detail] => Signature 'j9pCPxbXrs6REOOw8L1mQVFoLTrpD4j+DxrwXLgrRuA=' is invalid. )

이렇게 나오고 있는데 어디가 문제인지 확인 가능할까요?

**Comment by naver-searchad** [comment]
@jjsk109 안녕하세요 네이버 검색광고 API 담당자입니다.

서명 (signature) 생성이 잘못된것으로 보이는데요.

서명 생성시 uri 를 넣으실때 parameter 를 제거하고 넣으셨는지 확인 부탁드리겠습니다.

( ?type=AG 는 제외하고, /ncc/criterion/grp-a001-02-000000025126072 로 넣으셔야합니다 )

감사합니다.
