### ISSUE TITLE
/stat api 문의

### ISSUE THREAD

**Issue by mkms1104** [naver/searchad-apidoc#651]
아무리 조회해도 결과가 나오지를 않네요

200 응답은 받고 있는데 존재하는 id 값(캠페인, 소재, 그룹)으로 아무리 요청해도

응답 결과 값이 없네요..

preset last30days

stat 리포트 부분 결과 값 (reportTp : AD)
20220914	939281	cmp-a001-01-000000003822545	grp-a001-01-000000019716191	nkw-a001-01-000004498788768	nad-a001-01-000000152526674	bsn-a001-00-000000000082004	8753	M	2	0	0.0	4	0
20220914	939281	cmp-a001-01-000000003822545	grp-a001-01-000000019716191	nkw-a001-01-000004498788768	nad-a001-01-000000201504210	bsn-a001-00-000000000082004	8753	M	1	0	0.0	2	0
20220914	939281	cmp-a001-01-000000003822545	grp-a001-01-000000019716191	nkw-a001-01-000004531113056	nad-a001-01-000000152526674	bsn-a001-00-000000000082004	8753	M	2	0	0.0	4	0
20220914	939281	cmp-a001-01-000000003822545	grp-a001-01-000000019716191	nkw-a001-01-000004531113056	nad-a001-01-000000199334462	bsn-a001-00-000000000082004	33421	M	1	0	0.0	2	0
20220914	939281	cmp-a001-01-000000003822545	grp-a001-01-000000019716191	nkw-a001-01-000004531113056	nad-a001-01-000000199334462	bsn-a001-00-000000000082004	8753	M	1	0	0.0	1	0
20220914	939281	cmp-a001-01-000000003822545	grp-a001-01-000000019716191	nkw-a001-01-000004531113056	nad-a001-01-000000201504210	bsn-a001-00-000000000082004	33421	M	1	0	0.0	1	0
20220914	939281	cmp-a001-01-000000003822545	grp-a001-01-000000019716191	nkw-a001-01-000004531113058	nad-a001-01-000000152526674	bsn-a001-00-000000000082004	98128	M	2	0	0.0	4	0
20220914	939281	cmp-a001-01-000000003822545	grp-a001-01-000000019716191	nkw-a001-01-000004531113058	nad-a001-01-000000199334462	bsn-a001-00-000000000082004	98128	M	2	0	0.0	4	0
20220914	939281	cmp-a001-01-000000003822545	grp-a001-01-000000019716191	nkw-a001-01-000004531113058	nad-a001-01-000000201504210	bsn-a001-00-000000000082004	98128	M	3	0	0.0	6	0
20220914	939281	cmp-a001-01-000000003822545	grp-a001-01-000000019716192	nkw-a001-01-000003470542641	nad-a001-01-000000152540106	bsn-a001-00-000000000082004	139871	M	1

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API 입니다.

ids 파라미터를 사용할 때
id의 종류는 한 가지로(캠페인, 소재, 그룹) 통일하셔야 합니다.
요청에 사용하셨던 request param 을 자세히 알려주시면 더 안내해 드릴 수 있을 것 같습니다.

감사합니다.

**Comment by mkms1104** [comment]
https://api.naver.com/stats

id = "cmp-a001-02-000000003574727"
fields = "[ccnt, convAmt]"
datePreset = "last7days"

=> 400 Bad Request: "{"code":11001,"message":"잘못된 파라미터 형식입니다."}"

**Comment by mkms1104** [comment]
@naver-searchad
https://api.naver.com/stats

ids = "cmp-a001-02-000000003574727, cmp-a001-01-000000003822572"
fields = "[ccnt, convAmt]"
timeRange= "{since: 2022-09-21, until: 2022-09-21}"

=> 400 Bad Request: "{"code":11001,"message":"잘못된 파라미터 형식입니다."}"

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

 > fields=[ccnt, convAmt] 형태로 파라미터 전달을 주시는 것 같습니다.
> 아래와 같이 fields 의 각 항목은 string 형태로 처리될 수 있도록 " 이 추가해 주시면 정상 동작 할 것으로 보입니다.
> /stats?id=cmp-a001-02-000000003574727&fields=["ccnt","convAmt"]&datePreset=last7days

감사합니다.
