### ISSUE TITLE
시간대별 전환매출 조회여부 문의드립니다.

### ISSUE THREAD

**Issue by ChoiYoungWoo2197** [naver/searchad-apidoc#652]
/stats 요청시 (시간대별) 시간대별로 전환매출액을 알 수 있을까요?? 알 수 있다면 변수이름이 어떻게 되는지 궁금합니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

담당자에게 문의한 결과 `breakdown=hh24` 파라메터를 추가하면 확인이 가능하다고 합니다.

감사합니다.
