### ISSUE TITLE
/stat-reports post 에러 문의 드립니다.

### ISSUE THREAD

**Issue by jjsk109** [naver/searchad-apidoc#653]
const BASE_URL = 'https://api.naver.com';
const api_url = "/stat-reports";
const accessKey = "";
const secretKey = "";
const customerid = "";
const timestamp = moment().unix();
const hmac = CryptoJS.algo.HMAC.create(CryptoJS.algo.SHA256, secretKey);
const hash = hmac.finalize();
const parm = "";
const nowDate = moment().format('YYYYMMDD');
const body_object = {
    "reportTp": "AD",
    "statDt": nowDate,
}

const res = await fetch(`${BASE_URL}${api_url}${parm}`, {
  method: 'POST',
  headers: {
    'X-Timestamp': timestamp,
    'X-API-KEY': accessKey,
    'X-Customer': customerid,
    'X-Signature':  hash.toString(CryptoJS.enc.Base64),
  },
  body: JSON.stringify(body_object),
});

리포트 생성 /stat-reports 했을때

결과가 
{ code: 500, message: 'Internal Server Error' }
이렇게 나옵니다 

'content-type': 'application/json;', 추가 해서 확인 할경우
{ code: 11001, message: '잘못된 파라미터 형식입니다.' }
이렇게 나옵니다
환경은 node.js 입니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

리포트 날짜는 전날로 전달해 주어야 합니다.
statDt 를 yesterday 로 만들어 주시면 될 것 같습니다.

감사합니다.
