### ISSUE TITLE
Campaign 데이터에 editTm 에 대해 문의드립니다.

### ISSUE THREAD

**Issue by for2gles** [naver/searchad-apidoc#654]
안녕하세요
캠페인 데이터를 가지고 오는데에 질문이 있습니다.

### 상황
캠페인 데이터를 정리할 때, 'deleted_at' 혹은 'paused_at' 의 데이터가 존재하지않아
status 가 'PAUSED' 혹은 'DELETED' 일 경우 'editTm' 의 값으로 Paused 가 되었거나 Deleted 되었을 경우를 추정하였었습니다.

### 문제
현재 Paused 상태이고, editTm 이 8월 19일 인 캠페인에서 9월 11일에 Stat 값이 있는것을 발견하였습니다.
예상 결과 -  Paused 상태이고 editTm 이 8월 19일이기 때문에 해당 캠페인은 8월 19일에 Paused가 되어 그 이후에는 데이터가 존재하면 안됩니다.

### 질문
1. editTm 의 값은 정확히 언제 변경이 되는건가요? 상태가 변경할때에는 editTm이 변경되지 않나요?
2. deleted_at 혹은 paused_at 의 값을 추정할 수 있는 다른 방법이 있을까요?

**Comment by naver-searchad** [comment]
@for2gles 안녕하세요? 네이버 검색광고 API입니다.

네이버 검색광고 광고 데이터의 `editTm` 값은 `광고주가 해당 광고데이터를 수정한 시각`입니다. 예를 들어 캠페인의 경우 userLock 값이 바뀐다거나, dailyBudget 값이 바뀌는 경우 최종 변경된 시각을 나타냅니다.

문의하신 Paused 상태(아마도 userLock: true 를 말씀하시는듯 합니다.) 변경 이후에도 캠페인의 다른 값이 바뀐경우 `editTm`이 바뀌게 됩니다.

deleted_at의 경우 네이버 검색광고는 `광고주가 삭제한 광고 데이터`에 대해서는 API를 통해 전송하지 않습니다. (보고서의 경우 예외)

감사합니다.

**Comment by for2gles** [comment]
자동적으로 상태값이 변경될 경우에는 언제 바뀌었는지 데이터를 받을 수 없을까요?
예를들어 예산을 다 썼을경우 State 가 변경되는데 언제 바뀌었는지는 알수 없는건가요?

**Comment by naver-searchad** [comment]
@forgles 상태 변경에 따른 시간은 따로 제공하고 있지 않습니다.

감사합니다.
