### ISSUE TITLE
네이버 검색광고 카카오페이구매 전환 스크립트 관련 문의

### ISSUE THREAD

**Issue by 92hundredxxx** [naver/searchad-apidoc#656]
네이버 검색 광고 구매 전환 스크립트 관련하여 문의드립니다.
 
최근 많은 쇼핑몰에서 ‘카카오페이 구매’ 서비스를 연동하고 있는데요.
네이버 검색광고에서도 카카오페이 구매 전환을 측정할 수 있는 방법이 있을지 문의드립니다. 
 
감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API 담당자입니다. 

이 공간에서는 네이버 검색광고 API 서비스에 대한 기술 지원을 제공드리고 있으며 저희 내부 사정이기는 하나 검색광고 API와 전환 스크립트를 관리하는 부서가 서로 달라 
전환 스크립트에 관련된 기술지원 및 정책 답변은 드리지 못하고 있습니다. 

물론 저희가 담당자를 찾은 후 내용을 확인해서 이곳에서 답변을 드릴수는 있습니다만 이렇게 진행되면 아무래도 담당자를 찾는 등의 작업으로 인해 오랜 시간이 소요될수 있다는 단점이 있습니다. 그래서 고객센터로 바로 문의를 주시는 편이 바로 담당자에게 문의가 전달 될 수 있어 훨씬 더 빠르게 답을 받으실수 있는 방법이라고 생각 됩니다. 
아래는 네이버 검색광고 고객센터 연락처 입니다. 
https://saedu.naver.com/help/inquiry/bridge.naver
그리고 제 개인적인 경험입니다만 전화 보다는 실시간 채팅쪽이나 메일이 바로 질문 내용을 정리 전달 할수 있어서 약간이지만 더 빠르게 답변 드리고 있는 것으로 보입니다. 

감사합니다.
