### ISSUE TITLE
키워드 도구의 검색량과, 데이터랩 api의 검색비율 차

### ISSUE THREAD

**Issue by tjdcks106** [naver/searchad-apidoc#658]
<img width="768" alt="image" src="https://user-images.githubusercontent.com/36146098/192915735-3ecc5bb5-9a85-4349-af5d-b64c1998ac4d.png">

![image](https://user-images.githubusercontent.com/36146098/192915829-d072b200-8f38-4db0-a90a-88e4f6e3bd96.png)

안녕하세요
키워드 분석을 위해 네이버 데이터랩 api와 네이버 검색광고 api를 두고 테스트 중에 있습니다.

[네이버 데이터랩 api](https://developers.naver.com/docs/serviceapi/datalab/search/search.md#%ED%86%B5%ED%95%A9-%EA%B2%80%EC%83%89%EC%96%B4-%ED%8A%B8%EB%A0%8C%EB%93%9C-%EA%B0%9C%EC%9A%94)에서는 조회 기간동안의 최대값을 100으로 두고 상대적 비율을 제공하며,
네이버 검색광고 키워드 도구에서는 웹에서 조회시 월별 검색수를 조회할 수 있습니다.

첨부 사진은 "코웨이정수기"라는 키워드에 대해 2021-09~2022-08까지 "네이버 데이터랩 api"를 통해 조회한 비율과
"네이버 검색광고 키워드 도구"에서 조회한 월별 검색수로 계산한 비율을 비교한 표입니다.

보이는것처럼 두 비율상의 차이가 있는데
로직상의 차이가 있는것인지, 어떤 값이 더 신뢰도가 있는지 문의드립니다.

**Comment by naver-searchad** [comment]
@tjdcks106 
안녕하세요? 네이버 검색광고 API입니다.

키워드 도구의 검색수는 검색수 조회기능이 아니라 연관키워드를 확인하고 연관 키워드 간의 비교를 돕기 위해 검색수를 보조적으로 제공하고 있습니다. 그렇기 때문에 절대적인 검색수가 아니라 검색수 볼륨에 따른 Scaling이 적용되어 있습니다. (예.십만 이상이면 백의 자리까지만 식별 가능)
만약 연관키워드 조회가 아니라 키워드 검색수 확인을 원하시면 데이터랩을 활용하셔야 합니다.

검색광고에 관련되지 않은 검색광고 키워드 도구 API의 과도한 요청은 모니터링 대상이 될 수 있으니 유의하시기 바랍니다.

감사합니다.

**Comment by tjdcks106** [comment]
답변 감사합니다.

그럼 키워드에 대한 검색수 변화는 데이터랩의 비율이 더 정확하다고 이해해도 될까요?
