### ISSUE TITLE
StatReport Get 404 에러 답변 부탁드립니다

### ISSUE THREAD

**Issue by Byeonminu** [naver/searchad-apidoc#659]
stat report를 생성하고 가져오는 과정에서, status가 REGIST상태이다가, RUNNING 상태로 바뀐 후 갑자기 status code가 404가 됩니다.

`response.json(): {'code': 20011, 'message': '보고서를 찾을 수 없습니다.'}`
와 같은 response를 응답합니다.
생성중(RUNNING)이다가 갑자기 사라진 것일까요?

빠른 답변 부탁드립니다.

**Comment by Byeonminu** [comment]
@naver-searchad 답변 부탁드립니다

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

> 해당 보고서가 DELETE request를 요청하여 삭제되었을 가능성이 클 것 같습니다.
> 해당 현상이 지속되는 경우
> reportJobId 를 첨부해 주시면 더 자세히 확인할 수 있을 것 같습니다.


감사합니다.

**Comment by Byeonminu** [comment]
@naver-searchad 
report post 요청 후 1초 주기로 get 요청을 하고 있습니다. 1초 주기로 단순히 get request를 하는 것이기 때문에 delete request를 하지는 않는 상태입니다. 
report job id는 1623323598입니다.

**Comment by Byeonminu** [comment]
@naver-searchad 
삭제 요청 시각은 언제인지 알 수 있을까요? 삭제 시각이 삭제 요청 시각을 말씀하시는 걸까요?

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.
삭제시각은 서버에서 실재 삭제가 이뤄진 시각입니다. 삭제 요청시각은 삭제시각과 같거나 1,2초 전으로 보시면 될듯 합니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

리포트 리스트 전체 삭제 요청이 들어왔음을 확인하였습니다.
다만 해당 요청을 주신 ID 가 대행사로부터 들어온 삭제 요청으로 보입니다.

감사합니다.

**Comment by Byeonminu** [comment]
@naver-searchad 
안녕하세요
혹시 report를 생성하고 주기적으로 delete 해주지 않으면, 계속 쌓이게 되는지 궁금합니다.
만약 많은 report가 삭제되지 않고 쌓여있으면 임의로 삭제될 수도 있는지도 궁금합니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API 입니다.

만들어진 리포트가 100개에 도달할 경우
새로운 report 생성시 오래된 리포트부터 삭제하여 100개가 유지됩니다.

감사합니다.
