### ISSUE TITLE
No clean way to query for performance of nccKeywordId

### ISSUE THREAD

**Issue by sooheon** [naver/searchad-apidoc#66]
The docs for the /estimate/performance [endpoint](https://naver.github.io/searchad-apidoc/#/operations/POST/~2Festimate~2Fperformance~2F%7Btype%7D) show that the path params may be of type "keyword" or "id". For "keyword", one must also supply the "device". 

However, nccKeywordIds should already be disambiguated (as to whether they are meant for PC, MOBILE, or BOTH). But when POSTing to the endpoint with "id", I still must supply a "device", which overrides the actual device of the nccKeywordId (AFAICT). This defeats the purpose of using nccKeywordId, as it is then functionally the same as a keyword. nccKeywordIds should be unique, and include the "device" information.

This would be alleviated by adding a "device" property to the [AdKeyword](https://naver.github.io/searchad-apidoc/#/operations/GET/~2Fncc~2Fkeywords%7B%3Fids%7D) response. As it is now, I don't think there is a clean way to go from `[keyword-string, device] <=> nccKeywordId`.

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API 입니다. 한국어 가능하실 것으로 예상되어 한국어로 답변 드립니다.
혹 영문 답변이 필요하시면 말씀 부탁드립니다. 

hi. this is NAVER searchad API service manager. 

I'm sorry for late reply.
We are expecting you to be able to answer in Korean. If you need an answer in English, please let me know.

문의 주신 키워드 견적 기능 (Estimate: get (performance)은 두가지 인자를 사용하실 수 있습니다.
키워드 혹은 등록 키워드 아이디 (nccKeywordId) 양자간의 차이는 품질지수를 반영하느냐 하지 않느냐 
에 있습니다. 키워드를 입력 인자로 사용하신 경우는 품질지수를 키워드 등록 시 최초로 받게 되는 기본 품질지수(4단계)를 적용하여 입찰가에 따른 성과를 계산합니다. 등록 키워드 아이디를 입력하신 경우에는 해당 키워드가 이미 가지고 있는 품질지수를 반영하여 계산합니다. 
등록 키워드 아이디는 디바이스 인자와 무관하며 키워드 역시 무관한 독립 인자로서 키워드 아이디가 특정 노출 디바이스 정보를 가지고 있지 않습니다. 
추가로 네이버 검색광고에서 등록 키워드 아이디는 노출 디바이스의 정보를 담고 있지 않습니다. 
등록 키워드 아이디가 속한 그룹의 매체 설정을 통해 디바이스를 특정할수는있게지만 
견적 기능은 특정 입찰가로 특정 키워드를 특정 환경에서 광고 집행할때 예상되는 성과를 제공하는 
기능이므로 디바이스를 특정해서는 안됩니다. 노출해 보지 않는 디바이스에서의 성과 역시 확인할 필요가 있는 경우가 있기 때문입니다. 

마지막으로 다바이스는 실제로 기기를 나타내는 것은 아닙니다. 저희 네이버 검색광고에서는 기기 타겟팅이 존재하지 않습니다. 단, 광고가 노출 될 수 있는 광고 매체별로 모바일에 노출 되기위한 매체인지 PC에 노출 되기 위한 매체인지 분류가 될 뿐으로 실질적인 기기 타게팅이라기 보다는 매체 분류 기준이라고 이해해 주시면 되겠습니다. 

감사합니다.

**Comment by naver-searchad** [comment]
추가 말씀이 없으셔서 해결이 된것으로 일단 처리 하겠습니다. 필요시 다시 오픈 부탁드립니다.
