### ISSUE TITLE
네이버 api 요청시(nest js) 헤더 설정 관련 에러가 발생 하는 문제에 대해 질의 드립니다

### ISSUE THREAD

**Issue by hyunsokstar** [naver/searchad-apidoc#660]
github:

https://github.com/hyunsokstar/naver-api-test

<br />

back:

npm run start:dev

front:

npm run dev

<br />

controller 에서  http://localhost:8000/naver_add  요청을 받으면 네이버 광고에  api 요청(https://naver.github.io/searchad-apidoc/#/guides) 을 날려서 응답 받은걸 다시 프론트로 보내려고 하는데요

<br />

그런데 헤더 설정이 잘못되어서인지

import { NaverAddService } from './naver_add.service';
import { SuccessInterceptor } from './../common/interceptors/success.interceptor';
import { Controller, Get, Req, UseInterceptors } from '@nestjs/common';
import * as CryptoJS from 'crypto-js'

var method = "GET";
var api_url = "/keywordstool";
var timestamp = Date.now() + '';
const accessKey = "01000000000f85a84ea950600f3a5a2214f5f379afa3f09898cbf7a1699007c1167fe2e247"
var secretKey = "AQAAAAAPhahOqVBgDzpaIhT183mv52WgZFJyJCX8PE87IzXJwg==";

var method = "GET";
var timestamp = Date.now() + '';
var secretKey = "YOUR_SECRETKEY";
var hmac = CryptoJS.algo.HMAC.create(CryptoJS.algo.SHA256, secretKey);
hmac.update(timestamp + '.' + method + '.' + api_url);
var hash = hmac.finalize();
hash.toString(CryptoJS.enc.Base64);

@Controller('naver_add')
@UseInterceptors(SuccessInterceptor)
export class NaverAddController {

    constructor(
        private readonly naverAddService: NaverAddService
    ) { }

    @Get()
    getNaverAddInfo() {
        const api_key = process.env.API_KEY;
        const secret_key = process.env.SECRET_KEY;
        const customer_id = process.env.CUSTOMER_ID;

        const options = {
            url: 'https://api.naver.com/keywordstool?hintKeywords=' + "skilnote" + '&showDetail=1',
            headers: {
                'X-Timestamp': timestamp, 'X-API-KEY': api_key,
                'X-API-SECRET': secret_key, 'X-CUSTOMER': customer_id, 'X-Signature': hash.toString(CryptoJS.enc.Base64)
            }
        };
        const result = this.naverAddService.getNaverAddInfo(options).pipe().subscribe()

        console.log("result : ", result);
    }

}

요청 자체는 성공으로 출력 되지만
![image](https://user-images.githubusercontent.com/32297817/193172613-bff5d551-0bd6-4fd7-9f1b-2a7fd18a51de.png)

콘솔에 이런 에러가 발생 합니다.
![image](https://user-images.githubusercontent.com/32297817/193172662-18d25b79-e63f-468d-9b37-657667fc70b7.png)

혹시 이와 관련한 해결 방법 알려주시면 대단히 감사하겠습니다 ~!

**Comment by hyunsokstar** [comment]
친절한 답변 감사합니다. 그런데 일단 로그를 확인해보면  X-API-KEY 가 헤더에 출력 됩니다 그래도 에러가 발생하는데 코드 상으로 헤더 설정에 문제가 있는지는 확인해주시는게 불가할까요? 좀더 상세하게 알려주시면 대단히 감사하겠습니다.

**Comment by hyunsokstar** [comment]
그리고 한가지 더 여쭐게 있는데 api 요청을 프론트 엔드나 백엔드 둘중에서 백엔드에서 해야 하는게 기본 원칙이라고 할수 있을까요?

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API 입니다.

API호출 할때 사용하신 트랜젝션 ID를 알려주시면 로그를 찾아 보도록 하겠습니다. 하지만 아래의 코드를 보면 secretKey가 아래와 같이 재정의가 된게 문제가 아닐까 추측됩니다.
```
var secretKey = "YOUR_SECRETKEY";
```


네이버 검색광고 API를 호출하는 Client의 종류에 대해서는 저희가 강제하지 않습니다. 검색광고 API기준에 적합하게 호출하시면 됩니다.

감사합니다.

**Comment by hyunsokstar** [comment]
답변 감사합니다. 해당 부분을 수정 했는데요 여전히 에러가 발생 합니다 그런데 api 호출시 트랜잭션 아이디가 커스토머 아이디인가요?
CUSTOMER_ID는 "2670737"  입니다  한가지더 혹시 javascript 나 node js , nest js 로 api 요청하는 예제가 있을까요?

**Comment by hyunsokstar** [comment]
아직 문제를 해결 못해서 혹시 이문제 답변 해주실수 없나요?

**Comment by naver-searchad** [comment]
@hyunsokstar 
안녕하세요? 네이버 검색광고 API 입니다.

<img width="555" alt="image" src="https://user-images.githubusercontent.com/18188635/193989177-b4c76b3b-98a8-4dcd-ba39-a086fd80b7b4.png">

전체 로그를 볼수 없어서 정확하지 않지만, 해당 부분이 Request Header 로 보이고, Controller 에서 세팅하신 헤더가 제대로 전달되지 않는것으로 보입니다.

naverAddService.getNaverAddInfo 내부의 로직을 한번 검토해보시는것이 좋을것 같습니다.

javascript 로 된 예제는 제공되지 않습니다.
다른 언어로 된 예제 ( https://naver.github.io/searchad-apidoc/#/samples ) 참고 부탁드리겠습니다.
