### ISSUE TITLE
Naver Ads API. How to get detail click information

### ISSUE THREAD

**Issue by Dragon-rain** [naver/searchad-apidoc#662]
I need to know ip addres, and device information when somebody click my link, 

![example](https://user-images.githubusercontent.com/60503771/194188995-2afa1b5c-2fd8-4351-aba7-ff2caec8bcd1.png)

is there any possibility to get this data from naver ads?

If it's possible, so how to get this data?

**Comment by naver-searchad** [comment]
hello. I am in charge of Naver Search Ads API.

You sent your inquiry to the wrong channel. This page only deals with API services and does not include ad click tracking information you inquired about. Please contact us through the link below.

[https://saedu.naver.com/support/inquiry.naver?lang=en](https://saedu.naver.com/support/inquiry.naver?lang=en)

**Comment by Dragon-rain** [comment]
oh thank you
