### ISSUE TITLE
/stats 데이터에 impCnt 은 0 인데 clkCnt 와 salesAmt 값이 있는건 어떤상황일까요?

### ISSUE THREAD

**Issue by for2gles** [naver/searchad-apidoc#663]
안녕하세요 질문 그대로 /stats 데이터를 받았습니다.
일부 데이터에 impCnt 값이 0 인데, clkCnt, salesAmt 값이 있는 경우가 있더라구요.

혹시 어떤 상황인건지 알 수 있을까요?

**Comment by for2gles** [comment]
안녕하세요 호출정보입니다.

- Request Header
X-Customer: 684966 (토큰과 시그니처는 가리겠습니다.)
method: get
request url: /stats


- Request Prarms (Body)
fields: ["impCnt","clkCnt","salesAmt","ccnt","convAmt"]
id: nad-a001-02-000000139902380
timeRange: {
    since: '2022-10-08',
    until: '2022-10-08',
}

- API 호출 시점 
Tue, 11 Oct 2022 06:38:55 GMT = 2022-10-11 15:38:55 KST

- Transaction Id
C3ON28PPPHGP0

이 때 아래와 같은 결과값을 받습니다.
impCnt: 0
clkCnt: 1
salesAmt: 396
ccnt: 0
convAmt: 0

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

00시 전후로 날짜가 바뀔 때 발생 가능성이 높은 현상으로
전날 노출된 광고가 다음날 클릭된 경우 발생하는 현상입니다.
감사합니다.

**Comment by for2gles** [comment]
확인 감사드립니다.
