### ISSUE TITLE
/ncc/criterion GN(성별) 관련 질문입니다.

### ISSUE THREAD

**Issue by kaorimikage** [naver/searchad-apidoc#664]
다른 항목은 괜찮은데 해당 항목만 호출할때마다 regTm 와 editTm 이 계속 갱신되고 있습니다.
혹시 내부적으로 무슨 문제가 있는 것인지요?

**Comment by naver-searchad** [comment]
@kaorimikage 
안녕하세요? 네이버 검색광고 API입니다.

호출한 API의 상세 정보를 알려주셔야 합니다.
HTTP Header, HTTP Body를 모두 알려주시기 바랍니다.

추측하자면, 성별 타겟을 사용하지 않음으로 설정한경우, 서버에서 기본 값(모든 성별 노출)을 내려주고 있어서, 호출한 시점의 시각이 내려가게 됩니다.

감사합니다.
