### ISSUE TITLE
네이버 검색 광고 API 사용 간편 인증 방식에 관해 문의드립니다.

### ISSUE THREAD

**Issue by dewberry9** [naver/searchad-apidoc#665]
안녕하세요. 네이버 검색 광고 API 사용 간편 인증 방식에 관해 문의드립니다.

현재 검색 광고 API를 사용하려면 Customer ID, 액세스 라이선스, 비밀키를 수동으로 입력, 사용하게 되어 있는데요,
OAuth 등 간편 로그인 서비스로 해당 계정의 API를 호출할 수 있거나, 여기에 필요한 다른 두 값을 리턴 받을 수 있는지 궁금합니다.

이런 서비스를 운영하고 있지 않다면 운영 예정 사항이 있는지도 궁급합니다.
감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

네이버 검색광고 API를 사용하기 위해서는 광고주센터에서 액세스 라이선스, 비밀키를 발급 받아야 합니다.
또한 OAuth등 다른 간편 인증 방식에 대한 제공은 아직 고려되고 있지 않습니다.

감사합니다.
