### ISSUE TITLE
urn:naver:api:problem:invalid-signature 오류 문의

### ISSUE THREAD

**Issue by dvlpr91** [naver/searchad-apidoc#668]
![image](https://user-images.githubusercontent.com/40349371/197464370-cd24029c-6900-4074-b39c-459141efa38e.png)

참고로, 임폴트시킨 패키지는 다음과 같습니다.
```
import axios from 'axios'
import HmacSHA256 from 'crypto-js/hmac-sha256'
import Base64 from 'crypto-js/enc-base64'
import dayjs from 'dayjs'
```

어떤 문제가 존재하는 것일까요?

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다. 

HmacSHA256 함수의 파라메터 순서가 반대로 되어있는것 같습니다.

참고 : https://cryptojs.gitbook.io/docs/#hmac

감사합니다.

**Comment by dvlpr91** [comment]
앗 나의 실수...

감사합니다 ^^

아~ 정신이 없네~꿀밤 한방 맞아야 정신차릴거같은데
