### ISSUE TITLE
/stats timeIncrement value of 1 returns 400

### ISSUE THREAD

**Issue by sooheon** [naver/searchad-apidoc#67]
Calling /stats GET with following query params:

```
{"query-params":{"ids":["nkw-a001-01-000000338284997","nkw-a001-01-000000338284998"],"fields":["impCnt","clkCnt"],"timeIncrement":"1","datePreset":"lastmonth"}}
```

Returns s status 400. The [docs](http://naver.github.io/searchad-apidoc/#/operations/GET/~2Fstats%7B%3Fid,fields,timeRange,datePreset,timeIncrement,breakdown%7D) say that timeIncrement 1 is a valid option.

**Comment by naver-searchad** [comment]
If timeIncrement = 1, the ids parameter is not supported.
If timeIncrement = 1, the id parameter can be used,
If timeIncrement = allDays, both the id and ids parameters are available.

We are sorry for not specifying in the specific viewable condition.

**Comment by sooheon** [comment]
I see, thank you!
