### ISSUE TITLE
Master Report로 PlaceAd 요청 시 데이터 없음 확인

### ISSUE THREAD

**Issue by exit39** [naver/searchad-apidoc#670]
naver api를 이용하여 소재 정보를 얻으려고 합니다.

기타 다른 소재들은 마스터리포트를 통해 호출이 가능한데 PlaceAd의 경우
실제 Place 소재를 운영하고 있는데도 downloadUrl 정보를 못 받아서 수집이 불가능 합니다.

그래서 대용량 다운로드 보고서에서 제가 신청한 내용을 살펴보니 아래 이미지와 같이 데이터 없음 이라는걸 확인했고,

![naver](https://user-images.githubusercontent.com/64013581/197914837-8054ea1e-4220-4e8f-b4d9-3e1c0aeaae5d.png)

API 명칭이 아니고 PlaceAd라고 Api item명이 나와서 확인해보니 대용량보고서에서 아래와 같이 
플레이스 관련 다운로드 항목이 없던데 대용량 다운로드로는 제공을 안하는 것인지요?

![naver3](https://user-images.githubusercontent.com/64013581/197915147-edaf0f06-f533-4a96-bdaa-169ddc30679e.png)

해당 이미지는 실제 운영하고 있는 플레이스 소재 정보 입니다.
![naver2](https://user-images.githubusercontent.com/64013581/197915254-fe721069-7718-4957-ba5b-e27befc02e26.png)

확인 부탁드리겠습니다.

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 대용량 보고서 담당자입니다. 

문의 주신 마스터 placead는 지역소상공인 광고로 플레이스 광고는 지원하지 않습니다. 
과거 플레이스 광고가 출시되기 이전에는 지역소상공인 광고가 유일한 지역상품이었으므로 placead라는 명칭을 사용했었는데 
새로운 지역광고가 출시되면서  플레이스라는 명칭을 사용하게 되었고, 이미 사용중인 과거 코드를 임의로 수정할수 없어 이러한 혼란을 드리게 되었습니다. 이점 사과 드립니다. 
플레이스 광고 소재  정보는  API 마스터서비스 및 광고관리 시스템 대용량 다운로드 보고서에서 모두 지원하지 않습니다.

감사합니다.

**Comment by exit39** [comment]
마스터 리포트에서는 플레이스 소재에 대해 지원을 안한다면 API 메뉴얼에 있는 내용은 
새로운 지역 광고의 내용인 스마트 플레이스의 내용인건가요? 아니면 과거에 사용하던 플레이스 광고 소재의 내용인데
API의 기능에서는 빠졌는데 API 메뉴얼에서만 남아있다는 건가요?

http://naver.github.io/searchad-apidoc/#/tags/MasterReport

**Comment by naver-searchad** [comment]
@exit39 
안녕하십니까 네이버 검색광고 대용량 다운로드 보고서 담당자입니다. 

혼란을 피하기 위해 우선 상품명 및 서비스(기능)을 정리해서 말씀드립니다.
소상공인 광고 --> 2018년도에 출시된 지역 기반 광고 상품, 즉 과거 부터 존재하던 플레이스 광고 
플레이스 광고 --> 2021년에 출시된 새로운 지역 광고 상품

대용량 다운로드 보고서가 제공 되는 서비스(기능)
API의 MASTER REPORT(URI : /master-reports) 
광고관리 시스템(https://manage.searchad.naver.com/)의 보고서>대용량 다운로드 보고서 > 광고정보 일괄다운로드탭

현황을 말씀 드리면 아래와 같습니다.  

소상공인 광고 
API의 MASTER REPOR : 소재 정보 제공됨(마스터 생성 가능) 
광고관리 시스템(https://manage.searchad.naver.com/)의 보고서 : 소재 정보 제공되지 않음(신규 파일 생성 불가), 단 API를 통해 생성된 마스터 파일은 리스트에 표시됨 

플레이스 광고 
API의 MASTER REPOR : 지원하지 않음 
광고관리 시스템(https://manage.searchad.naver.com/)의 보고서 : 지원하지 않음

감사합니다

**Comment by exit39** [comment]
@naver-searchad 
네 명확한 설명 감사합니다.

결론적으로는 현재 플레이스 광고는 API 지원을 안 한다는 거군요.
과거부터 운영하던 소상공인 광고 관련 소재만 API를 통해서 생성이 가능한 것이구요.

그렇다면 현재 플레이스 광고에 대해 API 지원 계획은 어떻게 될까요?

**Comment by naver-searchad** [comment]
@exit39 
안녕하십니까 네이버 검색광고 대용량 다운로드 보고서 담당자입니다.

대용량 보고서 및 마스터에서 플레이스 광고(21년 출시)를 지원할 계획이나 의사는 없고, 향후에도 지원할 가능성은 희박할 것으로 예상됩니다.  또한 네이버 검색광고 API에서 해당 상품에 대한 "공식 지원" 계획이나 의사는 전혀 없습니다. 

참고로 "공식 지원"이라 함은 기술지원 및 메뉴얼 제공 그리고 정상 작동 보장등을 의미합니다. "공식 지원"이라는 표현을 사용한 이유는 캠페인이나 광고 관련 apI 기능들및 STAT 기능등 API의 여러 기능들을 검색광고 시스템 내 상품들이 공통적으로 사용하고 있으나 특정 상품에 대한 사용 금지 처리를 하지 않았기 때문으로 자체적으로 광고관리시스템의 호출 메세지등을 참고하셔서 API 토큰을 이용해 호출을 하신다면 사용은 가능합니다. 단, 정상적 작동이나 광고관리시스템에서 제공하는 모든 기능을 사용할수 있음을 보장하지 않습니다. 

감사합니다.

**Comment by exit39** [comment]
네 감사합니다.
