### ISSUE TITLE
키워드 문의드립니다.

### ISSUE THREAD

**Issue by for2gles** [naver/searchad-apidoc#671]
안녕하세요.
API에서 요청한 Keyword 와 Naver Ad 대시보드상의 Keyword 목록이 상이하여 확인요청드립니다.

대시보드상에서는 
```
customerId: 167462
adGroupId: grp-a001-02-000000026905960
```

에 대한 키워드 목록이 보이지만
```
{
  method: 'GET',
  url: '/ncc/keywords',
  params: {
    nccAdgroupId: 'grp-a001-02-000000026905960',
  },
  customerId: 167462,
}
```
위에 대한 요청에서는 keyword가 빈 어레이로 리턴됩니다.
(신규 API 도메인, 기존 API 도메인 모두 시도하였으며 동일한 결과가 리턴되었습니다.)

어떤부분때문에 데이터 키워드 목록이 나오지 않는지 확인부탁드립니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

`Naver Ad 대시보드`가 어디를 나타내는지 모르겠지만, 문의하신 광고그룹의 검색광고 시스템에 미삭제된 키워드 개수는 0입니다.

감사합니다.

**Comment by for2gles** [comment]
Naver Search Ad 대시보드 는 여기를 말합니다.
![image (12)](https://user-images.githubusercontent.com/28400932/198494884-26af8003-5eb1-4612-8caf-00cb37ce85ef.png)

여기서는 보이지만 API에서는 안보이는건 어떤것때문일까요?

**Comment by naver-searchad** [comment]
@for2gles 안녕하세요? 네이버 검색광고 API 입니다.

첨부해주신 화면은 쇼핑 캠페인의 쇼핑몰 상품형 광고그룹의 노출 제외 키워드 목록입니다.
쇼핑몰 상품형 광고그룹은 키워드를 등록할 수 없는 광고 그룹 유형입니다.

또한 노출 제외 키워드 목록의 하위에 보여지는 키워드는,  해당 광고그룹의 소재가 노출이되었을때, 유입된 쿼리 키워드 목록입니다.
노출 제외 키워드는 광고주가 원하지 않는 키워드에 광고가 노출이 되는걸 막기위해 사용하는 기능입니다.

감사합니다.

**Comment by for2gles** [comment]
답변 감사드립니다.

지금 제가 파악하는 바로는, 해당 페이지가 말씀해주신것 처럼 "노출 제외 키워드 목록" 로 확인입니다.

> 또한 노출 제외 키워드 목록의 하위에 보여지는 키워드는, 해당 광고그룹의 소재가 노출이되었을때, 유입된 쿼리 키워드 목록입니다.

위 말씀을 정리해보자면, 하위에 보여지는 키워드(검색어), 노출수, 클릭수, 총비용(VAT포함), 직접전환률(%) 에 대한 데이터는 광고그룹의 소재가 노출이 되며 발생한 데이터로 이해가 됩니다.

이때 아래의 궁금한 점이 있습니다.
1. 해당 키워드에 대한 데이터는 API페이지에 있는 키워드와는 다른 것 인가요?
2. 만일 다르다고 한다면 해당 데이터는 어떤 API를 통해 받을 수 있을까요?

**Comment by naver-searchad** [comment]
@for2gles 안녕하세요? 네이버 검색광고 API 입니다.

키워드라는 용어가 중의적으로 사용될수 있어 용어에 대한 설명을 우선 드립니다. 물론 이 용어들과 규칙은 네이버 검색광고 서비스와 시스템 내에서만 정의된 사항입니다. 

네이버 검색광고 상품중 내 광고가 노출 될 검색어(키워드)를 광고 시스템에 미리 등록해야 하는 상품들이 있습니다. 
대표적인 예가 파워링크인데요.
이렇게 등록된 검색어들을 네이버 검색 광고 시스템에서는 등록키워드라고 부르며(API 문서에서는 AD KEYWORD라는 표현을 사용합니다.) 등록 키워드 아이디를 부여하여 관리하고 있습니다. 말씀 주신  [API페이지에 있는 키워드](http://naver.github.io/searchad-apidoc/#/operations/GET/~2Fncc~2Fkeywords%7B%3FnccAdgroupId,baseSearchId,recordSize,selector%7D) api는 이러한 등록 키워드를 등록, 조회 관리하는 api 입니다. 이런 상품들에서는 등록키워드가 입찰가 설정, 광고 노출 통제등 광고관리의 중요한 요소로 사용되며 당연히 보고서 집계 단위로도 사용됩니다. 

한편 광고주(사용자)가 검색어를 지정하지 않고 소재(광고컨텐츠)만을 등록하면 광고 시스템(및 검색엔진)이 소재의 컨텐츠를 기반으로 검색어를 매칭하여 광고를 노출 하는 상품도 존재합니다. 대표적인 예가 네이버 쇼핑 검색광고 중 쇼핑몰 상품형입니다. 
이런 경우는 광고 시스템에 사용자가 별도로 검색어(키워드)를 등록할수 없으며 광고 시스템도 해당 검색어(API 문서에서는 search keyword  로 표현합니다.) 및 각 검색어에서 발생한 광고 성과만 보관 저장 할뿐 사용자가 이를 통제할수 없습니다. 
단 광고주가 원치 않는 검색어도 내 광고가 나갈수 있으므로 이를 방지할수 있도록 과거에 내 광고가 나간 검색어를 보고서 형태로 제공드리고 보고서 지표를 확인해서 성과가 낮은 검색어는 블랙리스트로 설정할수 있는 "보조적"인 기능 역시 추가로 제공드리고 있습니다. 이렇게 블랙리스트로 설정된 검색어(키워드)들은 광고 집행시 검색엔진이 필터링 조건으로만 사용할뿐, 앞서 말씀드린 등록 키워드와 같이 입찰가나 광고 노출 통제의 요소로 사용되지는 않습니다. 
키워드 대쉬보드(노출 제외 키워드 화면)라고 말씀하신 기능은 앞서 말씀 드린 보조적인 기능으로서 검색어(키워드는)와 성과로 구성된 일종의 보고서라고 생각해 주시면 되겠습니다.  예시로 보여주신 캡쳐는 쇼핑검색광고 쇼핑몰 상품형에서 사용되는 제외 키워드 설정 화면으로 보이는데요. 이 화면에서 사용된 지표들은 아래 기능을 통해 조회 하실수 있습니다. 

**STAT(보고서 조회  API)** 
*실제로 해당 화면에서 사용중인 지표와 동일한 값을 조회 하는 API입니다.
[Stat: get (by statType)](https://naver.github.io/searchad-apidoc/#/operations/GET/~2Fstats%7B%3Fid,statType%7D)
statType 파라미터를  NPLA_SCH_KEYWORD로 설정하시면 됩니다. 
이 기능의 단점은 지표 기간이 과거 한달로 고정되고, 광고 그룹 단위로만 제공되며 어떤 소재(상품)별 광고 노출 검색어(키워드)를 알수 없다는 점인데요.  일자별 상세 지표를 원하시면 아래 대용량 다운로드 보고서를 활용하시면 되겠습니다. 
 
**대용량 다운로드 보고서** 
[ StatReport](http://naver.github.io/searchad-apidoc/#/tags/StatReport) 에서 제공되는 보고서 중 
 Shopping Campaign Search Keyword Performance Detail Report (reportTp : SHOPPINGKEYWORD_DETAIL)

감사합니다.

**Comment by for2gles** [comment]
자세한 설명 감사드립니다.
