### ISSUE TITLE
보고서 작성 문의 드립니다.

### ISSUE THREAD

**Issue by jjsk109** [naver/searchad-apidoc#672]
<img width="804" alt="api 검색어 언어 문의" src="https://user-images.githubusercontent.com/39641848/199662796-08277d62-f7ec-4a29-8c38-529a384f3145.png">

안녕하세요 
보고서 작성중 키워드가(/ncc/keywords) 아닌 검색어로 검색하는 방법이 있을까요?

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 대용량 다운로드 보고서 담당자입니다.

문의 주신 질문을 이해하지 못하였습니다. 
다차원 보고서의 사용법을 문의 하셨을것 같지는 않은데요. 
혹 검색광고 API에서 제공되는 보고서들에서 검색어별 지표를 볼수 있는 보고서들을 문의 주신 것인지요?

감사합니다.

**Comment by jjsk109** [comment]
그림으로 혼선이 있어던거 같습니다.
예 검색광고 API에서 제공되는 보고서들에서 검색어별 지표를 볼수 있는 보고서에 대한 문의 입니다.

/ncc/keywords 와 같이 (/ncc/검색어 )  API가 있을까요?  

API 한눈에 보이는 리스트가 있을까요?

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 대용량 다운로드 보고서 담당자입니다. 

구체적으로 어떤 정보를 원하시는지 추정이 조금 어려워 일단 보고서 설명이 기술되어 있는 레퍼런스 링크를 안내 드립니다.

보고서는 크게 두가지 종류로 제공 드리고 있습니다. 

1.  STAT : 가공된 형태의 보고서로서 네이버 검색광고 관리시스템(manage.searchad.naver.com)에서 캠페인이나 광고그룹 리스트에서 함께 보여지는 성과 지표(노출수, 클릭수,광고비등)를 제공하는 API 입니다.
레퍼런스 페이지: https://naver.github.io/searchad-apidoc/#/tags/Stat
이 API의 경우 광고관리시스템에서 사용되는 지표를 제공하기 위한 목적으로 만들어졌기 때문에 검색어별 지표의 경우  지원되지 않는 상품도 존재하고 일자도 선택할수 없는 등 제약이 존재합니다. 

2. 대용량 다운로드 보고서 : 최대한 RAW 데이터에 가깝도록 광고 성과 지표를 제공드리기 위해 구성된 보고서 입니다. 
비동기성 API로 보고서 파일 생성을 요청하시고 파일이 생성되면 다운로드 링크를 리턴 받아서 보고서 파일을 다운받으시는 형태입니다. 또한 일단위로만 생성이 되므로 기간 데이터가 필요하시면 기간 중 보고서를 일별로 생성하신후 다운받아 합치셔야 합니다. 
레퍼런스 페이지 : https://naver.github.io/searchad-apidoc/#/tags/StatReport
이 보고서들은 효율적인 대량 데이터 제공을 위해 광고 메타 정보들에 대해서는 정규화가 어느정도 이루어져 있습니다. 
그래서 광고 메타 정보들은 마스터를 통해 별도로 받으셔서 각 아이디를 기준으로 join 하셔야 합니다. 
레퍼런스 페이지 : https://naver.github.io/searchad-apidoc/#/tags/MasterReport
각 보고서들의 스펙은 레퍼런스 페이지에 기재되어 있으며 한글 설명 파일은 아래 링크에서 [대용량 다운로드 보고서 데이터 사양서 다운로드](https://searchad.naver.com/File/downloadfilen/?type=10&filename=Report_MasterSpecification_02.pdf.pdf)를이용하시면 되겠습니다.
https://saedu.naver.com/help/faq/ncc/view.naver?faqSeq=178
단 한글 가이드 파일의 경우 광고관리 시스템에서 제공되는 보고서>대용량 다운로드 보고서 메뉴 사용자 메뉴얼이므로 
모든 보고서의 사양이 기재되어 있지는 않습니다. 
대용량 보고서에서는 상품별 검색어별 지표를 제공드리는데요.(물론 제공드리지 않는 상품도 있습니다)
예를 들어 KEYWORD PLUS Performance Report (reportTp : EXPKEYWORD)의 경우 파워링크에서 키워드 확장기능(키워드 플러스)기능을 이용하신 경우 등록 키워드가 아닌 검색어별 지표를 제공드리는 보고서이며, Shopping Campaign Search Keyword Performance Detail Report (reportTp : SHOPPINGKEYWORD_DETAIL)의 경우는 쇼핑 검색광고에서 검색어별 지표를 제공드리는 보고서 입니다. 

마지막으로 캡쳐로 보여주신 다차원보고서는 API 서비스를 통해 제공드리지 않으며 대용량 보고서를 이용해 비슷한 기능을 직접 개발하셔서 사용 하시는 형태로 가이드 드리고 있씁니다. 

사양을 살펴보시고 궁금하신 점이 있으시면 다시 코멘트 부탁드립니다. 

감사합니다.
