### ISSUE TITLE
/stats  last30days, lastweek, astmonth, lastquarter 에러 확인 부탁 드립니다

### ISSUE THREAD

**Issue by jjsk109** [naver/searchad-apidoc#673]
{"code":11003,"message":"선택하신 조건에 지표가 확인되지 않습니다. 동일한 캠페인 유형을 id, ids 파라미터에 포함해서 요청하세요."} 
last7days이내에는 정상 동작을 하지만

{"code":11003,"message":"선택하신 조건에 지표가 확인되지 않습니다. 동일한 캠페인 유형을 id, ids 파라미터에 포함해서 요청하세요."} 
이 외에 last30days,lastweek,lastmonth,lastquarter 에서는 위와 같은 에러가 납니다 

혹시 금일 기준 7일 이내만 출력이 가능할까요??

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

혹시 breakdown 파라미터를 활용하고 계신다면

캠페인 타입 | 제공기간 | 데이터 윈도우
-----|-----|-----
파워링크 | 최근7일 | 7
쇼핑검색 | 최근7일 | 7
파워컨텐츠 | 최근7일 | 7
브랜드검색 | 최근120일 | 90
신제품 | 최근7일 | 7
플레이스 광고 | 최근120일 | 90

위와 같은 제공 기간 제약이 있음을 알려드립니다.

감사합니다.
