### ISSUE TITLE
노출수 관련 문의입니다.

### ISSUE THREAD

**Issue by kgw7401** [naver/searchad-apidoc#674]
현재 보고서에서 제공하고 있는 키워드 노출수는 해당 파워링크 광고가 노출되는 횟수를 말하는 건가요?
만약 파워링크 광고가 제일 하단에 존재한다면 사용자가 하단까지 내려서 파워링크를 보았을 때 노출수가 +1 되는 것이 맞을까요?
(아니면 파워링크가 존재하는 해당 페이지가 노출되기만 하면 노출수가 +1 되는 것일까요?)

**Comment by naver-searchad** [comment]
@kgw7401 님 

안녕하십니까 네이버 검색광고 대용량 다운로드 보고서 담당자입니다. 

노출수는 등록한 광고가 설정한 매체에 노출된 횟수입니다.
따라서 통합검색 외에도 노출된 모든 매체의 노출수의 합이며
케이스별로 문의주신 부분에서 통합검색만 매체로 설정됨을 가정한다면 후자에 해당합니다.

감사합니다.

**Comment by kgw7401** [comment]
다시 한 번 확인차 질문드립니다. 통합검색을 기준으로 한다면 파워링크가 하단에 뜰 경우 아래까지 스크롤하지 않아도 해당 페이지가 노출되기만 한다면 노출수가 +1 되는 것이 맞을까요?

**Comment by naver-searchad** [comment]
안녕하십니까. 네이버 검색광고 대용량 다운로드 보고서 담당자입니다. 

이전 답변과 같이 노출수는 광고의 매체 노출 여부를 기준으로 합니다.

감사합니다.

**Comment by kgw7401** [comment]
감사합니다
