### ISSUE TITLE
ad 소재 등록 문의

### ISSUE THREAD

**Issue by jungmyounghwan** [naver/searchad-apidoc#675]
ad api 사용 시 네이버 쇼핑 상품ID말고 몰상품ID로는 안되나요? 사이트에서 직접 검색하는건 가능한데 api로는 안되는거같은데요

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고입니다.
쇼핑 검색의 광고 소재는 API를 이용하여 등록하지 않도록 권고하고 있습니다.
소재 등록에 필요한 nvmid (네이버 쇼핑에서 관리하는 내부 상품 ID) 값을 조회할 수 없기 때문입니다.


감사합니다.
