### ISSUE TITLE
광고 그룹 타겟팅 정보 조회 문의

### ISSUE THREAD

**Issue by universpace** [naver/searchad-apidoc#676]
### 아래와 같이 통계치를 확인해 보고 싶은데 criterion를 통해서 조회할 수 있는 방법이 있나요?
<img width="927" alt="image" src="https://user-images.githubusercontent.com/48277984/200243027-c8174ff8-6a07-40cb-ab4b-eb8dbf095b7d.png">

**Comment by naver-searchad** [comment]
안녕하세요?
네이버 검색광고 API입니다.

Stat API 의 breakdown 항목을 통해서 좀 더 자세한 리포트를 확인하실 수 있습니다.
http://naver.github.io/searchad-apidoc/#/operations/GET/~2Fstats%7B%3Fid,fields,timeRange,datePreset,timeIncrement,breakdown%7D

pcMblTp : PC/모바일 구분
dayw : 요일
hh24 : 시간
regnNo : 지역

감사합니다.
