### ISSUE TITLE
stats breakdown 집문입니다.

### ISSUE THREAD

**Issue by wasdq1234** [naver/searchad-apidoc#678]

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

성별 & 연령대는 공지사항에서 2022년 4월 19일 공지사항을 참고하시기 바랍니다.
* [2022-04-19] 타게팅 관리방식 변경에 따른 신규 보고서 API 추가에 대한 공지(Stat API)
* http://naver.github.io/searchad-apidoc/#/notice
