### ISSUE TITLE
확장소재 (Ad Extensions) 인터페이스 vs. API / adExtension 오브젝트 샘플 JSON 문의

### ISSUE THREAD

**Issue by nyob3** [naver/searchad-apidoc#679]
안녕하세요.

제공해주시는 AdExtension API를 활용하여 개발 중에 있는데요. 두 가지 문의사항을 드리고자 합니다.

첫 번째는 인터페이스에서 디스플레이 되는 확장소재 타입명과 API에서 사용되는 type 이름을 매칭하려고 하려는 가운데 '추가제목'과 '추가설명'에 해당하는 AdExtension Type 값이 (http://naver.github.io/searchad-apidoc/#/tags/AdExtension 문서를 참고하였습니다.) 어떤 값과 매칭이 되는지 확실하지 않아서 확인 부탁드리고자 합니다. (아래 이미지에 노란색으로 하이라이트 된 항목입니다.)

![image](https://user-images.githubusercontent.com/29356782/200878790-0bde38df-e69a-44b6-ada5-1873a796a259.png)

두 번째로는 해당 문서
- https://gist.github.com/naver-searchad/f8e941f61b9152972feb676689046b87#file-ad-extension-field-sample-md
- http://naver.github.io/searchad-apidoc/#/tags/AdExtension 
'adExtension' object에 대한 Sample Json가 안내가 되어 있지만 모든 타입이 언급되고 있지는 않아서 다소 어려움을 겪고 있습니다. 혹시 위 이미지에 초록색으로 하이라이트 된 확장소재 유형의 Sample Json을 본 이슈를 통해 안내해주시거나 다른 방법을 통해 (문서나 링크) 찾을 수 있다면 그 부분을 공유해주신다면 큰 도움이 될 것 같습니다.

감사합니다!

**Comment by naver-searchad** [comment]
@nyob3 
안녕하세요, API 참조는 추가제목 "HEADLINE", 추가설명 "DESCRIPTION_EXTRA"  입니다.

그리고,  sample json은 아래를 참고 하시기바랍니다.
1. 전화번호/위치정보/네이버예약
adExtension 객체에 정보를 저장하지 않고, mobileChannelId 의 비즈채널ID 값으로 비즈채널을 조회하여 전화번호/위치정보/네이버예약 정보를 조회합니다.

2. 추가제목
```
{
    adExtension:  {
      headline:"추가 제목"
    }
}
```

3. 추가설명 
```
{
   adExtension:  {
      "description":"추가설명 메시지"
   }
}
```

4, 블로그 리뷰, 플레이스 정보
adExtension 객체에 정보를 저장하지 않고, 플레이스 및 블로그 API를 통해서 제공되어서 JSON 정보가 제공되고 있지 않습니다.

**Comment by nyob3** [comment]
@naver-searchad 답변 감사드립니다!

언급해주신 것처럼 **전화번호, 위치정보, 네이버 예약, 플레이스 정보, 블로그 리뷰**는 Ad Extensions API에서 처리된다기 보다 다른 API와 연동되기 때문에 온라인 인터페이스에서 진행되거나 이를 권장하는 것으로 알고 있습니다.

이외에 다른 모든 유형은 샘플 Json이 제공되는 바, Ad Extensions API를 활용하여 생성 가능한 것으로 이해하면 될까요?

**Comment by naver-searchad** [comment]
@nyob3 
네, 샘플 json이 제공되는 것은 AdExtension API를 활용합니다.

감사합니다.
