### ISSUE TITLE
Search Ad API문서의 ad update 관련 문의드립니다.

### ISSUE THREAD

**Issue by secjong** [naver/searchad-apidoc#68]
안녕하세요.

현재 네이버 광고 api를 사용하여 개발중에 있습니다.
api문서에 따라 개발 중 네이버 쇼핑광고의 광고소재 UPDATE 기능에서 PUT request 형식이 api 문서와 맞지 않는 것 같아 문의드립니다.

http://naver.github.io/searchad-apidoc/#/operations/PUT/~2Fncc~2Fads~2F%7BadId%7D%7B%3Ffields%7D

해당 문서의 request body 와 query parameters 에 정확한 정보가 기입된게 맞을까요?
{"code":1028,"status":400,"title":"Invalid request message."}

**Comment by naver-searchad** [comment]
안녕하세요. 확인이 너무 늦어져서 죄송합니다.

말씀주신 api 문서 정보는 올바르게 되어 있습니다.
가령 on/off 설정을 update 하시려면,
request URL 에는 다음과 같이 parameter name과 value를 주시면 되고
/ncc/ads/nad-a001-01-000000000001111?fields=userLock
request body에는,
해당 소재를 get해서 얻은 object에서 (혹은 쇼핑 소재가 아닌 경우 그냥 nccAdId와 userLock 필드만 세팅하셔도 됩니다)
userLock만 true/false로 변경해서 요청하시면 됩니다.
