### ISSUE TITLE
계정에 존재하지 않는 값이 추적url에 들어올수도 있나요?

### ISSUE THREAD

**Issue by henlyshin** [naver/searchad-apidoc#680]
상당히 많은 값이 유입되긴 합니다만
하나만 예시를 좀 들어서..
grp-a001-01-000000024055880
nkw-a001-01-000004111688319

지점이 많아 관리하고 있는 계정이 많습니다.
위 파라미터값 (공개해도되나요?) 이 없는데도 유입이 되는데
혹시 어떤계정에 있는지 조회해보려면 방법이 있는지 궁금합니다.

**Comment by kaorimikage** [comment]
다른 계정에서 그룹 소재의 연결URL 설정을 잘못하면 다른 홈페이지로 유입될수도 있기 때문에 수집이 가능합니다.

어느 계정에 속하는지 확인하시려면 각 계정 API 키로 그룹 ID가 존재하는지 돌려보시는수 밖에 없을거예요.
