### ISSUE TITLE
/ncc/managedKeyword 의 PCPLMaxDepth 결과가 실제와 다릅니다.

### ISSUE THREAD

**Issue by kaorimikage** [naver/searchad-apidoc#681]
올레인터넷TV 키워드로 /ncc/managedKeyword 를 호출하면 PCPLMaxDepth 가 15로 표시됩니다.
그런데 www.naver.com 에서 해당 키워드로 검색하면 실제 표시되는 파워링크는 3개만 표시됩니다.

더보기를 통해 해당 키워드로 광고하고 있는 업체수가 3개가 넘어가므로 실제 적용되는 슬롯수는 3개로 확인됩니다.
API와 실제 네이버 플랫폼에 표시되는 슬롯수가 다른 이유는 무엇인가요?

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 API 담당자입니다.

네이버 검색광고는 광고 성과 향상을 위해 광고 노출 환경을 지속적으로 개선하여왔습니다. 이에 따라 실제 노출 가능 광고 갯수보다 적은 광고가 노출 되는 상황도 검색어 및 검색 시점에 따라 발생 할수 있습니다.
해당 정보는 PC 파워링크 매체 영역에 대상 키워드에서 광고가 나갈수 있는 "최대" 수를 제공하는 것으로 동일 키워드에 입찰한 광고들의 경쟁 상황 외의 앞서 말씀 드린 검색 상황에 따라 최대 수에 못 미치는 광고가 노출 될 수 있습니다.
한편  /ncc/managedKeyword  기능은 현재의 복합적인 검색 환경을을 잘 반영하고 있지 못하여 최근의 검색 환경에 맞게 해당 기능을 수정 보완하려는 계획을 가지고 있습니다. 

감사합니다.
