### ISSUE TITLE
네이버검색광고 API (키워드 조회)

### ISSUE THREAD

**Issue by contentsboxgroup** [naver/searchad-apidoc#683]
안녕하세요.
네이버검색광고 내 키워드 도구(키워드 검색량 조회) API를 연동해서 사용중입니다.

예를들어 키워드 80개를 조회하면 60개만 결과값에 나오는데요.
결과값에 무조건 60개만 나오는게 아니라,
45개도 나왔다가, 50개도 나왔다가, 80개 정상으로 나왔다가 들쭉날쭉 합니다.
두세번 호출해야 데이터를 받아오는것 같은데요..(오류화면 캡쳐)

**API에 문제가 있는지, 아니면 저희 설정값이 잘못된것인지 판단이 안됩니다.**
(만약 기존 API의 설정값이 바뀌었다면, 최신 버전의 설정 Tip 부탁드립니다..)

![오류화면](https://user-images.githubusercontent.com/118244467/201837108-7dffb7cc-d2c3-4268-b26b-d472d28a9927.png)

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 API 입니다. 

문의 주신 내용에 답변 드리기 앞서 캡쳐로 보여주신 서비스 페이지에 방문하여 보았는데요. 
금일 현재 해당 페이지(혹은 이미지 캡쳐로 보여주신 페이지)는 특정 사이트에 가입한 이용자에게 네이버 검색광고 API 를 통해 수집한 정보가 제공되는 페이지로 생각 됩니다. 

이와 같은 형태의 API 사용은 저희 네이버 검색광고 API 이용 약관에 부합하지 않는 것으로 사료되어 이에 
이용 약관을 면밀히 검토해 주시기를 당부드립니다. 

네이버 검색광고 API 이용약관(https://saedu.naver.com/adguide/policy/api.naver) 
제 7 조 (API 서비스를 통한 회사의 데이터 제공)
④ "광고 API"를 통해 제공되는 데이터는 "사용자" 본인 및 권한 기능을 통해 권한을 가진 다른 회원의 광고 관리 목적 범위 내에서만 사용하여야 합니다.  (_이하 서술 생략_)
제 9 조 (사용자의 의무)
⑨ "사용자"는 "API 서비스"에 관한 자료와 입찰 등 "API 서비스" 이용과정에서 취득한 일체의 정보를 제3자에게 제공, 공개 또는 누설하여서는 안 됩니다.

또한 네이버 검색광고 API는 네이버 검색광고 회원에게만 제공되는 서비스 이므로 네이버 검색광고 서비스 이용약관 역시
면밀히 검토해 주시기를 부탁드립니다. 

네이버 검색광고 서비스 이용약관(https://saedu.naver.com/adguide/policy/terms.naver)
제 16 조 (회원의 의무)
⑧ "회원"은 "서비스"에 관한 자료와 입찰 등 게재신청에 대한 정보 등 "서비스" 이용과정에서 취득한 일체의 정보를 "권한설정"을 통한 권한을 위탁하거나 위탁받은 다른 "회원" 이외의 제3자에게 제공, 공개 또는 누설하여서는 안 됩니다.

감사합니다.
