### ISSUE TITLE
/ncc/managedKeyword 의 PCPLMaxDepth 결과관련

### ISSUE THREAD

**Issue by kaorimikage** [naver/searchad-apidoc#685]
#681

이전에 답변을 주셨는데 점점 해당하는 키워드들이 늘어나서 재문의를 드립니다.
2022년 11월 09일(수) 14시 경에 네이버 검색광고 홈페이지에서 순위 정보 보기에서 PC/모바일의 순위가 3위까지만 노출되는 오류가 발생했었습니다. 해당 현상은 18시 경에 복구가 되었고 그 이후부터 API에서 주는 PCPLMaxDepth 값과 실제 네이버 포털에 노출되는 슬롯수가 다른 현상이 지속적으로 나타나고 있습니다.

검색광고 홈페이지에서 오류가 발생하기 전에는 API의 PCPLMaxDepth 값과 네이버 포털에 표시되는 슬롯수가 불일치하는 경우가 없었습니다.

확인 부탁드립니다.

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

말씀 주신 "네이버 검색광고 홈페이지에서 순위 정보 보기" 라는 메뉴는 어떤 기능을 말씀주신 것인지 좀더 상세히 말씀 부탁드립니다. 가능하시다면 기능의 캡쳐를 제공해 주실수 있으실까요?

감사합니다.

**Comment by kaorimikage** [comment]
네이버 검색광고 홈페이지 접속 > 도구 > 광고노출진단
입력란에 광고중인 키워드 입력 후 검색 하면 현재 노출중인 슬롯수와 순위 정보를 주고 있습니다.

![image](https://user-images.githubusercontent.com/25290207/202105471-cf6807af-2243-4a5e-b500-f88cecd70008.png)

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 API 담당자입니다. 

우선 말씀 주신 기능은 내 광고가 어떤 형태로 노출 될지를 보여드리는 기능으로 순위 정보가 현재 노출 되는 현황과 동일하다는 점을 보장하지 않는 다는 점을 안내드립니다. 따라서 해당 정보로 내 광고의 노출 순위를 확인하실수는 있으나 이점에 유의 하여 주시기 바랍니다. 
또한 해당 기능 및 네이버 검색광고 광고관리사이트는 말씀 주신 시점에 오류 및 장애가 발생한 일이 없습니다. 
이전에 답변 드린 것과 같이 검색어와 시점 및 광고 노출 매체의 상황에 따라 광고의 수가 충분하더라도 특정 매체에 노출 되는 광고수가 항상 최대 광고수와 같지 않을 수 있으며 이는 오류가 아닙니다. 

감사합니다.

**Comment by kaorimikage** [comment]
당시 검색광고 홈페이지 순위보기 기능에서 등록된 PC/모바일의 모든 키워드의 슬롯이 3위까지만 표시되었습니다. CPC가 많이 나가는 경쟁과다 키워드나 유명브랜드 키워드(예를들어 SK텔레콤같은)도 마찬가지였기때문에 슬롯수 3개는 이상하다고 판단됩니다.

서버상에서 request 200을 반환했기 때문에 확인가능한 오류는 없었어도 해당 기능의 로직상에는 오류가 있었을걸로 생각됩니다.

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 API 담당자입니다. 

위에 남겨 주신 코멘트의 의미를 알려주실수 있으실까요?
현재 상황을 남겨 주신것이라면 키워드(검색어)를 함께 알려주시기를 부탁드립니다. 

감사합니다.

**Comment by kaorimikage** [comment]
KT기가인터넷설치
올레인터넷TV
올레인터넷신청
KT기가인터넷가입
기가인터넷KT

등의 키워드 입니다.

해당 키워드들을 managedKeyword API 로 슬롯수 취득하면 PCPLMaxDepth 값이 15로 나옵니다. 하지만 노출 현황 기능에 표시되는 갯수 와 네이버 검색결과 광고 노출 매체에 표시되는 광고수는 3개입니다.

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API 담당자입니다. 

현재 "노출 현황 기능에 표시되는 갯수 <> 네이버 검색결과 광고 노출 매체에 표시되는 광고수" 건에 대한 해결책을 찾아 문제를 해결한 상태입니다. 
반면 네이버 검색결과 광고 노출 매체에 표시되는 광고수 <> PCPLMaxDepth 는 아직 방향을 모색 중인 상태 입니다. 

저에게는 미처 해결된 사항이 전파가 안되서 확인을 하는데 조금 시간이 걸렸습니다.

감사합니다.
