### ISSUE TITLE
keywordstool api 사용 시 월별 통계 확인

### ISSUE THREAD

**Issue by ghlim0116** [naver/searchad-apidoc#686]
안녕하세요!

keywordstool api를 사용하여 월별 검색수 추이, 월간 검색수 사용자 통계를 얻고자 합니다.

그런데 아래 링크에서 2020년 10월에 해당 api를 지원하지 않고 있다는 답변을 보았습니다. 혹시 아직 지원이 되지 않고 있나요?
https://github.com/naver/searchad-apidoc/issues/465

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 API 담당자입니다. 

문의 주신 월별 검색수 추이, 월간 검색수 사용자 통계는 현재 API 를 통해 제공드릴 계획이 전혀 없습니다. 
또한 향후에도 API를 통해 제공 드릴 가능성은 극히 낮을 것으로 예상됩니다.

감사합니다.
