### ISSUE TITLE
간헐적으로 발생하는 no permission

### ISSUE THREAD

**Issue by kimcheolwoo** [naver/searchad-apidoc#687]
{"code":1018,"status":404,"title":"No permission to access the resource."}

권한을 위임받은 계정들에 대해서 /ncc/keywords 조회시 위 오류가 발생합니다. 
계속 발생하는게 아니라 동일한 호출을 다시 하면 또 되고, 말 그대로 간헐적으로 발생합니다.

CustomerId 250043, 830477 입니다.

확인 부탁드립니다.

**Comment by naver-searchad** [comment]
@kimcheolwoo 안녕하세요? 네이버 검색광고 API입니다.

코드 1018의 경우 API 접속 정보(인증정보)의 광고주 계정에 소속되지 않는 데이터에 대해 access 시 발생합니다. 
이경우 보통 삭제된 경우 또는 다른 광고주의 광고 ID를 사용하는 경우입니다.

위와 같은 오류가 발생할 경우 Customer ID 두개에 속한 키워드에 대한 요청인지 확인이 필요합니다.

감사합니다.

**Comment by kimcheolwoo** [comment]
권한이 있는 계정입니다. 동일한 요청에 대해서 간헐적으로 발생합니다.
다시 확인 부탁드립니다.
