### ISSUE TITLE
확장소재 create api 사용 시 code:1010 오류

### ISSUE THREAD

**Issue by nayasms** [naver/searchad-apidoc#688]
안녕하세요.
현재 포스트맨으로 api 사용에 대한 테스트 중입니다.

파워링크 확장소재 추가 부분 테스트 중인데요.

body
{
	"pcChannelId":"bsn-a001-00-000000000294469",
	"mobileChannelId":"bsn-a001-00-000000000294469",
	"ownerId":"grp-a001-01-000000002626250",
	"schedule":"",
	"type":"DESCRIPTION",
	"adExtension": {
        "heading": "할인",
        "description": "5만원"
    },
	"userLock": false
}

response

{
    "code": 1010,
    "status": 400,
    "title": "Received value is not suitable for JSON format.",
    "detail": "instance type (string) does not match any allowed primitive type (allowed: [\"object\"]), at '' with 'type'\n"
}

adExtension 부분이 문제인것 같은데
어떻게 처리를 해야하는지 궁금합니다. 답변 부탁 드립니다.

**Comment by naver-searchad** [comment]
안녕하세요,
"schedule"이 ""가 아니고 아래처럼 null 로 지정해야합니다.

{
"pcChannelId":"bsn-a001-00-000000000294469",
"mobileChannelId":"bsn-a001-00-000000000294469",
"ownerId":"grp-a001-01-000000002626250",
**"schedule": null,**
"type":"DESCRIPTION",
"adExtension": {
  "heading": "할인",
  "description": "5만원"
},
"userLock": false
}
'''
