### ISSUE TITLE
Shopping Product 타입 masterReport 유니크 컬럼 중복 발생 이슈

### ISSUE THREAD

**Issue by mkms1104** [naver/searchad-apidoc#689]
api 문서 내에 유니크 값으로 표시되어 있는 컬럼인 Product ID 값이 중복으로 나타나고 있습니다.
fromTime 파라미터를 넘기지 않은 요청입니다.
확인 부탁드립니다.

2022-11-19, 09:00 기준 masterReport 조회 
요청 API path : /master-reports
Customer ID : 1285474
중복 Product ID : 
35863492362
35782195390
35782228089
35782164474
35759133054
35744049420
35697645662
35649346637
35649207364
35629433953
35629266025
35586034261
35557480402
35421472445
35421424483
35421462035
35331582295
35308523750
35083551986
34948702682
34495268615
34377105204
34239552448
34239272475
34203553589

**Comment by mkms1104** [comment]
11월 20일 자도 동일하게 발생하였으며, 빠른 확인 부탁드립니다.

**Comment by mkms1104** [comment]
@naver-searchad
11월 21일 자도 동일하게 발생하였으며, 빠른 확인 부탁드립니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API 입니다.

Product ID는 Product 내에서 유니크하지만, 마스터 리포트의 ShoppingProduct는 ad중에 TYPE값을 2로 설정한 정보와 refeerence_key 값이 Product ID와 같은 Product가 결합되어 반환됩니다.
두 관계가 1:1 이 아니기 때문에 동일 Product가 중복되어 반환될 수 있습니다.

감사합니다.

**Comment by mkms1104** [comment]
@naver-searchad 
ad중에 TYPE값을 2로 설정한 정보라는게 어떤 의미인지 좀 더 상세하게 설명해주실 수 있으실까요?

**Comment by naver-searchad** [comment]
@naver-searchad 쇼핑 캠페인의 쇼핑몰 상품형 광고그룹에서 등록한 소재입니다.
