### ISSUE TITLE
Estimate API 관련 문의

### ISSUE THREAD

**Issue by rndmania** [naver/searchad-apidoc#69]
/estimate/performance, /estimate/performance-bulk api를 사용중입니다.

performance api는 keyword 하나와 여러 bid 값(최대 100개) 조합으로 요청을 할 수 있고,
performance-bulk api는 {keyword,bid} 조합으로 최대 200개 요청할 수 있는것으로 보입니다. 

현재 open되어 있지 않지만,
네이버광고관리시스템 -> 키워드도구 -> 월간 예상실적 기능에서 내부적으로 사용되는 api의 경우
(https://manage.searchad.naver.com/api/estimate/performance-bid/keyword)
여러 키워드와 여러 bid 조합으로( {keys:[], bids:[]} ) 요청하여,
요청한 모든 keyword에 대해 bid가 별 예상실적을 합산하여 제공해주는것으로 보이는데요  

해당 api를 open해 주실 수 있는지 문의드립니다.

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

말씀 주신 오퍼레이션은 저희 UI 상에서 그래프를 표시 하기 위해 사용 되는 오퍼레이션입니다. 
대량 조회가 가능하고 1차 가공이 되어 있으므로 제공을 드리면 사용 편의가 증대될 것이라는 
점에 대해서는 저희 역시 동의 하고 있으며 저희 역시 제공을 드리고 싶은 마음은 큽니다만.
해당 기능의 경우 대량의 데이터를 조회해서 계산하는 오퍼레이션이다 보니 
성능에 대한 고려가 필요합니다. 
따라서 현재로서는 API 서비스로 정규 오픈을 하기에는 어려움이 있습니다.
양해를 부탁드립니다.

**Comment by rndmania** [comment]
네 답변 감사드립니다
