### ISSUE TITLE
연관키워드 조회 기준 api 제공여부를 알고 싶습니다.

### ISSUE THREAD

**Issue by ChoiYoungWoo2197** [naver/searchad-apidoc#690]
![image](https://user-images.githubusercontent.com/57242259/202950473-0465a32e-5b1a-4b5c-abf1-6740c63d2b0e.png)

해당 이미지처럼 키워드 조회시 관련된 연관키워드 조회 api가 제공될까요??

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 API입니다.

문의 주신 화면에 대응하는 API는 RelKwdStat 로서 아래 레퍼런스에서 스펙 확인하실수 있습니다.
https://naver.github.io/searchad-apidoc/#/tags/RelKwdStat

감사합니다.

**Comment by ChoiYoungWoo2197** [comment]
![image](https://user-images.githubusercontent.com/57242259/203457010-d36a3eea-7807-4583-a56c-8bd95f93205c.png)

안녕하세요 추가로 질문드립니다!

1. 해당 사진과 같이 '업종'은  api요청시 'biztpId'에 해당하는지 궁금합니다.
2. '업종'가 맞다면 업종코드를 알 수 있는지 궁금합니다.
3. RelkwdStat api는 정렬 기능을 제공여부를 알고 싶습니다.
   - 연관키워드 이름 정렬 - 오름차순, 내림차순
   - 월간검색수(PC)  정렬 - 오름차순, 내림차순

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까. 네이버 검색광고 API 담당자입니다. 

답변 드립니다. 
1. 네 biztpID 는 업종코드를 의미합니다. 
2. 업종 코드는 마스터리포트(http://naver.github.io/searchad-apidoc/#/tags/MasterReport)에서 BusinessCode (Biz)를 다운받으시면 됩니다. ID 필드가 업종 코드입니다. 
3. 정렬기능은 제공하지 않습니다. 데이터를 받으셔서 직접 정렬 하셔야 합니다. 

감사합니다.

**Comment by leesw1347** [comment]
궁금했던 내용인데, 감사합니다
