### ISSUE TITLE
/ncc/adgroups 에서 ids로 취득시 제한

### ISSUE THREAD

**Issue by kaorimikage** [naver/searchad-apidoc#691]
/ncc/adgroups 에서 ids로 group_id를 묶어서 값을 취득할때 기존에는 그룹id 200건까지 처리가 됐던것으로 기억합니다.(약 2019년) 그런데 오늘 확인해보니 135건이 넘어가면 request가 413으로 넘어오더군요.

/ncc/targets 의 경우도 최대 200건이었는데 134건으로 제한이 걸려있는 것을 확인했습니다.

혹시 이슈가 있는 것인지요?

**Comment by naver-searchad** [comment]
@kaorimikage 안녕하세요? 네이버 검색광고 API입니다.

ids 파라미터에 입력된 그룹 ID 개수는 최대 200건 제한이 걸려 있습니다. 하지만, http 요청 용량을 초과할 경우 413 코드가 반환될수 있습니다. Client에서는 최대 200개 한도에서 서버오류가 발생하지 않는 개수로 분할 하여 호출 하셔야 합니다.

감사합니다.

**Comment by kaorimikage** [comment]
착오가 있었습니다.

제가 api URL을 https://api.searchad.naver.com 로 호출하여 확인해서 135개에서 response 413이 반환된것으로 확인됩니다. https://api.naver.com 에서는 200개 넘는 470개 그룹 정보가 한번에 넘어오는 것을 확인하였습니다.

아무래도 api 서버 셋팅문제인것 같습니다. 내년에 api.searchad.naver.com 로 URL이 변경이 될텐데 서버 셋팅을 맞추게 될런지 궁금합니다.

**Comment by naver-searchad** [comment]
@kaorimikage 

안녕하십니까 네이버 검색광고 API 담당자입니다. 

위의 상황은 /ncc/adgroups와 /ncc/targets 에서 모두 동일하게 발생하는 현상이지요?
말씀 주신 것처럼 통신 메세지 크기 떄문에 발생하는 상황 같습니다. 신규 모메인쪽에 설정을 확인 해 보겠습니다. 
말씀 감사드립니다.

**Comment by kaorimikage** [comment]
네 /ncc/adgroups와 /ncc/targets 에서 모두 동일하게 발생하고 있습니다.

**Comment by naver-searchad** [comment]
@kaorimikage 
안녕하세요. 네이버 검색광고 API 담당자입니다.

불편을 끼쳐드려 죄송합니다.
말씀해주신대로 베타서비스중인 api.searchad.naver.com 도메인의 서버 설정이 기존과 다른 부분이 있었고, 
해당 문제는 수정하여 현재 적용완료 되었습니다.

추가적으로 베타서비스 중인 도메인에서 기존 도메인과 동작이 다른 경우 제보해주시면 최대한 빠르게 확인해보도록 하겠습니다.

감사합니다 :)

**Comment by kaorimikage** [comment]
확인해봤는데 기존에 413으로 넘어오던게 414로 넘어오면서 여전히 처리가 되지 않습니다.
Request Uri Too Large

**Comment by naver-searchad** [comment]
@kaorimikage 
안녕하세요. 네이버 검색광고 API 담당자입니다.

제보 감사드립니다. 
제보해주신 오류도 수정하여 방금 배포 완료되었습니다.

불편을 끼쳐 드려 죄송합니다. 또 오류가 있을경우 말씀주시면 바로 확인해보도록 하겠습니다.
감사합니다. :)

**Comment by kaorimikage** [comment]
확인되었습니다. 감사합니다.
