### ISSUE TITLE
keywordstool api 403 error

### ISSUE THREAD

**Issue by sspjk83** [naver/searchad-apidoc#692]
안녕하세요? 
keywordstool api 샘플 구현 중 403 에러가 발생하여 문의드립니다.
구현 소스는 아래와 같습니다.

import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.net.URLEncoder;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;

import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;

class HexTest {

    private static final String ALGOLISM = "HmacSHA256";
    private static final String key = "비밀키"; 
    private static String currentTime = "";
    private static String value = "";
    private static String result = "";

    public static void main(String[] args) {
    
        long current = System.currentTimeMillis();
        currentTime = current + "";
        value = Hmac.hget(currentTime);
        System.out.println("currentTime : " + currentTime);
        System.out.println("value : " + value);

        Thread getThread = new Thread(getRunnable);
        getThread.start();
    }

    public static String hget(String current) {
        try {
            Mac hasher = Mac.getInstance(ALGOLISM);
            hasher.init(new SecretKeySpec(key.getBytes(), ALGOLISM));
 
            String message = current + ".GET./keywordstool";
            byte[] hash = hasher.doFinal(message.getBytes());
            return byteToString(hash);
        }
        catch (NoSuchAlgorithmException e){
            e.printStackTrace();
        }
        catch (InvalidKeyException e){
            e.printStackTrace();
        }
        return "";
    }
 
    private static String byteToString(byte[] hash) {
        StringBuffer buffer = new StringBuffer();
 
        for (int i = 0; i < hash.length; i++) {
            int d = hash[i];
            d += (d < 0)? 256 : 0;
            if (d < 16) {
                buffer.append("0");
            }
            buffer.append(Integer.toString(d, 16));
        }
        return buffer.toString();
    }

    public static Runnable getRunnable = new Runnable() {
        public void run() {
            // String params = "?siteId=";
            // params += "&biztpId=";
            // params += "&event=";
            // params += "&month=10";
            // String params = "?showDetail=1";
            String params = "";
            try {
                params += "?hintKeywords=" + URLEncoder.encode("국내여행", "UTF-8");
            } catch (Exception e) {
              e.printStackTrace();
            }

            getInfo("https://api.searchad.naver.com/keywordstool" + params);
            System.out.println(result);
        };
    };

    /**
     * @param mUrl
     * @return
     */
    public static String getInfo(String mUrl) {
        try {
            URL url = new URL(mUrl);
            HttpURLConnection conn = (HttpURLConnection) url.openConnection();
            conn.setRequestMethod("GET");
            conn.setConnectTimeout(10000);
            conn.setReadTimeout(10000);
            conn.setDoInput(true);
            conn.setDoOutput(true);

            conn.setRequestProperty("X-Timestamp", currentTime);
            conn.setRequestProperty("X-API-KEY", "엑세스라이선스");
            conn.setRequestProperty("X-Customer", "CUSTOMER_ID");
            conn.setRequestProperty("X-Signature", value);

            InputStream is = conn.getInputStream();
            StringBuilder sb = new StringBuilder();
            BufferedReader br = new BufferedReader(new InputStreamReader(is, "UTF-8"));
            String temp;
            while ((temp = br.readLine()) != null) {
                sb.append(temp + '\n');
            }

            result = sb.toString();

            return result;

        } catch (Exception e) {
            if (e != null) {
                result = e.getCause() + " / " + e.getMessage() + "\n" + e.getSuppressed()
                + "\n" + e.getLocalizedMessage()
                + "\n" + e.getStackTrace();
            }
            e.printStackTrace();
        }
        return result;
    }
}

헤더 값이나 파라미터가 잘못된 건지 계속해서 403 에러가 발생하고 있습니다.
어떤 부분이 잘못되었을 까요? ㅜㅡ 도움주시면 감사하겠습니다.

(에러 로그)
java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.searchad.naver.com/keywordstool?hintKeywords=%EA%B5%AD%EB%82%B4%EC%97%AC%ED%96%89

**Comment by naver-searchad** [comment]
@sspjk83 안녕하세요? 네이버 검색광고 API입니다. 정확한 원인을 파악하기 위해서는 아래의 정보가 필요합니다.
1. API 호출 시간
2. 트랜잭션 ID
3. Request Header

감사합니다.

**Comment by sspjk83** [comment]
@naver-searchad 
1. 2022.11.28 13시17분
2. 1746183 (CUSTOMER_ID 맞나요?)
3. Request Header
 X-Timestamp : 1669609030295
 X-API-KEY : 01000000002e6422748978e0bf3f5f69cc9e973bc72539de565e84a069ac250869e6ad0009
 X-Customer : 1746183
 X-Signature : 4c077b81c58ddf64d0bb2de61524ab92357d483d11aa75ec9bd1beb178189003

확인 부탁드립니다!

**Comment by naver-searchad** [comment]
@sspjk83 안녕하세요. 네이버 검색광고 API입니다.

서명값 (X-Signature) 이 base64 인코딩 된 값으로 전송이 되야하는데, 그 부분이 잘못되있는것 같습니다.

https://github.com/naver/searchad-apidoc/blob/master/java-sample/src/main/java/com/naver/searchad/api/util/Signatures.java

예제의 서명 생성 로직 참고하시면 될것 같습니다.

참고로 403에러 응답시 response body에 오류 원인에 대한 내용도 포함해서 전달하고 있으니, 추후에는 그 부분도 참고 부탁드리겠습니다.

감사합니다.

**Comment by sspjk83** [comment]
이슈 잘 해결되었습니다. 감사합니다!
