### ISSUE TITLE
주요 매체 리스트 코드 관련

### ISSUE THREAD

**Issue by kaorimikage** [naver/searchad-apidoc#695]
![image](https://user-images.githubusercontent.com/25290207/205222340-4c49971d-b1bf-4cb4-89e1-f5501b98c2bb.png)

이 내용을 여기에 질문을 해야할지 모르겠습니다만, 네이버 검색광고 사이트에서 다운받는 주요 매체 리스트 엑셀파일이 관리가 되고 있는 것인지 문의 드립니다.

현재 다운받은 엑셀에 test001.com 이라는 이상한 사이트도 내용에 포함되어 있고. 스타일 추천 광고상품코드(510563)도 포함되어 있지 않습니다.

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API 대용량 다운로드 보고서 담당자입니다. 

네. 최근 해당 메뉴 관련 문의가 인입된 일이 있어 담당자에게 전수조사를 요청을 해둔 상태입니다. 
확인이 완료 되면 답변 드리도록 하겠습니다. 

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 API 담당자입니다. 

담당자에게 문의한 결과 해당 기능의 데이터는 관리되고 있었습니다. 단 수작업 관리는 아니고 저희 매체 정보 DB에서 데이터를
계속 업데이트 받는 형태이라 이상한 매체가 존재함에도 인지하지 못하고 있었던것으로 보입니다. 

 test001.com은 기능 테스트 과정에서 임의로 생성했던 매체인데 삭제 작업이 누락되어 있었으며
현재 삭제 완료 하였습니다. 혼란 드려 대단히 죄송합니다. 

캡쳐로 보여주신 곳은 파워링크 광고그룹의 광고 노출 매체 설정 화면인데요. 이 페이지에서 제공되는 매체 리스트는 파워링크 상품이 노출될수 있는 매체들로 한정됩니다. 
문의 주신 스타일 추천 광고상품코드 (510563)는 파워링크 노출 매체가 아니라서 제공되지 않은 것입니다. 

참고로 네이버 검색광고가 노출 되는 매체 전체를 확인하시려면 마스터의 미디어 마스터를 활용해 주시기 바랍니다. 

감사합니다.
