### ISSUE TITLE
state report 또는 master report 관련 질문이 있습니다.

### ISSUE THREAD

**Issue by jungseunghoon** [naver/searchad-apidoc#696]
state report 또는 master report 에서는  

SHOPPINGKEYWORD 으로 들어오는 키워드ID 에 대한  값 노출이 되지 않을까요 ?

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 대용량 보고서 담당자입니다. 

아마도 레퍼런스 상 Search keyword ID라고 표현이 잘못되어 있어 혼돈을 드린것 같습니다. 죄송합니다. 수정해 두었습니다.

쇼핑 상품의 경우 키워드(정확히 말씀드리면 검색어)를 광고 시스템에 등록하지 않기 떄문에 등록 키워드 ID (키워드 ID)가 존재하지 않습니다. 
따라서 STAT REPORT 중 Shopping Campaign Search Keyword Performance Detail Report (reportTp : SHOPPINGKEYWORD_DETAIL)와 Shopping Campaign Search Keyword Conversion Detail Report (reportTp : SHOPPINGKEYWORD_CONVERSION_DETAIL)의 Search keyword 필드에 표시되는 키워드명을 기준으로 지표를 확인하셔야 하며 어떤 검색어(키워드)에 광고가 노출 될지는 저희도 미리 알수 없으므로 마스터도 별도로 제공되지 않습니다. 

감사합니다.
