### ISSUE TITLE
list관련 api중 변경된 사항 정보는 어떤 것이 있나요?

### ISSUE THREAD

**Issue by younseunghyun** [naver/searchad-apidoc#7]
adgroup의 list의 response 값이 현재 변경 사항이 있는것 같은데, 다른 entity에서도 list에 관련하여 변경되어있는 사항이 있나요?

**Comment by naver-searchad** [comment]
따로 변경된 내용은 없습니다.
Adgroup 변경 된 내용은 https://github.com/naver/searchad-apidoc/issues/5#issuecomment-229844995 를 참고하세요.
자세한 변경 사항은 http://naver.github.io/searchad-apidoc/#/release-notes를 참고하세요.

**Comment by younseunghyun** [comment]
감사합니다  :)
