### ISSUE TITLE
매니저 아이디에 소속된 계정의 캠페인 정보는 못가져오나요 ?

### ISSUE THREAD

**Issue by jinwoo8333** [naver/searchad-apidoc#70]
안녕하세요.

customer-links (type => MYCLIENTS)로 매니저 계정에 소속된 계정정보를 가져오는건 성공했습니다

            [customerLinkId] => clk000000001445240
            [managerCustomerId] => xxxxxx
            [clientCustomerId] => xxxxxx
            [roleId] => 1
            [linkStatus] => 20
            [description] => salesRightAuto
            [regTm] => 2017-02-06T02:37:26.000Z
            [editTm] => 2017-02-06T02:37:26.000Z
            [managerLoginId] => xxxxxxxx
            [clientLoginId] => xxxxxxxxxxx
            [managerName] => xxxxxx
            [managerEnable] => 1
            [managerPenaltySt] => 0
            [managerCustomerDelFlag] => 0
            [clientEnable] => 1
            [clientPenaltySt] => 0
            [clientCustomerDelFlag] => 0
            [delFlag] => 0

위처럼 정보는 가지고 왔는데 이걸로 소속된 광고주의 계정의 캠페인 정보를 가져오는건
계속 권한이 없다라고 나옵니다. (아래는 사용한 소스 입니다.)

function Campaign ($customerID) {
        $qstr = array('ids' => $customerID);
	$res = RestApi::GET('/ncc/campaigns/'.$customerID);
	return $res;
}

위의 함수 결과값
Array
(
    [code] => 1018
    [status] => 404
    [title] => No permission to access the resource.
)

가능하다면 php로 된 Campaign 예제 부탁드립니다
 (최종 목표는 소속된 광고주 계정들의 리포트를 생성하는게 목표입니다.)

그리고 Master Report에서 헤더들은 원래 안나요나요 ?

xxxxxx	grp-a001-01-00000000xxxxxxx	nkw-a001-01-000000xxxxxxxxx	노트북	4

단순히 위 처럼 나와서 뭐가 뭔지를 모르겠네요

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

캠페인 조회건은 호출 시간과 트랜잭션 아이디를 알려 주실 수 있으실까요?
에러만 봐서는 호출 인자양식이 잘 못된것 같습니다. 
호출 URL 의 형태가 (앞부분생략) /campaigns?customerId = 호출대상이되는 계정의 커스터머 아이디 
이어야 합니다. 

두번째로 마스터는 헤더를 데이터 파일에 포함하지 않고 있습니다. 
저희 API 개편 된 시점인 2016년 7월 이전에는 헤더가 있었으나 
헤더가 있어 처리하기 불편하다는 의견이 압도적으로 높아 제거했습니다. 

헤더는 http://naver.github.io/searchad-apidoc/ 에서 보실 수 있습니다. 
보고서에 대한 한글 문서는 광고시스템>보고서>대용량 다운로드 보고서에서 확인하실 수 있습니다.
(단 , 몇개 마스터보고서는 스팩이 한글 판에는 아직 업데이트 전이라 이점 유의 부탁드립니다.)

감사합니다.

**Comment by jinwoo8333** [comment]
안녕하세요 : ) 댓글 감사합니다 !

트랜젝션 아이디는 Transaction-ID : AVKKG7IBHPO6C 입니다
위에 말씀하신대로 하니 Transaction-ID : unknown ,  404 Not Found가 리턴됩니다

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

제가 착각을 했습니다. 죄송합니다. 
캠페인을 계정 단위로 호출 하실때는 헤더 중 X-Customer 항목에 영업권 광고주님 커스터머 아이디  즉 customer-links를 통해 [clientCustomerId] 항목으로 리턴된 값을 넣으시고 
/ncc/campaigns 을 인자 없이 그대로 호출 하시면 되겠습니다.

감사합니다.

**Comment by jinwoo8333** [comment]
안녕하세요 좋은 아침입니다 : )
말씀하신대로하니 성공했습니다 감사합니다 : )

마스터 레포트도 위와같은 방식으로 하면 될까요 '' ?

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

호출에 성공 하셨다니 다행입니다. 
네 모든 API 호출 시 대상 계정(고객 커스터머아이디)를 x-customer 항목에 입력하셔서 헤더를 구성하시
면 해당 계정에 대한 정보가 리턴됩니다. 

마스터 리포트, STAT 리포트의 경우 
STEP 1. 파일 생성 요청 (POST /master-reports)
STEP 2. 파일 생성 여부 확인 (GET /master-reports/{id})
STEP 3. 생성된 파일의 리턴된 URL로 다운로드 (리턴된 downloadUrl 이용)

방식으로 사용하실 수 있습니다. 

p.s 오전에 마스터 리포트 생성에 지연이 발생하고 있다는 신고가 인입되어 확인 중입니다. 
해 보시고 안되시면 오후에 재 시도해 보시는 것이 좋을듯 싶습니다.

감사합니다.

**Comment by jinwoo8333** [comment]
와 엄청 빠른 답변 감사합니다 !
해보고 안되면 죄송하지만 다시 문의드릴께요 ! 좋은 하루 되세요 : )

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

장애가 있었고 복구 완료 되었습니다. (DOC.API.NAVER.COM 참고부탁드립니다.)
테스트 해보시면 되겠습니다.

불편 드려 죄송합니다.

**Comment by jinwoo8333** [comment]
안녕하세요 문의 또 드릴게 있어서 남깁니다 : )

캠페인 마스터 (Campaign)
캠페인 예산 마스터 (CampaignBudget)
비지니스채널 마스터 (BusinessChannel)
그룹 마스터 (Adgroup)
그룹예산 마스터 (AdgroupBudget)
키워드 마스터 (Keyword)
소재(광고) 마스터 (Ad)
확장 소재(광고) 마스터 (AdExtension)
품질지수 마스터 (Qi)
즐겨찾기 마스터 (Label)
즐겨찾기설정 마스터 (LabelRef)

이렇게 연관된다는것까지는 알았는데, 해당 리포트 마스터를 tsv로 다운 받으면
헤더가 없어서 무슨 값인지를 모르겠습니다 
(위에서 링크주시곳 들어가서 찾아봐도 모르겠습니다 ㅠㅠ)

혹시 위의 리포트 마스터를 각각 다운 받을 시, tsv 파일에 헤더를 좀 알려주실 수 있을까요 ?
예를 들면

캠페인 마스터 (Campaign)
	고객번호
	그룹아이디
	캠페인아이디
        ...
        ...
        ...

캠페인 예산 마스터 (CampaignBudget)
        고객번호
	캠페인아이디
        ...
        ...

이런식으로여... 부탁 좀 드릴께요...
리포트는 뽑아왔는데..
0 0 이렇게 나오면 모르겠어요.... ㅠㅠ

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

https://saedu.naver.com/help/faq/ncc/view.nhn?faqSeq=178
여기 사양서를 참고 부탁드립니다. (이쪽이 더 보기 편하실 껍니다.)
설명이 빠진 마스터는 
http://naver.github.io/searchad-apidoc/#/tags/MasterReport
여기서 확인 부탁드립니다.

감사합니다.

**Comment by jinwoo8333** [comment]
아 PDF 파일 받으니 나와있네요 ! 속이 시원합니다 ㅠㅠ
감사합니다 ㅠㅠㅠㅠㅠㅠㅠㅠ

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

네. 한두개 마스터가 빠져 있습니다만...마스터가 계속 추가될 예정이라 모아서 작업하느라 
아직 작업은 안되어있습니다. 불편하시더라도 빠진 마스터는 메뉴얼 사이트 참고 부탁드립니다. 

감사합니다.

**Comment by jinwoo8333** [comment]
안녕하세요 : ) 또 다시 문의 드리로 왔습니다 !!

[customerId] => xxxxxx  # 커스터머 ID
[campaignTp] => WEB_SITE # 캠페인 유형
[name] => API_파워링크 # 캠페인 명
[useDailyBudget] => 1 # 일일예산제한 사용 여부
[dailyBudget] => 10000 # 일일예산 금액
[deliveryMethod] => STANDARD # ? 예산균등배분
[trackingMode] => AUTO_TRACKING_MODE # 트래킹 여부
[usePeriod] => 1 # 기간 설정 여부
[periodStartDt] => 2017-11-17T00:00:00+09:00 # 시작일자
[periodEndDt] => 2018-02-01T00:00:00+09:00 # 종료일자 

Campaign을 생성하려고 POST 로 전송하려고 합니다 : )

[deliveryMethod] => STANDARD # ? 예산균등배분

이 부분이 예산 균등 배분이 맞는지 해서 문의 남깁니다 !

ACCELERATED = 예산 균등분배 하지 않음
STANDARD = 예산 균등분배 실행

이렇게 이해하는게 맞나요 '' ?

**Comment by jinwoo8333** [comment]
@naver-searchad 님 안녕하세요 : ) 또 다시 문의 드리로 왔습니다 !!

[customerId] => xxxxxx				# 커스터머 ID
[campaignTp] => WEB_SITE			# 캠페인 유형
[name] => API_파워링크				# 캠페인 명
[useDailyBudget] => 1				# 일일예산제한 사용 여부
[dailyBudget] => 10000				# 일일예산 금액
[deliveryMethod] => STANDARD			# ? 예산균등배분
[usePeriod] => 1				# 기간 설정 여부
[periodStartDt] => 2017-11-17T00:00:00+09:00	# 시작일자
[periodEndDt] => 2018-02-01T00:00:00+09:00	# 종료일자 
[trackingMode] => AUTO_TRACKING_MODE		# 트래킹 여부

Campaign을 생성하려고 POST 로 전송하려고 합니다 : )

[deliveryMethod] => STANDARD # ? 예산균등배분

이 부분이 예산 균등 배분이 맞는지 해서 문의 남깁니다 !

ACCELERATED = 예산 균등분배 하지 않음
STANDARD = 예산 균등분배 실행

이렇게 이해하는게 맞나요 '' ?

그리고 시간값

[periodStartDt] => 2017-11-17T00:00:00+09:00 # 시작일자
[periodEndDt] => 2018-02-01T00:00:00+09:00 # 종료일자 

이렇게 설정하는게 맞나요 '' ?

위와 같이 넣으니
Array
(
    [code] => 1028
    [status] => 400
    [title] => Invalid request message.
)

이렇게 나옵니다 ㅠ.ㅠ

트랜젝션 아이디는 Transaction-ID : AVOD6TOOPPAUO 입니다 !

영어때기를 아무리봐도.. 파파고건 번역을 돌려도 모르겠습니다 ㅠㅠ

**Comment by jinwoo8333** [comment]
@naver-searchad 안녕하세요 : )

문의드릴게 있어서 남깁니다

캠페인 생성 (Request) 시 예산 균등분배의 필드명은 무엇인가요 '' ?

**Comment by naver-searchad** [comment]
@jinwoo8333 

안녕하십니까 검색광고 API입니다. 

문의 주신 사항이 메일로는 확인이 되는데 (캠페인 설정 방식, 균등 노출 설정등)
GITTUB에서는 확인이 되지 않습니다. 
죄송합니다만 다시 한번 등록해 주실 수 있으실지요?(별도 이슈 등으로 등록해 주시는 것도 무방합니다.)
저희 기술 지원은 API 서비스를 직접 설계/구축하신 엔지니어 분들이 드리고 있어 
이슈에서 해당 건이 확인 되어야 답변을 원활하게 드릴 수 있는 점 양해 부탁드립니다.

감사합니다.

**Comment by jinwoo8333** [comment]
@naver-searchad 좋은 아침입니다 : )
지워서 죄송해요 ! 쓰고나서 이리저리 해보니 또 해결이 되어서지웠어요 ㅠㅠ
다음에 또 문의 있으면 남길께요 신경써주셔서 감사합니다 : )
