### ISSUE TITLE
Adgroup: update 문의

### ISSUE THREAD

**Issue by LeeJaiBok** [naver/searchad-apidoc#700]
adgroup에 update를 하는데 아무런 응답이 없네요. 뭐가 잘못된건지 혹시 확인이 가능할지....

조회데이터
$data = $api->GET("/ncc/adgroups/grp-a001-02-000000029313704");

조회데이터 응답 print_r로 찍음 : 
Array ( [nccAdgroupId] => grp-a001-02-000000029313704 [customerId] => 1369772 [nccCampaignId] => cmp-a001-02-000000005822071 [mobileChannelId] => bsn-a001-00-000000000888832 [pcChannelId] => bsn-a001-00-000000000888832 [bidAmt] => 100 [name] => 단체줄넘기(시험)_광고그룹#1 [userLock] => [useDailyBudget] => [useKeywordPlus] => [keywordPlusWeight] => 100 [contentsNetworkBidAmt] => 50 [useCntsNetworkBidAmt] => [mobileNetworkBidWeight] => 100 [pcNetworkBidWeight] => 100 [dailyBudget] => 0 [budgetLock] => [delFlag] => [regTm] => 2022-09-21T05:23:11.000Z [editTm] => 2022-12-28T04:53:57.000Z [targets] => Array ( [0] => Array ( [nccTargetId] => tgt-a001-02-000000333668035 [ownerId] => grp-a001-02-000000029313704 [targetTp] => MEDIA_TARGET [target] => Array ( [type] => 1 [search] => Array ( ) [contents] => Array ( ) [white] => Array ( [media] => [mediaGroup] => ) [black] => Array ( [media] => [mediaGroup] => ) ) [delFlag] => [regTm] => 2022-09-21T05:23:11.000Z [editTm] => 2022-12-28T04:27:28.000Z ) [1] => Array ( [nccTargetId] => tgt-a001-02-000000333668036 [ownerId] => grp-a001-02-000000029313704 [targetTp] => PC_MOBILE_TARGET [target] => Array ( [pc] => 1 [mobile] => 1 ) [delFlag] => [regTm] => 2022-09-21T05:23:11.000Z [editTm] => 2022-12-27T16:20:31.000Z ) ) [targetSummary] => Array ( [pcMobile] => all [media] => all ) [pcChannelKey] => 쭈비쭈비 (https://smartstore.naver.com/jjubi316) [mobileChannelKey] => 쭈비쭈비 (https://smartstore.naver.com/jjubi316) [status] => ELIGIBLE [statusReason] => ELIGIBLE [expectCost] => 0 [migType] => 0 [adgroupAttrJson] => Array ( [campaignTp] => 2 ) [adRollingType] => ROUND_ROBIN [adgroupType] => SHOPPING [systemBiddingType] => NONE [useCntsNetworkBidWeight] => [contentsNetworkBidWeight] => 100 )

수정데이터
$data2 = $api->PUT("/ncc/adgroups/grp-a001-02-000000029313704", $data);

수정데이터 응답 : 
아무것도 오지 않음. 

apidoc에 있는 항목은 다 넣었고, 변경값 고쳐서도 해보고, 받은값 그대로 던져도 뭔가 반응이 없습니다.
데이터가 잘못되면 잘못되었다던가 오류가 나야 할거같은데 응답도 없으니 답답하네요.

감사합니다.

**Comment by naver-searchad** [comment]
@LeeJaiBok 안녕하세요? 네이버 검색광고 API 담당자 입니다.

서버에서 해당 요청을 확인해본 결과 400 응답을 내려주고 있는데요.

오류응답은 정상적으로 내려가지만 클라이언트에서 오류 응답 출력이 안되는것으로 보입니다.

https://github.com/naver/searchad-apidoc/blob/57c4574df55bbababc4d4dafb69bedf9a3e39687/php-sample/restapi.php

제공되는 php 샘플코드를 사용하고 있으신걸로 보이는데요. 
해당 샘플의 경우 오류 응답을 리턴하지 않고, 콘솔에 오류를 출력하는 식으로 되어있으니 그 부분 참고 부탁드리겠습니다.

감사합니다 :)

**Comment by LeeJaiBok** [comment]
$resp = $api->PUT("/ncc/campaigns/cmp-a001-02-000000005822071", $campaign);

Array ( [nccCampaignId] => cmp-a001-02-000000005822071 [customerId] => 1369772 [name] => 단체줄넘기(시험) [userLock] => [campaignTp] => SHOPPING [deliveryMethod] => ACCELERATED [trackingMode] => TRACKING_DISABLED [usePeriod] => [dailyBudget] => 10000 [useDailyBudget] => [totalChargeCost] => 0 [status] => ELIGIBLE [statusReason] => ELIGIBLE [expectCost] => 0 [migType] => 0 [delFlag] => [regTm] => 2022-09-21T05:22:35.000Z [editTm] => 2022-12-28T08:52:51.000Z )

동일한 restapi를 써서 캠페인쪽을 수정하면 위와같이 응답이 옵니다.
그럼 오류출력은 그거랑 상관이 없지않을지....

그리고 형식을 아예 잘못보낼경우는 에러가 아래와 같이 나왔습니다.
Array ( [title] => Bad Request [status] => 400 [detail] => JSON parse error: Cannot deserialize instance of `java.util.ArrayList` out of VALUE_STRING token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.util.ArrayList` out of VALUE_STRING token at [Source: (PushbackInputStream); line: 1, column: 1] )

그런데 처음 문의한대로 던지면 답이 안보이는 상황이....

아니면 최종 에러난 오류라도 알려주시면 감사하겠습니다.

**Comment by naver-searchad** [comment]
@LeeJaiBok 
안녕하세요? 네이버 검색광고 API 담당자 입니다.

php 샘플을 사용하시는게 맞다면, 
https://github.com/naver/searchad-apidoc/blob/57c4574df55bbababc4d4dafb69bedf9a3e39687/php-sample/restapi.php#L85

해당 부분에서 header 와 body 를 바로 출력해서 확인 부탁드리겠습니다.
아마 body 를 json_decode 하는 과정에서 문제가 되지않았나 추측됩니다.

감사합니다.

**Comment by LeeJaiBok** [comment]
감사합니다.

일단 알려주신대로 body찍으니 나오네요.

그거 바탕으로 문제 해결하였습니다.

감사합니다.

새해 복 많이 받으세요~
