### ISSUE TITLE
stat-report에서 media code

### ISSUE THREAD

**Issue by develop-kjy** [naver/searchad-apidoc#701]
이건 각각 뭘의미하는지는 어떻게 알수잇나요??

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드보고서(STAT-REPORT 및 MASTER) 담당자입니다. 

MASTER REPORT(http://naver.github.io/searchad-apidoc/#/tags/MasterReport)에서 Media Details (Media)을 항목을 참고하여 주시기 바랍니다.

감사합니다.
