### ISSUE TITLE
변경 도메인에서 평균입찰가 조회 시 오류 문의

### ISSUE THREAD

**Issue by idiotHP** [naver/searchad-apidoc#702]
기존 도메인 : api.naver.com
변경 도메인 : api.searchad.naver.com

변경된 도메인으로 평균입찰가 조회 시 오류가 납니다.
 ※ 해당 REQUEST : POST /estimate/average-position-bid/{type}   - {type}은 id로 넣었습니다.

기존 도메인으로 요청 시 응답이 제대로 오지만
변경된 도메인으로 요청 시 응답이 "��VJI �LNU�R��w��qU�QJ-.��M,�EW+%e�(YYL}3{��" 이런식으로 옵니다.

header에 Content-Type은 'application/json; charset=UTF-8'으로 제대로 설정되어있습니다.

오류 확인 부탁드립니다.

**Comment by naver-searchad** [comment]
@idiotHP 안녕하세요. 네이버 검색광고 API 담당자 입니다.

말씀 주신 API 를 신규도메인으로 테스트해봤을때 정상응답이 오는것을 확인하였습니다.

1. 혹시 다른 API 를 호출하셨을때도 오류응답이 오는지도 한번 확인부탁드리겠습니다.
2. 오류응답이 왔을때의 응답의 다른 헤더나 body 의 정보  또는 해당 요청후 응답을 찍는 코드의 내용을 알려주시면 문제를 확인하는데 도움이 될것 같습니다.

감사합니다 :)
