### ISSUE TITLE
마스터리포트 downloadUrl 도메인 변경 여부 문의

### ISSUE THREAD

**Issue by hyoeun-dbase** [naver/searchad-apidoc#703]
안녕하세요
현재 /master-report를 조회하면 downloadUrl 필드의 도메인은 api.naver.com인데요,
도메인이 api.searchad.naver.com으로 바뀌면 마스터 리포트 다운로드 URL의 도메인도 변경되는 것인가요?
변경되는 것이라면 기존 마스터리포트 다운로드 URL 도에인도 변경되는 것인지 질문드립니다.

**Comment by naver-searchad** [comment]
안녕하세요. 네이버 검색광고 API 담당자입니다.

downloadUrl 필드의 도메인도 기존 도메인 종료전에 변경이 될 예정입니다.

감사합니다 :)
