### ISSUE TITLE
/stats API 새벽 시간대 데이터 문의

### ISSUE THREAD

**Issue by suhl-lee** [naver/searchad-apidoc#704]
안녕하세요,
오늘 광고 실적을 조회하기 위해 /stats API를 datePreset "today"로 호출하여 사용하고 있는데
새벽 2시경에는 오늘 실적이 아닌 전날의 실적으로 데이터가 리턴되는 것을 확인했습니다.

특정 시간대에 "today"로 호출하더라도 오늘 실적이 아닌 데이터가 들어올 수 있는 것인지,
그렇다면 몇 시 이후에 오늘 실적을 조회할 수 있는 것인지 문의 드립니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

today 지표는 정확하게 데이터를 전달 드리기 위해서 실제 시간과 4시간 정도의 delay를 가지고 제공하고 있습니다.
따라서 00시 ~ 01시 데이터는 새벽 4시부터 확인해 주시면 됩니다.

감사합니다.
