### ISSUE TITLE
Adgroup: list (keyword plus restricted keywords) 조회 관련 문의

### ISSUE THREAD

**Issue by ghost** [naver/searchad-apidoc#705]
안녕하세요. 제외 키워드 조회 시도하였으나 빈 list가 반환되어 문의드립니다.
signature는 아래와 같이 생성하였습니다
'1673953499446.GET./ncc/adgroups/{group_id}/restricted-keywords' << 실제 운영 중인 캠페인의 그룹 ID를 넣어서 생성

request의 header에는 아래와 같이 전송했습니다.
{'Content-Type': 'application/json; charset=UTF-8',
 'X-Timestamp': '1673958031698',
 'X-API-KEY': 'API_KEY',
 'X-Customer': 'CUSTOMER_ID',
 'X-Signature': b'1OH+4J0s4snNFeUoukaPwtx56aWXeKIk8/SvR+pz+cM='}

https://naver.github.io/searchad-apidoc/#/operations/GET/~2Fncc~2Fadgroups~2F%7BadgroupId%7D~2Frestricted-keywords%3Ftype=KEYWORD_PLUS_RESTRICT
위의 가이드 문서에서는 ?type&#x3D;KEYWORD_PLUS_RESTRICT 까지 포함하는 것으로 안내가 되어 있었으나,
포함하여 signature 생성할 경우 invalid signature 오류가 발생하여 제외하고 진행하였는데 관련하여 검토 부탁드립니다..!

**Comment by naver-searchad** [comment]
@jsmin123 안녕하세요? 네이버 검색광고 API입니다.

1. signature 생성시 파라미터는 빼고 생성하셔야 합니다.
2. 제외 키워드 조회시 빈 list가 반환 되었다고 하셨는데, 호출했던 Transaction id를 알려주셔야 확인이 가능합니다.

감사합니다.

**Comment by jsmin123** [comment]
안녕하세요, 답변 감사드립니다
의도했던 기능은 쇼핑검색 광고그룹에서의 제외키워드를 확인하는 것이었는데, 기능을 살펴보았을 때 키워드 확장 기능에서의 노출 제한 키워드에 대한 기능인 점을 확인하였습니다.
혹시 쇼핑검색 광고그룹의 제외키워드 목록을 확인할 수 있는 기능은 개발되어있는 것이 없을까요?

**Comment by jjung2945** [comment]
안녕하세요 저도 jsmin123님과 같은 질문이 있습니다. 혹시 키워드 제외는 매뉴얼한 방식으로만 진행되야 하는걸까요?
