### ISSUE TITLE
삭제한 광고의 type을 확인할 수 있는 api가 있을까요?

### ISSUE THREAD

**Issue by gojaeheon** [naver/searchad-apidoc#706]
<img width="712" alt="image" src="https://user-images.githubusercontent.com/121282118/213632307-41a83db5-1180-4bcc-8f94-9a4273976593.png">

Ad API를 활용하면, 삭제한 광고를 조회할 수 없는 것으로 알고 있습니다.

따라서 삭제한 광고(소재)를 조회를 master-report를 통해 하고 있습니다.
그런데, 삭제한 광고(소재)는 type[TEXT_45, SHOPPING_PRODUCT_AD, CONTENTS_AD_INFORMATION, CONTENTS_AD_PRODUCT, BRAND_SEARCH_AD, PLACE_AD, CATALOG_AD]을 조회할 수 없는 것 같습니다....

혹시 **삭제한 광고의 type**을 get할 수 있는 좋은 방법이 있을까요?

**Comment by naver-searchad** [comment]
@gojaeheon 안녕하세요? 네이버 검색광고 API입니다.

삭제한 광고에 대해서 조회하는 기능은 제공하고 있지 않습니다.

감사합니다.

**Comment by gojaeheon** [comment]
브랜드 검색 광고는 광고 시에, 소재를 동시에 최대 5개 밖에 지원을 안해서 계속 삭제했다가 생성하는 일이 많더라구요..

그래서 삭제한 광고들에 대해 type 데이터를 가져오는게 꼭 필요한데ㅠㅠ
개발 예정도 없으실까요 😥
개발 요청을 드릴 수도 없을까요.. 흑흑
