### ISSUE TITLE
/stats  변경된 도메인으로 호출 시 문제

### ISSUE THREAD

**Issue by J-vInyL** [naver/searchad-apidoc#707]
안녕하세요 /stats API 기존 도메인 호출 시 정상적으로 값 넘어오는걸 확인했습니다.

다만 변경된 도메인으로 똑같이 호출 시 오류가 출력되오니 확인 해주시면 감사하겠습니다.

* 기존 도메인 
          GET (https://api.naver.com/stats)
                    parmas : {
                    id : "cmp-a001-01-000000006227176",
                    fieldds: '["impCnt", "clkCnt"]',
                    datePreset: "last7days"
                    }
=> 정상  출력 
==================================

* 변경 도메인  
        GET (https://api.searchad.naver.com/stats)
                    parmas : {
                    id : "cmp-a001-01-000000006227176",
                    fieldds: '["impCnt", "clkCnt"]',
                    datePreset: "last7days"
                    }
=> data: { code: 11001, message: '잘못된 파라미터 형식입니다.' }

**Comment by naver-searchad** [comment]
@J-vInyL 안녕하세요. 검색광고 API 담당자입니다.

신규 URL 에서 기존 API 스펙과 다른 부분이 있어서, 동일하게 처리하도록 수정완료되었습니다.

제보감사드립니다. :)
