### ISSUE TITLE
API 호출 수 제한 문의

### ISSUE THREAD

**Issue by jungmyounghwan** [naver/searchad-apidoc#708]
raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=35103): Max retries exceeded with url: /session/4bb796d511144b269bbe1a0ea950b22d/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4abc8de4e0>: Failed to establish a new connection: [Errno 111] Connection refused',))

1시간에 100회 미만 호출 하는데 위 같은 에러가 발생해서 문의 드립니다.
시도하는 IP는 59.9.236.1xx 입니다.

**Comment by naver-searchad** [comment]
@jungmyounghwan 안녕하세요. 네이버 검색광고 API 담당자 입니다.

해당 오류는 클라이언트에서 발생한 오류로 보이는데요. 정상적으로 요청중이신지 한번 확인부탁드리겠습니다.

감사합니다.

**Comment by jungmyounghwan** [comment]
Max retries exceeded with url

위 오류는 과도한 요청으로 막힌건 아닌건가요?

**Comment by jungmyounghwan** [comment]
평소엔 잘 됐었습니다

**Comment by naver-searchad** [comment]
@jungmyounghwan 

올려주신 오류 메시지상으론 검색광고 API 도메인이 아닌 127.0.0.1: 35103 쪽으로 호출을 해서 발생하는 문제로 보입니다.
이 부분 한번 확인부탁드리겠습니다.

**Comment by jungmyounghwan** [comment]
아 넵 제가 테스트하다가 한 곳 이상하게 수정한게 있었네요.. 확인 감사합니다.
