### ISSUE TITLE
키워드 생성이 되지 않습니다.

### ISSUE THREAD

**Issue by kaorimikage** [naver/searchad-apidoc#709]
신규 키워드를 생성하려고 하는데 생성이 되지 않습니다. 확인 부탁드립니다.

x-transaction-id: f91d728853b2a3fc

{"code":1005,"status":500,"title":"Cannot handle the request."}

**Comment by runbright** [comment]
@kaorimikage 키워드 생성 request 정보가 더 필요합니다.

**Comment by kaorimikage** [comment]
트랜젝션 ID에 정보가 있을것 같아서 올리지 않았습니다.
아래와 같은 형식으로 호출했습니다.

$api_link->POST('/ncc/keywords', array(array('keyword' => '070전화')), array('nccAdgroupId' => 'grp-a001-01-000000XXXXXXXX'));

**Comment by runbright** [comment]
@kaorimikage 에러 발생 시각 부탁드립니다

**Comment by kaorimikage** [comment]
뭔가 적혔다가 지워진것 같은데 현재는 키워드가 잘 생성이 되는 관계로 이슈 종료합니다.
