### ISSUE TITLE
AdKeyword의 status

### ISSUE THREAD

**Issue by kimdohoyeong** [naver/searchad-apidoc#71]
각각 다른 그룹에 등록되어있는(혹은 복사된) 같은 이름(검색어)의 키워드가 둘다 켜져있을 때,
실제 파워링크 지면에 노출되고 있는 광고가 무엇인지 알지 못하는 문제점이 있는 것 같습니다.
혹시 이를 알 수 있는 방법이 있나요?

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

API 서비스나 광고 시스템에서는 미리 아실 방법은 없습니다.
단, 대원칙은 입찰가 & 품질지수(AND조건입니다.)가 높은 쪽이 우선권을 가집니다. 

혹 추적 URL을 쓰시고 계신다면 클릭 발생시에는 어떤 광고가 노출되어 클릭이 발생했는지는 
추적URL을 통해 확인이 가능하십니다. 

감사합니다.
