### ISSUE TITLE
Signature 생성 문의

### ISSUE THREAD

**Issue by sprinter707** [naver/searchad-apidoc#710]
실적을 가져오는 api를 사용하고 있습니다.

`https://api.naver.com/stats?ids=nkw-a001-01-000004342720550%2Cnkw-a001-01-00000434272....`

`<--- HTTP/1.0 429 Too Many Requests `
위와 같이 Too Many Request 를 응답 받고 

내부 fallback 로직에 따라 몇초후 재요청을 시도하였습니다.

재요청시 Signature 를 다시 생성하여 X-Signature, X-Timestamp를 업데이트 하여 재요청 하고 있습니다.

`<--- HTTP/1.1 403 Forbidden`

하지만 위와 같이 403에러를 반환 받았습니다.

======

Signature 생성 후 몇초이내에 Signature를 새로 생성하여 요청하는 것에 대해 제한 사항이 있는지 

Signature 를 어떻게 관리해야 맞는지 알려주세요

**Comment by sprinter707** [comment]
추가 요청 정보 알려드립니다.

- Too many
```
Time : 2023/02/06 18:50:56.107
X-API-KEY: 010000000011974d9bcb84631046921dd497715e26b83cecb40ab8fa7f900911ba3a4c7f7e
X-Customer : 479332
X-Signature: Fcy1sEweXYtLv0TbSBm3r/zqTfs/R0gcCYSdQSq3MGI=
X-Timestamp: 1675677056107
```

- 403 Forbidden
```
Time: 2023/02/06 18:50:58.589
X-API-KEY: 010000000011974d9bcb84631046921dd497715e26b83cecb40ab8fa7f900911ba3a4c7f7e
X-Customer: 479332
X-Signature: asILQ9tAaadq0n4+zSnPCbYDymtusOXKqCnADDr5p4Y=
X-Timestamp: 1675677058589
```

**Comment by naver-searchad** [comment]
@sprinter707 안녕하세요. 검색광고 API 담당자입니다.

아래 403 요청 확인해보니 signature 생성을 잘못하신것 같습니다.

서명생성로직을 확인하셔서 문제가 없는지 확인부탁드리겠습니다. (https://naver.github.io/searchad-apidoc/#/samples)

- signature 생성시의 API_SECRET 값 확인
- 서명 생성시 값이 1675677058589.GET./stats 로 잘 되어있는지.

참고로 429 응답과 서명 생성 로직과는 무관하니 참고부탁드립니다.

감사합니다.
