### ISSUE TITLE
update campaign by field 관련 질문

### ISSUE THREAD

**Issue by jjung2945** [naver/searchad-apidoc#711]
안녕하세요, 

update campaign에서 budget값을 업데이트 시도 하면 dailyBudget이 바뀌지 않고 useDailyBudget만 False로 바뀌는 상황입니다. 
dailyBudget만 바꾸고 useDailyBudget은 그대로 유지하고 싶은데 어떻게 하면 될지 문의 드립니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

useDailyBudget과 dailyBudget은 한쌍으로 의미를 가집니다.
useDailyBudget 값이 true일 경우에만 dailyBudget이 적용이되고, dailyBudget만 단독으로 적용을 할 수는 없습니다.

감사합니다.
