### ISSUE TITLE
breakdown hh24로 시간대별 데이터를 볼 때 질문입니다.

### ISSUE THREAD

**Issue by lhw8611** [naver/searchad-apidoc#712]
stat > breakdown > hh24로 했을때 전환매출액을 알 수 있는 방법은 없나요?

필드에 ConvAmt를 했을때 설정한 날짜의 전체 전환매출액은 나오지만 시간대별로는 나오지 않네요

**Comment by naver-searchad** [comment]
stat api 에서 breakdown 단위의 전환 매출액은 제공되지 않습니다.
시간별 전환 매출액이 필요하실 경우
대용량 다운로드 보고서(statReport API)의 전환상세보고서(reportTp = AD_CONVERSION_DETAIL) 를 활용하실 수 있습니다.

감사합니다.
