### ISSUE TITLE
[급]키워드 등록 API 에러 발생

### ISSUE THREAD

**Issue by choics** [naver/searchad-apidoc#713]
현재 키워드 등록을 API로 호출할 경우 
3001	요청하신 그룹이 존재하지 않습니다.	The ad group you requested does not exist.
해당 에러가 리턴됩니다.
광고그룹도 분명히 존재하기 때문에 API 상에서 어떤 부분이 문제가 있는지 확인 부탁드립니다.

**Comment by choics** [comment]
키워드의 랜딩URL을 수정할때도 동일 에러가 발생합니다.

**Comment by naver-searchad** [comment]
@choics input data등 구체적인 정보를 부탁드립니다.
키워드의 그룹id와 파라미터의 그룹id가 다를 경우 그러한 문제가 발생할 수 있습니다.

**Comment by choics** [comment]
키워드 랜딩 URL 수정에 대해서는 내부적으로 확인했습니다.
다만 키워드 등록은 에러가 발생하다가 답변 주신 이후 시도해보니 정상적으로 되는데
이슈가 있었던 것은 아닌지 확인 부탁드립니다.

**Comment by sanghyuk07** [comment]
어제 오후 6:00부터 저도 같은이슈로 문제가 있었습니다. 3001코드와 함께 
"The ad group you requested does not exist." 해당 에러가 리턴되었습니다. 현재는 저도 정상적으로 작동됩니다.
