### ISSUE TITLE
네이버 광고 API로 파워링크 순위를 가져 올 수 있을까요? 

### ISSUE THREAD

**Issue by samsunggnusmas** [naver/searchad-apidoc#714]
현재 네이버 광고 유료 서비스 사용중입니다.
파워링크 순위를 가져오고 싶은데 가능할까요?

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 API 입니다. 

보고서(STAT 및 STAT REPORT) 지표를 통해 과거에 실제 노출된 평균 노출 순위 정보를 받으실수 있습니다. 

STAT( avgRnk필드) : https://naver.github.io/searchad-apidoc/#/operations/GET/~2Fstats%7B%3Fid,fields,timeRange,datePreset,timeIncrement,breakdown%7D

STAT REPORT(각 보고서의 Sum of AD rank와 Impression 필드) : https://naver.github.io/searchad-apidoc/#/tags/StatReport

STAT의 경우 가장 짧은 기간은 1시간이며  STATREPORT의 경우 하루 입니다. 
또한 STAT REPORT의 경우는 어떤 단위(키워드, 광고그룹, 캠페인 등)로든 평균 노출 순위를 계산하실수 있도록 노출순위의 합과 노출수를 제공드리고 있습니다.
(평균 노출 순위 = 노출 순위의 합 / 노출수)

현재 노출 예상 순위(조회 시점 현재 노출이 발생한다면 노출될 것으로 예상되는 순위)정보는 저희로서도 알수 없으므로 제공드리지 않고 있습니다. 

감사합니다.

**Comment by samsunggnusmas** [comment]
빠르고 친절한 답변 감사합니다.
