### ISSUE TITLE
/stats datePreset에서 today로 조회하면 데이터가 표시 되지 않습니다.

### ISSUE THREAD

**Issue by samsunggnusmas** [naver/searchad-apidoc#715]
Http Status : 200 Transaction-ID : unknown Array ( [data] => Array ( ) [compTm] => 202302140959 [cycleBaseTm] => 202302140600 )

today, yesterday를 조회하면 위와 같은 메세지만 표시 되는데 무슨 이유일까요?
미리 답변 감사드립니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다

데이터가 존재하지 않는 (노출이나 클릭이 일어나지 않은) 날짜에 대해서 요청을 주신 것으로 보입니다.

감사합니다.
