### ISSUE TITLE
쇼핑박스도 API 지원을 하고 있나요?

### ISSUE THREAD

**Issue by ephiviolla** [naver/searchad-apidoc#716]
안녕하세요. 혹시 쇼핑박스도 API 지원을 하고 있나요?
만약 지원중이라면 API DOC 주소 부탁드리겠습니다.
지원하지 않고 있다면 지원 예정인지도 알고 싶습니다.

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 API 입니다. 

문의 주신 쇼핑박스 API는 현재 제공되지 않고 있습니다. 
향후 제공 여부 등 추가 문의가 있으신 경우 아래 문의 채널을 이용하여 주시기 바랍니다.

https://talk.naver.com/ct/wc3n30
https://center.shopping.naver.com/

감사합니다.

**Comment by ephiviolla** [comment]
답변 감사합니다!
