### ISSUE TITLE
CUSTOMER_ID 만 가지고 Stat Report를 다운 받을 수 있을까요? 

### ISSUE THREAD

**Issue by Jeongmin25** [naver/searchad-apidoc#717]
API_KEY와 SECRET_KEY 없이 Conversion Report를 다운 받고 싶습니다. 
CUSTOMER_ID 만 가지고 다운 받을 수 있는 방법이 있을까요? 

혹은  API_KEY와 SECRET_KEY 를 가지고 진행시 Performance Report만 다운이 되는데 
어떤 방법으로 진행해야 Conversion Report를 다운 받을 수 있을까요?

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 대용량 다운로드 보고서 담당자입니다. 

말씀의 의미를 정확하게 파악하기가 어려워 일단 아래와 같이 가정하여 답변 드립니다. 

 "API_KEY와 SECRET_KEY 없이"
--> API 서비스를 이용하지 않고 STAT REPORT를 다운받는 방식 
"혹은 API_KEY와 SECRET_KEY 를 가지고 진행시 Performance Report만 다운이 되는데
어떤 방법으로 진행해야 Conversion Report를 다운 받을 수 있을까요?" 
--> API를 이용해서 다양한 STAT REPORT를 다운받는 방식 

우선 API를 이용하지 않고 STAT REPORT를 수령하실수 있는 방법은 광고관리 시스템 UI를 이용하는 방식입니다. 

광고관리시스템(searchad.naver.com)을 이용하는 방식
본인의 계정 지표인 경우 : 로그인 아이디와 패스워드를 이용해 로그인 하신 후 보고서> 대용량 다운로드 보고서 메뉴을 이용하시면 됩니다. 
타인의 계정 지표인 경우 : 타인 계정에 대한 조회 이상의 권한을 본인 계정이 가지고 계신다고 가정할때 본인의 로그인 아이디와 패스워드를 이용해 광고 관리시스템에 로그인 하신 후 우측 상단 본인 아이디 클릭후 조회할 대상 광고 계정의 로그인 아이디를 입력하시어 해당 계정으로 이동하신 후 보고서> 대용량 다운로드 보고서 메뉴을 이용하시면 됩니다. 

API 서비스 혹은 광고관리시스템 UI 모두 동일한 보고서 기능을 이용하고 있으며 공통적으로 
전환 지표 관련 보고서는 아래와 같이 제공되고 있습니다. 
https://github.com/naver/searchad-apidoc/wiki/FAQ-stat#q-stattype-%EC%9D%84-%ED%86%B5%ED%95%B4%EC%84%9C-%EC%A0%9C%EA%B3%B5%EB%90%98%EB%8A%94-%EB%B3%B4%EA%B3%A0%EC%84%9C-%EC%A2%85%EB%A5%98
Conversion Report (reportTp : AD_CONVERSION)
Conversion Detail Report (reportTp : AD_CONVERSION_DETAIL)
AD extension Conversion Report (reportTp : ADEXTENSION_CONVERSION)
NAVER PAY Report (reportTp : NAVERPAY_CONVERSION)
Shopping Campaign Search Keyword Conversion Detail Report (reportTp : SHOPPINGKEYWORD_CONVERSION_DETAIL)
Shopping Campaign Brand Type Product Conversion Report(reportTp :SHOPPINGBRANDPRODUCT_CONVERSION)

두번째 문의 주신 다양한 보고서를 수령하기 위해서는 
Create 요청을 주실때 reportTp 에 원하는 보고서 타입 코드를 넣어서 요청 주시면 되겠습니다. 
혹 STAT REPORT 사용법이 익숙치 않으시다면 아래 레퍼런스를 참고해 주시기 바랍니다.
https://naver.github.io/searchad-apidoc/#/operations/POST/~2Fstat-reports

참고로  STAT REPORT의 기본적으로 아래와 같은 단계를 통해 제공됩니다. 

CREATE로 보고서 생성 요청 
GET 메소드를 통해 보고서 생성 여부 조회 
만일 생성이 완료 되었다면 리턴된 download URL로 파일 다운로드 

감사합니다.
