### ISSUE TITLE
[긴급..] 잘 되던 네이버 API가 특정 시간이 지나면 invalid api key로 에러처리가 됩니다.

### ISSUE THREAD

**Issue by sogangCSmaster** [naver/searchad-apidoc#718]
안녕하세요 네이버 광고 API를 잘 되다가
특정 시간이 지나면 갑자기 api key가 유효하지 않다고 뜹니다.

아무것도 코드를 변경하지 않고
엑세스 라이센스랑 와 비밀키를 다시 재발급 받으면 또 잘 작동됩니다.

```
data: {
      apikey: '{apikey}',
      detail: "API-KEY '{apikey}' is invalid.",
      status: 403,
      title: 'Invalid API-KEY',
      type: 'urn:naver:api:problem:invalid-apikey'
    }
```

이러다가 또 특정 시간이 지나면 위와 같은 에러가 발생합니다.

**Comment by sogangCSmaster** [comment]
![image](https://user-images.githubusercontent.com/32369381/218899131-27df0729-60fd-4ec5-bdb9-e85cc274af6d.png)

![image](https://user-images.githubusercontent.com/32369381/218899229-84e523e3-4266-44d7-9266-5603b94041a4.png)

추가 설명 드립니다.
예전엔 그러지 않다가 최근들어 잘 뜨다가 갑자기 데이터가 뜨지 않고 확인해보면 api key가 유효하지 않다고 뜹니다.
한번도 아니고 잘 되다가 또 시간지나면 api key가 유효하지 않다고 뜹니다.

**Comment by naver-searchad** [comment]
@sogangCSmaster 
안녕하세요 네이버 검색광고 API 담당자입니다.

확인하기 위해서는 요청하신 내용에 대한 정보가 더 필요합니다.

응답헤더의 X-Transaction-ID 정보 또는 Invalid API KEY 오류가 발생하고 있는 엑세스 라이센스 정보를 알려주시면 확인해보겠습니다.
(비밀키없이 엑세스 라이센스만 알려주시면 됩니다 )

**Comment by sogangCSmaster** [comment]
@naver-searchad 
안녕하세요 원인은 찾았습니다.

저희가 대행사인데 저희 계정으로 로그인해서 신규 광고주 계정을 이관받아 API key를 발급받으면
기존 저희 계정에 연결되어 있는 다른 모든 광고주 계정의 api key들이 동시 다발적으로 바뀌는것으로 확인했습니다.

엑세스 라이센스가 로그인하는 계정과 묶여있다보니
신규 광고주 계정을 이관 받으면 아래와 같은 화면이 아닌 기존 저희 엑세스 라이센스, 비밀키에 customerId만 다른 화면이 나오는게 맞지 않나 생각합니다.

![image](https://user-images.githubusercontent.com/32369381/218911477-b4b1b668-5d24-41d0-8bf1-2d11a93f6070.png)


저희처럼 여러 광고계정을 다루는 업체는 계정 이관받으면 저 화면 때문에 버튼을 누를 수 밖에 없고 결국 관리하는 모든 customerId들의 엑세스 라이센스가 바뀌게 됩니다. 이런 일을 방지하기 위해서는 저희 계정이 아닌 광고주 계정으로 직접 로그인해서 발급 받을 수 밖에 없습니다.
