### ISSUE TITLE
report 생성및 다운로드 error 500

### ISSUE THREAD

**Issue by sooheon** [naver/searchad-apidoc#72]
안녕하세요?

최근 master report와 stat report 생성 및 다운로드에 모두 500에러가 뜨는데 (master 생성, stat download), 오늘 온라인 UI에서도 같은 현상을 확인했습니다. 인지되신 사항인지 궁금해서 여쭤봅니다.

감사합니다

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

우선 불편 드려 죗오합니다. 
네 30분전에 인지해서 현재 확인 중입니다. 
문제 해결 되는데로 공지(doc.api.naver.com) 드리겠습니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

복구 완료 되었습니다.(금일 12시 현재)

감사합니다.

**Comment by JaehyunAhn** [comment]
감사합니다 💯

**Comment by sooheon** [comment]
감사합니다!
