### ISSUE TITLE
금일 2월19일자 리포트 생성 확인 요청

### ISSUE THREAD

**Issue by choics** [naver/searchad-apidoc#720]
리포트 API 호출시 {"code":20007,"message":"해당 일자 지표 준비중입니다."} 리턴 되고 있습니다.

언제쯤 리포트 생성될지 확인 부탁드립니다.

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 대용량 다운로드 보고서 담당자입니다. 

데이터 생성 과정에서 문제가 발생하여 지표 생성이 평소보다 지연 되었습니다. 

2월 20일 07시 50분 현재 정상 제공 중인 상황입니다. 

감사합니다.
