### ISSUE TITLE
금일도 지표 준비중 에러..

### ISSUE THREAD

**Issue by choics** [naver/searchad-apidoc#721]
금일도 리포트 API 호출시 {"code":20007,"message":"해당 일자 지표 준비중입니다."} 리턴 되고 있습니다.
2일째 반복되고 있네요

**Comment by bizspring-sangwon** [comment]
저도 똑같은 증상이네요. 어제 고쳐진 것으로 확인했었는데 여전히 해당 일자 지표 준비중으로 뜹니다.

**Comment by SM10855** [comment]
저도 아직까지 동일한 증상입니다.

**Comment by holyachon** [comment]
https://saedu.naver.com/notice/view.naver?notiSeq=4048
공지에 따르면 이슈가 있는 상황으로 보입니다.

**Comment by naver-searchad** [comment]
@choics 님, @bizspring-sangwon 님 @SM10855 님 @holyachon 님 

안녕하십니까 네이버 검색광고 대용량 보고서 담당자입니다. 

우선 이용에 불편을 드려 대단히 죄송합니다. 
어제와 동일한 문제가 오늘도 발생하여 지표 생성 지연 장애가 있었습니다. 
금일 오전 9시 26분 현재 복구 완료 되어 정상 서비스 중입니다. 

감사합니다.
