### ISSUE TITLE
플레이스 유형 문의

### ISSUE THREAD

**Issue by hon9hb-dbase** [naver/searchad-apidoc#722]
@naver-searchad 

안녕하세요.

Master Report - Adgroup - Adgroup Type apidoc 내
`6. NAVER Place Ad` 와 `10. Place Ad` 의 차이점이 무엇인가요?

기존 다른 이슈들을 확인하니 10번은 LOCAL_AD였던 것 같은데,
`Place -> 현 지역소상공인광고 (=6번. Naver Place Ad)`이고, `Local Ad -> 현 플레이스 검색 (=10번. Place Ad)`  인가요?

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 대용량 다운로드 보고서 담당자입니다. 

답변이 늦어 죄송합니다. 

파악하신 것과 같이 6번 타입은 소상공인 광고에서 사용되는 광고 그룹 타입이고, 10번은 플레이스 광고용입니다. 
플레이스 광고가 새롭게 출시 되면서 소상공인 광고의 영문 명칭은 local SMB 로 변경 되었는데요. 
메뉴얼 업데이트 과정에서 누락이 있었습니다. 수정해 두도록 하겠습니다.
혼란 드려 죄송합니다. 

감사합니다.

**Comment by hon9hb-dbase** [comment]
확인 감사합니다.

**Comment by hon9hb-dbase** [comment]
확인 감사합니다.
