### ISSUE TITLE
확장소재 타입 관련 문의 드립니다.

### ISSUE THREAD

**Issue by sinnotda** [naver/searchad-apidoc#724]
안녕하세요

http://naver.github.io/searchad-apidoc/#/operations/GET/~2Fncc~2Fad-extensions~2F%7BadExtensionId%7D에서

확장 소재 타입이
PHONE
LOCATION
BOOKING
TALK
CALCULATION
HEADLINE
DESCRIPTION
SUB_LINKS
PRICE_LINKS
PROMOTION
SHOPPING_EXTRA
POWER_LINK_IMAGE
IMAGE_SUB_LINKS
PLACE
CATALOG_RELEASE_DATE
CATALOG_EXTRA
CATALOG_DETAIL
CATALOG_IMAGE
CATALOG_PROMOTION
CATALOG_EVENT
CATALOG_MOVIE
NAVER_TV_VIDEO
NAVER_BLOG_REVIEW

나와 있는데요 광고센터에서 사용되는 한글명을 알 수 있을까요? 아니면 각각 항목이 무엇인지

정리된 페이지가 있을까요?

감사합니다

**Comment by naver-searchad** [comment]
@sinnotda 안녕하세요? 네이버 검색광고 API입니다. 다음의 링크에서 확장소재 항목과 한글을 확인하실 수 있습니다.

https://github.com/naver/searchad-apidoc/wiki/FAQ#q-%ED%99%95%EC%9E%A5%EC%86%8C%EC%9E%AC-%EC%9C%A0%ED%98%95%EC%9D%80-%EC%96%B4%EB%96%BB%EA%B2%8C-%EB%90%98%EB%82%98%EC%9A%94
