### ISSUE TITLE
대용량 다운로드 보고서 관련해서   현재 문제가 되고있는 부분이 있나요??

### ISSUE THREAD

**Issue by develop-kjy** [naver/searchad-apidoc#725]
Master report관련해서 혹시 문제가 되고 있는 부분이 있나요??

**Comment by naver-searchad** [comment]
@develop-kjy 님 

안녕하십니까 네이버 검색광고 대용량 다운로드 보고서 담당자입니다. 

혹 어떤 현상이 있는지 말씀해 주실수 있으실런지요?

감사합니다.

**Comment by develop-kjy** [comment]
아니요 이게 지금 api를 와서 하는 작업들이 뭘 바꾼게 없는데 어떨떈 진행이 다되고 어떨땐 오류가 뜨고 그래서... 얼마전까진 계속쭉잘되던건데... 엊그젠가 부터 한번씩 aborted같은 오류가 뜨거든요.

**Comment by naver-searchad** [comment]
@develop-kjy 님

안녕하십니까 네이버 검색광고 대용량 다운로드 보고서 담당자입니다.

최근 큰 작업이 있거나 장애 상황이 있었던 적은 없습니다. 
물론 장비 확충작업은 계속 하고 있지만 사용에 영향을 주지 않는 형태로 진행 중이고
최근에 가용량 증가 작업을 더 많이 하거나 더 자주하고 있지는 않습니다. 

하지만 전체 서비스 기준 사용량이 시점에 따라 몰리거나 하면 
에러가 리턴되는 경우가 없는 것은 아니며, 사용량은 지속적으로 증가 중이라 장비 확충 작업도 앞서 말씀 드린 것처럼 상시적으로 진행 하고 있습니다. 
간혹 저희 서비스 가용량을 증가 시키는 속도보다 사용량이 증가하는 속도가 좀더 늘면 
에러가 리턴될 확률이 증가하는데요. 이런 상황으로 보입니다. 
에러가 리턴되면 재시도 하시는 형태로 대응 부탁드립니다. 

마지막으로 사용에 불편 드려 대단히 죄송합니다. 불편 드리지 않도록 좀더 민첩하게 가용량 증가 작업을 진행하겠습니다. 

감사합니다.
