### ISSUE TITLE
exceeded limit of '100' numbers of 'job' 문의

### ISSUE THREAD

**Issue by chans-choi** [naver/searchad-apidoc#726]
안녕하세요. 
다건 커스터머ID로 MasterReport>Business Channel (BusinessChannel)조회하려 합니다.

200개 정도 수행 후 BadRequest 400 발생합니다.
--> {"name":"BadRequest","status":400,"title":"Bad Request","detail":"exceeded limit of '100' numbers of 'job'"}

어떻게 하면 해당 오류가 발생하지 않을까 문의 드리며,
job List 조회 api 있으면 알려주세요.

**Comment by naver-searchad** [comment]
@chans-choi 님
안녕하십니까 네이버 검색광고 대용량 다운로드 보고서 담당자입니다. 

우선 "다건"은 단건의 오타라고 보면 될지요? 다른 의미의 단어라면 말씀 다시 부탁드립니다. 

마스터는 생성 요청-> 보고서 생성-> 다운로드 형태로 구성되어 있는데요. 
마스터가 생성되면 별도로 삭제하지 않으시는한 계속 저희 장비에 보관이 되고 언제든 예전에 생성하신 마스터를 
다시 다운로드 받으실수 있습니다. 즉 생성된 마스터는 저희가 임의로 지우지 않으며 이때 최대 생성 가능한 마스터의 갯수는 마스터 생성 대상 계정 당 100개 입니다. 
따라서 위의 에러메세지가 리턴된다면 이미 다운받으셔서 보관하실 필요가 없는 마스터를 삭제하시고 요청 하시는 형태로
로직을 구성하시는 방법으로 대응이 가능합니다. 

그리고 한가지 주의 하실 점은 마스터는 UI(광고관리 시스템. manage.searchad.naver.com)에서도 생성이 가능한데요. 
API기반의 솔루션이나 서비스 외에 광고주나 대행사 혹은 해당 계정을 관리 하시는 분께서 직접 본인이 보실 마스터를 생성하시는 경우가 있습니다. 이렇게 생성된 마스터 역시 계정당 마스터 제한에 포함되기 떄문에(정확히 말씀드리면 UI에 구현된 기능은 API 서비스 용으로 제공되는 API와 동일한 API를 이용해 UI만 구성된 형태 입니다.) API를 통해 생성 요청된 마스터 갯수보다 더 많은 마스터가 존재할수 있다는 점입니다. 

지금까지 생성된 보고서들의 JOB ID들은 MasterReport: list(레퍼런스 https://naver.github.io/searchad-apidoc/#/operations/GET/~2Fmaster-reports)를 통해 확인 하실수 있으며 이 리스트에서는 UI 혹은 API를 통해서 생성된 건들이 
모두 제공 됩니다. 

감사합니다.

**Comment by chans-choi** [comment]
답변 주셔서 감사합니다.

**Comment by chans-choi** [comment]
마스터보고서 다운로드 후 보고서 삭제 요청하면 [HTTP/1.1 204 No Content] 나옵니다.
단건/다건 동일한 결과 입니다.   
해당 오류 확인 부탁 드리며, 
삭제 시 최대 생성 보고서 수에서 바로 차감되는 알고 싶습니다.

>>수행 로그<<
[단건삭제]
============ Request =============
**DELETE /master-reports/610EE9CD0D5CB2876B80FDF1F991F379** HTTP/1.1
>accept-encoding: gzip
>user-agent: unirest-java/1.3.11
>X-API-KEY: 
>X-Customer: **1017957**
>X-Signature: 
>X-Timestamp: 1677198632992

============ Response ============
**HTTP/1.1 204 No Content**
>date: Fri, 24 Feb 2023 00:30:31 GMT
>content-type: application/json;charset=UTF-8
>cache-control: no-store, must-revalidate
>x-transaction-id: baaff8f8ff81a7ad
>referrer-policy: unsafe-url
>server: nfront

[다건삭제]
============ Request =============
**DELETE /master-reports** HTTP/1.1
>accept-encoding: gzip
>user-agent: unirest-java/1.3.11
>X-API-KEY: 
>X-Customer: **1017957**
>X-Signature: 
>X-Timestamp: 1677199190302

============ Response ============
**HTTP/1.1 204 No Content**
>date: Fri, 24 Feb 2023 00:39:48 GMT
>content-type: application/json;charset=UTF-8
>cache-control: no-store, must-revalidate
>x-transaction-id: 0a55bd16aced8030
>referrer-policy: unsafe-url
>server: nfront

**Comment by naver-searchad** [comment]
@chans-choi 

안녕하십니까 네이버 검색광고 대용량 다운로드 보고서 담당자입니다.

우선 문의 주신 계정들의 경우 모두 정상적으로 마스터들이 삭제되었음을 확인하였으며 금일 10시 10분 현재 존재하는 마스터는 없었습니다.

정상적으로 delete가 수행된 경우 리턴되는 코드는 204를 리턴하고 있습니다. 
delete method 호출 시 성공한 경우, 작업 성공, 단 서버가 제공할 컨텐츠가 메세지가 없음이므로 http 규약에 따라 204번을 리턴하고 있는데요. 관련된 상세 설명이 러퍼런스에 없어서 혼란을 드린 것 같습니다. 죄송합니다. 레퍼런스나 다른 방식으로 관련사항을 표기할수 있도록 하겠습니다. 

 204 즉 성공이 리턴되면 즉시 제한수에 반영 됩니다.  제한에 도달하였는지 수를 카운트 하는 시점은 생성 호출이 들어왔을 시점으로 생성 호출 인입시점 기준 존재하는 마스터 수를 세어보는 방식입니다.

감사합니다.
