### ISSUE TITLE
stat-report 생성 요청을 하였는데 status가 error로 응답이 오는데 원인이 무엇인지 궁금합니다.

### ISSUE THREAD

**Issue by bizspring-sangwon** [naver/searchad-apidoc#727]
안녕하세요.
searchad api를 통하여 stat-report를 신청하였는데 응답 http code는 200으로 오지만 status가 error로 리턴되고 있습니다.
원인이 무엇인지 알 수 있을까요?? 일시적으로 충분히 생기는 상황인지 특이상황인지 궁금합니다.

x-transaction-id: 60b8bf3f8d641211

응답 값 (loginId는 지웠습니다)
{"reportJobId":1766060434,"statDt":"2023-02-26T15:00:00Z","updateTm":"2023-02-26T15:00:00Z","reportTp":"AD","status":"ERROR","downloadUrl":"","regTm":"2023-02-27T22:42:49Z","loginId":"{지움}"}

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

리턴되는 HTTP 코드는 호출 자체에 대한 결과로서 200이 리턴되었다는 것은 정상적으로 저희 장비로 호출이 들어와서 JOB의 등록이 시작되었음을 의미 합니다. 

대용량 보고서는 비동기성 처리로서 호출이 들어오면 들어온 호출에 따라 job을 수행한다는 것은 이미 잘 알고 계실텐데요. 
job의 처리 상황 및 결과는 아래와 같이 STATUS 항목으로 제공 됩니다. 

REGIST : job이 등록됨
RUNNING : 작업중 
BUILT : 보고서 생성 완료
NONE : 생성할 보고서가 없음(대부분 해당 일자에 광고 노출이 없는 등의 이유로 지표 자체가 없음)
ERROR : 보고서 생성 작업에 에러가 발생함. 
WAITING : 작업 대기중 
AGGREGATING  : 지표를 제공하기 위해 소스 데이터를 취합하는 중 (대체로 새벽에 저희 보고서 원본 데이터 생성 작업 때 리턴됩니다.)

이중 ERROR의 경우는 JOB 처리에 실패한 케이스인데요. 대부분의 경우 저희 장비 에러나 타임아웃 등 저희쪽 문제로서 사용자께서 하실수 있는 대응은 재시도를 하시는 것입니다. 대체로 재시도를 하게 되면 성공하게 되는데요. 계속 문제가 지속되면 장애 상황일 수 있으니 공지를 확인해 주시고, 공지가 없다면 신고 부탁드립니다. 

이번 건의 경우도 저희 쪽 장비의 문제 였습니다. 불편 드려 대단히 죄송합니다. 

감사합니다.

**Comment by bizspring-sangwon** [comment]
> 안녕하십니까 대용량 다운로드 보고서 담당자입니다.
> 
> 리턴되는 HTTP 코드는 호출 자체에 대한 결과로서 200이 리턴되었다는 것은 정상적으로 저희 장비로 호출이 들어와서 JOB의 등록이 시작되었음을 의미 합니다.
> 
> 대용량 보고서는 비동기성 처리로서 호출이 들어오면 들어온 호출에 따라 job을 수행한다는 것은 이미 잘 알고 계실텐데요. job의 처리 상황 및 결과는 아래와 같이 STATUS 항목으로 제공 됩니다.
> 
> REGIST : job이 등록됨 RUNNING : 작업중 BUILT : 보고서 생성 완료 NONE : 생성할 보고서가 없음(대부분 해당 일자에 광고 노출이 없는 등의 이유로 지표 자체가 없음) ERROR : 보고서 생성 작업에 에러가 발생함. WAITING : 작업 대기중 AGGREGATING : 지표를 제공하기 위해 소스 데이터를 취합하는 중 (대체로 새벽에 저희 보고서 원본 데이터 생성 작업 때 리턴됩니다.)
> 
> 이중 ERROR의 경우는 JOB 처리에 실패한 케이스인데요. 대부분의 경우 저희 장비 에러나 타임아웃 등 저희쪽 문제로서 사용자께서 하실수 있는 대응은 재시도를 하시는 것입니다. 대체로 재시도를 하게 되면 성공하게 되는데요. 계속 문제가 지속되면 장애 상황일 수 있으니 공지를 확인해 주시고, 공지가 없다면 신고 부탁드립니다.
> 
> 이번 건의 경우도 저희 쪽 장비의 문제 였습니다. 불편 드려 대단히 죄송합니다.
> 
> 감사합니다.

후처리가 필요한 상황인가 했었는데 status 중에 있는 것으로 보아 필요한 것 같네요.
답변 감사드립니다.
