### ISSUE TITLE
에러코드 1026 문의드립니다.

### ISSUE THREAD

**Issue by sinnotda** [naver/searchad-apidoc#728]
안녕하세요

키워드 등록 API 사용중  아래와 같은 데이터를 리턴 받았습니다.
{'code': 1026, 'status': 409, 'title': 'The resource you requested is handling another request. Please try again later.'}

해당 오류는 API 요청 초과에 따른 오류로 보면 되는건가요??

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

1026 오류코드는 리소스의 락을 잡지 못해 발생한 오류이고, 문의하신 키워드 등록 API 호출의 경우 광고그룹에 대해 다른 호출을 처리하고 있을때 발생됩니다.

감사합니다.
