### ISSUE TITLE
daily stats의 api 결과와 네이버 광고시스템내의 데이터 차이 문의

### ISSUE THREAD

**Issue by githubcnsbs** [naver/searchad-apidoc#729]
현재 StatReport로 naver shopping 데이터를 가져오고 있습니다. 
(SHOPPINGKEYWORD_DETAIL,
SHOPPINGKEYWORD_CONVERSION_DETAIL)

위 api로 호출 시 아래 사항 문의 드립니다.
- 날짜가 지나가며 실적 보정이 일어나는 지 문의 (오늘 받은 데이터와 3일 뒤 받은 데이터간 일부 데이터(노출/클릭/전환 실적 등)가 달라질 수 있는지 문의)
- (보정이 일어난다면) 데이터 변경 시 별도로 변경된 데이터만 받아올 수 있는 방법이 있는지 문의
- (보정이 일어난다면) 몇일 전까지의 데이터까지 받아야 더이상 보정이 일어나지 않는다고 생각할 수 있는지 문의

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

장애와 같이 특별한 상황이 아니라면 과거 데이터를 수정 하거나 업데이트 하는 등의 보정 작업은 하지 않습니다.장애인 경우는 공지를 통해 추후 변경 여부를 확인하실수 있습니다. 

일 단위 데이터의 경우 익일 새벽에 확정 데이터로 전달 드리고 있으며 
대용량 보고서와 광고관리내 보고서들은 동일한 raw 데이터를 이용해서 표현 형태만 다르게 가공한 것이므로 상호간 데이터가 같아야 합니다. 
(물론 지표 합산등 데이터를 가공하는 수식이 저희와 다르실수는 있으므로 대용량 보고서를 이용해서 데이터를 직접 가공하셨다면 이점은 유의 하셔야 합니다.지표 처리 식은 모두 공개하고 있으니 필요시 문의 부탁드립니다.)

감사합니다.

**Comment by githubcnsbs** [comment]
네, 감사합니다.

**Comment by githubcnsbs** [comment]
혹시 네이버 광고 시스템에서 정산 등과 관련하여 abuse click 등은 실적 보정을 하지 않나요.

**Comment by naver-searchad** [comment]
안녕하셔요 대용량 다운로드 보고서 담당자입니다. 

정확히 어떤 내용에 대한 질문인지 잘 이해가 되지 않는데요. 특히 정산이라고 표현해 주신 부분이 어떤 내용인지 여러 가지 해석이 있을수 있을것 같습니다. 
제공 되는 보고서는 발견된 무효가 모두 제거된 상태로 제공됩니다. 또한
보고서 제공 이후 무효 클릭 등 환불이 필요한 사항이 추가로 발견 혹은 발생 되는 경우 해당 금액을 대상 계정에 유상 비즈쿠폰 등을 발급하여 환불하나, 보고서 지표를 수정하지는 않습니다. 

감사합니다.

**Comment by githubcnsbs** [comment]
답변 감사드립니다.
하나만 더 확실히하고 싶어서 문의 드립니다.

> 또한 보고서 데이터 생성 이후(즉 하루 이상이 지나 이미 전일 보고서 지표가 생성된 이후) 무효 클릭등 환불이 필요한 사항이 추가로 발견 혹은 발생 되는 경우 해당 금액을 대상 계정에 유상 비즈쿠폰 등을 발급하여 환불하나, 보고서 지표를 수정하지는 않습니다.

이 의미가 2023-06-08일 데이터는 2023-06-09일 오전 7~8시 이전에 보고서 지표가 생성되어 제공되는 것으로 알고 있는데요. 
이때 제공된 보고서는 수정되지 않는다는 의미 일까요 (무효클릭, 전환값 수정 등 없음)

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자 입니다. 

네. 이해 하신바가 맞습니다. 이전 답변 드린 사항이 여러가지로 해석될수도 있는 표현들이 있어 예시를 들어 다시 설명 드리겠습니다. 

2023년 6월 8일에 집행된 광고를 예로 들면 

2023년 6월 8일에 집행된 광고의 보고서 데이터는 일자를 기준으로 크게 두가지로 분류 됩니다. 
1. 2023년 6월 8일 당일 중 최대 3시간이 지연된 형태로 생성되는 당일보고서 데이터
2. 2023년 6월 9일 새벽(말씀주신 늦어도 오전 9시에 생성되는)에 생성되는 전일 보고서 데이터 

1번과 같은 당일 보고서 데이터는 무효 지표나 전환 데이터 지연 인식 등으로 인한 누락이나 지표 미반영등에 영향을 받아 지표가 달라질수 있습니다. 단, 조회 가능 시점은 6월 8일 당일로만 한정되며, 6월9일 새벽에 폐기 됩니다.
2번 데이터의 경우는 확정 데이터로서 생성이 되면 이후 변경 되지 않습니다. 

따라서 6월 8일 중에 일중 보고서를 계속 수집한후 6월 9일 아침에 새롭게 생성된 6월 8일 광고 집행된 보고서 데이터와 비교하면 다를수 있습니다. ( 기준 일자가 같은 1번, 2번 보고서를 비교하면 값이 다를수 있습니다.)

이제 다시 2번 데이터 즉 다음날 확정 생성된 보고서 데이터로만 한정 하여 추가로 전환/무효 지표에 대하여 설명 드리겠습니다.

무효 지표의 경우 6월 9일 새벽에 8일자 데이터가 확정된 이후 새롭게 발견 되더라도 지표를 변경 하지 않습니다. 비즈 쿠폰을 통한 환불만 진행 됩니다. 

전환의 경우는 지표 기준일 = 전환 발생일 이므로 논리적으로 사후에 발견된다는 것은 장애 상황이 됩니다. 예를 들어 6월 8일자 보고서에 존재하는 전환 지표들은 6월 8일에 전환이 발생한 경우입니다. 즉 광고 노출과 클릭은 6월 7일이나 그 이전이어도 상관 없다는 뜻입니다. 만일 8일자에 발생한 전환이 수집되지 않아 보고서에 반영 되지 않았다면 이는 장애 상황으로 장애 공지 및 보고서 수정 공지 게시 후 보고서 정정이 진행됩니다. 

아무래도 저는 내부 구조와 데이터 흐름이 머리속에 있는 상태로 답변을 드리다 보니 누락이나 논리의 비약이 있을수 있다고 생각 됩니다. 이해가 어려우신 부분이 있으시면 다시 말씀 주십시오. 

감사합니다.

**Comment by githubcnsbs** [comment]
친절한 답변 감사합니다.
