### ISSUE TITLE
확장키워드 Stat report (EXPKEYWORD) 에서 "Search Keyword"

### ISSUE THREAD

**Issue by sooheon** [naver/searchad-apidoc#73]
Often the value of the "Search Keyword" column is `"-"`. If this is meant to be the keyword searched by end users which I the *client* did not register, but which EXPKEYWORD has caught, what is the interpretation of a value "-"? Are these cases where EXPKEYWORD did nothing?

한국말로 답변 주셔도 괜찮습니다.

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

EXPKEYWORD 보고서는 확장 매칭(키워드 플러스)이 되어 등록하신 키워드와 노출 키워드가 
다를때 해당 성과만 따로 제공 드리는 보고서입니다. (즉 기존 성과 보고서에 이 지표들은 이미 포함되
어 있습니다.)

그런데 저희가 이 보고서를 생성하는 방식이 노출 키워드와 구매(등록)키워드가 다를 경우로 
조건을 설정해 놓았는데요.  몇몇 검색 네트워크 매체들의 경우 검색어가 존재함에도 저희에게 
- 로 제공해 주시는 케이스가 있어 보고서에 포함되어 제공이 되고 있습니다. 

개선 작업을 진행할 예정으로 해당 지표는 버려 주시면 되겠습니다. 

정리하면 EXPKEYWORD 보고서에서 search_keyword가 "-" 인 경우는 해당 row를 쓰지 않으시면 되
겠습니다. 
불편 드려 죄송하오며 수정이 되면 별도 공지(doc.api.naver.com) 드리겠습니다.

감사합니다.
