### ISSUE TITLE
CUSTOMER_ID를 이용해서 데이터구할때...

### ISSUE THREAD

**Issue by develop-kjy** [naver/searchad-apidoc#730]
그냥 1달치 전체를 보는데 stats를 이용해주려니까 CUSTOMER_ID로만은 구할수없는거죠??

무조건 최소 campaignID 부터가 최소 기준인거죠??

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 보고서 담당자입니다. 

무엇의 1달치를 보신다는 말씀이신지 의문이 있기는 합니디만...STAT을 쓰신다고 하신 말씀으로 미루어 보고서지표를 보고자 하시는 것 같습니다. 

STAT의 경우는 캠페인 아이디 단위가 선택하실수 있는 최대 단위 입니다. 

감사합니다.
