### ISSUE TITLE
해당 일자 지표 준비중입니다. 에러 리포트 지연

### ISSUE THREAD

**Issue by choics** [naver/searchad-apidoc#731]
현재 해당 일자 지표 준비중입니다 에러 발생하고 있습니다

확인 부탁드립니다

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 보고서 담당자입니다. 

데이터 수집 지연이 있어 지표 생성이 지연 되는 문제가 있었습니다. 
대용량 보고서의 제공 가능 예상 시점은 금일 오전 7시 30분~8시 사이로 예상됩니다. 
불편드려 죄송합니다. 

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 보고서 담당자입니다.

STAT 지표에 관한 사항 말씀 드리지 않아 추가로 코멘트 남깁니다.
STAT의 제공 가능 시점은 금일 오전 9시로 예상 하고 있습니다. 

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 보고서 담당자입니다.

STAT 및 STAT-REPORT 모두 08시에 복구 완료 되었습니다. 

감사합니다.
