### ISSUE TITLE
API 요청 로그 및 광고비용 over spend 확인부탁드립니다.

### ISSUE THREAD

**Issue by for2gles** [naver/searchad-apidoc#732]
안녕하세요
customer id: *******
campaign id:  *******
문제기간:  ******* ~  *******

문제 발생 요약
- Daily 예산으로 설정되어있던 캠페인에 [Campaign: update](https://naver.github.io/searchad-apidoc/#/operations/PUT/~2Fncc~2Fcampaigns~2F%7BcampaignId%7D%7B%3Ffields%7D) 를 요청합니다.
  - 요청 내용
  - fields: budget
  - body: {
      dailyBudget: `number`
  }
- `useDailyBudget: true` 를 포함하지 않은탓에 최대 Budget으로 변경된 것 같습니다.

문제 사항
- 문제기간( ******* ~  *******)동안에 기존 설정했던 비용보다 초과되어 캠페인이 진행되었습니다.
- 문제는 아니고 궁금한사항인데, Daily Budget으로 생성된 캠페인에 `useDailyBudget: true`를 포함하지 않고 업데이트를 하면 최대 예산으로 적용되나요?
  - 마케터분들의 말씀을 들어보니 UI에서는 Daily > Maximum 예산으로 변경이 불가한 것 같다고 하시더라구요. 그리고, 위와같이 `useDailyBudget: true`를 포함하지 않고 업데이트를 하면 예산이 0원으로 보인다고 합니다. 이 때, 예산 제한이 풀려버리는건지 최대 예산으로 설정되는지 답변 부탁드립니다.
  - 또한 UI에서 Daily <-> Maximum 예산 설정 변경이 불가능하면, API요청에서도 실수를 막기위해 Bad Request 에러를 던져주실 수 있는지 확인부탁드립니다.(API Docs만을 보고 budget 설정시 어떤 property를 넣어야 하는지 파악이 어렵습니다. Request Body에 어떤 데이터를 입력해야하는지에 대한 정보가 없고 Response만 존재합니다.)

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

캠페인의 하루 예산은 두개의 필드로 구분되어 있습니다. 
* useDailyBudget
* dailyBudget

예산을 적용할때, useDailyBudget = true인 경우에 dailyBudget이 유효합니다. 이 경우에 dailyBudget까지 예산이 소진되면 budget lock이 걸리게 됩니다.
하지만, useDailyBudget = false 일 경우 dailyBudget값은 유효하지 않습니다. 또한 광고 계정에 budget lock이 걸리지 않고 광고주 계정 예산이 허용하는 한도까지 소진이 됩니다.

API를 이용하여 하루 예산을 설정하실 경우 useDailyBudget, dilayBudget 프로퍼티의 값을 꼭 설정하도록 권고하고 있습니다. useDailyBudget이 설정되지 않은 경우 기본값으로 false가 설정이 됩니다.

아래 이슈의 코멘트를 참고하시기 바랍니다.

https://github.com/naver/searchad-apidoc/issues/711#issuecomment-1420442137
https://github.com/naver/searchad-apidoc/issues/28#issuecomment-269734870

감사합니다.

**Comment by for2gles** [comment]
자세한 답변 감사드립니다.
해당 답변으로 모두 이해가 됐습니다.
