### ISSUE TITLE
criterion 모든 요일시간대, 모든성별, 모든지역 변경 방법

### ISSUE THREAD

**Issue by sm11356** [naver/searchad-apidoc#733]
타겟팅 유형별로 타겟팅을 변경할 수 있습니다.
PUT /ncc/criterion/{광고그룹 ID}/{dictionary type}

으로 유형별로 타켓팅 변경이 가능하다고 되어있는데, 
모든 요일시간대, 모든성별, 모든지역 으로 변경하는 방법이 있나요?

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.
모든요일, 모든 성별, 모든지역은 해당 타겟팅을 사용하지 않음으로 설정하면 됩니다.

감사합니다.
