### ISSUE TITLE
criterion API body 질문 확인 부탁드려요.

### ISSUE THREAD

**Issue by sm11356** [naver/searchad-apidoc#734]
* 타겟팅 변경시 Request Body에 포함되지 않는 코드는 모두 사용안함 처리 
-> 타겟팅 유형 : AG(연령대) 인 경우 정상작동 하지 않는것 같습니다. 

질문 1
PUT /ncc/criterion/groupId/AG   API로 요청하면 요청  dictionaryCode에 해당되는 데이터 외에는 노출되지 않는 맞는 것인가요?
예를들어, 기존 광센에 
owner_id : grp-a001-01-000000029105881 
AG0014
AG1418
AG1924
AG2529
AG3034
AG3539
AG4044
AG4549 
가 존재하는 상태에서 

 /ncc/criterion/groupId/AG  에 dictionaryCode : AG3034 , bidweight : 150 로 호출한 경우 기존의 타겟팅은 사라지고 AG3034 만 남아야 된다고 생각되는데 
(* 타겟팅 변경시 Request Body에 포함되지 않는 코드는 모두 사용안함 처리 )
-> 타겟팅 유형 : AG(연령대) 인 경우 정상작동 하지 않는것 같습니다. 

기존 유형이 모두 존재하고, AG3034 의 bidWeight 만 변경됩니다. 

질문 2
PUT /ncc/criterion/groupId/AG  API로 요청시 
기존 설정 타겟팅 결과가 광고대상 : 모든 연령대 인 경우  
 /ncc/criterion/groupId/AG  에 dictionaryCode : AG3034 , bidweight : 150 로 호출한 경우 기존의 모든 연령대는 사라지고 AG3034 만 남아야 된다고 생각되는데 

모든연령대가 변경되 지 않고  5102 에러가 떨어집니다. 
모든 연령대의 경우 수정사항과, 제가 모든 연령대로 세팅하고자 하는 경우 api 호출을 어떻게 해야되는지 궁금합니다.

**Comment by naver-searchad** [comment]
@sm11356 안녕하세요? 네이버 검색광고 API입니다.

성별/연령 타겟팅은 고정된 타겟팅 코드가 존재합니다. (추가되거나 삭제가 되지 않습니다.)
성별/연령 타겟팅의 사용함/사용하지 않음 여부는 해당 타겟팅 코드가 모두 있거나, 모두 없을 경우로 판단합니다.
성별/연령 타겟팅의 수정은 고정된 코드가 있기때문의 코드별 개별 수정이 가능합니다.

모든 연령대 사용은 Request Body에 빈 Array를 입력하시면, 해당 타겟팅을 사용안함(모든 연령대)으로 처리가 됩니다.

감사합니다.
