### ISSUE TITLE
키워드 사유 내용 문의

### ISSUE THREAD

**Issue by sm11356** [naver/searchad-apidoc#735]
안녕하세요. 
(https://naver.github.io/searchad-apidoc/#/tags/AdKeyword) API를 활용하여
 키워드 정보를 가져오는데 

키워드 상태 팝업에 나오는 키워드 사유를 받을 수 있는 방법이 있을까요? 

예시 ) 키워드 상태 안내
* 대상 키워드 : *키워드 
* 사유 : 사이트의 업종 또는 주된 콘텐츠와 관련이 없는 키워드입니다. 
감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

문의하신 키워드 검수 사유에 대한 내용은 API로 제공하고 있지 않습니다.

감사합니다.
