### ISSUE TITLE
쇼핑검색 관련 api문의 드립니다.

### ISSUE THREAD

**Issue by ChoiYoungWoo2197** [naver/searchad-apidoc#736]
캠페인(쇼핑검색)에 매핑되어 있는 소재에 대해서 성과지표를 구할려고 합니다.
이에 대해서 몇가지 질문을 드립니다.

1. StatReport Api를 사용하여 조회가 되는지 문의드립니다. 가능하다면 리포트타입(reportTp)도 같이 확인부탁드립니다.
2. Stat Api를 사용하여 소재ID를 이용해 조회가 되는지 확인부탁드립니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

StatReport API 에서 쇼핑검색광고의 아래 지표를 제공하고 있습니다.
쇼핑검색광고키워드상세보고서 : SHOPPINGKEYWORD_DETAIL
쇼핑검색광고키워드상세전환보고서 : SHOPPINGKEYWORD_CONVERSION_DETAIL

Stat Api 에서는 id 항목 또는 ids 항목에 소재ID 를 사용해서 리포트 조회가 가능합니다.
감사합니다.
