### ISSUE TITLE
[customer-links] You don't have permission to access on this server (resource)

### ISSUE THREAD

**Issue by ksh24865** [naver/searchad-apidoc#737]
안녕하세요 네이버 검색광고의 customer-links API 호출을 시도하던 도중 에러가 발생하여 문의 드립니다.

* customer-links 사용 시 `You don't have permission to access on this server (resource)` 에러가 발생하는 api_key가 존재합니다.

* customer_id, api_key, secret_key를 정상 입력 하였으나 아래와 같은 에러가 발생합니다.
    * response
        * body
            *  ``` {'status': 403, 'title': "You don't have permission to access on this server (resource)."} ```
        * header
            *  ``` {'Expires': 'Thu, 01 Jan 1970 00:00:00 GMT', 'Connection': 'close', 'Cache-Control': 'no-store, must-revalidate', 'X-Transaction-ID': 'C6RQE9K91HH0N', 'Access-Control-Expose-Headers': 'Date', 'Content-Type': 'application/json;charset=UTF-8', 'Date': 'Tue, 14 Mar 2023 05:34:10 GMT', 'Strict-Transport-Security': 'max-age=15768000'} ```
            
* 여러 네이버 검색광고 계정의 api_key를 사용하여 테스트 해본 결과 대부분 customer-links api가 정상 작동 하지만, 일부 api_key의 경우 위와 같은 에러가 발생하고 있습니다.

* 빠른 안내 및 조치 부탁 드립니다. 감사합니다 ! (__)

**Comment by naver-searchad** [comment]
@ksh24865 안녕하세요. 네이버 검색광고 API 담당자입니다.

customer-links API 의 경우는 API-KEY 를 발급받은 본인의 계정만 조회가 가능합니다.

실패하신 API 를 확인해보니 customer id 를 다른 계정으로 넣으셔서 권한이 없어서 403 응답이 리턴된것을 확인했습니다. 
API-KEY 발급받은 동일한 사용자 계정의 customer id 를 사용하시면 됩니다.

유사 이슈 : https://github.com/naver/searchad-apidoc/issues/540

**Comment by ksh24865** [comment]
@naver-searchad 
빠른 답변 정말 감사합니다. 
네이버 검색광고 -> 광고 시스템 -> 도구 -> API 사용 관리 페이지에서 확인되는
CUSTOMER_ID, 엑세스라이선스, 비밀키 세 쌍을 그대로 입력했음에도 불구하고 403 응답이 리턴되었습니다.

첨부된 사진과 함께 다시 한 번 확인 부탁 드립니다.
감사합니다 ! (__)

![nsa2](https://user-images.githubusercontent.com/55729930/224933618-422d2e6a-8b9d-406b-9ad5-d5e348a0c18d.png)

**Comment by naver-searchad** [comment]
@ksh24865 
안녕하세요

<img width="110" alt="image" src="https://user-images.githubusercontent.com/18188635/224939147-88226f3c-9a08-4160-82e1-25f07e10c528.png">

현재 스크린샷에서 오른쪽 위에 아이디 부분의 마지막이 (내계정) 인 상태로 customer id 를 확인하셔야 합니다.

위의 실패하셨던 요청의 실제 customerId 는 64로 시작하는 customer id 였습니다.

참고부탁드리겠습니다.

**Comment by ksh24865** [comment]
@naver-searchad 

안내 감사합니다.

지금 확인해보니 `(광고관리자)`로 되어있네요 ! 

그럼 광고관리자가 해당 API를 사용하고 싶을 경우 
해당 부분이 `(내계정)`으로 되어있는 admin에게 요청하여 customer id를 공유받아 사용하면 되는 건가요 ??

**Comment by naver-searchad** [comment]
@ksh24865 님 안녕하십니까 검색광고 API 담당자입니다. 

약간의 오해 소지가 있어 정책을 우선 설명 드리고 원하시는 정보에 대한 답변을 드리겠습니다. 

우선 광고관리자로 되어 있다는 것은 
로그인 하신 계정이 접속한 대상 계정에 대해 광고관리 권한을 가지고 있다는 것을 의미 합니다.
권한을 가진 계정이 권한을 준 계정의 권한 부여 내역 혹은 권한 수령 내역을 조회하실수 없습니다. 
예를 들어 ksh24865님의 계정이 A 이고  ksh24865님에게 광고관리자 권한을 주신 분의 계정이 B라고 하면. 
B 계정이 ksh24865님외에 권한을 준 내역과 혹은 다른 계정으로 부터 권한을 받은 내역을 ksh24865님께서는 조회하실수 없습니다. 

한편, 말씀주신 admin이 권한을 주신 분(위의 예시에서는 B)라고 한다면....
필요하신 정보는 위의 예시에서 B분 계정의 커스터머 아이디 일것으로 생각 됩니다. 

조회하는 본인의 API키, 비밀키와 본인 커스터머 아이디로 customer-links를 조회 하시면 **나에게 권한을 준** 계정들의 커스터머아이디(clientCustomerId)와 **내가 권한을 준** 계정들의 커스터머 아이디(managerCustomerId)를 모두 확인 하실수 있습니다. 물론 각 계정을 식별하실수 있도록 각 계정의 로그인 아이디도 함께 제공됩니다. 
UI를 참고해 보시면 이해에 도움이 되실것 같네요
customer-links는 광고주 관리 시스템의 내정보 중 권한 설정 화면 (https://searchad.naver.com/membership/myinfo/customer-links)에서도 사용되는 API입니다. (그리고 내정보는 로그인한 본인만 접근이 가능합니다.)
여기를 보시면 내가 권한을 준 계정, 내가 권한을 받은 계정 리스트가 모두 보이는데요. 이런식으로 조회가 된다고 생각해 주시면 되겠습니다. 

감사합니다.

**Comment by naver-searchad** [comment]
@ksh24865 님 안녕하십니까 검색광고 API 담당자입니다.

네 정확하게 말씀하신 내용이 맞습니다.

감사합니다.
