### ISSUE TITLE
report api에서 특정 계정의 호출이 실패하는 사유 문의드립니다.

### ISSUE THREAD

**Issue by ROSETTA-LEE** [naver/searchad-apidoc#739]
CUSTOMER_ID : 278758
호출 : /adnaverapi/master-reports/create_clientid/(계정아이디)/ShoppingProduct/00000000
응답 : reportjobid=7C36F9888A6ADAD18CCEF9110C57EBD5

안녕하세요.
위 계정에 대해 마스터리포트를 호출하였을 때 실제 광고시스템의 데이터와 상이하거나,
0으로 응답하는 현상이 반복되고 있습니다.
같은 방식으로 호출하는 다른 계정은 문제가 없으나 특정 계정에서만 응답 상태가 불규칙적일 수 있다면
그 사유를 알 수 있을지 확인 부탁드립니다. 감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 대용량 보고서 담당자입니다. 

문의에서 말씀주신 잡 아이디로 생성된 리포트는 바로 삭제하셨기 때문에 생성된 파일을 열어볼수 없어 
호출 시 사용하신 동일한 조건으로 파일을 생성해 보았으나 별다른 문제를 찾지 못했습니다. 

생성된 데이타가 광고시스템의 데이터와 상이하다고 말씀 주신 내용에서 어떤점이 상이한 것인지 몇가지 예를 들어 말씀 주시기 바랍니다. 그리고, 0으로 응답한다는 말씀은 호출 생성 요청시 리턴값을 말씀 주신 것인지요?

감사합니다.

**Comment by HYUNSEO-ROSETTA-LEE** [comment]
안녕하세요~ 확인 감사합니다.8FEE069400C412B2DD6DE340E69D5B62

**Comment by naver-searchad** [comment]
안녕하셔요. 네이버 검색광고 대용량 보고서 담당자입니다. 

말씀 주신 두개의 JOB id에 대한 호출 내역을 확인해 봤는데요. 
아래와 같습니다. 
Job ID : 8FEE069400C412B2DD6DE340E69D5B62
2023-03-16 13:15:35,847 POST
2023-03-16 13:16:02,620 DOWNLOAD
2023-03-16 16:48:34,517 GET
2023-03-16 16:48:35,013 DELETE

Job ID : 7A55278CB94177C5C75C012DF3CD687F
2023-03-16 15:39:21,120 POST
2023-03-16 15:39:50,026 DELETE
2023-03-16 15:43:21,928 GET
~
2023-03-16 16:27:26,520 GET

실은 말씀 주신 내용이 좀 이해가 어려운데요. 
보고서 생성 요청 후 생성된 보고서를 각각 시차를 두고 다운로드 받아 보니 한번은 데이터가 있었고, 한번은 데이터가 없더라 라는 상황인지요?

첫번째 건의 경우 다운로드 받으신 다음에 삭제해버리셨기 때문에 두번째 다운로드 하게 되면 아무것도 받을수 없어야 합니다. 그런데 0건이라는 건 파일을 받으셨는데 빈 파일이었다는 말씀이신지요?
두번째 잡 아이디의 경우 저희쪽 로그에 다운로드 받으신 이력 자체가 없습니다. 

대용량 보고서( master  및 stat-report)는 아래와 같은 순서로 이용하셔야 하는데요. 
POST -> GET …(반복: BUILT상태 확인) -> DOWNLOAD -> 필요시 DELETE (계정당 존재 가능한 리포트 수가 100개로 한정되어 있어 다운로드 후에는 delete하시는 것이 바람직합니다.)

한번 생성된 보고서는 저희 장비에 보관되고 delete 하시기 전까지는 계속 같은 파일을 다운받으시게 됩니다. 

가능하시다면 0건의 의미를 좀더 상세히 알려 주실수 있으실까요? 예를 들어 파일을 받았는데 빈 파일이더라 라던가, 파일이 없다고 리턴 되었다던가, 이런식으로요. 

감사합니다.

**Comment by ROSETTA-LEE** [comment]
![KakaoTalk_20230316_172500934](https://user-images.githubusercontent.com/87587045/225569028-0d547f5a-b725-4e7c-9540-2e8ac74360bb.png)
시차를 두고 다운로드 받았을 때 한번은 데이터가 있었고, 최근 한번은 없었던 것이 맞습니다.
그리고 실제 광고시스템에 데이터가 있음에도 api 호출 시 첨부한 사진처럼 'No Content' 로 응답합니다.
네이버에 저장된 보고서도 최근 7일 이전 것은 모두 삭제하고 진행하였습니다.

아래는 실제 호출 테스트한 순서입니다.

1. 호출 api : master report (ShoppingProduct)
2. CustomerID : 278758
3. registTime : 2023-03-16T08:53:29.555Z
4. downloadDate(네이버 응답시간) : 2023-03-16 오후 5:54:17
5. ReportJobID : 2B92F6CD7DB61EDD7CA9B0DDEBEB6BD3

위 조건으로 네이버에서 응답을 받았으며, 다운로드 링크까지 생성되었으나 실제 열어보면 데이터가 0입니다.
반면 네이버 광고시스템에서 ShoppingProduct 소재를 받아보면 539건의 데이터가 있습니다.

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 대용량 보고서 담당자입니다. 

우선 말씀 주신 내용으로 미루어 짐작컨데 비교 대상이 광고시스템의 보고서-> 대용량 다운로드 보고서 인것으로 추측 됩니다. 
해당 메뉴는 지금 호출 하시는 API를 동일하게 이용해서 저희가 클라이언트만 구성한 기능으로 보고서 파일 스토리지 역시 API 서비스와 공유 합니다. (당연한 이야기 지만 같은 API로 같은 스토리지를 쓰고 있기 때문입니다.) 
이 내용은 뒤에서 한번더 언급 되니 참고 부탁드립니다. 

한편 204번 코드는 없는 "파일"을 다운로드 시도할때 리턴되는 코드 입니다. 
즉 데이터가 없다는 것이 아니라 잡아이디에 속한 리포트 파일이 저희 서버에 없다는 의미입니다. 

이전 코멘트에서 로그를 보여 드린 것처럼 파일 생성 후 삭제를 하셨기 때문에 당연히 없는 보고서에 대해 다운로드 시도를 하게 되면 204(컨텐츠 없음)가 리턴되는 것으로 보입니다. 
작성하신 호출 코드상 delete가 다운로드 호출 이전에  call되고 있거나, 혹은 (꽤 자주있는 일입니다만)
코드상 파일 삭제를 하지 않으셨다면 광고시스템에서 수동으로 본인 혹은 광고관리 이상의 권한을 가진 누군가, 혹은 다른 검색광고 api 서비스 기반 솔루션에서 삭제하신게 아닌지 체크를 부탁드립니다. 
앞서 말씀드린 것처럼 API서비스와 광고시스템 메뉴는 동일한 파일 스토리지를 공유하고, API서비스에서 생성된 보고서는 광고시스템에서 확인 및 다운로드 삭제가 가능하고, 반대 상황도 가능합니다. 또한 권한을 가진 다른 유저 혹은 복수로 사용되는 솔루션들이 여러개 있을경우 타인이 만든 보고서를 지워 버리는 경우가 간혹 발생합니다. 

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 대용량 보고서 담당자입니다.

로그 패턴들을 쭉 살펴 봤는데요. 호출 하시는 패턴을 보니 왠지 get을 DOWNLOAD로 생각하고 계신것이 아닐까 하는 생각이 
듭니다. 이걸 오해하시는 경우도 상당히 많아서 혹시나 해서 말씀드려 봅니다. 
아래는 저희가 제공드리고 있는 샘플 코드 들인데요. 참고 부탁드립니다.
https://github.com/naver/searchad-apidoc/blob/master/java-sample/src/main/java/com/naver/searchad/api/sample/MasterReportSample.java
https://github.com/naver/searchad-apidoc/blob/master/php-sample/master_report_sample.php

감사합니다.

**Comment by ROSETTA-LEE** [comment]
회신 주신 내용을 바탕으로 다시 점검한 결과, 호출 관련하여 설정해두었던 이벤트들의 간격 때문에 다운로드 전 job id가 삭제되는 이슈가 있었습니다. 현재 해당 부분을 수정하여 해결하였습니다. 도움주셔서 감사합니다.
