### ISSUE TITLE
COMPANY NAME 에 대한 문의

### ISSUE THREAD

**Issue by freegate22** [naver/searchad-apidoc#741]
API 문서에 보면 MasterReport에서 AccessRights (Account) - 3. COMPANY NAME
이 있는데, 실제로 MasterReport를 조회해보면 결과가 나오지 않습니다.
어떻게 하면 결과를 볼 수 있는지 확인부탁드립니다.
http://naver.github.io/searchad-apidoc/#/tags/MasterReport

**Comment by naver-searchad** [comment]
안녕하세요. 
API요청후 응답으로 받으신 JobId를 알려주시면 확인해보겠습니다.
만약에 보고서를 삭제하셨다면, 새로 생성한 후에 ID를 확인하시고 알려주시기 바랍니다.

**Comment by naver-searchad** [comment]
두 보고서 모두 결과없음 상태입니다. 즉, 요청하신 계정으로 권한을 위임한 광고주 정보가 없다는 의미입니다.

**Comment by freegate22** [comment]
하나는 제 계정입니다. 권한을 어디서 어떻게 위임하나요?

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다. 
네이버 검색광고 광고주센터 (https://searchad.naver.com)에 로그인 하시고, 우측 상단의 "내정보" > "기본정보" > "권한설정" 메뉴에서 가능합니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

기능 사용방식은 아래 도움말을 참고하여 주십시오.
https://saedu.naver.com/help/faq/ncc/view.naver?faqSeq=44
https://saedu.naver.com/help/faq/ncc/view.naver?faqSeq=45

감사합니다.
