### ISSUE TITLE
searchad - stats 동작 확인 및 breakdown 문의

### ISSUE THREAD

**Issue by heartman** [naver/searchad-apidoc#742]
질문 1 : 
    * 금일 2023년 3월 22일 16시 기준 api.naver.com 이 서비스 종료되는 걸로 알고 있습니다.
       그런데 테스트 중 금일 대략 16:20분 경 부터 갑자기 /stats 요청에 응답이 없습니다. (물론 api.searchad.naver.com )
       다른 /keywordstool 요청은 여전히 잘 응답되고 있습니다. 
       확인 요청합니다.

       테스트 코드입니다.

		// $url = "/keywordstool?hintKeywords=" . urlencode("원피스") . "&format=json&showDetail=1";
                // ==> 응답 잘옴

		$url = '/stats?id=grp-a001-01-000000028485783&fields=["impCnt","clkCnt","salesAmt","ctr","cpc","avgRnk","ccnt","pcNxAvgRnk","mblNxAvgRnk","crto","convAmt","ror","cpConv","viewCnt"]&timeRange={"since":"2023-02-01","until":"2023-02-02"}&timeIncrement=1';
		$r = $api->GET($url);
		print_r(json_decode($r, true));
               // ==> 응답 없음

질문 2:

   위의 /stats 요청에 파라미터로 &breakdown=pcMblTp 를 추가하면 오류를 리턴합니다. 
     다른 dayw, regnNo 모두 동일한 오류를 발생시켰습니다.
   * 서비스 사양대로 breakdown을 pcMblTp를 요청했을 때 
      응답에 pc인지 mobile인지 구별자는 어떤 키로 넣어오는지 
      확인하려던 차에 서버 응답이 없네요.
   
     테스트 코드입니다.

		$url = '/stats?id=grp-a001-01-000000028485783&fields=["impCnt","clkCnt","salesAmt","ctr","cpc","avgRnk","ccnt","pcNxAvgRnk","mblNxAvgRnk","crto","convAmt","ror","cpConv","viewCnt"]&timeRange={"since":"2023-02-01","until":"2023-02-02"}&breakdown=pcMblTp&timeIncrement=1';
		$r = $api->GET($url);
		print_r(json_decode($r, true));

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

질문1

GET request는 url encoding을 해서 요청해 주시면 감사하겠습니다.
첨부해 주신 url 을 url encoding하면

/api/stats?id=grp-a001-01-000000028485783&fields=[%22impCnt%22,%22clkCnt%22,%22salesAmt%22,%22ctr%22,%22cpc%22,%22avgRnk%22,%22ccnt%22,%22pcNxAvgRnk%22,%22mblNxAvgRnk%22,%22crto%22,%22convAmt%22,%22ror%22,%22cpConv%22,%22viewCnt%22]&timeRange=%7B%22since%22:%222023-02-01%22,%22until%22:%222023-02-02%22%7D&timeIncrement=1
으로 요청하실 수 있습니다.

질문2

breakdown 의 요청 기간은 일반 요청보다 제한적이며, 기간 요약 지표로 제공합니다.

요청 기간을 아래와 같이 조정해 주시고 
timeIncrement의 값을 allDays 로 설정해 주세요

캠페인 타입 | 제공기간 | 데이터 윈도우
----|----|----
파워링크 | 7 | 7
쇼핑검색 | 7 | 7
파워컨텐츠 | 7 | 7
브랜드검색 | 120 | 90
신제품 | 7 | 7
플레이스 광고 | 120 | 90

**Comment by heartman** [comment]
얘기하신로 전달해 주신 URL과 breakdown도 잘 동작합니다.

다만, url을 통째로 url encoding하면 안되고,
광고API에서 데이터 문자열에 사용하는 " , { , }  요렇게 3개만 url encoding하고, url의 delimiter char는 유지해야 되서

$url = str_replace(["\"", "{", "}"], ["%22", "%7B", "%7D"], $url);

요렇게 처리해 주니 잘 됩니다.

수고하세요~
