### ISSUE TITLE
StatReport downloadUrl 이슈(https://api.naver.com/ 도메인)

### ISSUE THREAD

**Issue by choics** [naver/searchad-apidoc#744]
금일 StatReport API 호출 후 downloadUrl 로 파일을 다운로드 받는 과정에서 도메인이 변경되서 리턴되지 않고 있습니다.

downloadUrl 값이 https://api.naver.com/report-download 로 리턴되고 있어 https://api.naver.com/ 도메인 만료로 인해 정상적인 다운로드가 되지 않고 있습니다.

이슈 확인 부탁드립니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

업무에 불편을 드려 대단히 죄송합니다. 
해당 문제는 금일 오후 12시 40분 경에 수정해 두었습니다.
혹 같은 문제가 계속 되면 다시 코멘트 부탁드립니다. 

감사합니다.
