### ISSUE TITLE
/estimate/average-position-bid/keyword 403 에러

### ISSUE THREAD

**Issue by mosball** [naver/searchad-apidoc#745]
![스크린샷 2023-03-23 오후 9 07 17](https://user-images.githubusercontent.com/35107576/227199073-b8b27647-439a-4bae-a56d-d0eaf30a0190.png)

/estimate/average-position-bid/keyword api 호출시 Invalid Signature 에러가 반환됩니다.
동일한 시그니처 값으로 /keywordstool는 정상 동작합니다. 무엇이 문제일까요?

**Comment by naver-searchad** [comment]
@mosball 안녕하세요. 검색광고 API 담당자입니다.

서명생성시 오류가 있는것 같습니다. 

- 서명생성시 아래와 같은 형식으로 넣어서 생성하셨는지 확인부탁드리겠습니다.
{timestamp}.POST./estimate/average-position-bid/keyword 

감사합니다 :)

**Comment by mosball** [comment]
@naver-searchad 
서명 생성은 말씀해주신 것과 동일하게 하고 있습니다.
이상한 것은 로컬에서 테스트할 때는 정상적으로 동작하는데, 서버(AWS EC2)에 띄워서 테스트를 하면 403 응답이 온다는 것입니다.

**Comment by naver-searchad** [comment]
@naver-searchad 

- 혹시 구 도메인 ( api.naver.com ) 으로 호출중이신지 한번 확인 부탁드리겠습니다. ( api.searchad.naver.com 으로 호출하셔야 합니다 )
- 만약 계속 재현이 되신다면 response header 의 x-transaction-id 값을 알려주시면 감사하겠습니다.

**Comment by mosball** [comment]
@naver-searchad 
도메인은 문제 없는 것으로 확인하였습니다.
```
headers: {
    date: 'Fri, 24 Mar 2023 07:51:51 GMT',
    'transfer-encoding': 'chunked',
    'x-transaction-id': '314b99ef49a36381',
    'referrer-policy': 'unsafe-url',
    server: 'nfront',
    connection: 'close'
  }
```
response header 첨부드립니다.

**Comment by naver-searchad** [comment]
@mosball 

![image](https://user-images.githubusercontent.com/18188635/227459438-ddcbfb52-26e3-46ee-81f5-bd53e58ba5c7.png)

로그를 확인해보니 GET 요청을 주신것으로 보입니다.
signature 생성시에는 POST 로 생성하고, 실제 요청은 GET으로 하신것으로 보이는데요. 확인부탁드리겠습니다.

**Comment by mosball** [comment]
@naver-searchad 
![스크린샷 2023-03-24 오후 5 00 44](https://user-images.githubusercontent.com/35107576/227460073-637262d7-79d2-45c1-b7d7-6bc14addd5a4.png)

요청은 post로 보내고 있습니다.

**Comment by naver-searchad** [comment]
@mosball 

스크린샷을 보니 api.naver.com 로 요청을 보내고 계신것 같습니다.
api.searchad.naver.com 으로 수정을 하면 정상동작하실것 같습니다.

참고로 현재 api.naver.com 으로 요청시 308 Permanent Redirect 응답을 내려주고 있는데요. 아마 사용하시는 http 클라이언트에서 308 처리가 안되어있어서 POST 대신 GET 으로 요청하시는것으로 보입니다.

**Comment by mosball** [comment]
@naver-searchad 
아 맞네요..
동일한 서버에서 호출하는 /keywordstool api는 정상 동작 하여서 도메인을 업데이트 한 것으로 착각했습니다.
감사합니다!
