### ISSUE TITLE
/billing/bizmoney를 호출하면 301 에러가 납니다.

### ISSUE THREAD

**Issue by huhudaddy** [naver/searchad-apidoc#746]
Array
(
    [0] => X-Timestamp: 1679622228
    [1] => X-API-KEY: 0100000000da504b55e47504d6c093991a13b51eb29f9b3a05301d9720edd4279ff0529e70
    [2] => X-Customer: 1015591
    [3] => X-Signature: 1Dalgg8IeogTdiPQvP1gEhwhZgCGho2J3AZPvNJeLfg=
)

안녕하세요, 

bizmoney를 호출하면 며칠전부터 갑자기 301 에러가 납니다.
왜 그런지 알 수 있을까요?
참고로 저희가 광고 계정 3개가 있어서 아래와 같이 php 페이지를 한번 조회할때 동시 조회중이었습니다.

- 잔액조회 * 3
- 어제 사용금액 조회 * 3
- 그제 사용금액 조회 * 3

혹시 초당 사용량을 초과해서 그런건지요.
어떻게 해야 오류를 해결할 수 있을까요?
초당 사용량을 초과하여 차단되었다면 해제 후 2rps 정책에 맞게 수정하려고 합니다.

감사합니다.

**Comment by naver-searchad** [comment]
@huhudaddy 안녕하세요. 검색광고 API 담당자입니다.

22일자로 종료된 api.naver.com 으로 호출하신것으로 보입니다.

공지 내용 : https://github.com/naver/searchad-apidoc, https://naver.github.io/searchad-apidoc/#/notice

호출 도메인을 api.searchad.naver.com 로 변경 부탁드리겠습니다.

감사합니다. :)

**Comment by huhudaddy** [comment]
감사합니다, 바로 되네요. 혹시 이와 관련한 공지를 참조하는 페이지가 있을까요? 이후에도 비슷한 이슈가 생긴다면 해당 페이지를 참조하려고 합니다.

**Comment by huhudaddy** [comment]
등잔밑이 어두웠네요 😇
메인에서 공지 이제야 확인했습니다 ㅎㅎ🤣🤣
