### ISSUE TITLE
Stat-Report 에서 Age/Gender 에 대한 데이터는 받아볼 수 없을까요?

### ISSUE THREAD

**Issue by for2gles** [naver/searchad-apidoc#749]
안녕하세요.
Stat-Report 대용량 보고서에서 연령대/성별 데이터를 확인할 수 없는지, 또 계획은 없는지 문의드립니다.

다차원보고서와같이 7일이 넘는 데이터를 받아보고싶습니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

타게팅별 보고서 지표를 말씀 주시는 것이라면 이미 제공 드리고 있습니다. 
공지에서 아래 내용을 검색하여 주십시오. 
https://naver.github.io/searchad-apidoc/#/notice
[2022-07-21] 타게팅 관리방식 변경에 따른 신규 대용량 보고서 추가 공지(Stat API)

레퍼런스 페이지에는 문서작성 시스템 문제로 업데이트를 못하고 있어 공지나 릴리즈 노트를 통해 신규 보고서를 
말씀드리고 있습니다. 혼란 드려 죄송합니다. 

감사합니다.

**Comment by for2gles** [comment]
감사합니다 덕분에 확인했습니다.
해당 데이터의 **데이터 윈도우**는 어떻게 되나요?

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다.

모든 대용량 보고서 (STAT-REPORT)는 일단위 지표로만 조회가 가능하며 앞서 말씀 드린 신규 타게팅 기능에 따른 보고서 역시 대용량 보고서 중 하나로서 일 단위 지표를 제공 드립니다. 
보고서는 보고서 생성 요청 일자 0시부터 24시 사이에 발생한 지표들로 구성되며 전환 지표 역시 클릭 일시와 무관하게 전환이 발생한 일자의 데이터를 제공 드리고 있습니다. 

감사합니다.

**Comment by for2gles** [comment]
답변 감사드립니다.
대용량 보고서인 STAT-REPORT가 아닌 일반 보고서 STAT 요청시에는 아래 와같은 데이터 윈도우가 있다는 답변을 확인했습니다.

![image](https://user-images.githubusercontent.com/28400932/228411322-77dac6e5-c3ef-46d1-a5ea-31c0d369a776.png)
[github issue](https://github.com/naver/searchad-apidoc/issues/742#issuecomment-1479258380)
여기에서 breakdown에는 연령대/성별 등 타게팅 데이터별 요청을 했을 때 를 말합니다.

여기서 저는 **데이터 윈도우**를 "데이터가 변경될 수 있는 기간" 이라고 간락하게 이해하고있습니다.
대용량보고서는 별도의 데이터 윈도우를 가지고있는지 동일한 데이터 윈도우를 가지고 있는지 확인 부탁드립니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 보고서 담당자입니다. 

이전 답변 주신 STAT 기능 담당자분께 이전 답변의 배경을 확인하느라 답이 좀 늦었습니다.약간의 오해가 있으신듯 한데요. 일단 대용량 보고서 쪽 부터 설명 드리겠습니다. 

대용량 보고서(STAT-REPORT)는 하루 단위의 보고서만 제공 되며 각 보고서 별 데이터 제공 기간은 아래 링크와 같이 보고서 별로 각기 다릅니다. 
https://github.com/naver/searchad-apidoc/wiki/FAQ-stat#q-stat-report-%ED%95%AD%EB%AA%A9%EB%B3%84-%EA%B8%B0%EA%B0%84

사용 방식은 일단위 보고서를 일자별로 생성하셔서 원하시는 형태로 가공해서 사용하시는 것인데요. 예를 들어 어제부터 과거 일주일치 합산 데이터를 원하시면 어제일자 부터 7일 이전까지 총 7개의 보고서를 일자별로 생성하신 후 이를 합산 하시는 식입니다. 

따라서 대용량 보고서에서는 STAT의 "데이터 윈도우"라는 개념이 존재하지 않으며 굳이 말씀드리면 1일 이라고 말씀드릴수 있습니다. 

STAT에서의 데이터 윈도우라는 개념은 STAT API의 특성에 기인하는데요. 
STAT API는 사용자의 설정에 따라 데이터를 가공하여 제공 드리는 기능을 가지고 있습니다. 그렇기 때문에 거의 RAW log데이터를 일단위 합산만하여 제공드리는 STAT-REPORT와는 달리 기간 제약이나 데이터 조회 조건의 제약이 큰 편입니다. 
이러한 가공 옵션 중에 하나가 데이터 윈도우인데요. 이는 데이터를 합산할 단위기간을 의미 합니다. 그리고 표에서 보여주신 데이터 윈도우는 최대 합산 가능 일자의 의미입니다. 즉 데이터 윈도우가 7이라는 것은 조회 대상 일자로 부터 최대 7일까지 데이터를 합산해서 제공 받을수 있다라는 의미 구요. 당연히 3일 단위나 5일 단위, 하루 단위도 가능합니다. 
또한 제공 기간은 최종 데이터 생성일자 (대체로 어제자)부터 과거 몇일까지 데이터가 존재한다는 것이구요. 
이러한 내용들은 API만 보셔서는 이해하시기가 조금 어려우실터인데요. 광고 관리 시스템에서 제공되는 광고 성과 지표들은 모두 STAT API를 이용해 만들어진 것이므로 광고관리 시스템에서 UI를 통해 API를 호출 하는 내역을 개발자 모드 등에 들어가셔서 확인해 보시면 이해하시는데 큰 도움이 됩니다. 
예를 들어 아래 캡쳐의 붉은 네모 부분이 데이터 조회 기간과 윈도우를 안내하는 부분입니다. 
![image](https://user-images.githubusercontent.com/18188635/228443624-605cb77e-48d7-4db7-8275-363f0c5bce63.png)

반면 앞서 설명 드린 것처럼 STAT-REPROT는 값의 가공이나 합산은 사용자가 데이터를 다운로드 받아서 직접 수행 하시는 것을 전제로 대량의 데이터를 최대한의 자유도로 제공할수 있는 형태로 구성되어 있습니다. 그래서 광고 메타 정보(예를 들면 캠페인 이름이나 타게팅의 이름 등)조차 마스터라는 별도의 기능으로 분리해서 제공드립니다. 

추가로 궁금하신 사항이 있으시면 언제든 코멘트 부탁드립니다.

감사합니다.

**Comment by for2gles** [comment]
상세한 답변 감사드립니다.
대용량 보고서는 요청 하는 순간 생성하기 때문에 데이터 윈도우가 없다라고 말씀하시는 부분은 이해했습니다.

다른 부분에 대해 더 여쭤보고싶습니다.
1. 광고 데이터 자체에서 부정클릭를 검증하는 등의 작업은 얼마나의 기간에 걸쳐서 진행되나요?
2. 네이버 검색광고의 최대 **"전환 추적 기간"** 은 어떻게 되나요?

**Comment by naver-searchad** [comment]
안녕하셔요. 대용량 다운로드 보고서 담당자입니다. 

대용량 보고서는 요청 하는 순간 생성하기는 하지만...그렇기 떄문에 데이터 윈도우가 없는 것이 아니라 "1일치의" 데이터만 제공 드리기 형태이기 때문에 데이터 윈도우라는 개념자체가 무의미 하다는 뜻이었습니다. 이 부분 이해가 되지 않으신다면 다시 설명 드리겠습니다. 

추가로 질문 주신 부분 답변 드립니다. 

1. 일단 저희가 처리 하는 것은 부정 클릭이 아니라 무효 클릭입니다. 무효 클릭은  좀더 넓은 개념입니다. 상세사항은 아래 링크를 참고하여 주십시오. 
https://saedu.naver.com/help/ccenter/intro.naver
문의 주신것과 같은 무효 클릭 관련 정보는 악용의 소지가 있어 공개 하지 않습니다. 양해 부탁드립니다. 

2. 네이버 검색광고에서는 클릭으로 부터 전환 발생 시점까지의 기간을 기준으로 크게 두가지로 분류 합니다. 
a. 직접 전환 :광고 클릭 발생으로 부터 30분 이내에 전환이 발생한 경우 
b. 간접 전환 :광고 클릭 발생 이후 30분 이후 부터 사용자가 설정한 전환 추적 시점까지의 전환으로 전환 추적 기간은 7~20일 사이의 기간내에서 사용자가 직접 설정할 수 있습니다.
https://saedu.naver.com/help/faq/ncc/view.naver?faqSeq=127
감사합니다.

**Comment by for2gles** [comment]
자세한 설명 감사드립니다. 모두 이해가 갔습니다.
좋은하루되세요 🙂
