### ISSUE TITLE
master report post(생성) 요청 이후, get(조회) 시 유효하지 않은 응답 관련 문의

### ISSUE THREAD

**Issue by paul-yuk** [naver/searchad-apidoc#750]
안녕하세요.
마스터 리포트 관련 문의가 있습니다.

Adgroup 마스터 리포트 생성 요청을 같은 Customer ID 로 거의 같은 시간에 2개의 생성 및 조회 요청을 수행하였습니다. (꼭 Adgroup 뿐 아니라, 다른 리포트에 대해서 설명드리는 것과 동일 상황인 것으로 생각됩니다.)

2개의 생성 요청에 대한 응답으로, 서로 다른 리포트 ID 를 응답을 주었고 해당 리포트 ID 에 대해 조회 요청을 보내는 동작을 수행하였습니다.
조회 요청에 대해 응답 코드 200 과 요청 리포트 관련 정보를 내려주는게 일반적이지만, 문제 상황에서는 두 요청 모두에게 응답 코드 204 주는 것을 확인하였습니다.
관련하여 (의도하신 동작이 맞는지) 2개 동시에 요청을 보내면 안되는 것인지 문의 드립니다.

관련 Adgroup 마스터 리포트 ID 정보는 아래와 같습니다.
- 311DCE6DF93B30EA2D8B89059E3468B0
- 200552CE1E7D1AA00C1818AAEC8B59D5

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 보고서 담당자입니다. 

JOB ID를 알려 주실수 있으실지요?
JOB ID가 리턴되지 않았다면 리턴된 에러 코드를 알려 주시기를 부탁드립니다.

**Comment by paul-yuk** [comment]
> 안녕하십니까 대용량 보고서 담당자입니다.
> 
> JOB ID를 알려 주실수 있으실지요? JOB ID가 리턴되지 않았다면 리턴된 에러 코드를 알려 주시기를 부탁드립니다.

잘 못 눌러서 comment 를 다 쓰기 전에 이슈가 생성 되었네요, JOB ID 첨부해드렸습니다. 
확인 부탁드립니다, 감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

답변이 늦어져 죄송합니다. 답변을 이미 드린것으로 착오가 있었습니다.
아래와 같이 답변 드립니다. 

`Job= 200552CE1E7D1AA00C1818AAEC8B59D5`의  Timeline을 보면, 생성 후 전체 삭제를 호출했습니다.
이건 삭제 API를 잘못 사용하시는 것으로 보입니다.

Time | Action
--|--
2023-03-29 16:00:54,632 | POST
2023-03-29 16:00:54,985 | DELETE_ALL
2023-03-29 16:00:59,841 | GET
2023-03-29 16:00:59,873 | DELETE_ALL
2023-03-29 16:01:00,391 | DELETE_ALL

DELETE 호출시 jobId 하나를 삭제할 떄는 Body에 job정보를 넣는 것이 아니라, Path Parameter로 요청해야합니다.
`/api/master-reports` 이렇게 요청하면, 전체 삭제이고,
`/api/master-reports/******aa****` 이렇게 호출하면, Job `******aa****`  삭제 입니다.

감사합니다.

**Comment by paul-yuk** [comment]
@na

> 안녕하십니까 대용량 다운로드 보고서 담당자입니다.
> 
> 답변이 늦어져 죄송합니다. 답변을 이미 드린것으로 착각 하고 있었습니다. 아래와 같이 답변 드립니다.
> 
> `Job= 200552CE1E7D1AA00C1818AAEC8B59D5`의 Timeline을 보면, 생성 후 전체 삭제를 호출했습니다. 이건 삭제 API를 잘못 사용하시는 것으로 보입니다.
> 
> Time	Action
> 2023-03-29 16:00:54,632	POST
> 2023-03-29 16:00:54,985	DELETE_ALL
> 2023-03-29 16:00:59,841	GET
> 2023-03-29 16:00:59,873	DELETE_ALL
> 2023-03-29 16:01:00,391	DELETE_ALL
> DELETE 호출시 jobId 하나를 삭제할 떄는 Body에 job정보를 넣는 것이 아니라, Path Parameter로 요청해야합니다. `/api/master-reports` 이렇게 요청하면, 전체 삭제이고, `/api/master-reports/******aa****` 이렇게 호출하면, Job `******aa****` 삭제 입니다.
> 
> 감사합니다.

확인 감사합니다!
