### ISSUE TITLE
혹시 host도메인에 대한 체크방법이 있습니까?

### ISSUE THREAD

**Issue by henlyshin** [naver/searchad-apidoc#751]
안녕하세요 
api.searchad.naver.com 의 상태를 계속 체크하는 로직을 만들어볼까 했는데 
막혀있는것 같습니다.
혹시 허용된 방법이 있는지 궁금합니다.

**Comment by naver-searchad** [comment]
@henlyshin 

안녕하세요. 검색광고 API 담당자입니다.

도메인의 어떤 상태를 어떤 방식으로 체크하려고 하신지 알아야 정확한 답변을 드릴수 있을것 같습니다.

감사합니다. :)

**Comment by henlyshin** [comment]
curl 통해 체크하려 했습니다만 막혀있어서 허용하시는 방법이 있는지 질의드렸습니다~

**Comment by naver-searchad** [comment]
@henlyshin 
과도한 공격성 요청을 보내는것이 아니라면 따로 막혀있지는 않습니다. 

요청을 정상적으로 보내고 계신지 한번 확인 부탁드리겠습니다.

**Comment by henlyshin** [comment]
Curl로 체크하면 에러코드7이 리턴됩니다.
키를 꼭 입력해서 api호출을 해야만할까요?
체크한 도메인은 api.searchad.naver.com 입니다.

2023년 3월 30일 (목) 오전 11:25, naver-searchad ***@***.***>님이 작성:

**Comment by naver-searchad** [comment]
@henlyshin 

curl 사용이 잘못되셨거나, 현재 사용중인 네트워크에서 문제가 있으실수도 있을것 같습니다.

막고있는 부분은 없으니, 코드를 다시 한번 확인해보시거나, 다른 네트워크에서 시도부탁드리겠습니다.
