### ISSUE TITLE
signature is in valid

### ISSUE THREAD

**Issue by rheesungjun** [naver/searchad-apidoc#752]
안녕하세요.
vs-code로 네이버 검색광고 키워드 검색을 사용하고 싶습니다.

signature is in valid 라는 메세지가 나오는데
어디를 고쳐야할까요?

`

const readline = require('readline');
const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});

const crypto = require('crypto');
const request = require('request');
const qs = require('querystring');

const API_KEY = 'XXXXXXXXXXXX';
const SECRET_KEY = 'XXXXXXXXXXX';
const CUSTOMER_ID = '2146812';

// const BASE_URL = 'https://api.naver.com/'
const BASE_URL = 'https://api.searchad.naver.com/'

function getSignature(timestamp, method, uri){
    const hmac = crypto.createHmac('sha256', SECRET_KEY);
    hmac.update(`${timestamp}.${method}.${uri}`);
    return hmac.digest('base64');
}

function getRequestOptions(uri, params = {}){
    const timestamp = Date.now();
    const signature = getSignature(timestamp, 'GET', uri);

    // const CryptoJS = require('crypto-js');
    // const hmac=CryptoJS.algo.HMAC.create(CryptoJS.algo.SHA256, SECRET_KEY);
    // hmac.update(timestamp+'.'+'GET'+'.'+uri);
    // const hash = hmac.finalize();
    // const signature2 = hash.toString(CryptoJS.enc.Base64);

    const options = {
        url : `${BASE_URL}${uri}?${qs.stringify(params)}`,
        headers:{
            'X-Timestamp':timestamp,
            'X-API-KEY':API_KEY,
            'X-Customer':CUSTOMER_ID,
            'X-Signature':signature,
        },
        json:true,
    };
    return options;
}

function getKeywordList(keyword){
    const uri = 'keywordstool';
    const params ={
        hintKeywords:keyword,
        showDetail:1,
    };
    const options = getRequestOptions(uri, params);
    return new Promise((resolve, reject)=>{
        request.get(options, (error, response, body)=>{
            if(error){
                reject(error);
            }else{resolve(body);}
        });
    });
}

function main(){
    rl.question('검색할 키워드 입력:', async (keyword) =>{
        const keywordList = await getKeywordList(keyword);
        console.log(keywordList);
        const data = keywordList.keywordList.map((keyword)=>{
            return {
                '연관키워드': keyword.relKeyword,
                '월간검색수_PC':keyword.monthlyPcQcCnt,
                '월간검색수_모바일':keyword.monthlyMobileQcCnt,
                '월평균클릭수_PC':keyword.monthlyAvePcClkCnt,
                '월평균클릭수_모바일':keyword.monthlyAveMobileClkCnt,
                '월평균클릭률_PC':keyword.monthlyAvePcCtr,
                '월평균클릭률_모바일':keyword.monthlyAveMobileCtr,
                '경쟁정도':keyword.compIdx,
                '월평균노출광고수':keyword.plAvgDepth,
            };
        });
        console.table(data);
        rl.close();
    });
}

main();
`

아래는 에러 메세지입니다.

PS C:\Users\leegram\Documents\html\naverapp> node index.js
검색할 키워드 입력:discord
{
  signature: 'HYN7VpO66XVddcAmIOOjmr0fPLm9+Sx3HDyyWg9xruA=',
  status: 403,
  type: 'urn:naver:api:problem:invalid-signature',
  title: 'Invalid Signature',
  detail: "Signature 'HYN7VpO66XVddcAmIOOjmr0fPLm9+Sx3HDyyWg9xruA=' is invalid."
}
C:\Users\leegram\Documents\html\naverapp\index.js:69
        const data = keywordList.keywordList.map((keyword)=>{
                                             ^

TypeError: Cannot read properties of undefined (reading 'map')
    at C:\Users\leegram\Documents\html\naverapp\index.js:69:46
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.14.2

**Comment by naver-searchad** [comment]
@rheesungjun 안녕하세요. 네이버 검색광고 API 담당자입니다.

BASE_URL의 마지막 / 를 제거하시고, 
signature 생성시의 uri 의 제일 마지막에 / 을 추가하시면 됩니다.

아래와 같이 수정하시면 됩니다.

const BASE_URL = 'https://api.searchad.naver.com'
const uri = '/keywordstool';

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 API 담당자입니다. 

한가지 추가로 말씀 드릴 사항이 있어 코멘트 남깁니다. 
이곳은 전체 공개되어 있으므로 라이선스키와 비밀키를 게시 하시면 안됩니다. 
해당 키의 공개는 내 계정 및 내가 권한을 가진 모든 계정에 대한 보안상의 중대한 위험이 초래 되며, 설사 테스트용으로 사용하시는 계정일지라도 중대한 약관 위반에 해당하므로 사용 중지 조치가 이루어질수 있습니다. 최대한 빠른 시간내에 라이선스키와 비밀키를 다시 발급 받으시기를 당부드립니다. 

문의를 주실때는 리턴된 값에 포함된 트랜잭션 아이디와 호출 일시만 알려주시면 저희가 세부 사항은 모두 확인이 가능하오니 참고 부탁드립니다. 

감사합니다.
