### ISSUE TITLE
쇼핑검색 리포트 문의의 건

### ISSUE THREAD

**Issue by githubcnsbs** [naver/searchad-apidoc#753]
안녕하세요, 최근 쇼핑검색 Report 데이터가 이상하여 문의 드립니다.

쇼핑검색의 hourly report(stat)의 
 - adgroup id: grp-a001-02-000000025841310
 - search keyword: 유심구매
 - ad id: nad-a001-02-000000172563600
 - stat hour: 14
 - device type: M

데이터가 4/2일자에 3/30일의 hourly report를 받아온 데이터는 아래와 같으며,
 - impression: 51
 - click : 3

4/3일자에 3/30일의 hourly report를 받아온 데이터는 아래와 같습니다. (아래 내용이 정상데이터)
 - impression: 17
 - click: 1

위 내용은 한 예이며, 이와 같이 2배 / 3배로 hourly 데이터가 적재되었다가 다시 정상으로 돌아온 계정이 여러개 있었습니다. 

혹시 일시적인 문제였던 것인지, 아니면 이런 현상이 지속되는 것인지, 해당 현상이 발생하면 별도 공지나 api 에서 확인이 가능한 것인지 문의 드립니다.

감사합니다.

**Comment by naver-searchad** [comment]
@githubcnsbs 안녕하세요? 네이버 검색광고 API입니다.
확인 결과, 3/30 데이터는 정상적으로 3/31 새벽에 생성된 이후 변경된 이력이 없습니다.
각 시간대별 지표 전달해주시면 더 자세히 확인해 볼수 있을듯 합니다.

감사하겠습니다.

**Comment by githubcnsbs** [comment]
네, 저희도 다시 적재하였기에 현재 확인 되지 않습니다.
다음에 또 발생하게 되면 다시 문의 드리겠습니다.
