### ISSUE TITLE
소재명 관련해서

### ISSUE THREAD

**Issue by develop-kjy** [naver/searchad-apidoc#754]
https://user-images.githubusercontent.com/118158564/229982244-14fa8832-181c-4d28-920f-9177ea68cdd4.png

이거 쇼핑검색색의 특정 캠페인에 들어가면 나오는건데요

저기서 소재명은  마스터리포트에서 쇼핑상품마스터 로 받아와야하는거 맞죠??

네이버 검색광고 상에서는 특정 명칭으로 보이는데...

마스터리포트에는 생성해서 다운받은 데이터에서 소재ID기반으로 아무리 검색을 해봐도 그런 명칭이 없거든요.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 보고서 담당자입니다. 

주신 이미지 만으로는 저희도 어떤 캠페인 타입의 어떤 광고 형인지 확인이 어렵습니다. 
해당 광고 그룹의 광고 그룹 타입(광고 그룹 마스터를 보시면 확인 하실수 있습니다.)을 알려 주시기를 부탁드립니다. 
마스터는 광고관리시스템(manage.searchad.naver.com) 보고서>대용량 다운로드 보고서 >광고 정보 일괄 다운로드에서도 생성 및 다운로드가 가능합니다. 

감사합니다.

**Comment by develop-kjy** [comment]
아 쇼핑검색그룹타입이 카탈로그형 이런게 있는지 몰랏네요. ㅠㅠㅠㅎㅎㅎ 답변보고 찾아냈어요 감사합니다 :)
