### ISSUE TITLE
네이버 검색광고 AccountInfo 로 가져올 수 있는 유저 정보 

### ISSUE THREAD

**Issue by jaehle06** [naver/searchad-apidoc#755]
GetAccountInfo Operation 을 사용해 유저의 계정 정보를 가져올 수 있는 것 같은데 해당 오퍼레이션을 사용하는 API는 
ManagedCustomerLink에 대한 정보만을 제공해 주고 있습니다.
CustomerLink정보가 아닌, api를 호출하는 customer(본인)의 AccountInfo를 가져올 수 있는 API가 필요한 상황입니다.

가능할까요?

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API 담당자입니다. 

어떤 정보가 필요하신 상황인지요?
권한 현황외의 대부분의 계정 정보 항목들은 API서비스에서는 지원하지 않습니다. 

감사합니다.

**Comment by jaehle06** [comment]
안녕하세요 ! 
cutomer_id 만 받아 올 수 있어서  본인 계정의 명칭 CompanyName을 가져오고 싶어서 문의드렸습니다.

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API 담당자입니다. 

내 계정의 회사명 정보는 써드 파티 업체 혹은 대행사 등이 광고주(고객)에게 어플리케이션을 광고주 클라이언트 설치형으로 제공하거나 광고주가 직접 라이선스 키와 비밀키를 입력하여 사용하는 대여형 솔루션 혹은 외주 혹은 자가 제작인 경우 등에서는 필요할 것으로 예상은 하였습니다. 
그러나 저희 내부 사정이긴 합니다만 여러가지 어려움이 있어 제공 드리지 못하고 있습니다. 양해 부탁드립니다. 

감사합니다.

**Comment by jaehle06** [comment]
답변 감사합니다
