### ISSUE TITLE
마스터 리포트 생성 후, 취득 과정에서 204 에러가 나는 사유가 궁금합니다

### ISSUE THREAD

**Issue by bizspring-sangwon** [naver/searchad-apidoc#756]
안녕하세요.
다름이 아니라 마스터 리포트를 신청 후 jobId를 받았고, 해당 jobId로 마스터 리포트 정보를 조회하니 204 No Content 로 응답이 오는 것을 확인하였습니다.
마스터 리포트 변경 내용이 없다면(fromtime 설정) httpCode 200에 내용이 없는 것으로 오는 걸로 알고 있는데 204로 응답이 떨어지고 있는데요. 혹시 어떠한 상황인지 알 수 있을까요?

API 문제인건지, https://github.com/naver/searchad-apidoc/issues/750 해당 건처럼 삭제 요청이 들어온건지 궁금합니다

문제가 되고 있던 jobId 입니다.

- DA0CCE688B9325799E542115195D6F11
- 8869809AF10A47A3F30D1BE083C63613

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 보고서 담당자입니다. 

우선 답변이 늦어 대단히 죄송합니다. 담당자분께 문의가 전달 되는 과정에서 이전 질문 주신 내용과 동일건 오인식되어 이미 답변을 드린 것으로 착각하고 있었습니다. 

문의 주신 두개 잡 아이디는 모두 다운 받으시기 전에 삭제가 된 케이스인데요. 
상세히 살펴 보니 등록 요청 아이디와 삭제 요청 아이피가 다른 것으로 보아 다른 사용자 혹은 혹은 장비에서 삭제 요청이 이루어진것 같습니다.  
삭제 요청이 발생한 아이피는 49.XXX.XXX.49(정보보호를 위해 가운데 두자리를 XXX로 마스킹 하였습니다.) 입니다. 

감사합니다.

**Comment by bizspring-sangwon** [comment]
> 안녕하십니까 대용량 보고서 담당자입니다.
> 
> 우선 답변이 늦어 대단히 죄송합니다. 담당자분께 문의가 전달 되는 과정에서 이전 질문 주신 내용과 동일건 오인식되어 이미 답변을 드린 것으로 착각하고 있었습니다.
> 
> 문의 주신 두개 잡 아이디는 모두 다운 받으시기 전에 삭제가 된 케이스인데요. 상세히 살펴 보니 등록 요청 아이디와 삭제 요청 아이피가 다른 것으로 보아 다른 사용자 혹은 혹은 장비에서 삭제 요청이 이루어진것 같습니다. 삭제 요청이 발생한 아이피는 49.XXX.XXX.49(정보보호를 위해 가운데 두자리를 XXX로 마스킹 하였습니다.) 입니다.
> 
> 감사합니다.

답변 주셔서 감사합니다.
해당 IP를 알려주실 수는 없으실까요?
불가능하다면 삭제 요청된 시간이라도 알 수 있을까요?

**Comment by naver-searchad** [comment]
@bizspring-sangwon 
안녕하십니까 대용량 보고서 담당자입니다. 

아 죄송합니다. 제가 아이피를 잘못 알려 드렸네요. 아이피는  58.180.XXX.44 입니다. 
단, 이곳은 공개된 곳이라 IP를 모두 공개하는 것은 부적절하리라 생각 됩니다. 그래서 한자리만 마스킹 한 형태로 다시 말씀드립니다.

각 잡 아이디별 삭제 호출 일시(KST) 는 아래와 같습니다. 

# jobId : DA0CCE688B9325799E542115195D6F11
2023-04-06 04:55:37 
# jobId : 8869809AF10A47A3F30D1BE083C63613
2023-04-06 04:39:33 

감사합니다.

**Comment by bizspring-sangwon** [comment]
> @bizspring-sangwon 안녕하십니까 대용량 보고서 담당자입니다.
> 
> 아 죄송합니다. 제가 아이피를 잘못 알려 드렸네요. 아이피는 58.180.XXX.44 입니다. 단, 이곳은 공개된 곳이라 IP를 모두 공개하는 것은 부적절하리라 생각 됩니다. 그래서 한자리만 마스킹 한 형태로 다시 말씀드립니다.
> 
> 각 잡 아이디별 삭제 호출 일시(KST) 는 아래와 같습니다.
> 
> jobId : DA0CCE688B9325799E542115195D6F11 2023-04-06 04:55:37 jobId : 8869809AF10A47A3F30D1BE083C63613 2023-04-06 04:39:33
> 
> 감사합니다.

답변 주셔서 감사합니다.
저희 쪽 시스템 쪽에서 점검해보겠습니다.

감사합니다.
