### ISSUE TITLE
customer-links API 호출을 시도 시 에러발생

### ISSUE THREAD

**Issue by linkprice2** [naver/searchad-apidoc#757]
안녕하세요 네이버 검색광고의 customer-links API 호출을 시도하던 도중 에러가 발생하여 문의 드립니다.

저는 광고관리자(A)이고 광고주(B)에게 권한을 받아 광고를 관리하고 있습니다.
B에게 customer_id, api_key, secret_key를 전달 받아  customer-links API 호출를 시도하였으나,

response body : 
'status': 403, 'title': "You don't have permission to access on this server (resource)." 에러가 발생합니다.
response header :
{'date': 'Thu, 06 Apr 2023 00:52:55 GMT', 'content-type': 'application/json;charset=UTF-8', 'transfer-encoding': 'chunked', 'access-control-expose-headers': 'Date', 'cache-control': 'no-store, must-revalidate', 'expires': 'Thu, 01 Jan 1970 00:00:00 GMT', 'x-transaction-id': '6101f83f40a7d3b5', 'referrer-policy': 'unsafe-url', 'server': 'nfront'}

질문1. 
광고시스템에 B의 계정으로 로그인 하여 
우측 상단 로그인 정보를 표기하는 곳이 **B계정명(내계정)** 으로 표기 된 후  
도구 -> API 메뉴에서 보이는 customer_id, api_key, secret_key 정보를 그대로 사용 하면 되는것이 맞나요?

질문2.
A가 A계정으로 로그인 후 **B계정명(광고관리자)** 인 화면에서 도구 -> API메뉴에서 보이는 customer_id와 
B가 직접 전달해준  customer_id가 동일한데 
두  customer_id가 동일 값 일 수 있나요? (api_key, secret_key는 다릅니다.)

관련하여 안내 바랍니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

아래의 이슈내용을 참고해주시고, 이해가 안되거나 추가 문의가 있으면 코멘트 부탁드립니다.

https://github.com/naver/searchad-apidoc/issues/737

감사합니다.

**Comment by lpsdev1** [comment]
읽어보았으나 저의 경우 광고주B에게 전달받은 customer_id, api_key, secret_key를 사용하였습니다.

**Comment by naver-searchad** [comment]
@lpsdev1 안녕하세요. 검색광고 API 담당자입니다.

첨부해주신 'x-transaction-id': '6101f83f40a7d3b5' 요청으로 확인해보니

요청하실때 사용하신 API_KEY 의 발급받은 광고주와
X-CUSTOMER-ID 의 광고주가 다르게 요청주시는것을 확인했습니다.

API-KEY 발급받은 계정의 customer-id 는 269XXXX
X-CUSTOMER-ID 는 265XXXX 로 요청하셨습니다.

이 부분 확인부탁드리겠습니다.

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 API 담당자입니다. 

추가 설명 드립니다. 

customer_links의 사용 방식은 아래와 같습니다. 

질문하신 분이 A, 관리를 위임하신 광고주 고객분이 B 라고할때....
라이선스 키와 비밀키는 A 계정의 것(A계정으로 로그인 후 발급받은 라이선스키와 비밀키)을 사용하셔서 시그니쳐 생성 후 
A 계정의 customer id 로 customer_links를 호출 하시면 A가 권한을 주거나 받은 계정의 customer_id를 확인하는 형태 입니다.
즉, customer_links는 내가 주거나 받은 권한에 대한 정보만 조회할수 있으며 따라서
customer_links를 호출 할때는 라이선스키, 비밀키, 커스터머 아이디가 모두 동일한 계정의 것을 사용하여야 합니다. 

시도하신 호출처럼 A가 고객인 B의 주거나 받은 권한을 조회하려고 시도했거나 B가 광고 관리자로 권한을 준 A의 주거나 받은 권한을 조회하려고 하면 권한 없음이 리턴이 됩니다. 

이를 극단적인 예를 들어 말씀드리면 귀사의 고객이 귀사 모르게 API를 통해 귀사와 거래하는 고객의 리스트를 조회하려고 했거나 귀사가 고객의 허가와 무관하게 고객이 이용하는 솔루션 업체나 대행사의 리스트를 조회하려고 한 상황으로 이런 상황이 벌어지지 않도록 서비스를 구성하고 있습니다. 

마지막으로 타인에게 api_key, secret_key 그리고 로그인 패스워드를 전달하는 행위는 중대한 약관 위반으로서 계정 및 API 이용이 일시적 혹은 영구적으로 제한될수 있습니다. 또한 타인의 api_key, secret_key 그리고 로그인 패스워드를 이용해 API를 이용 혹은 네이버 검색광고에 로그인 하는 행위는 설사 해당 타인으로부터 허가 혹은 직접 전달을 받았다고 하더라도 민/형사상 책임에서 자유롭지 못할 수 있습니다. 
B분께 최대한 빠른 시간내에 비밀키/라이선스 재발급 및 패스워드 변경을 해주십사 말씀 부탁드립니다. 
또한 혹여 누군가 질문자분에게 라이선스와 비밀키 혹은 로그인 아이디와 패스워드를 전달 하더라도 사용 및 수령을 거부하시는 것이 바람직합니다. 

감사합니다.

**Comment by lpsdev1** [comment]
네. 위 방법으로 시도해보도록 하겠습니다. 기존에 사용하던 키는 재발급 및 변경처리 하도록 하겠습니다. 감사합니다.
