### ISSUE TITLE
Adkeyword 의 nccKeywordId 건

### ISSUE THREAD

**Issue by dongseoklee1541** [naver/searchad-apidoc#758]
안녕하세요.

search ad api를 사용하면서 몇 가지 문의 사항이 있어서 문의드립니다.

[adkeyword](http://naver.github.io/searchad-apidoc/#/tags/AdKeyword)  이 페이지의 api 를 통해서 adkeyword 메타 데이터를 받아오고 있습니다.

1. "editTm" 은 어떤 변화가 있을 때 갱신이 되나요? 
2. 매일 해당 데이터를 overwrite하는 형태로 갱신하고 있습니다. 혹시 같은 keyword 여도 nccKeywordId가 달라지게 되는 경우가 있는지 궁금합니다. 정리하자면 keyword 와 nccKeywordId는 1:1 관계가 아닌가요?

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

1. editTm은 해당 키워드의 변경이 있을 경우에 발생합니다. (입찰가, 사용자 잠금 등등)
2. 키워드를 등록후 삭제를 하지 않으면 nccKeywordId값이 변경이 되지 않습니다. 하지만, 등록된 키워드를 삭제하고, 같은 키워드를 다시 등록할 경우 nccKeywordId는 변경이됩니다.

감사합니다.

**Comment by dongseoklee1541** [comment]
답변 감사합니다!
