### ISSUE TITLE
엑셀 vba에서의 invalid-signature 에러 관련하여.

### ISSUE THREAD

**Issue by masanari555** [naver/searchad-apidoc#759]
vba처음 공부하고 2달 지난 초보입니다.
아직 파이썬 아주 조금 할 줄 압니다만, 업무에서 엑셀을 많이 사용해서 vba만으로 코드 작성하고 있어요.

이번에 검색광고 api로 업무를 해보고자 코드를 작성하였는데,  signature 에러가 발생하여, 혼자 끙끙 앓다 이렇게 글 올려서 문의 드립니다.

Option Explicit

Sub GetKeywordData()
    Dim customer_id As Long, api_key As String, secret_key As String
    customer_id = 내 아이디
    api_key = 내 api 키
    secret_key = 내 비밀키
    
    Dim baseUrl As String, uri As String, method As String
    baseUrl = "https://api.searchad.naver.com"
    uri = "/keywordstool"
    method = "GET"
    
    Dim strTimestamp As String
    Dim timestamp As Double
    Dim currentTime As Date
    currentTime = Now() - TimeSerial(9, 0, 0) ' UTC 시간대 (한국 시간대에서 -9)로 조정
    timestamp = CDbl(DateDiff("s", "01/01/1970 00:00:00", currentTime)) * 1000 + Timer * 1000 Mod 1000 ' 밀리초 단위로 변경 (UTC 기준) 
    strTimestamp = CStr(timestamp)

    Dim signature As String
    signature = GenerateSignature(strTimestamp, method, uri, secret_key)
    
    Dim objHTTP As Object
    Set objHTTP = CreateObject("MSXML2.ServerXMLHTTP.6.0")
    
    Dim encodedHintKeywords As String
    encodedHintKeywords = WorksheetFunction.EncodeURL("조회키워드 입력란")
    
    objHTTP.Open method, baseUrl & uri & "?hintKeywords=" & encodedHintKeywords & "&showDetail=1", False
    objHTTP.setRequestHeader "Content-Type", "application/json; charset=UTF-8"
    objHTTP.setRequestHeader "X-Timestamp", strTimestamp
    objHTTP.setRequestHeader "X-API-KEY", api_key
    objHTTP.setRequestHeader "X-Customer", CStr(customer_id)
    objHTTP.setRequestHeader "X-Signature", signature
    objHTTP.send
    
    ' 상태 코드 및 응답 확인
    Debug.Print "Status: " & objHTTP.Status & " " & objHTTP.statusText
    Debug.Print "Response: " & objHTTP.responseText

    Dim JSON As Object
    
    If objHTTP.Status = 200 Then
        Set JSON = ParseJson(objHTTP.responseText)
    
        Dim keywordList As Object, item As Object, i As Long
        Set keywordList = JSON("keywordList")
    
            i = 0
            For Each item In keywordList
                ThisWorkbook.Sheets("Sheet5").Cells(3 + i, 1).Value = item("relKeyword")
                ThisWorkbook.Sheets("Sheet5").Cells(3 + i, 2).Value = item("monthlyPcQcCnt")
                ThisWorkbook.Sheets("Sheet5").Cells(3 + i, 3).Value = item("monthlyMobileQcCnt")
                i = i + 1
            Next item
    Else
        MsgBox "Error: " & objHTTP.Status & " " & objHTTP.statusText
    End If
End Sub

' 이 밑으로는 signature 관련 함수

Function GenerateSignature(timestamp As String, method As String, uri As String, secret_key As String) As String
    Dim message As String
    message = timestamp & "." & method & "." & uri

    Dim byteSecretKey() As Byte
    byteSecretKey = DecodeBase64(secret_key)
    
    Dim byteMessage() As Byte
    byteMessage = StrConv(message, vbFromUnicode)
    
    Dim hashAlgorithm As Object
    Set hashAlgorithm = CreateObject("System.Security.Cryptography.HMACSHA256")
    hashAlgorithm.key = byteSecretKey
    
    Dim byteHash() As Byte
    byteHash = hashAlgorithm.ComputeHash_2(byteMessage)
    
    GenerateSignature = EncodeBase64(byteHash)
    
End Function

Public Function DecodeBase64(base64String As String) As Byte()
    Dim xml As Object
    Set xml = CreateObject("MSXML2.DOMDocument")
    
    Dim node As Object
    Set node = xml.createElement("b64")
    node.DataType = "bin.base64"
    node.text = base64String
    
    DecodeBase64 = node.nodeTypedValue
End Function

Public Function EncodeBase64(bytes() As Byte) As String
    Dim xml As Object
    Set xml = CreateObject("MSXML2.DOMDocument")
    
    Dim node As Object
    Set node = xml.createElement("b64")
    node.DataType = "bin.base64"
    node.nodeTypedValue = bytes
    
    EncodeBase64 = node.text
End Function

에러코드는 다음과 같습니다.
Response: {"signature":"obEOqFhmjWY8p2f3nkSPnvyG7xhRS990dT1RfJAG14Y=","status":403,"type":"urn:naver:api:problem:invalid-signature","title":"Invalid Signature","detail":"Signature 'obEOqFhmjWY8p2f3nkSPnvyG7xhRS990dT1RfJAG14Y=' is invalid."}

제가 생각하기로는 hashAlgorithm 이부분에서 뭔가 잘못된 키를 생성하는게 아닌가 싶은데.. 도통이유를 모르겠어요.. 도와주세요
그리고 엑셀로 더 쉽고 간결하게 코드 작성할 수 있다면,, 도움을 주셨으면 합니다..
엑셀 vba로 api연결하는 참고 예제를 보지를 못해서 헤매고 있습니다.

**Comment by naver-searchad** [comment]
@masanari555 안녕하세요 검색광고 API 담당자입니다.

코드는 간단히 살펴봤는데요. 말씀주신대로 hashAlgorithm 쪽에 문제가 있어보이고
일단 secretKey 사용시 base64 decode 를 하신뒤 사용하는데요. 
이 부분은 문제가 있을것으로 보이니 확인부탁드리겠습니다.

그리고 죄송하지만 VBA 예제코드는 제공해드리긴 어려울것 같구요.
검색 해보니 유사한 내용이 stackoverflow 에 있으니 참고하시면 좋을것 같습니다.
https://stackoverflow.com/questions/10068548/base64-hmac-sha1-string-in-vba

감사합니다.
