### ISSUE TITLE
Ad Extensions Type id 전체 list 어디서 찾을수 있나요?

### ISSUE THREAD

**Issue by sooheon** [naver/searchad-apidoc#76]
http://naver.github.io/searchad-apidoc/#/tags/MasterReport 에는 다음과 같이 있는데:

- 1: PHONE- 2: Address- 3: "NAVER Booking" Service- 4: "NAVER TALK" service

http://naver.github.io/searchad-apidoc/#/operations/GET/~2Fncc~2Fad-extensions~2F%7BadExtensionId%7D 에는 다음 10개 입니다. 

PHONE
LOCATION
BOOKING
TALK
CALCULATION
HEADLINE
DESCRIPTION
SUB_LINKS
PRICE_LINKS
PROMOTION

근데 Master Report 받아보니 id가 "11"인 경우도 있는데, 이는 어디에 매치 되는가요?

**Comment by sooheon** [comment]
아, 혹시 위 내용이 1~10 순서대로 이고 11이 확장소재 없는 경우인건가요?

**Comment by naver-searchad** [comment]
@sooheon 
안녕하세요.
네이버 검색광고 입니다.

우선 확장 소재 새로운 유형에 대한 release note가 누락되어 있었습니다.
불편함을 끼쳐 드려 죄송합니다.

ad-extension의 type에 대해서는 위에서 언급해주신 리스트를 확인해주시면 됩니다.

최근에 쇼핑검색 캠페인 하위에 생성될 수 있는 확장 소재 유형이 추가 되었습니다.
- type name : `SHOPPING_EXTRA`
- 광고주센터 에서의 한글 이름 : `쇼핑 상품 부가 정보`

이 유형이 master report 에서는 `11`번에 대응됩니다.

오늘 중으로 확장 소재 API document를 업데이트 하도록 하겠습니다.
