### ISSUE TITLE
Conversion Detail Report 의 conversion_type 건 

### ISSUE THREAD

**Issue by Jeongmin25** [naver/searchad-apidoc#760]
안녕하세요.
search ad api를 사용하면서 문의 사항이 있어서 문의드립니다.

Stat-Reports 에서 Conversion Detail Report 등록하여 사용 중입니다.
혹시 conversion_type 이 Others인 경우 어떤 전환인지 별도 구분 가능한 값이 있을까요? 

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드보고서 담당자입니다. 

문의주신 Others인 경우는 해당 전환을 "기타" 유형으로 사용자께서 지정한 경우로서 기타 유형 하위의 별도 분류 코드나 체계는 없어 세부 구분은 할수 없습니다.  아래 전환 스크립트 설치 가이드를 참고하여 주시기 바랍니다. 
https://searchad.naver.com/File/downloadfilen/?type=10&filename=160404_01_installation_guide.pdf

감사합니다.
