### ISSUE TITLE
일일 API 요청 문의

### ISSUE THREAD

**Issue by whoiscrm** [naver/searchad-apidoc#761]
안녕하세요,
네이버 키워드 검색광고를 하면서 자동입찰 시스템을 API 서버를 이용해서 사용하고 있는데

429(호출 한도 초과 오류)
오픈 API를 호출할 때 일 허용량을 초과하였을 경우
일 허용량 초과시 제휴신청을 합니다.

위와 같이 알림이 나오는데 일일 API 요청 트래픽 늘리는 방법이 있을까요?

**Comment by whoiscrm** [comment]
일일 API 트래픽 요청을 늘리는 방법이 있는지 문의드립니다

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API 입니다. 

검색광고 API는 속도 제한만 존재하며 속도는 시스템 전체 가용량에 따라 변경 됩니다. 
일반적인 상황에서 호출 속도 평균값은 대략 초당 15회~30회 정도이며 속도 측정 단위는 API 라이선스키입니다. 단, 대용량 보고서 등 빠른 호출이 불필요하거나 사용자가 아주 많은 기능들은 이보다 느린 속도로 제공됩니다. 
제한 속도를 초과한 속도로 호출 발생시 429번 에러가 리턴되기는 하지만 아래와 같은 문구는 저희가 리턴한 내용이 아닙니다. 

> 오픈 API를 호출할 때 일 허용량을 초과하였을 경우
일 허용량 초과시 제휴신청을 합니다.

429번 오류가 리턴될 경우 sleep을 0.1초 주고 다시 호출 한후 다시 429가 리턴되면 다시 sleep 시간을 조금씩 늘려가는 형태로 로직을 구성하시면 최대 속도에 가깝게 사용하실수 있습니다.

마지막으로 검색광고 API는 모든 사용자게에 동일한 속도를 제공하며 별도의 계약이나 제휴 등은 운영하고 있지 않습니다. 향후에도 이러한 제도는 운영할 계획이 전혀 없습니다. 

감사합니다.
