### ISSUE TITLE
소재 생성 시 패턴 문제

### ISSUE THREAD

**Issue by J-vInyL** [naver/searchad-apidoc#762]
안녕하세요 소재 생성 시 패턴 문제 때문에 문의 드립니다.

https://naver.github.io/searchad-apidoc/#/operations/POST/~2Fncc~2Fads    < 주소 예시 보면서 하는 중 TEXT_45 의  pc.final  과 mobile.final 의 vaild.pattern이 ^(https?):\/\/([^:\\/\\s]+)(:([^\\/]))?((\/[^\\s/\\/]+))?\/?([^#\\s\\?])(\?([^#\\s]))?(#(\w*))?$ 이런 형태로 되어 있어 regex 사이트에서 확인해 보니 url 뒤에 숫자 까지 포함시켜서 확인한 결과입니다.

![화면 캡처 2023-04-19 142707](https://user-images.githubusercontent.com/71584361/232975189-2b32c4d5-d2bd-43aa-8e4b-83d5181b5202.png)

  네이버 검색광고에서도 숫자를 뒤에 붙혀 등록을 할려고 하니 밑에 스크린샷 처럼 나오고있어 등록 진행을 못하였습니다.

![화면 캡처 2023-04-19 141415](https://user-images.githubusercontent.com/71584361/232974926-93be3083-f942-4e9c-b5e5-d0cc75fcceca.png)

혹시나 해서 /ncc/ads create 에서 위의  vaild.pattern을 사용하여 api 통신을 하였는데  이러한 오류가 발생하였습니다.

현재 문서 상 패턴 예시의 문제인지 아니면 api 문제 인지 확인해주시면 감사하겠습니다.

![화면 캡처 2023-04-19 142415](https://user-images.githubusercontent.com/71584361/232974677-8c799fad-4c37-4452-ab9a-3e1410fdc6d5.png)

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다. 예시로 참고하시는 코드의 링크가 정상적으로 연결이 안되어 확인이 어렵습니다.
소재에 등록가능한 링크는 https://en.wikipedia.org/wiki/Domain_name#Internationalized_domain_names 이규칙과  https://domainkeys.sourceforge.net/underscore.html (_) 까지 허용하고 있습니다.

감사합니다.

**Comment by J-vInyL** [comment]
안녕하세요 예시 참고 링크 수정하였습니다. 

https://naver.github.io/searchad-apidoc/#/operations/POST/~2Fncc~2Fads    << 이 부분이고 

response > type > example 버튼을 눌러 TEXT_45 의  Description of the items 의 valid charactors  이 부분 참고 했습니다.

확인해주시면 감사하겠습니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

* 참고한 예제의 패턴은 문서 작성 초기에 포함이 된것으로 보이며, 그 이후로 바뀐 네이버 검색광고 URL 등록 규칙이 반영이 안된것으로 보입니다.
* 문의하신 com1234는 [TLD](https://data.iana.org/TLD/tlds-alpha-by-domain.txt)에 존재하지 않습니다. 
* 검색광고 URL 등록 규칙은 [이전에 코멘트한 ](https://github.com/naver/searchad-apidoc/issues/762#issuecomment-1514416273) 내용을 참고해 주시기 바랍니다.

감사합니다.
