### ISSUE TITLE
광고그룹 대량리포트 다운로드 시 실시간 데이터 여부 문의

### ISSUE THREAD

**Issue by SEUNGHEESEO** [naver/searchad-apidoc#763]
안녕하세요. 
api 를 이용한 광고그룹 생성을 테스트 하고 있습니다.

과정 중
네이버 검색광고 콘솔에서 삭제 후 
바로 광고그룹 대용량 리포트를  
https://api.searchad.naver.com/report-download?authtoken={리포트다운로드URL} 이용하여 다운 받는데요, 

해당 데이터에 내용 중 콘솔에서 방금 삭제한 광고그룹의 삭제 시간이 나오지 않는 것으로 확인하였습니다.
위의 api 사용하여 받은 정보가 실시간으로 반영되고있는 정보인지 문의드립니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

결론만 우선 말씀드리면 실시간 반영 되지 않습니다. 정확히 말씀드리면 실시간 이라는 개념이 크게 의미 없는 형태의 서비스 구조를 가지고 있는 보고서들입니다. 

실은 질문 주신 내용이 전혀 이해가 되지 않아 몇가지 경우의 수로 말씀 드립니다. 

우선 참고로 대용량 보고서 중 STAT-REPORT의 보고서들은 일단위 정보입니다. 따라서 실시간 이 아닙니다. 이 보고서를 문의 주신것은 아닌것 같지만 질문 주신 내용에 정보가 거의 없어서 혹시나 하는 마음에 말씀드려 봅니다.

두번째로 대용량 보고서 중 MASTER-REPORT의 정보는 크게 스냅샷 정보와 변경분 정보로 나뉩니다. 
스냅샵 정보는 호출 시점에 가장 가까운 시점의 스냅샷 데이터를 제공드리는데 기준 시점은 get method 호출 시 리턴드리고 있습니다. 
변경분 정보는 지정하신 특정 시점부터 호출 시점에 가까운 특점 시점 까지의 변경이 발생한 리스트를 제공드립니다. 
변경에는 삭제도 포함되며 역시 스냅샷과 동일하게 호출 시점에 가까운 특정 시점은  get method 호출 시 리턴드리고 있습니다.

광고 그룹 대용량 리포트라고 표현 하신 것으로 짐작 컨데 "광고그룹 마스터"를 다운받으신것 같구요. 
이런 경우 

CASE 1. 광고 그룹 삭제후, 광고그룹 마스터 생성 요청을 하신 후 리턴된 다운로드 URL을 가지고 광고그룹 마스터를 받으셨다면 해당 보고서의 기준 시점이 삭제 이력에 표기된 시점 이후가 아니라면 그대로 제공 됩니다. 
CASE2. 광고 그룹 삭제후 광고 그룹 마스터를 생성 요청을 하지 않으시고 이전에 생성 요청한 광고 그룹 마스터의 다운로드 URL을 이용해서 다운받으셨다면 이전 시점에 생성된 것이므로 당연히 해당 그룹은 존재합니다. 

마지막으로 삭제된 항목은 변경분을 요청 하신것이 아니라면 마스터에 포함되지 않고 변경분에만 포함됩니다. 즉, 변경분 마스터가 아닌 마스터들은 삭제 일시 필드가 존재하지만 그곳에 값이 있을수 없습니다. 만일 삭제된 항목이 변경분이 아닌데 포함되어 있다면 위에서 말씀드린 두가지 케이스를 확인해 보시기 바랍니다. 

감사합니다.
