### ISSUE TITLE
쇼핑검색광고 제외키워드 관련

### ISSUE THREAD

**Issue by jungjinok** [naver/searchad-apidoc#765]
안녕하세요

쇼핑검색광고에서 '소재' 별로 각각 제외키워드를 등록하고 싶습니다.
관련하여 API 가 있을지 확인 부탁드립니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.
아래 링크의 내용을 참고하세요.
https://github.com/naver/searchad-apidoc/wiki/FAQ#q-쇼핑-검색의-노출제외-키워드와-검색어-없는-경우-노출-제외-기능은-어떻게-등록하나요

감사합니다.
