### ISSUE TITLE
다차원 보고서 질문드립니다

### ISSUE THREAD

**Issue by dkdkleelee** [naver/searchad-apidoc#767]
네이버 광고 다차원 보고서 API 가 지원하지않아 어려움을 격고있습니다.
![image](https://user-images.githubusercontent.com/108910154/234320706-92f743c5-91b3-4f74-902a-2658cc3c5ac6.png)
![image](https://user-images.githubusercontent.com/108910154/234320754-030bfe25-76cc-42b1-a718-9b38d79a55e6.png)
![image](https://user-images.githubusercontent.com/108910154/234320807-385c884a-ca8d-442e-850f-3fa3c7e21b5d.png)

스샷이미지 처럼 데이터를 가지고 와야하는데
cpc cpr 등의 데이터는 잘 가지고와지는거같습니다만 
쇼핑검색_매체이름이나 파워링크_키워도 파워링크_광고그룹 등등에 데이터를 가지고 오려면

MASTER계정 아래 100여개의 광고주들 계정이 있는데
각고객마다 캠페인 + 광고그룹 + 소재 + (키워드?) 검색해서 데이터 가지고 와야하나요???
엑셀처럼 데이터 만들고 싶습니다. 
도움 부탁드립니다.

**Comment by dkdkleelee** [comment]
+ 그렇게 되면 호출량이 많아질거같은데 네이버 광고API 하루 호출 제한도 있는지 추가문의드립니다.

**Comment by naver-searchad** [comment]
안녕하십니까.  대용량 다운로드 보고서 담당자입니다. 

API 서비스에서는 두가지 종류의 보고서가 제공 됩니다. 
STAT : 광고관리 사이트 내 각 광고 구성요소(캠페인, 광고 그룹등)리스트에서 제공되는 지표를 그대로 제공하는 보고서 
STAT-REPORT : 1일 단위로 계정에서 발생한 모든 광고 성과를 최하 엔티티 단위로 제공하는 보고서 

STAT의 경우는 단순 호출 만으로 가공된 최종 데이터를 수령할수 있어 가볍게 저희 UI 에서 제공되는 수준의 지표를 사용해야 할때 사용하실수 있는 기능입니다. 물론 자유도는 거의 없다고 보시면 되구요. 저희가 제공드리는 형태와 가공 수준으로만 사용하실수 있습니다. 
반면 STAT-REPORT는 거의 RAW 로그에 가까운 수준으로 최대한 가공되지 않게 원본 지표를 제공드리는 형태로 구성되어 있습니다. 당연히 크기도 크기때문에 비동기성 다운로드 파일 형태로 제공드리며 1회 보고서 생성시 1일치 데이터를 제공드리빈다. 예를 들어 과거 4주치라면 28회 보고서 생성 호출을 주시고 생성된 보고서를 각각 다운로드 받으셔서 자체 스토리지등에 업로드후 가공하여 사용하시면 되겠습니다. 
참고 레퍼런스 : https://naver.github.io/searchad-apidoc/#/tags/StatReport
다차원 보고서 역시 같은 데이터소스를 활용해서 만들고 있고 다차원 보고서에서 제공 되는 대부분의 지표는 대용량 보고서를 이용해 구성할수 있습니다.  
(다차원 지표들의 데이터 가공 수식은 모두 공개하고 있사오니 궁금하신점은 질문 주십시오, )
참고로 현재 지원이 되지않는 항목은 전환 지표 중 "방문당 평균 페이지뷰"와 "방문당 평균 체류시간" 이며 이 지표는 구조적인 문제로 현재 API서비스로는 지원을 못하고 있으며. 향후 전용 API를 별도로 구성하여 제공 드리는 방향으로 준비 중입니다. 

다시 대용량 보고서로 돌아와서 대용량 보고서(STAT-REPORT)는 최대한 상세한 수준의 많은 데이터를 빠르게 제공드리기 위해 광고 메타 정보 (캠페인 명이나 매체명등)는 아잉디와 코드로만 제공됩니다. 일종의 1차 정규화 정도를 한 수준이라고 보시면 되구요. 각 메타 정보를 얻기 위해서는 MASTER-REPORT를 이용해 광고 정보를 다운받으셔서 각 항목의 ID를 기준으로 join 하시면 되겠습니다. 과거 광고 성과 지표는 발생했으나 이미 삭제된 항목의 경우 MASTER의 변경분 서비스(from DT 입력시 특정 시점 부터 현재 기준시점까지의 삭제등 변경이 있었던 항목만 제공드리는 서비스)를 통해 정보를 확인하실수 있습니다. 
데이터의 구조 및 조인 방식은 아래 도움말의 2번 항목 참고 부탁드립니다. 한글 사양서도 아래 도움말에서 링크를 찾으실수 있습니다. 
https://saedu.naver.com/help/faq/ncc/view.naver?faqSeq=178
보고서 파일 생성 요청 및 다운로드는 아래 링크의 각 언어별 샘플 코드에서 확인 가능합니다.
https://github.com/naver/searchad-apidoc

추가로 한가지 팁을 더 드리면 대용량 보고서는 광고관리 시스템에서도 생성 및 다운로드 UI도 제공하고 있으므로 API 개발전에 미리 보고서 파일을 다운 받으셔서 설계에 참고하실수 있습니다. 

마지막으로 문의주신 사용량 제한은 속도 제한만이 존재하며 속도는 검색광고 시스템 전체의 서비스 가용량에 따라 유동적으로 변경 됩니다. 또한 서비스별로 약간씩 속도 차이가 있고 구조적으로 빠르게 호출할 필요가 없는 MASTER REPORT나 STAT REPORT의 경우는 아주 느린 속도로 제공됩니다. 
최근 관측된 최소 속도는 초당 15회 정도, 최고 속도는 초당 28회 정도이며, 호출 중 Too manay Request 에러가 리턴되면  sleep을 0.5초에서 1초 정도 주셨다가 호출 하시는 형태로 로직을 구성하시면 유동적인 속도변화에 대응이 가능하실것으로 생각 됩니다. 

감사합니다.

**Comment by dkdkleelee** [comment]
impCnt
clkCnt
salesAmt
ctr
cpc
avgRnk
ccnt
recentAvgRnk
recentAvgCpc
pcNxAvgRnk
mblNxAvgRnk
crto
convAmt
ror
cpConv
viewCnt

MASTER 나 STAT-REPORT나 tsv 다운로드하거나 
STAT 호출해도 
impCnt,clkCnt,salesAmt,ctr,cpc,avgRnk,ccnt,recentAvgRnk,recentAvgCpc,pcNxAvgRnk,mblNxAvgRnk,crto,convAmt,ror,cpConv,viewCnt 위 데이터 들은 잘가지고 오는데 

다차원 보고서 핵심이 
![image](https://user-images.githubusercontent.com/108910154/234506053-7bf78691-81b4-4b3d-a961-891e134fd450.png)


여기서 원하는 데이터 클릭해서 가지고오는건데 
제가 원하는건  파워링크에서 **키워드** 검색하여 (ex : 서울 강남 정형외과 검색) 같은 값을 가지고 오고싶습니다. 

![image](https://user-images.githubusercontent.com/108910154/234506330-d7730f53-bc1f-4a82-a8c8-2c2e3e5ae3be.png)


이 데이터들이요~! 이건 어느 API에서 값을 가지고 있을까요:?

**Comment by dkdkleelee** [comment]
확인해보겠습니다. 답변 진심으로 감사드립니다.
