### ISSUE TITLE
/ncc/campaigns 일별 금액 추출

### ISSUE THREAD

**Issue by t-dana** [naver/searchad-apidoc#768]
/ncc/campaigns 에서 campaingn ID로 검색해서 일별 결과를 보고 싶은데 가능할까요?
변수값에 일자를 넣는게 없어서 문의드립니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

캠페인의 일별 광고지표 확인을 원하시면 아래의 API를 사용하실 수 있습니다.

https://naver.github.io/searchad-apidoc/#/operations/GET/~2Fstats%7B%3Fid,fields,timeRange,datePreset,timeIncrement,breakdown%7D


감사합니다.
