### ISSUE TITLE
/keywordstool api 관련 문의

### ISSUE THREAD

**Issue by rndmania** [naver/searchad-apidoc#77]
http://naver.github.io/searchad-apidoc/#/operations/GET/~2Fkeywordstool

문서에 보면 event에 대한 id 값은 제공을 해주고 있는데
biztpId 값에 대한 설명은 없는것 같습니다.

biztpId 값에 대해서도 문서로 제공 부탁드리겠습니다.

**Comment by naver-searchad** [comment]
안녕하십니가 검색광고 API입니다. 

답변이 늦어 죄송합니다. 

MASTER 리포트의 BusinessCode (Biz) 항목에서 확인하실 수 있습니다. 
해당 코드는 한국어로는 업종 코드입니다. 

감사합니다.

**Comment by rndmania** [comment]
API로 값 확인했습니다.
감사합니다.
