### ISSUE TITLE
브랜드 검색 문의드립니다.

### ISSUE THREAD

**Issue by for2gles** [naver/searchad-apidoc#770]
안녕하세요.
`/ncc/ads` api를 활용하여 "브랜드 검색"의 데이터를 불러오는데, ad 객체에 `dittoId`, `thumbnail` 두개의 항목밖에 없습니다.
해당 소재의 각각 항목들에 입력되어있는 "링크"들이 필요합니다.
데이터 추가 혹은 확인할 수 있는 방법이 있는지 가능한지 문의드립니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

브랜드검색/신제품검색은 검색광고 API를 이용하여 데이터를 조회할 수 없습니다.

감사합니다.

**Comment by for2gles** [comment]
앞으로도 데이터를 API를 통해 제공해주실 계획은 없을까요?
현재 마스터레포트, `/ncc/ads` API 그 어느곳에서도 데이터를 확인할 수 없는것으로 알고있습니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

브랜드검색/신제품 검색의 경우 이미지와 링크가 많고, 별도의 소재 Editor를 제공해야 하는 문제가 있어 API보다는 네이버 검색광고 광고주센터를 이용하도록 권고하고 있습니다. 또한 브랜드 검색/신제품 검색의 경우 광고 집행을 위한 계약이 존재하고, 계약 기간이 있어 API 이용의 필요성이 상대적으로 떨어집니다.

유감스럽지만, 아직까지는 API를 이용하여 제공할 계획을 가지고 있지 않습니다.

감사합니다.
