### ISSUE TITLE
이 오류가 자꾸뜨는데...

### ISSUE THREAD

**Issue by develop-kjy** [naver/searchad-apidoc#771]
detail: 'A failure of processing the request message due to the internal execution error of the NAVER Search Ads system'

시스템상에 문제가 현재 있는건가요??

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 API 담당자입니다. 

기본적인 저희 서비스 헬스 체크에서 특별한 문제를 발견하지는 못했습니다. 
적어주신 러 메세지는 저희 검색광고API의 에러 메세지가 아니고 
사용하시는 혹은 구성하신 어플리케이션에서 저희가 리턴하는 메세지를 별도로 처리하신 것으로 보이는데요. 
저 메세지만으로는 상황 파악이 어렵습니다. 
에러가 발생한 호출의 호출 시점과 트랜잭션 아이디를 알려 주시면 상세히 확인해 보도록 하겠습니다. 

주의 : **라이선스키와 비밀키 및 커스터머 아이디를 이곳에 절대 남기지 마십시오"**
저희는 호출 일시와 트랜잭션 아이디만으로 상황 확인이 가능합니다. 

감사합니다.
