### ISSUE TITLE
stat-reports 4월9일 이전 보고서 데이터 생성 문의

### ISSUE THREAD

**Issue by nitmus-lab-jack** [naver/searchad-apidoc#772]
안녕하세요.

stat-reports API 를 사용하여 보고서 데이터 연동 작업을 진행중인데요

5월9일 ~ 4월9일 까지는 광고효과 보고서 생성이 정상적으로 되어 연동을 완료했는데요
4월9일 이전 보고서는 생성 요청을해도 아래와 같이 보고서 데이터를 찾을 수 없다고 응답되고 있습니다.

{'code': 20011, 'message': '보고서를 찾을 수 없습니다.'}
report_job_id : 1837616049

정책상 최근 365일 데이터를 가져올 수 있는걸로 알고 있는데요 혹시 정책이 바뀐 건지 문의 드립니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

우선 정책은 변경된 사항이 없습니다. 
문의 주신 잡 아이디를 비롯하여 해당 계정에 대한 4월 9일 이전 일자에 대한 보고서 생성 정상적으로 이루어졌고 파일도 정상으로 보이는데요. 20011 코드가 리턴된 호출의 트랜젝션 아이디와 호출 일시를 알려주실수 있으실지요?

감사합니다.
