### ISSUE TITLE
stats 함수 문의드립니다

### ISSUE THREAD

**Issue by t-dana** [naver/searchad-apidoc#773]
exports.handler = async(event) => {
  const uri = '/stats';
  const method = 'GET';
  const targetAdgroup = {
    nccCampaignId: 'nccCampaignId',
    nccAdgroupId: 'nccAdgroupId',
  };

 // const statIds = [targetAdgroup.nccCampaignId, targetAdgroup.nccAdgroupId];
  // const params = {
  //   id: statIds,
  //   fields: ["clkCnt","impCnt","salesAmt", "ctr", "cpc", "avgRnk", "ccnt"],
  //   timeRange: {"since":"2023-04-01","until":"2023-04-20"},
  // };
  const params =  {
    id : "nccCampaignId",
    fieldds: '["impCnt", "clkCnt"]',
    datePreset: "last7days"
  }
  const headers = getHeader(method, uri);
  const response = await axios.get(BASE_URL + uri, { params, headers });

  console.log(`response status_code = ${response.status}`);
  console.log(`response body = ${JSON.stringify(response.data)}`);
}

js로 짰는데 header 부분은 다른 api로 잘 되는거 확인했는데 stats에서 params부분이 문제인거같은데 아무리 해도 모르겠네요ㅜㅜ
주석된 부분과 주석아닌부분 둘 다 해봤는데,,, 모루겠습니다ㅜㅜㅜ 400에러만 계속나네요,,

**Comment by t-dana** [comment]
js로 된 sample code도 있으면 좋을 것 같습니다~!

**Comment by naver-searchad** [comment]
@t-dana 안녕하세요. 검색광고 API 담당자입니다.

1. params 의 fields 값이 fieldds 로 오타가 있는것으로 보입니다.
2. 주석처리된 코드에서는 아마 timeRange 값이 urlencoding 처리가 안되셔서 발생하신것으로 보이는데요. 그 부분 한번 확인해보시면 좋을것 같습니다.

추가로 문의주실때, 응답헤더의 x-transaction-id 값을 같이 적어주시면 더 정확한 확인이 가능하니 참고부탁드리고,
js 로 된 sample은 제공해드리기 어려울것 같습니다. 죄송합니다.

감사합니다.

**Comment by t-dana** [comment]
잘되네요!! 감사합니다~! 혹시 stats에서 campain type으로 검색도 가능할까요?
