### ISSUE TITLE
캠페인 유형 문의드립니다.

### ISSUE THREAD

**Issue by t-dana** [naver/searchad-apidoc#774]
docs에는 WEB_SITE, SHOPPING 이렇게 두개가 나와있는데 
캠페인 유형 중 파워링크, 쇼핑검색, 파워컨텐츠, 브랜드검색/신제품검색 이 4개의 코드를 알고싶습니다.

그리고 혹시 캠페인 타입별 일일 노출수, 클릭수 등을 알 수 있는 api가 있는지 문의드립니다

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

아래 링크의 내용을 참고하시기 바랍니다.
https://github.com/naver/searchad-apidoc/wiki/FAQ#q-캠페인-유형별-등록가능한-그룹-유형은-어떻게-되나요

캠페인 유형별 지표는 따로 제공하고 있지 않습니다. 개별 캠페인의 지표를 조회하신후, 캠페인 유형별 데이터를 Client에서 생성하셔야 합니다.

감사합니다.
