### ISSUE TITLE
stats 함수 params에 timeRange 문의드립니다.

### ISSUE THREAD

**Issue by t-dana** [naver/searchad-apidoc#775]
const params =  {
        id : v.nccCampaignId,
        fields: '["impCnt","clkCnt","salesAmt", "ccnt"]',
        // datePreset: "last7days",
        // timeRange: '%7B%22since%22%3A%222023-05-04%22%2C%22until%22%3A%222023-05-11%22%7D',
        timeRange: encodeURIComponent('{"since": "2023-05-04", "until": "2023-05-10"}')
      };

stats 함수 이용시에 timeRange를 사용하려고 했는데 URI인코드를 해서 보내라고 하셔서 그렇게 했는데 안되는 것 같아서 문의드립니다 ㅜㅜ
직접해서 보내도 안되네요,,

400 에러납니다

Response
{
  "errorType": "AxiosError",
  "errorMessage": "Request failed with status code 400",
  "trace": [
    "AxiosError: Request failed with status code 400",
    "    at settle (/var/task/node_modules/axios/dist/node/axios.cjs:1909:12)",
    "    at IncomingMessage.handleStreamEnd (/var/task/node_modules/axios/dist/node/axios.cjs:2989:11)",
    "    at IncomingMessage.emit (node:events:525:35)",
    "    at endReadableNT (node:internal/streams/readable:1359:12)",
    "    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)"
  ]
}

**Comment by naver-searchad** [comment]
@t-dana 안녕하세요. 검색광고 API 담당자입니다.

답변이 늦어서 죄송합니다.

아마 timeRange 의 encoding 이 잘못된것으로 추측되는데요. 정확한 내용은 요청주신 내용을 확인해봐야 할것 같습니다.

응답헤더의 x-transaction-id 값을 알려주시면 정확하게 확인이 가능하니 참고부탁드리겠습니다.
