### ISSUE TITLE
확장소재 create 시 userLock 을 paused 미반영

### ISSUE THREAD

**Issue by yuhee62wang** [naver/searchad-apidoc#776]
안녕하세요 ! 

http://naver.github.io/searchad-apidoc/#/operations/POST/~2Fncc~2Fads

확장소재 create 시 userLock 을 paused 로 설정하여 요청했는데요,
실제로 확인해보면 paused 로 반영되지 않고 enabled로 되어있습니다.
오류인지요? 
아니면 userlock이 문서상에는 있지만 사용 불가한 것인지요? 
생성 후 업데이트를 해야하는 건지요?

바쁘실테지만 확인 부탁드립니다 ~~

감사합니다 !

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

확장소재 신규 생성시 userLock 프로퍼티 값은 enabled(광고주 직접 설정 불가) 입니다.

userLock을 변경하기 위해서는 신규 생성후 update API를 호출 하셔야 합니다.
http://naver.github.io/searchad-apidoc/#/operations/PUT/~2Fncc~2Fads~2F%7BadId%7D%7B%3Ffields%7D

감사합니다.
