### ISSUE TITLE
플레이스 광고 노출중인 키워드

### ISSUE THREAD

**Issue by jxamen** [naver/searchad-apidoc#780]
안녕하세요.
광고 그룹에서 제외 키워드 추가 버튼을 클릭하면 현재 노출중인 키워드가 보이는데 이건 api로 어떻게 가져올 수 있나요?
이걸로는 데이터가 넘어오질 않습니다.
코드는 정상 작동하며 아래에는 일부만 적었습니다.

$nccAdgroupId = "ad.....";
$query = array("id"=>$nccAdgroupId,
							"statType"=>"NPLA_SCH_KEYWORD");
			$data = $this->GET('/stats', $query);

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

지표 담당자로부터 문의하신 부분 처리가 되었다는 전달을 받았습니다. API를 다시 호출해 보시고 문제가 있으면 코멘트 부탁드립니다.

**Comment by jxamen** [comment]
감사합니다.
