### ISSUE TITLE
키워드 확장에 대한 추적기능 문의 드립니다. (match parameter)

### ISSUE THREAD

**Issue by gimslab** [naver/searchad-apidoc#781]
안녕하세요. 키워드 확장기능을 테스트하고 있습니다.

https://saedu.naver.com/help/faq/ncc/view.naver?faqSeq=120
의 내용대로 했구요.

adGroup에 "키워드 확장 (beta)" 기능을 켜고 트래킹을 위해 키워드연결URL의 끝부분에 아래내용을 추가하였습니다.
```
&match={match}
```

몇 일 테스트해본 결과 저희 웹서버 로그에 저런 값이 들어오긴하는데 모두 match=1 값만 들어오고 있습니다.
하지만 네이버에서 제공되는 보고서에는 "확장" 검색이 일어났고 클릭이 발생한걸로 나오구요.

혹시 어떤 부분을 더 확인해야하는게 있을까요?

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 API입니다. 

이곳은 검색광고 API 서비스 관련 기술지원만을 제공하고 있으며 각 기능을 담당하는 저희 개발자분들이 본인들이 담당하고 있는 기능에 대한 문의를 직접 답변을 드리고 있습니다. 
즉 추적 URL기능 관련 담당자는 이 곳에 오지 않기 때문에 답변이 올라오지 않습니다. 물론 제가 담당자 분께 전달 드릴수도 있긴 한데요. 
질문 내용상 계정정보나 데이터 추적등 전체 공개인 이 공간에서는 이야기 나누기 어려운 정보들이 필요할 수 있고, 제가 담당자를 찾아 질문을 전달해서 다시 답변을 받아 이곳에 올리는 형태로 여러 단계를 거치는 것보다는 고객센터로 바로 문의 주시는 편이 효율적이고 훨씬 빠르게 답변을 받으실 수 있을 것 같습니다.

고객센터는 아래 링크에서 확인하실수 있습니다. 
https://saedu.naver.com/help/faq/ncc/index.naver
(검색 광고주센터 로그인 하시고 좌측 메뉴 하단에 전화 상담을 클릭하시면 됩니다.)

감사합니다.

**Comment by gimslab** [comment]
아 그렇군요. 안내 감사합니다.
