### ISSUE TITLE
소재 현재 입찰가 변경 문의 

### ISSUE THREAD

**Issue by jjsk109** [naver/searchad-apidoc#782]
안녕하세요~ 
PHP 셈픔로 소재 (ad id)로 소재의 현재 입찰가를 변경을 하려고 하는데 
결과는 성공과 같이 ad의 정보가 나오지만 금액은 변경되지 않아 문의 드립니다.

 $nccAds=array(
      'adAttr' => array("bidAmt" => 100,
                          "useGroupBidAmt" => true
                      ),
      'userLock' => true,
      'nccAdId' => 'nad-a001-02-000000177057577'
  );

  $update = $api->PUT('/ncc/ads/nad-a001-02-000000177057577', $nccAds, array("fields" => "userLock") );
  print_r($update);
  
  쌤플과 문서를 보고 작성한 내용입니다. 

아래는 print_r로 출력한 결과 입니다.
  Array ( [nccAdId] => nad-a001-02-000000177057577 [nccAdgroupId] => grp-a001-02-000000026460446 [customerId] => 1064402 [inspectStatus] => APPROVE ...

PS. 변경하고자 하는 소재는 관리 고객의 소재입니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

소재의 입찰가를 변경하기 위해서는 `PUT /ncc/ads/nad-a001-02-000000177057577?fields=adAttr` 을 사용하시고, adAttr json에 아래와 같이 입력 하시면 됩니다.

```javascript
{
  "bidAmt":500, // 바꾸고자 하는 입찰가
  "useGroupBidAmt":false // 그룹입찰가 사용여부는 false
}
```

**Comment by jjsk109** [comment]
$adIdArr["ids"] = ad-Id;
$nccKeyword=array(
    "adAttr" => array("bidAmt" => 50,
                "useGroupBidAmt" => false ),
    "nccAdId" => ad-Id,
    "type" => "SHOPPING_PRODUCT_AD"
);
$query = array(
        fields" => "adAttr"
);
$update = $api->PUT('/ncc/ads/ad-Id', $nccKeyword  ,$query ); 

이렇게 하니 잘 됬어요 너무 감사합니다
