### ISSUE TITLE
AdExtension: create (HEADLINE) 노출가능 위치지정 api 유무

### ISSUE THREAD

**Issue by ROSETTA-LEE** [naver/searchad-apidoc#784]
안녕하세요.
네이버 광고센터에서 확장소재 중 headline 생성 시 노출가능위치지정 옵션을 선택할 수 있게 되어 있는데요.
api 문서의 headline 항목(http://naver.github.io/searchad-apidoc/#/operations/POST/~2Fncc~2Fad-extensions)에는
해당 옵션을 지정하는 부분을 찾기 어려워 문의 드립니다.
혹 지원 가능한 부분이라면 문서 업데이트를 요청드릴 수 있을까요?

![1](https://github.com/naver/searchad-apidoc/assets/87587045/f627de07-c6aa-4644-9d44-4c0dca679fe8)

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요. 네이버 검색광고 입니다.

requestBody의 json 구조체의 필수 값(예: mobileChannelId 등등)을 지정하고, "adExtension" 필드내 "pin" 값이 1이면 위치1, 2이면 위치2에만 노출로 지정이 됩니다. 관련해서 문서에 반영하도록 하겠습니다.
```
{
  "mobileChannelId": "xxxxxx",
  "schedule": null,
  "userLock": false,
   ....
  "type": "HEADLINE",
  "adExtension": {
    "pin": 1,
    "headline": "추가제목 입니다."
  }
}
```
아래처럼 pin 필드 자체가 없으면 모든 위치에 노출 가능합니다.
```
{
  "mobileChannelId": "xxxxxx",
  "schedule": null,
  "userLock": false,
   ....
  "type": "HEADLINE",
 "adExtension": {
    "headline": "추가제목 입니다."
  }
}
```

감사합니다.
