### ISSUE TITLE
AdExtension: create (DESCRIPTION_EXTRA) API 추가 요청

### ISSUE THREAD

**Issue by ROSETTA-LEE** [naver/searchad-apidoc#785]
안녕하세요.
네이버 광고센터에서 추가설명 등록 후 type 조회 시 DESCRIPTION_EXTRA 로 확인되는데요.
현재 AdExtension 문서의 create 에 해당 항목이 보이지 않아, 혹 API로 생성하는 것이 가능하다면 방법을 안내 부탁드릴 수 있을까요?

![a](https://github.com/naver/searchad-apidoc/assets/87587045/ab3eecc0-6945-4bf5-b0ca-f8b1b668bb70)

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요. 네이버 검색광고 입니다.

문의하신 방법처럼 JSON 구조체를 설정하시면됩니다. "adExtension" 필드내의 "description" 에 추가 설명 사항을 입력합니다.
```
{
    "ownerId": "grp-a001-xxxxx",
    "type": "DESCRIPTION_EXTRA",
    "adExtension": {
        "description": "추가설명입니다."
    },
    "schedule": null,
    "pcChannelId": "bsn-a001-xxxx",
    "mobileChannelId": "bsn-a001-xxxx",
    "delFlag": false,
    "userLock": false,
    "usePeriod": false,
}
```

감사합니다.
