### ISSUE TITLE
Ad Extension: get (ownerId를 campaignId로 호출 시 데이터 없음)

### ISSUE THREAD

**Issue by ROSETTA-LEE** [naver/searchad-apidoc#786]
안녕하세요.
네이버 확장소재 정보를 받아오려면 ownerId를 캠페인과 그룹 2가지 중 하나를 지정하면 되는 것으로 문서에서 확인하였습니다.
그런데 캠페인 ID를 지정하여 호출했을 때 아무 데이터도 확인되지 않아,
현재 그룹 ID 지정 방식으로만 가능한 것인지 문의 드리고자 합니다.
바쁘시겠지만 가능하신 때에 답변 부탁 드리겠습니다.

감사합니다.
![AdExtension_get](https://github.com/naver/searchad-apidoc/assets/87587045/0c9c92af-e28b-4831-bca4-e1fd22497209)

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

ownerId로 지정한 campaign id에 실제 확장소재가 등록이 되어 있어야 조회가 가능합니다.

감사합니다.

**Comment by ROSETTA-LEE** [comment]
답변 감사합니다.
확장소재는 캠페인과 그룹 2곳에 등록할 수 있는데,
그룹의 확장소재는 상위 캠페인 ID가 아닌 그룹 ID로만 조회할 수 있다고 이해하면 될까요?

**Comment by naver-searchad** [comment]
네. 맞습니다. 
확장소재가 소속된 캠페인 또는 그룹의 ID를 ownerId로 지정하시면 됩니다.

감사합니다.
