### ISSUE TITLE
managedKeyword 이슈

### ISSUE THREAD

**Issue by kaorimikage** [naver/searchad-apidoc#787]
#685 해당 이슈로 부터 6개월 정도가 지났습니다.

여전히 네이버 검색결과에는 3개의 광고만 노출되는데 API로 호출한 PCPLMaxDepth는 15로 나오는 현상(올레인터넷신청)이 여전히 지속되고 있으며 반대로 네이버 검색결과에는 7개의 광고가 노출되는데 API로 호출한 PCPLMaxDepth는 3으로 나오는 현상(서면건선)이 있습니다.

어떻게 진행되고 있는지 알고 싶습니다.

**Comment by kaorimikage** [comment]
더불어 지금 볼만한 파워링크가 표시될 경우 슬롯수는 15개더라도 실제 표시되는 광고는 10개 뿐인데 이 경우에 대한 대응이 되는것인지 궁금합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API 입니다. 

우선 해당건에 대한 진행이 늦어지고 있는 점에 대해 사과 말씀드립니다. 
최대 노출 가능 광고수는 광고 상품의 변화에 크게 영향을 받는 데이터인데 
작년 말 ~ 올해 중반에 이르기까지 계속 광고 상품의 변화가 진행되고 있어 
이에 대한 처리 방안 마련에 난항을 겪고 있는 상황입니다. 

담당 부서장에게 진행 일정을 추가로 문의해 보니 늦어도 2,3 개월내에는 
방안을 마련해서 적용하겠다는 답변을 받았습니다. 

추후 방안이 마련되면 공지등을 통해 안내 드리도록 하겠습니다.

감사합니다.
