### ISSUE TITLE
키워드 플러스 성과 보고서 변경 공지 문의

### ISSUE THREAD

**Issue by SM10855** [naver/searchad-apidoc#788]
안녕하세요.

키워드 플러스 성과 보고서 (reportTp : EXPKEYWORD)

대상 보고서
KEYWORD PLUS Performance Report (reportTp : EXPKEYWORD)

변경 일시(KST 기준)
2023년 7월 6일 16시
변경 시점 이전에 생성된 보고서는 변경을 반영하지 않습니다. 필요시 재생성하여 주십시오.
또한 유사 검색어 기능이 제공되기 이전 시점인 7월 6일 이전 지표는 모두 검색어 타입이 1(키워드 플러스)로 표시 됩니다.

위와 같이 공지를 확인했습니다.

Q1) 2023년 7월 7일에 시점에  2023년 7월 5일자 보고서 요청시에는 변경되기 전 건으로 
유사 검색어 (Search Keyword Type) 지표는 보고서에 포함되지만 모두 1로 표시되는거로 인지하면 될까요.

Q2) Search Keyword Type이 1(확장), 2(유사검색어) 정상적으로 확인 가능한 일자는 2023년 7월 6일로 보면 될까요.

Q3) 유사 검색어 기능 제공에 따른 마스터 변경
대상 마스터 : Adgroup
20번쨰 열로 유사검색어 사용여부 항목이 추가되는데, 
적용 시점이 2023년 6월 28일 17시~17시30분 사이에 되면,

해당  Master-Report 요청시 요청 날짜(fromTime) 를 
2023년 6월 28일 이전으로 요청할 경우에도 
20번째 열이 추가된 상태로 반환 받는 거로 인지하면 될까요.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

답변 드립니다. 


Q1) 네 필드는 추가되나 7월 6일 유사 검색어가 노출에 반영 되기 이전에 값들은 모두 키워드 플러스로만 노출된 값들이므로 1로 표시됩니다. 

Q2) 일단위 보고서 이므로 보고서로 확인이 가능하신 시점은 7월 7일 아침(저희 보고서 기반 데이터 생성 작업이 진행되는 새벽이후)부터 이며 데이터 기준일자는 7월 6일자 데이터 부터 입니다. 

Q3) 네 마스터 보고서에대한 수정 시점 이후부터는 신규 필드가 추가되어 생성됩니다. 마스터 보고서는 스냅샷 생성 시점(to time)을 기준으로 만들어지기 때문에 신규 열은 저희 마스터 수정 적용 시점 이후부터는 항상 존재하게 됩니다.
단 해당 열이 null일수 있습니다.

감사합니다.

**Comment by SM10855** [comment]
답변 감사드립니다
