### ISSUE TITLE
inspect status 21은 무슨 값인가요?

### ISSUE THREAD

**Issue by sooheon** [naver/searchad-apidoc#79]
10 은 검토중, 20는 approved, 30는 limited approved, 40는 pending으로 기재되어있습니다. 대용량 리포트 다운받는 중 21의 값은 갖은 경우를 접해, 어떤경우인지 확인차원에서 여쭤봅니다. 감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

21번은 쇼핑 검색광고의 소재에서만 사용되는 값으로 
20번과 동일한 의미인 approved이므로 광고 노출은 가능합니다. 
단 21번의 의미는 쇼핑 캠페인 소재가 통과상태일때 
네이버 쇼핑의 상품 원본 정보가 업데이트 되어 이를 인터페이싱 받아온 상태일때 
의 상태 값으로 21번이 부여 되어 있으면 저희 시스템이 사후 검토를 추가로 수행하게 됩니다. 
단, 20번일때도 수시로 사후 검수나 모니터링 검수가 실시 되므로 
20번과 실질적인 차이는 없다고 보셔도 무방하겠습니다.

감사합니다.

**Comment by sooheon** [comment]
네 감사합니다
