### ISSUE TITLE
확장소재 등록시 userLock 값 지정시 미적용문의

### ISSUE THREAD

**Issue by parkheeyoung3** [naver/searchad-apidoc#790]
안녕하세요
네이버 확장소재 등록을 하는데 userLock을 'true'로 지정시 생성응답이 'true'로 지정되지 않는데 
해당값을 어떻게 지정하면 될까요?

AdExtension: create
POST /ncc/ad-extensions

post값
{"type":"HEADLINE","customerId":1018XXX,"userLock": "true","ownerId":"grp-a001-01-00000002211XXXX","usePeriod":"false","adExtension":{"headline":"추가제목 테스트11","pin":1}}

응답:
{
    "nccAdExtensionId": "ext-a001-01-00000016064XXXX",
    "ownerId": "grp-a001-01-00000002211XXXX",
    "customerId": 1018XXX,
    "inspectStatus": "UNDER_REVIEW",
    "type": "HEADLINE",
    "adExtension": {
        "headline": "추가제목 테스트11",
        "pin": 1
    },
    "schedule": null,
    "pcChannelId": "bsn-a001-00-000000004066237",
    "mobileChannelId": "bsn-a001-00-000000004066244",
    "delFlag": false,
    "regTm": "2023-06-14T06:54:51.000Z",
    "editTm": "2023-06-14T06:54:51.000Z",
    "inspectRequestTm": "2023-06-14T06:54:51.000Z",
    "userLock": false,
    "usePeriod": false,
    "status": "PAUSED",
    "statusReason": "AD_EXTENSION_UNDER_REVIEW",
    "enable": true
}

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

아래 이슈의 답변을 참고하시기 바랍니다.
https://github.com/naver/searchad-apidoc/issues/776


감사합니다.
