### ISSUE TITLE
타게팅 전환 보고서 데이터 중복 문의

### ISSUE THREAD

**Issue by SM10855** [naver/searchad-apidoc#792]
안녕하세요.

이전에 EXPKEYWORD에 대해서 
커스터머아이디, 캠페인아이디, 광고그룹아이디, 검색어, 매체, PC/모바일 구분이 동일함에도 두개 행으로 값이 나눠져서 표시되는 현상 문제가 있어서 최근에 수정을 해주신 부분과 동일한 증상으로 보입니다.

타게팅 전환 보고서 (Criterion Conversion Report) reportTp : CRITERION_CONVERSION 해당 보고서 데이터도
위와 같이 동일함에도 두개 행으로 값이 나눠져서 표시되는 현상이 있는것 같습니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다.

말씀 주신 부분 확인해 보겠습니다. 혹 가능하시다면 삭제되지 않은 보고서 잡 아이디 한개 정도를 알려주실수 있으실지요?

감사합니다.

**Comment by SM10855** [comment]
job_id : 1888346884

![image](https://github.com/naver/searchad-apidoc/assets/50356241/fb546f82-1d82-4ff5-aa39-5b44e46179cd)

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 담당자입니다. 

최근 일자 전체 데이터를 기준으로 체크를 해봤습니다. 말씀주신 현상을 발견 하지 못했습니다. 
예시를 하나 주실수 있다면 큰 도움이 될 것 같습니다. 

감사합니다.

**Comment by SM10855** [comment]
저도 다시 찾아보고 해당 문제가 있는 부분이 발견되면 다시 문의 드리겠습니다.
