### ISSUE TITLE
파워링크 확장소재 추가설명 type 번호

### ISSUE THREAD

**Issue by SM11187** [naver/searchad-apidoc#793]
안녕하세요.
파워링크 확장소재 추가설명 업로드/다운로드 기능 구현 중에 있습니다.

이전 개발자가 달아놓은 코멘트에
1. 전화번호 , 2. 위치정보, 3. 네이버 예약, 6. HEADLINE(추가제목) 7. DESCRIPTION(홍보문구), 8. 서브링크, 9. 가격링크  (API에서 내려오는 코드값) 이라고 적혀있는데,
혹시 추가설명 DESCRIPTION_EXTRA는 몇 번인지 알 수 있을까요?

감사합니다 !

**Comment by naver-searchad** [comment]
안녕하세요. 네이버 검색광고 API입니다.

DESCRIPTION_EXTRA 는 32번이며 다음의 wiki 를 참고하시면 되겠습니다. 

https://github.com/naver/searchad-apidoc/wiki/FAQ#q-%ED%99%95%EC%9E%A5%EC%86%8C%EC%9E%AC-%EC%9C%A0%ED%98%95%EC%9D%80-%EC%96%B4%EB%96%BB%EA%B2%8C-%EB%90%98%EB%82%98%EC%9A%94

감사합니다.

**Comment by SM11187** [comment]
확인되어 해결됐습니다. 
감사합니다!
