### ISSUE TITLE
Invalid Time Stamp 오류

### ISSUE THREAD

**Issue by scotties386** [naver/searchad-apidoc#794]
안녕하세요

샘플코드를 실행해보면 항상 

{"timestamp":"1687141399277","status":403,"type":"urn:naver:api:problem:invalid-timestamp","title":"Invalid Timestamp","detail":"Request has expired."}

이 발생합니다.

타임 스탬프값이 다른 것 같아 여러가지 방법으로 시도해 보았지만 언제나 invaild timestamp 오류가 발생합니다.
가져오는 타임스탭프 값을 http://currentmillis.com/ 와 비교해봐도 차이가 없는데
해당 오류가 왜 계속 발생하는 걸까요..

별도의 수정없이 샘플코드를 VS2022 에서 구동하였습니다.

어떻게 해결해야할지 도움 부탁드립니다..

**Comment by naver-searchad** [comment]
@scotties386 안녕하세요. 네이버 검색광고 API 담당자입니다.

테스트 하고 계신 장비의 시간이 정확한지 한번 확인 부탁드리겠습니다. 
정확한 시간이 아닐경우 서버와 시간이 차이가 나서 오류가 발생할수 있습니다.

만약 오류가 계속 발생하신다면, 응답 Header 의 x-transaction-id 값을 전달해주시면 더 정확한 확인이 가능하니, 참고 부탁드리겠습니다.

감사합니다.

**Comment by scotties386** [comment]
시간이 차이가 있었습니다. 답변 감사드립니다.
