### ISSUE TITLE
마스터리포트 - BrandThumbnailAd

### ISSUE THREAD

**Issue by SM10855** [naver/searchad-apidoc#795]
Thumnail Image path 관련 데이터 문의드립니다.

상대 이미지 경로로 데이터를 제공해주시는데, 
데이터를 보면 URL로 접속해서 볼 수 있는 값은 아닌거 같아 보입니다.
URL 주소로 변환해서 보는 방법이 있을까요?

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 보고서 담당자입니다. 

답변이 늦어 죄송합니다. 해당 건 저희 착오로 처리 누락이 되어 있었습니다. 
확인 되는데로 빠르게 답변 드리겠습니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 보고서 담당자입니다.

해당 건 이미지 처리 담당 부서에 문의 중으로 관련 가이드를 정리하고 있습니다. 
완료 되는데로 답변 드리도록 하겠습니다. 
늦어져서 죄송합니다. 

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 보고서 담당자입니다.

현재 해당 건에 대해 담당 부서와 작업이 진행 중에 있습니다.  대략 차주중에는 답변을 드릴수 있을리라 예상됩니다. 
답변이 크게 지연되어 상황 보고 드립니다. 

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

우선 답변이 지연 되어 대단히 죄송합니다. 

오래 기다리셨으므로 결론만을 간단히 정리해서 말씀드립니다. 
1. 제공되는 이미지 파일명은 인코딩 되어 있거나 한것이 아닌 이미지의 파일명이 입니다.
2. 저 이미지를 로딩하기위해서는 도메인과 URL이 필요한데 현재 이 도메인을 통해 이미지를 정상적으로 다운로드 받지 못하는 상황입니다. 
3. 따라서 현재  상품 이미지를 다운로드 하시거나 로딩 하실 방법이 존재하지 않습니다. 

**이에 이미지를 다운받으실수 있는 API를 별도로 준비 중이고 이 작업에 상당한 시일이 소요 될것으로 보입니다. 
제공 가능 일정이 확정되면  별도 공지 및 릴리즈 노트를 드리도록 하겠습니다.** 

결국 더 기다리시게 되어 대단히 죄송합니다. 

감사합니다.

**Comment by SM10855** [comment]
답변 감사합니다.
