### ISSUE TITLE
managedKeyword 관련이슈

### ISSUE THREAD

**Issue by kaorimikage** [naver/searchad-apidoc#796]
오늘 17시경부터 갑자기 API에서 pcplmaxDepth 값이 4와 5가 넘어오고 있습니다.

LGU플러스
KTTV인터넷

슬롯수 4나 5가 앞으로 적용되는 것인지요?
실제 네이버 포털에서 해당 키워드로 검색을 하면 광고가 15개가 표시됩니다. 
빠르게 확인 부탁드립니다.

**Comment by kaorimikage** [comment]
모바일 슬롯수와 비슷한데 혹시 모바일 슬롯수 넘겨주려다가 PC슬롯수값이 잘못 적용된 것인지요?

**Comment by naver-searchad** [comment]
안녕하세요. 네이버 검색광고 API입니다.
우선 이용에 불편을 드려 대단히 죄송합니다.

해당 오류 수정하여 배포하였습니다.

**Comment by kaorimikage** [comment]
아직 슬롯수가 잘못 넘어오는 키워드들이 있습니다.

수출바우처신청 키워드의 경우 네이버 포털에서 광고가 3개가 표시되는데 API에서 pcplmaxDepth 값이 1이 넘어오고 있습니다. 확인 부탁드립니다.
