### ISSUE TITLE
managedKeyword 관련이슈_2

### ISSUE THREAD

**Issue by kaorimikage** [naver/searchad-apidoc#798]
PCPLMaxDepth 값은 기존에 3 or 15만 넘어오고 있었습니다.
그런데 이전 #796 이슈에서 해결됐다고 한 이후 부터 PCPLMaxDepth 값이 1이 넘어오고 있습니다.

업데이트 확정된 내용인지 궁금합니다.

**Comment by naver-searchad** [comment]
안녕하세요. 네이버 검색광고 API입니다.

PCPLMaxDepth 관련 추가로 반영될 업데이트 사항이 있습니다.
금주 수요일(2023-06-28)에 업데이트 반영될 예정입니다.

감사합니다.

**Comment by kaorimikage** [comment]
업데이트 이슈 언제쯤 공개가 되나요?

**Comment by naver-searchad** [comment]
안녕하세요. 네이버 검색광고 API입니다.

금일 오후 5시 쯤에  업데이트 완료될 예정입니다.

**Comment by kaorimikage** [comment]
업데이트 이후 PCPLMaxDepth 값이 1로 넘어오던것이 다시 예전처럼 3으로 넘어오는 것인지요?

**Comment by naver-searchad** [comment]
안녕하세요. 네이버 검색광고 API입니다.

각 키워드의 속성에 따라 다릅니다.
어떤 키워드는 기존과 같이 3으로 나오는 경우가 있을 수 있고 
어떤 키워드는 1이나 다른 값으로 나올 수 있습니다.

참고 사항: 
 - 현재 업데이트 사항 반영된 상태입니다.

감사합니다.

**Comment by kaorimikage** [comment]
그럼 앞으로 PCPLMaxDepth 값이 1, 3, 15 외에 다른 값이 넘어올 수도 있다는 얘기인가요?

**Comment by naver-searchad** [comment]
안녕하세요. 네이버 검색광고 API입니다.

네 맞습니다.

특정 값으로 고정된 값이 아닌 수시로 변경될 수 있습니다.
1, 3, 15 외에 다른 값으로도 올 수 있습니다.

감사합니다.
