### ISSUE TITLE
소재 API GET response 문의

### ISSUE THREAD

**Issue by SM10855** [naver/searchad-apidoc#799]
http://naver.github.io/searchad-apidoc/#/operations/GET/~2Fncc~2Fads%7B%3Fids%7D

GET /ncc/ads/{adId}

property name 중 ad 부분에 Object type으로 받게 되는데,

최근 업데이트된 내용으로, 받아볼 수 있는 변수들을 알 수 있을까요?

현재 작성된 내용으로는 지금까지 업데이트 된 내용들에 대해서 보이지 않아서 요청드립니다.

감사합니다 :)

**Comment by naver-searchad** [comment]
@SM10855 
광고 유형별로 조금씩 다른 부분에 대해서 추후 보강해야 될 것으로 보입니다.
혹시 궁금하신 필드가 있을까요?

**Comment by SM10855** [comment]
안녕하세요, 광고소재의 TYPE별로 다른거 같아보입니다.

TEXT_45
SHOPPING_PRODUCT_AD
CONTENTS_AD_INFORMATION
CONTENTS_AD_PRODUCT
BRAND_SEARCH_AD
PLACE_AD
CATALOG_AD

위에는 API 문서상에 작성되어 있는 TYPE 인데 혹시 더 있을까요.
SHOPPING_BRAND_AD 라는 타입도 response 값이 다르게 내려오더라구요,
타입별로 ad(Object type)을 알 수 있으면 좋을 것 같습니다!

감사합니다 :)
