### ISSUE TITLE
Stat report downloadUrl 사용법 관련 질문 입니다.

### ISSUE THREAD

**Issue by younseunghyun** [naver/searchad-apidoc#8]
stat report api 콜을 통해서

downloadUrl을 받아왔습니다.

해당 대용량 보고서 url을 접근하기 위해 다른 api들의 사용법과 같이 header에 api-key, customer, signature, timestamp를 넣어 get 요청을 반환받은 url에 보내고 있습니다.

현재 signature invalid에러가 뜨는 상황입니다.

어떤식으로 요청을 보내야 할까요?

**Comment by naver-searchad** [comment]
안녕하십니까. 비즈상품운영실 조원근입니다. 
 
시그니쳐가 잘못 만들어 졌을 가능성이 상당히 높아 보이는데요. 
 
사용하신 시그니쳐와 타임스탬프, 라이선스를 받으신 광고주센터 아이디를알려 주시겠습니까?

감사합니다.이 메일은 나눔글꼴로 작성되었습니다. 설치하기

   조원근  Cho Wonkeun 
비즈상품운영실   / 광고서비스매니저 

 경기도 성남시 분당구 불정로 6 네이버 그린팩토리, 463-867
Tel 031-784-4013   Mobile 010-8953-3966 
Email  peiper.cho@navercorp.com 

 
   
-----Original Message-----

**Comment by younseunghyun** [comment]
안녕하세요

해당 이슈는 downloadUrl을 그대로 사용해서 다시 get 요청을 보내면서 문제가 발생하였습니다.

MasterReportSample에 있는 방법으로 인코딩 변환후 해결 하였습니다.

감사합니다 👍
