### ISSUE TITLE
Is estimate function returning data of one month?

### ISSUE THREAD

**Issue by developerlicw** [naver/searchad-apidoc#80]
Hello Naver searchad API developers.
I am using naver searchad API and tried to use Estimate API recently.
When using performance, I can get impression, click and cost data. But as I checked all the documents, I cannot find the time period of the estimate data. Is the data of one month long? As I checked the Naver SearchAd center, it seems to be so. But I want to make sure of it. 
Please help me. Best regards and many thanks.

**Comment by naver-searchad** [comment]
Hi. 

Yes, 
the data provided by the estimate (performance) API is one month(4 weeks, 28 days) long data

Thanks

**Comment by developerlicw** [comment]
Hello naver-searchad,

Thanks for your kind reply. It's very helpful for me and my team.

I will close this issue

**Comment by developerlicw** [comment]
Hello naver-searchad,

Sorry for reopening this issue. I want to confirm about the performance data's referring period.
As you kindly told me, the estimate data is for 4 weeks from the day to estimate, is it referring to the data of the same period of, for example, last year? Or is it using the data of just 4 weeks before this day?

This is quite import for using the API, I am looking forward to your reply.

Thanks very much.

**Comment by naver-searchad** [comment]
Hi 

Predictive logic is modeled using years of AD data to model performance patterns and tuned to data over the past four weeks.
So we look at both the recent 4-week data and the historical data over the years.
For reference, the last four weeks are the last 28 days from the last past Sunday.

thanks

**Comment by developerlicw** [comment]
Hello naver-searchad,
Thanks very much for the explanation. My sincere apologize for the late reply.
So the estimate is a combination of the data of last year and the last four weeks. I think I totally understand this.
Besides, sorry for asking again, but I want to know is there any way to move a keyword from one ad group to another without changing keyword id?
Until now, we have always been re-registering the keywords into destination adgroup, which will give new ids to the keywords, and then delete the old ones from the source adgroup. But is there a way which can keep the id? We really need to keep the id.

Thanks very much for you patience, I'm looking forward for your reply.

Sincerely Li.

**Comment by naver-searchad** [comment]
Hi.

we does not support moving keywords to other groups. This is because the system architecture does not support it.

thanks

**Comment by developerlicw** [comment]
Hi naver-searchad,

Thanks very much for the reply.
I see, so if I want to move the keywords, I will have to re-register and delete the old ones.
Okay, I see, I will close this issue.

Thanks very much for all the support.
