### ISSUE TITLE
확장소재 가격링크 create API 문의

### ISSUE THREAD

**Issue by SM11187** [naver/searchad-apidoc#800]
안녕하세요.

파워링크 확장소재 가격링크 create API 사용 중에 있는데요,
현재 가격링크1만 가능하도록 구현되어있는데
광고 페이지를 보니

![image](https://github.com/naver/searchad-apidoc/assets/94828850/c33600e9-16d2-4d64-b861-1806309d3c1c)

서브링크와 같이 3개까지 한번에 저장이 가능한 형식이여서 API로도 한번에 3개까지 저장 가능한지 여부가 궁금하며,
서브링크와 같은 방식으로 시도했는데 오류가 발생하여 예시도 부탁드리겠습니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요. 네이버 검색광고 API입니다.
아래와 같이 adExtension JSON 필드  하부에 array 형태로 등록하시면 되겠습니다.

```
{
   "type": "PRICE_LINKS",
   "adExtension": [
       {
           "name": "가격이름1",
           "price": 100,
           "modifier": "부터",
           "final": "http://test.com"
       },
       {
           "name": "가격이름2",
           "price": 200,
           "modifier": "까지",
           "final": "http://naver.com"
       },
       {
           "name": "가격이름3",
           "price": 300,
           "final": "http://test3.com"
       }
   ],
   "schedule": null,
   "userLock": false,
   .............
​
}​​
```
감사합니다.

**Comment by SM11187** [comment]
정상 저장되며, 오류는 개인적인 실수로 발생한 것 확인했습니다.

감사합니다.
