### ISSUE TITLE
StatReport 당일 데이터 요청 시 오류 문의

### ISSUE THREAD

**Issue by paul-yuk** [naver/searchad-apidoc#801]
안녕하세요

StatReport 에 대한 문의사항이 있습니다.
당일에 대한 리포트 생성 요청 (POST /stat-reports) 시 아래와 같은 오류가 발생함을 확인하였습니다.
```
# 요청 customer_id : 533124
{
    'code': 10004,
    'message': '선택하신 조건에 지표가 확인되지 않습니다. 보고서 항목이나 기간을 조정하세요.'
}
```

대시보드 상에는 데이터가 확인되므로, 데이터가 없어서 오류나는 것은 아니라고 생각됩니다.

전날 등의 과거 날짜에 대한 요청할 때는 정상적인 리포트 생성 요청이 이루어집니다.
당일 데이터에 대한 리포트 생성은 스펙상 안되는 것인지, 아니면 당일 기준 N시 이후에 되는것인지 궁금하여 문의 드립니다.

감사합니다.

**Comment by paul-yuk** [comment]
@naver-searchad 
혹시 확인이 어려우신 부분일까요?

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

답변이 지연되어 대단히 죄송합니다.  STAT-REPORT는 전일자 데이터 부터 제공됩니다. 
또한 전일자 지표라도 저희가 기반 데이터를 생성하는 시간이 필요하여 보통 오전 6시 이후(점검등이 있는 경우 오전 10시까지도 늦어질수 있습니다. 모든 점검은 공지 드리고 있습니다.) 부터 생성 됩니다.
당일자 지표는 STAT 을 활용해 주시기 바랍니다.  
STAT : https://naver.github.io/searchad-apidoc/#/operations/GET/~2Fstats%7B%3Fid,fields,timeRange,datePreset,timeIncrement,breakdown%7D

감사합니다.

**Comment by paul-yuk** [comment]
답변 감사합니다.
