### ISSUE TITLE
공유예산 API url 문의

### ISSUE THREAD

**Issue by SM10855** [naver/searchad-apidoc#802]
안녕하세요, 

http://naver.github.io/searchad-apidoc/#/release-notes

릴리즈노트에 공유예산 API 관련 레퍼런스가 존재하는데, 해당 Rest API로 호출하면 호출이 되지 않습니다.
URL이 존재하지 않거나, 다른 것인지 확인 부탁드립니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

호출하신 URL과 Paramter 등의 정보를 알려주시기 바랍니다.

감사합니다.

**Comment by SM10855** [comment]
안녕하세요.

공유예산 전체조회
호출 url : https://api.naver.com/ncc/shared-budgets
파라미터 x

나머지 파라미터 정보는 토큰정보로 제외하겠습니다.

감사합니다.

**Comment by naver-searchad** [comment]
@SM10855 
안녕하세요 네이버 검색광고 API 담당자입니다.

공유예산 API 관련해서 설정 오류가 있었고, 수정 완료되었습니다. 

불편을 끼쳐 드려 죄송합니다. 감사합니다.
