### ISSUE TITLE
광고그룹 마스터  유사검색어 기능 

### ISSUE THREAD

**Issue by SM10855** [naver/searchad-apidoc#803]
안녕하세요. 

광고그룹 마스터 리포트 유사검색어 반영이 2023년 6월 28일 17시 ~ 17시30분 사이에 반영된다고 공지받았습니다.

혹시 언제쯤 변경되는지 알 수 있을까요.

지금 내려받아도 이전 그대로 상태로 받고있습니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

현재 배포진행중인데요. 예상보다 조금더 시간이 걸리고 있습니다. 늦어져서 죄송합니다.
개별 장비별로는 반영이 된 장비와 되지 않은 장비가 현재 혼재 되어 있는 상태로
대략 6시 정도면 모든 장비에 반영이 완료 될것 같습니다. 

감사합니다.

**Comment by SM10855** [comment]
마스터 리포트 생성 요청해보니 ERROR 상태를 내려받고 있습니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다.

추가된 필드가 포함되지 않는 문제가 발생해서 재배포 중입니다. 불편 드려 죄송합니다. 
그리고 문의 주실때는 꼭  job 아이디를 함께 알려주시기를 부탁드립니다.

감사합니다.

**Comment by SM10855** [comment]
job_id=4C345DFD9F27B14CC0D7427475BBCF29

이제 ERROR는 안나오고 BUILT로 정상적으로 나오긴 합니다.
광고그룹마스터 요청시 20번째열 null로 내려오고 있습니다.

아마 다시 재배포 중이어서 그런거로 보면 될까요

감사합니다.

**Comment by SM10855** [comment]
job_id : DD276F6225F042EF75736007FADE9119

20번쨰 열에 1 값은 잘 나오는데, null 인 데이터가 중간에 존재합니다.

customer id, grp_id , cmpn_id
239017	grp-a001-04-000000003951129	cmp-a001-04-000000000674040


감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다.

네 현재 재배포의 영향인것 같습니다. 배포 완료 후 다시 코멘트 남기겠습니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 보고서 담당자입니다. 

문제가 해결 되지 않아 금일 배포는 원복 하고, 추후 다시 일정을 잡아 공지 드리도록 하겠습니다.
오래 기다리셨는데...대단히 죄송합니다. 

감사합니다.

**Comment by SM10855** [comment]
추후 공지해주시는 일정에 맞춰 대응하겠습니다. 
신속하게 확인해주셔서 감사합니다 :)
