### ISSUE TITLE
Adgroup create 시 발생 오류

### ISSUE THREAD

**Issue by shimshim-e** [naver/searchad-apidoc#804]
안녕하세요,
잘 되던 광고그룹 생성 API 가 갑자기 동작을 하지 않습니다.

{'code': 3709, 'status': 400, 'title': 'Invalid value in the Keyword Plus field of an ad group.'}

API 명세를 보니 파라미터에
useKeywordPlus
keywordPlusWeight
가 추가됐던데
useKeywordPlus : False
keywordPlusWeight : 100
이렇게 같이 보내도 같은 에러가 발생합니다.

어떻게 해결해야 할까요?

**Comment by shimshim-e** [comment]
자체 해결했습니다.
useCloseVariant
를 추가해야 하네요.
명세도 업데이트를 좀 해주셨으면..

**Comment by hon9hb-dbase** [comment]
@naver-searchad 

해당 내용 관련하여 릴리즈 노트(https://naver.github.io/searchad-apidoc/#/release-notes)에는
`광고그룹 생성시 일치(유사검색어) 노출 여부`를 입력하지 않을 경우 `사용함(true)로 설정`이라고 기재되어 있는데
실제 파워링크 광고그룹 생성 API 호출 시 `useCloseVariant`가 필수값으로 확인됩니다.
문서의 오기재인지 정책이 변경될 예정인지 궁금합니다..

**Comment by naver-searchad** [comment]
안녕하세요. 네이버 검색광고 API입니다

해당 부분은 내부 오류로 필수 값으로 동작했었고
현재 수정하여 반영하였습니다.

이용에 불편을 드려 대단히 죄송합니다.
감사합니다.
