### ISSUE TITLE
광고그룹 마스터리포트 - 유사검색어 관련 

### ISSUE THREAD

**Issue by SM10855** [naver/searchad-apidoc#805]
안녕하세요. 

최근에 마스터리포트 광고그룹 유사검색어 관련 반영은 롤백으로 연기되었는데,

마스터리포트 광고그룹 생성요청하여 파일 받아오면 유사검색어 데이터가 있는 상태로 내려받고 있습니다.

전부다 1로 내려받고 있는데, 6/28에 롤백이 된게 맞을까요

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

우선 혼란을 드려 대단히 죄송합니다. 
6월 28일 배포 실패후 롤백하였고, 6월 29일로 배포일정을 다시 잡아 공지 후 반영 완료 하였습니다. 

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

지금 다시 확인해 보니 API 레퍼런스 페이지 notice쪽 게시판에는 오류가 발생하여 공지 내용이 올라가지 않았고, 
gittub 대문(초기면)에만 공지가 게시 되어 있었습니다. 
다시 한번 혼란을 드린점 사과 말씀드립니다.

감사합니다.

**Comment by SM10855** [comment]
공지 확인하였습니다. 감사합니다.

**Comment by SM10855** [comment]
@naver-searchad 

안녕하세요. 광고그룹마스터 리포트 생성시

fromTime을 2023년 6월 28일부터 하여 호출해서 파일을 받아보면

앞에 모든 데이터가 null로 받아오는 문제가 있습니다.

job_id = 61B29D8CE5AA7598E659C58AB0B38937

입니다.

**Comment by naver-searchad** [comment]
@SM10855 위 job id는 모두 삭제된 id입니다. 삭제되지 않은 id를 알려주세요.

> fromTime을 최초 광고그룹 마스터 리포트 반영일자 시간부터 다시 반영하기 전(2023년6월29일)까지 날짜로 호출해서 파일을 받아보면
> 
> 앞에 모든 데이터가 null로 받아오는 문제가 있습니다.

앞에 모든 데이터가 null로 받아온다는게 어떤 상황을 말하시는건가요 ?

**Comment by SM10855** [comment]
job_id = 2B66C449D0AE1F38225E122BF8700AA5
예시로 하나만 남기겠습니다.

앞에 필수로 받아올 CustomerId, Ad Group Id, Campaign Id 부터 해서 19열까지 모두 .null 내려주고 있습니다.

**Comment by naver-searchad** [comment]
@SM10855 확인됐습니다. 6월28일 20시50분부터 21시사이에 신규컬럼을 추가하는 작업이 진행이 됐는데요.
`fromTime`에 위 작업시간이 포함되고, 다른 변경분이 없을 경우 위 컬럼 데이타만 변경분으로 전송되는 문제가 있습니다.
이 문제를 피하기 위해서는 6월28일 21시이후로 `fromTime`을 가져가시거나,
`fromTime`이 없는 전체 데이타를 가져가신 후 다시 이후의 변경분을 가져가셔야 합니다.

**Comment by hon9hb-dbase** [comment]
@naver-searchad 
안녕하세요, 이슈 작성자분과 동일한 현상을 겪고 있습니다.
혹시 관련하여 오류 수정 계획이 있으실까요? 있으시다면 수정 적용 예정일시가 궁금합니다.

**Comment by naver-searchad** [comment]
@hon9hb-dbase 불편을 드려서 죄송합니다. 위에 설명드린거처럼, 6월28일 21시 이후로 fromTime을 설정하시거나, fromTime없이 전체 데이타를 받으셔서 초기화 하신 후에 다음 변경분을 받으셔야 합니다.

**Comment by hon9hb-dbase** [comment]
@naver-searchad 
앞으로도 계속 6/28 이전으로 지정한 요청은 null 포함 데이터로 반환된다는 말씀이실까요?

**Comment by naver-searchad** [comment]
@hon9hb-dbase 그룹 변경분이 발생하게되면, 해당 레코드의 데이타는 채워져서 반환이되지만, 변경이 없다면, 앞으로도 신규 컬럼에 대해서만 값을 반환하게 됩니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

이 문제에 대해서 인지한 이후 현재까지 방안을 계속 모색했으나 현재로서는 이를 해결할수 있는 방안을 찾지 못하였습니다. 
대단히 죄송한 말씀이기는 하나 현재로서는 fromtime이 6월 28일 21시 이전인 변경분은 정상적인 서비스를 앞으로도 제공하지 못하게 될것으로 생각 됩니다. 

감사합니다.

**Comment by SM10855** [comment]
상세한 답변 감사합니다.

공지사항도 확인했습니다. 감사합니다.

해당 이슈는 닫을게요.
