### ISSUE TITLE
네이버 검색광고 API에서 상품수에 대한 API 정보가 있나요?

### ISSUE THREAD

**Issue by chobass1** [naver/searchad-apidoc#806]
네이버 검색광고 API를 사용중인데..상품수에 대한 API 정보가 있나요?

있다면 어디에서 찾아볼 수 있을까요?검색 키워드에 대한 검색수, 경쟁도... 등의 데이터 API는 있는데..상품수에 대한 API는 못찾겠습니다.

참고로. 네이버 검색광고 API 가이드 활용중입니다.

https://naver.github.io/searchad-apidoc/#/guides

**Comment by naver-searchad** [comment]
안녕하십니까.@chobass1 님 대용량 다운로드 보고서 담당자입니다. 

말씀 주신 상품수는 어떤 의미를 가진 값인지요? 구제적으로 지표에 대한 내용을 말씀해 주실수 있으실지요?

전자의 경우 대용량 

감사합니다.

**Comment by chobass1** [comment]
네이버 검색 키워드에 해당하는 

전체등록 상품수(쇼핑몰)를 얻고 싶습니다.

예컨데 검색 키워드의 월간 검색수에 대한 

상품수 비율이 경쟁강도라고 할때..

상품수 데이터를 얻어야 경쟁강도를 계산해 낼 수 있어서요.

**Comment by naver-searchad** [comment]
@chobass1 님 안녕하십니까...

우선 제가 코멘트 달때 들어간 "전자의 경우 대용량" 이 문구는 오타 입니다. 혼란 드려 죄송합니다. 

어떤 정보를 원하시는지 인지하였구요. 현재 저희 API서비스를 통해서는 해당 정보가 제공되지 않습니다. 
제가 알고 있기로는 해당 정보는 저희 시스템 어디에도 없는 정보라고 알고 있고 수집도 대단히 어려울 것으로 예상되어 상품 담당자에게 확인을 해보고 존재한다면 제공 가능 여부도 담당 개발부서와 검토하여 답변 드리겠습니다. 

감사합니다.

**Comment by naver-searchad** [comment]
@chobass1 님

네이버 대용량 다운로드 보고서 담당자입니다. 
한가지 말씀드리지 못한 사항이 있어서 추가로 코멘트 남깁니다. 
말씀 주신 "검색 키워드에 대한 검색수, 경쟁도... 등의 데이터 API"는 파워링크 상품에 대한 정보입니다. 
쇼핑 검색광고에 대해서 해당 정보가 제공되지 않습니다. 
말씀 주신 내용으로 생각보면 파워링크가 아니라 쇼핑 검색광고에 대한 지표 요청으로 생각되어 추가로 말씀드립니다. 

감사합니다.

**Comment by chobass1** [comment]
답변주신 내용은 정리해보면

네이버 검색광고 API에서는 '검색수', '경쟁도' 등의 정보는 제공하지만

'상품수'는 제공하지 않는다. 라고 이해하면 될까요?

https://naver.github.io/searchad-apidoc/#/guides

그렇다면 이해되지 않는 것이 

네이버 검색광고 API를 활용해서 서비스되고 있는 아이템스카우트, 판다랭크 등

많은 서비스 등에서 상품수를 보여주고 있는데.. 어떻게 이게 가능할까요?

상품수를 얻어낼 방법이 없을까요?  ㅠ.ㅠ



![아이템스카우트 상품수](https://github.com/naver/searchad-apidoc/assets/138850279/289d8972-cd99-459c-bb88-a4f23e0df9ee)

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다,. 

_"네이버 검색광고 API에서는 '검색수', '경쟁도' 등의 정보는 제공하지만
'상품수'는 제공하지 않는다. 라고 이해하면 될까요?"_

**이전에 답변 드린 사항은 간단히 말씀드리면 쇼핑 검색광고 상품 담당자에게 해당 정보가 존재하는지 확인해 보고 있다면 제공이 가능할지 확인해서 답변 드린다는 내용이었습니다.** 

현재 저희 API 스펙과 기반 데이터 DB, 광고 시스템 UI까지 확인해 보았지만 해당 지표가 발견되지 않아 관련부서에 문의를 한 상태입니다.  최종 결론이 도출 되면 바로 다시 답변 드리겠습니다. 

그리고 네이버 검색광고 API [RelKwdStat](https://naver.github.io/searchad-apidoc/searchad-apidoc)에서 제공드리는  '검색수', '경쟁도'는 파워링크 상품에 대한 정보로 네이버 통합검색에서 발생한 검색 및 광고 노출을 기준으로 제공드리는 것으로
저희 서비스 구조가 상품과 광고 노출 영역(미디어)에 따라 지표가 나뉘고 있으므로 지표를 보실때 주의 하셔야 합니다.예를 들어 네이버 검색광고 API [RelKwdStat](https://naver.github.io/searchad-apidoc/searchad-apidoc)에서 제공드리는  '검색수'는 네이버 통합 검색에서 검색한 횟수로서 네이버 쇼핑에서 검색한 횟수는 포함되어 있지 않습니다.

마지막으로 특정 서비스가 저희 API  서비스를 기반으로 한다고 해서 제공되는 모든 데이터가 저희 API에서 제공되는 데이터일 것으로 가정할 수는 없습니다. 이와 같은 혼란을 피하기 위해 API 이용 약관 7조 3항 _["사용자"는 "클라이언트" 내에서 "API 데이터"를 "사용자"가 스스로 제공하는 데이터와 시각적으로 구분되도록 표시하여야 합니다.]_ 이 존재 하는데요. 캡쳐상의 이미지만으로는 이를 구분하기가 어렵네요.  즉, 외부서비스에서 제공되는 데이터가 명시적으로 네이버 검색광고 API를 통해 수집된 데이터라고 표시 되지 않았다면 저희 데이터를 사용한다고 단정 하기는 어려울 것 같습니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다,.

광고 상품 정책 및 광고 노출, 지표 시스템 담당자등 조금이라도 연관이 있는 부서와 담당자들 대부분에게 확인해 보았습니다만 
요청 주신 정보는 저희 시스템에 존재하지 않고, 앞으로도 해당 정보를 수집하지 못 할 것으로 예상된다고 답변받았습니다. 
즉 특정 검색어에 대한 쇼핑 상품 수는 존재하지 저희 서비스와 시스템에는 존재하지 않습니다. 

예시로 들어주신 업체들이 해당 정보를 어떻게 제공하는지는 모르겠습니다만 최소한 저희 검색광고 시스템에서 제공한 데이터는 아닙니다. 

감사합니다.
