### ISSUE TITLE
키워드 플러스 성과 보고서 중복 행 문의

### ISSUE THREAD

**Issue by SM11348** [naver/searchad-apidoc#807]
안녕하세요. 항상 수고가 많으십니다. 

다름이 아니라, 금일 16시 이후 키워드 플러스 성과 보고서 변경이 된 점을 확인했는데,
중복 행 데이터가 그대로 존재하는 것으로 보입니다! 

7월 10일 이전 데이터여서 중복 행이 그대로 노출되는지 문의 드립니다!

-----------------------------------------------------------------------------
statDt : 20221114
JobId : 1914901500

**Comment by naver-searchad** [comment]
@SM11348 님 안녕하십니까.
대용량 다운로드 보고서 담당자입니다. 

네 말씀대로 이번 수정은 과거 데이터를 소급해서 변경할수 없어서 오늘 배포 이후 신규로 생성되는 데이터부터 적용이 됩니다. 
양해 부탁드립니다.

감사합니다.

**Comment by naver-searchad** [comment]
@SM11348 님 안녕하십니까.
대용량 다운로드 보고서 담당자입니다.

네 말씀대로 이번 수정은 과거 데이터를 소급해서 변경할수 없어서 오늘 배포 이후 신규로 생성되는 데이터부터 적용이 됩니다.
양해 부탁드립니다.

위와 같이 답변을 드렸는데요. 답변드리고 나서 다시 읽어 보니 오해 하실수 있게 답변 드렸네요. 죄송합니다. 
중복행 문제는 저희가 과거 데이터를 수정할 수 없어서 7월 10일자 보고서 즉  7월 11일에 생성/다운로드 하실수 있는 전일 데이터 부터 반영 됩니다. 

감사합니다.

**Comment by SM11348** [comment]
넵 답변 감사드립니다 :)

이 이슈는 닫도록 하겠습니다~
