### ISSUE TITLE
광고그룹 생성 error

### ISSUE THREAD

**Issue by miinye** [naver/searchad-apidoc#808]
광고그룹 생성시 useCloseVariant 필드의 미입력시 사용함으로 등록된다고 되어있으나
https://naver.github.io/searchad-apidoc/#/release-notes

실제 적용시 useCloseVariant 필드가 존재하지 않을시 error가 발생하고 있습니다.
![image](https://github.com/naver/searchad-apidoc/assets/58451194/666f6c56-c371-400b-92c7-7c648888dcfc)

확인 부탁드립니다.

**Comment by naver-searchad** [comment]
안녕하세요. 네이버 검색광고 API입니다

해당 부분은 내부 오류로 필수 값으로 동작했었고
현재 수정하여 반영하였습니다.

이용에 불편을 드려 대단히 죄송합니다.
감사합니다.

**Comment by miinye** [comment]
네 감사합니다
http://naver.github.io/searchad-apidoc/#/operations/POST/~2Fncc~2Fadgroups
해당 refference 에도 필드를 추가해주시면 좋을것같습니다.

**Comment by miinye** [comment]
https://naver.github.io/searchad-apidoc/#/operations/PUT/~2Fncc~2Fadgroups~2F%7BadgroupId%7D%7B%3Ffields%7D

업데이트 필드에 useCloseVariant 해당 필드로는 업데이트가 불가능한것으로 보입니다.
![image](https://github.com/naver/searchad-apidoc/assets/58451194/6b44abe1-2aa5-40ad-9f44-13fb604a6846)

저희가 사용중인 광고그룹을 일치로 사용하고 싶으나 해당 필드의 수정이 불가합니다. 
빠른 확인 부탁드립니다.

**Comment by naver-searchad** [comment]
@miinye 안녕하세요? 네이버 검색광고 API입니다.

필드별 update가 아닌 일반 update를 사용하시면 됩니다.
https://naver.github.io/searchad-apidoc/#/operations/PUT/~2Fncc~2Fadgroups~2F%7BadgroupId%7D

단 주의하실 내용은 일반 update api는 의도치 않게 다른 값도 수정이 될수 있으니, 기존 그룹 조회후 결과값에 원하는 변경사항을 적용하신후 호출하시길 권고드립니다.

감사합니다.

**Comment by naver-searchad** [comment]
@miinye 추가하자면 위에 설명한 전체 update api외에도 필드별 update(useKeywordPlus) api를 사용하실수 있습니다.
오류가 발생한 원인을 파악하기 위해서는 Request url과 body정보를 알려주셔야 합니다.

**Comment by miinye** [comment]
필드별 update(useCloseVariant) 로 호출하여 발생한 에러로
필드별 update(useKeywordPlus) 에 useCloseVariant를 포함하여 호출하니 정상작동하는것으로 확인하였습니다.
