### ISSUE TITLE
campaign, adgroup 등의 이름에 tab 문자가 들어가 있는 경우 master report에 escape 처리가 안 되는 이슈

### ISSUE THREAD

**Issue by autorsong-m** [naver/searchad-apidoc#809]
안녕하세요.

이번에 광고그룹에 대한 master report를 내려받고 파싱을 하니 일부 row에서 master report의 원래 컬럼 갯수와 실제 데이터의 컬럼 갯수가 맞지 않는 현상을 발견했습니다.
혹시 몰라서 네이버 광고 대시보드에서 저희 광고그룹명을 점검해 보니 맨 앞에 tab이 들어가 있었습니다.

tsv로 master report를 내려주시는 경우, 캠페인/광고그룹 등의 이름을 쌍따옴표 등으로 escape 처리해 주시거나,
아예 대시보드 상에서나 API를 통해서 캠페인/광고그룹 등을 생성할 때 이름에 tab 문자가 들어가는 것을 시스템적으로 막아주시는 것이 좋을 것 같아 의견드립니다.
그리고 장기적으로는 json 형식으로 master report를 내려주실 계획은 없는지도 문의드립니다.
header가 없는 tsv 형태로 리포트를 내려주시니, 리포트 스키마가 변경될 때마다 그에 맞춰서 파싱 코드에 pre-defined 된 헤더 목록을 변경해 주어야 하는 것이 꽤 불편합니다. 혹은 적어도 헤더가 포함되면 데이터 활용을 자동화하는 데 훨씬 용이할 것 같습니다.

감사합니다.

**Comment by autorsong-m** [comment]
@naver-searchad 안녕하세요. 혹시 확인이 어려우신 이슈일까요?

**Comment by naver-searchad** [comment]
@autorsong-m 님 

안녕하십니까 대용량 다운로드 담당자입니다. 

우선 답변이 늦어 죄송합니다. 

저희 규약상 이름에 탭문자가 들어오지 못하도록 막아둔 상태인데요. 이 작업이 API에서 빠져 있는것 같아
담당자들에게 확인 작업을 우선 진행하고 있었습니다.  
성능 문제로 UI에서만 처리가 되었을 가능성이 높아 보이고 확인이 완료되는 데로 막을 수 있는 방안을 강구해 보겠습니다. 

추가로 제안을 주신 텍스트 한정자의 건은 저도 몇년 전에 추진한 일이 있었으나 일반적으로 사용되는 따움표나 쌍따움표 등이 모두 이름으로 허용되는 문자이고, 허용 문자의 범위가 상당히 넓어서 포기했던 일이 있었습니다. 

이외의 json으로 드리는 방안은 저희 데이터 구조가 상품의 다변화/기능 강화 등으로 인해 단순한 2차원 테이블로 표시하기에는 너무 복잡해져 버려서(대표적인 예가 브랜드 검색의 광고 소재입니다.) 저희로서도 무척 바라는 바이기는 합니다만 앞서 말씀드린 허용 문자 문제 외에도 현재 UI 메뉴(광고관리 시스템 > 보고서 > 대용량 다운로드 보고서)를 통해 마스터를 엑셀등의 간단한 툴로 사용하시는 경우도 상당수 존재하여 모두 일원화하여 json으로 제공드리는 것은 쉽지 않은 일로 생각 됩니다. 
물론 서비스를 두 종류로 운영하는 방법도 있겠습니다만 현재 저희 상황에서는 이중화를 하는 것이 (특히 변경분)대단히 어려운 상황으로 이점 양해를 부탁드립니다. 

마지막으로 헤더의 문제는 과거 이 기능 개편시 많은 사용자분들의 요청에 따른 것이었는데요. 
저희로서도 현재와 같이 필드 변경이 자주 발생하는 상황이라면 헤더추가가 더 이득이 크지 않을까 라는 관점으로 검토하고 있습니다. 단, 이러한 변화는 지금의 저희 사용자 분들의 규모를 생각할때 쉽게 결정하기는 어려운 사항이다 보니 
빠르게 진행하는데는 어려움이 있다는 점 양해를 구합니다. 

탭 문자에 대한 방지 처리 현황 및 대응 방안은 다시 답변 드리도록 하겠습니다. 

감사합니다.

**Comment by autorsong-m** [comment]
@naver-searchad 말씀 주신 내용 충분히 이해했습니다. 상세한 답변 정말 감사드립니다!
