### ISSUE TITLE
비즈머니 기간으로 총 합계 검색

### ISSUE THREAD

**Issue by lee-ji-eun** [naver/searchad-apidoc#81]
비즈머니를 기간별로 총 합계를 내고싶은데,
/billing/bizmoney/cost{?statDt}
이걸로 하루하루 더하는 방법밖엔 없나요?

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

비즈머니 라 하심은 비즈머니 소진액을 의미하시는 것인지요?
아니면 일별 잔액을 의미하시는 것인지요?

감사합니다.

**Comment by lee-ji-eun** [comment]
소진액을 의미합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

소진액인 경우 말씀처럼 /billing/bizmoney/cost{?statDt} 오퍼레이션을 일단위 호출 하여 더하는 방법이
유일한데요. (특히 유상 무상 분류가 필요한 경우)
주의 하실 점의 브랜드 검색의 경우는 단순 손진액이 아니라 일종의 기간인식 금액입니다.
브랜드 검색은 계약시 계약된 금액 전체가 비즈머니에서 차감되나 
/billing/bizmoney/cost{?statDt}에서 제공되는 값은 브랜드 검색 집행 기간동안 일단위로 계약금액을 
일할한 금액으로 제공됩니다. 

예를 들어 지난 1일에 110만원(VAT포함)으로 1/10~1/19까지 브랜드 검색이 집행되는계약을 하셨다면 
1일에 비즈머니는 110만원이 차감되나 /billing/bizmoney/cost{?statDt}에서는 
10일~19일까지 각 11만원씩이 보이게 됩니다.

감사합니다.
