### ISSUE TITLE
쇼핑검색광고 광고그룹 입찰가를 동일한 값으로 수정 시 500 "Internal Server Error" 발생 확인 요청드립니다.

### ISSUE THREAD

**Issue by ephiviolla** [naver/searchad-apidoc#811]
안녕하세요.
쇼핑검색광고 광고그룹 입찰가 수정 시 수정하려는 입찰가가 현재 입찰가와 동일한 경우 500에러가 발생하고 있습니다.

호출 API : `PUT /ncc/adgroups/grp-a001-02-00000002xxxxxxx`
에러코드 : `{"code":1005,"status":500,"title":"Cannot handle the request."}`

파워링크, 쇼핑검색광고 모두 광고그룹 입찰가가 동일한 경우에 발생하는 해당 에러 코드가 이전부터 존재했던 것인지, 최근에 추가된 것인지 알고 싶습니다.
또한 동일한 입찰가로 수정하려는 경우 success|pass 시키거나 커먼한 500에러가 아닌 좀 더 상세하게 표시가 가능할까요?
500에러로 넘어오면 소스 코드상에서 "광고그룹 입찰가가 동일합니다." 와 같이 예외 처리하기에 다소 어려운 점이 있을 것 같습니다.

**Comment by ephiviolla** [comment]
안녕하세요. 혹시 언제쯤 답변 받을 수 있을까요?

**Comment by naver-searchad** [comment]
안녕하세요. 네이버 검색광고 API입니다

업데이트 API 요청 시 request body 전문을 확인을 해야 정확한 파악이 가능 합니다
최근 신규 추가된 [키워드 확장 Beta](http://naver.github.io/searchad-apidoc/#/release-notes) 의 속성(useCloseVariant)이 빠진 것인지 확인 부탁 드립니다.
위 사항 확인에도 문제사항이 없는 경우, 요청 request body  전문을 첨부 부탁 드립니다.

이용에 불편을 드려 대단히 죄송합니다.
감사합니다.

**Comment by ephiviolla** [comment]
안녕하세요. 당시 오류발생했을 때 사용된 Request Body 전문 첨부드립니다.

```json
{
   "useCntsNetworkBidAmt":false,
   "workStatusMessage":"",
   "useDailyBudget":false,
   "workStatus":true,
   "contentsNetworkBidAmt":50,
   "contentsNetworkBidWeight":50,
   "keywordPlusWeight":100,
   "useKeywordPlus":false,
   "mobileNetworkBidWeight":100,
   "useCntsNetworkBidWeight":true,
   "adRollingType":"ROUND_ROBIN",
   "bidAmt":80,
   "nccAdgroupId":"grp-a001-02-000000023147989",
   "userLock":false,
   "pcNetworkBidWeight":160,
   "dailyBudget":0
}
```

추가로 말씀주신대로 useCloseVariant 속성이 없어 추가해서 테스트해보니 정상적으로 작동하네요. 감사합니다~

**Comment by ephiviolla** [comment]
안녕하세요. 추가로 문의드릴 것이 있습니다.

1. 노출여부(useCloseVariant)를 사용하지 않을 시 default 값은 true라고 나와있는데 이는 request body에서 누락되어도 자동으로 true처리된다는 것인가요? 위 경우에는 누락되었는데도 default 처리가 되지 않고 있습니다.

2. 일치(유사검색어) 노출 여부는 파워링크 광고 그룹만 해당된다고 나와있는데 본 이슈에서 문제된 경우는 쇼핑검색 광고그룹이었습니다.
PUT /ncc/adgroups/{adgroupId} API 사용 시
adgroupType이 필수값이 아니여서 사용하지 않았는데 위처럼 사용하지 않고 request 사용 시 해당되는 광고그룹의 범위가 궁금합니다.
혹은 이번과 같은 에러를 방지하기 위해 adgroupType 필드를 필수로 넣어 사용해야할까요?

3. 공식 문서에 아직 useCloseVariant 값에 대한 설명이 추가되지 않은 것 같아 확인 부탁드리겠습니다.

바쁘신 와중에 답변주셔서 감사하고, 확인 한 번만 부탁드리겠습니다.

**Comment by naver-searchad** [comment]
안녕하세요. 네이버 검색광고 API입니다

1. 노출여부(useCloseVariant)를 사용하지 않을 시 default 값은 true라고 나와있는데 이는 request body에서 누락되어도 자동으로 true처리된다는 것인가요? 위 경우에는 누락되었는데도 default 처리가 되지 않고 있습니다.
   - 현재 광고그룹을 생성하는 경우에만 디폴트 처리가 되어 있습니다. 업데이트 시에도 디폴트 처리가 될 수 있도록 패치될 예정입니다.

2. 일치(유사검색어) 노출 여부는 파워링크 광고 그룹만 해당된다고 나와있는데 본 이슈에서 문제된 경우는 쇼핑검색 광고그룹이었습니다.
PUT /ncc/adgroups/{adgroupId} API 사용 시
adgroupType이 필수값이 아니여서 사용하지 않았는데 위처럼 사용하지 않고 request 사용 시 해당되는 광고그룹의 범위가 궁금합니다.
혹은 이번과 같은 에러를 방지하기 위해 adgroupType 필드를 필수로 넣어 사용해야할까요?
   - adgroupType 은 API 에서 자동으로 처리하고 있어 넣지 않아도 됩니다.

3. 공식 문서에 아직 useCloseVariant 값에 대한 설명이 추가되지 않은 것 같아 확인 부탁드리겠습니다.
   - 해당 문서는 현재 개편 중에 있어 [릴리즈노트](http://naver.github.io/searchad-apidoc/#/release-notes) 부분을 참고하여 주시기 바랍니다.

감사합니다.
