### ISSUE TITLE
여러 건의 ad update api 문의

### ISSUE THREAD

**Issue by githubcnsbs** [naver/searchad-apidoc#812]
안녕하세요.

AdKeyword update-items와 같이 여러 건의 Ad update가 가능한 api가 제공되는지 문의 드립니다.
여러 소재 입찰가를 변경하려하나 묶어서 입찰 할 수 있는 api를 찾을 수 없어 api 존재여부 문의 드립니다.

감사합니다.

**Comment by naver-searchad** [comment]
@githubcnsbs 
현재는 제공되고 있지 않습니다.

감사합니다.

**Comment by githubcnsbs** [comment]
답변 감사드립니다.
