### ISSUE TITLE
파워링크 > 광고그룹 기본입찰가 옵션을 '자동입찰 설정(beta)'로 했을 때 키워드확장 옵션 선택 오류

### ISSUE THREAD

**Issue by yuhee62wang** [naver/searchad-apidoc#814]
안녕하세요 ! 

네이버 광고주센터에서 파워링크 > 광고그룹 에서 기본입찰가 옵션을 '자동입찰 설정(beta)' 으로 설정하고 저장한 광고그룹을

**API**로 해당 광고그룹의 '키워드 확장(beta)'의 옵션을 확장 or 일치(유사검색어) or 일치 로 변경하면 오류가 발생합니다. 

광고그룹의 기본입찰가 > 자동입찰 설정(beta) 이 적용된 상태이면 **API로** '키워드 확장(beta)' 옵션을 변경할 수 없는 것인지요?
뭔가 오류인 듯 한데,, 확인 부탁드립니다 !!!

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요. 네이버 검색광고 API입니다

업데이트 API 요청 시 request body 전문을 확인을 해야 정확한 파악이 가능 합니다
최근 신규 추가된 [키워드 확장 Beta](http://naver.github.io/searchad-apidoc/#/release-notes) 의 속성(useCloseVariant)이 빠진 것인지 확인 부탁 드립니다.
위 사항 확인에도 문제 사항이 없는 경우, 요청 request body 전문을 첨부 부탁 드립니다.

이용에 불편을 드려 대단히 죄송합니다.
감사합니다.
