### ISSUE TITLE
api key access level 문의

### ISSUE THREAD

**Issue by githubcnsbs** [naver/searchad-apidoc#815]
안녕하세요.

api key의 access에 level이 있는지 문의드립니다.

 api 호출 수행시 관리하고 있는 customer의 
- customer id 
- api access key 
- secret key 
를 발급받아서 실적 조회(stats/statsReport api) / 입찰(keyword update api)까지 정상적으로 진행하고 있습니다.

그런데, 일부 customer (2개)는 동일한 api 정보를 이용하여 
- 실적 조회(stats/statsReport api)는 정상
- 입찰(keyword update api) 수행시 invalid api key error가 return 
되고 있는데, api access key / secret key까지 발급받은 계정도 api 권한 level이 존재하나요?

존재한다면 수정권한까지 있는 api key를 발급받기 위한 절차는 어디를 참고하면 될까요.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API 입니다. 

써 주신 내용만으로는 이해가 좀 어렵긴 한데요. 
A 라는 계정에서 라이선스키와 비밀키를 발급 받고 A 계정의 광고 정보에 접근하고 있는 상황을 말씀 주신것으로 이해됩니다. 
이런 경우는 전체 권한을 모두 가지고 있게 됩니다. API키와 커스터머 아이디를 다시 한번 확인해 주시기 바랍니다. 
그리고 에러 리턴시 함게 transaction_ID가 리턴되었다면 이 값과 호출 일시 (및 시간대)를 알려 주시면 상세한 확인이 가능합니다. 
권한은 API 라이선스를 받은 계정이 다른 계정에 접근하려고 할때만 적용됩니다. 
혹 A 계정의 라이센스 키로 B 계정에 접근 하고 계신중이라면 권한의 종류에 따라 접근할수 있는 내용이 달라지는데요. 
예를 들면 접근 대상이 되는 계정이 API 라이선스를 받은 계정에 광고관리 권한을 부여하여 준다면 쓰기/읽기가 모두 가능해집니다. 상세사항은 아래 내용을 참고하여 주십시오. API를 통한 호출도 계정 간 권한을 그대로 적용 받습니다. 
https://saedu.naver.com/help/faq/ncc/view.naver?faqSeq=33

감사합니다.

**Comment by githubcnsbs** [comment]
네, 확인결과,
api 키 조회시에 권한 부여받은 계정의 api key로 조회되어 발생했던 문제로 customer 계정으로 확인하여 정상동작 확인하여 이슈  close하겠습니다. 

감사합니다.
