### ISSUE TITLE
StatReport 조회 질문

### ISSUE THREAD

**Issue by jangyujin-hub** [naver/searchad-apidoc#816]
안녕하세요 소재리포트 데이터를 추출하기 위해
네이버 검색광고 api 의 Stat: get (by ids) 를 호출하고 있습니다.
첨부 이미지에 보이는 "소재상세"  데이터 단위로 리포트 row를 추출하고 싶은데,
해당 데이터를 추출할 수 있는 기능을 제공하는지 질문드립니다.

제공한다면, 어디에서 관련 문서를 확인할 수 있는지 문의드립니다.
 
![image](https://github.com/naver/searchad-apidoc/assets/84096321/c0fac35f-2496-40ab-b429-b9dcf21488b3)

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 보고서 담당자입니다. 

문의 주신 내용에 대한 기술지원을 드릴수 있는 담당자가 현재 부재중으로 답변이 늦어지고 있습니다. 
죄송합니다. 담당자가 복귀 하는데로 답변을 드릴수 있도록 하겠습니다. 

감사합니다.

**Comment by jangyujin-hub** [comment]
네 알겠습니다 감사합니다

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

소제 상세 데이터를 얻기 위해서는 `breakdown=eventCode`
파라미터를 추가해 주시면 됩니다.
감사합니다.
