### ISSUE TITLE
네이버 검색광고 상의 기능인데

### ISSUE THREAD

**Issue by develop-kjy** [naver/searchad-apidoc#817]
https://github.com/naver/searchad-apidoc/assets/118158564/646117be-bb85-41ba-aa51-322462c63fa3

이 기능은 api상으로 힘든가요? 복사 자체 기능이없어서 get, create로만 하기에는 똑같이 만들어지진않아서요.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

광고그룹 복사기능은 API로 제공하지 않습니다.

감사합니다.
