### ISSUE TITLE
StatReport 조회 질문

### ISSUE THREAD

**Issue by jangyujin-hub** [naver/searchad-apidoc#819]
안녕하세요 소재 리포트 데이터를 추출하기 위해
네이버 검색광고 api 의 Stat: get (by ids) 를 호출하고 있습니다.
첨부 이미지에 보이는 "소재상세" 데이터 (홈링크, 메인텍스트 등) 단위로 리포트 row를 추출하고 싶은데,
해당 데이터를 추출할 수 있는 기능을 제공하는지 질문드립니다.

제공한다면, 어디에서 관련 문서를 확인할 수 있는지 문의드립니다.

![image](https://github.com/naver/searchad-apidoc/assets/84096321/4dffa028-75bf-4681-b7ae-a7c155568ef7)
![image](https://github.com/naver/searchad-apidoc/assets/84096321/cd19881f-fa69-4838-9b77-27cc69caa314)

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 API 입니다. 

https://github.com/naver/searchad-apidoc/issues/816
위의 이슈를 통해 질문 주신 내용과 같은 내용으로 생각 되는데요. 
혹 다른 내용인지 문의 드립니다. 

감사합니다.
