### ISSUE TITLE
About median bid estimate of searchad API

### ISSUE THREAD

**Issue by developerlicw** [naver/searchad-apidoc#82]
Hello,
I am trying to use estimate of bid recently. And I found that there are three kind of bids:
1. average position bid
2. median bid
3. exposure minimum bid

I think I can understand 1 and 3, 1 is the average bid price for the given position, and 3 is the minimum bid price for displaying my ad on search.

But what does 2 mean? 
Actually, I tried the API and found that the median bid sometimes is lower than the exposure minimum bid. So the minimum bid is not actually minimum?
Besides,  if the minimum bid mean that my ad will at least be displayed at the last  position, does it change everyday?

I can only find instruction documents here : 
http://naver.github.io/searchad-apidoc/#/operations/POST/~2Festimate~2Fmedian-bid~2F%7Btype%7D
Is there any other documents in detail? 

Please help me with this question, and thanks for all the help before and in the future.

**Comment by naver-searchad** [comment]
HI 

The "median bid" is the statistical median of bids for all ads that have been exposed in the past 28 days in a particular ad media (PC : https://search.naver.com/search.naver,
모바일 : https://m.search.naver.com/search.naver).

thanks

**Comment by developerlicw** [comment]
Hi naver-searchad
Thanks for the reply. So median is a statistical number of historical bids for the same keyword, so searchad API thinks the median bid of last 28 days should be the same with future 28 days, is it right?
Thanks.

**Comment by naver-searchad** [comment]
HI 

We do not guarantee that past data will represent the future. It is desirable to think that average position bid, median bid, and exposure minimum bid provide past data neutrally.
Because we can not predict the future precisely, we can make the data creation logic as open as possible so that users can use it to their strategy.

thanks

**Comment by developerlicw** [comment]
Hi naver-searchad
Thanks for the kind reply. I totally understand this. I will close this issue.
