### ISSUE TITLE
확장, 유사, 일치 검색에 대한 실적 레포트 다운로드 방법 문의

### ISSUE THREAD

**Issue by gimslab** [naver/searchad-apidoc#820]
안녕하세요.

현재 검색유형별 실적을 확인하기 위해 어드민 화면의 다차원보고서를 이용하고 있습니다.
API를 이용해서 레포트를 다운로드 받고 싶은데요.

가장 유사한 레포트가 "Powerlink Search Term Report (reportTp: EXPKEYWORD)" 인것 같습니다.
그런데 api document를 보면 
```
Search Keyword Type | int | 1: Keyword Plus, 2: Close Variant
```
라고 나와있습니다.

질문1: 일치검색의 경우는 이 레포트에 포함이 아예 안되는 걸까요?

질문2: 그리고 위 레포트에는 검색어 필드만 있고 해당하는 키워드 정보는 필드가 없는것 같습니다. 키워드별로 위와 같은 실적을 볼수 있는 방법이 있을까요?

답변 부탁드립니다. 감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 담당자입니다. 

1. 네 일치 검색은 해당 보고서에 제공되지 않습니다. 
2. 키워드 정보는 등록 키워드 ID를 이용하여 Ad Keyword Master (Keyword)에서 조회 하셔야 합니다. 
 마스터 기능에 대한 레퍼런스 : https://naver.github.io/searchad-apidoc/#/tags/MasterReport

대용량 보고서(stat report)에서는 광고 메타 정보를 별도로 제공하지 않으며 메타 정보는 별도로 마스터를 생성하여 다운로드 받은후 각 항목별 ID로 join 하셔야 합니다. 

일반적인 사용 방식은 아래 도움말을 참고하여 주시기 바랍니다. 
https://saedu.naver.com/help/faq/ncc/view.naver?faqSeq=178

감사합니다.

**Comment by gimslab** [comment]
빠른 답변 감사합니다.
추가로 한가지 궁금한건 키워드 메타를 마스터에서 찾으려면 키워드ID가 필요할것 같은데요. 키워드ID 필드는 없는것 같습니다.
그렇다면 현재는 방법이 없는걸까요?

**Comment by naver-searchad** [comment]
안녕하셔요. 대용량 다운로드 보고서 담당자입니다. 

죄송합니다. 제가 착각을 했습니다. 
현재 어떤 등록 키워드에서 어떤 검색어로 확장이 발생했는지에 대한 정보는 보고서에서 제공이 되지 않고 있습니다. 

감사합니다.

**Comment by SM10855** [comment]
안녕하세요,, 저도 질문 내용이 비슷하여 추가로 댓글 문의 드립니다.

그렇다면 EXPKEYWORD에는 확장과 유사 검색어만 제공하고, 일치검색어는 포함되지 않는 것으로 보면 되고,

일치 검색 데이터를 확인할 수 있는 보고서는  Ad Keyword Master (Keyword) 에서 볼 수 있다는 걸까요??

해당 마스터 보고서에서 키워드가 일치인지 아닌지에 대한 것을 알 수 있는 값이 있나요

감사합니다.

**Comment by naver-searchad** [comment]
@SM10855 님 
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

대용량 보고서 어디에서도 일치만을 볼수 있는 보고서는 존재하지 않습니다. 
이 정보는 제공을 하는 방안을 현재 검토 중에 있습니다. 

감사합니다.

**Comment by gimslab** [comment]
안녕하세요 자세한 답변 감사드립니다.
혹시 키워드, 검색유형별 실적 레포트 제공 방안도 검토하고 계신지 알 수 있을까요?
예를 들어 AD나 AD_DETAIL 레포트에 '검색유형' 필드가 추가되는 형태 같은것입니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

검색 유형 중 일치에 관한 보고서만 별도로 제공드리거나 혹은 일치를 제외한 모든 검색 유형이 검색어 보고서에 담기게 하여 
기존 AD나 AD_detail에서 이를 차감 하여 일치를 확인할수 있도록 하는 방안등을 고려하고 있습니다 .
AD나 AD_DETAIL 에 검색 유형 필드를 추가하는 안도 역시 고려중이긴 하나..이 논의가 시작된 것이 유사 검색어 론치 시점 전후라 (이 부분은 저희가 일치 지표에 대한 고민이 크게 부족했던 점입니다.죄송합니다. ) 아직 구체적인 방향성이 도출 되지는 않았습니다. 
혹 의견이 있으시다면 말씀 부탁드립니다. 

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다.

이전에 말씀드린것과 같이 검색어 보고서에 일치 항목이 추가되는 일정이 확정 되어 말씀드립니다.
2023년 11월 14일(2023년 11월 13일자 데이터)부터 반영으로 상세사항은 공지 게시판을 참고하여 주시기 바랍니다.
https://naver.github.io/searchad-apidoc/#/notice

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다.

이전에 말씀드린것과 같이 검색어 보고서에 일치 항목이 추가되는 일정이 확정 되어 말씀드립니다.
2023년 11월 14일(2023년 11월 13일자 데이터)부터 반영으로 상세사항은 공지 게시판을 참고하여 주시기 바랍니다.
https://naver.github.io/searchad-apidoc/#/notice

감사합니다.
