### ISSUE TITLE
공유예산 api 문의

### ISSUE THREAD

**Issue by SM11187** [naver/searchad-apidoc#821]
안녕하세요.

/ncc/shared-budgets get api 를 통해 
캠페인 공유예산/광고그룹 공유예산 그리고 각각 안에 등록한 캠페인과 광고그룹 리스트를 조회하려고 합니다.

![image](https://github.com/naver/searchad-apidoc/assets/94828850/87577815-a171-4240-9cae-80eefcf4efe1)

디버깅을 해봤을 때, 캠페인 공유예산/광고그룹 공유예산 목록은 잘 조회가 되는데 
그 안에 조회되어야 할 등록 캠페인과 광고그룹들이 조회가 되지 않습니다.

campaignList와 adGroupList에 포함되어있을거라고 생각했는데 null로 표현이 되고 있습니다.

GET /ncc/shared-budgets/{공유예산 ID}도 사용해봤으나 
원하는 campaignid, campaignName, adgroupid, adgroupName 과 같은 정보를 확인할 수 없었는데요
어떻게하면 위의 정보들을 가져올 수 있는지 문의드립니다.

감사합니다!

**Comment by naver-searchad** [comment]
안녕하세요. 네이버 검색광고 API입니다

GET /ncc/shared-budgets 또는 GET /ncc/shared-budgets/{공유예산 ID} 를 통해 공유예산을 조회할 경우 각각 List\<SharedBudgetResponse> 와 SharedBudgetResponse를 반환하는데 campaignList와 adgroupList는 포함되어 있지 않습니다.

SharedBudgetResponse
```
{
  sharedBudgetId: string              // 공유예산 Id
  customerId: Long	              // 광고주 번호
  name: String                        // 공유예산 이름
  ownerType: SharedBudgetOwnerType    // 공유예산 종류 'Campaign', 'Adgroup'
  deliveryMethod: DeliveryMethodType  // 노출 방식 'Accelerated', 'Standard'
  dailyBudget: Long                   // 하루 예산
  budgetLock: Boolean                 // 노출 잠김 여부
  regTm: Date                         // 등록 시각
  editTm: Date                        // 수정 시각
  status: Status                      // 상태
  statusReason: StatusReason          // 상태 이유
  numberInUse: Int                    // 연결된 캠페인/광고그룹 수
}
```

공유예산에 포함된 캠페인 또는 광고그룹 정보를 얻기 위해서는 
캠페인: GET /ncc/campaigns/shared-budgets/{공유예산 ID} 
광고그룹: GET /ncc/adgroups/shared-budgets/{공유예산 ID} 를 활용해주시기 바랍니다.

자세한 내용은 [릴리즈노트](http://naver.github.io/searchad-apidoc/#/release-notes)의 공유예산 부분을 참고하여 주시기 바랍니다.
감사합니다.
