### ISSUE TITLE
matchtype 관련 문의

### ISSUE THREAD

**Issue by 10754** [naver/searchad-apidoc#823]
키워드 매치방식에 대해 자동추적 URL 파라미터를 제공할 계획이 있는지 문의 드립니다.
현재 자동 파라미터 값을 제공하지 않기 때문에 키워드 마다 직접 파라미터값을 추가를 해야 하는데
자동으로 제공할 계획이 없다면 대량으로 추가 가능한 부분이 있을지 문의 드립니다.
단순 파라미터값을 URL에 직접 추가 해야 하는데 그렇게 되면 키워드 검수가 들어가 광고 노출이 되지 않기에 문의 드립니다.
![image](https://github.com/naver/searchad-apidoc/assets/141803485/d9920611-675e-4410-b903-8c0b416690a1)

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API 담당자입니다. 

답변이 늦어 죄송합니다. 
이공간은 검색광고 API 관련 기술지원 및 기술 문의를 주시는 공간으로 추적 URL  관련 사항은 고객센터로 문의를 주시는 편이 더 빠른 답변을 받으실수 있습니다. 
문의 주신 건의 경우 해당 기능 담당자에게 전달 되었으며 
관련하여 추적 URL 기능 변경이 진행될 예정입니다. 
상세한 공지는 내일 검색광고홈페이지(https://searchad.naver.com/) 공지 게시판에 내일(8/18) 게시될 예정이오니 참고 부탁드립니다.

감사합니다.

**Comment by naver-searchad** [comment]
@10754
안녕하십니까 검색광고 API 담당자입니다. 

앞선 코멘트에서 말씀 드린 공지는 오늘 17시~18시 사이에 게시될 예정입니다. 
계속 기다리실것이 우려되어 말씀드립니다. 

감사합니다.
