### ISSUE TITLE
managedKeyword 슬롯수 제공 관련

### ISSUE THREAD

**Issue by kaorimikage** [naver/searchad-apidoc#824]
https://saedu.naver.com/notice/view.naver?notiSeq=4139&catg=&fixYn=N&searchOpt=all&keyword=

네이버 광고계정에서 이제 노출가능 광고개수(PC)제공하지 않는다는 공지를 보았습니다.
그럼 managedKeyword API에서 제공하던 슬롯수도 제공하지 않게 되는 것인지 알고 싶습니다.

**Comment by naver-searchad** [comment]
안녕하세요. 네이버 검색광고 API입니다.

네 맞습니다.
2023-08-30 (수) 반영 이후
managedKeyword API에서도 노출가능 광고개수(PC)(PCPLMaxDepth) 은 제공되지 않습니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 API 담당자입니다. 

이전 드린 답변에서 잘못된 부분이 있어 수정하여 답변드립니다. 
해당 공지에서 23/8/30에 데이터 제공이 중단되는 곳은 광고 관리시스템( UI)이며, 
API서비스에서는 23년 9월 13일 오후 5시 이후 제공이 중단됩니다. 

상세한 사항은 관련 공지를 참고 부탁드립니다. 
https://naver.github.io/searchad-apidoc/#/notice

감사합니다.
