### ISSUE TITLE
광고매체마스터 정보 변경(추가/수정/삭제) 여부 문의

### ISSUE THREAD

**Issue by yuhee62wang** [naver/searchad-apidoc#825]
안녕하세요 ~

'**광고매체 마스터**' 정보는 변경(추가/수정/삭제)이 되는 정보인가요?
네이버의 모든 블로그에 대한 ID 같은 개념이라면 블로그가 새로 추가되면 계속 이 'media   583163'   , 'media   583164' 가 늘어나나요?
추가나 수정, 삭제 등이 일어나는 지에 따라 갱신 주기를 정하려고 합니다. 

광고매체 마스터 (예시)
 
Text
media   583163  놀고 먹는 일상    http://blog.naver.com/phj2757330    true    false   true    true    false   true    1   2023-08-07T02:32:12.000Z    

media   583164  하루하루 소중한,   http://blog.naver.com/uuuudy    true    false   true    true    false   true    1   2023-08-07T02:32:14.000Z    

media   583165  일상 기록   http://blog.naver.com/dayuntoday    true    false   true    true    false   true    1   2023-08-07T02:32:15.000Z

바쁘실테지만 답글 부탁드립니다 ! 
감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

제가 어제 답변을 적어 두고 comment 버튼을 누르지 않았네요. 답변이 늦어져서 죄송합니다. 

1. MEDIA ID는 재활용하지 않는 것이 원칙입니다. 단, 매체의 통합등의 아주 특별한 이벤트가 있을떄 재활용 될수 있으며 이런 경우 별도 공지를 드리고 있습니다. 
2. 매체 추가 : 상시적으로 발생합니다. 
3. 매체 정보 수정 : 매체 명등은 수정 될수 있습니다. 단 주요 매체들의 매체명 수정은 별도 공지를 드리고 있으며 대체로 매체명 수정은 블로그에서 발생할수 있습니다. 또한 매체 특성(검색매체 등) 역시 변경 될수 있으나 극히 드물게 발생합니다. 
4. 매체 삭제 : 수시로 발생합니다. 

업데이트 주기를 잡으신다면 통상 일 1회 정도면 정보 누락이 없이 업데이트가 가능하실 것으로 생각됩니다. 
업데이트 시점은 대용량 보고서를 다운받으시는 새벽 6시~오전 9시 사이(한국시간) 정도가 적절할 것으로 생각 됩니다. 
삭제된 매체의 정보는 변경분( 마스터 생성 요청시 fromTime 설정, fromTime부터 현재까지 삭제/변경된 매체정보가 제공됨)기능을 이용하시면 확인하실수 있습니다. 

감사합니다.
