### ISSUE TITLE
마스터 리포트 ShoppingProduct 유형 다운로드 시 Product ID Of Mall 필드 공백 문의

### ISSUE THREAD

**Issue by mkms1104** [naver/searchad-apidoc#826]
안녕하세요!

마스터 리포트 ShoppingProduct 유형 다운로드 시 Product ID Of Mall 필드 값에 공백이 발생하여 문의드립니다.

해당 케이스는 현재 불규칙한 시점에 발생하는 것으로 파악됩니다.

예를 들면, 오전 9시 30분 경에 해당 리포트를 요청하는 경우 특정 행의 Product ID Of Mall 필드 값이 공백으로 표시되나,
오전 9시 40분 경에 동일한 리포트를 다시 요청하는 경우 Product ID Of Mall 필드 값이 정상 표기되는 차이가 발생하고 있습니다.
(위에서 작성한 시간은 임의의 시간입니다.)

해당 문제가 발생하는 원인을 알수있을까요?

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 보고서 담당자입니다. 

상품 정보는 네이버 쇼핑서비스로 부터 인터페이싱 되는 정보를 이용해 구성이 되고 있어 이 정보의 업데이트 주기와 관련된 사항으로 추정됩니다만 정확한 상황 확인을 위해 담당자에게 문의를 한 상태입니다. 몇개 부서를 거쳐서 확인이 진행되는 상황이라 조금 시간 걸릴것으로 예상되어 중간 답변 드립니다. 아마도 차주 월요일~화요일 정도 최종 확인이 가능할것으로 예상됩니다. 양해 부탁드립니다. 

감사합니다.

**Comment by mkms1104** [comment]
네 알겠습니다.
차주 답변 기다리겠습니다.

감사합니다

**Comment by mkms1104** [comment]
안녕하세요! 혹시 해당 문의 아직 처리중이실까요!?

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 보고서 담당자입니다.

답변이 늦어 죄송합니다. 아직 확인중입니다. 
혹 해당 현상이 발생한 일시와 네이버쇼핑 상품 아이디를 한개 정도 알려 주실수 있으실까요?

감사합니다.

**Comment by mkms1104** [comment]
발생 당시 로그로 따로 기록해놓지 않아서 명확한 발생 시간과 상품 아이디는 없습니다.
당시 대략적인 발생 시간과 cusotmer_id 정도는 전달드릴 수 있을 듯 합니다.

2023.07.20. 09:04:34 경에 다운로드 받은 리포트에 몰ID/상품명/카테고리 정보 **없음**
2023.07.20. 09:12:05 경에 다운로드 받은 리포트에 몰ID/상품명/카테고리 정보 **있음**

cusotmer_id  : 939281, 1248147, 1248148, 1285466, 1285474

그리고 해당 버그는 대략 7월 20일부터 최근까지 3~4번 정도 발생했습니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 보고서 담당자입니다.

자료 감사드립니다. 
커스터머 아이디는 제가 확인후 적어주신 코멘트에서 삭제하셨습니다. 
본래는 단순히 업데이트 시차 정도의 문제로 생각되었으나 담당자분들께 확인해 본 결과 시차 정도로 발생할수 있는 문제는 아닌것으로 확인되어 심층적인 조사를 진행중입니다. 

현재까지 확인/진행된 사항은 아래와 같습니다. 
1. 동일 네이버 쇼핑아이디 (Product ID) 내에서 존재하던 특정 정보 특히 상품몰ID 가 없어지는 것은 정상적인 작동 상황은 아님 
2. 원인은 여러가지가 있을수 있어 모든 케이스에 대한조사를 진행중 

한가지 크게 어려움이 있는 부분은 원본 데이터의 경우 저희가 최종 데이터만 보관하고 있어 쇼핑과 연계하여 전수조사를 통해 동일한 현상이 있는지 여부를 체크해야 한다는 점인데요. 워낙 양이 많아서 시간이 예상보다 많이 소요 되고 있습니다. 
양해를 부탁드리며 확인이 되는 데로 바로 답변 드리도록 하겠습니다. 

감사합니다.

**Comment by mkms1104** [comment]
네! 진행상황 공유 감사드리며, 답변 천천히 기다리고 있겠습니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

결론만 우선 말씀드리면 마스터 파일을 생성할때 발생하는 문제였고, 이 문제를 현재는 해결할 방법이 없는 상황입니다. 

쇼핑 상품 마스터는 쇼핑에서 제공한 상품 정보와 저희 광고 정보를 모두 이용하는데 쇼핑 정보를 읽어 오는 시점과 업데이트나 대량 처리등 쇼핑 정보 대량 작업이 발생하는 시점이 우연히 겹치면 데이터를 읽어 오는데 실패하는 것이 원인인데요. 
쇼핑 정보는 불규칙하게 업데이트되며, 또한 광고 노출량 역시 불규칙하여 이 현상은 특정한 패턴없이 발생하게 됩니다. 

현재로서는 가용량을 늘리는 등의 작업으로는 이를 해결할수 없어, 구조 자체를 완전히 변경하거나 서비스 방식 자체를 변경 하는 등의 수단을 고려해야 합니다만 해당 정보는 광고 집행 및 노출에서도 사용되고 있는 정보로 해결 방안을 찾기가 쉽지 않습니다. 

대단히 죄송합니다만 쇼핑몰아이디, 카테고리, 상품명등 필수적인 상품정보에 빈값이 있을 경우 다시 마스터를 생성하는 형태로 로직을 구성해 주시기를 부탁드립니다.

쇼핑 상품 마스터에서 null 혹은 빈값이 들어갈수 있는 항목은 아래와 같습니다.

카테고리중 하위 카테고리 일부--> 카테고리 아이디는 있는데 이름은 없다거나 반대의 경우는 존재할수 없습니다. 하위 카테고리는 있는데 상위 카테고리가 없거나 카테고리 1이 없는 경우도 존재하지 않습니다. 
PC/모바일 가격-->둘중 하나는 있어야 합니다.
PC/모바일 랜딩 URL-->둘중 하나는 있어야 합니다.
Delivery Fee 입니다. 

감사합니다.

**Comment by mkms1104** [comment]
답변 감사드립니다.

제안주신 아키텍처로 구성해서 사용하도록 하겠습니다.

추가적으로 쇼핑 상품 마스터 변경분 리포트에 대해서도 위의 문제는 동일하게 발생하는 걸까요?

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 보고서 담당자입니다. 

네 변경분에서도 동일한 현상이 발생할수 있습니다. 물론 변경분의 경우는 확률적으로 발생 가능성이 많이 낮습니다. 

감사합니다.

**Comment by mkms1104** [comment]
네 감사합니다.

**Comment by mkms1104** [comment]
@naver-searchad 
안녕하세요!

이전에 전달주신대로 필수 값이 존재하지 않을 경우 재시도를 통해 리포트를 다운로드 받고 있는데

현재 대략 07시부터 지속적으로 다운로드를 받아도 Product ID Of Mall 필드에 공백이 발생하고 있어서 문의드립니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

불편 드려 죄송합니다. 담당 개발부서에 확인 요청을 드리도록 하겠습니다. 
단, 현재 대부분의 담당자들이 출근전이라.(저희의 통상적인 근무 시작 시간은 10시입니다.) 조금 시간이 걸릴수도 있는점 
양해 부탁드립니다.

감사합니다.

**Comment by mkms1104** [comment]
네 알겠습니다!

**Comment by mkms1104** [comment]
@naver-searchad 
혹시 간략한 진행 상황 공유 해주실수 있으실까요??

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

전일 15시부터 등록된 신규 상품들에 대한 정보는 모두 불러 오지 못하고 있는 상황입니다. 
현재 복구에는 상당한 시간이 소요될것으로 보이며 하루 이상이 소요될 가능성도 있어 보입니다. 

죄송합니다.

**Comment by mkms1104** [comment]
네 알겠습니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다.

북구 완료 예상 시점은 23년 9월 14일 20시 입니다. 

불편드려 죄송합니다.

**Comment by mkms1104** [comment]
@naver-searchad 
안녕하세요!

현재 보고서 다운로드 받은 결과 여전히 몇몇 데이터에 공백이 발생하고 있어 재문의 드립니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다.

어제 복구 작업중에 누락된 상품들이 발견되어 추가 작업 진행 중입니다. 
완료 되면 다시 말씀 드리겠습니다. 

불편드려 대단히 죄송합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다.

작업이 완료 되었는데요. 재시도를 한번 해봐 주실수 있으실까요?

감사합니다.

**Comment by mkms1104** [comment]
네 정상 리포트 확인하였습니다.
감사합니다.

**Comment by mkms1104** [comment]
@naver-searchad 
안녕하세요.
금일도 재시도를 통해 마스터 리포트를 요청중이나 이전과 동일하게 공백 필드가 발생하고 있습니다.
확인 부탁드립니다!

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

보고서 잡아이디와 NVMID 몇개를 알려 주실수 있으실까요?

감사합니다.

**Comment by mkms1104** [comment]
보고서 ID : 5E31069FF71E85F2E91AE7FE13E2E02C
CUSTOMER ID = 939281 

전달드립니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

혹 삭제 안된 보고서의 잡 아이디를 알려주실수는 있으실까요?

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다.

현재 해당 문제는 오늘13시 30분 현재 해결하여 현재는 정상서비스 중입니다. 
이 문제의 원인은 네이버 쇼핑-네이버 검색광고간의 데이터 동기화 관련 정책 변화로 인한 것인데요. 
따라서 향후에도 동일한 문제가 계속 발생할수 있으므로 해결을 위한 마스터 기능 변화에 대해 빠른 시일내에 공지를 드리도록 하겠습니다. 
불편을 드려 대단히 죄송합니다. 

감사합니다.

**Comment by mkms1104** [comment]
네 알겠습니다.
답변 감사드립니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다.

데이터 누락 관련하여 몇가지 조치 방안이 도출되어 다행히 스팩/기능 변경 없이, 사용자 분들에게 전혀 영향을 주지 않고도 이전과 같은 서비스 수준을 유지할수 있을것으로 생각됩니다. 
관련된 패치는 금일 반영 예정이고, 사용상의 차이점은 전혀 없으나 예전보다 약간 더 보고서 생성에 시간이 아주 조금 더 소요되는 정도(약 수초 정도)의 변화만 있을 것으로 보입니다.  따라서 기능 변경이나 관련 공지는 게시 되지 않습니다. 참고 부탁드립니다. 

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

앞서 말씀드릴때는 관련 공지는 없다고 말씀드렸는데요. 데이터 누락과 관련된 패치를 진행하던 중에 데이터 누락과는 무관하게 꽤 예전부터 있던 버그를 발견하여 이를 수정하였고 공지를 게시하게 되었습니다. 혼란을 드릴까 우려되어 코멘트 남깁니다. 
https://naver.github.io/searchad-apidoc/#/notice

감사합니

**Comment by mkms1104** [comment]
@naver-searchad 
네 상세한 답변 감사드립니다.
업무에 참고하도록 하겠습니다
