### ISSUE TITLE
공유예산 API 오류 원인 

### ISSUE THREAD

**Issue by SM11187** [naver/searchad-apidoc#828]
안녕하세요

POST /ncc/shared-budgets API 사용하려고 테스트중에 있는데요,
API 전송 시,
[400]공유예산의 값이 잘못 설정 되었습니다., 공유예산을 등록할 수 없는 캠페인 유형입니다., X-Transaction-ID: f66dfdc5dae3cd96, {"status":"400","title":"공유예산의 값이 잘못 설정 되었습니다.","detail":"공유예산을 등록할 수 없는 캠페인 유형입니다.","transactionId":"f66dfdc5dae3cd96","code":"7402"}

라는 오류가 뜨고 있습니다.

![image](https://github.com/naver/searchad-apidoc/assets/94828850/c794c328-0352-45d3-8fb6-1be104ec51dd)
파라미터는 위와 같이 보내고 있습니다.

그리고 추가하려는 캠페인이 네이버 광고센터에서 직접 공유예산에 추가되는 캠페인임을 확인했습니다.

오류 원인 확인 부탁드리겠습니다.
감사합니다!

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API 입니다.

공유예산 생성 API 요청시 Request body의 campaignList 에는 SharedBudgetRequest 정보가 아닌 CampaignRequest 정보가 포함되어야 합니다.

```
SharedBudgetRequest
{
  sharedBudgetId: string              // 공유예산 Id
  customerId: Long	              // 광고주 번호
  name: String                        // 공유예산 이름
  ownerType: SharedBudgetOwnerType    // 공유예산 종류 'Campaign', 'Adgroup'
  deliveryMethod: DeliveryMethodType  // 노출 방식 'Accelerated', 'Standard'
  dailyBudget: Long                   // 하루 예산
  budgetLock: Boolean                 // 노출 잠김 여부
  regTm: Date                         // 등록 시각
  editTm: Date                        // 수정 시각
  numberInUse: Int                    // 연결된 캠페인/광고그룹 수
  campaignList: List<CampaignRequest> // 연결될 캠페인 
  adgroupList: List<<AdgroupRequest>  // 연결될 광고그룹
}
```
https://naver.github.io/searchad-apidoc/#/release-notes:~:text=%EC%83%88%EB%A1%9C%EC%9A%B4%20%EA%B4%91%EA%B3%A0%20%EA%B0%9D%EC%B2%B4(%EA%B3%B5%EC%9C%A0%EC%98%88%EC%82%B0)%EA%B0%80%20%EC%B6%94%EA%B0%80%EB%90%A9%EB%8B%88%EB%8B%A4. 참고 바랍니다.
CampaignRequest 정보에 nccCampaignId, name, campaignTp 이 정확히 기재되었는지 확인 부탁드립니다.

감사합니다.
