### ISSUE TITLE
/ncc/managedKeyword 의 PCPLMaxDepth 결과관련

### ISSUE THREAD

**Issue by kaorimikage** [naver/searchad-apidoc#829]
앞으로 PCPLMaxDepth 값은 제공하지 않는다고 들었습니다.

https://saedu.naver.com/notice/view.naver?notiSeq=4139&catg=&fixYn=N&searchOpt=all&keyword=
공지에서는 파워링크 PC는 15개, 파워링크 MO는 4개로 고정되어 노출된다고 되어 있습니다.

그런데 현재 PCPLMaxDepth 값이 7로 제공되고 있으며 실제 www.naver.com 에도 광고가 7개만 노출이 되고 있습니다. 앞으로 기본 슬롯수가 7로 제공되는것인지요?

**Comment by kaorimikage** [comment]
14시부터 검색결과가 10개, 15개 정상으로 나오는데 API는 여전히 7개만 나오고 있습니다.

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

광고 시스템과 API 서비스에서의 서비스 종료 시점이 서로 다릅니다. 
API에서는 아래 공지와 같이 2023년 9월 13일 오후 5시 00분까지 데이터가 제공됩니다. 
https://naver.github.io/searchad-apidoc/#/notice
------------------------------------------------------------------------------------------
[2023-08-14] ManagedKeyword 기능 변경 안내
안녕하십니까 네이버 검색광고 API입니다.

ManagedKeyword의 일부 데이터 제공이 종료 되어 공지드립니다.
관련 공지 : https://saedu.naver.com/notice/view.naver?notiSeq=4139

대상 기능 및 항목
ManagedKeyword(https://naver.github.io/searchad-apidoc/#/tags/ManagedKeyword) 의 PCPLMaxDepth

변경 일시(모든 일시 KST기준)
2023년 9월 13일 오후 5시 00분

변경 내역
변경 시점 이후 PCPLMaxDepth 필드가 제거 되며 더이상 제공되지 않습니다.

업무에 참고 부탁드립니다.

감사합니다.

**Comment by kaorimikage** [comment]
현재 PCPLMaxDepth 값이 7로 제공되고 있는 것은 정상인 것인가요?

**Comment by naver-searchad** [comment]
안녕하세요. 검색광고 API입니다.

공지사항 내용과 같이 실제 검색 결과와 PCPLMaxDepth  값이 정확히 일치 되지 않는 경우가 발생할 수 있습니다. 
현재 키워드에 따라 PCPLMaxDepth 값은  7이 나올 수 있습니다.

감사합니다.
