### ISSUE TITLE
Adgroup 를 이용 ad 정보 가져오기 질문

### ISSUE THREAD

**Issue by yoosangchul** [naver/searchad-apidoc#83]
$adgrouplist = $api->GET('/ncc/adgroups');
사용하여 정보를 가져온후
Array
--
  | (
  | [nccAdgroupId] => grp-a001-02-000000004359012
  | [customerId] => 1179027
  | [nccCampaignId] => cmp-a001-02-000000000744127
  | [mobileChannelId] => bsn-a001-00-000000000306303
  | [pcChannelId] => bsn-a001-00-000000000306303
  | [bidAmt] => 300
  | [name] => 친환경 폼롤러 33CM
  | [userLock] =>
  | [useDailyBudget] =>
  | [useKeywordPlus] =>
  | [keywordPlusWeight] => 100
  | [contentsNetworkBidAmt] => 70
  | [useCntsNetworkBidAmt] =>
  | [mobileNetworkBidWeight] => 100
  | [pcNetworkBidWeight] => 100
  | [dailyBudget] => 0
  | [budgetLock] =>
  | [delFlag] =>
  | [regTm] => 2017-09-08T04:19:47.000Z
  | [editTm] => 2017-09-26T09:07:31.000Z
  | [targetSummary] => Array
  | (
  | [week] => all
  | [pcMobile] => partially
  | [media] => partially
  | [time] => all
  | )
  |  
  | [pcChannelKey] => http://storefarm.naver.com/wkqwkq
  | [mobileChannelKey] => http://storefarm.naver.com/wkqwkq
  | [status] => ELIGIBLE
  | [statusReason] => ELIGIBLE
  | [expectCost] => 55
  | [migType] => 0
  | [adgroupAttrJson] => Array
  | (
  | [campaignTp] => 2
  | )
  |  
  | )
nccAdgroupId 정보를 획득후
GET /ncc/ads{?nccAdgroupId} 사용해서 데이터를 가져오려고 합니다.
$sc = $api->GET('/ncc/ads?nccAdgroupId=grp-a001-02-000000004359012');

Array
--
  | (
  | [signature] => er95QIJQXQk7q01OBVSfOlXaERWHsp7oFbxrUd7dZXw=
  | [status] => 403
  | [title] => Invalid Signature
  | [detail] => Signature 'er95QIJQXQk7q01OBVSfOlXaERWHsp7oFbxrUd7dZXw=' is invalid.
  | [type] => urn:naver:api:problem:invalid-signature
  | )
이러한 권한 내용을 가져오는데 제가 여러모로 잘 모르고 api 란건 이번에 처음 써봐서요 
이렇게 하는게 아닌가요??
궁극적으로는 광고소재(nad-XXX-XX-XXXXXX)에 대한 노출수/클릭수/클릭율등 정보를 알고 싶습니다

**Comment by naver-searchad** [comment]
안녕하세요. 네이버 검색광고 API입니다.

광고 소재에 대한 노출수, 클릭수 지표 등을 조회하려면 ```/stats```, ```/stat-reports``` API를 이용하실수 있습니다.

## /stats
* 특정 엔티티 ID(소재 ID, 광고그룹ID 등), 특정 조회기간에 대한 노출수, 클릭수, 광고비 통계지표 조회
  + http://naver.github.io/searchad-apidoc/#/tags/Stat
  + 요청 샘플 코드 https://github.com/naver/searchad-apidoc/blob/master/java-sample/src/main/java/com/naver/searchad/api/rest/Stats.java

## /stat-reports
* 대용량 다운로드 보고서
* 요청하고자하는 필드를 포함한 pre-defined된 특정 일자의 전체 데이터를 파일로 다운로드 가능
  + http://naver.github.io/searchad-apidoc/#/tags/StatReport
  + 요청 샘플 코드 https://github.com/naver/searchad-apidoc/blob/master/java-sample/src/main/java/com/naver/searchad/api/rest/StatReports.java

**Comment by yoosangchul** [comment]
$stat_req = array(
    "id" => $reportType,
    "fields" =>  ["impCnt","clkCnt","ctr","cpc","avgRnk","ccnt","recentAvgRnk","recentAvgCpc"],
    "timeRange" => array("since"=>"2018-01-20","until"=>"2018-01-22"),
    "datePreset" => 'last7days',
    "timeIncrement" => "allDays",
    "breakdown" => "dayw"
);
$response = $api->get("/stats",$stat_req);
[message] => 잘못된 파라미터 형식입니다. 라고 피드백 나옵니다 파라미터 잘못된 부분이 있을까요?:

**Comment by naver-searchad** [comment]
안녕하세요. 네이버 검색광고 API입니다.

http://naver.github.io/searchad-apidoc/#/operations/GET/~2Fstats%7B%3Fid,fields,timeRange,datePreset,timeIncrement,breakdown%7D

위와 같이 fiends 와 timeRange 는 object나 array 형태가 아닌 string 형태로 넣어주셔야 합니다.

해당 파라미터를 string 으로 입력 부탁 드립니다.

감사합니다.
