### ISSUE TITLE
PUT /ncc/campaigns/{?fields}  API 사용 예시

### ISSUE THREAD

**Issue by SM11187** [naver/searchad-apidoc#832]
PUT /ncc/campaigns/{?fields} 사용하려는 도중 오류가나서 API의 사용예시 (파라미터 필수값 포함) 부탁드리겠습니다.

마찬가지로 POST /ncc/shared-budgets API 사용 예시 (파라미터 필수값 포함)도 부탁드리겠습니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

정확한 요청 데이터와 오류코드를 알아야 원인을 확인할 수 있습니다.
필수값이 모두 있더라도, 데이터의 정합성 문제로 오류가 발생할수 있습니다.

감사합니다.

**Comment by SM11187** [comment]
> 안녕하세요? 네이버 검색광고 API입니다.
> 
> 정확한 요청 데이터와 오류코드를 알아야 원인을 확인할 수 있습니다. 필수값이 모두 있더라도, 데이터의 정합성 문제로 오류가 발생할수 있습니다.
> 
> 감사합니다.


![image](https://github.com/naver/searchad-apidoc/assets/94828850/d704af8e-cb52-4ea3-a2da-912e9686194a)

파라미터 값을 담아
String requestURI = "/ncc/campaigns/?fields=sharedBudget";

이렇게 호출하였습니다.

오류는
 [500]Cannot handle the request., X-Transaction-ID: 79c1b89f27bf7827, {"status":"500","title":"Cannot handle the request.","transactionId":"79c1b89f27bf7827","code":"1005"}

위와 같이 나고 있는 상태입니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.
customerId가 입력에 누락된 것으로 보입니다.

감사합니다.

**Comment by SM11187** [comment]
> 안녕하세요? 네이버 검색광고 API입니다. customerId가 입력에 누락된 것으로 보입니다.
> 
> 감사합니다.

> 안녕하세요? 네이버 검색광고 API입니다. customerId가 입력에 누락된 것으로 보입니다.
> 
> 감사합니다.


감사합니다.

덕분에 해결되었습니다.

하나 더 해결하지 못한게 있는데요,

이슈 #830번 확인 부탁드리겠습니다... !

**Comment by SM11187** [comment]
안녕하세요
하나 더 궁금한 점이 생겨 댓글 남깁니다.

![image](https://github.com/naver/searchad-apidoc/assets/94828850/e6620dcb-0990-41fc-99e6-1d7ef9402647)

위와 같이 같은 공유예산에 다른 캠페인을 넣고 동일한 하루예산을 설정했을 때,
캠페인이 2개가 모두 등록되는게 아닌 한개만 등록되고 있습니다.

하루예산을 다르게 바꾸면 그제서야 두 개가 추가되는데요,
동일한 하루예산으로 여러 캠페인 추가는 불가능한지 문의드립니다.

감사합니다!
