### ISSUE TITLE
API 호출 속도 제한 문의

### ISSUE THREAD

**Issue by zxxsol** [naver/searchad-apidoc#833]
안녕하세요. RelKwdStat API 호출 시, API 요청 횟수 제한은 없는 것을 확인하였습니다. 
( 관련 API 문서 : https://naver.github.io/searchad-apidoc/#/operations/GET/~2Fkeywordstool)

다만 API 호출 속도 제한은 있으며, 특정 숫자가 정해진 것은 아니고 초 단위 이하에서 측정한다고 하는데요.
API 호출 속도 제한의 특정값은 따로 없을까요? 

호출 평균값은 1초당 15~20회으로 알고 있습니다. 

( 관련 FAQ 문서: https://github.com/naver/searchad-apidoc/wiki/FAQ)

**Comment by naver-searchad** [comment]
안녕하셔요 검색광고 API입니다. 

네 호출 평균 값은 알고 계신바와 같이 15~20회정도 입니다. 
특정 값으로 셋팅 하시는 것보다는 호출 속도가 빠르다 (too many request)가 리턴되면 sleep을 짧게 주셨다가 다시 호출 해보시고 다시 속도 에러가 리턴되면 이전 보다  조금더 길게 sleep을 주시는 방식으로 로직을 구성하시면 해당 시점의 최대 속도에 가까운 속도로 호출이 가능합니다. 
빠른 속도가 불필요하시다면 sleep을 1초 정도 주시면 되겠습니다. 

감사합니다.
