### ISSUE TITLE
POST /ncc/shared-budgets API 오류 원인 재질문

### ISSUE THREAD

**Issue by SM11187** [naver/searchad-apidoc#834]
안녕하세요.
답변이 없으셔서 재질문드립니다.

POST "/ncc/shared-budgets" 호출 시
![image](https://github.com/naver/searchad-apidoc/assets/94828850/6401618c-d7fe-49c6-b6cc-b461682c8891)

위와 같이 파라미터를 담아서 보내는데요,

![image](https://github.com/naver/searchad-apidoc/assets/94828850/90030ef3-5a73-4962-92bb-0ced4e16a8aa)

해당 오류를 뱉어냅니다.

원인 무엇인지 확인 부탁드리겠습니다.

**Comment by naver-searchad** [comment]
안녕하세요? 검색광고 API입니다.

위 오류는 공유예산 생성 시 타입과 타입에 맞는 광고그룹/캠페인이 없어서 발생한 오류로 보입니다. 공유예산 생성 시 공유예산 타입(캠페인 공유예산 또는 광고그룹 공유예산)을 설정해주시고 타입에 맞는 캠페인 또는 광고그룹을 한개 이상 넣어주셔야 합니다. 

감사합니다.

**Comment by SM11187** [comment]
![image](https://github.com/naver/searchad-apidoc/assets/94828850/c2e71813-78bc-4ad4-a56b-266f9e05afa6)

이렇게 값을 넣었음에도 

Exception in thread "main" com.nsmcorp.apigateway.exception.SearchAdAPIException: [400]Invalid value in the daily shared budget field of campaign., X-Transaction-ID: 9540f25039f2f3f1, {"status":"400","title":"Invalid value in the daily shared budget field of campaign.","transactionId":"9540f25039f2f3f1","code":"3507"}

오류를 뱉어냅니다...

**Comment by naver-searchad** [comment]
안녕하세요? 검색광고 API입니다.

공유예산에 추가할 캠페인에 customerId가 빠진 것으로 확인됩니다.

감사합니다.

**Comment by SM11187** [comment]
아 드디어....됐네요...... 감사합니다ㅠㅠㅠ
