### ISSUE TITLE
매체 이름 조회 문의

### ISSUE THREAD

**Issue by mkms1104** [naver/searchad-apidoc#835]
안녕하세요.

현재 네이버 광고 API가 제공하는 기능을 통해 매체 이름 (Media name) 값을 얻기 위해서는

매체 마스터 리포트를 조회하는 방법 외에는 존재하지 않는게 맞을까요?

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

네. 말씀대로 API 서비스 내에서는 마스터의 매체 마스터를 사용하시는 방법만이 존재합니다. 
광고 시스템 UI 내에서는 광고 그룹 설정 내에 조회 시점 현재 기준 매체리스트 파일을 다운로드 하는 링크(버튼)이 제공됩니다.

감사합니다.

**Comment by mkms1104** [comment]
네 답변 감사드립니다
