### ISSUE TITLE
500 internal Server error

### ISSUE THREAD

**Issue by miinye** [naver/searchad-apidoc#837]
navar stat (20230910) 호출시 

재시도 처리를 하고 있으나 500 error가 빈번하게 발생하여 서버에 이슈가 있는지 문의드립니다.

java.lang.Exception: 500 Internal Server Error. X-Transaction-ID: null, Response Body: {"code":500,"message":"Internal Server Error"}

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 보고서 담당자입니다. 

9월 10일자 지표에 오류가 있었던것이 확인되어 복구 작업이 진행 중인데요. 
오류가 발생한 원인과 연관이 있었던 현상일수도 있을것 같습니다. 
STAT의경우 18시 현재 복구가 완료 되었으므로 해당 현상이 지속되면 다시 한번 말씀 부탁드립니다. 

불편드려 대단히 죄송합니다.
