### ISSUE TITLE
광고주센터 보고서 메뉴 항목 별 데이터 차이 문의

### ISSUE THREAD

**Issue by mkms1104** [naver/searchad-apidoc#838]
안녕하세요.

1. 보고서 > 다차원 보고서
![image](https://github.com/naver/searchad-apidoc/assets/19260410/fb93f0de-50ef-4612-8639-415eff2f43b3)

2. 보고서 > 대용량 다운로드 보고서 >대용량 보고서 다운로드
![image](https://github.com/naver/searchad-apidoc/assets/19260410/9db5ce0b-7511-4e65-ba6f-4fb9a787b896)

두 메뉴 각각에서 다운로드한 광고 성과 항목 중 노출, 클릭, 광고비 등의 데이터가 일치하지 않아서 문의드립니다.
customer_id, 광고 id와 무관하게 발생하고 있으며, 그 중 샘플로 1개 전달드립니다.

ad_id : nad-a001-02-000000262547616
pc_mobile_type : mo (pc도 동일)

실제로 2개의 메뉴에서 다운로드 받는 데이터들은 서로 차이가 발생할 수 있는건지요?

**Comment by naver-searchad** [comment]
안녕하셔요 대용량 다운로드 보고서 담당자입니다. 

동일한 합산 대상에 대해 올바르게 합산 하였다면(문의 주신 케이스는 소재)값이 다를수 없습니다. 
대용량 다운로드 보고서는 어떤 보고서를 다운로드 받으신 것이고, 다차원 보고서는 어떤 조건으로 생성하셨는지 말씀부탁드립니다. 

감사합니다.

**Comment by mkms1104** [comment]
대용량 다운로드 보고서는 광고 성과 보고서 항목으로 다운로드 하였으며,
다차원 보고서는 아래 이미지로 첨부드립니다.
![image](https://github.com/naver/searchad-apidoc/assets/19260410/1e2f5537-8825-4323-9edd-84d328a08a98)

보고서 기준 날짜는 모두 어제 기준인 9월 10일입니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

알려주신 값들을 대조해본 결과 차이가 확인되어 금일 오후 3시 30분 현재 데이터 체크 및 검산 작업 진행중입니다. 
또한 금일 오후부터 유사한 문의가 다수 인입되고 있어 전반적인 확인이 진행중입니다. 현재로서는 데이터에 문제가 있을 가능성이 높다고 생각 됩니다. 확인 되는데로 답변 드리도록 하겠습니다. 불편 드려 죄송합니다. 

감사합니다.

**Comment by mkms1104** [comment]
네 알겠습니다. 답변 기다리고 있겠습니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

문의 주신 사항은 stat-report의 오류가 맞으며 다차원보고서으 지표가 정확한 지표입니다. 
새로 보고서를 생성하시어 다운 받으시기를 부탁드립니다. 
단, 현재 stat-report 전체의 오류가 있어 지표 재생성 중으로 완료 예상 시점(금일 22시) 이후에 다시 생성 요청을 부탁드립니다. 
관련 공지는 아래 공지 게시판을 참고하여 주십시오. 
https://naver.github.io/searchad-apidoc/#/notice

다시 한번 불편드린점 사과 말씀드립니다. 

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다.

금일 18시 30분 현재 대용량 보고서 복구 완료 되었습니다. 

감사합니다.

**Comment by mkms1104** [comment]
네 감사합니다!
