### ISSUE TITLE
stat와 stat-report 데이터의 차이 발생 원인

### ISSUE THREAD

**Issue by ROSETTA-LEE** [naver/searchad-apidoc#839]
안녕하세요~
동일한 일자와 기간으로 네이버광고센터/stat와 stat-report 데이터를 조회하였을 때
stat-report에서만 확인되지 않는 데이터가 있으며,
모든 계정에서 공통적으로 같은 현상이 발생하고 있어 문의 드립니다.

아래 호출한 샘플 ad id 공유드립니다.

[stat (광고센터와 데이터 동일)]
naver/getstat/******/nad-a001-02-000000257774486/-/-/yesterday/allDays/-
{"data":[{"ctr":100,"pcNxAvgRnk":2,"mblNxAvgRnk":0,"convAmt":0,"crto":0,"ccnt":0,"avgRnk":2,"salesAmt":55,"clkCnt":1,"ror":0,"viewCnt":0,"cpc":55,"id":"nad-a001-02-000000257774486","cpConv":0,"impCnt":1}],"compTm":"202309110219","cycleBaseTm":"202309100000"}

[stat-report]
reportTp : AD
statDt : 20230910
데이터 없음

감사합니다!

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

혹 생성하신 STAT-REPORT의 잡아이디를 알려 주실수 있으실지요?

이는 별개로 현재 23년 9월 10일 보고서 지표들에 문제가 일부 발견되어 확인을 진행하고 있습니다. 
확인이 종료 되는 데로 답변을 드리도록 하겠습니다. 

불편 드려 죄송합니다.

**Comment by ROSETTA-LEE** [comment]
1985937259 입니다. 감사합니다!

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

문의 주신 사항은 stat-report의 오류가 맞으며 새로 보고서를 생성하시어 다운 받으시기를 부탁드립니다. 
단, 현재 stat-report 전체의 오류가 있어 지표 재생성 중으로 완료 예상 시점(금일 22시) 이후에 다시 생성 요청을 부탁드립니다. 
관련 공지는 아래 공지 게시판을 참고하여 주십시오. 
https://naver.github.io/searchad-apidoc/#/notice

다시 한번 불편드린점 사과 말씀드립니다. 

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다.

금일 18시 30분 현재 대용량 보고서 복구 완료 되었습니다. 

감사합니다.
