### ISSUE TITLE
n_match 값을 StatReport api 를 통해서 받을 수 있을까요?

### ISSUE THREAD

**Issue by gimslab** [naver/searchad-apidoc#840]
Keyword 별 (검색 키워드 아닌 키워드)로 n_match 값을 받을 수 있는 api 가 있을까요?

관련 기능 공지..
https://saedu.naver.com/notice/view.naver?notiSeq=4159&catg=&fixYn=N&searchOpt=all&keyword=%EC%B6%94%EC%A0%81

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

문의 주신 내용이 정확히 어떤 정보인지 이해가 어려운데요. 
보고서 지표를 말씀주시는 것인지요?
예를 들면 전환 지표들중 등록 키워드 아이디/매칭 타입 별 지표를 제공하는가? 라는 문의 이신지요?

감사합니다.

**Comment by gimslab** [comment]
안녕하세요. 제가 너무 짧게 질문을 드렸네요.

이번에 추가된 
n_match 파라미터와
https://naver.github.io/searchad-apidoc/#/tags/StatReport 화면의 레포트들에 대한 질문입니다.

저희가 원하는건 다음과 같은 데이터입니다.
```
Keyword | Search Keyword | n_match | Impression | Click | Cost | 기타 실적..
```

제가 보기엔 EXPKEYWORD가 가장 비슷해보입니다. 근데 키워드와 n_match 값이 없어서 어떤 키워드와 연계된 검색어인지 그리고 어떤 매치방식으로 검색된건지는 알 수가 없습니다.

혹시 이러한 요구사항을 구현할수 있는 방법이 있을까요?

답변감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

등록 키워드와 검색어가 조합된 지표는 지원되지 않습니다. 향후에도 지원될 가능성은 극히 낮다고 예상 됩니다. 
또한 추적 URL 서비스에서 분류하고 있는 검색 매칭 방식 (n_match로 )과 보고서에서 분류하는 검색 확장 방식의 종류 구분은 서로 다릅니다. 

대용량 보고서의 경우를 아래 n_match를 기준으로 설명 드리면 아래와 같습니다. 
- 일치 : 현재 대용량 보고서에서 제공되지 않으나 올해중 제공 예정 
- 키워드 확장 : 제공됨 
- 연관 검색 : 제공되지 않음 
- 일치(유사 검색어) : 제공됨
- 스마트 블록 : 키워드 확장으로 분류됨 

결론적으로 검색광고 API서비스 및 네이버 검색광고에서 제공하는 보고서 기능으로는 말씀 주신 데이터 셋을 구현할수 없습니다. 

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다.

이전에 말씀드린것과 같이 검색어 보고서에 일치 항목이 추가되는 일정이 확정 되어 말씀드립니다.
2023년 11월 14일(2023년 11월 13일자 데이터)부터 반영으로 상세사항은 공지 게시판을 참고하여 주시기 바랍니다.
https://naver.github.io/searchad-apidoc/#/notice

감사합니다.
