### ISSUE TITLE
estimate 견적 데이터 기간

### ISSUE THREAD

**Issue by nibxxad** [naver/searchad-apidoc#841]
Q1. **Estimate: get (average position bid)는 지난 28일 순위별 평균 입찰가가 맞나요..?**
https://naver.github.io/searchad-apidoc/#/operations/POST/~2Festimate~2Faverage-position-bid~2F%7Btype%7D

Q2. **Estimate: get (performance)의 리턴값으로 받는 데이터의 기간은 어떻게 되나요?**
ex. api 요청일 기준, 30일 이후의 예상 실적
https://naver.github.io/searchad-apidoc/#/operations/POST/~2Festimate~2Fperformance~2F%7Btype%7D

도움 부탁드립니다..!!!
감사합니다 :)

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 입찰 지원도구 담당자입니다. 

Q1. 네 28일 즉 4주간 데이터로서 주 1회 계산합니다. 
Q2. 
문의 주신 데이터는 과거 28일 데이터를 기준으로 추정되므로 4주 데이터(28일) 데이터로 보시면 되겠습니다. 
단, 추정으로 인한 오차범위를 고려한다면 28일/30일 이렇게 나눠서 생각하시기 보다는 대략 1개월 정도의 예상 성과라고 간주해 주시면 되겠습니다.  그리고 미래 성과를 예측하는 것이긴 하지만 정확한 컨셉은 "과거 28일 전으로 돌아가 현재까지 설정한
입찰가를 계속 유지 했다면 발생 했을 성과"입니다. 

계산 방식 및 추정 방식은 대략적으로 모두 공개 하고 있으므로 궁금하신 점이 있으시다면 문의 부탁드립니다. 

감사합니다.

**Comment by nibxxad** [comment]
상세한 답변 감사합니다~!
추가 문의드립니다!

Q1. 주 1회 업데이트되는 요일도 공유주실 수 있으신가요?

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 입찰 지원도구 담당자입니다.

매주 일요일 전일(토요일)로부터 과거 28일 데이터를 가지고 계산합니다. 

감사합니다.

**Comment by nibxxad** [comment]
안녕하세요 담당자님! RelKwdStat 데이터 갱신 주기 관련하여 문의 드립니다.
해당 데이터 역시 api 호출일 기준, 과거 28일 데이터를 보여주는건가요?
https://naver.github.io/searchad-apidoc/#/tags/RelKwdStat

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 입찰 지원도구 담당자입니다.

문의 주신 연관 키워드(RelKwdStat) 기능의 경우 일부 지표에서 대상 기간이 다릅니다. 
monthlyPcQcCnt, monthlyMobileQcCnt  --> 조회시점(조회시점이 0시~06시 사이가 아니라면) 전일로부터 과거 30일 , 매일 업데이트 
monthlyAvePcClkCnt,monthlyAveMobileClkCnt,monthlyAvePcCtr,monthlyAveMobileCtr,plAvgDepth,compIdx--> 과거 28일, 매주 일요일 업데이트

그리고 RelKwdStat의 값들은 스케일링(예를 들어 1231 -> 1230 같은 식입니다.)이 들어가 있어 정확한 값이라기 보다는 대략의 크기를 파악하는 정도로 활용되어야 합니다. 정확한 값을 제공드리는 기능은 현재 존재하지 않습니다. 

감사합니다.
