### ISSUE TITLE
statReport API 문의

### ISSUE THREAD

**Issue by 10754** [naver/searchad-apidoc#842]
자동 추적 URL 파라미터기능 제공과 관련하여
statReport API에 매치넘버 실적 정보가 포함된 계획이 있는지 문의 드립니다.
https://naver.github.io/searchad-apidoc/#/tags/StatReport)

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

정확히 원하시는 내용을 추측키 어려워 답변 드리기 어렵습니다만 질문 그대로만 해석한다면 계획이 없다고 답변 드릴수 밖에 없을것 같습니다. 

비슷한 정보로는 광고 그룹&검색어(등록키워드가 아님을 주의 부탁드립니다.)별 검색 유형별 보고서가 제공되고 있기는 합니다. 파워링크 검색어 보고서가 그것인데요. 현재 이 보고서에 일치에 관한 정보는 없어 이를 올해중에 추가할 계획은 있습니다. 

감사합니다.

**Comment by 10754** [comment]
이전 n_match 업데이트 내역으로, 매치 방식이 아래의 값으로 제공을 한다고 했는데
검색어 데이터를 아래와 같이 제공할 예정인지 문의를 드립니다.
- 일치 : 1
- 키워드 확장 : 2
- 연관 검색 : 3
- 일치(유사 검색어) : 4
- 스마트 블록 : 5

**Comment by 10754** [comment]
추가로 검색어로 노출이 되는 위 매치 값들은 
API 어느 영역에서 어디서 확인 가능한지 문의드립니다.

**Comment by naver-searchad** [comment]
안녕하셔요 대용량 다운로드 보고서 담당자입니다. 

대용량 보고서 기준으로 말씀드리면 파워링크 검색어 보고서(reportTp : EXPKEYWORD)에서 아래와 같이 제공 중입니다. 
일치 : 올해 중 제공 예정 
키워드 확장 : 제공중 
연관 검색 : 제공하지 않음 
일치(유사검색어): 제공중
스마트 블록 : 키워드 확장에 포함되어 제공중으로 별도 구분 되지 않음  

그리고 추적 URL의 n_match  값과 일치하는 값 자체를 제공하는 API는 제공되지 않습니다. 

감사합니다.

**Comment by 10754** [comment]
스마트블럭은 키워드 확장에 포함되어 제공중으로 별도 구분되지 않음 이라고 하셨는데,
그럼 공지사항 내 [스마트 블록 : 5 ] 값은 어떤 의미인지 알 수 있을까요?
당연히 reportTp : EXPKEYWORD 를 통해서 확인이 가능할거라 생각되어 내부적으로 테스트를 진행하고 있는데
공지사항에는 구분이 된다고 하고, 실제로는 키워드 확장과 스마트 블록 값이 검색어 값이 구분이 되지 않는다고 하여
혼동이 오고 있어 확인 부탁드립니다.

**Comment by naver-searchad** [comment]
안녕하셔요 대용량 다운로드 보고서 담당자입니다.

말씀주신 공지는 추적 URL 기능에 관한 공지로 생각됩니다. 
보고서와 관련된 공지는 아래 내용을 참고하여 주시기 바랍니다. 
https://naver.github.io/searchad-apidoc/#/notice
[2023-08-10] 대용량 보고서(파워링크 검색어 보고서) 변경 안내

보고서에서는 스마트블럭에서 제공되는 확장 방식(https://saedu.naver.com/notice/view.naver?notiSeq=4010)을 기존 키워드 플러스의 확장방식과 묶어 키워드 확장 검색으로 간주하여 처리하고 있습니다. 
따라서 Search Keyword Type 필드에는 1: Extend 로 표기 됩니다. 
반면 추적 URL에서는 이를 구분하여 제공한다는 의미 입니다. 

참고로 추적 URL 기능과 검색광고 API 서비스는 별개의 서비스로 동일한 광고 데이터를 다루는 도구이기는 하나 그렇다고 해서 반드시 동일한 정책과 서비스 방향으로 운영되지는 않습니다. 각자의 성격에 따라 서비스의 형상과 내용은 다를수 있습니다. 

감사합니다.

**Comment by 10754** [comment]
빠른 답변 주셔서 감사합니다.
이에 마지막으로 한가지만 문의를 드립니다.
https://naver.github.io/searchad-apidoc/#/tags/StatReport
KEYWORD PLUS Performance Report (reportTp : EXPKEYWORD)

위 링크에 나와 있는 API 개발 문서 페이지 내 내용이 최신 버전인지 문의 드립니다.
Report & Master Specification 해당 한글로된 대용량 다운로드 보고서 내 [파워링크 검색어 보고서] 에서
Search Keyword Type 내용이 API 개발 문서 페이지는 없기에 문의를 드립니다.

**Comment by naver-searchad** [comment]
안녕하셔요 대용량 다운로드 보고서 담당자입니다.

지난 몇년간 다양한 방식의 확장 검색 들이 도입되고 있고, 저희 상품 기능도 점차 강화 되고 있는 추세이므로 확정적으로 답변 드리기는 어렵겠습니다만 Performance Detail Repot 수준의 상세 데이터에 검색 타입 항목이 추가될 가능성은 향후 2,3년간은 아주 낮다고 말씀드릴수 있을것 같습니다. 
그리고 검색 타입 항목이 향후 추가 되더라도 이는 추적 URL의 매칭 넘버(넘버라고 써 있긴 하지만 실제 검색 매칭 종류를 나타내는 enum 값입니다.) 과는 다른 분류일 것으로 생각 됩니다. 

감사합니다.

**Comment by naver-searchad** [comment]
안녕하셔요 대용량 다운로드 보고서 담당자입니다.

아마 지우신것 같은데 현재 레퍼런스 페이지의 내용들이 최신 버전인지 문의를 주신내용에 대해 답변 드립니다. 

얼마전에 페이지를 개편하면서 대용량 보고서에서 그동안 업데이트 된 내용이 롤백 된것 같습니다. 
확인해 보고 최신내용으로 다시 업데이트 해 두겠습니다. 

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

이전에 말씀드린것과 같이 검색어 보고서에 일치 항목이 추가되는 일정이 확정 되어 말씀드립니다. 
2023년 11월 14일(2023년 11월 13일자 데이터)부터 반영으로 상세사항은 공지 게시판을 참고하여 주시기 바랍니다. 
https://naver.github.io/searchad-apidoc/#/notice

감사합니다.
