### ISSUE TITLE
광고그룹 마스터 보고서 문의

### ISSUE THREAD

**Issue by AlexandrossSSssSS** [naver/searchad-apidoc#844]
안녕하세요.

마스터 보고서 다운로드시 tsv 파일 한 줄에 탭이 하나가 추가되어 파싱이 안 되고 있습니다.

job id: 054A09E23C8B446FF0DDD14F095C6994

확인 부탁드립니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

답변이 늦어 죄송합니다. 
탭문자는 금지 문자이나 간혹 예전데이터 마이그레이션 과정 혹은 저희 오류 시점에 이름에 탭이 입력이 된 경우가 있습니다. 
저희가 임의로 데이터를 수정할수는 없어 해당 광고그룹명 등에서 탭을 제거하신후 다시 마스터를 다운로드 받아 주시기 바랍니다.

감사합니다.
