### ISSUE TITLE
Master Report (ShoppingProduct) 데이터 누락 원인

### ISSUE THREAD

**Issue by ROSETTA-LEE** [naver/searchad-apidoc#845]
안녕하세요~

오늘자 쇼핑상품 변경내용이 마스터리포트에 반영되지 않은채로 조회되고 있습니다.
오전부터 3차례에 걸쳐 호출하였지만 지속적으로 데이터가 누락된 상태였으며,
특정 customer id가 아닌 다수의 id에서 동일한 현상이 발생합니다.

누락데이터 샘플 : nad-a001-02-000000263449151
reportJobId : 9C703FEBE646A71FD6FB067FE0FB53BD

확인에 필요한 정보가 있다면 말씀 부탁드립니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

네 어제 밤부터 현상이 발견되어 현재 해당 보고서 장애 상황입니다. 
현재 어제 15시 이후 신규로 등록된 상품들의 정보를 보고서에 담지 못하고 있구요. 
복구 진행 중입니다. 
불편드려 대단히 죄송합니다. 

상세 사항은 공지를 참고 부탁드립니다. 

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다.

북구 완료 예상 시점은 23년 9월 14일 20시 입니다. 

불편드려 죄송합니다.
