### ISSUE TITLE
account status api 제공 여부

### ISSUE THREAD

**Issue by ROSETTA-LEE** [naver/searchad-apidoc#846]
안녕하세요, 광고계정의 상태를 조회할 수 있는 api가 있는지 문의드립니다.
잔액 부족으로 인한 상태는 ad, adextension, businesschannel의 status reason에서 확인 가능한 것으로 이해했는데요,
혹 계정에 대한 api가 별도로 있는지 궁금합니다.
감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API 담당자입니다. 

계정 단위로 비즈머니 상태에 따라 광고 노출 여부를 조회하는 기능은 지원되지 않습니다. 

감사합니다.
