### ISSUE TITLE
go 언어 stat/ 사용시 데이터 누락

### ISSUE THREAD

**Issue by carlsbug** [naver/searchad-apidoc#847]
go는 예제가 없어서 직접 짜보았는데요
/stats 의 정보를 받기 위해 API 전송후 response body를 확인해보면 생각보다 자주 몇몇 field들의 값이 0 으로 돌아오는 경우가 있습니다.
Get request를 여러번 보내야 모든 데이타가 들어 오는데요
Python 사용시에는 전혀 발생 하지 않았던 케이스라 약간 당황스럽네요

Python과 동일한 HTTP request 값(헤더포함)을 전송하였고 Status도 OK인데 
Request한 데이터가 온전히 다 들어오지 않는 경우가 생길 수 있는걸까요?

**Comment by carlsbug** [comment]
@naver-searchad 안녕하세요 글을 작성한지가 꽤 되어서요
한번 꼭 좀 확인 부탁드립니다
감사합니다

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다

stat API 은 일반적인 HTTP request 를 지원하고 있습니다.
GO 개발 코드상의 문제로 보여서 정확한 답변을 드리기 어려운 점 양해 부탁 드립니다.
