### ISSUE TITLE
STAT Report 400 코드 오류 관련의 건 

### ISSUE THREAD

**Issue by username1923** [naver/searchad-apidoc#848]
아래와 같이 Stat Report 코드를 짰는데 추출된 파일에 하기와 같은 오류가 계속 뜹니다.
API_KEY를 제대로 입력했는데 자꾸 header가 missing 되었다고 떠서 관련해서 어느 부분을 수정해야 하는지 문의드립니다.

오류 : {"header":"X-API-KEY","status":400,"type":"urn:naver:api:problem:missing-header","title":"Missing Header","detail":"HTTP header required: X-API-KEY"}

import time
import random
import requests
import signaturehelper
import pandas as pd
from datetime import datetime, timedelta

def get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID):
    timestamp = str(round(time.time() * 1000))
    signature = signaturehelper.Signature.generate(timestamp, method, uri, SECRET_KEY)
    response = requests.get(downloadUrl, headers=headers)
    return {'Content-Type': 'application/json; charset=UTF-8', 'X-Timestamp': timestamp, 'X-API-KEY': API_KEY, 'X-Customer': str(CUSTOMER_ID), 'X-Signature': signature}

BASE_URL = 'https://api.searchad.naver.com'
API_KEY = 'API키번호'
SECRET_KEY = '시크릿키번호'
CUSTOMER_ID = '유저ID'

############################################################
# JobId 호출 단계 (CREATE)

yesterday = datetime.now() - timedelta(1)
formatted_date = yesterday.strftime('%Y%m%d')

params = {
    "reportTp": "AD",  # 원하는 보고서 유형 입력 ex) AD
    "statDt": f"{formatted_date}"  # 날짜 입력 ex) 형식 -> 20230101
}

method = 'POST'

uri = '/stat-reports'

headers = get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID)
response = requests.post(BASE_URL + uri, headers=headers, json=params)

reportJobId = response.json().get('reportJobId')

############################################################
# URL 호출 단계 (GET)
method = 'GET'
uri = f'/stat-reports/{reportJobId}'

headers = get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID)
response = requests.get(BASE_URL + uri, headers=headers)

downloadUrl = response.json().get('downloadUrl')

############################################################
# 파일 다운로드
response = requests.get(downloadUrl)
df = response.json()

# JSON을 DataFrame으로 변환
df = pd.DataFrame([df])
filename = f"광고성과보고서_{reportJobId}_{formatted_date}.tsv"

# 저장 경로 설정하고 싶으면 수정
path = '경로'
filename = path + filename 
df.to_csv(filename, sep='\t', index=False)

**Comment by naver-searchad** [comment]
@username1923 안녕하세요. 네이버 검색광고 API 담당자 입니다.

파일 다운로드시에도 동일하게 header 를 넣어주셔야 하는데요. 그 부분이 누락되어서 오류가 발생한것으로 보입니다.

> requests.get(downloadUrl)

해당 부분을 수정부탁드리겠습니다.

감사합니다.

**Comment by naver-searchad** [comment]
@username1923 

정확한 원인 파악을 위해서는 응답 헤더에 포함되는 x-trasaction-id 를 전달해주시면 더 정확한 확인이 가능합니다.

실제로 x-api-key 가 전달되지 않는것으로 보이는데요. 
get_header 함수의 리턴값에 x-api-key 가 정확히 포함되는지 한번 점검 해보시는게 좋을것 같습니다.

 x-trasaction-id  를 알려주시면 좀 더 자세히 확인해보도록 하겠습니다.

**Comment by username1923** [comment]
오류 목록을 다시 살펴보니 유효하지 않은 signature로 인해 오류가 계속 발생하는 것으로 보여집니다.
시그니처 생성에는 별다른 오류가 보이지 않는데 확인 부탁드립니다.

추가로 말씀주시는 x-trascation-id는 apikey, secrectkey, customerid 말씀주시는 게 맞으실까요?

오류 : {'signature': '서명~~', 'status': 403, 'type': 'urn:naver:api:problem:invalid-signature', 'title': 'Invalid Signature', 'detail': "Signature '서명~~' is invalid."}

**Comment by naver-searchad** [comment]
@username1923 

1. 응답 body 가 아닌 header 에 X-Transaction-ID 값으로 들어가 있으니 해당 값 확인 부탁드리겠습니다.


2. signature 오류의 원인은 코드를 제공해주시지 않아서 정확히 확인은 어렵지만, 보통 
- http method 를 잘못 넣거나
- uri 생성시 query param 을 포함하거나, 또는 path parameter 를 제외하고 생성
하는 경우 많이 발생합니다. 해당 부분 체크해보시면 좋을것 같습니다.

감사합니다.

**Comment by naver-searchad** [comment]
@username1923 

요청을 확인해보니, /report-download 요청 오류이고, 말씀하신대로 signature 생성을 잘못하신것 같은데요.

{timestamp}.GET./report-download 값으로 서명을 생성하셨는지 확인 부탁드리겠습니다.

request parameter 를 포함하여 생성하신게 아닐지 확인해보시면 좋을것 같습니다.
