### ISSUE TITLE
Estimate median bid, exposure minimum bid 데이터 확인 요청 건

### ISSUE THREAD

**Issue by choics** [naver/searchad-apidoc#849]
현재 모든 키워드에 대한 median bid, exposure minimum bid 의 API에 대해서 
리턴되는 bid 값이 70원으로 밖에 확인되고 있지 않습니다.

해당 API 데이터에 대해 확인 부탁드립니다.

**Comment by naver-searchad** [comment]
안녕하십니까 입찰 지원도구 담당자입니다. 

전일 밤에 장비 이전 과정에서 문제가 발생하여 데이터가 제공되지 않았습니다. 
불편 드려 대단히 죄송합니다. 
9월 20일 오전 9시 57분 현재 복구가 완료되었습니다. 

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 입찰 지원도구 담당자입니다.

질문 주신 시점을 제가 미쳐 보지 못하였는데요. 
문제가 있었던 것은 맞으나 이는 기존에 저희쪽에 정보가 없던 키워드로 한정됩니다. 
그래서 어제 오후에는 정상적으로 데이터가 조회되고 있었어야 하는데요. 
호출하신 키워드를 알려주실수 있으실까요? 다른 문제일 가능성도 있어 보입니다.

감사합니다.

**Comment by choics** [comment]
안녕하세요.
전일 다수의 키워드로 조회시 모두 70원으로 조회되었으며 복구 완료 후 다시 조회해 보니 정상 조회되고 있습니다
자동차보험
이바나헬싱키
닐바이피
리리앤코
가을하객룩
등...전일 대략 400개 정도의 키워드가 모두 70원이 리턴되었습니다.

참고 부탁드립니다.

**Comment by naver-searchad** [comment]
안녕하십니까 입찰 지원도구 담당자입니다.

확인 완료하여 답변 드립니다. 
어제 오전부터 문제가 있었고, 어제 하루 동안 많은 키워드들에서 조회시 70원이 리턴된것으로 확인되었습니다. 
해당 문제는 오늘 오전 복구 과정에서 같이 자연스럽게 해결 되어 빠른 확인이 어려웠습니다. 이점 양해 부탁드립니다. 
금일 오전 복구 완료후 현재 완전히 정상적인 상황입니다. 
불편 드려 대단히 죄송합니다. 

감사합니다.
