### ISSUE TITLE
파워링크 키워드 확장 / 광고그룹  컬럼 문의

### ISSUE THREAD

**Issue by SM10855** [naver/searchad-apidoc#850]
안녕하세요.

최근에 반영된 노출여부 기능과,
![image](https://github.com/naver/searchad-apidoc/assets/50356241/a2378b3c-590b-4d92-94a4-da21a8556fff)

https://saedu.naver.com/notice/view.naver?notiSeq=4159&catg=&fixYn=N&searchOpt=all&keyword=
추적기능에 '매치 방식' 정보가  추가된 내용에 대해 궁금한 부분이 있어서 문의드립니다.

- 일치 : 1
- 키워드 확장 : 2
- 연관 검색 : 3
- 일치(유사 검색어) : 4
- 스마트 블록 : 5

매치 방식에는 위와 같이 제공된다고 하는데, 

노출여부 기능 광고그룹에 있는 컬럼 조합으로 위와 같이 1~5 까지의 값을 어떤 조합으로 나타내었을때
위에 기술된 내용과 매칭이 되는 것인지 궁금합니다.

또한 파워링크 검색어 보고서에서도 위와 같이 키워드 유형별로 데이터를 뽑아낼 수 있는지도 궁금합니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

추적 URL과 검색 매칭 설정은 실상 크게 관련이 없어서 어떻게 설명을 드려야 할지 난감합니다. 
추적 URL은 광고가 노출 된 이후 클릭이 발생했을때 광고 노출 및 클릭에 대한 값들을 전달 드리는 것입니다. 
설정은 내 광고가 어떻게 나갈지를 결정하는 것이구요. 
예를 들어 검색 매칭이 어떻게 설정되어 있든 등록키워드와 검색어가 동일하면 일치가 됩니다. 
그래서 설정 값과 추적 URL 혹은 보고서의 값을 비교하는 것은 대단히 어색한 일이될것입니다. 
따라서 제가 설명 드릴수 있는 것은 추적 URL의 각 항목별로 어떤 설정으로 인해 이런 값이 발생될수 있는지에 대해서
말씀드리는 형태가 될수 밖에 없음에 대해 양해를 구합니다. 

일치 --> 앞서 예시로 들어드린 것처럼 설정이 무엇이든간에 등록 키워드와 검색어가 동일한 케이스입니다. 
               현재 대용량 보고서의 파워링크 검색어 보고서에서는 지원되지 않으나 올해중에 해당 지표도 제공될수 있도록 보고서 
               수정 작업이 진행 중입니다. 
키워드 확장 --> USE KEYWORD PLUS가 TRUE인 경우 발생 될수 있습니다. 
                      파워링크 검색어보고서에서 확장(Search Keyword Type=1)으로 표시 됩니다.   
연관 검색 --> 매체에 연관된 방식입니다. 콘텐츠네트워크에 노출 되는 광고들이 연관 검색 방식으로 노출 됩니다. 
                   대용량 보고서내 일반적인 보고들에서 컨텐츠 네트워크에 속한 매체들의 정보만을 선택하시면 확인 하실수있습니
                   다. Ad media Master (Media)에서 Contents Ad Networks=TRUE로 설정된 매체들이 컨텐츠 네트워크 매체입니다. 
일치(유사 검색어) --> 얼마전 새롭게 기능 제공되기 시작한 유사 검색어 입니다. USE CLOSEVALIANT=TURE인 경우 발생될수 있 
                                   습니다. 파워링크 검색어보고서에서 유사검색어(Search Keyword Type=2)으로 표시 됩니다.   
스마트 블록 --> 특정 매체에만 한정된 방식입니다. 네이버 통합검색 파워링크 스마트블록- PC', '네이버 통합검색 파워링크 
                           스마트블록 - 모바일'  매체에 나가는 광고는 모두 스마트 블록 방식으로 노출됩니다. 
                           파워링크 검색어보고서에서 확장(Search Keyword Type=1)으로 표시 됩니다. 

즉 설정 값이 어떤 조합이든 실제로 노출된 상황에 따라 추적기능의 값은 제공됩니다. 
따라서 이를 특정 조합으로 설명드릴수는 없을것 같습니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다.

이전에 말씀드린것과 같이 검색어 보고서에 일치 항목이 추가되는 일정이 확정 되어 말씀드립니다.
2023년 11월 14일(2023년 11월 13일자 데이터)부터 반영으로 상세사항은 공지 게시판을 참고하여 주시기 바랍니다.
https://naver.github.io/searchad-apidoc/#/notice

감사합니다.
