### ISSUE TITLE
이용자 세그먼트(BETA) 성과데이터 관련 문의

### ISSUE THREAD

**Issue by dpgpa** [naver/searchad-apidoc#854]
안녕하세요.

최근 업데이트된 이용자 세그먼트 관련 문의드립니다.

현재 세그먼트의 성과 데이터를 다차원 보고서에서 다운로드가 불가능한데요.
API 로도 데이터를 별도 제공하지는 않는 듯 합니다.

혹시 beta 종료 후 정식서비스화 되면 아래 두 항목에 대한 제공이 가능하게 될 지 확인 부탁드립니다.
- 다차원보고서 내 해당 지표 제공
- API로 데이터 제공

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드보고서 담당자입니다. 

이용자 세그먼트(이전 명칭 잠재고객타게팅) 지표는 대용량 다운로드 보고서(STAT_REPORT)에서 제공 되고 있습니다. 
아래 공지 내용을 참고 부탁드립니다. 
그리고 STAT 기능에서 제공 여부는 담당자에게 확인후 다시 답변 드리도록 하겠습니다. 

-------------
[2023-08-18] 잠재고객타게팅(BETA) 기능 제공에 따른 마스터 및 대용량 보고서 이용 안내
안녕하십니까 네이버 검색광고 API입니다.

잠재고객타게팅(BETA) 기능이 2023년 8월 23일부터 제공됨에 따라
대용량 보고서 지원 사항 안내 드립니다.
관련 공지 : https://saedu.naver.com/notice/view.naver?notiSeq=4151

MASTERREPORT
기존의 타게팅과 동일하게 설정된 타게팅 정보는 Criterion Master (Criterion)를 통해 조회하실수 있습니다.
잠재고객타게팅으로 생성된 Criterion은 Criterion Master (Criterion)의 Type 중 “AD”로 분류 됩니다.

STATREPORT
설정된 잠재고객 타게팅 별 광고 성과 지표는 기존 타게팅 보고서인 아래 두 보고서를 통해 동일하게 제공되며
보고서 사양의 변화는 없습니다.
Criterion Report (reportTp: CRITERION)
Criterion Conversion Report (reportTp: CRITERION_CONVERSION)

잠재고객타게팅(BETA)적용 일시(모든 일시 KST기준)
MASTERREPORT : 2023년 8월 23일부터 적용
STATREPORT: 2023년 8월 25일(2023년 8월 25일자 보고서)부터 적용

업무에 참고 부탁드립니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

STAT(https://naver.github.io/searchad-apidoc/#/tags/Stat) 기능에서도 지표가 제공되고 있는 것을 확인하였습니다. 
생성한 각 항목별 criterion_id를 이용하여 호출하시면 되겠습니다. 

감사합니다.
