### ISSUE TITLE
마스터 리포트 변경분 (fromTime) 데이터에 대한 문의

### ISSUE THREAD

**Issue by mkms1104** [naver/searchad-apidoc#855]
안녕하세요.

AD_KEYWORD_MASTER 리포트의 Ad Keyword ID 컬럼은

변경분 데이터 내에서 중복되어 나타날 수 있나요??

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

변경분은 최종 변경내역만을 담고 있기 떄문에 "이론적으로는" 중복이 되면 안됩니다. 
혹 발견이 되신다면 보고서 잡아이디를 알려주시면 감사하겠습니다. 
그리고 저희 사정이기는 합니다만 현재 담당 개발자가 휴가 중으로 빠른 답변이 어려울수 있다는점 양해를 부탁드립니다. 

감사합니다.

**Comment by mkms1104** [comment]
@naver-searchad
네 참고 하겠습니다. 답변 감사드립니다.
변경분 내역에 대해 추가적으로 조금 더 질문드리겠습니다

- 금일 기준 변경분 fromTime = 10/10 00시로 지정할 경우 포함되는 내역은
a. 10/10 00시 ~ 현재 사이에 삭제된 내역
b. 10/10 00시 ~ 현재 사이에 수정된 내역 (특정 컬럼 아무거나 수정)
c. 10/10 00시 ~ 현재 사이에 등록된 내역

a, b, c 항목 모두 포함되는 것이 맞을까요?

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다.

네 A, B, C가 변경분의 대상입니다. 한가지 주의 하실점은 B의 경우 마스터에는 포함되어 있지 않지만 저희 내부 테이블 상에는 존재하는 내부 관리용 컬럼들이 존재하는데요. 이 컬럼들이 업데이트 된 경우에도 B 케이스로 제공된다는 점입니다. 
또한 드문일이긴 하지만 내부 데이터 관리과정에서 기존 값과 동일한 값으로 업데이트가 이루어지는 경우도 있습니다. 이런 경우 실제로 값은 변화가 없으나 변경분에는 포함됩니다. 이점 감안을 부탁드립니다. 

감사합니다.

**Comment by mkms1104** [comment]
@naver-searchad 
네. 상세한 답변 감사드립니다!

**Comment by SM10855** [comment]
안녕하세요. 위 질문에 이어서 하나 문의드립니다.

장개기간동안의 변경된 데이터들이 , 실제로 Master- Report 를 통해서 받아오는 내역에 포함되어 있지 않았다는 내용으로 이해하면 될까요?

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

"장애기간동안 변경된 데이터들이 , 실제로 Master- Report 를 통해서 받아오는 내역에 포함되어 있지 않았다는 내용으로 이해하면 될까요?"
위의 문의는 제가 말씀드린 어떤 내용에 대한 말씀 이신지요?

감사합니다.

**Comment by SM10855** [comment]
안녕하세요. 
http://naver.github.io/searchad-apidoc/#/notice
공지사항에 올라온 
[2023-10-13] 마스터 데이터 지연 반영 장애 공지 관련된 내용인데, 이 내용을 제가 빠트렸습니다.
공지사항에 대한 질문과 관련된 문의인줄 알고 이곳에 이어서 질문드렸습니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다.

공지 드린 장애건은 장애 처리 완료 시점 이후에는 데이터가 모두 존재하는 상태입니다. 
대용량 보고서의 데이터 누락 케이스들은 특별한 상황이 아니면 데이터 누락이 없도록 처리하는 것이 원칙이며 영구적인 데이터 누락이 존재하는 경우에는 별도로 공지내에 이 사실을 고지하고 있습니다. 

감사합니다.

**Comment by SM10855** [comment]
네 알겠습니다 답변 감사합니다
