### ISSUE TITLE
Campaign: get 이 메소드에서 Invalid Signature 문제가 발생합니다.

### ISSUE THREAD

**Issue by Parkjunwu** [naver/searchad-apidoc#856]
Campaign: list (by customer id, campaign type)
Campaign: list (by ids)
Stat: get (by id)

여기에서는 문제가 생기지 않는데 
Campaign: get
이거를 사용할 때에만 Invalid Signature 문제가 발생합니다.

nodejs 환경 입니다.

```typescript
import * as CryptoJS from 'crypto-js';

private readonly host = "https://api.searchad.naver.com"

private readonly getCampaignPath = "/ncc/campaigns"

getHeaders(api_url: string, method: string = "GET") {

        const timestamp = Date.now() + '';
        const hmac = CryptoJS.algo.HMAC.create(CryptoJS.algo.SHA256, this.SECRET_KEY);
        hmac.update(timestamp + '.' + method + '.' + api_url);
        const hash = hmac.finalize();
        
        const headers = {
            'X-Timestamp': timestamp,
            'X-API-KEY': this.ACCESS_LICENCE_KEY,
            'X-API-SECRET': this.SECRET_KEY,
            'X-CUSTOMER': this.CUSTOMER_ID,
            'X-Signature': hash.toString(CryptoJS.enc.Base64)
        };
        return headers;
 }

async getCampaign({ campaignId }: NaverSearchAdCampaignDto) {
        try {
            const api_url = this.getCampaignPath;
            const url = `${this.host}${api_url}/${campaignId}`
            const headers = this.getHeaders(api_url);
            const { data } = await firstValueFrom(this.axios.get(url, {
                headers
            }));

            return data;
        } catch (error) {
            console.log("Naver.getCampaign error : ", error?.response?.data || error);
        }
}
```

결과
Naver.getCampaign error :  {
  signature: 'i6zqXeuXOiSs61ZGXP3TkPwCmgZ/RigQICPkJFN3ZUk=',
  status: 403,
  type: 'urn:naver:api:problem:invalid-signature',
  title: 'Invalid Signature',
  detail: "Signature 'i6zqXeuXOiSs61ZGXP3TkPwCmgZ/RigQICPkJFN3ZUk=' is invalid."
}

어떤 문제가 있는 건가요? getHeaders 로 받은 headers 는 Campaign: list (by customer id, campaign type), Campaign: list (by ids), Stat: get (by id) 에서는 잘 작동해서 결과까지 잘 받습니다.

답변해 주시면 감사드리겠습니다.

**Comment by naver-searchad** [comment]
@Parkjunwu 안녕하세요. 검색광고 API 담당자입니다.

Signature 생성시에 요청하시는 전체 path 를 넣으셔야합니다.

예제기준으로는 api_url 가 아닌 `${api_url}/${campaignId}` 를 기준으로 생성하셔야 정상동작할것 같습니다.

감사합니다.
