### ISSUE TITLE
네이버 브랜드 검색광고 데이터를 api로 끌어오고 싶은데 방법이 없나요?? 

### ISSUE THREAD

**Issue by bumy97** [naver/searchad-apidoc#857]
노출량만 가져오면 됩니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

브랜드 검색의 노출수 정보는 아래 API를 통해 조회 하실수 있습니다. 

STAT 
https://naver.github.io/searchad-apidoc/#/tags/Stat
https://github.com/naver/searchad-apidoc/wiki/FAQ-stat

감사합니다.
