### ISSUE TITLE
상품-키워드 순위를 확인할 수 있는 방법이 있나요?

### ISSUE THREAD

**Issue by minyeamer** [naver/searchad-apidoc#858]
#257 를 참조해서 /Stats 경로로 소재별 지연된 평균순위를 확인할 수 있는 것은 확인했습니다.
하지만 해당 소재의 각 키워드별 순위를 확인할 수는 없어보였습니다.
자사의 쇼핑 광고 상품의 키워드별 순위를 모니터링할 목적이 있는데, 해당 방법이 있나요?

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

문의 주신 소재(쇼핑검색광고 상품 포함)의 각 검색어별 노출 순위 정보를 제공하는 기능은 네이버 검색광고 서비스에 존재하지 않습니다. 또한 향후 제공할 계획도 없습니다. 

감사합니다.
