### ISSUE TITLE
product-groups 요청 문의 드립니다

### ISSUE THREAD

**Issue by jjsk109** [naver/searchad-apidoc#859]
$ACCESS_LICENSE = "";
$SECRET_KEY = "";
$CUSTOMER_ID = "";

$api = new RestApi('https://api.searchad.naver.com', $ACCESS_LICENSE, $SECRET_KEY, $CUSTOMER_ID);

$get_data = $api->GET('/ncc/product-groups');
print_r($get_data);

에러도 없이 결과가 아무것도 나오지 않아 문의 드립니다. 
혹시 서비스를 안하나요? 
아니면 광고에 상품을 등록해야 나올까요?

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.
상품 그룹을 먼저 생성하셔야 합니다.

감사합니다.
