### ISSUE TITLE
RelKwdStat 파라메터값에 대해 문의 드립니다.

### ISSUE THREAD

**Issue by blackspo** [naver/searchad-apidoc#86]
Query Parameters 중에

siteID / biztpId 이 두값은 어디에서 확인가능한지 문의드립니다.

그리고 해당샘플은 없는지도 같이 문의드립니다.

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다.

답변이 늦어 죄송합니다. 

두 인자는 비지니스 채널 (http://naver.github.io/searchad-apidoc/#/tags/BusinessChannel)에서 
조회 하시거나 혹은 마스터리포트(http://naver.github.io/searchad-apidoc/#/tags/MasterReport)의 
Business Channel (BusinessChannel) 마스터를 통해 조회 하실 수 잇습니다. 

마스터 리포트 생성 요청 및 조회 샘플코드는 이 깃텁에서 제공되고 있습니다. 
비즈채널 조회나 해당 인자를 입력하여 조회하는 연관키워드 조회 샘플은 제공되지 않고 있습니다.

감사합니다.
