### ISSUE TITLE
keyword plus restricted keywords 관련 질문입니다. 상위 AdGroup 삭제하면 속해있는 모든 restricted_keyword가 삭제되나요?

### ISSUE THREAD

**Issue by gimslab** [naver/searchad-apidoc#861]
AdGroup을 삭제하면 거기에 속해있는 모든 keyword-plus-restricted-keyword는 자동으로 삭제되나요?

아니면 AdGroup삭제 전에 명시적으로 모두 지워야하는지 궁금해서 질문합니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

광고그룹 삭제시 노출 제외 키워드 목록도 같이 삭제가 됩니다.

감사합니다.
