### ISSUE TITLE
Master Report (ShoppingProduct) 데이터 누락 원인

### ISSUE THREAD

**Issue by ROSETTA-LEE** [naver/searchad-apidoc#863]
안녕하세요~

오늘자 쇼핑상품 변경내용이 마스터리포트에 반영되지 않은채로 조회되고 있습니다.
지난 9/15에 발생했던 쇼핑 상품 마스터 오류와 유사한 이슈로 보이는데요, 요청량 과다로 인한 데이터 누락일까요?

누락데이터 샘플 : 
nad-a001-02-000000199320866
nad-a001-02-000000199321441
nad-a001-02-000000199342382

reportJobId : 17F43F8314B677CFE194AAEE5DED079E

확인에 필요한 정보가 있다면 말씀 부탁드립니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

요청량과는 무관한 현상입니다. 
현재 확인 중인데요. 혹시 삭제되지 않은 보고서 잡아이디가 있다면 알려주실수 있으실까요?

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다.

현재 해당 문제는 해결 된 상황입니다. 
그러나 향후에도 동일한 문제가 발생할 여지가 있고, 이에 대한 원인과 해결 방안 그리고 해결을 위한 마스터 기능 수정에 대해 
빠른 시일내에 공지를 드리도록 하겠습니다. 
불편을 드려 대단히 죄송합니다. 

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다.

데이터 누락 관련하여 몇가지 조치 방안이 도출되어 다행히 사용자 분들에게 영향을 주지 않고도 이전과 같은 서비스 수준을 유지할수 있을것으로 생각됩니다. 
관련된 패치는 금일 반영 예정이고, 사용상의 차이점은 전혀 없으나 예전보다 약간 더 보고서 생성에 시간이 더 걸리는(평균 수초 정도) 정도의 변화만 있을 것으로 보입니다.  따라서 기능 변경이나 관련 공지는 게시 되지 않습니다. 참고 부탁드립니다. 

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

앞서 말씀드릴때는 관련 공지는 없다고 말씀드렸는데요. 데이터 누락과 관련된 패치를 진행하던 중에 데이터 누락과는 무관하게 꽤 예전부터 있던 버그를 발견하여 이를 수정하였고 공지를 게시하게 되었습니다. 혼란을 드릴까 우려되어 코멘트 남깁니다. 
https://naver.github.io/searchad-apidoc/#/notice

감사합니다.
