### ISSUE TITLE
요일/시간 타겟팅 반영 소요 시간 문의드립니다. 

### ISSUE THREAD

**Issue by pocaaaaa** [naver/searchad-apidoc#864]
안녕하세요. 
요일/시간 타켓팅 반영 시간과 관련하여 '요일/시간대 타겟팅 수정의 경우, 반영에 최대 30분 소요됩니다' 라고 FAQ에 나와 있는데 
아래의 2개 API 사용시에도 API 호출후 실제 네이버 광고그룹에 변경된 요일/시간 타겟팅 정보가 반영되어 
네이버 광고에 적용되는 것은 최대 30분이 소요될 수 있는 건가요? 
아니면 하단의 API 사용시에는 즉시 반영이 될 수도 있는 건가요? 

1. 타겟팅 입찰가 가중치 변경
PUT /ncc/criterion/{광고그룹 ID}/bidWeight?codes={dictionaryCode 리스트}&bidWeight={입찰가 가중치 50 ~ 500}

2. 타겟팅 변경
PUT /ncc/criterion/{광고그룹 ID}/{dictionary type}

* 요일/시간 타겟팅 설정하기 FAQ : https://saedu.naver.com/help/faq/ncc/view.naver?faqSeq=872#
* searchad-apidoc : https://naver.github.io/searchad-apidoc/#/release-notes (타겟팅 입찰가 가중치 변경 및 타켓팅 변경 부분) 

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

네이버 검색광고의 광고 관리에 따른 모든 변경 (타겟팅, 입찰가, on/off 등등) 사항은 즉시 반영이 되지 않고, 최대 30분까지 소요가 될 수 있습니다.
또한 검색광고 외부 연동 데이터 (쇼핑, 플레이스 등등)는 각 데이터 저장소와의 동기 주기 및 상황에 따라 조금씩 다르게 반영이 될 수 있습니다.

감사합니다.
