### ISSUE TITLE
소재 정보는 API로 조회할 수 있으나 마스터 리포트(item=Ad)로는 다운로드 받을 수 없을까요?

### ISSUE THREAD

**Issue by grea2yru** [naver/searchad-apidoc#865]
안녕하세요?

[소재 정보를 조회하는 API](https://naver.github.io/searchad-apidoc/#/operations/GET/~2Fncc~2Fads%7B%3Fids%7D)를 이용하여 소재 정보가 있음을 확인하고 [Master Report 를 생성](https://naver.github.io/searchad-apidoc/#/operations/POST/~2Fmaster-reports)을 item=Ad로 요청하여 데이터를 다운로드 받고자 합니다.
하지만 Master Report 생성 요청 이후 Master Report 조회 API 호출하면 status=NONE 으로 보이며 downloadUrl이 존재하지 않는 응답으로 받게 됩니다.

이런 경우 어떻게해야 [소재 조회 API](https://naver.github.io/searchad-apidoc/#/operations/GET/~2Fncc~2Fads%7B%3Fids%7D)에 해당하는 Master Report 데이터를 다운로드 받을 수 있을까요?

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

소재 마스터는 모든 형태의 소재 정보를 제공하지는 않습니다. 
소재의 경우는 그 특성상 다양한 정보가 각기 다른 형태로 존재하는데 이를 표준화된 하나의 형태로 만들지 못해 각 소재 별로 마스터를 별도로 구성하였고, 이중 아예 마스터를 제공하지 않는 소재 형태(예를 들면 브랜드 검색)도 존재합니다. 
아래는 마스터에서 지원되는 소재들입니다. 

[Ad Master (Ad)](https://naver.github.io/searchad-apidoc/searchad-apidoc#ad-master-ad) : 파워링크 소재들만 지원됩니다. 
* [Ad Extension Master (AdExtension)](https://naver.github.io/searchad-apidoc/searchad-apidoc#ad-extension-master-adextension) 확장소재의 경우 일부 확장 소재 형태만 지원됩니다. 지원되는 확장 소재 내역은 스펙을 참고하여 주십시오. 

[Shopping shopping mall product Master (ShoppingProduct)](https://naver.github.io/searchad-apidoc/searchad-apidoc#shopping-shopping-mall-product-master-shoppingproduct): 기본적으로 쇼핑상품 마스터지만 쇼핑 소재를 구성하는 대부분의 정보를 담고 있어 쇼핑검색광고 쇼핑검색 유형의 소재 마스터라고 간주하셔도 무방합니다. 

[PowerContents ad Master (ContentsAd)](https://naver.github.io/searchad-apidoc/searchad-apidoc#powercontents-ad-master-contentsad): 파워컨텐츠 상품의 소재 마스터입니다. 

[Place ad ad Master (PlaceAd)](https://naver.github.io/searchad-apidoc/searchad-apidoc#place-ad-ad-master-placead) : 플레이스 광고의 소재입니다. 단, 지역소상공인 광고는 제공되지 않습니다. 

[Shopping brand product banner Ad Master (BrandBannerAd)](https://naver.github.io/searchad-apidoc/searchad-apidoc#shopping-brand-product-banner-ad-master-brandbannerad) : 쇼핑검색광고쇼핑 브랜드형 중 배너소재 마스터입니다.

[Shopping brand product thumbnail Ad Master (BrandThumbnailAd)](https://naver.github.io/searchad-apidoc/searchad-apidoc#shopping-brand-product-thumbnail-ad-master-brandthumbnailad): 쇼핑검색광고쇼핑 브랜드형 중 썸네일소재 마스터입니다.

이외에 각종 소재들에 대한 지원 방안은 계속 모색 중인데요. 현재로서는 여러가지 문제로 인해 제공을드리지못하고 있는 상황이오니 지원되지 않는 소재는 API를 호출 하여 주시는 형태로 이용 부탁드립니다. 

감사합니다.

**Comment by grea2yru** [comment]
답변 감사합니다!
