### ISSUE TITLE
campaign type별 광고 실적 레포트 문의

### ISSUE THREAD

**Issue by githubcnsbs** [naver/searchad-apidoc#866]
안녕하세요.

campaign type별로 광고실적 정보를 가져올 수 있는 StatReport reportTp 문의 드립니다. 

- WEB_SITE: AD_DETAIL
- SHOPPING: SHOPPINGKEYWORD_DETAIL
- POWER_CONTENTS: AD_DETAIL?
- BRAND_SEARCH: AD_DETAIL?
- PLACE: ?

내용 파악이 가능한 api문서 link등이 있으면 같이 공유 부탁드립니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

아래 보고서는 모든 캠페인 타입에서 발생한 광고 실적을 제공합니다. 
Ad Performance Report (reportTp: AD)
Ad Performance Detail Report (reportTp: AD_DETAIL)
Ad Extension Performance Report (reportTp: ADEXTENSION)
Conversion Report (reportTp: AD_CONVERSION)
Conversion Detail Report (reportTp: AD_CONVERSION_DETAIL)
AD extension Conversion Report (reportTp: ADEXTENSION_CONVERSION)
NAVER PAY Report (reportTp: NAVERPAY_CONVERSION)
Criterion Report (reportTp: CRITERION)
Criterion Conversion Report (reportTp: CRITERION_CONVERSION)

아래 보고서는 파워링크 상품 즉, 캠페인 타입 WEB_SITE인 캠페인에서 발생한 성과만 제공드립니다. 
Powerlink Search Term Report (reportTp: EXPKEYWORD)

아래 보고서들은 쇼핑 상품 즉 캠페인 타입 SHOPPING인 캠페인에서 발생한 성과만을 제공드립니다. 
Shopping Search Term Performance Detail Report (reportTp: SHOPPINGKEYWORD_DETAIL)
Shopping Search Term Conversion Detail Report (reportTp: SHOPPINGKEYWORD_CONVERSION_DETAIL)

아래 보고서들은 쇼핑 검색광고 상품형 중 쇼핑 브랜드형에서 발생한 성과만을 담고 있습니다.
Shopping Brand Product Performance Report (reportTp: SHOPPINGBRANDPRODUCT)
Shopping Brand Product Conversion Report (reportTp: SHOPPINGBRANDPRODUCT_CONVERSION)

대용량 다운로드 보고서(STAT REPORT)은 특정 캠페인 별로 분류되어 있지 않고 일반적인 경우 모든 캠페인 타입의 정보를 제공합니다. 이중 기존의 보고서들로 성과를 제공드리기 어려운 경우 특화 보고서를 추가로 제공드리는데요. 예를 들면 
특정 광고 구성요소 (예를 들면 Criterion), 특정 데이터 원천(예를 들면 NAVER PAY), 특정 상품형의 광고 대상 상품 (Shopping Brand Product)별로 지표를 제공드리게 됩니다. 
특화 보고서에서 지표를 제공드린다고 해서  AD나 AD_DETAIL등과 같은 일반적인 보고서에서 캠페인별, 광고그룹별, 소재별 광고 성과 정보가 빠져 있는 것은 아니며 추가로 제공 드리는 개념입니다. 

감사합니다.
