### ISSUE TITLE
Criterion Stat Report 제공 지표에 대하여 문의드립니다

### ISSUE THREAD

**Issue by ROSETTA-LEE** [naver/searchad-apidoc#867]
안녕하세요,
criterion report에서 Criterion id로는 타겟별(age, gender 등) 노출순위 합(sum of rank) 또는 평균노출순위(avgrnk)을
조회할 수 없는 것 같은데요, 혹시 이 데이터를 확인할 수 있는 방법이 있을까요?
확인 부탁드립니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

대용량 보고서외 다른 기능들도 모두 확인 하느라 답변이 늦었습니다. 죄송합니다. 
문의 주신 평균노출 순위 혹은 평균 노출 순위를 계산할수 있는 기본값인 노출 순위의 합은  Criterion별로 제공드리지 않습니다. 
찾아보니 STAT API에 값이 있기는 하나 이는 일종의 오류로 빠른 시일내에 오류가 수정될 예정입니다. 

Criterion은 캠페인/광고그룹/키워드/소재 등과 같은 광고 운영 대상이 아닌 광고 운영을 위한 설정값으로서 노출가능 광고수가 다른 여러 매체에 걸쳐 값이 생성되며, 각기 다른 광고 전략을 쓰는 광고 운영 대상의 값이 합쳐지고 있으므로 평균 노출 순위와 같이 제한적인 상황하에서 의미가 있는 값을 제공드리는 것은 부적절하다고 판단하고 있습니다. 
따라서 해당 값을 향후에도 제공드릴 가능성은 없다고 생각해 주시면 되겠습니다. 

감사합니다.

**Comment by ROSETTA-LEE** [comment]
답변 감사드립니다.
현재 광고센터에서 제공하는 맞춤보고서에는 타겟팅이 적용된 광고그룹을 대상으로
평균노출순위를 추가하여 조회할 수 있도록 하고 있습니다.
API로는 breakdown 중 디바이스(PC/M)와 기간 단위로만 해당 수치를 조회할 수 있는데요,
향후에도 성, 연령 등의 타겟별로는 평균노출순위 관련 데이터를 API로 조회할 수 없는걸까요?

**Comment by hyunah00** [comment]
안녕하세요, 다차원보고서 담당자입니다.
다차원보고서에서는 criterion의 관점에서는 보고서를 제공하고 있지 않습니다.

확인하실 수 있는 "타겟팅 구분"은 설정된 타겟팅인 criteion의 개념이 아니라 전체 성과를 구분하는 항목의 개념입니다.
따라서 해당 데이터를 참조해서 타겟팅 설정에 참고하실 수 있는 것이지 설정된 타겟팅(criterion)의 성과가 아닙니다.
예를 들어 "지역"의 경우 criteion의 일환이라면 추가하거나 제외한 지역 설정 값의 데이터가 보여야 하는데 
다차원보고서에서는 전체 성과를 지역으로 나눠만 볼 수 있습니다.

**Comment by naver-searchad** [comment]
안녕하세요, 다차원보고서 담당자입니다.

답변을 모두 달지 못했는데 코멘트 버튼을 클릭해서 추가로 답변 드립니다. 
복잡하지만 저희 광고의 구조적인 설명을 드리긴 했는데요. 결론적으로는 criteion ID별로는 평균노출 순위 정보를 제공드리지 않습니다. STAT의 경우도 criteion ID를 조회 대상즉 입력 인자로 사용하시는 경우에는 평균노출 순위 정보를 제공드리지 않게 됩니다. 

감사합니다.

**Comment by ROSETTA-LEE** [comment]
> 안녕하세요, 다차원보고서 담당자입니다. 다차원보고서에서는 criterion의 관점에서는 보고서를 제공하고 있지 않습니다.
> 
> 확인하실 수 있는 "타겟팅 구분"은 설정된 타겟팅인 criteion의 개념이 아니라 전체 성과를 구분하는 항목의 개념입니다. 따라서 해당 데이터를 참조해서 타겟팅 설정에 참고하실 수 있는 것이지 설정된 타겟팅(criterion)의 성과가 아닙니다. 예를 들어 "지역"의 경우 criteion의 일환이라면 추가하거나 제외한 지역 설정 값의 데이터가 보여야 하는데 다차원보고서에서는 전체 성과를 지역으로 나눠만 볼 수 있습니다.

답변 감사합니다.
다차원보고서는 전체성과를 타겟팅 종류로 구분한 데이터이고 타겟팅 설정인 criterion과는 별개의 개념으로 이해하였습니다.
사실 제가 필요한 데이터가 이것이었는데요, 혹시 searchad api로 조회하는 방법은 없을까요?

![stat report api](https://github.com/naver/searchad-apidoc/assets/87587045/868f6fcc-3331-463c-8217-2f4c75a828ef)

위와 같이 대용량보고서(stat report)에서 관련 성과를 제공하는 것으로 이해하여 혼선이 있었던 것 같습니다.

그럼 답변 부탁드리겠습니다. 감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

질문자 분께서 달을 가리키고 있었는데 제가 손가락인 criterion만 바라보고 있었네요. 
죄송합니다. 
문의 주신 사항은 다차원보고서 처럼 age나 gender 별 지표를 STAT이나 STAT-REPORT 혹은 다른 API에서 찾을수 있는가?
없다면 줄 계획이 있는가?라고 이해 됩니다. 

첫번째 문의 주신 내용에서 현재 다차원보고서에서 제공되는  age나 gender 별 지표를 제공드리고 있는 API 기능은 존재하지 않습니다. 향후에 제공할 것인가에 대해서는 다차원의 경우도 향후에는 criterion 을 이용한 타게팅 구조를 바탕으로 지표를 제공 드리는 방향으로 변경되어 갈 것이므로 향후에도 제공드리게 되지는 않을 것으로 생각됩니다. 

감사합니다.
