### ISSUE TITLE
IpExclusion API 반환 데이터 문의

### ISSUE THREAD

**Issue by SM10855** [naver/searchad-apidoc#869]
안녕하세요.

GET /tool/ip-exclusions
해당 API에서 반환받는 데이터가 regTm 기준으로 정렬이 오름차순, 또는 내림차순인지 문의드립니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

응답값에 대해 정렬은 Client에서 기준에 맞춰 진행하셔야 합니다.
응답값의 순서에 대해서는 보장하지 않습니다.

감사합니다.
