### ISSUE TITLE
RelKwdStat 호출 시 오류

### ISSUE THREAD

**Issue by nambak** [naver/searchad-apidoc#87]
RelKwdStat 호출 시 오류 메세지가 'Invalid Parameter, There are invalid parameters'라고 나오는데 혹시 hintKeywords 파라메터에 빈 공백이나 . 같은 문자가 들어가면 안되는 것인가요?

**Comment by naver-searchad** [comment]
@nambak 

안녕하십니까 검색광고 API 담당자입니다. 

hintKeywords 의 경우 저희 광고 등록 키워드의 허용 캐릭터셋과 동일한 규칙이 적용 됩니다.

저희 허용 캐릭터 셋은 아래와 같습니다. 
영문자(소문자 입력시 대문자로 변환되어 조회됨), 한글, 로마자, 한자, 일본어(히라가나 가타카나),
일부 특수문자 입력이 가능합니다. 
허용가능 charset: "#&.=+%?!;_@()~'\\/a-zA-Z0-9가-힣ㄱ-ㅎㅏ-ㅣ
공백은 허용되지 않으므로 에러가 발생하게 됩니다.

감사합니다.
