### ISSUE TITLE
쇼핑 광고 소재 등록  862번 이슈 답변 부탁드립니다

### ISSUE THREAD

**Issue by blueleo77** [naver/searchad-apidoc#870]
안녕하세요.

https://github.com/naver/searchad-apidoc/issues/862

상기 문의에 대한 답변만 넘어간 상황입니다.
저희도 고객사에 얘기할 내용이 있어야 되는데요.
호출 방식이 잘못되었으면 올바른 호출 방식을 안내해 주시거나,
혹시 내부에 이슈가 있으면 배포 일정이라도 공지해 주시면 좋겠습니다.

그럼 확인 부탁드립니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고입니다.
쇼핑 검색의 광고 소재는 API를 이용하여 등록하지 않도록 권고하고 있습니다.
소재 등록에 필요한 nvmid (네이버 쇼핑에서 관리하는 내부 상품 ID) 값을 조회할 수 없기 때문입니다.


감사합니다.

**Comment by blueleo77** [comment]
권고하지 않는다면 가능은 한데 추천되지 않는다는 의미인 것 같습니다.
어떻게 호출하면 소재 등록이 가능한지도 함께 안내해 주시면 좋겠습니다.

감사합니다.
