### ISSUE TITLE
공유예산 적용 캠페인, 광고그룹의 일예산 변경 시 적용 결과 상이

### ISSUE THREAD

**Issue by yuhee62wang** [naver/searchad-apidoc#871]
안녕하세요!
공유예산 적용 중인 캠페인과 광고그룹의 일예산 변경 관련 문의드립니다.

광고플랫폼 어드민에서는 공유예산을 적용 중인 캠페인과 광고그룹의 일예산 변경 불가, 공유예산 제외 후 가능 - 으로 알고 있는데요,

update 메서드 호출로 공유예산을 적용 중인 캠페인과 광고그룹의 일예산을 변경하면 
(dailyBudget, updateDailyBidAmt() 둘 다 동일한 결과) 

1) 캠페인은 sharedBudget 이 해제되고 일예산이 변경됨
2) 광고그룹은 sharedBudget 이 해제 안되고 일예산도 변경 안 됨

질문1) 왜 캠페인과 광고그룹의 결과가 다른가요?? 
질문2) 혹시나 의도한 게 아니라면 추후 하나로 통일할 계획이 있으신가요? (대략적 예상 시점도 궁금합니다!) 
질문3) 통일한다면 캠페인처럼 or 광고그룹처럼 중 어느 쪽으로 통일하려나요? 

바쁘실테지만 답변 기다리겠습니다 !
감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고입니다.

공유예산이 설정된 캠페인의 dailyBudget을 변경하면 광고그룹과 동일하게 공유예산이 해제되지 않고 dailyBudget이 변경되지 않도록 차주 중으로 수정되어 반영될 예정입니다.

감사합니다.
