### ISSUE TITLE
RelKwdStat API 데이터 업데이트 관련 건

### ISSUE THREAD

**Issue by choics** [naver/searchad-apidoc#872]
현재 RelKwdStat 데이터가 전일 조회한 데이터와 금일 조회한 데이터의 변동이 없는 것으로 확인되고 있습니다.

관련하여 확인 부탁드립니다.

**Comment by naver-searchad** [comment]
안녕하세요. 네이버 검색광고입니다.

혹시 말씀주신 RelKwdStat 지표 중, 어떤 키워드의 지표가 변동이 없었는지 알 수 있을까요?

감사합니다.

**Comment by choics** [comment]
현재 시점 조회 결과 monthlyPcQcCnt, monthlyMobileQcCnt 지표는 변동이 있으나
그 외 지표는 변동이 없는 것으로 확인되고 있습니다.
정상 업데이트 된 것일지 확인 부탁드립니다.

**Comment by naver-searchad** [comment]
확인 감사합니다.

- monthlyPcQcCnt, monthlyMobileQcCnt 지표는 업데이트 지연이 확인되어 현재 조치 완료였습니다.
- 그 외 지표는 일별로 업데이트 되는 지표가 아니므로 현재 정상 상황입니다.

감사합니다.
