### ISSUE TITLE
Master Report  Criterion 에 대한 질문 

### ISSUE THREAD

**Issue by moominbelly** [naver/searchad-apidoc#873]
안녕하세요, 
Master Criterion  Report  에 관련해 질문 드립니다. 
현재 광고설정  UI 상으로 타겟팅이 남성, 여성, 알수없음 이렇게 세가지로 설정이 된 경우 api로 호출하는 Master Report 상에 TYPE이 GN 인것이 보이지 않는데  이부분은 어떻게 해결해야 하나요 ? 

이해한 바로는 광고설정 ui에서  모든 연령이나 모든 요일, 모든 성별로 선택시에는 타겟팅 사용하지 않음으로 설정이 되어 Master report  상에 나오지 않는 것인데,   ui 상에서는 성별은 모든 성별을 선택하나 , 노출 성별 선택(세가지 항목  on  한 경우)을 선택하나  남성, 여성, 알수없음으로 설정이 되어 나옵니다. 이 경우에는 GN이 master report 에 표시가 되는 경우와 표시가 되지 않는 경우가 있는데 이 두가지의 차이가 무엇인지 궁금합니다.

**Comment by moominbelly** [comment]
안녕하세요, 
네, 정리주신 내용이 맞습니다.

**Comment by moominbelly** [comment]
답변 감사합니다. 
이해한 바로는 
1. 타겟 설정을 한번도 안한 경우 => criterion master report 에서 보여지지 않음. 단, 광고 관리 화면에서는 성별값이 보임(하지만 이 값은 타겟팅을 설정해서 보여진 값이 아니라 자동으로 보여짐. 즉 타겟팅에 따른 퍼포먼스가 아님)
2. 타겟 설정을 한 경우 =>  criterion master report 에서 보여줌, 광고 화면에서도 퍼포먼스 확인 가능. 
이 맞을까요 ?

그럼, 타겟 설정을 한 경우, criterion master report 값과 광고 관리 화면상 성별 (남/여/알수없음)의 노출 클릭 전환수가 같게 표시되는 것이 맞나요 ?

또한  criterion master report 만으로 타겟설정이 되지 않는 경우를 판별할 수 있는 방법이 있을까요 ?

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드보고서 담당자입니다. 

이해하신 바에 약간에 오해가 있어 보입니다. 

마스터는 저희 광고 정보 (흔히 말하는 광고 메타 데이터)를 제공드리는 기능입니다. 
타게팅 마스터는 저희 DB 내 criterion 테이블에 있는 정보를 그대로 제공드리게 되는데요. 
즉 마스터는 설정값을 제공드리지 이 정보 자체는 광고 성과(퍼포먼스) 즉 지표는 제공드리지 않습니다. 따라서 마스터에 정보가 있고 없음과 지표 간에는 큰 관련이 없습니다. 

제가 설명드린 내용은 마스터 즉 저희 DB에 criterion 아이디가 생성되는 기준을 말씀드린것으로 지표에 대한 설명을 드린 것은 아니며, STAT-REPORT의 Criterion Report (reportTp: CRITERION)및 Criterion Conversion Report (reportTp: CRITERION_CONVERSION) 가 지표를 제공드리는 보고서 입니다. 
위의 두보고서 경우는 UI(STAT)와는 달리 Criterion에 Criterion ID가 존재하는 경우에만 값이 제공됩니다. 

종합해서 답변 드리면 

> 1. 타겟 설정을 한번도 안한 경우 => criterion master report 에서 보여지지 않음. 단, 광고 관리 화면에서는 성별값이 보임(하지만 이 값은 타겟팅을 설정해서 보여진 값이 아니라 자동으로 보여짐. 즉 타겟팅에 따른 퍼포먼스가 아님)

네 이해하신 내용이 맞습니다.  타게팅 퍼포먼스의 의미가 조금 다를수 있긴 한데 이 단어를 "내가 설정한 타게팅에 대한 성과"라고 표현하면 말씀주신 내용이 맞습니다. 

>2. 타겟 설정을 한 경우 => criterion master report 에서 보여줌, 광고 화면에서도 퍼포먼스 확인 가능.
이 맞을까요 ?

이 부분에서 약간 오해의 소지가 있어 보입니다. 지표를 제공드리는 부분은 UI와 대용량 보고서(STAT-REPORT)가 있는데요.
UI에서는 내가 설정을 하든 안하든 무조건 지표를 보여줍니다. 대용량보고서에서는 설정을 한(즉 criterion ID가 존재하는) 경우에만 지표가 제공됩니다. 물론 설정을 하신후에 UI와 대용량 보고서를 비교해 보시면 값이 같아야 합니다. 

>또한 criterion master report 만으로 타겟설정이 되지 않는 경우를 판별할 수 있는 방법이 있을까요 ?

판별은 간단합니다. criterion ID가 존재하는 경우만 설정된 것입니다. 물론 타게팅 설정의 종류는 네가티브(노출안함)인지 포지티브(노출함)가 있고 이는 criterion 마스터를 통해 확인이 가능합니다. 

감사합니다.

**Comment by moominbelly** [comment]
안녕하세요, 아 네! 지표 관련 내용은  master 가 아닌 stat report라고 하는것을 잘못 적었네요 ! 
다시 정리하자면 
1. master report 에는 criterion id가 있는 경우만 나옴 (타겟팅을 설정한 경우.)
2. criterion id 값이 있는 경우에만 stat report에서 지표를 확인 할 수있는데, criterion id가 없는경우에도  ui상에서 확인시에는 타겟팅 설정을 안해도 default 로 무조건 값이 보임. 
3. criterion id 값이 있는 경우에 나오는 지표 (노출,클릭,비용,전환등)는 ui로 확인할때는 값이 stat report와 같게 나옴. 
4. criterion id 값이 없는 경우는 타게팅을 설정하지 않은 광고로 봄. 

이렇게 보는것이 맞을까요 ? 
감사합니다.

**Comment by moominbelly** [comment]
@naver-searchad  안녕하세요, 담당자님,제가 다시 확인한 바로는 연령과 성별에 대한 criterion id 가 criterion master report 에 없어도 criterion stat report 에 성별과 연령에 대한 내용이 나옵니다. 이 경우는 왜 성별과 연령에 대한 내용이 나오나요? 
위에서 이해한 바로는 criterion id가 있는 것에 한하여 stat report지표를 확인할 수있다 인데 , 설정이 되어 있지 않은 내용까지 나오는 부분은 어떤 이유일까요 ? (ui상에서는 성별/연령별은 나오는것까진 이해를 했습니다.)

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

MASTER에 존재하지 않는 criterion id 로 STAT REPORT에 지표가 있다는 말씀이시지요?

위와 같은 현상이 있는 criterion id를 몇개 정도 샘플로 알려 주실수 있으실까요?

감사합니다.

**Comment by moominbelly** [comment]
네 맞습니다 ! 
master 에 존재하지 않는 criterion id중 몇가지 추려 보내드립니다. 

grp-a001-01-000000013401096~AG4044
grp-a001-01-000000013401096~AG1418
grp-a001-01-000000013401096~GNF
grp-a001-01-000000013401096~GNM

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

죄송합니다. 제가 대용량 보고서쪽 지표에서 착각을 했습니다. 
STAT-REPORT나 STAT(UI의 API) 모두 동일한 데이터 소스를 쓰고 가공 정도가 다른 것 뿐이라 대용량 보고서에서도 성별/나이 타게팅의경우 설정을 하지 않아도 값이 제공됩니다. 

크라이테리온 아이디는 딕션어리코드와 해당 타게팅이 설정된 오너 아이디(현재는 광고그룹)의 아이디로 구성된 일종의 조합키 이므로 마스터에 없더라도 쉽게 구분이 가능합니다. 

추가로 성별/나이 외의 타게팅은 크라이테리온 ID가 설정된 상태 즉 타게팅이 설정된 상태에서만 값이 제공됩니다. 

혼란 드린점 다시 한번 사과 말씀드립니다.

감사합니다.
