### ISSUE TITLE
마스터 리포트가 만들어지지않네요.

### ISSUE THREAD

**Issue by develop-kjy** [naver/searchad-apidoc#875]
생성요청 상태에서 완료로 바뀌질않네요.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

한국표준시 기준 생성 요청 일시와 JOB ID를 알려 주실수 있으실까요?

감사합니다.

**Comment by develop-kjy** [comment]
아 지금은 만들어졌습니다. 너무 오랜시간 생성요청에서 넘어가질않아서 문의드린거였어요.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

마스터 생성이 지연되는 대표적인 케이스로는 아래와 같은 케이스가 있습니다. 

1. 평일 오전 8시~10시 사이 시스템 전체의 사용량이 많아져서 느려집니다. 
2. 대상 계정에 API를 통한 대량 호출 혹은 광고 관리시스템 내의 대량 작업이 작동되고 있는 시점에는 약간 느려집니다. 
3. 시스템 메인터넌스가 있거나 신규 기능/패치 등이 배포되는 시점 
4. 비정기 점검등 점검이 있는 경우, 이 경우에는 별도 공지가 됩니다. 
5. 실제로 느려지는 케이스는 아니나 광고 관리 시스템 내 대용량 다운로드 보고서> 마스터 메뉴에서 마스터 생성시 화면 새로고침 기능이 존재하지 않으므로 생성이 되었더라도 이를 인지하지 못하는 경우가 많습니다. 

물론 느려진다고 해도 아주 약간 느려지는 정도이지 오랜 시간 생성이 안되지는 않습니다. 
평소보다 아주 느려진 경우 (예를 들어 평소 10분 정도면 생성되던 마스터가 1시간이 지나도 생성중으로 표시되는등) 잡아이디와 생성 요청 시점을 알려 주시기를 부탁드립니다.

감사합니다.
