### ISSUE TITLE
키워드가 통합검색 순위에 나타나지 않습니다.

### ISSUE THREAD

**Issue by kaorimikage** [naver/searchad-apidoc#876]
어제 저녁부터 통합검색에서 1위하던 키워드가 표시되지 않습니다.
더보기를 하면 1위를 하고 있습니다.

이 현상에 대해 알 수 있는 방법이 있을런지요.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

이곳은 API 관련 기술 문의를 하는 곳으로 각 기능별 담당 개발자 분들이 답변을 드리고 있습니다. 
문의 주신 사항은 광고 노출 및 입찰 관련 사항으로 이 기능들은 API 기능과는 크게 관련이 없어 이곳에 계신 분들은 답변을 드릴수가 없는 사항입니다. 네이버 검색광고 고객센터로 문의를 주시기를 부탁드립니다. 혹 대행사 소속이시라면 대행사 문의 채널을 이용하여 주시기를 부탁드립니다.(사내에 알아 보시면 문의 채널을 찾으실수 있습니다.)
고객센터 : https://saedu.naver.com/help/faq/ncc/index.naver#

이와는 별개로 문의 주신 내용을 볼때 우선 체크해 보실 부분은 광고 노출 매체 설정인데요. 
해당 키워드가 속한 광고그룹의 광고 노출 매체 설정을 한번 확인해 보시는 것이 좋을것 같습니다. 

감사합니다.
