### ISSUE TITLE
/stats 에서 "code":11001 리턴 관련 문의드립니다.

### ISSUE THREAD

**Issue by sannamchon** [naver/searchad-apidoc#878]
안녕하세요, 네이버 검색광고를 집행하고 있는 광고주입니다.
네이버 검색광고 리포트 API에서 키워드 단위로 리포트를 호출하고 싶어 리퀘스트 했으나 더 진행이 어려워 문의글 남깁니다.

환경은 구글 앱스스크립트이며 JSON 문자열화 후 인코딩하여 쿼리 부분을 전송했습니다.
x-transaction-id는 c55ed1fdf8b5b0c7 이며 쿼리의 내용은 아래 디테일하게 전달드립니다.

어떤 부분에서 잘못된 파라미터가 전달되고 있는 지 어떻게하면 이 문제를 해결할 수 있는 지 알려주시면 감사하겠습니다.

회신 부탁드립니다.

오전 9:13:39	정보	query: ?ids=%5B%22nkw-a001-01-000002612185136%22%2C%22nkw-a001-01-000002612185138%22%2C%22nkw-a001-01-000002612185140%22%2C%22nkw-a001-01-000002612185142%22%2C%22nkw-a001-01-000002612185147%22%2C%22nkw-a001-01-000002612185148%22%5D&fields=%5B%22impCnt%22%2C%22clkCnt%22%2C%22salesAmt%22%2C%22avgRnk%22%2C%22ccnt%22%2C%22pcNxAvgRnk%22%2C%22mblNxAvgRnk%22%2C%22crto%22%2C%22convAmt%22%2C%22ror%22%2C%22cpConv%22%2C%22viewCnt%22%5D&timeRange=%7B%22since%22%3A%222023-12-10%22%2C%22until%22%3A%222023-12-11%22%7D
오전 9:13:41	정보	x-transaction-id: c55ed1fdf8b5b0c7
오전 9:13:41	정보	response: {"code":11001,"message":"잘못된 파라미터 형식입니다."}

**Comment by kyungryongLee** [comment]
문의사항이 또 생겨서 댓글로 남깁니다 ㅠㅠ 대용량보고서를 생성하려고 post 방식으로 리퀘스트하여 돌아오는 response 코드는 200으로 정상이나, 네이버 검색광고 어드민 페이지에서 확인해볼 때는 대용량보고서가 생성되지 않는 것으로 보입니다. response 코드가 200으로 정상처리된 것으로 보이기 때문에 요청 보내는 입장에서는 어떤 부분에 문제가 있는지 파악이 어렵습니다. 제가 제대로 요청을 보낸 것인지 확인을 요청드립니다.

HTTP request는 POST 방식으로 /stat-reports에 전달하였으며 전달되는 파라미터, x-transaction-id는 다음과 같습니다.

파라미터: {method=POST, headers={X-Signature=<SIGNATURE>, Content-Type=application/json; charset=UTF-8, X-API-KEY=<API-KEY>, X-Customer=<CUSTOMER>, X-Timestamp=1702428327947}, payload={"reportTp":"AD","statDt":"20231212"}}
x-transaction-id: 75e05170c6cbfd40

제가 개발자가 아니어서 개발에 미숙한 부분이 많다보니 실수가 많은 거 같습니다. 확인 꼭 부탁드리오며, 요청의 어떤 부분에 문제가 있는지 알려주시면 감사하겠습니다.

아래는 실행 로그입니다.


오전 9:45:27	알림	실행이 시작됨
오전 9:45:27	정보	{method=POST, headers={X-Signature=<SIGNATURE>, Content-Type=application/json; charset=UTF-8, X-API-KEY=<API-KEY>, X-Customer=<CUSTOMER>, X-Timestamp=1702428327947}, payload={"reportTp":"AD","statDt":"20231212"}}
오전 9:45:29	정보	x-transaction-id: 75e05170c6cbfd40
오전 9:45:29	정보	ResponseCode: 200
오전 9:45:29	정보	Logging output too large. Truncating output. [{loginId=brandsearch, updateTm=2023-11-19T15:00:00Z, reportJobId=2.070100143E9, reportTp=AD, downloadUrl=...

**Comment by sannamchon** [comment]
문의사항이 또 생겨서 댓글로 남깁니다 ㅠㅠ 대용량보고서를 생성하려고 post 방식으로 리퀘스트하여 돌아오는 response 코드는 200으로 정상이나, 네이버 검색광고 어드민 페이지에서 확인해볼 때는 대용량보고서가 생성되지 않는 것으로 보입니다. response 코드가 200으로 정상처리된 것으로 보이기 때문에 요청 보내는 입장에서는 어떤 부분에 문제가 있는지 파악이 어렵습니다. 제가 제대로 요청을 보낸 것인지 확인을 요청드립니다.

HTTP request는 POST 방식으로 /stat-reports에 전달하였으며 전달되는 파라미터, x-transaction-id는 다음과 같습니다.

파라미터: {method=POST, headers={X-Signature=, Content-Type=application/json; charset=UTF-8, X-API-KEY=, X-Customer=, X-Timestamp=1702428327947}, payload={"reportTp":"AD","statDt":"20231212"}}
x-transaction-id: 75e05170c6cbfd40

제가 개발자가 아니어서 개발에 미숙한 부분이 많다보니 실수가 많은 거 같습니다. 확인 꼭 부탁드리오며, 요청의 어떤 부분에 문제가 있는지 알려주시면 감사하겠습니다.

아래는 실행 로그입니다.

오전 9:45:27 알림 실행이 시작됨
오전 9:45:27 정보 {method=POST, headers={X-Signature=, Content-Type=application/json; charset=UTF-8, X-API-KEY=, X-Customer=, X-Timestamp=1702428327947}, payload={"reportTp":"AD","statDt":"20231212"}}
오전 9:45:29 정보 x-transaction-id: 75e05170c6cbfd40
오전 9:45:29 정보 ResponseCode: 200
오전 9:45:29 정보 Logging output too large. Truncating output. [{loginId=brandsearch, updateTm=2023-11-19T15:00:00Z, reportJobId=2.070100143E9, reportTp=AD, downloadUrl=...
