### ISSUE TITLE
/stats 호출시 Bad Request, transactionId : bb230eb78e1e8de5

### ISSUE THREAD

**Issue by SM11295** [naver/searchad-apidoc#879]
안녕하세요

/stats 호출시 위에 트랜잭션 ID 와 함께 Bad Request가 뜹니다
ids  파라미터갯수가 100개 이상인데 혹시 갯수가 많아서 일까요?

확인 부탁드립니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

ids 파라미터는 100개 이상의 id 갯수도 요청하실 수 있습니다.
다른 문제가 있는 지 확인해 주세요

감사합니다.
