### ISSUE TITLE
How long will you update managed keywords's info

### ISSUE THREAD

**Issue by developerlicw** [naver/searchad-apidoc#88]
Hello,
In the API, there is a "Managed Keywords", and it can return the PCPLMaxDepth and other information.
Now I am trying to use it, but not sure whether this will be updated quite often. Let's say for one keyword "iphone", will its PCPLMaxDepth change as time goes by? Let's say 3 on Monday and 15 on Tuesday?

Looking for your response, thanks.

**Comment by naver-searchad** [comment]
hi 

Changes to the "Managed Keywords" are irregular. Because  it is determined by the general search intention of the users searching. However, it does not change in real time or change frequently, and usually changes once or twice a month. Also, most keywords rarely change.

thanks

**Comment by developerlicw** [comment]
Thanks very much. :)

**Comment by developerlicw** [comment]
Sorry for reopening it.
I have another question whether the managed keyword is related to account.
As you know, when using the API, we must have account id and secret keys, will the managed keyword return different information when using different account and keys?
Besides, I saw there is somehow "editTm" and "regTm" in the document:http://naver.github.io/searchad-apidoc/#/definitions/ManagedKeyword
but never found them from the request response. 
Thanks.

**Comment by naver-searchad** [comment]
HI. 


The managed keyword  is information that belongs to the keyword and is independent of your account. Please provide the transaction ID of the different result of the information. Let's check the details.
In addition, regtim and edittm will check and respond again.

Thanks

**Comment by developerlicw** [comment]
Hi, 
Sorry for the late reply.
Thank you for the explanation. So managed keywords are only based on keywords, no relationship with accounts, I see.
Sorry but what do you mean by "provide the transaction ID of the different results"? I think it has nothing to do with transaction.

**Comment by developerlicw** [comment]
Hello,
Sorry for disturb again. I found another question and hope for some help:

In the "managed keyword" API, I can get slot information: PCPLMaxDepth, and it is always 3 or 15.
And in the keyword performance report: Performance Report (reportTp : AD), there is sumOfAdRank and impression, and I can get average rank by sumOfAdRank/impression. 
This average rank is always smaller than 3 or 15, but it can be 200 or larger. How can it be so large if slot is only 3 or 15? 

Actually I tried using naver to search for iphone, and I found there is a "view more" below the "power link" area. And after clicked, it will give lots of products. So I wonder if my link is not directly displayed in the search result, but in the "view more" page, it will also have 1 impression, is it right?

I'm looking forward to your reply.  Or is there any document explaining it?

Thanks and best regards.

**Comment by naver-searchad** [comment]
Hi. 

"provide the transaction ID of the different results" 
--> 
If you receive different values ​​for the same keyword when the customer id is changed, you are told to have the value of the x-transactionID entry in the returned message, respectively.


 PCPLMaxDepth provides the maximum number of "Power Link ads" that can be viewed on the PC Naver search media (search.naver.com), ie. ads exposed on other mediums, such as mobile Naver Search (m.search.naver.com) Information is not provided. Therefore, when calculating the average rank, it should be limited to search.naver.com (media id: 27758).

tnanks

**Comment by developerlicw** [comment]
Hi,
Thanks for your kind reply. 
I can see why I've got so huge average ranks now.

By the way, is there a list of naver media ids? such as : 27758 stands for search.naver.com  , or something like this? Actually I've found only this page: http://naver.github.io/searchad-apidoc/#/guides, and you know that seems to be really not enough information.

Thanks and best regards.

**Comment by naver-searchad** [comment]
Hello 

I'm really sorry. I missed your last question. 
You can download the complete list through MASTERREPORT.
The report name is Media Details and its argument is item = Media.
The report specification can be found at the link below. 
http://naver.github.io/searchad-apidoc/#/operations/POST/~2Fmaster-reports

One thing to note is that the name of the media is written in Korean.
The media name is the unique name of the media, so it is not translated into English. So if you think about the medium, think about it based on the URL.

Thanks

**Comment by developerlicw** [comment]
Hello,

Thanks very much for the reply.
I will download the report and pay attention to the media name, thank you a lot.
