### ISSUE TITLE
API KEY ERROR 일시적 발생 관련 문의

### ISSUE THREAD

**Issue by githubcnsbs** [naver/searchad-apidoc#880]
안녕하세요.

 API KEY ERROR 가 발생하다가 다시 정상적으로 사용이 되고 있어 어떤 현상인지 문의드립니다.

 아래는 12월 12일(어제) 하루 발생한 내용입니다. 

customer id - 발생시각
- 1735496: 10:29분 / 22:29분
- 2856706: 14:28분
- 2889282: 21:27분
- 1735474: 23:28분

**Comment by naver-searchad** [comment]
@githubcnsbs 안녕하세요. 네이버 검색광고 API 담당자입니다.

말씀주신 시점에 해당 광고주 요청을 확인해보았는데 특별한 인증 오류는 확인하지 못하였습니다.

실패시의 정확한 trasaction-id ( 응답헤더에 포함 ) 를 알려주시면, 추가로 확인해보도록 하겠습니다.

**Comment by githubcnsbs** [comment]
오늘도 아래 시각에 동일현상 발생하였습니다. 
- 2856706: 16:39:31초에 발생
- 2889282: 13:57:48초에 발생

이후로는 동일 api key로 정상 동작함.

 간헐적으로 발생하는 현상으로 재현이 어려우며, 현재 저희 log상으로 transaction-id 헤더를 볼 수 없는데 시간과 account로 확인은 어려운 것일까요. 발생 당시의 header 확인을 위하여 운영서버에 배포하여야 하는 어려움이 있습니다.

 저희 시스템 내 많은 계정 중에 특정 광고주의 계정에서만 이런 현상이 발생합니다.

**Comment by naver-searchad** [comment]
@githubcnsbs 님 안녕하세요.

2856706 광고주의 해당 시간대에 로그를 확인해보니
16:39:30.727 에 403 오류를 확인할수 있었습니다.

해당 요청에 함께 보내신 timestamp 을 확인해보니 1702453110720 으로 확인되었는데요. 
해당 값을 변환해보면 16:38:30.720 으로, 실제 서버시간과 차이가 있어서 invalid timstamp 오류가 발생하였습니다.

다른 성공한 요청을 보면 제대로된 timestamp 값을 보내시는것을 확인할수 있었는데요.
timestamp 생성후 요청을 보낼때 딜레이가 생기는 경우가 있는지 확인해보시면 좋을것 같습니다.

감사합니다.

**Comment by githubcnsbs** [comment]
네, 상세한 답변 감사드립니다.
