### ISSUE TITLE
대용량 다운로드 보고서 > 광고 정보 일괄 다운로드 > 타겟팅대상마스터 - 변경사항 매우 많은데 '데이터 없음' 상태

### ISSUE THREAD

**Issue by yuhee62wang** [naver/searchad-apidoc#881]
안녕하세요. 

2023년 12월 12일에 타겟 수정을 약 200건 정도 시행했고 (이력 관리에서 확인함)
12월 12일자 대용량 다운로드 보고서 > 광고 정보 일괄 다운로드 > 타겟팅대상마스터 를 받으면 '데이터 없음' 상태로 나옵니다. 

왜그런가요~?

오전에도 12월 12일자 수정 변경분 마스터리포트를 호출하니 9월에 삭제된 데이터가 나오거나 null 컬럼으로 오류가 나서 재수집을 거듭하느라 애먹는데요, 

뭔가 에러가 있는지요? 공지가 아직 없어서 따로 문의드립니다.
 
![image](https://github.com/naver/searchad-apidoc/assets/134270159/dcaf8f1e-029d-4fcd-a981-d4e7279f7361)
![image](https://github.com/naver/searchad-apidoc/assets/134270159/ac881e1d-15f9-458f-90a7-b77c42a45658)

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

저희가 가용량 확대를 위해 장비 교체나 스토리지 추가 등의 작업을 수시로 실시하고 있는데요. 최근에는 12월 초에 해당 작업이 있었습니다. 
현상으로 봐서는 아마도 위의 작업으로 인한 변경분 누락일 가능성이 있어 보이는데요. 
커스터머 아이디를 알려 주실수 있으실까요?

감사합니다.

**Comment by yuhee62wang** [comment]
612164 입니다 !

**Comment by hon9hb-dbase** [comment]
@naver-searchad 

안녕하세요, 2290553 도 확인 부탁드립니다.
![image](https://github.com/naver/searchad-apidoc/assets/88298771/c9aec798-3540-4652-b2da-f73d3f74d5c3)

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

답변을 드리기 앞서 "타게팅"이라는 용어가 저희 서비스 내에서 혼재되어 사용되어 혼란을 드리게 된 점 사과의 말씀을 드립니다. 
현재 저희 검색광고 서비스에서는 지난 2022년 부터 타게팅 관리 방식과 구조를 개편하는 와중에 있으며 여러가지 광고 집행 상의 부작용을 피하기 위해 점진적으로 적용 중이다 보니 아직 모든 체계가 새로운 관리 방식으로 전환된 상황은 아닙니다. 
관련 공지 https://saedu.naver.com/notice/view.naver?notiSeq=3868, https://saedu.naver.com/notice/view.naver?notiSeq=4151
개편 전에는 대부분의 타게팅을 마스터보고서가 대응하지 못하고 있는 상황에 비해 나아지고 있기는 합니다만 
아직 criterion 마스터가 타게팅 전체 항목을 모두 담지 못하고 있습니다. 
한편, 과거의 타게팅으로 간주했던 제외 키워드나 매체 설정 등을 타게팅의 일종으로 볼지 아니면 단순한 광고 집행 설정으로 볼지 여부에 대해서도 아직은 확실한 결론이 나지 않은 상황으로 현재 UI 상 용어가 혼재되어 사용되고 있는 상황입니다. 
이로 인해 변경 이력 상 타게팅 설정 변경으로 표시 되나 criterion 항목이 아니라서 마스터에서는 제공되지 않는 등 과도기의 혼란스러운 상황이 발생하고 있는데요. 
현재 예시로 보여주신 제외키워드 설정, 미디어 설정은 TARGET(https://naver.github.io/searchad-apidoc/#/tags/Target)에 속한 기능으로서 이전 부터 마스터로는 지원이 되지 않는 항목들입니다. 이중 일부는 타게팅 개편이 완료되면 critrrion으로 제공이 되게 될것이구요. 일부는 광고 그룹이나 개별 광고 항목들의 정보로 들어가게 될것 같습니다. 추가로 제외 키워드의 경우는 향후에도 지원될 가능성은 낮습니다. 

현재 타게팅마스터 (criterion)에서 지원되는 항목은 아래와 같습니다. 
SCHEDULE(SD), REGIONAL(RL), PROXIMITY(RP), AGE(AG), GENDER(GN), AUDIENCE(AD)

다시 한번 혼란을 드린 점에 대해 사과 말씀드립니다. 

감사합니다.
