### ISSUE TITLE
관리중인 광고주들의 소진금액을 한번에 불러오는 API가 별도로 있는지 문의드립니다.

### ISSUE THREAD

**Issue by kiyj** [naver/searchad-apidoc#882]
ManagedCustomerLink에서 제공하는 관리하는 광고주 리스트(MYCLIENTS) 를 통해 관리권한이있는 광고주ID 값을 불러올 수 있는데
혹시 해당 광고주 리스트들의 한달 소진광고비를 광고주별로 API를 받아오는게 아니라 한번에 관리중인 모든 광고주의 소진액을 불러 올 수 있는 API가 별도로 존재할까요?

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 API 담당자 입니다. 

여러 광고주의 비즈머니 소진액 정보를 한번의 호출로 조회할수 있는 기능은 제공되지 않습니다. 저희 권한 구조 특성상 권한 구조가 변경되기 전까지는 해당 기능의 제공은 불가능할 것으로 예상됩니다. 

감사합니다.
