### ISSUE TITLE
캠페인명, 광고그룹명에 탭 제거 처리 요청

### ISSUE THREAD

**Issue by yuhee62wang** [naver/searchad-apidoc#883]
안녕하세요.

광고주관리센터(어드민)에서는 광고그룹명, 캠페인명을 입력할 때 복사해서 붙여넣으면 탭 입력이 가능해서
추후 보고서(tsv)를 수집하고 파싱할 때 이 탭 때문에 문제가 됩니다.
※ 소재, 확장소재는 탭을 특수문자로 인식해서 어드민에서 등록 불가

저희도 사용자 입장에서 탭은 사용하지 않도록 자제하겠습니다만 
tsv로 보고서를 주는 이상 
소재나 확장소재처럼 탭 입력이 불가하게 개선해주시거나 '명'에서 탭을 제거한 상태로 제공을 하면 좋겠습니다. 

바쁘시겠지만 검토 부탁드립니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

우선 사용에 불편을 드린 점에 대해 사과 드립니다. 
말씀 주신 문제에 대해서는 저희도 모두 인지하고 있으나, 여러 다른 작업들로 인해 아직까지 작업이 완료 되지 않은 상황입니다. 담당 부서에 한번 더 입력 금지 문자 처리에 대해 진행을 요청 드리도록 하겠습니다.

감사합니다.
