### ISSUE TITLE
Master Report "ShoppingProduct"(쇼핑검색 쇼핑몰상품형 상품마스터) 노출용 이미지 관련

### ISSUE THREAD

**Issue by m3h13r** [naver/searchad-apidoc#884]
안녕하세요, Master Report 중 쇼핑검색 쇼핑몰상품형 상품마스터에서 No.7인 "**Ad Image URL**" 값이 모두 비어 있어서 문의드립니다.
실제 소재에서는 노출용 이미지가 등록되어 있는데, 보고서 값에는 왜 비어 있는 지 모르겠습니다.
"**Ad Image URL**" 가 노출용 이미지 URL이 아닌 건가요?

(참고) MasterReport (ShoppingProduct) API 문서

> Shopping shopping mall product Master (ShoppingProduct)
> No | Field Name | Value | Max.Length | Description
> 1 | Customer ID | int |   | Customer ID
> 2 | Ad Group ID | string | 31 | Ad Group ID
> 3 | Ad ID | string | 31 | Ad Creative ID
> 4 | Ad Creative Inspect Status | int |   | - 10: UNDER_REVIEW- 20: APPROVED- 21: ELIGIBLE- 30: LIMITED_APPROVED- 40: PENDING
> 5 | ON/OFF | int |   | - 0: ON- 1: OFF
> 6 | Ad Product Name | string | 256 | product name when ad is exposed.
> **7 | Ad Image URL | string | 256 | product image url when ad is exposed.** => 모든 값이 비어 있음. 노출용 이미지가 있는 Ad에도.
> 8 | Bid | int |   | Korean Won(KRW), from 50 to 100,000
> 9 | Using Ad Group Bid Amount | boolean |   | - false: not used- true: used
> 10 | Ad Link Status | int |   | 0: Disable.1: Enable.
> 11 | regTm | date |   | The time at which information was created(ISO8601)
> 12 | delTm | date |   | The time at which the campaign was deleted(ISO8601)
> 13 | Product ID | string | 256 | Unique key of Shopping Product
> 14 | Product ID Of Mall | string | 256 | Product Id of Mall
> 15 | Product Name | string | 256 | Product name
> **16 | Product Image URL | string | 256 | Product Image URL** => 소재 이미지 URL과 동일함 확인
> 17 | PC Landing URL | string | 256 | Product landing page(PC)
> 18 | Mobile Landing URL | string | 256 | Product landing page(Mobile)
> 19 | Price(PC) | string | 256 | Low Price(PC)
> 20 | Price(Mobile) | string | 256 | Low Price(Mobile)
> 21 | Delivery Fee | string | 256 | delivery fee

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

문의 주신 필드는 광고관리 시스템에서 광고 노출시 표시될 이지를 별도로 등록한 경우에만 값이 존재하는 필드인데요. 
말씀 주신 내용으로 보아 등록을 했음에도 값이 없다는 말씀으로 이해 됩니다. 
지난 10월부터 쇼핑검색 쇼핑몰상품형 상품마스터의 스토리지를 업그레이드 하는 과정에서 문제가 발생하여 수정 작업을 계속 하고 있는 중인데요. 그 영향일 가능성이 높아 보입니다. 
담당 개발부서와 확인하여 해결할수 있도록 하겠습니다. 
혹 해당 현상이 발생하는 커스터머 아이디 한두개 정도를 알려 주실수 있으실지요?

감사합니다.

**Comment by m3h13r** [comment]
customer_id:
2055549
2201514

2개 전달드립니다!

**Comment by m3h13r** [comment]
안녕하세요!
혹시 수정 작업이 진행되고 있는 상태일까요?

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

네 현재 작업중입니다. 죄송한 말씀이긴 합니다만 제가 개인적인 사정이 생겨 몇일 출근을 하지 못하였습니다. 
차주중에는 해결이 될것으로 예상됩니다.

감사합니다.
