### ISSUE TITLE
api 요청 사항에대해 궁금한점이 있어서 문의드립니다(cors)

### ISSUE THREAD

**Issue by soyoung931014** [naver/searchad-apidoc#885]
안녕하세요!
api 요청 사항에대해 궁금한점이 있어서 문의드립니다

제 경우 제가 만든 백엔드 서버에서 검색광고 api 요청을 보내면 데이터가 잘 들어오지만
브라우저에서 api 요청을 보내면 cors문제가 발생합니다.  
이 경우 제가 네이버 백엔드 서버에 접근할 수 없으니.. 
제가 만든 백엔드 서버를 통해 검색광고 api에 접근해야만 하는건가요? 
브라우저에서 따로 접근할 수 있는방법은 없는걸까요?

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

네이버 검색광고 API는 광고주가 별도의 서버를 구축하여 광고관리하는 기능을 지원하기 위해 제공하고 있습니다.

브라우저를 이용한 접속은 네이버 검색광고 광고주센터 (https://searchad.naver.com)을 이용해 주시기 바랍니다.

감사합니다.

**Comment by soyoung931014** [comment]
제가 이해를 잘 못한것 같아서 다시 문의드립니다..ㅜ 초보라 이해부탁드립니다.
제가 원하는건 저의 클라이언트서버에서 api(https://api.searchad.naver.com) 요청을 보냈는데 cors에러를 마주한 문제였습니다.
제 클라이언트브라우저에서 api 요청을 바로 보내 데이터를 받을 순 없는걸까요?
따로 백엔드 서버를 두어 거기에서 api를 요청해야하는걸까요?

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

문의하신 cors 에러는 클라이언트 브라우저에서 처음에 접속한 도메인과 검색광고 API 서버의 도메인이 다르기 때문에 발생하는 오류입니다.
cors 에러는 브라우저에서 발생하는 오류이고, 이 경우 검색광고 API 서버에서 cors 설정을 모든 도메인에 대해 허용으로 풀어주거나, server to server 방식으로 API를 사용하셔야 합니다. 검색광고 API 서버의 경우 보안상의 이유로 모든 도메인에 대해 cors를 풀고 있지는 않습니다.

그외 다른 방법으로, 브라우저가 접속하는 도메인을 서빙하는 http 서버(apache 또는 nginx 등)에서 redirect로 해결할 수 있습니다.

감사합니다.
