### ISSUE TITLE
확장소재 SHOPPING_BRAND ~ (VIDEO/BROADCAST/EVENT) 유형의 샘플 요청 드립니다

### ISSUE THREAD

**Issue by ROSETTA-LEE** [naver/searchad-apidoc#887]
안녕하세요, 아래와 같은 쇼검 확장소재 유형을 api 로 생성하고자 합니다. 

SHOPPING_BRAND_VIDEO
SHOPPING_BRAND_BROADCAST
SHOPPING_BRAND_EVENT

다만 아래 샘플 문서에는 해당 항목이 아직 업데이트가 되지 않은 것으로 보여
이 내용을 어디에서 확인할 수 있을지 문의 드립니다.

https://gist.github.com/naver-searchad/f8e941f61b9152972feb676689046b87

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

아래의 확장소재 유형은 API를 이용하여 생성이 불가능 합니다.

* SHOPPING_EXTRA
* CATALOG_EXTRA
* CATALOG_EVENT
* CATALOG_PURCHASE_CONDITION
* SHOPPING_BRAND_BROADCAST
* SHOPPING_BRAND_EVENT
* PLACE_SMART_ORDER,NAVER_BLOG_REVIEW
* POWER_LINK_IMAGE
* IMAGE_SUB_LINKS
* CATALOG_IMAGE
* NAVER_TV_VIDEO
* SHOPPING_BRAND_IMAGE
* SHOPPING_BRAND_VIDEO
* SHOPPING_BRAND_DAY

**Comment by ROSETTA-LEE** [comment]
전달 주신 유형 중 아래 항목은 api로 등록이 되거나 문서에 샘플 코드까지 기재되어 있는데요,
그럼 현재의 api 문서는 말씀주신 내용으로 업데이트 되어야 하는 상황일까요?
보통 문서나 게시판의 내용을 참고해 개발하는데
실제 사용을 하고 있음에도 불가 항목에 포함되어 있어 진행 시 약간 혼선이 있습니다.

CATALOG_EVENT : 샘플코드 O
{
  "dittoId": "crtv-pf13nizz2f5c",
  "thumbnail": "https://ssl.pstatic.net/adimg2.search/o/tachikoma/pf1/crtv-pf13nizz2f5c.png"
}

CATALOG_IMAGE : 샘플코드 O
{
  "imagePath": "/MjAxNzExMjJfMTEw/MDAxNTExMzM5NzYwODk1.QnHcPp6mAr3I-Kkx18IjxoWIAJNrvTgx7NTqXQTfd9kg.Y6csE9Q37Wph49njzVczrmjJWxSkpRPXehxDxpBvlw4g.PNG/mong1.PNG"
}

NAVER_TV_VIDEO : 샘플코드 O
{
  "imagePath" : "/MjAxNzExMjJfMTEw/MDAxNTExMzM5NzYwODk1.QnHcPp6mAr3I-Kkx18IjxoWIAJNrvTgx7NTqXQTfd9kg.Y6csE9Q37Wph49njzVczrmjJWxSkpRPXehxDxpBvlw4g.PNG/mong1.PNG",
  "description": "동영상 설명",
  "isSponsorReview": true
}

POWER_LINK_IMAGE : 샘플코드 O, 실제로도 API 호출 및 등록 O
IMAGE_SUB_LINKS : 샘플코드 O, 실제로도 API 호출 및 등록 O

그럼 확인 부탁드립니다.
감사합니다.
