### ISSUE TITLE
estimate 견적 데이터 산출 방법

### ISSUE THREAD

**Issue by nibxxad** [naver/searchad-apidoc#888]
안녕하세요~

Estimate: get (average position bid) 와 Estimate: get (performance) 데이터의 산출 방법과 그 기준을 알 수 있을까요?
해당 데이터가 어떻게 추출되는지 대략적인 공식 알려주시면 감사하겠습니다!

**Comment by naver-searchad** [comment]
안녕하십니까 기능 담당자입니다. 

조금 긴 내용이 될수 있는 점 양해 부탁드립니다. 
1. 순위별 평균입찰가 (파워링크)
매주 일요일 계산되며, 계산일 전일로부터 과거 28일 간의 데이터를 모수로 합니다. 
과거 28일간 광고 노출이 발생한 모든 키워드(검색어)의 순위별 노출 광고의 입찰가를 모아서 단순 평균합니다. 
이때 평균에 사용되는 입찰가는 품질지수 4단계 기준으로 일반화한 입찰가로서 사용자에게 제공될때 등록 키워드를 인자로 사용할 경우 해당 등록 키워드의 품질지수를 반영 한 값으로 제공됩며, 검색어를 입력 인자로 사용할 경우 4단계 기준의 값으로 제공됩니다. 
또한 일주일에 한번 계산된 값은 각 요일별 패턴에 따른 가중치를 적용하여 조회 하는 시점의 요일에 따라 다르게 제공됩니다.
마지막으로 단순 산술평균을 사용하고 있는 만큼 소위 통계학에서 말하는 "평균의 함정(오해)"이 발생할수 있을만큼 모수가 적은 케이스 및 노출 광고수가 적은 케이스는 계산하지 않습니다. 모수의 크고 작음은 각 검색어의 통계적인 노출 분포를 고려하여 판단합니다. 

2.  Estimate: get (performance)
노출, 클릭, 비용을 각각 추정하며 노출과 클릭, 노출과 비용간은 완전히 독립적으로 계산됩니다. (이로 인해 노출과 클릭간 역전 현상이 발생하기도 하나 별도 보정을 하지 않습니다.)
매주 일요일, 일주일에 각 키워드별/매체(PC통검, 모바일검색)로 1회 계산되며, 각 항목별 추정 방식에 사용되는 모델은 복수의 후보들이 준비되어 있으며 대체로 통계적인 방법론들을 이용한 추정 방식을 이용하여 구성된 것들입니다. 이 후보들을 최신성을 유지하기 위해 최근 28일간의 데이터를 분포와 비교하여 가장 현재 분포를 잘 설명할수 있는 모델을 채택하는 형태입니다. 
A. 노출 
미리 만들어준 예측 모델과 최소 입찰가(70)원부터 최소노출입찰가 (과거 28일 간 해당 입찰가로 입찰 했다면 모든 노출 기회에 노출이 가능했던 입찰가)까지의 입찰가 분포를 비교하여 가장 최신 분포를 잘 반영하는 모델을 채택합니다. 
해당 모델은 노출수와 입찰가간의 함수로 구성됩니다. 최소 노출 입찰가 이상의 입찰가가 입력된 경우 대상 검색어의 총 검색수를 노출수로 제공합니다. 
B. 클릭 
미리 만들어둔 예측 모델과 비교하는 것은 동일합니다. 
단, 입찰가별 클릭의 분포는 별도로 계산하는대로 특정 입찰가로 과거 28일 전부터 28일 내내 입찰하고 있을때 각 노출 기회 별로 특정 순위를 차지할수 있는 확률을 계산합니다. 또한 각 노출 기회별로 특정 순위를 차지 했을때 클릭 받을 확률을 계산합니다. 이때 아웃라이어는 제거하거나 일반화 합니다. 
이를 통해 각 입찰가별 클릭발생 확률 분포를 계산하게 됩니다. 이 분포와 미리 만들어둔 모델들을 비교하여 가장 연관성이 높고 분포를 잘 설명할수 있는 모델을 채택합니다. 
이상의 계산 방식에서 아실수 있듯이 클릭 확률을 계산하고 있으므로 이론적으로 특정 입찰가를 사용했을때 받을수 있는 최대 클리수에 가까운 값을 제공드리고 있습니다. 
C. 광고비(클릭당 비용)
각 입찰가별로 발생 가능한 최대 광고비 분포와 미리 만들어둔 복수의 모델을 비교한 후 가장 분포를 잘 설명할수 있는 모델을 채택합니다. ,이 모델을 통해 도출된 입찰가별 광고비 수식을 통해 광고비를 도출하고 동일한 입찰가로 도출된 클릭수를 나눠서 클릭당 비용을 산출 합니다. 

키워드 플러스 적용 여부는 키워드 플러스 적용시 확장되는 트래픽 양을 계산하여 반영하고 있습니다. 단 현재의 유사 검색어 등의 새로운 확장 검색 방법론들은 반영 되어 있지 않아 2024년 중 로직을 개편하거나 수정할 예정입니다. 

감사합니다.

**Comment by nibxxad** [comment]
상세한 답변 감사합니다 :)
그렇다면 Estimate: get (average position bid) 와 Estimate: get (performance) 두 데이터 모두 매주 일요일 주 1회 업데이트 되는 것으로 이해하면 될까요?

**Comment by naver-searchad** [comment]
안녕하십니까 담당자입니다. 

네 원본 데이터 자체는 일주일에 1번 업데이트 됩니다. 단  파워링크용 Estimate: get (average position bid) 의 경우는 주 1회 계산을 할때 요일별 가중치(?)값을 같이 계산해서 요일마다 적용합니다. 예를 들어 오늘 조회 한다면 화요일 가중치가 반영된 값이 조회 됩니다. 

감사합니다.
