### ISSUE TITLE
Stats report AD_CONVERSION_DETAIL 문의

### ISSUE THREAD

**Issue by jaehawnlee** [naver/searchad-apidoc#889]
안녕하세요.

시간 데이터를 가져오기 위해 detail 리포트를 호출하고있습니다.

11/01 호출 시 보고서를 찾을 수 없다는 에러가 출력 되고있습니다.

하지만 AD_CONVERSION 호출시 에러 없이 정상적으로 보고서 다운로드를 확인했습니다.

원인 알 수 있을까요

**Comment by naver-searchad** [comment]
안녕하십니까. 대용량 다운로드 보고서 담당자입니다. 

현재 삭제되지 않은 잡아이디나 보고서를 추출하신 대상 계정의 커스터머 아이디를 알려 주실수 있으실까요? 
(라이선스키나 비밀키, 로그인 아이디등은 **절대 이곳에 남기지 말아 주십시오**. 잡아이디나 커스터머 아이디면 충분합니다.)

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까. 대용량 다운로드 보고서 담당자입니다.

아 죄송합니다. AD_DETAIL 로 제가 잘못봤네요..
CONVERSION_DETAIL은 과거 45일간만 제공됩니다. 
보고서 별 제공 기간은 아래 링크를 참고해 주십시오.
https://github.com/naver/searchad-apidoc/wiki/FAQ-stat#q-stat-report-%ED%95%AD%EB%AA%A9%EB%B3%84-%EA%B8%B0%EA%B0%84

감사합니다.

**Comment by jaehawnlee** [comment]
답변 감사드립니다.

한가지 더 궁금한점이 있는데

Job status, REGIST, RUNNING, BUILT, NONE, ERROR, WAITING, AGGREGATING


status의 종류입니다. 유효한 값 목록은 다음과 같습니다.
The type of the status.Valid items are:

REGIST
RUNNING
BUILT
NONE
ERROR
WAITING
AGGREGATING

각 스테이터스에 대한 정확한 의미를 알 수 있을까요?

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

각 상태값의 의미는 아래와 같습니다. 

REGIST : 보고서 생성 요청이 등록되었음을 의미합니다. 
RUNNING : 요청된 보고서를 생성중인 경우 표시됩니다. 
BUILT : 요청된 보고서의 생성이 완료된 경우의 상태입니다. 
NONE : 요청된 보고서를 생성 시도 했으니 지표가 없어(대표적으로 해당 일자 노출이 없는 경우가 있습니다.) 보고서가 생성되지 않았음을 의미 합니다. 
ERROR : 보고서 생성 과정에서 오류가 발생한 경우입니다. 
WAITING : 보고서 생성 요청이 많아 대기하고 있는 경우입니다. 
AGGREGATING : 보고서용 지표의 기반 데이터를 생성하고 있음을 의미합니다. 보통 새벽 1시~3시 사이에 간혹 등장합니다. 

NONE 의 경우는 아직 지표가 생성되지 않은 날짜에 대한 요청을 할때도 발생합니다만 대부분은 광고 성과가 없는(노출이 없는) 일자에 대해 요청한 경우 발생하는 경우가 많습니다. 
저희 내부적으로는 여러가지 케이스가 있어서 앞서 질문 주신 것처럼 지원되지 않는 과거 일자에 대해 생성 요청을 한경우 API 호출 단에서 에러를 리턴하는 케이스도 있지만...JOB이 등록된 이후에 ERROR로 NONE으로 표시되는 케이스도 존재합니다. 

WAITING이 오래(몇시간 이상) 지속되는 케이스는 행이 걸려 버린 케이스일수 있는데요. 정상적이라면 결국 ERROR로 상태값이 바뀌게 되어야 하지만...바뀌지 않는 경우도 드물게 확인되고 있습니다. 이런 경우는 이 게시판에 문의를 주시면 되겠습니다. 
보통 WAITING은 월요일 새벽이나 오전 처럼 보고서 생성이 몰리는 시점에 간혹 발생하나 대체로 대기시간이 길지는 않는 편입니다. 

감사합니다.
