### ISSUE TITLE
요일/시간대 타겟팅 관련 문의드립니다. 

### ISSUE THREAD

**Issue by pocaaaaa** [naver/searchad-apidoc#890]
안녕하세요. 
요일/시간대 타켓팅과 관련하여 문의드립니다. 

현재 저희 사이트에서 요일/시간대 타켓팅을 매요일 + 매시간 (총 168개 dictionaryCode) 가중치를 셋팅하여 사용하고 있고,
광고그룹 기준 최대 7725건에 대해 요일/시간대 타켓팅을 매일 배치를 이용하여 타겟팅 변경 API (/ncc/criterion/{광고그룹 ID}/{dictionary type}) 를 사용하여 갱신하고 있습니다. 

* 참고 : [타겟팅 변경 API](https://naver.github.io/searchad-apidoc/#/operations/PUT/~2Fncc~2Fcriterion~2F%7BadgroupId%7D~2F%7B%3Fdictionary%20type%7D)

그런데 일주일 기준으로 배치 시간을 측정해보니 총 7725건에 대하여 최대 168개 (월~일, 24시간) 의 dictionaryCode 를 변경할때마다 배치 소요시간 편차가 크게 발생합니다. 

|배치 날짜|소요시간|
|------|---|
|12월 14일 15:41:16|15:41:38 ~ 18:22:18 (2시간 20분 40초)|
|12월 15일|00:00:34 ~ 00:29:57 ( 29분 23초 )|
|12월 16일|00:00:33 ~ 00:43:54 ( 43분 21초 )|
|12월 17일|00:00:28 ~ 00:35:00 ( 34분 22초 )|
|12월 18일|00:00:36 ~ 01:14:35 ( 1시간 13분 59초 )|
|12월 19일|00:00:36 ~ 01:39:21 (1시간 38분 45초)|
|12월 20일|00:00:32 ~ 12:23:21 (22분 49초)|

전체 광고그룹 (7725건)에 대하여 특정 요일/시간 (ex: SDFRI0304, SDFRI0405) 에 광고 노출 하지 않기 않기 위해서는 비노출할 요일/시간의 dictionaryCode를 제거하고 모든 광고그룹을 다시 타켓팅 변경 API를 사용하여 갱신해야 하는데, 소요시간이 1시간 이상 걸리기 때문에 긴급하게 광고 비노출이 필요한 경우 현재 기준으로는 사용하기 어려움이 발생합니다. 

이와 관련하여 아래의 내용 검토 부탁드리겠습니다. 

#### 1. 타겟팅 변경 API 와 관련하여 속도 개선이 가능할까요? 
  - 기존에 하루 기준으로 dictionaryCode(SDMON0024, SDTUE0024, … / 총 7개) 로 타겟팅 변경 API 호출시  7분 ~ 17분 정도 소요되었는데, dictionaryCode를 매요일/매시간 기준(SDMON0001, SDMON0002, … SDSUN2324 / 총 168개) 으로 변경한 후 22분 ~ 1시간 28분 정도로 소요됩니다. 
  - 동일한 광고그룹(7725건)에 168개의 dictionaryCode를 갱신하는데 소요시간의 편차가 큽니다. 
   
#### 2. 등록된 타겟팅의 가중치를 변경할 수 있는것처럼 등록도니 타겟팅의 타겟팅 사용 여부(enable)를 제어할 수 있는 기능이 추가 될 가능성이 있을까요? 
- 참고 : [타겟팅 입찰가 가중치 변경](https://naver.github.io/searchad-apidoc/#/operations/PUT/~2Fncc~2Fcriterion~2F%7BadgroupId%7D~2FbidWeight%7B%3FdictionaryCode%7D%7B%3FbidWeight%7D)

#### 3. 타겟팅 변경 API의 경우 '타겟팅 변경시 Request Body에 포함되지 않는 코드는 모두 사용안함 처리' 되기 때문에 위와 같이 특정 시간의 타겟을 사용 하지 않을때도 비활성화 하려는 타겟을 제외하거나 enable=false 하여 모든 dictionaryCode를 Request Body에 전달해야 합니다. 혹시 전체가 아닌 특정 타겟만 업데이트 할 수 있는 기능이 추가될 가능성이 있을까요? 

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

1. 타겟팅 변경 API 와 관련하여 속도 개선이 가능할까요?
 => 타겟팅을 설정하실때 요일/시간별로 다르게 설정할 경우 시간이 오래 걸릴수 있습니다. 1개의 광고그룹에 요일별(7), 시간대별(24)개를 다르게 설정할 경우 168개의 설정이 처리됩니다. 또한 문의하신 광고그룹 7725개의 설정을 모두 처리할 경우 1,297,800 개를 처리 해야 합니다. 다수의 광고주가 동시에 요청할 경우 처리 속도에 지연이 있을수 있습니다. 

2. 등록된 타겟팅의 가중치를 변경할 수 있는것처럼 등록도니 타겟팅의 타겟팅 사용 여부(enable)를 제어할 수 있는 기능이 추가 될 가능성이 있을까요?
=> 이 부분은 저희도 고민하고 있는 부분이고, 기존 등록된 설정과 충돌하거나 잘못 반영이 되어 발생할 수 있는 문제점들에 대해 검토하고 있습니다. 검색광고 API 개선 일정은 추후 확정이 되는데로 공유드릴 예정입니다.

감사합니다.

**Comment by pocaaaaa** [comment]
안녕하세요. 
답변 감사합니다. 

답변해주신 부분과 관련하여 추가적으로 문의드릴 부분이 있습니다. 

첫번째 답변과 관련하여 광고그룹 7725개의 설정을 모두 처리하여 1,297,800개를 처리할 때 
다수의 광고주가 동시에 요청할 경우 처리 속도에 지연이 있을수 있다는 말씀이
타겟팅 변경 API를 동시에 호출하는 광고주가 많을 때 동일하게 1,297,800개의 데이터를 처리하더라도 
처리 시간의 편차가 발생할 수 있다는 말씀이실까요? 

원래 계정당(광고주당) API가 트래픽을 분산해서 처리하고 있는 걸로 알고 있는데, 
타겟팅 변경 API는 모든 트래픽이 한 서버로 몰리기 때문에 다수의 광고주가 동시에 요청할 경우 
처리 속도의 편차가 발생하는걸까요? 

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

네이버 검색광고 API 시스템은 광고주의 요청 트래픽을 최대한 받을수 있도록 시스템이 구축이 되어 있습니다.
하지만, 모든 리소스를 광고주 몇몇분의 트래픽이 점유할 경우 다른 광고주에게 피해가 갈 수 있어 광고주별 트래픽을 제한하고 있습니다.

그럼에도 시스템 특성상 광고주들의 트래픽이 집중되는 시간이 있을수 있고, 이 시간에는 한정된 자원을 공유해서 사용하기 때문에 처리 시간에 편차가 있을수 있습니다.

감사합니다.
