### ISSUE TITLE
다차원, 대용량 보고서의 Click 필드 중복여부

### ISSUE THREAD

**Issue by yjunej** [naver/searchad-apidoc#894]
Click의 경우 어떤 방식으로 집계되나요?
스마트스토어 센터의 통계에 표시되는 "고객수"의 값과 동일한 기준으로 측정되나요?

**Comment by naver-searchad** [comment]
안녕하십니까  대용량 다운로드 보고서 담당자입니다. 

우선 스마트스토어 센터의 통계가 어떻게 집계 되는지 저희는 알수 없어 각 집계 기준의 동일함을 말씀드리기는 어려울것 같습니다. 
에초에 서비스의 구조가 다르므로 혹 같더라도 우연일 것으로 생각 되기도 하구요. 

대용량 보고서상 click 필드는 해당 필드의 광고에서 발생한 클릭수를 보고서내 지표 구분 단위(예를 들면 일단위, 시간 단위)로합산 한 것입니다. 
이때 광고를 클릭한 수는 무효 클릭을 제외한 클릭을 의미 하며 무효 클릭에 관하여서는 아래 링크의 내용을 참고하여 주시기 바랍니다. 
https://saedu.naver.com/help/ccenter/intro.naver

감사합니다.
