### ISSUE TITLE
비즈머니 기간별 내역 조회 API 결과에 customerId:0로 표기되는 건

### ISSUE THREAD

**Issue by hon9hb-dbase** [naver/searchad-apidoc#897]
@naver-searchad 

안녕하세요.

비즈머니 기간별 내역 조회 API (/billing/bizmoney/histories/period) 결과 중
customerId가 0으로 들어오는 데이터가 있어서 확인 요청 드립니다.
해당 내용은 API 호출 및 searchAd UI에서 호출 시에도 동일합니다.
(하기 이미지 참고 부탁 드립니다.)

조회 기간은 1/1 ~ 금일(1/11)로 지정하여 조회하였는데
혹시 금일 데이터에 대해서만 그렇게 표기가 되는 것인지 앞으로도 그렇게 조회될 예정인지 여부가 궁금합니다.

또한 일전에 올린 이슈발행건도 (#895) 확인 부탁드립니다.

감사합니다.

![image](https://github.com/naver/searchad-apidoc/assets/88298771/708b2123-a84b-4081-9f57-8c500fa69b32)

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.
불편 드려 대단히 죄송합니다.

현재 당일 조회 결과에 대해서만 customerId:0 으로 나오는 현상으로
차주에 수정 반영될 예정입니다.

감사합니다.
