### ISSUE TITLE
/stats today 질문입니다.

### ISSUE THREAD

**Issue by sonbumee** [naver/searchad-apidoc#898]
/stats today 데이터는 몇시간 전 데이터를 보여주며 
언제 최신화 되는지 알고싶습니다.

제가 보기로는 4시간 전 데이터를 매시간마다 api 최신데이터를 보내준다고 보고있는데
맞는지 궁금합니다.

**Comment by hwanython** [comment]
호출 endpoint의 param이 어떻게되죠..?

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다

네 확인하신대로 4시간 전 데이터를 매시간 업데이트하고 있습니다.
예) 0시 데이터는 4시에 확인하실 수 있습니다.

감사합니다.
