### ISSUE TITLE
Stat Report 오류 문의 - 에러코드 400

### ISSUE THREAD

**Issue by na0118** [naver/searchad-apidoc#899]
안녕하세요,

네이버 api를 사용해 검색광고 리포트를 생성하는 과정에서 오류가 뜹니다.

Stat / Stat report 를 통해 데이터를 불러오면 다음과 같은 에러코드가 확인됩니다.

[에러코드 400]

![stat error](https://github.com/naver/searchad-apidoc/assets/156977599/a12762ea-cf73-4667-814b-5c4f2dc97604)

다른 Adgroup이나 /ncc/Campaign을 불러오는 것에는 다음과 같이 문제가 없어

어떤 부분이 오류를 발생시키는지 혹시 알 수 있을까요?

[에러 없음]

![other](https://github.com/naver/searchad-apidoc/assets/156977599/26ab8982-fa2b-419c-9cf9-10616e7e1149)

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.


해당 에러는 요청하신 리포트에 대해서 노출 등이 발생하지 않아 데이터가 존재하지 않을 때 발생할 수 있습니다.

생각해 볼 수 있는 원인은 

1. 리포트 요청하신 기간이 지표가 발생하지 않은 기간임.
2. 리포트 요청하신 campaign이나 ad group 에서 지표가 발생하지 않음.


API 의 동작은 아래 sample Request를 통해서 데이터가 전달됨을 내부적으로 확인하였습니다.

stats?fields=[%22clkCnt%22,%22impCnt%22,%22salesAmt%22,%22ctr%22,%22cpc%22,%22ccnt%22,%22crto%22,%22convAmt%22,%22ror%22,%22cpConv%22,%22viewCnt%22]&timeIncrement=allDays&datePreset=last7days&ids=cmp-a001-01-000000002279253


감사합니다.
