### ISSUE TITLE
BusinessChannel의 businessInfo field 문의

### ISSUE THREAD

**Issue by rndmania** [naver/searchad-apidoc#9]
문서를 보면 BusinessChannel에 businessInfo field가 json format으로 포함되어있는데
상세한 설명이 없어서 문의드립니다.
businessInfo field에 대한 문서 업데이트 계획이 있으신가요?
가능하시다면 해당 field의 값에 대한 설명 부탁드립니다.

**Comment by naver-searchad** [comment]
안녕하세요
businessInfo field 에 대한 API 문서 업데이트 중에 있으며

https://gist.github.com/naver-searchad/6d0f4f48ed6cc6f8b80b633eb75e385a

에서 먼저 확인이 가능합니다.

**Comment by rndmania** [comment]
네 감사합니다
