### ISSUE TITLE
estimate api 에 대한 질문

### ISSUE THREAD

**Issue by moominbelly** [naver/searchad-apidoc#901]
안녕하세요, 
estimate 항목 중 Estimate: get (performance) - NPC 라는 항목에 대해 
궁금한 것 이있습니다. 
현재 이 항목에 NPC 라는 것이 어떤 걸 의미하는 걸까요 ?
또한 parameter 값 중에 level (integer) -stepwise cumulative distribution에 관련한 
내용이 어디에도 상세 설명이 없어 어떤 항목인지 유추가 불가능한데 상세한 설명을 받을 수 있을까요 ?

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 네이버 검색광고 기능 담당자입니다. 

문의 주신 Estimate: get (performance) - NPC 는 콘텐츠검색광고(파워컨텐츠 유형)의 광고 실적 예상 기능입니다. 
 level 은 1~4가 있으며 각 값의 의미는 아래와 같습니다. 레벨값을 입력하시면 해당 값에 준하여 실적을 예상합니다. 

1: 충분한 예산, 방문자 극대화 전략 
2: 적정한 예산, 방문자 극대화 전략 
3. 예산대비 효율 중시 전략 
4. 소규모 예산 활용 전략 

주의 하실 점은 level의 설정 기준이 상품 출시 초기에 맞춰져 있어서 현재와 같이 등록 가능 키워드가 크게 증가한 상황에서는 
실제보다 과소 예상될수 있다는 점입니다. 

감사합니다.

**Comment by moominbelly** [comment]
아 넵 답변 감사합니다. 
다만,
답변주신 값으로 이해해서 레벨값을 입력해 비교해 보았는데  
![image](https://github.com/naver/searchad-apidoc/assets/77463110/b34d853d-653f-43a2-a9d4-131dcadc31ed)
레벨 1 충분한 예산, 방문자 극대화 전략의 노출클릭비용이 
레벨 2 적정한 예산, 방문자 극대화 전략의 노출클릭비용 보다 작게 값이 나와서 
이런 경우는 어떻게 해석해야 하는 것일까요? 

감사합니다.
