### ISSUE TITLE
쇼핑검색 소재의 새 확장소재 추가홍보문구 API 

### ISSUE THREAD

**Issue by SM11187** [naver/searchad-apidoc#902]
안녕하세요.

쇼핑검색 소재의 새 확장소재 추가홍보문구 추가하는 API가 있을까요?
쇼핑검색 새 확장소재 추가인 /ncc/ad-extensions가 아닌
 
네이버 검색광고 센터 페이지에서
쇼핑검색 > 광고 그룹 탭에서 광고그룹 클릭 > 소재 탭에서 소재 컬럼 속 상세보기 버튼 클릭 > 확장 소재 탭에서 새 확장 소재 선택

![image](https://github.com/naver/searchad-apidoc/assets/94828850/6afc8435-4e7f-41a4-9bf8-e2c46d7056d6)

이 추가홍보문구를 API 통해서 추가할 수 있는지 답변 부탁드리겠습니다
감사합니다.

**Comment by naver-searchad** [comment]
/ncc/ad-extensions 를 이용해서 ownerId 를 광고소재 ID를 아래 처럼 입력하고, type은 PROMOTION으로 선택하고, adExtension내에 출력할 문구를 입력하면 됩니다. basicText는 필수 이고 additionalText는 option 입니다.

감사합니다.
```
{
  "adExtension": {
    "basicText": "테스트 홍보문구1",
    "additionalText": "선택 문구"
  },
  "customerId": 123456,
  "pcChannelId": null,
  "mobileChannelId": null,
  "nccAdExtensionId": "",
  "ownerId": "nad-a001-02-000000000011111",
  "type": "PROMOTION",
  "usePeriod": false,
  "userLock": false
}
```
