### ISSUE TITLE
"code":500,"message":"Internal Server Error"

### ISSUE THREAD

**Issue by homehonohonome** [naver/searchad-apidoc#903]
안녕하세요
stat-report ad 를 최근 10일치를 반복해서 받으려고 하는데요
internal server error 가 계속 뜨네요 시간이 지나도 해결이 안되서 문의드립니다.

import requests
import json
import signaturehelper
import time
import datetime
import shutil
import os

def get_header(method, uri, api_key, secret_key, customer_id):
    timestamp = str(round(time.time() * 1000))
    signature = signaturehelper.Signature.generate(timestamp, method, uri, secret_key)
    return {
        'Content-Type': 'application/json; charset=UTF-8',
        'X-Timestamp': timestamp,
        'X-API-KEY': api_key,
        'X-Customer': str(customer_id),
        'X-Signature': signature
    }

# API정보 설정
BASE_URL = 'https://api.searchad.naver.com'
API_KEY = ''
SECRET_KEY = ''
CUSTOMER_ID = ''

# 오늘 날짜와 10일 전 날짜 계산
today = datetime.date.today()
start_date = today - datetime.timedelta(days=10)

for i in range(10):
    report_date = start_date + datetime.timedelta(days=i-1)
    report_date_str = report_date.strftime('%Y%m%d')

    # Report 생성 요청
    create_uri = '/stat-reports'
    method = 'POST'

    create_response = requests.post(BASE_URL + create_uri, headers = get_header(method, create_uri, API_KEY, SECRET_KEY, CUSTOMER_ID),params = {"reportTp": "Ad", "statDt": report_date_str})
    
    if create_response.status_code in [200, 201]:
        create_response_data = create_response.json()
        report_id = create_response_data.get("reportJobId")
        print("보고서 생성 완료, ID:", report_id)

    else:
        print("보고서 생성 실패:", create_response.status_code, create_response.text)

**Comment by guswnd1** [comment]
날짜 형식을 수정하시면 될 것으로 보입니다.

# 오늘 날짜 가져오기
today = datetime.date.today()

# 어제 날짜 계산
yesterday = today - datetime.timedelta(days=1)

# 어제의 시작 시간 (UTC)
yesterday_start = datetime.datetime.combine(yesterday, datetime.time.min, tzinfo=datetime.timezone.utc)

# 어제의 끝 시간 (UTC)
yesterday_end = datetime.datetime.combine(yesterday, datetime.time.max, tzinfo=datetime.timezone.utc)

# 어제의 중간 시간 (UTC), 여기서는 자정으로 설정합니다.
yesterday_middle = datetime.datetime.combine(yesterday, datetime.time(12, 0), tzinfo=datetime.timezone.utc)

# 어제 중간 시간을 지정된 형식으로 포맷팅
formatted_yesterday_middle = yesterday_middle.strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"


# 대용량 보고서 생성하는 코드

uri = '/stat-reports/'
method = 'POST'
params={
    'reportTp' : "AD",
    'statDt' : formatted_yesterday_middle
}

# 헤더 생성
headers = get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID)

# 요청 보내기
r = requests.post(BASE_URL + uri, json=params, headers=headers)
