### ISSUE TITLE
쇼핑검색, 파워링크 확장소재 등록 시, 요일/시간대 설정 API

### ISSUE THREAD

**Issue by SM11187** [naver/searchad-apidoc#905]
안녕하세요.

쇼핑검색, 파워링크 확장소재 등록 시, '요일/시간대'도 설정할 수 있는지 문의 드립니다.

https://naver.github.io/searchad-apidoc/#/operations/POST/~2Fncc~2Fad-extensions

위 api 문서를 확인해보면
periodEndDt, periodStartDt로 시작, 종료일을 지정할 수는 있는 것 같은데 
요일/시간대를 설정하려면 어떻게 보내야하는지 답변 부탁드리겠습니다.

![l_170551385_1542_a8f16928bc2a1f10b770c40d1741f73b](https://github.com/naver/searchad-apidoc/assets/94828850/ec9e3554-5f38-4c9f-8d95-2b371be8f47d)

감사합니다 :)

**Comment by naver-searchad** [comment]
아래 처럼 schedule 과 periodStartDt/periodEndDt를 설정하시면 되겠습니다. schedule 은 bit 구조체이며 1~24 까지를 bit로 표현합니다. 예를 들면 16777215 bit 데이터는 아래 처럼 시간을 설정합니다.
```
let bitData = 16777215
for (hourIndex = i = 0; i < 24; hourIndex = ++i) {
  if ((bitData & (1 << hourIndex)) !== 0) schedule = true
  else schedule = false
} 

```

schedule 와 period 설정은 아래를 참고하세요.
```
{
  "mobileChannelId": "bsn-a001-00-00000000000XXXX",
  "nccAdExtensionId": "ext-a001-01-0000000000XXXX",
  "ownerId": "grp-a001-01-0000000000XXXX",
  "pcChannelId": "bsn-a001-00-00000000000XXXX",
  "schedule": {
    "MON": 16777215,
    "TUE": 16777214,
    "WED": 16777086,
    "THU": 16777215,
    "FRI": 16777215,
    "SAT": 16777087,
    "SUN": 16777215
  },
  "periodStartDt": "2024-01-31T15:00:00.000Z",
  "periodEndDt": "2024-02-09T15:00:00.000Z",
  "enable": true,
  ......
}
```

감사합니다.
