### ISSUE TITLE
캠페인 아이디 반영 문의건

### ISSUE THREAD

**Issue by jaehawnlee** [naver/searchad-apidoc#907]
안녕하세요 현재  광고 시스템에서 캠페인 아이디를 1월중에 수정했습니다.

혹시 수정된 캠페인 아이디 내역이 API에 반영되기까지 시간이 좀 걸리나요?

현재 데이터의 총 합은 맞으나 캠페인별 데이터가 조금 다릅니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

캠페인 ID는 수정이 불가능합니다. 신규 캠페인 등록시 시스템에서 부여한 고유값이기 때문입니다.
혹시 캠페인 이름을 수정하신걸까요?
캠페인 이름은 수정시 바로 반영이 됩니다.

감사합니다.
