### ISSUE TITLE
keywordstool  타임아웃(?) 이슈

### ISSUE THREAD

**Issue by park-sung-hwan** [naver/searchad-apidoc#908]
수고하십니다
keywordstool 를 사용해서 복수의 키워드를 넣어 연관검색어를 받아오는 파이썬 코드를 작성중입니다
일련의 질의에 원하는 답변을 회신 받고 있으나, 대략 60초를 지나는 시점에 답변이 멈추는 현상이 발생합니다

부하를 나누기 위해 아래와 같은 간격으로 호출중인데요
def delayed_function_call():
    # x초간 딜레이
    time.sleep(2)
    # 
    get_results()    

....
....

def get_token(method, uri, api_key, secret_key, customer_id):
    global payload
    timestamp = str(round(time.time() * 1000))
    signature = Signature.generate(timestamp, method, uri, secret_key)

    payload= {'Content-Type': 'application/json; charset=UTF-8', 'X-Timestamp': timestamp, 
            'X-API-KEY': api_key, 'X-Customer': str(customer_id), 'X-Signature': signature}
....
....
def get_results():
    global naver_response_df    
    global uri
    global base_url
    global payload    
    hintKeywords=input_word_df["기준키워드"][my_now_loop]
    # 
    # 
    params={}
    params['hintKeywords']=hintKeywords
    params['showDetail']='1'
    # 
    r=requests.get(base_url + uri, params=params, headers=payload)
    # 
    naver_response_df=pd.DataFrame(r.json()['keywordList'])
    # 
    print(naver_response_df)
    # 
    make_dp4_write(hintKeywords)
# 

sleep시간을 길게/짧게 조정해 봤으나 모든 경우에서 대략 60초 시점에 답변에서 오류가 발생합니다

수정할 만한 단서를 알고 싶습니다

**24.02.07 추가 질의**
위의 60초 타임아웃 이슈와 별개로 정확히 600개 질의를 넘는 순간 keywordstool 의 회신에 에러가 발생합니다
질의 일 쿼터의 문제인가요? (토큰당? 상점당? IP당?)

감사합니다

**Comment by naver-searchad** [comment]
@park-sung-hwan 님 안녕하세요. 검색광고 API 담당자입니다.

말씀주신 정보로는 정확히 확인이 어려울것 같습니다.

1. 답변이 멈춘다는 것이 API 응답 오류를 말씀하시는걸까요? 그렇다면 API 응답 코드 및 Response Header 의 Transaction-id 정보를 주시면 정확히 확인이 가능할것 같습니다.

2. 마찬가지로  600개 질의를 넘는 순간 keywordstool 오류시의 API http 응답코드 및 transactionid 정보 전달 부탁드리겠습니다.

감사합니다.

**Comment by park-sung-hwan** [comment]
개발자님 reply 감사드립니다
문의드렸던 2개의 이슈 다음과 같은 방법으로 해결 하였습니다

1. 60초 시점 답변 오류의 건
  토큰 획득후 50초 정도 지났을때 토큰을 재발급 받자 해결 되었습니다

2. 600개 이상 질의 불가의 건
  제가 오해했던 건 입니다
  질의하는 "키워드"를 엑셀에서 읽어 오는데, 원본 엑셀의 text에 공백이 들어있었습니다
  공백삭제 후 문제는 발생하지 않았습니다

검토해 주셔서 감사합니다
