### ISSUE TITLE
keywordstool api 사용시 403오류납니다

### ISSUE THREAD

**Issue by jesu237** [naver/searchad-apidoc#910]
keywordstool api 를 사용했는데 403오류가 아래와 같은 오류가 납니다
getTimestamp함수는 restapi에서 제공하는 함수 그대로 사용했습니다

제가 작성한 코드는 php로 만들었습니다.

require_once 'restapi.php';
$config = parse_ini_file("sample.ini");

$api = new RestApi($config['BASE_URL'], $config['API_KEY'], $config['SECRET_KEY'], $config['CUSTOMER_ID']);
$params = array(
    "hintKeywords" => "선풍기",
    'showDetail' => 1
);

$response = $api->GET("/keywordstool", $params);
echo "<pre>"; print_r($response, true); echo "</pre>";

입니다. 

sign = 1707265814673.GET./keywordstool Http Status : 403 Transaction-ID : unknown

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

요청하신 Transaction id를 알려주시면 로그를 확인해 보도록 하겠습니다.

감사합니다.

**Comment by naver-searchad** [comment]
@jesu237 님 안녕하세요. 검색광고 API 담당자 입니다.

주신 정보로 서버 로그를 확인해보니
입력 하신 timestamp 의 시간 값과 서버의 시간의 차이가 커서 서버에서 403 응답을 한것을 확인하였습니다.

timestamp 를 가져오는 함수를 확인해보시거나, 아니면 API 호출 하신 머신의 시간이 정확한 시간으로 세팅되어있으신지 한번 확인 부탁드리겠습니다.

감사합니다.

**Comment by jesu237** [comment]
restapi.php 에서 사용하는 
protected function getTimestamp()
    {
        return round(microtime(true) * 1000);
    }
    이것을 그대로 사용하는데 제가 어떻게 수정해야 하나요?
그리고 제 CUSTOMER_ID는 2218517 입니다
restapi.php에서 사용하는 __construct($baseUrl, $apiKey, $secretKey, $customerId)
에서 $this->customerId = $customerId; 되어있습니다. 
그래서 $customerId와 $this->customerId를 화면에 출력해 보면 
$customerId2218517  가 맞는데 $this->customerId는 221851721
으로 나옵니다 .
이것이 맞는 건가요?
제가 사용하는 url은 http://marketing.sionmall.kr/naver/keywords.php 입니다.

**Comment by naver-searchad** [comment]
@jesu237 님 안녕하세요

주셨던 링크에서 테스트 해보면, 시간이 실제 시간보다 약 1분정도 빠르게 나오고 있는것 같습니다.
