### ISSUE TITLE
statusReason (상태이유) 코드 관련 문의

### ISSUE THREAD

**Issue by serrimm** [naver/searchad-apidoc#911]
안녕하세요, 
statusReason(상태이유) 코드 관련 문의드립니다.

상태이유 코드 중 KEYWORD_DENIED, GROUP_PAUSED_BY_INVALID_TARGET 의 경우, 비즈채널 API 를 통해서 확인할 수 있는데요.
해당 코드의 경우, 키워드/광고그룹 API에서는 확인할 수 없는 상태이유 코드인 지 확인 부탁드립니다.

또한, API FAQ 확인 시 해당 상태코드는 각각 '키워드 반려'와 '그룹 타겟팅 오류'를 의미하는 것으로 확인되는데요.
해당 상태코드가 정확히 어떤 상태를 의미하는 지 설명 주시면 감사하겠습니다 (__)!

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

KEYWORD_DENIED 상태이유 코드는 '광고키워드'에서만 나타나는 코드입니다. 등록한 광고키워드가 반려 상태일때 발생하는 상태이유입니다.

GROUP_PAUSED_BY_INVALID_TARGET 상태이유는 광고그룹의 PC_MOBILE_TARGET 타겟의 설정이 잘못된 경우 발생합니다.

PC_MOBILE_TARGET의 경우 `target`값이 아래와 같은 JSON 구조를 가져야 합니다.
```json
{"pc":true,"mobile":true}
``` 

감사합니다.

**Comment by serrimm** [comment]
@naver-searchad 전달주신 답변 확인하였으며, 추가 문의 드립니다. 
두 상태코드(KEYWORD_DENIED, GROUP_PAUSED_BY_INVALID_TARGET)가 비즈채널 API가 아니라 키워드와 광고그룹 API에서 확인되는 코드라는 말씀이실까요? 
하기 API 문서 내 statusReason 속성 확인 시에는 해당 코드가 비즈채널 문서에만 존재하고 키워드와 광고그룹 문서에는 존재하지 않는 것으로 확인되는데요.

API 문서가 잘못 작성된 건 지 확인 부탁드립니다 :) 

- 비즈채널 list: https://naver.github.io/searchad-apidoc/#/operations/GET/~2Fncc~2Fchannels
- 키워드 list: https://naver.github.io/searchad-apidoc/#/operations/GET/~2Fncc~2Fkeywords%7B%3Fids%7D
- 광고그룹 list: https://naver.github.io/searchad-apidoc/#/operations/GET/~2Fncc~2Fadgroups%7B%3Fids%7D

추가적으로, 광고그룹의 PC_MOBILE_TARGET 타겟의 설정이 잘못된 경우라고 함은 어떤 케이스를 말씀하시는 지 구체적으로 알 수 있을까요?

문의 빠르게 확인주셔서 감사합니다!

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.
비즈채널 API 문서에 나온 StatusReason 코드는 전체 상태이유 코드 목록을 나타내고 있습니다. 해당 목록중에 일부가 비즈채널에 적용이 됩니다.
키워드와 광고그룹쪽은 아직 업데이트가 되지 않아 이전 코드목록을 보여주고 있습니다. 빠르게 업데이트 하도록 하겠습니다.

PC_MOBILE_TARGET의 JSON 구조 (`pc`, `mobile` 프로퍼티가 필수, 타입은 boolean)에 맞지 않을 경우입니다. 
예를 들어 아래와 같이 되어 있을 경우 발생할 수 있습니다.

```
- {"pc":"true","mobile":"true"}
- {"pc":true}
- {"mobile":true}
- {"NAVER":true}
- {"pc":true,"MOBILE":true}
- {}
```

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

광고그룹 상태이유에 아래와 같은 코드가 나올수 있습니다.

* ELIGIBLE
* GROUP_DELETED
* BUSINESS_CHANNEL_UNDER_REVIEW
* BUSINESS_CHANNEL_ABNORMAL_INTERLOCK
* BUSINESS_CHANNEL_DISAPPROVED
* PC_BUSINESS_CHANNEL_DISAPPROVED
* PC_BUSINESS_CHANNEL_UNDER_REVIEW
* MOBILE_BUSINESS_CHANNEL_DISAPPROVED
* MOBILE_BUSINESS_CHANNEL_UNDER_REVIEW
* GROUP_PAUSED
* CAMPAIGN_PAUSED
* GROUP_LIMITED_BY_BUDGET
* GROUP_LIMITED_BY_SHARED_BUDGET
* CAMPAIGN_LIMITED_BY_BUDGET
* CAMPAIGN_LIMITED_BY_SHARED_BUDGET
* CAMPAIGN_PENDING
* CAMPAIGN_ENDED
* CAMPAIGN_DELETED

감사합니다.

**Comment by serrimm** [comment]
@naver-searchad 바쁘신 와중에, 친절한 답변 감사합니다!
최종적으로 추가 문의 전달드리오니 확인 부탁드리겠습니다 (__)..!

1. 전달주신 광고그룹 상태이유 내 GROUP_PAUSED_BY_INVALID_TARGET 해당 코드가 존재하지 않는 것으로 보이는데요, 해당 코드는 어느 API 에서 확인 가능한 코드인 지 문의드립니다!
2. LACK_OF_ACCOUNT_BALANCE 상태이유 코드는 어느 API에서 확인 가능 한 지 문의드립니다.
3. 키워드 API에서 확인 가능한 상태이유 코드 목록도 전달 가능하실까요?

정확한 확인을 위해 여러 번 문의드리는 점 양해 부탁드립니다! 감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

1. GROUP_PAUSED_BY_INVALID_TARGET 코드도 광고그룹의 상태이유에 포함됩니다. (기존 코멘트에 빠져 있어서 추가 했습니다.)
2. LACK_OF_ACCOUNT_BALANCE 상태이유 코드는 광고주의 상태에 포함이되고, 비즈머니관련 상태를 나타냅니다. 그렇기 때문에 광고주 정보를 포함하는 여러곳의 API에서 나타날 수 있습니다.
3. 광고키워드의 상태이유 코드는 대략 아래와 같습니다.
* KEYWORD_DELETED
* KEYWORD_DISAPPROVED
* KEYWORD_UNDER_REVIEW
* KEYWORD_DENIED
* KEYWORD_PAUSED
* ELIGIBLE
