### ISSUE TITLE
keywordstool api 에서 검색조건으로 검색 건

### ISSUE THREAD

**Issue by jesu237** [naver/searchad-apidoc#912]
keywordstool api 에보면 카테고리나 검색일자를 지정하는 것을 못찾아서 문의드립니다

스마트스토어에서 상품을 등록할때 선택해야하는카테고리를 네이버 검색광고 연관키워드 api인 keywordsttol api에서 사용하려면 어떻게 해야하는지요

keywordstool api 를 사용했는데 검색조건으로
네이버에서 제공하는 카테고리(네이버에서는 3자 카테고리가 있음)를 선택하고
검색일자를 검색시작일과 검색종료일을 지정하여 조회하려연 어떻게 해야하는지요?

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

----
keywordstool은 추천 키워드를 전달하고 해당 추천 키워드들에 대한 대략적인 qc 를 제공하는 것을 목적으로 하고 있습니다.
따라서 해당 API 는 날짜 범위를 가지는 요청이 아님을 알려드립니다.

감사합니다.
