### ISSUE TITLE
현재 순위를 알수있는 API 문의 건

### ISSUE THREAD

**Issue by jesu237** [naver/searchad-apidoc#915]
제가 스마트스토어에 상품을 올리고 있는데, 스마트스토어에 올라간 상품들의 현재 순위를 알수 있는 API가 있는지요?

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

광고의 현재 노출 순위를 확인할 수 있는 방법을 API로 제공하고 있지는 않습니다.

감사합니다.
