### ISSUE TITLE
소재의 상태에 대한 구체적인 사유 확인 가능여부 문의

### ISSUE THREAD

**Issue by choics** [naver/searchad-apidoc#917]
안녕하세요.
소재 및 확장소재의 상태에 대해서 정상 상태가 아닐경우(노출 제한 상태 등..) 구체적인 사유를 확인하고 싶습니다.

네이버 광고센터에서는 동일한 상태(확장 소재 노출제한) 으로 확인되나 상태 클릭하여 사유를 확인하면

품질이 낮은 이미지는 등록할 수 없습니다.
이미지는 광고대상 ‘상품’과 충분한 관련이 있어야 합니다.
등 서로 다른 사유를 확인할 수 있습니다.

구체적인 사유에 대해 대량으로 확인할 수 있는 방법이 있을지 확인 부탁드립니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

등록한 광고키워드, 광고 소재, 확장 소재의 검수 보류/반려 이유에 따른 상세한 "상태이유" 값은 따로 제공하지 않고 있습니다.

감사합니다.
