### ISSUE TITLE
브랜드검색 소재 상세 데이터

### ISSUE THREAD

**Issue by h-y-e-j-i** [naver/searchad-apidoc#918]
안녕하세요.

API로 브랜드검색 소재 상세 데이터를 가져올 수 있나요?
이미지와 같이 홈링크.링크, 메인이미지.링크, 메인텍스트.링크 별 노출수, 클릭수 값을 가져오고 싶습니다.

![image](https://github.com/naver/searchad-apidoc/assets/58590260/cc535081-0e93-4a29-a015-3228b86dd7b3)

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

브랜드 검색 소재의 상세 데이터 지표는 검색광고 API로 제공하지 않고 있습니다.

감사합니다.
