### ISSUE TITLE
키워드/소재/확장소재 InspectStatus 값 관련 문의

### ISSUE THREAD

**Issue by taetaej** [naver/searchad-apidoc#919]
안녕하세요.

키워드/소재/확장소재 InspectStatus 값 관련 문의드립니다. 

**1. 문서마다 InspectStatus 값에 대한 안내가 상이하여 확인 요청드립니다.** 
하기의 다섯 개 값이 존재하는 게 맞는지, 값 별 국문 해석이 맞는지도 같이 확인 부탁드립니다. 

10:UNDER_REVIEW → 검수 대기
20: APPROVED → 통과
21: ELIGIBLE → 사용 가능
30: LIMITED_APPROVED → 보류
40: PENDING → 반려

(하기 이미지는 API 가이드에서 안내하고 있는 소재(AD)의 InspectStatus 값 입니다.)
![image](https://github.com/naver/searchad-apidoc/assets/161435506/41633d4b-c397-4a39-a28d-e19827f6025e)

2. 네이버 광고플랫폼에서 키워드와 소재의 '노출제한' 상태인 경우에만 재검토 요청이 가능한 것으로 안내되고 있습니다.
그렇다면, **InspectStatus가 PENDING인 경우에만 재검토 요청이 가능한 것으로 이해하면 될런지요?**

만약 아니라면 재검토 요청을 할 수 있는 '노출제한'에 해당하는 다른 값 기준에 대해 안내 부탁드리겠습니다. 

3. InspectStatus의 ELIGIBLE 값의 경우 쇼핑검색(쇼핑몰상품형)에서만 확인되는게 맞는지 확인 부탁드립니다.
3-1. 쇼핑검색(쇼핑몰상품형)에서만 확인되는 게 맞다면 사유도 같이 알 수 있을지요?

바쁘시겠지만 확인 부탁드리겠습니다!

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

1. 네이버 검색광고의 검수 상태는 아래와 같습니다.
* UNDER_REVIEW: 검수 대기
* APPROVED: 통과
* PENDING:  보류
* DENIED: 반려
* ELIGIBLE: 사용 가능

2. 검수상태가 PENDING인 경우에만 재검수 요청을 할 수 있습니다.
3. 광고소재는 수정이 되지 않지만, 쇼핑 검색과 같이 기존 노출 소재의 이미지를 수정할 경우, 이전 검수 상태에 따라 ELIGIBLE 상태를 잠시 가질수 있습니다.

감사합니다.
