### ISSUE TITLE
API 파라미터 문의

### ISSUE THREAD

**Issue by ccwon77** [naver/searchad-apidoc#92]
안녕하세요. Naver Search Ad API를 이용하려고 예시 코드를 보고 있는데, 
파라미터가 잘 이해되지 않아서요.

깃헙에 있는 ad_management_sample.php 예시 (https://github.com/naver/searchad-apidoc/blob/master/php-sample/ad_management_sample.php) 를 보면,

$api = new RestApi($config['BASE_URL'], $config['API_KEY'], $config['SECRET_KEY'], $config['CUSTOMER_ID'])

라고 있는데, 다른 건 알겠는데, BASE_URL은 무엇을 입력해야 하나요? 여기에 대한 정보는 어디에서 찾아볼 수 있는지요?

빠른 회신 주시면 감사하겠습니다.

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

우선 답변이 늦어 죄송합니다. 

저희 검색광고 서비스의 기본 호출 URL 입니다. 
BASE_URL = "https://api.naver.com"
샘플 코드 중에 sample.ini 을 보시면 변수별 데이터 이해에 도움이 되실 것 같습니다. 

감사합니다.
