### ISSUE TITLE
BusinessChannel: create 관련 문의

### ISSUE THREAD

**Issue by nitmus-lab-jack** [naver/searchad-apidoc#920]
안녕하세요.

API를 통한 비즈채널 추가 관련하여 문의사항이 있어 글 남깁니다.

POST /ncc/channels 을 통해 비즈채널 전화번호 추가 테스트 진행중에 있는데요 

아래와 같이 데이터 전달시 400에러가 발생하고 있습니다.
혹시 전달 데이터중 문제가 되거나 빠진 항목이 있을까요?

요청
`{'channelTp': 'PHONE', 'name': 'PHONE_ADD_TEST', 'businessInfo': {'phone': '0212345678', 'primary': None, 'secondary': None, 'countryCallingCode': '+82', 'phoneTp': 'NORMAL', 'mobileCertStatus': 20}}`

응답
`{'code': 1002, 'status': 400, 'title': 'Invalid request'}`

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

전화번호 채널은 API를 이용하여 등록할 수 없습니다.
API로 등록가능한 채널은 'SITE' 유형의 채널만 가능합니다.

감사합니다.

**Comment by nitmus-lab-jack** [comment]
확인 감사합니다.

그럼 유효한 channelTp 은 SITE 한가지라고 보면 될까요?

api 문서상에는 SITE외 여러가지가 유효하다고 나와있어서 확인차 문의드립니다.

<img width="679" alt="image" src="https://github.com/naver/searchad-apidoc/assets/11782761/b027675a-1c13-4a45-a7d8-9bbaebb5490c">

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

api 문서의 channelTp 값은 조회시 받은 값기준으로 작성이 되어 있어서 모두 표시가 되고 있습니다.
'EXAMPLE' 버튼을 클릭해서 예제를 보시면, SITE 값 외에 등록 불가하다는 설명이 되어 있습니다.

감사합니다.

**Comment by nitmus-lab-jack** [comment]
넵 내용 확인 했습니다.
감사합니다~!
