### ISSUE TITLE
반응형 소재 리포트 문의

### ISSUE THREAD

**Issue by SM10855** [naver/searchad-apidoc#921]
안녕하세요.
3월 20일에 반응형 소재유형이 추가된다고 공지를 확인했습니다.

https://naver.github.io/searchad-apidoc/#/release-notes

Master Report 또는 StatReport 에 item에 신규로 추가되는 건지, 기존 소재데이터에 포함되어 받아오는지 문의드립니다.

https://naver.github.io/searchad-apidoc/#/tags/MasterReport
https://naver.github.io/searchad-apidoc/#/tags/StatReport

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

MASTER의 경우 ASSET과 ASSET과 AD간의 연결 정보는 제공하는 2개의 신규 마스터가 추가됩니다. 

지표의 경우 STAT REPORT의 AD를 통해 제공됩니다. 단 이때 제공되는 항목은 기존의 AD와 동일하게 AD ID 별 지표가 되며 ASSET별 지표는 제공되지 않습니다. 
반응형 소재로 인해 신규로 제공되는 지표는 ASSET과 AD간의 연결 아이디(nccAdAssetLinkId)별 노출수가 있는데요. 이 값은 대용량 보고서 형태로 제공드리는 것에 사용상 큰 이득이 없어 STAT API를 통해서만 제공됩니다. 

신규 추가되는 마스터 및 기존 소재 마스터 수정 사항에 대해서는 금주 중 공지가 게시될 예정입니다. 

감사합니다.

**Comment by SM10855** [comment]
기존 STAT-REPORT를 통해서 제공하는 AD에 는 신규로추가되는 지표가 없고,
STAT API를 통해서 받아볼 수 있는거로  보면 되는게 맞죠

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 보고서 담당자입니다. 

우선 답변 드리기 전에 한가지 제가 잘못 답변 드린 사항이 있어 정정합니다. 
마스터는 총 3개가 추가 됩니다. 
1. ASSET 마스터 
2. ASSET과 AD간의 관계를 나타내는 마스터 
3. RSA용 AD 마스터 --> 기존의 AD MASTER를 그대로 사용할수 없어 추가합니다. 

그리고 답변을 드리자면 이해하신 바가 맞습니다. 
RSA 용 AD의 기본적인 지표들인 노출/클릭/광고비/전환 등은 기존의 STAT REPORT를 통해 제공됩니다. 
이때 AD ID는 RSA용 AD 마스터 를 통해 조회 하실수 있습니다. 
신규 추가 되는 ASSET과 AD간의 연결 아이디(nccAdAssetLinkId)별 노출수는 대용량 보고서를 통해 제공되지 않고 STAT API에만 존재하게 됩니다. 

감사합니다.

**Comment by SM10855** [comment]
상세한 답변 감사드립니다.

**Comment by naver-searchad** [comment]
@SM10855 님 
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

관련 공지가 게시되어 코멘트 드립니다.
https://naver.github.io/searchad-apidoc/#/notice

감사합니다.

**Comment by SM10855** [comment]
안녕하세요. 

공유해주셔서 감사합니다.
