### ISSUE TITLE
RelKwdStat 관련 문의 드립니다 (Recent 30 days)

### ISSUE THREAD

**Issue by Outouniverse** [naver/searchad-apidoc#922]
안녕하세요, RelKwdStat 관련하여 질문 드립니다.

Property 중 monthlyPcQcCnt와 monthlyMobileQcCnt 설명을 보면 

최근 30일 동안의 PC, 모바일 검색수 합계라고 설명이 되어있는데,

예를 들어 오늘('24.03.12) 오후 1시 기준으로 API에  '콜라' 키워드를 날리게 되면 

그 결과값은 '24.02.11 ~ '24.03.11, 30일 간의 '콜라' 키워드 검색량 절대값인 것으로 이해해도 될까요?

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

조회일 기준 전일까지의 30일동안(전일 포함) 의 검색수의 합입니다.

감사합니다.
