### ISSUE TITLE
LabelRef 관련 문의

### ISSUE THREAD

**Issue by serrimm** [naver/searchad-apidoc#923]
안녕하세요, LabelRef 관련 문의 드립니다.

LabelRef:update 는 광고그룹, 소재, 키워드에 설정된 즐겨찾기를 수정하는 API 가 맞을까요?

맞다면, 필수 입력 파라미터가 무엇인 지 알 수 있을까요? 
API 문서 내 파라미터 항목 확인 시에는 전체 항목이 표기되는데 해당 파라미터 모두 필수적으로 입력이 필요한 부분인 지 확인 부탁드립니다.
- customerId, editTm, enable, nccLabelId, refId, refTp, regTm

추가적으로, LabelRef API 는 샘플 코드가 존재하지 않는 것인 지 확인 부탁드립니다.

감사합니다 :)

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

GET /ncc/labels 를 이용하여 즐겨찾기 목록을 가져올 수 있습니다.

응답값은 아래와 같습니다.

```
[
    {
        "nccLabelId": "lbl-m001-00-000000000000000",
        "customerId": 123456,
        "name": "주요키워드1",
        "color": "#E65050",
        "regTm": "2010-01-13T02:56:31.000Z"
    }
]
```

그리고 labelId를 이용하여 아래와 같이 광고그룹, 광고 키워드, 광고 소재 목록을 조회할 수 있습니다.

* http://naver.github.io/searchad-apidoc/#/operations/GET/~2Fncc~2Fadgroups%7B%3FnccLabelId%7D

http://naver.github.io/searchad-apidoc/#/operations/PUT/~2Fncc~2Flabel-refs API를 이용하여 조회된 즐겨찾기에 정보를 추가하거나 삭제 할 수 있습니다.

필수 정보는 아래와 같습니다.
* customerId(광고주 정보)
* nccLabelId(즐겨찾기 번호)
* refId(추가/변경할 광고그룹, 광고소재, 광고 키워드, 확장 소재  ID)
* refTp(광고그룹, 광고소재, 광고 키워드, 확장 소재 유형)
* enable (추가-true/삭제-false 여부)


감사합니다.
