### ISSUE TITLE
Estimate InternalServerError 관련 문의

### ISSUE THREAD

**Issue by KMGeon** [naver/searchad-apidoc#924]
안녕하세요.
노출 최소, 중간 입찰가를 얻어오는 과정에서 궁금한 사항이 있어서 문의합니다.
해당 API를 호출하면 다음과 같은 에러가 발생합니다.

현재 Estimate 관련 API는 네이버 자체적인 문제인지 궁금합니다.

- 만약 네이버 서버적인 이슈이면 관련 API가 언제 정상화가 가능한지 궁금합니다.

```json
{
    "name": "InternalServerError",
    "status": 500,
    "title": "Internal Server Error",
    "detail": "A failure of processing the request message due to the internal execution error of the NAVER Search Ads system"
}
```

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 기능담당자입니다. 

알려주신 내용만으로는 언제 , 무엇을, 어떻게 호출 하셨는지 알수 없으므로 답변을 드리기 어렵습니다. 
호출시 리턴된 헤더에 존재하는 transaction ID와 호출 일시를 알려 주십시오. 
저희가 조사를 하는데에는 transaction ID와 호출 일시외에 어떠한 추가 정보도 필요하지 않으며 
이곳은 전체 공개된 곳이므로 라이선스키나 비밀키 등을 기재하지 않도록 주의하여 주시기 바랍니다. 

감사합니다.

**Comment by KMGeon** [comment]
안녕하세요. 답변 감사합니다.

트랜잭션 ID ( X-transation-id) : f2183f7e2a677dce 입니다.

**Comment by naver-searchad** [comment]
@KMGeon 님 
기능 담당자입니다. 

혹 호출 일자와 시간(기준 시간대와 함꼐)도  알려 주실수 있으실까요?

감사합니다.

**Comment by KMGeon** [comment]
현재 다시 API를 호출을 했습니다.
API 호출 시간:   2024년 3월 15일 오전 1시 15분 42초
트랜잭션 id : 78947db41ad9e64e

**Comment by naver-searchad** [comment]
@KMGeon 님

안녕하십니까 기능 담당자입니다. 

호출 URI가 잘못되어 에러가 발생하였습니다.

호출 하실때 
/api/npla-estimate/exposure-minimum-bid/nkw-a001-02-000000000000000
위와 같이 호출 대상 아이디값을 기입하시셨는데요. 

우선 npla(네이버 쇼핑검색광고)에서는 키워드가 존재하지않습니다. 소재와 상품으로 조회가 가능하구요. 
items에 소재로 조회를 하실 경우에는 
"/api/npla-estimate/exposure-minimum-bid/id"
이런식으로 실제 소재 아이디값이 아니라 단어 "id"로 기입 후 바디 items에 소재아이디를 넣어주시면 되고
상품으로 조회 하실때는 
"/api/npla-estimate/exposure-minimum-bid/product"
제일 마지막에 "product"로 기입 후 바디 items에 상품 아이디(네이버 쇼핑 상품아이디)를 넣어주시면 됩니다.

저희 메뉴얼에 설명이 작성할때는 인지하지 못하였는데 이제와서 보니 좀 헷갈리게 표현이 되어 있어서 
잘못 호출 하신것 같습니다.혼란 드려 죄송합니다. 
좀 더 명확하게 표현할수 있도록 문구를 수정하거나 샘플 메세지 추가를 고려해 보겠습니다.

추가로 500에러가 리턴되는 이유도 궁금하실텐데요. 
저희 내부 서비스 구조로인한 것이라 상세한 설명을 드리지 못하는점 양해 부탁드립니다. 

마지막으로 저희가 서비스하고 있는 API들의 거의 대부분은 광고관리시스템(manage.searchad.naver.com)에서도 함께 사용하고 있습니다;
글로만 설명을 드리니 명확하게 설명 드리기가 조금 어려운데요. 
광고관리 시스템 UI에서 해당 기능을 호출 하시고, 서버와 주고 받는 메세지를 보시면 좀더 이해에 도움이 되실수 있을것 같습니다.

감사합니다.

**Comment by KMGeon** [comment]
넵 답변 감사합니다. 👍🏻
