### ISSUE TITLE
네이버 브랜드 검색 소재 미리보기 문의 건

### ISSUE THREAD

**Issue by h-y-e-j-i** [naver/searchad-apidoc#925]
안녕하세요. 네이버 브랜드 소재 미리보기 - 항목 상세보기를 API로 가져올 수 있는 방법이 있을까요?

![image](https://github.com/naver/searchad-apidoc/assets/58590260/a32c964d-1f3c-4fc0-ab49-40f85761dfdd)

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

브랜드검색관련 기능은 검색광고 API로 제공이 되지 않습니다.

감사합니다.
