### ISSUE TITLE
Stat by statType 기간 지정 문의건

### ISSUE THREAD

**Issue by whdcks4904** [naver/searchad-apidoc#926]
안녕하세요.

stat get by statType 를 요청하면 지난 30일 기준으로 response data를 받을 수 있는데요,
여기서 parameter값을 변경하여 지난 90일 까지 데이터를 받을 수 있는 방법이 있는지 문의 드립니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

해당 API가 제공하는 데이터는 30일단위로 적재하고 있으며 기간에 대한 파라미터를 따로 제공하고 있지 않습니다.

감사합니다.
