### ISSUE TITLE
/stats 값이 반환되지 않는 이슈

### ISSUE THREAD

**Issue by GyuBumKim** [naver/searchad-apidoc#927]
현재 /stats API 를 사용 중 입니다.

광고 그룹에 breakdown 으로 연령, 성별을 넣을 경우 데이터가 넘어옵니다.

breakdown을 제외하고 광고 그룹 아이디를 넣으면 값이 모두 0으로 반환 됩니다.

keyword 데이터도 모두 0으로 넘어오고 있습니다.

몇달 전에 개발할 시엔 값을 확인했었는데 변경된 사항이 있을까요?

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

저희쪽에서 API를 이용하여 확인한 결과 특이사항이 발견되지 않았습니다.
또한 문의하신 부분에 대한 저희쪽 변경사항이 없어서 조금더 많은 정보를 알려 주셔야 할듯 합니다.

API 호출 정보를 알려주시면 로그를 확인해 보도록 하겠습니다.
