### ISSUE TITLE
소재 상세 데이터 매핑 테이블 문의 건

### ISSUE THREAD

**Issue by h-y-e-j-i** [naver/searchad-apidoc#928]
안녕하세요.
`/stats`에 `breakdown=eventCode` 파라미터를 추가하여 소재 상세 데이터를 받고 있는데요.
대시보드처럼 한국어 변경하고 싶은데, 혹시 관련 매핑 테이블이 있는지 문의드립니다.

![image](https://github.com/naver/searchad-apidoc/assets/58590260/3c526709-9a16-4359-86c2-e845a5ed3a7a)
![image](https://github.com/naver/searchad-apidoc/assets/58590260/6bcebb9d-db11-4f93-ac69-6bd09b418f6b)

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.
eventCode에 대한 name값들을 제공하는 API는 제공하고 있지 않습니다.

감사합니다.
