### ISSUE TITLE
검색광고 소재관련 API 확인 요청드립니다

### ISSUE THREAD

**Issue by bomwo** [naver/searchad-apidoc#929]
안녕하세요 검색광고 소재 관련 API 확인 요청드립니다.

현재 [문서](https://naver.github.io/searchad-apidoc/#/operations/GET/~2Fncc~2Fads%7B%3FnccAdgroupId%7D)에 있는 GET /ncc/ads{?nccAdgroupId}를 사용중에 있습니다.

그룹아이디로 소재데이터를 조회하는 API인데 여기서 특정 소재가 조회되지 않는것을 확인했는데 모두 삭제된 소재인것을 확인했습니다.
위 /ncc/ads{?nccAdgroupId} 의 경우는 삭제된 소재 값을 제공하지 않는게 맞을까요? 맞다면 삭제된 소재 값을 조회할 수 있는 방법이 있는지 궁금합니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.
/ncc/ads{?nccAdgroupId} API는 삭제된 소재는 포함하지 않습니다.
삭제요청된 소재는 검색광고에서 바로 삭제가 되고, 삭제된 소재를 조회할 수 있는 별도의 API는 제공하고 있지 않습니다.

감사합니다.

**Comment by bomwo** [comment]
> 안녕하세요? 네이버 검색광고 API입니다. /ncc/ads{?nccAdgroupId} API는 삭제된 소재는 포함하지 않습니다. 삭제요청된 소재는 검색광고에서 바로 삭제가 되고, 삭제된 소재를 조회할 수 있는 별도의 API는 제공하고 있지 않습니다.
> 
> 감사합니다.

답변되었습니다 감사합니다.
