### ISSUE TITLE
비즈머니 기간 검색 api 건의

### ISSUE THREAD

**Issue by lee-ji-eun** [naver/searchad-apidoc#93]
비즈머니 api에 기간 검색에 대한 api를 추가해주실 수 있는지 문의드립니다.
하루하루 검색해서 건건이 가져와 처리하니 시간이 너무 많이 걸려서요...
기간단위로 가져올 수 있게 api에 추가해주실 수 있는지 여쭙니다.

**Comment by lee-ji-eun** [comment]
현재 원하는건 일정 기간에 대해서 광고 소진액 합계입니다.
아직 개발 예정에는 없으나 현황의 소진탭의 기능이 있으면 좋을 것 같습니다.

**Comment by naver-searchad** [comment]
@lee-ji-eun 
안녕하십니까 검색광고 API 입니다. 

네 말씀 주신 내용 기반으로 상세 스팩과 작업 일정을 검토해 보겠습니다. 
단, 기간 합계인 경우 리턴에 걸리는 시간이 길어 질 수 있어서 장기간은 조금 어려울듯 싶긴 합니다. 

추가로 현재 저희 작업 일정을 간략히 본바 단기간에 지원은 조금 어려울 듯 싶습니다. 
이점 양해 부탁드립니다.  스팩과 일정이 
확정되면 공지 게시판(doc.api.naver.com)을 통해 공지 드리겠습니다.

감사합니다.

**Comment by lee-ji-eun** [comment]
@naver-searchad 
공지사항에 아직 안올라와있는데 아직 안된거 맞나요?
6개월이상 지났는데 무소식이네요.
대략적으로 언제쯤 기획이 될지 문의드립니다.

**Comment by naver-searchad** [comment]
@lee-ji-eun 

안녕하십니까 검색광고 API입니다.

현재 개발 작업 중입니다.  거의 작업이 마무리 단계라 이번달에는 제공 공지를 드릴 수 있을것 같습니다.

감사합니다.
