### ISSUE TITLE
place ad ad master 가져오기

### ISSUE THREAD

**Issue by moominbelly** [naver/searchad-apidoc#930]
안녕하세요 master report 를 사용하는중에 place ad  master report를 가져오고 싶은데
항목중에 place ad report 가 https://naver.github.io/searchad-apidoc/#/operations/GET/~2Fmaster-reports 에는 보이지 않는데 
어떤 항목으로 가져와야 place ad 에 대한 소재 등등을 가져올 수 있을까요 ?

**Comment by naver-searchad** [comment]
@moominbelly 안녕하세요. 검색광고API 입니다.
https://naver.github.io/searchad-apidoc/#/tags/MasterReport 이 페이지에서, 
"Place ad ad Master (PlaceAd)"를 확인하시면 됩니다. 아이템 코드는 `PlaceAd`입니다.

**Comment by moominbelly** [comment]
@naver-searchad  안녕하세요, 확인해 보았는데 ui 상에서는  place ad 퍼포먼스를 확인해 볼 방법이 없나요 ? 
대용량 다운로드 보고서에 항목이 없는걸로 보입니다. 
![master_report](https://github.com/naver/searchad-apidoc/assets/77463110/3b2309e8-befa-4a4c-8c73-8fda8a88a65d)

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

https://naver.github.io/searchad-apidoc/#/tags/MasterReport  레퍼런스 페이지에서 누락된 부분은 수정 완료해 두었습니다. 
광고관리사이트 대용량 다운로드보고서 메뉴에서는 플레이스 소재 마스터는 제공드리지 않습니다. 

감사합니다.

**Comment by moominbelly** [comment]
@naver-searchad 
안녕하세요 여기 보면 place ad api는 지원을 안한다고 하는데 어떤것이 맞는건가요? 
제가 이해한 바로는 소상공인 광고만 지원하고 나머지 플레이스 광고를 지원을 안한다는거라면 
place ad ad master는 플레이스 광고가 아닌건가요 ?

https://github.com/naver/searchad-apidoc/issues/670

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 보고서 담당자입니다. 
 
플레이스광고 (https://saedu.naver.com/adbiz/searchad/placeSearch.naver) 상품은 API를 통해 공식 지원이 되지 않습니다. 
대용량 보고서(마스터 포함)도 제공되지 않습니다.  현재 마스터의 item = placead는 소상공인 광고의 소재 정보를 담고 있습니다. 

상세사항은 https://github.com/naver/searchad-apidoc/issues/670의 내용을 참고해 주십시오. 

감사합니다.
