### ISSUE TITLE
exceeded limit of '100' numbers of 'job' 문의드립니다.

### ISSUE THREAD

**Issue by violetismeand** [naver/searchad-apidoc#931]
Report를 조회하는 과정에서 아래와 같은 오류가 발생합니다.
ResponseException(status=400, errorCode=null, errorMessage=Bad Request, detailErrorMessage=exceeded limit of '100' numbers of 'job')

계정 화면에서 확인했을 때, 해당 계정의 리포트가 100개를 넘어가지 않습니다.

확인 부탁드립니다. :)

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다. 

말씀 주신 현상이 발생하는 호출의 트랜젝션 아이디와 호출 일시를 알려주실수 있으실지요?
(이곳은 공개된 공간이므로 라이선스 키와 비밀키 등, 저희가 요청드리지 않은 정보를 기재하지 않도록 주의 부탁드립니다. 
저희는 트랜잭션 아이디와 호출 일시만으로도 충분히 모든 정보를 확인할수 있습니다.) 
이 현상은 두가지 원인이 존재할수 있는데요.  

1. 동일 계정에 대해 여러 사용자가 사용하고 있는 경우 “우연히” 다른 사용자를 통해 생성된  보고서가 100개 였던 시점에 생성 요청을 하신 경우  
2. 삭제되었어야 하는 보고서들이 저희 내부 작업(스토리지 교체나 업그레이드 등) 과정에서 미처 삭제되지 않고 남아 있는 경우(이 경우에는 보고서 리스트에서는 제거되었지만...실제 보고서는 저희 스토리지에 남아 있어서 보고서 조회시 보이지 않습니다.)

위의 경우 중 대부분의 경우는 2번 케이스로 트랜잭션 아이디와 호출 시점 정보를 주시면 저희가 조치를 할수 있습니다. 

불편 드려 죄송합니다.

**Comment by violetismeand** [comment]
트랜젝션 아이디는 확인이 어렵습니다. ㅠㅠ

혹시 customerId로 확인은 어려우실까요?

답변 부탁드립니다. :)

**Comment by naver-searchad** [comment]
@violetismeand 위 두 광고주id에 대해서, 잘못 카운트된 job 정보를 조치했습니다. 불편을 드려서 대단히 죄송합니다.

**Comment by violetismeand** [comment]
@naver-searchad 

정상 동작 확인했습니다. :)

감사합니다.
