### ISSUE TITLE
안녕하세요? 궁금한 점이 있어 여쭤봅니다!

### ISSUE THREAD

**Issue by tkdals920403** [naver/searchad-apidoc#932]
구글시트 내에 앱스스크립트를 활용하여
네이버 검색광고에 대한 광고 성과를 불러오고 싶은데,
개발에 대한 지식이 전혀 없습니다.

어떠한 유형이든 상관 없으니(일별 데이터이든, 키워드 데이터이든 상관X)
광고 성과에 대한 데이터를 불러오는 예시 코드를 알 수 있을까요?

해당 코드를 기반으로 공부하며 수정을 하고 싶습니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다. 아래 예제를 활용하면 어떨까 합니다.

https://github.com/naver/searchad-apidoc/tree/master/java-sample/src/main/java/com/naver/searchad/api/rest

감사합니다.
