### ISSUE TITLE
keyword 데이터 api 문의입니다.

### ISSUE THREAD

**Issue by hyung-kyung** [naver/searchad-apidoc#934]
검색광고 /stats api를 사용하여 keyword 데이터를 조회하고 있는데 키워드 데이터 값이 항상 0으로 넘어오고 있습니다.
지난 1년 동안 잘 사용하고 있었는데 언제부턴가 키워드 데이터기 모두 0으로 내려 옵니다.
아래 주소 API reference 를 참고해서 개발했고, 현재 내용이 변경된 것으로 보이지 않는데, 뭔가 수정된 것이 있다면 확인 부탁드립니다.

https://naver.github.io/searchad-apidoc/#/operations/GET/~2Fstats%7B%3Fid,fields,timeRange,datePreset,timeIncrement,breakdown%7D

**Comment by naver-searchad** [comment]
안녕하세요. 검색광고 API 담당자 입니다.

말씀주신 stats api에서는 변동사항이 없습니다. 해당 api 확인결과 이상이 발견되지 않았습니다. 
이상현상이 재현된다면 호출정보를 전달주시면 추가확인해보도록 하겠습니다.

감사합니다.
