### ISSUE TITLE
StatReport 에서 제공하는 금액 데이터는 모두 부가세 미포함 금액인가요?

### ISSUE THREAD

**Issue by bizspring-sangwon** [naver/searchad-apidoc#935]
안녕하세요.
다름이 아니라 네이버 검색광고 StatReport API [https://naver.github.io/searchad-apidoc/#/tags/StatReport] 에서 제공하는 금액 관련 데이터(총비용, 전환매출액 등)은 부가세 미포함인가요?

report_tp AD_CONVERSION 에서 Sales by conversion 항목의 부가세 포함여부가 궁금해서 문의드립니다.

**Comment by naver-searchad** [comment]
안녕하세요 대용량다운로드보고서 담당자입니다.

총비용과 같은 광고비는 모두 VAT제외 금액이며, 전환매출액은 광고주 사이트에서 설정된 전환 스크립트를 통해 광고주가 제공하는 값이므로, VAT가 포함된 금액인지 여부는 알 수 없습니다.

감사합니다.
