### ISSUE TITLE
기능 사용 가능 여부

### ISSUE THREAD

**Issue by beerbank3** [naver/searchad-apidoc#936]
검색광고 API가 아니라 검색광고 시스템에서 제공하는 기능들을 호출하여 데이터를 사용하는게 가능할까요?

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

네이버 검색광고 API는 광고 관리 시스템의 기능중 일부를 Open API로 제공하고 있습니다. 공개된 Open API외에 다른 기능은 검색광고 API를 이용하여 사용할 수 없습니다.

감사합니다.

**Comment by beerbank3** [comment]
검색광고 시스템에서 제공하는 URI를 직접 사용해서 기능을 사용해도 되나요?

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

유효한 네이버 검색광고 API 라이선스와 비밀키를 이용하여 생성된 인증 토큰으로URI를 호출한 경우에 API 사용으로 간주하고 있습니다.  즉 API 사용 여부는 인증 방식으로 구분하고 있다고 생각해 주시면 쉽게 구분이 가능하실 것 같습니다. 
한편, API를 이용하지 않은 호출 중 광고관리사이트 UI를 통해 생성되지 않은 호출은 서비스 이용 약관에서 금지하고 기계적 호출에 해당하며, UI를 통해 생성된 호출일지라도 과도하게 빠른 속도나 양으로 인해 검색광고 서비스에 운영 영향을 주게 되면 접근 차단/계정 해지 조치가 있을수 있으며 사안이 중대한 경우 민/형사상 책임이 발생할수 있습니다. 

감사합니다.
