### ISSUE TITLE
캠페인명, 캠페인 하루 예산 수정 가능 API 여부 문의

### ISSUE THREAD

**Issue by SM11187** [naver/searchad-apidoc#937]
안녕하세요.

https://naver.github.io/searchad-apidoc/#/operations/PUT/~2Fncc~2Fcampaigns~2F%7BcampaignId%7D%7B%3Ffields%7D
위 url에서 찾아보니 Adgroup에는 파라미터로 name, dailyBudget이 존재하는데 Campaign에는 없어서
캠페인명과 캠페인 하루예산을 수정할 수 있는 API가 있는지 궁금합니다.

가능하다면 사용 예시 코드 하나만 부탁드리겠습니다!

감사합니다 (_ _)

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

캠페인 하루 예산 수정할 수 있는 API는 http://naver.github.io/searchad-apidoc/#/operations/PUT/~2Fncc~2Fcampaigns~2F%7BcampaignId%7D%7B%3Ffields%7D 를 사용하시고, field 파라미터에 budget을 입력하시면 됩니다.

또한 캠페인 이름은 아래와 같이 가능합니다.
1. 캠페인 정보 조회
2. 응답에서 이름을 변경 (다른 값을 수정하면, 수정된 값이 반영되기 때문에 주의가 필요합니다.)
3. field 파라미터 없이 http://naver.github.io/searchad-apidoc/#/operations/PUT/~2Fncc~2Fcampaigns~2F%7BcampaignId%7D%7B%3Ffields%7D 호출 


감사합니다.
