### ISSUE TITLE
asset report 문의 

### ISSUE THREAD

**Issue by moominbelly** [naver/searchad-apidoc#938]
안녕하세요 @naver-searchad 

이번에 새로 추가된 반응형 소재들의 stat report 에 대한 문의 입니다. 
현재는 asset id 로 세세한 노출수를 확인할 수있는 stat report 가 따로 없나요 ? 

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요 대용량다운로드보고서 담당자입니다.

현재 asset id에 대한 stat report는 따로 제공 중이지 않고, asset id와 nccAdAssetLinkId(asset과 ad 간 연결 Id) 별 노출수는 stat api로만 제공하고 있습니다.

참고로 RSA의 Ad id에 대한 노출/클릭/광고비/전환 등의 지표는 기존 stat report를 통해 조회할 수 있습니다.

감사합니다.
