### ISSUE TITLE
/stats ids 개수 제한 문의 

### ISSUE THREAD

**Issue by royholicbang** [naver/searchad-apidoc#939]
안녕하세요 

stats GET (by ids) API 에서 
ids 파라미터에 개수 제한이 있는지 확인 할 수 있을까요?

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

stats GET 요청에 사용할수 있는 파라미터의 개수는 따로 지정되지 않았습니다.
하지만 파라미터의 개수가 많을 경우 응답시간이 길어질 수 있기 때문에 적절한 수량으로 조절하여 호출 하도록 가이드 드립니다.

감사합니다.
