### ISSUE TITLE
Master Report API AdAssetLink 파일문의

### ISSUE THREAD

**Issue by SM10855** [naver/searchad-apidoc#940]
안녕하세요.

MasterReport API 반응형 소재 마스터 데이터 문의입니다.

Ad Asset Link Master (AdAssetLink)

다른 마스터 리포트는 마지막에 탭이 하나만 존재하는데, 
AdAssetLink 는 마지막에 탭이 두 개나 존재합니다. 
마지막에 delTm이 있다고 가정해 보면 다른 마스터 파일과 다르게 탭이 하나 더 있어서 
데이터가 있는 것으로 인지할 수 있을 것 같은데
변경될 여지가 있을지 아니면 이대로 하면 될지 문의드립니다.

'Pin' 필드에는 광고의 위치를 나타내는 1, 2 이렇게 표시 한다고 설명은 되어있는데, 파일을 받아보니 null 문자로 받습니다. null은 설정을 하지 않은 것으로 보면 될까요

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요 대용량다운로드보고서 담당자입니다.

우선 Ad Asset Link Master의 컬럼 수는 8개이며,
말씀주신 마지막에 하나 더 존재하는 컬럼은 데이터가 존재하는 컬럼이 아닌 버그 사항으로, 빠르게 수정하도록 하겠습니다.

또한, 'Pin' 필드에서 null 문자로 반환되는 부분은 pin 설정을 하지 않을 경우 null 문자로 반환되는 것이 정상입니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요 대용량다운로드보고서 담당자입니다.

말씀주신 Ad Asset Link Master에서 빈 컬럼이 출력되는 문제는 현재 수정 적용 완료되었습니다.
확인 부탁드리겠습니다.

감사합니다.

**Comment by SM10855** [comment]
모두 확인했습니다. 감사합니다 :)
