### ISSUE TITLE
키워드 검색 상품 리스트 및 상품 6개월 매출 확인방법 문의

### ISSUE THREAD

**Issue by boardpen** [naver/searchad-apidoc#941]
네이버 키워드로 검색시
 - 상품의 리스트를 제공하나요?
 - 제공된 상품의 6개월 매출 데이터를 확인 할 수 있을까요?

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

문의하신 `상품의 리스트`가 쇼핑검색광고의 상품을 말씀 하시는 걸까요?
쇼핌 검색광고의 상품 목록 조회는 API로 제공하고 있지 않습니다.

감사합니다.
