### ISSUE TITLE
Stat Report의 Timezone 문의

### ISSUE THREAD

**Issue by githubcnsbs** [naver/searchad-apidoc#942]
안녕하세요.

 GET /stat-reports/reportJobId 로 받는 AD_DETAIL / AD_CONVERSION_DETAIL 등 실적 tsv file의 date 및 hour의 기준 timezone이 Asia/Seoul 기준인지 UTC 기준인지 문의 드립니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요 대용량다운로드보고서 담당자입니다.

보고서에서 제공되는 성과/전환 정보는 모두 Korean Standard Time (KST) 기준 시점이므로, Asia/Seoul 기준이 맞습니다.
상세 보고서에서 제공되는 Hour은 특정 시간대(1시간 단위) 별로 발생한 성과/전환 정보에 대해서 제공하는 segment이므로 시점의 기준은 존재하지 않습니다. 이때, 시간대 별 정보는 KST 기준이며, 예를 들어 표시된 값이 01이면 01:00~02:00 사이의 지표, 12이면 12:00~13:00 사이의 지표라고 보시면 될 것 같습니다.

감사합니다.

**Comment by githubcnsbs** [comment]
답변 감사드립니다.
