### ISSUE TITLE
검색광고 광고그룹(/ncc/adgroups) 타겟팅 정보가 안가져와집니다.

### ISSUE THREAD

**Issue by rjpark-epe** [naver/searchad-apidoc#943]
API로 광고그룹 조회 시 TIME_WEEKLY_TARGET 에 해당 하는 광고주 센터에서 설정하였는데도 불구하고 가져와지지 않는 케이스가 발생하여 문의 드립니다.

TIME_WEEKLY_TARGET 타겟팅의 경우 별도로 가져와야하는것인지 아니면 광고그룹 API만으로 가져와지는 것인지요?

추가적으로 Target(/targets)을 직접적으로 가져와보려고도 했는데 doc 쪽에 별도로 type에 대한 언급은 없는데
요청할때 type은 어떤 것들이 있을까요?

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

[Release note](https://naver.github.io/searchad-apidoc/#/release-notes)의 "[2023-08-23] Release Note" 내용을 참고하시기 바랍니다.

또한 https://naver.github.io/searchad-apidoc/#/operations/GET/~2Fncc~2Fcriterion~2F%7BadgroupId%7D%7B%3FCriterionDictionaryType%7D 이 API도 같이 참고 부탁드립니다.

감사합니다.
