### ISSUE TITLE
GET /master-reports, GET /stat-reports API 문의

### ISSUE THREAD

**Issue by HwangWonGyu** [naver/searchad-apidoc#945]
안녕하세요. 광고 정보와 보고서를 조회하는 API 관련하여 질문이 있습니다.
그전에 아직 보고서 API와 검색광고 관리자 페이지가 익숙치 않은 상태라 질문이 모호할 수 있는점 양해바랍니다.

1) API 문서에 나온것처럼 list 조회 API에는 파라미터가 없나요?
https://naver.github.io/searchad-apidoc/#/operations/GET/~2Fstat-reports
https://naver.github.io/searchad-apidoc/#/operations/GET/~2Fmaster-reports

2) '네이버 검색 광고 https://searchad.naver.com/ 에 접속 후 로그인 -> 우측 상단 광고플랫폼 -> 대용량 다운로드 보고서'에 진입 후
생성요청 버튼을 통해 보고서를 생성하거나
POST /master-reports, POST /stat-reports API를 통해 보고서를 생성해야 조회도 할 수 있는건가요?

쇼핑검색 검색어상세보고서(ReportType : SHOPPINGKEYWORD_DETAIL),
쇼핑검색 검색어전환상세보고서(ReportType : SHOPPINGKEYWORD_CONVERSION_DETAIL)
위 2가지에 대한 데이터 분석이 필요한 상황인데 아직 보고서는 없는 상태입니다.

확인 부탁드립니다. 감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요 네이버 검색광고 API 담당자입니다.

1. 네, 보내주신 StatReport와 MasterReport의 list 조회 API는 등록된 모든 Job Id에 대한 리스트를 출력하는 API이므로 별도의 파라미터는 제공되지 않습니다.

2. 네, 말씀주신 부분처럼 대용량다운로드보고서를 생성할 수 있는 방법은 (1) 광고 플랫폼에서 생성 요청하시거나, (2) POST /master-reports, POST /stat-reports API를 통해 생성하시는 방법 2가지가 있습니다. 생성된 보고서에 대한 조회 방법은 생성 요청한 광고 플랫폼에서 보고서가 생성 완료되면 다운로드 하는 방법과, reportJobId에 대한 GET /master-reports/{id}, GET /stat-reports/{reportJobId} API를 사용하는 방법 2가지가 존재합니다.

감사합니다.

**Comment by HwangWonGyu** [comment]
@naver-searchad 
자세한 답변 감사합니다
