### ISSUE TITLE
광고 소재 API 항목 호출 여부 가능 문의 

### ISSUE THREAD

**Issue by mz-heesun** [naver/searchad-apidoc#946]
해당 항목을 찾아보려했으나 해당 부분을 찾기 어려워 이렇게 문의드립니다.

저는 
광고소재 > 소재 미리보기 > 항목 상세보기
의 하위 항목들을 api를 통해서 받아보고싶습니다. 

해당 링크의 utm 링크를 가져오기 위해서 인데요

<img width="878" alt="image" src="https://github.com/naver/searchad-apidoc/assets/34467514/89a03685-2c34-4322-adaa-87369719015d">
<img width="837" alt="image" src="https://github.com/naver/searchad-apidoc/assets/34467514/d5c0eab8-5846-40e3-b16f-7a067a8ac720">
<img width="843" alt="image" src="https://github.com/naver/searchad-apidoc/assets/34467514/7aa5c48c-8799-41bc-8f26-d3238cbdb208">

위의 해당 부분들을 api를 통해서 받아보려고했으나
어디에 있는지 확인할 수 없었습니다.

확인 부탁드립니다 !

**Comment by mz-heesun** [comment]
api로 받아오는게 안된다면 혹시 개발 예정에 들어가있는지도 같이 확인 가능하실까요..?

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.
네이버 검색광고 API로 브랜드검색 소재의 항목 상세보기는 제공하고 있지 않습니다.
또한 아직 API로의 제공 여부도 결정이 된 부분이 없습니다.

감사합니다.
