### ISSUE TITLE
노출 현황 진단 API 지원 여부

### ISSUE THREAD

**Issue by hon9hb-dbase** [naver/searchad-apidoc#947]
안녕하세요.

파워링크 키워드 대시보드 내 상태가 노출가능일 때,
마우스오버 시, 노출 현황 진단이라는 타이틀과 함께 PC/모바일의 노출여부를 제공해주시는 것으로 확인됩니다.
<img width="339" alt="image" src="https://github.com/naver/searchad-apidoc/assets/88298771/8bdd48b7-c59f-45fb-81ff-0a210f5eb4dd">

요일/시간대 타겟팅으로 인해 노출되고 있지 않거나
PC/모바일 지정으로 노출되고 있지 않거나 한 상태를 확인가능한데
이와 관련한 API(impression-status)는 별도로 외부제공되지 않고 있는 것일까요?
동일한 정보를 위해서는 해당 키워드의 광고그룹 조회하여 노출 매체를, 타겟팅을 조회하여 요일/시간대를 조회하여
현재 노출여부를 추측하는 방법밖에는 없을지 문의 드립니다.

혹시 직관적으로 실제 노출상태를 알 수 있는 API가 있거나 지원 예정이신지 궁금합니다.

감사합니다.

@naver-searchad

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

네이버 검색광고 API를 이용하여 현재 노출중인 광고상품을 조회할 수는 없습니다.
또한 광고의 노출 상태를 확인하기 위해서는 [FAQ](https://github.com/naver/searchad-apidoc/wiki/FAQ#q-각-항목의-상태와-상태이유-계산-방식은-어떻게-되나요) 내용을 참고하시기 바랍니다.

감사합니다.
