### ISSUE TITLE
쇼핑검색 광고 상품 구분 api

### ISSUE THREAD

**Issue by sujinlee2094** [naver/searchad-apidoc#948]
안녕하세요, 네이버 개발 api를 활용해서 특정 검색어 기준으로 쇼핑 검색 페이지 결과 중 광고 상품만 확인하여 카테고리를 분석하고자 하는데,
네이버 개발 api 문서에서는 따로 구분 값이 안나와 있어 확인할 수 있는 방법이 따로 있을까요?
네이버 파라미터 값을 기준으로 구분하자니, 자동추적 기능을 사용하지 않는 광고들도 여럿 있어서요

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

네이버 검색광고 API에서는 현재 노출중인 광고를 조회할 수 있는 API를 제공하고 있지 않습니다.

감사합니다.
