### ISSUE TITLE
그룹 내 '소재 노출 방식' api 제공여부 문의

### ISSUE THREAD

**Issue by sm10903** [naver/searchad-apidoc#949]
안녕하세요.

광고그룹 정보 등록/수정 시 [소재 노출 방식] 에서 '성과기반노출', '동일비중노출' 선택이 가능한데요,

![캡처](https://github.com/naver/searchad-apidoc/assets/58065597/b5fb4bde-23b2-45c4-942b-b83383d120be)

API 에서 이 데이터를 제공하는지 확인 요청드립니다.

감사합니다.

@naver-searchad

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

네이버 검색광고 API를 이용하여 광고 그룹 정보를 조회하면 `adRollingType` 정보가 포함이 됩니다.
http://naver.github.io/searchad-apidoc/#/tags/Adgroup

감사합니다.
