### ISSUE TITLE
Stat 문의 드립니다.

### ISSUE THREAD

**Issue by sourcreamy** [naver/searchad-apidoc#95]
query parameters 의 fields에 drtCrto 를 추가하면 
{"code":20001,"message":"선택하신 조건에 지표가 확인되지 않습니다. 보고서 항목이나 기간을 조정하세요."}  라고 나옵니다.  조회가 안되는 건가요?

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다.

http://naver.github.io/searchad-apidoc/#/operations/GET/~2Fstats%7B%3Fid,fields,timeRange,datePreset,timeIncrement,breakdown%7D

위의 문서를 참고 하시어 필요하신 field를 선택하여 주시기 바랍니다.

사용 가능하신 fields 값은 아래와 같습니다.

impCnt
clkCnt
ctr
cpc
avgRnk
ccnt
recentAvgRnk
recentAvgCpc

감사합니다.

**Comment by parkyounghwan** [comment]
'DailyStatMap' 에 속성으로 사용할 수 있는 fields 들이 나열되어 있습니다.
추가적으로, 현재 시점(2025. 02. 20 일자)으로 테스트 해 본 결과 아래의 필드들이 추가적으로 사용 가능합니다.

"pcNxAvgRnk" 
"mblNxAvgRnk"
"convAmt"
"ror"
"cpConv"

* 'DailyStatMap' : https://naver.github.io/searchad-apidoc/#/definitions/DailyStatMap
