### ISSUE TITLE
StatReport API로 TSV 데이터를 받아올 때 컬럼 값에 double quote가 있는 경우에 대한 처리 문의

### ISSUE THREAD

**Issue by donghwan-ahn** [naver/searchad-apidoc#950]
`stat-reports` API로 SHOPPINGKEYWORD_DETAIL 타입의 보고서 데이터를 가져올 때 `Search keyword` 컬럼의 경우 값에 double quote가 들어간 경우가 있습니다.

예를 들면 `"듀이듀이“`가 있는데요.
대시보드에서 다운로드 하는 CSV 데이터는 `""듀이듀이“"`와 같이 되어 있어 문제가 없는데, API로 다운로드 하는 TSV 데이터는 `"듀이듀이“`로 되어 있어 파싱할 때 오류가 발생합니다. (`"듀이듀이“`에서 처음과 끝의 double quote는 다른 문자임)

대시보드 데이터
```csv
"2024.06.02.","0.29cm4_쇼핑검색","일반운영_226",""듀이듀이“","1","0","0","0","0","0","0","0","0","0","0","0","0","0"
```

API 데이터
```csv
20240602	1649507	cmp-a001-02-000000002001327	grp-a001-02-000000017490102	"듀이듀이“	nad-a001-02-000000302073007	bsn-a001-00-000000002171322	11	17	33421	M	1	0	0	4	0
```

API로 내려 주는 TSV 데이터에서 컬럼 값에 double quote가 들어간 경우, 이스케이프 처리가 필요할 것 같습니다.

**Comment by naver-searchad** [comment]
안녕하세요 대용량 다운로드 보고서 담당자입니다.

대용량 보고서의 파일 유형은 TSV로, 즉 TAB을 delimiter로 사용하고 있습니다. 또한 별도의 텍스트 한정자는 없습니다.
말씀주신 오류의 원인은 대용량 보고서 스펙에 맞춰 파서가 구성되지 않아 오류가 발생하는 것으로 보이는데요, TSV 유형에 맞춰 파싱을 하신다면 해당 문자들로 인한 오류는 해결될 것으로 보입니다.

감사합니다.

**Comment by donghwan-ahn** [comment]
답변 감사합니다.

말씀하신 것처럼 사용하는 쪽에서 파싱 옵션을 변경해서 해결할 수 있는 문제이긴 합니다만, 아쉬운 점들이 있습니다.

- TSV 또는 CSV에서 `"`을 quote character로 사용하는 것이 일반적이고, 값에 quote character가 포함되어 있는 경우 이스케이프 처리를 하는 것이 사실상의 표준(de facto)으로 알고 있습니다. 이런 관례를 따르지 않는 특별한 이유가 있으신가요?
- TSV에서도 quote 문자가 필요한 경우가 분명히 있습니다. 예를 들어, 광고그룹 이름에 실수로 탭 문자를 넣는 경우가 실제로 있었고, 이런 경우 quote 문자로 감싸 주지 않으면 파싱을 잘못 하게 될 수 밖에 없습니다. 이런 점은 어떻게 생각하시나요?
- 마지막으로 대시보드에서 CSV로 다운로드 할 때는 quote 문자를 사용하고는 있는데, 잘못 적용되어 있습니다.
예를 들어 값이 `"듀이듀이“`인 경우, `""듀이듀이“"`와 같이 데이터를 내려주고 있는데, 제대로 하려면 `"""듀이듀이“"`와 같이 되어야 합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 대용량 다운로드 보고서 담당자입니다.

답변 드립니다. 
1. 여러가지 환경과 이유가 있으나 저희 내부 구조가 공개하지 않으면 설명이 어려운 내용이라 상세한 사정을 설명드리기는 어렵습니다. 그래서 납득이 어려우시겠지만 그럼에도 이유를 말씀드린 다면 가장 큰 이유는 "보고서 제공 속도"입니다. 
여기서 보고서 제공 속도라 함은 전일 데이터를 다음날 새벽 몇시쯤에 제공할수 있는가? 입니다. 
2. 해당 서비스가 구성된 시점에는 TAB문자는 입력 금지 문자 였습니다. 그 이후 광고관리시스템 구조 여러차례 개편이 되면서 TAB이 특정 시점에 허용 되었고 이로 인해 택스트 한정자 추가를 고려했으나 역시 "속도" 문제로 포기한 일이 있었습니다. 현재도 담당부서에 TAB문자 금지를 계속 요청하고 있는 상황이구요. 그러나 향후 대용량 보고서 서비스가 재구성 혹은 개편 된다면 택스트 한정자가 들어가는 편이 제공자 사용자 모두에게 이득이 크다고 보는 입장입니다. 물론 현재의 속도로 보고서를 계속 제공할수 있다는 전제입니다.
3. 대시 보드 부분은 담당 부서에 말씀 주신 내용에 대해 전달 드리도록 하겠습니다. 

제안 주신 부분들은 저희로서도 아쉬운 부분이기는 하나 현재로서는 해결이 어려운 상황이고, 
앞으로도 해결 할수 있을지 장담 드리기 어려운 상황입니다. 이점 양해 부탁드립니다. 

감사합니다. 
감사합니다.

**Comment by donghwan-ahn** [comment]
자세한 답변 감사 드립니다.

**Comment by naver-searchad** [comment]
@donghwan-ahn 님 

대용량 다운로드 보고서 담당자입니다. 

게런티는 드리지 못하였지만 저희도 double quote는 해결할 방안을 계속 모색 중이긴 합니다. 이 말씀이 누락되어 추가 답변 드립니다. 

감사합니다.
