### ISSUE TITLE
소재 제목, 설명 아이디어 API 사용 문의

### ISSUE THREAD

**Issue by SM11187** [naver/searchad-apidoc#954]
안녕하세요

네이버 검색광고 사이트 내에서 소재 등록 시, 팝업 우측에 클로바 AI를 활용한 소재 제목, 설명 추천 기능이 뜨고 있는 걸 발견했는데요,
확인해보니

https://gw.searchad.naver.com/api/ncc/ads/suggest로 받아오고 있더라구요
혹시 이 api 사용이 가능할까요?

![image](https://github.com/naver/searchad-apidoc/assets/94828850/db693e43-9c1d-42df-9198-8f2f585b8447)

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

클로바 AI를 이용한 문안 추천기능은 검색광고 API로 제공하고 있지 않습니다.

감사합니다.
