### ISSUE TITLE
파워컨텐츠 API 문의

### ISSUE THREAD

**Issue by xptmxm1231** [naver/searchad-apidoc#955]
Adgroup -> create
adgroupAttrJson 파라미터 에 파워컨텐츠는 INFORMATION , PRODUCT 를 넣게 되어 있는데
광고주센터 쪽에서는 이 부분 선택하는 부분이 없는것 같은데
이 두가지의 차이를 알 수 있을까요??
만약에 기본적으로 어떤걸 넣어야하는건지 
어떤 설정에 따라 달라지는건지를 잘 모르겠어서 문의 남깁니다.
그룹생성 API를 만들어야 하는데 이부분에서 막힙니다

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

이전 파워컨텐츠 광고에 상품형, 정보형 구분이 있어 INFORMATION, PRODUCT 구분이 필요해서 사용하던 값입니다.
상품형이 없어지면서, PRODUCT는 더이상 사용하지 않습니다. `INFORMATION`값으로 넣어 주시면 됩니다.

감사합니다.
