### ISSUE TITLE
구글 앱스 스크립트를 통한 검색광고 API 연결 중 Invalid Signature(403) 문제 발생

### ISSUE THREAD

**Issue by kangjunick** [naver/searchad-apidoc#956]
안녕하세요, 구글 앱스 스크립트를 통해 네이버 검색광고 성과 API를 연결해서 구글 스프레드 시트로 데이터가 입력되도록 하려고 합니다.
stats를 이용하려고 하고요.
이 과정에서 아래와 같은 오류가 발생하는데, 이 오류의 원인과 해결방법을 알고 싶습니다.

Response Code: 403
{"signature":"ydRwOQd0DuCaCl6ZTxlWotV0EDz0TzdV8hFww1KU844=","status":403,"type":"urn:naver:api:problem:invalid-signature","title":"Invalid Signature","detail":"Signature 'ydRwOQd0DuCaCl6ZTxlWotV0EDz0TzdV8hFww1KU844=' is invalid."}

아래는 코드 원문이며, apikey, secretcode, customerid 값은 임의로 변경 진행하였습니다.

`function fetchNaverAdStats() {
  // CryptoJS 라이브러리 로드
  var cdnjs = "https://cdnjs.cloudflare.com/ajax/libs/crypto-js/4.1.1/crypto-js.min.js";
  eval(UrlFetchApp.fetch(cdnjs).getContentText());

  var apiKey = '010000000046ae2d81a22c5dd3d2c49f9d6f54f6dc10e55449e783f621befc5f9c12345678';
  var apiSecret = 'ABCDEFGHri2Boixd09LEn51vVPbclziZ6TIHA/UWrqLY1nBKXw==';
  var customerId = '1234568';
  var method = 'GET';
  var requestUri = '/stats';
  var queryParams = '?id=cmp-a001-01-000000007901849&fields=impCnt,clkCnt&timeRange=20240401-20240431&datePreset=today&timeIncrement=allDays';
  var totaluri = requestUri + queryParams;

  // 현재 시간을 밀리초 단위의 UNIX 타임스탬프로 가져오기
  var timestamp = String(Date.now()); // UNIX 타임스탬프 (밀리초 단위)

  Logger.log('Timestamp: ' + timestamp);

  // 서명 생성 (쿼리 파라미터 제외)
  var signature = generateSignature(apiSecret, timestamp, method, requestUri);
  Logger.log('Generated Signature: ' + signature);

  var apiUrl = 'https://api.searchad.naver.com' + totaluri;
  Logger.log('API URL: ' + apiUrl);

  // 요청 옵션 설정
  var options = {
    'method': 'get',
    'headers': {
      'X-Timestamp': timestamp,
      'X-API-KEY': apiKey,
      'X-Customer': customerId,
      'X-Signature': signature,
      'Content-Type': 'application/json; charset=UTF-8'
    },
    'muteHttpExceptions': true
  };
  Logger.log('Request Options: ' + JSON.stringify(options));

  // API 호출
  try {
    var response = UrlFetchApp.fetch(apiUrl, options);
    Logger.log('Response Code: ' + response.getResponseCode());
    Logger.log('Response Content: ' + response.getContentText());
  } catch (e) {
    Logger.log('Error: ' + e.toString());
  }
}

function generateSignature(apiSecret, timestamp, method, requestUri) {
  var message = timestamp + '.' + method + '.' + 'https://api.searchad.naver.com' + requestUri;
  Logger.log('Message: ' + message);

  // Base64 디코딩
  var secretKey = CryptoJS.enc.Base64.parse(apiSecret);
  var hash = CryptoJS.HmacSHA256(message, secretKey);
  var signature = CryptoJS.enc.Base64.stringify(hash);
  Logger.log('Generated Signature: ' + signature);

  return signature;
}
`

**Comment by naver-searchad** [comment]
@kangjunick 안녕하세요. 검색광고 API 담당자 입니다.

generateSignature 함수에서 'https://api.searchad.naver.com/' 은 제외하고 생성하시면 됩니다.

감사합니다.

**Comment by kangjunick** [comment]
@naver-searchad 안녕하세요 !

해당 부분을 제거하고 실행해도 여전히 같은 오류가 발생하고 있습니다 ㅠ

또 점검해봐야할 사항이 있을까요?

**Comment by naver-searchad** [comment]
@kangjunick 님 안녕하세요.

httpmethod 도 대문자로 변경을 하셔야 할것 같습니다.

감사합니다.

**Comment by kangjunick** [comment]
method도 대문자로 변경했는데 같은 오류가 발생하고 있습니다 ! ㅠ
아래는 코드 실행 시 로그 메시지 입니다.

---

Message: 1718184142317.GET./stats
Generated Signature: rvjhmXC+w8HyfrWoup8Ayw/uWL6QZssmgxOkbu3qYNk=

API URL: https://api.searchad.naver.com/stats?id=cmp-a001-01-000000007901849&fields=impCnt,clkCnt&timeRange=20240401-20240431&datePreset=today&timeIncrement=allDays

Request Options: {"method":"GET","headers":{"X-Timestamp":"1718184142317","X-API-KEY":"xxxxxx","X-Customer":"1234567","X-Signature":"rvjhmXC+w8HyfrWoup8Ayw/uWL6QZssmgxOkbu3qYNk=","Content-Type":"application/json; charset=UTF-8"},"muteHttpExceptions":true}

Response Code: 403
Response Content: {"signature":"rvjhmXC+w8HyfrWoup8Ayw/uWL6QZssmgxOkbu3qYNk=","status":403,"type":"urn:naver:api:problem:invalid-signature","title":"Invalid Signature","detail":"Signature 'rvjhmXC+w8HyfrWoup8Ayw/uWL6QZssmgxOkbu3qYNk=' is invalid."}

**Comment by naver-searchad** [comment]
@kangjunick 님 안녕하세요.

코드를 자세히 보니 secretKey 를 처리하는 부분이 문제가 될것 같습니다.

아래와 같이 수정하시면 될것 같습니다.

``` js
// Base64 디코딩
// var secretKey = CryptoJS.enc.Base64.parse(apiSecret); 해당 부분은 필요 없습니다.
var hash = CryptoJS.HmacSHA256(message, apiSecret);
var signature = CryptoJS.enc.Base64.stringify(hash);
```

감사합니다.

**Comment by kangjunick** [comment]
@naver-searchad

안녕하세요 !
공유주신 덕에 signature 관련 오류는 해결한 것 같습니다.
다만, parameter 관련 오류가 뜨는 것 같습니다..!

혹시 도움 요청할 수 있을까요?

아래는 실행 로그입니다..!
(민감한 정보는 처리하였습니다.)

Response Code: 400
Response Content: {"code":11001,"message":"잘못된 파라미터 형식입니다."}

API URL: https://api.searchad.naver.com/stats?params=%7B%22id%22%3A%5B%22cmp-a001-01-000000008072255%22%5D%2C%22fields%22%3A%5B%22impCnt%22%2C%22clkCnt%22%5D%2C%22timeRange%22%3A%7B%22since%22%3A%222024-06-11%22%2C%22until%22%3A%222024-06-12%22%7D%7D

Request Options: {"method":"GET","headers":{"X-Timestamp":"1718260222724","X-API-KEY":"xxxxxx","X-Customer":"1234567","X-Signature":"m8MPmT6ahC3VItiwVR32fdSBwJPtDmsRkQGI5KAEMr8=","Content-Type":"application/json; charset=UTF-8"},"muteHttpExceptions":true}
