### ISSUE TITLE
쇼핑 API 제공여부 문의

### ISSUE THREAD

**Issue by wykim8902** [naver/searchad-apidoc#957]
안녕하세요

광고로 등록되지 않은 상품(EP로 네이버에는 등록된 상품)의 `네이버 쇼핑 상품 ID`를 받아올수있는 API가 있나요?

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

검색광고에서는 네이버 쇼핑에서 제공하는 API를 따로 제공하고 있지 않습니다.
네이버 쇼핑관련 API문의는 네어버 고객센터에 문의하실수 있습니다.

감사합니다.
