### ISSUE TITLE
bizmoney cost 결과에서 질문

### ISSUE THREAD

**Issue by henlyshin** [naver/searchad-apidoc#96]
안녕하세요
customerid 를 남기면 안되나싶어 일단 가립니다만

[customerId] => xxxxx
            [date] => 2016-12-31T15:00:00.000Z
            [productCode] => BRND
            [device] => PC
            [refundableAmt] => 18333
            [nonRefundableAmt] => 0

  [date] => 2016-12-31T15:00:00.000Z
            [productCode] => CC_WEB
            [device] => MOBILE
            [networkType] => NAVER
            [refundableAmt] => 31911
            [nonRefundableAmt] => 0

이렇게 2개값이 나오는데
BRND 이건 브랜드검색으로 보여지는데요

관리자화면에서 보고서->2017년 01월01일 날짜로 검색시
31911 원의 값은 나오는데 위에 BRND 는 없습니다.

혹시 CC_WEB ,CPC 이런것들이 매체와 어떻게 매칭 해야하는지 설명좀 해주실 수 있을까요?
또 device 도 mobile 로 나오는데... 왜 mobile로 나오는것인지 저것도 궁금합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

브랜드 검색의 경우 비즈머니 소진 기준이 아니라 기간 인식 매출 (총 계약액 / 집행기간)로 표기 됩니다. 
BRND는 업그레이드 이전의 브랜드 검색 으로 12월 31일 (한국시간 기준)으로 모든 계약이 종료 되어 12월 31일 이후 값은 더이상 리턴되지 않으니 참고 부탁드립니다. 
새로운 브랜드 검색은 BRAND_SEARCH 항목으로 값이 리턴되고 역시 동일하게 기간인식 방식으로 일할
 계산된 값이 일별로 제공 됩니다. 
관리자화면에서 보고서--> 광고 시스템의 보고서를 의미 하시는지 우선 알려 주시면 좀 더 정확하게 답변을 드릴 수 있을듯 싶네요. 

CPC--> 2016년 7월 2일 이전 클릭초이스 상품 입니다. 
CC_WEB --> 2016년 7월 1일 이후 파워링크(이전 클릭초이스) 상품입니다. 
BRND --> 업그레이드 이전 브랜드 검색입니다. 
CCP--> 클릭초이스플러스 입니다. 
PLA --> 클릭초이스 상품광고 입니다. 
BRAND_SEARCH --> 업그레이드 이후 브랜드 검색입니다. 

getCOST에서 제공되는 데이터의 구분은 
상품별로 모바일 매체로 분류된 매체들 기준 , PC  매체로 분류된 매체 기준 유상, 무상 광고비를 제공드리게 됩니다.(device는 실제 디바이스는 아니고 STATREPORT의 MEDIAMATER를 받아 보셨을때 PC, 모바일로 분류된 매체 분류를 반영한 것입니다.)

마지막으로  유상광고비(실제 광고주가 비용을 지불한 케이스) , 무상 광고비로 분류해서 광고비를 계산하시는 것이 아니라면 GETCOST보다는 STAT이나 STATreport의 광고비 항목을 보시는 것이 좋습니다.

감사합니다.

**Comment by henlyshin** [comment]
답변 감사합니다.
혹시 무상광고비라 하심의 뜻을 조금더 자세히 알수있을까요?

제가 조회기간을 2017-01-01 로 했는데 2016-12-31 이 나오는것은 31일자의 값이 1월1일에 나오기 떄문인지요? 

그렇다면 조회기간을 정할때 +1d 를 해서 보여줌이 맞겠네요. 사용자입장에서 헷갈려할것 같아서요.
저도 12-31 이라는 날짜를 복사붙여넣기 할떄까지 못보다가 지금에서야 본지라.. 사용자도 헷갈릴것 같네요 ㅎㅎ 

또 아래 글을 보니 기간산정에 대한 기능이 추가될 예정이라 적혀있던데
저희 개발기간 고려해서 반영일이 가까우면 좀 다른걸 먼저할까 하는데
대략적인 시기라도 좀 알수없을까요?

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

유/무상에 대한 설명이 빠져서 추가 답변 드립니다. 

비즈머니는 크게 유상비즈머니와 무상비즈머니로 나뉩니다. 
광고시스템에 비즈머니 메뉴에서 보시면 유/무상 구분을 보실 수 있으실 것인데요. 
유상 비즈머니라 함은 카드, 현금 등 실제로 금원을 지불하셔서 충전하신 비즈머니를 의미합니다. 
무상 비즈머니라 함은 네이버 즉 저희가 지급한 무상 비즈쿠폰을 이용해 충전한 비즈머니를 의미합니다. 
무상 비즈 쿠폰은 직접운영 광고주에 대한 적립금이나 이벤트 프로모션등으로 지급됩니다. 
광고 집행 시 비즈머니 소진 우선순위는 무상 비즈머니가 존재하면 무상 비즈머니를 우선 소진하게 됩니다.
감사합니다.
