### ISSUE TITLE
POST /stat-reports 문의

### ISSUE THREAD

**Issue by bluesyoo** [naver/searchad-apidoc#961]
안녕하세요.
광고 보고서를 조회하는 API 관련하여 문의드립니다.

광고 보고서는 최대 1년 전 데이터까지 생성 요청 가능한 것으로 확인했습니다.
API doc 문서에 생성 요청시 일자별로 요청만 가능한 것으로 파악되는데 

1. 최근 1년치 데이터를 전송받으려면 365번 생성 요청하는 방식밖에 없는지와
2. 리포트 생성 요청은 계정별로 동시에 몇 개까지 요청 가능한지

문의드립니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

api가 현재 단일날짜로밖에 지원이되지않아 해당 방식으로 조회를 하셔야합니다.
또한 요청ID가 100개가 넘어갔을때는 가장 오래된 요청ID부터 삭제되는점 참고바랍니다.

감사합니다.
