### ISSUE TITLE
네이버 검색광고 계약정보 관련 문의

### ISSUE THREAD

**Issue by SonByungjin** [naver/searchad-apidoc#963]
브랜드 검색 계약 형식의 광고 정보는 어느 API를 활용하여 원격으로 받을 수 있나요?
광고정보와 함께 계약기간이나 계약광고비 정보를 API 요청으로 받고 싶습니다

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

브랜드 검색의 계약정보API는 제공하지 않습니다. 브랜드 검색의 경우 네이버 검색광고 광고주센터를 이용하여주시기 바랍니다.

감사합니다.
