### ISSUE TITLE
공유예산 API Call limit

### ISSUE THREAD

**Issue by kwak82721** [naver/searchad-apidoc#964]
공유예산 api 를 사용하고자 하는데, call limit 조건이 어떻게 되는지 궁금합니다.
계정별, api 별 제한이 있다면 상세히 확인 부탁드립니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

아래 FAQ 내용을 참고하시기 바랍니다.

https://github.com/naver/searchad-apidoc/wiki/FAQ#q-api-호출-회수와-속도-제한이-있나요

감사합니다.
