### ISSUE TITLE
쇼핑검색 - 쇼핑브랜드형 그룹생성 요청 데이터 문의

### ISSUE THREAD

**Issue by shdrbs** [naver/searchad-apidoc#965]
안녕하세요.
검색광고 api 사용해서 쇼핑검색 그룹생성이 가능한지 알고 싶습니다.
가능하다면 필수로 요청해야될 옵션값이 어떤 것들이 있는지도 알려주시면 좋을 거 같습니다.

$data = array(
	"name" => "그룹이름",
	"nccCampaignId" => "캠페인 아이디",
	"pcChannelId" => "",
	"mobileChannelId" => "",
	"adgroupType" => "SHOPPING_BRAND",
	"bidAmt" => 70,
	"dailyBudget" => 70,
	"useDailyBudget" => true,
	"userLock" => false
);

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

쇼핑브랜드 광고 그룹 유형 생성은 기존 광고 그룹 생성 API와 동일합니다.
https://naver.github.io/searchad-apidoc/#/operations/POST/~2Fncc~2Fadgroups

하지만 [Release note](https://naver.github.io/searchad-apidoc/#/release-notes) [2021년 3월 17일](https://github.com/naver/searchad-apidoc/blob/gh-pages/_posts/2021-03-17-release-note.md)에 포함된 "nccProductGroupId" 값이 필수로 포함이 되어야 합니다.

감사합니다.
