### ISSUE TITLE
검색광고 API Docs가 고장난것 같습니다!

### ISSUE THREAD

**Issue by junsoopooh** [naver/searchad-apidoc#966]
https://github.com/naver/searchad-apidoc/commit/d1946d7e93a4f71695b1dc9979d1600f2badd59a

배포하신 이후 시점인듯한데, http://naver.github.io/searchad-apidoc/ 에 접속해도 메뉴들이 나타나지 않습니다.

저에게만 있는 현상일까요..?

**Comment by naver-searchad** [comment]
안녕하세요 검색광고 API 담당자입니다.

현재 API Docs 오류에 대해 해결 완료했습니다. 다시 조회 부탁드립니다!

감사합니다.

**Comment by junsoopooh** [comment]
빠른 조치 감사합니다! 복받으세요
