### ISSUE TITLE
https://naver.github.io/searchad-apidoc 가이드 사이트 확인 요청

### ISSUE THREAD

**Issue by withbrotherdev** [naver/searchad-apidoc#967]
안녕하세요.

검색광고데이터 관련하여 api 작업중입니다. 

현재 가이드 사이트가 정상적으로 동작하지 않는 것 같습니다.
확인 좀 부탁드립니다.

그리고 전환 추적 서비스의 전환유형이 확대될 것으로 알고 있습니다.

1. 구매완료
2. 회원가입
3. 장바구니 담기
4. 신청 완료
5. 사용자 정의#1
6. 위시리스트 추가
7. 소식 받기/구독
8. 예약 완료
9. 컨텐츠 보기
10. 사용자 정의 #2~10
11. 결제 시작
12. 상품 상세 보기
13. 상품 목록 보기
14. 스토어찜/저장
15. 검색하기
16. 공유하기
17. 쿠폰 발급
18. 리뷰/평가 쓰기
19. 문의/상담하기
20. 전화하기
21. 사업장 위치 보기/길 찾기
22. 이벤트/프로모션 신청
23. 의사소통 채널 추가
24. 마케팅 수신 동의
25. 업체 소개 보기

stat-reports 의 Conversion Type 이 최대 1 ~ 25까지 나온다고 기대하면될까요?

**Comment by naver-searchad** [comment]
안녕하세요 검색광고 API 담당자입니다.

1. 현재 API Docs 오류에 대해 해결 완료했습니다. 다시 조회 부탁드리겠습니다.
2. conversion type은 총 18가지가 제공될 예정이며, 제공되는 데이터 유형은 string입니다. 자세한 사항은 StatReport doc(http://naver.github.io/searchad-apidoc/#/tags/StatReport)에서 conversion type 필드에 대한 설명 봐주시면 될 것 같습니다.

감사합니다.
