### ISSUE TITLE
공유예산에 최대 등록가능한 campaign/adgroup 갯수 제한

### ISSUE THREAD

**Issue by kwak82721** [naver/searchad-apidoc#968]
공유예산에 최대 등록가능한 campaign/adgroup 개수 제한이 있는지 문의드립니다.
또한 create api (https://naver.github.io/searchad-apidoc/#/operations/POST/~2Fncc~2Fshared-budgets) 를 통해 생성 시에는 adgroupList 의 개수 제한이 있는지 문의드립니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

아래 FAQ내용을 참고하세요.
https://github.com/naver/searchad-apidoc/wiki/FAQ#%EA%B3%B5%EC%9C%A0%EC%98%88%EC%82%B0%EC%9D%80-%EB%AA%87%EA%B0%9C%EA%B9%8C%EC%A7%80-%EC%83%9D%EC%84%B1%ED%95%A0-%EC%88%98-%EC%9E%88%EB%82%98%EC%9A%94

```
공유예산은 몇개까지 생성할 수 있나요?
  * 광고주별 캠페인용 공유예산은 최대 20개까지 생성가능합니다.
  * 광고주별 광고그룹용 공유예산은 최대 20개까지 생성가능합니다.
  * 캠페인용 공유예산에 포함되는 캠페인의 개수는 최대 200개까지 입니다.
  * 광고그룹용 공유예산에 포함되는 광고그룹의 개수는 최대 200개까지 입니다.
```

감사합니다.
