### ISSUE TITLE
과금을 유발한 ip 의 리스트는 볼수 없나요?

### ISSUE THREAD

**Issue by henlyshin** [naver/searchad-apidoc#97]
안녕하세요
키워드를 클릭해서 과금을 유발한 ip 에 대해서 조회가 가능한지 궁금합니다.

예를들어 기간을 설정 또는 기간을 지정하면 해당 기간에 맞는 과금된 키워드와 그 키워드에 대한 IP목록을 보고 싶은데요

로그분석을 유료로 주고 가입을 해야만 이것이 가능해서
네이버측에서 혹시 별도로 제공하는지 궁금합니다.

ip차단은 있는데 그 ip를 알수가 없으니 차단을 어떻게 해야할지 모르겠습니다.
방법좀 알려주시면 감사하겠습니다.

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 api입니다. 

클릭 아이피 정보는 제공하지 않습니다. 

광고 대상 사이트에 광고를 통해 접근하는 트래픽을 체크하시는 방법은 가장 간단한 것이 추적 url을 사용하는 방식입니다. 

추적 url 붙어 있다고 해서 반드시 광고를 통한 접근이라고 100% 확신할 수는 없지만(추적 url이 붙은 상태로 즐겨 찾기를 하거나 붙은 상태의 주소를 그래도 복사&붙여 넣기 해서 인입되는 경우도 있습니다.)
일단 보고서와 매칭해 보시면 대략 파악이 가능합니다. 

물론 로그는 광고 대상 웹서비스의 로그를 직접 보셔야 합니다. 

유효 로그분석 서비스를 사용하실지 직접 서버에서 로그를 파싱하실지 여부등은 광고주님의 선택의 문에 입니다만 반드시 유료로그분석 서비스만을 이용해야 하는 것은 아닙니다. 

감사합니다.

**Comment by henlyshin** [comment]
아 그런가요? 조금 의외네요
그럼 로그를 사용하지 않는 사용자는 API를 통해 
과금이 된것에 대한 목록을 대조해 볼 수  없는것인가요?

저희의 경우 다루는 액수가 좀 커서 억을 넘다보니 좀 정확한 값을 뽑기 위해 지금 개발을 하고 있습니다만
향후 네이버에서 지원을 해주시는것인지
아니면 어떻게 대조하는것이 가장 정확한 값을 주주들에게 보여줄 수 있는지를 좀 방향을 제시해주시면 감사하겠습니다.

단순히 유입된 로그만 가지고 들어왔다 라는것은 알수있겠지만
유입된 IP와 키워드를 가지고 이게 클릭시에 얼마에 과금이 되었고 네이버 보고서에 나와있는 금액과 대조했을때 얼마나 근접하는지 에 대한 값을 보여줘야하는데요.. 

네이버에서 제공되는 값이 과거에 비해 너무 제한적이라서 지금 좀 많이 애로사항이 있는 상황입니다.
도움좀 부탁드립니다.

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

클릭로그를 그대로 제공드릴 계획은 없습니다. 
과거에도 제공드린 일은 없었구요. 

추적 URL의 스팩은 아래와 같습니다. 
https://saedu.naver.com/help/faq/ncc/view.nhn?faqSeq=120

100% 정확하지는 않지만 대조는 가능합니다. 
단 말씀대로 정확한 광고비를 원하신다면 GETCOST나 보고서의 광고비 항목을 보시는 것이 바람직합니다. 

매 클릭마다 보고가 필요하신 것인지 혹은 저희 보고서를 신뢰하실 수 없는 것인지 
(간혹 장애가 나긴 합니다만 공지를 드리고 있습니다.)
실은 필요하신 의도가 선듯 이해가 되지 않습니다. 

마지막으로 과거에도 클릭 로그 등은 제공드린 일이 없는데 어떤 부분이 제한적이라고 말씀 주신 것인지 
문의 드립니다. 

감사합니다.

**Comment by henlyshin** [comment]
과거에는 클릭로그는 없었지만 클릭시 해당 키워드의 유입순위 와 키워드 순위별 금액이 제공이 되었었기에 (저도 당시 저희가 개발한게 아니었어서 그게 4주평균이었는지 클릭시 과금비용인지 모르겠습니다만..) 그걸로 어느정도 과금대비 비용을 대조해볼 수 있었던걸로 기억합니다.
저희 임원들은 보고서를 신뢰할 수 없는게 아니라 그냥 좀더 정확성을 기대하는것입니다.
지금은 네이버 보고서에 하루 얼마 썼다하면 그걸 그대로 믿을수밖에 없는 부분이 불만인 사람들인지라
상세데이타를 제시해서 ip별 이만큼의 사람들이 유입이 되었고 이사람들이 전환이 되었고 페이지뷰가 얼만큼 있었고 하는 등의 통계를 보고 싶어해서 개발을 진행하고 있는 상황입니다^^;
그래서 api 로 어떻게 접근해서 이분들을 설득할 자료를 만들어야할지 좀.. 감이 안잡히고 있는 상황입니다.
예를들어 지금은 제공하고 있지 않지만 곧 제공할거다 라고 한다면 그 일정에 맞춰 다른걸 하고 있다가 제공이 시작되면 그때 개발을 하거나 하는 식으로 일정을 조절해볼 수 있을텐데
그게 아니라면 불가하다고 얘기를 하던지 다른 방법을 찾아서 제시하던지 해야해서
도움을 좀 구합니다.

한 계정에서만 보면 많은 비용을 쓰는건 아니지만 전지점을 합친 금액은 나름 몇억씩 쓰는 곳인데다 이게 또 지점별로 다 금액을 나눠서 내다보니 더더욱 이런 상세데이타를 요구하는 상황입니다.

조언 좀 부탁드리겠습니다.

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API 입니다. 

말씀 주신 과거의 시점이 언제 인지 명확하지 않으나 유입순위는 2016년에 추가되어 현재 까지 변함없이 추적 (URL) 기능을 통해 제공 중이며 순위별 금액은 과거부터 평균 입찰가 금액만 제공 드리고 있었습니다. 
저 데이터만으로 어떻게 대조를 하실 수 있으셨는지는 의문입니다만 어쨌든 데이터 제공 내역은 변함이 없으니 기억이 정확하시다면 데이터가 부족해서 대조를 못하시는 상황일 가능성은 낮아 보입니다. 

두번째로 말씀 주신 유입 분석(페이지뷰, 전환 등등)은 로그분석의 범위입니다. 저희 검색광고에서는 프리미엄로그분석이라는 형태의 무료 로그분석 도구를 제공드리고 있긴 합니다만 ip단위로 보시진 못하시니 이전 답변드린 것처럼 추적url을 이용해서 로그분석을 하시 방법 밖에는 없어 보입니다. 

저희 검색광고 보고서 데이터만으로 한정해서 말씀을 드린다면 
계정, 캠페인, 광고, 그룹, 비즈채널(EX.웹사이트), 등록키워드, 소재, 확장소재,매체,매체의 pc/모바일 여부,  지역,  시간대 단위로 데이터를 드리고 있습니다.
글로벌 기준으로 보아도 상당히 세밀한 편에 속하고 광고 집행 로그를 시간대 단위 정도로만 합산한 수준으로 이 이상 세밀한 수준은 저희도 지원드리기 어렵겠습니다. 

감사합니다.
