### ISSUE TITLE
공유예산 리스트 조회 시 Campaign/adgroupId 기준 필터링 조회

### ISSUE THREAD

**Issue by kwak82721** [naver/searchad-apidoc#970]
/ncc/shared-budgetsAPI 호출 시 특정 Campaign, Adgroup 이 공유예산으로 설정되어 있는지 체크 할 수 있나요?
혹시 다른 확인가능한 API 가 있다면 알려주시면 감사하겠습니다!

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

공유예산조회 결과에, 해당 공유예산을 사용중인 캠페인, 광고그룹 정보는 포함이 되지 않습니다. 대신에 몇개의 캠페인, 광고그룹이 해당 공유예산을 사용중인지는 numberInUse 값으로 확인 가능합니다.

감사합니다.
