### ISSUE TITLE
공유예산 초과 시, statusreason이 ELIGIBLE인 이유

### ISSUE THREAD

**Issue by SM11187** [naver/searchad-apidoc#971]
안녕하세요!

공유예산을 생성해서 사용하고 있는데 예산이 초과되어 아래와 같이 중단되고 난 후

![image](https://github.com/naver/searchad-apidoc/assets/94828850/706b1235-fb35-4f19-8d9c-7632b34b8ae1)

공유예산 api를 통해 조회했는데 결과로 아래처럼 ELIGIBLE를 뱉어내고 있습니다.

![image](https://github.com/naver/searchad-apidoc/assets/94828850/a7faff62-ba44-42bb-b619-3ffcb3b8f686)

캠페인이나 그룹은 중단되면 CAMPAIGN_LIMITED_BY_BUDGET, GROUP_LIMITED_BY_BUDGET 로 바뀌는데,
공유예산은 바뀌지 않는 이유가 궁금합니다!

감사합니다!

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

공유예산을 조회할 경우의 상태/상태이유값은 기본값으로 설정이 됩니다. 공유 예산에서 상태관련 값은 budgetLock 값만 유효하다고 생각하시면 됩니다.

감사합니다.
