### ISSUE TITLE
상품 그룹 목록 api 관련하여 문의드립니다.

### ISSUE THREAD

**Issue by shdrbs** [naver/searchad-apidoc#973]
안녕하세요.
상품 그룹 목록을 조회할려고 합니다.
https://api.searchad.naver.com/ncc/product-groups
GET방식으로 요청 시 404 Not Found 뜨고 있습니다.
해결 방법 알고 싶습니다.

**Comment by naver-searchad** [comment]
@shdrbs 안녕하세요. 검색광고 API 담당자입니다.

서버 설정 문제로 호출이 되지 않고 있었고, 수정되었습니다.

불편을 드려 죄송합니다. 다시 확인부탁드리겠습니다. 

감사합니다.

**Comment by shdrbs** [comment]
네 정상적으로 호출되는 거 확인했습니다.
감사합니다.
