### ISSUE TITLE
안녕하세요. 검색광고(플레이스) 관련 문의드립니다.

### ISSUE THREAD

**Issue by dbwnsgur741** [naver/searchad-apidoc#974]
1. 오프라인에서 평양냉면 음식점을 운영하고 있는 비즈니스입니다.
2. 메타 광고를 통해 네이버 플레이스로 유입을 시키고 있으나, 이후 예약 데이터가 추적이 안되어 실제 광고가 매장 방문에 영향을 미쳤는지 추적이 불가한 상황입니다.
3. 네이버 API를 활용하여 광고로 유입된 타겟이 예약을 진행했는지 추적 할 수 있는 방법이 있을지 문의드립니다.
현재 랜딩되고 있는 네이버 플레이스 링크 함께 첨부드립니다.

교대점 : https://naver.me/FEJdwTsn
홍대점 : https://naver.me/FNG2podW

---
개발자 포럼쪽에 문의를 남겨보았지만, 아무도 답변해주지 않아 이쪽에 남깁니다 ㅠㅠ
구현이 가능한건지 확인 한번 부탁드립니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

네이버 플레이스에 대한 전환 추적은 아직 제공하고 있지 않습니다. 전환 추적이 제공될때, 추후 공지를 통해 확인하실 수 있습니다.

감사합니다.

**Comment by dbwnsgur741** [comment]
@naver-searchad 
네 확인 감사합니다!
