### ISSUE TITLE
Adgroup: list (by ids) 조회시 최대 조회 가능한 adgroup 수

### ISSUE THREAD

**Issue by kwak82721** [naver/searchad-apidoc#975]
안녕하세요,

Adgroup: list (by ids) 의 paramter 중 ids 로 검색이 가능한 최대 개수는 몇개 궁금합니다.
약 48,000 개의 adgroup을 가지고 있어서 전체 정보를 조회하려 했으나 응답이 다음과 같이 나옵니다.
혹시 paging 처리가 되는지 또한 궁금합니다.

[응답값]
```
<html><body><h1>400 Bad request</h1>
Your browser sent an invalid request.
</body></html>

```

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

Adgroup: list (by ids)로 조회할 수 있는 최대 개수는 1000개입니다.

다수의 adgroup을 조회하기 위해서는 http://naver.github.io/searchad-apidoc/#/operations/GET/~2Fncc~2Fadgroups%7B%3FnccCampaignId,baseSearchId,recordSize,selector%7D API를 사용하시기 바랍니다. (이 API는 paging 처리가 가능합니다.)

감사합니다.
