### ISSUE TITLE
/stats 호출 시, 잘못된 파라미터 형식입니다.

### ISSUE THREAD

**Issue by hwanython** [naver/searchad-apidoc#976]
안녕하세요 , /stats를 호출하고자 합니다. 

근데, example 코드 보면서 확인했는데, 어떤게 잘못되었을까요?

`async def get_naver_stat(request: Request, response: Response):

    # get the target adgroup
    uri = '/ncc/adgroups'
    method = 'GET'                           
    r = requests.get(BASE_URL + uri, headers=get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID))
    
    target_adgroups = r.json()
    target_adgroup = target_adgroups[0]

    # get the stat report for the target adgroup
    uri = '/stats'
    method = 'GET'
    stat_ids = [target_adgroup['nccCampaignId'], target_adgroup['nccAdgroupId']]

    r = requests.get(BASE_URL + uri, params={'ids': stat_ids, 
                                             'fields': '["clkCnt","impCnt","salesAmt", "ctr", "cpc", "avgRnk", "ccnt"]', 
                                             'timeRange': '{"since":"2024-07-01","until":"2024-07-25"}'}, 
                     headers=get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID))

    print("response status_code = {}".format(r.status_code))
    print("response body = {}".format(r.json()))
    return r.json()
`

아시는 분 빠르게 답변해주시면 정말 감사하겠습니다! ㅠㅠ

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

다른 종류의 id가 ids 에 포함될 경우 잘못된 파라미터 형식이 리턴됩니다.
(첨부해 주신 예제에서는 nccCampaignId 와 nccAdgroupId 두 종류를 모두 ids에 포함시킨 것 같습니다.)

nccCampaignId 의 목록이나 nccAdgroupId의 목록 중 한 종류만 ids 에 포함시켜 주시면 될 것 같습니다.

감사합니다.
