### ISSUE TITLE
/stat-reports 같은 일자기준으로 다운로드한 보고서 원본 tsv 파일을 몇일 후 다시 다운로드 하면 tsv 내용이 다른 현상 문의 

### ISSUE THREAD

**Issue by chanwj82** [naver/searchad-apidoc#977]
/stat-reports API 로 20240711 일자 전환보고서  (AD_CONVERSION) tsv 파일을 2024-07-12 일 06시에 정상 다운로드 하여 총 267 raw 를 저장하였고, 이후 보고서 내역이 누락이 있다는 담당자 문의로 금일 2024-07-17일 16시에 /stat-reports API 로 20240711 일자 전환보고서  (AD_CONVERSION) tsv 파일을 다시 다운로드 하였더니 총 273 raw 가 확인되었습니다. 

**[조건]**
보고서 기준 일자 : 20240711
보고서 유형 : AD_CONVERSION
보고서 API 다운로드 결과 비교
  1) 2024-07-12 06:00 : 총 267 raw 확인 
  2) 2024-07-17 16:00 : 총 273 raw 확인 

20240711 일자에 장애가 있었던 것인지 /stat-reports 동일한 일자의 전환 보고서가 왜 차이가 있는지 문의드립니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

11일 전환매출액 처리과정에서 일부 오류가 있어 수정 배포되었고 현재는 정상화 되었습니다.

따라서 이전에 받아보신 값은 오류가 있는 값으로 보여지고, 17일에 신규로 받으신 값이 정상화된 값입니다.

감사합니다

**Comment by chanwj82** [comment]
별도 공지도 없었던거 같은데요,, 오류가 있었다면 API 를 사용하는 입장에서는 어떤식으로 해당 문제를 사전에 감지 및 조치를 할수 있는지도
문의드립니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

데이터 검수가 지연되어 공지도 함께 지연되었으며 금일 부 공지 완료되었습니다.

전환수 집계 오류로 인해 업무에 불편을 드려 대단히 죄송합니다.
앞으로 업무에 차질이 없으시도록 이슈 발생 시 공지를 통해 빠르게 공유드릴 수 있도록 하겠습니다.

감사합니다

**Comment by chanwj82** [comment]
http://naver.github.io/searchad-apidoc/#/notice

아직 공지문이 안올라온거 같은데요.. 공지는 어디서 확인하면 되나요??

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

http://naver.github.io/searchad-apidoc/#/notice 가장 위 공지입니다
![image](https://github.com/user-attachments/assets/34a04eb1-c2bf-4581-844f-47c0f137addf)
