### ISSUE TITLE
다차원 보고서의 cost 값 문의

### ISSUE THREAD

**Issue by stellanoh** [naver/searchad-apidoc#979]
안녕하세요,
stat-reports 를 통해서 데이터를 조회하고 있는데, cost 필드의 경우 vat 10%를 붙여야 다차원 보고서의 값과 일치하는 것 같더라구요

다차원 보고서의 값의 cost의 경우, 비즈머니 유/무상 값의 따라 분리해서 vat를 붙이는 건가요? 아니면 일괄적으로 10%를 붙여서 표현해주고 있는 건가요?

감사합니다!

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API 입니다. 

담당자 변경 과정에서 답변이 누락되어 지금에야 답변을 드리게 되었습니다. 
대단히 죄송합니다. 

> 다차원 보고서의 값의 cost의 경우, 비즈머니 유/무상 값의 따라 분리해서 vat를 붙이는 건가요? 아니면 일괄적으로 10%를 붙여서 표현해주고 있는 건가요?

모든 보고서의 값은 유/무상이 분리 되어 있지 않습니다. 
다차원 보고서 등 광고관리 시스템(UI)를통해 제공되는 값은 일괄적으로 VAT(10%)를 붙여서 표현합니다. 

대용량 보고서와  광고관리 시스템의 비용 표현 방식의 차이이 있는 이유는 
API는 이후 가공을 기준으로 하고 있어 사용자의 자유도를 최대화 하기 위해 가급적이면 가공을 하지 않는 것을 원칙으로 하고 
있으나 사용자가 화면을 통해 직접 값을 확인 하시는 광고관리사이트(UI)에서는 최대한 사용자가 혼란을 느끼지 않도록 최대한 가공을 하고 있기 떄문입니다. 

감사합니다.
