### ISSUE TITLE
등록한 키워드의 pc/모바일 별 클릭수

### ISSUE THREAD

**Issue by sourcreamy** [naver/searchad-apidoc#98]
안녕하세요.
광고주가 등록한 키워드의 pc/모바일별 클릭비용,클릭수, 전환수를 날짜별로 가져 올 수 있는
기능이 있을까요?

**Comment by naver-searchad** [comment]
안녕하십니까 검색광고 API입니다. 

STAT(http://naver.github.io/searchad-apidoc/#/tags/Stat)
STATREPORT (http://naver.github.io/searchad-apidoc/#/tags/StatReport)

기능을 이용해 주시면 되겠습니다.

단, 대상 계정에 대한 권한을 가지고 계셔야 합니다. 
권한 관련 설명은 아래 도움말을 참고해 주시기 바랍니다.
https://saedu.naver.com/help/faq/ncc/view.nhn?faqSeq=33

감사합니다,
