### ISSUE TITLE
convTp에 따른 stats 리포트

### ISSUE THREAD

**Issue by sogangCSmaster** [naver/searchad-apidoc#980]
안녕하세요
최근 구매, 회원가입, 장바구니가 모두 ccnt에 포함되고 있는 것 같은데요.

전환 type에 따라 리포트를 볼 수 있는 방법이 있는지 확인 부탁드립니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

전환 상세를 보고싶으신 경우 StatReport 를 통해서 확인할 수 있습니다.

https://naver.github.io/searchad-apidoc/#/operations/POST/~2Fstat-reports

에서

reportTp = AD_CONVERSION 또는 reportTp = AD_CONVERSION_DETAIL

API를 사용해서 전환상세 지표를 확인할 수 있습니다.

감사합니다.
