### ISSUE TITLE
키워드 생성시 403에러 문의드립니다

### ISSUE THREAD

**Issue by jaemitsu** [naver/searchad-apidoc#981]
트랜잭션ID 6f4148136d6265f5 입니다

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

로그를 확인해보니, 자체 reverse proxy를 이용하여 API를 호출 하는듯 합니다. cors 체크에서 오류로 처리가 된 것으로 보입니다.

[api.searchad.naver.com](https://api.searchad.naver.com/) 으로 직접 호출해서 키워드를 생성하시면 됩니다.
또한 요청하신 데이터에 필수 항목인 links property가 없으니 참고하시기 바랍니다.

감사합니다.

**Comment by jaemitsu** [comment]
브라우저에서의 post요청도 가능한가요?
