### ISSUE TITLE
/ncc/keywords/ 키워드 입찰가 변경이 되지 않는 현상 문의

### ISSUE THREAD

**Issue by chanwj82** [naver/searchad-apidoc#982]
네이버 입찰가 변경 API 요청 및 응답은 오류없이 진행되나, API 결과는 변경전 입찰가로 여전히 확인됩니다. 

응답 결과 status=ELIGIBLE, statusReason=ELIGIBLE 로도 정상 확인되는데, 입찰가는 변경되지 않는 원인 문의드립니다.

**1) 키워드 입찰가 요청 : 110 으로 변경요청** 

PUT /ncc/keywords/nkw-a001-01-000006415290992?fields=bidAmt

nccKeywordId=nkw-a001-01-000006415290992, nccAdgroupId=grp-a001-01-000000043839957, **_bidAmt=110_**, useGroupBidAmt=true

**2) 입찰가 변경 응답 결과 : 100 변경전 입찰가로 확인됨**

nccKeywordId=nkw-a001-01-000006415290992, keyword=LG에어컨렌탈, nccAdgroupId=grp-a001-01-000000043839957, nccCampaignId=cmp-a001-01-000000008380641, userLock=false, **_bidAmt=100_**, useGroupBidAmt=true, **_status=ELIGIBLE, statusReason=ELIGIBLE_**, nccQi=Keyword.NccQi(qiGrade=4), resultStatus=null

> 참고로 다른 키워드ID 에서는 정상적으로 입찰가가 변경되는 로직으로 테스트하였으며, 단지 키워드ID 'nkw-a001-01-000006415290992' 호출시 발생하는 현상입니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

광고키워드의 입찰가는 useGroupBidAmt = false 일 경우에 변경 가능합니다.
