### ISSUE TITLE
검색 광고 상품 등록 문의

### ISSUE THREAD

**Issue by startergate** [naver/searchad-apidoc#984]
#635 상에는 referenceId 통해서 광고 등록이 가능한걸로 나오는데 문서에는 없어서 현재도 가능한게 맞는지 문의 드립니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.
`referenceId` property는 광고 소재에는 없습니다. nvmid 값을 `referenceKey` property 에 입력하셔야 합니다.

또한 검색광고 API를 이용하여 쇼핑광고 소재등록은 추천하고 있지 않습니다. 쇼핑 검색 광고에 필수 정보인 nvmid 값을 검색광고 API에서는 제공하고 있지 않기 때문입니다.  

만약 nvmid값을 알고 있다면, 아래와 같이 request body에 데이터를 넣어 주시기 바랍니다.
request body는 json array 타입이고, 또한 요청 파라미터에 isList=true 가 포함되어야 합니다.

쇼핑몰 상품형
```
[
    {
        "ad": {},
        "adAttr": {
            "useGroupBidAmt": 그룹 입찰가 사용여부(true/false),
            "bidAmt": 입찰가격
        },
        "customerId": 광고주번호,
        "nccAdgroupId": 광고그룹 번호,
        "referenceKey": nvmid값
        "type": "SHOPPING_PRODUCT_AD"
    }
]
```
제품 카탈로그형
```
[
    {
        "catalogType": "MAKER",
        "ad": {
            "catalogType": "MAKER"(고정)
        },
        "adAttr": {
            "useGroupBidAmt": 그룹 입찰가 사용여부(true/false),
            "bidAmt": 입찰가격
        },
        "customerId": 광고주번호,
        "nccAdgroupId": 광고그룹 번호,
        "referenceKey": nvmid 값
        "type": "CATALOG_AD"
    }
]
```

**Comment by startergate** [comment]
네 확인 감사합니다 :)
