### ISSUE TITLE
Invalid API-KEY 오류 문의

### ISSUE THREAD

**Issue by chanwj82** [naver/searchad-apidoc#985]
금일 오전 11시 까지는 정상적으로 API 호출/응답 확인되었는데  
11시 이후 부터 갑지기 API 호출시 403 Invalid API-KEY 오류가 지속 발생하고있어 문의드립니다.

**x-transaction-id : 26c74678e01f172b**

**1. request**
[https://api.searchad.naver.com/ncc/campaigns] <[Content-Type:"application/json", X-Timestamp:"1723005281031", X-API-KEY:"0100000000320dd14b1310caeea9e014407d99950dc348f3e1d49715ac9441ded91a32e", X-Customer:"1490239", X-Signature:"AoDsVNhV1q4YHQBSNas+bAtohd9DurlzpCJN46bdOZM="]>

**2. response** 
<403,{"apikey":"0100000000320dd14b1310caeea9e0144075d5d99950dc348f3e1d49715ac9441ded91a32e","status":403,"type":"urn:naver:api:problem:invalid-apikey","titl"Invalid API-KEY","detail":"API-KEY '0100000000320dd14b1310caeea9e0144075d5d99950dc348f3e1d49715ac9441ded91a32e' is invalid."},[date:"Wed, 07 Aug 2024 04:34:41 GMT", transfer-encoding:"chunked", x-transaction-id:"26c74678e01f172b", referrer-policy:"unsafe-url", server:"nfront"]>

**Comment by naver-searchad** [comment]
@chanwj82 님 안녕하세요. 검색광고 API 담당자 입니다.

오늘 11시 26분 경에 새로운 API_KEY 를 발급받으신걸로 이력이 확인이 됩니다.

새로 발급시, 기존의 API_KEY 는 사용이 불가능한점 참고 부탁드리겠습니다.

감사합니다.

**Comment by chanwj82** [comment]
가정 먼저 403 애러가 확인된 시점은 11:01 분 경으로 확인되었고, 담당자 분이  급하게 API KEY를 여러번 새로 발급한건 맞습니다. (11시 26분 포함)

다만, 11시 01분에 최초 403 애러가 발생한 정확한 원인 확인이 필요하여 재 문의드립니다. 

**x-transaction-id : 7904cb98d4bb2146**

**[2024-08-07 11:01:16.852] - 1. request** - [https://api.searchad.naver.com/billing/bizmoney] <[Content-Type:"application/json", X-Timestamp:"1722996076830", X-API-KEY:"01000000004a2aaccbd9122f2b155cec501f6e98ef63376f12bc245bd2f692c9453707f12b", X-Customer:"1490239", X-Signature:"UEf0JoAfN8Iqof7qfox7ud3qEI7PY/f1TmN97YENfpE="]>

**[2024-08-07 11:01:16.853] - 2. response** - <403,{"apikey":"01000000004a2aaccbd9122f2b155cec501f6e98ef63376f12bc245bd2f692c9453707f12b","status":403,"type":"urn:naver:api:problem:invalid-apikey","title":"Invalid API-KEY","detail":"API-KEY '01000000004a2aaccbd9122f2b155cec501f6e98ef63376f12bc245bd2f692c9453707f12b' is invalid."},[date:"Wed, 07 Aug 2024 02:01:16 GMT", transfer-encoding:"chunked", x-transaction-id:"7904cb98d4bb2146", referrer-policy:"unsafe-url", server:"nfront"]>

**Comment by naver-searchad** [comment]
@chanwj82  안녕하세요.

추가로 코멘트주신 API-KEY는 처음에 코멘트 주신 API_KEY 와 다른 API_KEY 들로 확인이 됩니다.

해당 키는 10시 53분에 만료된걸로 이력이 남아있으니 참고부탁드립니다.

**Comment by chanwj82** [comment]
01000000004a2aaccbd9122f2b155cec501f6e98ef63376f12bc245bd2f692c9453707f12b 키가 10시 53분에 만료가 되었다면
API KEY가 새로 발급된건가요? 

그러면, 아래와 같이 Customer "1490239"  의 API KEY 새로 발급한 이력을 알수있을까요?

누가(로그인ID or IP). /  새로발급된 일시 yyyy-MM-dd HH:mi:ss / 새로발급된 API-KEY

**Comment by naver-searchad** [comment]
@chanwj82 님 안녕하세요.

해당 정보는 여기서는 본인확인이 어려워 제공해드리기 어려울것 같습니다.

네이버 고객센터를 통해서 문의 부탁드리겠습니다.
