### ISSUE TITLE
Estimate 에 NPLA API 관련 문의

### ISSUE THREAD

**Issue by kaorimikage** [naver/searchad-apidoc#986]
쇼핑검색 API 에서 최소노출 입찰가(exposure minimum bid - NPLA)와 평균순위 입찰가(average position bid - NPLA)를 소재ID로 조회할 때 해당 소재가 실적이 없는 경우와 실적이 있는 경우에 나오는 값이 달라지는지 확인하고 싶습니다.

그리고 어떤 방식으로 최소노출 입찰가가 결정되는지 알고 싶습니다.

**Comment by kaorimikage** [comment]
@naver-searchad 확인부탁드립니다.

**Comment by naver-searchad** [comment]
@kaorimikage 님 

안녕하십니까 네이버 검색광고 API 담당자입니다. 

답변이 지연 되어 죄송합니다. 

소재ID를 이용해 조회 하실때는 소재의 품질지수를 반영한 값으로 제공드립니다. 
품질지수는 소재의 과거 집행 결과도 참고하므로 값이 달라질 수 도 있습니다. 즉
품질지수가 달라진다면 값이 달라질수 있지만 집행 상황과 내용에 따라 품질지수가 달라지지 않았을수도 있으므로 
"달라질 수 도" 있다고 표현하였습니다. 

최소노출 입찰가는 과거 28일이전으로 되돌아가 조회된 입찰가로 입찰 했을때 모든 노출 기회에서 통합검색에 노출 되었던 입찰가입니다. 즉 이를 달리 말하면 과거 28일 동안 통합검색에 노출 되었던 광고들의 입찰가 중 "가장 큰" 값입니다. 
그런데 쇼핑검색광고의 경우 이를 반드시 보장할수는 없습니다. 그 이유는 쇼핑 검색광고의 순위별 평균입찰가나 최소노출 입찰가 를 계산하는 방식에 기인하는데요. 
파워링크의 경우는 검색어(exact 매칭인 경우 등록 키워드와 동일) 별로 노출된 광고의 정보를 수집하여 처리하고 있으나 
쇼핑 검색광고는 어떤 검색어에 광고가 노출 될지 추정은 가능해도 미리 100% 알수 있지는 않습니다. 
그래서 매일 매일 등록된 모든 광고 중 노출 가능성이 높은 광고들(노출 가능성이 없는 광고의 예는 검토 통과 이전이라던가, 계정에 비즈머니 잔액이 전혀 없는 상황이 오래 지속되었다던가, 사용자가 OFF를 해 둔 광고 등의 케이스입니다.) 에 대해 해당 광고가 노출될 가능성이 높은 검색어를 추정하는 작업을 합니다. 
이렇게 추정된 검색어들의 검색량과 광고와 검색어간 연관도가 높은 순서대로 몇개의 검색어를 지정하고 
이 지정된 검색어들에 노출된 광고의 노출 정보들을 모아 계산하는 방식입니다. 
따라서 위에 지정된 검색어가 아닌 검색어에 광고가 노출 된다면 과거 28일 전에 돌아가 최소노출 입찰가로 입찰 했더라도 노출이 안되 었을수 있습니다. 또한 경매는 검색어별(정확히 말씀드리면 검색이 발생한 그순간)에 이루어지므로 위의 방식은 각각의 독립된 경매의 결과를 모아 이를 하나의 대표값으로 만드는 과정이므로 이에 따른 지표의 오차는 발생할수 있습니다. 예를 들어 
A라는 검색어는 1등이 입찰가 300원인데 B라는 검색어는 1등이 100원이었고 각 광고의 품질지수는 동일하며 노출이 각각 한번씩만 있었다고 가정할때 (물론 이렇게 노출수가 적은 경우는 아웃라이어로 제거하게 됩니다만 이해를 돕기 위해 단순화 하였습니다.) 1위의 평균입찰가는 단순 평균을 하고 있으므로 200원이 제공되게 됩니다. 

순위별 평균입찰가와 최소노출입찰가의 계산방식, 기반 지표 구성, 로직 등은 모두 공개하고 있사오니 추가로 궁금하신 점이 있다면 언제든 문의 부탁드립니다. 

다시 한번 답변이 지연된 부분에 대해 사과 말씀올립니다.

**Comment by kaorimikage** [comment]
소재가 오늘 추가되어서 실적이 없어도, 추정 로직에 따라서 최소노출 입찰가와 평균순위 입찰가를 산정하는 것으로 이해하면 될까요?

**Comment by naver-searchad** [comment]
@kaorimikage 님 
안녕하십니까 네이버 검색광고 API 담당자 입니다. 

로직상으로는 집행 실적이 전혀 없어도 데이터가 제공됩니다. 

그런데 한가지 주의 하실 점은 소재별 키워드 추정 작업이 완료 되어야 값이 정상 조회된다는 점입니다. 
오늘 등록하고 검토 통과 상태이며 노출이 가능하더라도 오늘 키워드 추정이 완료될 가능성은 거의 없습니다. 보통 하루나 이틀 정도 시간이 걸립니다. 그런데 이 추정은 NVMID (상품) 별로 이루어지므로 동일 계정내 소재로 처음 생성되는 NVMID 인 경우에만 해당 됩니다. 기존에 소재로 등록되어 estimate를 통해 정상 조회가 되었었다면 신규 소재 등록을 하셔도 바로 조회가 가능합니다. 아래 설명은 nvmid가 한번도 계정에 등록된 적이 없는 경우입니다. 
일반적으로 신규 등록의 경우 90%이상은 하루나 이틀 정도 기다리면 값을 조회 할수 있지만 여러가지 케이스로 키워드 추정을 하지 못하는 경우도 있습니다. 아래 순서는 빈도가 높은 순입니다. 
1. 여러가지 이유로 노출이 불가능한 상태일 경우 
--> 광고관리시스템 >도구>광고노출진단 기능을 이용해 대상 광고가 노출 가능한 상태인지 확인
2. 입찰가가 시세에 비해 너무 낮은 케이스 
--> 입찰가 가격대가 높게 형성되는 상품의 경우 (고가품등) 입찰가가 너무 낮으면 어차피 노출될 가능성이 없으므로 
      키워드 추정을 하지 않습니다. 물론 생각 보다 노출 가능성이 있는 입찰가 범위는 크기 때문에 아주 약간만 입찰가를 
      조정해 보시면 됩니다. 
3. 저희 추정 로봇이 일을 모두 마치지 못해서 큐가 밀리는 경우 
--> 특정 시점에 작동되는 배치 형태가 아니라. 이전 작업 셋(전체 광고 재 추정)이 종료되면 새롭게 작업을 시작하는 형태인데요. 신규 등록광고가 아주 많거나 저희 점검일이라 작업 시간이 좀 부족하거나 극히 드물지만 성능이 조금 떨어지거나 하는 경우에 24~48 시간 동안 작업을 모두 마무리 못하는 경우가 있습니다. 이 경우 expire time을 초과하면 이전 작업이 완료되지 않았더라도 새작업을 시작합니다. 운 나쁘게 작업 리스트의 제일 끝부분에 내 광고가 존재하는 경우 몇일 더 걸리게 됩니다. 

이런 여러가지 문제로 아예 추정 시간을 좀더 길게 잡으려는 고민도 있는데요. 아직은 대체로 하루, 늦어도 이틀 정도의 속도를 
유지하고 있습니다. 

감사합니다.
