### ISSUE TITLE
Adgroup, Ad, AdKeyword 목록 조회시 상태가 ELIGIBLE 인 경우만 조회가능 여부

### ISSUE THREAD

**Issue by withbrotherdev** [naver/searchad-apidoc#987]
안녕하세요.

광고목록조회: Adgroup: list (by campaign id)
https://naver.github.io/searchad-apidoc/#/operations/GET/~2Fncc~2Fadgroups%7B%3FnccCampaignId,baseSearchId,recordSize,selector%7D

예시)
https://api.searchad.naver.com/ncc/adgroups?nccCampaignId=cmp-a001-01-000000003756636&status=ELIGIBLE&,,,

검색조건을 status라든지 해당 속성을 추가해서 필터링하는 방법이 있나요?

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

광고 그룹조회시 별도의 필터링 옵션은 제공하고 있지 않습니다.
API 응답값을 이용하여 Client에서 필터링 하셔야 합니다.

감사합니다.

**Comment by withbrotherdev** [comment]
답변 감사드립니다.
