### ISSUE TITLE
GET /keywordstool - 키워드 월간 검색수 데이터 업데이트 시점

### ISSUE THREAD

**Issue by SM11295** [naver/searchad-apidoc#988]
안녕하세요

GET /keywordstool
API 호출을 통해서 키워드의 월간 검색수를 확인했는데요
새벽 3시와 오전 10시경에 호출한 특정 키워드에 대한 월간 검색수가 차이가 나는것으로 확인이 되는데요
업데이트 되는 시점을 알수 있을까요?

감사합니다.

**Comment by naver-searchad** [comment]
@SM11295 님 

안녕하십니까 기능 담당자입니다. 

문의 주신 사항에 대해 늦었지만 제가 지난주 금요일에 답변을 드린것으로 기억하는데 이 이슈에 답변이 달려 있지 않아 
문의 드립니다. 
혹 답변을 받지 못하였는지요?
