### ISSUE TITLE
Adgroup Type 문의

### ISSUE THREAD

**Issue by SM10855** [naver/searchad-apidoc#989]
안녕하세요.

http://naver.github.io/searchad-apidoc/#/tags/MasterReport

Master Report Adgroup 에서의  Adgroup Type 

- 1: NAVER PowerLink
- 2: NAVER Shopping Product Ad
- 3: NAVER PowerContents Information
- 4: NAVER PowerContents Product
- 5: NAVER Brand SearchAd
- 6: Local SMB Ad
- 7: NAVER Catalog Ad
- 8: NAVER Brand SearchAd Brand Zone
- 9: NAVER Brand Shopping SearchAd
- 10 Place ad
-11: New product search ad

http://naver.github.io/searchad-apidoc/#/operations/GET/~2Fncc~2Fadgroups~2F%7BadgroupId%7D
Adgroup 에서 type
- WEB_SITE
- SHOPING
- INFORMATION
- PRODUCT
- BRAND_SEARCH
- PLACE
- CATALOG
- SHOPPING_BRAND
- LOCAL_AD
- BRAND_NEW

이렇게 문서상에 작성되어있는데, 

위 타입이 어떻게 매칭이 되는지 궁금하며

BRAND_NEW,BRAND_SEARCH_NEW_AD에 대한 타입도 Master Report Adgroup 의 AdgroupType으로 어떤값으로 내려주는지 궁금합니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

아래 FAQ의 내용을 참고하시기 바랍니다.

https://github.com/naver/searchad-apidoc/wiki/FAQ#q-%EA%B4%91%EA%B3%A0-%EA%B4%80%EB%A6%AC%EC%9D%98-%EB%AC%B8%EC%9E%90%EC%97%B4-%EC%BD%94%EB%93%9C%EC%99%80-master-report%EC%9D%98-%EC%88%AB%EC%9E%90-%EC%BD%94%EB%93%9C%EB%8A%94-%EC%96%B4%EB%96%BB%EA%B2%8C-%EB%A7%A4%ED%95%91%EC%9D%B4-%EB%90%98%EB%82%98%EC%9A%94


감사합니다.
