### ISSUE TITLE
키워드 검색수 데이터 업데이트 시점 문의(GET /keywordstool )

### ISSUE THREAD

**Issue by SM11295** [naver/searchad-apidoc#990]
안녕하세요,

GET /keywordstool API 호출을 통해 특정 키워드의 PC/MO 월간 검색수를 확인하고 있습니다. 확인 도중 새벽 3시와 오전 10시경에 호출한 특정 키워드의 월간 검색수가 약간 차이가 나는 것을 발견했습니다. 이를 토대로 검색수 데이터가 오전에 업데이트된다고 판단하고 있습니다.

데이터 업데이트 시점을 알 수 있다면 공유 부탁드립니다. 이는 데이터를 업데이트한 후 API 호출을 하기 위함입니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 기능 담당자입니다. 

이전 질문 주신 내용을 답변을 달았던것으로 기억하는데 제가 답변만 달고 comment 버턴을 클릭하지 않았을지도 모르겠습니다. 
경위야 어떻게 되었던 답변을 보시지 못하신것 같습니다. 
저의 불찰로 답변이 지연되어 대단히 죄송합니다. 

업데이트 시점은 대략 새벽 언젠가 ~ 오전 10시 사이인데요. 
시작하는 시점은 최근 몇년간 관측치를 봤을때 대략 새벽 3시~4시 이후 정도인것 같습니다. 

저희도 명확하게 알려 드릴수가 없는 이유는 이전 작업들이 완료 되어야 작업하는 순차 배치 형태이기 때문에 이전작업량에 
따라 시작 시점이 계속 변하기 떄문입니다. 또 제공 드리는 검색수는 유효 검색수인데 유효 판정이 확정 되는 시점도 날마다 다르다는 이유도 있습니다. 

(점검이 없는) 일반적인 경우 목표 시점은 늦어도 9시~10사이에 끝낸다 정도라 업무상 크게 무리가 없으시면 10시이후에 
조회 하시는 것이 최신 데이터를 받을수 있는 가능성이 높다라고 생각 됩니다. 
그리고 작업 시간 중에는 업데이트 된 검색어와 되지 않은 검색어가 섞여 있을수 있사오니 이점 참고 부탁드립니다. 

감사합니다.

**Comment by SM11295** [comment]
넵 상세한 답변 감사드립니다.

마지막으로 업데이트의 경우 하루에 한번 이루어지는게 맞을까요? 

바쁘시겠지만 해당내용 한번더 확인 부탁드리겠습니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하십니까 기능 담당자입니다.

검색수는 검색어 별로 하루에 한번 업데이트 됩니다. 

감사합니다.
