### ISSUE TITLE
/stats의 cycleBaseTm과 datePreset=today의 관계 문의

### ISSUE THREAD

**Issue by lll4592** [naver/searchad-apidoc#991]
cycleBaseTm이 아직 전일자로 되어 있는 경우에 /stats API를 호출하면 datePreset을 today로 지정해도 전일자 리포트 데이터를 리턴합니다.

datePreset이 today인데 왜 전일자 리포트 데이터를 리턴하는지 이해가 가지 않습니다.
오늘치 데이터가 아직 집계되지 않았더라도 today로 조회를 했으면 오늘치 리포트에 해당하는 fields 값들을 0으로 리턴하거나 아예 아무것도 보내지 않는게 더 올바른게 아닌가 생각합니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

소중한 의견 감사드립니다.
말씀하신 대로 today는 현재 데이터 제공 가능한 시간을 고려해서 전달하고 있습니다.

today 에 대한 의견은 검토해 보겠습니다.

감사합니다.
