### ISSUE TITLE
[문의] 키워드 확장 종료 및 확장 검색 도입에 따른 Master 수정 사항

### ISSUE THREAD

**Issue by SM10855** [naver/searchad-apidoc#993]
안녕하세요. 플레이디입니다.

10월 2일 17시경에 아래 마스터 리포트 대상으로 필드 스펙이 변경될 예정인데,

광고그룹 마스터 (item = Adgroup)
광고그룹 예산 마스터 (item = AdgroupBudget)
공유 예산 마스터 (item = SharedBudget)

필드 변경건은 10월 2일 17시경 기준으로 이전, 이후 에 따라 생성된 변경분에 대해서도 
모두 동일하게 필드가 삭제/추가/변경으로 나오는 것으로 보면 될까요

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요 네이버 검색광고 API입니다.

10월 2일 17시 기준으로 새로 요청한 보고서에만 변경된 포맷으로 제공됩니다.
기존에 생성 후 삭제되지 않은 보고서는 이전 포맷으로 남아있지만,
요청 시간 기준으로 과거 시간대 관계없이, 새 포맷으로 변경되어 제공됩니다. 

다만 배포에 시간이 소요될 수 있어 17시 정각보단 어느정도 시각에 여유를 두시고 보고서 생성을 진행하시기 부탁드리겠습니다.

감사합니다 !
