### ISSUE TITLE
안녕하세요. 10월에 확장 검색 기능 신규 오픈 API 문의

### ISSUE THREAD

**Issue by SM10855** [naver/searchad-apidoc#995]
안녕하세요. 플레이디 입니다.

https://ads.naver.com/notice/16304?searchValue=&page=1
10월 7일부터 확장검색 기능이 디폴트로 ON 결정된다고 들었는데, 
OFF 처리할 수 있는 API 가 있는지 문의드립니다.

감사합니다.

**Comment by naver-searchad** [comment]
안녕하세요 네이버 검색광고 API입니다.

관련하여 API로 일괄 처리할 수 있는 기능 제공 예정이며
곧 릴리즈 노트(https://naver.github.io/searchad-apidoc/#/release-notes) 에 관련내용 공지될 예정입니다.

감사합니다.
즐거운 추석 명절 되세요 :)

**Comment by SM10855** [comment]
답변 감사합니다 :)
