### ISSUE TITLE
Python sample에서 uri=/stat 호출시 잘못된 파라미터 형식

### ISSUE THREAD

**Issue by tunakang** [naver/searchad-apidoc#996]
안녕하세요.
@naver-searchad Naver API 담당자님.

제공해주신 python-sample 코드를 수정 없이 사용할 때, 아래 부분에서 문제가 발생하여 문의드립니다.

```
# 1. GET Summary Report per multiple entities 

uri = '/stats'
method = 'GET'
stat_ids = [target_adgroup['nccCampaignId'], target_adgroup['nccAdgroupId']]
r = requests.get(BASE_URL + uri, params={'ids': stat_ids, 'fields': '["clkCnt","impCnt","salesAmt", "ctr", "cpc", "avgRnk", "ccnt"]', 'timeRange': '{"since":"2019-06-01","until":"2019-06-25"}'}, headers=get_header(method, uri, API_KEY, SECRET_KEY, CUSTOMER_ID))

print("response status_code = {}".format(r.status_code))
print("response body = {}".format(r.json()))
```
코드는 위와 같고 python-sample과 동일합니다.
그리고 아래와 같이 출력 됩니다.
```
response status_code = 400
response body = {'code': 11001, 'message': '잘못된 파라미터 형식입니다.'}
```

[naver-openapi-guide](https://naver.github.io/naver-openapi-guide/errorcode.html)를 살펴보니 param이 잘못 설정된 것 같은데요.
![image](https://github.com/user-attachments/assets/c9798882-23f9-4dd9-9122-4cc20d40c4bb)

살펴보니 https://github.com/naver/searchad-apidoc/issues/976 이것과 동일한 이슈 같은데, 어떻게 해결할 수 있을까요??

답변해주시면 감사하겠습니다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

다른 종류의 id가 ids 에 포함될 경우 잘못된 파라미터 형식이 리턴됩니다.
(첨부해 주신 예제에서는 nccCampaignId 와 nccAdgroupId 두 종류를 모두 ids에 포함시킨 것 같습니다.)

nccCampaignId 의 목록이나 nccAdgroupId의 목록 중 한 종류만 ids 에 포함시켜 주시면 될 것 같습니다.

감사합니다.
