### ISSUE TITLE
Python Search Ads Stats Inqury

### ISSUE THREAD

**Issue by JamesLi197412** [naver/searchad-apidoc#998]
Hello, Naver Team

I attempted to call Search Ads API. When it comes to stats part, I followed the document and send the response. But responses are always invalid parameters 잘못된 파라미터 형식입니다. I wish to find out a solution to it.

**Comment by naver-searchad** [comment]
If different "types" of IDs are included in the [ids] parameter, an invalid parameter format will be returned.
Please include only one type of ID, either a list of nccCampaignIds or a list of nccAdgroupIds, in the [ids] parameter.

```python
stat_ids = [target_adgroup['nccCampaignId'], target_adgroup['nccAdgroupId']] #Please include only one type of ID
```

Thank you,

**Comment by JamesLi197412** [comment]
Thanks for your previous responses. Here is my sample code
![image](https://github.com/user-attachments/assets/2a5d7fb6-bbdf-4b49-bef3-0e53c330158b)
The responses is still 400!.  {'code': 11001, 'message': '잘못된 파라미터 형식입니다.'}

**Comment by searchad-api-customer-service** [comment]
Hello. @JamesLi197412

Try changing the type of parameter ('fields') used to call the API. (type `list` -> `str`)

This is an example of using the list type and the str type.
An error will occur when using the list type.

```python
...
fields = '["impCnt", "clkCnt", "salesAmt", "crto"]' # valid (str type)
# fields = ["impCnt", "clkCnt", "salesAmt", "crto"] # invalid
...
```

<img src="https://github.com/user-attachments/assets/46c0164f-1205-40b8-a19c-76bfe97ad8bd" width='300' />

---

```python
...
# fields = '["impCnt", "clkCnt", "salesAmt", "crto"]' # valid
fields = ["impCnt", "clkCnt", "salesAmt", "crto"] # invalid (list type)
...
```

<img src="https://github.com/user-attachments/assets/5c8c93f8-8f52-4566-bdf2-ec1a8e37c89b" width='500' />



Thank you and best regards.

**Comment by JamesLi197412** [comment]
Thank you for your responses. Two more question about the parameters. 

Firstly, if I wish to extract information over 1 year or even more, e.g. set time ranging from 2023-09-01 to 2024-10-01, the responses will be 400 and information will be 잘못된 파라미터 형식입니다. But it will work from 2024-09-01 to 2024-10-01.
![image](https://github.com/user-attachments/assets/e350a214-9f85-4702-932a-3db96b055cad)

Secondly, speaking of fields parameter, if I input all the Valid items shown from [Link](https://naver.github.io/searchad-apidoc/#/operations/GET/~2Fstats%7B%3Fids,fields,timeRange,datePreset,timeIncrement,breakdown%7D) like '["impCnt", "clkCnt", "salesAmt", "ctr", "cpc", "avgRnk", "ccnt", "recentAvgRnk", "recentAvgCpc", "pcNxAvgRnk", "mblNxAvgRnk", "crto", "convAmt", "ror", "cpConv", "viewCnt"]' for test and keep timeRange from 2024-09-01 to 2024-10-01, then response will be 500 and messages are 선택하신 조건에 지표가 확인되지 않습니다. 보고서 항목이나 기간을 조정하세요. But the filed_test will work. 

![image](https://github.com/user-attachments/assets/1928a5a1-e667-47f0-87e2-c5c19db95a6a)


Thank you for your patience and responses.

Kind regards,
James

**Comment by searchad-api-customer-service** [comment]
Hello. Here is the answer to your inquiry.

## case 1

[1] The range of the `timeRange` parameter should be at most 3 months (92 days).
**`2023-09-01` ~ `2024-10-01`**: The valid range is exceeded, so an error occurred and this range should be modified.
- Since the maximum range(92 days) of the 'time window' is set, you need to move the time window when querying data for a period outside this range.

## case 2

Two fields(`recentAvgRnk` and `recentAvgCpc`) cannot be provided with `nccAdgroupId`.

<br/><br/>
Thank you and best regards.

---

[1] https://oss.navercorp.com/sa-platform/why/wiki/FAQ-stat#q-timerange-%EA%B8%B0%EC%A4%80-%EB%B2%94%EC%9C%84

**Comment by JamesLi197412** [comment]
Hello, Thanks for the response.

One more last question regarding the stat, if ids are a list of nccAdgroupId, then responses will be aggregated values for this entire list of AdgroupId. If I am seeking for every AdgroupID performance, then I basically go through each one and concat them into a larger dataframe, am I right?

Kind regards,
James

**Comment by searchad-api-customer-service** [comment]
Hello.

Please use 'campaign' which is the parent of 'groupId'.
You will be able to find the information you want.

Thank you and best regards.
