### ISSUE TITLE
네이버 검색광고 '반응형 소재' 의 성과데이터를 api로 불러올 수 있는지 문의드립니다.

### ISSUE THREAD

**Issue by dpgpa** [naver/searchad-apidoc#999]
현재 반응형소재의 성과를 확인하려면 
개별 그룹마다 "그룹>소재>에셋" 에 들어가서 하나씩 데이터를 확인해야 하는데요.

그룹ID / 그룹명 / 소재구분 (제목, 설명) / 제목, 설명 텍스트 / 노출수

형태로 API 호출하여 받아볼 수 있는지 문의드립니다.

**Comment by naver-searchad** [comment]
안녕하세요 검색광고 API 입니다.

현재 API로는 AD 단위까지의 지표만 제공하고 있고
말씀주신 반응형소재의 ASSET 단위까지의 성과는 제공하지 않고 있습니다.
업무에 참고 부탁드리겠습니다

감사합니다
